Tudat: tudat::observation_partials::RotationMatrixPartial Class Reference
tudat::observation_partials::RotationMatrixPartial Class Reference abstract
Base class for partial derivatives of rotation matrix from body fixed to inertial frame w.r.t. a parameter.
#include <rotationMatrixPartial.h>
Public Member Functions
RotationMatrixPartial (const boost::shared_ptr< ephemerides::RotationalEphemeris > rotationModel)
virtual ~RotationMatrixPartial ()
Virtual destructor.
Eigen::Matrix< double, 3, Eigen::Dynamic > calculatePartialOfInertialPositionWrtParameter (const double time, const Eigen::Vector3d vectorInLocalFrame)
Function to calculate the partial of the position of a vector, which is given in a body-fixed frame, in the inertial frame wrt a parameter denoting a property of the rotation between a body-fixed and an inertial frame.
Eigen::Matrix< double, 3, Eigen::Dynamic > calculatePartialOfInertialVelocityWrtParameter (const double time, const Eigen::Vector3d vectorInLocalFrame)
Function to calculate the partial of the velocity of a vector, which is given in a body-fixed frame, in the inertial frame wrt a parameter denoting a property of the rotation between a body-fixed and an inertial frame.
virtual std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter (const double time)=0
Function to calculate partials of rotation matrix derivative wrt a parameter (for double or VectorXd parameters).
virtual std::vector< Eigen::Matrix3d > calculatePartialOfRotationMatrixToBaseFrameWrParameter (const double time)=0
Function to calculate partials of rotation matrix wrt a parameter (for either double or VectorXd parameters).
virtual std::string getSecondaryIdentifier ()
Function to return the secondary identifier of the estimated parameter.
Protected Attributes
boost::shared_ptr< ephemerides::RotationalEphemeris > rotationModel_
Detailed Description
Base class for partial derivatives of rotation matrix from body fixed to inertial frame w.r.t. a parameter. A derived class is implemented for each estimatable parameter which represents a property of a rotation matrix from a body-fixed frame (as defined by the isParameterRotationMatrixProperty function). Pointers to this class are used for both PositionPartials and the SphericalHarmonicsGravityPartial partial. In this manner, only a single partial object needs to be implemented for both the state and partial and the sh acceleration partial wrt a rotational parameter when such a parameter is added.
Definition at line 96 of file rotationMatrixPartial.h.
Constructor & Destructor Documentation
tudat::observation_partials::RotationMatrixPartial::RotationMatrixPartial (const boost::shared_ptr< ephemerides::RotationalEphemeris > rotationModel) inline
Definition at line 100 of file rotationMatrixPartial.h.
virtual tudat::observation_partials::RotationMatrixPartial::~RotationMatrixPartial () inline virtual
Definition at line 104 of file rotationMatrixPartial.h.
References calculatePartialOfInertialPositionWrtParameter(), calculatePartialOfInertialVelocityWrtParameter(), calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter(), and calculatePartialOfRotationMatrixToBaseFrameWrParameter().
Member Function Documentation
virtual std::vector< Eigen::Matrix3d > tudat::observation_partials::RotationMatrixPartial::calculatePartialOfRotationMatrixToBaseFrameWrParameter (const double time) pure virtual
Function to calculate partials of rotation matrix from the body-fixed to the inertial base frame wrt a parameter. For a double parameter, the size of the return vector is 1, for a VectorXd parameter, the size is equal to the size of the parameter and the entries of the vector returned from here correspond to partials of the same index in the parameter.
Parameters
time Time at which the partial(s) is(are) to be evaluated.
Returns
Vector of partials of rotation matrix from body-fixed to inertial frame wrt parameter(s)
Implemented in tudat::observation_partials::RotationMatrixPartialWrtPoleOrientation, and tudat::observation_partials::RotationMatrixPartialWrtConstantRotationRate.
Referenced by calculatePartialOfInertialPositionWrtParameter(), calculatePartialOfInertialVelocityWrtParameter(), and ~RotationMatrixPartial().
virtual std::vector< Eigen::Matrix3d > tudat::observation_partials::RotationMatrixPartial::calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter (const double time) pure virtual
Function to calculate partials of rotation matrix derivative from the body-fixed to the inertial base frame. For a double parameter, the size of the return vector is 1, for a VectorXd parameter, the size is equal to the size of the parameter and the entries of the vector returned from here correspond to partials of the same index in the parameter.
Parameters
time Time at which the partial(s) is(are) to be evaluated.
Returns
Vector of partials of rotation matrix from body-fixed to inertial frame wrt parameter(s)
Implemented in tudat::observation_partials::RotationMatrixPartialWrtPoleOrientation, and tudat::observation_partials::RotationMatrixPartialWrtConstantRotationRate.
Referenced by calculatePartialOfInertialVelocityWrtParameter(), and ~RotationMatrixPartial().
Eigen::Matrix< double, 3, Eigen::Dynamic > tudat::observation_partials::RotationMatrixPartial::calculatePartialOfInertialPositionWrtParameter (const double time, const Eigen::Vector3d vectorInLocalFrame)
Function to calculate the partial of the position of a vector, which is given in a body-fixed frame, in the inertial frame wrt a parameter.
The type of parameter is defined by the derived class and a a separate derived class is impleneted for each parameter. An example is the change in position of a ground station, as expressed in the inertial frame, wrt a rotational parameter. Each column of the return Matrix denotes a single entry of the parameter (so it is a Vector3d for a double parameter).
Parameters
time Time at which the partial is to be evaluated.
vectorInLocalFrame Vector, expressed in the body-fixed frame, of which the partial in an inertial frame wrt parameter is to be determined.
Returns
Partial of the value of the vector in an inertial frame wrt the parameter(s).
Function to calculate the partial of the position of a vector, which is given in a body-fixed frame, in the inertial frame wrt a parameter.
Definition at line 103 of file rotationMatrixPartial.cpp.
References calculatePartialOfRotationMatrixToBaseFrameWrParameter().
Referenced by ~RotationMatrixPartial().
Eigen::Matrix< double, 3, Eigen::Dynamic > tudat::observation_partials::RotationMatrixPartial::calculatePartialOfInertialVelocityWrtParameter (const double time, const Eigen::Vector3d vectorInLocalFrame)
Function to calculate the partial of the velocity of a vector, which is given in a body-fixed frame, in the inertial frame wrt a parameter.
The type of parameter is defined by the derived class and a a separate derived class is impleneted for each parameter. An example is the change in velocity of a ground station, as expressed in the inertial frame, wrt a rotational parameter. Each column of the return Matrix denotes a single entry of the parameter (so it is a Vector3d for a double parameter). NOTE: This function currently only works for points that are static in a local frame (e.g. 0 velocity in this local frame).
Parameters
time Time at which the partial is to be evaluated.
vectorInLocalFrame Vector, expressed in the body-fixed frame, of which the partial in an inertial frame wrt parameter is to be determined.
Returns
Partial of the value of the vector in an inertial frame wrt the parameter(s).
Function to calculate the partial of the velocity of a vector, which is given in a body-fixed frame, in the inertial frame wrt a parameter.
Definition at line 120 of file rotationMatrixPartial.cpp.
References calculatePartialOfRotationMatrixDerivativeToBaseFrameWrParameter(), calculatePartialOfRotationMatrixToBaseFrameWrParameter(), and rotationModel_.
Referenced by ~RotationMatrixPartial().
virtual std::string tudat::observation_partials::RotationMatrixPartial::getSecondaryIdentifier () inline virtual
Function to return the secondary identifier of the estimated parameter. This function returns an empty string by default, and can be overridden in the derived class if the associated parameter has a secondary identifier.
Returns
Secondary identifier of the estimated parameter
Definition at line 174 of file rotationMatrixPartial.h.
Member Data Documentation
boost::shared_ptr< ephemerides::RotationalEphemeris > tudat::observation_partials::RotationMatrixPartial::rotationModel_ protected
Definition at line 179 of file rotationMatrixPartial.h.
Referenced by calculatePartialOfInertialVelocityWrtParameter().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/ObservationPartials/rotationMatrixPartial.h
Astrodynamics/OrbitDetermination/ObservationPartials/rotationMatrixPartial.cpp