Tudat: tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType > Class Template Reference
tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType > Class Template Reference
Class for computing the state derivative for rotational dynamics of N bodies.
#include <rotationalMotionStateDerivative.h>
Public Member Functions
RotationalMotionStateDerivative (const basic_astrodynamics::TorqueModelMap &torqueModelsPerBody, const std::vector< std::string > &bodiesToPropagate, std::vector< boost::function< Eigen::Matrix3d() > > bodyInertiaTensorFunctions, std::vector< boost::function< Eigen::Matrix3d() > > bodyInertiaTensorTimeDerivativeFunctions=std::vector< boost::function< Eigen::Matrix3d() > >())
Constructor.
~RotationalMotionStateDerivative ()
Destructor.
void calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative)
Calculates the state derivative of the rotational motion of the system.
void clearStateDerivativeModel ()
Function to clear reference/cached values of rotational state derivative model.
void convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentRotationalState)
Function to convert the propagator-specific form of the state to the conventional form in the global frame.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &outputSolution, const TimeType &time)
Function to convert the state in the conventional form to the propagator-specific form.
void convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentLocalSoluton)
Function to convert the propagator-specific form of the state to the conventional form.
std::vector< std::string > getBodiesToBeIntegratedNumerically ()
Function to get list of names of bodies that are to be integrated numerically.
int getStateSize ()
Function to return the size of the state handled by the object.
basic_astrodynamics::TorqueModelMap getTorquesMap ()
Eigen::Vector3d getTotalTorqueForBody (const std::string &bodyName)
void updateStateDerivativeModel (const TimeType currentTime)
Function to update the state derivative model to the current time.
Public Member Functions inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
SingleStateTypeDerivative (const IntegratedStateType integratedStateType)
Constructor.
virtual ~SingleStateTypeDerivative ()
Virtual destructor.
IntegratedStateType getIntegratedStateType ()
Function to return the type of dynamics for which the state derivative is calculated.
Protected Member Functions
std::vector< Eigen::Vector3d > sumTorquesPerBody ()
Function to get the total torques acting on each body, expressed in the body-fixed frames.
Protected Attributes
std::vector< std::string > bodiesToPropagate_
List of names of bodies for which rotational state is to be propagated.
std::vector< boost::function< Eigen::Matrix3d() > > bodyInertiaTensorFunctions_
List of functions returning inertia tensors of bodiesToPropagate (in same order)
std::vector< boost::function< Eigen::Matrix3d() > > bodyInertiaTensorTimeDerivativeFunctions_
List of functions returning time derivatives of inertia tensors of bodiesToPropagate (in same order)
basic_astrodynamics::SingleBodyTorqueModelMap::iterator innerTorqueIterator
Predefined iterator to save (de-)allocation time.
basic_astrodynamics::TorqueModelMap::iterator torqueModelMapIterator
Predefined iterator to save (de-)allocation time.
basic_astrodynamics::TorqueModelMap torqueModelsPerBody_
A map containing the list of torques acting on each body,.
Protected Attributes inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
IntegratedStateType integratedStateType_
Type of dynamics for whichh the state derivative is calculated.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >
Class for computing the state derivative for rotational dynamics of N bodies., using quaternion from body-fixed to inertial frame (in quaternion format) and angular velocity-vector of body expressed in body-fixed frame as the rotational state of a single body
Definition at line 77 of file rotationalMotionStateDerivative.h.
Constructor & Destructor Documentation
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::RotationalMotionStateDerivative (const basic_astrodynamics::TorqueModelMap & torqueModelsPerBody, const std::vector< std::string > & bodiesToPropagate, std::vector< boost::function< Eigen::Matrix3d() > > bodyInertiaTensorFunctions, std::vector< boost::function< Eigen::Matrix3d() > > bodyInertiaTensorTimeDerivativeFunctions = std::vector< boost::function< Eigen::Matrix3d() > >()) inline
Constructor
Parameters
torqueModelsPerBody List of torque models (first map key body undergoing acceleration, second map key body exerting acceleration)
bodiesToPropagate List of names of bodies for which rotational state is to be propagated
bodyInertiaTensorFunctions List of functions returning inertia tensors of bodiesToPropagate (in same order)
bodyInertiaTensorTimeDerivativeFunctions List of functions returning time derivatives of inertia tensors of bodiesToPropagate (in same order). Default empty, denoting time-invariant inertia tensors.
Definition at line 93 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodyInertiaTensorFunctions_, and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodyInertiaTensorTimeDerivativeFunctions_.
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::~RotationalMotionStateDerivative () inline
Definition at line 128 of file rotationalMotionStateDerivative.h.
Member Function Documentation
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::updateStateDerivativeModel (const TimeType currentTime) inline virtual
Function to update the state derivative model (i.e. torque models) to the current time. Note that this function only updates the state derivative model itself, the environment models must be updated before calling this function.
Parameters
currentTime Time at which state derivative is to be calculated
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 137 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::innerTorqueIterator, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelMapIterator, and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelsPerBody_.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentRotationalState) inline virtual
Function to convert the propagator-specific form of the state to the conventional form in the global frame. The conventional form for translational dynamics this is the quaternion from body-fixed to propagation frame (in vector form) and the body's angular velocity vector in body-fixed frame. For this class the 'conventional' and 'propagator-specific' forms are equal.
Parameters
internalSolution State in propagator-specific form (i.e. form that is used in numerical integration).
time Current time at which the state is valid.
currentRotationalState State (internalSolution), converted to the rotational state in 'conventional' format (equal in this case).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 166 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::clearStateDerivativeModel () inline virtual
Function to clear reference/cached values of rotational state derivative model. For each derived class, this entails resetting the current time in the acceleration models to NaN.
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 183 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::innerTorqueIterator, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelMapIterator, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelsPerBody_, and TUDAT_NAN.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative) inline virtual
Calculates the state derivative of the rotational motion of the system at the given time and rotational state.
Parameters
time Time (seconds since reference epoch) at which the system is to be updated.
stateOfSystemToBeIntegrated List of 7 * bodiesToPropagate_.size(), containing rotation quaternion/angular velocity of the bodies being propagated. The order of the values is defined by the order of bodies in bodiesToPropagate_
stateDerivative Current state derivative (quaternion rate+angular acceleration) of system of bodies integrated numerically (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 209 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodyInertiaTensorFunctions_, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodyInertiaTensorTimeDerivativeFunctions_, tudat::propagators::calculateQuaternionDerivative(), tudat::propagators::evaluateRotationalEquationsOfMotion(), and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::sumTorquesPerBody().
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & outputSolution, const TimeType & time) inline virtual
Function to convert the state in the conventional form to the propagator-specific form. For this propagator, the two are equivalent, and this function returns the input state.
Parameters
outputSolution State in 'conventional form'
time Current time at which the state is valid (not used in this class).
Returns
State (outputSolution), converted to the 'propagator-specific form' (which is equal to outputSolution).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 241 of file rotationalMotionStateDerivative.h.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentLocalSoluton) inline virtual
Function to convert the propagator-specific form of the state to the conventional form. For the this propagator, the two are equivalent, and this function returns the input state.
Parameters
internalSolution State in propagator-specific form (which is equal to outputSolution to conventional form for this propagator)
time Current time at which the state is valid (not used in this class).
currentLocalSoluton State (internalSolution), converted to the 'conventional form', which is equal to outputSolution for this class (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 257 of file rotationalMotionStateDerivative.h.
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::string > tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getBodiesToBeIntegratedNumerically () inline
Function to get list of names of bodies that are to be integrated numerically.
Returns
List of names of bodies that are to be integrated numerically.
Definition at line 268 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_.
Referenced by tudat::propagators::getRotationalStateDerivativeModelForBody().
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getStateSize () inline virtual
Function to return the size of the state handled by the object
Returns
Size of the state under consideration (7 times the number if integrated bodies).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 278 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_.
template<typename StateScalarType = double, typename TimeType = double> Eigen::Vector3d tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getTotalTorqueForBody (const std::string & bodyName) inline
Definition at line 283 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::innerTorqueIterator, and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelsPerBody_.
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::TorqueModelMap tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getTorquesMap () inline
Definition at line 319 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelsPerBody_.
template<typename StateScalarType = double, typename TimeType = double> std::vector< Eigen::Vector3d > tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::sumTorquesPerBody () inline protected
Function to get the total torques acting on each body, expressed in the body-fixed frames. The environment and torque models must have been updated to the current state before calling this function.
Returns
Total torques acting on each body, expressed in the body-fixed frames (in order of bodiesToPropagate_).
Definition at line 333 of file rotationalMotionStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::innerTorqueIterator, and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelsPerBody_.
Referenced by tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative().
Member Data Documentation
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::TorqueModelMap tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelsPerBody_ protected
A map containing the list of torques acting on each body, identifying the body being acted on and the body acted on by an acceleration. The map has as key a string denoting the name of the body the list of torques, provided as the value corresponding to a key, is acting on. This map-value is again a map with string as key, denoting the body exerting the acceleration, and as value a pointer to an acceleration model.
Definition at line 370 of file rotationalMotionStateDerivative.h.
Referenced by tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::clearStateDerivativeModel(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getTorquesMap(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getTotalTorqueForBody(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::sumTorquesPerBody(), and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::updateStateDerivativeModel().
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::string > tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_ protected
Definition at line 373 of file rotationalMotionStateDerivative.h.
Referenced by tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::convertCurrentStateToGlobalRepresentation(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getBodiesToBeIntegratedNumerically(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getStateSize(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getTotalTorqueForBody(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::RotationalMotionStateDerivative(), and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::sumTorquesPerBody().
template<typename StateScalarType = double, typename TimeType = double> std::vector< boost::function< Eigen::Matrix3d() > > tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodyInertiaTensorFunctions_ protected
Definition at line 376 of file rotationalMotionStateDerivative.h.
Referenced by tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::RotationalMotionStateDerivative().
template<typename StateScalarType = double, typename TimeType = double> std::vector< boost::function< Eigen::Matrix3d() > > tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodyInertiaTensorTimeDerivativeFunctions_ protected
Definition at line 379 of file rotationalMotionStateDerivative.h.
Referenced by tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::RotationalMotionStateDerivative().
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::TorqueModelMap::iterator tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::torqueModelMapIterator protected
Definition at line 383 of file rotationalMotionStateDerivative.h.
Referenced by tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::clearStateDerivativeModel(), and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::updateStateDerivativeModel().
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::SingleBodyTorqueModelMap::iterator tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::innerTorqueIterator protected
Definition at line 386 of file rotationalMotionStateDerivative.h.
Referenced by tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::clearStateDerivativeModel(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::getTotalTorqueForBody(), tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::sumTorquesPerBody(), and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::updateStateDerivativeModel().
The documentation for this class was generated from the following file:
Astrodynamics/Propagators/rotationalMotionStateDerivative.h