Tudat: tudat::observation_models::FirstOrderLightTimeCorrectionCalculator Class Reference
tudat::observation_models::FirstOrderLightTimeCorrectionCalculator Class Reference
Class to calculate first order relativistic light time correction (Shapiro time delay) due to a set of point masses.
#include <firstOrderRelativisticLightTimeCorrection.h>
Public Member Functions
FirstOrderLightTimeCorrectionCalculator (const std::vector< boost::function< Eigen::Vector6d(const double) > > &perturbingBodyStateFunctions, const std::vector< boost::function< double() > > &perturbingBodyGravitationalParameterFunctions, const std::vector< std::string > perturbingBodyNames, const std::string transmittingBody, const std::string receivingBody, const boost::function< double() > &ppnParameterGammaFunction=boost::lambda::constant(1.0))
Constructor, takes and sets gravitating body properties.
~FirstOrderLightTimeCorrectionCalculator ()
Destructor.
double calculateLightTimeCorrection (const Eigen::Vector6d &transmitterState, const Eigen::Vector6d &receiverState, const double transmissionTime, const double receptionTime)
Function to calculate first-order relativistic light time correction due to set of gravitating point masses.
Eigen::Matrix< double, 3, 1 > calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition (const Eigen::Vector6d &transmitterState, const Eigen::Vector6d &receiverState, const double transmissionTime, const double receptionTime, const LinkEndType linkEndAtWhichPartialIsEvaluated)
Function to compute the partial derivative of the light-time correction w.r.t. link end position.
double calculateLightTimeCorrectionPartialDerivativeWrtLinkEndTime (const Eigen::Vector6d &transmitterState, const Eigen::Vector6d &receiverState, const double transmissionTime, const double receptionTime, const LinkEndType fixedLinkEnd, const LinkEndType linkEndAtWhichPartialIsEvaluated)
Function to compute the partial derivative of the light-time correction w.r.t. observation time.
double getCurrentLightTimeCorrectionComponent (const int bodyIndex)
Function to get the light-time correction of given perturbing body, as computed by last call to calculateLightTimeCorrection.
double getCurrentTotalLightTimeCorrection ()
Function to get the total light-time correction, as computed by last call to calculateLightTimeCorrection.
std::vector< boost::function< double() > > getPerturbingBodyGravitationalParameterFunctions ()
Function to get the set of functions returning the gravitational parameters of the gravitating bodies.
std::vector< std::string > getPerturbingBodyNames ()
Function to get the names of bodies causing light-time correction.
boost::function< double() > getPpnParameterGammaFunction_ ()
Function to get the function returning the parametric post-Newtonian parameter gamma.
Public Member Functions inherited from tudat::observation_models::LightTimeCorrection
LightTimeCorrection (const LightTimeCorrectionType lightTimeCorrectionType)
Constructor.
virtual ~LightTimeCorrection ()
Destructor.
virtual double calculateLightTimeCorrectionDerivativeWrtLinkEndTime (const Eigen::Vector6d &transmitterState, const Eigen::Vector6d &receiverState, const double transmissionTime, const double receptionTime, const LinkEndType fixedLinkEnd, const LinkEndType linkEndAtWhichPartialIsEvaluated)
Function to compute the full derivative of the light-time correction w.r.t. observation time.
LightTimeCorrectionType getLightTimeCorrectionType ()
Function to retrieve the type of light-time correction represented by instance of class.
Private Attributes
std::vector< double > currentLighTimeCorrectionComponents_
double currentTotalLightTimeCorrection_
Total light-time correction, as computed by last call to calculateLightTimeCorrection.
std::vector< double > lightTimeEvaluationContribution_
List of values (between 0 and 1) of how far into the light-time the state of each perturbing body is to be evaluated.
std::vector< boost::function< double() > > perturbingBodyGravitationalParameterFunctions_
Set of functions returning the gravitational parameters of the gravitating bodies.
std::vector< std::string > perturbingBodyNames_
Names of bodies causing light-time correction.
std::vector< boost::function< Eigen::Vector6d(const double) > > perturbingBodyStateFunctions_
Set of function returning the state of the gravitating bodies as a function of time.
boost::function< double() > ppnParameterGammaFunction_
Function returning the parametric post-Newtonian parameter gamma.
Additional Inherited Members
Protected Attributes inherited from tudat::observation_models::LightTimeCorrection
LightTimeCorrectionType lightTimeCorrectionType_
Type of light-time correction represented by instance of class.
Detailed Description
Class to calculate first order relativistic light time correction (Shapiro time delay) due to a set of point masses. This class has the properties (mass and position) of the gravitating bodies as member variables. It receives the states and times of receiver and transmitter as input each time a light time is to be calculated. NOTE: If the perturbing body is equal to the transmitting or receiving body, the transmission or reception time, respectively, are used to evaluate this perturbing body's state when computing the correction. For all other bodies, the mid-way point of the light time is used.
Definition at line 41 of file firstOrderRelativisticLightTimeCorrection.h.
Constructor & Destructor Documentation
tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::FirstOrderLightTimeCorrectionCalculator (const std::vector< boost::function< Eigen::Vector6d(const double) > > & perturbingBodyStateFunctions, const std::vector< boost::function< double() > > & perturbingBodyGravitationalParameterFunctions, const std::vector< std::string > perturbingBodyNames, const std::string transmittingBody, const std::string receivingBody, const boost::function< double() > & ppnParameterGammaFunction = boost::lambda::constant(1.0)) inline
Constructor, takes and sets gravitating body properties.
Parameters
perturbingBodyStateFunctions Set of function returning the state of the gravitating bodies as a function of time.
perturbingBodyGravitationalParameterFunctions Set of functions returning the gravitational parameters of the gravitating bodies.
perturbingBodyNames Names of bodies causing light-time correction.
transmittingBody Name of transmitting body
receivingBody Name of receiving body
ppnParameterGammaFunction Function returning the parametric post-Newtonian parameter gamma, a measure for the space-time curvature due to a unit rest mass (default 1.0; value from GR)
Definition at line 58 of file firstOrderRelativisticLightTimeCorrection.h.
References currentLighTimeCorrectionComponents_, currentTotalLightTimeCorrection_, lightTimeEvaluationContribution_, and perturbingBodyNames_.
tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::~FirstOrderLightTimeCorrectionCalculator () inline
Definition at line 93 of file firstOrderRelativisticLightTimeCorrection.h.
References calculateLightTimeCorrection().
Member Function Documentation
double tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::calculateLightTimeCorrection (const Eigen::Vector6d & transmitterState, const Eigen::Vector6d & receiverState, const double transmissionTime, const double receptionTime) virtual
Function to calculate first order relativistic light time correction due to set of gravitating point masses.
Function to calculate first order relativistic light time correction due to set of gravitating point masses, according to Eq. (11.17) of 2010 IERS conventions. Calculation are performed by calling ca calculateFirstOrderLightTimeCorrectionFromCentralBody function for each gravitating body.
Parameters
transmitterState State of transmitter at transmission time.
receiverState State of receiver at reception time
transmissionTime Time of signal transmission
receptionTime Time of signal reception
Returns
Total light time correction due to gravitating masses defined by perturbingBodyStateFunctions_ and perturbingBodyGravitationalParameterFunctions_ member variables.
Implements tudat::observation_models::LightTimeCorrection.
Definition at line 24 of file firstOrderRelativisticLightTimeCorrection.cpp.
References tudat::relativity::calculateFirstOrderLightTimeCorrectionFromCentralBody(), calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition(), currentLighTimeCorrectionComponents_, currentTotalLightTimeCorrection_, lightTimeEvaluationContribution_, perturbingBodyGravitationalParameterFunctions_, perturbingBodyStateFunctions_, ppnParameterGammaFunction_, and TUDAT_NAN.
Referenced by ~FirstOrderLightTimeCorrectionCalculator().
double tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::calculateLightTimeCorrectionPartialDerivativeWrtLinkEndTime (const Eigen::Vector6d & transmitterState, const Eigen::Vector6d & receiverState, const double transmissionTime, const double receptionTime, const LinkEndType fixedLinkEnd, const LinkEndType linkEndAtWhichPartialIsEvaluated) inline virtual
Function to compute the partial derivative of the light-time correction w.r.t. observation time, equal to zero in this model.
Parameters
transmitterState State of transmitted at transmission time
receiverState State of receiver at reception time
transmissionTime Time of signal transmission
receptionTime Time of singal reception
fixedLinkEnd Reference link end for observation
linkEndAtWhichPartialIsEvaluated Link end at which the time partial is to be taken
Returns
Light-time correction w.r.t. observation time
Implements tudat::observation_models::LightTimeCorrection.
Definition at line 124 of file firstOrderRelativisticLightTimeCorrection.h.
References calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition().
Eigen::Matrix< double, 3, 1 > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition (const Eigen::Vector6d & transmitterState, const Eigen::Vector6d & receiverState, const double transmissionTime, const double receptionTime, const LinkEndType linkEndAtWhichPartialIsEvaluated) virtual
Function to compute the partial derivative of the light-time correction w.r.t. link end position
Parameters
transmitterState State of transmitted at transmission time
receiverState State of receiver at reception time
transmissionTime Time of signal transmission
receptionTime Time of singal reception
linkEndAtWhichPartialIsEvaluated Link end at which the position partial is to be taken
Returns
Light-time correction w.r.t. link end position
Implements tudat::observation_models::LightTimeCorrection.
Definition at line 55 of file firstOrderRelativisticLightTimeCorrection.cpp.
References tudat::relativity::calculateFirstOrderCentralBodyLightTimeCorrectionGradient(), lightTimeEvaluationContribution_, perturbingBodyGravitationalParameterFunctions_, perturbingBodyStateFunctions_, ppnParameterGammaFunction_, tudat::observation_models::receiver, and TUDAT_NAN.
Referenced by calculateLightTimeCorrection(), and calculateLightTimeCorrectionPartialDerivativeWrtLinkEndTime().
std::vector< std::string > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::getPerturbingBodyNames () inline
Function to get the names of bodies causing light-time correction.
Returns
Names of bodies causing light-time correction.
Definition at line 157 of file firstOrderRelativisticLightTimeCorrection.h.
References perturbingBodyNames_.
std::vector< boost::function< double() > > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::getPerturbingBodyGravitationalParameterFunctions () inline
Function to get the set of functions returning the gravitational parameters of the gravitating bodies.
Returns
Set of functions returning the gravitational parameters of the gravitating bodies.
Definition at line 167 of file firstOrderRelativisticLightTimeCorrection.h.
References perturbingBodyGravitationalParameterFunctions_.
double tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::getCurrentTotalLightTimeCorrection () inline
Function to get the total light-time correction, as computed by last call to calculateLightTimeCorrection.
Returns
Total light-time correction, as computed by last call to calculateLightTimeCorrection.
Definition at line 177 of file firstOrderRelativisticLightTimeCorrection.h.
References currentTotalLightTimeCorrection_.
double tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::getCurrentLightTimeCorrectionComponent (const int bodyIndex) inline
Function to get the light-time correction of given perturbing body, as computed by last call to calculateLightTimeCorrection.
Parameters
bodyIndex Index in list of bodies for which the correction is to be returbed
Returns
Light-time correction of given perturbing body, as computed by last call to calculateLightTimeCorrection.
Definition at line 191 of file firstOrderRelativisticLightTimeCorrection.h.
References currentLighTimeCorrectionComponents_.
boost::function< double() > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::getPpnParameterGammaFunction_ () inline
Function to get the function returning the parametric post-Newtonian parameter gamma
Returns
Function returning the parametric post-Newtonian parameter gamma
Definition at line 201 of file firstOrderRelativisticLightTimeCorrection.h.
References ppnParameterGammaFunction_.
Member Data Documentation
std::vector< boost::function< Eigen::Vector6d(const double) > > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::perturbingBodyStateFunctions_ private
Definition at line 209 of file firstOrderRelativisticLightTimeCorrection.h.
Referenced by calculateLightTimeCorrection(), and calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition().
std::vector< boost::function< double() > > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::perturbingBodyGravitationalParameterFunctions_ private
Definition at line 212 of file firstOrderRelativisticLightTimeCorrection.h.
Referenced by calculateLightTimeCorrection(), calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition(), and getPerturbingBodyGravitationalParameterFunctions().
std::vector< std::string > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::perturbingBodyNames_ private
Definition at line 215 of file firstOrderRelativisticLightTimeCorrection.h.
Referenced by FirstOrderLightTimeCorrectionCalculator(), and getPerturbingBodyNames().
boost::function< double() > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::ppnParameterGammaFunction_ private
Function returning the parametric post-Newtonian parameter gamma, a measure for the space-time curvature due to a unit rest mass (1.0 in GR)
Definition at line 222 of file firstOrderRelativisticLightTimeCorrection.h.
Referenced by calculateLightTimeCorrection(), calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition(), and getPpnParameterGammaFunction_().
std::vector< double > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::lightTimeEvaluationContribution_ private
Definition at line 225 of file firstOrderRelativisticLightTimeCorrection.h.
Referenced by calculateLightTimeCorrection(), calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition(), and FirstOrderLightTimeCorrectionCalculator().
std::vector< double > tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::currentLighTimeCorrectionComponents_ private
List of light-time correction due to each separate perturbing body, as computed by last call to calculateLightTimeCorrection.
Definition at line 229 of file firstOrderRelativisticLightTimeCorrection.h.
Referenced by calculateLightTimeCorrection(), FirstOrderLightTimeCorrectionCalculator(), and getCurrentLightTimeCorrectionComponent().
double tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::currentTotalLightTimeCorrection_ private
Definition at line 232 of file firstOrderRelativisticLightTimeCorrection.h.
Referenced by calculateLightTimeCorrection(), FirstOrderLightTimeCorrectionCalculator(), and getCurrentTotalLightTimeCorrection().
The documentation for this class was generated from the following files:
Astrodynamics/ObservationModels/ObservableCorrections/firstOrderRelativisticLightTimeCorrection.h
Astrodynamics/ObservationModels/ObservableCorrections/firstOrderRelativisticLightTimeCorrection.cpp