Tudat: tudat::ephemerides::KeplerEphemeris Class Reference
tudat::ephemerides::KeplerEphemeris Class Reference
Ephemeris derived class that calculates the Cartesian position as a function of time assuming a Kepler orbit.
#include <keplerEphemeris.h>
Public Member Functions
KeplerEphemeris (const Eigen::Vector6d &initialStateInKeplerianElements, const double epochOfInitialState, const double centralBodyGravitationalParameter, const std::string &referenceFrameOrigin="SSB", const std::string &referenceFrameOrientation="ECLIPJ2000", const double rootFinderAbsoluteTolerance=200.0 *std::numeric_limits< double >::epsilon(), const double rootFinderMaximumNumberOfIterations=1000.0)
Class constructor.
Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)
Function to get state from ephemeris.
Public Member Functions inherited from tudat::ephemerides::Ephemeris
Ephemeris (const std::string &referenceFrameOrigin="", const std::string &referenceFrameOrientation="")
Constructor.
virtual ~Ephemeris ()
Default destructor.
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get state from ephemeris (with long double as state scalar).
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with long double as state scalar and Time as time type).
virtual Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with double as state scalar and Time as time type).
std::string getReferenceFrameOrientation ()
Get reference frame orientation.
std::string getReferenceFrameOrigin ()
Get reference frame origin.
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (double specialization).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (long double specialization).
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (double specialization with Time input).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (long double specialization with Time input).
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > getTemplatedStateFromEphemeris (const TimeType &time)
Get state from ephemeris, with state scalar as template type.
Private Attributes
double centralBodyGravitationalParameter_
Gravitational parameter of central body about which the Kepler orbit is defined.
double eccentricity_
Eccentricity of orbit.
double epochOfInitialState_
Initial epoch from which propagation of Kepler orbit is performed.
double initialMeanAnomaly_
Mean anomaly at epochOfInitialState.
Eigen::Vector6d initialStateInKeplerianElements_
Kepler elements at time epochOfInitialState.
bool isOrbitHyperbolic_
Boolean denoting whether orbit is hyperbolic or elliptical (parabola not supported).
boost::shared_ptr< root_finders::RootFinderCore< double > > rootFinder_
Root finder used to convert mean to eccentric anomalies.
Eigen::Quaterniond rotationFromOrbitalPlane_
Rotation from orbital plane to frame in which the orbit is defined.
double semiLatusRectum_
Semi-latus rectum of orbit.
double semiMajorAxis_
Semi-major axis of orbit.
Additional Inherited Members
Protected Attributes inherited from tudat::ephemerides::Ephemeris
std::string referenceFrameOrientation_
Reference frame orientation.
std::string referenceFrameOrigin_
Reference frame origin.
Detailed Description
Ephemeris derived class that calculates the Cartesian position as a function of time assuming a Kepler orbit.
In this class, both the Kepler propagation and conversion to Cartesian coordinates is done internally using precomputed values of the initial Kepler elements, thereby reducing computation time compared to succesively using the propagateKeplerOrbit or convertKeplerianToCartesianElements functions.
Definition at line 36 of file keplerEphemeris.h.
Constructor & Destructor Documentation
tudat::ephemerides::KeplerEphemeris::KeplerEphemeris (const Eigen::Vector6d & initialStateInKeplerianElements, const double epochOfInitialState, const double centralBodyGravitationalParameter, const std::string & referenceFrameOrigin = "SSB", const std::string & referenceFrameOrientation = "ECLIPJ2000", const double rootFinderAbsoluteTolerance = 200.0 * std::numeric_limits< double >::epsilon(), const double rootFinderMaximumNumberOfIterations = 1000.0)
Class constructor, sets the characteristics of the Kepler orbit and the root finder used for converting mean to eccentric anomalies.
Parameters
initialStateInKeplerianElements Kepler elements at time epochOfInitialState.
epochOfInitialState Time at which initialStateInKeplerianElements represents the Keplerian state.
centralBodyGravitationalParameter Gravitational parameter of the central body that is used in the computations.
referenceFrameOrigin Origin of reference frame (string identifier) (default SSB).
referenceFrameOrientation Orientation of reference frame (string identifier) (default ECLIPJ000
rootFinderAbsoluteTolerance Convergence tolerance for root finder used to convert mean to eccentric anomaly on each call to getCartesianState (default 200*epsilon).
rootFinderMaximumNumberOfIterations Maximum iteration for root finder used to convert mean to eccentric anomaly on each call to getCartesianState (default 1000).
Definition at line 24 of file keplerEphemeris.cpp.
References tudat::orbital_element_conversions::argumentOfPeriapsisIndex, tudat::orbital_element_conversions::convertEccentricAnomalyToMeanAnomaly(), tudat::orbital_element_conversions::convertHyperbolicEccentricAnomalyToMeanAnomaly(), tudat::orbital_element_conversions::convertTrueAnomalyToEccentricAnomaly(), tudat::orbital_element_conversions::convertTrueAnomalyToHyperbolicEccentricAnomaly(), eccentricity_, tudat::orbital_element_conversions::eccentricityIndex, tudat::orbital_element_conversions::inclinationIndex, initialMeanAnomaly_, initialStateInKeplerianElements_, isOrbitHyperbolic_, tudat::orbital_element_conversions::longitudeOfAscendingNodeIndex, rootFinder_, rotationFromOrbitalPlane_, semiLatusRectum_, semiMajorAxis_, tudat::orbital_element_conversions::semiMajorAxisIndex, and tudat::orbital_element_conversions::trueAnomalyIndex.
Member Function Documentation
Eigen::Vector6d tudat::ephemerides::KeplerEphemeris::getCartesianState (const double secondsSinceEpoch) virtual
Returns state from ephemeris at given time, assuming a purely Keplerian orbit
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Keplerian orbit Cartesian state at given time.
Implements tudat::ephemerides::Ephemeris.
Definition at line 101 of file keplerEphemeris.cpp.
References centralBodyGravitationalParameter_, tudat::orbital_element_conversions::convertEccentricAnomalyToTrueAnomaly(), tudat::orbital_element_conversions::convertElapsedTimeToEllipticalMeanAnomalyChange(), tudat::orbital_element_conversions::convertElapsedTimeToHyperbolicMeanAnomalyChange(), tudat::orbital_element_conversions::convertMeanAnomalyToEccentricAnomaly(), tudat::orbital_element_conversions::convertMeanAnomalyToHyperbolicEccentricAnomaly(), eccentricity_, epochOfInitialState_, initialMeanAnomaly_, isOrbitHyperbolic_, rotationFromOrbitalPlane_, semiLatusRectum_, semiMajorAxis_, tudat::input_output::field_types::state::trueAnomaly, and TUDAT_NAN.
Member Data Documentation
Eigen::Vector6d tudat::ephemerides::KeplerEphemeris::initialStateInKeplerianElements_ private
Definition at line 82 of file keplerEphemeris.h.
Referenced by KeplerEphemeris().
double tudat::ephemerides::KeplerEphemeris::semiLatusRectum_ private
Definition at line 85 of file keplerEphemeris.h.
Referenced by getCartesianState(), and KeplerEphemeris().
double tudat::ephemerides::KeplerEphemeris::initialMeanAnomaly_ private
Definition at line 88 of file keplerEphemeris.h.
Referenced by getCartesianState(), and KeplerEphemeris().
double tudat::ephemerides::KeplerEphemeris::semiMajorAxis_ private
Definition at line 91 of file keplerEphemeris.h.
Referenced by getCartesianState(), and KeplerEphemeris().
double tudat::ephemerides::KeplerEphemeris::eccentricity_ private
Definition at line 94 of file keplerEphemeris.h.
Referenced by getCartesianState(), and KeplerEphemeris().
Eigen::Quaterniond tudat::ephemerides::KeplerEphemeris::rotationFromOrbitalPlane_ private
Definition at line 97 of file keplerEphemeris.h.
Referenced by getCartesianState(), and KeplerEphemeris().
boost::shared_ptr< root_finders::RootFinderCore< double > > tudat::ephemerides::KeplerEphemeris::rootFinder_ private
Definition at line 100 of file keplerEphemeris.h.
Referenced by KeplerEphemeris().
double tudat::ephemerides::KeplerEphemeris::epochOfInitialState_ private
Definition at line 103 of file keplerEphemeris.h.
Referenced by getCartesianState().
double tudat::ephemerides::KeplerEphemeris::centralBodyGravitationalParameter_ private
Definition at line 106 of file keplerEphemeris.h.
Referenced by getCartesianState().
bool tudat::ephemerides::KeplerEphemeris::isOrbitHyperbolic_ private
Definition at line 109 of file keplerEphemeris.h.
Referenced by getCartesianState(), and KeplerEphemeris().
The documentation for this class was generated from the following files:
Astrodynamics/Ephemerides/keplerEphemeris.h
Astrodynamics/Ephemerides/keplerEphemeris.cpp