Tudat: tudat::simulation_setup::FullThrustInterpolationInterface Class Reference
tudat::simulation_setup::FullThrustInterpolationInterface Class Reference
#include <accelerationSettings.h>
Public Member Functions
FullThrustInterpolationInterface (const std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Vector3d > > thrustInterpolator, const std::function< Eigen::Matrix3d() > rotationFunction=[](){ return Eigen::Matrix3d::Identity();})
Constructor.
Eigen::Vector3d getThrustDirection (const double time)
Function to retrieve the current thrust direction (in the propagation frame).
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Vector3d > > getThrustInterpolator ()
Function to retrieve the thrust interpolator.
double getThrustMagnitude (const double time)
Function to retrieve the current thrust magnitude.
void resetRotationFunction (const std::function< Eigen::Matrix3d() > rotationFunction)
Function to reset the function to rotate to propation frame.
void resetTime (const double currentTime=TUDAT_NAN)
Private Member Functions
void updateThrust (const double time)
Function to update the thrust vector to the current time.
Private Attributes
Eigen::Vector3d currentThrust_
Total thrust vector (in propagation frame) computed by last call to updateThrust function.
double currentTime_
Time at which the last call to updateThrust was made (e.g. time associated with current thrust).
std::function< Eigen::Matrix3d() > rotationFunction_
Function that returns the rotation matrix from the frame B to the frame in which the propagation is performed.
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Vector3d > > thrustInterpolator_
Object that returns the total thrust vector, expressed in some reference frame B.
Detailed Description
Interface class that allows single interpolator to be used for thrust direction and magnitude (which are separated in thrust implementation)
Definition at line 232 of file accelerationSettings.h.
Constructor & Destructor Documentation
FullThrustInterpolationInterface()
tudat::simulation_setup::FullThrustInterpolationInterface::FullThrustInterpolationInterface (const std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Vector3d > > thrustInterpolator, const std::function< Eigen::Matrix3d() > rotationFunction = [ ](){ return Eigen::Matrix3d::Identity(); }) inline
Constructor
Parameters
thrustInterpolator Object that returns the total thrust vector, expressed in some reference frame B
rotationFunction Function that returns the rotation matrix from the frame B to the frame in which the propagation is performed.
Definition at line 243 of file accelerationSettings.h.
Member Function Documentation
getThrustMagnitude()
double tudat::simulation_setup::FullThrustInterpolationInterface::getThrustMagnitude (const double time) inline
Function to retrieve the current thrust magnitude, updates thrust to current time if needed.
Parameters
time Time at which thrust must be evaluated.
Returns
Current thrust magnitude.
Definition at line 257 of file accelerationSettings.h.
References currentThrust_, and updateThrust().
Referenced by tudat::simulation_setup::ThrustAccelerationSettings::ThrustAccelerationSettings().
getThrustDirection()
Eigen::Vector3d tudat::simulation_setup::FullThrustInterpolationInterface::getThrustDirection (const double time) inline
Function to retrieve the current thrust direction (in the propagation frame)., updates thrust to current time if needed.
Parameters
time Time at which thrust must be evaluated.
Returns
Current thrust direction in propagation frame..
Definition at line 271 of file accelerationSettings.h.
References currentThrust_, and updateThrust().
Referenced by tudat::simulation_setup::ThrustAccelerationSettings::ThrustAccelerationSettings().
resetRotationFunction()
void tudat::simulation_setup::FullThrustInterpolationInterface::resetRotationFunction (const std::function< Eigen::Matrix3d() > rotationFunction) inline
Function to reset the function to rotate to propation frame
Parameters
rotationFunction New function that returns the rotation matrix from the frame B to the frame in which the propagation is performed.
Definition at line 283 of file accelerationSettings.h.
References rotationFunction_.
resetTime()
void tudat::simulation_setup::FullThrustInterpolationInterface::resetTime (const double currentTime = TUDAT_NAN) inline
Definition at line 288 of file accelerationSettings.h.
References currentTime_.
Referenced by tudat::simulation_setup::ThrustAccelerationSettings::ThrustAccelerationSettings().
getThrustInterpolator()
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Vector3d > > tudat::simulation_setup::FullThrustInterpolationInterface::getThrustInterpolator () inline
Function to retrieve the thrust interpolator.
Definition at line 297 of file accelerationSettings.h.
References thrustInterpolator_.
updateThrust()
void tudat::simulation_setup::FullThrustInterpolationInterface::updateThrust (const double time) inline private
Function to update the thrust vector to the current time
Parameters
time Time at which thrust must be evaluated.
Definition at line 309 of file accelerationSettings.h.
References currentThrust_, currentTime_, rotationFunction_, and thrustInterpolator_.
Referenced by getThrustDirection(), and getThrustMagnitude().
Member Data Documentation
thrustInterpolator_
std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Vector3d > > tudat::simulation_setup::FullThrustInterpolationInterface::thrustInterpolator_ private
Definition at line 319 of file accelerationSettings.h.
Referenced by getThrustInterpolator(), and updateThrust().
rotationFunction_
std::function< Eigen::Matrix3d() > tudat::simulation_setup::FullThrustInterpolationInterface::rotationFunction_ private
Definition at line 322 of file accelerationSettings.h.
Referenced by resetRotationFunction(), and updateThrust().
currentThrust_
Eigen::Vector3d tudat::simulation_setup::FullThrustInterpolationInterface::currentThrust_ private
Definition at line 325 of file accelerationSettings.h.
Referenced by getThrustDirection(), getThrustMagnitude(), and updateThrust().
currentTime_
double tudat::simulation_setup::FullThrustInterpolationInterface::currentTime_ private
Definition at line 328 of file accelerationSettings.h.
Referenced by resetTime(), and updateThrust().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/accelerationSettings.h