Tudat: tudat::json_interface::UndefinedKeyError Class Reference
tudat::json_interface::UndefinedKeyError Class Reference
Class for errors generated when trying to access a key from a json object that does not exist.
#include <errorHandling.h>
Public Member Functions
UndefinedKeyError (const KeyPath &keyPath)
Constructor.
void handleUseOfDefaultValue (const nlohmann::json &defaultValue, const ExceptionResponseType &response) const
Rethrow this if default values are not allowed, or print a message if requested by user.
template<typename NumberType >
void rethrowIfNaNNotAllowed (bool allowNaN, const NumberType &defaultValue) const
Rethrow this if NaN default values are not allowed and the provided default value is NaN.
Public Member Functions inherited from tudat::json_interface::ValueAccessError
ValueAccessError (const std::string &errorMessage, const KeyPath &keyPath)
Constructor.
void rethrowIfNotTriggeredByMissingValueAt (const KeyPath &keyPath) const
Rethrow this if this was not generated when trying to access keyPath.
bool wasTriggeredByMissingValueAt (const KeyPath &keyPath) const
Whether this was generated when trying to access keyPath.
virtual const char * what () const throw ()
Full error message.
Additional Inherited Members
Public Attributes inherited from tudat::json_interface::ValueAccessError
KeyPath keyPath
Key path trying to access / accessed when the error was generated.
Detailed Description
Class for errors generated when trying to access a key from a json object that does not exist.
Definition at line 114 of file errorHandling.h.
Constructor & Destructor Documentation
UndefinedKeyError()
tudat::json_interface::UndefinedKeyError::UndefinedKeyError (const KeyPath & keyPath) inline
Constructor.
Parameters
keyPath Key path trying to access when the error was generated.
Definition at line 122 of file errorHandling.h.
Member Function Documentation
handleUseOfDefaultValue()
void tudat::json_interface::UndefinedKeyError::handleUseOfDefaultValue (const nlohmann::json & defaultValue, const ExceptionResponseType & response) const inline
Rethrow this if default values are not allowed, or print a message if requested by user.
Parameters
defaultValue json representation of the dafault value to be used.
response The response to usage of dafault values.
Definition at line 130 of file errorHandling.h.
References tudat::json_interface::containsAnyOf(), tudat::json_interface::continueSilently, tudat::json_interface::ValueAccessError::keyPath, tudat::json_interface::SpecialKeys::objectContaining, and tudat::json_interface::throwError.
Referenced by tudat::json_interface::getValue().
rethrowIfNaNNotAllowed()
template<typename NumberType > void tudat::json_interface::UndefinedKeyError::rethrowIfNaNNotAllowed (bool allowNaN, const NumberType & defaultValue) const inline
Rethrow this if NaN default values are not allowed and the provided default value is NaN.
Parameters
allowNaN Whether NaN default values are allowed.
defaultValue The default value to be checked.
Definition at line 155 of file errorHandling.h.
References tudat::json_interface::isNaN().
The documentation for this class was generated from the following file:
JsonInterface/Support/errorHandling.h