Tudat: tudat::observation_partials::CartesianStatePartial Class Reference
tudat::observation_partials::CartesianStatePartial Class Reference abstract
Base class for calculating the partial of an inertial position wrt a parameter.
#include <positionPartials.h>
Public Member Functions
CartesianStatePartial ()
virtual ~CartesianStatePartial ()
Destructor.
virtual Eigen::Matrix< double, 3, Eigen::Dynamic > calculatePartialOfPosition (const Eigen::Vector6d &state, const double time)=0
Pure virtual base class function for determining partial at current time and body state.
virtual Eigen::Matrix< double, 3, Eigen::Dynamic > calculatePartialOfVelocity (const Eigen::Vector6d &state, const double time)=0
Detailed Description
Base class for calculating the partial of an inertial position wrt a parameter. A derived class is implemented for each (type of) estimatable parameter. A separate instance of the class must be made for each distinct state. Note that partials wrt parameters describing a property of a rotation matrix from a local to the inertial frame is implemented in the RotationMatrixPartial class, which is then used by the CartesianStatePartialWrtRotationMatrixParameter derived class of this class
Definition at line 62 of file positionPartials.h.
Constructor & Destructor Documentation
tudat::observation_partials::CartesianStatePartial::CartesianStatePartial () inline
Definition at line 66 of file positionPartials.h.
virtual tudat::observation_partials::CartesianStatePartial::~CartesianStatePartial () inline virtual
Definition at line 69 of file positionPartials.h.
References calculatePartialOfPosition(), and calculatePartialOfVelocity().
Member Function Documentation
virtual Eigen::Matrix< double, 3, Eigen::Dynamic > tudat::observation_partials::CartesianStatePartial::calculatePartialOfPosition (const Eigen::Vector6d & state, const double time) pure virtual
Pure virtual base class function for determining partial at current time and body state wrt parameter of specific implemented derived. class.
Parameters
state Current inertial state of point of which partial is to be calculated by derived class
time Current time
Returns
Partial of point position wrt parameter (with specific parameter determined by derived class implementation).
Implemented in tudat::observation_partials::CartesianPartialWrtBodyFixedPosition, tudat::observation_partials::CartesianStatePartialWrtRotationMatrixParameter, and tudat::observation_partials::CartesianStatePartialWrtCartesianState.
Referenced by ~CartesianStatePartial().
virtual Eigen::Matrix< double, 3, Eigen::Dynamic > tudat::observation_partials::CartesianStatePartial::calculatePartialOfVelocity (const Eigen::Vector6d & state, const double time) pure virtual
Implemented in tudat::observation_partials::CartesianPartialWrtBodyFixedPosition, tudat::observation_partials::CartesianStatePartialWrtRotationMatrixParameter, and tudat::observation_partials::CartesianStatePartialWrtCartesianState.
Referenced by ~CartesianStatePartial().
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/ObservationPartials/positionPartials.h