Tudat: tudat::basic_astrodynamics::TorqueModel Class Reference
tudat::basic_astrodynamics::TorqueModel Class Reference abstract
Pure virtual base class for a model that computes the torque acting on a body.
#include <torqueModel.h>
Public Member Functions
TorqueModel ()
Constructor.
virtual ~TorqueModel ()
Destructor.
virtual Eigen::Vector3d getTorque ()=0
Function to retrieve the current value of the toruqe.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
virtual void updateMembers (const double currentTime)=0
Update member variables used by the torque model.
Protected Attributes
double currentTime_
Last time at which the updateMembers was evaluated (or NaN if next call is to recompute torque).
Detailed Description
Pure virtual base class for a model that computes the torque acting on a body. These models are used in the propagation of the rotational equations of motion. Every specific torque model requires its own derived class.
Definition at line 35 of file torqueModel.h.
Constructor & Destructor Documentation
tudat::basic_astrodynamics::TorqueModel::TorqueModel () inline
Definition at line 40 of file torqueModel.h.
virtual tudat::basic_astrodynamics::TorqueModel::~TorqueModel () inline virtual
Definition at line 44 of file torqueModel.h.
References getTorque(), and updateMembers().
Member Function Documentation
virtual Eigen::Vector3d tudat::basic_astrodynamics::TorqueModel::getTorque () pure virtual
Returns the toruqe. No arguments are passed to this function for generality. Instead, all data required for computation is to be obtained from pointers to functions/ classes/structs, etc which are to be set in a derived class and evaluated by the updateMembers() function below.
Returns
Current torque, as computed by last call to updateMembers function.
Implemented in tudat::aerodynamics::AerodynamicTorque, and tudat::gravitation::SecondDegreeGravitationalTorqueModel.
Referenced by tudat::propagators::getDoubleDependentVariableFunction(), tudat::propagators::getVectorDependentVariableFunction(), and ~TorqueModel().
virtual void tudat::basic_astrodynamics::TorqueModel::updateMembers (const double currentTime) pure virtual
Updates member variables used by the torque model. In the case of torque models containing varying parameters, function-pointers returning such a parameter (for instance the Cartesian state of a body) will be set as a member variable. This function evaluates such function-pointers and updates member variables to the 'current' values of these parameters. Only these current values, not the function-pointers are then used by the getTorque function. This pure virtual function must be overridden by derived classes.
Parameters
currentTime Time at which torque model is to be updated.
Implemented in tudat::aerodynamics::AerodynamicTorque, and tudat::gravitation::SecondDegreeGravitationalTorqueModel.
Referenced by ~TorqueModel().
virtual void tudat::basic_astrodynamics::TorqueModel::resetTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the current time of the torque model.
Parameters
currentTime Current time (default NaN).
Definition at line 74 of file torqueModel.h.
References currentTime_.
Member Data Documentation
double tudat::basic_astrodynamics::TorqueModel::currentTime_ protected
Definition at line 82 of file torqueModel.h.
Referenced by resetTime(), and tudat::aerodynamics::AerodynamicTorque::updateMembers().
The documentation for this class was generated from the following file:
Astrodynamics/BasicAstrodynamics/torqueModel.h