Tudat: tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType > Class Template Reference
tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType > Class Template Reference
Top-level class for performing orbit determination.
#include <orbitDeterminationManager.h>
Public Types
typedef std::map< observation_models::ObservableType, std::map< observation_models::LinkEnds, std::pair< std::map< TimeType, ObservationScalarType >, observation_models::LinkEndType > > > AlternativePodInputType
typedef Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > ObservationVectorType
Typedef for vector of observations.
typedef Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > ParameterVectorType
Typedef for vector of parameters.
typedef std::map< observation_models::ObservableType, SingleObservablePodInputType > PodInputType
Typedef for complete set of observations data, as used in orbit determination.
typedef std::map< observation_models::LinkEnds, std::pair< ObservationVectorType, std::pair< std::vector< TimeType >, observation_models::LinkEndType > > > SingleObservablePodInputType
Typedef for observations per link ends, with associated times and reference link end.
Public Member Functions
OrbitDeterminationManager (const NamedBodyMap &bodyMap, const boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const observation_models::SortedObservationSettingsMap &observationSettingsMap, const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const boost::shared_ptr< propagators::PropagatorSettings< ObservationScalarType > > propagatorSettings)
Constructor.
OrbitDeterminationManager (const NamedBodyMap &bodyMap, const boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const observation_models::ObservationSettingsMap &observationSettingsMap, const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const boost::shared_ptr< propagators::PropagatorSettings< ObservationScalarType > > propagatorSettings)
Constructor.
void calculateObservationMatrixAndResiduals (const PodInputType &observationsAndTimes, const int parameterVectorSize, const int totalObservationSize, std::pair< Eigen::VectorXd, Eigen::MatrixXd > &residualsAndPartials)
Function to calculate the observation partials matrix and residuals.
boost::shared_ptr< PodOutput< ObservationScalarType > > estimateParameters (const boost::shared_ptr< PodInput< ObservationScalarType, TimeType > > &podInput, const boost::shared_ptr< EstimationConvergenceChecker > convergenceChecker=boost::make_shared< EstimationConvergenceChecker >())
Function to perform parameter estimation from measurement data.
ParameterVectorType getCurrentParameterEstimate ()
Function to retrieve the current paramater estimate.
boost::shared_ptr< observation_models::ObservationManagerBase< ObservationScalarType, TimeType > > getObservationManager (const observation_models::ObservableType observableType) const
Function to retrieve an observation manager.
std::map< observation_models::ObservableType, boost::shared_ptr< observation_models::ObservationManagerBase< ObservationScalarType, TimeType > > > getObservationManagers () const
Function to retrieve map of all observation managers.
std::map< observation_models::ObservableType, boost::shared_ptr< observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType > > > getObservationSimulators () const
Function to retrieve map of all observation simulators.
boost::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > getStateTransitionAndSensitivityMatrixInterface ()
Function to retrieve the object used to propagate/process the solution of the variational equations/dynamics.
boost::shared_ptr< propagators::VariationalEquationsSolver< ObservationScalarType, TimeType > > getVariationalEquationsSolver () const
Function to retrieve the object to numerical integrate and update the variational equations and equations of motion.
Eigen::VectorXd normalizeObservationMatrix (Eigen::MatrixXd &observationMatrix)
void resetParameterEstimate (const ParameterVectorType &newParameterEstimate, const bool reintegrateVariationalEquations=1)
Function to reset the current parameter estimate.
Static Public Member Functions
static PodInputType convertPodInput (const AlternativePodInputType &alternativePodInput)
Function to convert from one representation of all measurement data to the other.
static std::vector< int > getNumberOfObservationsPerLinkEnd (const SingleObservablePodInputType &dataPerLinkEnd)
Function to determine the number of observations per link end.
static std::pair< std::map< observation_models::ObservableType, int >, int > getNumberOfObservationsPerObservable (const PodInputType &observationsAndTimes)
Function to determine total number of observation and number of observations per observable.
Protected Member Functions
void initializeOrbitDeterminationManager (const NamedBodyMap &bodyMap, const observation_models::SortedObservationSettingsMap &observationSettingsMap, const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const boost::shared_ptr< propagators::PropagatorSettings< ObservationScalarType > > propagatorSettings)
Function called by either constructor to initialize the object.
Protected Attributes
ParameterVectorType currentParameterEstimate_
Current values of the vector of estimated parameters.
bool dynamicsIsMultiArc_
bool integrateAndEstimateOrbit_
Boolean to denote whether any dynamical parameters are estimated.
std::vector< int > observationLinkParameterIndices_
std::map< observation_models::ObservableType, boost::shared_ptr< observation_models::ObservationManagerBase< ObservationScalarType, TimeType > > > observationManagers_
List of object that compute the values/partials of the observables.
boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate_
Container object for all parameters that are to be estimated.
boost::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionAndSensitivityMatrixInterface_
Object used to interpolate the numerically integrated result of the state transition/sensitivity matrices.
boost::shared_ptr< propagators::VariationalEquationsSolver< ObservationScalarType, TimeType > > variationalEquationsSolver_
Object used to propagate/process the numerical solution of the variational equations/dynamics.
Detailed Description
template<typename ObservationScalarType = double, typename TimeType = double>
class tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >
Top-level class for performing orbit determination. All required propagation/estimation settings are provided to this class, which then creates all objects needed for the propagation and estimation process. The parameter estimation itself is performed by providing measurement data and related metadata (as PodInput) to the estimateParameters function.
Definition at line 162 of file orbitDeterminationManager.h.
Member Typedef Documentation
template<typename ObservationScalarType = double, typename TimeType = double> typedef Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::ObservationVectorType
Definition at line 167 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> typedef Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::ParameterVectorType
Definition at line 170 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> typedef std::map< observation_models::LinkEnds, std::pair< ObservationVectorType, std::pair< std::vector< TimeType >, observation_models::LinkEndType > > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::SingleObservablePodInputType
Definition at line 174 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> typedef std::map< observation_models::ObservableType, SingleObservablePodInputType > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType
Definition at line 177 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> typedef std::map< observation_models::ObservableType, std::map< observation_models::LinkEnds, std::pair< std::map< TimeType, ObservationScalarType >, observation_models::LinkEndType > > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::AlternativePodInputType
Typedef for complete set of observations data in alternative form, as used in orbit determination, convertible to PodInputType by convertPodInput function.
Definition at line 183 of file orbitDeterminationManager.h.
Constructor & Destructor Documentation
template<typename ObservationScalarType = double, typename TimeType = double> tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::OrbitDeterminationManager (const NamedBodyMap & bodyMap, const boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const observation_models::SortedObservationSettingsMap & observationSettingsMap, const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const boost::shared_ptr< propagators::PropagatorSettings< ObservationScalarType > > propagatorSettings) inline
Constructor
Parameters
bodyMap Map of body objects with names of bodies, storing all environment models used in simulation.
parametersToEstimate Container object for all parameters that are to be estimated
observationSettingsMap Sets of observation model settings per link ends (i.e. transmitter, receiver, etc.) per observable type for which measurement data is to be provided in orbit determination process (through estimateParameters function)
integratorSettings Settings for numerical integrator.
propagatorSettings Settings for propagator.
Definition at line 196 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::OrbitDeterminationManager (const NamedBodyMap & bodyMap, const boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const observation_models::ObservationSettingsMap & observationSettingsMap, const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const boost::shared_ptr< propagators::PropagatorSettings< ObservationScalarType > > propagatorSettings) inline
Constructor
Parameters
bodyMap Map of body objects with names of bodies, storing all environment models used in simulation.
parametersToEstimate Container object for all parameters that are to be estimated
observationSettingsMap Sets of observation model settings per link ends (i.e. transmitter, receiver, etc.) for which measurement data is to be provided in orbit determination process (through estimateParameters function)
integratorSettings Settings for numerical integrator.
propagatorSettings Settings for propagator.
Definition at line 219 of file orbitDeterminationManager.h.
References tudat::observation_models::convertUnsortedToSortedObservationSettingsMap().
Member Function Documentation
template<typename ObservationScalarType = double, typename TimeType = double> std::map< observation_models::ObservableType, boost::shared_ptr< observation_models::ObservationManagerBase< ObservationScalarType, TimeType > > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::getObservationManagers () const inline
Function to retrieve map of all observation managers. A single observation manager can simulate observations and calculate observation partials for all link ends involved in the given observable type.
Returns
Map of observation managers for all observable types involved in current orbit determination.
Definition at line 240 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> std::map< observation_models::ObservableType, boost::shared_ptr< observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType > > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::getObservationSimulators () const inline
Function to retrieve map of all observation simulators. A single observation simulators can simulate observations all link ends involved in the given observable type. The observation simulators are retrieved from the observation manager objects (that are stored in the observationManagers_ map).
Returns
Map of observation simulators for all observable types involved in current orbit determination.
Definition at line 254 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> static std::vector< int > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::getNumberOfObservationsPerLinkEnd (const SingleObservablePodInputType & dataPerLinkEnd) inline static
Function to determine the number of observations per link end from a map of observations for each link ends. The input type is directly related to the data stored for a single observable in PodInput::PodInputDataType.
Parameters
dataPerLinkEnd Map of observations and times for a set of link ends.
Returns
Vector of size of number of observations in input map (in order of forward iterator over input map).
Definition at line 277 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> static std::pair< std::map< observation_models::ObservableType, int >, int > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::getNumberOfObservationsPerObservable (const PodInputType & observationsAndTimes) inline static
Function to determine total number of observation and number of observations per observable from the complete set of measurement data.
Parameters
observationsAndTimes Set of measurement data per obsevable type and link ends
Returns
Pair first: map with number of observations per observable type, second: total number of observations (i.e. sum of valus of first)
Definition at line 302 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> void tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::calculateObservationMatrixAndResiduals (const PodInputType & observationsAndTimes, const int parameterVectorSize, const int totalObservationSize, std::pair< Eigen::VectorXd, Eigen::MatrixXd > & residualsAndPartials) inline
This function calculates the observation partials matrix and residuals, based on the state transition matrix, sensitivity matrix and body states resulting from the previous numerical integration iteration. Partials and observations are calculated by the observationManagers_.
Parameters
observationsAndTimes Observable values and associated time tags, per observable type and set of link ends.
parameterVectorSize Length of the vector of estimated parameters
totalObservationSize Total number of observations in observationsAndTimes map.
residualsAndPartials Pair of residuals of computed w.r.t. input observable values and partials of observables w.r.t. parameter vector (return by reference).
Definition at line 342 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> Eigen::VectorXd tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::normalizeObservationMatrix (Eigen::MatrixXd & observationMatrix) inline
Definition at line 387 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> boost::shared_ptr< PodOutput< ObservationScalarType > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::estimateParameters (const boost::shared_ptr< PodInput< ObservationScalarType, TimeType > > & podInput, const boost::shared_ptr< EstimationConvergenceChecker > convergenceChecker = boost::make_shared< EstimationConvergenceChecker >()) inline
Function to perform parameter estimation, including orbit determination, i.e. body initial states, from measurement data. All observable types and link ends per obsevable types that are included in the measurement data input must have been provided to the constructor by the observationSettingsMap parameter.
Parameters
podInput Object containing all measurement data, associated metadata, including measurement weight, and a priori estimate for covariance matrix and parameter adjustment.
convergenceChecker Object used to check convergence/termination of algorithm
reintegrateEquationsOnFirstIteration Boolean denoting whether the dynamics and variational equations are to be reintegrated on first iteration, or if existing values are to be used to perform first iteration.
reintegrateVariationalEquations Boolean denoting whether the variational equations are to be reintegrated when first calling this object (e.g. before 1st iteration of algorithm)
saveInformationmatrix Boolean denoting whether to save the partials matrix in the output
printOutput Boolean denoting whether to print output to th terminal when running the estimation.
saveResidualsFromFirstIteration Boolean denoting whether the residuals from the 1st iteration are to be saved
Returns
Object containing estimated parameter value and associateed data, such as residuals and observation partials.
Definition at line 455 of file orbitDeterminationManager.h.
References tudat::simulation_setup::getConcatenatedWeightsVector(), tudat::linear_algebra::getVectorEntryRootMeanSquare(), and tudat::linear_algebra::performLeastSquaresAdjustmentFromInformationMatrix().
template<typename ObservationScalarType = double, typename TimeType = double> void tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::resetParameterEstimate (const ParameterVectorType & newParameterEstimate, const bool reintegrateVariationalEquations = 1) inline
Function to reset the current parameter estimate; reintegrates the variational equations and equations of motion with new estimate.
Parameters
newParameterEstimate New estimate of parameter vector.
reintegrateVariationalEquations Boolean denoting whether the variational equations are to be reintegrated
Definition at line 616 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> static PodInputType tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::convertPodInput (const AlternativePodInputType & alternativePodInput) inline static
Function to convert from one representation of all measurement data (AlternativePodInputType) to the other (PodInputType). In the former, the vector of times and vector of associated observations are stored separately. In the latter, they are stored as a map with time as key and obsevation as value.
Parameters
alternativePodInput Original representation of measurement data
Returns
Converted measurement data.
Definition at line 637 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> boost::shared_ptr< propagators::VariationalEquationsSolver< ObservationScalarType, TimeType > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::getVariationalEquationsSolver () const inline
Function to retrieve the object to numerical integrate and update the variational equations and equations of motion
Returns
Object to numerical integrate and update the variational equations and equations of motion
Definition at line 686 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> boost::shared_ptr< observation_models::ObservationManagerBase< ObservationScalarType, TimeType > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::getObservationManager (const observation_models::ObservableType observableType) const inline
Function to retrieve an observation manager for a single observable type. The observation manager can simulate observations and calculate observation partials for all link ends involved in the given observable type.
Parameters
observableType Type of observable for which manager is to be retrieved.
Returns
Observation manager for given observable type.
Definition at line 698 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> ParameterVectorType tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::getCurrentParameterEstimate () inline
Function to retrieve the current paramater estimate.
Returns
Current paramater estimate.
Definition at line 717 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> boost::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::getStateTransitionAndSensitivityMatrixInterface () inline
Function to retrieve the object used to propagate/process the numerical solution of the variational. equations/dynamics.
Returns
Object used to propagate/process the numerical solution of the variational equations/dynamics.
Definition at line 729 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> void tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::initializeOrbitDeterminationManager (const NamedBodyMap & bodyMap, const observation_models::SortedObservationSettingsMap & observationSettingsMap, const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const boost::shared_ptr< propagators::PropagatorSettings< ObservationScalarType > > propagatorSettings) inline protected
Function called by either constructor to initialize the object.
Parameters
bodyMap Map of body objects with names of bodies, storing all environment models used in simulation.
observationSettingsMap Sets of observation model settings per link ends (i.e. transmitter, receiver, etc.) for which measurement data is to be provided in orbit determination process (through estimateParameters function)
integratorSettings Settings for numerical integrator.
propagatorSettings Settings for propagator.
Definition at line 747 of file orbitDeterminationManager.h.
References tudat::estimatable_parameters::getMultiArcStateEstimationArcStartTimes(), and tudat::estimatable_parameters::isParameterObservationLinkProperty().
Member Data Documentation
template<typename ObservationScalarType = double, typename TimeType = double> bool tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::integrateAndEstimateOrbit_ protected
Definition at line 872 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> boost::shared_ptr< propagators::VariationalEquationsSolver< ObservationScalarType, TimeType > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::variationalEquationsSolver_ protected
Definition at line 876 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> std::map< observation_models::ObservableType, boost::shared_ptr< observation_models::ObservationManagerBase< ObservationScalarType, TimeType > > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::observationManagers_ protected
Definition at line 880 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::parametersToEstimate_ protected
Definition at line 883 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> ParameterVectorType tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::currentParameterEstimate_ protected
Definition at line 886 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> std::vector< int > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::observationLinkParameterIndices_ protected
Definition at line 888 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> boost::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::stateTransitionAndSensitivityMatrixInterface_ protected
Definition at line 892 of file orbitDeterminationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> bool tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType >::dynamicsIsMultiArc_ protected
Definition at line 894 of file orbitDeterminationManager.h.
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/orbitDeterminationManager.h