Tudat: tudat::reference_frames::AerodynamicAngleCalculator Class Reference
tudat::reference_frames::AerodynamicAngleCalculator Class Reference
Object to calculate aerodynamic orientation angles from current vehicle state.
#include <aerodynamicAngleCalculator.h>
Public Member Functions
AerodynamicAngleCalculator (const std::function< Eigen::Vector6d() > bodyFixedStateFunction, const std::function< Eigen::Quaterniond() > rotationFromCorotatingToInertialFrame, const std::string centralBodyName, const bool calculateVerticalToAerodynamicFrame=false, const std::function< double() > angleOfAttackFunction=std::function< double() >(), const std::function< double() > angleOfSideslipFunction=std::function< double() >(), const std::function< double() > bankAngleFunction=std::function< double() >(), const std::function< void(const double) > angleUpdateFunction=std::function< void(const double) >())
Constructor.
double getAerodynamicAngle (const AerodynamicsReferenceFrameAngles angleId)
Function to get a single orientation angle.
std::string getCentralBodyName ()
Function to get the name of central body w.r.t. which the angles are computed.
Eigen::Vector6d getCurrentAirspeedBasedBodyFixedState ()
Function to get the current airspeed-based body-fixed state of vehicle, as set by previous call to update().
Eigen::Vector6d getCurrentGroundspeedBasedBodyFixedState ()
Function to get the current groundspeed-based body-fixed state of vehicle, as set by previous call to update().
Eigen::Vector3d getCurrentGroundspeedBasedBodyFixedVelocity ()
Function to get the current groundspeed-based body-fixed velocity of vehicle, as set by previous call to update().
std::function< Eigen::Quaterniond() > getRotationFromCorotatingToInertialFrame ()
Function to get the function returning the quaternion that rotates from the corotating to the inertial frame.
Eigen::Quaterniond getRotationQuaternionBetweenFrames (const AerodynamicsReferenceFrames originalFrame, const AerodynamicsReferenceFrames targetFrame)
Function to get the rotation quaternion between two frames.
Eigen::Quaterniond getRotationToGlobalFrame ()
Function to get the current rotation from the local (body-fixed) to the global (propagation/inertial) frame.
Eigen::Quaterniond getRotationToLocalFrame ()
Function to get the current rotation from the global (propagation/inertial) to the local (body-fixed) frame.
void resetDerivedClassTime (const double currentTime=TUDAT_NAN)
Function to reset the value of the currentBodyAngleTime_ variable.
void setOrientationAngleFunctions (const std::function< double() > angleOfAttackFunction=std::function< double() >(), const std::function< double() > angleOfSideslipFunction=std::function< double() >(), const std::function< double() > bankAngleFunction=std::function< double() >(), const std::function< void(const double) > angleUpdateFunction=std::function< void(const double) >())
Function to set the trajectory<->body-fixed orientation angles.
void setOrientationAngleFunctions (const double angleOfAttack=TUDAT_NAN, const double angleOfSideslip=TUDAT_NAN, const double bankAngle=TUDAT_NAN)
Function to set constant trajectory<->body-fixed orientation angles.
void setWindModel (const std::shared_ptr< aerodynamics::WindModel > windModel, const std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel)
Function to set the atmospheric wind model.
void update (const double currentTime, const bool updateBodyOrientation)
Function to update the orientation angles to the current state.
void updateCalculator (const double currentTime)
Function to update the orientation angles to the current state.
Public Member Functions inherited from tudat::reference_frames::DependentOrientationCalculator
DependentOrientationCalculator ()
Constructor.
virtual ~DependentOrientationCalculator ()
Destructor.
Eigen::Quaterniond computeAndGetRotationToLocalFrame (const double currentTime)
Function to update the object to the current time and retrieve the rotation to the local frame.
Eigen::Quaterniond getRotationToGlobalFrame (const double currentTime)
Function to update the object to the current time and retrieve the rotation to the global frame.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the object.
Private Attributes
std::function< double() > angleOfAttackFunction_
Function to determine the angle of attack of the vehicle.
std::function< double() > angleOfSideslipFunction_
Function to determine the angle of sideslip of the vehicle.
std::function< void(const double) > angleUpdateFunction_
Function to update the bank, attack and sideslip angles to current time.
std::function< double() > bankAngleFunction_
Function to determine the bank angle of the vehicle.
std::function< Eigen::Vector6d() > bodyFixedStateFunction_
Vehicle state in a frame fixed w.r.t. the central body.
bool calculateVerticalToAerodynamicFrame_
std::string centralBodyName_
Name of central body w.r.t. which the angles are computed.
std::map< AerodynamicsReferenceFrameAngles, double > currentAerodynamicAngles_
Map of current angles, as calculated by previous call to update() function.
double currentBodyAngleTime_
Current time to which the bank, attack and sideslip angles have been updated.
Eigen::Vector6d currentBodyFixedAirspeedBasedState_
Current airspeed-based body-fixed state of vehicle, as set by previous call to update().
Eigen::Vector6d currentBodyFixedGroundSpeedBasedState_
Current groundspeed-based body-fixed state of vehicle, as set by previous call to update().
Eigen::Quaterniond currentRotationFromCorotatingToInertialFrame_
Current rotation from central-body-corotating to inertial frame, as set by previous call to update().
std::map< std::pair< AerodynamicsReferenceFrames, AerodynamicsReferenceFrames >, Eigen::Quaterniond > currentRotationMatrices_
Map of current transformation quaternions, as calculated since previous call to update() function.
std::function< Eigen::Quaterniond() > rotationFromCorotatingToInertialFrame_
Function returning the quaternion that rotates from the corotating to the inertial frame.
std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel_
Shape model of central body, used in computation of altitude that is required for wind calculation.
std::shared_ptr< aerodynamics::WindModel > windModel_
Model that computes the atmospheric wind as a function of position and time.
Additional Inherited Members
Protected Attributes inherited from tudat::reference_frames::DependentOrientationCalculator
double currentTime_
Current simulation time.
Detailed Description
Object to calculate aerodynamic orientation angles from current vehicle state.
Definition at line 82 of file aerodynamicAngleCalculator.h.
Constructor & Destructor Documentation
AerodynamicAngleCalculator()
tudat::reference_frames::AerodynamicAngleCalculator::AerodynamicAngleCalculator (const std::function< Eigen::Vector6d() > bodyFixedStateFunction, const std::function< Eigen::Quaterniond() > rotationFromCorotatingToInertialFrame, const std::string centralBodyName, const bool calculateVerticalToAerodynamicFrame = false, const std::function< double() > angleOfAttackFunction = std::function< double() >(), const std::function< double() > angleOfSideslipFunction = std::function< double() >(), const std::function< double() > bankAngleFunction = std::function< double() >(), const std::function< void(const double) > angleUpdateFunction = std::function< void(const double) >()) inline
Constructor.
Parameters
bodyFixedStateFunction Vehicle state in a frame fixed w.r.t. the central body. Note that this state is w.r.t. the body itself, not w.r.t. the local atmosphere.
rotationFromCorotatingToInertialFrame Function returning the quaternion that rotates from the corotating to the inertial frame.
centralBodyName Name of central body w.r.t. which the angles are computed.
calculateVerticalToAerodynamicFrame Boolean to determine whether to determine vertical <-> aerodynamic frame conversion when calling update function.
angleOfAttackFunction Function to determine the angle of attack of the vehicle.
angleOfSideslipFunction Function to determine the angle of sideslip of the vehicle.
bankAngleFunction Function to determine the bank angle of the vehicle.
angleUpdateFunction Function to update the aerodynamic angles to the current time (default none).
Definition at line 101 of file aerodynamicAngleCalculator.h.
Member Function Documentation
setWindModel()
void tudat::reference_frames::AerodynamicAngleCalculator::setWindModel (const std::shared_ptr< aerodynamics::WindModel > windModel, const std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel) inline
Function to set the atmospheric wind model
Parameters
windModel Model that computes the atmospheric wind as a function of position and time
shapeModel Shape model of central body, used in computation of altitude that is required for wind calculation
Definition at line 127 of file aerodynamicAngleCalculator.h.
References shapeModel_, and windModel_.
getRotationToLocalFrame()
Eigen::Quaterniond tudat::reference_frames::AerodynamicAngleCalculator::getRotationToLocalFrame () inline virtual
Function to get the current rotation from the global (propagation/inertial) to the local (body-fixed) frame. Implementation of pure virtual base class function, calls getRotationQuaternionBetweenFrames function.
Returns
Current rotation from the global (propagation/inertial) to the local (body-fixed) frame.
Implements tudat::reference_frames::DependentOrientationCalculator.
Definition at line 141 of file aerodynamicAngleCalculator.h.
References tudat::reference_frames::body_frame, getRotationQuaternionBetweenFrames(), and tudat::reference_frames::inertial_frame.
getRotationToGlobalFrame()
Eigen::Quaterniond tudat::reference_frames::AerodynamicAngleCalculator::getRotationToGlobalFrame () inline virtual
Function to get the current rotation from the local (body-fixed) to the global (propagation/inertial) frame. Implementation of pure virtual base class function, calls getRotationQuaternionBetweenFrames function.
Returns
Current rotation from the local (body-fixed) to the global (propagation/inertial) frame.
Implements tudat::reference_frames::DependentOrientationCalculator.
Definition at line 152 of file aerodynamicAngleCalculator.h.
References tudat::reference_frames::body_frame, getRotationQuaternionBetweenFrames(), and tudat::reference_frames::inertial_frame.
updateCalculator()
void tudat::reference_frames::AerodynamicAngleCalculator::updateCalculator (const double currentTime) inline virtual
Function to update the orientation angles to the current state, implements base class pure virtual function; calls update function. Note, when calling this function, the bank angle, angle of attack and sideslip angle are NOT updated (due to possible cross-dependency with aerodynamic coefficients).
See also
AerodynamicAngleCalculator::update
Implements tudat::reference_frames::DependentOrientationCalculator.
Definition at line 164 of file aerodynamicAngleCalculator.h.
References update().
update()
void tudat::reference_frames::AerodynamicAngleCalculator::update (const double currentTime, const bool updateBodyOrientation)
This function updates all requires orientation angles to the current state of the vehicle. The current state is retrieved from the bodyFixedStateFunction_ member variable function pointer.
Parameters
currentTime Time to which angle calculator is to be updated.
updateBodyOrientation Boolean denoting whether the trajectory<->body-fixed angles are to be updated.
Definition at line 100 of file aerodynamicAngleCalculator.cpp.
References tudat::reference_frames::angle_of_attack, tudat::reference_frames::angle_of_sideslip, angleOfAttackFunction_, angleOfSideslipFunction_, angleUpdateFunction_, tudat::reference_frames::bank_angle, bankAngleFunction_, bodyFixedStateFunction_, tudat::reference_frames::calculateFlightPathAngle(), tudat::reference_frames::calculateHeadingAngle(), calculateVerticalToAerodynamicFrame_, currentAerodynamicAngles_, currentBodyAngleTime_, currentBodyFixedAirspeedBasedState_, currentBodyFixedGroundSpeedBasedState_, currentRotationFromCorotatingToInertialFrame_, currentRotationMatrices_, tudat::reference_frames::DependentOrientationCalculator::currentTime_, tudat::reference_frames::flight_path_angle, tudat::reference_frames::getRotatingPlanetocentricToLocalVerticalFrameTransformationQuaternion(), tudat::reference_frames::heading_angle, tudat::reference_frames::latitude_angle, tudat::reference_frames::longitude_angle, tudat::mathematical_constants::PI, rotationFromCorotatingToInertialFrame_, shapeModel_, and windModel_.
Referenced by updateCalculator().
getRotationQuaternionBetweenFrames()
Eigen::Quaterniond tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames (const AerodynamicsReferenceFrames originalFrame, const AerodynamicsReferenceFrames targetFrame)
Function to get the rotation quaternion between two frames. This function uses the values calculated by the previous call of the update() function.
Parameters
originalFrame Id for 'current' frame
targetFrame Id for frame to which transformation object should transfrom a vector (from originalFrame).
Returns
Rotation quaternion from originalFrame to targetFrame.
Definition at line 184 of file aerodynamicAngleCalculator.cpp.
References tudat::reference_frames::aerodynamic_frame, tudat::reference_frames::angle_of_attack, tudat::reference_frames::angle_of_sideslip, tudat::reference_frames::bank_angle, tudat::reference_frames::body_frame, calculateVerticalToAerodynamicFrame_, tudat::reference_frames::corotating_frame, currentAerodynamicAngles_, currentRotationFromCorotatingToInertialFrame_, currentRotationMatrices_, tudat::reference_frames::flight_path_angle, tudat::reference_frames::getAerodynamicToTrajectoryFrameTransformationQuaternion(), tudat::reference_frames::getAirspeedBasedAerodynamicToBodyFrameTransformationQuaternion(), tudat::reference_frames::getBodyToAirspeedBasedAerodynamicFrameTransformationQuaternion(), tudat::reference_frames::getLocalVerticalFrameToTrajectoryTransformationQuaternion(), tudat::reference_frames::getLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion(), tudat::reference_frames::getRotatingPlanetocentricToLocalVerticalFrameTransformationQuaternion(), tudat::reference_frames::getTrajectoryToAerodynamicFrameTransformationQuaternion(), tudat::reference_frames::getTrajectoryToLocalVerticalFrameTransformationQuaternion(), tudat::reference_frames::heading_angle, tudat::reference_frames::inertial_frame, tudat::reference_frames::latitude_angle, tudat::reference_frames::longitude_angle, tudat::reference_frames::trajectory_frame, and tudat::reference_frames::vertical_frame.
Referenced by tudat::reference_frames::getAerodynamicForceTransformationFunction(), getRotationToGlobalFrame(), getRotationToLocalFrame(), and tudat::propagators::getVectorDependentVariableFunction().
getAerodynamicAngle()
double tudat::reference_frames::AerodynamicAngleCalculator::getAerodynamicAngle (const AerodynamicsReferenceFrameAngles angleId)
Function to get a single orientation angle, as calculated by previous call to update() function.
Parameters
angleId Id of requested angle.
Returns
Value of requested angle.
Definition at line 359 of file aerodynamicAngleCalculator.cpp.
References currentAerodynamicAngles_, and TUDAT_NAN.
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
setOrientationAngleFunctions() [1/2]
void tudat::reference_frames::AerodynamicAngleCalculator::setOrientationAngleFunctions (const std::function< double() > angleOfAttackFunction = std::function< double() >(), const std::function< double() > angleOfSideslipFunction = std::function< double() >(), const std::function< double() > bankAngleFunction = std::function< double() >(), const std::function< void(const double) > angleUpdateFunction = std::function< void(const double) >())
Function to set the trajectory<->body-fixed orientation angles.
Parameters
angleOfAttackFunction Function to return the angle of attack.
angleOfSideslipFunction Function to return the angle of sideslip.
bankAngleFunction Function to return the bank angle.
angleUpdateFunction Function to update the angles to the current time.
Definition at line 376 of file aerodynamicAngleCalculator.cpp.
References angleOfAttackFunction_, angleOfSideslipFunction_, angleUpdateFunction_, and bankAngleFunction_.
Referenced by setOrientationAngleFunctions().
setOrientationAngleFunctions() [2/2]
void tudat::reference_frames::AerodynamicAngleCalculator::setOrientationAngleFunctions (const double angleOfAttack = TUDAT_NAN, const double angleOfSideslip = TUDAT_NAN, const double bankAngle = TUDAT_NAN)
Function to set constant trajectory<->body-fixed orientation angles.
Parameters
angleOfAttack Constant angle of attack (default NaN, used if no angle is to be defined).
angleOfSideslip Constant angle of sideslip (default NaN, used if no angle is to be defined).
bankAngle Constant bank angle (default NaN, used if no angle is to be defined).
Definition at line 420 of file aerodynamicAngleCalculator.cpp.
References setOrientationAngleFunctions().
getRotationFromCorotatingToInertialFrame()
std::function< Eigen::Quaterniond() > tudat::reference_frames::AerodynamicAngleCalculator::getRotationFromCorotatingToInertialFrame () inline
Function to get the function returning the quaternion that rotates from the corotating to the inertial frame.
Returns
Function returning the quaternion that rotates from the corotating to the inertial frame.
Definition at line 232 of file aerodynamicAngleCalculator.h.
References rotationFromCorotatingToInertialFrame_.
getCentralBodyName()
std::string tudat::reference_frames::AerodynamicAngleCalculator::getCentralBodyName () inline
Function to get the name of central body w.r.t. which the angles are computed.
Returns
Name of central body w.r.t. which the angles are computed.
Definition at line 242 of file aerodynamicAngleCalculator.h.
References centralBodyName_.
getCurrentAirspeedBasedBodyFixedState()
Eigen::Vector6d tudat::reference_frames::AerodynamicAngleCalculator::getCurrentAirspeedBasedBodyFixedState () inline
Function to get the current airspeed-based body-fixed state of vehicle, as set by previous call to update().
Returns
Current airspeed-based body-fixed state of vehicle, as set by previous call to update().
Definition at line 252 of file aerodynamicAngleCalculator.h.
References currentBodyFixedAirspeedBasedState_.
Referenced by tudat::aerodynamics::FlightConditions::FlightConditions(), and tudat::aerodynamics::FlightConditions::setAerodynamicAngleCalculator().
getCurrentGroundspeedBasedBodyFixedState()
Eigen::Vector6d tudat::reference_frames::AerodynamicAngleCalculator::getCurrentGroundspeedBasedBodyFixedState () inline
Function to get the current groundspeed-based body-fixed state of vehicle, as set by previous call to update().
Returns
Current groundspeed-based body-fixed state of vehicle, as set by previous call to update().
Definition at line 262 of file aerodynamicAngleCalculator.h.
References currentBodyFixedGroundSpeedBasedState_.
getCurrentGroundspeedBasedBodyFixedVelocity()
Eigen::Vector3d tudat::reference_frames::AerodynamicAngleCalculator::getCurrentGroundspeedBasedBodyFixedVelocity () inline
Function to get the current groundspeed-based body-fixed velocity of vehicle, as set by previous call to update().
Returns
Current groundspeed-based body-fixed velocity of vehicle, as set by previous call to update().
Definition at line 272 of file aerodynamicAngleCalculator.h.
References currentBodyFixedGroundSpeedBasedState_.
Referenced by tudat::propagators::getVectorDependentVariableFunction().
resetDerivedClassTime()
void tudat::reference_frames::AerodynamicAngleCalculator::resetDerivedClassTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the value of the currentBodyAngleTime_ variable. Typically used to reset the time to NaN, signalling the need to recompute all quantities upon the next relevant function call.
Parameters
currentTime New current time.
Reimplemented from tudat::reference_frames::DependentOrientationCalculator.
Definition at line 283 of file aerodynamicAngleCalculator.h.
References currentBodyAngleTime_.
Member Data Documentation
windModel_
std::shared_ptr< aerodynamics::WindModel > tudat::reference_frames::AerodynamicAngleCalculator::windModel_ private
Definition at line 291 of file aerodynamicAngleCalculator.h.
Referenced by setWindModel(), and update().
shapeModel_
std::shared_ptr< basic_astrodynamics::BodyShapeModel > tudat::reference_frames::AerodynamicAngleCalculator::shapeModel_ private
Definition at line 294 of file aerodynamicAngleCalculator.h.
Referenced by setWindModel(), and update().
currentAerodynamicAngles_
std::map< AerodynamicsReferenceFrameAngles, double > tudat::reference_frames::AerodynamicAngleCalculator::currentAerodynamicAngles_ private
Definition at line 297 of file aerodynamicAngleCalculator.h.
Referenced by getAerodynamicAngle(), getRotationQuaternionBetweenFrames(), and update().
currentRotationMatrices_
std::map< std::pair< AerodynamicsReferenceFrames, AerodynamicsReferenceFrames >, Eigen::Quaterniond > tudat::reference_frames::AerodynamicAngleCalculator::currentRotationMatrices_ private
Definition at line 301 of file aerodynamicAngleCalculator.h.
Referenced by getRotationQuaternionBetweenFrames(), and update().
currentBodyFixedAirspeedBasedState_
Eigen::Vector6d tudat::reference_frames::AerodynamicAngleCalculator::currentBodyFixedAirspeedBasedState_ private
Definition at line 304 of file aerodynamicAngleCalculator.h.
Referenced by getCurrentAirspeedBasedBodyFixedState(), and update().
currentBodyFixedGroundSpeedBasedState_
Eigen::Vector6d tudat::reference_frames::AerodynamicAngleCalculator::currentBodyFixedGroundSpeedBasedState_ private
Definition at line 307 of file aerodynamicAngleCalculator.h.
Referenced by getCurrentGroundspeedBasedBodyFixedState(), getCurrentGroundspeedBasedBodyFixedVelocity(), and update().
currentRotationFromCorotatingToInertialFrame_
Eigen::Quaterniond tudat::reference_frames::AerodynamicAngleCalculator::currentRotationFromCorotatingToInertialFrame_ private
Definition at line 310 of file aerodynamicAngleCalculator.h.
Referenced by getRotationQuaternionBetweenFrames(), and update().
bodyFixedStateFunction_
std::function< Eigen::Vector6d() > tudat::reference_frames::AerodynamicAngleCalculator::bodyFixedStateFunction_ private
Vehicle state in a frame fixed w.r.t. the central body. Note that this state is w.r.t. the body itself, not w.r.t. the local atmosphere
Definition at line 317 of file aerodynamicAngleCalculator.h.
Referenced by update().
rotationFromCorotatingToInertialFrame_
std::function< Eigen::Quaterniond() > tudat::reference_frames::AerodynamicAngleCalculator::rotationFromCorotatingToInertialFrame_ private
Definition at line 320 of file aerodynamicAngleCalculator.h.
Referenced by getRotationFromCorotatingToInertialFrame(), and update().
centralBodyName_
std::string tudat::reference_frames::AerodynamicAngleCalculator::centralBodyName_ private
Definition at line 323 of file aerodynamicAngleCalculator.h.
Referenced by getCentralBodyName().
calculateVerticalToAerodynamicFrame_
bool tudat::reference_frames::AerodynamicAngleCalculator::calculateVerticalToAerodynamicFrame_ private
Boolean to determine whether to determine vertical <-> aerodynamic frame conversion when calling update function.
Definition at line 327 of file aerodynamicAngleCalculator.h.
Referenced by getRotationQuaternionBetweenFrames(), and update().
angleOfAttackFunction_
std::function< double() > tudat::reference_frames::AerodynamicAngleCalculator::angleOfAttackFunction_ private
Definition at line 330 of file aerodynamicAngleCalculator.h.
Referenced by setOrientationAngleFunctions(), and update().
angleOfSideslipFunction_
std::function< double() > tudat::reference_frames::AerodynamicAngleCalculator::angleOfSideslipFunction_ private
Definition at line 333 of file aerodynamicAngleCalculator.h.
Referenced by setOrientationAngleFunctions(), and update().
bankAngleFunction_
std::function< double() > tudat::reference_frames::AerodynamicAngleCalculator::bankAngleFunction_ private
Definition at line 336 of file aerodynamicAngleCalculator.h.
Referenced by setOrientationAngleFunctions(), and update().
angleUpdateFunction_
std::function< void(const double) > tudat::reference_frames::AerodynamicAngleCalculator::angleUpdateFunction_ private
Definition at line 339 of file aerodynamicAngleCalculator.h.
Referenced by setOrientationAngleFunctions(), and update().
currentBodyAngleTime_
double tudat::reference_frames::AerodynamicAngleCalculator::currentBodyAngleTime_ private
Definition at line 342 of file aerodynamicAngleCalculator.h.
Referenced by resetDerivedClassTime(), and update().
The documentation for this class was generated from the following files:
Astrodynamics/ReferenceFrames/aerodynamicAngleCalculator.h
Astrodynamics/ReferenceFrames/aerodynamicAngleCalculator.cpp