Tudat: tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType > Class Template Reference
tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType > Class Template Reference abstract
Base class for interpolator.
#include <interpolator.h>
Public Member Functions
virtual ~Interpolator ()
Destructor.
virtual int getNumberOfDimensions ()=0
Function to return the number of independent variables of the interpolation.
virtual DependentVariableType interpolate (const std::vector< IndependentVariableType > &independentVariableValues)=0
Interpolate.
Detailed Description
template<typename IndependentVariableType, typename DependentVariableType>
class tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >
Base class for the interpolators included in Tudat, the dependent and independent variable types are specified as user parameters, as are the number of dimensions. The number of dimensions is chosen as a template parameter, so that a boost multi_array of this dimension can be used as a member variable of derived classes.
Template Parameters
IndependentVariableType Type of independent variable(s).
IndependentVariableType Type of dependent variable.
numberOfDimensions Number of independent directions for independent variables.
Definition at line 33 of file interpolator.h.
Constructor & Destructor Documentation
template<typename IndependentVariableType , typename DependentVariableType > virtual tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >::~Interpolator () inline virtual
Destructor.
Definition at line 41 of file interpolator.h.
References tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >::getNumberOfDimensions(), and tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >::interpolate().
Member Function Documentation
template<typename IndependentVariableType , typename DependentVariableType > virtual DependentVariableType tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >::interpolate (const std::vector< IndependentVariableType > & independentVariableValues) pure virtual
This function performs the interpolation. It must be implemented in derived classes.
Parameters
independentVariableValues Vector of values of independent variables at which the value of the dependent variable is to be determined.
Returns
Interpolated value of dependent variable.
Implemented in tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >.
Referenced by tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >::~Interpolator().
template<typename IndependentVariableType , typename DependentVariableType > virtual int tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >::getNumberOfDimensions () pure virtual
Function to return the number of independent variables of the interpolation, i.e. size that the vector used as input for Interpolator::interpolate should be.
Returns
Number of independent variables of the interpolation.
Implemented in tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >.
Referenced by tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >::~Interpolator().
The documentation for this class was generated from the following file:
Mathematics/Interpolators/interpolator.h