Tudat: tudat::basic_astrodynamics::BodyShapeModel Class Reference
tudat::basic_astrodynamics::BodyShapeModel Class Reference abstract
Base class for body shape models.
#include <bodyShapeModel.h>
Public Member Functions
BodyShapeModel ()
Default constructor.
virtual ~BodyShapeModel ()
Virtual destructor.
virtual double getAltitude (const Eigen::Vector3d &bodyFixedPosition)=0
Calculates the altitude above the shape.
virtual double getAverageRadius ()=0
Function to return the mean radius of the shape model.
Detailed Description
This is the base class for shape models for (celestial) bodies, such as spheres, ellipsoids, or tri-axial ellipsoids. It can be used to calculate the altitude above such a shape or the local radius.
Definition at line 36 of file bodyShapeModel.h.
Constructor & Destructor Documentation
tudat::basic_astrodynamics::BodyShapeModel::BodyShapeModel () inline
Definition at line 41 of file bodyShapeModel.h.
virtual tudat::basic_astrodynamics::BodyShapeModel::~BodyShapeModel () inline virtual
Definition at line 44 of file bodyShapeModel.h.
References getAltitude(), tudat::basic_astrodynamics::getAltitudeFromNonBodyFixedPosition(), tudat::basic_astrodynamics::getAltitudeFromNonBodyFixedPositionFunctions(), and getAverageRadius().
Member Function Documentation
virtual double tudat::basic_astrodynamics::BodyShapeModel::getAltitude (const Eigen::Vector3d & bodyFixedPosition) pure virtual
Function to calculate the altitude above the shape from the a body fixed position.
Parameters
bodyFixedPosition Cartesian, body-fixed position of the point at which the altitude is to be determined.
Returns
Altitude above the body.
Implemented in tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel, and tudat::basic_astrodynamics::SphericalBodyShapeModel.
Referenced by ~BodyShapeModel().
virtual double tudat::basic_astrodynamics::BodyShapeModel::getAverageRadius () pure virtual
Function to return the mean radius of the shape model, to be used for functions requiring moderate to low accuracy for shape model, i.e. using a 'nearest equivalent' sphere.
Returns
Average radius of shape model.
Implemented in tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel, and tudat::basic_astrodynamics::SphericalBodyShapeModel.
Referenced by tudat::propagators::getDoubleDependentVariableFunction(), and ~BodyShapeModel().
The documentation for this class was generated from the following file:
Astrodynamics/BasicAstrodynamics/bodyShapeModel.h