Tudat: tudat::aerodynamics::AtmosphericFlightConditions Class Reference
tudat::aerodynamics::AtmosphericFlightConditions Class Reference
Class for calculating aerodynamic flight characteristics of a vehicle during numerical integration.
#include <flightConditions.h>
Public Member Functions
AtmosphericFlightConditions (const std::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel, const std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel, const std::shared_ptr< AerodynamicCoefficientInterface > aerodynamicCoefficientInterface, const std::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator=std::shared_ptr< reference_frames::AerodynamicAngleCalculator >(), const std::function< double(const std::string &)> controlSurfaceDeflectionFunction=std::function< double(const std::string &)>())
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
std::vector< double > getAerodynamicCoefficientIndependentVariables ()
Function to return list of independent variables of the aerodynamic coefficient interface.
std::shared_ptr< AerodynamicCoefficientInterface > getAerodynamicCoefficientInterface ()
Function to return object from which the aerodynamic coefficients are obtained.
std::shared_ptr< aerodynamics::AtmosphereModel > getAtmosphereModel () const
Function to return atmosphere model object.
std::map< std::string, std::vector< double > > getControlSurfaceAerodynamicCoefficientIndependentVariables ()
Function to return list of independent variables of the control surface aerodynamic coefficient interface.
double getCurrentAerodynamicHeatRate ()
Function to retrieve (and compute if necessary) the current aerodynamic heat rate.
double getCurrentAirspeed ()
Function to retrieve (and compute if necessary) the current airspeed.
Eigen::Vector3d getCurrentAirspeedBasedVelocity ()
Function to return current central body-fixed velocity of vehicle.
double getCurrentDensity ()
Function to retrieve (and compute if necessary) the current freestream density.
double getCurrentDynamicPressure ()
Function to retrieve (and compute if necessary) the current freestream dynamic pressure.
double getCurrentFreestreamTemperature ()
Function to retrieve (and compute if necessary) the current freestream temperature.
double getCurrentMachNumber ()
Function to retrieve (and compute if necessary) the current Mach number.
double getCurrentPressure ()
Function to retrieve (and compute if necessary) the current freestream pressure.
double getCurrentSpeedOfSound ()
Function to retrieve (and compute if necessary) the current speed of sound.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the flight conditions.
void setAerodynamicCoefficientsIndependentVariableFunction (const AerodynamicCoefficientsIndependentVariables independentVariable, const std::function< double() > coefficientDependency)
Function to set custom dependency of aerodynamic coefficients.
void updateConditions (const double currentTime)
Function to update all flight conditions.
Public Member Functions inherited from tudat::aerodynamics::FlightConditions
FlightConditions (const std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel, const std::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator=std::shared_ptr< reference_frames::AerodynamicAngleCalculator >())
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
virtual ~FlightConditions ()
Destructor.
std::shared_ptr< reference_frames::AerodynamicAngleCalculator > getAerodynamicAngleCalculator ()
Function to return aerodynamic angle calculator object.
double getCurrentAltitude ()
Function to retrieve (and compute if necessary) the current altitude.
Eigen::Vector6d getCurrentBodyCenteredBodyFixedState ()
Function to return current central body-fixed state of vehicle.
double getCurrentGeodeticLatitude ()
Function to retrieve (and compute if necessary) the current geodetic latitude.
double getCurrentLongitude ()
Function to retrieve (and compute if necessary) the current longitude.
double getCurrentTime ()
Function to return the current time of the AtmosphericFlightConditions.
void setAerodynamicAngleCalculator (const std::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Function to (re)set aerodynamic angle calculator object.
Private Member Functions
void computeAerodynamicHeatRate ()
Function to compute and set the current aerodynamic heat rate.
void computeAirspeed ()
Function to compute and set the current airspeed.
void computeDensity ()
Function to compute and set the current freestream density.
void computeDynamicPressure ()
Function to compute and set the current freestream dynamic pressure.
void computeFreestreamPressure ()
Function to compute and set the current freestream pressure.
void computeMachNumber ()
Function to compute and set the current Mach number.
void computeSpeedOfSound ()
Function to compute and set the current speed of sound.
void computeTemperature ()
Function to compute and set the current freestream temperature.
double getAerodynamicCoefficientIndependentVariable (const AerodynamicCoefficientsIndependentVariables independentVariableType, const std::string &secondaryIdentifier="")
Function to (compute and) retrieve the value of an independent variable of aerodynamic coefficients.
void updateAerodynamicCoefficientInput ()
Function to update the independent variables of the aerodynamic coefficient interface.
void updateAtmosphereInput ()
Function to update input to atmosphere model (altitude, as well as latitude and longitude if needed).
Private Attributes
std::vector< double > aerodynamicCoefficientIndependentVariables_
Current list of independent variables of the aerodynamic coefficient interface.
std::shared_ptr< AerodynamicCoefficientInterface > aerodynamicCoefficientInterface_
Object from which the aerodynamic coefficients are obtained.
std::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel_
Atmosphere model of atmosphere through which vehicle is flying.
std::map< std::string, std::vector< double > > controlSurfaceAerodynamicCoefficientIndependentVariables_
std::function< double(const std::string &) > controlSurfaceDeflectionFunction_
Function returning control surface deflection, with input the control surface identifier.
std::map< AerodynamicCoefficientsIndependentVariables, std::function< double() > > customCoefficientDependencies_
List of custom functions for aerodynamic coefficient dependencies.
bool updateLatitudeAndLongitudeForAtmosphere_
Boolean setting whether latitude and longitude are to be updated by updateConditions().
Additional Inherited Members
Protected Types inherited from tudat::aerodynamics::FlightConditions
enum FlightConditionVariables {
altitude_flight_condition, density_flight_condition, pressure_flight_condition, temperature_flight_condition,
latitude_flight_condition, longitude_flight_condition, mach_number_flight_condition, speed_of_sound_flight_condition,
airspeed_flight_condition, geodetic_latitude_condition, dynamic_pressure_condition, aerodynamic_heat_rate
}
List of variables that can be computed by flight condition.
Protected Member Functions inherited from tudat::aerodynamics::FlightConditions
void computeAltitude ()
Function to compute and set the current altitude.
void computeGeodeticLatitude ()
Function to compute and set the current geodetic latitude.
void computeLatitudeAndLongitude ()
Function to compute and set the current latitude and longitude.
Protected Attributes inherited from tudat::aerodynamics::FlightConditions
std::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator_
Object from which the aerodynamic/trajectory angles of the vehicle are calculated.
std::function< Eigen::Vector6d() > bodyCenteredPseudoBodyFixedStateFunction_
Function to return the current state of the vehicle in a body-fixed frame.
std::string centralBody_
Name of central body (i.e. body with the atmosphere)
Eigen::Vector6d currentBodyCenteredAirspeedBasedBodyFixedState_
Current state of vehicle in body-fixed frame.
Eigen::Vector6d currentBodyCenteredState_
Current state of vehicle in base frame for Body objects.
double currentTime_
Current time of propagation.
std::function< double(const Eigen::Vector3d &) > geodeticLatitudeFunction_
bool isLatitudeAndLongitudeSet_
Boolean denoting whether the current latitude and longitude have been computed at current time step.
std::map< FlightConditionVariables, double > scalarFlightConditions_
List of atmospheric/flight properties computed at current time step.
const std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel_
Model describing the shape of the body w.r.t. which the flight is taking place.
Detailed Description
Class for calculating aerodynamic flight characteristics of a vehicle during numerical integration.
Class is used to ensure that dependent variables such as density, altitude, etc. are only calculated once during each numerical integration step. The get functions of this class are linked to the various models in the code that subsequently require these values.
Definition at line 268 of file flightConditions.h.
Constructor & Destructor Documentation
AtmosphericFlightConditions()
tudat::aerodynamics::AtmosphericFlightConditions::AtmosphericFlightConditions (const std::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel, const std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel, const std::shared_ptr< AerodynamicCoefficientInterface > aerodynamicCoefficientInterface, const std::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator = std::shared_ptr< reference_frames::AerodynamicAngleCalculator >(), const std::function< double(const std::string &)> controlSurfaceDeflectionFunction = std::function< double(const std::string&)>())
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
Parameters
atmosphereModel Atmosphere model of atmosphere through which vehicle is flying
shapeModel Model describing the shape of the body w.r.t. which the flight is taking place.
aerodynamicCoefficientInterface Class from which the aerodynamic (force and moment) coefficients are retrieved
aerodynamicAngleCalculator Object from which the aerodynamic/trajectory angles of the vehicle are calculated.
controlSurfaceDeflectionFunction Function returning control surface deflection, with input the control surface identifier.
Definition at line 69 of file flightConditions.cpp.
References tudat::aerodynamics::FlightConditions::aerodynamicAngleCalculator_, atmosphereModel_, tudat::aerodynamics::FlightConditions::isLatitudeAndLongitudeSet_, and updateLatitudeAndLongitudeForAtmosphere_.
Member Function Documentation
updateConditions()
void tudat::aerodynamics::AtmosphericFlightConditions::updateConditions (const double currentTime) virtual
Function to update all flight conditions (altitude, density, force coefficients) to current state of vehicle and central body.
Parameters
currentTime Time to which conditions are to be updated.
Reimplemented from tudat::aerodynamics::FlightConditions.
Definition at line 119 of file flightConditions.cpp.
References tudat::aerodynamics::FlightConditions::aerodynamicAngleCalculator_, aerodynamicCoefficientIndependentVariables_, aerodynamicCoefficientInterface_, tudat::aerodynamics::FlightConditions::bodyCenteredPseudoBodyFixedStateFunction_, controlSurfaceAerodynamicCoefficientIndependentVariables_, tudat::aerodynamics::FlightConditions::currentBodyCenteredAirspeedBasedBodyFixedState_, tudat::aerodynamics::FlightConditions::currentTime_, and updateAerodynamicCoefficientInput().
getCurrentDensity()
double tudat::aerodynamics::AtmosphericFlightConditions::getCurrentDensity () inline
Function to retrieve (and compute if necessary) the current freestream density
Returns
Current freestream density
Definition at line 310 of file flightConditions.h.
References computeDensity(), tudat::aerodynamics::FlightConditions::density_flight_condition, and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by computeAerodynamicHeatRate(), computeDynamicPressure(), tudat::simulation_setup::createAerodynamicAcceleratioModel(), tudat::simulation_setup::createAerodynamicTorqueModel(), tudat::propagators::getDoubleDependentVariableFunction(), and tudat::simulation_setup::getPropulsionInputVariables().
getCurrentFreestreamTemperature()
double tudat::aerodynamics::AtmosphericFlightConditions::getCurrentFreestreamTemperature () inline
Function to retrieve (and compute if necessary) the current freestream temperature
Returns
Current freestream temperature
Definition at line 324 of file flightConditions.h.
References computeTemperature(), tudat::aerodynamics::FlightConditions::scalarFlightConditions_, and tudat::aerodynamics::FlightConditions::temperature_flight_condition.
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
getCurrentDynamicPressure()
double tudat::aerodynamics::AtmosphericFlightConditions::getCurrentDynamicPressure () inline
Function to retrieve (and compute if necessary) the current freestream dynamic pressure
Returns
Current freestream dynamic pressure
Definition at line 338 of file flightConditions.h.
References computeDynamicPressure(), tudat::aerodynamics::FlightConditions::dynamic_pressure_condition, and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by tudat::propagators::getDoubleDependentVariableFunction(), and tudat::simulation_setup::getPropulsionInputVariables().
getCurrentAerodynamicHeatRate()
double tudat::aerodynamics::AtmosphericFlightConditions::getCurrentAerodynamicHeatRate () inline
Function to retrieve (and compute if necessary) the current aerodynamic heat rate
Returns
Current aerodynamic heat rate
Definition at line 352 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::aerodynamic_heat_rate, computeAerodynamicHeatRate(), and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
getCurrentPressure()
double tudat::aerodynamics::AtmosphericFlightConditions::getCurrentPressure () inline
Function to retrieve (and compute if necessary) the current freestream pressure
Returns
Current freestream dynamic pressure
Definition at line 366 of file flightConditions.h.
References computeFreestreamPressure(), tudat::aerodynamics::FlightConditions::pressure_flight_condition, and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by tudat::simulation_setup::getPropulsionInputVariables().
getCurrentAirspeed()
double tudat::aerodynamics::AtmosphericFlightConditions::getCurrentAirspeed () inline
Returns
Current airspeed
Definition at line 379 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::airspeed_flight_condition, computeAirspeed(), and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by computeAerodynamicHeatRate(), computeDynamicPressure(), computeMachNumber(), tudat::simulation_setup::createAerodynamicAcceleratioModel(), tudat::simulation_setup::createAerodynamicTorqueModel(), and tudat::propagators::getDoubleDependentVariableFunction().
getCurrentSpeedOfSound()
double tudat::aerodynamics::AtmosphericFlightConditions::getCurrentSpeedOfSound () inline
Function to retrieve (and compute if necessary) the current speed of sound
Returns
Current speed of sound
Definition at line 393 of file flightConditions.h.
References computeSpeedOfSound(), tudat::aerodynamics::FlightConditions::scalarFlightConditions_, and tudat::aerodynamics::FlightConditions::speed_of_sound_flight_condition.
Referenced by computeMachNumber(), and tudat::propagators::getDoubleDependentVariableFunction().
getCurrentMachNumber()
double tudat::aerodynamics::AtmosphericFlightConditions::getCurrentMachNumber () inline
Function to retrieve (and compute if necessary) the current Mach number
Returns
Current Mach number
Definition at line 407 of file flightConditions.h.
References computeMachNumber(), tudat::aerodynamics::FlightConditions::mach_number_flight_condition, and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by getAerodynamicCoefficientIndependentVariable(), and tudat::simulation_setup::getPropulsionInputVariables().
getAtmosphereModel()
std::shared_ptr< aerodynamics::AtmosphereModel > tudat::aerodynamics::AtmosphericFlightConditions::getAtmosphereModel () const inline
Function to return atmosphere model object
Returns
Atmosphere model object
Definition at line 421 of file flightConditions.h.
References atmosphereModel_.
setAerodynamicCoefficientsIndependentVariableFunction()
void tudat::aerodynamics::AtmosphericFlightConditions::setAerodynamicCoefficientsIndependentVariableFunction (const AerodynamicCoefficientsIndependentVariables independentVariable, const std::function< double() > coefficientDependency)
Function to set custom dependency of aerodynamic coefficients. If needed, the AerodynamicCoefficientsIndependentVariables enum may be expanded to include e.g. control surface deflections, the values of which will then be retrieved from the function set here
Parameters
independentVariable Identifier of independent variable
coefficientDependency Function returning the current value of the independent variable.
Definition at line 98 of file flightConditions.cpp.
References tudat::aerodynamics::altitude_dependent, tudat::aerodynamics::angle_of_attack_dependent, tudat::aerodynamics::angle_of_sideslip_dependent, customCoefficientDependencies_, tudat::propagators::independentVariable, and tudat::aerodynamics::mach_number_dependent.
getCurrentAirspeedBasedVelocity()
Eigen::Vector3d tudat::aerodynamics::AtmosphericFlightConditions::getCurrentAirspeedBasedVelocity () inline
Function to return central body-fixed velocity of vehicle.
Returns
Current central body-fixed velocity of vehicle.
Definition at line 443 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::currentBodyCenteredAirspeedBasedBodyFixedState_.
Referenced by tudat::propagators::getVectorDependentVariableFunction().
getAerodynamicCoefficientInterface()
std::shared_ptr< AerodynamicCoefficientInterface > tudat::aerodynamics::AtmosphericFlightConditions::getAerodynamicCoefficientInterface () inline
Function to return object from which the aerodynamic coefficients are obtained.
Returns
Object from which the aerodynamic coefficients are obtained.
Definition at line 453 of file flightConditions.h.
References aerodynamicCoefficientInterface_.
getAerodynamicCoefficientIndependentVariables()
std::vector< double > tudat::aerodynamics::AtmosphericFlightConditions::getAerodynamicCoefficientIndependentVariables () inline
Function to return list of independent variables of the aerodynamic coefficient interface
Returns
List of independent variables of the aerodynamic coefficient interface
Definition at line 463 of file flightConditions.h.
References aerodynamicCoefficientIndependentVariables_, aerodynamicCoefficientInterface_, and updateAerodynamicCoefficientInput().
Referenced by tudat::simulation_setup::setTrimmedConditions(), and tudat::aerodynamics::setTrimmedConditions().
getControlSurfaceAerodynamicCoefficientIndependentVariables()
std::map< std::string, std::vector< double > > tudat::aerodynamics::AtmosphericFlightConditions::getControlSurfaceAerodynamicCoefficientIndependentVariables () inline
Function to return list of independent variables of the control surface aerodynamic coefficient interface
Returns
List of independent variables of the control surface aerodynamic coefficient interface, with map key the control surface identifiers.
Definition at line 480 of file flightConditions.h.
References aerodynamicCoefficientInterface_, controlSurfaceAerodynamicCoefficientIndependentVariables_, and updateAerodynamicCoefficientInput().
Referenced by tudat::simulation_setup::setTrimmedConditions(), and tudat::aerodynamics::setTrimmedConditions().
resetCurrentTime()
void tudat::aerodynamics::AtmosphericFlightConditions::resetCurrentTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the current time of the flight conditions. This function is typically sused to set the current time to NaN, indicating the need to recompute all quantities for the next time computation.
Parameters
currentTime
Reimplemented from tudat::aerodynamics::FlightConditions.
Definition at line 497 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::aerodynamicAngleCalculator_, aerodynamicCoefficientIndependentVariables_, controlSurfaceAerodynamicCoefficientIndependentVariables_, tudat::aerodynamics::FlightConditions::currentTime_, tudat::aerodynamics::FlightConditions::isLatitudeAndLongitudeSet_, and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
getAerodynamicCoefficientIndependentVariable()
double tudat::aerodynamics::AtmosphericFlightConditions::getAerodynamicCoefficientIndependentVariable (const AerodynamicCoefficientsIndependentVariables independentVariableType, const std::string & secondaryIdentifier = "") private
Function to (compute and) retrieve the value of an independent variable of aerodynamic coefficients
Parameters
independentVariableType Identifier for type of independent variable
secondaryIdentifier String used as secondary identifier of independent variable (e.g. control surface name).
Returns
Current value of requested independent variable.
Definition at line 150 of file flightConditions.cpp.
References tudat::aerodynamics::FlightConditions::aerodynamicAngleCalculator_, tudat::aerodynamics::altitude_dependent, tudat::reference_frames::angle_of_attack, tudat::aerodynamics::angle_of_attack_dependent, tudat::reference_frames::angle_of_sideslip, tudat::aerodynamics::angle_of_sideslip_dependent, tudat::aerodynamics::control_surface_deflection_dependent, controlSurfaceDeflectionFunction_, customCoefficientDependencies_, tudat::aerodynamics::FlightConditions::getCurrentAltitude(), getCurrentMachNumber(), and tudat::aerodynamics::mach_number_dependent.
Referenced by updateAerodynamicCoefficientInput().
updateAtmosphereInput()
void tudat::aerodynamics::AtmosphericFlightConditions::updateAtmosphereInput () inline private
Definition at line 523 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::altitude_flight_condition, tudat::aerodynamics::FlightConditions::computeAltitude(), tudat::aerodynamics::FlightConditions::computeLatitudeAndLongitude(), tudat::aerodynamics::FlightConditions::latitude_flight_condition, tudat::aerodynamics::FlightConditions::longitude_flight_condition, tudat::aerodynamics::FlightConditions::scalarFlightConditions_, and updateLatitudeAndLongitudeForAtmosphere_.
Referenced by computeDensity(), computeFreestreamPressure(), computeSpeedOfSound(), and computeTemperature().
computeDensity()
void tudat::aerodynamics::AtmosphericFlightConditions::computeDensity () inline private
Definition at line 546 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::altitude_flight_condition, atmosphereModel_, tudat::aerodynamics::FlightConditions::currentTime_, tudat::aerodynamics::FlightConditions::density_flight_condition, tudat::aerodynamics::FlightConditions::latitude_flight_condition, tudat::aerodynamics::FlightConditions::longitude_flight_condition, tudat::aerodynamics::FlightConditions::scalarFlightConditions_, and updateAtmosphereInput().
Referenced by getCurrentDensity().
computeTemperature()
void tudat::aerodynamics::AtmosphericFlightConditions::computeTemperature () inline private
Definition at line 557 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::altitude_flight_condition, atmosphereModel_, tudat::aerodynamics::FlightConditions::currentTime_, tudat::aerodynamics::FlightConditions::latitude_flight_condition, tudat::aerodynamics::FlightConditions::longitude_flight_condition, tudat::aerodynamics::FlightConditions::scalarFlightConditions_, tudat::aerodynamics::FlightConditions::temperature_flight_condition, and updateAtmosphereInput().
Referenced by getCurrentFreestreamTemperature().
computeFreestreamPressure()
void tudat::aerodynamics::AtmosphericFlightConditions::computeFreestreamPressure () inline private
Definition at line 568 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::altitude_flight_condition, atmosphereModel_, tudat::aerodynamics::FlightConditions::currentTime_, tudat::aerodynamics::FlightConditions::latitude_flight_condition, tudat::aerodynamics::FlightConditions::longitude_flight_condition, tudat::aerodynamics::FlightConditions::pressure_flight_condition, tudat::aerodynamics::FlightConditions::scalarFlightConditions_, and updateAtmosphereInput().
Referenced by getCurrentPressure().
computeSpeedOfSound()
void tudat::aerodynamics::AtmosphericFlightConditions::computeSpeedOfSound () inline private
Definition at line 580 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::altitude_flight_condition, atmosphereModel_, tudat::aerodynamics::FlightConditions::currentTime_, tudat::aerodynamics::FlightConditions::latitude_flight_condition, tudat::aerodynamics::FlightConditions::longitude_flight_condition, tudat::aerodynamics::FlightConditions::scalarFlightConditions_, tudat::aerodynamics::FlightConditions::speed_of_sound_flight_condition, and updateAtmosphereInput().
Referenced by getCurrentSpeedOfSound().
computeAirspeed()
void tudat::aerodynamics::AtmosphericFlightConditions::computeAirspeed () inline private
Definition at line 591 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::airspeed_flight_condition, tudat::aerodynamics::FlightConditions::currentBodyCenteredAirspeedBasedBodyFixedState_, and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by getCurrentAirspeed().
computeDynamicPressure()
void tudat::aerodynamics::AtmosphericFlightConditions::computeDynamicPressure () inline private
Definition at line 597 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::dynamic_pressure_condition, getCurrentAirspeed(), getCurrentDensity(), and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by getCurrentDynamicPressure().
computeAerodynamicHeatRate()
void tudat::aerodynamics::AtmosphericFlightConditions::computeAerodynamicHeatRate () inline private
Definition at line 605 of file flightConditions.h.
References tudat::aerodynamics::FlightConditions::aerodynamic_heat_rate, getCurrentAirspeed(), getCurrentDensity(), and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by getCurrentAerodynamicHeatRate().
computeMachNumber()
void tudat::aerodynamics::AtmosphericFlightConditions::computeMachNumber () inline private
Definition at line 613 of file flightConditions.h.
References getCurrentAirspeed(), getCurrentSpeedOfSound(), tudat::aerodynamics::FlightConditions::mach_number_flight_condition, and tudat::aerodynamics::FlightConditions::scalarFlightConditions_.
Referenced by getCurrentMachNumber().
updateAerodynamicCoefficientInput()
void tudat::aerodynamics::AtmosphericFlightConditions::updateAerodynamicCoefficientInput () private
Definition at line 214 of file flightConditions.cpp.
References aerodynamicCoefficientIndependentVariables_, aerodynamicCoefficientInterface_, controlSurfaceAerodynamicCoefficientIndependentVariables_, and getAerodynamicCoefficientIndependentVariable().
Referenced by getAerodynamicCoefficientIndependentVariables(), getControlSurfaceAerodynamicCoefficientIndependentVariables(), and updateConditions().
Member Data Documentation
atmosphereModel_
std::shared_ptr< aerodynamics::AtmosphereModel > tudat::aerodynamics::AtmosphericFlightConditions::atmosphereModel_ private
Definition at line 624 of file flightConditions.h.
Referenced by AtmosphericFlightConditions(), computeDensity(), computeFreestreamPressure(), computeSpeedOfSound(), computeTemperature(), and getAtmosphereModel().
aerodynamicCoefficientInterface_
std::shared_ptr< AerodynamicCoefficientInterface > tudat::aerodynamics::AtmosphericFlightConditions::aerodynamicCoefficientInterface_ private
Definition at line 627 of file flightConditions.h.
Referenced by getAerodynamicCoefficientIndependentVariables(), getAerodynamicCoefficientInterface(), getControlSurfaceAerodynamicCoefficientIndependentVariables(), updateAerodynamicCoefficientInput(), and updateConditions().
controlSurfaceDeflectionFunction_
std::function< double(const std::string&) > tudat::aerodynamics::AtmosphericFlightConditions::controlSurfaceDeflectionFunction_ private
Definition at line 630 of file flightConditions.h.
Referenced by getAerodynamicCoefficientIndependentVariable().
customCoefficientDependencies_
std::map< AerodynamicCoefficientsIndependentVariables, std::function< double() > > tudat::aerodynamics::AtmosphericFlightConditions::customCoefficientDependencies_ private
Definition at line 634 of file flightConditions.h.
Referenced by getAerodynamicCoefficientIndependentVariable(), and setAerodynamicCoefficientsIndependentVariableFunction().
updateLatitudeAndLongitudeForAtmosphere_
bool tudat::aerodynamics::AtmosphericFlightConditions::updateLatitudeAndLongitudeForAtmosphere_ private
Definition at line 637 of file flightConditions.h.
Referenced by AtmosphericFlightConditions(), and updateAtmosphereInput().
aerodynamicCoefficientIndependentVariables_
std::vector< double > tudat::aerodynamics::AtmosphericFlightConditions::aerodynamicCoefficientIndependentVariables_ private
Definition at line 641 of file flightConditions.h.
Referenced by getAerodynamicCoefficientIndependentVariables(), resetCurrentTime(), updateAerodynamicCoefficientInput(), and updateConditions().
controlSurfaceAerodynamicCoefficientIndependentVariables_
std::map< std::string, std::vector< double > > tudat::aerodynamics::AtmosphericFlightConditions::controlSurfaceAerodynamicCoefficientIndependentVariables_ private
List of independent variables of the control surface aerodynamic coefficient interface, with map key control surface identifiers.
Definition at line 645 of file flightConditions.h.
Referenced by getControlSurfaceAerodynamicCoefficientIndependentVariables(), resetCurrentTime(), updateAerodynamicCoefficientInput(), and updateConditions().
The documentation for this class was generated from the following files:
Astrodynamics/Aerodynamics/flightConditions.h
Astrodynamics/Aerodynamics/flightConditions.cpp