Tudat: tudat::transfer_trajectories::DepartureLegMga1DsmVelocity Class Reference
tudat::transfer_trajectories::DepartureLegMga1DsmVelocity Class Reference
Departure Leg class of an MGA-1DSM velocity formulation trajectory model.
#include <departureLegMga1DsmVelocity.h>
Public Member Functions
DepartureLegMga1DsmVelocity (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, const double departureBodyGravitationalParameter, const double semiMajorAxis, const double eccentricity, const double dsmTimeOfFlightFraction, const double excessVelocityMagnitude, const double excessVelocityInPlaneAngle, const double excessVelocityOutOfPlaneAngle, const bool includeDepartureDeltaV=true)
Constructor with immediate definition of parameters.
void calculateLeg (Eigen::Vector3d &velocityBeforeArrivalBody, double &deltaV)
Calculate the leg.
void intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, const double startingTime=0.)
Calculate intermediate positions and their corresponding times.
void maneuvers (std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, std::vector< double > &deltaVVector, const double startingTime=0.)
Return maneuvres along the leg.
void updateDefiningVariables (const Eigen::VectorXd &variableVector)
Update the defining variables.
Public Member Functions inherited from tudat::transfer_trajectories::DepartureLeg
DepartureLeg (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, const double departureBodyGravitationalParameter, const double semiMajorAxis, const double eccentricity, const bool includeDepartureDeltaV=true)
Constructor with immediate definition of parameters.
void getEscapeDeltaV (double &escapeDeltaV)
Function to retrieve the value of the escape Delta V.
Public Member Functions inherited from tudat::transfer_trajectories::SpaceLeg
SpaceLeg (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~SpaceLeg ()
void updateEphemeris (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const Eigen::Vector3d &departureBodyVelocity)
Update the ephemeris.
Public Member Functions inherited from tudat::transfer_trajectories::MissionLeg
MissionLeg (const Eigen::Vector3d &departureBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~MissionLeg ()
virtual destructor.
void returnDepartureVariables (Eigen::Vector3d &departureBodyPosition, Eigen::Vector3d &departureBodyVelocity, Eigen::Vector3d &velocityAfterDeparture)
Return Departure Variables.
Private Attributes
double deltaVDsm_
The deltaV of the DSM.
Eigen::Vector3d dsmLocation_
The DSM location.
double dsmTime_
The DSM time.
double dsmTimeOfFlightFraction_
The fraction of the time of flight of the DSM.
double excessVelocityInPlaneAngle_
The excess velocity in plane angle.
double excessVelocityMagnitude_
The excess velocity magnitude.
double excessVelocityOutOfPlaneAngle_
The excess velocity out of plane angle.
Eigen::Vector3d velocityAfterDsm_
The velocity after the DSM.
Eigen::Vector3d velocityBeforeDsm_
The velocity before the DSM.
Additional Inherited Members
Protected Attributes inherited from tudat::transfer_trajectories::DepartureLeg
double departureBodyGravitationalParameter_
The departure body gravitational parameter.
double eccentricity_
The eccentricity of the departure orbit.
double escapeDeltaV_
Double denoting the value of the escape Delta V.
bool includeDepartureDeltaV_
Boolean denoting whether to include the Delta V of arrival.
double semiMajorAxis_
The semi-major axis of the departure orbit.
Protected Attributes inherited from tudat::transfer_trajectories::SpaceLeg
Eigen::Vector3d arrivalBodyPosition_
The arrival body position.
Protected Attributes inherited from tudat::transfer_trajectories::MissionLeg
double centralBodyGravitationalParameter_
The central body gravitational parameter.
double deltaV_
The total deltaV of the leg.
Eigen::Vector3d departureBodyPosition_
The departure body position.
Eigen::Vector3d departureBodyVelocity_
The departure body velocity.
double timeOfFlight_
The time of flight.
Eigen::Vector3d velocityAfterDeparture_
The velocity after departure.
Detailed Description
A class that calculates the required impulses for a departure leg for an MGA-1DSM velocity formulation trajectory model. This model specifies the trajectory by defining the initial hyperbolic excess velocity (in 3D) and the moment of application of the DSM. The leg is split in two sublegs. The first subleg is analyzed using a kepler propagator, whereas the second leg is analyzed using a lambert targeter. Typically the user will be primarily interested in the total delta V and the arrival velocity of the spacecraft before the arrival planet.
Definition at line 42 of file departureLegMga1DsmVelocity.h.
Constructor & Destructor Documentation
DepartureLegMga1DsmVelocity()
tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::DepartureLegMga1DsmVelocity (const Eigen::Vector3d & departureBodyPosition, const Eigen::Vector3d & arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d & departureBodyVelocity, const double centralBodyGravitationalParameter, const double departureBodyGravitationalParameter, const double semiMajorAxis, const double eccentricity, const double dsmTimeOfFlightFraction, const double excessVelocityMagnitude, const double excessVelocityInPlaneAngle, const double excessVelocityOutOfPlaneAngle, const bool includeDepartureDeltaV = true) inline
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
Parameters
departureBodyPosition location of the departure body.
arrivalBodyPosition position of the target body.
timeOfFlight Length of the leg.
departureBodyVelocity velocity of the departure body.
centralBodyGravitationalParameter gravitational parameter of the cebtral body (most cases the Sun).
departureBodyGravitationalParameter gravitational parameter of the departure body.
semiMajorAxis semi-major axis of the orbit after the capture is performed.
eccentricity eccentricity of the orbit after the capture is performed.
dsmTimeOfFlightFraction the fraction of the TOF at which the DSM is performed.
excessVelocityMagnitude the magnitude of the hyperbolic excess velocity of the DSM.
excessVelocityInPlaneAngle the in plane angle of the hyperbolic excess velocity.
excessVelocityOutOfPlaneAngle the out of plane angle of the hyperbolic excess velocity.
includeDepartureDeltaV Boolean denoting whether to include the Delta V of departure.
Definition at line 64 of file departureLegMga1DsmVelocity.h.
References TUDAT_NAN, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
Member Function Documentation
calculateLeg()
void tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::calculateLeg (Eigen::Vector3d & velocityBeforeArrivalBody, double & deltaV) virtual
Calculate the leg and update the Delta V and the velocity before the next body.
Performs all calculations required for this leg.
Parameters
velocityBeforeArrivalBody the velocity of the spacecraft before it arrives at the target body.
deltaV the delta V required to perform the leg.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 20 of file departureLegMga1DsmVelocity.cpp.
References tudat::transfer_trajectories::SpaceLeg::arrivalBodyPosition_, tudat::json_interface::cartesianElements, tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::mission_segments::computeEscapeOrCaptureDeltaV(), tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::transfer_trajectories::MissionLeg::deltaV_, deltaVDsm_, tudat::transfer_trajectories::DepartureLeg::departureBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, tudat::transfer_trajectories::MissionLeg::departureBodyVelocity_, dsmLocation_, dsmTime_, dsmTimeOfFlightFraction_, tudat::transfer_trajectories::DepartureLeg::eccentricity_, tudat::transfer_trajectories::DepartureLeg::escapeDeltaV_, excessVelocityInPlaneAngle_, excessVelocityMagnitude_, excessVelocityOutOfPlaneAngle_, tudat::transfer_trajectories::DepartureLeg::includeDepartureDeltaV_, tudat::json_interface::keplerianElements, tudat::orbital_element_conversions::propagateKeplerOrbit(), tudat::transfer_trajectories::DepartureLeg::semiMajorAxis_, tudat::mission_segments::solveLambertProblemIzzo(), tudat::transfer_trajectories::MissionLeg::timeOfFlight_, tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_, velocityAfterDsm_, and velocityBeforeDsm_.
Referenced by intermediatePoints(), and maneuvers().
intermediatePoints()
void tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, const double startingTime = 0.) virtual
Calculates intermediate positions and their corresponding times in the leg, based on a maximum time between two points.
Parameters
maximumTimeStep the maximum time between two points along the trajectory.
positionVector Vector of positions along the orbit, space according to the maximum time step.
timeVector The times corresponding to the positions.
startingTime the initial time from which the intermediate points are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 91 of file departureLegMga1DsmVelocity.cpp.
References calculateLeg(), tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, dsmLocation_, dsmTime_, tudat::transfer_trajectories::returnTrajectory(), tudat::transfer_trajectories::MissionLeg::timeOfFlight_, tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_, and velocityAfterDsm_.
maneuvers()
void tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::maneuvers (std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, std::vector< double > & deltaVVector, const double startingTime = 0.) virtual
Returns the maneuver points, times and sizes along the trajectory.
Parameters
positionVector Vector of the positions of the maneuvers.
timeVector The times corresponding to the positions.
deltaVVector the delta V required for each maneuver.
startingTime the initial time from which the maneuvers are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 138 of file departureLegMga1DsmVelocity.cpp.
References calculateLeg(), deltaVDsm_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, dsmLocation_, dsmTime_, tudat::transfer_trajectories::DepartureLeg::escapeDeltaV_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
updateDefiningVariables()
void tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::updateDefiningVariables (const Eigen::VectorXd & variableVector) virtual
Sets the trajectory defining variables to the newly specified values. Required for re-using the class, without re-initializing it. For this leg: time of flight, DSM time of flight fraction, excess velocity magnitude, excess velocity in plane angle and the excess velocity out of plane angle.
Parameters
variableVector the new variable vector.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 168 of file departureLegMga1DsmVelocity.cpp.
References dsmTimeOfFlightFraction_, excessVelocityInPlaneAngle_, excessVelocityMagnitude_, excessVelocityOutOfPlaneAngle_, and tudat::transfer_trajectories::MissionLeg::timeOfFlight_.
Member Data Documentation
dsmTimeOfFlightFraction_
double tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::dsmTimeOfFlightFraction_ private
The fraction of the time of flight of the corresponding leg at which the DSM is performed.
Definition at line 147 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and updateDefiningVariables().
excessVelocityMagnitude_
double tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::excessVelocityMagnitude_ private
The magnitude of the relative velocity of the spacecraft leaving the departure planet with the departure planet.
Definition at line 154 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and updateDefiningVariables().
excessVelocityInPlaneAngle_
double tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::excessVelocityInPlaneAngle_ private
The rotation angle of the excess velocity in the xy-plane of the central reference frame.
Definition at line 160 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and updateDefiningVariables().
excessVelocityOutOfPlaneAngle_
double tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::excessVelocityOutOfPlaneAngle_ private
The rotation angle of the excess velocity in the z-direction of the central reference frame.
Definition at line 166 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and updateDefiningVariables().
dsmLocation_
Eigen::Vector3d tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::dsmLocation_ private
The position at which the deep space maneuver is performed.
Definition at line 172 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg(), intermediatePoints(), and maneuvers().
dsmTime_
double tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::dsmTime_ private
The time at which the deep space maneuver is performed.
Definition at line 178 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg(), intermediatePoints(), and maneuvers().
velocityBeforeDsm_
Eigen::Vector3d tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::velocityBeforeDsm_ private
The velocity of the spacecraft just before the deep space maneuver is performed.
Definition at line 184 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg().
velocityAfterDsm_
Eigen::Vector3d tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::velocityAfterDsm_ private
The velocity of the spacecraft just after the deep space maneuver is performed.
Definition at line 190 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and intermediatePoints().
deltaVDsm_
double tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::deltaVDsm_ private
The deltaV of the deep Space Maneuver.
Definition at line 196 of file departureLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and maneuvers().
The documentation for this class was generated from the following files:
Astrodynamics/TrajectoryDesign/departureLegMga1DsmVelocity.h
Astrodynamics/TrajectoryDesign/departureLegMga1DsmVelocity.cpp