Tudat: tudat::acceleration_partials::AerodynamicAccelerationPartial Class Reference
tudat::acceleration_partials::AerodynamicAccelerationPartial Class Reference
Class to calculate the partials of the aerodynamic acceleration w.r.t. parameters and states.
#include <aerodynamicAccelerationPartial.h>
Public Member Functions
AerodynamicAccelerationPartial (const boost::shared_ptr< aerodynamics::AerodynamicAcceleration > aerodynamicAcceleration, const boost::shared_ptr< aerodynamics::FlightConditions > flightConditions, const boost::function< Eigen::Vector6d() > vehicleStateGetFunction, const boost::function< void(const Eigen::Vector6d &) > vehicleStateSetFunction, const std::string acceleratedBody, const std::string acceleratingBody)
Constructor.
std::pair< boost::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter.
std::pair< boost::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter.
bool isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the acceleration is dependent on a non-translational integrated state.
void update (const double currentTime=TUDAT_NAN)
Function for updating partial w.r.t. the bodies' positions.
void wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration..
void wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body exerting acceleration..
void wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration..
void wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body exerting acceleration..
Public Member Functions inherited from tudat::acceleration_partials::AccelerationPartial
AccelerationPartial (const std::string &acceleratedBody, const std::string &acceleratingBody, const basic_astrodynamics::AvailableAcceleration accelerationType)
Base class constructor.
virtual ~AccelerationPartial ()
Virtual destructor.
std::string getAcceleratedBody ()
Function to retrieve the name of the body undergoing acceleration.
std::string getAcceleratingBody ()
Function to retrieve the name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration getAccelerationType ()
Function to retrieve the type of acceleration w.r.t. which partial is taken..
std::pair< boost::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
virtual bool isAccelerationPartialWrtAdditionalBodyNonNull (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the translational state of a third body is non-zero.
bool isStateDerivativeDependentOnIntegratedState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to check whether a partial w.r.t. some integrated state is non-zero.
virtual void wrtNonTranslationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the acceleration w.r.t. a non-translational integrated state.
virtual void wrtPositionOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of the third body.
void wrtStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body undergoing acceleration.
void wrtStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body exerting acceleration.
void wrtStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the third body.
virtual void wrtVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Protected Member Functions
void computeAccelerationPartialWrtCurrentDragCoefficient (Eigen::MatrixXd &accelerationPartial)
Function to compute the partial derivative of the acceleration w.r.t. the drag coefficient.
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Protected Attributes
boost::shared_ptr< aerodynamics::AerodynamicAcceleration > aerodynamicAcceleration_
Object that computes the aerodynamic acceleration.
Eigen::Vector6d bodyStatePerturbations_
Eigen::Matrix< double, 3, 6 > currentAccelerationStatePartials_
Partial derivative of aerodynamic acceleration w.r.t. current state, numerically computed by update function.
boost::shared_ptr< aerodynamics::FlightConditions > flightConditions_
boost::function< Eigen::Vector6d() > vehicleStateGetFunction_
Function to retrieve the state of the body undergoing the acceleration.
boost::function< void(const Eigen::Vector6d &) > vehicleStateSetFunction_
Function to set the state of the body undergoing the acceleration.
Protected Attributes inherited from tudat::acceleration_partials::AccelerationPartial
std::string acceleratedBody_
Name of the body undergoing acceleration.
std::string acceleratingBody_
Name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration accelerationType_
Type of acceleration w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, boost::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, boost::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, boost::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, boost::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Class to calculate the partials of the aerodynamic acceleration w.r.t. parameters and states. Note that the state partials are computed numerically by 2nd-order central difference with perturbations hard-coded in the constructor
Definition at line 31 of file aerodynamicAccelerationPartial.h.
Constructor & Destructor Documentation
tudat::acceleration_partials::AerodynamicAccelerationPartial::AerodynamicAccelerationPartial (const boost::shared_ptr< aerodynamics::AerodynamicAcceleration > aerodynamicAcceleration, const boost::shared_ptr< aerodynamics::FlightConditions > flightConditions, const boost::function< Eigen::Vector6d() > vehicleStateGetFunction, const boost::function< void(const Eigen::Vector6d &) > vehicleStateSetFunction, const std::string acceleratedBody, const std::string acceleratingBody) inline
Constructor
Parameters
aerodynamicAcceleration Object that computes the aerodynamic acceleration
flightConditions Object that computes the current atmospheric and flight conditions, as well as associated angles, for the body undergoing acceleration
vehicleStateGetFunction Function to retrieve the state of the body undergoing the acceleration.
vehicleStateSetFunction Function to set the state of the body undergoing the acceleration.
acceleratedBody Body undergoing acceleration.
acceleratingBody Body exerting acceleration.
Definition at line 46 of file aerodynamicAccelerationPartial.h.
References bodyStatePerturbations_.
Member Function Documentation
void tudat::acceleration_partials::AerodynamicAccelerationPartial::wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 71 of file aerodynamicAccelerationPartial.h.
References currentAccelerationStatePartials_.
void tudat::acceleration_partials::AerodynamicAccelerationPartial::wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian velocity of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 96 of file aerodynamicAccelerationPartial.h.
References currentAccelerationStatePartials_.
void tudat::acceleration_partials::AerodynamicAccelerationPartial::wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body exerting acceleration and adding it to the existing partial block. The update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 121 of file aerodynamicAccelerationPartial.h.
References currentAccelerationStatePartials_.
void tudat::acceleration_partials::AerodynamicAccelerationPartial::wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body exerting acceleration and adding it to the existing partial block. The update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 145 of file aerodynamicAccelerationPartial.h.
References currentAccelerationStatePartials_.
bool tudat::acceleration_partials::AerodynamicAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline virtual
Function for determining if the acceleration is dependent on a non-translational integrated state. No dependency is implemented, but a warning is provided if partial w.r.t. mass of body exerting acceleration (and undergoing acceleration if mutual attraction is used) is requested.
Parameters
stateReferencePoint Reference point id of propagated state
integratedStateType Type of propagated state for which dependency is to be determined.
Returns
True if dependency exists (non-zero partial), false otherwise.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 167 of file aerodynamicAccelerationPartial.h.
References tudat::acceleration_partials::AccelerationPartial::acceleratedBody_, tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, and tudat::propagators::body_mass_state.
std::pair< boost::function< void(Eigen::MatrixXd&) >, int > tudat::acceleration_partials::AerodynamicAccelerationPartial::getParameterPartialFunction (boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) inline virtual
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency, 1 otherwise).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 188 of file aerodynamicAccelerationPartial.h.
References tudat::acceleration_partials::AccelerationPartial::acceleratedBody_, computeAccelerationPartialWrtCurrentDragCoefficient(), and tudat::estimatable_parameters::constant_drag_coefficient.
std::pair< boost::function< void(Eigen::MatrixXd&) >, int > tudat::acceleration_partials::AerodynamicAccelerationPartial::getParameterPartialFunction (boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) inline virtual
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 217 of file aerodynamicAccelerationPartial.h.
References TUDAT_NAN, and update().
void tudat::acceleration_partials::AerodynamicAccelerationPartial::update (const double currentTime = TUDAT_NAN) virtual
Function for updating common blocks of partial to current state. The partial of the acceleration w.r.t. the current state (in inertial frame) is computed numerically.
Parameters
currentTime Time at which partials are to be calculated
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 21 of file aerodynamicAccelerationPartial.cpp.
References aerodynamicAcceleration_, bodyStatePerturbations_, currentAccelerationStatePartials_, flightConditions_, TUDAT_NAN, vehicleStateGetFunction_, and vehicleStateSetFunction_.
Referenced by getParameterPartialFunction().
void tudat::acceleration_partials::AerodynamicAccelerationPartial::computeAccelerationPartialWrtCurrentDragCoefficient (Eigen::MatrixXd & accelerationPartial) inline protected
Definition at line 235 of file aerodynamicAccelerationPartial.h.
References tudat::reference_frames::aerodynamic_frame, aerodynamicAcceleration_, flightConditions_, and tudat::reference_frames::inertial_frame.
Referenced by getParameterPartialFunction().
Member Data Documentation
Eigen::Vector6d tudat::acceleration_partials::AerodynamicAccelerationPartial::bodyStatePerturbations_ protected
Perturbations of Cartesian state used in the numerical (central difference) computation of currentAccelerationStatePartials_
Definition at line 252 of file aerodynamicAccelerationPartial.h.
Referenced by AerodynamicAccelerationPartial(), and update().
Eigen::Matrix< double, 3, 6 > tudat::acceleration_partials::AerodynamicAccelerationPartial::currentAccelerationStatePartials_ protected
Definition at line 255 of file aerodynamicAccelerationPartial.h.
Referenced by update(), wrtPositionOfAcceleratedBody(), wrtPositionOfAcceleratingBody(), wrtVelocityOfAcceleratedBody(), and wrtVelocityOfAcceleratingBody().
boost::shared_ptr< aerodynamics::AerodynamicAcceleration > tudat::acceleration_partials::AerodynamicAccelerationPartial::aerodynamicAcceleration_ protected
Definition at line 258 of file aerodynamicAccelerationPartial.h.
Referenced by computeAccelerationPartialWrtCurrentDragCoefficient(), and update().
boost::shared_ptr< aerodynamics::FlightConditions > tudat::acceleration_partials::AerodynamicAccelerationPartial::flightConditions_ protected
Object that computes the current atmospheric and flight conditions, as well as associated angles, for the body undergoing acceleration
Definition at line 262 of file aerodynamicAccelerationPartial.h.
Referenced by computeAccelerationPartialWrtCurrentDragCoefficient(), and update().
boost::function< Eigen::Vector6d() > tudat::acceleration_partials::AerodynamicAccelerationPartial::vehicleStateGetFunction_ protected
Definition at line 265 of file aerodynamicAccelerationPartial.h.
Referenced by update().
boost::function< void(const Eigen::Vector6d&) > tudat::acceleration_partials::AerodynamicAccelerationPartial::vehicleStateSetFunction_ protected
Definition at line 268 of file aerodynamicAccelerationPartial.h.
Referenced by update().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/AccelerationPartials/aerodynamicAccelerationPartial.h
Astrodynamics/OrbitDetermination/AccelerationPartials/aerodynamicAccelerationPartial.cpp