Tudat: Astrodynamics/CMakeLists.txt File Reference
Astrodynamics/CMakeLists.txt File Reference
Functions
EarthOrientation endif () add_subdirectory("$
Propulsion if (USE_SOFA) set(EARTHORIENTATIONDIR"$
set (AERODYNAMICSDIR"${ASTRODYNAMICSDIR}/Aerodynamics") set(BASICASTRODYNAMICSDIR"$
BasicAstrodynamics set (ELECTROMAGNETISMDIR"${ASTRODYNAMICSDIR}/ElectroMagnetism") set(EPHEMERIDESDIR"$
Ephemerides set (GRAVITATIONDIR"${ASTRODYNAMICSDIR}/Gravitation") set(GROUNDSTATIONSDIR"$
GroundStations set (MISSIONSEGMENTSDIR"${ASTRODYNAMICSDIR}/MissionSegments") set(REFERENCEFRAMESDIR"$
ReferenceFrames set (OBSERVATIONMODELSDIR"${ASTRODYNAMICSDIR}/ObservationModels") set(ORBITDETERMINATIONDIR"$
OrbitDetermination set (PROPAGATORSDIR"${ASTRODYNAMICSDIR}/Propagators") set(RELATIVITYDIR"$
Relativity set (SYSTEMMODELSDIR"${ASTRODYNAMICSDIR}/SystemModels") set(PROPULSIONDIR"$
Function Documentation
set (AERODYNAMICSDIR"${ASTRODYNAMICSDIR}/Aerodynamics")
Definition at line 13 of file CMakeLists.txt.
BasicAstrodynamics set (ELECTROMAGNETISMDIR"${ASTRODYNAMICSDIR}/ElectroMagnetism")
Definition at line 15 of file CMakeLists.txt.
Ephemerides set (GRAVITATIONDIR"${ASTRODYNAMICSDIR}/Gravitation")
Definition at line 17 of file CMakeLists.txt.
GroundStations set (MISSIONSEGMENTSDIR"${ASTRODYNAMICSDIR}/MissionSegments")
Definition at line 19 of file CMakeLists.txt.
ReferenceFrames set (OBSERVATIONMODELSDIR"${ASTRODYNAMICSDIR}/ObservationModels")
Definition at line 21 of file CMakeLists.txt.
OrbitDetermination set (PROPAGATORSDIR"${ASTRODYNAMICSDIR}/Propagators")
Definition at line 23 of file CMakeLists.txt.
Relativity set (SYSTEMMODELSDIR"${ASTRODYNAMICSDIR}/SystemModels")
Definition at line 25 of file CMakeLists.txt.
Propulsion if (USE_SOFA)
Definition at line 27 of file CMakeLists.txt.
Referenced by SearchBox(), and SearchResults().
EarthOrientation endif ()
Definition at line 29 of file CMakeLists.txt.
Referenced by cmake_minimum_required(), and set().