Tudat: tudat::observation_partials::PositionPartialScaling Class Reference
tudat::observation_partials::PositionPartialScaling Class Reference abstract
Base class for scaling position partials to observable partials.
#include <observationPartial.h>
Public Member Functions
virtual ~PositionPartialScaling ()
Destructor.
virtual void update (const std::vector< Eigen::Vector6d > &linkEndStates, const std::vector< double > &times, const observation_models::LinkEndType fixedLinkEnd, const Eigen::VectorXd currentObservation)=0
Update the scaling object to the current times and states (pure virtual).
Detailed Description
Base class for scaling position partials to observable partials. For observables computed from the three-dimensional positions of reference points, the partial derivatives are computed from the partials of these positions. Each observation model requires a specific derived class of PositionPartialScaling, that computes how position partials are converted to ('scaled to') observable partials
Definition at line 43 of file observationPartial.h.
Constructor & Destructor Documentation
virtual tudat::observation_partials::PositionPartialScaling::~PositionPartialScaling () inline virtual
Definition at line 48 of file observationPartial.h.
References update().
Member Function Documentation
virtual void tudat::observation_partials::PositionPartialScaling::update (const std::vector< Eigen::Vector6d > & linkEndStates, const std::vector< double > & times, const observation_models::LinkEndType fixedLinkEnd, const Eigen::VectorXd currentObservation) pure virtual
Update the scaling object to the current times and states (pure virtual).
Parameters
linkEndStates List of states at each link end during observation.
times List of times at each link end during observation.
fixedLinkEnd Link end at which observation time is defined, i.e. link end for which associated time is kept constant when computing observable.
currentObservation Value of observation for which partial scaling is to be computed
Implemented in tudat::observation_partials::PositionObservationScaling, tudat::observation_partials::OneWayDopplerScaling, tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling, tudat::observation_partials::AngularPositionScaling, tudat::observation_partials::NWayRangeScaling, tudat::observation_partials::OneWayRangeRateScaling, and tudat::observation_partials::OneWayRangeScaling.
Referenced by tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::OneWayDopplerDirectFirstOrderProperTimeComponentScaling(), tudat::observation_partials::OneWayDopplerScaling::~OneWayDopplerScaling(), and ~PositionPartialScaling().
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/ObservationPartials/observationPartial.h