Tudat: tudat::Time Class Reference
tudat::Time Class Reference
Class for defining time with a resolution that is sub-fs for very long periods of time.
#include <timeType.h>
Public Member Functions
Time ()
Constructor, initialize time to 0.
Time (const int fullPeriods, const long double secondsIntoFullPeriod)
Constructor, sets current hour and time into current hour directly.
Time (const long double numberOfSeconds)
Constructor, sets number of seconds since epoch (with long double representation as input)
Time (const double secondsIntoFullPeriod)
Constructor, sets number of seconds since epoch (with double representation as input)
Time (const int secondsIntoFullPeriod)
Constructor, sets number of seconds since epoch (with int representation as input)
Time (const Time &otherTime)
Copy constructor.
int getFullPeriods () const
Function to get the number of full hours since epoch.
template<typename ScalarType >
ScalarType getSeconds () const
Function to get the total seconds since epoch, in templated precision.
long double getSecondsIntoFullPeriod () const
Function to get the number of seconds into current hour.
operator double () const
Function to get the total seconds since epoch, in int precision (cast of Time to double)
operator int () const
Function to get the total seconds since epoch, in int precision (cast of Time to int)
operator long double () const
Function to get the total seconds since epoch, in int precision (cast of Time to long sdouble)
void operator*= (const double timeToMultiply)
Multiply and assign operator for multiplying by double.
void operator*= (const long double timeToMultiply)
Multiply and assign operator for multiplying by long double.
void operator+= (const Time &timeToAdd)
Add and assign operator for adding a Time.
void operator+= (const double timeToAdd)
Add and assign operator for adding a double.
void operator+= (const long double timeToAdd)
Add and assign operator for adding a double.
void operator-= (const Time &timeToSubtract)
Subtract and assign operator for adding a Time.
void operator-= (const double timeToSubtract)
Subtract and assign operator for adding a double.
void operator-= (const long double timeToSubtract)
Subtract and assign operator for adding a long double.
void operator/= (const double timeToDivide)
Divided and assign operator for dividing by double.
void operator/= (const long double timeToDivide)
Divided and assign operator for dividing by long double.
Time & operator= (const Time &timeToCopy)
Definition of = operator for Time type.
Protected Member Functions
void normalizeMembers ()
Function to renormalize the members of the Time object, so that secondsIntoFullPeriod_ is between 0 and 3600.
Protected Attributes
int daysToAdd
Pre-declared variable used in often-called normalizeMembers function.
int fullPeriods_
Number of full hours since epoch.
long double secondsIntoFullPeriod_
Number of seconds into current hour.
Friends
bool operator!= (const Time &timeToCompare1, const Time &timeToCompare2)
Inequality operator for two Time objects.
bool operator!= (const Time &timeToCompare1, const double timeToCompare2)
Inequality operator for a Time object with a double.
bool operator!= (const double timeToCompare1, const Time &timeToCompare2)
Inequality operator for a Time object with a double.
bool operator!= (const Time &timeToCompare1, const long double timeToCompare2)
Inequality operator for a Time object with a long double.
bool operator!= (const long double timeToCompare1, const Time &timeToCompare2)
Inequality operator for a Time object with a long double.
Time operator* (const long double timeToMultiply1, const Time &timeToMultiply2)
Multiplication operator of a long double with a Time object (i.e. to rescale time)
Time operator* (const Time &timeToMultiply1, const long double timeToMultiply2)
Multiplication operator of a long double with a Time object (i.e. to rescale time)
Time operator* (const double timeToMultiply1, const Time &timeToMultiply2)
Multiplication operator of a double with a Time object (i.e. to rescale time)
Time operator* (const Time &timeToMultiply1, const double timeToMultiply2)
Multiplication operator of a double with a Time object (i.e. to rescale time)
Time operator+ (const Time &timeToAdd1, const Time &timeToAdd2)
Addition operator for two Time objects.
Time operator+ (const double &timeToAdd1, const Time &timeToAdd2)
Addition operator for double variable with Time object.
Time operator+ (const long double &timeToAdd1, const Time &timeToAdd2)
Addition operator for long double variable with Time object.
Time operator+ (const Time &timeToAdd2, const double &timeToAdd1)
Addition operator for Time object with double variable.
Time operator+ (const Time &timeToAdd2, const long double &timeToAdd1)
Addition operator for Time object with long double variable.
Time operator- (const Time &timeToSubtract1, const Time &timeToSubtract2)
Subtraction operator for two Time objects.
Time operator- (const Time &timeToSubtract1, const double timeToSubtract2)
Subtraction operator for double from Time object.
Time operator- (const Time &timeToSubtract1, const long double timeToSubtract2)
Subtraction operator for double from Time object.
Time operator- (const double timeToSubtract1, const Time &timeToSubtract2)
Subtraction operator for Time object from double.
Time operator- (const long double timeToSubtract1, const Time &timeToSubtract2)
Subtraction operator for Time object from long double.
const Time operator/ (const Time &original, const double doubleToDivideBy)
Division operator of a Time object with a double (i.e. to rescale time)
const Time operator/ (const Time &original, const long double doubleToDivideBy)
Division operator of a Time object with a long double (i.e. to rescale time)
bool operator< (const Time &timeToCompare1, const Time &timeToCompare2)
Smaller-than operator for two Time objects.
bool operator< (const Time &timeToCompare1, const double timeToCompare2)
Smaller-than operator for Time object with double.
bool operator< (const Time &timeToCompare1, const long double timeToCompare2)
Smaller-than operator for Time object with long double.
bool operator< (const double timeToCompare1, const Time &timeToCompare2)
Smaller-than operator for Time object with double.
bool operator< (const long double timeToCompare1, const Time &timeToCompare2)
Smaller-than operator for Time object with long double.
std::ostream & operator<< (std::ostream &stream, const Time &timeToPrint)
Output operator for Time object.
bool operator<= (const Time &timeToCompare1, const Time &timeToCompare2)
Smaller-than-or-equal-to operator for two Time objects.
bool operator<= (const Time &timeToCompare1, const double timeToCompare2)
Smaller-than-or-equal operator for Time object with double.
bool operator<= (const Time &timeToCompare1, const long double timeToCompare2)
Smaller-than-or-equal operator for Time object with long double.
bool operator<= (const double timeToCompare1, const Time &timeToCompare2)
Smaller-than-or-equal operator for Time object with double.
bool operator<= (const long double timeToCompare1, const Time &timeToCompare2)
Smaller-than-or-equal operator for Time object with long double.
bool operator== (const Time &timeToCompare1, const Time &timeToCompare2)
Equality operator for two Time objects.
bool operator== (const Time &timeToCompare1, const int timeToCompare2)
Equality operator for a Time object with an integer.
bool operator== (const Time &timeToCompare1, const double timeToCompare2)
Equality operator for a Time object with a double.
bool operator== (const double timeToCompare1, const Time &timeToCompare2)
Equality operator for a Time object with a double.
bool operator== (const Time &timeToCompare1, const long double timeToCompare2)
Equality operator for a Time object with a long double.
bool operator== (const long double timeToCompare1, const Time &timeToCompare2)
Equality operator for a Time object with a long double.
bool operator> (const Time &timeToCompare1, const Time &timeToCompare2)
Greater-than operator for two Time objects.
bool operator> (const Time &timeToCompare1, const double timeToCompare2)
Greater-than operator for Time object with double.
bool operator> (const Time &timeToCompare1, const long double timeToCompare2)
Greater-than operator for Time object with long double.
bool operator> (const double timeToCompare1, const Time &timeToCompare2)
Greater-than operator for Time object with double.
bool operator> (const long double timeToCompare1, const Time &timeToCompare2)
Greater-than operator for Time object with long double.
bool operator>= (const Time &timeToCompare1, const Time &timeToCompare2)
Greater-than-or-equal-to operator for two Time objects.
bool operator>= (const Time &timeToCompare1, const double timeToCompare2)
Greater-than-or-equal operator for Time object with double.
bool operator>= (const Time &timeToCompare1, const long double timeToCompare2)
Greater-than-or-equal operator for Time object with long double.
bool operator>= (const double timeToCompare1, const Time &timeToCompare2)
Greater-than-or-equal operator for Time object with double.
bool operator>= (const long double timeToCompare1, const Time &timeToCompare2)
Greater-than-or-equal operator for Time object with long double.
Detailed Description
Class for defining time with a resolution that is sub-fs for very long periods of time. Using double or long double precision as a representation of time, the issue of reduced quality will occur that over long time-period. For instance, over a period of 10^8 seconds (about 3 years), double and long double representations have resolution of about 10^-8 and 10^-11 s respectively, which is insufficient for various applications. This type uses an int to represent the number of hours since an epoch, and long double to represent the number of seconds into the present hour. This provides a resulution of < 1 femtosecond, over a range of 2147483647 hours (about 300,000 years), which is more than sufficient for practical applications.
Definition at line 36 of file timeType.h.
Constructor & Destructor Documentation
Time() [1/6]
tudat::Time::Time () inline
Definition at line 41 of file timeType.h.
Time() [2/6]
tudat::Time::Time (const int fullPeriods, const long double secondsIntoFullPeriod) inline
Constructor, sets current hour and time into current hour directly
Parameters
fullPeriods Number of full hours since epoch
secondsIntoFullPeriod Number of seconds into current hour. Note that this value need not be in the range between 0 and 3600: the time representation is normalized upon construction to ensure that the internal representation is in this range.
Definition at line 51 of file timeType.h.
References normalizeMembers().
Time() [3/6]
tudat::Time::Time (const long double numberOfSeconds) inline
Constructor, sets number of seconds since epoch (with long double representation as input)
Parameters
numberOfSeconds Number of seconds since epoch.
Definition at line 62 of file timeType.h.
References normalizeMembers().
Time() [4/6]
tudat::Time::Time (const double secondsIntoFullPeriod) inline
Constructor, sets number of seconds since epoch (with double representation as input)
Parameters
secondsIntoFullPeriod Number of seconds since epoch.
Definition at line 73 of file timeType.h.
References normalizeMembers().
Time() [5/6]
tudat::Time::Time (const int secondsIntoFullPeriod) inline
Constructor, sets number of seconds since epoch (with int representation as input)
Parameters
secondsIntoFullPeriod Number of seconds since epoch.
Definition at line 84 of file timeType.h.
References normalizeMembers().
Time() [6/6]
tudat::Time::Time (const Time & otherTime) inline
Copy constructor
Parameters
otherTime Time that is to be copied.
Definition at line 95 of file timeType.h.
References normalizeMembers().
Member Function Documentation
operator=()
Time& tudat::Time::operator= (const Time & timeToCopy) inline
Definition of = operator for Time type
Parameters
timeToCopy Time that is to be copied by operator
Returns
Assigned Time object
Definition at line 107 of file timeType.h.
References fullPeriods_, normalizeMembers(), and secondsIntoFullPeriod_.
operator+=() [1/3]
void tudat::Time::operator+= (const Time & timeToAdd) inline
Add and assign operator for adding a Time
Parameters
timeToAdd Time that is to be added
Definition at line 364 of file timeType.h.
References fullPeriods_, normalizeMembers(), and secondsIntoFullPeriod_.
operator+=() [2/3]
void tudat::Time::operator+= (const double timeToAdd) inline
Add and assign operator for adding a double
Parameters
timeToAdd Time that is to be added (in double representation)
Definition at line 376 of file timeType.h.
References normalizeMembers(), and secondsIntoFullPeriod_.
operator+=() [3/3]
void tudat::Time::operator+= (const long double timeToAdd) inline
Add and assign operator for adding a double
Parameters
timeToAdd Time that is to be added (in long double representation)
Definition at line 387 of file timeType.h.
References normalizeMembers(), and secondsIntoFullPeriod_.
operator-=() [1/3]
void tudat::Time::operator-= (const Time & timeToSubtract) inline
Subtract and assign operator for subtracting a Time
Parameters
timeToSubtract Time that is to be subtracted
Definition at line 398 of file timeType.h.
References fullPeriods_, normalizeMembers(), and secondsIntoFullPeriod_.
operator-=() [2/3]
void tudat::Time::operator-= (const double timeToSubtract) inline
Subtract and assign operator for subtracting a double
Parameters
timeToSubtract Time that is to be subtracted (in double representation)
Definition at line 410 of file timeType.h.
References normalizeMembers(), and secondsIntoFullPeriod_.
operator-=() [3/3]
void tudat::Time::operator-= (const long double timeToSubtract) inline
Subtract and assign operator for subtracting a long double
Parameters
timeToSubtract Time that is to be subtracted (in long double representation)
Definition at line 421 of file timeType.h.
References normalizeMembers(), and secondsIntoFullPeriod_.
operator*=() [1/2]
void tudat::Time::operator*= (const double timeToMultiply) inline
Multiply and assign operator for multiplying by a double
Parameters
timeToMultiply Value by which time is to be multiplied (in double representation)
Definition at line 432 of file timeType.h.
References fullPeriods_, normalizeMembers(), secondsIntoFullPeriod_, and tudat::TIME_NORMALIZATION_TERM.
operator*=() [2/2]
void tudat::Time::operator*= (const long double timeToMultiply) inline
Multiply and assign operator for multiplying by a long double
Parameters
timeToMultiply Value by which time is to be multiplied (in long double representation)
Definition at line 449 of file timeType.h.
References fullPeriods_, normalizeMembers(), secondsIntoFullPeriod_, and tudat::TIME_NORMALIZATION_TERM.
operator/=() [1/2]
void tudat::Time::operator/= (const double timeToDivide) inline
Divided and assign operator for dividing by double
Parameters
timeToDivide Value by which time is to be divided (in double representation)
Definition at line 466 of file timeType.h.
References fullPeriods_, normalizeMembers(), and secondsIntoFullPeriod_.
operator/=() [2/2]
void tudat::Time::operator/= (const long double timeToDivide) inline
Divided and assign operator for dividing by long double
Parameters
timeToDivide Value by which time is to be divided (in long double representation)
Definition at line 483 of file timeType.h.
References fullPeriods_, normalizeMembers(), and secondsIntoFullPeriod_.
getSeconds()
template<typename ScalarType > ScalarType tudat::Time::getSeconds () const inline
Function to get the total seconds since epoch, in templated precision
Returns
Total seconds since epoch.
Definition at line 939 of file timeType.h.
References fullPeriods_, secondsIntoFullPeriod_, and tudat::TIME_NORMALIZATION_TERM.
Referenced by tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getCartesianLongStateFromExtendedTime(), tudat::ephemerides::Ephemeris::getCartesianLongStateFromExtendedTime(), tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getCartesianStateFromExtendedTime(), tudat::ephemerides::Ephemeris::getCartesianStateFromExtendedTime(), tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToBaseFrameFromExtendedTime(), tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToTargetFrameFromExtendedTime(), tudat::ephemerides::RotationalEphemeris::getRotationToBaseFrameFromExtendedTime(), and tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrameFromExtendedTime().
operator int()
tudat::Time::operator int () const inline
Function to get the total seconds since epoch, in int precision (cast of Time to int)
Returns
Total seconds int epoch.
Definition at line 950 of file timeType.h.
operator double()
tudat::Time::operator double () const inline
Function to get the total seconds since epoch, in int precision (cast of Time to double)
Returns
Total seconds int epoch.
Definition at line 960 of file timeType.h.
operator long double()
tudat::Time::operator long double () const inline
Function to get the total seconds since epoch, in int precision (cast of Time to long double)
Returns
Total seconds int epoch.
Definition at line 970 of file timeType.h.
getFullPeriods()
int tudat::Time::getFullPeriods () const inline
Function to get the number of full hours since epoch
Returns
Number of full hours since epoch
Definition at line 980 of file timeType.h.
References fullPeriods_.
getSecondsIntoFullPeriod()
long double tudat::Time::getSecondsIntoFullPeriod () const inline
Function to get the number of seconds into current hour
Returns
Definition at line 990 of file timeType.h.
References secondsIntoFullPeriod_.
normalizeMembers()
void tudat::Time::normalizeMembers () inline protected
Definition at line 998 of file timeType.h.
References daysToAdd, fullPeriods_, secondsIntoFullPeriod_, and tudat::TIME_NORMALIZATION_TERM.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), operator=(), and Time().
Friends And Related Function Documentation
operator+ [1/5]
Time operator+ (const Time & timeToAdd1, const Time & timeToAdd2) friend
Addition operator for two Time objects
Parameters
timeToAdd1 First time that is to be added.
timeToAdd2 Second time that is to be added.
Returns
Input arguments, added together
Definition at line 130 of file timeType.h.
operator+ [2/5]
Time operator+ (const double & timeToAdd1, const Time & timeToAdd2) friend
Addition operator for two Time objects
Parameters
timeToAdd1 First time that is to be added (as a double).
timeToAdd2 Second time that is to be added (as a Time object).
Returns
Input arguments, added together as Time object.
Definition at line 143 of file timeType.h.
operator+ [3/5]
Time operator+ (const long double & timeToAdd1, const Time & timeToAdd2) friend
Addition operator for two Time objects
Parameters
timeToAdd1 First time that is to be added (as a long double).
timeToAdd2 Second time that is to be added (as a Time object).
Returns
Input arguments, added together as Time object.
Definition at line 155 of file timeType.h.
operator+ [4/5]
Time operator+ (const Time & timeToAdd2, const double & timeToAdd1) friend
Addition operator for two Time objects
Parameters
timeToAdd1 First time that is to be added (as Time object).
timeToAdd2 Second time that is to be added (as a double).
Returns
Input arguments, added together as Time object.
Definition at line 167 of file timeType.h.
operator+ [5/5]
Time operator+ (const Time & timeToAdd2, const long double & timeToAdd1) friend
Addition operator for two Time objects
Parameters
timeToAdd1 First time that is to be added (as Time object).
timeToAdd2 Second time that is to be added (as a long double).
Returns
Input arguments, added together as Time object.
Definition at line 179 of file timeType.h.
operator- [1/5]
Time operator- (const Time & timeToSubtract1, const Time & timeToSubtract2) friend
Addition operator for two Time objects
Parameters
timeToSubtract1 Time from which second time is to be subtracted
timeToSubtract2 Time that is to be subtracted from first input
Returns
Input arguments, subtracted from one another
Definition at line 193 of file timeType.h.
operator- [2/5]
Time operator- (const Time & timeToSubtract1, const double timeToSubtract2) friend
Addition operator for two Time objects
Parameters
timeToSubtract1 Time from which second time is to be subtracted (as a Time object)
timeToSubtract2 Time that is to be subtracted from first input (as a double)
Returns
Input arguments, subtracted from one another
Definition at line 207 of file timeType.h.
operator- [3/5]
Time operator- (const Time & timeToSubtract1, const long double timeToSubtract2) friend
Addition operator for two Time objects
Parameters
timeToSubtract1 Time from which second time is to be subtracted (as a Time object)
timeToSubtract2 Time that is to be subtracted from first input (as a long double)
Returns
Input arguments, subtracted from one another
Definition at line 220 of file timeType.h.
operator- [4/5]
Time operator- (const double timeToSubtract1, const Time & timeToSubtract2) friend
Addition operator for two Time objects
Parameters
timeToSubtract1 Time from which second time is to be subtracted (as a double)
timeToSubtract2 Time that is to be subtracted from first input (as a Time object)
Returns
Input arguments, subtracted from one another
Definition at line 232 of file timeType.h.
operator- [5/5]
Time operator- (const long double timeToSubtract1, const Time & timeToSubtract2) friend
Addition operator for two Time objects
Parameters
timeToSubtract1 Time from which second time is to be subtracted (as a long double)
timeToSubtract2 Time that is to be subtracted from first input (as a Time object)
Returns
Input arguments, subtracted from one another
Definition at line 245 of file timeType.h.
operator* [1/4]
Time operator* (const long double timeToMultiply1, const Time & timeToMultiply2) friend
Multiplication operator of a long double with a Time object (i.e. to rescale time)
Parameters
timeToMultiply1 Value by which Time is to be multiplied
timeToMultiply2 Time that is to be multiplied by first input argument
Returns
Multiplied Time object.
Definition at line 258 of file timeType.h.
operator* [2/4]
Time operator* (const Time & timeToMultiply1, const long double timeToMultiply2) friend
Multiplication operator of a long double with a Time object (i.e. to rescale time)
Parameters
timeToMultiply1 Time that is to be multiplied by second input argument
timeToMultiply2 Value by which Time is to be multiplied
Returns
Multiplied Time object.
Definition at line 277 of file timeType.h.
operator* [3/4]
Time operator* (const double timeToMultiply1, const Time & timeToMultiply2) friend
Multiplication operator of a double with a Time object (i.e. to rescale time)
Parameters
timeToMultiply1 Value by which Time is to be multiplied
timeToMultiply2 Time that is to be multiplied by first input argument
Returns
Multiplied Time object.
Definition at line 289 of file timeType.h.
operator* [4/4]
Time operator* (const Time & timeToMultiply1, const double timeToMultiply2) friend
Multiplication operator of a double with a Time object (i.e. to rescale time)
Parameters
timeToMultiply1 Time that is to be multiplied by second input argument
timeToMultiply2 Value by which Time is to be multiplied
Returns
Multiplied Time object.
Definition at line 310 of file timeType.h.
operator/ [1/2]
const Time operator/ (const Time & original, const double doubleToDivideBy) friend
Division operator of a Time object with a double (i.e. to rescale time)
Parameters
original Time that is to be divided by second input argument
doubleToDivideBy Value by which first argument is to be divided.
Returns
Divided Time object.
Definition at line 322 of file timeType.h.
operator/ [2/2]
const Time operator/ (const Time & original, const long double doubleToDivideBy) friend
Division operator of a Time object with a long double (i.e. to rescale time)
Parameters
original Time that is to be divided by second input argument
doubleToDivideBy Value by which first argument is to be divided.
Returns
Divided Time object.
Definition at line 345 of file timeType.h.
operator== [1/6]
bool operator== (const Time & timeToCompare1, const Time & timeToCompare2) friend
Equality operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare
Returns
True if two times are fully equal; false if not.
Definition at line 503 of file timeType.h.
operator!= [1/5]
bool operator!= (const Time & timeToCompare1, const Time & timeToCompare2) friend
Inqquality operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare
Returns
False if two times are fully equal; true if not.
Definition at line 516 of file timeType.h.
operator== [2/6]
bool operator== (const Time & timeToCompare1, const int timeToCompare2) friend
Equality operator for a Time object with an integer. Comparison is performed at double precision (i.e. integer is cast to double and compared).
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (in integer precision)
Returns
True if two times are fully equal; false if not.
Definition at line 529 of file timeType.h.
operator== [3/6]
bool operator== (const Time & timeToCompare1, const double timeToCompare2) friend
Equality operator for a Time object with a double. Comparison is performed at double precision (i.e. Time is cast to double and compared)
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (in double precision)
Returns
True if two times are fully equal; false if not.
Definition at line 542 of file timeType.h.
operator== [4/6]
bool operator== (const double timeToCompare1, const Time & timeToCompare2) friend
Equality operator for a Time object with a double. Comparison is performed at double precision (i.e. Time is cast to double and compared)
Parameters
timeToCompare1 First time to compare (in double precision)
timeToCompare2 Second time to compare
Returns
True if two times are fully equal; false if not.
Definition at line 555 of file timeType.h.
operator!= [2/5]
bool operator!= (const Time & timeToCompare1, const double timeToCompare2) friend
Inequality operator for a Time object with a double. Comparison is performed at double precision (i.e. Time is cast to double and compared)
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (in double precision)
Returns
True if two times are fully equal; false if not.
Definition at line 568 of file timeType.h.
operator!= [3/5]
bool operator!= (const double timeToCompare1, const Time & timeToCompare2) friend
Inequality operator for a Time object with a double. Comparison is performed at double precision (i.e. Time is cast to double and compared)
Parameters
timeToCompare1 First time to compare (in double precision)
timeToCompare2 Second time to compare
Returns
True if two times are fully equal; false if not.
Definition at line 581 of file timeType.h.
operator== [5/6]
bool operator== (const Time & timeToCompare1, const long double timeToCompare2) friend
Equality operator for a Time object with a long double. Comparison is performed at lgon double precision (i.e. Time is cast to long double and compared)
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (in long double precision)
Returns
True if two times are fully equal; false if not.
Definition at line 594 of file timeType.h.
operator== [6/6]
bool operator== (const long double timeToCompare1, const Time & timeToCompare2) friend
Equality operator for a Time object with a long double. Comparison is performed at lgon double precision (i.e. Time is cast to long double and compared)
Parameters
timeToCompare1 First time to compare (in long double precision)
timeToCompare2 Second time to compare
Returns
True if two times are fully equal; false if not.
Definition at line 607 of file timeType.h.
operator!= [4/5]
bool operator!= (const Time & timeToCompare1, const long double timeToCompare2) friend
Inequality operator for a Time object with a long double. Comparison is performed at lgon double precision (i.e. Time is cast to long double and compared)
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (in long double precision)
Returns
True if two times are fully equal; false if not.
Definition at line 620 of file timeType.h.
operator!= [5/5]
bool operator!= (const long double timeToCompare1, const Time & timeToCompare2) friend
Inequality operator for a Time object with a long double. Comparison is performed at lgon double precision (i.e. Time is cast to long double and compared)
Parameters
timeToCompare1 First time to compare (in long double precision)
timeToCompare2 Second time to compare
Returns
True if two times are fully equal; false if not.
Definition at line 633 of file timeType.h.
operator> [1/5]
bool operator> (const Time & timeToCompare1, const Time & timeToCompare2) friend
Greater-than operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is larger than timeToCompare2, false otherwise.
Definition at line 645 of file timeType.h.
operator>= [1/5]
bool operator>= (const Time & timeToCompare1, const Time & timeToCompare2) friend
Greater-than-or-equal-to-than operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is larger than or equal to timeToCompare2, false otherwise.
Definition at line 669 of file timeType.h.
operator< [1/5]
bool operator< (const Time & timeToCompare1, const Time & timeToCompare2) friend
Smaller-than operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is smaller than timeToCompare2, false otherwise.
Definition at line 693 of file timeType.h.
operator<= [1/5]
bool operator<= (const Time & timeToCompare1, const Time & timeToCompare2) friend
Smaller-than-or-equal-to-than operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is smaller than or equal to timeToCompare2, false otherwise.
Definition at line 717 of file timeType.h.
operator< [2/5]
bool operator< (const Time & timeToCompare1, const double timeToCompare2) friend
Smaller-than operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (as double)
Returns
True if timeToCompare1 is smaller than timeToCompare2, false otherwise.
Definition at line 741 of file timeType.h.
operator< [3/5]
bool operator< (const Time & timeToCompare1, const long double timeToCompare2) friend
Smaller-than operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (as double)
Returns
True if timeToCompare1 is smaller than timeToCompare2, false otherwise.
Definition at line 753 of file timeType.h.
operator<= [2/5]
bool operator<= (const Time & timeToCompare1, const double timeToCompare2) friend
Smaller-than-or-equal operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (as double)
Returns
True if timeToCompare1 is smaller than or equal to timeToCompare2, false otherwise.
Definition at line 765 of file timeType.h.
operator<= [3/5]
bool operator<= (const Time & timeToCompare1, const long double timeToCompare2) friend
Smaller-than-or-equal operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (as double)
Returns
True if timeToCompare1 is smaller than or equal to timeToCompare2, false otherwise.
Definition at line 777 of file timeType.h.
operator> [2/5]
bool operator> (const Time & timeToCompare1, const double timeToCompare2) friend
Greater-than operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (as double)
Returns
True if timeToCompare1 is larger than timeToCompare2, false otherwise.
Definition at line 789 of file timeType.h.
operator> [3/5]
bool operator> (const Time & timeToCompare1, const long double timeToCompare2) friend
Greater-than operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (as double)
Returns
True if timeToCompare1 is larger than timeToCompare2, false otherwise.
Definition at line 801 of file timeType.h.
operator>= [2/5]
bool operator>= (const Time & timeToCompare1, const double timeToCompare2) friend
Greater-than-or-equal operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (as double)
Returns
True if timeToCompare1 is larger than or equal to timeToCompare2, false otherwise.
Definition at line 813 of file timeType.h.
operator>= [3/5]
bool operator>= (const Time & timeToCompare1, const long double timeToCompare2) friend
Greater-than-or-equal operator for two Time objects
Parameters
timeToCompare1 First time to compare
timeToCompare2 Second time to compare (as double)
Returns
True if timeToCompare1 is larger than or equal to timeToCompare2, false otherwise.
Definition at line 825 of file timeType.h.
operator< [4/5]
bool operator< (const double timeToCompare1, const Time & timeToCompare2) friend
Smaller-than operator for two Time objects
Parameters
timeToCompare1 First time to compare (as double)
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is smaller than timeToCompare2, false otherwise.
Definition at line 837 of file timeType.h.
operator< [5/5]
bool operator< (const long double timeToCompare1, const Time & timeToCompare2) friend
Smaller-than operator for two Time objects
Parameters
timeToCompare1 First time to compare (as long double)
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is smaller than timeToCompare2, false otherwise.
Definition at line 849 of file timeType.h.
operator<= [4/5]
bool operator<= (const double timeToCompare1, const Time & timeToCompare2) friend
Smaller-than-or-equal operator for two Time objects
Parameters
timeToCompare1 First time to compare (as double)
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is smaller than or equal to timeToCompare2, false otherwise.
Definition at line 861 of file timeType.h.
operator<= [5/5]
bool operator<= (const long double timeToCompare1, const Time & timeToCompare2) friend
Smaller-than-or-equal operator for two Time objects
Parameters
timeToCompare1 First time to compare (as long double)
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is smaller than or equal to timeToCompare2, false otherwise.
Definition at line 873 of file timeType.h.
operator> [4/5]
bool operator> (const double timeToCompare1, const Time & timeToCompare2) friend
Greater-than operator for two Time objects
Parameters
timeToCompare1 First time to compare (as double)
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is larger than timeToCompare2, false otherwise.
Definition at line 885 of file timeType.h.
operator> [5/5]
bool operator> (const long double timeToCompare1, const Time & timeToCompare2) friend
Greater-than operator for two Time objects
Parameters
timeToCompare1 First time to compare (as long double)
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is larger than timeToCompare2, false otherwise.
Definition at line 897 of file timeType.h.
operator>= [4/5]
bool operator>= (const double timeToCompare1, const Time & timeToCompare2) friend
Greater-than-or-equal operator for two Time objects
Parameters
timeToCompare1 First time to compare (as double)
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is larger than or equal to timeToCompare2, false otherwise.
Definition at line 909 of file timeType.h.
operator>= [5/5]
bool operator>= (const long double timeToCompare1, const Time & timeToCompare2) friend
Greater-than-or-equal operator for two Time objects
Parameters
timeToCompare1 First time to compare (as long double)
timeToCompare2 Second time to compare
Returns
True if timeToCompare1 is larger than or equal to timeToCompare2, false otherwise.
Definition at line 921 of file timeType.h.
operator<<
std::ostream& operator<< (std::ostream & stream, const Time & timeToPrint) friend
Definition at line 927 of file timeType.h.
Member Data Documentation
daysToAdd
int tudat::Time::daysToAdd protected
Definition at line 1009 of file timeType.h.
Referenced by normalizeMembers().
fullPeriods_
int tudat::Time::fullPeriods_ protected
Definition at line 1012 of file timeType.h.
Referenced by getFullPeriods(), getSeconds(), normalizeMembers(), operator*=(), operator+=(), operator-=(), operator/=(), and operator=().
secondsIntoFullPeriod_
long double tudat::Time::secondsIntoFullPeriod_ protected
Definition at line 1015 of file timeType.h.
Referenced by getSeconds(), getSecondsIntoFullPeriod(), normalizeMembers(), operator*=(), operator+=(), operator-=(), operator/=(), and operator=().
The documentation for this class was generated from the following file:
Basics/timeType.h