Tudat: tudat::aerodynamics::NRLMSISE00Atmosphere Class Reference
tudat::aerodynamics::NRLMSISE00Atmosphere Class Reference
NRLMSISE-00 atmosphere model class.
#include <nrlmsise00Atmosphere.h>
Public Types
typedef std::function< NRLMSISE00Input(double, double, double, double) > NRLMSISE00InputFunction
NRLMSISEInput function.
Public Member Functions
NRLMSISE00Atmosphere (const NRLMSISE00InputFunction nrlmsise00InputFunction, const bool useIdealGasLaw=true)
Default constructor.
NRLMSISE00Atmosphere (const NRLMSISE00InputFunction nrlmsise00InputFunction, const double specificHeatRatio, const GasComponentProperties gasProperties, const bool useIdealGasLaw=true)
Constructor.
double getAverageNumberDensity (const double altitude, const double longitude, const double latitude, const double time)
Get local average number density.
double getDensity (const double altitude, const double longitude, const double latitude, const double time)
Get local density.
std::pair< std::vector< double >, std::vector< double > > getFullOutput (const double altitude, const double longitude, const double latitude, const double time)
Get the full model output.
double getMeanFreePath (const double altitude, const double longitude, const double latitude, const double time)
Get local mean free path.
double getMeanMolarMass (const double altitude, const double longitude, const double latitude, const double time)
Get local mean molar mass.
NRLMSISE00Input getNRLMSISE00Input ()
Function to get Input data to NRLMSISE00 atmosphere model.
std::vector< double > getNumberDensities (const double altitude, const double longitude, const double latitude, const double time)
get local number density of the gas components.
double getPressure (const double altitude, const double longitude, const double latitude, const double time)
Get local pressure.
double getSpeedOfSound (const double altitude, const double longitude, const double latitude, const double time)
Get local speed of sound.
double getTemperature (const double altitude, const double longitude, const double latitude, const double time)
Get local temperature.
double getWeightedAverageCollisionDiameter (const double altitude, const double longitude, const double latitude, const double time)
Get local weighted average collision diameter.
void resetHashKey ()
Reset the hash key.
void setGasComponentProperties (const GasComponentProperties gasComponentProperties)
Set gas component properties.
Public Member Functions inherited from tudat::aerodynamics::AtmosphereModel
virtual ~AtmosphereModel ()
Default destructor.
std::shared_ptr< WindModel > getWindModel ()
Function to retrieve the model describing the wind velocity vector of the atmosphere.
void setWindModel (const std::shared_ptr< WindModel > windModel)
Function to set the model describing the wind velocity vector of the atmosphere.
Private Member Functions
void computeProperties (const double altitude, const double longitude, const double latitude, const double time)
Compute the local atmospheric properties.
size_t hashFunc (const double altitude, const double longitude, const double latitude, const double time)
Get Hash Key.
Private Attributes
ap_array aph_
Magnetic index structure of 7d array.
double averageNumberDensity_
Current average number density (M-3)
double density_
Current local density (kg/m3)
nrlmsise_flags flags_
Flags set for NRLMSISE computations.
GasComponentProperties gasComponentProperties_
Data structure that contains the colision diameter.
size_t hashKey_
Current key hash.
nrlmsise_input input_
Input structure with 10 scalar settings and magnetic values struct.
NRLMSISE00Input inputData_
Input data to NRLMSISE00 atmosphere model.
double meanFreePath_
Current mean free path (m)
double meanMolarMass_
mean molar mass (kg/mole)
double molarGasConstant_
Molar gas constant (J/mol K)
NRLMSISE00InputFunction nrlmsise00InputFunction_
Shared pointer to solar activity function.
std::vector< double > numberDensities_
Current number densities of gas components numberDensities_[0] - HE NUMBER DENSITY (M-3) numberDensities_[1] - O NUMBER DENSITY (M-3) numberDensities_[2] - N2 NUMBER DENSITY (M-3) numberDensities_[3] - O2 NUMBER DENSITY (M-3) numberDensities_[4] - AR NUMBER DENSITY (M-3) numberDensities_[5] - H NUMBER DENSITY (M-3) numberDensities_[6] - N NUMBER DENSITY (M-3) numberDensities_[7] - Anomalous oxygen NUMBER DENSITY (M-3)
nrlmsise_output output_
Ouput structure of densities (9d) and temperature (2d) arrays.
double pressure_
Current local pressure (Implemented with ideal gass law only!)
double specificHeatRatio_
Specific heat ratio.
double speedOfSound_
Current speed of sound (m/s)
double temperature_
Current local temperature (K)
bool useIdealGasLaw_
Use the ideal gas law for the computation of the pressure.
double weightedAverageCollisionDiameter_
Current weighted average of the collision diameter using the number density as weights in (M)
Additional Inherited Members
Protected Attributes inherited from tudat::aerodynamics::AtmosphereModel
std::shared_ptr< WindModel > windModel_
Model describing the wind velocity vector of the atmosphere.
Detailed Description
NRLMSISE-00 atmosphere model class. This class uses the NRLMSISE00 atmosphere model to calculate atmospheric density and temperature. The GTD7 function is used: Neutral Atmosphere Empircial Model from the surface to lower exosphere. Currently the ideal gas law is used to compute the speed of sound. The specific heat ratio is assumed to be constant and equal to 1.4.
Definition at line 180 of file nrlmsise00Atmosphere.h.
Member Typedef Documentation
NRLMSISE00InputFunction
typedef std::function< NRLMSISE00Input(double, double, double, double) > tudat::aerodynamics::NRLMSISE00Atmosphere::NRLMSISE00InputFunction
Boost function that accepts (altitude, longitude, latitude, time) and returns NRLMSISEInput data.
Definition at line 189 of file nrlmsise00Atmosphere.h.
Constructor & Destructor Documentation
NRLMSISE00Atmosphere() [1/2]
tudat::aerodynamics::NRLMSISE00Atmosphere::NRLMSISE00Atmosphere (const NRLMSISE00InputFunction nrlmsise00InputFunction, const bool useIdealGasLaw = true) inline
Default constructor.
Parameters
nrlmsise00InputFunction Function which provides the NRLMSISE00 model input as a function of (altitude, longitude, latitude, time).
useIdealGasLaw Variable denoting whether to use the ideal gas law for computation of pressure.
Definition at line 198 of file nrlmsise00Atmosphere.h.
References gasComponentProperties_, tudat::physical_constants::MOLAR_GAS_CONSTANT, molarGasConstant_, resetHashKey(), specificHeatRatio_, and useIdealGasLaw_.
NRLMSISE00Atmosphere() [2/2]
tudat::aerodynamics::NRLMSISE00Atmosphere::NRLMSISE00Atmosphere (const NRLMSISE00InputFunction nrlmsise00InputFunction, const double specificHeatRatio, const GasComponentProperties gasProperties, const bool useIdealGasLaw = true) inline
Constructor that sets the gas component properties and specific heat ratio.
Parameters
nrlmsise00InputFunction shared function pointer to provide all necessary input.
specificHeatRatio value of the specific heat ratio.
gasProperties a GasComponentProperties data structure that contains the molecule collision diameters and the molar mass.
useIdealGasLaw Boolean denoting whether the ideal gas law is to be used.
Definition at line 219 of file nrlmsise00Atmosphere.h.
References gasComponentProperties_, tudat::physical_constants::MOLAR_GAS_CONSTANT, molarGasConstant_, resetHashKey(), specificHeatRatio_, and useIdealGasLaw_.
Member Function Documentation
setGasComponentProperties()
void tudat::aerodynamics::NRLMSISE00Atmosphere::setGasComponentProperties (const GasComponentProperties gasComponentProperties) inline
Sets the gas component properties. These are required for the calculation of the speed of sound and the mean free path.
Parameters
gasComponentProperties Properties of the gas components
Definition at line 238 of file nrlmsise00Atmosphere.h.
References gasComponentProperties_.
getDensity()
double tudat::aerodynamics::NRLMSISE00Atmosphere::getDensity (const double altitude, const double longitude, const double latitude, const double time) inline virtual
Returns the local density of the atmosphere in kg per meter^3.
Parameters
altitude Altitude at which density is to be computed [m].
longitude Longitude at which density is to be computed [rad].
latitude Latitude at which density is to be computed [rad].
time Time at which density is to be computed (seconds since J2000).
Returns
Atmospheric density [kg/m^3].
Implements tudat::aerodynamics::AtmosphereModel.
Definition at line 252 of file nrlmsise00Atmosphere.h.
References computeProperties(), and density_.
getPressure()
double tudat::aerodynamics::NRLMSISE00Atmosphere::getPressure (const double altitude, const double longitude, const double latitude, const double time) inline virtual
Returns the local pressure of the atmosphere in Newton per meter^2. The pressure is not implemented in the current version (returns NaN).
Parameters
altitude Altitude at which pressure is to be computed [m].
longitude Longitude at which pressure is to be computed [rad].
latitude Latitude at which pressure is to be computed [rad].
time Time at which pressure is to be computed (seconds since J2000).
Returns
Atmospheric pressure.
Implements tudat::aerodynamics::AtmosphereModel.
Definition at line 269 of file nrlmsise00Atmosphere.h.
References computeProperties(), pressure_, and useIdealGasLaw_.
getTemperature()
double tudat::aerodynamics::NRLMSISE00Atmosphere::getTemperature (const double altitude, const double longitude, const double latitude, const double time) inline virtual
Returns the local temperature of the atmosphere parameter in Kelvin.
Parameters
altitude Altitude at which temperature is to be computed [m].
longitude Longitude at which temperature is to be computed [rad].
latitude Latitude at which temperature is to be computed [rad].
time Time at which temperature is to be computed (seconds since J2000).
Returns
Atmospheric temperature.
Implements tudat::aerodynamics::AtmosphereModel.
Definition at line 292 of file nrlmsise00Atmosphere.h.
References computeProperties(), and temperature_.
getSpeedOfSound()
double tudat::aerodynamics::NRLMSISE00Atmosphere::getSpeedOfSound (const double altitude, const double longitude, const double latitude, const double time) inline virtual
Returns the local speed of sound in m/s.
Parameters
altitude Altitude at which speed of sound is to be computed [m].
longitude Longitude at which speed of sound is to be computed [rad].
latitude Latitude at whichspeed of sound is to be computed [rad].
time Time at which speed of sound is to be computed (seconds since J2000).
Returns
Speed of sound.
Implements tudat::aerodynamics::AtmosphereModel.
Definition at line 308 of file nrlmsise00Atmosphere.h.
References computeProperties(), and speedOfSound_.
getMeanFreePath()
double tudat::aerodynamics::NRLMSISE00Atmosphere::getMeanFreePath (const double altitude, const double longitude, const double latitude, const double time) inline
Returns the local mean free path in m.
Parameters
altitude Altitude at which mean free path is to be computed [m].
longitude Longitude at which mean free path is to be computed [rad].
latitude Latitude at which mean free path is to be computed [rad].
time Time at which mean free path is to be computed (seconds since J2000).
Returns
Mean free path.
Definition at line 324 of file nrlmsise00Atmosphere.h.
References computeProperties(), and meanFreePath_.
getMeanMolarMass()
double tudat::aerodynamics::NRLMSISE00Atmosphere::getMeanMolarMass (const double altitude, const double longitude, const double latitude, const double time) inline
Returns the local mean molar mass in kg/mol.
Parameters
altitude Altitude at which mean molar mass is to be computed [m].
longitude Longitude at which mean molar mass is to be computed [rad].
latitude Latitude at which mean molar mass is to be computed [rad].
time Time at which mean molar mass is to be computed (seconds since J2000).
Returns
mean molar mass.
Definition at line 340 of file nrlmsise00Atmosphere.h.
References computeProperties(), and meanMolarMass_.
getNumberDensities()
std::vector< double > tudat::aerodynamics::NRLMSISE00Atmosphere::getNumberDensities (const double altitude, const double longitude, const double latitude, const double time) inline
Returns the number density of each gas component in a vector.
Parameters
altitude Altitude at which number density is to be computed [m].
longitude Longitude at which number density is to be computed [rad].
latitude Latitude at which number density is to be computed [rad].
time Time at which number density is to be computed (seconds since J2000).
Returns
Number densities of gas components
Definition at line 356 of file nrlmsise00Atmosphere.h.
References computeProperties(), and numberDensities_.
getAverageNumberDensity()
double tudat::aerodynamics::NRLMSISE00Atmosphere::getAverageNumberDensity (const double altitude, const double longitude, const double latitude, const double time) inline
Returns the local average number density in m^-3
Parameters
altitude Altitude at which density is to be computed [m].
longitude Longitude at which density is to be computed [rad].
latitude Latitude at which density is to be computed [rad].
time Time at which density is to be computed (seconds since J2000).
Returns
average number density.
Definition at line 372 of file nrlmsise00Atmosphere.h.
References averageNumberDensity_, and computeProperties().
getWeightedAverageCollisionDiameter()
double tudat::aerodynamics::NRLMSISE00Atmosphere::getWeightedAverageCollisionDiameter (const double altitude, const double longitude, const double latitude, const double time) inline
Returns the local weighted average collision diameter using the number densities as weights.
Parameters
altitude Altitude at which average collision diameter is to be computed [m].
longitude Longitude at which average collision diameter is to be computed [rad].
latitude Latitude at which average collision diameter is to be computed [rad].
time Time at which average collision diameter is to be computed (seconds since J2000).
Returns
weighted average collision diameter.
Definition at line 388 of file nrlmsise00Atmosphere.h.
References computeProperties(), and weightedAverageCollisionDiameter_.
getFullOutput()
std::pair< std::vector< double >, std::vector< double > > tudat::aerodynamics::NRLMSISE00Atmosphere::getFullOutput (const double altitude, const double longitude, const double latitude, const double time)
Gets the output directly from the model. This will return a pair of double vectors containing density and temperature values.
Parameters
altitude Altitude at which output is to be computed [m].
longitude Longitude at which output is to be computed [rad].
latitude Latitude at which output is to be computed [rad].
time Time at which output is to be computed (seconds since J2000).
Returns
Full density and temperature values
Definition at line 148 of file nrlmsise00Atmosphere.cpp.
References computeProperties(), and output_.
resetHashKey()
void tudat::aerodynamics::NRLMSISE00Atmosphere::resetHashKey () inline
Resets the hash key, this allows re-computation even if the independent parameters haven't changed. Such as in the case of changes to the model.
Definition at line 416 of file nrlmsise00Atmosphere.h.
References hashKey_.
Referenced by NRLMSISE00Atmosphere().
getNRLMSISE00Input()
NRLMSISE00Input tudat::aerodynamics::NRLMSISE00Atmosphere::getNRLMSISE00Input () inline
Function to get input data to NRLMSISE00 atmosphere model
Returns
Input data to NRLMSISE00 atmosphere model
Definition at line 426 of file nrlmsise00Atmosphere.h.
References inputData_.
hashFunc()
size_t tudat::aerodynamics::NRLMSISE00Atmosphere::hashFunc (const double altitude, const double longitude, const double latitude, const double time) inline private
Returns hash key value based on a vector of keys
Parameters
altitude Altitude [m].
longitude Longitude [rad].
latitude Latitude [rad].
time time.
Returns
hash key value.
Definition at line 568 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties().
computeProperties()
void tudat::aerodynamics::NRLMSISE00Atmosphere::computeProperties (const double altitude, const double longitude, const double latitude, const double time) private
Computes the local atmospheric density, pressure and temperature.
Parameters
altitude Altitude at which output is to be computed [m].
longitude Longitude at which output is to be computed [rad].
latitude Latitude at which output is to be computed [rad].
time Time at which output is to be computed (seconds since J2000).
Definition at line 21 of file nrlmsise00Atmosphere.cpp.
References tudat::aerodynamics::NRLMSISE00Input::apDaily, aph_, tudat::aerodynamics::NRLMSISE00Input::apVector, averageNumberDensity_, tudat::aerodynamics::computeMeanFreePath(), tudat::aerodynamics::computeSpeedOfSound(), tudat::aerodynamics::NRLMSISE00Input::dayOfTheYear, density_, tudat::aerodynamics::GasComponentProperties::diameterArgon, tudat::aerodynamics::GasComponentProperties::diameterAtomicHydrogen, tudat::aerodynamics::GasComponentProperties::diameterAtomicNitrogen, tudat::aerodynamics::GasComponentProperties::diameterAtomicOxygen, tudat::aerodynamics::GasComponentProperties::diameterHelium, tudat::aerodynamics::GasComponentProperties::diameterNitrogen, tudat::aerodynamics::GasComponentProperties::diameterOxygen, tudat::aerodynamics::NRLMSISE00Input::f107, tudat::aerodynamics::NRLMSISE00Input::f107a, flags_, gasComponentProperties_, hashFunc(), hashKey_, input_, inputData_, tudat::aerodynamics::NRLMSISE00Input::localSolarTime, meanFreePath_, meanMolarMass_, molarGasConstant_, tudat::aerodynamics::GasComponentProperties::molarMassArgon, tudat::aerodynamics::GasComponentProperties::molarMassAtomicHydrogen, tudat::aerodynamics::GasComponentProperties::molarMassAtomicNitrogen, tudat::aerodynamics::GasComponentProperties::molarMassAtomicOxygen, tudat::aerodynamics::GasComponentProperties::molarMassHelium, tudat::aerodynamics::GasComponentProperties::molarMassNitrogen, tudat::aerodynamics::GasComponentProperties::molarMassOxygen, nrlmsise00InputFunction_, numberDensities_, output_, tudat::mathematical_constants::PI, pressure_, tudat::aerodynamics::NRLMSISE00Input::secondOfTheDay, specificHeatRatio_, speedOfSound_, tudat::aerodynamics::NRLMSISE00Input::switches, temperature_, TUDAT_NAN, useIdealGasLaw_, weightedAverageCollisionDiameter_, and tudat::aerodynamics::NRLMSISE00Input::year.
Referenced by getAverageNumberDensity(), getDensity(), getFullOutput(), getMeanFreePath(), getMeanMolarMass(), getNumberDensities(), getPressure(), getSpeedOfSound(), getTemperature(), and getWeightedAverageCollisionDiameter().
Member Data Documentation
nrlmsise00InputFunction_
NRLMSISE00InputFunction tudat::aerodynamics::NRLMSISE00Atmosphere::nrlmsise00InputFunction_ private
Definition at line 434 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties().
useIdealGasLaw_
bool tudat::aerodynamics::NRLMSISE00Atmosphere::useIdealGasLaw_ private
Definition at line 437 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), getPressure(), and NRLMSISE00Atmosphere().
hashKey_
size_t tudat::aerodynamics::NRLMSISE00Atmosphere::hashKey_ private
Definition at line 440 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and resetHashKey().
density_
double tudat::aerodynamics::NRLMSISE00Atmosphere::density_ private
Definition at line 443 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getDensity().
temperature_
double tudat::aerodynamics::NRLMSISE00Atmosphere::temperature_ private
Definition at line 446 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getTemperature().
pressure_
double tudat::aerodynamics::NRLMSISE00Atmosphere::pressure_ private
Definition at line 449 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getPressure().
speedOfSound_
double tudat::aerodynamics::NRLMSISE00Atmosphere::speedOfSound_ private
Definition at line 452 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getSpeedOfSound().
meanFreePath_
double tudat::aerodynamics::NRLMSISE00Atmosphere::meanFreePath_ private
Definition at line 455 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getMeanFreePath().
numberDensities_
std::vector< double > tudat::aerodynamics::NRLMSISE00Atmosphere::numberDensities_ private
Definition at line 468 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getNumberDensities().
averageNumberDensity_
double tudat::aerodynamics::NRLMSISE00Atmosphere::averageNumberDensity_ private
Definition at line 471 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getAverageNumberDensity().
weightedAverageCollisionDiameter_
double tudat::aerodynamics::NRLMSISE00Atmosphere::weightedAverageCollisionDiameter_ private
Definition at line 474 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getWeightedAverageCollisionDiameter().
meanMolarMass_
double tudat::aerodynamics::NRLMSISE00Atmosphere::meanMolarMass_ private
Definition at line 477 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getMeanMolarMass().
gasComponentProperties_
GasComponentProperties tudat::aerodynamics::NRLMSISE00Atmosphere::gasComponentProperties_ private
Definition at line 480 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), NRLMSISE00Atmosphere(), and setGasComponentProperties().
specificHeatRatio_
double tudat::aerodynamics::NRLMSISE00Atmosphere::specificHeatRatio_ private
Definition at line 483 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and NRLMSISE00Atmosphere().
molarGasConstant_
double tudat::aerodynamics::NRLMSISE00Atmosphere::molarGasConstant_ private
Definition at line 486 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and NRLMSISE00Atmosphere().
flags_
nrlmsise_flags tudat::aerodynamics::NRLMSISE00Atmosphere::flags_ private
Definition at line 489 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties().
aph_
ap_array tudat::aerodynamics::NRLMSISE00Atmosphere::aph_ private
Magnetic index structure of 7d array: 0 : daily AP 1 : 3 hr AP index for current time 2 : 3 hr AP index for 3 hrs before current time 3 : 3 hr AP index for 6 hrs before current time 4 : 3 hr AP index for 9 hrs before current time 5 : Average of eight 3 hr AP indicies from 12 to 33 hrs prior to current time 6 : Average of eight 3 hr AP indicies from 36 to 57 hrs prior to current time
Definition at line 504 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties().
input_
nrlmsise_input tudat::aerodynamics::NRLMSISE00Atmosphere::input_ private
Input structure with 10 scalar settings and magnetic values struct. year - year, currently ignored (int) doy - day of the year (int) sec - seconds in the day (UT) (double) alt - altitude in kilometers (double) g_lat - geodetic latitude in deg (double) g_long - geodetic longitude in deg (double) lst - local apparent solar time (hours) (double) f107A - 81 day average of F10.7 flux (centered on doy) (double) f107 - daily F10.7 flux for previous day (double) ap - magnetic index (daily) (double) ap_a - magnetic index struct (see above) (ap_array)
Definition at line 521 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties().
output_
nrlmsise_output tudat::aerodynamics::NRLMSISE00Atmosphere::output_ private
Ouput structure of densities (9d) and temperature (2d) arrays: d[0] - HE NUMBER DENSITY(CM-3) d[1] - O NUMBER DENSITY(CM-3) d[2] - N2 NUMBER DENSITY(CM-3) d[3] - O2 NUMBER DENSITY(CM-3) d[4] - AR NUMBER DENSITY(CM-3)
d[5] - TOTAL MASS DENSITY(GM/CM3) [includes d[8] in td7d] d[6] - H NUMBER DENSITY(CM-3) d[7] - N NUMBER DENSITY(CM-3) d[8] - Anomalous oxygen NUMBER DENSITY(CM-3) t[0] - EXOSPHERIC TEMPERATURE t[1] - TEMPERATURE AT ALT
O, H, and N are set to zero below 72.5 km
t[0], Exospheric temperature, is set to global average for
altitudes below 120 km. The 120 km gradient is left at global
average value for altitudes below 72 km.
d[5], TOTAL MASS DENSITY, is NOT the same for subroutines GTD7
and GTD7D
  SUBROUTINE GTD7 -- d[5] is the sum of the mass densities of the
  species labeled by indices 0-4 and 6-7 in output variable d.
  This includes He, O, N2, O2, Ar, H, and N but does NOT include
  anomalous oxygen (species index 8).
  SUBROUTINE GTD7D -- d[5] is the "effective total mass density
  for drag" and is the sum of the mass densities of all species
  in this model, INCLUDING anomalous oxygen.
Definition at line 557 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getFullOutput().
inputData_
NRLMSISE00Input tudat::aerodynamics::NRLMSISE00Atmosphere::inputData_ private
Definition at line 591 of file nrlmsise00Atmosphere.h.
Referenced by computeProperties(), and getNRLMSISE00Input().
The documentation for this class was generated from the following files:
Astrodynamics/Aerodynamics/nrlmsise00Atmosphere.h
Astrodynamics/Aerodynamics/nrlmsise00Atmosphere.cpp