Tudat: tudat::system_models::DirectEngineModel Class Reference
tudat::system_models::DirectEngineModel Class Reference
Engine model derived class in which the thrust is computed directly from the propellant mass flow and specific impulse.
#include <engineModel.h>
Public Member Functions
DirectEngineModel (const std::function< double() > specificImpulseFunction, const std::function< double() > massFlowFunction, const Eigen::Vector3d bodyFixedThrustDirection=Eigen::Vector3d::UnitX())
Constructor.
double getCurrentMassRate ()
Function to retrieve the propellant mass rate.
void updateEngineModel (const double currentTime)
Function to update the engine model to the current time.
Public Member Functions inherited from tudat::system_models::EngineModel
EngineModel (const Eigen::Vector3d bodyFixedThrustDirection=Eigen::Vector3d::UnitX())
Constructor.
virtual ~EngineModel ()
Destructor.
Eigen::Vector3d getBodyFixedThrustDirection ()
Function to retrieve the vector denoting the direction of the thrust delivered by the engine in the body-fixed frame.
double getCurrentThrust ()
Function to retrive the magnitude of the current engine thrust.
Protected Attributes
std::function< double() > massFlowFunction_
Variable mass flow function (no input arguments provided; must be updated by associated guidance law).
std::function< double() > specificImpulseFunction_
Variable specific impulse of engine (no input arguments provided; must be updated by associated guidance law).
Protected Attributes inherited from tudat::system_models::EngineModel
Eigen::Vector3d bodyFixedThrustDirection_
Vector denoting the direction of the thrust delivered by the engine in the body-fixed frame.
double currentThrust_
Current magnitude of the thrust delivered by the engine.
Detailed Description
Engine model derived class in which the thrust is computed directly from the propellant mass flow and specific impulse These two variables may be either constant or variable (magnitudes controlled by associated class defining e.g. GNC system.
Definition at line 109 of file engineModel.h.
Constructor & Destructor Documentation
DirectEngineModel()
tudat::system_models::DirectEngineModel::DirectEngineModel (const std::function< double() > specificImpulseFunction, const std::function< double() > massFlowFunction, const Eigen::Vector3d bodyFixedThrustDirection = Eigen::Vector3d::UnitX()) inline
Constructor
Parameters
specificImpulseFunction Variable specific impulse of engine. (no input arguments provided; must be updated by associated guidance law).
massFlowFunction Variable mass flow function. (no input arguments provided; must be updated by associated guidance law).
bodyFixedThrustDirection Vector denoting the direction of the thrust delivered by the engine in the body-fixed frame (for an ideal engine, this is the opposite direction of the nozzle direction). By default, this vector is set to the positive x-direction, along the longitudinal axis.
Definition at line 124 of file engineModel.h.
Member Function Documentation
updateEngineModel()
void tudat::system_models::DirectEngineModel::updateEngineModel (const double currentTime) inline virtual
Function to update the engine model to the current time. Retrieves the current mass flow and specific impulse; consequently computes the current thrust.
Parameters
currentTime Current itme in simulation.
Implements tudat::system_models::EngineModel.
Definition at line 139 of file engineModel.h.
References tudat::propulsion::computeThrustFromSpecificImpulse(), tudat::system_models::EngineModel::currentThrust_, massFlowFunction_, and specificImpulseFunction_.
getCurrentMassRate()
double tudat::system_models::DirectEngineModel::getCurrentMassRate () inline virtual
Function to retrieve the propellant mass rate.
Returns
Propellant mass rate.
Implements tudat::system_models::EngineModel.
Definition at line 149 of file engineModel.h.
References massFlowFunction_.
Member Data Documentation
specificImpulseFunction_
std::function< double() > tudat::system_models::DirectEngineModel::specificImpulseFunction_ protected
Definition at line 157 of file engineModel.h.
Referenced by updateEngineModel().
massFlowFunction_
std::function< double() > tudat::system_models::DirectEngineModel::massFlowFunction_ protected
Definition at line 160 of file engineModel.h.
Referenced by getCurrentMassRate(), and updateEngineModel().
The documentation for this class was generated from the following file:
Astrodynamics/SystemModels/engineModel.h