Tudat: tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType > Class Template Reference
tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType > Class Template Reference
Linear interpolation class with discrete jumps in data.
#include <jumpDataLinearInterpolator.h>
Public Member Functions
JumpDataLinearInterpolator (const std::map< IndependentVariableType, DependentVariableType > &dataMap, const DependentVariableType maximumAllowableVariation, const DependentVariableType jumpSize, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const DependentVariableType &defaultExtrapolationValue=IdentityElement::getAdditionIdentity< DependentVariableType >())
Constructor from map of independent/dependent data.
JumpDataLinearInterpolator (const std::vector< IndependentVariableType > independentValues, const std::vector< DependentVariableType > dependentValues, const DependentVariableType maximumAllowableVariation, const DependentVariableType jumpSize, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const DependentVariableType &defaultExtrapolationValue=IdentityElement::getAdditionIdentity< DependentVariableType >())
Constructor from vectors of independent/dependent data.
~JumpDataLinearInterpolator ()
Destructor.
DependentVariableType interpolate (const IndependentVariableType independentVariableValue)
Function interpolates dependent variable value at given independent variable value.
Public Member Functions inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
OneDimensionalInterpolator (const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Constructor.
OneDimensionalInterpolator (const BoundaryInterpolationType boundaryHandling, const DependentVariableType &defaultExtrapolationValue)
Constructor.
virtual ~OneDimensionalInterpolator ()
Destructor.
std::vector< DependentVariableType > getDependentValues ()
Function to return the ector with dependent variables used by the interpolator.
std::vector< IndependentVariableType > getIndependentValues ()
Function to return the ector with independent variables used by the interpolator.
std::shared_ptr< LookUpScheme< IndependentVariableType > > getLookUpScheme ()
Function to return the lookup scheme used by the interpolator.
int getNumberOfDimensions ()
Function to return the number of independent variables of the interpolation.
virtual DependentVariableType interpolate (const std::vector< IndependentVariableType > &independentVariableValues)
Function to perform interpolation.
DependentVariableType interpolateNonConst (IndependentVariableType independentVariableValue)
Function to perform interpolation, with non-const input argument.
Public Member Functions inherited from tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >
virtual ~Interpolator ()
Destructor.
Private Attributes
DependentVariableType jumpSize_
Magnitude of jumps in dependent variable data.
DependentVariableType maximumAllowableVariation_
Maximum allowable deviation between two dependent variable values, above which a jump is identified.
Additional Inherited Members
Protected Member Functions inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
void checkBoundaryCase (DependentVariableType &dependentVariable, bool &useValue, const IndependentVariableType &targetIndependentVariable)
Function to check whether boundary handling needs to be applied, depending on method chosen.
int checkInterpolationBoundary (const IndependentVariableType &targetIndependentVariable)
Function to return the condition of the current independent variable.
void makeLookupScheme (const AvailableLookupScheme selectedScheme)
Make look-up scheme that is to be used.
Protected Attributes inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
BoundaryInterpolationType boundaryHandling_
Behavior of interpolator when independent variable is outside range.
std::pair< DependentVariableType, DependentVariableType > defaultExtrapolationValue_
Default value to be used for extrapolation.
std::vector< DependentVariableType > dependentValues_
Vector with dependent variables.
std::vector< IndependentVariableType > independentValues_
Vector with independent variables.
std::shared_ptr< LookUpScheme< IndependentVariableType > > lookUpScheme_
Pointer to look up scheme.
Detailed Description
template<typename IndependentVariableType, typename DependentVariableType>
class tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >
This class is used to perform linear interpolation in a single dimension from a set of data in independent and dependent variables. The dependent variables contain discrete jumps at specified locations. The jumps are identified by a maximum allowed deviation between two dependent variable data points. The jump in data is fixed to a user-supplied value when a jump is identified.
Definition at line 48 of file jumpDataLinearInterpolator.h.
Constructor & Destructor Documentation
JumpDataLinearInterpolator() [1/2]
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::JumpDataLinearInterpolator (const std::map< IndependentVariableType, DependentVariableType > & dataMap, const DependentVariableType maximumAllowableVariation, const DependentVariableType jumpSize, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm, const BoundaryInterpolationType boundaryHandling = extrapolate_at_boundary, const DependentVariableType & defaultExtrapolationValue = IdentityElement::getAdditionIdentity< DependentVariableType >()) inline
This constructor initializes the interpolator from a map containing independent variables as key and dependent variables as value. A look-up scheme can be provided to override the given default.
Parameters
dataMap Map containing independent variables as key and dependent variables as value.
maximumAllowableVariation Maximum allowable deviation between two dependent variable values, above which a jump is identified.
jumpSize Magnitude of jumps in dependent variable data.
selectedLookupScheme Identifier of lookupscheme from enum. This algorithm is used to find the nearest lower data point in the independent variables when requesting interpolation.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 74 of file jumpDataLinearInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::jumpSize_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::makeLookupScheme(), and tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::maximumAllowableVariation_.
JumpDataLinearInterpolator() [2/2]
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::JumpDataLinearInterpolator (const std::vector< IndependentVariableType > independentValues, const std::vector< DependentVariableType > dependentValues, const DependentVariableType maximumAllowableVariation, const DependentVariableType jumpSize, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm, const BoundaryInterpolationType boundaryHandling = extrapolate_at_boundary, const DependentVariableType & defaultExtrapolationValue = IdentityElement::getAdditionIdentity< DependentVariableType >()) inline
This constructor initializes the interpolator from two vectors containing the independent variables and dependent variables. A look-up scheme can be provided to override the given default.
Parameters
independentValues Vector of values of independent variables that are used, must be sorted in ascending order.
dependentValues Vector of values of dependent variables that are used.
maximumAllowableVariation Maximum allowable deviation between two dependent variable values, above which a jump is identified.
jumpSize Magnitude of jumps in dependent variable data.
selectedLookupScheme Identifier of lookupscheme from enum. This algorithm is used to find the nearest lower data point in the independent variables when requesting interpolation.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 123 of file jumpDataLinearInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::jumpSize_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::makeLookupScheme(), and tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::maximumAllowableVariation_.
~JumpDataLinearInterpolator()
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::~JumpDataLinearInterpolator () inline
Definition at line 145 of file jumpDataLinearInterpolator.h.
Member Function Documentation
interpolate()
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::interpolate (const IndependentVariableType independentVariableValue) inline virtual
Function interpolates dependent variable value at given independent variable value.
Parameters
independentVariableValue Value of independent variable at which interpolation is to take place.
Returns
Interpolated value of dependent variable.
Implements tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >.
Definition at line 154 of file jumpDataLinearInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::checkBoundaryCase(), tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::jumpSize_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::lookUpScheme_, and tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::maximumAllowableVariation_.
Member Data Documentation
maximumAllowableVariation_
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::maximumAllowableVariation_ private
Definition at line 195 of file jumpDataLinearInterpolator.h.
Referenced by tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::interpolate(), and tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::JumpDataLinearInterpolator().
jumpSize_
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::jumpSize_ private
Definition at line 198 of file jumpDataLinearInterpolator.h.
Referenced by tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::interpolate(), and tudat::interpolators::JumpDataLinearInterpolator< IndependentVariableType, DependentVariableType >::JumpDataLinearInterpolator().
The documentation for this class was generated from the following file:
Mathematics/Interpolators/jumpDataLinearInterpolator.h