Tudat: tudat::relativity::RelativisticAccelerationCorrection Class Reference
tudat::relativity::RelativisticAccelerationCorrection Class Reference
Class to compute typical relativistic corrections to the dynamics of an orbiter.
#include <relativisticAccelerationCorrection.h>
Public Member Functions
RelativisticAccelerationCorrection (std::function< Eigen::Vector6d() > stateFunctionOfAcceleratedBody, std::function< Eigen::Vector6d() > stateFunctionOfCentralBody, std::function< Eigen::Vector6d() > stateFunctionOfPrimaryBody, std::function< double() > gravitationalParameterFunctionOfCentralBody, std::function< double() > gravitationalParameterFunctionOfPrimaryBody, std::string primaryBodyName, std::function< Eigen::Vector3d() > centalBodyAngularMomentumFunction=std::function< Eigen::Vector3d() >(), std::function< double() > ppnParameterGammaFunction=[](){ return 1.0;}, std::function< double() > ppnParameterBetaFunction=[](){ return 1.0;}, const bool calculateSchwarzschildCorrection=true)
Constructor, used when including deSitter acceleration.
RelativisticAccelerationCorrection (std::function< Eigen::Vector6d() > stateFunctionOfAcceleratedBody, std::function< Eigen::Vector6d() > stateFunctionOfCentralBody, std::function< double() > gravitationalParameterFunctionOfCentralBody, std::function< Eigen::Vector3d() > centalBodyAngularMomentumFunction, std::function< double() > ppnParameterGammaFunction=[](){ return 1.0;}, std::function< double() > ppnParameterBetaFunction=[](){ return 1.0;}, const bool calculateSchwarzschildCorrection=true)
Constructor, used when including Lense-Thirring, but not de Sitter, acceleration.
RelativisticAccelerationCorrection (std::function< Eigen::Vector6d() > stateFunctionOfAcceleratedBody, std::function< Eigen::Vector6d() > stateFunctionOfCentralBody, std::function< double() > gravitationalParameterFunctionOfCentralBody, std::function< double() > ppnParameterGammaFunction=[](){ return 1.0;}, std::function< double() > ppnParameterBetaFunction=[](){ return 1.0;})
Constructor, used for Schwarzschild term only.
~RelativisticAccelerationCorrection ()
Destructor.
Eigen::Vector3d getAcceleration ()
Function to return the current acceleration.
bool getCalculateDeSitterCorrection ()
Function to return the boolean denoting wheter the de Sitter term is used.
bool getCalculateLenseThirringCorrection ()
Function to return the boolean denoting wheter the Lense-Thirring term is used.
bool getCalculateSchwarzschildCorrection ()
Function to return the boolean denoting wheter the Schwarzschild term is used.
std::function< double() > getGravitationalParameterFunctionOfCentralBody ()
Function to return the current gravitational parameter of central body.
std::function< double() > getPpnParameterBetaFunction_ ()
Function to return the current PPN parameter beta.
std::function< double() > getPpnParameterGammaFunction_ ()
Function to return the current PPN parameter gamma.
std::string getPrimaryBodyName ()
std::function< Eigen::Vector6d() > getStateFunctionOfAcceleratedBody ()
Function to return the current state of the body undergoing acceleration.
std::function< Eigen::Vector6d() > getStateFunctionOfCentralBody ()
Function to return the current state of the main body exerting acceleration.
void updateMembers (const double currentTime=TUDAT_NAN)
Update member variables used by the relativistic correction acceleration model.
Public Member Functions inherited from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >
AccelerationModel ()
Constructor.
virtual ~AccelerationModel ()
Virtual destructor.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
Private Attributes
bool calculateDeSitterCorrection_
Boolean denoting wheter the de Sitter term is used.
bool calculateLenseThirringCorrection_
Boolean denoting wheter the Lense-Thirring term is used.
bool calculateSchwarzschildCorrection_
Boolean denoting wheter the Schwarzschild term is used.
Eigen::Vector3d centalBodyAngularMomentum_
Current angulat momentum vector of central body.
std::function< Eigen::Vector3d() > centalBodyAngularMomentumFunction_
Function returning the angular momenum of the central body (expressed in the propagation frame)
double commonCorrectionTerm_
Pre-computed common term for corrections (computed by calculateRelativisticAccelerationCorrectionsCommonterm)
Eigen::Vector3d currentAcceleration_
Relativistic acceleration correction, as computed by last call to updateMembers function.
std::function< double() > gravitationalParameterFunctionOfCentralBody_
Function returning the gravitational parameter of the central body.
std::function< double() > gravitationalParameterFunctionOfPrimaryBody_
Function returning the gravitational parameter of the primary body.
double gravitationalParameterOfCentralBody_
Current gravitational parameter of central body.
double gravitationalParameterOfPrimaryBody_
Current gravitational parameter of primary body.
double ppnParameterBeta_
Current PPN parameter beta.
std::function< double() > ppnParameterBetaFunction_
Function returning the PPN parameter beta.
double ppnParameterGamma_
Current PPN parameter gamma.
std::function< double() > ppnParameterGammaFunction_
Function returning the PPN parameter gamma.
std::string primaryBodyName_
Name of primary body (e.g. Sun for acceleration acting on an Earth-orbiting satellite)
std::function< Eigen::Vector6d() > stateFunctionOfAcceleratedBody_
State function of vehicle undergoing acceleration.
std::function< Eigen::Vector6d() > stateFunctionOfCentralBody_
State function of main body exerting acceleration (e.g. Earth for an Earth-orbiting satellite).
std::function< Eigen::Vector6d() > stateFunctionOfPrimaryBody_
Eigen::Vector6d stateOfAcceleratedBody_
Current state of the body undergoing acceleration, as computed by last call to updateMembers function.
Eigen::Vector6d stateOfAcceleratedBodyWrtCentralBody_
Current state of the primary body, as computed by last call to updateMembers function.
Eigen::Vector6d stateOfCentralBodyWrtPrimaryBody_
Current state of the main body exerting acceleration, as computed by last call to updateMembers function.
Additional Inherited Members
Protected Attributes inherited from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >
double currentTime_
Previous time to which acceleration model was updated.
Detailed Description
Class to compute typical relativistic corrections to the dynamics of an orbiter. The model allows the inclusion of the Schwarzschild, Lense-Thirring and de Sitter terms (any one of them may be turned on and off). An excellent introduction to these models is given in 'General Relativity and Space Geodesy' by L. Combrinck (2012).
Definition at line 154 of file relativisticAccelerationCorrection.h.
Constructor & Destructor Documentation
RelativisticAccelerationCorrection() [1/3]
tudat::relativity::RelativisticAccelerationCorrection::RelativisticAccelerationCorrection (std::function< Eigen::Vector6d() > stateFunctionOfAcceleratedBody, std::function< Eigen::Vector6d() > stateFunctionOfCentralBody, std::function< Eigen::Vector6d() > stateFunctionOfPrimaryBody, std::function< double() > gravitationalParameterFunctionOfCentralBody, std::function< double() > gravitationalParameterFunctionOfPrimaryBody, std::string primaryBodyName, std::function< Eigen::Vector3d() > centalBodyAngularMomentumFunction = std::function< Eigen::Vector3d() >(), std::function< double() > ppnParameterGammaFunction = [ ](){ return 1.0; }, std::function< double() > ppnParameterBetaFunction = [ ](){ return 1.0; }, const bool calculateSchwarzschildCorrection = true) inline
Constructor, used when including deSitter acceleration
Parameters
stateFunctionOfAcceleratedBody State function of vehicle undergoing acceleration
stateFunctionOfCentralBody State function of main body exerting acceleration (e.g. Earth for an Earth-orbiting satellite).
stateFunctionOfPrimaryBody State function of large body primarily responsible for motion of central body (e.g. Sun for acceleration acting on an Earth-orbiting satellite).
gravitationalParameterFunctionOfCentralBody Function returning the gravitational parameter of the central body
gravitationalParameterFunctionOfPrimaryBody Function returning the gravitational parameter of the primary body
primaryBodyName Name of primary body (e.g. Sun for acceleration acting on an Earth-orbiting satellite)
centalBodyAngularMomentumFunction Function returning the angular momenum of the central body, expressed in the propagation frame (default empty; no Lense-Thirring acceleration if empty).
ppnParameterGammaFunction Function returning the PPN parameter gamma (default 1)
ppnParameterBetaFunction Function returning the PPN parameter beta (default 1)
calculateSchwarzschildCorrection Boolean denoting whether the schwarzschild term is to be used.
Definition at line 175 of file relativisticAccelerationCorrection.h.
RelativisticAccelerationCorrection() [2/3]
tudat::relativity::RelativisticAccelerationCorrection::RelativisticAccelerationCorrection (std::function< Eigen::Vector6d() > stateFunctionOfAcceleratedBody, std::function< Eigen::Vector6d() > stateFunctionOfCentralBody, std::function< double() > gravitationalParameterFunctionOfCentralBody, std::function< Eigen::Vector3d() > centalBodyAngularMomentumFunction, std::function< double() > ppnParameterGammaFunction = [ ](){ return 1.0; }, std::function< double() > ppnParameterBetaFunction = [ ](){ return 1.0; }, const bool calculateSchwarzschildCorrection = true) inline
Constructor, used when including Lense-Thirring, but not de Sitter, acceleration
Parameters
stateFunctionOfAcceleratedBody State function of vehicle undergoing acceleration
stateFunctionOfCentralBody State function of main body exerting acceleration (e.g. Earth for an Earth-orbiting satellite).
gravitationalParameterFunctionOfCentralBody Function returning the gravitational parameter of the central body
centalBodyAngularMomentumFunction Function returning the angular momenum of the central body, expressed in the propagation frame (default empty; no Lense-Thirring acceleration if empty).
ppnParameterGammaFunction Function returning the PPN parameter gamma (default 1)
ppnParameterBetaFunction Function returning the PPN parameter beta (default 1)
calculateSchwarzschildCorrection Boolean denoting whether the schwarzschild term is to be used.
Definition at line 214 of file relativisticAccelerationCorrection.h.
RelativisticAccelerationCorrection() [3/3]
tudat::relativity::RelativisticAccelerationCorrection::RelativisticAccelerationCorrection (std::function< Eigen::Vector6d() > stateFunctionOfAcceleratedBody, std::function< Eigen::Vector6d() > stateFunctionOfCentralBody, std::function< double() > gravitationalParameterFunctionOfCentralBody, std::function< double() > ppnParameterGammaFunction = [ ](){ return 1.0; }, std::function< double() > ppnParameterBetaFunction = [ ](){ return 1.0; }) inline
Constructor, used for Schwarzschild term only
Parameters
stateFunctionOfAcceleratedBody State function of vehicle undergoing acceleration
stateFunctionOfCentralBody State function of main body exerting acceleration (e.g. Earth for an Earth-orbiting satellite).
gravitationalParameterFunctionOfCentralBody Function returning the gravitational parameter of the central body
ppnParameterGammaFunction Function returning the PPN parameter gamma (default 1)
ppnParameterBetaFunction Function returning the PPN parameter beta (default 1)
Definition at line 244 of file relativisticAccelerationCorrection.h.
~RelativisticAccelerationCorrection()
tudat::relativity::RelativisticAccelerationCorrection::~RelativisticAccelerationCorrection () inline
Definition at line 262 of file relativisticAccelerationCorrection.h.
Member Function Documentation
getAcceleration()
Eigen::Vector3d tudat::relativity::RelativisticAccelerationCorrection::getAcceleration () inline virtual
Returns the relativistic correction acceleration. Value is computed by updateMembers function
Returns
Acceleration.
Implements tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 269 of file relativisticAccelerationCorrection.h.
References currentAcceleration_.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::RelativisticAccelerationPartial().
updateMembers()
void tudat::relativity::RelativisticAccelerationCorrection::updateMembers (const double currentTime = TUDAT_NAN) inline virtual
Updates member variables used by the relativistic correction acceleration model. Function pointers to retrieve the current values of quantities from which the acceleration is to be calculated are set by constructor. This function calls them to update the associated variables to their current state.
Parameters
currentTime Time at which acceleration model is to be updated.
Implements tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 282 of file relativisticAccelerationCorrection.h.
References calculateDeSitterCorrection_, tudat::relativity::calculateDeSitterCorrectionAcceleration(), calculateLenseThirringCorrection_, tudat::relativity::calculateLenseThirringCorrectionAcceleration(), tudat::relativity::calculateRelativisticAccelerationCorrectionsCommonterm(), tudat::relativity::calculateScharzschildGravitationalAccelerationCorrection(), calculateSchwarzschildCorrection_, centalBodyAngularMomentum_, centalBodyAngularMomentumFunction_, commonCorrectionTerm_, currentAcceleration_, tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >::currentTime_, gravitationalParameterFunctionOfCentralBody_, gravitationalParameterFunctionOfPrimaryBody_, gravitationalParameterOfCentralBody_, gravitationalParameterOfPrimaryBody_, ppnParameterBeta_, ppnParameterBetaFunction_, ppnParameterGamma_, ppnParameterGammaFunction_, tudat::physical_constants::SPEED_OF_LIGHT, stateFunctionOfAcceleratedBody_, stateFunctionOfCentralBody_, stateFunctionOfPrimaryBody_, stateOfAcceleratedBodyWrtCentralBody_, and stateOfCentralBodyWrtPrimaryBody_.
getStateFunctionOfAcceleratedBody()
std::function< Eigen::Vector6d() > tudat::relativity::RelativisticAccelerationCorrection::getStateFunctionOfAcceleratedBody () inline
Function to return the current state of the body undergoing acceleration
Returns
Current state of the body undergoing acceleration
Definition at line 360 of file relativisticAccelerationCorrection.h.
References stateFunctionOfAcceleratedBody_.
getStateFunctionOfCentralBody()
std::function< Eigen::Vector6d() > tudat::relativity::RelativisticAccelerationCorrection::getStateFunctionOfCentralBody () inline
Function to return the current state of the main body exerting acceleration
Returns
Current state of the main body exerting acceleration
Definition at line 368 of file relativisticAccelerationCorrection.h.
References stateFunctionOfCentralBody_.
getGravitationalParameterFunctionOfCentralBody()
std::function< double() > tudat::relativity::RelativisticAccelerationCorrection::getGravitationalParameterFunctionOfCentralBody () inline
Function to return the current gravitational parameter of central body
Returns
Current gravitational parameter of central body
Definition at line 376 of file relativisticAccelerationCorrection.h.
References gravitationalParameterFunctionOfCentralBody_.
getPpnParameterGammaFunction_()
std::function< double() > tudat::relativity::RelativisticAccelerationCorrection::getPpnParameterGammaFunction_ () inline
Function to return the current PPN parameter gamma
Returns
Current PPN parameter gamma
Definition at line 384 of file relativisticAccelerationCorrection.h.
References ppnParameterGammaFunction_.
getPpnParameterBetaFunction_()
std::function< double() > tudat::relativity::RelativisticAccelerationCorrection::getPpnParameterBetaFunction_ () inline
Function to return the current PPN parameter beta
Returns
Current PPN parameter beta
Definition at line 392 of file relativisticAccelerationCorrection.h.
References ppnParameterBetaFunction_.
getCalculateSchwarzschildCorrection()
bool tudat::relativity::RelativisticAccelerationCorrection::getCalculateSchwarzschildCorrection () inline
Function to return the boolean denoting wheter the Schwarzschild term is used.
Returns
Boolean denoting wheter the Schwarzschild term is used.
Definition at line 400 of file relativisticAccelerationCorrection.h.
References calculateSchwarzschildCorrection_.
getCalculateDeSitterCorrection()
bool tudat::relativity::RelativisticAccelerationCorrection::getCalculateDeSitterCorrection () inline
Function to return the boolean denoting wheter the de Sitter term is used.
Returns
Boolean denoting wheter the de Sitter term is used.
Definition at line 408 of file relativisticAccelerationCorrection.h.
References calculateDeSitterCorrection_.
getCalculateLenseThirringCorrection()
bool tudat::relativity::RelativisticAccelerationCorrection::getCalculateLenseThirringCorrection () inline
Function to return the boolean denoting wheter the Lense-Thirring term is used.
Returns
Boolean denoting wheter the Lense-Thirring term is used.
Definition at line 416 of file relativisticAccelerationCorrection.h.
References calculateLenseThirringCorrection_.
getPrimaryBodyName()
std::string tudat::relativity::RelativisticAccelerationCorrection::getPrimaryBodyName () inline
Definition at line 419 of file relativisticAccelerationCorrection.h.
References primaryBodyName_.
Referenced by tudat::propagators::createTranslationalEquationsOfMotionEnvironmentUpdaterSettings().
Member Data Documentation
stateFunctionOfAcceleratedBody_
std::function< Eigen::Vector6d() > tudat::relativity::RelativisticAccelerationCorrection::stateFunctionOfAcceleratedBody_ private
Definition at line 426 of file relativisticAccelerationCorrection.h.
Referenced by getStateFunctionOfAcceleratedBody(), and updateMembers().
stateFunctionOfCentralBody_
std::function< Eigen::Vector6d() > tudat::relativity::RelativisticAccelerationCorrection::stateFunctionOfCentralBody_ private
Definition at line 429 of file relativisticAccelerationCorrection.h.
Referenced by getStateFunctionOfCentralBody(), and updateMembers().
stateFunctionOfPrimaryBody_
std::function< Eigen::Vector6d() > tudat::relativity::RelativisticAccelerationCorrection::stateFunctionOfPrimaryBody_ private
State function of large body primarily responsible for motion of central body (e.g. Sun for acceleration acting on an Earth-orbiting satellite).
Definition at line 433 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
gravitationalParameterFunctionOfCentralBody_
std::function< double() > tudat::relativity::RelativisticAccelerationCorrection::gravitationalParameterFunctionOfCentralBody_ private
Definition at line 436 of file relativisticAccelerationCorrection.h.
Referenced by getGravitationalParameterFunctionOfCentralBody(), and updateMembers().
gravitationalParameterFunctionOfPrimaryBody_
std::function< double() > tudat::relativity::RelativisticAccelerationCorrection::gravitationalParameterFunctionOfPrimaryBody_ private
Definition at line 439 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
primaryBodyName_
std::string tudat::relativity::RelativisticAccelerationCorrection::primaryBodyName_ private
Definition at line 442 of file relativisticAccelerationCorrection.h.
Referenced by getPrimaryBodyName().
centalBodyAngularMomentumFunction_
std::function< Eigen::Vector3d() > tudat::relativity::RelativisticAccelerationCorrection::centalBodyAngularMomentumFunction_ private
Definition at line 445 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
ppnParameterGammaFunction_
std::function< double() > tudat::relativity::RelativisticAccelerationCorrection::ppnParameterGammaFunction_ private
Definition at line 448 of file relativisticAccelerationCorrection.h.
Referenced by getPpnParameterGammaFunction_(), and updateMembers().
ppnParameterBetaFunction_
std::function< double() > tudat::relativity::RelativisticAccelerationCorrection::ppnParameterBetaFunction_ private
Definition at line 451 of file relativisticAccelerationCorrection.h.
Referenced by getPpnParameterBetaFunction_(), and updateMembers().
stateOfAcceleratedBody_
Eigen::Vector6d tudat::relativity::RelativisticAccelerationCorrection::stateOfAcceleratedBody_ private
Definition at line 456 of file relativisticAccelerationCorrection.h.
stateOfCentralBodyWrtPrimaryBody_
Eigen::Vector6d tudat::relativity::RelativisticAccelerationCorrection::stateOfCentralBodyWrtPrimaryBody_ private
Definition at line 459 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
stateOfAcceleratedBodyWrtCentralBody_
Eigen::Vector6d tudat::relativity::RelativisticAccelerationCorrection::stateOfAcceleratedBodyWrtCentralBody_ private
Definition at line 462 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
gravitationalParameterOfCentralBody_
double tudat::relativity::RelativisticAccelerationCorrection::gravitationalParameterOfCentralBody_ private
Definition at line 465 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
gravitationalParameterOfPrimaryBody_
double tudat::relativity::RelativisticAccelerationCorrection::gravitationalParameterOfPrimaryBody_ private
Definition at line 468 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
centalBodyAngularMomentum_
Eigen::Vector3d tudat::relativity::RelativisticAccelerationCorrection::centalBodyAngularMomentum_ private
Definition at line 471 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
ppnParameterGamma_
double tudat::relativity::RelativisticAccelerationCorrection::ppnParameterGamma_ private
Definition at line 474 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
ppnParameterBeta_
double tudat::relativity::RelativisticAccelerationCorrection::ppnParameterBeta_ private
Definition at line 477 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
commonCorrectionTerm_
double tudat::relativity::RelativisticAccelerationCorrection::commonCorrectionTerm_ private
Definition at line 480 of file relativisticAccelerationCorrection.h.
Referenced by updateMembers().
calculateSchwarzschildCorrection_
bool tudat::relativity::RelativisticAccelerationCorrection::calculateSchwarzschildCorrection_ private
Definition at line 485 of file relativisticAccelerationCorrection.h.
Referenced by getCalculateSchwarzschildCorrection(), and updateMembers().
calculateDeSitterCorrection_
bool tudat::relativity::RelativisticAccelerationCorrection::calculateDeSitterCorrection_ private
Definition at line 488 of file relativisticAccelerationCorrection.h.
Referenced by getCalculateDeSitterCorrection(), and updateMembers().
calculateLenseThirringCorrection_
bool tudat::relativity::RelativisticAccelerationCorrection::calculateLenseThirringCorrection_ private
Definition at line 491 of file relativisticAccelerationCorrection.h.
Referenced by getCalculateLenseThirringCorrection(), and updateMembers().
currentAcceleration_
Eigen::Vector3d tudat::relativity::RelativisticAccelerationCorrection::currentAcceleration_ private
Definition at line 496 of file relativisticAccelerationCorrection.h.
Referenced by getAcceleration(), and updateMembers().
The documentation for this class was generated from the following file:
Astrodynamics/Relativity/relativisticAccelerationCorrection.h