Tudat: tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType > Class Template Reference
tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType > Class Template Reference
#include <variationalEquationsSolver.h>
Public Types
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > MatrixType
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > VectorType
Public Types inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > MatrixType
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > VectorType
Public Member Functions
MultiArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::vector< double > arcStartTimes, const bool integrateDynamicalAndVariationalEquationsConcurrently=true, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > variationalOnlyIntegratorSettings=std::shared_ptr< numerical_integrators::IntegratorSettings< double > >(), const bool clearNumericalSolution=true, const bool integrateEquationsOnCreation=false)
Constructor.
~MultiArcVariationalEquationsSolver ()
Destructor.
std::shared_ptr< MultiArcDynamicsSimulator< StateScalarType, TimeType > > getDynamicsSimulator ()
Function to return object used for numerically propagating and managing the solution of the equations of motion.
std::shared_ptr< DynamicsSimulator< StateScalarType, TimeType > > getDynamicsSimulatorBase ()
Function to retrieve the dynamics simulator object (as base-class pointer)
std::vector< std::vector< std::map< double, Eigen::MatrixXd > > > getNumericalVariationalEquationsSolution ()
Function to return the numerical solution history of integrated variational equations, per arc.
void integrateDynamicalEquationsOfMotionOnly (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &initialStateEstimate)
Function to integrate equations of motion only.
void integrateDynamicalEquationsOfMotionOnly (const std::vector< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &initialStateEstimate)
Function to integrate equations of motion only.
void integrateVariationalAndDynamicalEquations (const VectorType &concatenatedInitialStates, const bool integrateEquationsConcurrently)
Function to integrate variational equations and equations of motion.
void integrateVariationalAndDynamicalEquations (const std::vector< VectorType > &initialStateEstimate, const bool integrateEquationsConcurrently)
Function to integrate variational equations and equations of motion.
void resetParameterEstimate (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > newParameterEstimate, const bool areVariationalEquationsToBeIntegrated=true)
Function to reset parameter estimate and re-integrate equations of motion and, if desired, variational equations.
Public Member Functions inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
VariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool clearNumericalSolution=1)
Constructor.
virtual ~VariationalEquationsSolver ()
Destructor.
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > getParametersToEstimate ()
Function to get the list of objects representing the parameters that are to be integrated.
std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > getStateTransitionMatrixInterface ()
Function to get the state transition matric interface object.
Private Member Functions
void resetVariationalEquationsInterpolators ()
Reset solutions of variational equations.
Private Attributes
std::vector< double > arcStartTimes_
List of start times of each arc. NOTE: This list is updated after every propagation.
std::shared_ptr< MultiArcDynamicsSimulator< StateScalarType, TimeType > > dynamicsSimulator_
Object to propagate the dynamics for all arcs.
std::vector< std::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > > dynamicsStateDerivatives_
State derivative models for each arc (retrieved from dynamicsSimulator_).
int numberOfArcs_
Number of arcs over which propagation is to be performed.
std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > propagatorSettings_
Settings for propagation of equations of motion.
std::vector< std::vector< std::map< double, Eigen::MatrixXd > > > variationalEquationsSolution_
Numerical solution history of integrated variational equations, per arc.
Additional Inherited Members
Protected Member Functions inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
MatrixType createInitialConditions (const VectorType initialStateEstimate)
Create initial matrix of numerical soluation to variational + dynamical equations.
Eigen::MatrixXd createInitialVariationalEquationsSolution ()
Create initial matrix of numerical soluation to variational equations.
Protected Attributes inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
simulation_setup::NamedBodyMap bodyMap_
Map of bodies (with names) of all bodies in integration.
bool clearNumericalSolution_
Boolean to determine whether to clear the raw numerical solution member variables after propagation.
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate_
Object containing all parameters that are to be estimated and their current settings and values.
int parameterVectorSize_
Number of rows in sensitivity matrix.
std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface_
Object used for interpolating numerical results of state transition and sensitivity matrix.
int stateTransitionMatrixSize_
Size (rows and columns are equal) of state transition matrix.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >
Definition at line 915 of file variationalEquationsSolver.h.
Member Typedef Documentation
MatrixType
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MatrixType
Definition at line 919 of file variationalEquationsSolver.h.
VectorType
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::VectorType
Definition at line 920 of file variationalEquationsSolver.h.
Constructor & Destructor Documentation
MultiArcVariationalEquationsSolver()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const std::vector< double > arcStartTimes, const bool integrateDynamicalAndVariationalEquationsConcurrently = true, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > variationalOnlyIntegratorSettings = std::shared_ptr< numerical_integrators::IntegratorSettings< double > >(), const bool clearNumericalSolution = true, const bool integrateEquationsOnCreation = false) inline
Constructor, sets up object for automatic evaluation and numerical integration of variational equations and equations of motion.
Parameters
bodyMap Map of bodies (with names) of all bodies in integration.
integratorSettings Settings for numerical integrator.
propagatorSettings Settings for propagator.
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values.
arcStartTimes Start times for separate arcs
integrateDynamicalAndVariationalEquationsConcurrently Boolean defining whether variational and dynamical equations are to be propagated concurrently (if true) or sequentially (of false)
variationalOnlyIntegratorSettings Settings for numerical integrator when integrating only variational equations.
clearNumericalSolution Boolean to determine whether to clear the raw numerical solution member variables (default true) after propagation and resetting of state transition interface.
integrateEquationsOnCreation Boolean to denote whether equations should be integrated immediately at the end of this contructor.
Definition at line 945 of file variationalEquationsSolver.h.
References tudat::propagators::checkMultiArcPropagatorSettingsAndParameterEstimationConsistency(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_, tudat::estimatable_parameters::getSingleArcParameterSetSize(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parametersToEstimate_, tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parameterVectorSize_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_, tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionMatrixSize_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsObject_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_.
~MultiArcVariationalEquationsSolver()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::~MultiArcVariationalEquationsSolver () inline
Destructor
Definition at line 1026 of file variationalEquationsSolver.h.
Member Function Documentation
integrateDynamicalEquationsOfMotionOnly() [1/2]
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & initialStateEstimate) inline virtual
Function to integrate equations of motion only (for all arcs). If dynamical solution is to be processed, the environment is also updated to the new solution.
Parameters
initialStateEstimate Initial state of the equations of motion that is to be used (in same order as in parametersToEstimate_), concatenated for all arcs.
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 1035 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_.
integrateDynamicalEquationsOfMotionOnly() [2/2]
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly (const std::vector< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & initialStateEstimate) inline
Function to integrate equations of motion only (for all arcs). If dynamical solution is to be processed, the environment is also updated to the new solution.
Parameters
initialStateEstimate Initial state of the equations of motion that is to be used, as a list with separate entries for each arc.
Definition at line 1053 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_.
integrateVariationalAndDynamicalEquations() [1/2]
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations (const VectorType & concatenatedInitialStates, const bool integrateEquationsConcurrently) inline virtual
Function to integrate variational equations and equations of motion, for all arcs. At the end of this function, the stateTransitionInterface_ is reset with the new state transition and sensitivity matrices. If dynamical solution is to be processed, the environment is also updated to the new solution.
Parameters
concatenatedInitialStates Initial state of the equations of motion that is to be used (in same order as in parametersToEstimate_), concatenated for all arcs.
integrateEquationsConcurrently Variable determining whether the equations of motion are to be propagated concurrently with variational equations of motion (if true), or before variational equations (if false).
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 1074 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
integrateVariationalAndDynamicalEquations() [2/2]
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations (const std::vector< VectorType > & initialStateEstimate, const bool integrateEquationsConcurrently) inline
Function to integrate variational equations and equations of motion, for all arcs. At the end of this function, the stateTransitionInterface_ is reset with the new state transition and sensitivity matrices. If dynamical solution is to be processed, the environment is also updated to the new solution.
Parameters
initialStateEstimate Initial state of the equations of motion that is to be used, in a list with initial state for each arc stored separately.
integrateEquationsConcurrently Variable determining whether the equations of motion are to be propagated concurrently with variational equations of motion (if true), or before variational equations (if false).
Definition at line 1107 of file variationalEquationsSolver.h.
References tudat::propagators::convertNumericalStateSolutionsToOutputSolutions(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialConditions(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialVariationalEquationsSolution(), tudat::utilities::createVectorBlockMatrixHistory(), tudat::linear_algebra::doesMatrixHaveNanEntries(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_, tudat::propagators::getArcInitialStateFromPreviousArcResult(), tudat::propagators::EquationIntegrationInterface< StateType, TimeType >::integrateEquations(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parametersToEstimate_, tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parameterVectorSize_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), tudat::propagators::setPropagatorSettingsMultiArcStatesInEstimatedDynamicalParameters(), tudat::propagators::setVariationalEquationsSolution(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionMatrixSize_, tudat::propagators::translational_state, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_.
getDynamicsSimulator()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< MultiArcDynamicsSimulator< StateScalarType, TimeType > > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulator () inline
Function to return object used for numerically propagating and managing the solution of the equations of motion.
Returns
Object used for numerically propagating and managing the solution of the equations of motion.
Definition at line 1304 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_.
getDynamicsSimulatorBase()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< DynamicsSimulator< StateScalarType, TimeType > > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulatorBase () inline virtual
Function to retrieve the dynamics simulator object (as base-class pointer)
Returns
Dynamics simulator object (as base-class pointer)
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 1314 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulator().
resetParameterEstimate()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > newParameterEstimate, const bool areVariationalEquationsToBeIntegrated = true) inline virtual
Function to reset parameter estimate and re-integrate equations of motion and, if desired, variational equations using the new physical parameters/body initial states.
Parameters
newParameterEstimate New estimate of parameters that are to be estimated, in same order as defined in parametersToEstimate_ member.
areVariationalEquationsToBeIntegrated Boolean defining whether the variational equations are to be reintegrated with the new parameter values.
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 1330 of file variationalEquationsSolver.h.
References tudat::estimatable_parameters::getInitialStateVectorOfBodiesToEstimate(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parametersToEstimate_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_.
getNumericalVariationalEquationsSolution()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::vector< std::map< double, Eigen::MatrixXd > > > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::getNumericalVariationalEquationsSolution () inline
Function to return the numerical solution history of integrated variational equations, per arc. Each vector entry contains the results of a single arc, stored in a vector of maps. Inner vector has size two: first entry is state transition matrix history, second is sensitivity matrix history, both stored as maps. Key of map denotes time, values are matrices.
Returns
Numerical solution history of integrated variational equations, per arc.
Definition at line 1360 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_.
resetVariationalEquationsInterpolators()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators () inline private
Reset solutions of variational equations (stateTransitionMatrixInterpolator_ and sensitivityMatrixInterpolator_) for each arc,* i.e. use numerical integration results to create new look-up tables and interpolators of state transition and sensitivity matrices.
Definition at line 1375 of file variationalEquationsSolver.h.
References tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::clearNumericalSolution_, tudat::propagators::createStateTransitionAndSensitivityMatrixInterpolator(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parametersToEstimate_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_, tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionInterface_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_.
Member Data Documentation
dynamicsSimulator_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< MultiArcDynamicsSimulator< StateScalarType, TimeType > > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_ private
Definition at line 1416 of file variationalEquationsSolver.h.
variationalEquationsSolution_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::vector< std::map< double, Eigen::MatrixXd > > > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_ private
Numerical solution history of integrated variational equations, per arc. Each vector entry contains the results of a single arc, stored in a vector of maps. Inner vector has size two: first entry is state transition matrix history, second is sensitivity matrix history, both stored as maps. Key of map denotes time, values are matrices.
Definition at line 1425 of file variationalEquationsSolver.h.
arcStartTimes_
template<typename StateScalarType = double, typename TimeType = double> std::vector< double > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::arcStartTimes_ private
Definition at line 1428 of file variationalEquationsSolver.h.
propagatorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_ private
Definition at line 1432 of file variationalEquationsSolver.h.
dynamicsStateDerivatives_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > > tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsStateDerivatives_ private
Definition at line 1435 of file variationalEquationsSolver.h.
numberOfArcs_
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::numberOfArcs_ private
Definition at line 1438 of file variationalEquationsSolver.h.
The documentation for this class was generated from the following file:
SimulationSetup/EstimationSetup/variationalEquationsSolver.h