Tudat: tudat::simulation_setup Namespace Reference
tudat::simulation_setup Namespace Reference
Classes
class AccelerationLimitedThrottleGuidance
Class to compute throttling law for the parameterized thrust magnitude, where the throttle is determined from a maximum, the user must provide the interpolator for the (maximum) thrust, as well as the associated physical meaning of the independent variables.
class AccelerationSettings
Class for providing settings for acceleration model.
class AerodynamicCoefficientSettings
Class for providing settings for aerodynamic coefficient model.
class ApproximatePlanetPositionSettings
EphemerisSettings derived class for defining settings of an approximate ephemeris for major planets, as inplemented in ApproximatePlanetPositions class and derived class, described on http://ssd.jpl.nasa.gov/txt/aprx_pos_planets.pdf.
class AtmosphereSettings
Class for providing settings for atmosphere model.
class BaseStateInterface
Base class used for the determination of the inertial state of a Body's ephemeris origin.
class BaseStateInterfaceImplementation
Class used for the determination of the inertial state of a Body's ephemeris origin.
class BasicSolidBodyGravityFieldVariationSettings
class Body
Body class representing the properties of a celestial body (natural or artificial).
struct BodySettings
Struct holding settings for a body to be created.
class BodyShapeSettings
Class for providing settings for body shape model.
class CannonBallRadiationPressureInterfaceSettings
Class providing settings for the creation of a cannonball radiation pressure interface.
class CentralGravityFieldSettings
Derived class of GravityFieldSettings defining settings of point mass gravity field.
class ConstantAerodynamicCoefficientSettings
AerodynamicCoefficientSettings for defining a constant aerodynamic coefficients.
class ConstantEphemerisSettings
class ConstantThrustMagnitudeSettings
Class to define settigns for constant thrust settings.
class ControlSurfaceIncrementAerodynamicCoefficientSettings
Class for providing settings for aerodynamic coefficient model of control surfaces.
class CustomConstantTemperatureAtmosphereSettings
AtmosphereSettings for defining custom constant temperature atmosphere.
class CustomEphemerisSettings
class CustomMassRateModelSettings
Class defining the settings for a custom (i.e. predefined function of time) mass rate model.
class CustomThrustDirectionSettings
Class for defining custom thrust direction (i.e. predefined thrust function of time)
class CustomThrustOrientationSettings
Class for defining custom orientation of thrust (i.e. predefined body-fixed-to-propagation rotation as function of time)
class CustomWindModelSettings
Class to define settings for a custom, user-defined, wind model.
class DirectSpiceEphemerisSettings
EphemerisSettings derived class for defining settings of an ephemeris linked directly to Spice.
class DirectTidalDissipationAccelerationSettings
Class for providing settings for a direct tidal acceleration model, with approach of Lainey et al. (2007, 2009, ..)
class EmpiricalAccelerationSettings
Class to define settings for empirical accelerations.
class EphemerisSettings
Class for providing settings for ephemeris model.
class EstimationConvergenceChecker
Class that is used during the orbit determination/parameter estimation to determine whether the estimation is converged.
class ExponentialAtmosphereSettings
AtmosphereSettings for defining an exponential atmosphere.
class FromBodyThrustMagnitudeSettings
Class to define thrust magnitude to be taken directly from an engine model.
class FromFileSphericalHarmonicsGravityFieldSettings
class FromFunctionThrustMagnitudeSettings
Class to define custom settings for thrust magnitude/specific impulse.
class FromThrustMassModelSettings
Class defining the settings of a thrust model where the thrust is directly retrieved from (a) model(s) of an engine.
class FullThrustInterpolationInterface
class GravityFieldSettings
Class for providing settings for gravity field model.
class GravityFieldVariationSettings
Base class for defining settings for gravity field variations.
class GroundStationSettings
class InterpolatedSpiceEphemerisSettings
EphemerisSettings derived class for defining settings of a ephemeris interpolated from Spice data.
class KeplerEphemerisSettings
class MassRateModelSettings
Class for providing settings for a mass rate model.
class MeeCostateBasedThrustDirectionSettings
Class for defining settings for MEE-costate based thrust direction guidance.
class ModelInterpolationSettings
Object to define settings to be used for interpolating time-variations computed by an environment model.
class MutualSphericalHarmonicAccelerationSettings
Class for providing acceleration settings for mutual spherical harmonics acceleration model.
class NRLMSISE00AtmosphereSettings
AtmosphereSettings for defining an NRLMSISE00 atmosphere reading space weather data from a text file.
class OblateSphericalBodyShapeSettings
class OrbitDeterminationManager
Top-level class for performing orbit determination.
class ParameterizedThrustMagnitudeSettings
Class to define the thrust magnitude and specific impulse as an interpolated function of N independent variables.
class PodInput
Data structure used to provide input to orbit determination procedure.
struct PodOutput
Data structure through which the output of the orbit determination is communicated.
class RadiationPressureInterfaceSettings
Base class for radiation pressure interface settings.
class RelativisticAccelerationCorrectionSettings
Class to proivide settings for typical relativistic corrections to the dynamics of an orbiter.
class RotationModelSettings
Class for providing settings for rotation model.
class SimpleRotationModelSettings
RotationModelSettings derived class for defining settings of a simple rotational ephemeris.
class SphericalBodyShapeSettings
BodyShapeSettings derived class for defining settings of a spherical shape model.
class SphericalHarmonicAccelerationSettings
Class for providing settings for spherical harmonics acceleration model.
class SphericalHarmonicsGravityFieldSettings
class TabulatedAerodynamicCoefficientSettings
Object for setting aerodynamic coefficients from a user-defined N-dimensional table (with N>1).
class TabulatedAerodynamicCoefficientSettings< 1 >
Object for setting aerodynamic coefficients from a user-defined 1-dimensional table.
class TabulatedAerodynamicCoefficientSettingsBase
Base class (non-functional) for the different classes of TabulatedAerodynamicCoefficientSettings.
class TabulatedAtmosphereSettings
AtmosphereSettings for defining an atmosphere with tabulated data from file.
class TabulatedControlSurfaceIncrementAerodynamicCoefficientSettings
Object for setting aerodynamic coefficients from a user-defined N-dimensional table.
class TabulatedEphemerisSettings
EphemerisSettings derived class for defining settings of an ephemeris created from tabulated data.
class TabulatedGravityFieldVariationSettings
Class to define settings for tabulated gravity field variations.
class ThrustAccelerationSettings
Class for providing acceleration settings for a thrust acceleration model.
class ThrustDirectionFromStateGuidanceSettings
Thrust guidance settings for thrust that is colinear with position/velocity vector.
class ThrustDirectionGuidanceSettings
Class defining settings for the thrust direction.
class ThrustInputParameterGuidance
Interface base class that can be defined by user to make the use of the ParameterizedThrustMagnitudeSettings class easier.
class ThrustMagnitudeSettings
Class defining settings for the thrust magnitude.
class TorqueSettings
Class for providing settings for torque model.
class WindModelSettings
Class for providing settings for wind model.
Typedefs
typedef std::unordered_map< std::string, std::shared_ptr< Body > > NamedBodyMap
Typdef for a list of body objects (as unordered_map for efficiency reasons)
typedef std::map< std::string, std::vector< std::pair< std::string, std::shared_ptr< AccelerationSettings > > > > SelectedAccelerationList
typedef std::map< std::string, std::map< std::string, std::vector< std::shared_ptr< AccelerationSettings > > > > SelectedAccelerationMap
typedef std::map< std::string, std::vector< std::shared_ptr< MassRateModelSettings > > > SelectedMassRateModelMap
typedef std::map< std::string, std::map< std::string, std::vector< std::shared_ptr< TorqueSettings > > > > SelectedTorqueMap
Enumerations
enum AerodynamicCoefficientTypes { constant_aerodynamic_coefficients, hypersonic_local_inclincation_coefficients, tabulated_coefficients }
List of aerodynamic coefficient models available in simulations.
enum AtmosphereTypes { exponential_atmosphere, custom_constant_temperature_atmosphere, tabulated_atmosphere, nrlmsise00 }
List of atmosphere models available in simulations.
enum BodyShapeTypes { spherical, spherical_spice, oblate_spheroid }
Types of body shape models that can be used.
enum EphemerisType {
approximate_planet_positions, direct_spice_ephemeris, tabulated_ephemeris, interpolated_spice,
constant_ephemeris, kepler_ephemeris, custom_ephemeris
}
List of ephemeris models available in simulations.
enum GravityFieldType { central, central_spice, spherical_harmonic }
List of gravity field models available in simulations.
enum RadiationPressureType { cannon_ball }
List of radiation pressure model types.
enum RotationModelType { simple_rotation_model, spice_rotation_model, gcrs_to_itrs_rotation_model }
List of rotation models available in simulations.
enum SphericalHarmonicsModel {
customModel, egm96, ggm02c, ggm02s,
glgm3150, lpe200, jgmro120d
}
Spherical harmonics models supported by Tudat.
enum ThrustDirectionGuidanceTypes {
colinear_with_state_segment_thrust_direction, thrust_direction_from_existing_body_orientation, custom_thrust_direction, custom_thrust_orientation,
mee_costate_based_thrust_direction
}
List of available types of thust direction guidance.
enum ThrustFrames { unspecified_thurst_frame = -1, inertial_thurst_frame = 0, lvlh_thrust_frame = 1 }
Enum defining identifiers of frames in which a user-specifief thrust is defined.
enum ThrustMagnitudeTypes { constant_thrust_magnitude, from_engine_properties_thrust_magnitude, thrust_magnitude_from_time_function, thrust_magnitude_from_dependent_variables }
List of available types of thust magnitude types.
enum WindModelTypes { custom_wind_model }
List of wind models available in simulations.
Functions
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< TimeType, Eigen::MatrixXd > calculateCovarianceMatrixAsFunctionOfTime (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType &measurementData, const Eigen::MatrixXd &typeAndLinkSortedNormalizedInformationMatrix, const Eigen::VectorXd &normalizationFactors, const double outputTimeStep, const Eigen::VectorXd &diagonalOfWeightMatrix, const Eigen::MatrixXd &normalizedInverseAPrioriCovariance)
Function to create a map of the estimation covariance as a function of time.
template<typename ObservationScalarType = double, typename TimeType = double, typename StateScalarType = ObservationScalarType, typename ParameterScalarType = double>
std::map< TimeType, Eigen::MatrixXd > calculateCovarianceMatrixAsFunctionOfTime (const std::shared_ptr< PodInput< ObservationScalarType, TimeType > > &podInputData, const std::shared_ptr< PodOutput< ParameterScalarType > > &podOutputData, const double outputTimeStep)
Function to create a map of the estimation covariance as a function of time.
std::shared_ptr< ParameterizedThrustMagnitudeSettings > createAccelerationLimitedParameterizedThrustMagnitudeSettings (const NamedBodyMap &bodyMap, const std::string nameOfBodyWithGuidance, const double maximumAcceleration, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double specificImpulse, const std::string nameOfCentralBody="")
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration.
std::shared_ptr< ParameterizedThrustMagnitudeSettings > createAccelerationLimitedParameterizedThrustMagnitudeSettings (const NamedBodyMap &bodyMap, const std::string nameOfBodyWithGuidance, const double maximumAcceleration, const std::string thrustMagnitudeDataFile, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double specificImpulse, const std::string nameOfCentralBody="")
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration.
std::shared_ptr< ParameterizedThrustMagnitudeSettings > createAccelerationLimitedParameterizedThrustMagnitudeSettings (const NamedBodyMap &bodyMap, const std::string nameOfBodyWithGuidance, const double maximumAcceleration, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::shared_ptr< interpolators::Interpolator< double, double > > specificImpulseInterpolator, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables, const std::string nameOfCentralBody="")
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration.
std::shared_ptr< ParameterizedThrustMagnitudeSettings > createAccelerationLimitedParameterizedThrustMagnitudeSettings (const NamedBodyMap &bodyMap, const std::string nameOfBodyWithGuidance, const double maximumAcceleration, const std::string thrustMagnitudeDataFile, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::string specificImpulseDataFile, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables, const std::string nameOfCentralBody="")
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration.
std::shared_ptr< AccelerationModel< Eigen::Vector3d > > createAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string &nameOfCentralBody, const NamedBodyMap &bodyMap)
Function to create acceleration model object.
basic_astrodynamics::AccelerationMap createAccelerationModelsMap (const NamedBodyMap &bodyMap, const SelectedAccelerationMap &selectedAccelerationPerBody, const std::map< std::string, std::string > &centralBodies)
Function to create a set of acceleration models from a map of bodies and acceleration model types.
basic_astrodynamics::AccelerationMap createAccelerationModelsMap (const NamedBodyMap &bodyMap, const SelectedAccelerationMap &selectedAccelerationPerBody, const std::vector< std::string > &propagatedBodies, const std::vector< std::string > &centralBodies)
Function to create acceleration models from a map of bodies and acceleration model types.
template<typename InitialStateParameterType >
orbit_determination::StateDerivativePartialsMap createAccelerationPartialsMap (const basic_astrodynamics::AccelerationMap &accelerationMap, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > > parametersToEstimate)
This function creates acceleration partial objects for translational dynamics.
template orbit_determination::StateDerivativePartialsMap createAccelerationPartialsMap< double > (const basic_astrodynamics::AccelerationMap &accelerationMap, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< double > > parametersToEstimate)
template orbit_determination::StateDerivativePartialsMap createAccelerationPartialsMap< long double > (const basic_astrodynamics::AccelerationMap &accelerationMap, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< long double > > parametersToEstimate)
std::shared_ptr< aerodynamics::AerodynamicAcceleration > createAerodynamicAcceleratioModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration)
Function to create an aerodynamic acceleration model.
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > createAerodynamicCoefficientInterface (const std::shared_ptr< AerodynamicCoefficientSettings > coefficientSettings, const std::string &body)
Function to create and aerodynamic coefficient interface.
std::shared_ptr< aerodynamics::AerodynamicTorque > createAerodynamicTorqueModel (const std::shared_ptr< simulation_setup::Body > bodyUndergoingTorque, const std::shared_ptr< simulation_setup::Body > bodyExertingTorque, const std::string &nameOfBodyUndergoingTorque, const std::string &nameOfBodyExertingTorque)
Function to create an aerodynamic torque model.
template<typename InitialStateParameterType = double>
std::shared_ptr< acceleration_partials::AccelerationPartial > createAnalyticalAccelerationPartial (std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, const std::pair< std::string, std::shared_ptr< simulation_setup::Body > > acceleratedBody, const std::pair< std::string, std::shared_ptr< simulation_setup::Body > > acceleratingBody, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > > parametersToEstimate=std::shared_ptr< estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > >())
Function to create a single acceleration partial derivative object.
template std::shared_ptr< acceleration_partials::AccelerationPartial > createAnalyticalAccelerationPartial< double > (std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, const std::pair< std::string, std::shared_ptr< simulation_setup::Body > > acceleratedBody, const std::pair< std::string, std::shared_ptr< simulation_setup::Body > > acceleratingBody, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< double > > parametersToEstimate)
std::shared_ptr< aerodynamics::AtmosphereModel > createAtmosphereModel (const std::shared_ptr< AtmosphereSettings > atmosphereSettings, const std::string &body)
Function to create an atmosphere model.
std::shared_ptr< aerodynamics::AtmosphericFlightConditions > createAtmosphericFlightConditions (const std::shared_ptr< Body > bodyWithFlightConditions, const std::shared_ptr< Body > centralBody, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::function< double() > angleOfAttackFunction, const std::function< double() > angleOfSideslipFunction, const std::function< double() > bankAngleFunction, const std::function< void(const double) > angleUpdateFunction)
Function to create an atmospheric flight conditions object.
NamedBodyMap createBodies (const std::map< std::string, std::shared_ptr< BodySettings > > &bodySettings)
Function to create a map of bodies objects.
std::shared_ptr< ephemerides::Ephemeris > createBodyEphemeris (const std::shared_ptr< EphemerisSettings > ephemerisSettings, const std::string &bodyName)
Function to create a ephemeris model.
std::shared_ptr< basic_astrodynamics::BodyShapeModel > createBodyShapeModel (const std::shared_ptr< BodyShapeSettings > shapeSettings, const std::string &body)
Function to create a body shape model.
std::shared_ptr< CannonBallRadiationPressureAcceleration > createCannonballRadiationPressureAcceleratioModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration)
Function to create a cannonball radiation pressure acceleration model.
std::shared_ptr< CentralGravitationalAccelerationModel3d > createCentralGravityAcceleratioModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const bool useCentralBodyFixedFrame)
Function to create central gravity acceleration model.
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > createConstantCoefficientAerodynamicCoefficientInterface (const Eigen::Vector3d constantForceCoefficient, const Eigen::Vector3d constantMomentCoefficient, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const bool areCoefficientsInAerodynamicFrame, const bool areCoefficientsInNegativeAxisDirection)
Function to create an aerodynamic coefficient interface containing constant coefficients.
std::shared_ptr< aerodynamics::ControlSurfaceIncrementAerodynamicInterface > createControlSurfaceIncrementAerodynamicCoefficientInterface (const std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > coefficientSettings, const std::string &body)
Function to tabulated control surface aerodynamic coefficients from associated settings object.
std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > createDirectGravitationalAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const std::string &nameOfCentralBody, const bool isCentralBody)
Function to create a direct (i.e. not third-body) gravitational acceleration (of any type)
std::shared_ptr< gravitation::DirectTidalDissipationAcceleration > createDirectTidalDissipationAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create a direct tical acceleration model, according to approach of Lainey et al. (2007, 2009, ...)
std::shared_ptr< EstimatableParameter< double > > createDoubleParameterToEstimate (const std::shared_ptr< EstimatableParameterSettings > &doubleParameterName, const NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationModelMap)
Function to create an interface object for estimating a parameter defined by a single double value.
std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > createDoubleParameterToEstimate (const std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > &doubleParameterName, const NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationModelMap=basic_astrodynamics::AccelerationMap())
Function to create an interface object for estimating a parameter defined by a single double value.
std::shared_ptr< EmpiricalAcceleration > createEmpiricalAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create empirical acceleration model.
std::shared_ptr< aerodynamics::FlightConditions > createFlightConditions (const std::shared_ptr< Body > bodyWithFlightConditions, const std::shared_ptr< Body > centralBody, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration)
Function to create a flight conditions object.
std::shared_ptr< AccelerationModel< Eigen::Vector3d > > createGravitationalAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string &nameOfCentralBody)
Function to create gravitational acceleration (of any type)
std::shared_ptr< gravitation::GravityFieldModel > createGravityFieldModel (const std::shared_ptr< GravityFieldSettings > gravityFieldSettings, const std::string &body, const NamedBodyMap &bodyMap, const std::vector< std::shared_ptr< GravityFieldVariationSettings > > &gravityFieldVariationSettings)
Function to create a gravity field model.
std::shared_ptr< gravitation::GravityFieldVariationsSet > createGravityFieldModelVariationsSet (const std::string &body, const NamedBodyMap &bodyMap, const std::vector< std::shared_ptr< GravityFieldVariationSettings > > &gravityFieldVariationSettings)
Function to create a set of gravity field variations, stored in the associated interface class.
std::shared_ptr< gravitation::GravityFieldVariations > createGravityFieldVariationsModel (const std::shared_ptr< GravityFieldVariationSettings > gravityFieldVariationSettings, const std::string body, const NamedBodyMap &bodyMap)
Function to create a single gravity field variation object.
void createGroundStation (const std::shared_ptr< Body > &body, const std::string groundStationName, const std::shared_ptr< ground_stations::GroundStationState > groundStationState)
Function to create a ground station from pre-defined station state object, and add it to a Body object.
void createGroundStation (const std::shared_ptr< Body > &body, const std::string groundStationName, const Eigen::Vector3d groundStationPosition, const coordinate_conversions::PositionElementTypes positionElementType)
Function to create a ground station and add it to a Body object.
void createGroundStation (const std::shared_ptr< Body > &body, const std::string &bodyName, const std::shared_ptr< GroundStationSettings > groundStationSettings)
void createGroundStations (const NamedBodyMap &bodyMap, const std::map< std::pair< std::string, std::string >, Eigen::Vector3d > &groundStationsWithPosition, const coordinate_conversions::PositionElementTypes positionElementType)
Function to create a set of ground stations and add them to the corresponding Body objects.
std::shared_ptr< SphericalHarmonicsGravityFieldSettings > createHomogeneousTriAxialEllipsoidGravitySettings (const double axisA, const double axisB, const double axisC, const double ellipsoidDensity, const int maximumDegree, const int maximumOrder, const std::string &associatedReferenceFrame)
Function to create gravity field settings for a homogeneous triaxial ellipsoid.
template<typename InitialStateParameterType = double>
std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > createInitialDynamicalStateParameterToEstimate (const NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > &parameterSettings)
Function to create interface object for estimating parameters representing an initial dynamical state.
std::shared_ptr< basic_astrodynamics::MassRateModel > createMassRateModel (const std::string &bodyWithMassRate, const std::shared_ptr< MassRateModelSettings > massRateModelSettings, const NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationModels)
Function to create a mass rate model.
basic_astrodynamics::MassRateModelMap createMassRateModelsMap (const NamedBodyMap &bodyMap, const SelectedMassRateModelMap &massRateModelSettings, const basic_astrodynamics::AccelerationMap &accelerationModels)
Function to create a list of mass rate models for a list of bodies.
std::shared_ptr< gravitation::MutualSphericalHarmonicsGravitationalAccelerationModel > createMutualSphericalHarmonicsGravityAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const bool useCentralBodyFixedFrame, const bool acceleratedBodyIsCentralBody)
Function to create mutual spherical harmonic gravity acceleration model.
std::shared_ptr< ParameterizedThrustMagnitudeSettings > createParameterizedThrustMagnitudeSettings (const std::shared_ptr< ThrustInputParameterGuidance > thrustInputParameterGuidance, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::shared_ptr< interpolators::Interpolator< double, double > > specificImpulseInterpolator, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables)
Function to create thrust magnitude settings from guidance input and tables.
std::shared_ptr< ParameterizedThrustMagnitudeSettings > createParameterizedThrustMagnitudeSettings (const std::shared_ptr< ThrustInputParameterGuidance > thrustInputParameterGuidance, const std::string thrustMagnitudeDataFile, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::string specificImpulseDataFile, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables)
Function to create thrust magnitude settings from guidance input and tables.
std::shared_ptr< ParameterizedThrustMagnitudeSettings > createParameterizedThrustMagnitudeSettings (const std::shared_ptr< ThrustInputParameterGuidance > thrustInputParameterGuidance, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double constantSpecificImpulse)
Function to create thrust magnitude settings from guidance input and tables, with constant specific impulse.
std::shared_ptr< ParameterizedThrustMagnitudeSettings > createParameterizedThrustMagnitudeSettings (const std::shared_ptr< ThrustInputParameterGuidance > thrustInputParameterGuidance, const std::string thrustMagnitudeDataFile, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double constantSpecificImpulse)
Function to create thrust magnitude settings from guidance input and tables, with constant specific impulse.
template<typename InitialStateParameterType = double>
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > > createParametersToEstimate (const std::vector< std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > > &parameterNames, const NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationModelMap=basic_astrodynamics::AccelerationMap())
Function to create the interface object for estimating any number/type of parameters.
std::shared_ptr< electro_magnetism::RadiationPressureInterface > createRadiationPressureInterface (const std::shared_ptr< RadiationPressureInterfaceSettings > radiationPressureInterfaceSettings, const std::string &bodyName, const NamedBodyMap &bodyMap)
Function to create a radiation pressure interface.
std::shared_ptr< relativity::RelativisticAccelerationCorrection > createRelativisticCorrectionAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const NamedBodyMap &bodyMap)
Function to create an orbiter relativistic correction acceleration model.
std::shared_ptr< ephemerides::RotationalEphemeris > createRotationModel (const std::shared_ptr< RotationModelSettings > rotationModelSettings, const std::string &body)
Function to create a rotation model.
std::shared_ptr< gravitation::SecondDegreeGravitationalTorqueModel > createSecondDegreeGravitationalTorqueModel (const std::shared_ptr< simulation_setup::Body > bodyUndergoingTorque, const std::shared_ptr< simulation_setup::Body > bodyExertingTorque, const std::string &nameOfBodyUndergoingTorque, const std::string &nameOfBodyExertingTorque)
Function to create a second-degree gravitational torque.
template<typename StateScalarType = double, typename TimeType = double>
std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > createSingleArcDynamicsSimulator (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< propagators::PropagatorSettings< StateScalarType > > propagatorSettings, const bool areEquationsOfMotionToBeIntegrated=true, const bool clearNumericalSolutions=true, const bool setIntegratedResult=true)
template<typename StateScalarType = double, typename TimeType = double, typename ParameterType = double>
std::shared_ptr< propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > createSingleArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< propagators::PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const bool integrateDynamicalAndVariationalEquationsConcurrently=1, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > variationalOnlyIntegratorSettings=std::shared_ptr< numerical_integrators::IntegratorSettings< double > >(), const bool clearNumericalSolution=1, const bool integrateEquationsOnCreation=1)
std::shared_ptr< gravitation::SphericalHarmonicsGravitationalAccelerationModel > createSphericalHarmonicsGravityAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const bool useCentralBodyFixedFrame)
Function to create spherical harmonic gravity acceleration model.
template<typename StateScalarType , typename TimeType >
std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > createStateDerivativePartials (const std::unordered_map< propagators::IntegratedStateType, std::vector< std::shared_ptr< propagators::SingleStateTypeDerivative< StateScalarType, TimeType > > > > stateDerivativeModels, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate)
Function to create a set of state derivative partial objects.
template std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > createStateDerivativePartials< double, double > (const std::unordered_map< propagators::IntegratedStateType, std::vector< std::shared_ptr< propagators::SingleStateTypeDerivative< double, double > > > > stateDerivativeModels, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< double > > parametersToEstimate)
template<unsigned int NumberOfDimensions>
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > createTabulatedCoefficientAerodynamicCoefficientInterface (const std::vector< std::vector< double > > independentVariables, const boost::multi_array< Eigen::Vector3d, static_cast< size_t >(NumberOfDimensions) > forceCoefficients, const boost::multi_array< Eigen::Vector3d, static_cast< size_t >(NumberOfDimensions) > momentCoefficients, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const bool areCoefficientsInAerodynamicFrame=false, const bool areCoefficientsInNegativeAxisDirection=true, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings=nullptr)
Factory function for tabulated (N-D independent variables) aerodynamic coefficient interface.
template<unsigned int NumberOfDimensions>
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > createTabulatedCoefficientAerodynamicCoefficientInterface (const std::shared_ptr< AerodynamicCoefficientSettings > coefficientSettings, const std::string &body)
Factory function for tabulated aerodynamic coefficient interface from coefficient settings.
template<unsigned int NumberOfDimensions>
std::shared_ptr< aerodynamics::ControlSurfaceIncrementAerodynamicInterface > createTabulatedControlSurfaceIncrementAerodynamicCoefficientInterface (const std::vector< std::vector< double > > independentVariables, const boost::multi_array< Eigen::Vector3d, static_cast< size_t >(NumberOfDimensions) > forceCoefficients, const boost::multi_array< Eigen::Vector3d, static_cast< size_t >(NumberOfDimensions) > momentCoefficients, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings from user-defined coefficients.
template<unsigned int NumberOfDimensions>
std::shared_ptr< aerodynamics::ControlSurfaceIncrementAerodynamicInterface > createTabulatedControlSurfaceIncrementAerodynamicCoefficientInterface (const std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > coefficientSettings, const std::string &body)
Function to create tabulated control surface aerodynamic coefficients from associated settings object.
std::shared_ptr< gravitation::ThirdBodyCentralGravityAcceleration > createThirdBodyCentralGravityAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::string &nameOfCentralBody)
Function to create a third body central gravity acceleration model.
std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > createThirdBodyGravitationalAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::string &nameOfCentralBody, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create a third-body gravitational acceleration (of any type)
std::shared_ptr< gravitation::ThirdBodyMutualSphericalHarmonicsGravitationalAccelerationModel > createThirdBodyMutualSphericalHarmonicGravityAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::string &nameOfCentralBody, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create a third body mutual spheric harmonic gravity acceleration model.
std::shared_ptr< gravitation::ThirdBodySphericalHarmonicsGravitationalAccelerationModel > createThirdBodySphericalHarmonicGravityAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string &nameOfBodyUndergoingAcceleration, const std::string &nameOfBodyExertingAcceleration, const std::string &nameOfCentralBody, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create a third body spheric harmonic gravity acceleration model.
std::shared_ptr< propulsion::ThrustAcceleration > createThrustAcceleratioModel (const std::shared_ptr< AccelerationSettings > accelerationSettings, const NamedBodyMap &bodyMap, const std::string &nameOfBodyUndergoingThrust)
Function to create a thrust acceleration model.
std::shared_ptr< propulsion::BodyFixedForceDirectionGuidance > createThrustGuidanceModel (const std::shared_ptr< ThrustDirectionGuidanceSettings > thrustDirectionGuidanceSettings, const NamedBodyMap &bodyMap, const std::string &nameOfBodyWithGuidance, const std::function< Eigen::Vector3d() > bodyFixedThrustOrientation, std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > &magnitudeUpdateSettings)
Function to create the object determining the direction of the thrust acceleration.
std::shared_ptr< propulsion::ThrustMagnitudeWrapper > createThrustMagnitudeWrapper (const std::shared_ptr< ThrustMagnitudeSettings > thrustMagnitudeSettings, const NamedBodyMap &bodyMap, const std::string &nameOfBodyWithGuidance, std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > &magnitudeUpdateSettings)
Function to create a wrapper object that computes the thrust magnitude.
std::vector< std::shared_ptr< orbit_determination::TidalLoveNumberPartialInterface > > createTidalLoveNumberInterfaces (const NamedBodyMap &bodyMap, const std::string &acceleratingBodyName)
Function to create a list of objects that can be used to compute partials of tidal gravity field variations.
std::shared_ptr< basic_astrodynamics::TorqueModel > createTorqueModel (const std::shared_ptr< simulation_setup::Body > bodyUndergoingTorque, const std::shared_ptr< simulation_setup::Body > bodyExertingTorque, const std::shared_ptr< TorqueSettings > torqueSettings, const std::string &nameOfBodyUndergoingTorque, const std::string &nameOfBodyExertingTorque)
Function to create torque model object.
basic_astrodynamics::TorqueModelMap createTorqueModelsMap (const NamedBodyMap &bodyMap, const SelectedTorqueMap &selectedTorquePerBody)
Function to create torque models from a map of bodies and torque model settings.
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > createUnivariateTabulatedCoefficientAerodynamicCoefficientInterface (const std::shared_ptr< AerodynamicCoefficientSettings > coefficientSettings, const std::string &body)
Factory function for tabulated (1-D independent variables) aerodynamic coefficient interface from coefficient settings.
std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > createVectorParameterToEstimate (const std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > &vectorParameterName, const NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationModelMap=basic_astrodynamics::AccelerationMap())
Function to create an interface object for estimating a parameter defined by a list of double values.
std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > createVectorParameterToEstimate (const std::shared_ptr< EstimatableParameterSettings > &vectorParameterName, const NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationModelMap)
Function to create an interface object for estimating a parameter defined by a list of double values.
std::shared_ptr< aerodynamics::WindModel > createWindModel (const std::shared_ptr< WindModelSettings > windSettings, const std::string &body)
Function to create a wind model.
std::vector< std::pair< std::string, std::shared_ptr< BodySettings > > > determineBodyCreationOrder (const std::map< std::string, std::shared_ptr< BodySettings > > &bodySettings)
Function that determines the order in which bodies are to be created.
template<typename TimeType = double, typename StateScalarType = double>
std::pair< std::shared_ptr< PodOutput< StateScalarType > >, Eigen::VectorXd > determinePostfitParameterInfluence (const NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< propagators::PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > perturbedParameterSettings, const double simulatedObservationInterval, const std::vector< double > parameterPerturbations, const std::vector< int > parameterIndices, const int numberOfIterations=2)
Function that determines how well the translational dynamics of N bodies can absorb the influence of a change in an environmental parameter value.
void from_json (const nlohmann::json &jsonObject, RadiationPressureType &radiationPressureType)
Convert json to RadiationPressureType.
void from_json (const nlohmann::json &jsonObject, BodyShapeTypes &bodyShapeType)
Convert json to BodyShapeTypes.
void from_json (const nlohmann::json &jsonObject, RotationModelType &rotationModelType)
Convert json to RotationModelType.
void from_json (const nlohmann::json &jsonObject, GravityFieldType &gravityFieldType)
Convert json to GravityFieldType.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< TorqueSettings > &torqueSettings)
Create a shared pointer to a TorqueSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, ThrustDirectionGuidanceTypes &thrustDirectionType)
Convert json to ThrustDirectionGuidanceTypes.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< MassRateModelSettings > &massRateModelSettings)
Create a shared pointer to a MassRateModelSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< RadiationPressureInterfaceSettings > &radiationPressureInterfaceSettings)
Create a json object from a shared pointer to a RadiationPressureInterfaceSettings object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< ThrustDirectionGuidanceSettings > &directionSettings)
Create a shared pointer to a ThrustDirectionGuidanceSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< BodyShapeSettings > &bodyShapeSettings)
Create a shared pointer to a BodyShapeSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< RotationModelSettings > &rotationModelSettings)
Create a shared pointer to a RotationModelSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< GravityFieldVariationSettings > &variationSettings)
Create a shared pointer to a GravityFieldVariationSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, SphericalHarmonicsModel &sphericalHarmonicsModel)
Convert json to SphericalHarmonicsModel.
void from_json (const nlohmann::json &jsonObject, AerodynamicCoefficientTypes &aerodynamicCoefficientType)
Convert json to AerodynamicCoefficientTypes.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< AtmosphereSettings > &atmosphereSettings)
Create a shared pointer to a AtmosphereSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, EphemerisType &ephemerisType)
Convert json to EphemerisType.
void from_json (const nlohmann::json &jsonObject, ThrustMagnitudeTypes &thrustMagnitudeType)
Convert json to ThrustMagnitudeTypes.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< GravityFieldSettings > &gravityFieldSettings)
Create a shared pointer to a GravityFieldSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, AtmosphereTypes &atmosphereType)
Convert json to AtmosphereTypes.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< EphemerisSettings > &ephemerisSettings)
Create a shared pointer to a EphemerisSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< AccelerationSettings > &accelerationSettings)
Create a shared pointer to a AccelerationSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< ModelInterpolationSettings > &modelInterpolationSettings)
Create a shared pointer to a ModelInterpolationSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< ThrustMagnitudeSettings > &magnitudeSettings)
Create a shared pointer to a ThrustMagnitudeSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, ThrustFrames &thrustFrameType)
Convert json to ThrustFrames.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< AerodynamicCoefficientSettings > &aerodynamicSettings)
Create a json object from a shared pointer to a AerodynamicCoefficientSettings object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< ThrustAccelerationSettings > &thrustAccelerationSettings)
Create a shared pointer to a ThrustAccelerationSettings object from a json object.
template<typename StateScalarType = double, typename TimeType = double>
Eigen::Matrix< StateScalarType, 3, 1 > getBodyAccelerationInBaseFramefromNumericalDifferentiation (const std::shared_ptr< Body > bodyWithAcceleration, const TimeType nominalEvalutationTime)
Function to compute the acceleration of a body, using its ephemeris and finite differences.
std::function< Eigen::Vector3d() > getBodyFixedThrustDirection (const std::shared_ptr< ThrustMagnitudeSettings > thrustMagnitudeSettings, const NamedBodyMap &bodyMap, const std::string bodyName)
Function to create a function that returns the thrust direction in the body-fixed frame.
Eigen::Vector3d getCombinedThrustDirection (const std::vector< std::function< Eigen::Vector3d()> > &thrustDirections, const std::vector< std::function< double()> > &thrustMagnitudes)
Function to retrieve the effective thrust direction from a set of thrust sources.
template<typename ObservationScalarType = double, typename TimeType = double>
std::pair< std::vector< int >, std::map< observation_models::LinkEnds, int > > getConcatenatedGroundStationIndex (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType &measurementData)
Function to create a single vector of link end indices for all observations.
template<typename ObservationScalarType = double, typename TimeType = double>
Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > getConcatenatedMeasurementVector (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType &measurementData)
Function to create a single vector of observations from full observation input data.
template<typename ObservationScalarType = double, typename TimeType = double>
std::vector< int > getConcatenatedObservableTypes (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType &measurementData)
Function to create a single vector of observable types for all observations.
template<typename ObservationScalarType = double, typename TimeType = double>
std::vector< TimeType > getConcatenatedTimeVector (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType &measurementData)
Function to create a single vector of times from all observation times.
template<typename ObservationScalarType = double>
Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > getConcatenatedWeightsVector (const typename std::map< observation_models::ObservableType, std::map< observation_models::LinkEnds, Eigen::VectorXd > > &weightsData)
Function to create a single vector of observation weights from weights sorted by link ends/observation type.
template Eigen::Matrix< double, Eigen::Dynamic, 1 > getConcatenatedWeightsVector< double > (const typename std::map< observation_models::ObservableType, std::map< observation_models::LinkEnds, Eigen::VectorXd > > &weightsData)
template Eigen::Matrix< long double, Eigen::Dynamic, 1 > getConcatenatedWeightsVector< long double > (const typename std::map< observation_models::ObservableType, std::map< observation_models::LinkEnds, Eigen::VectorXd > > &weightsData)
std::shared_ptr< AtmosphereSettings > getDefaultAtmosphereModelSettings (const std::string &bodyName, const double initialTime, const double finalTime)
Function to create default settings for a body's atmosphere model.
std::map< std::string, std::shared_ptr< BodySettings > > getDefaultBodySettings (const std::vector< std::string > &bodies, const double initialTime, const double finalTime, const double timeStep)
Function to create default settings from which to create a set of body objects.
std::map< std::string, std::shared_ptr< BodySettings > > getDefaultBodySettings (const std::vector< std::string > &bodies)
Function to create default settings from which to create a set of body objects using the code in createBodies.h/.cpp.
std::shared_ptr< BodyShapeSettings > getDefaultBodyShapeSettings (const std::string &bodyName, const double initialTime, const double finalTime)
Function to create default settings for a body's shape model.
std::shared_ptr< EphemerisSettings > getDefaultEphemerisSettings (const std::string &bodyName)
Function to create default settings for a body's ephemeris.
std::shared_ptr< EphemerisSettings > getDefaultEphemerisSettings (const std::string &bodyName, const double initialTime, const double finalTime, const double timeStep)
Function to create default settings for a body's ephemeris.
std::shared_ptr< GravityFieldSettings > getDefaultGravityFieldSettings (const std::string &bodyName, const double initialTime, const double finalTime)
Function to create default settings for a body's gravity field model.
std::shared_ptr< RotationModelSettings > getDefaultRotationModelSettings (const std::string &bodyName, const double initialTime, const double finalTime)
Function to create default settings from which to create a single body object.
std::shared_ptr< BodySettings > getDefaultSingleBodySettings (const std::string &bodyName, const double initialTime, const double finalTime, const double timeStep)
Function to create default settings for a body's rotation model.
std::string getGlobalFrameOrigin (const NamedBodyMap &bodyMap)
Function ot retrieve the common global translational state origin of the environment.
void getOccultingBodiesInformation (const NamedBodyMap &bodyMap, const std::vector< std::string > &occultingBodies, std::vector< std::function< Eigen::Vector3d() > > &occultingBodyPositions, std::vector< double > &occultingBodyRadii)
Function to obtain (by reference) the position functions and radii of occulting bodies.
std::string getPathForSphericalHarmonicsModel (const SphericalHarmonicsModel sphericalHarmonicsModel)
Get the path of the SH file for a SH model.
std::vector< std::function< double() > > getPropulsionInputVariables (const std::shared_ptr< Body > bodyWithGuidance, const std::vector< propulsion::ThrustIndependentVariables > independentVariables, const std::vector< std::function< double() > > guidanceInputFunctions)
Function to create a list of functions that (compute and) return independent variables for thrust.
std::string getReferenceFrameForSphericalHarmonicsModel (const SphericalHarmonicsModel sphericalHarmonicsModel)
Get the associated reference frame for a SH model.
std::pair< double, double > getSafeInterpolationInterval (const std::shared_ptr< ephemerides::Ephemeris > ephemerisModel)
Function that retrieves the time interval at which an ephemeris can be safely interrogated.
template<typename ObservationScalarType = double, typename TimeType = double>
std::pair< Eigen::MatrixXd, std::vector< TimeType > > getTimeOrderedInformationMatrix (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType &measurementData, const Eigen::MatrixXd &typeAndLinkSortedInformationMatrix, std::vector< int > &timeOrder)
Function to sort the information matrix by the time of the associated observations.
double multiplyMaximumThrustByScalingFactor (const std::function< double(const std::vector< double > &) > maximumThrustFunction, const std::function< double() > maximumThrustMultiplier, const std::vector< double > &maximumThrustIndependentVariables)
Interface function to multiply a maximum thrust by a multiplier to obtain the actual thrust.
SelectedAccelerationList orderSelectedAccelerationMap (const SelectedAccelerationMap &selectedAccelerationsPerBody)
Function to put SelectedAccelerationMap in correct order, to ensure correct model creation.
std::shared_ptr< interpolators::Interpolator< double, double > > readCoefficientInterpolatorFromFile (const std::string coefficientFile)
Function to read a thrust or specific impulse interpolator from a file.
template<unsigned int NumberOfDimensions>
std::shared_ptr< AerodynamicCoefficientSettings > readGivenSizeTabulatedAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::map< int, std::string > momentCoefficientFiles, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame=true, const bool areCoefficientsInNegativeAxisDirection=true, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings=nullptr)
Function to create aerodynamic coefficient settings from coefficients stored in data files.
template<unsigned int NumberOfDimensions>
std::shared_ptr< AerodynamicCoefficientSettings > readGivenSizeTabulatedAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const double referenceArea, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame=true, const bool areCoefficientsInNegativeAxisDirection=true, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings=nullptr)
Function to create aerodynamic coefficient settings from coefficients stored in data files.
template<unsigned int NumberOfIndependentVariables>
std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > readGivenSizeTabulatedControlIncrementAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::map< int, std::string > momentCoefficientFiles, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings fom coefficients stored in data files.
template<unsigned int NumberOfIndependentVariables>
std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > readGivenSizeTabulatedControlIncrementAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings fom coefficients stored in data files.
std::pair< double, double > readGravityFieldFile (const std::string &fileName, const int maximumDegree, const int maximumOrder, std::pair< Eigen::MatrixXd, Eigen::MatrixXd > &coefficients, const int gravitationalParameterIndex, const int referenceRadiusIndex)
Function to read a gravity field file.
std::shared_ptr< AerodynamicCoefficientSettings > readTabulatedAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::map< int, std::string > momentCoefficientFiles, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame, const bool areCoefficientsInNegativeAxisDirection, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings)
Function to create aerodynamic coefficient settings from coefficients stored in data files.
std::shared_ptr< AerodynamicCoefficientSettings > readTabulatedAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const double referenceArea, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame, const bool areCoefficientsInNegativeAxisDirection, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings)
Function to create aerodynamic coefficient settings from coefficients stored in data files.
std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > readTabulatedControlIncrementAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::map< int, std::string > momentCoefficientFiles, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings fom coefficients stored in data files.
std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > readTabulatedControlIncrementAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings fom coefficients stored in data files.
void resetThrustMagnitudeAndDirectionTime (const std::shared_ptr< propulsion::ThrustMagnitudeWrapper > thrustMagnitudeWrapper, const std::shared_ptr< propulsion::BodyFixedForceDirectionGuidance > thrustDirectionGuidance, const double currentTime)
Function to reset the current time variable of the thrust magnitude and direction wrappers.
template<typename StateScalarType = double, typename TimeType = double>
void setGlobalFrameBodyEphemerides (const NamedBodyMap &bodyMap, const std::string &globalFrameOrigin, const std::string &globalFrameOrientation)
Function to define the global origin and orientation of the reference frame.
void setGuidanceAnglesFunctions (const std::shared_ptr< aerodynamics::AerodynamicGuidance > aerodynamicGuidance, const std::shared_ptr< reference_frames::AerodynamicAngleCalculator > angleCalculator)
Function that must be called to link the AerodynamicGuidance object to the simulation.
void setGuidanceAnglesFunctions (const std::shared_ptr< aerodynamics::AerodynamicGuidance > aerodynamicGuidance, const std::shared_ptr< simulation_setup::Body > bodyWithAngles)
Function that must be called to link the AerodynamicGuidance object to the simulation.
std::shared_ptr< aerodynamics::TrimOrientationCalculator > setTrimmedConditions (const std::shared_ptr< aerodynamics::AtmosphericFlightConditions > flightConditions)
Function to set the angle of attack to trimmed conditions.
std::shared_ptr< aerodynamics::TrimOrientationCalculator > setTrimmedConditions (const std::shared_ptr< Body > bodyWithFlightConditions)
Function to set the angle of attack to trimmed conditions.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< GravityFieldSettings > &gravityFieldSettings)
Create a json object from a shared pointer to a GravityFieldSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< TorqueSettings > &torqueSettings)
Create a json object from a shared pointer to a TorqueSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< MassRateModelSettings > &massRateModelSettings)
Create a json object from a shared pointer to a MassRateModelSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< RadiationPressureInterfaceSettings > &radiationPressureInterfaceSettings)
Create a json object from a shared pointer to a RadiationPressureInterfaceSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< RotationModelSettings > &rotationModelSettings)
Create a json object from a shared pointer to a RotationModelSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< BodyShapeSettings > &bodyShapeSettings)
Create a json object from a shared pointer to a BodyShapeSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< AccelerationSettings > &accelerationSettings)
Create a json object from a shared pointer to a AccelerationSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< AerodynamicCoefficientSettings > &aerodynamicSettings)
Create a json object from a shared pointer to a AerodynamicCoefficientSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< GravityFieldVariationSettings > &variationSettings)
Create a json object from a shared pointer to a GravityFieldVariationSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< AtmosphereSettings > &atmosphereSettings)
Create a json object from a shared pointer to a AtmosphereSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< EphemerisSettings > &ephemerisSettings)
Create a json object from a shared pointer to a EphemerisSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< ThrustDirectionGuidanceSettings > &directionSettings)
Create a json object from a shared pointer to a AccelerationSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< BodySettings > &bodySettings)
Create a json object from a shared pointer to a BodySettings object.
void to_json (nlohmann::json &jsonObject, const RadiationPressureType &radiationPressureType)
Convert RadiationPressureType to json.
void to_json (nlohmann::json &jsonObject, const BodyShapeTypes &bodyShapeType)
Convert BodyShapeTypes to json.
void to_json (nlohmann::json &jsonObject, const RotationModelType &rotationModelType)
Convert RotationModelType to json.
void to_json (nlohmann::json &jsonObject, const GravityFieldType &gravityFieldType)
Convert GravityFieldType to json.
void to_json (nlohmann::json &jsonObject, const ThrustDirectionGuidanceTypes &thrustDirectionType)
Convert ThrustDirectionGuidanceTypes to json.
void to_json (nlohmann::json &jsonObject, const SphericalHarmonicsModel &sphericalHarmonicsModel)
Convert SphericalHarmonicsModel to json.
void to_json (nlohmann::json &jsonObject, const AerodynamicCoefficientTypes &aerodynamicCoefficientType)
Convert AerodynamicCoefficientTypes to json.
void to_json (nlohmann::json &jsonObject, const EphemerisType &ephemerisType)
Convert EphemerisType to json.
void to_json (nlohmann::json &jsonObject, const ThrustMagnitudeTypes &thrustMagnitudeType)
Convert ThrustMagnitudeTypes to json.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< ThrustMagnitudeSettings > &magnitudeSettings)
Create a json object from a shared pointer to a ThrustMagnitudeSettings object.
void to_json (nlohmann::json &jsonObject, const AtmosphereTypes &atmosphereType)
Convert AtmosphereTypes to json.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< ModelInterpolationSettings > &modelInterpolationSettings)
Create a json object from a shared pointer to a ModelInterpolationSettings object.
void to_json (nlohmann::json &jsonObject, const ThrustFrames &thrustFrameType)
Convert ThrustFrames to json.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< ThrustAccelerationSettings > &thrustAccelerationSettings)
Create a json object from a shared pointer to a ThrustAccelerationSettings object.
void updateThrustMagnitudeAndDirection (const std::shared_ptr< propulsion::ThrustMagnitudeWrapper > thrustMagnitudeWrapper, const std::shared_ptr< propulsion::BodyFixedForceDirectionGuidance > thrustDirectionGuidance, const double currentTime)
Function to update the thrust magnitude and direction to current time.
Variables
static std::map< AerodynamicCoefficientTypes, std::string > aerodynamicCoefficientTypes
Map of AerodynamicCoefficientTypes string representations.
static std::map< AtmosphereTypes, std::string > atmosphereTypes
Map of AtmosphereTypes string representations.
static std::map< BodyShapeTypes, std::string > bodyShapeTypes
Map of BodyShapeTypes string representations.
static const std::map< std::string, double > defaultRadiatedPowerValues
Default values for radiation pressure.
static std::map< EphemerisType, std::string > ephemerisTypes
Map of EphemerisTypes string representations.
static std::map< GravityFieldType, std::string > gravityFieldTypes
Map of GravityFieldTypes string representations.
static std::map< RadiationPressureType, std::string > radiationPressureTypes
Map of RadiationPressureTypes string representations.
static std::map< RotationModelType, std::string > rotationModelTypes
Map of RotationModelTypes string representations.
static std::map< SphericalHarmonicsModel, std::string > sphericalHarmonicsModels
Map of SphericalHarmonicsModels string representations.
static std::map< ThrustDirectionGuidanceTypes, std::string > thrustDirectionTypes
Map of ThrustDirectionGuidanceTypes string representations.
static std::map< ThrustFrames, std::string > thrustFrameTypes
Map of ThrustFrames string representations.
static std::map< ThrustMagnitudeTypes, std::string > thrustMagnitudeTypes
Map of ThrustMagnitudeTypes string representations.
static std::vector< AerodynamicCoefficientTypes > unsupportedAerodynamicCoefficientTypes
AerodynamicCoefficientTypes not supported by json_interface.
static std::vector< AtmosphereTypes > unsupportedAtmosphereTypes = { custom_constant_temperature_atmosphere }
AtmosphereTypes not supported by json_interface.
static std::vector< BodyShapeTypes > unsupportedBodyShapeTypes = { }
BodyShapeTypes not supported by json_interface.
static std::vector< EphemerisType > unsupportedEphemerisTypes
EphemerisType not supported by json_interface.
static std::vector< GravityFieldType > unsupportedGravityFieldTypes = { }
GravityFieldType not supported by json_interface.
static std::vector< RadiationPressureType > unsupportedRadiationPressureTypes = { }
RadiationPressureTypes not supported by json_interface.
static std::vector< RotationModelType > unsupportedRotationModelTypes = { }
RotationModelTypes not supported by json_interface.
static std::vector< SphericalHarmonicsModel > unsupportedSphericalHarmonicsModels = { }
SphericalHarmonicsModel not supported by json_interface.
static std::vector< ThrustDirectionGuidanceTypes > unsupportedThrustDirectionTypes
ThrustDirectionGuidanceTypes not supported by json_interface.
static std::vector< ThrustFrames > unsupportedThrustFrameTypes
ThrustFrames not supported by json_interface.
static std::vector< ThrustMagnitudeTypes > unsupportedThrustMagnitudeTypes
ThrustMagnitudeTypes not supported by json_interface.
Typedef Documentation
NamedBodyMap
typedef std::unordered_map< std::string, std::shared_ptr< Body > > tudat::simulation_setup::NamedBodyMap
Definition at line 1245 of file body.h.
SelectedAccelerationMap
typedef std::map< std::string, std::map< std::string, std::vector< std::shared_ptr< AccelerationSettings > > > > tudat::simulation_setup::SelectedAccelerationMap
Typedef defining a list of acceleration settings, set up in the same manner as the AccelerationMap typedef.
Definition at line 502 of file accelerationSettings.h.
SelectedAccelerationList
typedef std::map< std::string, std::vector< std::pair< std::string, std::shared_ptr< AccelerationSettings > > > > tudat::simulation_setup::SelectedAccelerationList
Definition at line 505 of file accelerationSettings.h.
SelectedMassRateModelMap
typedef std::map< std::string, std::vector< std::shared_ptr< MassRateModelSettings > > > tudat::simulation_setup::SelectedMassRateModelMap
Definition at line 112 of file createMassRateModels.h.
SelectedTorqueMap
typedef std::map< std::string, std::map< std::string, std::vector< std::shared_ptr< TorqueSettings > > > > tudat::simulation_setup::SelectedTorqueMap
Definition at line 29 of file createTorqueModel.h.
Enumeration Type Documentation
AerodynamicCoefficientTypes
enum tudat::simulation_setup::AerodynamicCoefficientTypes
List of aerodynamic coefficient models available in simulations. Aerodynamic coefficient models not defined by this given enum cannot be used for automatic model setup.
Enumerator
constant_aerodynamic_coefficients
hypersonic_local_inclincation_coefficients
tabulated_coefficients
Definition at line 35 of file createAerodynamicControlSurfaces.h.
WindModelTypes
enum tudat::simulation_setup::WindModelTypes
List of wind models available in simulations. Wind models not defined by this given enum cannot be used for automatic model setup.
Enumerator
custom_wind_model
Definition at line 39 of file createAtmosphereModel.h.
AtmosphereTypes
enum tudat::simulation_setup::AtmosphereTypes
List of atmosphere models available in simulations. Atmosphere models not defined by this given enum cannot be used for automatic model setup.
Enumerator
exponential_atmosphere
custom_constant_temperature_atmosphere
tabulated_atmosphere
nrlmsise00
Definition at line 133 of file createAtmosphereModel.h.
BodyShapeTypes
enum tudat::simulation_setup::BodyShapeTypes
Enumerator
spherical
spherical_spice
oblate_spheroid
Definition at line 27 of file createBodyShapeModel.h.
EphemerisType
enum tudat::simulation_setup::EphemerisType
List of ephemeris models available in simulations. Ephemeris models not defined by this given enum cannot be used for automatic model setup.
Enumerator
approximate_planet_positions
direct_spice_ephemeris
tabulated_ephemeris
interpolated_spice
constant_ephemeris
kepler_ephemeris
custom_ephemeris
Definition at line 37 of file createEphemeris.h.
GravityFieldType
enum tudat::simulation_setup::GravityFieldType
List of gravity field models available in simulations. Gravity field models not defined by this given enum cannot be used for automatic model setup.
Enumerator
central
central_spice
spherical_harmonic
Definition at line 38 of file createGravityField.h.
SphericalHarmonicsModel
enum tudat::simulation_setup::SphericalHarmonicsModel
Enumerator
customModel
egm96
ggm02c
ggm02s
glgm3150
lpe200
jgmro120d
Definition at line 227 of file createGravityField.h.
RadiationPressureType
enum tudat::simulation_setup::RadiationPressureType
Enumerator
cannon_ball
Definition at line 32 of file createRadiationPressureInterface.h.
RotationModelType
enum tudat::simulation_setup::RotationModelType
List of rotation models available in simulations. Rotation models not defined by this given enum cannot be used for automatic model setup.
Enumerator
simple_rotation_model
spice_rotation_model
gcrs_to_itrs_rotation_model
Definition at line 37 of file createRotationModel.h.
ThrustFrames
enum tudat::simulation_setup::ThrustFrames
Enumerator
unspecified_thurst_frame
inertial_thurst_frame
lvlh_thrust_frame
Definition at line 334 of file accelerationSettings.h.
ThrustDirectionGuidanceTypes
enum tudat::simulation_setup::ThrustDirectionGuidanceTypes
Enumerator
colinear_with_state_segment_thrust_direction
thrust_direction_from_existing_body_orientation
custom_thrust_direction
custom_thrust_orientation
mee_costate_based_thrust_direction
Definition at line 40 of file thrustSettings.h.
ThrustMagnitudeTypes
enum tudat::simulation_setup::ThrustMagnitudeTypes
Enumerator
constant_thrust_magnitude
from_engine_properties_thrust_magnitude
thrust_magnitude_from_time_function
thrust_magnitude_from_dependent_variables
Definition at line 272 of file thrustSettings.h.
Function Documentation
to_json() [1/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< AerodynamicCoefficientSettings > & aerodynamicSettings)
Definition at line 23 of file aerodynamics.cpp.
References aerodynamicCoefficientTypes, tudat::json_interface::assertNonnullptrPointer(), constant_aerodynamic_coefficients, tudat::simulation_setup::AerodynamicCoefficientSettings::getInterpolatorSettings(), tudat::json_interface::handleUnimplementedEnumValue(), tudat::json_interface::isNaN(), tabulated_coefficients, and unsupportedAerodynamicCoefficientTypes.
from_json() [1/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< AerodynamicCoefficientSettings > & aerodynamicSettings)
Definition at line 130 of file aerodynamics.cpp.
References aerodynamicCoefficientTypes, constant_aerodynamic_coefficients, tudat::simulation_setup::AerodynamicCoefficientSettings::getAreCoefficientsInAerodynamicFrame(), tudat::simulation_setup::AerodynamicCoefficientSettings::getAreCoefficientsInNegativeAxisDirection(), tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), tudat::json_interface::isDefined(), readTabulatedAerodynamicCoefficientsFromFiles(), tabulated_coefficients, TUDAT_NAN, and unsupportedAerodynamicCoefficientTypes.
to_json() [2/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const AerodynamicCoefficientTypes & aerodynamicCoefficientType) inline
Definition at line 75 of file aerodynamics.h.
References aerodynamicCoefficientTypes, and tudat::json_interface::stringFromEnum().
from_json() [2/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, AerodynamicCoefficientTypes & aerodynamicCoefficientType) inline
Definition at line 81 of file aerodynamics.h.
References aerodynamicCoefficientTypes, and tudat::json_interface::enumFromString().
to_json() [3/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< AtmosphereSettings > & atmosphereSettings)
Definition at line 23 of file atmosphere.cpp.
References tudat::json_interface::assertNonnullptrPointer(), atmosphereTypes, exponential_atmosphere, tudat::json_interface::handleUnimplementedEnumValue(), nrlmsise00, tabulated_atmosphere, and unsupportedAtmosphereTypes.
from_json() [3/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< AtmosphereSettings > & atmosphereSettings)
Definition at line 81 of file atmosphere.cpp.
References atmosphereTypes, exponential_atmosphere, tudat::simulation_setup::TabulatedAtmosphereSettings::getBoundaryHandling(), tudat::simulation_setup::TabulatedAtmosphereSettings::getDependentVariables(), tudat::simulation_setup::TabulatedAtmosphereSettings::getIndependentVariables(), tudat::simulation_setup::ExponentialAtmosphereSettings::getRatioOfSpecificHeats(), tudat::simulation_setup::TabulatedAtmosphereSettings::getRatioOfSpecificHeats(), tudat::simulation_setup::ExponentialAtmosphereSettings::getSpecificGasConstant(), tudat::simulation_setup::TabulatedAtmosphereSettings::getSpecificGasConstant(), tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), tudat::json_interface::isDefined(), nrlmsise00, tabulated_atmosphere, and unsupportedAtmosphereTypes.
to_json() [4/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const AtmosphereTypes & atmosphereType) inline
Definition at line 99 of file atmosphere.h.
References atmosphereTypes, and tudat::json_interface::stringFromEnum().
from_json() [4/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, AtmosphereTypes & atmosphereType) inline
Definition at line 105 of file atmosphere.h.
References atmosphereTypes, and tudat::json_interface::enumFromString().
to_json() [5/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< BodySettings > & bodySettings)
Definition at line 30 of file body.cpp.
References tudat::json_interface::assignIfNotEmpty(), tudat::json_interface::assignIfNotNaN(), and tudat::json_interface::assignIfNotnullptr().
to_json() [6/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< EphemerisSettings > & ephemerisSettings)
Definition at line 23 of file ephemeris.cpp.
References approximate_planet_positions, tudat::json_interface::assertNonnullptrPointer(), constant_ephemeris, direct_spice_ephemeris, ephemerisTypes, tudat::json_interface::handleUnimplementedEnumValue(), interpolated_spice, kepler_ephemeris, tabulated_ephemeris, and unsupportedEphemerisTypes.
from_json() [5/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< EphemerisSettings > & ephemerisSettings)
Definition at line 116 of file ephemeris.cpp.
References approximate_planet_positions, constant_ephemeris, direct_spice_ephemeris, ephemerisTypes, tudat::simulation_setup::DirectSpiceEphemerisSettings::getConvergeLighTimeAberration(), tudat::simulation_setup::DirectSpiceEphemerisSettings::getCorrectForLightTimeAberration(), tudat::simulation_setup::DirectSpiceEphemerisSettings::getCorrectForStellarAberration(), tudat::simulation_setup::EphemerisSettings::getFrameOrientation(), tudat::simulation_setup::EphemerisSettings::getFrameOrigin(), tudat::simulation_setup::InterpolatedSpiceEphemerisSettings::getInterpolatorSettings(), tudat::simulation_setup::KeplerEphemerisSettings::getRootFinderAbsoluteTolerance(), tudat::simulation_setup::KeplerEphemerisSettings::getRootFinderMaximumNumberOfIterations(), tudat::simulation_setup::InterpolatedSpiceEphemerisSettings::getUseLongDoubleStates(), tudat::simulation_setup::TabulatedEphemerisSettings::getUseLongDoubleStates(), tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), interpolated_spice, tudat::json_interface::isDefined(), kepler_ephemeris, tudat::simulation_setup::InterpolatedSpiceEphemerisSettings::setUseLongDoubleStates(), tudat::simulation_setup::TabulatedEphemerisSettings::setUseLongDoubleStates(), tabulated_ephemeris, TUDAT_NAN, and unsupportedEphemerisTypes.
to_json() [7/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const EphemerisType & ephemerisType) inline
Definition at line 81 of file ephemeris.h.
References ephemerisTypes, and tudat::json_interface::stringFromEnum().
from_json() [6/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, EphemerisType & ephemerisType) inline
Definition at line 87 of file ephemeris.h.
References tudat::json_interface::enumFromString(), and ephemerisTypes.
to_json() [8/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< GravityFieldSettings > & gravityFieldSettings)
Definition at line 21 of file gravityField.cpp.
References tudat::json_interface::assertNonnullptrPointer(), central, central_spice, customModel, tudat::simulation_setup::FromFileSphericalHarmonicsGravityFieldSettings::getSphericalHarmonicsModel(), gravityFieldTypes, tudat::json_interface::handleUnimplementedEnumValue(), spherical_harmonic, and unsupportedGravityFieldTypes.
from_json() [7/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< GravityFieldSettings > & gravityFieldSettings)
Definition at line 104 of file gravityField.cpp.
References central, central_spice, tudat::json_interface::getValue(), gravityFieldTypes, tudat::json_interface::handleUnimplementedEnumValue(), tudat::json_interface::isDefined(), tudat::orbital_element_conversions::radiusIndex, spherical_harmonic, TUDAT_NAN, and unsupportedGravityFieldTypes.
to_json() [9/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const GravityFieldType & gravityFieldType) inline
Definition at line 38 of file gravityField.h.
References gravityFieldTypes, and tudat::json_interface::stringFromEnum().
from_json() [8/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, GravityFieldType & gravityFieldType) inline
Definition at line 44 of file gravityField.h.
References tudat::json_interface::enumFromString(), and gravityFieldTypes.
to_json() [10/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const SphericalHarmonicsModel & sphericalHarmonicsModel) inline
Definition at line 68 of file gravityField.h.
References sphericalHarmonicsModels, and tudat::json_interface::stringFromEnum().
from_json() [9/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, SphericalHarmonicsModel & sphericalHarmonicsModel) inline
Definition at line 74 of file gravityField.h.
References tudat::json_interface::enumFromString(), and sphericalHarmonicsModels.
to_json() [11/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< GravityFieldVariationSettings > & variationSettings)
Definition at line 23 of file gravityFieldVariation.cpp.
References tudat::json_interface::assertNonnullptrPointer(), tudat::gravitation::basic_solid_body, tudat::gravitation::bodyDeformationTypes, tudat::json_interface::handleUnimplementedEnumValue(), tudat::gravitation::tabulated_variation, and tudat::gravitation::unsupportedBodyDeformationTypes.
from_json() [10/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< GravityFieldVariationSettings > & variationSettings)
Definition at line 66 of file gravityFieldVariation.cpp.
References tudat::gravitation::basic_solid_body, tudat::gravitation::bodyDeformationTypes, tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), tudat::gravitation::tabulated_variation, TUDAT_NAN, and tudat::gravitation::unsupportedBodyDeformationTypes.
to_json() [12/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< RadiationPressureInterfaceSettings > & radiationPressureInterfaceSettings)
Definition at line 21 of file radiationPressure.cpp.
References tudat::json_interface::assertNonnullptrPointer(), cannon_ball, tudat::json_interface::handleUnimplementedEnumValue(), radiationPressureTypes, and unsupportedRadiationPressureTypes.
from_json() [11/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< RadiationPressureInterfaceSettings > & radiationPressureInterfaceSettings)
Definition at line 57 of file radiationPressure.cpp.
References cannon_ball, tudat::json_interface::getParentKey(), tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), tudat::json_interface::isDefined(), radiationPressureTypes, TUDAT_NAN, and unsupportedRadiationPressureTypes.
to_json() [13/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const RadiationPressureType & radiationPressureType) inline
Definition at line 34 of file radiationPressure.h.
References radiationPressureTypes, and tudat::json_interface::stringFromEnum().
from_json() [12/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, RadiationPressureType & radiationPressureType) inline
Definition at line 40 of file radiationPressure.h.
References tudat::json_interface::enumFromString(), and radiationPressureTypes.
to_json() [14/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< RotationModelSettings > & rotationModelSettings)
Definition at line 21 of file rotationModel.cpp.
References tudat::json_interface::assertNonnullptrPointer(), gcrs_to_itrs_rotation_model, tudat::json_interface::handleUnimplementedEnumValue(), rotationModelTypes, simple_rotation_model, spice_rotation_model, and unsupportedRotationModelTypes.
from_json() [13/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< RotationModelSettings > & rotationModelSettings)
Definition at line 64 of file rotationModel.cpp.
References gcrs_to_itrs_rotation_model, tudat::json_interface::handleUnimplementedEnumValue(), tudat::basic_astrodynamics::iau_2006, tudat::json_interface::isDefined(), rotationModelTypes, simple_rotation_model, spice_rotation_model, and unsupportedRotationModelTypes.
to_json() [15/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const RotationModelType & rotationModelType) inline
Definition at line 37 of file rotationModel.h.
References rotationModelTypes, and tudat::json_interface::stringFromEnum().
from_json() [14/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, RotationModelType & rotationModelType) inline
Definition at line 43 of file rotationModel.h.
References tudat::json_interface::enumFromString(), and rotationModelTypes.
to_json() [16/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< BodyShapeSettings > & bodyShapeSettings)
Definition at line 21 of file shapeModel.cpp.
References tudat::json_interface::assertNonnullptrPointer(), bodyShapeTypes, tudat::json_interface::handleUnimplementedEnumValue(), oblate_spheroid, spherical, spherical_spice, and unsupportedBodyShapeTypes.
from_json() [15/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< BodyShapeSettings > & bodyShapeSettings)
Definition at line 60 of file shapeModel.cpp.
References bodyShapeTypes, tudat::json_interface::handleUnimplementedEnumValue(), oblate_spheroid, spherical, spherical_spice, and unsupportedBodyShapeTypes.
to_json() [17/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const BodyShapeTypes & bodyShapeType) inline
Definition at line 36 of file shapeModel.h.
References bodyShapeTypes, and tudat::json_interface::stringFromEnum().
from_json() [16/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, BodyShapeTypes & bodyShapeType) inline
Definition at line 42 of file shapeModel.h.
References bodyShapeTypes, and tudat::json_interface::enumFromString().
to_json() [18/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< ModelInterpolationSettings > & modelInterpolationSettings)
Definition at line 110 of file interpolation.cpp.
from_json() [17/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< ModelInterpolationSettings > & modelInterpolationSettings)
Definition at line 126 of file interpolation.cpp.
References tudat::simulation_setup::ModelInterpolationSettings::finalTime_, tudat::json_interface::getValue(), tudat::simulation_setup::ModelInterpolationSettings::initialTime_, tudat::simulation_setup::ModelInterpolationSettings::interpolatorSettings_, and tudat::simulation_setup::ModelInterpolationSettings::timeStep_.
to_json() [19/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< AccelerationSettings > & accelerationSettings)
Definition at line 22 of file acceleration.cpp.
References tudat::basic_astrodynamics::accelerationTypes, tudat::basic_astrodynamics::aerodynamic, tudat::json_interface::assertNonnullptrPointer(), tudat::basic_astrodynamics::cannon_ball_radiation_pressure, tudat::basic_astrodynamics::empirical_acceleration, tudat::json_interface::handleUnimplementedEnumValue(), tudat::basic_astrodynamics::mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::point_mass_gravity, tudat::basic_astrodynamics::relativistic_correction_acceleration, tudat::basic_astrodynamics::spherical_harmonic_gravity, tudat::basic_astrodynamics::third_body_mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::third_body_point_mass_gravity, tudat::basic_astrodynamics::third_body_spherical_harmonic_gravity, tudat::basic_astrodynamics::thrust_acceleration, tudat::basic_astrodynamics::undefined_acceleration, and tudat::basic_astrodynamics::unsupportedAccelerationTypes.
from_json() [18/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< AccelerationSettings > & accelerationSettings)
Definition at line 122 of file acceleration.cpp.
References tudat::basic_astrodynamics::accelerationTypes, tudat::basic_astrodynamics::aerodynamic, tudat::simulation_setup::RelativisticAccelerationCorrectionSettings::calculateDeSitterCorrection_, tudat::simulation_setup::RelativisticAccelerationCorrectionSettings::calculateLenseThirringCorrection_, tudat::simulation_setup::RelativisticAccelerationCorrectionSettings::calculateSchwarzschildCorrection_, tudat::basic_astrodynamics::cannon_ball_radiation_pressure, tudat::simulation_setup::RelativisticAccelerationCorrectionSettings::centralBodyAngularMomentum_, tudat::simulation_setup::EmpiricalAccelerationSettings::constantAcceleration_, tudat::simulation_setup::EmpiricalAccelerationSettings::cosineAcceleration_, tudat::basic_astrodynamics::empirical_acceleration, tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), tudat::simulation_setup::MutualSphericalHarmonicAccelerationSettings::maximumDegreeOfCentralBody_, tudat::simulation_setup::MutualSphericalHarmonicAccelerationSettings::maximumOrderOfCentralBody_, tudat::basic_astrodynamics::mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::point_mass_gravity, tudat::simulation_setup::RelativisticAccelerationCorrectionSettings::primaryBody_, tudat::basic_astrodynamics::relativistic_correction_acceleration, tudat::simulation_setup::EmpiricalAccelerationSettings::sineAcceleration_, tudat::basic_astrodynamics::spherical_harmonic_gravity, tudat::basic_astrodynamics::third_body_mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::third_body_point_mass_gravity, tudat::basic_astrodynamics::third_body_spherical_harmonic_gravity, tudat::basic_astrodynamics::thrust_acceleration, tudat::basic_astrodynamics::undefined_acceleration, and tudat::basic_astrodynamics::unsupportedAccelerationTypes.
to_json() [20/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< MassRateModelSettings > & massRateModelSettings)
Definition at line 21 of file massRateModel.cpp.
References tudat::json_interface::assertNonnullptrPointer(), tudat::json_interface::assignIfNotEmpty(), tudat::basic_astrodynamics::from_thrust_mass_rate_model, tudat::json_interface::handleUnimplementedEnumValue(), tudat::basic_astrodynamics::massRateTypes, and tudat::basic_astrodynamics::unsupportedMassRateType.
from_json() [19/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< MassRateModelSettings > & massRateModelSettings)
Definition at line 51 of file massRateModel.cpp.
References tudat::basic_astrodynamics::from_thrust_mass_rate_model, tudat::json_interface::handleUnimplementedEnumValue(), tudat::basic_astrodynamics::massRateTypes, tudat::basic_astrodynamics::unsupportedMassRateType, tudat::json_interface::updateFromJSON(), and tudat::json_interface::updateFromJSONIfDefined().
to_json() [21/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< ThrustDirectionGuidanceSettings > & directionSettings)
Create a json object from a shared pointer to a ThrustDirectionGuidanceSettings object.
Definition at line 26 of file thrust.cpp.
References tudat::json_interface::assertNonnullptrPointer(), colinear_with_state_segment_thrust_direction, tudat::json_interface::handleUnimplementedEnumValue(), thrust_direction_from_existing_body_orientation, thrustDirectionTypes, and unsupportedThrustDirectionTypes.
from_json() [20/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< ThrustDirectionGuidanceSettings > & directionSettings)
Create a shared pointer to a AccelerationSettings object from a json object.
Definition at line 59 of file thrust.cpp.
References colinear_with_state_segment_thrust_direction, tudat::json_interface::handleUnimplementedEnumValue(), thrust_direction_from_existing_body_orientation, thrustDirectionTypes, and unsupportedThrustDirectionTypes.
to_json() [22/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< ThrustMagnitudeSettings > & magnitudeSettings)
Definition at line 90 of file thrust.cpp.
References tudat::json_interface::assertNonnullptrPointer(), tudat::json_interface::assignIfNotEmpty(), constant_thrust_magnitude, from_engine_properties_thrust_magnitude, tudat::json_interface::handleUnimplementedEnumValue(), thrustMagnitudeTypes, and unsupportedThrustMagnitudeTypes.
from_json() [21/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< ThrustMagnitudeSettings > & magnitudeSettings)
Create a shared pointer to a AccelerationSettings object from a json object.
Definition at line 128 of file thrust.cpp.
References tudat::simulation_setup::ConstantThrustMagnitudeSettings::bodyFixedThrustDirection_, constant_thrust_magnitude, from_engine_properties_thrust_magnitude, tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), thrustMagnitudeTypes, tudat::simulation_setup::ThrustMagnitudeSettings::thrustOriginId_, TUDAT_NAN, unsupportedThrustMagnitudeTypes, and tudat::simulation_setup::FromBodyThrustMagnitudeSettings::useAllEngines_.
to_json() [23/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< ThrustAccelerationSettings > & thrustAccelerationSettings)
Definition at line 162 of file thrust.cpp.
References tudat::json_interface::assignIfNotEmpty(), and tudat::basic_astrodynamics::thrust_acceleration.
from_json() [22/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< ThrustAccelerationSettings > & thrustAccelerationSettings)
Definition at line 189 of file thrust.cpp.
References tudat::json_interface::getValue(), and tudat::json_interface::isDefined().
to_json() [24/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const ThrustDirectionGuidanceTypes & thrustDirectionType) inline
Definition at line 44 of file thrust.h.
References tudat::json_interface::stringFromEnum(), and thrustDirectionTypes.
from_json() [23/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, ThrustDirectionGuidanceTypes & thrustDirectionType) inline
Definition at line 50 of file thrust.h.
References tudat::json_interface::enumFromString(), and thrustDirectionTypes.
to_json() [25/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const ThrustMagnitudeTypes & thrustMagnitudeType) inline
Definition at line 84 of file thrust.h.
References tudat::json_interface::stringFromEnum(), and thrustMagnitudeTypes.
from_json() [24/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, ThrustMagnitudeTypes & thrustMagnitudeType) inline
Definition at line 90 of file thrust.h.
References tudat::json_interface::enumFromString(), and thrustMagnitudeTypes.
to_json() [26/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const ThrustFrames & thrustFrameType) inline
Definition at line 122 of file thrust.h.
References tudat::json_interface::stringFromEnum(), and thrustFrameTypes.
from_json() [25/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, ThrustFrames & thrustFrameType) inline
Definition at line 128 of file thrust.h.
References tudat::json_interface::enumFromString(), and thrustFrameTypes.
to_json() [27/27]
void tudat::simulation_setup::to_json (nlohmann::json & jsonObject, const std::shared_ptr< TorqueSettings > & torqueSettings)
Definition at line 21 of file torque.cpp.
References tudat::basic_astrodynamics::aerodynamic_torque, tudat::json_interface::handleUnimplementedEnumValue(), tudat::basic_astrodynamics::second_order_gravitational_torque, tudat::basic_astrodynamics::torqueTypes, tudat::basic_astrodynamics::underfined_torque, and tudat::basic_astrodynamics::unsupportedTorqueTypes.
from_json() [26/26]
void tudat::simulation_setup::from_json (const nlohmann::json & jsonObject, std::shared_ptr< TorqueSettings > & torqueSettings)
Definition at line 45 of file torque.cpp.
References tudat::basic_astrodynamics::aerodynamic_torque, tudat::json_interface::handleUnimplementedEnumValue(), tudat::basic_astrodynamics::second_order_gravitational_torque, tudat::basic_astrodynamics::torqueTypes, tudat::basic_astrodynamics::underfined_torque, and tudat::basic_astrodynamics::unsupportedTorqueTypes.
getGlobalFrameOrigin()
std::string tudat::simulation_setup::getGlobalFrameOrigin (const NamedBodyMap & bodyMap)
Function ot retrieve the common global translational state origin of the environment. This function throws an exception if multiple bodies are found as the frame origin
Parameters
bodyMap List of body objects.
Returns
Global translational state origin of the environment
Definition at line 83 of file body.cpp.
Referenced by tudat::propagators::createCentralBodyData().
getBodyAccelerationInBaseFramefromNumericalDifferentiation()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, 3, 1 > tudat::simulation_setup::getBodyAccelerationInBaseFramefromNumericalDifferentiation (const std::shared_ptr< Body > bodyWithAcceleration, const TimeType nominalEvalutationTime)
Function to compute the acceleration of a body, using its ephemeris and 8th order finite difference and 100 s time step
Parameters
bodyWithAcceleration Body for which acceleration is to be computed
nominalEvalutationTime Time at which acceleration is to be evaluated.
Definition at line 1263 of file body.h.
References tudat::numerical_derivatives::computeCentralDifferenceFromFunction(), and tudat::numerical_derivatives::order8.
readTabulatedAerodynamicCoefficientsFromFiles() [1/2]
std::shared_ptr< AerodynamicCoefficientSettings > tudat::simulation_setup::readTabulatedAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::map< int, std::string > momentCoefficientFiles, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d & momentReferencePoint, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame = true, const bool areCoefficientsInNegativeAxisDirection = true, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings = nullptr)
Function to create aerodynamic coefficient settings from coefficients stored in data files. Separate files are defined for the three components of the force coefficients. The file format is discussed in the Tudat wiki
Parameters
forceCoefficientFiles List (size 3) of files containing the aerodynamic force coefficients
momentCoefficientFiles List (size 3) of files containing the aerodynamic moment coefficients
referenceLength Reference length with which aerodynamic moments (about x- and z- axes) are non-dimensionalized.
referenceArea Reference area with which aerodynamic forces and moments are non-dimensionalized.
lateralReferenceLength Reference length with which aerodynamic moments (about y-axis) is non-dimensionalized.
momentReferencePoint Point w.r.t. aerodynamic moment is calculated
independentVariableNames Physical meaning of the independent variables of the aerodynamic coefficients
areCoefficientsInAerodynamicFrame Boolean to define whether the aerodynamic coefficients are defined in the aerodynamic frame (drag, side, lift force) or in the body frame (typically denoted as Cx, Cy, Cz).
areCoefficientsInNegativeAxisDirection Boolean to define whether the aerodynamic coefficients are positive along the positive axes of the body or aerodynamic frame (see areCoefficientsInAerodynamicFrame). Note that for (drag, side, lift force), the coefficients are typically defined in negative direction.
interpolatorSettings Pointer to an interpolator settings object, where the conditions for interpolation are saved.
Returns
Settings for creation of aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles and reference data given as input.
Definition at line 22 of file createAerodynamicCoefficientInterface.cpp.
References tudat::input_output::getNumberOfIndependentVariablesInCoefficientFile().
Referenced by from_json().
readTabulatedAerodynamicCoefficientsFromFiles() [2/2]
std::shared_ptr< AerodynamicCoefficientSettings > tudat::simulation_setup::readTabulatedAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const double referenceArea, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame = true, const bool areCoefficientsInNegativeAxisDirection = true, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings = nullptr)
Function to create aerodynamic coefficient settings from coefficients stored in data files. Separate files are defined for the three components of the force coefficients. From this function, no moment coefficients are read (set to zero for all cases). The file format is discussed in the Tudat wiki
Parameters
forceCoefficientFiles List (size 3) of files containing the aerodynamic coefficients
referenceArea Reference area of aerodynamic coefficients
independentVariableNames Physical meaning of the independent variables of the aerodynamic coefficients
areCoefficientsInAerodynamicFrame Boolean to define whether the aerodynamic coefficients are defined in the aerodynamic frame (drag, side, lift force) or in the body frame (typically denoted as Cx, Cy, Cz).
areCoefficientsInNegativeAxisDirection Boolean to define whether the aerodynamic coefficients are positive along the positive axes of the body or aerodynamic frame (see areCoefficientsInAerodynamicFrame). Note that for (drag, side, lift force), the coefficients are typically defined in negative direction.
interpolatorSettings Pointer to an interpolator settings object, where the conditions for interpolation are saved.
Returns
Settings for creation of aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles and reference data given as input.
Definition at line 72 of file createAerodynamicCoefficientInterface.cpp.
References tudat::input_output::getNumberOfIndependentVariablesInCoefficientFile().
createConstantCoefficientAerodynamicCoefficientInterface()
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > tudat::simulation_setup::createConstantCoefficientAerodynamicCoefficientInterface (const Eigen::Vector3d constantForceCoefficient, const Eigen::Vector3d constantMomentCoefficient, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d & momentReferencePoint, const bool areCoefficientsInAerodynamicFrame = false, const bool areCoefficientsInNegativeAxisDirection = true)
Function to create an aerodynamic coefficient interface containing constant coefficients, As a result, the generated coefficient interface depends on zero parameters.
Parameters
constantForceCoefficient Constant force coefficients.
constantMomentCoefficient Constant moment coefficients.
referenceLength Reference length with which aerodynamic moments (about x- and z- axes) are non-dimensionalized.
referenceArea Reference area with which aerodynamic forces and moments are non-dimensionalized.
lateralReferenceLength Reference length with which aerodynamic moments (about y-axis) is non-dimensionalized.
momentReferencePoint Point w.r.t. aerodynamic moment is calculated
areCoefficientsInAerodynamicFrame Boolean to define whether the aerodynamic coefficients are defined in the aerodynamic frame (drag, side, lift force) or in the body frame (typically denoted as Cx, Cy, Cz).
areCoefficientsInNegativeAxisDirection Boolean to define whether the aerodynamic coefficients are positiver along tyhe positive axes of the body or aerodynamic frame (see areCoefficientsInAerodynamicFrame). Note that for (drag, side, lift force), the coefficients are typically defined in negative direction.
Returns
Aerodynamic coefficient interface with constant coefficients.
Definition at line 115 of file createAerodynamicCoefficientInterface.cpp.
Referenced by createAerodynamicCoefficientInterface().
createUnivariateTabulatedCoefficientAerodynamicCoefficientInterface()
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > tudat::simulation_setup::createUnivariateTabulatedCoefficientAerodynamicCoefficientInterface (const std::shared_ptr< AerodynamicCoefficientSettings > coefficientSettings, const std::string & body)
Factory function for tabulated (1-D independent variables) aerodynamic coefficient interface from coefficient settings.
Parameters
coefficientSettings Settings for aerodynamic coefficient interface, must be of derived type TabulatedAerodynamicCoefficientSettings< 1 >
body Name of body for which coefficient interface is to be made.
Returns
Tabulated aerodynamic coefficient interface pointer.
Definition at line 139 of file createAerodynamicCoefficientInterface.cpp.
References tudat::interpolators::createOneDimensionalInterpolator(), and tudat::interpolators::linear_interpolator.
Referenced by createAerodynamicCoefficientInterface().
createAerodynamicCoefficientInterface()
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > tudat::simulation_setup::createAerodynamicCoefficientInterface (const std::shared_ptr< AerodynamicCoefficientSettings > coefficientSettings, const std::string & body)
Function to create an aerodynamic coefficient interface.
Function to create an aerodynamic coefficient interface from interface settings.
Parameters
coefficientSettings Settings for the aerodynamic coefficient interface.
body Name of body for which aerodynamic coefficients are to be made.
Returns
Aerodynamic coefficient interface pointer of reqyested type and settings.
Definition at line 193 of file createAerodynamicCoefficientInterface.cpp.
References constant_aerodynamic_coefficients, createConstantCoefficientAerodynamicCoefficientInterface(), createControlSurfaceIncrementAerodynamicCoefficientInterface(), createUnivariateTabulatedCoefficientAerodynamicCoefficientInterface(), and tabulated_coefficients.
Referenced by createBodies(), and tudat::unit_tests::executeEarthOrbiterParameterEstimation().
readGivenSizeTabulatedAerodynamicCoefficientsFromFiles() [1/2]
template<unsigned int NumberOfDimensions> std::shared_ptr< AerodynamicCoefficientSettings > tudat::simulation_setup::readGivenSizeTabulatedAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::map< int, std::string > momentCoefficientFiles, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d & momentReferencePoint, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame = true, const bool areCoefficientsInNegativeAxisDirection = true, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings = nullptr)
Function to create aerodynamic coefficient settings from coefficients stored in data files. Separate files are defined for the three components of the force coefficients. The file format is discussed in the Tudat wiki Note that this function requires the number of independent variables in the coefficient files to be known. If this is not the case, the readTabulatedAerodynamicCoefficientsFromFiles function should be used.
Parameters
forceCoefficientFiles List (size 3) of files containing the aerodynamic force coefficients
momentCoefficientFiles List (size 3) of files containing the aerodynamic moment coefficients
referenceLength Reference length with which aerodynamic moments (about x- and z- axes) are non-dimensionalized.
referenceArea Reference area with which aerodynamic forces and moments are non-dimensionalized.
lateralReferenceLength Reference length with which aerodynamic moments (about y-axis) is non-dimensionalized.
momentReferencePoint Point w.r.t. aerodynamic moment is calculated
independentVariableNames Physical meaning of the independent variables of the aerodynamic coefficients
areCoefficientsInAerodynamicFrame Boolean to define whether the aerodynamic coefficients are defined in the aerodynamic frame (drag, side, lift force) or in the body frame (typically denoted as Cx, Cy, Cz).
areCoefficientsInNegativeAxisDirection Boolean to define whether the aerodynamic coefficients are positive along the positive axes of the body or aerodynamic frame (see areCoefficientsInAerodynamicFrame). Note that for (drag, side, lift force), the coefficients are typically defined in negative direction.
interpolatorSettings Pointer to an interpolator settings object, where the conditions for interpolation are saved.
Returns
Settings for creation of aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles and reference data given as input.
Definition at line 865 of file createAerodynamicCoefficientInterface.h.
References tudat::input_output::compareIndependentVariables().
readGivenSizeTabulatedAerodynamicCoefficientsFromFiles() [2/2]
template<unsigned int NumberOfDimensions> std::shared_ptr< AerodynamicCoefficientSettings > tudat::simulation_setup::readGivenSizeTabulatedAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const double referenceArea, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame = true, const bool areCoefficientsInNegativeAxisDirection = true, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings = nullptr)
Function to create aerodynamic coefficient settings from coefficients stored in data files. Separate files are defined for the three components of the force coefficients. From this function, no moment coefficients are read (set to zero for all cases). The file format is discussed in the Tudat wiki Note that this function requires the number of independent variables in the coefficient files to be known. If this is not the case, the readTabulatedAerodynamicCoefficientsFromFiles function should be used.
Parameters
forceCoefficientFiles List (size 3) of files containing the aerodynamic coefficients
referenceArea Reference area of aerodynamic coefficients
independentVariableNames Physical meaning of the independent variables of the aerodynamic coefficients
areCoefficientsInAerodynamicFrame Boolean to define whether the aerodynamic coefficients are defined in the aerodynamic frame (drag, side, lift force) or in the body frame (typically denoted as Cx, Cy, Cz).
areCoefficientsInNegativeAxisDirection Boolean to define whether the aerodynamic coefficients are positive along the positive axes of the body or aerodynamic frame (see areCoefficientsInAerodynamicFrame). Note that for (drag, side, lift force), the coefficients are typically defined in negative direction.
interpolatorSettings Pointer to an interpolator settings object, where the conditions for interpolation are saved.
Returns
Settings for creation of aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles and reference data given as input.
Definition at line 933 of file createAerodynamicCoefficientInterface.h.
createTabulatedCoefficientAerodynamicCoefficientInterface() [1/2]
template<unsigned int NumberOfDimensions> std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > tudat::simulation_setup::createTabulatedCoefficientAerodynamicCoefficientInterface (const std::vector< std::vector< double > > independentVariables, const boost::multi_array< Eigen::Vector3d, static_cast< size_t >(NumberOfDimensions) > forceCoefficients, const boost::multi_array< Eigen::Vector3d, static_cast< size_t >(NumberOfDimensions) > momentCoefficients, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d & momentReferencePoint, const bool areCoefficientsInAerodynamicFrame = false, const bool areCoefficientsInNegativeAxisDirection = true, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings = nullptr)
Factory function for tabulated (N-D independent variables) aerodynamic coefficient interface.
Parameters
independentVariables Values of indepependent variables at which the coefficients in the input multi arrays are defined.
forceCoefficients Values of force coefficients at independent variables defined by independentVariables.
momentCoefficients Values of moment coefficients at independent variables defined by independentVariables.
referenceLength Reference length with which aerodynamic moments (about x- and z- axes) are non-dimensionalized.
referenceArea Reference area with which aerodynamic forces and moments are non-dimensionalized.
lateralReferenceLength Reference length with which aerodynamic moments (about y-axis) is non-dimensionalized.
momentReferencePoint Point w.r.t. aerodynamic moment is calculated
independentVariableNames Vector with identifiers the physical meaning of each independent variable of the aerodynamic coefficients.
areCoefficientsInAerodynamicFrame Boolean to define whether the aerodynamic coefficients are defined in the aerodynamic frame (drag, side, lift force) or in the body frame (typically denoted as Cx, Cy, Cz).
areCoefficientsInNegativeAxisDirection Boolean to define whether the aerodynamic coefficients are positive along the positive axes of the body or aerodynamic frame (see areCoefficientsInAerodynamicFrame). Note that for (drag, side, lift force), the coefficients are typically defined in negative direction.
interpolatorSettings Pointer to an interpolator settings object, where the conditions for interpolation are saved.
Returns
Tabulated aerodynamic coefficient interface pointer.
Definition at line 1091 of file createAerodynamicCoefficientInterface.h.
References tudat::interpolators::huntingAlgorithm, tudat::interpolators::multi_linear_interpolator, and tudat::interpolators::use_boundary_value.
createTabulatedCoefficientAerodynamicCoefficientInterface() [2/2]
template<unsigned int NumberOfDimensions> std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > tudat::simulation_setup::createTabulatedCoefficientAerodynamicCoefficientInterface (const std::shared_ptr< AerodynamicCoefficientSettings > coefficientSettings, const std::string & body)
Factory function for tabulated aerodynamic coefficient interface from coefficient settings. This function is included to allow easier interface between the non-templated general createAerodynamicCoefficientInterface and the templated createTabulatedCoefficientAerodynamicCoefficientInterface.
Parameters
coefficientSettings Settings for aerodynamic coefficient interface, must be of derived type TabulatedAerodynamicCoefficientSettings< NumberOfDimensions >/
body Name of body for which coefficient interface is to be made.
Returns
Tabulated aerodynamic coefficient interface pointer.
Definition at line 1180 of file createAerodynamicCoefficientInterface.h.
readTabulatedControlIncrementAerodynamicCoefficientsFromFiles() [1/2]
std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > tudat::simulation_setup::readTabulatedControlIncrementAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::map< int, std::string > momentCoefficientFiles, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings fom coefficients stored in data files. Separate files are defined for the three components of the force coefficients. The file format is discussed in the Tudat wiki
Parameters
forceCoefficientFiles List (containing entries at key = 0,1 and/or 2, denoting coefficients in x, y and z direction) of files containing the aerodynamic force coefficients
momentCoefficientFiles List (containing entries at key = 0,1 and/or 2, denoting coefficients in x, y and z direction) of files containing the aerodynamic moment coefficients
independentVariableNames Physical meaning of the independent variables of the aerodynamic coefficients
Returns
Settings for creation of control surface aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles and momentCoefficientFiles.
Definition at line 21 of file createAerodynamicControlSurfaces.cpp.
References tudat::input_output::getNumberOfIndependentVariablesInCoefficientFile().
readTabulatedControlIncrementAerodynamicCoefficientsFromFiles() [2/2]
std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > tudat::simulation_setup::readTabulatedControlIncrementAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings fom coefficients stored in data files. Separate files are defined for the three components of the force coefficients. From this function, no moment coefficients are read (set to zero for all cases). The file format is discussed in the Tudat wiki
Parameters
forceCoefficientFiles List (containing entries at key = 0,1 and/or 2, denoting coefficients in x, y and z direction) of files containing the aerodynamic force coefficients.
independentVariableNames Physical meaning of the independent variables of the aerodynamic coefficients
Returns
Settings for creation of control surface aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles
Definition at line 60 of file createAerodynamicControlSurfaces.cpp.
References tudat::input_output::getNumberOfIndependentVariablesInCoefficientFile().
createControlSurfaceIncrementAerodynamicCoefficientInterface()
std::shared_ptr< aerodynamics::ControlSurfaceIncrementAerodynamicInterface > tudat::simulation_setup::createControlSurfaceIncrementAerodynamicCoefficientInterface (const std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > coefficientSettings, const std::string & body)
Function to tabulated control surface aerodynamic coefficients from associated settings object
Parameters
coefficientSettings Object containing settings for control surface aerodynamic coefficients
body Name of body for which coefficients are to be created.
Returns
Object used to compute/update control surface aerodynamics during propagation.
Definition at line 97 of file createAerodynamicControlSurfaces.cpp.
References tabulated_coefficients.
Referenced by createAerodynamicCoefficientInterface().
readGivenSizeTabulatedControlIncrementAerodynamicCoefficientsFromFiles() [1/2]
template<unsigned int NumberOfIndependentVariables> std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > tudat::simulation_setup::readGivenSizeTabulatedControlIncrementAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::map< int, std::string > momentCoefficientFiles, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings fom coefficients stored in data files. Separate files are defined for the three components of the force coefficients. The file format is discussed in the Tudat wiki Note that this function requires the number of independent variables in the coefficient files to be known. If this is not the case, the readTabulatedAerodynamicCoefficientsFromFiles function should be used.
Parameters
forceCoefficientFiles List (size 3) of files containing the aerodynamic force coefficients
momentCoefficientFiles List (size 3) of files containing the aerodynamic moment coefficients
independentVariableNames Physical meaning of the independent variables of the aerodynamic coefficient
Returns
Settings for creation of control surface aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles and momentCoefficientFiles
Definition at line 249 of file createAerodynamicControlSurfaces.h.
References tudat::input_output::compareIndependentVariables().
readGivenSizeTabulatedControlIncrementAerodynamicCoefficientsFromFiles() [2/2]
template<unsigned int NumberOfIndependentVariables> std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > tudat::simulation_setup::readGivenSizeTabulatedControlIncrementAerodynamicCoefficientsFromFiles (const std::map< int, std::string > forceCoefficientFiles, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings fom coefficients stored in data files. Separate files are defined for the three components of the force coefficients. From this function, no moment coefficients are read (set to zero for all cases). The file format is discussed in the Tudat wiki Note that this function requires the number of independent variables in the coefficient files to be known. If this is not the case, the readTabulatedAerodynamicCoefficientsFromFiles function should be used.
Parameters
forceCoefficientFiles List (size 3) of files containing the aerodynamic coefficients
independentVariableNames Physical meaning of the independent variables of the aerodynamic coefficients
Returns
Settings for creation of control surface aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles and reference data given as input
Definition at line 292 of file createAerodynamicControlSurfaces.h.
createTabulatedControlSurfaceIncrementAerodynamicCoefficientInterface() [1/2]
template<unsigned int NumberOfDimensions> std::shared_ptr< aerodynamics::ControlSurfaceIncrementAerodynamicInterface > tudat::simulation_setup::createTabulatedControlSurfaceIncrementAerodynamicCoefficientInterface (const std::vector< std::vector< double > > independentVariables, const boost::multi_array< Eigen::Vector3d, static_cast< size_t >(NumberOfDimensions) > forceCoefficients, const boost::multi_array< Eigen::Vector3d, static_cast< size_t >(NumberOfDimensions) > momentCoefficients, const std::vector< aerodynamics::AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Function to create control surface aerodynamic coefficient settings from crom user-defined coefficients.
Parameters
independentVariables Values of indepependent variables at which the coefficients in the input multi arrays are defined.
forceCoefficients Values of force coefficients at independent variables defined by independentVariables.
momentCoefficients Values of moment coefficients at independent variables defined by independentVariables.
independentVariableNames Vector with identifiers the physical meaning of each independent variable of the aerodynamic coefficients (must contain exactly one entry of control_surface_deflection_dependent)
Returns
Settings for creation of control surface aerodynamic coefficient interface, based on contents read from files defined in forceCoefficientFiles
Definition at line 364 of file createAerodynamicControlSurfaces.h.
createTabulatedControlSurfaceIncrementAerodynamicCoefficientInterface() [2/2]
template<unsigned int NumberOfDimensions> std::shared_ptr< aerodynamics::ControlSurfaceIncrementAerodynamicInterface > tudat::simulation_setup::createTabulatedControlSurfaceIncrementAerodynamicCoefficientInterface (const std::shared_ptr< ControlSurfaceIncrementAerodynamicCoefficientSettings > coefficientSettings, const std::string & body)
Function to create tabulated control surface aerodynamic coefficients from associated settings object
Parameters
coefficientSettings Object containing settings for tabulated control surface aerodynamic coefficients
body Name of body for which coefficients are to be created.
Returns
Object used to compute/update control surface aerodynamics during propagation.
Definition at line 415 of file createAerodynamicControlSurfaces.h.
createWindModel()
std::shared_ptr< aerodynamics::WindModel > tudat::simulation_setup::createWindModel (const std::shared_ptr< WindModelSettings > windSettings, const std::string & body)
Function to create a wind model based on model-specific settings for the wind model.
Parameters
windSettings Settings for the wind model that is to be created, defined a pointer to an object of class (derived from) WindModelSettings.
body Name of the body for which the wind model is to be created.
Returns
Wind model created according to settings in windSettings.
Definition at line 31 of file createAtmosphereModel.cpp.
References custom_wind_model.
Referenced by createAtmosphereModel().
createAtmosphereModel()
std::shared_ptr< aerodynamics::AtmosphereModel > tudat::simulation_setup::createAtmosphereModel (const std::shared_ptr< AtmosphereSettings > atmosphereSettings, const std::string & body)
Function to create an atmosphere model based on model-specific settings for the atmosphere.
Parameters
atmosphereSettings Settings for the atmosphere model that is to be created, defined a pointer to an object of class (derived from) AtmosphereSettings.
body Name of the body for which the atmosphere model is to be created.
Returns
Atmosphere model created according to settings in atmosphereSettings.
Definition at line 63 of file createAtmosphereModel.cpp.
References createWindModel(), custom_constant_temperature_atmosphere, exponential_atmosphere, tudat::aerodynamics::exponentialAtmosphereModel(), tudat::input_output::getSpaceWeatherDataPath(), nrlmsise00, tudat::aerodynamics::nrlmsiseInputFunction(), tudat::input_output::solar_activity::readSolarActivityData(), tabulated_atmosphere, TUDAT_NAN, and tudat::aerodynamics::undefined_body.
Referenced by createBodies().
determineBodyCreationOrder()
std::vector< std::pair< std::string, std::shared_ptr< BodySettings > > > tudat::simulation_setup::determineBodyCreationOrder (const std::map< std::string, std::shared_ptr< BodySettings > > & bodySettings)
Function that determines the order in which bodies are to be created, to ensure that any dependency between body models are correctly handled. Currently, no dependencies exist that force any particular creation order.
Parameters
bodySettings Map of body settings (with map key the body name)
Returns
List of pairs: name and body settings of that body
Definition at line 32 of file createBodies.cpp.
Referenced by createBodies().
createBodies()
NamedBodyMap tudat::simulation_setup::createBodies (const std::map< std::string, std::shared_ptr< BodySettings > > & bodySettings)
Function to create a msap of body objects based on model-specific settings for the bodies, containing settings for each relevant environment model.
Parameters
bodySettings List of settings for the bodies that are to be created, defined as a map of pointers to an object of class BodySettings
Returns
List of bodies created according to settings in bodySettings.
Definition at line 50 of file createBodies.cpp.
References createAerodynamicCoefficientInterface(), createAtmosphereModel(), createBodyEphemeris(), createBodyShapeModel(), createGravityFieldModel(), createGravityFieldModelVariationsSet(), createGroundStation(), createRadiationPressureInterface(), createRotationModel(), and determineBodyCreationOrder().
Referenced by tudat::unit_tests::executeEarthOrbiterBiasEstimation(), tudat::unit_tests::executeEarthOrbiterParameterEstimation(), tudat::unit_tests::executePlanetaryParameterEstimation(), and tudat::json_interface::updateBodiesFromJSON().
setGlobalFrameBodyEphemerides()
template<typename StateScalarType = double, typename TimeType = double> void tudat::simulation_setup::setGlobalFrameBodyEphemerides (const NamedBodyMap & bodyMap, const std::string & globalFrameOrigin, const std::string & globalFrameOrientation)
Function to define the global origin and orientation of the reference frame that is to be used in the simulations. This function checks the origin and orientation of the Ephemeris and RotationalEphemeris, and checks whether their origin/orientation is the same as that globalFrameOrigin and globalFrameOrientation provided as input. In particular, this function sets the ephemerisFrameToBaseFrameFunction_ anf ephemerisFrameToBaseFrameLongFunction_ variables of the Body objects, which provide a time-dependent translation of the global origin to the body's ephemeris origin. In case of an inconsistency in the current and requried frames, this function throws an error.
Parameters
bodyMap List of body objects that constitute the environment.
globalFrameOrigin Global reference frame origin.
globalFrameOrientation Global referencef frame orientation.
Definition at line 112 of file createBodies.h.
References tudat::propagators::createFrameManager().
Referenced by tudat::unit_tests::executeEarthOrbiterBiasEstimation(), tudat::unit_tests::executeEarthOrbiterParameterEstimation(), tudat::unit_tests::executePlanetaryParameterEstimation(), and tudat::json_interface::updateBodiesFromJSON().
createBodyShapeModel()
std::shared_ptr< basic_astrodynamics::BodyShapeModel > tudat::simulation_setup::createBodyShapeModel (const std::shared_ptr< BodyShapeSettings > shapeSettings, const std::string & body)
Function to create a body shape model based on model-specific settings for the shape.
Parameters
shapeSettings Settings for the shape model that is to be created, defined a pointer to an object of class (derived from) BodyShapeSettings.
body Name of the body for which the shape model is to be created.
Returns
Shape model created according to settings in shapeSettings.
Definition at line 25 of file createBodyShapeModel.cpp.
References tudat::spice_interface::getAverageRadius(), oblate_spheroid, spherical, and spherical_spice.
Referenced by createBodies().
createBodyEphemeris()
std::shared_ptr< ephemerides::Ephemeris > tudat::simulation_setup::createBodyEphemeris (const std::shared_ptr< EphemerisSettings > ephemerisSettings, const std::string & bodyName)
Function to create a ephemeris model based on model-specific settings for the ephemeris.
Parameters
ephemerisSettings Settings for the ephemeris model that is to be created, defined a pointer to an object of class (derived from) EphemerisSettings.
bodyName Name of the body for which the ephemeris model is to be created.
Returns
Ephemeris model created according to settings in ephemerisSettings.
Definition at line 35 of file createEphemeris.cpp.
References approximate_planet_positions, constant_ephemeris, custom_ephemeris, direct_spice_ephemeris, tudat::interpolators::huntingAlgorithm, interpolated_spice, kepler_ephemeris, tudat::interpolators::lagrange_cubic_spline_boundary_interpolation, and tabulated_ephemeris.
Referenced by createBodies().
getSafeInterpolationInterval()
std::pair< double, double > tudat::simulation_setup::getSafeInterpolationInterval (const std::shared_ptr< ephemerides::Ephemeris > ephemerisModel)
Function that retrieves the time interval at which an ephemeris can be safely interrogated. For most ephemeris types, this function returns the full range of double values (lowest() to max()). For the tabulated ephemeris, the interval on which the interpolator inside this object is valid is checked and returned
Parameters
ephemerisModel Ephemeris model for which the interval is to be determined.
Returns
The time interval at which the ephemeris can be safely interrogated
Definition at line 297 of file createEphemeris.cpp.
References tudat::ephemerides::getTabulatedEphemerisSafeInterval(), and tudat::ephemerides::isTabulatedEphemeris().
Referenced by tudat::ephemerides::getTabulatedEphemerisSafeInterval().
createAtmosphericFlightConditions()
std::shared_ptr< aerodynamics::AtmosphericFlightConditions > tudat::simulation_setup::createAtmosphericFlightConditions (const std::shared_ptr< Body > bodyWithFlightConditions, const std::shared_ptr< Body > centralBody, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::function< double() > angleOfAttackFunction = std::function< double() >(), const std::function< double() > angleOfSideslipFunction = std::function< double() >(), const std::function< double() > bankAngleFunction = std::function< double() >(), const std::function< void(const double) > angleUpdateFunction = std::function< void(const double) >())
Function to create an atmospheric flight conditions object, which is responsible for calculating the various dependent variables required for calculation of the aerodynamic acceleration
Parameters
bodyWithFlightConditions Body for which flight conditions are to be created.
centralBody Body in the atmosphere of which bodyWithFlightConditions is flying
nameOfBodyUndergoingAcceleration Name of body undergoing acceleration.
nameOfBodyExertingAcceleration Name of body with the atmosphere causing acceleration.
angleOfAttackFunction Function returning the current angle of attack (default 0).
angleOfSideslipFunction Function returning the current angle of sideslip (default 0).
bankAngleFunction Function returning the current bank angle (default 0).
angleUpdateFunction Function to update the aerodynamic angles to the current time (default none).
Returns
Flight conditions object for given bodies and settings.
Definition at line 31 of file createFlightConditions.cpp.
References tudat::system_models::VehicleSystems::getCurrentControlSurfaceDeflection(), tudat::simulation_setup::Body::getCurrentRotationMatrixDerivativeToLocalFrame(), tudat::simulation_setup::Body::getCurrentRotationToGlobalFrame(), tudat::simulation_setup::Body::getCurrentRotationToLocalFrame(), and tudat::simulation_setup::Body::getState().
Referenced by tudat::simulation_setup::AccelerationLimitedThrottleGuidance::AccelerationLimitedThrottleGuidance(), tudat::propagators::checkAndModifyEnvironmentForDependentVariableSaving(), createAerodynamicAcceleratioModel(), and createAerodynamicTorqueModel().
createFlightConditions()
std::shared_ptr< aerodynamics::FlightConditions > tudat::simulation_setup::createFlightConditions (const std::shared_ptr< Body > bodyWithFlightConditions, const std::shared_ptr< Body > centralBody, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration)
Function to create a flight conditions object, which is responsible for calculating various dependent variables (altitude, latitude, etc) for non-atmospheric flight
Parameters
bodyWithFlightConditions Body for which flight conditions are to be created.
centralBody Body in the atmosphere of which bodyWithFlightConditions is flying
nameOfBodyUndergoingAcceleration Name of body undergoing acceleration.
nameOfBodyExertingAcceleration Name of body with the atmosphere causing acceleration.
Returns
Flight conditions object for given bodies and settings.
Definition at line 129 of file createFlightConditions.cpp.
References tudat::simulation_setup::Body::getCurrentRotationMatrixDerivativeToLocalFrame(), tudat::simulation_setup::Body::getCurrentRotationToGlobalFrame(), tudat::simulation_setup::Body::getCurrentRotationToLocalFrame(), and tudat::simulation_setup::Body::getState().
Referenced by tudat::propagators::checkAndModifyEnvironmentForDependentVariableSaving().
setTrimmedConditions() [1/2]
std::shared_ptr< aerodynamics::TrimOrientationCalculator > tudat::simulation_setup::setTrimmedConditions (const std::shared_ptr< aerodynamics::AtmosphericFlightConditions > flightConditions)
Function to set the angle of attack to trimmed conditions. Using this function requires the aerodynamic coefficient interface to be dependent on the angle of attack.
Parameters
flightConditions Flight conditions for body that is to have trimmed conditions.
Definition at line 179 of file createFlightConditions.cpp.
References tudat::aerodynamics::TrimOrientationCalculator::findTrimAngleOfAttackFromFunction(), tudat::aerodynamics::AtmosphericFlightConditions::getAerodynamicCoefficientIndependentVariables(), and tudat::aerodynamics::AtmosphericFlightConditions::getControlSurfaceAerodynamicCoefficientIndependentVariables().
Referenced by setTrimmedConditions().
setTrimmedConditions() [2/2]
std::shared_ptr< aerodynamics::TrimOrientationCalculator > tudat::simulation_setup::setTrimmedConditions (const std::shared_ptr< Body > bodyWithFlightConditions)
Function to set the angle of attack to trimmed conditions. Using this function requires the aerodynamic coefficient interface to be dependent on the angle of attack.
Parameters
bodyWithFlightConditions Body for which trimmed conditions are to be imposed.
Definition at line 203 of file createFlightConditions.cpp.
References setTrimmedConditions().
setGuidanceAnglesFunctions() [1/2]
void tudat::simulation_setup::setGuidanceAnglesFunctions (const std::shared_ptr< aerodynamics::AerodynamicGuidance > aerodynamicGuidance, const std::shared_ptr< reference_frames::AerodynamicAngleCalculator > angleCalculator)
Function that must be called to link the AerodynamicGuidance object to the simulation
Parameters
aerodynamicGuidance Object computing the current aerodynamic angles.
angleCalculator Object that handles all aerodynamic angles in the numerical propagation
Definition at line 217 of file createFlightConditions.cpp.
References tudat::aerodynamics::AerodynamicGuidance::getCurrentAngleOfAttack(), tudat::aerodynamics::AerodynamicGuidance::getCurrentAngleOfSideslip(), tudat::aerodynamics::AerodynamicGuidance::getCurrentBankAngle(), and tudat::aerodynamics::AerodynamicGuidance::updateGuidance().
Referenced by setGuidanceAnglesFunctions().
setGuidanceAnglesFunctions() [2/2]
void tudat::simulation_setup::setGuidanceAnglesFunctions (const std::shared_ptr< aerodynamics::AerodynamicGuidance > aerodynamicGuidance, const std::shared_ptr< simulation_setup::Body > bodyWithAngles)
Function that must be called to link the AerodynamicGuidance object to the simulation
Parameters
aerodynamicGuidance Object computing the current aerodynamic angles.
bodyWithAngles Body for which the orientation is to be controlled.
Definition at line 229 of file createFlightConditions.cpp.
References setGuidanceAnglesFunctions().
getPathForSphericalHarmonicsModel()
std::string tudat::simulation_setup::getPathForSphericalHarmonicsModel (const SphericalHarmonicsModel sphericalHarmonicsModel)
Get the path of the SH file for a SH model.
Parameters
sphericalHarmonicsModel The spherical harmonics model.
Returns
The path of the SH file for a SH model.
Definition at line 29 of file createGravityField.cpp.
References egm96, tudat::input_output::getGravityModelsPath(), ggm02c, ggm02s, glgm3150, jgmro120d, and lpe200.
getReferenceFrameForSphericalHarmonicsModel()
std::string tudat::simulation_setup::getReferenceFrameForSphericalHarmonicsModel (const SphericalHarmonicsModel sphericalHarmonicsModel)
Get the associated reference frame for a SH model.
Parameters
sphericalHarmonicsModel The spherical harmonics model.
Returns
The associated reference frame for a SH model.
Definition at line 52 of file createGravityField.cpp.
References egm96, ggm02c, ggm02s, glgm3150, jgmro120d, and lpe200.
readGravityFieldFile()
std::pair< double, double > tudat::simulation_setup::readGravityFieldFile (const std::string & fileName, const int maximumDegree, const int maximumOrder, std::pair< Eigen::MatrixXd, Eigen::MatrixXd > & coefficients, const int gravitationalParameterIndex = -1, const int referenceRadiusIndex = -1)
Function to read a spherical harmonic gravity field file.
Function to read a spherical harmonic gravity field file, returns (by reference) cosine and sine spherical harmomic coefficients. The file structure should be as follows: The first line may be a file header with metadata. If this is the case, the gravitationalParameterIndex and referenceRadiusIndex should be used as input, to communicate which entries in the list of metadata represents these quantities. If both these variables are NaN, the file is assumed to have no header. The following lines of the file must have the following structure: Degree, Order, Cosine Coefficient, Sine Coefficients Subsequent columns may be present in the file, but are ignored when parsing. All coefficients not defined in the file are set to zero (except C(0,0) which is always 1.0)
Parameters
fileName Name of PDS gravity field file to be loaded.
maximumDegree Maximum degree of gravity field to be loaded.
maximumOrder Maximum order of gravity field to be loaded.
gravitationalParameterIndex
referenceRadiusIndex
coefficients Spherical harmonics coefficients (first is cosine, second is sine).
Returns
Pair of gravitational parameter and reference radius, values are non-NaN if gravitationalParameterIndex and referenceRadiusIndex are >=0.
Definition at line 107 of file createGravityField.cpp.
References tudat::json_interface::split(), and TUDAT_NAN.
Referenced by tudat::simulation_setup::FromFileSphericalHarmonicsGravityFieldSettings::FromFileSphericalHarmonicsGravityFieldSettings().
createGravityFieldModel()
std::shared_ptr< gravitation::GravityFieldModel > tudat::simulation_setup::createGravityFieldModel (const std::shared_ptr< GravityFieldSettings > gravityFieldSettings, const std::string & body, const NamedBodyMap & bodyMap = NamedBodyMap(), const std::vector< std::shared_ptr< GravityFieldVariationSettings > > & gravityFieldVariationSettings = std::vector< std::shared_ptr< GravityFieldVariationSettings > >())
Function to create a gravity field model based on model-specific settings for the gravity field.
Parameters
gravityFieldSettings Settings for the gravity field model that is to be created, defined a pointer to an object of class (derived from) GravityFieldSettings.
body Name of the body for which the gravity field model is to be created.
bodyMap List of body objects, as currently created (used when setting gravityFieldVariationSettings)
gravityFieldVariationSettings List of settings for the variations of the gravity field that are to be used (but not immediately set!) by current body under consideration.
Returns
Gravity field model created according to settings in gravityFieldSettings.
Definition at line 217 of file createGravityField.cpp.
References central, central_spice, tudat::spice_interface::getBodyGravitationalParameter(), and spherical_harmonic.
Referenced by createBodies().
createHomogeneousTriAxialEllipsoidGravitySettings()
std::shared_ptr< SphericalHarmonicsGravityFieldSettings > tudat::simulation_setup::createHomogeneousTriAxialEllipsoidGravitySettings (const double axisA, const double axisB, const double axisC, const double ellipsoidDensity, const int maximumDegree, const int maximumOrder, const std::string & associatedReferenceFrame)
Function to create gravity field settings for a homogeneous triaxial ellipsoid. The gravity field is expressed in normalized spherical harmonic coefficients. X-axis is alligned with largest axis, y-axis with middle axis and z-axis with smallest axis
Parameters
axisA Largest axis of triaxial ellipsoid
axisB Middle axis of triaxial ellipsoid
axisC Smallest axis of triaxial ellipsoid
ellipsoidDensity Density of ellipsoid.
maximumDegree Maximum degree of expansion
maximumOrder Maximum oredr of expansion
associatedReferenceFrame Identifier for body-fixed reference frame to which the coefficients are referred.
Returns
Gravity field settings for a homogeneous triaxial ellipsoid of given properties.
Definition at line 345 of file createGravityField.cpp.
References tudat::gravitation::calculateTriAxialEllipsoidVolume(), tudat::gravitation::createTriAxialEllipsoidNormalizedSphericalHarmonicCoefficients(), and tudat::physical_constants::GRAVITATIONAL_CONSTANT.
createGravityFieldModelVariationsSet()
std::shared_ptr< gravitation::GravityFieldVariationsSet > tudat::simulation_setup::createGravityFieldModelVariationsSet (const std::string & body, const NamedBodyMap & bodyMap, const std::vector< std::shared_ptr< GravityFieldVariationSettings > > & gravityFieldVariationSettings)
Function to create a set of gravity field variations, stored in the associated interface class of type GravityFieldVariationsSet
Parameters
body Body for which gravity field variations are createad
bodyMap List of body objects in simulations.
gravityFieldVariationSettings List of settings for gravity field variations
Returns
Interface class containing list of GravityFieldVariations.
Definition at line 27 of file createGravityFieldVariations.cpp.
References tudat::gravitation::basic_solid_body, and createGravityFieldVariationsModel().
Referenced by createBodies().
createGravityFieldVariationsModel()
std::shared_ptr< gravitation::GravityFieldVariations > tudat::simulation_setup::createGravityFieldVariationsModel (const std::shared_ptr< GravityFieldVariationSettings > gravityFieldVariationSettings, const std::string body, const NamedBodyMap & bodyMap)
Function to create a single gravity field variation object.
Parameters
gravityFieldVariationSettings Settings for the gravity field variation object that is to be created. Depending on the settings and type of the gravity field variations, spherical harmonic corrections are calculated a priori and handled by an interpolator during propagation, or they are directly calculated from the current state during numerical propagation.
body Body for which gravity field variations are createad
bodyMap List of body objects in simulations.
Returns
Single gravity field variation object.
Definition at line 108 of file createGravityFieldVariations.cpp.
References tudat::gravitation::basic_solid_body, tudat::simulation_setup::Body::getCurrentRotationToLocalFrame(), tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrame(), tudat::simulation_setup::Body::getState(), and tudat::gravitation::tabulated_variation.
Referenced by createGravityFieldModelVariationsSet().
createGroundStation() [1/3]
void tudat::simulation_setup::createGroundStation (const std::shared_ptr< Body > & body, const std::string groundStationName, const std::shared_ptr< ground_stations::GroundStationState > groundStationState)
Function to create a ground station from pre-defined station state object, and add it to a Body object
Parameters
body Body object in which the newly created ground station is to be added.
groundStationName Name of ground station that is to be created
groundStationState Object defining the state of the ground-station in a body-fixed frame
Definition at line 21 of file createGroundStations.cpp.
References tudat::ground_stations::GroundStationState::getRotationFromBodyFixedToTopocentricFrame(), and tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrame().
Referenced by createBodies(), createGroundStation(), createGroundStations(), tudat::unit_tests::executeEarthOrbiterBiasEstimation(), and tudat::unit_tests::executeEarthOrbiterParameterEstimation().
createGroundStation() [2/3]
void tudat::simulation_setup::createGroundStation (const std::shared_ptr< Body > & body, const std::string groundStationName, const Eigen::Vector3d groundStationPosition, const coordinate_conversions::PositionElementTypes positionElementType = coordinate_conversions::cartesian_position)
Function to create a ground station and add it to a Body object
Parameters
body Body object in which the newly created ground station is to be added.
groundStationName Name of ground station that is to be created
groundStationPosition Position of ground station in body-fixed frame
positionElementType Element type (e.g. Cartesian, spherical, etc.) of groundStationPosition.
Definition at line 35 of file createGroundStations.cpp.
References createGroundStation().
createGroundStations()
void tudat::simulation_setup::createGroundStations (const NamedBodyMap & bodyMap, const std::map< std::pair< std::string, std::string >, Eigen::Vector3d > & groundStationsWithPosition, const coordinate_conversions::PositionElementTypes positionElementType = coordinate_conversions::cartesian_position)
Function to create a set of ground stations and add them to the corresponding Body objects
Parameters
bodyMap List of body objects to which the ground stations are to be added
groundStationsWithPosition List of ground station positions, key is first: associated body; second: ground station name
positionElementType Element type (e.g. Cartesian, spherical, etc.) of Vector3d in groundStationsWithPosition.
Definition at line 47 of file createGroundStations.cpp.
References createGroundStation().
createGroundStation() [3/3]
void tudat::simulation_setup::createGroundStation (const std::shared_ptr< Body > & body, const std::string & bodyName, const std::shared_ptr< GroundStationSettings > groundStationSettings)
Definition at line 64 of file createGroundStations.cpp.
References createGroundStation().
getOccultingBodiesInformation()
void tudat::simulation_setup::getOccultingBodiesInformation (const NamedBodyMap & bodyMap, const std::vector< std::string > & occultingBodies, std::vector< std::function< Eigen::Vector3d() > > & occultingBodyPositions, std::vector< double > & occultingBodyRadii)
Function to obtain (by reference) the position functions and radii of occulting bodies.
Parameters
bodyMap List of body objects.
occultingBodies List of bodies causing occultation.
occultingBodyPositions List of position functions of occulting bodies (return by reference output variable).
occultingBodyRadii List of radii of occulting bodies (return by reference output variable).
Definition at line 24 of file createRadiationPressureInterface.cpp.
References tudat::simulation_setup::Body::getPosition().
Referenced by createRadiationPressureInterface().
createRadiationPressureInterface()
std::shared_ptr< electro_magnetism::RadiationPressureInterface > tudat::simulation_setup::createRadiationPressureInterface (const std::shared_ptr< RadiationPressureInterfaceSettings > radiationPressureInterfaceSettings, const std::string & bodyName, const NamedBodyMap & bodyMap)
Function to create a radiation pressure interface.
Parameters
radiationPressureInterfaceSettings Settings for the radiation pressure interface.
bodyName Name of body for which radiation pressure interface.
bodyMap List of body objects to use for creation of radiation pressure interface.
Returns
Radiation pressure interface pointer of requested type and settings.
Definition at line 54 of file createRadiationPressureInterface.cpp.
References cannon_ball, defaultRadiatedPowerValues, getOccultingBodiesInformation(), and tudat::simulation_setup::Body::getPosition().
Referenced by createBodies(), and tudat::unit_tests::executeEarthOrbiterParameterEstimation().
createRotationModel()
std::shared_ptr< ephemerides::RotationalEphemeris > tudat::simulation_setup::createRotationModel (const std::shared_ptr< RotationModelSettings > rotationModelSettings, const std::string & body)
Function to create a rotation model based on model-specific settings for the rotation.
Parameters
rotationModelSettings Settings for the rotation model that is to be created, defined a pointer to an object of class (derived from) RotationSettings.
body Name of the body for which the rotation model is to be created.
Returns
Rotation model created according to settings in rotationModelSettings.
Definition at line 34 of file createRotationModel.cpp.
References gcrs_to_itrs_rotation_model, simple_rotation_model, and spice_rotation_model.
Referenced by createBodies().
getDefaultAtmosphereModelSettings()
std::shared_ptr< AtmosphereSettings > tudat::simulation_setup::getDefaultAtmosphereModelSettings (const std::string & bodyName, const double initialTime, const double finalTime)
Function to create default settings for a body's atmosphere model. Currently set to no atmosphere, except for Earth, for which a tabulated version of the 1976 Standard Atmosphere is set.
Parameters
bodyName Name of body for which default atmosphere settings are to be retrieved.
initialTime Start time at which environment models in body are to be created (not currently used by this function, but included for consistency).
finalTime End time up to which environment models in body are to be created (not currently used by this function, but included for consistency).
Returns
Default settings for a body's atmosphere model.
Definition at line 24 of file defaultBodies.cpp.
References tudat::input_output::getAtmosphereTablesPath().
Referenced by getDefaultSingleBodySettings().
getDefaultEphemerisSettings() [1/2]
std::shared_ptr< EphemerisSettings > tudat::simulation_setup::getDefaultEphemerisSettings (const std::string & bodyName)
Function to create default settings for a body's ephemeris without a limitation on the time interval.
Parameters
bodyName Name of body for which default ephemeris settings are to be retrieved.
Returns
Default settings for a body's ephemeris.
Definition at line 43 of file defaultBodies.cpp.
Referenced by getDefaultSingleBodySettings().
getDefaultEphemerisSettings() [2/2]
std::shared_ptr< EphemerisSettings > tudat::simulation_setup::getDefaultEphemerisSettings (const std::string & bodyName, const double initialTime, const double finalTime, const double timeStep = 300.0)
Function to create default settings for a body's ephemeris. Currently set to a creating a 6th order Lagrange interpolator from Spice.
Parameters
bodyName Name of body for which default ephemeris settings are to be retrieved.
initialTime Start time at which ephemeris is to be created.
finalTime End time up to which ephemeris is to be created.
timeStep Time step with which interpolated data from Spice should be created.
Returns
Default settings for a body's ephemeris.
Definition at line 56 of file defaultBodies.cpp.
getDefaultGravityFieldSettings()
std::shared_ptr< GravityFieldSettings > tudat::simulation_setup::getDefaultGravityFieldSettings (const std::string & bodyName, const double initialTime, const double finalTime)
Function to create default settings for a body's gravity field model. Currently set to a point mass gravty field, with the gravitational parameter obtained from Spice.
Parameters
bodyName Name of body for which default gravity field settings are to be retrieved.
initialTime Start time at which environment models in body are to be created (not currently used by this function, but included for consistency).
finalTime End time up to which environment models in body are to be created (not currently used by this function, but included for consistency).
Returns
Default settings for a body's gravity field model.
Definition at line 72 of file defaultBodies.cpp.
References central_spice, egm96, jgmro120d, and lpe200.
Referenced by getDefaultSingleBodySettings().
getDefaultRotationModelSettings()
std::shared_ptr< RotationModelSettings > tudat::simulation_setup::getDefaultRotationModelSettings (const std::string & bodyName, const double initialTime, const double finalTime)
Function to create default settings for a body's rotation model.
Function to create default settings for a body's rotation model. Currently set to a rotation model taken directly from Spice
Parameters
bodyName Name of body for which default rotation model settings are to be retrieved.
initialTime Start time at which environment models in body are to be created (not currently used by this function, but included for consistency).
finalTime End time up to which environment models in body are to be created (not currently used by this function, but included for consistency).
Returns
Default settings for a body's rotation model.
Definition at line 102 of file defaultBodies.cpp.
References spice_rotation_model, and TUDAT_UNUSED_PARAMETER.
Referenced by getDefaultSingleBodySettings().
getDefaultBodyShapeSettings()
std::shared_ptr< BodyShapeSettings > tudat::simulation_setup::getDefaultBodyShapeSettings (const std::string & bodyName, const double initialTime, const double finalTime)
Function to create default settings for a body's shape model. Currently set to a spherical model, with the radius taken from Spice
Parameters
bodyName Name of body for which default shape model settings are to be retrieved.
initialTime Start time at which environment models in body are to be created (not currently used by this function, but included for consistency).
finalTime End time up to which environment models in body are to be created (not currently used by this function, but included for consistency).
Definition at line 120 of file defaultBodies.cpp.
References tudat::spice_interface::getAverageRadius(), and TUDAT_UNUSED_PARAMETER.
Referenced by getDefaultSingleBodySettings().
getDefaultSingleBodySettings()
std::shared_ptr< BodySettings > tudat::simulation_setup::getDefaultSingleBodySettings (const std::string & body, const double initialTime, const double finalTime, const double timeStep = 300.0)
Function to create default settings for a single for body.
Function to create default settings for a single body from which to create a object using the code in createBodies.h/.cpp. This function is included to streamline and simplify the creation of typical celestial bodies. The default settings for the various environment models of the body are defined in the various functions defined in this file.
Parameters
body Name of body for which default settings are to be retrieved.
initialTime Start time at which environment models in body are to be created (included as some environment models require e.g., interpolators to be created over a certain time period).
finalTime End time up to which environment models in body are to be created (included as some environment models require e.g., interpolators to be created over a certain time period).
timeStep Time step with which interpolated data from Spice should be created.
Definition at line 137 of file defaultBodies.cpp.
References getDefaultAtmosphereModelSettings(), getDefaultBodyShapeSettings(), getDefaultEphemerisSettings(), getDefaultGravityFieldSettings(), and getDefaultRotationModelSettings().
Referenced by getDefaultBodySettings().
getDefaultBodySettings() [1/2]
std::map< std::string, std::shared_ptr< BodySettings > > tudat::simulation_setup::getDefaultBodySettings (const std::vector< std::string > & bodies, const double initialTime, const double finalTime, const double timeStep = 300.0)
Function to create default settings from which to create a set of body objects using the code in createBodies.h/.cpp. This function is included to streamline and simplify the creation of typical celestial bodies. The default settings for the various environment models of the body are defined in the various functions defined in this file.
Parameters
bodies List of bodies for which default settings are to be retrieved.
initialTime Start time at which environment models in body are to be created (included as some environment models require e.g., interpolators to be created over a certain time period).
finalTime End time up to which environment models in body are to be created (included as some environment models require e.g., interpolators to be created over a certain time period).
timeStep Time step with which interpolated data from Spice should be created.
Returns
Default settings from which to create a set of body objects.
Definition at line 176 of file defaultBodies.cpp.
References getDefaultSingleBodySettings().
Referenced by tudat::unit_tests::executeEarthOrbiterBiasEstimation(), tudat::unit_tests::executeEarthOrbiterParameterEstimation(), tudat::unit_tests::executePlanetaryParameterEstimation(), and tudat::json_interface::updateBodiesFromJSON().
getDefaultBodySettings() [2/2]
std::map< std::string, std::shared_ptr< BodySettings > > tudat::simulation_setup::getDefaultBodySettings (const std::vector< std::string > & bodies)
Function to create default settings from which to create a set of body objects, without stringent limitations on time-interval of validity of environment.
Function to create default settings from which to create a set of body objects, without stringent limitations on time-interval of validity of environment.
This function is included to streamline and simplify the creation of typical celestial bodies. The default settings for the various environment models of the body are defined in the various functions defined in this file.
Parameters
bodies List of bodies for which default settings are to be retrieved.
Returns
Default settings from which to create a set of body objects.
Definition at line 196 of file defaultBodies.cpp.
References getDefaultSingleBodySettings(), and TUDAT_NAN.
createTidalLoveNumberInterfaces()
std::vector< std::shared_ptr< orbit_determination::TidalLoveNumberPartialInterface > > tudat::simulation_setup::createTidalLoveNumberInterfaces (const NamedBodyMap & bodyMap, const std::string & acceleratingBodyName)
Function to create a list of objects that can be used to compute partials of tidal gravity field variations
Parameters
bodyMap List of all body objects
acceleratingBodyName Name of body for which tidal gravity field variation objects are to be created
Returns
List of tidal gravity field variation objects, one for each such field variation object of bodyacceleratingBodyName
Definition at line 22 of file createAccelerationPartials.cpp.
References tudat::utilities::dynamicCastSVectorToTVector(), tudat::simulation_setup::Body::getCurrentRotationToLocalFrame(), and tudat::simulation_setup::Body::getPosition().
Referenced by createAnalyticalAccelerationPartial().
createAnalyticalAccelerationPartial< double >()
template std::shared_ptr< acceleration_partials::AccelerationPartial > tudat::simulation_setup::createAnalyticalAccelerationPartial< double > (std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, const std::pair< std::string, std::shared_ptr< simulation_setup::Body > > acceleratedBody, const std::pair< std::string, std::shared_ptr< simulation_setup::Body > > acceleratingBody, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< double > > parametersToEstimate)
createAccelerationPartialsMap< double >()
template orbit_determination::StateDerivativePartialsMap tudat::simulation_setup::createAccelerationPartialsMap< double > (const basic_astrodynamics::AccelerationMap & accelerationMap, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< double > > parametersToEstimate)
createAccelerationPartialsMap< long double >()
template orbit_determination::StateDerivativePartialsMap tudat::simulation_setup::createAccelerationPartialsMap< long double > (const basic_astrodynamics::AccelerationMap & accelerationMap, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< long double > > parametersToEstimate)
createAnalyticalAccelerationPartial()
template<typename InitialStateParameterType = double> std::shared_ptr< acceleration_partials::AccelerationPartial > tudat::simulation_setup::createAnalyticalAccelerationPartial (std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, const std::pair< std::string, std::shared_ptr< simulation_setup::Body > > acceleratedBody, const std::pair< std::string, std::shared_ptr< simulation_setup::Body > > acceleratingBody, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > > parametersToEstimate = std::shared_ptr< estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > >())
Function to create a single acceleration partial derivative object.
Parameters
accelerationModel Acceleration model for which a partial derivative is to be computed.
acceleratedBody Pair of name and object of body undergoing acceleration
acceleratingBody Pair of name and object of body exerting acceleration
bodyMap List of all body objects
parametersToEstimate List of parameters that are to be estimated. Empty by default, only required for selected types of partials (e.g. spherical harmonic acceleration w.r.t. rotational parameters).
Returns
Single acceleration partial derivative object.
Definition at line 63 of file createAccelerationPartials.h.
References tudat::basic_astrodynamics::aerodynamic, tudat::basic_astrodynamics::cannon_ball_radiation_pressure, tudat::basic_astrodynamics::central_gravity, tudat::observation_partials::createRotationMatrixPartials(), createTidalLoveNumberInterfaces(), tudat::basic_astrodynamics::direct_tidal_dissipation_in_central_body_acceleration, tudat::basic_astrodynamics::direct_tidal_dissipation_in_orbiting_body_acceleration, tudat::basic_astrodynamics::empirical_acceleration, tudat::basic_astrodynamics::getAccelerationModelType(), tudat::simulation_setup::Body::getState(), tudat::basic_astrodynamics::mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::relativistic_correction_acceleration, tudat::simulation_setup::Body::setState(), tudat::basic_astrodynamics::spherical_harmonic_gravity, tudat::basic_astrodynamics::third_body_central_gravity, tudat::basic_astrodynamics::third_body_mutual_spherical_harmonic_gravity, and tudat::basic_astrodynamics::third_body_spherical_harmonic_gravity.
Referenced by createAccelerationPartialsMap().
createAccelerationPartialsMap()
template<typename InitialStateParameterType > orbit_determination::StateDerivativePartialsMap tudat::simulation_setup::createAccelerationPartialsMap (const basic_astrodynamics::AccelerationMap & accelerationMap, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > > parametersToEstimate)
This function creates acceleration partial objects for translational dynamics from acceleration models and list of bodies' states of which derivatives are needed. The return type is an StateDerivativePartialsMap, a standardized type for communicating such lists of these objects.
Parameters
accelerationMap Map of maps containing list of acceleration models, identifying which acceleration acts on which body.
bodyMap List of body objects constituting environment for calculations.
parametersToEstimate List of parameters which are to be estimated.
Returns
List of acceleration-partial-calculating objects in StateDerivativePartialsMap type.
Definition at line 436 of file createAccelerationPartials.h.
References tudat::estimatable_parameters::arc_wise_initial_body_state, createAnalyticalAccelerationPartial(), and tudat::estimatable_parameters::initial_body_state.
createDoubleParameterToEstimate() [1/2]
std::shared_ptr< EstimatableParameter< double > > tudat::simulation_setup::createDoubleParameterToEstimate (const std::shared_ptr< EstimatableParameterSettings > & doubleParameterName, const NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationModelMap)
Definition at line 42 of file createEstimatableParameters.cpp.
References tudat::estimatable_parameters::constant_drag_coefficient, tudat::estimatable_parameters::constant_rotation_rate, tudat::estimatable_parameters::direct_dissipation_tidal_time_lag, tudat::estimatable_parameters::equivalence_principle_lpi_violation_parameter, tudat::gravitation::getTidalDissipationAccelerationModels(), tudat::estimatable_parameters::gravitational_parameter, tudat::estimatable_parameters::isDoubleParameter(), tudat::estimatable_parameters::ppn_parameter_beta, tudat::estimatable_parameters::ppn_parameter_gamma, tudat::relativity::ppnParameterSet, and tudat::estimatable_parameters::radiation_pressure_coefficient.
Referenced by createParametersToEstimate().
createVectorParameterToEstimate() [1/2]
std::shared_ptr< EstimatableParameter< Eigen::VectorXd > > tudat::simulation_setup::createVectorParameterToEstimate (const std::shared_ptr< EstimatableParameterSettings > & vectorParameterName, const NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationModelMap)
Definition at line 209 of file createEstimatableParameters.cpp.
References tudat::estimatable_parameters::arc_wise_empirical_acceleration_coefficients, tudat::estimatable_parameters::arc_wise_radiation_pressure_coefficient, tudat::estimatable_parameters::arcwise_constant_additive_observation_bias, tudat::estimatable_parameters::arcwise_constant_relative_observation_bias, tudat::estimatable_parameters::constant_additive_observation_bias, tudat::estimatable_parameters::constant_relative_observation_bias, tudat::basic_astrodynamics::empirical_acceleration, tudat::estimatable_parameters::empirical_acceleration_coefficients, tudat::estimatable_parameters::full_degree_tidal_love_number, tudat::basic_astrodynamics::getAccelerationModelType(), tudat::gravitation::SphericalHarmonicsGravityField::getCosineCoefficients(), tudat::observation_models::getLinkEndIndicesForLinkEndTypeAtObservable(), tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getNominalCosineCoefficients(), tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getNominalSineCoefficients(), tudat::gravitation::SphericalHarmonicsGravityField::getSineCoefficients(), tudat::estimatable_parameters::ground_station_position, tudat::estimatable_parameters::isDoubleParameter(), tudat::estimatable_parameters::rotation_pole_position, tudat::gravitation::SphericalHarmonicsGravityField::setCosineCoefficients(), tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::setNominalCosineCoefficients(), tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::setNominalSineCoefficients(), tudat::gravitation::SphericalHarmonicsGravityField::setSineCoefficients(), tudat::estimatable_parameters::single_degree_variable_tidal_love_number, tudat::estimatable_parameters::spherical_harmonics_cosine_coefficient_block, and tudat::estimatable_parameters::spherical_harmonics_sine_coefficient_block.
Referenced by createParametersToEstimate().
createInitialDynamicalStateParameterToEstimate()
template<typename InitialStateParameterType = double> std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > > > tudat::simulation_setup::createInitialDynamicalStateParameterToEstimate (const NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > & parameterSettings)
Function to create interface object for estimating parameters representing an initial dynamical state.
Parameters
bodyMap Map of body objects containing the fll simulation environment.
parameterSettings Object defining the parameter interface that is to be created.
Returns
Interface object for estimating an initial state.
Definition at line 38 of file createEstimatableParameters.h.
References tudat::estimatable_parameters::arc_wise_initial_body_state, tudat::propagators::getInitialStateOfBody(), tudat::estimatable_parameters::initial_body_state, tudat::estimatable_parameters::InitialTranslationalStateEstimatableParameterSettings< InitialStateParameterType >::initialStateValue_, and tudat::estimatable_parameters::isParameterDynamicalPropertyInitialState().
createDoubleParameterToEstimate() [2/2]
std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > tudat::simulation_setup::createDoubleParameterToEstimate (const std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > & doubleParameterName, const NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationModelMap = basic_astrodynamics::AccelerationMap())
Function to create an interface object for estimating a parameter defined by a single double value
Parameters
doubleParameterName Object defining the parameter interface that is to be created.
bodyMap Map of body objects containing the fll simulation environment.
accelerationModelMap List of acceleration models used in simulations; empty by default (only required for selected parameters).
Returns
Interface object for estimating parameter.
createVectorParameterToEstimate() [2/2]
std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > tudat::simulation_setup::createVectorParameterToEstimate (const std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > & vectorParameterName, const NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationModelMap = basic_astrodynamics::AccelerationMap())
Function to create an interface object for estimating a parameter defined by a list of single double values
Parameters
vectorParameterName Object defining the parameter interface that is to be created.
bodyMap Map of body objects containing the fll simulation environment.
accelerationModelMap List of acceleration models used in simulations; empty by default (only required for selected parameters).
Returns
Interface object for estimating parameter.
createParametersToEstimate()
template<typename InitialStateParameterType = double> std::shared_ptr< estimatable_parameters::EstimatableParameterSet< InitialStateParameterType > > tudat::simulation_setup::createParametersToEstimate (const std::vector< std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > > & parameterNames, const NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationModelMap = basic_astrodynamics::AccelerationMap())
Function to create the interface object for estimating any number/type of parameters. This can include both environmental parameters and initial dynamical states. The types of parameters are defined by the parameterNames m input variables
Parameters
parameterNames List of objects defining the parameters that are to be estimated.
bodyMap Map of body objects containing the fll simulation environment.
accelerationModelMap List of acceleration models used in simulations; empty by default (only required for selected parameters).
Returns
Interface object for estimating a set of parameters.
Definition at line 192 of file createEstimatableParameters.h.
References createDoubleParameterToEstimate(), createVectorParameterToEstimate(), tudat::estimatable_parameters::isDoubleParameter(), and tudat::estimatable_parameters::isParameterDynamicalPropertyInitialState().
Referenced by tudat::unit_tests::executeEarthOrbiterBiasEstimation(), and tudat::unit_tests::executeEarthOrbiterParameterEstimation().
createStateDerivativePartials< double, double >()
template std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > tudat::simulation_setup::createStateDerivativePartials< double, double > (const std::unordered_map< propagators::IntegratedStateType, std::vector< std::shared_ptr< propagators::SingleStateTypeDerivative< double, double > > > > stateDerivativeModels, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< double > > parametersToEstimate)
createStateDerivativePartials()
template<typename StateScalarType , typename TimeType > std::map< propagators::IntegratedStateType, orbit_determination::StateDerivativePartialsMap > tudat::simulation_setup::createStateDerivativePartials (const std::unordered_map< propagators::IntegratedStateType, std::vector< std::shared_ptr< propagators::SingleStateTypeDerivative< StateScalarType, TimeType > > > > stateDerivativeModels, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate)
Function to create a set of state derivative partial objects for any propagated state types.
Parameters
stateDerivativeModels List of state derivative models, ordered by state type (key)
bodyMap List of boy objects storing environment models of simulation
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values. return List partials of state derivative models from. The key is the type of dynamics for which partials are taken, the values are StateDerivativePartialsMap (see StateDerivativePartialsMap definition for details).
Definition at line 37 of file createStateDerivativePartials.h.
References tudat::propagators::translational_state.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
determinePostfitParameterInfluence()
template<typename TimeType = double, typename StateScalarType = double> std::pair< std::shared_ptr< PodOutput< StateScalarType > >, Eigen::VectorXd > tudat::simulation_setup::determinePostfitParameterInfluence (const NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< propagators::PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSettings > perturbedParameterSettings, const double simulatedObservationInterval, const std::vector< double > parameterPerturbations, const std::vector< int > parameterIndices, const int numberOfIterations = 2)
Function that determines how well the translational dynamics of N bodies can absorb the influence of a change in an environmental parameter value
The methods outlined by e.g. Dirkx et al. (2016); Planetary and Space Science 134:82-95. This function uses a nominal dynamical model to simulate ideal observations of a set of N bodies' 3-dimensional positions. These observations are then used as input to an orbit determination routing in which a set of parameters have their values adjusted w.r.t. the nominal case. In the orbit determination, only the initial states of the N bodies are estimated. As such, this function provides the degree to which a change (e.g. uncertainty) in the environment can be mimicked by a change in the bodies initial conditions.
Parameters
bodyMap List of body objects that comprises the environment
integratorSettings Settings for numerical integrator.
propagatorSettings Settings for propagator.
perturbedParameterSettings Type of parameter that is to be adjusted in analysis.
simulatedObservationInterval Time interval between consecutive simulated 3-dimensional position observations
parameterPerturbations Perturbations in the parameter vector that are to be used
parameterIndices Indices in the vector of perturbed parameter at which to apply the perturbations in parameterPerturbations, e.g. index parameterIndices(i) of the parameter vector gets perturbation parameterPerturbations(i)
numberOfIterations Number of iterations to use in the orbit determination loop
Returns
Pair of estimation output (first) and adjustment to initial state vectors (second)
Definition at line 50 of file determinePostFitParameterInfluence.h.
References tudat::ephemerides::getTabulatedEphemerisSafeInterval(), tudat::observation_models::observed_body, and tudat::observation_models::position_observable.
getConcatenatedWeightsVector< double >()
template Eigen::Matrix< double, Eigen::Dynamic, 1 > tudat::simulation_setup::getConcatenatedWeightsVector< double > (const typename std::map< observation_models::ObservableType, std::map< observation_models::LinkEnds, Eigen::VectorXd > > & weightsData)
getConcatenatedWeightsVector< long double >()
template Eigen::Matrix< long double, Eigen::Dynamic, 1 > tudat::simulation_setup::getConcatenatedWeightsVector< long double > (const typename std::map< observation_models::ObservableType, std::map< observation_models::LinkEnds, Eigen::VectorXd > > & weightsData)
getConcatenatedWeightsVector()
template<typename ObservationScalarType = double> Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > tudat::simulation_setup::getConcatenatedWeightsVector (const typename std::map< observation_models::ObservableType, std::map< observation_models::LinkEnds, Eigen::VectorXd > > & weightsData)
Function to create a single vector of observation weights from weights sorted by link ends/observation type, the ruesulting vector is sorted according to the iteration order of the inner and outer maps in the weightsData input
Parameters
weightsData Weights sorted by link ends and observation type
Returns
Concatenated vector of weights
Definition at line 41 of file orbitDeterminationManager.h.
Referenced by tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::estimateParameters().
getConcatenatedTimeVector()
template<typename ObservationScalarType = double, typename TimeType = double> std::vector< TimeType > tudat::simulation_setup::getConcatenatedTimeVector (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType & measurementData)
Function to create a single vector of times from all observation times, created by concatenating all observation times, in the order of first observable type and the link ends, as they are stored in the input data type (PodInputType).
Parameters
measurementData Data structure containing all measurement data, first by observable type, then by link ends.
Returns
Concatenated vector of times.
Definition at line 30 of file podProcessing.h.
References tudat::observation_models::getObservableSize().
getConcatenatedGroundStationIndex()
template<typename ObservationScalarType = double, typename TimeType = double> std::pair< std::vector< int >, std::map< observation_models::LinkEnds, int > > tudat::simulation_setup::getConcatenatedGroundStationIndex (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType & measurementData)
Function to create a single vector of link end indices for all observations, created by assigning an integer to each set of link ends, and these indices for all observations, in the order of first observable type and the link ends, as they are stored in the input data type (PodInputType). Output vector has same size as vector of observables, so for an observation of size N, N values are added to the output vector
Parameters
measurementData Data structure containing all measurement data, first by observable type, then by link ends.
Returns
Concatenated vector of link end indices (first), mapping of LinkEnds to index (second)
Definition at line 85 of file podProcessing.h.
References tudat::observation_models::getObservableSize().
getConcatenatedObservableTypes()
template<typename ObservationScalarType = double, typename TimeType = double> std::vector< int > tudat::simulation_setup::getConcatenatedObservableTypes (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType & measurementData)
Function to create a single vector of observable types for all observations, in the order of first observable type and the link ends, as they are stored in the input data type (PodInputType). Output vector has same size as vector of observables, so for an observation of size N, N values are added to the output vector
Parameters
measurementData Data structure containing all measurement data, first by observable type, then by link ends.
Returns
Concatenated vector of observable types.
Definition at line 140 of file podProcessing.h.
References tudat::observation_models::getObservableSize().
getConcatenatedMeasurementVector()
template<typename ObservationScalarType = double, typename TimeType = double> Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > tudat::simulation_setup::getConcatenatedMeasurementVector (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType & measurementData)
Function to create a single vector of observations from full observation input data, created by concatenating all observations in the order of first observable type and the link ends, as they are stored in the input data type (PodInputType).
Parameters
measurementData Data structure containing all measurement data, first by observable type, then by link ends.
Returns
Concatenated vector of observations.
Definition at line 178 of file podProcessing.h.
getTimeOrderedInformationMatrix()
template<typename ObservationScalarType = double, typename TimeType = double> std::pair< Eigen::MatrixXd, std::vector< TimeType > > tudat::simulation_setup::getTimeOrderedInformationMatrix (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType & measurementData, const Eigen::MatrixXd & typeAndLinkSortedInformationMatrix, std::vector< int > & timeOrder)
Function to sort the information matrix (e.g. matrix with partial derivatives of observables w.r.t. estimated parameters) by the time of the associated observations, in ascending order. That is, the time associated withthe observation wrt which the partial is stored in a given line of the information matrix is used to determine the new row position of that row in the ordered matrix. The lowest time is the first row; the highest time is the last row.
Parameters
measurementData Set of all measurement data, ordered by observable type and link end set
typeAndLinkSortedInformationMatrix information matrix, in original ordering (observable type and link ends) as produced by OrbitDeterminationManager.
timeOrder Order in which the observation time vector was sorted to obtain the time-sorted information matrix (returned by reference_
Returns
Information matrix, ordered by associated observation time
Definition at line 222 of file podProcessing.h.
References tudat::utilities::getSortOrderOfVectorAndSortedVector().
calculateCovarianceMatrixAsFunctionOfTime() [1/2]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< TimeType, Eigen::MatrixXd > tudat::simulation_setup::calculateCovarianceMatrixAsFunctionOfTime (const typename OrbitDeterminationManager< ObservationScalarType, TimeType >::PodInputType & measurementData, const Eigen::MatrixXd & typeAndLinkSortedNormalizedInformationMatrix, const Eigen::VectorXd & normalizationFactors, const double outputTimeStep, const Eigen::VectorXd & diagonalOfWeightMatrix, const Eigen::MatrixXd & normalizedInverseAPrioriCovariance)
Function to create a map of the estimation covariance as a function of time
Parameters
measurementData Data structure containing all observable values, as well as associated times and reference link ends
typeAndLinkSortedNormalizedInformationMatrix Information matrix, normalized by the normalizationFactors, and sorted as in the normalizationFactors: first by observable type, then by link ends
normalizationFactors Values by which the parameters (and partials) have been normalized, in order to stabilize the solution of the normal equations
outputTimeStep Time step with which the covariance is to be computed for the output map
diagonalOfWeightMatrix Vector containing the diagonal of the weights matrix used in the estimation
normalizedInverseAPrioriCovariance Inverse a priori covariance matrix, with parameters normalized by normalizationFactors
Returns
Covariance (map values) as a function of time (map keys) for the given estimation input settings and output times.
Definition at line 271 of file podProcessing.h.
References tudat::linear_algebra::calculateInverseOfUpdatedCovarianceMatrix(), and tudat::interpolators::BinarySearchLookupScheme< IndependentVariableType >::findNearestLowerNeighbour().
calculateCovarianceMatrixAsFunctionOfTime() [2/2]
template<typename ObservationScalarType = double, typename TimeType = double, typename StateScalarType = ObservationScalarType, typename ParameterScalarType = double> std::map< TimeType, Eigen::MatrixXd > tudat::simulation_setup::calculateCovarianceMatrixAsFunctionOfTime (const std::shared_ptr< PodInput< ObservationScalarType, TimeType > > & podInputData, const std::shared_ptr< PodOutput< ParameterScalarType > > & podOutputData, const double outputTimeStep)
Function to create a map of the estimation covariance as a function of time
Parameters
podInputData Data structure containing all input to the orbit determination process.
podOutputData Data structure containing all output of the orbit determination process.
outputTimeStep Time step with which the covariance is to be computed for the output map.
Returns
Covariance (map values) as a function of time (map keys) for the given estimation input settings and output times.
Definition at line 382 of file podProcessing.h.
createDirectGravitationalAcceleration()
std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > tudat::simulation_setup::createDirectGravitationalAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const std::string & nameOfCentralBody = "", const bool isCentralBody = 0)
Function to create a direct (i.e. not third-body) gravitational acceleration of any type (i.e. point mass, spherical harmonic, mutual spherical harmonic).
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the gravitational acceleration.
nameOfBodyUndergoingAcceleration Name of body that is being accelerated.
nameOfBodyExertingAcceleration Name of body that is exerting the gravitational acceleration.
accelerationSettings Settings object for the gravitational acceleration.
nameOfCentralBody Name of central body in frame centered at which acceleration is to be calculated.
isCentralBody Boolean defining whether the body undergoing the acceleration is the central body for a third-body acceleration, of which the return object of this funciton is one of the sub-parts. Boolean is only used when creating mutual spherical harmonic acceleration, to ensure the correct usage of the acceleration settings.
Returns
Direct gravitational acceleration model of requested settings.
Definition at line 42 of file createAccelerationModels.cpp.
References tudat::basic_astrodynamics::central_gravity, createCentralGravityAcceleratioModel(), createMutualSphericalHarmonicsGravityAcceleration(), createSphericalHarmonicsGravityAcceleration(), tudat::basic_astrodynamics::mutual_spherical_harmonic_gravity, and tudat::basic_astrodynamics::spherical_harmonic_gravity.
Referenced by createGravitationalAccelerationModel(), and createThirdBodyGravitationalAcceleration().
createThirdBodyGravitationalAcceleration()
std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > tudat::simulation_setup::createThirdBodyGravitationalAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::string & nameOfCentralBody, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create a direct third-body gravitational acceleration of any type (i.e. point mass, spherical harmonic, mutual spherical harmonic).
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the gravitational acceleration.
centralBody Pointer to central body in frame centered at which acceleration is to be calculated.
nameOfBodyUndergoingAcceleration Name of body that is being accelerated.
nameOfBodyExertingAcceleration Name of body that is exerting the gravitational acceleration.
nameOfCentralBody Name of central body in frame centered at which acceleration is to be calculated.
accelerationSettings Settings object for the gravitational acceleration.
Returns
Third-body gravitational acceleration model of requested settings.
Definition at line 100 of file createAccelerationModels.cpp.
References tudat::basic_astrodynamics::central_gravity, createDirectGravitationalAcceleration(), tudat::basic_astrodynamics::mutual_spherical_harmonic_gravity, and tudat::basic_astrodynamics::spherical_harmonic_gravity.
Referenced by createGravitationalAccelerationModel().
createGravitationalAccelerationModel()
std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > tudat::simulation_setup::createGravitationalAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string & nameOfCentralBody)
Function to create a third-body or direct gravitational acceleration of any type (i.e. point mass, spherical harmonic, mutual spherical harmonic).
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the gravitational acceleration.
accelerationSettings Settings object for the gravitational acceleration.
centralBody Pointer to central body in frame centered at which acceleration is to be calculated.
nameOfBodyUndergoingAcceleration Name of body that is being accelerated.
nameOfBodyExertingAcceleration Name of body that is exerting the gravitational acceleration.
nameOfCentralBody Name of central body in frame centered at which acceleration is to be calculated.
Returns
Gravitational acceleration model of requested settings.
Definition at line 160 of file createAccelerationModels.cpp.
References tudat::basic_astrodynamics::central_gravity, createDirectGravitationalAcceleration(), createThirdBodyGravitationalAcceleration(), tudat::ephemerides::isFrameInertial(), tudat::basic_astrodynamics::mutual_spherical_harmonic_gravity, and tudat::basic_astrodynamics::spherical_harmonic_gravity.
Referenced by createAccelerationModel().
createCentralGravityAcceleratioModel()
std::shared_ptr< gravitation::CentralGravitationalAccelerationModel3d > tudat::simulation_setup::createCentralGravityAcceleratioModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const bool useCentralBodyFixedFrame)
Function to create central gravity acceleration model from bodies exerting and undergoing acceleration.
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the central gravity acceleration.
nameOfBodyUndergoingAcceleration Name of body that is being accelerated.
nameOfBodyExertingAcceleration Name of body that is exerting the central gravity acceleration.
useCentralBodyFixedFrame Boolean setting whether the central attraction of body undergoing acceleration on body exerting acceleration is to be included in acceleration model. Should be set to true in case the body undergoing acceleration is a celestial body (with gravity field) and integration is performed in the frame centered at the body exerting acceleration.
Returns
Central gravity acceleration model pointer.
Definition at line 202 of file createAccelerationModels.cpp.
References tudat::gravitation::GravityFieldModel::getGravitationalParameter(), and tudat::simulation_setup::Body::getPosition().
Referenced by createDirectGravitationalAcceleration(), and createThirdBodyCentralGravityAccelerationModel().
createSphericalHarmonicsGravityAcceleration()
std::shared_ptr< gravitation::SphericalHarmonicsGravitationalAccelerationModel > tudat::simulation_setup::createSphericalHarmonicsGravityAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const bool useCentralBodyFixedFrame)
Function to create spherical harmonic gravity acceleration model from bodies exerting and undergoing acceleration.
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the spherical harmonic gravity acceleration.
nameOfBodyUndergoingAcceleration Name of body that is being accelerated.
nameOfBodyExertingAcceleration Name of body that is exerting the spherical harmonic gravity acceleration.
accelerationSettings Settings for acceleration model that is to be created (should be of derived type associated with spherical harmonic acceleration.
useCentralBodyFixedFrame Boolean setting whether the central attraction of body undergoing acceleration on body exerting acceleration is to be included in acceleration model. Should be set to true in case the body undergoing acceleration is a celestial body (with gravity field) and integration is performed in the frame centered at the body exerting acceleration.
Returns
Spherical harmonic gravity acceleration model pointer.
Definition at line 262 of file createAccelerationModels.cpp.
References tudat::gravitation::SphericalHarmonicsGravityField::getCosineCoefficientsBlock(), tudat::simulation_setup::Body::getCurrentRotationToGlobalFrame(), tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::simulation_setup::Body::getPosition(), and tudat::gravitation::SphericalHarmonicsGravityField::getSineCoefficientsBlock().
Referenced by createDirectGravitationalAcceleration(), and createThirdBodySphericalHarmonicGravityAccelerationModel().
createMutualSphericalHarmonicsGravityAcceleration()
std::shared_ptr< gravitation::MutualSphericalHarmonicsGravitationalAccelerationModel > tudat::simulation_setup::createMutualSphericalHarmonicsGravityAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const bool useCentralBodyFixedFrame, const bool acceleratedBodyIsCentralBody)
Function to create mutual spherical harmonic gravity acceleration model from bodies exerting and undergoing acceleration.
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the mutual spherical harmonic gravity acceleration.
nameOfBodyUndergoingAcceleration Name of body that is being accelerated.
nameOfBodyExertingAcceleration Name of body that is exerting the mutual spherical harmonic gravity acceleration.
accelerationSettings Settings for acceleration model that is to be created (should be of derived type associated with mutual spherical harmonic acceleration).
useCentralBodyFixedFrame Boolean setting whether the central attraction of body undergoing acceleration on body exerting acceleration is to be included in acceleration model. Should be set to true in case the body undergoing acceleration is a celestial body (with gravity field) and integration is performed in the frame centered at the body exerting acceleration.
acceleratedBodyIsCentralBody Boolean defining whether the body undergoing the acceleration is the central body for a third-body acceleration, of which the return object of this funciton is one of the sub-parts.
Returns
Mutual spherical harmonic gravity acceleration model pointer.
Definition at line 369 of file createAccelerationModels.cpp.
References tudat::gravitation::SphericalHarmonicsGravityField::getCosineCoefficientsBlock(), tudat::simulation_setup::Body::getCurrentRotationToGlobalFrame(), tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::simulation_setup::Body::getPosition(), and tudat::gravitation::SphericalHarmonicsGravityField::getSineCoefficientsBlock().
Referenced by createDirectGravitationalAcceleration(), and createThirdBodyMutualSphericalHarmonicGravityAccelerationModel().
createThirdBodyCentralGravityAccelerationModel()
std::shared_ptr< gravitation::ThirdBodyCentralGravityAcceleration > tudat::simulation_setup::createThirdBodyCentralGravityAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::string & nameOfCentralBody)
Function to create a third body central gravity acceleration model from bodies exerting and undergoing acceleration, as well as the central body, w.r.t. which the integration is to be performed.
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the acceleration.
centralBody Pointer to central body in frame centered at which acceleration is to be calculated.
nameOfBodyUndergoingAcceleration Name of object of body that is being accelerated.
nameOfBodyExertingAcceleration Name of object of body that is exerting the central gravity acceleration.
nameOfCentralBody Name of central body in frame cenetered at which acceleration is to be calculated.
Returns
Pointer to object for calculating central gravity acceleration between bodies.
Definition at line 494 of file createAccelerationModels.cpp.
References createCentralGravityAcceleratioModel().
createThirdBodySphericalHarmonicGravityAccelerationModel()
std::shared_ptr< gravitation::ThirdBodySphericalHarmonicsGravitationalAccelerationModel > tudat::simulation_setup::createThirdBodySphericalHarmonicGravityAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::string & nameOfCentralBody, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create a third body spheric harmonic gravity acceleration model from bodies exerting and undergoing acceleration, as well as the central body, w.r.t. which the integration is to be performed.
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the acceleration.
centralBody Pointer to central body in frame centered at which acceleration is to be calculated.
nameOfBodyUndergoingAcceleration Name of object of body that is being accelerated.
nameOfBodyExertingAcceleration Name of object of body that is exerting the central gravity acceleration.
nameOfCentralBody Name of central body in frame cenetered at which acceleration is to be calculated.
accelerationSettings Settings for acceleration model that is to be created (should be of derived type associated with spherical harmonic acceleration).
Returns
Pointer to object for calculating third-body spheric harmonic gravity acceleration between bodies.
Definition at line 522 of file createAccelerationModels.cpp.
References createSphericalHarmonicsGravityAcceleration().
createThirdBodyMutualSphericalHarmonicGravityAccelerationModel()
std::shared_ptr< gravitation::ThirdBodyMutualSphericalHarmonicsGravitationalAccelerationModel > tudat::simulation_setup::createThirdBodyMutualSphericalHarmonicGravityAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< Body > centralBody, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::string & nameOfCentralBody, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create a third body mutual spheric harmonic gravity acceleration model from bodies exerting and undergoing acceleration, as well as the central body, w.r.t. which the integration is to be performed.
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the acceleration.
centralBody Pointer to central body in frame centered at which acceleration is to be calculated.
nameOfBodyUndergoingAcceleration Name of object of body that is being accelerated.
nameOfBodyExertingAcceleration Name of object of body that is exerting the central gravity acceleration.
nameOfCentralBody Name of central body in frame cenetered at which acceleration is to be calculated.
accelerationSettings Settings for acceleration model that is to be created (should be of derived type associated with mutual spherical harmonic acceleration).
Returns
Pointer to object for calculating third-body mutual spheric harmonic gravity acceleration between bodies.
Definition at line 577 of file createAccelerationModels.cpp.
References createMutualSphericalHarmonicsGravityAcceleration().
createAerodynamicAcceleratioModel()
std::shared_ptr< aerodynamics::AerodynamicAcceleration > tudat::simulation_setup::createAerodynamicAcceleratioModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration)
Function to create an aerodynamic acceleration model, automatically creates all required links to environment models, vehicle properies and frame conversions
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the acceleration, i.e. body with the atmosphere through which the accelerated body is flying.
nameOfBodyUndergoingAcceleration Name of object of body that is being accelerated.
nameOfBodyExertingAcceleration Name of object of body that is exerting the acceleration.
Returns
Pointer to object for calculating aerodynamic acceleration.
Definition at line 658 of file createAccelerationModels.cpp.
References tudat::reference_frames::aerodynamic_frame, tudat::reference_frames::body_frame, createAtmosphericFlightConditions(), tudat::reference_frames::getAerodynamicForceTransformationFunction, tudat::simulation_setup::Body::getBodyMass(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentAirspeed(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentDensity(), tudat::aerodynamics::AerodynamicCoefficientInterface::getCurrentForceCoefficients(), tudat::simulation_setup::Body::getCurrentRotationToGlobalFrame(), tudat::aerodynamics::AerodynamicCoefficientInterface::getReferenceArea(), tudat::reference_frames::inertial_frame, and tudat::reference_frames::transformVectorFunctionFromVectorFunctions().
Referenced by createAccelerationModel().
createCannonballRadiationPressureAcceleratioModel()
std::shared_ptr< electro_magnetism::CannonBallRadiationPressureAcceleration > tudat::simulation_setup::createCannonballRadiationPressureAcceleratioModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration)
Function to create a cannonball radiation pressure automatically creates all required links to environment models, vehicle properies and frame conversions
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting the acceleration, i.e. body emitting the radiation.
nameOfBodyUndergoingAcceleration Name of object of body that is being accelerated.
nameOfBodyExertingAcceleration Name of object of body that is exerting the acceleration.
Returns
Pointer to object for calculating cannonball radiation pressures acceleration.
Definition at line 743 of file createAccelerationModels.cpp.
References tudat::electro_magnetism::RadiationPressureInterface::getArea(), tudat::simulation_setup::Body::getBodyMass(), tudat::electro_magnetism::RadiationPressureInterface::getCurrentRadiationPressure(), tudat::simulation_setup::Body::getPosition(), and tudat::electro_magnetism::RadiationPressureInterface::getRadiationPressureCoefficient().
Referenced by createAccelerationModel().
createRelativisticCorrectionAcceleration()
std::shared_ptr< relativity::RelativisticAccelerationCorrection > tudat::simulation_setup::createRelativisticCorrectionAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const NamedBodyMap & bodyMap)
Function to create an orbiter relativistic correction acceleration model (Schwarzschild, Lense-Thirring and/or de Sitter terms).
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of main body that is exerting the acceleration (e.g. Earth for an orbiter around the Earth).
nameOfBodyUndergoingAcceleration Name of object of body that is being accelerated.
nameOfBodyExertingAcceleration Name of object of body that is exerting the acceleration
accelerationSettings Settings for the acceleration model.
bodyMap List of pointers to bodies that comprise the full environment.
Returns
Pointer to object for calculating relativistic correction acceleration.
Definition at line 774 of file createAccelerationModels.cpp.
References tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::simulation_setup::Body::getState(), and tudat::relativity::ppnParameterSet.
Referenced by createAccelerationModel().
createEmpiricalAcceleration()
std::shared_ptr< basic_astrodynamics::EmpiricalAcceleration > tudat::simulation_setup::createEmpiricalAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create empirical acceleration model from body undergoing acceleration and body wrt which its orbit is determined for setting determining phase of once per orbit empirical accelerations.
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body wrt whic orbit of body undergoing the acceleration is calculated.
nameOfBodyUndergoingAcceleration Name of body that is being accelerated.
nameOfBodyExertingAcceleration Name of body wrt whic orbit of body undergoing the acceleration is calculated.
accelerationSettings Object containing additional settings for acceleration model, must be of type EmpiricalAccelerationSettings
Returns
Pointer to object for calculating empiricalt acceleration.
Definition at line 904 of file createAccelerationModels.cpp.
References tudat::gravitation::GravityFieldModel::getGravitationalParameter(), and tudat::simulation_setup::Body::getState().
Referenced by createAccelerationModel().
createThrustAcceleratioModel()
std::shared_ptr< propulsion::ThrustAcceleration > tudat::simulation_setup::createThrustAcceleratioModel (const std::shared_ptr< AccelerationSettings > accelerationSettings, const NamedBodyMap & bodyMap, const std::string & nameOfBodyUndergoingThrust)
Function to create a thrust acceleration model. Creates all required links to environment models, vehicle properies and frame conversions.
Parameters
accelerationSettings Settings of thrust acceleration model.
bodyMap List of pointers to bodies required for the creation of the acceleration model objects.
nameOfBodyUndergoingThrust Name of body that is undergoing the thrust acceleration
Returns
Pointer to object for calculating thrust acceleration.
Definition at line 951 of file createAccelerationModels.cpp.
References tudat::propagators::addEnvironmentUpdates(), createThrustGuidanceModel(), createThrustMagnitudeWrapper(), getBodyFixedThrustDirection(), tudat::simulation_setup::Body::getBodyMass(), tudat::propulsion::BodyFixedForceDirectionGuidance::getCurrentForceDirectionInPropagationFrame(), tudat::propulsion::ThrustMagnitudeWrapper::getCurrentMassRate(), tudat::propulsion::ThrustMagnitudeWrapper::getCurrentThrustMagnitude(), tudat::simulation_setup::Body::getState(), tudat::reference_frames::getVelocityBasedLvlhToInertialRotationFromFunctions(), inertial_thurst_frame, tudat::ephemerides::isFrameInertial(), lvlh_thrust_frame, resetThrustMagnitudeAndDirectionTime(), thrust_direction_from_existing_body_orientation, unspecified_thurst_frame, and updateThrustMagnitudeAndDirection().
Referenced by createAccelerationModel().
createDirectTidalDissipationAcceleration()
std::shared_ptr< gravitation::DirectTidalDissipationAcceleration > tudat::simulation_setup::createDirectTidalDissipationAcceleration (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings)
Function to create a direct tical acceleration model, according to approach of Lainey et al. (2007, 2009, ...).
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of main body that is exerting the acceleration
nameOfBodyUndergoingAcceleration Name of object of body that is being accelerated.
nameOfBodyExertingAcceleration Name of object of body that is exerting the acceleration
accelerationSettings Settings for the acceleration model
Returns
Pointer to object for calculating acceleration.
Definition at line 1048 of file createAccelerationModels.cpp.
References tudat::simulation_setup::Body::getCurrentAngularVelocityVectorInGlobalFrame(), tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::simulation_setup::Body::getState(), and TUDAT_NAN.
Referenced by createAccelerationModel().
createAccelerationModel()
std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > tudat::simulation_setup::createAccelerationModel (const std::shared_ptr< Body > bodyUndergoingAcceleration, const std::shared_ptr< Body > bodyExertingAcceleration, const std::shared_ptr< AccelerationSettings > accelerationSettings, const std::string & nameOfBodyUndergoingAcceleration, const std::string & nameOfBodyExertingAcceleration, const std::shared_ptr< Body > centralBody = std::shared_ptr< Body >(), const std::string & nameOfCentralBody = "", const NamedBodyMap & bodyMap = NamedBodyMap())
Function to create acceleration model object. Type of requested model is checked and corresponding factory function is called.
Parameters
bodyUndergoingAcceleration Pointer to object of body that is being accelerated.
bodyExertingAcceleration Pointer to object of body that is exerting acceleration,
accelerationSettings Settings for acceleration model that is to be created.
nameOfBodyUndergoingAcceleration Name of object of body that is being accelerated.
nameOfBodyExertingAcceleration Name of object of body that is exerting the acceleration.
centralBody Pointer to central body in frame centered at which acceleration is to be calculated (optional, only relevant for third body accelerations).
nameOfCentralBody Name of central body in frame cenetered at which acceleration is to be calculated (optional, only relevant for third body accelerations).
bodyMap List of pointers to bodies required for the creation of the acceleration model objects.
Returns
Acceleration model pointer.
Definition at line 1167 of file createAccelerationModels.cpp.
References tudat::basic_astrodynamics::aerodynamic, tudat::basic_astrodynamics::cannon_ball_radiation_pressure, tudat::basic_astrodynamics::central_gravity, createAerodynamicAcceleratioModel(), createCannonballRadiationPressureAcceleratioModel(), createDirectTidalDissipationAcceleration(), createEmpiricalAcceleration(), createGravitationalAccelerationModel(), createRelativisticCorrectionAcceleration(), createThrustAcceleratioModel(), tudat::basic_astrodynamics::direct_tidal_dissipation_in_central_body_acceleration, tudat::basic_astrodynamics::direct_tidal_dissipation_in_orbiting_body_acceleration, tudat::basic_astrodynamics::empirical_acceleration, tudat::basic_astrodynamics::mutual_spherical_harmonic_gravity, tudat::basic_astrodynamics::relativistic_correction_acceleration, tudat::basic_astrodynamics::spherical_harmonic_gravity, and tudat::basic_astrodynamics::thrust_acceleration.
Referenced by createAccelerationModelsMap().
orderSelectedAccelerationMap()
SelectedAccelerationList tudat::simulation_setup::orderSelectedAccelerationMap (const SelectedAccelerationMap & selectedAccelerationPerBody)
Function to put SelectedAccelerationMap in correct order, to ensure correct model creation
Parameters
selectedAccelerationPerBody List of acceleration settings per body.
Returns
selectedAccelerationPerBody, put in order to ensure correct model creation.
Definition at line 1265 of file createAccelerationModels.cpp.
References tudat::basic_astrodynamics::aerodynamic, and tudat::basic_astrodynamics::thrust_acceleration.
Referenced by createAccelerationModelsMap().
createAccelerationModelsMap() [1/2]
basic_astrodynamics::AccelerationMap tudat::simulation_setup::createAccelerationModelsMap (const NamedBodyMap & bodyMap, const SelectedAccelerationMap & selectedAccelerationPerBody, const std::map< std::string, std::string > & centralBodies)
Function to create acceleration models from a map of bodies and acceleration model types.
Function to create acceleration models from a map of bodies and acceleration model types. The return type can be used to identify both the body undergoing and exerting acceleration.
Parameters
bodyMap List of pointers to bodies required for the creation of the acceleration model objects.
selectedAccelerationPerBody List identifying which bodies exert which type of acceleration(s) on which bodies.
centralBodies Map of central bodies for each body undergoing acceleration.
Returns
List of acceleration model objects, in form of AccelerationMap.
Definition at line 1361 of file createAccelerationModels.cpp.
References createAccelerationModel(), tudat::ephemerides::isFrameInertial(), orderSelectedAccelerationMap(), and tudat::basic_astrodynamics::thrust_acceleration.
Referenced by createAccelerationModelsMap(), tudat::unit_tests::executeEarthOrbiterBiasEstimation(), tudat::unit_tests::executeEarthOrbiterParameterEstimation(), tudat::unit_tests::executePlanetaryParameterEstimation(), and tudat::propagators::TranslationalStatePropagatorSettings< StateScalarType >::resetIntegratedStateModels().
createAccelerationModelsMap() [2/2]
basic_astrodynamics::AccelerationMap tudat::simulation_setup::createAccelerationModelsMap (const NamedBodyMap & bodyMap, const SelectedAccelerationMap & selectedAccelerationPerBody, const std::vector< std::string > & propagatedBodies, const std::vector< std::string > & centralBodies)
Function to create acceleration models from a map of bodies and acceleration model types. The return type can be used to identify both the body undergoing and exerting acceleration.
Parameters
bodyMap List of pointers to bodies required for the creation of the acceleration model objects.
selectedAccelerationPerBody List identifying which bodies exert which type of acceleration(s) on which bodies.
propagatedBodies List of bodies that are to be propagated
centralBodies List of central bodies for each body undergoing acceleration (in same order as propagatedBodies).
Returns
List of acceleration model objects, in form of AccelerationMap.
Definition at line 1486 of file createAccelerationModels.cpp.
References createAccelerationModelsMap().
createMassRateModel()
std::shared_ptr< basic_astrodynamics::MassRateModel > tudat::simulation_setup::createMassRateModel (const std::string & bodyWithMassRate, const std::shared_ptr< MassRateModelSettings > massRateModelSettings, const NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationModels = basic_astrodynamics::AccelerationMap())
Function to create a mass rate model, from specific settings and the full set of environment models.
Parameters
bodyWithMassRate Name of body for which a mass rate model is to be created.
massRateModelSettings Settings for the mass rate model that is to be created.
bodyMap List of pointers to body objects; defines the full simulation environment.
accelerationModels List of acceleration models that are used during numerical propagation (empty by default).
Returns
Mass rate model that is to be used during numerical propagation.
Definition at line 22 of file createMassRateModels.cpp.
References tudat::basic_astrodynamics::custom_mass_rate_model, tudat::basic_astrodynamics::from_thrust_mass_rate_model, tudat::basic_astrodynamics::getAccelerationModelsOfType(), and tudat::basic_astrodynamics::thrust_acceleration.
Referenced by createMassRateModelsMap().
createMassRateModelsMap()
basic_astrodynamics::MassRateModelMap tudat::simulation_setup::createMassRateModelsMap (const NamedBodyMap & bodyMap, const SelectedMassRateModelMap & massRateModelSettings, const basic_astrodynamics::AccelerationMap & accelerationModels = basic_astrodynamics::AccelerationMap())
Function to create a list of mass rate models for a list of bodies, from specific settings and the full set of environment models.
Parameters
bodyMap List of pointers to body objects; defines the full simulation environment.
massRateModelSettings Settings for the mass rate models that are to be created (key is body id).
accelerationModels List of acceleration models that are used during numerical propagation (empty by default).
Returns
Mass rate models that are to be used during numerical propagation (key is body id)..
Definition at line 124 of file createMassRateModels.cpp.
References createMassRateModel().
Referenced by tudat::propagators::MassPropagatorSettings< StateScalarType >::resetIntegratedStateModels().
createSingleArcDynamicsSimulator()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > tudat::simulation_setup::createSingleArcDynamicsSimulator (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< propagators::PropagatorSettings< StateScalarType > > propagatorSettings, const bool areEquationsOfMotionToBeIntegrated = true, const bool clearNumericalSolutions = true, const bool setIntegratedResult = true)
Definition at line 25 of file createNumericalSimulator.h.
createSingleArcVariationalEquationsSolver()
template<typename StateScalarType = double, typename TimeType = double, typename ParameterType = double> std::shared_ptr< propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType > > tudat::simulation_setup::createSingleArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< propagators::PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ParameterType > > parametersToEstimate, const bool integrateDynamicalAndVariationalEquationsConcurrently = 1, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > variationalOnlyIntegratorSettings = std::shared_ptr< numerical_integrators::IntegratorSettings< double > >(), const bool clearNumericalSolution = 1, const bool integrateEquationsOnCreation = 1)
Definition at line 41 of file createNumericalSimulator.h.
createThrustGuidanceModel()
std::shared_ptr< propulsion::BodyFixedForceDirectionGuidance > tudat::simulation_setup::createThrustGuidanceModel (const std::shared_ptr< ThrustDirectionGuidanceSettings > thrustDirectionGuidanceSettings, const NamedBodyMap & bodyMap, const std::string & nameOfBodyWithGuidance, const std::function< Eigen::Vector3d() > bodyFixedThrustOrientation, std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > & magnitudeUpdateSettings)
Function to create the object determining the direction of the thrust acceleration.
Parameters
thrustDirectionGuidanceSettings Settings for thrust direction gudiance.
bodyMap List of pointers to body objects defining the full simulation environment.
nameOfBodyWithGuidance Name of body for which thrust guidance is to be created.
bodyFixedThrustOrientation Thrust direction in body-fixed frame.
magnitudeUpdateSettings Settings for the required updates to the environment during propagation. List is extended by this function as needed.
Returns
Function determining the thrust direction in the propagation frame according to given requirements.
Definition at line 22 of file createThrustModelGuidance.cpp.
References tudat::propagators::body_rotational_state_update, tudat::propagators::body_translational_state_update, colinear_with_state_segment_thrust_direction, custom_thrust_direction, custom_thrust_orientation, tudat::simulation_setup::Body::getCurrentRotationToGlobalFrame(), tudat::propulsion::getForceDirectionColinearWithPosition(), tudat::propulsion::getForceDirectionColinearWithVelocity(), tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::ephemerides::getRelativeState(), tudat::simulation_setup::Body::getState(), mee_costate_based_thrust_direction, thrust_direction_from_existing_body_orientation, and tudat::propagators::vehicle_flight_conditions_update.
Referenced by createThrustAcceleratioModel().
getCombinedThrustDirection()
Eigen::Vector3d tudat::simulation_setup::getCombinedThrustDirection (const std::vector< std::function< Eigen::Vector3d()> > & thrustDirections, const std::vector< std::function< double()> > & thrustMagnitudes)
Function to retrieve the effective thrust direction from a set of thrust sources.
Parameters
thrustDirections List of functions returning thrust directions.
thrustMagnitudes List of functions returning thrust magnitude.
Returns
Effective thrust direction.
Definition at line 224 of file createThrustModelGuidance.cpp.
Referenced by getBodyFixedThrustDirection().
getBodyFixedThrustDirection()
std::function< Eigen::Vector3d() > tudat::simulation_setup::getBodyFixedThrustDirection (const std::shared_ptr< ThrustMagnitudeSettings > thrustMagnitudeSettings, const NamedBodyMap & bodyMap, const std::string bodyName)
Function to create a function that returns the thrust direction in the body-fixed frame.
Parameters
thrustMagnitudeSettings Settings for the thrust magnitude
bodyMap List of body objects that comprises the environment
bodyName Name of body for which thrust is to be created.
Returns
Function that returns the thrust direction in the body-fixed frame.
Definition at line 240 of file createThrustModelGuidance.cpp.
References constant_thrust_magnitude, from_engine_properties_thrust_magnitude, tudat::system_models::EngineModel::getBodyFixedThrustDirection(), getCombinedThrustDirection(), tudat::system_models::EngineModel::getCurrentThrust(), thrust_magnitude_from_dependent_variables, and thrust_magnitude_from_time_function.
Referenced by createThrustAcceleratioModel().
createThrustMagnitudeWrapper()
std::shared_ptr< propulsion::ThrustMagnitudeWrapper > tudat::simulation_setup::createThrustMagnitudeWrapper (const std::shared_ptr< ThrustMagnitudeSettings > thrustMagnitudeSettings, const NamedBodyMap & bodyMap, const std::string & nameOfBodyWithGuidance, std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > & magnitudeUpdateSettings)
Function to create a wrapper object that computes the thrust magnitude
Parameters
thrustMagnitudeSettings Settings for the thrust magnitude
bodyMap List of body objects that comprises the environment
nameOfBodyWithGuidance Name of body for which thrust is to be created.
magnitudeUpdateSettings Environment update settings that are required to compute the thrust direction (updated by function as needed).
Returns
Object used during propagation to compute the thrust direction
Definition at line 369 of file createThrustModelGuidance.cpp.
References constant_thrust_magnitude, from_engine_properties_thrust_magnitude, getPropulsionInputVariables(), thrust_magnitude_from_dependent_variables, and thrust_magnitude_from_time_function.
Referenced by createThrustAcceleratioModel().
updateThrustMagnitudeAndDirection()
void tudat::simulation_setup::updateThrustMagnitudeAndDirection (const std::shared_ptr< propulsion::ThrustMagnitudeWrapper > thrustMagnitudeWrapper, const std::shared_ptr< propulsion::BodyFixedForceDirectionGuidance > thrustDirectionGuidance, const double currentTime)
Function to update the thrust magnitude and direction to current time.
Parameters
thrustMagnitudeWrapper Object used during propagation to compute the thrust magnitude
thrustDirectionGuidance Object used during propagation to compute the body-fixed thrust direction
currentTime Time to which objects are to be updated.
Definition at line 498 of file createThrustModelGuidance.cpp.
Referenced by createThrustAcceleratioModel().
resetThrustMagnitudeAndDirectionTime()
void tudat::simulation_setup::resetThrustMagnitudeAndDirectionTime (const std::shared_ptr< propulsion::ThrustMagnitudeWrapper > thrustMagnitudeWrapper, const std::shared_ptr< propulsion::BodyFixedForceDirectionGuidance > thrustDirectionGuidance, const double currentTime = TUDAT_NAN)
Function to reset the current time variable of the thrust magnitude and direction wrappers. This function does not update the actual thrust direction and guidance; it is typically used to reset the current time to NaN, thereby signalling the need to recompute the magnitude/direction upon next call to update functions
Parameters
thrustMagnitudeWrapper Object used during propagation to compute the thrust magnitude
thrustDirectionGuidance Object used during propagation to compute the body-fixed thrust direction
currentTime New current time variable that is to be set.
Definition at line 508 of file createThrustModelGuidance.cpp.
Referenced by createThrustAcceleratioModel().
createAerodynamicTorqueModel()
std::shared_ptr< aerodynamics::AerodynamicTorque > tudat::simulation_setup::createAerodynamicTorqueModel (const std::shared_ptr< simulation_setup::Body > bodyUndergoingTorque, const std::shared_ptr< simulation_setup::Body > bodyExertingTorque, const std::string & nameOfBodyUndergoingTorque, const std::string & nameOfBodyExertingTorque)
Function to create an aerodynamic torque model, automatically creates all required links to environment models, vehicle properies and frame conversions
Parameters
bodyUndergoingTorque Pointer to object of body that is being accelerated.
bodyExertingTorque Pointer to object of body that is exerting the torque, i.e. body with the atmosphere through which the accelerated body is flying.
nameOfBodyUndergoingTorque Name of object of body that is being accelerated.
nameOfBodyExertingTorque Name of object of body that is exerting the torque.
Returns
Pointer to object for calculating aerodynamic torque.
Definition at line 21 of file createTorqueModel.cpp.
References tudat::reference_frames::aerodynamic_frame, tudat::reference_frames::body_frame, createAtmosphericFlightConditions(), tudat::reference_frames::getAerodynamicForceTransformationFunction, tudat::aerodynamics::AtmosphericFlightConditions::getCurrentAirspeed(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentDensity(), tudat::aerodynamics::AerodynamicCoefficientInterface::getCurrentMomentCoefficients(), tudat::simulation_setup::Body::getCurrentRotationToGlobalFrame(), tudat::aerodynamics::AerodynamicCoefficientInterface::getReferenceArea(), tudat::aerodynamics::AerodynamicCoefficientInterface::getReferenceLengths(), and tudat::reference_frames::transformVectorFunctionFromVectorFunctions().
Referenced by createTorqueModel().
createSecondDegreeGravitationalTorqueModel()
std::shared_ptr< gravitation::SecondDegreeGravitationalTorqueModel > tudat::simulation_setup::createSecondDegreeGravitationalTorqueModel (const std::shared_ptr< simulation_setup::Body > bodyUndergoingTorque, const std::shared_ptr< simulation_setup::Body > bodyExertingTorque, const std::string & nameOfBodyUndergoingTorque, const std::string & nameOfBodyExertingTorque)
Function to create a second-degree gravitational torque.
Parameters
bodyUndergoingTorque Pointer to object of body that is being accelerated.
bodyExertingTorque Pointer to object of body that is exerting the gravitational torque.
nameOfBodyUndergoingTorque Name of body that is being accelerated.
nameOfBodyExertingTorque Name of body that is exerting the gravitational torque.
Returns
Pointer to object for calculating gravitational torque.
Definition at line 107 of file createTorqueModel.cpp.
References tudat::simulation_setup::Body::getBodyInertiaTensor(), tudat::simulation_setup::Body::getCurrentRotationToLocalFrame(), tudat::gravitation::GravityFieldModel::getGravitationalParameter(), and tudat::simulation_setup::Body::getPosition().
Referenced by createTorqueModel().
createTorqueModel()
std::shared_ptr< basic_astrodynamics::TorqueModel > tudat::simulation_setup::createTorqueModel (const std::shared_ptr< simulation_setup::Body > bodyUndergoingTorque, const std::shared_ptr< simulation_setup::Body > bodyExertingTorque, const std::shared_ptr< TorqueSettings > torqueSettings, const std::string & nameOfBodyUndergoingTorque, const std::string & nameOfBodyExertingTorque)
Function to create torque model object. Type of requested model is checked and corresponding factory function is called.
Parameters
bodyUndergoingTorque Pointer to object of body that is being accelerated.
bodyExertingTorque Pointer to object of body that is exerting torque,
torqueSettings Settings for torque model that is to be created.
nameOfBodyUndergoingTorque Name of object of body that is being accelerated.
nameOfBodyExertingTorque Name of object of body that is exerting the torque.
Returns
Torque model pointer.
Definition at line 146 of file createTorqueModel.cpp.
References tudat::basic_astrodynamics::aerodynamic_torque, createAerodynamicTorqueModel(), createSecondDegreeGravitationalTorqueModel(), and tudat::basic_astrodynamics::second_order_gravitational_torque.
Referenced by createTorqueModelsMap().
createTorqueModelsMap()
basic_astrodynamics::TorqueModelMap tudat::simulation_setup::createTorqueModelsMap (const NamedBodyMap & bodyMap, const SelectedTorqueMap & selectedTorquePerBody)
Function to create torque models from a map of bodies and torque model settings. The return type can be used to identify both the body undergoing and exerting torque.
Parameters
bodyMap List of pointers to bodies required for the creation of the torque model objects.
selectedTorquePerBody List identifying which bodies exert which type of torque(s) on which bodies.
Definition at line 180 of file createTorqueModel.cpp.
References createTorqueModel().
Referenced by tudat::propagators::RotationalStatePropagatorSettings< StateScalarType >::resetIntegratedStateModels().
getPropulsionInputVariables()
std::vector< std::function< double() > > tudat::simulation_setup::getPropulsionInputVariables (const std::shared_ptr< Body > bodyWithGuidance, const std::vector< propulsion::ThrustIndependentVariables > independentVariables, const std::vector< std::function< double() > > guidanceInputFunctions = std::vector< std::function< double() > >())
Function to create a list of functions that (compute and) return independent variables for thrust and/or specific impulse. This parameterization is used in the thrust mangitude type is thrust_magnitude_from_dependent_variables. This function retrieves all input functions from the environment and a list of user-defined functions.
Parameters
bodyWithGuidance Name of body for which the propulsion settings are to be retrieved.
independentVariables List of variables for which function returning them are to be created. Note that the number of guidance_input_dependent_thrust entries must be equal to the size of guidanceInputFunctions. No entries of type throttle_dependent_thrust are allowed.
guidanceInputFunctions Functions returning user-defined variables on which the thrust/specific impulse depends
Returns
List of functions that (compute and) return independent variables for thrust
Definition at line 22 of file thrustSettings.cpp.
References tudat::propulsion::altitude_dependent_thrust, tudat::propulsion::density_dependent_thrust, tudat::propulsion::dynamic_pressure_dependent_thrust, tudat::aerodynamics::FlightConditions::getCurrentAltitude(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentDensity(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentDynamicPressure(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentMachNumber(), tudat::aerodynamics::AtmosphericFlightConditions::getCurrentPressure(), tudat::propulsion::guidance_input_dependent_thrust, tudat::propulsion::mach_number_dependent_thrust, tudat::propulsion::pressure_dependent_thrust, and tudat::propulsion::throttle_dependent_thrust.
Referenced by tudat::simulation_setup::AccelerationLimitedThrottleGuidance::AccelerationLimitedThrottleGuidance(), and createThrustMagnitudeWrapper().
multiplyMaximumThrustByScalingFactor()
double tudat::simulation_setup::multiplyMaximumThrustByScalingFactor (const std::function< double(const std::vector< double > &) > maximumThrustFunction, const std::function< double() > maximumThrustMultiplier, const std::vector< double > & maximumThrustIndependentVariables)
Interface function to multiply a maximum thrust by a multiplier to obtain the actual thrust
Parameters
maximumThrustFunction Function returning the maxumum thrust as a function of a number of independent variables
maximumThrustMultiplier Function returning a value by which the output of maximumThrustFunction is to be multiplied to obtain the actual thrust.
maximumThrustIndependentVariables List of variables to be passed as input to maximumThrustFunction
Returns
Definition at line 106 of file thrustSettings.cpp.
Referenced by tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::parseInputDataAndCheckConsistency().
readCoefficientInterpolatorFromFile()
std::shared_ptr< interpolators::Interpolator< double, double > > tudat::simulation_setup::readCoefficientInterpolatorFromFile (const std::string coefficientFile)
Function to read a thrust or specific impulse interpolator from a file.
Parameters
coefficientFile Filename containing data to be used as input for interpolator.
Returns
Interpolator set according to data in coefficientFile
Definition at line 213 of file thrustSettings.cpp.
References tudat::input_output::getNumberOfIndependentVariablesInCoefficientFile(), and tudat::input_output::MultiArrayFileReader< NumberOfDimensions >::readMultiArrayAndIndependentVariables().
Referenced by createAccelerationLimitedParameterizedThrustMagnitudeSettings(), and createParameterizedThrustMagnitudeSettings().
createParameterizedThrustMagnitudeSettings() [1/4]
std::shared_ptr< ParameterizedThrustMagnitudeSettings > tudat::simulation_setup::createParameterizedThrustMagnitudeSettings (const std::shared_ptr< ThrustInputParameterGuidance > thrustInputParameterGuidance, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::shared_ptr< interpolators::Interpolator< double, double > > specificImpulseInterpolator, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables)
Function to create thrust magnitude settings from guidance input and tables
Parameters
thrustInputParameterGuidance Object that computes all guidance-input parameters as a function of time/state Note that the number of implemented parameters must be consistent with the numbet of associated entries in thrustIndependentVariables and specificImpulseDependentVariables
thrustMagnitudeInterpolator Interpolator returning the current thrust (or maximum thrust if thrustIndependentVariables contains an throttle_dependent_thrust entry) as a function of the independent variables.
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of thrustMagnitudeInterpolator.
specificImpulseInterpolator Interpolator returning the current specific impulse as a function of the independent variables.
specificImpulseDependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of specificImpulseInterpolator.
Returns
Thrust magnitude settings for given input.
Definition at line 251 of file thrustSettings.cpp.
References tudat::simulation_setup::ThrustInputParameterGuidance::getSpecificImpulseInputGuidanceParameter(), tudat::simulation_setup::ThrustInputParameterGuidance::getThrustInputGuidanceParameter(), and tudat::simulation_setup::ThrustInputParameterGuidance::update().
Referenced by createAccelerationLimitedParameterizedThrustMagnitudeSettings(), and createParameterizedThrustMagnitudeSettings().
createParameterizedThrustMagnitudeSettings() [2/4]
std::shared_ptr< ParameterizedThrustMagnitudeSettings > tudat::simulation_setup::createParameterizedThrustMagnitudeSettings (const std::shared_ptr< ThrustInputParameterGuidance > thrustInputParameterGuidance, const std::string thrustMagnitudeDataFile, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::string specificImpulseDataFile, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables)
Function to create thrust magnitude settings from guidance input and tables
Parameters
thrustInputParameterGuidance Object that computes all guidance-input parameters as a function of time/state Note that the number of implemented parameters must be consistent with the numbet of associated entries in thrustIndependentVariables and specificImpulseDependentVariables
thrustMagnitudeDataFile File containing data for the thrust (or maximum thrust if thrustIndependentVariables contains an throttle_dependent_thrust entry) and associated independent variables
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of thrustMagnitudeInterpolator.
specificImpulseDataFile File containing data for the specific impulse and associated independent variables.
specificImpulseDependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of specificImpulseInterpolator.
Returns
Thrust magnitude settings for given input.
Definition at line 288 of file thrustSettings.cpp.
References createParameterizedThrustMagnitudeSettings(), and readCoefficientInterpolatorFromFile().
createParameterizedThrustMagnitudeSettings() [3/4]
std::shared_ptr< ParameterizedThrustMagnitudeSettings > tudat::simulation_setup::createParameterizedThrustMagnitudeSettings (const std::shared_ptr< ThrustInputParameterGuidance > thrustInputParameterGuidance, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double constantSpecificImpulse)
Function to create thrust magnitude settings from guidance input and tables, with constant specific impulse
Parameters
thrustInputParameterGuidance Object that computes all guidance-input parameters as a function of time/state Note that the number of implemented parameters must be consistent with the numbet of associated entries in thrustIndependentVariables and specificImpulseDependentVariables
thrustMagnitudeInterpolator Interpolator returning the current thrust (or maximum thrust if thrustIndependentVariables contains an throttle_dependent_thrust entry) as a function of the independent variables.
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of thrustMagnitudeInterpolator.
constantSpecificImpulse Specific impulse that is to be used at all times.
Returns
Thrust magnitude settings for given input.
Definition at line 303 of file thrustSettings.cpp.
References tudat::simulation_setup::ThrustInputParameterGuidance::getThrustInputGuidanceParameter(), and tudat::simulation_setup::ThrustInputParameterGuidance::update().
createParameterizedThrustMagnitudeSettings() [4/4]
std::shared_ptr< ParameterizedThrustMagnitudeSettings > tudat::simulation_setup::createParameterizedThrustMagnitudeSettings (const std::shared_ptr< ThrustInputParameterGuidance > thrustInputParameterGuidance, const std::string thrustMagnitudeDataFile, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double constantSpecificImpulse)
Function to create thrust magnitude settings from guidance input and tables
Parameters
thrustInputParameterGuidance Object that computes all guidance-input parameters as a function of time/state Note that the number of implemented parameters must be consistent with the numbet of associated entries in thrustIndependentVariables and specificImpulseDependentVariables
thrustMagnitudeDataFile File containing data for the thrust (or maximum thrust if thrustIndependentVariables contains an throttle_dependent_thrust entry) and associated independent variables
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of thrustMagnitudeInterpolator.
constantSpecificImpulse Specific impulse that is to be used at all times.
Returns
Thrust magnitude settings for given input.
Definition at line 328 of file thrustSettings.cpp.
References createParameterizedThrustMagnitudeSettings(), and readCoefficientInterpolatorFromFile().
createAccelerationLimitedParameterizedThrustMagnitudeSettings() [1/4]
std::shared_ptr< ParameterizedThrustMagnitudeSettings > tudat::simulation_setup::createAccelerationLimitedParameterizedThrustMagnitudeSettings (const NamedBodyMap & bodyMap, const std::string nameOfBodyWithGuidance, const double maximumAcceleration, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double specificImpulse, const std::string nameOfCentralBody)
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration (constant specific impulse).
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration (constant specific impulse).
Parameters
bodyMap List of pointers to body objects defining the full simulation environment.
nameOfBodyWithGuidance Name of body for which thrust guidance is to be created.
maximumAcceleration Maxmum allowable acceleration due to the thrust force.
thrustMagnitudeInterpolator Interpolator that computes the maximum thrust as a function of the independent variables.
thrustIndependentVariables Physical meaning of each of the independent variables used as input to the thrustInterpolator.
specificImpulse Specific impulse of the propulsion system
nameOfCentralBody Name of body w.r.t. which thrust guidance is computed (e.g. Earth if the altitude from Earth is used as an independent variable of the thrust).
Returns
Thrust magnitude settings according to input.
Definition at line 343 of file thrustSettings.cpp.
References createParameterizedThrustMagnitudeSettings().
Referenced by createAccelerationLimitedParameterizedThrustMagnitudeSettings().
createAccelerationLimitedParameterizedThrustMagnitudeSettings() [2/4]
std::shared_ptr< ParameterizedThrustMagnitudeSettings > tudat::simulation_setup::createAccelerationLimitedParameterizedThrustMagnitudeSettings (const NamedBodyMap & bodyMap, const std::string nameOfBodyWithGuidance, const double maximumAcceleration, const std::string thrustMagnitudeDataFile, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double specificImpulse, const std::string nameOfCentralBody)
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration (constant specific impulse).
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration (constant specific impulse).
Parameters
bodyMap List of pointers to body objects defining the full simulation environment.
nameOfBodyWithGuidance Name of body for which thrust guidance is to be created.
maximumAcceleration Maxmum allowable acceleration due to the thrust force.
thrustMagnitudeDataFile File containing table with maximum thrust values.
thrustIndependentVariables Physical meaning of each of the independent variables used as input to the thrustInterpolator.
specificImpulse Specific impulse of the propulsion system
nameOfCentralBody Name of body w.r.t. which thrust guidance is computed (e.g. Earth if the altitude from Earth is used as an independent variable of the thrust).
Returns
Thrust magnitude settings according to input.
Definition at line 363 of file thrustSettings.cpp.
References createAccelerationLimitedParameterizedThrustMagnitudeSettings(), and readCoefficientInterpolatorFromFile().
createAccelerationLimitedParameterizedThrustMagnitudeSettings() [3/4]
std::shared_ptr< ParameterizedThrustMagnitudeSettings > tudat::simulation_setup::createAccelerationLimitedParameterizedThrustMagnitudeSettings (const NamedBodyMap & bodyMap, const std::string nameOfBodyWithGuidance, const double maximumAcceleration, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::shared_ptr< interpolators::Interpolator< double, double > > specificImpulseInterpolator, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables, const std::string nameOfCentralBody)
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration.
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration.
Parameters
bodyMap List of pointers to body objects defining the full simulation environment.
nameOfBodyWithGuidance Name of body for which thrust guidance is to be created.
maximumAcceleration Maxmum allowable acceleration due to the thrust force.
thrustMagnitudeInterpolator Interpolator returning the current thrust (or maximum thrust if thrustIndependentVariables contains an throttle_dependent_thrust entry) as a function of the independent variables.
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of thrustMagnitudeInterpolator.
specificImpulseInterpolator Interpolator returning the current specific impulse as a function of the independent variables.
specificImpulseDependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of specificImpulseInterpolator.
nameOfCentralBody Name of body w.r.t. which thrust guidance is computed (e.g. Earth if the altitude from Earth is used as an independent variable of the thrust).
Returns
Thrust magnitude settings according to input.
Definition at line 380 of file thrustSettings.cpp.
References createParameterizedThrustMagnitudeSettings().
createAccelerationLimitedParameterizedThrustMagnitudeSettings() [4/4]
std::shared_ptr< ParameterizedThrustMagnitudeSettings > tudat::simulation_setup::createAccelerationLimitedParameterizedThrustMagnitudeSettings (const NamedBodyMap & bodyMap, const std::string nameOfBodyWithGuidance, const double maximumAcceleration, const std::string thrustMagnitudeDataFile, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::string specificImpulseDataFile, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables, const std::string nameOfCentralBody)
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration.
Function to create a thrust magnitude settings based on interpolated maximum thrust, with throttle determined by maximum allowed axial acceleration.
Parameters
bodyMap List of pointers to body objects defining the full simulation environment.
nameOfBodyWithGuidance Name of body for which thrust guidance is to be created.
maximumAcceleration Maxmum allowable acceleration due to the thrust force.
thrustMagnitudeDataFile File containing data for the thrust (or maximum thrust if thrustIndependentVariables contains an throttle_dependent_thrust entry) and associated independent variables
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of thrustMagnitudeInterpolator.
specificImpulseDataFile File containing data for the specific impulse and associated independent variables.
specificImpulseDependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of specificImpulseInterpolator.
nameOfCentralBody Name of body w.r.t. which thrust guidance is computed (e.g. Earth if the altitude from Earth is used as an independent variable of the thrust).
Returns
Thrust magnitude settings according to input.
Definition at line 402 of file thrustSettings.cpp.
References createAccelerationLimitedParameterizedThrustMagnitudeSettings(), and readCoefficientInterpolatorFromFile().
Variable Documentation
aerodynamicCoefficientTypes
std::map< AerodynamicCoefficientTypes, std::string > tudat::simulation_setup::aerodynamicCoefficientTypes static
Initial value:
=
{
    { constant_aerodynamic_coefficients, "constant" },
    { hypersonic_local_inclincation_coefficients, "hypersonicLocalInclincation" },
    { tabulated_coefficients, "tabulated" }
}
Definition at line 61 of file aerodynamics.h.
Referenced by from_json(), and to_json().
unsupportedAerodynamicCoefficientTypes
std::vector< AerodynamicCoefficientTypes > tudat::simulation_setup::unsupportedAerodynamicCoefficientTypes static
Initial value:
=
{
    hypersonic_local_inclincation_coefficients
}
Definition at line 69 of file aerodynamics.h.
Referenced by from_json(), and to_json().
atmosphereTypes
std::map< AtmosphereTypes, std::string > tudat::simulation_setup::atmosphereTypes static
Initial value:
=
{
    { exponential_atmosphere, "exponential" },
    { tabulated_atmosphere, "tabulated" },
    { nrlmsise00, "nrlmsise00" }
}
Definition at line 88 of file atmosphere.h.
Referenced by from_json(), and to_json().
unsupportedAtmosphereTypes
std::vector< AtmosphereTypes > tudat::simulation_setup::unsupportedAtmosphereTypes = { custom_constant_temperature_atmosphere } static
Definition at line 96 of file atmosphere.h.
Referenced by from_json(), and to_json().
ephemerisTypes
std::map< EphemerisType, std::string > tudat::simulation_setup::ephemerisTypes static
Initial value:
=
{
    { approximate_planet_positions, "approximatePlanetPositions" },
    { direct_spice_ephemeris, "directSpice" },
    { tabulated_ephemeris, "tabulated" },
    { interpolated_spice, "interpolatedSpice" },
    { constant_ephemeris, "constant" },
    { kepler_ephemeris, "kepler" },
    { custom_ephemeris, "custom" }
}
Definition at line 63 of file ephemeris.h.
Referenced by from_json(), and to_json().
unsupportedEphemerisTypes
std::vector< EphemerisType > tudat::simulation_setup::unsupportedEphemerisTypes static
Initial value:
=
{
    custom_ephemeris
}
Definition at line 75 of file ephemeris.h.
Referenced by from_json(), and to_json().
gravityFieldTypes
std::map< GravityFieldType, std::string > tudat::simulation_setup::gravityFieldTypes static
Initial value:
=
{
    { central, "pointMass" },
    { central_spice, "pointMassSpice" },
    { spherical_harmonic, "sphericalHarmonic" }
}
Definition at line 27 of file gravityField.h.
Referenced by from_json(), and to_json().
unsupportedGravityFieldTypes
std::vector< GravityFieldType > tudat::simulation_setup::unsupportedGravityFieldTypes = { } static
Definition at line 35 of file gravityField.h.
Referenced by from_json(), and to_json().
sphericalHarmonicsModels
std::map< SphericalHarmonicsModel, std::string > tudat::simulation_setup::sphericalHarmonicsModels static
Initial value:
=
{
    { customModel, "custom" },
    { egm96, "egm96" },
    { ggm02c, "ggm02c" },
    { ggm02s, "ggm02s" },
    { glgm3150, "glgm3150" },
    { lpe200, "lpe200" },
    { jgmro120d, "jgmro120d" }
}
Definition at line 53 of file gravityField.h.
Referenced by from_json(), and to_json().
unsupportedSphericalHarmonicsModels
std::vector< SphericalHarmonicsModel > tudat::simulation_setup::unsupportedSphericalHarmonicsModels = { } static
Definition at line 65 of file gravityField.h.
radiationPressureTypes
std::map< RadiationPressureType, std::string > tudat::simulation_setup::radiationPressureTypes static
Initial value:
=
{
    { cannon_ball, "cannonBall" }
}
Definition at line 25 of file radiationPressure.h.
Referenced by from_json(), and to_json().
unsupportedRadiationPressureTypes
std::vector< RadiationPressureType > tudat::simulation_setup::unsupportedRadiationPressureTypes = { } static
Definition at line 31 of file radiationPressure.h.
Referenced by from_json(), and to_json().
rotationModelTypes
std::map< RotationModelType, std::string > tudat::simulation_setup::rotationModelTypes static
Initial value:
=
{
    { simple_rotation_model, "simple" },
    { spice_rotation_model, "spice" },
    { gcrs_to_itrs_rotation_model, "gcrsToItrs" }
}
Definition at line 26 of file rotationModel.h.
Referenced by from_json(), and to_json().
unsupportedRotationModelTypes
std::vector< RotationModelType > tudat::simulation_setup::unsupportedRotationModelTypes = { } static
Definition at line 34 of file rotationModel.h.
Referenced by from_json(), and to_json().
bodyShapeTypes
std::map< BodyShapeTypes, std::string > tudat::simulation_setup::bodyShapeTypes static
Initial value:
=
{
    { spherical, "spherical" },
    { spherical_spice, "sphericalSpice" },
    { oblate_spheroid, "oblateSpheroid" }
}
Definition at line 25 of file shapeModel.h.
Referenced by from_json(), and to_json().
unsupportedBodyShapeTypes
std::vector< BodyShapeTypes > tudat::simulation_setup::unsupportedBodyShapeTypes = { } static
Definition at line 33 of file shapeModel.h.
Referenced by from_json(), and to_json().
thrustDirectionTypes
std::map< ThrustDirectionGuidanceTypes, std::string > tudat::simulation_setup::thrustDirectionTypes static
Initial value:
=
{
    { colinear_with_state_segment_thrust_direction, "colinearWithStateSegment" },
    { thrust_direction_from_existing_body_orientation, "fromExistingBodyOrientation" },
    { custom_thrust_direction, "customDirection" },
    { custom_thrust_orientation, "customOrientation" }
}
Definition at line 28 of file thrust.h.
Referenced by from_json(), and to_json().
unsupportedThrustDirectionTypes
std::vector< ThrustDirectionGuidanceTypes > tudat::simulation_setup::unsupportedThrustDirectionTypes static
Initial value:
=
{
    custom_thrust_direction,
    custom_thrust_orientation
}
Definition at line 37 of file thrust.h.
Referenced by from_json(), and to_json().
thrustMagnitudeTypes
std::map< ThrustMagnitudeTypes, std::string > tudat::simulation_setup::thrustMagnitudeTypes static
Initial value:
=
{
    { constant_thrust_magnitude, "constant" },
    { from_engine_properties_thrust_magnitude, "fromEngineProperties" },
    { thrust_magnitude_from_time_function, "timeDependent" },
    { thrust_magnitude_from_dependent_variables, "variableDependent" }
}
Definition at line 68 of file thrust.h.
Referenced by from_json(), and to_json().
unsupportedThrustMagnitudeTypes
std::vector< ThrustMagnitudeTypes > tudat::simulation_setup::unsupportedThrustMagnitudeTypes static
Initial value:
=
{
    thrust_magnitude_from_time_function,
    thrust_magnitude_from_dependent_variables
}
Definition at line 77 of file thrust.h.
Referenced by from_json(), and to_json().
thrustFrameTypes
std::map< ThrustFrames, std::string > tudat::simulation_setup::thrustFrameTypes static
Initial value:
=
{
    { unspecified_thurst_frame, "unspecified" },
    { inertial_thurst_frame, "intertial" },
    { lvlh_thrust_frame, "lvlh" }
}
Definition at line 108 of file thrust.h.
Referenced by from_json(), and to_json().
unsupportedThrustFrameTypes
std::vector< ThrustFrames > tudat::simulation_setup::unsupportedThrustFrameTypes static
Initial value:
=
{
    unspecified_thurst_frame
}
Definition at line 116 of file thrust.h.
defaultRadiatedPowerValues
const std::map< std::string, double > tudat::simulation_setup::defaultRadiatedPowerValues static
Initial value:
=
{ { "Sun",  3.839E26 } }
Definition at line 28 of file createRadiationPressureInterface.h.
Referenced by createRadiationPressureInterface().