Tudat: tudat::gravitation::GravityFieldModel Class Reference
tudat::gravitation::GravityFieldModel Class Reference
GravityFieldModel class.
#include <gravityFieldModel.h>
Public Member Functions
GravityFieldModel (const double gravitationalParameter)
Default constructor.
virtual ~GravityFieldModel ()
Default destructor.
virtual Eigen::Vector3d getGradientOfPotential (const Eigen::Vector3d &bodyFixedPosition)
Get the gradient of the potential.
double getGravitationalParameter ()
Get the gravitational parameter.
double getGravitationalPotential (const Eigen::Vector3d &bodyFixedPosition)
Get the gravitational potential at given body-fixed position.
void resetGravitationalParameter (const double gravitationalParameter)
Set the gravitational parameter.
Protected Attributes
double gravitationalParameter_
Gravitational parameter.
Detailed Description
Gravity field model class included in Tudat.
Definition at line 30 of file gravityFieldModel.h.
Constructor & Destructor Documentation
tudat::gravitation::GravityFieldModel::GravityFieldModel (const double gravitationalParameter) inline
Default constructor.
Parameters
gravitationalParameter Gravitational parameter associated with gravity field
Definition at line 39 of file gravityFieldModel.h.
virtual tudat::gravitation::GravityFieldModel::~GravityFieldModel () inline virtual
Default destructor.
Definition at line 47 of file gravityFieldModel.h.
Member Function Documentation
void tudat::gravitation::GravityFieldModel::resetGravitationalParameter (const double gravitationalParameter) inline
Define the gravitational parameter in meter^3 per second^2.
Parameters
gravitationalParameter New gravitational parameter associated with gravity field.
Definition at line 54 of file gravityFieldModel.h.
References gravitationalParameter_.
double tudat::gravitation::GravityFieldModel::getGravitationalParameter () inline
Return the gravitational parameter in meter^3 per second^2.
Returns
Gravitational parameter.
Definition at line 64 of file gravityFieldModel.h.
References gravitationalParameter_.
Referenced by tudat::simulation_setup::createCentralGravityAcceleratioModel(), tudat::simulation_setup::createEmpiricalAcceleration(), tudat::simulation_setup::createGravityFieldVariationsModel(), tudat::observation_models::createLightTimeCorrections(), tudat::simulation_setup::createMutualSphericalHarmonicsGravityAcceleration(), tudat::observation_models::createOneWayDopplerProperTimeCalculator(), tudat::simulation_setup::createRelativisticCorrectionAcceleration(), tudat::simulation_setup::createSecondDegreeGravitationalTorqueModel(), tudat::simulation_setup::createSphericalHarmonicsGravityAcceleration(), and tudat::propagators::getDoubleDependentVariableFunction().
double tudat::gravitation::GravityFieldModel::getGravitationalPotential (const Eigen::Vector3d & bodyFixedPosition) inline
Return the gravitational potential at given body-fixed position.
Parameters
bodyFixedPosition Position at which the gravitational potential is to be evaluated.
Returns
Gravitational potential.
Definition at line 76 of file gravityFieldModel.h.
References gravitationalParameter_.
virtual Eigen::Vector3d tudat::gravitation::GravityFieldModel::getGradientOfPotential (const Eigen::Vector3d & bodyFixedPosition) inline virtual
Returns the gradient of the potential for the gravity field selected.
Parameters
bodyFixedPosition Position at which gradient of potential is to be determined.
Returns
Gradient of potential.
Reimplemented in tudat::gravitation::SphericalHarmonicsGravityField.
Definition at line 87 of file gravityFieldModel.h.
References tudat::gravitation::computeGravitationalAcceleration(), and gravitationalParameter_.
Member Data Documentation
double tudat::gravitation::GravityFieldModel::gravitationalParameter_ protected
The gravitational parameter in meter^3 per second^2.
Definition at line 98 of file gravityFieldModel.h.
Referenced by getGradientOfPotential(), tudat::gravitation::SphericalHarmonicsGravityField::getGradientOfPotential(), getGravitationalParameter(), getGravitationalPotential(), tudat::gravitation::SphericalHarmonicsGravityField::getGravitationalPotential(), and resetGravitationalParameter().
The documentation for this class was generated from the following file:
Astrodynamics/Gravitation/gravityFieldModel.h