Tudat: tudat::estimatable_parameters::ConstantObservationBiasParameter Class Reference
tudat::estimatable_parameters::ConstantObservationBiasParameter Class Reference
Interface class for the estimation of a constant absolute observation bias.
#include <observationBiasParameter.h>
Public Member Functions
ConstantObservationBiasParameter (const boost::function< Eigen::VectorXd() > getCurrentBias, const boost::function< void(const Eigen::VectorXd &) > resetCurrentBias, const observation_models::LinkEnds linkEnds, const observation_models::ObservableType observableType)
Constructor.
~ConstantObservationBiasParameter ()
Destructor.
observation_models::LinkEnds getLinkEnds ()
Function to retrieve the observation link ends for which the bias is active.
observation_models::ObservableType getObservableType ()
Function to retrieve the observable type for which the bias is active.
std::string getParameterDescription ()
int getParameterSize ()
Function to retrieve the size of the parameter (equal to the size of the observable).
Eigen::VectorXd getParameterValue ()
Function to get the current value of the constant absolute observation bias that is to be estimated.
void setObservationBiasFunctions (const boost::function< Eigen::VectorXd() > getCurrentBias, const boost::function< void(const Eigen::VectorXd &) > resetCurrentBias)
Function to reset the get/set function of the observation bias.
void setParameterValue (Eigen::VectorXd parameterValue)
Function to reset the value of the constant absolute observation bias that is to be estimated.
Public Member Functions inherited from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >
EstimatableParameter (const EstimatebleParametersEnum parameterName, const std::string &associatedBody, const std::string &pointOnBodyId="")
Constructor.
virtual ~EstimatableParameter ()
Virtual destructor.
EstimatebleParameterIdentifier getParameterName ()
Function to retrieve the type and associated body of the parameter.
virtual std::string getSecondaryIdentifier ()
Function to return additional identifier for parameter.
Private Attributes
boost::function< Eigen::VectorXd() > getCurrentBias_
Function to retrieve the current observation bias.
observation_models::LinkEnds linkEnds_
Observation link ends for which the bias is active.
observation_models::ObservableType observableType_
Observable type for which the bias is active.
boost::function< void(const Eigen::VectorXd &) > resetCurrentBias_
Function to reset the current observation bia.
Additional Inherited Members
Protected Attributes inherited from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >
EstimatebleParameterIdentifier parameterName_
Identifier of parameter.
Detailed Description
Interface class for the estimation of a constant absolute observation bias (at given link ends and observable type). Unlike most other EstimatableParameter derived classes, this class does not have direct access to the class (ConstantObservationBias) used in the simulations for the observation bias. This is due to the fact that the ConstantObservationBias class is templated by the observable size, whil this class is not.
Definition at line 33 of file observationBiasParameter.h.
Constructor & Destructor Documentation
tudat::estimatable_parameters::ConstantObservationBiasParameter::ConstantObservationBiasParameter (const boost::function< Eigen::VectorXd() > getCurrentBias, const boost::function< void(const Eigen::VectorXd &) > resetCurrentBias, const observation_models::LinkEnds linkEnds, const observation_models::ObservableType observableType) inline
Constructor
Parameters
getCurrentBias Function to retrieve the current observation bias.
resetCurrentBias Function to reset the current observation bias
linkEnds Observation link ends for which the bias is active.
observableType Observable type for which the bias is active.
Definition at line 46 of file observationBiasParameter.h.
tudat::estimatable_parameters::ConstantObservationBiasParameter::~ConstantObservationBiasParameter () inline
Definition at line 56 of file observationBiasParameter.h.
Member Function Documentation
Eigen::VectorXd tudat::estimatable_parameters::ConstantObservationBiasParameter::getParameterValue () inline virtual
Function to get the current value of the constant absolute observation bias that is to be estimated.
Returns
Current value of the constant absolute observation bias that is to be estimated.
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 63 of file observationBiasParameter.h.
References getCurrentBias_.
void tudat::estimatable_parameters::ConstantObservationBiasParameter::setParameterValue (Eigen::VectorXd parameterValue) inline virtual
Function to reset the value of the constant absolute observation bias that is to be estimated.
Parameters
parameterValue New value of the constant absolute observation bias that is to be estimated.
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 73 of file observationBiasParameter.h.
References resetCurrentBias_.
int tudat::estimatable_parameters::ConstantObservationBiasParameter::getParameterSize () inline virtual
Function to retrieve the size of the parameter (equal to the size of the observable).
Returns
Size of parameter value (equal to the size of the observable).
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 83 of file observationBiasParameter.h.
References tudat::observation_models::getObservableSize(), and observableType_.
void tudat::estimatable_parameters::ConstantObservationBiasParameter::setObservationBiasFunctions (const boost::function< Eigen::VectorXd() > getCurrentBias, const boost::function< void(const Eigen::VectorXd &) > resetCurrentBias) inline
Function to reset the get/set function of the observation bias. This function is needed since te observation models/biases are typically created after the estimated parameter objects
Parameters
getCurrentBias New function to retrieve the current observation bias.
resetCurrentBias New function to reset the current observation bias
Definition at line 95 of file observationBiasParameter.h.
References getCurrentBias_, and resetCurrentBias_.
observation_models::LinkEnds tudat::estimatable_parameters::ConstantObservationBiasParameter::getLinkEnds () inline
Function to retrieve the observation link ends for which the bias is active.
Returns
Observation link ends for which the bias is active.
Definition at line 114 of file observationBiasParameter.h.
References linkEnds_.
observation_models::ObservableType tudat::estimatable_parameters::ConstantObservationBiasParameter::getObservableType () inline
Function to retrieve the observable type ends for which the bias is active.
Returns
Observable type for which the bias is active.
Definition at line 124 of file observationBiasParameter.h.
References observableType_.
std::string tudat::estimatable_parameters::ConstantObservationBiasParameter::getParameterDescription () inline virtual
Reimplemented from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 129 of file observationBiasParameter.h.
References tudat::observation_models::getLinkEndsString(), tudat::observation_models::getObservableName(), tudat::estimatable_parameters::getParameterTypeString(), linkEnds_, observableType_, and tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >::parameterName_.
Member Data Documentation
boost::function< Eigen::VectorXd() > tudat::estimatable_parameters::ConstantObservationBiasParameter::getCurrentBias_ private
Definition at line 142 of file observationBiasParameter.h.
Referenced by getParameterValue(), tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::getParameterValue(), setObservationBiasFunctions(), and tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::setObservationBiasFunctions().
boost::function< void(const Eigen::VectorXd&) > tudat::estimatable_parameters::ConstantObservationBiasParameter::resetCurrentBias_ private
Definition at line 145 of file observationBiasParameter.h.
Referenced by setObservationBiasFunctions(), tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::setObservationBiasFunctions(), setParameterValue(), and tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::setParameterValue().
observation_models::LinkEnds tudat::estimatable_parameters::ConstantObservationBiasParameter::linkEnds_ private
Definition at line 148 of file observationBiasParameter.h.
Referenced by getLinkEnds(), tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::getLinkEnds(), getParameterDescription(), and tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::getParameterDescription().
observation_models::ObservableType tudat::estimatable_parameters::ConstantObservationBiasParameter::observableType_ private
Definition at line 151 of file observationBiasParameter.h.
Referenced by getObservableType(), tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::getObservableType(), getParameterDescription(), tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::getParameterDescription(), getParameterSize(), and tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter::getParameterSize().
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/EstimatableParameters/observationBiasParameter.h