Tudat: tudat::mission_segments::ImprovedInversePolynomialWall Class Reference
tudat::mission_segments::ImprovedInversePolynomialWall Class Reference
This class contains an improved inverse polynomial function, and its exact first and second derivative w.r.t.
#include <improvedInversePolynomialWall.h>
Public Member Functions
ImprovedInversePolynomialWall (const boost::function< double() > aTimeDependentParameter, const boost::function< std::pair< Eigen::Vector3d, Eigen::Vector3d >() > aSetOfBoundaryParameters)
Default constructor with immediate definition of parameters.
~ImprovedInversePolynomialWall ()
Default destructor.
double computeDefiniteIntegral (const unsigned int order, const double lowerBound, const double upperBound)
Compute the definite integral of the function.
double computeDerivative (const unsigned int order, const double anAzimuthalAngle)
Compute the derivative of the function.
double evaluate (const double anAzimuthalAngle)
Evaluate the function value for a given (in-plane) azimuthal angle.
Public Member Functions inherited from tudat::basic_mathematics::Function< >
virtual ~Function ()
Default destructor.
double operator() (const double inputValue)
Alias for evaluate(double).
Private Attributes
boost::function< std::pair< Eigen::Vector3d, Eigen::Vector3d >) > boundaryParameters_
The parameters of the function, related to the boundary conditions.
boost::function< double() > timeDependentParameter_
The time-dependent parameter.
Detailed Description
Improved inverse polynomial function approximating the radial position of a thrusting spacecraft.
the azimuthal angle . It is a mathematical function, and can be used to approximate the radial position of a thrusting spacecraft. The function is documented by Wall et al. [2010] as the "improved inverse polynomial method". The radial position of the spacecraft is parameterized in terms of an independent variable, the (in-plane) azimuthal angle . The first and second derivative are taken with respect to this independent variable.
The function is completely described by the independent variable and a set of seven parameters. These parameters are related to the boundary conditions of the problem: three initial conditions, three final conditions and the total time-of-flight. One of the parameters is used to solve for the time-of-flight and is therefore a time-dependent parameter. These seven parameters are passed to this class as boost::functions to facilitate the flexible external manipulation of their values.
Definition at line 65 of file improvedInversePolynomialWall.h.
Constructor & Destructor Documentation
tudat::mission_segments::ImprovedInversePolynomialWall::ImprovedInversePolynomialWall (const boost::function< double() > aTimeDependentParameter, const boost::function< std::pair< Eigen::Vector3d, Eigen::Vector3d >() > aSetOfBoundaryParameters) inline
Default constructor with immediate definition of parameters through boost::functions. This setup allows for a flexible external manipulation of the values of the parameters.
Parameters
aTimeDependentParameter The parameter that is used to solve for the time-of-flight. This parameter is equivalent to parameter d from Wall et al. [2010].
aSetOfBoundaryParameters A set of six parameters, related to the position boundary conditions. These parameters are equivalent to the parameters a, b, c, e, f, and g from Wall et al. [2010]. The order is important! aSetOfBoundaryParameters.first(0) = a aSetOfBoundaryParameters.first(1) = b aSetOfBoundaryParameters.first(2) = c aSetOfBoundaryParameters.second(0) = e aSetOfBoundaryParameters.second(1) = f aSetOfBoundaryParameters.second(2) = g
Definition at line 87 of file improvedInversePolynomialWall.h.
tudat::mission_segments::ImprovedInversePolynomialWall::~ImprovedInversePolynomialWall () inline
Default destructor.
Definition at line 97 of file improvedInversePolynomialWall.h.
References computeDefiniteIntegral(), computeDerivative(), and evaluate().
Member Function Documentation
double tudat::mission_segments::ImprovedInversePolynomialWall::evaluate (const double anAzimuthalAngle) virtual
Evaluates the inverse polynomial function for a given (in-plane) azimuthal angle .
The (improved version of the) inverse polynomial function is given by Wall et al. [2010] as:
in which is the radial position of the spacecraft, is the (in-plane) azimuthal angle and are parameters that define the shape of the trajectory. The parameter is the time-dependent parameter which is used to solve for a required time-of-flight.
Parameters
anAzimuthalAngle Value of the (in-plane) azimuthal angle [rad].
Returns
The radial position at [m].
Implements tudat::basic_mathematics::Function< >.
Definition at line 42 of file improvedInversePolynomialWall.cpp.
References boundaryParameters_, and timeDependentParameter_.
Referenced by computeDerivative(), and ~ImprovedInversePolynomialWall().
double tudat::mission_segments::ImprovedInversePolynomialWall::computeDerivative (const unsigned int order, const double anAzimuthalAngle) virtual
Computes the derivative of a given order of the function, for a given (in-plane) azimuthal angle . It only evaluates the first, second or third derivative, therefore the order should be 1, 2 or 3.
The first derivative of the function is:
The second derivative of the function is:
When substituting for the first derivative, the equation becomes:
The third derivative of the function is:
When substituting for the first and second derivative, the equation becomes:
In these formulas is the radial position of the spacecraft, is the (in-plane) azimuthal angle, the prime indicates the derivative with respect to , and are parameters that define the shape of the trajectory. The parameter is the time-dependent parameter which is used to solve for a required time-of-flight.
Parameters
order Order of the derivative to evaluate. Can be either 1, 2 or 3.
anAzimuthalAngle Value of the (in-plane) azimuthal angle [rad].
Returns
Value of the derivative of order 1, 2 or 3 of the function [-, rad^-1, rad^-2].
Implements tudat::basic_mathematics::Function< >.
Definition at line 62 of file improvedInversePolynomialWall.cpp.
References boundaryParameters_, evaluate(), and timeDependentParameter_.
Referenced by ~ImprovedInversePolynomialWall().
double tudat::mission_segments::ImprovedInversePolynomialWall::computeDefiniteIntegral (const unsigned int order, const double lowerBound, const double upperBound) virtual
This function throws a runtime error when it is called. The integral of the inverse polynomial function is not part of the shape-based method and has not been implemented.
Parameters
order Order of the integral to evaluate.
lowerBound Integration lower bound (integrate from this point).
upperBound Integration upper bound (integrate to this point).
Returns
Value of the integral.
Exceptions
std::runtime_error when this function is used.
Implements tudat::basic_mathematics::Function< >.
Definition at line 161 of file improvedInversePolynomialWall.cpp.
References TUDAT_UNUSED_PARAMETER.
Referenced by ~ImprovedInversePolynomialWall().
Member Data Documentation
boost::function< double() > tudat::mission_segments::ImprovedInversePolynomialWall::timeDependentParameter_ private
The time-dependent parameter, which is used to satisfy a required time-of-flight.
Definition at line 212 of file improvedInversePolynomialWall.h.
Referenced by computeDerivative(), and evaluate().
boost::function< std::pair< Eigen::Vector3d , Eigen::Vector3d >) > tudat::mission_segments::ImprovedInversePolynomialWall::boundaryParameters_ private
The six time-independent parameters of the function. These parameters determine the shape of the trajectory and are dependent on the initial and final boundary conditions.
The first three parameters are dependent on the initial boundary conditions and the last three parameters are dependent on the final boundary conditions plus the time-dependent parameter 'aTimeDependentParameter'. The parameters correspond to Wall et al. [2010] in the following manner: the first three parameters are a, b and c; the last three parameters are e, f, and g.
The order is important! boundaryParameters_.first(0) = a boundaryParameters_.first(1) = b boundaryParameters_.first(2) = c boundaryParameters_.second(0) = e boundaryParameters_.second(1) = f boundaryParameters_.second(2) = g
Definition at line 233 of file improvedInversePolynomialWall.h.
Referenced by computeDerivative(), and evaluate().
The documentation for this class was generated from the following files:
Astrodynamics/MissionSegments/improvedInversePolynomialWall.h
Astrodynamics/MissionSegments/improvedInversePolynomialWall.cpp