Tudat: tudat::propulsion Namespace Reference
tudat::propulsion Namespace Reference
Classes
class BodyFixedForceDirectionGuidance
Base class for computing the direction of a given force/acceleration.
class CustomThrustMagnitudeWrapper
Class for custom computations of thrust magnitude and mass rate.
class DirectionBasedForceGuidance
Class for computing the force direction directly from a function returning the associated unit vector of direction.
class FromThrustMassRateModel
This class provides the mass rate from a (set of) thrust model(s), used in numerically propagating a body's total mass.
class OrientationBasedForceGuidance
Class for computing the force direction using the rotation matrix from the propagation to the body-fixed frame.
class ParameterizedThrustMagnitudeWrapper
Class to compute the engine thrust and specific impulse as a parameterized function of any number of indepedent variables.
class ThrustAcceleration
Class used for computing an acceleration due to a continuous thrust.
class ThrustMagnitudeFromEngineWrapper
Class to compute the engine thrust and mass rate from EngineModel object(s).
class ThrustMagnitudeWrapper
Base class for determining the current thrust magnitude from method defined in derived class.
Enumerations
enum ThrustIndependentVariables {
mach_number_dependent_thrust, altitude_dependent_thrust, density_dependent_thrust, dynamic_pressure_dependent_thrust,
pressure_dependent_thrust, guidance_input_dependent_thrust, throttle_dependent_thrust
}
Variables on which parameterized thrust can depend.
Functions
double computePropellantMassRateFromSpecificImpulse (const double thrustMagnitude, const double specificImpulse)
Function to compute propellant mass rate from engine thrust and specific impulse.
double computeThrustFromSpecificImpulse (const double propellantMassRate, const double specificImpulse)
Function to compute engine thrust from propellant mass rate and specific impulse.
Eigen::Vector3d getForceDirectionColinearWithPosition (const boost::function< void(Eigen::Vector6d &) > currentStateFunction, const double currentTime, const bool putForceInOppositeDirection)
Function to get the unit vector colinear with position segment of a translational state.
Eigen::Vector3d getForceDirectionColinearWithVelocity (const boost::function< void(Eigen::Vector6d &) > currentStateFunction, const double currentTime, const bool putForceInOppositeDirection)
Function to get the unit vector colinear with velocity segment of a translational state.
Eigen::Vector3d getForceDirectionFromTimeOnlyFunction (const double currentTime, const boost::function< Eigen::Vector3d(const double) > timeOnlyFunction)
Function to get the force direction from a time-only function.
void mergeUpdateFunctions (const boost::function< void(const double) > updateFunction1, const boost::function< void(const double) > updateFunction2, const double time)
Function used as interface to merge two update functions.
Enumeration Type Documentation
enum tudat::propulsion::ThrustIndependentVariables
Enumerator
mach_number_dependent_thrust
altitude_dependent_thrust
density_dependent_thrust
dynamic_pressure_dependent_thrust
pressure_dependent_thrust
guidance_input_dependent_thrust
throttle_dependent_thrust
Definition at line 308 of file thrustMagnitudeWrapper.h.
Function Documentation
void tudat::propulsion::mergeUpdateFunctions (const boost::function< void(const double) > updateFunction1, const boost::function< void(const double) > updateFunction2, const double time) inline
Function used as interface to merge two update functions. Calling this function will update the two update functions (in order)
Parameters
updateFunction1 First update function.
updateFunction2 Second update function.
time Time to which both functions are to be updated
Definition at line 38 of file thrustAccelerationModel.h.
Referenced by tudat::propulsion::ThrustAcceleration::setThrustUpdateFunction().
double tudat::propulsion::computeThrustFromSpecificImpulse (const double propellantMassRate, const double specificImpulse)
Function to compute engine thrust from propellant mass rate and specific impulse
Parameters
propellantMassRate Propellant mass rate
specificImpulse Specific impulse (normalized with g0 from physical_constants namespace)
Returns
Total engine thrust
Definition at line 22 of file thrustFunctions.cpp.
References tudat::physical_constants::SEA_LEVEL_GRAVITATIONAL_ACCELERATION.
Referenced by tudat::system_models::DirectEngineModel::updateEngineModel().
double tudat::propulsion::computePropellantMassRateFromSpecificImpulse (const double thrustMagnitude, const double specificImpulse)
Function to compute propellant mass rate from engine thrust and specific impulse
Parameters
thrustMagnitude Total engine thrust
specificImpulse Specific impulse (normalized with g0 from physical_constants namespace)
Returns
Propellant mass rate
Definition at line 29 of file thrustFunctions.cpp.
References tudat::physical_constants::SEA_LEVEL_GRAVITATIONAL_ACCELERATION.
Referenced by tudat::propulsion::CustomThrustMagnitudeWrapper::getCurrentMassRate(), and tudat::propulsion::ParameterizedThrustMagnitudeWrapper::getCurrentMassRate().
Eigen::Vector3d tudat::propulsion::getForceDirectionColinearWithVelocity (const boost::function< void(Eigen::Vector6d &) > currentStateFunction, const double currentTime, const bool putForceInOppositeDirection)
Function to get the unit vector colinear with velocity segment of a translational state.
Parameters
currentStateFunction Function returning (by reference) translational Cartesian state from which the unit velocity vector is to be retrieved.
currentTime Time at which computation is to be done (not used here; included for interface compatibility).
putForceInOppositeDirection Boolean denoting whether the output vector should be in opposite (if true) or same direction (if false) as velocity segment of currentState
Returns
Unit vector colinear with velocity segment of currentState.
Definition at line 20 of file thrustGuidance.cpp.
Referenced by tudat::simulation_setup::createThrustGuidanceModel().
Eigen::Vector3d tudat::propulsion::getForceDirectionColinearWithPosition (const boost::function< void(Eigen::Vector6d &) > currentStateFunction, const double currentTime, const bool putForceInOppositeDirection)
Function to get the unit vector colinear with position segment of a translational state.
Parameters
currentStateFunction Function returning (by reference) translational Cartesian state from which the unit position vector is to be retrieved.
currentTime Time at which computation is to be done (not used here; included for interface compatibility).
putForceInOppositeDirection Boolean denoting whether the output vector should be in opposite (if true) or same direction (if false) as position segment of current state
Returns
Unit vector colinear with position segment of current state.
Definition at line 30 of file thrustGuidance.cpp.
Referenced by tudat::simulation_setup::createThrustGuidanceModel().
Eigen::Vector3d tudat::propulsion::getForceDirectionFromTimeOnlyFunction (const double currentTime, const boost::function< Eigen::Vector3d(const double) > timeOnlyFunction)
Function to get the force direction from a time-only function.
Parameters
currentTime Current time.
timeOnlyFunction Function returning unit vector (thrust direction) as a funtion of time.
Returns
Thrust direction.
Definition at line 40 of file thrustGuidance.cpp.