Tudat: tudat::ground_stations::GroundStationState Class Reference
tudat::ground_stations::GroundStationState Class Reference
Class storing and computing the (time-variable) state of a ground station in a body-fixed frame.
#include <groundStationState.h>
Public Member Functions
GroundStationState (const Eigen::Vector3d stationPosition, const coordinate_conversions::PositionElementTypes inputElementType=coordinate_conversions::cartesian_position, const std::shared_ptr< basic_astrodynamics::BodyShapeModel > bodySurface=std::shared_ptr< basic_astrodynamics::BodyShapeModel >())
Constructor.
virtual ~GroundStationState ()
std::shared_ptr< basic_astrodynamics::BodyShapeModel > getBodySurface ()
Function to retrieve the shape of body on which state is defined.
Eigen::Vector3d getCartesianPositionInTime (const double secondsSinceEpoch, const double inputReferenceEpoch=basic_astrodynamics::JULIAN_DAY_ON_J2000)
Function to obtain the Cartesian position of the ground station in the local frame at a given time.
Eigen::Vector6d getCartesianStateInTime (const double secondsSinceEpoch, const double inputReferenceEpoch=basic_astrodynamics::JULIAN_DAY_ON_J2000)
Function to obtain the Cartesian state of the ground station in the local frame at a given time.
double getLatitude ()
Function to return the geocentric latitude of the station.
double getLongitude ()
Function to return the geocentric longtude of the station.
Eigen::Vector3d getNominalCartesianPosition ()
Function to return the nominal (unperturbed) Cartesian position of the station.
Eigen::Vector3d getNominalGeodeticPosition ()
Function to return the nominal (unperturbed) geodetic position of the station.
Eigen::Vector3d getNominalSphericalPosition ()
Function to return the nominal (unperturbed) spherical position of the station.
Eigen::Quaterniond getRotationFromBodyFixedToTopocentricFrame (const double time)
Function to return current rotation from body-fixed to topocentric frame.
void resetGroundStationPositionAtEpoch (const Eigen::Vector3d stationPosition, const coordinate_conversions::PositionElementTypes inputElementType=coordinate_conversions::cartesian_position)
Function to (re)set the nominal state of the station.
Protected Member Functions
void setTransformationAndUnitVectors ()
Function to reset the rotation from the body-fixed to local topocentric frame, and associated unit vectors.
Protected Attributes
Eigen::Quaterniond bodyFixedToTopocentricFrameRotation_
Rotation from body-fixed to topocentrix frame.
std::shared_ptr< basic_astrodynamics::BodyShapeModel > bodySurface_
Shape of body on which state is defined.
Eigen::Vector3d cartesianPosition_
Cartesian position of station.
std::vector< Eigen::Vector3d > geocentricUnitVectors_
Set of unit vectors of topocentric frame.
Eigen::Vector3d geodeticPosition
Geodetic position of station.
Eigen::Vector3d sphericalPosition_
Spherical position of station.
Detailed Description
Definition at line 48 of file groundStationState.h.
Constructor & Destructor Documentation
GroundStationState()
tudat::ground_stations::GroundStationState::GroundStationState (const Eigen::Vector3d stationPosition, const coordinate_conversions::PositionElementTypes inputElementType = coordinate_conversions::cartesian_position, const std::shared_ptr< basic_astrodynamics::BodyShapeModel > bodySurface = std::shared_ptr< basic_astrodynamics::BodyShapeModel >())
Constructor
Parameters
stationPosition Position of ground station in body-fixed frame
inputElementType Element type (e.g. Cartesian, spherical, etc.) of groundStationPosition.
bodySurface Shape of body on which state is defined. If nullptr (default), no conversions to/from geodetic position are possible.
Definition at line 48 of file groundStationState.cpp.
References resetGroundStationPositionAtEpoch().
~GroundStationState()
virtual tudat::ground_stations::GroundStationState::~GroundStationState () inline virtual
Definition at line 66 of file groundStationState.h.
Member Function Documentation
getCartesianStateInTime()
Eigen::Vector6d tudat::ground_stations::GroundStationState::getCartesianStateInTime (const double secondsSinceEpoch, const double inputReferenceEpoch = basic_astrodynamics::JULIAN_DAY_ON_J2000)
Function to obtain the Cartesian state of the ground station in the local frame (body-fixed, not topocentric) at a given time. Adds all position variations to the nominal state (at the requested time) and returns the state. NOTE: poisition variations are as yet not included.
Parameters
secondsSinceEpoch Seconds since reference epoch at which the position is to be retrieved.
inputReferenceEpoch Reference epoch julian day
Returns
Cartesian state of station in local frame at requested time.
Definition at line 58 of file groundStationState.cpp.
References cartesianPosition_.
Referenced by getCartesianPositionInTime().
getCartesianPositionInTime()
Eigen::Vector3d tudat::ground_stations::GroundStationState::getCartesianPositionInTime (const double secondsSinceEpoch, const double inputReferenceEpoch = basic_astrodynamics::JULIAN_DAY_ON_J2000) inline
Function to obtain the Cartesian position of the ground station in the local frame (body-fixed, not topocentric) at a given time. Adds all position variations to the nominal state (at the requested time) and returns the state. NOTE: poisition variations are as yet not included.
Parameters
secondsSinceEpoch Seconds since reference epoch at which the position is to be retrieved.
inputReferenceEpoch Reference epoch julian day
Returns
Cartesian position of station in local frame at requested time.
Definition at line 90 of file groundStationState.h.
References getCartesianStateInTime().
Referenced by tudat::observation_partials::createCartesianStatePartialsWrtParameter().
getNominalCartesianPosition()
Eigen::Vector3d tudat::ground_stations::GroundStationState::getNominalCartesianPosition () inline
Function to return the nominal Cartesian (unperturbed, i.e. not including linear drift, eccentricity, tidal variations, etc.) position of the station in body-fixed system.
Returns
Unperturbed Cartesian position of the station
Definition at line 103 of file groundStationState.h.
References cartesianPosition_.
getNominalSphericalPosition()
Eigen::Vector3d tudat::ground_stations::GroundStationState::getNominalSphericalPosition () inline
Function to return the nominal spherical (unperturbed, i.e. not including linear drift, eccentricity, tidal variations, etc.) position of the station in body-fixed system.
Returns
Unperturbed spherical position of the station
Definition at line 114 of file groundStationState.h.
References sphericalPosition_.
getNominalGeodeticPosition()
Eigen::Vector3d tudat::ground_stations::GroundStationState::getNominalGeodeticPosition () inline
Function to return the nominal geodetic (unperturbed, i.e. not including linear drift, eccentricity, tidal variations, etc.) position of the station in body-fixed system. NOTE: This vector is only defined in bodySurface_ was non-nullptr at last setting of nominal state (call to resetGroundStationPositionAtEpoch).
Returns
Unperturbed geodetic position of the station
Definition at line 127 of file groundStationState.h.
References geodeticPosition.
getLatitude()
double tudat::ground_stations::GroundStationState::getLatitude () inline
Function to return the geocentric latitude of the station.
Returns
Geocentric latitude of the station.
Definition at line 141 of file groundStationState.h.
References sphericalPosition_.
Referenced by setTransformationAndUnitVectors().
getLongitude()
double tudat::ground_stations::GroundStationState::getLongitude () inline
Function to return the geocentric longtude of the station.
Returns
Geocentric longtude of the station.
Definition at line 151 of file groundStationState.h.
References sphericalPosition_.
Referenced by setTransformationAndUnitVectors().
getRotationFromBodyFixedToTopocentricFrame()
Eigen::Quaterniond tudat::ground_stations::GroundStationState::getRotationFromBodyFixedToTopocentricFrame (const double time) inline
Function to return current rotation from body-fixed to topocentric frame, with topocentric xyz-axes in ENU (Earth-North-Up) order. Note that no relativistic rescaling of vectors is performed, only a rotation is applied.
Parameters
time Time at which rotation quaternion is to be evaluated.
Returns
Current rotation from body-fixed to topocentrix frame
Definition at line 163 of file groundStationState.h.
References bodyFixedToTopocentricFrameRotation_.
Referenced by tudat::simulation_setup::createGroundStation().
resetGroundStationPositionAtEpoch()
void tudat::ground_stations::GroundStationState::resetGroundStationPositionAtEpoch (const Eigen::Vector3d stationPosition, const coordinate_conversions::PositionElementTypes inputElementType = coordinate_conversions::cartesian_position)
Function to (re)set the nominal state of the station. Input may be in any type of elements defined in PositionElementTypes enum.
Parameters
stationPosition Position of ground station in body-fixed frame
inputElementType Element type (e.g. Cartesian, spherical, etc.) of groundStationPosition.
Definition at line 66 of file groundStationState.cpp.
References bodySurface_, tudat::coordinate_conversions::cartesian_position, cartesianPosition_, tudat::coordinate_conversions::convertPositionElements(), tudat::coordinate_conversions::geodetic_position, geodeticPosition, tudat::mathematical_constants::PI, setTransformationAndUnitVectors(), tudat::coordinate_conversions::spherical_position, sphericalPosition_, and TUDAT_NAN.
Referenced by GroundStationState().
getBodySurface()
std::shared_ptr< basic_astrodynamics::BodyShapeModel > tudat::ground_stations::GroundStationState::getBodySurface () inline
Function to retrieve the shape of body on which state is defined \ return Shape of body on which state is defined
Definition at line 184 of file groundStationState.h.
References bodySurface_.
setTransformationAndUnitVectors()
void tudat::ground_stations::GroundStationState::setTransformationAndUnitVectors () protected
Definition at line 95 of file groundStationState.cpp.
References bodyFixedToTopocentricFrameRotation_, bodySurface_, cartesianPosition_, geocentricUnitVectors_, tudat::ground_stations::getGeocentricLocalUnitVectors(), getLatitude(), getLongitude(), and tudat::ground_stations::getRotationQuaternionFromBodyFixedToTopocentricFrame().
Referenced by resetGroundStationPositionAtEpoch().
Member Data Documentation
cartesianPosition_
Eigen::Vector3d tudat::ground_stations::GroundStationState::cartesianPosition_ protected
Cartesian position of station, without variations (linear drift, eccentricity, tides, etc.), in the body-fixed frame.
Definition at line 199 of file groundStationState.h.
Referenced by getCartesianStateInTime(), getNominalCartesianPosition(), resetGroundStationPositionAtEpoch(), and setTransformationAndUnitVectors().
sphericalPosition_
Eigen::Vector3d tudat::ground_stations::GroundStationState::sphericalPosition_ protected
Spherical position of station, without variations (linear drift, eccentricity, tides, etc.), in the body-fixed frame. The order of the entries is: radius, geocentric latitude, longitude.
Definition at line 206 of file groundStationState.h.
Referenced by getLatitude(), getLongitude(), getNominalSphericalPosition(), and resetGroundStationPositionAtEpoch().
geodeticPosition
Eigen::Vector3d tudat::ground_stations::GroundStationState::geodeticPosition protected
Geodetic position of station, without variations (linear drift, eccentricity, tides, etc.), in the body-fixed frame. The order of the entries is: altitude, geodetic latitude, longitude. This vector is only defined in bodySurface_ was non-nullptr at last setting of nominal state (call to resetGroundStationPositionAtEpoch).
Definition at line 214 of file groundStationState.h.
Referenced by getNominalGeodeticPosition(), and resetGroundStationPositionAtEpoch().
geocentricUnitVectors_
std::vector< Eigen::Vector3d > tudat::ground_stations::GroundStationState::geocentricUnitVectors_ protected
Set of unit vectors of topocentric frame, expressed in body-fixed frame, in ENU (Earth-North-Up) order. The up-vector is generated by drawing a line from the center of the body to the (nominal) position of the station. For a sphere, this coincides with the true topocentric frame, for which the East-North vectors span a local tangent plane. The transformation from body-fixed to 'true' topocentric frame is described by the bodyFixedToTopocentricFrameRotation_ variable.
Definition at line 224 of file groundStationState.h.
Referenced by setTransformationAndUnitVectors().
bodyFixedToTopocentricFrameRotation_
Eigen::Quaterniond tudat::ground_stations::GroundStationState::bodyFixedToTopocentricFrameRotation_ protected
Rotation from body-fixed to topocentrix frame, with topocentric xyz-axes in ENU (Earth-North-Up) order. In this frame the East-North vectors span a local tangent plane. The frame is time-independent and is based on the cartesianPosition_ member, without variations.
Definition at line 232 of file groundStationState.h.
Referenced by getRotationFromBodyFixedToTopocentricFrame(), and setTransformationAndUnitVectors().
bodySurface_
std::shared_ptr< basic_astrodynamics::BodyShapeModel > tudat::ground_stations::GroundStationState::bodySurface_ protected
Definition at line 235 of file groundStationState.h.
Referenced by getBodySurface(), resetGroundStationPositionAtEpoch(), and setTransformationAndUnitVectors().
The documentation for this class was generated from the following files:
Astrodynamics/GroundStations/groundStationState.h
Astrodynamics/GroundStations/groundStationState.cpp