Tudat: tudat::ephemerides::KeplerStateExtractor Class Reference
tudat::ephemerides::KeplerStateExtractor Class Reference
Keplerian State extractor class.
#include <keplerStateExtractor.h>
Public Member Functions
boost::shared_ptr< Eigen::Vector6d > extract (ParsedDataLineMapPtr dataLineMap)
Extract the Keplerian Elements.
Public Member Functions inherited from tudat::input_output::Extractor< Eigen::Vector6d >
virtual ~Extractor ()
Default destructor.
virtual boost::shared_ptr< Eigen::Vector6d > extract (parsed_data_vector_utilities::ParsedDataLineMapPtr data)=0
Extract function.
Additional Inherited Members
Protected Types inherited from tudat::input_output::Extractor< Eigen::Vector6d >
typedef parsed_data_vector_utilities::FieldValuePtr FieldValuePtr
typedef parsed_data_vector_utilities::ParsedDataLineMapPtr ParsedDataLineMapPtr
Shortcut to parsed data line map shared-pointer.
typedef parsed_data_vector_utilities::ParsedDataVectorPtr ParsedDataVectorPtr
Shortcut to parsed data vector shared-pointer.
Protected Member Functions inherited from tudat::input_output::Extractor< Eigen::Vector6d >
bool checkOptionalFieldType (ParsedDataLineMapPtr dataLineMap, int numberOfFields,...)
Check if the given data map contains all the passed FieldTypes. Returns false on fail.
void checkRequiredFieldType (ParsedDataLineMapPtr dataLineMap, int numberOfFields,...)
Check if the given data map contains all the passed FieldTypes. Throws an exception on fail.
Detailed Description
This class contains the functionality of extracting the Keplerian elements from a parsed data line map.
Definition at line 33 of file keplerStateExtractor.h.
Member Function Documentation
boost::shared_ptr< Eigen::Vector6d > tudat::ephemerides::KeplerStateExtractor::extract (ParsedDataLineMapPtr dataLineMap)
Returns a KeplerianElements object containing the orbital parameters found in the input data line map. If one of the elements is not present, the function throws an exception. If no true anomaly field type is found, the function searches for the mean anomaly field type and performs the necessary conversions. The if-statements can be easily extended to deal with other non-standard field types.
Parameters
dataLineMap Data map corresponding to a parsed line.
Returns
A KeplerianElements object containing the orbital parameters found in the data map.
Definition at line 37 of file keplerStateExtractor.cpp.
References tudat::input_output::field_types::state::argumentOfPeriapsis, tudat::orbital_element_conversions::argumentOfPeriapsisIndex, tudat::input_output::Extractor< Eigen::Vector6d >::checkOptionalFieldType(), tudat::orbital_element_conversions::convertEccentricAnomalyToTrueAnomaly(), tudat::orbital_element_conversions::convertMeanAnomalyToEccentricAnomaly(), tudat::input_output::field_types::state::eccentricity, tudat::orbital_element_conversions::eccentricityIndex, tudat::input_output::field_types::state::inclination, tudat::orbital_element_conversions::inclinationIndex, tudat::json_interface::keplerianElements, tudat::input_output::field_types::state::longitudeOfAscendingNode, tudat::orbital_element_conversions::longitudeOfAscendingNodeIndex, tudat::input_output::field_types::state::meanAnomaly, tudat::input_output::field_types::state::semiMajorAxis, tudat::orbital_element_conversions::semiMajorAxisIndex, tudat::input_output::field_types::state::trueAnomaly, and tudat::orbital_element_conversions::trueAnomalyIndex.
The documentation for this class was generated from the following files:
Astrodynamics/Ephemerides/keplerStateExtractor.h
Astrodynamics/Ephemerides/keplerStateExtractor.cpp