Tudat: tudat::input_output::stream_filters::RemoveComment Class Reference
tudat::input_output::stream_filters::RemoveComment Class Reference
Filter that removes comments from a stream.
#include <streamFilters.h>
Public Member Functions
RemoveComment (char skipCharacter= '#', bool isOmitIfEmpty=true)
Create a comment filter for a given start comment character.
std::string do_filter (const std::string &line)
Remove comments in a single line.
Private Attributes
bool isOmitIfEmpty_
Omit state for filtered line.
char skipCharacter_
Skip character.
Detailed Description
This class allows for a data stream to be filtered to remove comments starting with a given character, e.g., "#". When this character is the first of a line, the entire line is considered comment, and is removed. When the comment appears in the middle of a line, only the text after this line is removed. NOTE: The start of a comment is always a single character! NOTE: You cannot escape the comment character! NOTE: A comment always runs until the end of the same line!
Definition at line 39 of file streamFilters.h.
Constructor & Destructor Documentation
tudat::input_output::stream_filters::RemoveComment::RemoveComment (char skipCharacter = '#', bool isOmitIfEmpty = true) inline
Creates a comment filter for a given start comment character. Note that the variable "line_filter" is set to true, to indicate to Boost not to append newline characters.
Parameters
skipCharacter Character that initiates a comment.
isOmitIfEmpty True if a line should be removed when a complete line is filtered away. (When the 'skipCharacter' is the first character on the line)
Definition at line 52 of file streamFilters.h.
References do_filter().
Member Function Documentation
std::string tudat::input_output::stream_filters::RemoveComment::do_filter (const std::string & line)
Executes filter to remove comments from input line of data. For more information see boost::iostreams::line_filter (overrides definition of line_filter to enable chaining of filters).
Parameters
line Unfiltered line.
Returns
Filtered line.
Definition at line 26 of file streamFilters.cpp.
References isOmitIfEmpty_, and skipCharacter_.
Referenced by RemoveComment(), tudat::input_output::stream_filters::ReplaceElements::ReplaceElements(), and tudat::input_output::stream_filters::SkipFirstLines::SkipFirstLines().
Member Data Documentation
char tudat::input_output::stream_filters::RemoveComment::skipCharacter_ private
Character that initiates a comment.
Definition at line 74 of file streamFilters.h.
Referenced by do_filter().
bool tudat::input_output::stream_filters::RemoveComment::isOmitIfEmpty_ private
If filtered line is empty, and omit flag is set to true, no newline empty line is returned.
Definition at line 80 of file streamFilters.h.
Referenced by do_filter(), and tudat::input_output::stream_filters::SkipFirstLines::do_filter().
The documentation for this class was generated from the following files:
InputOutput/streamFilters.h
InputOutput/streamFilters.cpp