Tudat: tudat::json_interface::ValueAccessError Class Reference
tudat::json_interface::ValueAccessError Class Reference
Class for errors generated during the retrieval of a value from a json object.
#include <errorHandling.h>
Public Member Functions
ValueAccessError (const std::string &errorMessage, const KeyPath &keyPath)
Constructor.
void rethrowIfNotTriggeredByMissingValueAt (const KeyPath &keyPath) const
Rethrow this if this was not generated when trying to access keyPath.
bool wasTriggeredByMissingValueAt (const KeyPath &keyPath) const
Whether this was generated when trying to access keyPath.
virtual const char * what () const throw ()
Full error message.
Public Attributes
KeyPath keyPath
Key path trying to access / accessed when the error was generated.
Detailed Description
Class for errors generated during the retrieval of a value from a json object.
Definition at line 43 of file errorHandling.h.
Constructor & Destructor Documentation
ValueAccessError()
tudat::json_interface::ValueAccessError::ValueAccessError (const std::string & errorMessage, const KeyPath & keyPath) inline
Constructor.
Parameters
errorMessage The first part of the message to be printed.
keyPath Key path trying to access / accessed when the error was generated.
Definition at line 52 of file errorHandling.h.
Member Function Documentation
what()
virtual const char* tudat::json_interface::ValueAccessError::what () const throw () inline virtual
Reimplemented in tudat::json_interface::IllegalValueError.
Definition at line 59 of file errorHandling.h.
References keyPath.
Referenced by tudat::json_interface::IllegalValueError::what().
wasTriggeredByMissingValueAt()
bool tudat::json_interface::ValueAccessError::wasTriggeredByMissingValueAt (const KeyPath & keyPath) const inline
Whether this was generated when trying to access keyPath.
Parameters
keyPath The key path to which the instance's key path is to be compared.
Returns
Whether this was generated when trying to access keyPath.
Definition at line 73 of file errorHandling.h.
References keyPath.
Referenced by rethrowIfNotTriggeredByMissingValueAt().
rethrowIfNotTriggeredByMissingValueAt()
void tudat::json_interface::ValueAccessError::rethrowIfNotTriggeredByMissingValueAt (const KeyPath & keyPath) const inline
Rethrow this if this was not generated when trying to access keyPath.
Parameters
keyPath The key path to which the instance's key path is to be compared.
Definition at line 83 of file errorHandling.h.
References keyPath, and wasTriggeredByMissingValueAt().
Referenced by tudat::json_interface::getValue().
Member Data Documentation
keyPath
KeyPath tudat::json_interface::ValueAccessError::keyPath
Definition at line 56 of file errorHandling.h.
Referenced by tudat::json_interface::UndefinedKeyError::handleUseOfDefaultValue(), rethrowIfNotTriggeredByMissingValueAt(), wasTriggeredByMissingValueAt(), and what().
The documentation for this class was generated from the following file:
JsonInterface/Support/errorHandling.h