Tudat: tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients Class Reference
tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients Class Reference
Interface class for estimation of spherical harmonic gravity field sine coefficients.
#include <sphericalHarmonicSineCoefficients.h>
Public Member Functions
SphericalHarmonicsSineCoefficients (const boost::function< Eigen::MatrixXd() > getSineCoefficients, const boost::function< void(Eigen::MatrixXd) > setSineCoefficients, const std::vector< std::pair< int, int > > &blockIndices, const std::string &associatedBody)
Constructor.
~SphericalHarmonicsSineCoefficients ()
Destructor.
std::vector< std::pair< int, int > > getBlockIndices ()
Function to retrieve the list of sine coefficient indices which are to be estimated.
std::string getParameterDescription ()
int getParameterSize ()
Function to retrieve the size of the parameter.
Eigen::VectorXd getParameterValue ()
Function to retrieve the current values of the sine coefficients that are to be estimated.
void setParameterValue (const Eigen::VectorXd parameterValue)
Function to reset the sine coefficients that are to be estimated.
Public Member Functions inherited from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >
EstimatableParameter (const EstimatebleParametersEnum parameterName, const std::string &associatedBody, const std::string &pointOnBodyId="")
Constructor.
virtual ~EstimatableParameter ()
Virtual destructor.
EstimatebleParameterIdentifier getParameterName ()
Function to retrieve the type and associated body of the parameter.
virtual std::string getSecondaryIdentifier ()
Function to return additional identifier for parameter.
Private Attributes
std::vector< std::pair< int, int > > blockIndices_
List of sine coefficient indices which are to be estimated.
boost::function< Eigen::MatrixXd() > getSineCoefficients_
Function to retrieve the full set of sine coefficients, of which a subset is to be estimated.
int parameterSize_
Number of coefficients that are to be estimated (i.e. length of blockIndices_ vector).
boost::function< void(Eigen::MatrixXd) > setSineCoefficients_
Function to reset the full set of sine coefficients, of which a subset is to be estimated.
Additional Inherited Members
Protected Attributes inherited from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >
EstimatebleParameterIdentifier parameterName_
Identifier of parameter.
Detailed Description
Interface class for estimation of spherical harmonic gravity field sine coefficients. Interfaces the estimation with the member coefficients of an instance of the SphericalHarmonicsGravityField (or nominal coefficients of TimeDependentSphericalHarmonicsGravityField).
Definition at line 32 of file sphericalHarmonicSineCoefficients.h.
Constructor & Destructor Documentation
tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::SphericalHarmonicsSineCoefficients (const boost::function< Eigen::MatrixXd() > getSineCoefficients, const boost::function< void(Eigen::MatrixXd) > setSineCoefficients, const std::vector< std::pair< int, int > > & blockIndices, const std::string & associatedBody) inline
Constructor
Parameters
getSineCoefficients Function to retrieve the full set of sine coefficients, of which a subset is to be estimated.
setSineCoefficients Function to reset the full set of sine coefficients, of which a subset is to be estimated.
blockIndices List of sine coefficient indices which are to be estimated (first and second are degree and order for each vector entry).
associatedBody Name of body for which sine coefficients are to be estimated.
Definition at line 48 of file sphericalHarmonicSineCoefficients.h.
References blockIndices_, and parameterSize_.
tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::~SphericalHarmonicsSineCoefficients () inline
Definition at line 61 of file sphericalHarmonicSineCoefficients.h.
References getParameterValue(), tudat::input_output::field_types::general::parameterValue, and setParameterValue().
Member Function Documentation
Eigen::VectorXd tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::getParameterValue () virtual
Function to retrieve the current values of the sine coefficients that are to be estimated. The order of the entries in this vector is the same as in the blockIndices_ member vector.
Returns
List of values for sine coefficients that are to be estimated.
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 21 of file sphericalHarmonicSineCoefficients.cpp.
References blockIndices_, getSineCoefficients_, and parameterSize_.
Referenced by ~SphericalHarmonicsSineCoefficients().
void tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::setParameterValue (const Eigen::VectorXd parameterValue) virtual
Function to reset the sine coefficients that are to be estimated. The order of the entries in this vector is the same as in the blockIndices_ member vector.
Parameters
parameterValue List of new values for sine coefficients that are to be estimated.
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 36 of file sphericalHarmonicSineCoefficients.cpp.
References blockIndices_, getSineCoefficients_, tudat::input_output::field_types::general::parameterValue, and setSineCoefficients_.
Referenced by ~SphericalHarmonicsSineCoefficients().
int tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::getParameterSize () inline virtual
Function to retrieve the size of the parameter, equal to the length of the blcokIndices_ member vector, i.e. the number of coefficients that are to be estimated.
Returns
Size of parameter value.
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 85 of file sphericalHarmonicSineCoefficients.h.
References parameterSize_.
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction().
std::vector< std::pair< int, int > > tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::getBlockIndices () inline
Function to retrieve the list of sine coefficient indices which are to be estimated (first and second are degree and order for each vector entry).
Returns
List of sine coefficient indices which are to be estimated.
Definition at line 93 of file sphericalHarmonicSineCoefficients.h.
References blockIndices_.
std::string tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::getParameterDescription () inline virtual
Reimplemented from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 98 of file sphericalHarmonicSineCoefficients.h.
References blockIndices_, tudat::estimatable_parameters::getParameterTypeString(), and tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >::parameterName_.
Member Data Documentation
boost::function< Eigen::MatrixXd() > tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::getSineCoefficients_ private
Definition at line 117 of file sphericalHarmonicSineCoefficients.h.
Referenced by getParameterValue(), and setParameterValue().
boost::function< void(Eigen::MatrixXd) > tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::setSineCoefficients_ private
Definition at line 120 of file sphericalHarmonicSineCoefficients.h.
Referenced by setParameterValue().
std::vector< std::pair< int, int > > tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::blockIndices_ private
List of sine coefficient indices which are to be estimated (first and second are degree and order for each vector entry).
Definition at line 127 of file sphericalHarmonicSineCoefficients.h.
Referenced by getBlockIndices(), getParameterDescription(), getParameterValue(), setParameterValue(), and SphericalHarmonicsSineCoefficients().
int tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::parameterSize_ private
Definition at line 130 of file sphericalHarmonicSineCoefficients.h.
Referenced by getParameterSize(), getParameterValue(), and SphericalHarmonicsSineCoefficients().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/EstimatableParameters/sphericalHarmonicSineCoefficients.h
Astrodynamics/OrbitDetermination/EstimatableParameters/sphericalHarmonicSineCoefficients.cpp