Tudat: tudat::mission_segments::PericenterFindingFunctions Class Reference
tudat::mission_segments::PericenterFindingFunctions Class Reference
Pericenter finding functions class.
#include <gravityAssist.h>
Public Member Functions
PericenterFindingFunctions (const double absoluteIncomingSemiMajorAxis, const double absoluteOutgoingSemiMajorAxis, const double bendingAngle)
Constructor with immediate definition of parameters.
double computeFirstDerivativePericenterRadiusFunction (const double pericenterRadius)
Compute first-derivative of the pericenter radius function.
double computePericenterRadiusFunction (const double pericenterRadius)
Compute pericenter radius function.
Private Attributes
const double absoluteIncomingSemiMajorAxis_
The absolute semi-major axis of the incoming hyperbolic leg.
const double absoluteOutgoingSemiMajorAxis_
The absolute semi-major axis of the outgoing hyperbolic leg.
const double bendingAngle_
Bending angle between the excess velocities.
Detailed Description
This class contains the functions required by the root-finders to find the pericenter radius in the gravity assist function to find the deltaV.
Definition at line 110 of file gravityAssist.h.
Constructor & Destructor Documentation
tudat::mission_segments::PericenterFindingFunctions::PericenterFindingFunctions (const double absoluteIncomingSemiMajorAxis, const double absoluteOutgoingSemiMajorAxis, const double bendingAngle) inline
Constructor that sets all the parameters in the pericenter finding functions for use in the Newton Raphson rootfinder. Note that absolute values of the semi-major axis are required due to the rootfinding process.
Parameters
absoluteIncomingSemiMajorAxis The absolute semi-major axis of the incoming hyperbolic leg. [m]
absoluteOutgoingSemiMajorAxis The absolute semi-major axis of the outgoing hyperbolic leg. [m]
bendingAngle The bending angle between the excess velocities. [rad]
Definition at line 126 of file gravityAssist.h.
References computeFirstDerivativePericenterRadiusFunction(), and computePericenterRadiusFunction().
Member Function Documentation
double tudat::mission_segments::PericenterFindingFunctions::computePericenterRadiusFunction (const double pericenterRadius)
Computes pericenter radius function. This function is used by the Newton-Raphson root-finder to find the pericenter radius that matches the bending angle required in the gravity assist.
Parameters
pericenterRadius Pericenter radius.
Returns
Pericenter radius root finding function value.
See also
NewtonRaphson().
Definition at line 360 of file gravityAssist.cpp.
Referenced by tudat::mission_segments::gravityAssist(), and PericenterFindingFunctions().
double tudat::mission_segments::PericenterFindingFunctions::computeFirstDerivativePericenterRadiusFunction (const double pericenterRadius)
Computes the first-derivative of the pericenter radius function. This function is used by the Newton-Raphson root-finder to find the pericenter radius that matches the bending angle required in the gravity assist.
Parameters
pericenterRadius Pericenter radius.
Returns
Pericenter radius root finding function first-derivative value.
See also
NewtonRapshon().
Definition at line 369 of file gravityAssist.cpp.
Referenced by PericenterFindingFunctions().
Member Data Documentation
const double tudat::mission_segments::PericenterFindingFunctions::absoluteIncomingSemiMajorAxis_ private
The absolute semi-major axis of the incoming hyperbolic leg. The absolute value is required because otherwisely the first derivative of the pericenter radius finding function will compute the root of a negative value.
Definition at line 165 of file gravityAssist.h.
const double tudat::mission_segments::PericenterFindingFunctions::absoluteOutgoingSemiMajorAxis_ private
The absolute semi-major axis of the outgoing hyperbolic leg. The absolute value is required because otherwisely the first derivative of the pericenter radius finding function will compute the root of a negative value.
Definition at line 173 of file gravityAssist.h.
const double tudat::mission_segments::PericenterFindingFunctions::bendingAngle_ private
Bending angle between the excess velocities.
Definition at line 179 of file gravityAssist.h.
The documentation for this class was generated from the following files:
Astrodynamics/MissionSegments/gravityAssist.h
Astrodynamics/MissionSegments/gravityAssist.cpp