Tudat: tudat::mission_segments::LambertFunctionsGooding Class Reference
tudat::mission_segments::LambertFunctionsGooding Class Reference
Gooding Lambert functions class.
#include <lambertRoutines.h>
Public Member Functions
LambertFunctionsGooding (const double aQParameter, const double aNormalizedTimeOfFlight)
Constructor with immediate definition of parameters.
double computeFirstDerivativeLambertFunctionGooding (const double xParameter)
Define first derivative of general Lambert function.
double computeLambertFunctionGooding (const double xParameter)
Define general Lambert function.
double lambertFirstDerivativeFunctionNegativeGooding (const double xParameter)
Define first derivative of Lambert function for negative lambertEccentricAnomaly.
double lambertFirstDerivativeFunctionPositiveGooding (const double xParameter)
Define first derivative of Lambert function for positive lambertEccentricAnomaly.
double lambertFunctionNegativeGooding (const double xParameter)
Define Lambert function for negative lambertEccentricAnomaly.
double lambertFunctionPositiveGooding (const double xParameter)
Define Lambert function for positive lambertEccentricAnomaly.
Private Attributes
const double normalizedTimeOfFlight
Normalized time of flight for Lambert implementation.
const double qParameter
Lambert q-parameter.
Detailed Description
This class contains the auxiliary functions required by the root-finder in the Lambert routine from Gooding.
Definition at line 116 of file lambertRoutines.h.
Constructor & Destructor Documentation
tudat::mission_segments::LambertFunctionsGooding::LambertFunctionsGooding (const double aQParameter, const double aNormalizedTimeOfFlight) inline
Constructor that sets all the parameters in the Lambert functions for use in the Newton-Raphson rootfinder.
Parameters
aQParameter The value of the Lambert q-parameter. [-]
aNormalizedTimeOfFlight The normalized time-of-flight for the Lambert problem. [-]
Definition at line 127 of file lambertRoutines.h.
References computeFirstDerivativeLambertFunctionGooding(), computeLambertFunctionGooding(), lambertFirstDerivativeFunctionNegativeGooding(), lambertFirstDerivativeFunctionPositiveGooding(), lambertFunctionNegativeGooding(), and lambertFunctionPositiveGooding().
Member Function Documentation
double tudat::mission_segments::LambertFunctionsGooding::computeLambertFunctionGooding (const double xParameter)
Defines the general Lambert function.
Parameters
xParameter x-parameter.
Returns
Lambert function value.
Definition at line 611 of file lambertRoutines.cpp.
Referenced by LambertFunctionsGooding(), and tudat::mission_segments::solveLambertProblemGooding().
double tudat::mission_segments::LambertFunctionsGooding::computeFirstDerivativeLambertFunctionGooding (const double xParameter)
Defines the first derivative of general Lambert function.
Parameters
xParameter x-parameter.
Returns
Derivative of the Lambert function.
Definition at line 627 of file lambertRoutines.cpp.
Referenced by LambertFunctionsGooding().
double tudat::mission_segments::LambertFunctionsGooding::lambertFunctionPositiveGooding (const double xParameter)
Defines the Lambert function for a positive lambertEccentricAnomaly.
Parameters
xParameter x-parameter.
Returns
Lambert function value for a positive lambertEccentricAnomaly.
Definition at line 643 of file lambertRoutines.cpp.
Referenced by LambertFunctionsGooding().
double tudat::mission_segments::LambertFunctionsGooding::lambertFunctionNegativeGooding (const double xParameter)
Defines the Lambert function for a negative lambertEccentricAnomaly.
Parameters
xParameter x-parameter.
Returns
Lambert function value for a negative lambertEccentricAnomaly.
Definition at line 658 of file lambertRoutines.cpp.
Referenced by LambertFunctionsGooding().
double tudat::mission_segments::LambertFunctionsGooding::lambertFirstDerivativeFunctionPositiveGooding (const double xParameter)
Defines the first derivative of Lambert function for a positive lambertEccentricAnomaly.
Parameters
xParameter x-parameter.
Returns
Derivative of the Lambert function for a positive lambertEccentricAnomaly.
Definition at line 673 of file lambertRoutines.cpp.
Referenced by LambertFunctionsGooding().
double tudat::mission_segments::LambertFunctionsGooding::lambertFirstDerivativeFunctionNegativeGooding (const double xParameter)
Defines first derivative of Lambert function for negative lambertEccentricAnomaly.
Parameters
xParameter x-parameter.
Returns
Derivative of the Lambert function for a negative lambertEccentricAnomaly.
Definition at line 705 of file lambertRoutines.cpp.
Referenced by LambertFunctionsGooding().
Member Data Documentation
const double tudat::mission_segments::LambertFunctionsGooding::qParameter private
Lambert q-parameter.
Definition at line 188 of file lambertRoutines.h.
const double tudat::mission_segments::LambertFunctionsGooding::normalizedTimeOfFlight private
Normalized time of flight for Lambert implementation.
Definition at line 194 of file lambertRoutines.h.
The documentation for this class was generated from the following files:
Astrodynamics/MissionSegments/lambertRoutines.h
Astrodynamics/MissionSegments/lambertRoutines.cpp