Tudat: tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType > Class Template Reference
tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType > Class Template Reference abstract
Virtual base class for the observation manager class,.
#include <observationManager.h>
Public Member Functions
ObservationManagerBase (const ObservableType observableType, const boost::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionMatrixInterface, const std::map< LinkEnds, boost::shared_ptr< observation_partials::PositionPartialScaling > > &observationPartialScalers)
Constructor.
virtual ~ObservationManagerBase ()
Virtual destructor.
virtual std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, Eigen::MatrixXd > computeObservationsWithPartials (const std::vector< TimeType > &times, const LinkEnds linkEnds, const LinkEndType linkEndAssociatedWithTime)=0
Function to simulate observations between specified link ends and associated partials at set of observation times.
virtual boost::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > getObservationSimulator ()=0
Function (ṕure virtual) to return the object used to simulate noise-free observations.
virtual int getObservationSize (const LinkEnds &linkEnds)=0
Pure virtual function to return the size of the observable for a given set of link ends.
Protected Member Functions
Eigen::MatrixXd getCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime)
Function to get the state transition and sensitivity matrix.
Protected Attributes
ObservableType observableType_
Type of observable for which the instance of this class will compute observations/observation partials.
std::map< LinkEnds, boost::shared_ptr< observation_partials::PositionPartialScaling > > observationPartialScalers_
boost::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionMatrixInterface_
Object used to compute the state transition/sensitivity matrix at a given time.
int stateTransitionMatrixSize_
Size of (square) state transition matrix.
Detailed Description
template<typename ObservationScalarType = double, typename TimeType = double>
class tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >
Virtual base class for the observation manager class, which is used to compute observable values and partials of a single type of observable during estimation. This base class is sued for practical purposes, as the derived class has a\ template argument for the observable size, precluding the possibility of making a list of objects for all observation managers (e.g. one for each observable type)
Definition at line 35 of file observationManager.h.
Constructor & Destructor Documentation
template<typename ObservationScalarType = double, typename TimeType = double> tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::ObservationManagerBase (const ObservableType observableType, const boost::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionMatrixInterface, const std::map< LinkEnds, boost::shared_ptr< observation_partials::PositionPartialScaling > > & observationPartialScalers) inline
Constructor
Parameters
observableType Type of observable for which the instance of this class will compute observations/observation partials
stateTransitionMatrixInterface Object used to compute the state transition/sensitivity matrix at a given time
observationPartialScalers Map of objects (one per set of link ends) used to compute the scaling of position partials that are used to compute the observation partials in the derived class
Definition at line 48 of file observationManager.h.
References tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::stateTransitionMatrixInterface_, and tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::stateTransitionMatrixSize_.
template<typename ObservationScalarType = double, typename TimeType = double> virtual tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::~ObservationManagerBase () inline virtual
Definition at line 68 of file observationManager.h.
References tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::computeObservationsWithPartials(), tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::getObservationSimulator(), and tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::getObservationSize().
Member Function Documentation
template<typename ObservationScalarType = double, typename TimeType = double> virtual int tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::getObservationSize (const LinkEnds & linkEnds) pure virtual
Pure virtual function to return the size of the observable for a given set of link ends
Parameters
linkEnds Link ends for which observable size is to be computed
Returns
Size of observable
Implemented in tudat::observation_models::ObservationManager< ObservationSize, ObservationScalarType, TimeType >.
Referenced by tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::~ObservationManagerBase().
template<typename ObservationScalarType = double, typename TimeType = double> virtual std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, Eigen::MatrixXd > tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::computeObservationsWithPartials (const std::vector< TimeType > & times, const LinkEnds linkEnds, const LinkEndType linkEndAssociatedWithTime) pure virtual
Function(pure virtual) to simulate observations between specified link ends and associated partials at set of observation times, used the sensitivity and state transition matrix interpolators set in this base class.
Parameters
times Vector of times at which observations are performed
linkEnds Set of stations, S/C etc. in link, with specifiers of type of link end.
linkEndAssociatedWithTime Link end at which input times are valid, i.e. link end for which associated time is kept constant (to input value)
Returns
Pair of observable values and partial matrix
Implemented in tudat::observation_models::ObservationManager< ObservationSize, ObservationScalarType, TimeType >.
Referenced by tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::~ObservationManagerBase().
template<typename ObservationScalarType = double, typename TimeType = double> virtual boost::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::getObservationSimulator () pure virtual
Function (ṕure virtual) to return the object used to simulate noise-free observations
Returns
Object used to simulate ideal observations
Implemented in tudat::observation_models::ObservationManager< ObservationSize, ObservationScalarType, TimeType >.
Referenced by tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::~ObservationManagerBase().
template<typename ObservationScalarType = double, typename TimeType = double> Eigen::MatrixXd tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::getCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime) inline protected
Function to get the state transition matrix Phi and sensitivity matrix S at a given time as a single matrix [Phi;S]
Parameters
evaluationTime Time at which matrices are to be evaluated
Returns
Concatenated state transition and sensitivity matrices at given time.
Definition at line 110 of file observationManager.h.
References tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::stateTransitionMatrixInterface_.
Referenced by tudat::observation_models::ObservationManager< ObservationSize, ObservationScalarType, TimeType >::determineObservationPartialMatrix().
Member Data Documentation
template<typename ObservationScalarType = double, typename TimeType = double> ObservableType tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::observableType_ protected
Definition at line 117 of file observationManager.h.
template<typename ObservationScalarType = double, typename TimeType = double> boost::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::stateTransitionMatrixInterface_ protected
Definition at line 120 of file observationManager.h.
Referenced by tudat::observation_models::ObservationManager< ObservationSize, ObservationScalarType, TimeType >::determineObservationPartialMatrix(), tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::getCombinedStateTransitionAndSensitivityMatrix(), and tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::ObservationManagerBase().
template<typename ObservationScalarType = double, typename TimeType = double> std::map< LinkEnds, boost::shared_ptr< observation_partials::PositionPartialScaling > > tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::observationPartialScalers_ protected
Map of objects (one per set of link ends) used to compute the scaling of position partials that are used to compute the observation partials in the derived class
Definition at line 124 of file observationManager.h.
Referenced by tudat::observation_models::ObservationManager< ObservationSize, ObservationScalarType, TimeType >::updatePartials().
template<typename ObservationScalarType = double, typename TimeType = double> int tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::stateTransitionMatrixSize_ protected
Size of (square) state transition matrix.
Definition at line 130 of file observationManager.h.
Referenced by tudat::observation_models::ObservationManager< ObservationSize, ObservationScalarType, TimeType >::determineObservationPartialMatrix(), and tudat::observation_models::ObservationManagerBase< ObservationScalarType, TimeType >::ObservationManagerBase().
The documentation for this class was generated from the following file:
Astrodynamics/ObservationModels/observationManager.h