Tudat: tudat::orbit_determination::TidalLoveNumberPartialInterface Class Reference
tudat::orbit_determination::TidalLoveNumberPartialInterface Class Reference
(Base) class for calculating the partial of a spherical harmonic acceleration w.r.t. a tidal love number.
#include <tidalLoveNumberPartialInterface.h>
Public Member Functions
TidalLoveNumberPartialInterface (const boost::shared_ptr< gravitation::BasicSolidBodyTideGravityFieldVariations > gravityFieldVariations, const boost::function< Eigen::Vector3d() > deformedBodyPositionFunction, const std::vector< boost::function< Eigen::Vector3d() > > deformingBodyStateFunctions, const boost::function< Eigen::Quaterniond() > rotationToDeformedBodyFrameFrameFunction, const std::string &deformedBody)
Constructor from objects.
virtual ~TidalLoveNumberPartialInterface ()
Destructor.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumber (const int degree, const std::vector< int > &deformingBodyIndices, const int maximumDegree, const int maximumOrder)
Function to calculate the partial of spherical harmonic acceleration w.r.t. complex tidal love numbers.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers (const int degree, const std::vector< int > &orders, const std::vector< int > &deformingBodyIndices, const int maximumDegree, const int maximumOrder)
Function to calculate the partial of spherical harmonic acceleration w.r.t. complex tidal love numbers.
virtual std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumber (const int degree, const std::vector< int > &deformingBodyIndices, const int maximumDegree, const int maximumOrder)
Function to calculate the partial of spherical harmonic acceleration w.r.t. real tidal love numbers.
virtual std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers (const int degree, const std::vector< int > &orders, const std::vector< int > &deformingBodyIndices, const int maximumDegree, const int maximumOrder)
Function to calculate the partial of spherical harmonic acceleration w.r.t. real tidal love numbers.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > & getCurrentDoubleParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, const std::pair< int, int > maximumDegreeAndOrder)
Function to retrieve a partial w.r.t. a double parameter.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > & getCurrentParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, const std::pair< int, int > maximumDegreeAndOrder)
Function to retrieve a partial w.r.t. a double parameter.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > & getCurrentParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, const std::pair< int, int > maximumDegreeAndOrder)
Function to retrieve a partial w.r.t. a vector parameter.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > & getCurrentVectorParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, const std::pair< int, int > maximumDegreeAndOrder)
Function to retrieve a partial w.r.t. a vector parameter.
std::vector< int > getSelectedDeformingBodyIds (const std::vector< std::string > &selectedBodyNames)
Function to obtain the indices of given list of body names in deformingBodies_ member vector.
void resetTime (const double currentTime=TUDAT_NAN)
Reset current time of tidal Love number interface.
virtual std::pair< int, std::pair< int, int > > setParameterPartialFunction (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, const int maximumDegree, const int maximumOrder)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual std::pair< int, std::pair< int, int > > setParameterPartialFunction (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, const int maximumDegree, const int maximumOrder)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void update (const double currentTime)
Update tidal Love number interface to current time.
void updateParameterPartials ()
Function to update the values of the partial derivatives to current state and time.
Protected Member Functions
std::vector< Eigen::Vector2d > calculateCoefficientPartialWrtRealTidalLoveNumber (const int degree, const std::vector< int > &orders, const std::vector< int > &deformingBodyIndices, const int maximumDegree, const int maximumOrder)
Function to calculate the partial of spherical harmonic coefficients w.r.t. real part of tidal love numbers.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > calculateSphericalHarmonicCoefficientPartialMatrix (const std::vector< Eigen::Vector2d > &coefficientPartialsPerOrder, const std::pair< Eigen::Matrix< double, 2, Eigen::Dynamic >, Eigen::Matrix< double, 2, Eigen::Dynamic > > &coefficientPartialScalers)
Function to compute Love number partials from pre-computed partials and provided scaling values.
virtual void setCurrentTidalBodyStates (const int degree, const int order, const int body)
Function to set current state of single body and derived quantities.
virtual void updateCurrentTidalBodyStates (const std::vector< int > &deformingBodiesToUpdate)
Function to pre-calculate all states of bodies involved.
Protected Attributes
boost::function< Eigen::Vector3d() > acceleratingBodyPositionFunction_
Function to retrieve current state of body being accelerated.
std::vector< int > allDeformingBodyIndices_
std::pair< Eigen::Matrix< double, 2, 2 >, Eigen::Matrix< double, 2, 2 > > complexLoveNumberScaler_
Values used to scale real Love number partials to complex Love number partials.
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::pair< int, int > >, std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > > currentDoubleParameterPartials_
List of functions to compute values of partials w.r.t. double parameter partials.
double currentTime_
Current time to which object has been updated.
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::pair< int, int > >, std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
std::string deformedBody_
Name of body being deformed.
double deformedBodyGravitationalParameter_
Current gravitational parameter of body being deformed.
boost::function< double() > deformedBodyGravitationalParameterFunction_
Function to retrieve current gravitational parameter of body being deformed.
boost::function< Eigen::Vector3d() > deformedBodyPositionFunction_
Function to retrieve current state of body being tidally deformed.
double deformedBodyReferenceRadius_
Reference radius used by tidal deformation model.
std::vector< std::string > deformingBodies_
List of bodies causing deformation.
std::vector< boost::function< double() > > deformingBodyGravitationalParameters_
Vector of function to retrieve current gravitational parameters of bodies causing deformation.
std::vector< boost::function< Eigen::Vector3d() > > deformingBodyStateFunctions_
Functions for retrieving states at current time of bodies causing deformation.
std::complex< double > iLongitude_
double massRatio_
Current mass ratio of body causing, w.r.t. body undergoing, deformation, as set by setCurrentTidalBodyStates function.
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::pair< int, int > >, boost::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::pair< int, int > >, boost::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >) > > parameterDoublePartialFunctions_
List of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::pair< int, int > >, boost::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::pair< int, int > >, boost::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >) > > parameterVectorPartialFunctions_
List of functions to compute values of partials w.r.t. vector parameter partials.
Eigen::Vector3d positionOfTidallyDeformedBody_
Current position of deformed body.
std::vector< Eigen::Vector3d > positionsOfDeformingBodies_
List of current positions of bodies causing deformation.
double radiusRatio_
Current radius ratio of body causing, w.r.t. body undergoing, deformation, as set by setCurrentTidalBodyStates function.
std::pair< Eigen::Matrix< double, 2, 1 >, Eigen::Matrix< double, 2, 1 > > realLoveNumberScaler_
Values used to scale real Love number partials to themselves (trivial, but required for interface)
Eigen::Vector3d relativeDeformingBodyPosition_
Current relative position in inertial frame of body causing deformation, as set by setCurrentTidalBodyStates function.
Eigen::Vector3d relativeDeformingBodySphericalPosition_
boost::function< Eigen::Quaterniond() > rotationToDeformedBodyFrameFrameFunction_
Function returning the rotation from inertial to body-fixed frame of deformed body.
Eigen::Quaterniond rotationToTidallyDeformedBody_
Current rotation from inertial frame to body-fixed frame of deformed body.
double sineOfLatitude_
Detailed Description
(Base) class for calculating the partial of a spherical harmonic acceleration w.r.t. a tidal love number. These calculations are implemented separately from the SphericalHarmonicsGravityPartial class as its functionality is quite specific and only used by the SphericalHarmonicsGravityPartial for certain cases. Also, this architecture allows different implementations for different tidal models. This base class assumes no direct tidal lag in teh calculations, i.e. state and rotation functions are all evaluated at same time and lag is implemented by the possibility of complex love numbers (for non-zonal terms).
Definition at line 40 of file tidalLoveNumberPartialInterface.h.
Constructor & Destructor Documentation
tudat::orbit_determination::TidalLoveNumberPartialInterface::TidalLoveNumberPartialInterface (const boost::shared_ptr< gravitation::BasicSolidBodyTideGravityFieldVariations > gravityFieldVariations, const boost::function< Eigen::Vector3d() > deformedBodyPositionFunction, const std::vector< boost::function< Eigen::Vector3d() > > deformingBodyStateFunctions, const boost::function< Eigen::Quaterniond() > rotationToDeformedBodyFrameFrameFunction, const std::string & deformedBody) inline
Constructor from objects.
Parameters
gravityFieldVariations Gravity field variation object which calculates spherical harmonic coefficient variations due to considered love number(s).
deformedBodyPositionFunction Function to retrieve current state of body being tidally deformed
deformingBodyStateFunctions Functions for retrieving states at current time of bodies causing deformation.
rotationToDeformedBodyFrameFrameFunction Function returning the rotation from inertial to body-fixed frame of deformed body.
deformedBody Name of body being tidally deformed.
Definition at line 55 of file tidalLoveNumberPartialInterface.h.
References allDeformingBodyIndices_, complexLoveNumberScaler_, deformedBodyGravitationalParameterFunction_, deformedBodyReferenceRadius_, deformingBodies_, deformingBodyGravitationalParameters_, deformingBodyStateFunctions_, positionsOfDeformingBodies_, and realLoveNumberScaler_.
virtual tudat::orbit_determination::TidalLoveNumberPartialInterface::~TidalLoveNumberPartialInterface () inline virtual
Definition at line 87 of file tidalLoveNumberPartialInterface.h.
References calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), and getSelectedDeformingBodyIds().
Member Function Documentation
std::vector< int > tudat::orbit_determination::TidalLoveNumberPartialInterface::getSelectedDeformingBodyIds (const std::vector< std::string > & selectedBodyNames)
Function to obtain the indices of given list of body names in deformingBodies_ member vector. Function throws an exception if the input vector contains names of bodies not contained in the deformingBodies_ vector
Parameters
selectedBodyNames List of bodies for which the indices in the deformingBodies_ vector are to be obtained
Returns
The indices of given list of body names in deformingBodies_ member vector
Definition at line 47 of file tidalLoveNumberPartialInterface.cpp.
References calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), and deformingBodies_.
Referenced by setParameterPartialFunction(), and ~TidalLoveNumberPartialInterface().
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers (const int degree, const std::vector< int > & orders, const std::vector< int > & deformingBodyIndices, const int maximumDegree, const int maximumOrder)
Function to calculate the partial of spherical harmonic acceleration wrt complex tidal love numbers.
Function to calculate the partial of spherical harmonic acceleration w.r.t. complex tidal love numbers at a single degree. The orders of the love numbers w.r.t. which the partials to be taken are required as input.
Parameters
degree Degree of love numbers w.r.t. which partials are to be taken
orders Spherical harmonic orders in current degree at which the partials are to be taken.
deformingBodyIndices Indices of deforming bodies (in deformingBodies_ member vector) due to which the deformation is to be taken into account
maximumDegree Maximum degree of the acceleration for which the partial derivatives are to be calculated.
maximumOrder Maximum order of the acceleration for which the partial derivatives are to be calculated.
Returns
Partial derivatives of spherical harmonic coefficients. Stl vector entries denote values at requested orders, Eigen vector rows denote C and S coefficient, respectively; columns denote real and complex tidal Love number components.
Definition at line 73 of file tidalLoveNumberPartialInterface.cpp.
References calculateCoefficientPartialWrtRealTidalLoveNumber(), calculateSphericalHarmonicCoefficientPartialMatrix(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), complexLoveNumberScaler_, deformedBodyGravitationalParameter_, deformedBodyGravitationalParameterFunction_, and updateCurrentTidalBodyStates().
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumber(), getSelectedDeformingBodyIds(), setParameterPartialFunction(), and ~TidalLoveNumberPartialInterface().
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumber (const int degree, const std::vector< int > & deformingBodyIndices, const int maximumDegree, const int maximumOrder) inline
Function to calculate the partial of spherical harmonic acceleration w.r.t. complex tidal love numbers at all orders of a single degree.
Parameters
degree Degree of love numbers w.r.t. which partials are to be taken
deformingBodyIndices Indices of deforming bodies (in deformingBodies_ member vector) due to which the deformation is to be taken into account
maximumDegree Maximum degree of the acceleration for which the partial derivatives are to be calculated.
maximumOrder Maximum order of the acceleration for which the partial derivatives are to be calculated.
Returns
Partial derivatives of spherical harmonic coefficients. Stl vector entries denote values at all orders at degree, Eigen vector rows denote C and S coefficient, respectively; columns denote real and complex tidal Love number components.
Definition at line 133 of file tidalLoveNumberPartialInterface.h.
References calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), and tudat::estimatable_parameters::fullDegreeOrders.
Referenced by setParameterPartialFunction().
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers (const int degree, const std::vector< int > & orders, const std::vector< int > & deformingBodyIndices, const int maximumDegree, const int maximumOrder) virtual
Function to calculate the partial of spherical harmonic acceleration wrt real tidal love numbers.
Function to calculate the partial of spherical harmonic acceleration w.r.t. real tidal love numbers at a single degree. The orders of the love numbers w.r.t. which the partials to be taken are required as input.
Parameters
degree Degree of love numbers w.r.t. which partials are to be taken
orders Spherical harmonic orders in current degree at which the partials are to be taken.
deformingBodyIndices Indices of deforming bodies (in deformingBodies_ member vector) due to which the deformation is to be taken into account
maximumDegree Maximum degree of the acceleration for which the partial derivatives are to be calculated.
maximumOrder Maximum order of the acceleration for which the partial derivatives are to be calculated.
Returns
Partial derivatives of spherical harmonic coefficients. Stl vector entries denote values at requested orders, Eigen vector rows denote C and S coefficient, respectively; Eigen vector has one column, denoting real part of tidal Love number.
Definition at line 96 of file tidalLoveNumberPartialInterface.cpp.
References calculateCoefficientPartialWrtRealTidalLoveNumber(), calculateSphericalHarmonicCoefficientPartialMatrix(), deformedBodyGravitationalParameter_, deformedBodyGravitationalParameterFunction_, realLoveNumberScaler_, and updateCurrentTidalBodyStates().
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumber(), calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumber(), and setParameterPartialFunction().
virtual std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumber (const int degree, const std::vector< int > & deformingBodyIndices, const int maximumDegree, const int maximumOrder) inline virtual
Function to calculate the partial of spherical harmonic acceleration w.r.t. real tidal love numbers at all orders of a single degree.
Parameters
degree Degree of love numbers w.r.t. which partials are to be taken
deformingBodyIndices Indices of deforming bodies (in deformingBodies_ member vector) due to which the deformation is to be taken into account
maximumDegree Maximum degree of the acceleration for which the partial derivatives are to be calculated.
maximumOrder Maximum order of the acceleration for which the partial derivatives are to be calculated.
Returns
Partial derivatives of spherical harmonic coefficients. Stl vector entries denote values at all orders at degree, Eigen vector rows denote C and S coefficient, respectively; Eigen vector has one column, denoting real part of tidal Love number.
Definition at line 180 of file tidalLoveNumberPartialInterface.h.
References calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), and tudat::estimatable_parameters::fullDegreeOrders.
Referenced by setParameterPartialFunction().
void tudat::orbit_determination::TidalLoveNumberPartialInterface::update (const double currentTime) inline
Update tidal Love number interface to current time. NOTE: This function currently has very limited functionality, resulting in reduced computational efficiency of the class.
Parameters
currentTime Current time to which interface is to be set.
Definition at line 197 of file tidalLoveNumberPartialInterface.h.
References currentTime_, rotationToDeformedBodyFrameFrameFunction_, and rotationToTidallyDeformedBody_.
void tudat::orbit_determination::TidalLoveNumberPartialInterface::resetTime (const double currentTime = TUDAT_NAN) inline
Reset current time of tidal Love number interface, typically used to set NaN time, signalling that an update of the object is required
Parameters
currentTime Current time to which interface is to be set.
Definition at line 209 of file tidalLoveNumberPartialInterface.h.
References currentDoubleParameterPartials_, currentTime_, and currentVectorParameterPartials_.
void tudat::orbit_determination::TidalLoveNumberPartialInterface::updateParameterPartials () inline
Function to update the values of the partial derivatives to current state and time. The list of functions computing the partial derivatives is determined by the calls to the setParameterPartialFunction functions of this class.
Definition at line 224 of file tidalLoveNumberPartialInterface.h.
References currentDoubleParameterPartials_, currentVectorParameterPartials_, parameterDoublePartialFunctionIterator_, parameterDoublePartialFunctions_, parameterVectorPartialFunctionIterator_, parameterVectorPartialFunctions_, and setParameterPartialFunction().
std::pair< int, std::pair< int, int > > tudat::orbit_determination::TidalLoveNumberPartialInterface::setParameterPartialFunction (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, const int maximumDegree, const int maximumOrder) virtual
Function to set a dependency of this partial object w.r.t. a given double parameter. If a dependency exists, the given partial is recomputed on every call of updateParameterPartials.
Parameters
parameter Partial w.r.t. which dependency is to be checked and set.
maximumDegree Maximum degree of the acceleration for which the partial derivatives are to be calculated.
maximumOrder Maximum order of the acceleration for which the partial derivatives are to be calculated.
Returns
Pair, with first: Size (number of columns) of parameter partial. Zero if no dependency, 1 otherwise. Pair second: maximum degree and order of gravity field that are affected by the partials (NaN if no dependency).
Definition at line 117 of file tidalLoveNumberPartialInterface.cpp.
Referenced by updateParameterPartials().
std::pair< int, std::pair< int, int > > tudat::orbit_determination::TidalLoveNumberPartialInterface::setParameterPartialFunction (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, const int maximumDegree, const int maximumOrder) virtual
Function to set a dependency of this partial object w.r.t. a given vector parameter. If a dependency exists, the given partial is recomputed on every call of updateParameterPartials.
Parameters
parameter Partial w.r.t. which dependency is to be checked and set.
maximumDegree Maximum degree of the acceleration for which the partial derivatives are to be calculated.
maximumOrder Maximum order of the acceleration for which the partial derivatives are to be calculated.
Returns
Pair, with first: Size (number of columns) of parameter partial. Zero if no dependency. Pair second: maximum degree and order of gravity field that are affected by the partials (NaN if no dependency).
Definition at line 126 of file tidalLoveNumberPartialInterface.cpp.
References calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumber(), calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumber(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), deformedBody_, deformingBodies_, tudat::estimatable_parameters::full_degree_tidal_love_number, tudat::orbit_determination::getMaximumUsedDegreeAndOrder(), getSelectedDeformingBodyIds(), parameterVectorPartialFunctions_, and tudat::estimatable_parameters::single_degree_variable_tidal_love_number.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >& tudat::orbit_determination::TidalLoveNumberPartialInterface::getCurrentParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, const std::pair< int, int > maximumDegreeAndOrder) inline
Function to retrieve a partial w.r.t. a double parameter. An error is thrown if there is no dependency w.r.t. the requested parameter. A warning is printed if the dependency exists, but has not yet been computed for the current time step.
Parameters
parameter Partial w.r.t. which a parameter is to be computed
maximumDegreeAndOrder Maximum degree and order that are to be used.
Returns
Partial of state derivative w.r.t. given parameter
Definition at line 290 of file tidalLoveNumberPartialInterface.h.
References currentDoubleParameterPartials_, and parameterDoublePartialFunctions_.
Referenced by getCurrentDoubleParameterPartial(), and getCurrentVectorParameterPartial().
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >& tudat::orbit_determination::TidalLoveNumberPartialInterface::getCurrentDoubleParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, const std::pair< int, int > maximumDegreeAndOrder) inline
Function to retrieve a partial w.r.t. a double parameter. An error is thrown if there is no dependency w.r.t. the requested parameter. A warning is printed if the dependency exists, but has not yet been computed for the current time step.
Parameters
parameter Partial w.r.t. which a parameter is to be computed
maximumDegreeAndOrder Maximum degree and order that are to be used.
Returns
Partial of state derivative w.r.t. given parameter
Definition at line 323 of file tidalLoveNumberPartialInterface.h.
References getCurrentParameterPartial().
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction().
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >& tudat::orbit_determination::TidalLoveNumberPartialInterface::getCurrentParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, const std::pair< int, int > maximumDegreeAndOrder) inline
Function to retrieve a partial w.r.t. a vector parameter. An error is thrown if there is no dependency w.r.t. the requested parameter. A warning is printed if the dependency exists, but has not yet been computed for the current time step.
Parameters
parameter Partial w.r.t. which a parameter is to be computed
maximumDegreeAndOrder Maximum degree and order that are to be used.
Returns
Partial of state derivative w.r.t. given parameter
Definition at line 340 of file tidalLoveNumberPartialInterface.h.
References currentVectorParameterPartials_, and parameterVectorPartialFunctions_.
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >& tudat::orbit_determination::TidalLoveNumberPartialInterface::getCurrentVectorParameterPartial (const boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, const std::pair< int, int > maximumDegreeAndOrder) inline
Function to retrieve a partial w.r.t. a vector parameter. An error is thrown if there is no dependency w.r.t. the requested parameter. A warning is printed if the dependency exists, but has not yet been computed for the current time step.
Parameters
parameter Partial w.r.t. which a parameter is to be computed
maximumDegreeAndOrder Maximum degree and order that are to be used.
Returns
Partial of state derivative w.r.t. given parameter
Definition at line 375 of file tidalLoveNumberPartialInterface.h.
References calculateCoefficientPartialWrtRealTidalLoveNumber(), calculateSphericalHarmonicCoefficientPartialMatrix(), getCurrentParameterPartial(), setCurrentTidalBodyStates(), and updateCurrentTidalBodyStates().
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction().
std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateSphericalHarmonicCoefficientPartialMatrix (const std::vector< Eigen::Vector2d > & coefficientPartialsPerOrder, const std::pair< Eigen::Matrix< double, 2, Eigen::Dynamic >, Eigen::Matrix< double, 2, Eigen::Dynamic > > & coefficientPartialScalers) protected
Function to compute Love number partials from pre-computed partials and provided scaling values. This function is used to compute, for instance, the partials of complex Love numbers from the partials of the real components, which are obtained from a simple sclaing
Parameters
coefficientPartialsPerOrder Partial derivatives of C and S coefficients (row 0 and 1) that are to be scaled by coefficientPartialScalers.
coefficientPartialScalers Pair of values by which to scale C and S coefficients (first and second of pair, respectively).
Returns
Love number partials obtained from pre-computed partials and provided scaling values
Definition at line 295 of file tidalLoveNumberPartialInterface.cpp.
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), getCurrentVectorParameterPartial(), and setCurrentTidalBodyStates().
std::vector< Eigen::Vector2d > tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateCoefficientPartialWrtRealTidalLoveNumber (const int degree, const std::vector< int > & orders, const std::vector< int > & deformingBodyIndices, const int maximumDegree, const int maximumOrder) protected
Function to calculate the partial of spherical harmonic coefficients w.r.t. real part of tidal love numbers. Partials at a single degree are calculated, with the desired orders required as input.
Parameters
degree Spherical harmonic degree at which partials are to be taken.
orders Spherical harmonic orders at given degree at which partials are to be taken (if vector is empty, all orders at given degree are used, in ascending order).
deformingBodyIndices Indices of deforming bodies (in deformingBodies_ member vector) due to which the deformation is to be taken into account
maximumDegree Maximum degree of the acceleration for which the partial derivatives are to be calculated.
maximumOrder Maximum order of the acceleration for which the partial derivatives are to be calculated.
Returns
Vector of partials of Spherical harmonic coefficients ([C_{nm};S_{nm}]). w.r.t. real part of tidal love number Entries of return vector correspond to orders given by corresponding entry in orders vector.
Definition at line 321 of file tidalLoveNumberPartialInterface.cpp.
References tudat::gravitation::calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude(), tudat::basic_mathematics::computeLegendrePolynomialExplicit(), iLongitude_, massRatio_, radiusRatio_, tudat::basic_mathematics::raiseToIntegerPower(), setCurrentTidalBodyStates(), and sineOfLatitude_.
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), and getCurrentVectorParameterPartial().
void tudat::orbit_determination::TidalLoveNumberPartialInterface::updateCurrentTidalBodyStates (const std::vector< int > & deformingBodiesToUpdate) protected virtual
Function to pre-calculate all states of bodies involved. Implemented here assuming no time lag, derived classes could provide modified implementations.
Parameters
deformingBodiesToUpdate Indices of deforming bodies (in deformingBodies_ member vector) due to which the deformationis to be taken into accountused.
Definition at line 266 of file tidalLoveNumberPartialInterface.cpp.
References deformedBodyPositionFunction_, deformingBodyStateFunctions_, positionOfTidallyDeformedBody_, and positionsOfDeformingBodies_.
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), and getCurrentVectorParameterPartial().
void tudat::orbit_determination::TidalLoveNumberPartialInterface::setCurrentTidalBodyStates (const int degree, const int order, const int body) protected virtual
Function to set current state of single body and derived quantities Sets the variables used in calculation loop from pre-calculations of updateCurrentTidalBodyStates function.
Parameters
body Index of body for which variables are to be computed.
order Degree of field at which updated is to be performed (not used; may be used in derived class function)
degree Degree of field at which updated is to be performed (not used; may be used in derived class function)
Definition at line 278 of file tidalLoveNumberPartialInterface.cpp.
References calculateSphericalHarmonicCoefficientPartialMatrix(), tudat::coordinate_conversions::convertCartesianToSpherical(), deformedBodyGravitationalParameter_, deformedBodyReferenceRadius_, deformingBodyGravitationalParameters_, iLongitude_, massRatio_, tudat::mathematical_constants::PI, positionOfTidallyDeformedBody_, positionsOfDeformingBodies_, radiusRatio_, relativeDeformingBodyPosition_, relativeDeformingBodySphericalPosition_, rotationToTidallyDeformedBody_, and sineOfLatitude_.
Referenced by calculateCoefficientPartialWrtRealTidalLoveNumber(), and getCurrentVectorParameterPartial().
Member Data Documentation
double tudat::orbit_determination::TidalLoveNumberPartialInterface::deformedBodyReferenceRadius_ protected
Definition at line 445 of file tidalLoveNumberPartialInterface.h.
Referenced by setCurrentTidalBodyStates(), and TidalLoveNumberPartialInterface().
boost::function< Eigen::Vector3d() > tudat::orbit_determination::TidalLoveNumberPartialInterface::deformedBodyPositionFunction_ protected
Function to retrieve current state of body being tidally deformed. Typically linked to spherical harmonic acceleration model. Function is also used for tidal spherical harmonic variation calculations in case of no tidal time delay.
Definition at line 454 of file tidalLoveNumberPartialInterface.h.
Referenced by updateCurrentTidalBodyStates().
boost::function< Eigen::Vector3d() > tudat::orbit_determination::TidalLoveNumberPartialInterface::acceleratingBodyPositionFunction_ protected
Definition at line 457 of file tidalLoveNumberPartialInterface.h.
boost::function< double() > tudat::orbit_determination::TidalLoveNumberPartialInterface::deformedBodyGravitationalParameterFunction_ protected
Definition at line 462 of file tidalLoveNumberPartialInterface.h.
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), and TidalLoveNumberPartialInterface().
double tudat::orbit_determination::TidalLoveNumberPartialInterface::deformedBodyGravitationalParameter_ protected
Definition at line 466 of file tidalLoveNumberPartialInterface.h.
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), and setCurrentTidalBodyStates().
std::vector< boost::function< double() > > tudat::orbit_determination::TidalLoveNumberPartialInterface::deformingBodyGravitationalParameters_ protected
Definition at line 469 of file tidalLoveNumberPartialInterface.h.
Referenced by setCurrentTidalBodyStates(), and TidalLoveNumberPartialInterface().
std::vector< boost::function< Eigen::Vector3d() > > tudat::orbit_determination::TidalLoveNumberPartialInterface::deformingBodyStateFunctions_ protected
Definition at line 472 of file tidalLoveNumberPartialInterface.h.
Referenced by TidalLoveNumberPartialInterface(), and updateCurrentTidalBodyStates().
boost::function< Eigen::Quaterniond() > tudat::orbit_determination::TidalLoveNumberPartialInterface::rotationToDeformedBodyFrameFrameFunction_ protected
Definition at line 475 of file tidalLoveNumberPartialInterface.h.
Referenced by update().
double tudat::orbit_determination::TidalLoveNumberPartialInterface::currentTime_ protected
Definition at line 478 of file tidalLoveNumberPartialInterface.h.
Referenced by resetTime(), and update().
Eigen::Vector3d tudat::orbit_determination::TidalLoveNumberPartialInterface::relativeDeformingBodyPosition_ protected
Definition at line 483 of file tidalLoveNumberPartialInterface.h.
Referenced by setCurrentTidalBodyStates().
Eigen::Vector3d tudat::orbit_determination::TidalLoveNumberPartialInterface::relativeDeformingBodySphericalPosition_ protected
Current relative position of body causing deformation in body-fixed frame of deformed body, as set by setCurrentTidalBodyStates function
Definition at line 487 of file tidalLoveNumberPartialInterface.h.
Referenced by setCurrentTidalBodyStates().
double tudat::orbit_determination::TidalLoveNumberPartialInterface::massRatio_ protected
Definition at line 490 of file tidalLoveNumberPartialInterface.h.
Referenced by calculateCoefficientPartialWrtRealTidalLoveNumber(), and setCurrentTidalBodyStates().
double tudat::orbit_determination::TidalLoveNumberPartialInterface::radiusRatio_ protected
Definition at line 493 of file tidalLoveNumberPartialInterface.h.
Referenced by calculateCoefficientPartialWrtRealTidalLoveNumber(), and setCurrentTidalBodyStates().
double tudat::orbit_determination::TidalLoveNumberPartialInterface::sineOfLatitude_ protected
Current sine of latitude of body causing deformation, in frame fixed to body being deformed, as set by setCurrentTidalBodyStates function
Definition at line 497 of file tidalLoveNumberPartialInterface.h.
Referenced by calculateCoefficientPartialWrtRealTidalLoveNumber(), and setCurrentTidalBodyStates().
std::complex< double > tudat::orbit_determination::TidalLoveNumberPartialInterface::iLongitude_ protected
Current sine of longitude of body causing deformation, in frame fixed to body being deformed, times i (sqrt(-1)) as set by setCurrentTidalBodyStates function
Definition at line 501 of file tidalLoveNumberPartialInterface.h.
Referenced by calculateCoefficientPartialWrtRealTidalLoveNumber(), and setCurrentTidalBodyStates().
std::pair< Eigen::Matrix< double, 2, 1 >, Eigen::Matrix< double, 2, 1 > > tudat::orbit_determination::TidalLoveNumberPartialInterface::realLoveNumberScaler_ protected
Definition at line 505 of file tidalLoveNumberPartialInterface.h.
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtRealTidalLoveNumbers(), and TidalLoveNumberPartialInterface().
std::pair< Eigen::Matrix< double, 2, 2 >, Eigen::Matrix< double, 2, 2 > > tudat::orbit_determination::TidalLoveNumberPartialInterface::complexLoveNumberScaler_ protected
Definition at line 508 of file tidalLoveNumberPartialInterface.h.
Referenced by calculateSphericalHarmonicCoefficientsPartialWrtComplexTidalLoveNumbers(), and TidalLoveNumberPartialInterface().
std::vector< int > tudat::orbit_determination::TidalLoveNumberPartialInterface::allDeformingBodyIndices_ protected
Definition at line 510 of file tidalLoveNumberPartialInterface.h.
Referenced by TidalLoveNumberPartialInterface().
std::string tudat::orbit_determination::TidalLoveNumberPartialInterface::deformedBody_ protected
Definition at line 513 of file tidalLoveNumberPartialInterface.h.
Referenced by setParameterPartialFunction().
std::vector< std::string > tudat::orbit_determination::TidalLoveNumberPartialInterface::deformingBodies_ protected
Definition at line 516 of file tidalLoveNumberPartialInterface.h.
Referenced by getSelectedDeformingBodyIds(), setParameterPartialFunction(), and TidalLoveNumberPartialInterface().
Eigen::Quaterniond tudat::orbit_determination::TidalLoveNumberPartialInterface::rotationToTidallyDeformedBody_ protected
Definition at line 519 of file tidalLoveNumberPartialInterface.h.
Referenced by setCurrentTidalBodyStates(), and update().
Eigen::Vector3d tudat::orbit_determination::TidalLoveNumberPartialInterface::positionOfTidallyDeformedBody_ protected
Definition at line 522 of file tidalLoveNumberPartialInterface.h.
Referenced by setCurrentTidalBodyStates(), and updateCurrentTidalBodyStates().
std::vector< Eigen::Vector3d > tudat::orbit_determination::TidalLoveNumberPartialInterface::positionsOfDeformingBodies_ protected
Definition at line 525 of file tidalLoveNumberPartialInterface.h.
Referenced by setCurrentTidalBodyStates(), TidalLoveNumberPartialInterface(), and updateCurrentTidalBodyStates().
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::pair< int, int > >, std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > > tudat::orbit_determination::TidalLoveNumberPartialInterface::currentDoubleParameterPartials_ protected
Definition at line 530 of file tidalLoveNumberPartialInterface.h.
Referenced by getCurrentParameterPartial(), resetTime(), and updateParameterPartials().
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::pair< int, int > >, boost::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >) > > tudat::orbit_determination::TidalLoveNumberPartialInterface::parameterDoublePartialFunctions_ protected
Definition at line 535 of file tidalLoveNumberPartialInterface.h.
Referenced by getCurrentParameterPartial(), and updateParameterPartials().
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::pair< int, int > >, boost::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >) > >::iterator tudat::orbit_determination::TidalLoveNumberPartialInterface::parameterDoublePartialFunctionIterator_ protected
Definition at line 540 of file tidalLoveNumberPartialInterface.h.
Referenced by updateParameterPartials().
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::pair< int, int > >, std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > > > tudat::orbit_determination::TidalLoveNumberPartialInterface::currentVectorParameterPartials_ protected
Definition at line 545 of file tidalLoveNumberPartialInterface.h.
Referenced by getCurrentParameterPartial(), resetTime(), and updateParameterPartials().
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::pair< int, int > >, boost::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >) > > tudat::orbit_determination::TidalLoveNumberPartialInterface::parameterVectorPartialFunctions_ protected
Definition at line 550 of file tidalLoveNumberPartialInterface.h.
Referenced by getCurrentParameterPartial(), setParameterPartialFunction(), and updateParameterPartials().
std::map< std::pair< boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::pair< int, int > >, boost::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >) > >::iterator tudat::orbit_determination::TidalLoveNumberPartialInterface::parameterVectorPartialFunctionIterator_ protected
Definition at line 555 of file tidalLoveNumberPartialInterface.h.
Referenced by updateParameterPartials().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/AccelerationPartials/tidalLoveNumberPartialInterface.h
Astrodynamics/OrbitDetermination/AccelerationPartials/tidalLoveNumberPartialInterface.cpp