Tudat: CMakeLists.txt File Reference
CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 2.6) project(Tudat) if($
Function Documentation
cmake_minimum_required (VERSION 2. 6)
Definition at line 11 of file CMakeLists.txt.
References add_subdirectory(), endif(), tudat::simulation_setup::nrlmsise00, and setup_tudat_library_target().