Tudat: tudat::aerodynamics::CustomAerodynamicCoefficientInterface Class Reference
tudat::aerodynamics::CustomAerodynamicCoefficientInterface Class Reference
Aerodynamic coefficient interface taking function pointers providing aerodynamics coefficients as a function of independent variables (doubles).
#include <customAerodynamicCoefficientInterface.h>
Public Member Functions
CustomAerodynamicCoefficientInterface (const boost::function< Eigen::Vector3d(const std::vector< double > &) > forceCoefficientFunction, const boost::function< Eigen::Vector3d(const std::vector< double > &) > momentCoefficientFunction, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame=true, const bool areCoefficientsInNegativeAxisDirection=true)
Constructor.
CustomAerodynamicCoefficientInterface (const boost::function< Eigen::Vector6d(const std::vector< double > &) > coefficientFunction, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame=true, const bool areCoefficientsInNegativeAxisDirection=true)
Constructor.
void resetConstantCoefficients (const Eigen::Vector6d &constantCoefficients)
Function to reset the constant aerodynamic coefficients, only valid if coefficients are already constant.
virtual void updateCurrentCoefficients (const std::vector< double > &independentVariables)
Compute the aerodynamic coefficients at current flight condition.
Public Member Functions inherited from tudat::aerodynamics::AerodynamicCoefficientInterface
AerodynamicCoefficientInterface (const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame=true, const bool areCoefficientsInNegativeAxisDirection=true)
Constructor.
virtual ~AerodynamicCoefficientInterface ()
Default destructor.
bool getAreCoefficientsInAerodynamicFrame ()
Function that returns whether the coefficients are given in aerodynamic frame.
bool getAreCoefficientsInNegativeAxisDirection ()
Function that returns whether the coefficients are positive in positive axes directions.
AerodynamicCoefficientsIndependentVariables getControlSurfaceIndependentVariableName (const std::string &controlSurface, const unsigned int index)
Function to get the identifier for a single independent variable for a single control surface.
std::map< std::string, std::vector< AerodynamicCoefficientsIndependentVariables > > getControlSurfaceIndependentVariables ()
Function to get the list of independent variables for all control surfaces.
std::string getControlSurfaceName (const int index)
Function to get control surface name at given index in list of control surfaces.
Eigen::Matrix< double, 6, 1 > getCurrentAerodynamicCoefficients ()
Function for calculating and returning aerodynamic force and moment coefficients.
Eigen::Vector3d getCurrentForceCoefficients ()
Pure virtual function for calculating and returning aerodynamic force coefficients.
Eigen::Vector3d getCurrentMomentCoefficients ()
Pure virtual function for calculating and returning aerodynamic moment coefficients.
AerodynamicCoefficientsIndependentVariables getIndependentVariableName (const unsigned int index)
Function to return a single identifier of the physical meaning of one independent variable.
std::vector< AerodynamicCoefficientsIndependentVariables > getIndependentVariableNames ()
Function to return the identifiers of the physical meaning of each independent variable.
double getLateralReferenceLength ()
Get lateral reference length.
Eigen::VectorXd getMomentReferencePoint ()
Get moment reference point.
unsigned int getNumberOfControlSurfaceIndependentVariables (const std::string controlSurface)
Function to return the number of independent variables for a given control surface.
unsigned int getNumberOfControlSurfaces ()
Function to return the number of control surfaces in current coefficient interface.
unsigned int getNumberOfIndependentVariables ()
Function to return the number of independent variables upon which the coeficients depend.
double getReferenceArea ()
Get reference area.
double getReferenceLength ()
Get reference length.
Eigen::Vector3d getReferenceLengths ()
Get reference lengths.
void setControlSurfaceIncrements (const std::map< std::string, boost::shared_ptr< ControlSurfaceIncrementAerodynamicInterface > > controlSurfaceIncrementInterfaces)
Function to set the list of control surface aerodynamic coefficient interfaces.
void updateCurrentControlSurfaceCoefficientsCoefficients (const std::string &currentControlSurface, std::vector< double > controlSurfaceIndependentVariables)
Compute the aerodynamic coefficients for a single control surface, and add to full configuration coefficients.
void updateFullCurrentCoefficients (const std::vector< double > &independentVariables, const std::map< std::string, std::vector< double > > &controlSurfaceIndependentVariables=std::map< std::string, std::vector< double > >())
Function to update the aerodynamic coefficients of the full body with control surfaces.
Private Attributes
boost::function< Eigen::Vector6d(const std::vector< double > &) > coefficientFunction_
Additional Inherited Members
Protected Attributes inherited from tudat::aerodynamics::AerodynamicCoefficientInterface
bool areCoefficientsInAerodynamicFrame_
Boolean to denote whether coefficients are defined in aerodynamic or body frame.
bool areCoefficientsInNegativeAxisDirection_
Boolean to denote whether coefficients are positive along frame axes.
std::map< std::string, boost::shared_ptr< ControlSurfaceIncrementAerodynamicInterface > > controlSurfaceIncrementInterfaces_
List of control surface aerodynamic coefficient interfaces.
std::vector< std::string > controlSurfaceNames_
Explicit list of control surface names, in same order as iterator over controlSurfaceIncrementInterfaces_.
Eigen::Vector3d currentForceCoefficients_
The current force coefficients.
Eigen::Vector3d currentMomentCoefficients_
The current moment coefficients.
std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames_
double lateralReferenceLength_
Lateral aerodynamic reference length.
Eigen::Vector3d momentReferencePoint_
Aerodynamic moment reference point.
unsigned int numberOfIndependentVariables_
Number of independent variables upon which the force and moment coefficients depend.
double referenceArea_
Aerodynamic reference area.
double referenceLength_
Aerodynamic reference length.
Eigen::Vector3d referenceLengths_
Aerodynamic reference lengths.
Detailed Description
Aerodynamic coefficient interface taking function pointers providing aerodynamics coefficients as a function of independent variables (doubles).
The origin of the coefficients or the nature of the independent variables is irrelevant for this class. A factory functios (createConstantCoefficientAerodynamicCoefficientInterface) is provided in the createFlightConditions file, which can be used to define constant coefficients. NOTE: Functionality of this class is tested in test_aerodynamic_coefficient_generator test suite.
Definition at line 40 of file customAerodynamicCoefficientInterface.h.
Constructor & Destructor Documentation
tudat::aerodynamics::CustomAerodynamicCoefficientInterface::CustomAerodynamicCoefficientInterface (const boost::function< Eigen::Vector3d(const std::vector< double > &) > forceCoefficientFunction, const boost::function< Eigen::Vector3d(const std::vector< double > &) > momentCoefficientFunction, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d & momentReferencePoint, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame = true, const bool areCoefficientsInNegativeAxisDirection = true) inline
Constructor.
Parameters
forceCoefficientFunction Function returning the aerodynamic force coefficients as function of the set of independent variables.
momentCoefficientFunction Function returning the aerodynamic force coefficients as function of the set of independent variables.
referenceLength Reference length with which aerodynamic moments (about x- and z- axes) are non-dimensionalized.
referenceArea Reference area with which aerodynamic forces and moments are non-dimensionalized.
lateralReferenceLength Reference length with which aerodynamic moments (about y-axis) is non-dimensionalized.
momentReferencePoint Point w.r.t. which aerodynamic moment is calculated.
independentVariableNames Vector with identifiers for the physical meaning of each independent variable of the aerodynamic coefficients.
areCoefficientsInAerodynamicFrame Boolean to define whether the aerodynamic coefficients are defined in the aerodynamic frame (drag, side, lift force) or in the body frame (typically denoted as Cx, Cy, Cz) (default true).
areCoefficientsInNegativeAxisDirection Boolean to define whether the aerodynamic coefficients are positiver along tyhe positive axes of the body or aerodynamic frame (see areCoefficientsInAerodynamicFrame). Note that for (drag, side, lift force), the coefficients are typically defined in negative direction (default true).
Definition at line 68 of file customAerodynamicCoefficientInterface.h.
References coefficientFunction_, and tudat::aerodynamics::concatenateForceAndMomentCoefficients().
tudat::aerodynamics::CustomAerodynamicCoefficientInterface::CustomAerodynamicCoefficientInterface (const boost::function< Eigen::Vector6d(const std::vector< double > &) > coefficientFunction, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d & momentReferencePoint, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame = true, const bool areCoefficientsInNegativeAxisDirection = true) inline
Constructor.
Parameters
coefficientFunction Function returning the concatenated aerodynamic force and moment coefficients as function of the set of independent variables.
referenceLength Reference length with which aerodynamic moments (about x- and z- axes) are non-dimensionalized.
referenceArea Reference area with which aerodynamic forces and moments are non-dimensionalized.
lateralReferenceLength Reference length with which aerodynamic moments (about y-axis) is non-dimensionalized.
momentReferencePoint Point w.r.t. which aerodynamic moment is calculated
independentVariableNames Vector with identifiers for the physical meaning of each independent variable of the aerodynamic coefficients.
areCoefficientsInAerodynamicFrame Boolean to define whether the aerodynamic coefficients are defined in the aerodynamic frame (drag, side, lift force) or in the body frame (typically denoted as Cx, Cy, Cz) (default true).
areCoefficientsInNegativeAxisDirection Boolean to define whether the aerodynamic coefficients are positiver along tyhe positive axes of the body or aerodynamic frame (see areCoefficientsInAerodynamicFrame). Note that for (drag, side, lift force), the coefficients are typically defined in negative direction (default true).
Definition at line 112 of file customAerodynamicCoefficientInterface.h.
Member Function Documentation
virtual void tudat::aerodynamics::CustomAerodynamicCoefficientInterface::updateCurrentCoefficients (const std::vector< double > & independentVariables) inline virtual
Compute the aerodynamic coefficients at current flight conditions (independent variables). Input is a set of independent variables (doubles) which represent the variables from which the coefficients are calculated. The physical nature of these variables depends on the coefficientFunction_ variables. The size of the independent variable vector must be numberOfIndependentVariables_
Parameters
independentVariables Independent variables of force and moment coefficient determination implemented by derived class
Implements tudat::aerodynamics::AerodynamicCoefficientInterface.
Definition at line 139 of file customAerodynamicCoefficientInterface.h.
References coefficientFunction_, tudat::aerodynamics::AerodynamicCoefficientInterface::currentForceCoefficients_, tudat::aerodynamics::AerodynamicCoefficientInterface::currentMomentCoefficients_, and tudat::aerodynamics::AerodynamicCoefficientInterface::numberOfIndependentVariables_.
void tudat::aerodynamics::CustomAerodynamicCoefficientInterface::resetConstantCoefficients (const Eigen::Vector6d & constantCoefficients) inline
Function to reset the constant aerodynamic coefficients, only valid if coefficients are already constant. Function checks if the numberOfIndependentVariables_ is equal to zero, and throws an error if it is not.
Parameters
constantCoefficients New force and moment coefficients (in that order) expressed in the same frame as existing coefficients.
Definition at line 164 of file customAerodynamicCoefficientInterface.h.
References coefficientFunction_, and tudat::aerodynamics::AerodynamicCoefficientInterface::numberOfIndependentVariables_.
Member Data Documentation
boost::function< Eigen::Vector6d(const std::vector< double >&) > tudat::aerodynamics::CustomAerodynamicCoefficientInterface::coefficientFunction_ private
Function returning the concatenated aerodynamic force and moment coefficients as function of the set of independent variables.
Definition at line 179 of file customAerodynamicCoefficientInterface.h.
Referenced by CustomAerodynamicCoefficientInterface(), resetConstantCoefficients(), and updateCurrentCoefficients().
The documentation for this class was generated from the following file:
Astrodynamics/Aerodynamics/customAerodynamicCoefficientInterface.h