Tudat: tudat::acceleration_partials::EmpiricalAccelerationPartial Class Reference
tudat::acceleration_partials::EmpiricalAccelerationPartial Class Reference
#include <empiricalAccelerationPartial.h>
Public Member Functions
EmpiricalAccelerationPartial (std::shared_ptr< basic_astrodynamics::EmpiricalAcceleration > empiricalAcceleration, std::string acceleratedBody, std::string acceleratingBody)
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter.
void update (const double currentTime=TUDAT_NAN)
Function for updating common blocks of partial to current state.
void wrtArcWiseEmpiricalAccelerationCoefficient (std::shared_ptr< estimatable_parameters::ArcWiseEmpiricalAccelerationCoefficientsParameter > parameter, Eigen::MatrixXd &partialDerivativeMatrix)
Function to compute the partial w.r.t. arcwise empirical acceleration components.
void wrtEmpiricalAccelerationCoefficient (std::shared_ptr< estimatable_parameters::EmpiricalAccelerationCoefficientsParameter > parameter, Eigen::MatrixXd &partialDerivativeMatrix)
Function to compute the partial w.r.t. time-independent empirical acceleration components.
void wrtEmpiricalAccelerationCoefficientFromIndices (const int numberOfAccelerationComponents, const std::map< basic_astrodynamics::EmpiricalAccelerationFunctionalShapes, std::vector< int > > &accelerationIndices, Eigen::MatrixXd &partialDerivativeMatrix)
Function to compute the partial w.r.t. time-independent empirical acceleration components.
void wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration..
void wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration..
void wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration..
void wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration..
Public Member Functions inherited from tudat::acceleration_partials::AccelerationPartial
AccelerationPartial (const std::string &acceleratedBody, const std::string &acceleratingBody, const basic_astrodynamics::AvailableAcceleration accelerationType)
Base class constructor.
virtual ~AccelerationPartial ()
Virtual destructor.
std::string getAcceleratedBody ()
Function to retrieve the name of the body undergoing acceleration.
std::string getAcceleratingBody ()
Function to retrieve the name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration getAccelerationType ()
Function to retrieve the type of acceleration w.r.t. which partial is taken..
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
virtual bool isAccelerationPartialWrtAdditionalBodyNonnullptr (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the translational state of a third body is non-zero.
virtual bool isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the acceleration is dependent on a non-translational integrated state (default none).
bool isStateDerivativeDependentOnIntegratedState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to check whether a partial w.r.t. some integrated state is non-zero.
virtual void wrtNonTranslationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the acceleration w.r.t. a non-translational integrated state.
virtual void wrtPositionOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of the third body.
void wrtStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body undergoing acceleration.
void wrtStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body exerting acceleration.
void wrtStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the third body.
virtual void wrtVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
virtual std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to retrieve the function that computes (by reference) a given double parameter partial.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Private Attributes
Eigen::Matrix< double, 1, 6 > cartesianStateElementPerturbations
Perturbations to use on Cartesian state elements when computing partial of true anomaly w.r.t. state.
Eigen::Matrix3d currentPositionPartial_
Current partial of empirical acceleration w.r.t. position of body undergoing acceleration.
Eigen::Matrix3d currentVelocityPartial_
Current partial of empirical acceleration w.r.t. velocity of body undergoing acceleration.
std::shared_ptr< basic_astrodynamics::EmpiricalAcceleration > empiricalAcceleration_
Acceleration w.r.t. which partials are to be computed.
Additional Inherited Members
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Protected Attributes inherited from tudat::acceleration_partials::AccelerationPartial
std::string acceleratedBody_
Name of the body undergoing acceleration.
std::string acceleratingBody_
Name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration accelerationType_
Type of acceleration w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Definition at line 42 of file empiricalAccelerationPartial.h.
Constructor & Destructor Documentation
EmpiricalAccelerationPartial()
tudat::acceleration_partials::EmpiricalAccelerationPartial::EmpiricalAccelerationPartial (std::shared_ptr< basic_astrodynamics::EmpiricalAcceleration > empiricalAcceleration, std::string acceleratedBody, std::string acceleratingBody) inline
Definition at line 47 of file empiricalAccelerationPartial.h.
References cartesianStateElementPerturbations.
Member Function Documentation
wrtPositionOfAcceleratedBody()
void tudat::acceleration_partials::EmpiricalAccelerationPartial::wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 65 of file empiricalAccelerationPartial.h.
References currentPositionPartial_.
wrtPositionOfAcceleratingBody()
void tudat::acceleration_partials::EmpiricalAccelerationPartial::wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration and adding it to the existing partial block. The update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 90 of file empiricalAccelerationPartial.h.
References currentPositionPartial_.
wrtVelocityOfAcceleratedBody()
void tudat::acceleration_partials::EmpiricalAccelerationPartial::wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 114 of file empiricalAccelerationPartial.h.
References currentVelocityPartial_.
wrtVelocityOfAcceleratingBody()
void tudat::acceleration_partials::EmpiricalAccelerationPartial::wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration and adding it to the existing partial block. The update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 139 of file empiricalAccelerationPartial.h.
References currentVelocityPartial_.
getParameterPartialFunction()
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::EmpiricalAccelerationPartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 79 of file empiricalAccelerationPartial.cpp.
References tudat::estimatable_parameters::arc_wise_empirical_acceleration_coefficients, tudat::estimatable_parameters::empirical_acceleration_coefficients, wrtArcWiseEmpiricalAccelerationCoefficient(), and wrtEmpiricalAccelerationCoefficientFromIndices().
update()
void tudat::acceleration_partials::EmpiricalAccelerationPartial::update (const double currentTime = TUDAT_NAN) virtual
Function for updating common blocks of partial to current state. Position and velocity partials are computed and set.
Parameters
currentTime Time at which partials are to be calculated
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 116 of file empiricalAccelerationPartial.cpp.
References tudat::acceleration_partials::calculateNumericalPartialOfTrueAnomalyWrtState(), tudat::linear_algebra::calculatePartialOfNormalizedVector(), tudat::basic_astrodynamics::cosine_empirical, tudat::linear_algebra::getCrossProductMatrix(), and tudat::basic_astrodynamics::sine_empirical.
wrtArcWiseEmpiricalAccelerationCoefficient()
void tudat::acceleration_partials::EmpiricalAccelerationPartial::wrtArcWiseEmpiricalAccelerationCoefficient (std::shared_ptr< estimatable_parameters::ArcWiseEmpiricalAccelerationCoefficientsParameter > parameter, Eigen::MatrixXd & partialDerivativeMatrix)
Function to compute the partial w.r.t. arcwise empirical acceleration components
Parameters
parameter Object defining the properties of the arcwise components that are to be estimated.
partialDerivativeMatrix Matrix of partial derivatives of accelerations w.r.t. empirical accelerations (returned by reference)
Definition at line 183 of file empiricalAccelerationPartial.cpp.
Referenced by getParameterPartialFunction().
wrtEmpiricalAccelerationCoefficient()
void tudat::acceleration_partials::EmpiricalAccelerationPartial::wrtEmpiricalAccelerationCoefficient (std::shared_ptr< estimatable_parameters::EmpiricalAccelerationCoefficientsParameter > parameter, Eigen::MatrixXd & partialDerivativeMatrix) inline
Function to compute the partial w.r.t. time-independent empirical acceleration components
Parameters
parameter Object defining the properties of the components that are to be estimated.
partialDerivativeMatrix Matrix of partial derivatives of accelerations w.r.t. empirical accelerations (returned by reference)
Definition at line 187 of file empiricalAccelerationPartial.h.
References wrtEmpiricalAccelerationCoefficientFromIndices().
wrtEmpiricalAccelerationCoefficientFromIndices()
void tudat::acceleration_partials::EmpiricalAccelerationPartial::wrtEmpiricalAccelerationCoefficientFromIndices (const int numberOfAccelerationComponents, const std::map< basic_astrodynamics::EmpiricalAccelerationFunctionalShapes, std::vector< int > > & accelerationIndices, Eigen::MatrixXd & partialDerivativeMatrix)
Function to compute the partial w.r.t. time-independent empirical acceleration components from list of components and functional shapes.
Parameters
numberOfAccelerationComponents Total number of empirical acceleration components w.r.t. which partials are to be computed.
accelerationIndices Map denoting list of components of accelerations that are to be computed. Key: functional shape of empirical accelerations. Value: list of acceleration vaector entries that are to be used (0: radial (R), 1: along-track (S), 2: cross-track (W)).
partialDerivativeMatrix Matrix of partial derivatives of accelerations w.r.t. empirical accelerations (returned by reference)
Definition at line 207 of file empiricalAccelerationPartial.cpp.
References tudat::basic_astrodynamics::constant_empirical, tudat::basic_astrodynamics::cosine_empirical, and tudat::basic_astrodynamics::sine_empirical.
Referenced by getParameterPartialFunction(), and wrtEmpiricalAccelerationCoefficient().
Member Data Documentation
empiricalAcceleration_
std::shared_ptr< basic_astrodynamics::EmpiricalAcceleration > tudat::acceleration_partials::EmpiricalAccelerationPartial::empiricalAcceleration_ private
Definition at line 216 of file empiricalAccelerationPartial.h.
currentPositionPartial_
Eigen::Matrix3d tudat::acceleration_partials::EmpiricalAccelerationPartial::currentPositionPartial_ private
Definition at line 219 of file empiricalAccelerationPartial.h.
Referenced by wrtPositionOfAcceleratedBody(), and wrtPositionOfAcceleratingBody().
currentVelocityPartial_
Eigen::Matrix3d tudat::acceleration_partials::EmpiricalAccelerationPartial::currentVelocityPartial_ private
Definition at line 222 of file empiricalAccelerationPartial.h.
Referenced by wrtVelocityOfAcceleratedBody(), and wrtVelocityOfAcceleratingBody().
cartesianStateElementPerturbations
Eigen::Matrix< double, 1, 6 > tudat::acceleration_partials::EmpiricalAccelerationPartial::cartesianStateElementPerturbations private
Definition at line 225 of file empiricalAccelerationPartial.h.
Referenced by EmpiricalAccelerationPartial().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/AccelerationPartials/empiricalAccelerationPartial.h
Astrodynamics/OrbitDetermination/AccelerationPartials/empiricalAccelerationPartial.cpp