Tudat: tudat::geometric_shapes::CompositeSurfaceGeometry Class Reference
tudat::geometric_shapes::CompositeSurfaceGeometry Class Reference
Composite surface geometry class.
#include <compositeSurfaceGeometry.h>
Public Types
typedef boost::shared_ptr< CompositeSurfaceGeometry > CompositeSurfaceGeometryPointer
Typedef for shared-pointer to CompositeSurfaceGeometry object.
Public Member Functions
CompositeSurfaceGeometry ()
Default constructor.
CompositeSurfaceGeometry (std::vector< boost::shared_ptr< SingleSurfaceGeometry > > singleSurfaceGeometryList, std::vector< boost::shared_ptr< CompositeSurfaceGeometry > > compositeSurfaceGeometryList)
Constructor, sets constituent surface geometries of objects.
virtual ~CompositeSurfaceGeometry ()
Default destructor.
boost::shared_ptr< CompositeSurfaceGeometry > getCompositeSurfaceGeometry (const unsigned int index)
Get pointer to a stored CompositeSurfaceGeometry object.
unsigned int getNumberOfCompositeSurfaceGeometries ()
Get number of composite surface geometries.
unsigned int getNumberOfSingleSurfaceGeometries ()
Get number of single surface geometries.
boost::shared_ptr< SingleSurfaceGeometry > getSingleSurfaceGeometry (const unsigned int index)
Get pointer to stored SingleSurfaceGeometry object.
Public Member Functions inherited from tudat::SurfaceGeometry
virtual ~SurfaceGeometry ()
Default destructor.
Protected Member Functions
void setCompositeSurfaceGeometry (boost::shared_ptr< CompositeSurfaceGeometry > compositeSurfaceGeometry, const unsigned int index)
Set pointer to a CompositeSurfaceGeometry object.
void setNumberOfCompositeSurfaceGeometries (const unsigned int numberOfCompositeSurfaceGeometries)
Set number of composite surface geometries.
void setNumberOfSingleSurfaceGeometries (const unsigned int numberOfSingleSurfaceGeometries)
Set number of single surface geometries.
void setSingleSurfaceGeometry (boost::shared_ptr< SingleSurfaceGeometry > singleSurfaceGeometry, const unsigned int index)
Set pointer to SingleSurfaceGeometry object.
Protected Attributes
std::vector< CompositeSurfaceGeometryPointer > compositeSurfaceGeometryList_
Array of pointers to CompositeSurfaceGeometries.
unsigned int numberOfCompositeSurfaceGeometries_
Size of compositeSurfaceGeometryList_.
unsigned int numberOfSingleSurfaceGeometries_
Size of singleSurfaceGeometryList_.
std::vector< SingleSurfaceGeometryPointer > singleSurfaceGeometryList_
Array of pointers to SingleSurfaceGeometries.
Friends
std::ostream & operator<< (std::ostream &stream, CompositeSurfaceGeometry &compositeSurfaceGeometry)
Overload ostream to print class information.
Detailed Description
Class for a composite surface geometry, which can be composed of any number of single surface or composite surface geometries, to be set by the user. This class is a container class for surface geometries.
SingleSurfaceGeometry objects should be retrieved from this class (or recursively from a member of CompositeSurfaceGeometry objects) to perform geometric operations.
Definition at line 37 of file compositeSurfaceGeometry.h.
Member Typedef Documentation
typedef boost::shared_ptr< CompositeSurfaceGeometry > tudat::geometric_shapes::CompositeSurfaceGeometry::CompositeSurfaceGeometryPointer
Definition at line 42 of file compositeSurfaceGeometry.h.
Constructor & Destructor Documentation
tudat::geometric_shapes::CompositeSurfaceGeometry::CompositeSurfaceGeometry () inline
Default constructor.
Definition at line 48 of file compositeSurfaceGeometry.h.
tudat::geometric_shapes::CompositeSurfaceGeometry::CompositeSurfaceGeometry (std::vector< boost::shared_ptr< SingleSurfaceGeometry > > singleSurfaceGeometryList, std::vector< boost::shared_ptr< CompositeSurfaceGeometry > > compositeSurfaceGeometryList)
Constructor, sets constituent surface geometries of objects.
Parameters
singleSurfaceGeometryList vector of pointers to SingleSurfaceGeometries
compositeSurfaceGeometryList vector of pointers to CompositeSurfaceGeometries
Definition at line 19 of file compositeSurfaceGeometry.cpp.
References numberOfCompositeSurfaceGeometries_, numberOfSingleSurfaceGeometries_, setCompositeSurfaceGeometry(), setNumberOfCompositeSurfaceGeometries(), setNumberOfSingleSurfaceGeometries(), and setSingleSurfaceGeometry().
virtual tudat::geometric_shapes::CompositeSurfaceGeometry::~CompositeSurfaceGeometry () inline virtual
Default destructor.
Definition at line 65 of file compositeSurfaceGeometry.h.
Member Function Documentation
boost::shared_ptr< SingleSurfaceGeometry > tudat::geometric_shapes::CompositeSurfaceGeometry::getSingleSurfaceGeometry (const unsigned int index) inline
Returns a pointer to a SingleSurfaceGeometry object stored in singleSurfaceGeometryList_.
Parameters
index Index of singleSurfaceGeometryList_ where the object to be retrieved is stored.
Returns
Pointer to SingleSurfaceGeometry object at index location in singleSurfaceGeometryList_.
Definition at line 76 of file compositeSurfaceGeometry.h.
References singleSurfaceGeometryList_.
boost::shared_ptr< CompositeSurfaceGeometry > tudat::geometric_shapes::CompositeSurfaceGeometry::getCompositeSurfaceGeometry (const unsigned int index) inline
Returns a pointer to a CompositeSurfaceGeometry object stored in compositeSurfaceGeometryList_.
Parameters
index Index of compositeSurfaceGeometryList_ where the object to be retrieved is stored.
Returns
Pointer to CompositeSurfaceGeometry object at index location in compositeSurfaceGeometryList_.
Definition at line 90 of file compositeSurfaceGeometry.h.
References compositeSurfaceGeometryList_.
unsigned int tudat::geometric_shapes::CompositeSurfaceGeometry::getNumberOfSingleSurfaceGeometries () inline
Returns the number of single surface geometries stored in singleSurfaceGeometryList_.
Returns
Number of SingleSurfaceGeometry objects stored in class.
Definition at line 102 of file compositeSurfaceGeometry.h.
References numberOfSingleSurfaceGeometries_.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::HypersonicLocalInclinationAnalysis().
unsigned int tudat::geometric_shapes::CompositeSurfaceGeometry::getNumberOfCompositeSurfaceGeometries () inline
Returns the number of composite surface geometries stored in compositeSurfaceGeometryList_.
Returns
Number of CompositeSurfaceGeometry objects stored in class.
Definition at line 113 of file compositeSurfaceGeometry.h.
References numberOfCompositeSurfaceGeometries_, and operator<<.
void tudat::geometric_shapes::CompositeSurfaceGeometry::setSingleSurfaceGeometry (boost::shared_ptr< SingleSurfaceGeometry > singleSurfaceGeometry, const unsigned int index) inline protected
Sets a pointer to a SingleSurfaceGeometry object in singleSurfaceGeometryList_.
Parameters
singleSurfaceGeometry Pointer to SingleSurfaceGeometry object which is to be stored in singleSurfaceGeometryList_.
index Index of singleSurfaceGeometryList_ at which the surface is to be set.
Definition at line 139 of file compositeSurfaceGeometry.h.
References singleSurfaceGeometryList_.
Referenced by tudat::geometric_shapes::Capsule::Capsule(), and CompositeSurfaceGeometry().
void tudat::geometric_shapes::CompositeSurfaceGeometry::setCompositeSurfaceGeometry (boost::shared_ptr< CompositeSurfaceGeometry > compositeSurfaceGeometry, const unsigned int index) inline protected
Sets a pointer to a CompositeSurfaceGeometry in compositeSurfaceGeometryList_.
Parameters
compositeSurfaceGeometry Pointer to CompositeSurfaceGeometry object which is to be stored in compositeSurfaceGeometryList_.
index Index of compositeSurfaceGeometryList_ at which the surface is to be set.
Definition at line 154 of file compositeSurfaceGeometry.h.
References compositeSurfaceGeometryList_.
Referenced by CompositeSurfaceGeometry().
void tudat::geometric_shapes::CompositeSurfaceGeometry::setNumberOfSingleSurfaceGeometries (const unsigned int numberOfSingleSurfaceGeometries) inline protected
Sets and allocates number of SingleSurfaceGeometry objects.
Parameters
numberOfSingleSurfaceGeometries Number of SingleSurfaceGeometry objects stored.
Definition at line 165 of file compositeSurfaceGeometry.h.
References numberOfSingleSurfaceGeometries_, and singleSurfaceGeometryList_.
Referenced by tudat::geometric_shapes::Capsule::Capsule(), and CompositeSurfaceGeometry().
void tudat::geometric_shapes::CompositeSurfaceGeometry::setNumberOfCompositeSurfaceGeometries (const unsigned int numberOfCompositeSurfaceGeometries) inline protected
Sets and allocates number of CompositeSurfaceGeometry objects.
Parameters
numberOfCompositeSurfaceGeometries Number of CompositeSurfaceGeometry objects stored.
Definition at line 177 of file compositeSurfaceGeometry.h.
References compositeSurfaceGeometryList_, and numberOfCompositeSurfaceGeometries_.
Referenced by tudat::geometric_shapes::Capsule::Capsule(), and CompositeSurfaceGeometry().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, CompositeSurfaceGeometry & compositeSurfaceGeometry) friend
Overloads ostream to print class information, prints the class type, and number of constituent SingleSurfaceGeometry and compositeSurfaceGeometry objects.
Parameters
stream Stream object.
compositeSurfaceGeometry compositeSurfaceGeometry object.
Returns
Stream object.
Definition at line 40 of file compositeSurfaceGeometry.cpp.
Referenced by getNumberOfCompositeSurfaceGeometries().
Member Data Documentation
unsigned int tudat::geometric_shapes::CompositeSurfaceGeometry::numberOfSingleSurfaceGeometries_ protected
Size of singleSurfaceGeometryList_.
Definition at line 188 of file compositeSurfaceGeometry.h.
Referenced by tudat::geometric_shapes::Capsule::Capsule(), CompositeSurfaceGeometry(), getNumberOfSingleSurfaceGeometries(), tudat::geometric_shapes::operator<<(), and setNumberOfSingleSurfaceGeometries().
unsigned int tudat::geometric_shapes::CompositeSurfaceGeometry::numberOfCompositeSurfaceGeometries_ protected
Size of compositeSurfaceGeometryList_.
Definition at line 194 of file compositeSurfaceGeometry.h.
Referenced by CompositeSurfaceGeometry(), getNumberOfCompositeSurfaceGeometries(), tudat::geometric_shapes::operator<<(), and setNumberOfCompositeSurfaceGeometries().
std::vector< SingleSurfaceGeometryPointer > tudat::geometric_shapes::CompositeSurfaceGeometry::singleSurfaceGeometryList_ protected
Array of pointers to SingleSurfaceGeometries.
Definition at line 200 of file compositeSurfaceGeometry.h.
Referenced by tudat::geometric_shapes::Capsule::Capsule(), getSingleSurfaceGeometry(), setNumberOfSingleSurfaceGeometries(), and setSingleSurfaceGeometry().
std::vector< CompositeSurfaceGeometryPointer > tudat::geometric_shapes::CompositeSurfaceGeometry::compositeSurfaceGeometryList_ protected
Array of pointers to CompositeSurfaceGeometries.
Definition at line 206 of file compositeSurfaceGeometry.h.
Referenced by getCompositeSurfaceGeometry(), setCompositeSurfaceGeometry(), and setNumberOfCompositeSurfaceGeometries().
The documentation for this class was generated from the following files:
Mathematics/GeometricShapes/compositeSurfaceGeometry.h
Mathematics/GeometricShapes/compositeSurfaceGeometry.cpp