Tudat: tudat::observation_models Namespace Reference
tudat::observation_models Namespace Reference
Classes
class AngularPositionObservationModel
Class for simulating angular position (right ascension/declination) observables.
class ArcWiseConstantObservationBiasSettings
Class for defining settings for the creation of an arc-wise constant absolute or relative observation bias model.
class BodyAvoidanceAngleCalculator
Function to check whether an observation is possible, based on body avoidance angle, as vied from single link end.
class ConstantArcWiseObservationBias
Class for an arc-wise constant absolute observation bias of a given size.
class ConstantObservationBias
Class for a constant absolute observation bias of a given size.
class ConstantObservationBiasSettings
Class for defining settings for the creation of a constant absolute or relative observation bias model.
class ConstantRelativeArcWiseObservationBias
Class for an arc-wise constant relative observation bias of a given size.
class ConstantRelativeObservationBias
Class for a constant relative observation bias of a given size.
class CustomDopplerProperTimeRateInterface
Class to compute proper time rate for one-way Doppler observation using user-provided custom function.
class DirectFirstOrderDopplerProperTimeRateInterface
Function to compute first-order approximation of proper-time rate for one-way Doppler observable.
class DirectFirstOrderDopplerProperTimeRateSettings
Class to define the settings for first-order, single body, proper time rate (at a single link end) in one-way Doppler mode.
class DopplerProperTimeRateInterface
Base class for interface class that is used to compute proper-time rate at a transmitter/receiver for one-way Doppler model.
class DopplerProperTimeRateSettings
Base class to define the settings for proper time rate (at a single link end) in one-way Doppler mode.
class FirstOrderLightTimeCorrectionCalculator
Class to calculate first order relativistic light time correction (Shapiro time delay) due to a set of point masses.
class FirstOrderRelativisticLightTimeCorrectionSettings
class LightTimeCalculator
Class to calculate the light time between two points.
class LightTimeCorrection
Base class for computing deviations from the light-time w.r.t. straight-line propagation at constant velocity (c).
class LightTimeCorrectionFunctionWrapper
Class for wrapping a custom light-time correction function.
class LightTimeCorrectionSettings
Base class for light-time correction settings.
class MinimumElevationAngleCalculator
Function to check whether an observation is possible based on minimum elevation angle criterion at one link end.
class MultipleObservationBiasSettings
Class for defining settings for the creation of a multiple biases for a single observable.
class MultiTypeObservationBias
Class for combining multiple observation bias models into a single bias value.
class NWayRangeObservationModel
Class for simulating n-way range observables.
class NWayRangeObservationSettings
Class to define the settings for one-way differenced range-rate (e.g. closed-loop Doppler) observable.
class ObservationBias
Base class (non-functional) for describing observation biases.
class ObservationBiasSettings
Base class to define settings for creation of an observation bias model.
class ObservationManager
Class to manage simulation of observables and associated partials for a single type of observable.
class ObservationManagerBase
Virtual base class for the observation manager class,.
class ObservationModel
Base class for models of observables (i.e. range, range-rate, etc.).
class ObservationModelCreator
Interface class for creating observation models.
class ObservationModelCreator< 1, ObservationScalarType, TimeType >
Interface class for creating observation models of size 1.
class ObservationModelCreator< 2, ObservationScalarType, TimeType >
Interface class for creating observation models of size 2.
class ObservationModelCreator< 3, ObservationScalarType, TimeType >
Interface class for creating observation models of size 3.
class ObservationSettings
Class used for defining the settings for an observation model that is to be created.
struct ObservationSimulationTimeSettings
Base struct for defining times at which observations are to be simulated.
class ObservationSimulator
Objects used to simulate a set of observations of a given kind.
class ObservationSimulatorBase
Virtual base class for the observation simulator class.
class ObservationViabilityCalculator
Base class for determining whether an observation is possible or not.
class ObservationViabilitySettings
Class to define settings for observation viability calculator creation.
class OccultationCalculator
Function to check whether an observation is possible, based on whether a given body is causing an occultation of the link.
class OneWayDifferencedRangeObservationModel
Class for simulating one-way differenced range (e.g. closed-loop Doppler) observable.
class OneWayDifferencedRangeRateObservationSettings
Class to define the settings for one-way differenced range-rate (e.g. closed-loop Doppler) observable.
class OneWayDopplerObservationModel
Computes observable the (simplified) one-way Doppler observation between two link ends, omitting proper time rates and light time corrections.
class OneWayDopplerObservationSettings
Class to define the settings for one-way Doppler observable.
class OneWayRangeObservationModel
Class for simulating one-way range observables.
class PositionObservationModel
Class for simulating observations of three-dimensional position.
struct TabulatedObservationSimulationTimeSettings
class TwoWayDopplerObservationModel
Computes observable the (simplified) one-way Doppler observation between two link ends, omitting proper time rates and light time corrections.
class TwoWayDopplerObservationSettings
Class to define the settings for one-way Doppler observable.
Typedefs
typedef std::function< double(const Eigen::Vector6d &, const Eigen::Vector6d &, const double, const double) > LightTimeCorrectionFunction
Typedef for function calculating light-time correction in light-time calculation loop.
typedef std::map< LinkEnds, std::vector< std::shared_ptr< LightTimeCorrectionSettings > > > LightTimeCorrectionSettingsMap
Typedef for a list of list time correction settings per link end.
typedef std::pair< std::string, std::string > LinkEndId
Typedef for the identifier of a given link-end (body and reference points)
typedef std::map< LinkEndType, LinkEndId > LinkEnds
Typedef for list of link ends, with associated role, used for a single observation (model).
typedef std::multimap< LinkEnds, std::shared_ptr< ObservationSettings > > ObservationSettingsMap
typedef std::vector< std::shared_ptr< observation_models::ObservationViabilitySettings > > ObservationViabilitySettingsList
Typedef for vector of ObservationViabilitySettings pointers.
typedef std::map< LinkEnds, std::vector< std::shared_ptr< ObservationViabilityCalculator > > > PerLinkEndsObservationViabilityCalculatorList
Typedef for a list of observation viability calculators for a single observable type, sorted by and link ends.
typedef std::map< ObservableType, std::map< LinkEnds, std::vector< std::shared_ptr< ObservationViabilityCalculator > > > > PerObservableObservationViabilityCalculatorList
Typedef for a list of observation viability calculators, sorted by observable type and link ends.
typedef std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSettings > > > SortedObservationSettingsMap
Enumerations
enum DopplerProperTimeRateType { custom_doppler_proper_time_rate, direct_first_order_doppler_proper_time_rate }
Enum defining all possible types of proper time rate computations in one-way Doppler.
enum LightTimeCorrectionType { first_order_relativistic, function_wrapper_light_time_correction }
Enum defining different types of light time corrections.
enum LinkEndType {
unidentified_link_end = -1, transmitter = 0, reflector1 = 1, reflector2 = 2,
reflector3 = 3, reflector4 = 4, receiver = 5, observed_body = 6
}
Enum defining different link end types.
enum ObservableType {
one_way_range = 0, angular_position = 1, position_observable = 2, one_way_doppler = 3,
one_way_differenced_range = 4, n_way_range = 5, two_way_doppler = 6
}
Enum for types of observations.
enum ObservationBiasTypes {
multiple_observation_biases, constant_absolute_bias, constant_relative_bias, arc_wise_constant_absolute_bias,
arc_wise_constant_relative_bias
}
Enum listing types of observation biases that are availabe.
enum ObservationViabilityType { minimum_elevation_angle, body_avoidance_angle, body_occultation }
Enum defining possible checks which can be performed for observation viability,.
Functions
template<typename ObservationScalarType = double>
ObservationScalarType calculateLineOfSightVelocityAsCFraction (const Eigen::Matrix< ObservationScalarType, 3, 1 > &lineOfSightUnitVector, const Eigen::Matrix< ObservationScalarType, 3, 1 > &velocityVector)
Function to compute the component of a (velocity) vector projected along a unit vector, divided by speed of light.
template<typename ObservationScalarType = double, typename TimeType = double>
ObservationScalarType calculateLineOfSightVelocityAsCFractionFromReceiverStateFunction (const std::function< Eigen::Matrix< ObservationScalarType, 6, 1 >(const double) > &receiverStateFunction, const Eigen::Matrix< ObservationScalarType, 3, 1 > &transmitterPosition, const TimeType currentTime)
Function to compute component of transmitter velocity projected along line-of-sight vector, divided by speed of light.
template<typename ObservationScalarType = double, typename TimeType = double>
ObservationScalarType calculateLineOfSightVelocityAsCFractionFromTransmitterStateFunction (const Eigen::Matrix< ObservationScalarType, 3, 1 > &receiverPosition, const std::function< Eigen::Matrix< ObservationScalarType, 6, 1 >(const double) > &transmitterStateFunction, const TimeType currentTime)
Function to compute component of transmitter velocity projected along line-of-sight vector, divided by speed of light.
template<typename ObservationScalarType = double>
ObservationScalarType computeDopplerProperTimeInfluenceTaylorSeriesExpansion (const ObservationScalarType transmitterProperTimeRateDifference, const ObservationScalarType receiverProperTimeRateDifference, const int taylorSeriesOrder)
Function to compute proper time contribution one-way Doppler term from a Taylor series expansion.
template<typename ObservationScalarType = double>
ObservationScalarType computeOneWayFirstOrderDopplerTaylorSeriesExpansion (Eigen::Matrix< ObservationScalarType, 6, 1 > &transmitterState, Eigen::Matrix< ObservationScalarType, 6, 1 > &receiverState, Eigen::Matrix< ObservationScalarType, 1, 3 > &lightTimeWrtTransmitterPositionPartial, Eigen::Matrix< ObservationScalarType, 1, 3 > &lightTimeWrtReceiverPositionPartial, const int taylorSeriesOrder)
Function to compute first-order (radial) Doppler term from a Taylor series expansion.
SortedObservationSettingsMap convertUnsortedToSortedObservationSettingsMap (const ObservationSettingsMap &unsortedObservationSettingsMap)
Function to create list of observation models sorted by observable type and link ends from list only sorted in link ends.
std::shared_ptr< BodyAvoidanceAngleCalculator > createBodyAvoidanceAngleCalculator (const simulation_setup::NamedBodyMap &bodyMap, const LinkEnds linkEnds, const ObservableType observationType, const std::shared_ptr< ObservationViabilitySettings > observationViabilitySettings)
Function to create an object to check if a body avoidance angle condition is met for an observation.
template<typename ObservationScalarType = double, typename TimeType = double>
std::shared_ptr< observation_models::LightTimeCalculator< ObservationScalarType, TimeType > > createLightTimeCalculator (const std::function< Eigen::Matrix< ObservationScalarType, 6, 1 >(const TimeType) > &transmitterCompleteEphemeris, const std::function< Eigen::Matrix< ObservationScalarType, 6, 1 >(const TimeType) > &receiverCompleteEphemeris, const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::shared_ptr< LightTimeCorrectionSettings > > &lightTimeCorrections, const LinkEndId &transmittingLinkEnd, const LinkEndId &receivingLinkEnd)
Function to create a light-time calculation object.
template<typename ObservationScalarType = double, typename TimeType = double>
std::shared_ptr< observation_models::LightTimeCalculator< ObservationScalarType, TimeType > > createLightTimeCalculator (const LinkEndId &transmittingLinkEnd, const LinkEndId &receivingLinkEnd, const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::shared_ptr< LightTimeCorrectionSettings > > &lightTimeCorrections=std::vector< std::shared_ptr< LightTimeCorrectionSettings > >())
Function to create a light-time calculation object.
std::shared_ptr< LightTimeCorrection > createLightTimeCorrections (const std::shared_ptr< LightTimeCorrectionSettings > correctionSettings, const simulation_setup::NamedBodyMap &bodyMap, const std::pair< std::string, std::string > &transmitter, const std::pair< std::string, std::string > &receiver)
Function to create object that computes a single (type of) correction to the light-time.
std::shared_ptr< MinimumElevationAngleCalculator > createMinimumElevationAngleCalculator (const simulation_setup::NamedBodyMap &bodyMap, const LinkEnds linkEnds, const ObservableType observationType, const std::shared_ptr< ObservationViabilitySettings > observationViabilitySettings, const std::string &stationName)
Function to create an object to check if a minimum elevation angle condition is met for an observation.
template<int ObservationSize = 1>
std::shared_ptr< ObservationBias< ObservationSize > > createObservationBiasCalculator (const LinkEnds linkEnds, const ObservableType observableType, const std::shared_ptr< ObservationBiasSettings > biasSettings, const simulation_setup::NamedBodyMap &bodyMap)
Function to create an object that computes an observation bias.
template<int ObservationSize = 1, typename ObservationScalarType , typename TimeType >
std::shared_ptr< ObservationManagerBase< ObservationScalarType, TimeType > > createObservationManager (const ObservableType observableType, const std::map< LinkEnds, std::shared_ptr< ObservationSettings > > settingsPerLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const std::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionMatrixInterface)
Function to create an object to simulate observations of a given type and associated partials.
template<typename ObservationScalarType , typename TimeType >
std::shared_ptr< ObservationManagerBase< ObservationScalarType, TimeType > > createObservationManagerBase (const ObservableType observableType, const std::map< LinkEnds, std::shared_ptr< ObservationSettings > > settingsPerLinkEnds, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const std::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionMatrixInterface)
Function to create an object to simulate observations of a given type and associated partials.
template<typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > createObservationSimulationTimeSettingsMap (const std::map< ObservableType, std::map< LinkEnds, std::pair< std::vector< TimeType >, LinkEndType > > > &originalMap)
Function to generate ObservationSimulationTimeSettings objects from simple time list input.
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double>
std::shared_ptr< ObservationSimulator< ObservationSize, ObservationScalarType, TimeType > > createObservationSimulator (const ObservableType observableType, const std::map< LinkEnds, std::shared_ptr< ObservationSettings > > settingsPerLinkEnds, const simulation_setup::NamedBodyMap &bodyMap)
Function to create an object to simulate observations of a given type.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > createObservationSimulators (observation_models::SortedObservationSettingsMap observationSettingsMap, const simulation_setup::NamedBodyMap &bodyMap)
Function to create a map of object to simulate observations (one object for each type of observable).
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > createObservationSimulators (observation_models::ObservationSettingsMap observationSettingsMap, const simulation_setup::NamedBodyMap &bodyMap)
Function to create a map of object to simulate observations (one object for each type of observable).
std::vector< std::shared_ptr< ObservationViabilityCalculator > > createObservationViabilityCalculators (const simulation_setup::NamedBodyMap &bodyMap, const LinkEnds linkEnds, const ObservableType observationType, const std::vector< std::shared_ptr< ObservationViabilitySettings > > &observationViabilitySettings)
Function to create an list of obervation viability conditions for a single set of link ends.
std::map< LinkEnds, std::vector< std::shared_ptr< ObservationViabilityCalculator > > > createObservationViabilityCalculators (const simulation_setup::NamedBodyMap &bodyMap, const std::vector< LinkEnds > linkEnds, const ObservableType observationType, const std::vector< std::shared_ptr< ObservationViabilitySettings > > &observationViabilitySettings)
Function to create an list of obervation viability conditions for a number of sets of link ends, for a single observable type.
PerObservableObservationViabilityCalculatorList createObservationViabilityCalculators (const simulation_setup::NamedBodyMap &bodyMap, const std::map< ObservableType, std::vector< LinkEnds > > linkEndsPerObservable, const std::vector< std::shared_ptr< ObservationViabilitySettings > > &observationViabilitySettings)
Function to create a list of obervation viability conditions for any number of sets of link ends and observable types.
std::shared_ptr< OccultationCalculator > createOccultationCalculator (const simulation_setup::NamedBodyMap &bodyMap, const LinkEnds linkEnds, const ObservableType observationType, const std::shared_ptr< ObservationViabilitySettings > observationViabilitySettings)
Function to create an object to check if a body occultation condition is met for an observation.
template<typename ObservationScalarType = double, typename TimeType = double>
std::shared_ptr< DopplerProperTimeRateInterface > createOneWayDopplerProperTimeCalculator (std::shared_ptr< DopplerProperTimeRateSettings > properTimeRateSettings, const LinkEnds &linkEnds, const simulation_setup::NamedBodyMap &bodyMap, const LinkEndType linkEndForCalculator)
Function to create the proper time rate calculator for use in one-way Doppler.
template<typename TimeType = double, typename StateScalarType = double>
std::shared_ptr< ephemerides::Ephemeris > createReferencePointEphemeris (const std::shared_ptr< simulation_setup::Body > bodyWithReferencePoint, const std::shared_ptr< ephemerides::RotationalEphemeris > bodyRotationModel, const std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType &) > referencePointStateFunction)
Function to create an ephemeris for a reference point on a body.
template<int ObservationSize = Eigen::Dynamic, typename ObservationScalarType = double, typename TimeType = double>
std::map< LinkEnds, std::shared_ptr< ObservationBias< ObservationSize > > > extractObservationBiasList (std::map< LinkEnds, std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > > observationModels)
Function to extract a list of observtion bias models from a list of observation models.
ObservationViabilitySettingsList filterObservationViabilitySettings (const ObservationViabilitySettingsList &observationViabilitySettings, const LinkEnds &linkEnds)
Function to filter list of observationViabilitySettings, so that only those relevant for single set of link ends are retained.
template<typename ObservationScalarType = double>
ObservationScalarType getDefaultLightTimeTolerance ()
Function to retrieve the default tolerance for the light-time equation solution.
template<>
double getDefaultLightTimeTolerance< double > ()
Function to retrieve the default tolerance for the light-time equation solution.
template<>
long double getDefaultLightTimeTolerance< long double > ()
Function to retrieve the default tolerance for the light-time equation solution.
Eigen::VectorXd getIdenticallyAndIndependentlyDistributedNoise (const std::function< double(const double) > noiseFunction, const int observationSize, const double evaluationTime)
template<typename TimeType = double, typename StateScalarType = double>
std::function< Eigen::Matrix< StateScalarType, 6, 1 > const TimeType &) > getLinkEndCompleteEphemerisFunction (const std::shared_ptr< simulation_setup::Body > bodyWithLinkEnd, const std::pair< std::string, std::string > &linkEndId)
Function to retrieve a state function for a link end (either a body center of mass or ground station).
template<typename TimeType = double, typename StateScalarType = double>
std::function< Eigen::Matrix< StateScalarType, 6, 1 > const TimeType) > getLinkEndCompleteEphemerisFunction (const std::pair< std::string, std::string > linkEndId, const simulation_setup::NamedBodyMap &bodyMap)
Function to create a state function of a link end, expressed in base frame.
std::vector< int > getLinkEndIndicesForLinkEndTypeAtObservable (const ObservableType observableType, const LinkEndType linkEndType, const int numberOfLinkEnds)
Function to get the indices in link end times/states for a given link end type and observable type.
std::vector< std::pair< int, int > > getLinkEndIndicesForObservationViability (const LinkEnds &linkEnds, const ObservableType observableType, const LinkEndId linkEndToCheck)
Function to retrieve the link end indices in link end states/times that are to be used in viability calculation.
std::string getLinkEndsString (const LinkEnds linkEnds)
Function to get a string identifier for a set of link ends.
std::string getLinkEndTypeString (const LinkEndType linkEndType)
Function to get a string identifier for a link end type.
std::vector< int > getNWayLinkEndIndicesFromLinkEndId (const LinkEndId &linkEndid, const LinkEnds &linkEnds)
Function to get the list of indices in link-end list for n-way observables that matches a given link end id.
std::vector< int > getNWayLinkEndIndicesFromLinkEndId (const std::vector< LinkEndType > &linkEndTypes, const LinkEnds &linkEnds)
Function to get the list of indices in link-end list for n-way observables that matches a list of link-end types.
LinkEndType getNWayLinkEnumFromIndex (const int linkEndIndex, const int numberOfLinkEnds)
Function to get the link end type enum of a link end in n-way observable from link index.
int getNWayLinkIndexFromLinkEndType (const LinkEndType linkEndType, const int numberOfLinkEnds)
Function to get the link end index (0=transmitter, numberOfLinkEnds-1=receiver) of a link end in n-way observable.
std::vector< LinkEndType > getNWayLinkIndicesFromLinkEndId (const LinkEndId &linkEndid, const LinkEnds &linkEnds)
Function to get the list of link end types in link-end list for n-way observables that match a given link end id.
std::string getObservableName (const ObservableType observableType, const int numberOfLinkEnds)
Function to get the name (string) associated with a given observable type.
int getObservableSize (const ObservableType observableType)
Function to get the size of an observable of a given type.
ObservableType getObservableType (const std::string &observableName)
Function to get the observable type.ssociated with the name (string) of observable.
template<int ObservationSize>
ObservationBiasTypes getObservationBiasType (const std::shared_ptr< ObservationBias< ObservationSize > > biasObject)
Function to retrieve the type of an observation bias.
template<typename ObservationScalarType = double, typename TimeType = double>
double getSizeOneObservationAtDoublePrecision (std::function< Eigen::Matrix< ObservationScalarType, 1, 1 >(const TimeType, const observation_models::LinkEndType) > observationFunction, const double currentTime, const LinkEndType referenceLinkEnd)
Function to compute an observation of size 1 at double precision, with double precision input.
template<typename ObservationScalarType = double, typename TimeType = double>
std::function< double(const double, const observation_models::LinkEndType) > getSizeOneObservationFunctionAtDoublePrecision (std::function< Eigen::Matrix< ObservationScalarType, 1, 1 >(const TimeType, const observation_models::LinkEndType) > observationFunction)
Function to generate a function that computes a size 1 observation at double precision, from a templated observation function.
template<typename ObservationScalarType = double, typename TimeType = double>
std::function< double(const double, const observation_models::LinkEndType) > getSizeOneObservationFunctionAtDoublePrecisionFromObservationModel (const std::shared_ptr< ObservationModel< 1, ObservationScalarType, TimeType > > observationModel)
Function to generate a function that computes an observation at double precision from an ObservationModel.
template<typename ObservationScalarType = double, typename TimeType = double>
std::function< Eigen::Matrix< ObservationScalarType, 1, 1 > const TimeType, const observation_models::LinkEndType) > getSizeOneObservationFunctionFromObservationModel (const std::shared_ptr< ObservationModel< 1, ObservationScalarType, TimeType > > observationModel)
Function to generate a function that computes an observation from an ObservationModel.
bool isObservationViable (const std::vector< Eigen::Vector6d > &states, const std::vector< double > &times, const LinkEnds &linkEnds, const std::map< LinkEnds, std::vector< std::shared_ptr< ObservationViabilityCalculator > > > &viabilityCalculators)
Function to check whether an observation is viable.
bool isObservationViable (const std::vector< Eigen::Vector6d > &states, const std::vector< double > &times, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > &viabilityCalculators)
Function to check whether an observation is viable.
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double>
void performObservationParameterEstimationClosure (std::shared_ptr< ObservationSimulator< ObservationSize, ObservationScalarType, TimeType > > observationSimulator, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate)
Function to perform the closure between observation models and estimated parameters.
template<int ObservationSize = 1>
void performObservationParameterEstimationClosureForSingleModelSet (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, const std::shared_ptr< ObservationBias< ObservationSize > > observationBias, const LinkEnds linkEnds, const ObservableType observableType)
Function to perform the closure a single observation bias and a single estimated bias parameter.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::vector< TimeType > > > > removeLinkIdFromSimulatedObservations (std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulatedObservations)
Function to remove link id from the simulated observations.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulateObservations (const std::map< ObservableType, std::map< LinkEnds, std::pair< std::vector< TimeType >, LinkEndType > > > &observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > &observationSimulators)
Function to simulate observations from set of observables and link and sets and simple vectors of requested times.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulateObservations (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > &observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > &observationSimulators, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList=PerObservableObservationViabilityCalculatorList())
Function to simulate observations from set of observables and link and sets.
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double>
std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::vector< TimeType > > simulateObservationsWithCheck (const std::vector< TimeType > &observationTimes, const std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > observationModel, const LinkEndType linkEndAssociatedWithTime, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > linkViabilityCalculators=std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to simulate observables, checking whether they are viable according to settings passed to this function.
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double>
std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > simulateObservationsWithCheckAndLinkEndIdOutput (const std::vector< TimeType > &observationTimes, const std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > observationModel, const LinkEndType linkEndAssociatedWithTime, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > linkViabilityCalculators=std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to simulate observables, checking whether they are viable according to settings passed to this function.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > &observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > &observationSimulators, const std::map< ObservableType, std::map< LinkEnds, std::function< Eigen::VectorXd(const double) > > > &noiseFunctions, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList=PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables and link and sets.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > &observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > &observationSimulators, const std::map< ObservableType, std::map< LinkEnds, std::function< double(const double) > > > &noiseFunctions, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList=PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables and link and sets.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > &observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > &observationSimulators, const std::map< ObservableType, std::function< Eigen::VectorXd(const double) > > &noiseFunctions, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList=PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables and link and sets.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > &observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > &observationSimulators, const std::map< ObservableType, std::function< double(const double) > > &noiseFunctions, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList=PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables and link and sets.
template<typename ObservationScalarType = double, typename TimeType = double>
std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > &observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > &observationSimulators, const std::function< double(const double) > &noiseFunction, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList=PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables and link and sets.
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double>
std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, bool > simulateObservationWithCheck (const TimeType &observationTime, const std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > observationModel, const LinkEndType linkEndAssociatedWithTime, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > linkViabilityCalculators=std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to simulate an observable, checking whether it is viable according to settings passed to this function.
template<typename ObservationScalarType = double, typename TimeType = double, int ObservationSize = 1>
std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > simulateSingleObservationSet (const std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > observationsToSimulate, const std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > observationModel, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > currentObservationViabilityCalculators=std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to compute observations at times defined by settings object using a given observation model.
template<typename ObservationScalarType = double, typename TimeType = double, int ObservationSize = 1>
std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > simulateSingleObservationSet (const std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > observationsToSimulate, const std::shared_ptr< ObservationSimulator< ObservationSize, ObservationScalarType, TimeType > > observationSimulator, const LinkEnds &linkEnds, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > currentObservationViabilityCalculators=std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to simulate observations for single observable and single set of link ends.
Typedef Documentation
LightTimeCorrectionFunction
typedef std::function< double(const Eigen::Vector6d &, const Eigen::Vector6d &, const double, const double) > tudat::observation_models::LightTimeCorrectionFunction
Definition at line 43 of file lightTimeSolution.h.
LinkEndId
typedef std::pair< std::string, std::string > tudat::observation_models::LinkEndId
Definition at line 41 of file linkTypeDefs.h.
LinkEnds
typedef std::map< LinkEndType, LinkEndId > tudat::observation_models::LinkEnds
Definition at line 44 of file linkTypeDefs.h.
PerObservableObservationViabilityCalculatorList
typedef std::map< ObservableType, std::map< LinkEnds, std::vector< std::shared_ptr< ObservationViabilityCalculator > > > > tudat::observation_models::PerObservableObservationViabilityCalculatorList
Definition at line 361 of file observationViabilityCalculator.h.
PerLinkEndsObservationViabilityCalculatorList
typedef std::map< LinkEnds, std::vector< std::shared_ptr< ObservationViabilityCalculator > > > tudat::observation_models::PerLinkEndsObservationViabilityCalculatorList
Definition at line 365 of file observationViabilityCalculator.h.
ObservationViabilitySettingsList
typedef std::vector< std::shared_ptr< observation_models::ObservationViabilitySettings > > tudat::observation_models::ObservationViabilitySettingsList
Definition at line 368 of file observationViabilityCalculator.h.
LightTimeCorrectionSettingsMap
typedef std::map< LinkEnds, std::vector< std::shared_ptr< LightTimeCorrectionSettings > > > tudat::observation_models::LightTimeCorrectionSettingsMap
Definition at line 72 of file createLightTimeCorrection.h.
SortedObservationSettingsMap
typedef std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSettings > > > tudat::observation_models::SortedObservationSettingsMap
Typedef of list of observation models per obserable type and link ends: note that ObservableType key must be consistent with contents of ObservationSettings pointers. The ObservationSettingsMap may be used as well, which contains the same type of information. This typedef, however, has some advantages in terms of book-keeping when creating observation models.
Definition at line 558 of file createObservationModel.h.
ObservationSettingsMap
typedef std::multimap< LinkEnds, std::shared_ptr< ObservationSettings > > tudat::observation_models::ObservationSettingsMap
Typedef of list of observation models per link ends. Multiple observation models for a single set of link ends are allowed, since this typedef represents a multimap.
Definition at line 562 of file createObservationModel.h.
Enumeration Type Documentation
LinkEndType
enum tudat::observation_models::LinkEndType
Enum defining different roles that a given link end can play in an observation model.
Enumerator
unidentified_link_end
transmitter
reflector1
reflector2
reflector3
reflector4
receiver
observed_body
Definition at line 28 of file linkTypeDefs.h.
LightTimeCorrectionType
enum tudat::observation_models::LightTimeCorrectionType
Enumerator
first_order_relativistic
function_wrapper_light_time_correction
Definition at line 24 of file lightTimeCorrection.h.
ObservableType
enum tudat::observation_models::ObservableType
Enumerator
one_way_range
angular_position
position_observable
one_way_doppler
one_way_differenced_range
n_way_range
two_way_doppler
Definition at line 26 of file observableTypes.h.
ObservationBiasTypes
enum tudat::observation_models::ObservationBiasTypes
Enumerator
multiple_observation_biases
constant_absolute_bias
constant_relative_bias
arc_wise_constant_absolute_bias
arc_wise_constant_relative_bias
Definition at line 37 of file observationBias.h.
ObservationViabilityType
enum tudat::observation_models::ObservationViabilityType
Enum defining possible checks which can be performed for observation viability, the string and double parameter shown in the comments are used to define it when making an ObservationViabilitySettings object
Enumerator
minimum_elevation_angle
body_avoidance_angle
body_occultation
Definition at line 285 of file observationViabilityCalculator.h.
DopplerProperTimeRateType
enum tudat::observation_models::DopplerProperTimeRateType
Enumerator
custom_doppler_proper_time_rate
direct_first_order_doppler_proper_time_rate
Definition at line 239 of file createObservationModel.h.
Function Documentation
getDefaultLightTimeTolerance< double >()
template<> double tudat::observation_models::getDefaultLightTimeTolerance< double > ()
Definition at line 24 of file lightTimeSolution.cpp.
getDefaultLightTimeTolerance< long double >()
template<> long double tudat::observation_models::getDefaultLightTimeTolerance< long double > ()
Definition at line 31 of file lightTimeSolution.cpp.
getDefaultLightTimeTolerance()
template<typename ObservationScalarType = double> ObservationScalarType tudat::observation_models::getDefaultLightTimeTolerance ()
Function to retrieve the default tolerance for the light-time equation solution. This tolerance denotes the difference between two subsequent light time solutions (in s) that is deemed acceptable for convergence/
Returns
Default light-time tolerance for given template arguments.
getLinkEndTypeString()
std::string tudat::observation_models::getLinkEndTypeString (const LinkEndType linkEndType)
Function to get a string identifier for a link end type
Parameters
linkEndType Enum identifier for a link end type
Returns
String identifier for a link end type
Definition at line 20 of file linkTypeDefs.cpp.
References observed_body, receiver, reflector1, reflector2, reflector3, reflector4, and transmitter.
Referenced by getLinkEndsString().
getLinkEndsString()
std::string tudat::observation_models::getLinkEndsString (const LinkEnds linkEnds)
Function to get a string identifier for a set of link ends
Parameters
linkEnds Link ends for which string identifier is to be created.
Returns
String identifier for a link ends
Definition at line 55 of file linkTypeDefs.cpp.
References getLinkEndTypeString().
Referenced by tudat::unit_tests::executeEarthOrbiterParameterEstimation(), tudat::estimatable_parameters::ConstantObservationBiasParameter::getParameterDescription(), and tudat::estimatable_parameters::ArcWiseObservationBiasParameter::getParameterDescription().
getNWayLinkIndexFromLinkEndType()
int tudat::observation_models::getNWayLinkIndexFromLinkEndType (const LinkEndType linkEndType, const int numberOfLinkEnds)
Function to get the link end index (0=transmitter, numberOfLinkEnds-1=receiver) of a link end in n-way observable
Parameters
linkEndType Link end type for which index is to be retrieved
numberOfLinkEnds Total number of link ends in n-way observable
Returns
Requested link end index
Definition at line 80 of file linkTypeDefs.cpp.
References receiver, reflector1, and transmitter.
Referenced by tudat::observation_partials::NWayRangePartial::calculatePartial(), tudat::observation_partials::TwoWayDopplerPartial::calculatePartial(), tudat::observation_models::NWayRangeObservationModel< ObservationScalarType, TimeType >::computeIdealObservationsWithLinkEndData(), getLinkEndIndicesForLinkEndTypeAtObservable(), getNWayLinkEndIndicesFromLinkEndId(), tudat::observation_partials::NWayRangeScaling::update(), and tudat::observation_partials::TwoWayDopplerScaling::update().
getNWayLinkEnumFromIndex()
LinkEndType tudat::observation_models::getNWayLinkEnumFromIndex (const int linkEndIndex, const int numberOfLinkEnds)
Function to get the link end type enum of a link end in n-way observable from link index (0=transmitter, numberOfLinkEnds-1=receiver)
Parameters
linkEndIndex Link end index for which type is to be retrieved
numberOfLinkEnds Total number of link ends in n-way observable
Returns
Requested link end type
Definition at line 104 of file linkTypeDefs.cpp.
References receiver, reflector1, and transmitter.
Referenced by tudat::observation_partials::createNWayRangePartials(), and tudat::observation_partials::createTwoWayDopplerPartials().
getNWayLinkEndIndicesFromLinkEndId() [1/2]
std::vector< int > tudat::observation_models::getNWayLinkEndIndicesFromLinkEndId (const LinkEndId & linkEndid, const LinkEnds & linkEnds)
Function to get the list of indices in link-end list for n-way observables that match a given link end id.
Function to get the list of indices in link-end list for n-way observables that match a given link end id.
Parameters
linkEndid Link end id for which the link-end indices in linkEnds are to be determined
linkEnds N-way link ends
Returns
List of indices (transmitter = 0, receiver = linkEnds.size() - 1) at which linkEndid occurs in linkEnds.
Definition at line 134 of file linkTypeDefs.cpp.
References getNWayLinkIndicesFromLinkEndId().
Referenced by getLinkEndIndicesForObservationViability().
getNWayLinkEndIndicesFromLinkEndId() [2/2]
std::vector< int > tudat::observation_models::getNWayLinkEndIndicesFromLinkEndId (const std::vector< LinkEndType > & linkEndTypes, const LinkEnds & linkEnds)
Function to get the list of indices in link-end list for n-way observables that match a list of link-end types.
Function to get the list of indices in link-end list for n-way observables that match a list of link-end types.
Parameters
linkEndTypes List of link end types for which the link-end indices in linkEnds are to be determined
linkEnds N-way link ends
Returns
List of indices (transmitter = 0, receiver = linkEnds.size() - 1) at which linkEndTypes occurs in linkEnds.
Definition at line 142 of file linkTypeDefs.cpp.
References getNWayLinkIndexFromLinkEndType().
getNWayLinkIndicesFromLinkEndId()
std::vector< LinkEndType > tudat::observation_models::getNWayLinkIndicesFromLinkEndId (const LinkEndId & linkEndid, const LinkEnds & linkEnds)
Function to get the list of link end types in link-end list for n-way observables that match a given link end id.
Parameters
linkEndid Link end id for which the link-end indices in linkEnds are to be determined
linkEnds N-way link ends
Returns
List of link end type at which linkEndid occurs in linkEnds.
Definition at line 153 of file linkTypeDefs.cpp.
Referenced by getNWayLinkEndIndicesFromLinkEndId().
getObservableName()
std::string tudat::observation_models::getObservableName (const ObservableType observableType, const int numberOfLinkEnds)
Function to get the name (string) associated with a given observable type.
Parameters
observableType Type of observable.
numberOfLinkEnds Number of link ends in observable
Returns
Name of observable
Definition at line 21 of file observableTypes.cpp.
References angular_position, n_way_range, one_way_differenced_range, one_way_doppler, one_way_range, position_observable, and two_way_doppler.
Referenced by tudat::estimatable_parameters::ConstantObservationBiasParameter::getParameterDescription(), and tudat::estimatable_parameters::ArcWiseObservationBiasParameter::getParameterDescription().
getObservableType()
ObservableType tudat::observation_models::getObservableType (const std::string & observableName)
Function to get the observable type.ssociated with the name (string) of observable.
Parameters
observableName of observable
Returns
Type of observable.
Definition at line 84 of file observableTypes.cpp.
References angular_position, one_way_differenced_range, one_way_doppler, one_way_range, position_observable, and two_way_doppler.
getObservableSize()
int tudat::observation_models::getObservableSize (const ObservableType observableType)
Function to get the size of an observable of a given type.
Parameters
observableType Type of observable.
Returns
Size of observable.
Definition at line 124 of file observableTypes.cpp.
References angular_position, n_way_range, one_way_differenced_range, one_way_doppler, one_way_range, position_observable, and two_way_doppler.
Referenced by tudat::estimatable_parameters::ArcWiseObservationBiasParameter::ArcWiseObservationBiasParameter(), createObservationSimulators(), tudat::simulation_setup::getConcatenatedGroundStationIndex(), tudat::simulation_setup::getConcatenatedObservableTypes(), tudat::simulation_setup::getConcatenatedTimeVector(), tudat::estimatable_parameters::ConstantObservationBiasParameter::getParameterSize(), and simulateObservationsWithNoise().
getLinkEndIndicesForLinkEndTypeAtObservable()
std::vector< int > tudat::observation_models::getLinkEndIndicesForLinkEndTypeAtObservable (const ObservableType observableType, const LinkEndType linkEndType, const int numberOfLinkEnds)
Function to get the indices in link end times/states for a given link end type and observable type
Parameters
observableType Type of observable for which link end indices are to be returned
linkEndType Type of link end for which link end indices are to be returned
numberOfLinkEnds Number of link ends in observable
Returns
Indices in link end times/states for given link end type and observable type
Definition at line 159 of file observableTypes.cpp.
References angular_position, getNWayLinkIndexFromLinkEndType(), n_way_range, observed_body, one_way_differenced_range, one_way_doppler, one_way_range, position_observable, receiver, reflector1, transmitter, and two_way_doppler.
Referenced by createObservationBiasCalculator(), and tudat::simulation_setup::createVectorParameterToEstimate().
getObservationBiasType()
template<int ObservationSize> ObservationBiasTypes tudat::observation_models::getObservationBiasType (const std::shared_ptr< ObservationBias< ObservationSize > > biasObject)
Function to retrieve the type of an observation bias.
Parameters
biasObject Bias for which the type is to be determined
Returns
Bias type for biasObject.
Definition at line 642 of file observationBias.h.
References arc_wise_constant_absolute_bias, arc_wise_constant_relative_bias, constant_absolute_bias, constant_relative_bias, and multiple_observation_biases.
Referenced by performObservationParameterEstimationClosureForSingleModelSet().
getSizeOneObservationAtDoublePrecision()
template<typename ObservationScalarType = double, typename TimeType = double> double tudat::observation_models::getSizeOneObservationAtDoublePrecision (std::function< Eigen::Matrix< ObservationScalarType, 1, 1 >(const TimeType, const observation_models::LinkEndType) > observationFunction, const double currentTime, const LinkEndType referenceLinkEnd)
Function to compute an observation at double precision, with double precision input, from an observation function templated at state scalar and time type.
Parameters
observationFunction Function that computes the observation as a function of observation time and reference link end time, templated by the state and time scalar type.
currentTime Time at which to evaluate the observation function
referenceLinkEnd Reference link end for the observation
Returns
Observation computed by observationFunction, cast to double precision, with input time at double precision
Definition at line 311 of file observationModel.h.
getSizeOneObservationFunctionAtDoublePrecision()
template<typename ObservationScalarType = double, typename TimeType = double> std::function< double(const double, const observation_models::LinkEndType) > tudat::observation_models::getSizeOneObservationFunctionAtDoublePrecision (std::function< Eigen::Matrix< ObservationScalarType, 1, 1 >(const TimeType, const observation_models::LinkEndType) > observationFunction)
Function to generate a function that computes a size 1 observation at double precision, from a templated observation function.
Parameters
observationFunction Function that computes the observation as a function of observation time and reference link end time, templated by the state and time scalar type.
Returns
Function that computes the observation as a function of observation time and reference link end time.
Definition at line 326 of file observationModel.h.
Referenced by getSizeOneObservationFunctionAtDoublePrecisionFromObservationModel().
getSizeOneObservationFunctionFromObservationModel()
template<typename ObservationScalarType = double, typename TimeType = double> std::function< Eigen::Matrix< ObservationScalarType, 1, 1 > const TimeType, const observation_models::LinkEndType) > tudat::observation_models::getSizeOneObservationFunctionFromObservationModel (const std::shared_ptr< ObservationModel< 1, ObservationScalarType, TimeType > > observationModel)
Function to generate a function that produces an observation, only applicable for observation models of size one. This function uses std::bind to link the computeObservations function of the observationModel to the output of this function.
Parameters
observationModel Observation model for which the observation function is to be returned.
Returns
Function that computes the observation as a function of observation time and reference link end time.
Definition at line 343 of file observationModel.h.
Referenced by getSizeOneObservationFunctionAtDoublePrecisionFromObservationModel().
getSizeOneObservationFunctionAtDoublePrecisionFromObservationModel()
template<typename ObservationScalarType = double, typename TimeType = double> std::function< double(const double, const observation_models::LinkEndType) > tudat::observation_models::getSizeOneObservationFunctionAtDoublePrecisionFromObservationModel (const std::shared_ptr< ObservationModel< 1, ObservationScalarType, TimeType > > observationModel)
Function to generate a function that computes an observation at double precision, only applicable for observation models of size one. This function uses std::bind to link the computeObservations function of the observationModel to the output of this function, casting in/and output to double precisiono if needed.
Parameters
observationModel Observation model for which the observation function is to be returned.
Returns
Function that computes the observation as a function of observation time and reference link end time.
Definition at line 359 of file observationModel.h.
References getSizeOneObservationFunctionAtDoublePrecision(), and getSizeOneObservationFunctionFromObservationModel().
Referenced by tudat::observation_partials::createTwoWayDopplerPartials().
extractObservationBiasList()
template<int ObservationSize = Eigen::Dynamic, typename ObservationScalarType = double, typename TimeType = double> std::map< LinkEnds, std::shared_ptr< ObservationBias< ObservationSize > > > tudat::observation_models::extractObservationBiasList (std::map< LinkEnds, std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > > observationModels)
Function to extract a list of observtion bias models from a list of observation models. Function iterates over input map of observationModels, extracts the bias from it and adds it to the list of bias objects if it is not nullptr.
Parameters
observationModels List of observation models (per LinkEnds) from which the bias objects are to be extracted
Returns
List of observation bias objects (per LinkEnds), as extracted from observationModels (nullptr bias objects not added to list).
Definition at line 375 of file observationModel.h.
Referenced by performObservationParameterEstimationClosure().
simulateObservationWithCheck()
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double> std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, bool > tudat::observation_models::simulateObservationWithCheck (const TimeType & observationTime, const std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > observationModel, const LinkEndType linkEndAssociatedWithTime, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > linkViabilityCalculators = std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to simulate an observable, checking whether it is viable according to settings passed to this function (if viability calculators are passed to this function).
Parameters
observationTime Time at which observable is to be computed
observationModel Model used to compute observable
linkEndAssociatedWithTime Model Reference link end for observable
linkViabilityCalculators List of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Observation at given time.
Definition at line 39 of file observationSimulator.h.
References isObservationViable().
simulateObservationsWithCheck()
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double> std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::vector< TimeType > > tudat::observation_models::simulateObservationsWithCheck (const std::vector< TimeType > & observationTimes, const std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > observationModel, const LinkEndType linkEndAssociatedWithTime, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > linkViabilityCalculators = std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to simulate observables, checking whether they are viable according to settings passed to this function (if viability calculators are passed to this function).
Parameters
observationTimes Times at which observables are to be computed
observationModel Model used to compute observables
linkEndAssociatedWithTime Model Reference link end for observables
linkViabilityCalculators List of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Observations at given time (concatenated in an Eigen vector) and associated times.
Definition at line 75 of file observationSimulator.h.
References tudat::utilities::createConcatenatedEigenMatrixFromMapValues(), and tudat::utilities::createVectorFromMapKeys().
Referenced by simulateObservationsWithCheckAndLinkEndIdOutput().
simulateObservationsWithCheckAndLinkEndIdOutput()
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double> std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > tudat::observation_models::simulateObservationsWithCheckAndLinkEndIdOutput (const std::vector< TimeType > & observationTimes, const std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > observationModel, const LinkEndType linkEndAssociatedWithTime, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > linkViabilityCalculators = std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to simulate observables, checking whether they are viable according to settings passed to this function (if viability calculators are passed to this function).
Parameters
observationTimes Times at which observables are to be computed
observationModel Model used to compute observables
linkEndAssociatedWithTime Model Reference link end for observables
linkViabilityCalculators List of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Observations at given times (concatenated in an Eigen vector), with associated times and reference link end.
Definition at line 116 of file observationSimulator.h.
References simulateObservationsWithCheck().
Referenced by simulateSingleObservationSet().
isObservationViable() [1/2]
bool tudat::observation_models::isObservationViable (const std::vector< Eigen::Vector6d > & states, const std::vector< double > & times, const LinkEnds & linkEnds, const std::map< LinkEnds, std::vector< std::shared_ptr< ObservationViabilityCalculator > > > & viabilityCalculators)
Function to check whether an observation is viable. The input from which the viability of an observation is calculated are a vector of times and states of the link ends involved in the observation.
Parameters
times Vector of times of the link ends involved in the observation, in the order as provided by the function computeObservationsAndLinkEndData of the associated ObservationModel.
states Vector of states of the link ends involved in the observation, in the order as provided by the function computeObservationsAndLinkEndData of the associated ObservationModel.
linkEnds Link ends for current observation
viabilityCalculators List of viability calculators, for each set of link ends (function retrieves vector for linkEnds input.
Returns
True if observation is viable, false if not.
Definition at line 20 of file observationViabilityCalculator.cpp.
Referenced by simulateObservationWithCheck().
isObservationViable() [2/2]
bool tudat::observation_models::isObservationViable (const std::vector< Eigen::Vector6d > & states, const std::vector< double > & times, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > & viabilityCalculators)
Function to check whether an observation is viable. The input from which the viability of an observation is calculated are a vector of times and states of the link ends involved in the observation.
Parameters
times Vector of times of the link ends involved in the observation, in the order as provided by the function computeObservationsAndLinkEndData of the associated ObservationModel.
states Vector of states of the link ends involved in the observation, in the order as provided by the function computeObservationsAndLinkEndData of the associated ObservationModel.
viabilityCalculators List of viability calculators
Returns
True if observation is viable, false if not.
Definition at line 35 of file observationViabilityCalculator.cpp.
calculateLineOfSightVelocityAsCFraction()
template<typename ObservationScalarType = double> ObservationScalarType tudat::observation_models::calculateLineOfSightVelocityAsCFraction (const Eigen::Matrix< ObservationScalarType, 3, 1 > & lineOfSightUnitVector, const Eigen::Matrix< ObservationScalarType, 3, 1 > & velocityVector)
Function to compute the component of a (velocity) vector projected along a unit vector, divided by speed of light.
Parameters
lineOfSightUnitVector Unit vector along which velocityVector is to be projected
velocityVector Vector for which component along lineOfSightUnitVector is to be computed
Returns
The component of a (velocity) vector projected along a unit vector, divided by speed of light.
Definition at line 42 of file oneWayDopplerObservationModel.h.
calculateLineOfSightVelocityAsCFractionFromTransmitterStateFunction()
template<typename ObservationScalarType = double, typename TimeType = double> ObservationScalarType tudat::observation_models::calculateLineOfSightVelocityAsCFractionFromTransmitterStateFunction (const Eigen::Matrix< ObservationScalarType, 3, 1 > & receiverPosition, const std::function< Eigen::Matrix< ObservationScalarType, 6, 1 >(const double) > & transmitterStateFunction, const TimeType currentTime)
Function to compute component of transmitter velocity projected along line-of-sight vector, divided by speed of light, from the receiver position and transmitter state function. The unit vector is computed in the direction from the transmitter to the receiver
Parameters
receiverPosition Cartesian position of receiver
transmitterStateFunction Function returning the Cartesian state of the transmitter.
currentTime Time at which transmitterStateFunction is to be evaluated.
Returns
Component of transmitter velocity projected along line-of-sight vector to receiver, divided by speed of light.
Definition at line 60 of file oneWayDopplerObservationModel.h.
calculateLineOfSightVelocityAsCFractionFromReceiverStateFunction()
template<typename ObservationScalarType = double, typename TimeType = double> ObservationScalarType tudat::observation_models::calculateLineOfSightVelocityAsCFractionFromReceiverStateFunction (const std::function< Eigen::Matrix< ObservationScalarType, 6, 1 >(const double) > & receiverStateFunction, const Eigen::Matrix< ObservationScalarType, 3, 1 > & transmitterPosition, const TimeType currentTime)
Function to compute component of transmitter velocity projected along line-of-sight vector, divided by speed of light, from the receiver state function and transmitter position. The unit vector is computed in the direction from the transmitter to the receiver
Parameters
receiverStateFunction Function returning the Cartesian state of the receiver.
transmitterPosition Cartesian position of transmitter
currentTime Time at which transmitterStateFunction is to be evaluated.
Returns
Component of transmitter velocity projected along line-of-sight vector to receiver, divided by speed of light.
Definition at line 81 of file oneWayDopplerObservationModel.h.
computeOneWayFirstOrderDopplerTaylorSeriesExpansion()
template<typename ObservationScalarType = double> ObservationScalarType tudat::observation_models::computeOneWayFirstOrderDopplerTaylorSeriesExpansion (Eigen::Matrix< ObservationScalarType, 6, 1 > & transmitterState, Eigen::Matrix< ObservationScalarType, 6, 1 > & receiverState, Eigen::Matrix< ObservationScalarType, 1, 3 > & lightTimeWrtTransmitterPositionPartial, Eigen::Matrix< ObservationScalarType, 1, 3 > & lightTimeWrtReceiverPositionPartial, const int taylorSeriesOrder)
Function to compute first-order (radial) Doppler term from a Taylor series expansion. The function computes the (dt1/dt2 -1) term, with t2 the coordinate reception time and t1 the coordinate transmission time of the signal. Light time corrections are not included in this function. The Taylor series of the denominator of dt1/dt2 is used in the calculation, to an order that is provided as input.
Parameters
transmitterState Cartesian state of the transmitter at t1
receiverState Cartesian state of the receiver at t2
lightTimeWrtTransmitterPositionPartial Light time partial w.r.t. transmitter position
lightTimeWrtReceiverPositionPartial Light time partial w.r.t. receiver position
taylorSeriesOrder Order to which Taylor series is to be expanded
Returns
First-order Doppler effect for electromagnetic signal transmission from transmitter to receiver as: (dt1/dt2 -1) with t2 the coordinate reception time and t1 the coordinate transmission time of the signal.
Definition at line 106 of file oneWayDopplerObservationModel.h.
Referenced by tudat::observation_models::OneWayDopplerObservationModel< ObservationScalarType, TimeType >::computeIdealObservationsWithLinkEndData().
computeDopplerProperTimeInfluenceTaylorSeriesExpansion()
template<typename ObservationScalarType = double> ObservationScalarType tudat::observation_models::computeDopplerProperTimeInfluenceTaylorSeriesExpansion (const ObservationScalarType transmitterProperTimeRateDifference, const ObservationScalarType receiverProperTimeRateDifference, const int taylorSeriesOrder)
Function to compute proper time contribution one-way Doppler term from a Taylor series expansion.
Parameters
transmitterProperTimeRateDifference Derivative of deviation between proper and coordinate time (Delta - t) w.r.t. coordinate time t at transmitter
receiverProperTimeRateDifference Derivative of deviation between proper and coordinate time (Delta - t) w.r.t. coordinate time t at receiver
taylorSeriesOrder Order to which Taylor series is to be expanded
Definition at line 146 of file oneWayDopplerObservationModel.h.
Referenced by tudat::observation_models::OneWayDopplerObservationModel< ObservationScalarType, TimeType >::computeIdealObservationsWithLinkEndData().
getIdenticallyAndIndependentlyDistributedNoise()
Eigen::VectorXd tudat::observation_models::getIdenticallyAndIndependentlyDistributedNoise (const std::function< double(const double) > noiseFunction, const int observationSize, const double evaluationTime)
Definition at line 9 of file simulateObservations.cpp.
Referenced by simulateObservationsWithNoise().
simulateSingleObservationSet() [1/2]
template<typename ObservationScalarType = double, typename TimeType = double, int ObservationSize = 1> std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > tudat::observation_models::simulateSingleObservationSet (const std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > observationsToSimulate, const std::shared_ptr< ObservationModel< ObservationSize, ObservationScalarType, TimeType > > observationModel, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > currentObservationViabilityCalculators = std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to compute observations at times defined by settings object using a given observation model
Parameters
observationsToSimulate Object that computes/defines settings for observation times/reference link end
observationModel Observation model that is to be used to compute observations
currentObservationViabilityCalculators List of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Pair of observable values and observation time (with associated reference link end)
Definition at line 72 of file simulateObservations.h.
References simulateObservationsWithCheckAndLinkEndIdOutput().
simulateSingleObservationSet() [2/2]
template<typename ObservationScalarType = double, typename TimeType = double, int ObservationSize = 1> std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > tudat::observation_models::simulateSingleObservationSet (const std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > observationsToSimulate, const std::shared_ptr< ObservationSimulator< ObservationSize, ObservationScalarType, TimeType > > observationSimulator, const LinkEnds & linkEnds, const std::vector< std::shared_ptr< ObservationViabilityCalculator > > currentObservationViabilityCalculators = std::vector< std::shared_ptr< ObservationViabilityCalculator > >())
Function to simulate observations for single observable and single set of link ends. From the observation time settings and the observation simulator, the required observations are simulated and returned.
Parameters
observationsToSimulate Object that computes/defines settings for observation times/reference link end
observationSimulator Observation simulator for observable for which observations are to be calculated.
linkEnds Link end set for which observations are to be calculated.
currentObservationViabilityCalculators List of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Pair of first: vector of observations; second: vector of times at which observations are taken (reference to link end defined in observationsToSimulate).
Definition at line 113 of file simulateObservations.h.
createObservationSimulationTimeSettingsMap()
template<typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > tudat::observation_models::createObservationSimulationTimeSettingsMap (const std::map< ObservableType, std::map< LinkEnds, std::pair< std::vector< TimeType >, LinkEndType > > > & originalMap)
Function to generate ObservationSimulationTimeSettings objects, as required for observation simulation from simulateSingleObservationSet from simple time vectors input.
Parameters
originalMap List of observation times per link end set per observable type.
Returns
TabulatedObservationSimulationTimeSettings objects from time list input (originalMap)
Definition at line 153 of file simulateObservations.h.
Referenced by simulateObservations().
simulateObservations() [1/2]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > > > tudat::observation_models::simulateObservations (const std::map< ObservableType, std::map< LinkEnds, std::pair< std::vector< TimeType >, LinkEndType > > > & observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > & observationSimulators)
Function to simulate observations from set of observables and link and sets and simple vectors of requested times. Function calls function for creation of ObservationSimulationTimeSettings and subsequently uses these for function call to observation simulation function.
Parameters
observationsToSimulate List of observation times per link end set per observable type.
observationSimulators List of Observation simulators per link end set per observable type.
Returns
Simulated observatoon values and associated times for requested observable types and link end sets.
Definition at line 190 of file simulateObservations.h.
References createObservationSimulationTimeSettingsMap().
Referenced by simulateObservationsWithNoise().
simulateObservations() [2/2]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > > > tudat::observation_models::simulateObservations (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > & observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > & observationSimulators, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList = PerObservableObservationViabilityCalculatorList())
Function to simulate observations from set of observables, link ends and observation time settings Iterates over all observables and link ends and simulates observations.
Parameters
observationsToSimulate List of observation time settings per link end set per observable type.
observationSimulators List of Observation simulators per link end set per observable type.
viabilityCalculatorList List (per observable type and per link ends) of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Simulated observatoon values and associated times for requested observable types and link end sets.
Definition at line 214 of file simulateObservations.h.
simulateObservationsWithNoise() [1/5]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > > > tudat::observation_models::simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > & observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > & observationSimulators, const std::map< ObservableType, std::map< LinkEnds, std::function< Eigen::VectorXd(const double) > > > & noiseFunctions, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList = PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables, link ends and observation time settings Iterates over all observables and link ends, simulates observations and adds noise according to given noise function. This function allows different noise functions to be defined for each observable/link ends combination
Parameters
observationsToSimulate List of observation time settings per link end set per observable type.
observationSimulators List of Observation simulators per link end set per observable type.
noiseFunctions Double map with functions that return the observation noise as a function of observation time.
viabilityCalculatorList List (per observable type and per link ends) of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Simulated observatoon values and associated times for requested observable types and link end sets.
Definition at line 334 of file simulateObservations.h.
References getObservableSize(), and simulateObservations().
Referenced by simulateObservationsWithNoise().
simulateObservationsWithNoise() [2/5]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > > > tudat::observation_models::simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > & observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > & observationSimulators, const std::map< ObservableType, std::map< LinkEnds, std::function< double(const double) > > > & noiseFunctions, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList = PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables, link ends and observation time settings Iterates over all observables and link ends, simulates observations and adds noise according to given noise function. This function allows different noise functions to be defined for each observable/link ends combination. However, the noise functions required as input are defined as doubles. For multi-valued observables (e.g. angular position), the noise function will be equal for all entries.
Parameters
observationsToSimulate List of observation time settings per link end set per observable type.
observationSimulators List of Observation simulators per link end set per observable type.
noiseFunctions Double map with functions that return the observation noise as a function of observation time.
viabilityCalculatorList List (per observable type and per link ends) of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Simulated observatoon values and associated times for requested observable types and link end sets.
Definition at line 431 of file simulateObservations.h.
References getIdenticallyAndIndependentlyDistributedNoise(), getObservableSize(), and simulateObservationsWithNoise().
simulateObservationsWithNoise() [3/5]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > > > tudat::observation_models::simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > & observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > & observationSimulators, const std::map< ObservableType, std::function< Eigen::VectorXd(const double) > > & noiseFunctions, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList = PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables, link ends and observation time settings Iterates over all observables and link ends, simulates observations and adds noise according to given noise function. This function allows different noise functions to be defined for each observable, but independent of link end.
Parameters
observationsToSimulate List of observation time settings per link end set per observable type.
observationSimulators List of Observation simulators per link end set per observable type.
noiseFunctions Map with functions that return the observation noise as a function of observation time.
viabilityCalculatorList List (per observable type and per link ends) of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Simulated observatoon values and associated times for requested observable types and link end sets.
Definition at line 476 of file simulateObservations.h.
References simulateObservationsWithNoise().
simulateObservationsWithNoise() [4/5]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > > > tudat::observation_models::simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > & observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > & observationSimulators, const std::map< ObservableType, std::function< double(const double) > > & noiseFunctions, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList = PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables, link ends and observation time settings Iterates over all observables and link ends, simulates observations and adds noise according to given noise function. This function allows different noise functions to be defined for each observable, but independent of link end. The noise functions required as input are defined as doubles. For multi-valued observables (e.g. angular position), the noise function will be equal for all entries.
Parameters
observationsToSimulate List of observation time settings per link end set per observable type.
observationSimulators List of Observation simulators per link end set per observable type.
noiseFunctions Map with functions that return the observation noise as a function of observation time.
viabilityCalculatorList List (per observable type and per link ends) of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Simulated observatoon values and associated times for requested observable types and link end sets.
Definition at line 530 of file simulateObservations.h.
References getIdenticallyAndIndependentlyDistributedNoise(), getObservableSize(), and simulateObservationsWithNoise().
simulateObservationsWithNoise() [5/5]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::pair< std::vector< TimeType >, LinkEndType > > > > tudat::observation_models::simulateObservationsWithNoise (const std::map< ObservableType, std::map< LinkEnds, std::shared_ptr< ObservationSimulationTimeSettings< TimeType > > > > & observationsToSimulate, const std::map< ObservableType, std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > & observationSimulators, const std::function< double(const double) > & noiseFunction, const PerObservableObservationViabilityCalculatorList viabilityCalculatorList = PerObservableObservationViabilityCalculatorList())
Function to simulate observations with observation noise from set of observables, link ends and observation time settings Iterates over all observables and link ends, simulates observations and adds noise according to given noise function. This function allows a single noise function to be provided, which is used for each observable/link end combination
Parameters
observationsToSimulate List of observation time settings per link end set per observable type.
observationSimulators List of Observation simulators per link end set per observable type.
noiseFunction Function that returns the observation noise as a function of observation time.
viabilityCalculatorList List (per observable type and per link ends) of observation viability calculators, which are used to reject simulated observation if they dont fulfill a given (set of) conditions, e.g. minimum elevation angle (default none).
Returns
Simulated observatoon values and associated times for requested observable types and link end sets.
Definition at line 569 of file simulateObservations.h.
References simulateObservationsWithNoise().
removeLinkIdFromSimulatedObservations()
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >,std::vector< TimeType > > > > tudat::observation_models::removeLinkIdFromSimulatedObservations (std::map< ObservableType, std::map< LinkEnds, std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > > > simulatedObservations)
/param simulatedObservations The simulated observation /return Simulated observations without link end id
Definition at line 599 of file simulateObservations.h.
createReferencePointEphemeris()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< ephemerides::Ephemeris > tudat::observation_models::createReferencePointEphemeris (const std::shared_ptr< simulation_setup::Body > bodyWithReferencePoint, const std::shared_ptr< ephemerides::RotationalEphemeris > bodyRotationModel, const std::function< Eigen::Matrix< StateScalarType, 6, 1 >(const TimeType &) > referencePointStateFunction)
Function to create an ephemeris for a reference point on a body, taking into account the time-variable rotation of the body and its global ephemeris
Parameters
bodyWithReferencePoint Body on which reference point is located
bodyRotationModel Rotation model that is to be used for going from body-fixed to inertial frame
referencePointStateFunction Function returning the state of the reference point on the body (in a body-fixed frame).
Returns
Reference point ephemeris in global coordinates.
Definition at line 36 of file createLightTimeCalculator.h.
References tudat::simulation_setup::Body::getStateInBaseFrameFromEphemeris(), and tudat::ephemerides::transformStateToGlobalFrame().
getLinkEndCompleteEphemerisFunction() [1/2]
template<typename TimeType = double, typename StateScalarType = double> std::function< Eigen::Matrix< StateScalarType, 6, 1 > const TimeType&) > tudat::observation_models::getLinkEndCompleteEphemerisFunction (const std::shared_ptr< simulation_setup::Body > bodyWithLinkEnd, const std::pair< std::string, std::string > & linkEndId)
Function to retrieve a state function for a link end (either a body center of mass or ground station).
Parameters
bodyWithLinkEnd Body on/in which link end is situated.
linkEndId Id of link end for which state function is to be created. First: name of body, second: name of reference point (empty if center of mass is to be used
Returns
Requested state function
Definition at line 67 of file createLightTimeCalculator.h.
References tudat::ground_stations::GroundStation::getStateInPlanetFixedFrame().
getLinkEndCompleteEphemerisFunction() [2/2]
template<typename TimeType = double, typename StateScalarType = double> std::function< Eigen::Matrix< StateScalarType, 6, 1 > const TimeType) > tudat::observation_models::getLinkEndCompleteEphemerisFunction (const std::pair< std::string, std::string > linkEndId, const simulation_setup::NamedBodyMap & bodyMap)
Function to create a state function of a link end, expressed in base frame.
Parameters
linkEndId Name of the reference point for which state function is to be created.
bodyMap List of body objects that comprises the environment
Returns
Requested state function.
Definition at line 114 of file createLightTimeCalculator.h.
createLightTimeCalculator() [1/2]
template<typename ObservationScalarType = double, typename TimeType = double> std::shared_ptr< observation_models::LightTimeCalculator< ObservationScalarType, TimeType > > tudat::observation_models::createLightTimeCalculator (const std::function< Eigen::Matrix< ObservationScalarType, 6, 1 >(const TimeType) > & transmitterCompleteEphemeris, const std::function< Eigen::Matrix< ObservationScalarType, 6, 1 >(const TimeType) > & receiverCompleteEphemeris, const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::shared_ptr< LightTimeCorrectionSettings > > & lightTimeCorrections, const LinkEndId & transmittingLinkEnd, const LinkEndId & receivingLinkEnd)
Function to create a light-time calculation object from light time correction settings environment and link end state functions.
Parameters
transmitterCompleteEphemeris Function returning the transmitter Cartesian state as a function of time.
receiverCompleteEphemeris Function returning the receiver Cartesian state as a function of time.
bodyMap List of body objects that comprises the environment
lightTimeCorrections List of light time corrections (w.r.t. Euclidean distance) that are applied when computing light time.
transmittingLinkEnd Identifier for transmitting link end.
receivingLinkEnd Identifier for receiving link end.
Definition at line 140 of file createLightTimeCalculator.h.
References createLightTimeCorrections().
createLightTimeCalculator() [2/2]
template<typename ObservationScalarType = double, typename TimeType = double> std::shared_ptr< observation_models::LightTimeCalculator< ObservationScalarType, TimeType > > tudat::observation_models::createLightTimeCalculator (const LinkEndId & transmittingLinkEnd, const LinkEndId & receivingLinkEnd, const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::shared_ptr< LightTimeCorrectionSettings > > & lightTimeCorrections = std::vector< std::shared_ptr< LightTimeCorrectionSettings > >())
Function to create a light-time calculation object from light time correction settings environment and link end identifiers.
Parameters
transmittingLinkEnd Identifier for transmitting link end.
receivingLinkEnd Identifier for receiving link end.
bodyMap List of body objects that comprises the environment
lightTimeCorrections List of light time corrections (w.r.t. Euclidean distance) that are applied when computing light time.
Definition at line 176 of file createLightTimeCalculator.h.
createLightTimeCorrections()
std::shared_ptr< LightTimeCorrection > tudat::observation_models::createLightTimeCorrections (const std::shared_ptr< LightTimeCorrectionSettings > correctionSettings, const simulation_setup::NamedBodyMap & bodyMap, const std::pair< std::string, std::string > & transmitter, const std::pair< std::string, std::string > & receiver)
Function to create object that computes a single (type of) correction to the light-time
Parameters
correctionSettings User-defined settings for the light-time correction that is to be created
bodyMap List of body objects that constitutes the environment
transmitter Id of transmitting body/reference point (first/second)
receiver Id of receiving body/reference point (first/second)
Returns
Object for computing required light-time correction
Definition at line 23 of file createLightTimeCorrection.cpp.
References first_order_relativistic, tudat::gravitation::GravityFieldModel::getGravitationalParameter(), tudat::relativity::PPNParameterSet::getParameterGamma(), tudat::relativity::ppnParameterSet, receiver, and transmitter.
Referenced by createLightTimeCalculator().
performObservationParameterEstimationClosureForSingleModelSet()
template<int ObservationSize = 1> void tudat::observation_models::performObservationParameterEstimationClosureForSingleModelSet (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, const std::shared_ptr< ObservationBias< ObservationSize > > observationBias, const LinkEnds linkEnds, const ObservableType observableType)
Function to perform the closure a single observation bias and a single estimated bias parameter. Estimated parameter objects are typically created prior to observation models. This function must be called for the estimated parameter object creation to be finalized, in the case link properties are estimated (e.g. observation biases).
Definition at line 39 of file createObservationManager.h.
References tudat::estimatable_parameters::arcwise_constant_additive_observation_bias, tudat::estimatable_parameters::arcwise_constant_relative_observation_bias, tudat::estimatable_parameters::constant_additive_observation_bias, tudat::estimatable_parameters::constant_relative_observation_bias, tudat::mathematical_constants::E, getObservationBiasType(), and multiple_observation_biases.
Referenced by performObservationParameterEstimationClosure().
performObservationParameterEstimationClosure()
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double> void tudat::observation_models::performObservationParameterEstimationClosure (std::shared_ptr< ObservationSimulator< ObservationSize, ObservationScalarType, TimeType > > observationSimulator, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate)
Function to perform the closure between observation models and estimated parameters. Estimated parameter objects are typically created prior to observation models. This function must be called for the estimated parameter object creation to be finalized, in the case link properties are estimated (e.g. observation biases).
Definition at line 240 of file createObservationManager.h.
References extractObservationBiasList(), tudat::estimatable_parameters::isParameterObservationLinkProperty(), and performObservationParameterEstimationClosureForSingleModelSet().
Referenced by createObservationManager().
createObservationManager()
template<int ObservationSize = 1, typename ObservationScalarType , typename TimeType > std::shared_ptr< ObservationManagerBase< ObservationScalarType, TimeType > > tudat::observation_models::createObservationManager (const ObservableType observableType, const std::map< LinkEnds, std::shared_ptr< ObservationSettings > > settingsPerLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const std::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionMatrixInterface)
Function to create an object to simulate observations of a given type and associated partials
Parameters
observableType Type of observable for which object is to simulate ObservationSimulator
settingsPerLinkEnds Map of settings for the observation models that are to be created in the simulator object: one for each required set of link ends (each settings object must be consistent with observableType).
bodyMap Map of Body objects that comprise the environment
parametersToEstimate Object containing the list of all parameters that are to be estimated
stateTransitionMatrixInterface Object used to compute the state transition/sensitivity matrix at a given time
Returns
Object that simulates the observations of a given type and associated partials
Definition at line 293 of file createObservationManager.h.
References performObservationParameterEstimationClosure(), and tudat::observation_partials::splitObservationPartialsAndScalers().
createObservationManagerBase()
template<typename ObservationScalarType , typename TimeType > std::shared_ptr< ObservationManagerBase< ObservationScalarType, TimeType > > tudat::observation_models::createObservationManagerBase (const ObservableType observableType, const std::map< LinkEnds, std::shared_ptr< ObservationSettings > > settingsPerLinkEnds, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< ObservationScalarType > > parametersToEstimate, const std::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionMatrixInterface)
Function to create an object to simulate observations of a given type and associated partials
Parameters
observableType Type of observable for which object is to simulate ObservationSimulator
settingsPerLinkEnds Map of settings for the observation models that are to be created in the simulator object: one for each required set of link ends (each settings object must be consistent with observableType).
bodyMap Map of Body objects that comprise the environment
parametersToEstimate Object containing the list of all parameters that are to be estimated
stateTransitionMatrixInterface Object used to compute the state transition/sensitivity matrix at a given time
Returns
Object that simulates the observations of a given type and associated partials
Definition at line 352 of file createObservationManager.h.
References angular_position, n_way_range, one_way_differenced_range, one_way_doppler, one_way_range, position_observable, and two_way_doppler.
convertUnsortedToSortedObservationSettingsMap()
SortedObservationSettingsMap tudat::observation_models::convertUnsortedToSortedObservationSettingsMap (const ObservationSettingsMap & unsortedObservationSettingsMap)
Function to create list of observation models sorted by observable type and link ends from list only sorted in link ends.
Parameters
unsortedObservationSettingsMap List (multimap_) of observation models sorted link ends
Returns
List (map of maps) of observation models sorted by observable type and link ends
Definition at line 27 of file createObservationModel.cpp.
Referenced by createObservationSimulators(), and tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::OrbitDeterminationManager().
filterObservationViabilitySettings()
ObservationViabilitySettingsList tudat::observation_models::filterObservationViabilitySettings (const ObservationViabilitySettingsList & observationViabilitySettings, const LinkEnds & linkEnds)
Function to filter list of observationViabilitySettings, so that only those relevant for single set of link ends are retained
Parameters
observationViabilitySettings Full, unfiltered, list of observation viability settings
linkEnds Link ends for which the relevant observation vaibilityies are to be retrieved
Returns
List of observationViabilitySettings that are relevant for linkEnds
Definition at line 42 of file createObservationModel.cpp.
Referenced by createObservationViabilityCalculators().
getLinkEndIndicesForObservationViability()
std::vector< std::pair< int, int > > tudat::observation_models::getLinkEndIndicesForObservationViability (const LinkEnds & linkEnds, const ObservableType observableType, const LinkEndId linkEndToCheck)
Function to retrieve the link end indices in link end states/times that are to be used in viability calculation. Return variable is a vector of pairs, where each the first entry denotes the index of the point at which the link is to be checkd. The second entry denotes the index for the opposite end of the link.
Parameters
linkEnds Complete set of link ends for which check is to be performed
observableType Observable type for which check is to be performed
linkEndToCheck Link end at which check is to be performed
Returns
Link end indices in link end states/times that are to be used in viability calculation
Definition at line 69 of file createObservationModel.cpp.
References angular_position, getNWayLinkEndIndicesFromLinkEndId(), n_way_range, one_way_differenced_range, one_way_doppler, one_way_range, position_observable, receiver, reflector1, transmitter, and two_way_doppler.
Referenced by createBodyAvoidanceAngleCalculator(), createMinimumElevationAngleCalculator(), and createOccultationCalculator().
createMinimumElevationAngleCalculator()
std::shared_ptr< MinimumElevationAngleCalculator > tudat::observation_models::createMinimumElevationAngleCalculator (const simulation_setup::NamedBodyMap & bodyMap, const LinkEnds linkEnds, const ObservableType observationType, const std::shared_ptr< ObservationViabilitySettings > observationViabilitySettings, const std::string & stationName)
Function to create an object to check if a minimum elevation angle condition is met for an observation
Parameters
bodyMap Map of body objects that constitutes the environment
linkEnds Link ends for which viability check object is to be made
observationType Type of observable for which viability check object is to be made
observationViabilitySettings Object that defines the settings for the creation of the viability check creation (settings must be compatible with minimum elevation angle check). Ground station must ve specified by associatedLinkEnd_.second in observationViabilitySettings.
stationName Name of the ground station for which calculator is to be computed (if no station is explicitly given in observationViabilitySettings).
Returns
Object to check if a minimum elevation angle condition is met for an observation
Definition at line 211 of file createObservationModel.cpp.
References getLinkEndIndicesForObservationViability(), and minimum_elevation_angle.
Referenced by createObservationViabilityCalculators().
createBodyAvoidanceAngleCalculator()
std::shared_ptr< BodyAvoidanceAngleCalculator > tudat::observation_models::createBodyAvoidanceAngleCalculator (const simulation_setup::NamedBodyMap & bodyMap, const LinkEnds linkEnds, const ObservableType observationType, const std::shared_ptr< ObservationViabilitySettings > observationViabilitySettings)
Function to create an object to check if a body avoidance angle condition is met for an observation
Parameters
bodyMap Map of body objects that constitutes the environment
linkEnds Link ends for which viability check object is to be made
observationType Type of observable for which viability check object is to be made
observationViabilitySettings Object that defines the settings for the creation of the viability check creation (settings must be compatible with body avoidance angle check). If ground station is not specified (by associatedLinkEnd_.second in observationViabilitySettings), check is performed for all ground stations on (or c.o.m. of) body (defined by associatedLinkEnd_.first) automatically.
Returns
Object to check if a body avoidance angle condition is met for an observation
Definition at line 258 of file createObservationModel.cpp.
References body_avoidance_angle, and getLinkEndIndicesForObservationViability().
Referenced by createObservationViabilityCalculators().
createOccultationCalculator()
std::shared_ptr< OccultationCalculator > tudat::observation_models::createOccultationCalculator (const simulation_setup::NamedBodyMap & bodyMap, const LinkEnds linkEnds, const ObservableType observationType, const std::shared_ptr< ObservationViabilitySettings > observationViabilitySettings)
Function to create an object to check if a body occultation condition is met for an observation
Parameters
bodyMap Map of body objects that constitutes the environment
linkEnds Link ends for which viability check object is to be made
observationType Type of observable for which viability check object is to be made
observationViabilitySettings Object that defines the settings for the creation of the viability check creation (settings must be compatible with body occultation check). If ground station is not specified (by associatedLinkEnd_.second in observationViabilitySettings), check is performed for all ground stations on (or c.o.m. of) body (defined by associatedLinkEnd_.first) automatically, or fo
Returns
Object to check if a body occultation condition is met for an observation
Definition at line 289 of file createObservationModel.cpp.
References body_occultation, and getLinkEndIndicesForObservationViability().
Referenced by createObservationViabilityCalculators().
createObservationViabilityCalculators() [1/3]
std::vector< std::shared_ptr< ObservationViabilityCalculator > > tudat::observation_models::createObservationViabilityCalculators (const simulation_setup::NamedBodyMap & bodyMap, const LinkEnds linkEnds, const ObservableType observationType, const std::vector< std::shared_ptr< ObservationViabilitySettings > > & observationViabilitySettings)
Function to create an list of obervation viability conditions for a single set of link ends
Parameters
bodyMap Map of body objects that constitutes the environment
linkEnds Link ends for which viability check object is to be made
observationType Type of observable for which viability check object is to be made
observationViabilitySettings List of viability settings from which viability check objects are to be created
Returns
List of obervation viability conditions for a single set of link ends
Definition at line 321 of file createObservationModel.cpp.
References body_avoidance_angle, body_occultation, createBodyAvoidanceAngleCalculator(), createMinimumElevationAngleCalculator(), createOccultationCalculator(), filterObservationViabilitySettings(), and minimum_elevation_angle.
Referenced by createObservationViabilityCalculators().
createObservationViabilityCalculators() [2/3]
std::map< LinkEnds, std::vector< std::shared_ptr< ObservationViabilityCalculator > > > tudat::observation_models::createObservationViabilityCalculators (const simulation_setup::NamedBodyMap & bodyMap, const std::vector< LinkEnds > linkEnds, const ObservableType observationType, const std::vector< std::shared_ptr< ObservationViabilitySettings > > & observationViabilitySettings)
Function to create an list of obervation viability conditions for a number of sets of link ends, for a single observable type
Parameters
bodyMap Map of body objects that constitutes the environment
linkEnds List of link ends for which viability check object is to be made
observationType Type of observable for which viability check object is to be made
observationViabilitySettings List of viability settings from which viability check objects are to be created
Returns
List of obervation viability conditions for a number of sets of link ends, for a single observable type
Definition at line 389 of file createObservationModel.cpp.
References createObservationViabilityCalculators().
createObservationViabilityCalculators() [3/3]
PerObservableObservationViabilityCalculatorList tudat::observation_models::createObservationViabilityCalculators (const simulation_setup::NamedBodyMap & bodyMap, const std::map< ObservableType, std::vector< LinkEnds > > linkEndsPerObservable, const std::vector< std::shared_ptr< ObservationViabilitySettings > > & observationViabilitySettings)
Function to create a list of obervation viability conditions for any number of sets of link ends and observable types
Parameters
bodyMap Map of body objects that constitutes the environment
linkEndsPerObservable List of link ends, for each observable type, for which viability check object is to be made
observationViabilitySettings List of viability settings from which viability check objects are to be created
Returns
List of obervation viability conditions for any number of sets of link ends and observable types
Definition at line 409 of file createObservationModel.cpp.
References createObservationViabilityCalculators().
createOneWayDopplerProperTimeCalculator()
template<typename ObservationScalarType = double, typename TimeType = double> std::shared_ptr< DopplerProperTimeRateInterface > tudat::observation_models::createOneWayDopplerProperTimeCalculator (std::shared_ptr< DopplerProperTimeRateSettings > properTimeRateSettings, const LinkEnds & linkEnds, const simulation_setup::NamedBodyMap & bodyMap, const LinkEndType linkEndForCalculator)
Function to create the proper time rate calculator for use in one-way Doppler
Parameters
properTimeRateSettings Settings for proper time rate model
linkEnds Link ends of one-way Doppler observation model
bodyMap List of body objects that constitutes the environment
linkEndForCalculator Link end for which the proper time rate is to be computed
Returns
Proper time rate calculator for use in one-way Doppler
Definition at line 485 of file createObservationModel.h.
References direct_first_order_doppler_proper_time_rate, tudat::gravitation::GravityFieldModel::getGravitationalParameter(), receiver, transmitter, and unidentified_link_end.
createObservationBiasCalculator()
template<int ObservationSize = 1> std::shared_ptr< ObservationBias< ObservationSize > > tudat::observation_models::createObservationBiasCalculator (const LinkEnds linkEnds, const ObservableType observableType, const std::shared_ptr< ObservationBiasSettings > biasSettings, const simulation_setup::NamedBodyMap & bodyMap)
Function to create an object that computes an observation bias, which can represent any type of system-dependent influence on the observed value (e.g. absolute bias, relative bias, clock drift, etc.)
Parameters
linkEnds Observation link ends for which the bias is to be created.
observableType Observable type for which bias is to be created
biasSettings Settings for the observation bias that is to be created.
bodyMap List of body objects that comprises the environment.
Returns
Object that computes an observation bias according to requested settings.
Definition at line 585 of file createObservationModel.h.
References arc_wise_constant_absolute_bias, arc_wise_constant_relative_bias, constant_absolute_bias, constant_relative_bias, getLinkEndIndicesForLinkEndTypeAtObservable(), and multiple_observation_biases.
Referenced by tudat::observation_models::ObservationModelCreator< 1, ObservationScalarType, TimeType >::createObservationModel().
createObservationSimulator()
template<int ObservationSize = 1, typename ObservationScalarType = double, typename TimeType = double> std::shared_ptr< ObservationSimulator< ObservationSize, ObservationScalarType, TimeType > > tudat::observation_models::createObservationSimulator (const ObservableType observableType, const std::map< LinkEnds, std::shared_ptr< ObservationSettings > > settingsPerLinkEnds, const simulation_setup::NamedBodyMap & bodyMap)
Function to create an object to simulate observations of a given type
Parameters
observableType Type of observable for which object is to simulate ObservationSimulator
settingsPerLinkEnds Map of settings for the observation models that are to be created in the simulator object: one for each required set of link ends (each settings object must be consistent with observableType).
bodyMap Map of Body objects that comprise the environment
Returns
Object that simulates the observables according to the provided settings.
Definition at line 1301 of file createObservationModel.h.
References tudat::observation_models::ObservationModelCreator< ObservationSize, ObservationScalarType, TimeType >::createObservationModel().
createObservationSimulators() [1/2]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType,std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > tudat::observation_models::createObservationSimulators (observation_models::SortedObservationSettingsMap observationSettingsMap, const simulation_setup::NamedBodyMap & bodyMap)
Function to create a map of object to simulate observations (one object for each type of observable).
Parameters
observationSettingsMap Map of settings for the observation models that are to be created in the simulator object: first map key is observable type, second is link ends for observation. One observation settings object must be given for each required set of link ends/observable (each settings object must be consistent with observable type in first entry).
bodyMap Map of Body objects that comprise the environment
Returns
List of objects that simulate the observables according to the provided settings.
Definition at line 1333 of file createObservationModel.h.
References getObservableSize().
createObservationSimulators() [2/2]
template<typename ObservationScalarType = double, typename TimeType = double> std::map< ObservableType,std::shared_ptr< ObservationSimulatorBase< ObservationScalarType, TimeType > > > tudat::observation_models::createObservationSimulators (observation_models::ObservationSettingsMap observationSettingsMap, const simulation_setup::NamedBodyMap & bodyMap)
Function to create a map of object to simulate observations (one object for each type of observable), from a list of observation settings not sorted by observable type.
Parameters
observationSettingsMap Multi-map of settings for the observation models that are to be created in the simulator object map key is link ends for observation.
bodyMap Map of Body objects that comprise the environment
Returns
List of objects that simulate the observables according to the provided settings.
Definition at line 1387 of file createObservationModel.h.
References convertUnsortedToSortedObservationSettingsMap().