var searchData=
[
  ['halleyrootfindercore',['HalleyRootFinderCore',['../d0/d48/classtudat_1_1root__finders_1_1_halley_root_finder_core.html#a699852e1e5066afc555d5dc4e4e0f43e',1,'tudat::root_finders::HalleyRootFinderCore::HalleyRootFinderCore(TerminationFunction terminationFunction)'],['../d0/d48/classtudat_1_1root__finders_1_1_halley_root_finder_core.html#a5abe46bfab9183bdafe48b9519e6f88f',1,'tudat::root_finders::HalleyRootFinderCore::HalleyRootFinderCore(const DataType relativeXTolerance, const unsigned int maxIterations)']]],
  ['handleunimplementedenumvalue',['handleUnimplementedEnumValue',['../d8/d24/namespacetudat_1_1json__interface.html#ad66b734e4a05cd2af739ecdb12b3fafa',1,'tudat::json_interface']]],
  ['handleuseofdefaultvalue',['handleUseOfDefaultValue',['../dc/d36/classtudat_1_1json__interface_1_1_undefined_key_error.html#a85d24fc22955403b49b79a6dbeeeab1c',1,'tudat::json_interface::UndefinedKeyError']]],
  ['hash_5fconstructor',['hash_constructor',['../d3/dc2/namespacetudat_1_1input__output_1_1field__types.html#ac38ef97c6c25573e009ab73ed7e054dd',1,'tudat::input_output::field_types']]],
  ['hashfunc',['hashFunc',['../d5/d1b/classtudat_1_1aerodynamics_1_1_n_r_l_m_s_i_s_e00_atmosphere.html#ac13dcc930e184a5c9bc173f2a60da5de',1,'tudat::aerodynamics::NRLMSISE00Atmosphere']]],
  ['hermitecubicsplineinterpolator',['HermiteCubicSplineInterpolator',['../d8/d88/classtudat_1_1interpolators_1_1_hermite_cubic_spline_interpolator.html#a231d2f1479003eade4ca1f66bbd83b7d',1,'tudat::interpolators::HermiteCubicSplineInterpolator::HermiteCubicSplineInterpolator(const std::vector&lt; IndependentVariableType &gt; &amp;independentValues, const std::vector&lt; DependentVariableType &gt; &amp;dependentValues, const std::vector&lt; DependentVariableType &gt; &amp;derivativeValues, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair&lt; DependentVariableType, DependentVariableType &gt; &amp;defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity&lt; DependentVariableType &gt;(), IdentityElement::getAdditionIdentity&lt; DependentVariableType &gt;()))'],['../d8/d88/classtudat_1_1interpolators_1_1_hermite_cubic_spline_interpolator.html#ab61fc3bdbd0c50e828a1eaba2a91e874',1,'tudat::interpolators::HermiteCubicSplineInterpolator::HermiteCubicSplineInterpolator(const std::map&lt; IndependentVariableType, DependentVariableType &gt; &amp;dataMap, const std::vector&lt; DependentVariableType &gt; &amp;derivativeValues, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair&lt; DependentVariableType, DependentVariableType &gt; &amp;defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity&lt; DependentVariableType &gt;(), IdentityElement::getAdditionIdentity&lt; DependentVariableType &gt;()))']]],
  ['hermitedatasettings',['HermiteDataSettings',['../dd/d93/classtudat_1_1interpolators_1_1_hermite_data_settings.html#ac88f1895a1d615f402b052fa49ff5bf6',1,'tudat::interpolators::HermiteDataSettings']]],
  ['huntingalgorithmlookupscheme',['HuntingAlgorithmLookupScheme',['../d7/dde/classtudat_1_1interpolators_1_1_hunting_algorithm_lookup_scheme.html#a3fb7eafeb1f8b9056632e9ccca263da4',1,'tudat::interpolators::HuntingAlgorithmLookupScheme']]],
  ['hybridpropagationterminationcondition',['HybridPropagationTerminationCondition',['../da/d57/classtudat_1_1propagators_1_1_hybrid_propagation_termination_condition.html#a44c5272b512c8e20462068eca871c410',1,'tudat::propagators::HybridPropagationTerminationCondition']]],
  ['hypersoniclocalinclinationanalysis',['HypersonicLocalInclinationAnalysis',['../d7/dc6/classtudat_1_1aerodynamics_1_1_hypersonic_local_inclination_analysis.html#aafd554c05c7f1fae402513861d067290',1,'tudat::aerodynamics::HypersonicLocalInclinationAnalysis']]]
];
