var searchData=
[
  ['basestateinterface',['BaseStateInterface',['../d9/df4/classtudat_1_1simulation__setup_1_1_base_state_interface.html#aaef83a88c7daddd073c395d2c7f12361',1,'tudat::simulation_setup::BaseStateInterface']]],
  ['basestateinterfaceimplementation',['BaseStateInterfaceImplementation',['../d3/dfb/classtudat_1_1simulation__setup_1_1_base_state_interface_implementation.html#a3e659050cd3fc0915a9744f0daa0eab8',1,'tudat::simulation_setup::BaseStateInterfaceImplementation']]],
  ['basicfunction',['BasicFunction',['../d8/d11/classtudat_1_1basic__mathematics_1_1_basic_function.html#a6db9f3a2a2b5be0e10132e2b9b648132',1,'tudat::basic_mathematics::BasicFunction']]],
  ['basicsolidbodygravityfieldvariationsettings',['BasicSolidBodyGravityFieldVariationSettings',['../de/d4d/classtudat_1_1simulation__setup_1_1_basic_solid_body_gravity_field_variation_settings.html#a57c60a57058d16a8f86cfaa049b5ed14',1,'tudat::simulation_setup::BasicSolidBodyGravityFieldVariationSettings']]],
  ['basicsolidbodytidegravityfieldvariations',['BasicSolidBodyTideGravityFieldVariations',['../d5/db1/classtudat_1_1gravitation_1_1_basic_solid_body_tide_gravity_field_variations.html#a3a8524f6959e9c1e9f4ff68f8700d140',1,'tudat::gravitation::BasicSolidBodyTideGravityFieldVariations']]],
  ['binarysearchlookupscheme',['BinarySearchLookupScheme',['../d9/d60/classtudat_1_1interpolators_1_1_binary_search_lookup_scheme.html#aa2ef6246aeee011cb6ab3786d0386481',1,'tudat::interpolators::BinarySearchLookupScheme']]],
  ['bisectioncore',['BisectionCore',['../d9/d67/classtudat_1_1root__finders_1_1_bisection_core.html#a947611a377418f1bbaf3e02c3e1b1ccd',1,'tudat::root_finders::BisectionCore::BisectionCore(const TerminationFunction terminationFunction, const DataType lowerBound=-1.0, const DataType upperBound=1.0)'],['../d9/d67/classtudat_1_1root__finders_1_1_bisection_core.html#a631cdc22e0e5c364af8ba37af4183918',1,'tudat::root_finders::BisectionCore::BisectionCore(const DataType relativeXTolerance, const unsigned int maxIterations, const DataType lowerBound=-1.0, const DataType upperBound=1.0)']]],
  ['body',['Body',['../d5/de5/classtudat_1_1simulation__setup_1_1_body.html#a802232493506b5fc4956779e74468f06',1,'tudat::simulation_setup::Body']]],
  ['bodyaerodynamicanglevariablesavesettings',['BodyAerodynamicAngleVariableSaveSettings',['../d2/d63/classtudat_1_1propagators_1_1_body_aerodynamic_angle_variable_save_settings.html#a59c775527210635f230ccb61bcfa8162',1,'tudat::propagators::BodyAerodynamicAngleVariableSaveSettings']]],
  ['bodyavoidanceanglecalculator',['BodyAvoidanceAngleCalculator',['../d1/db1/classtudat_1_1observation__models_1_1_body_avoidance_angle_calculator.html#a6b204e9253ba46dc10d1b13abc06dfff',1,'tudat::observation_models::BodyAvoidanceAngleCalculator']]],
  ['bodyfixedforcedirectionguidance',['BodyFixedForceDirectionGuidance',['../d9/d8d/classtudat_1_1propulsion_1_1_body_fixed_force_direction_guidance.html#ad6935329963c8c162a25b187e44479e6',1,'tudat::propulsion::BodyFixedForceDirectionGuidance']]],
  ['bodymassintegratedstateprocessor',['BodyMassIntegratedStateProcessor',['../d0/dd7/classtudat_1_1propagators_1_1_body_mass_integrated_state_processor.html#acb9c2430a95e3b770f86ba639340f6c0',1,'tudat::propagators::BodyMassIntegratedStateProcessor']]],
  ['bodymassstatederivative',['BodyMassStateDerivative',['../de/d98/classtudat_1_1propagators_1_1_body_mass_state_derivative.html#ab82adb6257ee76580cbb76d9363e8b73',1,'tudat::propagators::BodyMassStateDerivative::BodyMassStateDerivative(const std::map&lt; std::string, std::shared_ptr&lt; basic_astrodynamics::MassRateModel &gt; &gt; &amp;massRateModels, const std::vector&lt; std::string &gt; &amp;bodiesToIntegrate)'],['../de/d98/classtudat_1_1propagators_1_1_body_mass_state_derivative.html#afe1bb9bba0114dbda0e055195c3428d7',1,'tudat::propagators::BodyMassStateDerivative::BodyMassStateDerivative(const std::map&lt; std::string, std::vector&lt; std::shared_ptr&lt; basic_astrodynamics::MassRateModel &gt; &gt; &gt; &amp;massRateModels, const std::vector&lt; std::string &gt; &amp;bodiesToIntegrate)']]],
  ['bodyshapemodel',['BodyShapeModel',['../db/d9d/classtudat_1_1basic__astrodynamics_1_1_body_shape_model.html#a9afa14876ae1e01c193995c53c443f8e',1,'tudat::basic_astrodynamics::BodyShapeModel']]],
  ['bodyshapesettings',['BodyShapeSettings',['../d6/da0/classtudat_1_1simulation__setup_1_1_body_shape_settings.html#af015990acdf8491ce08eaa09942e9ba9',1,'tudat::simulation_setup::BodyShapeSettings']]],
  ['boostcontinuousprobabilitydistribution',['BoostContinuousProbabilityDistribution',['../de/d8e/classtudat_1_1statistics_1_1_boost_continuous_probability_distribution.html#a0c61159df17227b0779b2d0d332cca88',1,'tudat::statistics::BoostContinuousProbabilityDistribution']]],
  ['bulirschstoerintegratorsettings',['BulirschStoerIntegratorSettings',['../dd/dea/classtudat_1_1numerical__integrators_1_1_bulirsch_stoer_integrator_settings.html#a8c21c643bf84b6caefa79cf501968dc9',1,'tudat::numerical_integrators::BulirschStoerIntegratorSettings']]],
  ['bulirschstoervariablestepsizeintegrator',['BulirschStoerVariableStepSizeIntegrator',['../d5/d2d/classtudat_1_1numerical__integrators_1_1_bulirsch_stoer_variable_step_size_integrator.html#a932910c0b7e3e0db03775aadaf394ca5',1,'tudat::numerical_integrators::BulirschStoerVariableStepSizeIntegrator::BulirschStoerVariableStepSizeIntegrator(const std::vector&lt; unsigned int &gt; &amp;sequence, const StateDerivativeFunction &amp;stateDerivativeFunction, const IndependentVariableType intervalStart, const StateType &amp;initialState, const TimeStepType minimumStepSize, const TimeStepType maximumStepSize, const StateType &amp;relativeErrorTolerance, const StateType &amp;absoluteErrorTolerance, const TimeStepType safetyFactorForNextStepSize=0.6, const TimeStepType maximumFactorIncreaseForNextStepSize=4.0, const TimeStepType minimumFactorDecreaseForNextStepSize=0.1)'],['../d5/d2d/classtudat_1_1numerical__integrators_1_1_bulirsch_stoer_variable_step_size_integrator.html#a2d9903693f89b139b7d9cadfe4b89b37',1,'tudat::numerical_integrators::BulirschStoerVariableStepSizeIntegrator::BulirschStoerVariableStepSizeIntegrator(const std::vector&lt; unsigned int &gt; &amp;sequence, const StateDerivativeFunction &amp;stateDerivativeFunction, const IndependentVariableType intervalStart, const StateType &amp;initialState, const TimeStepType minimumStepSize, const TimeStepType maximumStepSize, const typename StateType::Scalar relativeErrorTolerance=1.0e-12, const typename StateType::Scalar absoluteErrorTolerance=1.0e-12, const TimeStepType safetyFactorForNextStepSize=0.75, const TimeStepType maximumFactorIncreaseForNextStepSize=4.0, const TimeStepType minimumFactorDecreaseForNextStepSize=0.1)']]]
];
