Tudat: tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial Class Reference
tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial Class Reference
Class for computing the partial derivatives of 1st-order relativistic light-time correction.
#include <firstOrderRelativisticLightTimeCorrectionPartial.h>
Public Member Functions
FirstOrderRelativisticLightTimeCorrectionPartial (const boost::shared_ptr< observation_models::FirstOrderLightTimeCorrectionCalculator > correctionCalculator)
Constructor.
~FirstOrderRelativisticLightTimeCorrectionPartial ()
Destructor.
std::vector< std::string > getPerturbingBodies ()
Function to get the names of bodies causing light-time correction.
SingleOneWayRangePartialReturnType wrtBodyGravitationalParameter (const std::vector< Eigen::Vector6d > &states, const std::vector< double > &times, const int bodyIndex)
Function to compute partial derivative of 1st order relativistic correction w.r.t. gravitational parameter.
SingleOneWayRangePartialReturnType wrtPpnParameterGamma (const std::vector< Eigen::Vector6d > &states, const std::vector< double > &times)
Function to compute partial derivative of 1st order relativistic correction w.r.t. PPN parameter gamma.
Public Member Functions inherited from tudat::observation_partials::LightTimeCorrectionPartial
LightTimeCorrectionPartial (const observation_models::LightTimeCorrectionType correctionType)
Constructor.
virtual ~LightTimeCorrectionPartial ()
Destructor.
observation_models::LightTimeCorrectionType getCorrectionType ()
Function to return type of light-time correction for which partial is to be computed.
Protected Attributes
boost::shared_ptr< observation_models::FirstOrderLightTimeCorrectionCalculator > correctionCalculator_
Object used to compute light-time correction.
std::vector< std::string > perturbingBodies_
Names of bodies causing light-time correction.
std::vector< boost::function< double() > > perturbingBodyGravitationalParameterFunctions_
Set of functions returning the gravitational parameters of the gravitating bodies.
Protected Attributes inherited from tudat::observation_partials::LightTimeCorrectionPartial
observation_models::LightTimeCorrectionType correctionType_
Type of light-time correction for which partial is to be computed.
Additional Inherited Members
Public Types inherited from tudat::observation_partials::LightTimeCorrectionPartial
typedef std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > SingleOneWayRangePartialReturnType
Typedef for return argument for light time partial (partial with vector and associated time)
Detailed Description
Definition at line 44 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
Constructor & Destructor Documentation
tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::FirstOrderRelativisticLightTimeCorrectionPartial (const boost::shared_ptr< observation_models::FirstOrderLightTimeCorrectionCalculator > correctionCalculator) inline
Constructor
Parameters
correctionCalculator Object used to compute light-time correction.
Definition at line 53 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
References correctionCalculator_, perturbingBodies_, and perturbingBodyGravitationalParameterFunctions_.
tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::~FirstOrderRelativisticLightTimeCorrectionPartial () inline
Definition at line 64 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
Member Function Documentation
SingleOneWayRangePartialReturnType tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::wrtBodyGravitationalParameter (const std::vector< Eigen::Vector6d > & states, const std::vector< double > & times, const int bodyIndex) inline
Function to compute partial derivative of 1st order relativistic correction w.r.t. gravitational parameter.
Parameters
states States of link ends for observation for which partial is to be computed
times Times of link ends for observation for which partial is to be computed
bodyIndex Index of body in correctionCalculator_->currentLighTimeCorrectionComponents_ for which partial is to be computed. NOTE: this index must be smaller than the number of bodies perturbing the light-time.
Returns
Partial derivative of 1st order relativistic correction w.r.t. gravitational parameter.
Definition at line 75 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
References correctionCalculator_, tudat::observation_partials::getPartialOfFirstOrderRelativisticLightTimeCorrectionWrtSingleGravitationalParameter(), perturbingBodies_, and perturbingBodyGravitationalParameterFunctions_.
Referenced by tudat::observation_partials::getLightTimeParameterPartialFunction().
SingleOneWayRangePartialReturnType tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::wrtPpnParameterGamma (const std::vector< Eigen::Vector6d > & states, const std::vector< double > & times) inline
Function to compute partial derivative of 1st order relativistic correction w.r.t. PPN parameter gamma.
Parameters
states States of link ends for observation for which partial is to be computed
times Times of link ends for observation for which partial is to be computed
Returns
Partial derivative of 1st order relativistic correction w.r.t. PPN parameter gamma.
Definition at line 99 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
References correctionCalculator_, and tudat::observation_partials::getPartialOfFirstOrderRelativisticLightTimeCorrectionWrtPpnParameterGamma().
Referenced by tudat::observation_partials::getLightTimeParameterPartialFunction().
std::vector< std::string > tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::getPerturbingBodies () inline
Function to get the names of bodies causing light-time correction.
Returns
Names of bodies causing light-time correction.
Definition at line 115 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
References perturbingBodies_.
Member Data Documentation
boost::shared_ptr< observation_models::FirstOrderLightTimeCorrectionCalculator > tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::correctionCalculator_ protected
Definition at line 124 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
Referenced by FirstOrderRelativisticLightTimeCorrectionPartial(), wrtBodyGravitationalParameter(), and wrtPpnParameterGamma().
std::vector< std::string > tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::perturbingBodies_ protected
Definition at line 127 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
Referenced by FirstOrderRelativisticLightTimeCorrectionPartial(), getPerturbingBodies(), and wrtBodyGravitationalParameter().
std::vector< boost::function< double() > > tudat::observation_partials::FirstOrderRelativisticLightTimeCorrectionPartial::perturbingBodyGravitationalParameterFunctions_ protected
Definition at line 130 of file firstOrderRelativisticLightTimeCorrectionPartial.h.
Referenced by FirstOrderRelativisticLightTimeCorrectionPartial(), and wrtBodyGravitationalParameter().
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/LightTimeCorrectionPartials/firstOrderRelativisticLightTimeCorrectionPartial.h