Tudat: tudat::input_output::field_types::state Namespace Reference
tudat::input_output::field_types::state Namespace Reference
Variables
static const FieldType apoapsisDistance = hash_constructor("State: Kepler_element: Apoapsis_distance")
Apoapsis distance [m].
static const FieldType argumentOfPeriapsis = hash_constructor("State: Kepler_element: Argument_of_periapsis")
Argument of Perifocus, w [rad].
static const FieldType cartesianXAcceleration = hash_constructor("State: Cartesian: X_acceleration")
Cartesian X acceleration [m/s].
static const FieldType cartesianXCoordinate = hash_constructor("State: Cartesian: X_coordinate")
Cartesian X coordinate [m].
static const FieldType cartesianXVelocity = hash_constructor("State: Cartesian: X_velocity")
Cartesian X velocity [m/s].
static const FieldType cartesianYAcceleration = hash_constructor("State: Cartesian: Y_acceleration")
Cartesian Y acceleration [m/s].
static const FieldType cartesianYCoordinate = hash_constructor("State: Cartesian: Y_coordinate")
Cartesian Y coordinate [m].
static const FieldType cartesianYVelocity = hash_constructor("State: Cartesian: Y_velocity")
Cartesian Y velocity [m/s].
static const FieldType cartesianZAcceleration = hash_constructor("State: Cartesian: Z_acceleration")
Cartesian Z acceleration [m/s].
static const FieldType cartesianZCoordinate = hash_constructor("State: Cartesian: Z_coordinate")
Cartesian Z coordinate [m].
static const FieldType cartesianZVelocity = hash_constructor("State: Cartesian: Z_velocity")
Cartesian Z velocity [m/s].
static const FieldType eccentricity = hash_constructor("State: Kepler_element: Eccentricity")
Eccentricity, e [-].
static const FieldType inclination = hash_constructor("State: Kepler_element: Inclination")
Inclination with respect to xy-plane, i [rad].
static const FieldType longitudeOfAscendingNode = hash_constructor("State: Kepler_element: Longitude_of_the_ascending_node")
Longitude of Ascending Node, OMEGA [rad].
static const FieldType meanAnomaly = hash_constructor("State: Kepler_element: Mean_anomaly")
Mean anomaly, M [rad].
static const FieldType meanMotion = hash_constructor("State: Mean_motion")
Mean motion, n [rad/s].
static const FieldType orbitalPeriod = hash_constructor("State: Orbital_period")
Orbital period [s].
static const FieldType periapsisDistance = hash_constructor("State: Kepler_element: Periapsis_distance")
Periapsis distance [m].
static const FieldType semiMajorAxis = hash_constructor("State: Kepler_element: Semi_major_axis")
Semi-major axis, a [m].
static const FieldType timeOfPeriapsisPassage = hash_constructor("State: Kepler_element: Time_of_periapsis")
Time of periapsis passage [JD, UT1].
static const FieldType trueAnomaly = hash_constructor("State: Kepler_element: True_anomaly")
True anomaly, theta [rad].
Variable Documentation
const FieldType tudat::input_output::field_types::state::cartesianXCoordinate = hash_constructor("State: Cartesian: X_coordinate") static
Definition at line 93 of file fieldType.h.
Referenced by tudat::ephemerides::CartesianStateExtractor::extract().
const FieldType tudat::input_output::field_types::state::cartesianYCoordinate = hash_constructor("State: Cartesian: Y_coordinate") static
Definition at line 97 of file fieldType.h.
Referenced by tudat::ephemerides::CartesianStateExtractor::extract().
const FieldType tudat::input_output::field_types::state::cartesianZCoordinate = hash_constructor("State: Cartesian: Z_coordinate") static
Definition at line 101 of file fieldType.h.
Referenced by tudat::ephemerides::CartesianStateExtractor::extract().
const FieldType tudat::input_output::field_types::state::cartesianXVelocity = hash_constructor("State: Cartesian: X_velocity") static
Definition at line 105 of file fieldType.h.
Referenced by tudat::ephemerides::CartesianStateExtractor::extract().
const FieldType tudat::input_output::field_types::state::cartesianYVelocity = hash_constructor("State: Cartesian: Y_velocity") static
Definition at line 109 of file fieldType.h.
Referenced by tudat::ephemerides::CartesianStateExtractor::extract().
const FieldType tudat::input_output::field_types::state::cartesianZVelocity = hash_constructor("State: Cartesian: Z_velocity") static
Definition at line 113 of file fieldType.h.
Referenced by tudat::ephemerides::CartesianStateExtractor::extract().
const FieldType tudat::input_output::field_types::state::cartesianXAcceleration = hash_constructor("State: Cartesian: X_acceleration") static
Definition at line 117 of file fieldType.h.
const FieldType tudat::input_output::field_types::state::cartesianYAcceleration = hash_constructor("State: Cartesian: Y_acceleration") static
Definition at line 121 of file fieldType.h.
const FieldType tudat::input_output::field_types::state::cartesianZAcceleration = hash_constructor("State: Cartesian: Z_acceleration") static
Definition at line 125 of file fieldType.h.
const FieldType tudat::input_output::field_types::state::eccentricity = hash_constructor("State: Kepler_element: Eccentricity") static
Definition at line 129 of file fieldType.h.
Referenced by tudat::mission_segments::computeEscapeOrCaptureDeltaV(), tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements(), tudat::orbital_element_conversions::convertEccentricAnomalyToMeanAnomaly(), tudat::orbital_element_conversions::convertEllipticalEccentricAnomalyToTrueAnomaly(), tudat::orbital_element_conversions::convertKeplerianToModifiedEquinoctialElements(), tudat::orbital_element_conversions::convertMeanAnomalyToEccentricAnomaly(), tudat::orbital_element_conversions::convertModifiedEquinoctialToKeplerianElements(), tudat::orbital_element_conversions::convertTrueAnomalyToEccentricAnomaly(), tudat::orbital_element_conversions::convertTrueAnomalyToHyperbolicEccentricAnomaly(), tudat::ephemerides::KeplerStateExtractor::extract(), tudat::reference_frames::getVelocityBasedLvlhToPlanetocentricRotationKeplerian(), and tudat::mission_segments::gravityAssist().
const FieldType tudat::input_output::field_types::state::inclination = hash_constructor("State: Kepler_element: Inclination") static
Definition at line 133 of file fieldType.h.
Referenced by tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements(), tudat::orbital_element_conversions::convertKeplerianToModifiedEquinoctialElements(), tudat::ephemerides::KeplerStateExtractor::extract(), and tudat::reference_frames::getVelocityBasedLvlhToPlanetocentricRotationKeplerian().
const FieldType tudat::input_output::field_types::state::longitudeOfAscendingNode = hash_constructor("State: Kepler_element: Longitude_of_the_ascending_node") static
Definition at line 137 of file fieldType.h.
Referenced by tudat::orbital_element_conversions::convertModifiedEquinoctialToKeplerianElements(), and tudat::ephemerides::KeplerStateExtractor::extract().
const FieldType tudat::input_output::field_types::state::argumentOfPeriapsis = hash_constructor("State: Kepler_element: Argument_of_periapsis") static
Definition at line 141 of file fieldType.h.
Referenced by tudat::ephemerides::KeplerStateExtractor::extract(), and tudat::reference_frames::getVelocityBasedLvlhToPlanetocentricRotationKeplerian().
const FieldType tudat::input_output::field_types::state::timeOfPeriapsisPassage = hash_constructor("State: Kepler_element: Time_of_periapsis") static
Definition at line 145 of file fieldType.h.
const FieldType tudat::input_output::field_types::state::meanAnomaly = hash_constructor("State: Kepler_element: Mean_anomaly") static
Definition at line 149 of file fieldType.h.
Referenced by tudat::orbital_element_conversions::computeKeplersFunctionForEllipticalOrbits(), tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::orbital_element_conversions::convertMeanAnomalyToEccentricAnomaly(), and tudat::ephemerides::KeplerStateExtractor::extract().
const FieldType tudat::input_output::field_types::state::trueAnomaly = hash_constructor("State: Kepler_element: True_anomaly") static
Definition at line 153 of file fieldType.h.
Referenced by tudat::orbital_element_conversions::convertTrueAnomalyToEccentricAnomaly(), tudat::ephemerides::KeplerStateExtractor::extract(), tudat::ephemerides::KeplerEphemeris::getCartesianState(), and tudat::reference_frames::getVelocityBasedLvlhToPlanetocentricRotationKeplerian().
const FieldType tudat::input_output::field_types::state::semiMajorAxis = hash_constructor("State: Kepler_element: Semi_major_axis") static
Definition at line 157 of file fieldType.h.
Referenced by tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements(), tudat::basic_astrodynamics::computeKeplerEnergy(), tudat::orbital_element_conversions::computeSemiLatusRectum(), tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeTimeOfFlight(), tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::computeTimeOfFlight(), tudat::mission_segments::computeTimeOfFlightIzzo(), tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::computeVelocities(), tudat::orbital_element_conversions::convertMeanAnomalyChangeToElapsedTime(), tudat::ephemerides::KeplerStateExtractor::extract(), and tudat::mission_segments::solveLambertProblemIzzo().
const FieldType tudat::input_output::field_types::state::apoapsisDistance = hash_constructor("State: Kepler_element: Apoapsis_distance") static
Definition at line 161 of file fieldType.h.
const FieldType tudat::input_output::field_types::state::periapsisDistance = hash_constructor("State: Kepler_element: Periapsis_distance") static
Definition at line 165 of file fieldType.h.
const FieldType tudat::input_output::field_types::state::meanMotion = hash_constructor("State: Mean_motion") static
Definition at line 168 of file fieldType.h.
Referenced by tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements().
const FieldType tudat::input_output::field_types::state::orbitalPeriod = hash_constructor("State: Orbital_period") static
Definition at line 171 of file fieldType.h.