Tudat: tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType > Class Template Reference
tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType > Class Template Reference
Class that determines an ephemeris from tabulated data.
#include <tabulatedEphemeris.h>
Public Types
typedef std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > StateInterpolatorPointer
Typedef for state interpolator.
typedef Eigen::Matrix< StateScalarType, 6, 1 > StateType
Public Member Functions
TabulatedCartesianEphemeris (const StateInterpolatorPointer interpolator, const std::string referenceFrameOrigin="SSB", const std::string referenceFrameOrientation="ECLIPJ2000")
Constructor, sets data interpolator and frame data.
~TabulatedCartesianEphemeris ()
Destructor.
template<>
Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get cartesian state from ephemeris (in long double precision), for double StateScalarType.
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get state from ephemeris (with long double as state scalar).
template<>
Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get cartesian state from ephemeris (in long double precision), for long double StateScalarType.
template<>
Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get cartesian state from ephemeris (in long double precision), for double StateScalarType.
Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get cartesian state from ephemeris (in long double precision).
template<>
Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get cartesian state from ephemeris (in long double precision), for long double StateScalarType.
template<>
Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in long double precision from Time input), for double StateScalarType.
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with long double as state scalar and Time as time type).
template<>
Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in long double precision from Time input), for double StateScalarType.
template<>
Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in long double precision from Time input).
Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in long double precision from Time input).
template<>
Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in long double precision from Time input).
template<>
Eigen::Vector6d getCartesianState (const double ephemerisTime)
Get cartesian state from ephemeris (in double precision), for double StateScalarType.
virtual Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)=0
Get state from ephemeris.
template<>
Eigen::Vector6d getCartesianState (const double ephemerisTime)
Get cartesian state from ephemeris (in double precision), for long double StateScalarType.
template<>
Eigen::Vector6d getCartesianState (const double ephemerisTime)
Get cartesian state from ephemeris (in double precision), double StateScalarType.
Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)
Get cartesian state from ephemeris.
template<>
Eigen::Vector6d getCartesianState (const double ephemerisTime)
Get cartesian state from ephemeris (in double precision), for long double StateScalarType.
template<>
Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in double precision from Time input), for double StateScalarType.
virtual Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with double as state scalar and Time as time type).
template<>
Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in double precision from Time input), for double StateScalarType.
template<>
Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in double precision from Time input).
Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in double precision from Time input).
template<>
Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &time)
Get cartesian state from ephemeris (in double precision from Time input).
StateInterpolatorPointer getInterpolator ()
Function to return the interpolator.
std::pair< double, double > getSafeInterpolationInterval ()
Function that retrieves the time interval at which this ephemeris can be safely interrogated.
void resetInterpolator (const StateInterpolatorPointer interpolator)
Function to reset the state interpolator.
Public Member Functions inherited from tudat::ephemerides::Ephemeris
Ephemeris (const std::string &referenceFrameOrigin="", const std::string &referenceFrameOrientation="")
Constructor.
virtual ~Ephemeris ()
Default destructor.
std::string getReferenceFrameOrientation ()
Get reference frame orientation.
std::string getReferenceFrameOrigin ()
Get reference frame origin.
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (double specialization).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (long double specialization).
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (double specialization with Time input).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (long double specialization with Time input).
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > getTemplatedStateFromEphemeris (const TimeType &time)
Get state from ephemeris, with state scalar as template type.
Private Attributes
StateInterpolatorPointer interpolator_
Interpolator that returns body state as a function of time.
Additional Inherited Members
Protected Attributes inherited from tudat::ephemerides::Ephemeris
std::string referenceFrameOrientation_
Reference frame orientation.
std::string referenceFrameOrigin_
Reference frame origin.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >
Class that determines an ephemeris from tabulated data, by using numerical interpolation of this data. Required input to this class is a OneDimensionalInterpolator, which may be reset. This class may for instance be used for setting the numerically integrated state of a body as its 'new' ephemeris
Definition at line 39 of file tabulatedEphemeris.h.
Member Typedef Documentation
StateType
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::StateType
Definition at line 48 of file tabulatedEphemeris.h.
StateInterpolatorPointer
template<typename StateScalarType = double, typename TimeType = double> typedef std::shared_ptr< interpolators::OneDimensionalInterpolator < TimeType, StateType > > tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::StateInterpolatorPointer
Definition at line 52 of file tabulatedEphemeris.h.
Constructor & Destructor Documentation
TabulatedCartesianEphemeris()
template<typename StateScalarType = double, typename TimeType = double> tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::TabulatedCartesianEphemeris (const StateInterpolatorPointer interpolator, const std::string referenceFrameOrigin = "SSB", const std::string referenceFrameOrientation = "ECLIPJ2000") inline
Constructor, sets data interpolator and frame data.
Parameters
interpolator Interpolator that returns the interpolated state as a function of time.
referenceFrameOrigin Origin of reference frame in which state is defined.
referenceFrameOrientation Orientation of reference frame in which state is defined.
Definition at line 62 of file tabulatedEphemeris.h.
~TabulatedCartesianEphemeris()
template<typename StateScalarType = double, typename TimeType = double> tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::~TabulatedCartesianEphemeris () inline
Destructor
Definition at line 73 of file tabulatedEphemeris.h.
Member Function Documentation
resetInterpolator()
template<typename StateScalarType = double, typename TimeType = double> void tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::resetInterpolator (const StateInterpolatorPointer interpolator) inline
Function to reset the state interpolator, for instance following an update of the states of the body after a new numerical integration.
Parameters
interpolator New interpolator that returns the interpolated state as a function of time.
Definition at line 82 of file tabulatedEphemeris.h.
References tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::interpolator_.
Referenced by tudat::propagators::resetIntegratedEphemerisOfBody().
getCartesianState() [1/6]
template<typename StateScalarType = double, typename TimeType = double> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getCartesianState (const double secondsSinceEpoch) virtual
Returns cartesian state from ephemeris, as calculated from interpolator_.
Parameters
secondsSinceEpoch Seconds since epoch.
Returns
State in Cartesian elements from ephemeris.
Implements tudat::ephemerides::Ephemeris.
getCartesianLongState() [1/6]
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getCartesianLongState (const double secondsSinceEpoch) virtual
Returns cartesian state from ephemeris (in long double precision), as calculated from interpolator_. For double StateScalarType class template argument, this function returns the double precision interpolated values, cast to long double. Only for long double StateScalarType argument is this function used to its fullest.
Parameters
secondsSinceEpoch Seconds since epoch.
Returns
State in Cartesian elements from ephemeris.
Reimplemented from tudat::ephemerides::Ephemeris.
getCartesianStateFromExtendedTime() [1/6]
template<typename StateScalarType = double, typename TimeType = double> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getCartesianStateFromExtendedTime (const Time & time) virtual
Returns cartesian state from ephemeris (in double precision from Time input), as calculated from interpolator_.
Parameters
time Time at which ephemeris is to be evaluated
Returns
State in Cartesian elements from ephemeris.
Reimplemented from tudat::ephemerides::Ephemeris.
getCartesianLongStateFromExtendedTime() [1/6]
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getCartesianLongStateFromExtendedTime (const Time & time) virtual
Returns cartesian state from ephemeris (in long double precision from Time input), as calculated from interpolator_. For double StateScalarType class template argument, this function returns the double precision interpolated values, cast to long double. Only for long double StateScalarType argument is this function used to its fullest.
Parameters
time Time at which ephemeris is to be evaluated
Returns
State in Cartesian elements from ephemeris.
Reimplemented from tudat::ephemerides::Ephemeris.
getInterpolator()
template<typename StateScalarType = double, typename TimeType = double> StateInterpolatorPointer tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getInterpolator () inline
Function to return the interpolator that is to be used to calculate the state.
Returns
Interpolator that is to be used to calculate the state.
Definition at line 133 of file tabulatedEphemeris.h.
References tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::interpolator_.
getSafeInterpolationInterval()
template<typename StateScalarType = double, typename TimeType = double> std::pair< double, double > tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getSafeInterpolationInterval () inline
Function that retrieves the time interval at which this ephemeris can be safely interrogated. The interval on which the interpolator inside this object is valid is checked and returned
Returns
The time interval at which the tabulated ephemeris can be safely interrogated
Definition at line 144 of file tabulatedEphemeris.h.
References tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::interpolator_.
getCartesianState() [2/6]
template<> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< double, double >::getCartesianState (const double ephemerisTime) virtual
Implements tudat::ephemerides::Ephemeris.
Definition at line 20 of file tabulatedEphemeris.cpp.
getCartesianLongState() [2/6]
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< double, double >::getCartesianLongState (const double secondsSinceEpoch) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 28 of file tabulatedEphemeris.cpp.
getCartesianStateFromExtendedTime() [2/6]
template<> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< double, double >::getCartesianStateFromExtendedTime (const Time & time) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 36 of file tabulatedEphemeris.cpp.
References tudat::Time::getSeconds().
getCartesianLongStateFromExtendedTime() [2/6]
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< double, double >::getCartesianLongStateFromExtendedTime (const Time & time) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 44 of file tabulatedEphemeris.cpp.
References tudat::Time::getSeconds().
getCartesianState() [3/6]
template<> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< long double, double >::getCartesianState (const double ephemerisTime) virtual
Implements tudat::ephemerides::Ephemeris.
Definition at line 56 of file tabulatedEphemeris.cpp.
getCartesianLongState() [3/6]
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< long double, double >::getCartesianLongState (const double secondsSinceEpoch) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 64 of file tabulatedEphemeris.cpp.
getCartesianStateFromExtendedTime() [3/6]
template<> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< long double, double >::getCartesianStateFromExtendedTime (const Time & time) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 72 of file tabulatedEphemeris.cpp.
References tudat::Time::getSeconds().
getCartesianLongStateFromExtendedTime() [3/6]
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< long double, double >::getCartesianLongStateFromExtendedTime (const Time & time) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 80 of file tabulatedEphemeris.cpp.
References tudat::Time::getSeconds().
getCartesianState() [4/6]
template<> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< double, Time >::getCartesianState (const double ephemerisTime) virtual
Implements tudat::ephemerides::Ephemeris.
Definition at line 89 of file tabulatedEphemeris.cpp.
getCartesianLongState() [4/6]
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< double, Time >::getCartesianLongState (const double secondsSinceEpoch) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 97 of file tabulatedEphemeris.cpp.
getCartesianStateFromExtendedTime() [4/6]
template<> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< double, Time >::getCartesianStateFromExtendedTime (const Time & time) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 105 of file tabulatedEphemeris.cpp.
getCartesianLongStateFromExtendedTime() [4/6]
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< double, Time >::getCartesianLongStateFromExtendedTime (const Time & time) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 113 of file tabulatedEphemeris.cpp.
getCartesianState() [5/6]
template<> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< long double, Time >::getCartesianState (const double ephemerisTime) virtual
Implements tudat::ephemerides::Ephemeris.
Definition at line 123 of file tabulatedEphemeris.cpp.
getCartesianLongState() [5/6]
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< long double, Time >::getCartesianLongState (const double secondsSinceEpoch) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 131 of file tabulatedEphemeris.cpp.
getCartesianStateFromExtendedTime() [5/6]
template<> Eigen::Vector6d tudat::ephemerides::TabulatedCartesianEphemeris< long double, Time >::getCartesianStateFromExtendedTime (const Time & time) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 139 of file tabulatedEphemeris.cpp.
getCartesianLongStateFromExtendedTime() [5/6]
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::TabulatedCartesianEphemeris< long double, Time >::getCartesianLongStateFromExtendedTime (const Time & time) virtual
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 147 of file tabulatedEphemeris.cpp.
getCartesianState() [6/6]
template<typename StateScalarType = double, typename TimeType = double> virtual Eigen::Vector6d tudat::ephemerides::Ephemeris::getCartesianState
Returns state from ephemeris at given Julian date.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
State from ephemeris.
getCartesianLongState() [6/6]
template<typename StateScalarType = double, typename TimeType = double> virtual Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::Ephemeris::getCartesianLongState inline
Returns state from ephemeris with long double as state scalar at given time. By default, this function casts the double getCartesianState to long double. It may be overridden by derived classes to make use of full long double computations.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
State from ephemeris with long double as state scalar
Definition at line 73 of file ephemeris.h.
getCartesianStateFromExtendedTime() [6/6]
template<typename StateScalarType = double, typename TimeType = double> virtual Eigen::Vector6d tudat::ephemerides::Ephemeris::getCartesianStateFromExtendedTime inline
Returns state from ephemeris with double as state scalar at given time (as custom Time type). By default, this function casts the double getCartesianState to double. It may be overridden by derived classes.
Parameters
currentTime Time at which state is to be evaluated
Returns
State from ephemeris with double as state scalar
Definition at line 88 of file ephemeris.h.
getCartesianLongStateFromExtendedTime() [6/6]
template<typename StateScalarType = double, typename TimeType = double> virtual Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::Ephemeris::getCartesianLongStateFromExtendedTime inline
Returns state from ephemeris with long double as state scalar at given time (as custom Time type). By default, this function casts the double getCartesianState to long double. It may be overridden by derived classes to make use of full long double computations.
Parameters
currentTime Time at which state is to be evaluated
Returns
State from ephemeris with long double as state scalar
Definition at line 102 of file ephemeris.h.
Member Data Documentation
interpolator_
template<typename StateScalarType = double, typename TimeType = double> StateInterpolatorPointer tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::interpolator_ private
Interpolator that returns body state as a function of time by calling the interpolate function (i.e. time as independent variable and states as dependent variables).
Definition at line 190 of file tabulatedEphemeris.h.
Referenced by tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getInterpolator(), tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::getSafeInterpolationInterval(), and tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >::resetInterpolator().
The documentation for this class was generated from the following file:
Astrodynamics/Ephemerides/tabulatedEphemeris.h