Tudat: tudat::simulation_setup::ThrustAccelerationSettings Class Reference
tudat::simulation_setup::ThrustAccelerationSettings Class Reference
Class for providing acceleration settings for a thrust acceleration model.
#include <accelerationSettings.h>
Public Member Functions
ThrustAccelerationSettings (const std::shared_ptr< ThrustDirectionGuidanceSettings > thrustDirectionGuidanceSettings, const std::shared_ptr< ThrustMagnitudeSettings > thrustMagnitudeSettings)
Constructor from separate magnitude and diretion settings.
ThrustAccelerationSettings (const std::shared_ptr< interpolators::DataInterpolationSettings< double, Eigen::Vector3d > > &dataInterpolationSettings, const std::function< double(const double) > specificImpulseFunction, const ThrustFrames thrustFrame=unspecified_thurst_frame, const std::string centralBody="")
Constructor used for defining total thrust vector (in local or inertial frame) from interpolator using variable specific impulse.
ThrustAccelerationSettings (const std::shared_ptr< interpolators::DataInterpolationSettings< double, Eigen::Vector3d > > &dataInterpolationSettings, const double constantSpecificImpulse, const ThrustFrames thrustFrame=unspecified_thurst_frame, const std::string centralBody="")
Constructor used for defining total thrust vector (in local or inertial frame) from interpolator using constant specific impulse.
~ThrustAccelerationSettings ()
Destructor.
Public Member Functions inherited from tudat::simulation_setup::AccelerationSettings
AccelerationSettings (const basic_astrodynamics::AvailableAcceleration accelerationType)
Constructor, sets type of acceleration.
virtual ~AccelerationSettings ()
Destructor.
Public Attributes
std::string centralBody_
Central body identifier for thrustFrame.
double constantSpecificImpulse_ = TUDAT_NAN
std::shared_ptr< interpolators::DataInterpolationSettings< double, Eigen::Vector3d > > dataInterpolationSettings_
Settings to create the interpolator interface.
std::shared_ptr< FullThrustInterpolationInterface > interpolatorInterface_
Interface object used when full thrust (direction and magnitude) are defined by a single user-supplied interpolation.
std::shared_ptr< ThrustDirectionGuidanceSettings > thrustDirectionGuidanceSettings_
Settings for the direction of the thrust.
ThrustFrames thrustFrame_
Identifier of frame in which thrust returned by fullThrustInterpolator is expressed.
std::shared_ptr< ThrustMagnitudeSettings > thrustMagnitudeSettings_
Settings for the magnitude of the thrust.
Public Attributes inherited from tudat::simulation_setup::AccelerationSettings
basic_astrodynamics::AvailableAcceleration accelerationType_
Type of acceleration from AvailableAcceleration enum.
Detailed Description
Class for providing acceleration settings for a thrust acceleration model. Settings for the direction and magnitude guidance of the thrust are provided/
Definition at line 346 of file accelerationSettings.h.
Constructor & Destructor Documentation
ThrustAccelerationSettings() [1/3]
tudat::simulation_setup::ThrustAccelerationSettings::ThrustAccelerationSettings (const std::shared_ptr< ThrustDirectionGuidanceSettings > thrustDirectionGuidanceSettings, const std::shared_ptr< ThrustMagnitudeSettings > thrustMagnitudeSettings) inline
Constructor from separate magnitude and diretion settings.
Parameters
thrustDirectionGuidanceSettings Settings for the direction of the thrust
thrustMagnitudeSettings Settings for the magnitude of the thrust
Definition at line 356 of file accelerationSettings.h.
ThrustAccelerationSettings() [2/3]
tudat::simulation_setup::ThrustAccelerationSettings::ThrustAccelerationSettings (const std::shared_ptr< interpolators::DataInterpolationSettings< double, Eigen::Vector3d > > & dataInterpolationSettings, const std::function< double(const double) > specificImpulseFunction, const ThrustFrames thrustFrame = unspecified_thurst_frame, const std::string centralBody = "") inline
Constructor used for defining total thrust vector (in local or inertial frame) from interpolator using variable specific impulse
Parameters
dataInterpolationSettings Settings to create the interpolator that returns the thrust as a function of time in frame defined by thrustFrame
specificImpulseFunction Function returning the specific impulse as a function of time
thrustFrame Identifier of frame in which thrust returned by fullThrustInterpolator is expressed
centralBody Central body identifier for thrustFrame (if needed; empty by default).
Definition at line 375 of file accelerationSettings.h.
References tudat::interpolators::createOneDimensionalInterpolator(), tudat::simulation_setup::FullThrustInterpolationInterface::getThrustDirection(), tudat::simulation_setup::FullThrustInterpolationInterface::getThrustMagnitude(), interpolatorInterface_, tudat::simulation_setup::FullThrustInterpolationInterface::resetTime(), thrustDirectionGuidanceSettings_, and thrustMagnitudeSettings_.
ThrustAccelerationSettings() [3/3]
tudat::simulation_setup::ThrustAccelerationSettings::ThrustAccelerationSettings (const std::shared_ptr< interpolators::DataInterpolationSettings< double, Eigen::Vector3d > > & dataInterpolationSettings, const double constantSpecificImpulse, const ThrustFrames thrustFrame = unspecified_thurst_frame, const std::string centralBody = "") inline
Constructor used for defining total thrust vector (in local or inertial frame) from interpolator using constant specific impulse
Parameters
dataInterpolationSettings Settings to create the interpolator that returns the thrust as a function of time in frame defined by thrustFrame
constantSpecificImpulse Constant specific impulse
thrustFrame Identifier of frame in which thrust returned by fullThrustInterpolator is expressed
centralBody Central body identifier for thrustFrame (if needed; empty by default).
Definition at line 407 of file accelerationSettings.h.
~ThrustAccelerationSettings()
tudat::simulation_setup::ThrustAccelerationSettings::~ThrustAccelerationSettings () inline
Definition at line 423 of file accelerationSettings.h.
Member Data Documentation
thrustDirectionGuidanceSettings_
std::shared_ptr< ThrustDirectionGuidanceSettings > tudat::simulation_setup::ThrustAccelerationSettings::thrustDirectionGuidanceSettings_
Definition at line 427 of file accelerationSettings.h.
Referenced by ThrustAccelerationSettings().
thrustMagnitudeSettings_
std::shared_ptr< ThrustMagnitudeSettings > tudat::simulation_setup::ThrustAccelerationSettings::thrustMagnitudeSettings_
Definition at line 430 of file accelerationSettings.h.
Referenced by ThrustAccelerationSettings().
constantSpecificImpulse_
double tudat::simulation_setup::ThrustAccelerationSettings::constantSpecificImpulse_ = TUDAT_NAN
Constant specific impulse used when determining the direction and magnitude of thrust from an interpolator. NaN if the specific impulse is not constant (i.e. is defined using a std::function).
Definition at line 434 of file accelerationSettings.h.
thrustFrame_
ThrustFrames tudat::simulation_setup::ThrustAccelerationSettings::thrustFrame_
Identifier of frame in which thrust returned by fullThrustInterpolator is expressed. Unspecifief by default, only used if interpolatorInterface_ is set
Definition at line 441 of file accelerationSettings.h.
centralBody_
std::string tudat::simulation_setup::ThrustAccelerationSettings::centralBody_
Central body identifier for thrustFrame. Empty by default, only used if interpolatorInterface_ is set
Definition at line 448 of file accelerationSettings.h.
dataInterpolationSettings_
std::shared_ptr< interpolators::DataInterpolationSettings< double, Eigen::Vector3d > > tudat::simulation_setup::ThrustAccelerationSettings::dataInterpolationSettings_
Definition at line 451 of file accelerationSettings.h.
interpolatorInterface_
std::shared_ptr< FullThrustInterpolationInterface > tudat::simulation_setup::ThrustAccelerationSettings::interpolatorInterface_
Definition at line 454 of file accelerationSettings.h.
Referenced by ThrustAccelerationSettings().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/accelerationSettings.h