Tudat: tudat::gravitation::TimeDependentSphericalHarmonicsGravityField Class Reference
tudat::gravitation::TimeDependentSphericalHarmonicsGravityField Class Reference
Class for time dependent spherical harmonic gravity field.
#include <timeDependentSphericalHarmonicsGravityField.h>
Public Member Functions
TimeDependentSphericalHarmonicsGravityField (const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd &nominalCosineCoefficients, const Eigen::MatrixXd &nominalSineCoefficients, const std::string &fixedReferenceFrame="")
Semi-dummy constructor, used for setting up gravity field and variations.
TimeDependentSphericalHarmonicsGravityField (const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd &nominalCosineCoefficients, const Eigen::MatrixXd &nominalSineCoefficients, const std::shared_ptr< GravityFieldVariationsSet > gravityFieldVariationUpdateSettings, const std::string &fixedReferenceFrame="")
Full class constructor.
~TimeDependentSphericalHarmonicsGravityField ()
Destructor.
void clearVariations ()
Function to clear all gravity field variations.
std::shared_ptr< GravityFieldVariationsSet > getGravityFieldVariationsSet ()
Function to get object containing all gravity field variations and related settings.
Eigen::MatrixXd getNominalCosineCoefficients ()
Get nominal (i.e. with zero variations) cosine coefficients.
Eigen::MatrixXd getNominalSineCoefficients ()
Get nominal (i.e. with zero variations) sine coefficients.
Eigen::MatrixXd getTotalCosineCoefficientCorrection (const int maximumDegree, const int maximumOrder)
Get current total correction to cosine coefficients.
Eigen::MatrixXd getTotalSineCoefficientCorrection (const int maximumDegree, const int maximumOrder)
Get current total correction to sine coefficients.
void setFieldVariationSettings (const std::shared_ptr< GravityFieldVariationsSet > gravityFieldVariationUpdateSettings, const bool updateCorrections=1)
Function to (re)set the gravity field variations.
void setNominalCosineCoefficient (const int degree, const int order, const double coefficient)
Set nominal (i.e. with zero variations) cosine coefficient of given degree and order.
void setNominalCosineCoefficients (Eigen::MatrixXd nominalCosineCoefficients)
Set nominal (i.e. with zero variations) cosine coefficients.
void setNominalSineCoefficient (const int degree, const int order, const double coefficient)
Set nominal (i.e. with zero variations) sine coefficient of given degree and order.
void setNominalSineCoefficients (const Eigen::MatrixXd &nominalSineCoefficients)
Set nominal (i.e. with zero variations) sine coefficients.
void update (const double time)
Update gravity field to current time.
void updateCorrectionFunctions ()
Update correction functions.
Public Member Functions inherited from tudat::gravitation::SphericalHarmonicsGravityField
SphericalHarmonicsGravityField (const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd &cosineCoefficients=Eigen::MatrixXd::Identity(1, 1), const Eigen::MatrixXd &sineCoefficients=Eigen::MatrixXd::Zero(1, 1), const std::string &fixedReferenceFrame="")
Class constructor.
virtual ~SphericalHarmonicsGravityField ()
Virtual destructor.
Eigen::MatrixXd getCosineCoefficients ()
Function to get the cosine spherical harmonic coefficients (geodesy normalized)
Eigen::MatrixXd getCosineCoefficientsBlock (const int maximumDegree, const int maximumOrder)
Function to get a cosine spherical harmonic coefficient block (geodesy normalized)
double getDegreeOfExpansion ()
Get maximum degree of spherical harmonics gravity field expansion.
std::string getFixedReferenceFrame ()
Function to retrieve the tdentifier for body-fixed reference frame.
Eigen::Vector3d getGradientOfPotential (const Eigen::Vector3d &bodyFixedPosition)
Get the gradient of the potential.
Eigen::Vector3d getGradientOfPotential (const Eigen::Vector3d &bodyFixedPosition, const double maximumDegree, const double maximumOrder)
Get the gradient of the potential.
double getGravitationalPotential (const Eigen::Vector3d &bodyFixedPosition)
Function to calculate the gravitational potential at a given point.
double getGravitationalPotential (const Eigen::Vector3d &bodyFixedPosition, const double maximumDegree, const double maximumOrder, const double minimumDegree=0, const double minimumOrder=0)
Function to calculate the gravitational potential due to terms up to given degree and order due to this body at a given point.
double getOrderOfExpansion ()
Get maximum order of spherical harmonics gravity field expansion.
double getReferenceRadius ()
Function to get the reference radius.
Eigen::MatrixXd getSineCoefficients ()
Function to get the sine spherical harmonic coefficients (geodesy normalized)
Eigen::MatrixXd getSineCoefficientsBlock (const int maximumDegree, const int maximumOrder)
Function to get a sine spherical harmonic coefficient block (geodesy normalized)
void setCosineCoefficients (const Eigen::MatrixXd &cosineCoefficients)
Function to reset the cosine spherical harmonic coefficients (geodesy normalized)
void setSineCoefficients (const Eigen::MatrixXd &sineCoefficients)
Function to reset the cosine spherical harmonic coefficients (geodesy normalized)
Public Member Functions inherited from tudat::gravitation::GravityFieldModel
GravityFieldModel (const double gravitationalParameter)
Default constructor.
virtual ~GravityFieldModel ()
Default destructor.
double getGravitationalParameter ()
Get the gravitational parameter.
double getGravitationalPotential (const Eigen::Vector3d &bodyFixedPosition)
Get the gravitational potential at given body-fixed position.
void resetGravitationalParameter (const double gravitationalParameter)
Set the gravitational parameter.
Private Attributes
std::vector< std::function< void(const double, Eigen::MatrixXd &, Eigen::MatrixXd &) > > correctionFunctions_
List of update functions which are called when calculating current gravity field variations.
std::shared_ptr< GravityFieldVariationsSet > gravityFieldVariationsSet_
Object containing all GravityFieldVariations objects and update settings.
Eigen::MatrixXd nominalCosineCoefficients_
Nominal (i.e. with zero variations) sine coefficients.
Eigen::MatrixXd nominalSineCoefficients_
Nominal (i.e. with zero variations) cosine coefficients.
Additional Inherited Members
Protected Attributes inherited from tudat::gravitation::SphericalHarmonicsGravityField
Eigen::MatrixXd cosineCoefficients_
Cosine spherical harmonic coefficients (geodesy normalized)
std::string fixedReferenceFrame_
Identifier for body-fixed reference frame.
double referenceRadius_
Reference radius of spherical harmonic field expansion.
Eigen::MatrixXd sineCoefficients_
Sine spherical harmonic coefficients (geodesy normalized)
std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache_
Cache object for potential calculations.
Protected Attributes inherited from tudat::gravitation::GravityFieldModel
double gravitationalParameter_
Gravitational parameter.
Detailed Description
Class for time dependent spherical harmonic gravity field, i.e where the sine and cosine coefficients are functions of time. This class combines nominal values with time-dependent variations, which are calculated by object of GravityFieldVariation derived classes (one object per variation). All spherical harmonic coefficients used in this class, as well as the variations, are implicitly assumed to be geodesy-normalized.
Definition at line 39 of file timeDependentSphericalHarmonicsGravityField.h.
Constructor & Destructor Documentation
TimeDependentSphericalHarmonicsGravityField() [1/2]
tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::TimeDependentSphericalHarmonicsGravityField (const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd & nominalCosineCoefficients, const Eigen::MatrixXd & nominalSineCoefficients, const std::string & fixedReferenceFrame = "") inline
Semi-dummy constructor, used for setting up gravity field and variations. This constructor is neede, as some gravity field variations need to be linked to properties of the nominal gravity field (for instance gravitational parameter), but the complete object of this type cannot be created until all variations are created, causing a circular dependency. The object is fully created when subsequently calling the setFieldVariationSettings function and setting the field variation objects.
Parameters
gravitationalParameter Gravitational parameter of massive body.
referenceRadius Reference radius of spherical harmonic field expansion.
nominalCosineCoefficients Nominal (i.e. with zero variation) cosine spherical harmonic coefficients.
nominalSineCoefficients Nominal (i.e. with zero variation) sine spherical harmonic coefficients.
fixedReferenceFrame Identifier for body-fixed reference frame to which the field is fixed (optional).
Definition at line 60 of file timeDependentSphericalHarmonicsGravityField.h.
TimeDependentSphericalHarmonicsGravityField() [2/2]
tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::TimeDependentSphericalHarmonicsGravityField (const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd & nominalCosineCoefficients, const Eigen::MatrixXd & nominalSineCoefficients, const std::shared_ptr< GravityFieldVariationsSet > gravityFieldVariationUpdateSettings, const std::string & fixedReferenceFrame = "") inline
Full class constructor.
Parameters
gravitationalParameter Gravitational parameter of massive body.
referenceRadius Reference radius of spherical harmonic field expansion.
nominalCosineCoefficients Nominal (i.e. with zero variation) cosine spherical harmonic coefficients.
nominalSineCoefficients Nominal (i.e. with zero variation) sine spherical harmonic coefficients.
gravityFieldVariationUpdateSettings Object containing all gravity field variations and related settings.
fixedReferenceFrame Identifier for body-fixed reference frame to which the field is fixed (optional).
Definition at line 86 of file timeDependentSphericalHarmonicsGravityField.h.
References updateCorrectionFunctions().
~TimeDependentSphericalHarmonicsGravityField()
tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::~TimeDependentSphericalHarmonicsGravityField () inline
Destructor
Definition at line 106 of file timeDependentSphericalHarmonicsGravityField.h.
Member Function Documentation
update()
void tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::update (const double time)
Update gravity field coefficient corrections to current time. All correction functions are called and subsequently added to the nominal value.
Parameters
time Current time.
Definition at line 45 of file timeDependentSphericalHarmonicsGravityField.cpp.
References correctionFunctions_, tudat::gravitation::SphericalHarmonicsGravityField::cosineCoefficients_, nominalCosineCoefficients_, nominalSineCoefficients_, and tudat::gravitation::SphericalHarmonicsGravityField::sineCoefficients_.
updateCorrectionFunctions()
void tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::updateCorrectionFunctions () inline
Update correction functions, for instance to account for changed changed environmental parameters.
Definition at line 121 of file timeDependentSphericalHarmonicsGravityField.h.
References correctionFunctions_, and gravityFieldVariationsSet_.
Referenced by setFieldVariationSettings(), and TimeDependentSphericalHarmonicsGravityField().
setFieldVariationSettings()
void tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::setFieldVariationSettings (const std::shared_ptr< GravityFieldVariationsSet > gravityFieldVariationUpdateSettings, const bool updateCorrections = 1)
Function to (re)set the gravity field variations object. An option is provided for determining whether or not the variations should be immediately recalculated.
Parameters
gravityFieldVariationUpdateSettings Object storing all variation models and associated settings.
updateCorrections Flag to determine whether the gravity field variation functions should be immediately updated with new settings.
Definition at line 22 of file timeDependentSphericalHarmonicsGravityField.cpp.
References gravityFieldVariationsSet_, and updateCorrectionFunctions().
clearVariations()
void tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::clearVariations ()
Function to clear all gravity field variations, the gravityFieldVariationsSet_ is set to nullptr, and the correctionFunctions_ list is cleared.
Definition at line 37 of file timeDependentSphericalHarmonicsGravityField.cpp.
References correctionFunctions_, and gravityFieldVariationsSet_.
getNominalCosineCoefficients()
Eigen::MatrixXd tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getNominalCosineCoefficients () inline
Function to get nominal (i.e. with zero variations) cosine coefficients.
Returns
Nominal cosine coefficients.
Definition at line 161 of file timeDependentSphericalHarmonicsGravityField.h.
References nominalCosineCoefficients_.
Referenced by tudat::simulation_setup::createVectorParameterToEstimate().
getTotalCosineCoefficientCorrection()
Eigen::MatrixXd tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getTotalCosineCoefficientCorrection (const int maximumDegree, const int maximumOrder) inline
Get current total correction to cosine coefficients up to given degree and order
Parameters
maximumDegree Maximum degree of coefficients
maximumOrder Maximum order of coefficients
Returns
Total correction to cosine coefficients up to given degree and order
Definition at line 173 of file timeDependentSphericalHarmonicsGravityField.h.
References tudat::gravitation::SphericalHarmonicsGravityField::cosineCoefficients_, and nominalCosineCoefficients_.
Referenced by tudat::propagators::getVectorDependentVariableFunction().
getTotalSineCoefficientCorrection()
Eigen::MatrixXd tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getTotalSineCoefficientCorrection (const int maximumDegree, const int maximumOrder) inline
Get current total correction to sine coefficients up to given degree and order
Parameters
maximumDegree Maximum degree of coefficients
maximumOrder Maximum order of coefficients
Returns
Total correction to sine coefficients up to given degree and order
Definition at line 187 of file timeDependentSphericalHarmonicsGravityField.h.
References nominalSineCoefficients_, and tudat::gravitation::SphericalHarmonicsGravityField::sineCoefficients_.
Referenced by tudat::propagators::getVectorDependentVariableFunction().
setNominalCosineCoefficients()
void tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::setNominalCosineCoefficients (Eigen::MatrixXd nominalCosineCoefficients) inline
Function to set nominal (i.e. with zero variations) cosine coefficients.
Parameters
nominalCosineCoefficients New nominal cosine coefficients.
Definition at line 200 of file timeDependentSphericalHarmonicsGravityField.h.
References nominalCosineCoefficients_.
Referenced by tudat::simulation_setup::createVectorParameterToEstimate().
setNominalCosineCoefficient()
void tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::setNominalCosineCoefficient (const int degree, const int order, const double coefficient) inline
Set nominal (i.e. with zero variations) cosine coefficients of given degree and order.
Parameters
degree Spherical harmonic degree.
order Spherical harmonic order.
coefficient New cosine coefficient for given degree and order.
Definition at line 212 of file timeDependentSphericalHarmonicsGravityField.h.
References nominalCosineCoefficients_.
getNominalSineCoefficients()
Eigen::MatrixXd tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getNominalSineCoefficients () inline
Function to get nominal (i.e. with zero variations) sine coefficients.
Returns
Nominal sine coefficients.
Definition at line 230 of file timeDependentSphericalHarmonicsGravityField.h.
References nominalSineCoefficients_.
Referenced by tudat::simulation_setup::createVectorParameterToEstimate().
setNominalSineCoefficients()
void tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::setNominalSineCoefficients (const Eigen::MatrixXd & nominalSineCoefficients) inline
Function to set nominal (i.e. with zero variations) sine coefficients.
Parameters
nominalSineCoefficients New nominal sine coefficients.
Definition at line 240 of file timeDependentSphericalHarmonicsGravityField.h.
References nominalSineCoefficients_.
Referenced by tudat::simulation_setup::createVectorParameterToEstimate().
setNominalSineCoefficient()
void tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::setNominalSineCoefficient (const int degree, const int order, const double coefficient) inline
Set nominal (i.e. with zero variations) sine coefficients of given degree and order.
Parameters
degree Spherical harmonic degree.
order Spherical harmonic order.
coefficient New sine coefficient for given degree and order.
Definition at line 252 of file timeDependentSphericalHarmonicsGravityField.h.
References nominalSineCoefficients_.
getGravityFieldVariationsSet()
std::shared_ptr< GravityFieldVariationsSet > tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::getGravityFieldVariationsSet () inline
Function to get object containing all gravity field variations and related settings
Definition at line 269 of file timeDependentSphericalHarmonicsGravityField.h.
References gravityFieldVariationsSet_.
Member Data Documentation
nominalSineCoefficients_
Eigen::MatrixXd tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::nominalSineCoefficients_ private
Nominal (i.e. with zero variations) cosine coefficients. When calling the update function, all corrections are calculated and the sum of these corrections and this nominal value is set as cosineCoefficients_ base class member.
Definition at line 282 of file timeDependentSphericalHarmonicsGravityField.h.
Referenced by getNominalSineCoefficients(), getTotalSineCoefficientCorrection(), setNominalSineCoefficient(), setNominalSineCoefficients(), and update().
nominalCosineCoefficients_
Eigen::MatrixXd tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::nominalCosineCoefficients_ private
Nominal (i.e. with zero variations) sine coefficients. When calling the update function, all corrections are calculated and the sum of these corrections and this nominal value is set as sineCoefficients_ base class member.
Definition at line 290 of file timeDependentSphericalHarmonicsGravityField.h.
Referenced by getNominalCosineCoefficients(), getTotalCosineCoefficientCorrection(), setNominalCosineCoefficient(), setNominalCosineCoefficients(), and update().
correctionFunctions_
std::vector< std::function< void(const double, Eigen::MatrixXd&, Eigen::MatrixXd&) > > tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::correctionFunctions_ private
List of update functions which are called when calculating current gravity field variations. Functions are either linked to PairInterpolationInterface, which contains an interpolator created from a GravityFieldVariations object, or the addSphericalHarmonicsCorrections of the GravityFieldVariations object directly.
Definition at line 300 of file timeDependentSphericalHarmonicsGravityField.h.
Referenced by clearVariations(), update(), and updateCorrectionFunctions().
gravityFieldVariationsSet_
std::shared_ptr< GravityFieldVariationsSet > tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::gravityFieldVariationsSet_ private
Object containing all GravityFieldVariations objects and update settings (i.e. time settings for interpolator)
Definition at line 307 of file timeDependentSphericalHarmonicsGravityField.h.
Referenced by clearVariations(), getGravityFieldVariationsSet(), setFieldVariationSettings(), and updateCorrectionFunctions().
The documentation for this class was generated from the following files:
Astrodynamics/Gravitation/timeDependentSphericalHarmonicsGravityField.h
Astrodynamics/Gravitation/timeDependentSphericalHarmonicsGravityField.cpp