Tudat: tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType > Class Template Reference
tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType > Class Template Reference
Class for performing full numerical integration of a dynamical system over multiple arcs.
#include <dynamicsSimulator.h>
Public Member Functions
MultiArcDynamicsSimulator (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::vector< double > arcStartTimes, const bool areEquationsOfMotionToBeIntegrated=true, const bool clearNumericalSolutions=true, const bool setIntegratedResult=true)
Constructor of multi-arc simulator for same integration settings per arc.
MultiArcDynamicsSimulator (const simulation_setup::NamedBodyMap &bodyMap, const std::vector< std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const bool areEquationsOfMotionToBeIntegrated=true, const bool clearNumericalSolutions=true, const bool setIntegratedResult=true)
Constructor of multi-arc simulator for different integration settings per arc.
~MultiArcDynamicsSimulator ()
Destructor.
std::vector< double > getArcStartTimes ()
Function to retrieve the current state and end times of the arcs.
std::vector< std::map< TimeType, double > > getCumulativeComputationTimeHistory ()
std::vector< std::map< TimeType, double > > getCumulativeComputationTimeHistoryBase ()
std::vector< std::map< TimeType, Eigen::VectorXd > > getDependentVariableHistory ()
Function to return the numerical solution of the dependent variables.
std::vector< std::map< TimeType, Eigen::VectorXd > > getDependentVariableNumericalSolutionBase ()
Function to return the numerical solution of the dependent variables (base class interface)
std::vector< std::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > > getDynamicsStateDerivative ()
Function to get the list of DynamicsStateDerivativeModel objects used for each arc.
std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > getEquationsOfMotionNumericalSolution ()
Function to return the numerical solution to the equations of motion.
std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > getEquationsOfMotionNumericalSolutionBase ()
Function to return the numerical solution to the equations of motion (base class interface).
std::vector< std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > > getSingleArcDynamicsSimulators ()
Function to get the list of DynamicsSimulator objects used for each arc.
void integrateEquationsOfMotion (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &concatenatedInitialStates)
This function numerically (re-)integrates the equations of motion, using concatenated states for all arcs.
void integrateEquationsOfMotion (const std::vector< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &initialStatesList)
This function numerically (re-)integrates the equations of motion, using separate states for all arcs.
virtual bool integrationCompletedSuccessfully () const
Get whether the integration was completed successfully.
void manuallySetAndProcessRawNumericalEquationsOfMotionSolution (std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > &equationsOfMotionNumericalSolution, std::vector< std::map< TimeType, Eigen::VectorXd > > &dependentVariableHistory)
Function to reset the environment using an externally provided list of (numerically integrated) states.
Public Member Functions inherited from tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >
DynamicsSimulator (const simulation_setup::NamedBodyMap &bodyMap, const bool clearNumericalSolutions=true, const bool setIntegratedResult=true)
Constructor of simulator.
virtual ~DynamicsSimulator ()
Virtual destructor.
simulation_setup::NamedBodyMap getNamedBodyMap ()
Function to get the map of named bodies involved in simulation.
void resetNamedBodyMap (const simulation_setup::NamedBodyMap &bodyMap)
Function to reset the named body map.
void resetSetIntegratedResult (const bool setIntegratedResult)
Protected Member Functions
void processNumericalEquationsOfMotionSolution ()
This function updates the environment with the numerical solution of the propagation.
Protected Attributes
std::vector< double > arcStartTimes_
List of start times of each arc. NOTE: This list is updated after every propagation.
std::vector< std::map< TimeType, double > > cumulativeComputationTimeHistory_
std::vector< std::map< TimeType, Eigen::VectorXd > > dependentVariableHistory_
List of maps of dependent variable history that was saved during numerical propagation.
std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > equationsOfMotionNumericalSolution_
List of maps of state history of numerically integrated states.
std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > multiArcPropagatorSettings_
Propagator settings used by this objec.
std::vector< std::shared_ptr< PropagationTerminationDetails > > propagationTerminationReasons_
Event that triggered the termination of the propagation.
std::vector< std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > > singleArcDynamicsSimulators_
Objects used to compute the dynamics of the sepatrate arcs.
Protected Attributes inherited from tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >
simulation_setup::NamedBodyMap bodyMap_
Map of bodies (with names) of all bodies in integration.
bool clearNumericalSolutions_
bool setIntegratedResult_
Boolean to determine whether to automatically use the integrated results to set ephemerides.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >
Class for performing full numerical integration of a dynamical system over multiple arcs, equations of motion are set up for each arc (and need not be equal for each arc). In this class, the governing equations are set once, but can be re-integrated for different initial conditions using the same instance of the class.
Definition at line 928 of file dynamicsSimulator.h.
Constructor & Destructor Documentation
MultiArcDynamicsSimulator() [1/2]
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::vector< double > arcStartTimes, const bool areEquationsOfMotionToBeIntegrated = true, const bool clearNumericalSolutions = true, const bool setIntegratedResult = true) inline
Constructor of multi-arc simulator for same integration settings per arc.
Parameters
bodyMap Map of bodies (with names) of all bodies in integration.
integratorSettings Integrator settings for numerical integrator, used for all arcs.
propagatorSettings Propagator settings for dynamics (must be of multi arc type)
arcStartTimes Times at which the separate arcs start
areEquationsOfMotionToBeIntegrated Boolean to denote whether equations of motion should be integrated at the end of the contructor or not.
clearNumericalSolutions Boolean to determine whether to clear the raw numerical solution member variables after propagation and resetting ephemerides (default true).
setIntegratedResult Boolean to determine whether to automatically use the integrated results to set ephemerides (default true).
Definition at line 949 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::arcStartTimes_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::cumulativeComputationTimeHistory_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariableHistory_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::equationsOfMotionNumericalSolution_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::multiArcPropagatorSettings_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::propagationTerminationReasons_, and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_.
MultiArcDynamicsSimulator() [2/2]
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator (const simulation_setup::NamedBodyMap & bodyMap, const std::vector< std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const bool areEquationsOfMotionToBeIntegrated = true, const bool clearNumericalSolutions = true, const bool setIntegratedResult = true) inline
Constructor of multi-arc simulator for different integration settings per arc.
Parameters
bodyMap Map of bodies (with names) of all bodies in integration.
integratorSettings List of integrator settings for numerical integrator, defined per arc.
propagatorSettings Propagator settings for dynamics (must be of multi arc type)
areEquationsOfMotionToBeIntegrated Boolean to denote whether equations of motion should be integrated at the end of the contructor or not.
clearNumericalSolutions Boolean to determine whether to clear the raw numerical solution member variables after propagation and resetting ephemerides (default true).
setIntegratedResult Boolean to determine whether to automatically use the integrated results to set ephemerides (default true).
Definition at line 1014 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::arcStartTimes_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::cumulativeComputationTimeHistory_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariableHistory_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::equationsOfMotionNumericalSolution_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::multiArcPropagatorSettings_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::propagationTerminationReasons_, and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_.
~MultiArcDynamicsSimulator()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::~MultiArcDynamicsSimulator () inline
Definition at line 1065 of file dynamicsSimulator.h.
Member Function Documentation
integrateEquationsOfMotion() [1/2]
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & concatenatedInitialStates) inline virtual
This function numerically (re-)integrates the equations of motion, using the settings set through the constructor and a new initial state vector provided here. The raw results are set in the equationsOfMotionNumericalSolution_
Parameters
concatenatedInitialStates Initial state vector that is to be used for numerical integration. Note that this state should be in the correct frame (i.e. corresponding to centralBodies in propagatorSettings_), but not in the propagator- specific form (i.e Encke, Gauss, etc. for translational dynamics). The states for all arcs must be concatenated in order into a single Eigen Vector.
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 1076 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator().
integrateEquationsOfMotion() [2/2]
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion (const std::vector< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & initialStatesList) inline
This function numerically (re-)integrates the equations of motion, using the settings set through the constructor and a new initial state vector provided here. The raw results are set in the equationsOfMotionNumericalSolution_
Parameters
initialStatesList Initial state vector that is to be used for numerical integration. Note that this state should be in the correct frame (i.e. corresponding to centralBodies in propagatorSettings_), but not in the propagator- specific form (i.e Encke, Gauss, etc. for translational dynamics). The states for all stored, in order, in the input std vector.
Definition at line 1106 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::arcStartTimes_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::cumulativeComputationTimeHistory_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariableHistory_, tudat::linear_algebra::doesMatrixHaveNanEntries(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::equationsOfMotionNumericalSolution_, tudat::propagators::getArcInitialStateFromPreviousArcResult(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::multiArcPropagatorSettings_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::propagationTerminationReasons_, tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::setIntegratedResult_, and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_.
getEquationsOfMotionNumericalSolution()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution () inline
Function to return the numerical solution to the equations of motion for last numerical integration. Each vector entry denotes one arc. Key of map denotes time, values are full propagated state vectors.
Returns
List of maps of history of numerically integrated states.
Definition at line 1181 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::equationsOfMotionNumericalSolution_.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolutionBase().
getDependentVariableHistory()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, Eigen::VectorXd > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableHistory () inline
Function to return the numerical solution of the dependent variables for last numerical integration. Each vector entry denotes one arc. Key of map denotes time, values are dependent variable vectors
Returns
List of maps of dependent variable history
Definition at line 1192 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariableHistory_.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableNumericalSolutionBase().
getCumulativeComputationTimeHistory()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, double > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getCumulativeComputationTimeHistory () inline
Definition at line 1197 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::cumulativeComputationTimeHistory_.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getCumulativeComputationTimeHistoryBase().
getEquationsOfMotionNumericalSolutionBase()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolutionBase () inline virtual
Function to return the numerical solution to the equations of motion for last numerical integration. Each vector entry denotes one arc. Key of map denotes time, values are full propagated state vectors.
Returns
List of maps of history of numerically integrated states.
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 1209 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution().
getDependentVariableNumericalSolutionBase()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, Eigen::VectorXd > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableNumericalSolutionBase () inline virtual
Function to return the numerical solution of the dependent variables for last numerical integration. Each vector entry denotes one arc. Key of map denotes time, values are dependent variable vectors
Returns
List of maps of dependent variable history
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 1220 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableHistory().
getCumulativeComputationTimeHistoryBase()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, double > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getCumulativeComputationTimeHistoryBase () inline virtual
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 1225 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getCumulativeComputationTimeHistory().
manuallySetAndProcessRawNumericalEquationsOfMotionSolution()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::manuallySetAndProcessRawNumericalEquationsOfMotionSolution (std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > & equationsOfMotionNumericalSolution, std::vector< std::map< TimeType, Eigen::VectorXd > > & dependentVariableHistory) inline
Function to reset the environment using an externally provided list of (numerically integrated) states, for instance provided by a variational equations solver.
Parameters
equationsOfMotionNumericalSolution Vector of state histories (externally provided equationsOfMotionNumericalSolution_)
dependentVariableHistory Vector of dependent variable histories (externally provided dependentVariableHistory_)
Definition at line 1239 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::arcStartTimes_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariableHistory_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::equationsOfMotionNumericalSolution_, and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution().
getDynamicsStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getDynamicsStateDerivative () inline
Function to get the list of DynamicsStateDerivativeModel objects used for each arc
Returns
List of DynamicsStateDerivativeModel objects used for each arc
Definition at line 1273 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_.
getSingleArcDynamicsSimulators()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getSingleArcDynamicsSimulators () inline
Function to get the list of DynamicsSimulator objects used for each arc
Returns
List of DynamicsSimulator objects used for each arc
Definition at line 1288 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_.
getArcStartTimes()
template<typename StateScalarType = double, typename TimeType = double> std::vector< double > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getArcStartTimes () inline
Function to retrieve the current state and end times of the arcs
Returns
The current state and end times of the arcs
Definition at line 1298 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::arcStartTimes_.
integrationCompletedSuccessfully()
template<typename StateScalarType = double, typename TimeType = double> virtual bool tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrationCompletedSuccessfully () const inline virtual
Get whether the integration was completed successfully.
Returns
Whether the integration was completed successfully by reaching the termination condition.
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 1308 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_.
processNumericalEquationsOfMotionSolution()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution () inline protected virtual
This function updates the environment with the numerical solution of the propagation. It sets the propagated dynamics solution as the new input for e.g., the ephemeris object of the boies that were propagated (for translational states).
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 1330 of file dynamicsSimulator.h.
References tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::arcStartTimes_, tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::clearNumericalSolutions_, tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::equationsOfMotionNumericalSolution_, tudat::propagators::resetIntegratedMultiArcStatesWithEqualArcDynamics(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::manuallySetAndProcessRawNumericalEquationsOfMotionSolution().
Member Data Documentation
equationsOfMotionNumericalSolution_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::equationsOfMotionNumericalSolution_ protected
List of maps of state history of numerically integrated states. Each entry in the list contains data on a single arc. Key of map denotes time, values are concatenated vectors of body states in order of bodiesToIntegrate
Definition at line 1351 of file dynamicsSimulator.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::manuallySetAndProcessRawNumericalEquationsOfMotionSolution(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution().
dependentVariableHistory_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, Eigen::VectorXd > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariableHistory_ protected
Definition at line 1354 of file dynamicsSimulator.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableHistory(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::manuallySetAndProcessRawNumericalEquationsOfMotionSolution(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator().
cumulativeComputationTimeHistory_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, double > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::cumulativeComputationTimeHistory_ protected
Definition at line 1356 of file dynamicsSimulator.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getCumulativeComputationTimeHistory(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator().
singleArcDynamicsSimulators_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::singleArcDynamicsSimulators_ protected
Definition at line 1359 of file dynamicsSimulator.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getDynamicsStateDerivative(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getSingleArcDynamicsSimulators(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrationCompletedSuccessfully(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution().
arcStartTimes_
template<typename StateScalarType = double, typename TimeType = double> std::vector< double > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::arcStartTimes_ protected
Definition at line 1362 of file dynamicsSimulator.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::getArcStartTimes(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::manuallySetAndProcessRawNumericalEquationsOfMotionSolution(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution().
propagationTerminationReasons_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< PropagationTerminationDetails > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::propagationTerminationReasons_ protected
Definition at line 1365 of file dynamicsSimulator.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator().
multiArcPropagatorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< MultiArcPropagatorSettings< StateScalarType > > tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::multiArcPropagatorSettings_ protected
Definition at line 1368 of file dynamicsSimulator.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/dynamicsSimulator.h