Tudat: tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType > Class Template Reference
tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType > Class Template Reference
Absolute or relative tolerance for root termination condition.
#include <terminationConditions.h>
Public Member Functions
RootAbsoluteOrRelativeToleranceTerminationCondition (const ScalarType anAbsoluteTolerance=1.0e-15, const ScalarType aRelativeTolerance=1.0e-12, const unsigned int aMaximumNumberOfIterations=1000, const bool aThrowRunTimeExceptionFlag=true)
Default constructor, taking a root absolute tolerance (default=1.0e-15), root relative tolerance (default=1.0e-12), a specified maximum number of iterations (default=1000) and a flag indicating if a run-time exception should be thrown if this number is exceeded (default=true).
bool checkTerminationCondition (const ScalarType currentRootGuess, const ScalarType previousRootGuess, const ScalarType currentRootFunctionValue, const ScalarType previousRootFunctionValue, const unsigned int numberOfIterations)
Check termination condition (combined ans. and rel. tolerance and max. itetations)
Public Member Functions inherited from tudat::root_finders::termination_conditions::TerminationConditionBase< ScalarType >
virtual ~TerminationConditionBase ()
Virtual destructor.
Private Attributes
const ScalarType absoluteTolerance
Absolute tolerance.
const unsigned int maximumNumberOfIterations
Maximum number of iterations.
const ScalarType relativeTolerance
Relative tolerance.
const bool throwRunTimeException
Flag indicating if run-time exception should be thrown.
Detailed Description
template<typename ScalarType = double>
class tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >
This class implements the TerminationCondition base class to check if the absolute or relative tolerance for the root value computed by the root-finder that this class is used in conjunction with has been reached. Additionally, this termination condition also checks if the maximum number of iterations has been exceeded. This class effectively serves as a wrapper for the checkRootAbsoluteTolerance()-, checkRootRelativeTolerance()- and checkMaximumIterationsExceeded()-functions.
See also
checkRootAbsoluteTolerance(), checkRootRelativeTolerance(), checkMaximumIterationsExceeded().
Definition at line 325 of file terminationConditions.h.
Constructor & Destructor Documentation
RootAbsoluteOrRelativeToleranceTerminationCondition()
template<typename ScalarType = double> tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::RootAbsoluteOrRelativeToleranceTerminationCondition (const ScalarType anAbsoluteTolerance = 1.0e-15, const ScalarType aRelativeTolerance = 1.0e-12, const unsigned int aMaximumNumberOfIterations = 1000, const bool aThrowRunTimeExceptionFlag = true) inline
Default constructor, taking root absolute and relative tolerances, maximum number of iterations and run-time exception flag.
Parameters
anAbsoluteTolerance A absolute tolerance (default=1.0e-12).
aRelativeTolerance A relative tolerance (default=1.0e-12).
aMaximumNumberOfIterations Maximum number of iterations (default=1000).
aThrowRunTimeExceptionFlag Flag that indicates if run-time error should be triggered if maximum number of iterations is exceeded (default=true).
Definition at line 343 of file terminationConditions.h.
Member Function Documentation
checkTerminationCondition()
template<typename ScalarType = double> bool tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition (const ScalarType currentRootGuess, const ScalarType previousRootGuess, const ScalarType currentRootFunctionValue, const ScalarType previousRootFunctionValue, const unsigned int numberOfIterations) inline virtual
Check termination condition (wrapper for checkRootRelativeTolerance()- checkRootAbsoluteTolerance()- and checkMaximumIterationsExceeded()-functions).
Parameters
currentRootGuess Current root value.
previousRootGuess Previous root value.
currentRootFunctionValue Current root function value (not used, included for base class compatibility).
previousRootFunctionValue Previous root function value (not used, included for base class compatibility).
numberOfIterations Number of iterations that have been completed.
Returns
Flag indicating if termination condition has been reached.
Implements tudat::root_finders::termination_conditions::TerminationConditionBase< ScalarType >.
Definition at line 367 of file terminationConditions.h.
References tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::absoluteTolerance, tudat::root_finders::termination_conditions::checkMaximumIterationsExceeded(), tudat::root_finders::termination_conditions::checkRootAbsoluteTolerance(), tudat::root_finders::termination_conditions::checkRootRelativeTolerance(), tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::maximumNumberOfIterations, tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::relativeTolerance, and tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::throwRunTimeException.
Member Data Documentation
absoluteTolerance
template<typename ScalarType = double> const ScalarType tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::absoluteTolerance private
Definition at line 383 of file terminationConditions.h.
Referenced by tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition().
relativeTolerance
template<typename ScalarType = double> const ScalarType tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::relativeTolerance private
Definition at line 386 of file terminationConditions.h.
Referenced by tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition().
maximumNumberOfIterations
template<typename ScalarType = double> const unsigned int tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::maximumNumberOfIterations private
Definition at line 389 of file terminationConditions.h.
Referenced by tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition().
throwRunTimeException
template<typename ScalarType = double> const bool tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::throwRunTimeException private
Definition at line 392 of file terminationConditions.h.
Referenced by tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition().
The documentation for this class was generated from the following file:
Mathematics/RootFinders/terminationConditions.h