Tudat: tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType > Class Template Reference
tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType > Class Template Reference
Class that combines a series of translational and rotational ephemeris functions.
#include <compositeEphemeris.h>
Public Types
typedef Eigen::Matrix< StateScalarType, 6, 1 > StateType
Public Member Functions
CompositeEphemeris (const std::map< int, std::function< StateType(const TimeType &) > > translationalEphemerides, const std::map< int, std::function< StateType(const TimeType, const StateType &) > > rotationalEphemerides, const std::string referenceFrameOrigin="SSB", const std::string referenceFrameOrientation="ECLIPJ2000")
Constructor from series of translational and rotational ephemeris functions.
CompositeEphemeris (const std::map< int, std::pair< std::function< StateType(const TimeType &) >, bool > > translationalEphemerides, const std::map< int, std::function< StateType(const TimeType, const StateType &) > > rotationalEphemerides, const std::string referenceFrameOrigin="SSB", const std::string referenceFrameOrientation="ECLIPJ2000")
Constructor from series of translational and rotational ephemeris functions.
~CompositeEphemeris ()
Destructor.
void addTranslationalEphemeris (const std::function< StateType(const TimeType &) > stateFunction, const int add=1)
Add an additional translational ephemeris at the end of the chain.
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get state from ephemeris (with long double as state scalar).
Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get state from ephemeris (with long double as state scalar).
Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with long double as state scalar and Time as time type).
virtual Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)=0
Get state from ephemeris.
Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)
Get state from ephemeris.
Eigen::Matrix< double, 6, 1 > getCartesianStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with double as state scalar and Time as time type).
template<typename OutputTimeType , typename OutputStateScalarType >
Eigen::Matrix< OutputStateScalarType, 6, 1 > getTemplatedCartesianStateFromCompositeEphemeris (const OutputTimeType &currentTime)
Templated function to get the state from tabulated ephemeris.
Public Member Functions inherited from tudat::ephemerides::Ephemeris
Ephemeris (const std::string &referenceFrameOrigin="", const std::string &referenceFrameOrientation="")
Constructor.
virtual ~Ephemeris ()
Default destructor.
std::string getReferenceFrameOrientation ()
Get reference frame orientation.
std::string getReferenceFrameOrigin ()
Get reference frame origin.
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (double specialization).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (long double specialization).
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (double specialization with Time input).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (long double specialization with Time input).
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > getTemplatedStateFromEphemeris (const TimeType &time)
Get state from ephemeris, with state scalar as template type.
Private Attributes
std::vector< bool > isCurrentEphemerisTranslational_
Vector indicating order of translational and rotational ephemeris.
std::vector< std::function< StateType(const TimeType, const StateType &) > > rotationalEphemerides_
Vector of rotational ephemeris functions.
std::vector< std::pair< std::function< StateType(const TimeType &) >, int > > translationalEphemerides_
Vector of translational ephemeris functions.
Additional Inherited Members
Protected Attributes inherited from tudat::ephemerides::Ephemeris
std::string referenceFrameOrientation_
Reference frame orientation.
std::string referenceFrameOrigin_
Reference frame origin.
Detailed Description
template<typename TimeType = double, typename StateScalarType = double>
class tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >
Class that combines a series of translational and rotational ephemeris functions to yield a single translational ephemeris. By using this class, a single object can be used for calling a series of translations and rotations. The option is provided for both adding or subtracting a given translational state.
Definition at line 43 of file compositeEphemeris.h.
Member Typedef Documentation
StateType
template<typename TimeType = double, typename StateScalarType = double> typedef Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::StateType
Definition at line 50 of file compositeEphemeris.h.
Constructor & Destructor Documentation
CompositeEphemeris() [1/2]
template<typename TimeType = double, typename StateScalarType = double> tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::CompositeEphemeris (const std::map< int, std::function< StateType(const TimeType &) > > translationalEphemerides, const std::map< int, std::function< StateType(const TimeType, const StateType &) > > rotationalEphemerides, const std::string referenceFrameOrigin = "SSB", const std::string referenceFrameOrientation = "ECLIPJ2000") inline
Constructor from series of translational and rotational ephemeris functions. Input is provided as maps, with key being the index providing the position in the order where the given function should be applied. Each index must be present only once (i.e. either in translation or rotation), must start with 0 (which must be a translational ephemeris), and must be increasing by 1.
Parameters
translationalEphemerides List of translational ephemerides.
rotationalEphemerides List of rotational ephemerides.
referenceFrameOrigin Origin of reference frame in which state is defined.
referenceFrameOrientation Orientation of reference frame in which state is defined.
Definition at line 64 of file compositeEphemeris.h.
References tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::isCurrentEphemerisTranslational_, tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::rotationalEphemerides_, and tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::translationalEphemerides_.
CompositeEphemeris() [2/2]
template<typename TimeType = double, typename StateScalarType = double> tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::CompositeEphemeris (const std::map< int, std::pair< std::function< StateType(const TimeType &) >, bool > > translationalEphemerides, const std::map< int, std::function< StateType(const TimeType, const StateType &) > > rotationalEphemerides, const std::string referenceFrameOrigin = "SSB", const std::string referenceFrameOrientation = "ECLIPJ2000") inline
Constructor from series of translational and rotational ephemeris functions, allowing either addition or subtraction of translation ep Input is provided as maps, with key being the index providing the position in the order where the given function should be applied. Each index must be present only once (i.e. either in translation or rotation), must start with 0 (which must be a translational ephemeris), and must be increasing by 1. The second element of the pair that is the translational map value denotes whether to add (1) or subtract(0) it.
Parameters
translationalEphemerides List of translational ephemerides, with subtraction/addition indicator.
rotationalEphemerides List of rotational ephemerides.
referenceFrameOrigin Origin of reference frame in which state is defined.
referenceFrameOrientation Orientation of reference frame in which state is defined.
Definition at line 134 of file compositeEphemeris.h.
References tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::isCurrentEphemerisTranslational_, tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::rotationalEphemerides_, and tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::translationalEphemerides_.
~CompositeEphemeris()
template<typename TimeType = double, typename StateScalarType = double> tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::~CompositeEphemeris () inline
Definition at line 193 of file compositeEphemeris.h.
Member Function Documentation
getCartesianState() [1/2]
template<typename TimeType = double, typename StateScalarType = double> Eigen::Vector6d tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::getCartesianState (const double secondsSinceEpoch) inline virtual
Returns state from ephemeris at given time.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Constant state given by combined rotations and translations.
Implements tudat::ephemerides::Ephemeris.
Definition at line 201 of file compositeEphemeris.h.
getCartesianLongState() [1/2]
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::getCartesianLongState (const double secondsSinceEpoch) inline virtual
Returns state from ephemeris with long double as state scalar at given time.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Constant state with long double as state scalar given by combined rotations and translations.
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 213 of file compositeEphemeris.h.
getCartesianStateFromExtendedTime()
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< double, 6, 1 > tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::getCartesianStateFromExtendedTime (const Time & currentTime) inline virtual
Returns state from ephemeris with double as state scalar at given time (as custom Time type).
Parameters
currentTime Time at which state is to be evaluated
Returns
State from ephemeris with long double as state scalar
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 225 of file compositeEphemeris.h.
getCartesianLongStateFromExtendedTime()
template<typename TimeType = double, typename StateScalarType = double> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::getCartesianLongStateFromExtendedTime (const Time & currentTime) inline virtual
Returns state from ephemeris with long double as state scalar at given time (as custom Time type).
Parameters
currentTime Time at which state is to be evaluated
Returns
State from ephemeris with long double as state scalar
Reimplemented from tudat::ephemerides::Ephemeris.
Definition at line 237 of file compositeEphemeris.h.
getTemplatedCartesianStateFromCompositeEphemeris()
template<typename TimeType = double, typename StateScalarType = double> template<typename OutputTimeType , typename OutputStateScalarType > Eigen::Matrix< OutputStateScalarType, 6, 1 > tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::getTemplatedCartesianStateFromCompositeEphemeris (const OutputTimeType & currentTime) inline
Templated function to get the state from tabulated ephemeris. This function is called with the appropriate template arguments by each of the specific state functions. Its function is to have only a single function implemented, while ensuring that the numerical precision is at least that of the CompositeEphemeris and requested time/state scalar types.
Parameters
currentTime Seconds since epoch at which ephemeris is to be evaluated.
Returns
State given by combined rotations and translations, at requested precision.
Definition at line 253 of file compositeEphemeris.h.
References tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::isCurrentEphemerisTranslational_, tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::rotationalEphemerides_, and tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::translationalEphemerides_.
addTranslationalEphemeris()
template<typename TimeType = double, typename StateScalarType = double> void tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::addTranslationalEphemeris (const std::function< StateType(const TimeType &) > stateFunction, const int add = 1) inline
Function to add an additional translational ephemeris at the end of the chain.
Parameters
stateFunction Translational ephemeris function to add.
add Identifier setting whether to add (1) or subtract (-1) translation.
Definition at line 291 of file compositeEphemeris.h.
References tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::isCurrentEphemerisTranslational_, and tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::translationalEphemerides_.
getCartesianLongState() [2/2]
template<typename TimeType = double, typename StateScalarType = double> virtual Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::Ephemeris::getCartesianLongState inline
Returns state from ephemeris with long double as state scalar at given time. By default, this function casts the double getCartesianState to long double. It may be overridden by derived classes to make use of full long double computations.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
State from ephemeris with long double as state scalar
Definition at line 73 of file ephemeris.h.
getCartesianState() [2/2]
template<typename TimeType = double, typename StateScalarType = double> virtual Eigen::Vector6d tudat::ephemerides::Ephemeris::getCartesianState
Returns state from ephemeris at given Julian date.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
State from ephemeris.
Member Data Documentation
translationalEphemerides_
template<typename TimeType = double, typename StateScalarType = double> std::vector< std::pair< std::function< StateType(const TimeType&) >, int > > tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::translationalEphemerides_ private
Vector of translational ephemeris functions and addition (1) or subtraction (-1) indicator.
Definition at line 312 of file compositeEphemeris.h.
Referenced by tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::addTranslationalEphemeris(), tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::CompositeEphemeris(), and tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::getTemplatedCartesianStateFromCompositeEphemeris().
rotationalEphemerides_
template<typename TimeType = double, typename StateScalarType = double> std::vector< std::function< StateType(const TimeType, const StateType&) > > tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::rotationalEphemerides_ private
Vector of rotational ephemeris functions.
Definition at line 318 of file compositeEphemeris.h.
Referenced by tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::CompositeEphemeris(), and tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::getTemplatedCartesianStateFromCompositeEphemeris().
isCurrentEphemerisTranslational_
template<typename TimeType = double, typename StateScalarType = double> std::vector< bool > tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::isCurrentEphemerisTranslational_ private
Vector indicating order of translational and rotational ephemeris (0 is first, highest is last)
Definition at line 324 of file compositeEphemeris.h.
Referenced by tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::addTranslationalEphemeris(), tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::CompositeEphemeris(), and tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >::getTemplatedCartesianStateFromCompositeEphemeris().
The documentation for this class was generated from the following file:
Astrodynamics/Ephemerides/compositeEphemeris.h