Tudat: tudat::orbital_element_conversions Namespace Reference
tudat::orbital_element_conversions Namespace Reference
Enumerations
enum CartesianElementIndices {
xCartesianPositionIndex = 0, yCartesianPositionIndex = 1, zCartesianPositionIndex = 2, xCartesianVelocityIndex = 3,
yCartesianVelocityIndex = 4, zCartesianVelocityIndex = 5
}
Cartesian elements indices.
enum ExponentialMapElementIndices { e1ExponentialMapIndex = 0, e2ExponentialMapIndex = 1, e3ExponentialMapIndex = 2, shadowFlagExponentialMapIndex = 3 }
Exponential map indices.
enum KeplerianElementIndices {
semiMajorAxisIndex = 0, eccentricityIndex = 1, inclinationIndex = 2, argumentOfPeriapsisIndex = 3,
longitudeOfAscendingNodeIndex = 4, trueAnomalyIndex = 5, semiLatusRectumIndex = 0
}
Keplerian elements indices.
enum ModifiedEquinoctialElementVectorIndices {
semiParameterIndex = 0, fElementIndex = 1, gElementIndex = 2, hElementIndex = 3,
kElementIndex = 4, trueLongitudeIndex = 5
}
Modified equinoctial element vector indices.
enum ModifiedRodriguesParametersElementIndices { sigma1ModifiedRodriguesParametersIndex = 0, sigma2ModifiedRodriguesParametersIndex = 1, sigma3ModifiedRodriguesParametersIndex = 2, shadowFlagModifiedRodriguesParametersIndex = 3 }
Modified Rodrigues parameters indices.
enum QuaternionsElementIndices { etaQuaternionIndex = 0, epsilon1QuaternionIndex = 1, epsilon2QuaternionIndex = 2, epsilon3QuaternionIndex = 3 }
Quaternions indices.
enum SphericalOrbitalStateElementIndices {
radiusIndex = 0, latitudeIndex = 1, longitudeIndex = 2, speedIndex = 3,
flightPathIndex = 4, headingAngleIndex = 5
}
Spherical orbital state element indices.
enum UnifiedStateModelExponentialMapElementIndices {
CHodographUSMEMIndex = 0, Rf1HodographUSMEMIndex = 1, Rf2HodographUSMEMIndex = 2, e1USMEMIndex = 3,
e2USMEMIndex = 4, e3USMEMIndex = 5, shadowFlagUSMEMIndex = 6
}
Unified state model with exponential map indices.
enum UnifiedStateModelModifiedRodriguesParametersElementIndices {
CHodographUSM6Index = 0, Rf1HodographUSM6Index = 1, Rf2HodographUSM6Index = 2, sigma1USM6Index = 3,
sigma2USM6Index = 4, sigma3USM6Index = 5, shadowFlagUSM6Index = 6
}
Unified state model with modified Rodrigues parameters indices.
enum UnifiedStateModelQuaternionsElementIndices {
CHodographUSM7Index = 0, Rf1HodographUSM7Index = 1, Rf2HodographUSM7Index = 2, etaUSM7Index = 3,
epsilon1USM7Index = 4, epsilon2USM7Index = 5, epsilon3USM7Index = 6
}
Unified state model with quaternions indices.
Functions
double calculateFlightPathAngle (const Eigen::Vector3d &velocityInVerticalFrame)
Calculatre current flight path angle.
double calculateHeadingAngle (const Eigen::Vector3d &velocityInVerticalFrame)
Calculate current heading angle.
template<typename ScalarType = double>
ScalarType computeFirstDerivativeKeplersFunctionForEllipticalOrbits (const ScalarType eccentricAnomaly, const ScalarType eccentricity)
Compute first-derivative of Kepler's function for elliptical orbits.
template<typename ScalarType = double>
ScalarType computeFirstDerivativeKeplersFunctionForHyperbolicOrbits (const ScalarType hyperbolicEccentricAnomaly, const ScalarType eccentricity)
Compute first-derivative of Kepler's function for hyperbolic orbits.
template<typename ScalarType = double>
ScalarType computeKeplersFunctionForEllipticalOrbits (const ScalarType eccentricAnomaly, const ScalarType eccentricity, const ScalarType meanAnomaly)
Compute Kepler's function for elliptical orbits.
template<typename ScalarType = double>
ScalarType computeKeplersFunctionForHyperbolicOrbits (const ScalarType hyperbolicEccentricAnomaly, const ScalarType eccentricity, const ScalarType hyperbolicMeanAnomaly)
Compute Kepler's function for hyperbolic orbits.
template<typename ScalarType = double>
ScalarType computeOrbitalAngularMomentumPerUnitMass (const ScalarType semiLatusRectum, const ScalarType centralBodyGravitationalParameter)
Function to compute orbit angular momentum per unit mass.
template<typename ScalarType = double>
ScalarType computeSemiLatusRectum (const ScalarType eccentricity, const ScalarType semiMajorAxis, const ScalarType tolerance)
Function to compute orbit semi-latus rectum.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertCartesianToKeplerianElements (const Eigen::Matrix< ScalarType, 6, 1 > &cartesianElements, const ScalarType centralBodyGravitationalParameter)
Convert Cartesian to Keplerian orbital elements.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertCartesianToKeplerianElementsFromFunctions (const std::function< Eigen::Matrix< ScalarType, 6, 1 >() > cartesianElementsFunction, const std::function< ScalarType() > centralBodyGravitationalParameterFunction)
Convert Cartesian to Keplerian orbital elements.
Eigen::Vector6d convertCartesianToModifiedEquinoctialElements (const Eigen::Vector6d &cartesianElements, const double centralBodyGravitationalParameter)
Convert Cartesian to modified equinoctial orbital elements using implicit MEE equation set.
Eigen::Vector6d convertCartesianToModifiedEquinoctialElements (const Eigen::Vector6d &cartesianElements, const double centralBodyGravitationalParameter, const bool avoidSingularityAtPiInclination)
Convert Cartesian to modified equinoctial orbital elements using explicit MEE equation set.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertCartesianToModifiedEquinoctialElements (const Eigen::Matrix< ScalarType, 6, 1 > &cartesianElements, const ScalarType centralBodyGravitationalParameter)
Convert Cartesian to modified equinoctial orbital elements using implicit MEE equation set.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertCartesianToModifiedEquinoctialElements (const Eigen::Matrix< ScalarType, 6, 1 > &cartesianElements, const ScalarType centralBodyGravitationalParameter, const bool flipSingularityToZeroInclination)
Convert Cartesian to modified equinoctial orbital elements using explicit MEE equation set.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertCartesianToModifiedEquinoctialElementsFromStateFunction (const std::function< Eigen::Matrix< ScalarType, 6, 1 >() > &cartesianElementsFunction, const std::function< ScalarType() > centralBodyGravitationalParameterFunction)
Eigen::Vector6d convertCartesianToSphericalOrbitalState (const Eigen::Vector6d &bodyFixedCartesianState)
Function to convert a Cartesian to a spherical orbital state.
Eigen::Vector7d convertCartesianToUnifiedStateModelExponentialMapElements (const Eigen::Vector6d &cartesianElements, const double centralBodyGravitationalParameter)
Convert Cartesian elements to unified state model elements with exponential map.
Eigen::Vector7d convertCartesianToUnifiedStateModelModifiedRodriguesParameterElements (const Eigen::Matrix< double, 6, 1 > &cartesianElements, const double centralBodyGravitationalParameter)
Convert Cartesian elements to unified state model elements with modified rodrigues parameters.
Eigen::Vector7d convertCartesianToUnifiedStateModelQuaternionsElements (const Eigen::Matrix< double, 6, 1 > &cartesianElements, const double centralBodyGravitationalParameter)
Convert Cartesian elements to unified state model elements with quaternions.
template<typename ScalarType = double>
ScalarType convertEccentricAnomalyToMeanAnomaly (const ScalarType eccentricAnomaly, const ScalarType eccentricity)
Convert eccentric anomaly to mean anomaly.
template<typename ScalarType = double>
ScalarType convertEccentricAnomalyToTrueAnomaly (const ScalarType eccentricAnomaly, const ScalarType eccentricity)
Convert eccentric anomaly to true anomaly.
template<typename ScalarType = double>
ScalarType convertElapsedTimeToEllipticalMeanAnomalyChange (const ScalarType elapsedTime, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Convert elapsed time to (elliptical) mean anomaly change.
template<typename ScalarType = double>
ScalarType convertElapsedTimeToHyperbolicMeanAnomalyChange (const ScalarType elapsedTime, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Convert elapsed time to mean anomaly change for hyperbolic orbits.
template<typename ScalarType = double>
ScalarType convertElapsedTimeToMeanAnomalyChange (const ScalarType elapsedTime, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Convert elapsed time to mean anomaly change.
template<typename ScalarType = double>
ScalarType convertEllipticalEccentricAnomalyToMeanAnomaly (const ScalarType ellipticalEccentricAnomaly, const ScalarType eccentricity)
Convert (elliptical) eccentric anomaly to mean anomaly.
template<typename ScalarType = double>
ScalarType convertEllipticalEccentricAnomalyToTrueAnomaly (const ScalarType ellipticEccentricAnomaly, const ScalarType eccentricity)
Convert (elliptical) eccentric anomaly to true anomaly.
template<typename ScalarType = double>
ScalarType convertEllipticalMeanAnomalyChangeToElapsedTime (const ScalarType ellipticalMeanAnomalyChange, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Convert (elliptical) mean anomaly change to elapsed time.
template<typename ScalarType = double>
ScalarType convertEllipticalMeanMotionToSemiMajorAxis (const ScalarType ellipticalMeanMotion, const ScalarType centralBodyGravitationalParameter)
Convert (elliptical) mean motion to semi-major axis.
Eigen::Vector4d convertExponentialMapToQuaternionElements (const Eigen::Vector4d &exponentialMapElements)
Convert exponential map to quaternions.
template<typename ScalarType = double>
ScalarType convertHyperbolicEccentricAnomalyToMeanAnomaly (const ScalarType hyperbolicEccentricAnomaly, const ScalarType eccentricity)
Convert hyperbolic eccentric anomaly to mean anomaly.
template<typename ScalarType = double>
ScalarType convertHyperbolicEccentricAnomalyToTrueAnomaly (const ScalarType hyperbolicEccentricAnomaly, const ScalarType eccentricity)
Convert hyperbolic eccentric anomaly to true anomaly.
template<typename ScalarType = double>
ScalarType convertHyperbolicMeanAnomalyChangeToElapsedTime (const ScalarType hyperbolicMeanAnomalyChange, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Convert hyperbolic mean anomaly change to elapsed time.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertKeplerianToCartesianElements (const Eigen::Matrix< ScalarType, 6, 1 > &keplerianElements, const ScalarType centralBodyGravitationalParameter)
Convert Keplerian to Cartesian orbital elements.
Eigen::Vector6d convertKeplerianToModifiedEquinoctialElements (const Eigen::Vector6d &keplerianElements)
Convert Keplerian to modified equinoctial orbital elements using implicit MEE equation set.
Eigen::Vector6d convertKeplerianToModifiedEquinoctialElements (const Eigen::Vector6d &keplerianElements, const bool avoidSingularityAtPiInclination)
Convert Keplerian to modified equinoctial orbital elements using MEE explicit equation set.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertKeplerianToModifiedEquinoctialElements (const Eigen::Matrix< ScalarType, 6, 1 > &keplerianElements, const bool flipSingularityToZeroInclination)
Convert Keplerian to modified equinoctial orbital elements using MEE explicit equation set.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertKeplerianToModifiedEquinoctialElements (const Eigen::Matrix< ScalarType, 6, 1 > &keplerianElements)
Convert Keplerian to modified equinoctial orbital elements using implicit MEE equation set.
Eigen::Vector7d convertKeplerianToUnifiedStateModelExponentialMapElements (const Eigen::Vector6d &keplerianElements, const double centralBodyGravitationalParameter)
Convert Keplerian elements to unified state model elements with exponential map.
Eigen::Vector7d convertKeplerianToUnifiedStateModelModifiedRodriguesParameterElements (const Eigen::Vector6d &keplerianElements, const double centralBodyGravitationalParameter)
Convert Keplerian elements to unified state model elements with modified Rodrigues parameters.
Eigen::Vector7d convertKeplerianToUnifiedStateModelQuaternionsElements (const Eigen::Vector6d &keplerianElements, const double centralBodyGravitationalParameter)
Convert Keplerian elements to unified state model elements with quaternions.
template<typename ScalarType = double>
ScalarType convertMeanAnomalyChangeToElapsedTime (const ScalarType meanAnomalyChange, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Convert mean anomaly change to elapsed time.
template<typename ScalarType = double>
ScalarType convertMeanAnomalyToEccentricAnomaly (const ScalarType eccentricity, const ScalarType aMeanAnomaly, const bool useDefaultInitialGuess=true, const ScalarType userSpecifiedInitialGuess=TUDAT_NAN, std::shared_ptr< root_finders::RootFinderCore< ScalarType > > rootFinder=std::shared_ptr< root_finders::RootFinderCore< ScalarType > >())
Convert mean anomaly to eccentric anomaly.
template<typename ScalarType = double>
ScalarType convertMeanAnomalyToHyperbolicEccentricAnomaly (const ScalarType eccentricity, const ScalarType hyperbolicMeanAnomaly, const bool useDefaultInitialGuess=true, const ScalarType userSpecifiedInitialGuess=TUDAT_NAN, std::shared_ptr< root_finders::RootFinderCore< ScalarType > > aRootFinder=std::shared_ptr< root_finders::RootFinderCore< ScalarType > >())
Convert mean anomaly to hyperbolic eccentric anomaly.
Eigen::Vector6d convertModifiedEquinoctialToCartesianElements (const Eigen::Vector6d &modifiedEquinoctialElements, const double centralBodyGravitationalParameter, const bool avoidSingularityAtPiInclination)
Convert Modified Equinoctial Elements to Cartesian Elements.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertModifiedEquinoctialToCartesianElements (const Eigen::Matrix< ScalarType, 6, 1 > &modifiedEquinoctialElements, const ScalarType centralBodyGravitationalParameter, const bool flipSingularityToZeroInclination)
Convert modified equinoctial elements to Cartesian orbital elements.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertModifiedEquinoctialToCartesianElementsViaKeplerElements (const Eigen::Matrix< ScalarType, 6, 1 > &modifiedEquinoctialElements, const ScalarType centralBodyGravitationalParameter, const bool flipSingularityToZeroInclination)
Convert modified equinoctial elements to Cartesian orbital elements.
Eigen::Vector6d convertModifiedEquinoctialToKeplerianElements (const Eigen::Vector6d &modifiedEquinoctialElements, const bool avoidSingularityAtPiInclination)
Convert modified equinoctial to Keplerian orbital elements.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > convertModifiedEquinoctialToKeplerianElements (const Eigen::Matrix< ScalarType, 6, 1 > &modifiedEquinoctialElements, const bool flipSingularityToZeroInclination)
Convert modified equinoctial to Keplerian orbital elements.
Eigen::Vector4d convertModifiedRodriguesParametersToQuaternionElements (const Eigen::Vector4d &modifiedRodriguesParameterElements)
Convert modified Rodrigues parameters to quaternions.
Eigen::Vector4d convertQuaternionsToExponentialMapElements (const Eigen::Vector4d &quaternionElements)
Convert quaternions to exponential map.
Eigen::Vector4d convertQuaternionsToModifiedRodriguesParameterElements (const Eigen::Vector4d &quaternionElements)
Convert quaternions to modified Rodrigues parameters.
template<typename ScalarType = double>
ScalarType convertSemiMajorAxisToEllipticalMeanMotion (const ScalarType semiMajorAxis, const ScalarType centralBodyGravitationalParameter)
Convert semi-major axis to elliptical mean motion.
Eigen::Vector6d convertSphericalOrbitalToCartesianState (const Eigen::Vector6d &sphericalOrbitalState)
Function to convert a spherical orbital to a Cartesian state.
template<typename ScalarType = double>
ScalarType convertTrueAnomalyToEccentricAnomaly (const ScalarType trueAnomaly, const ScalarType eccentricity)
Convert true anomaly to eccentric anomaly.
template<typename ScalarType = double>
ScalarType convertTrueAnomalyToEllipticalEccentricAnomaly (const ScalarType trueAnomaly, const ScalarType eccentricity)
Convert true anomaly to (elliptical) eccentric anomaly.
template<typename ScalarType = double>
ScalarType convertTrueAnomalyToHyperbolicEccentricAnomaly (const ScalarType trueAnomaly, const ScalarType eccentricity)
Convert true anomaly to hyperbolic eccentric anomaly.
Eigen::Vector6d convertUnifiedStateModelExponentialMapToCartesianElements (const Eigen::Vector7d &unifiedStateModelExponentialMapElements, const double centralBodyGravitationalParameter)
Convert unified state model elements with exponential map to Cartesian elements.
Eigen::Vector6d convertUnifiedStateModelExponentialMapToKeplerianElements (const Eigen::Vector7d &unifiedStateModelElements, const double centralBodyGravitationalParameter)
Convert unified state model elements with exponential map to Keplerian elements.
Eigen::Vector6d convertUnifiedStateModelModifiedRodriguesParametersToCartesianElements (const Eigen::Vector7d &unifiedStateModelModifiedRodriguesParametersElements, const double centralBodyGravitationalParameter)
Convert unified state model elements with modified Rodrigues parameters to Cartesian elements.
Eigen::Vector6d convertUnifiedStateModelModifiedRodriguesParametersToKeplerianElements (const Eigen::Vector7d &unifiedStateModelElements, const double centralBodyGravitationalParameter)
Convert unified state model elements with modified Rodrigues parameters to Keplerian elements.
Eigen::Vector6d convertUnifiedStateModelQuaternionsToCartesianElements (const Eigen::Vector7d &unifiedStateModelElements, const double centralBodyGravitationalParameter, const bool forceQuaternionNormalization)
Convert unified state model elements with quaternions to Cartesian elements.
Eigen::Vector6d convertUnifiedStateModelQuaternionsToKeplerianElements (const Eigen::Vector7d &unifiedStateModelElements, const double centralBodyGravitationalParameter, const bool forceQuaternionNormalization)
Convert unified state model elements with quaternions to Keplerian elements.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 6, 1 > propagateKeplerOrbit (const Eigen::Matrix< ScalarType, 6, 1 > &initialStateInKeplerianElements, const ScalarType propagationTime, const ScalarType centralBodyGravitationalParameter, std::shared_ptr< root_finders::RootFinderCore< ScalarType > > aRootFinder=std::shared_ptr< root_finders::RootFinderCore< ScalarType > >())
Propagate Kepler orbit.
Enumeration Type Documentation
CartesianElementIndices
enum tudat::orbital_element_conversions::CartesianElementIndices
Enumerator
xCartesianPositionIndex
yCartesianPositionIndex
zCartesianPositionIndex
xCartesianVelocityIndex
yCartesianVelocityIndex
zCartesianVelocityIndex
Definition at line 22 of file stateVectorIndices.h.
KeplerianElementIndices
enum tudat::orbital_element_conversions::KeplerianElementIndices
Enumerator
semiMajorAxisIndex
eccentricityIndex
inclinationIndex
argumentOfPeriapsisIndex
longitudeOfAscendingNodeIndex
trueAnomalyIndex
semiLatusRectumIndex
Definition at line 33 of file stateVectorIndices.h.
ModifiedEquinoctialElementVectorIndices
enum tudat::orbital_element_conversions::ModifiedEquinoctialElementVectorIndices
Enumerator
semiParameterIndex
fElementIndex
gElementIndex
hElementIndex
kElementIndex
trueLongitudeIndex
Definition at line 45 of file stateVectorIndices.h.
SphericalOrbitalStateElementIndices
enum tudat::orbital_element_conversions::SphericalOrbitalStateElementIndices
Enumerator
radiusIndex
latitudeIndex
longitudeIndex
speedIndex
flightPathIndex
headingAngleIndex
Definition at line 56 of file stateVectorIndices.h.
UnifiedStateModelQuaternionsElementIndices
enum tudat::orbital_element_conversions::UnifiedStateModelQuaternionsElementIndices
Enumerator
CHodographUSM7Index
Rf1HodographUSM7Index
Rf2HodographUSM7Index
etaUSM7Index
epsilon1USM7Index
epsilon2USM7Index
epsilon3USM7Index
Definition at line 67 of file stateVectorIndices.h.
UnifiedStateModelModifiedRodriguesParametersElementIndices
enum tudat::orbital_element_conversions::UnifiedStateModelModifiedRodriguesParametersElementIndices
Enumerator
CHodographUSM6Index
Rf1HodographUSM6Index
Rf2HodographUSM6Index
sigma1USM6Index
sigma2USM6Index
sigma3USM6Index
shadowFlagUSM6Index
Definition at line 79 of file stateVectorIndices.h.
UnifiedStateModelExponentialMapElementIndices
enum tudat::orbital_element_conversions::UnifiedStateModelExponentialMapElementIndices
Enumerator
CHodographUSMEMIndex
Rf1HodographUSMEMIndex
Rf2HodographUSMEMIndex
e1USMEMIndex
e2USMEMIndex
e3USMEMIndex
shadowFlagUSMEMIndex
Definition at line 91 of file stateVectorIndices.h.
QuaternionsElementIndices
enum tudat::orbital_element_conversions::QuaternionsElementIndices
Enumerator
etaQuaternionIndex
epsilon1QuaternionIndex
epsilon2QuaternionIndex
epsilon3QuaternionIndex
Definition at line 103 of file stateVectorIndices.h.
ModifiedRodriguesParametersElementIndices
enum tudat::orbital_element_conversions::ModifiedRodriguesParametersElementIndices
Enumerator
sigma1ModifiedRodriguesParametersIndex
sigma2ModifiedRodriguesParametersIndex
sigma3ModifiedRodriguesParametersIndex
shadowFlagModifiedRodriguesParametersIndex
Definition at line 112 of file stateVectorIndices.h.
ExponentialMapElementIndices
enum tudat::orbital_element_conversions::ExponentialMapElementIndices
Enumerator
e1ExponentialMapIndex
e2ExponentialMapIndex
e3ExponentialMapIndex
shadowFlagExponentialMapIndex
Definition at line 121 of file stateVectorIndices.h.
Function Documentation
convertQuaternionsToModifiedRodriguesParameterElements()
Eigen::Vector4d tudat::orbital_element_conversions::convertQuaternionsToModifiedRodriguesParameterElements (const Eigen::Vector4d & quaternionElements)
Convert quaternions to modified Rodrigues parameters. The conversion is slightly different for modified Rodrigues parameters (MRP) than for shadow modified Rodrigues parameters (SMRP). This difference is embodied by conversionSign.
Parameters
quaternionElements Vector of quaternion elements.
Returns
convertedModifiedRodriguesParameterElements Vector of (shadow) modified Rodrigues parameter elements.
Definition at line 27 of file attitudeElementConversions.cpp.
References epsilon1QuaternionIndex, etaQuaternionIndex, shadowFlagModifiedRodriguesParametersIndex, and sigma1ModifiedRodriguesParametersIndex.
Referenced by convertCartesianToUnifiedStateModelModifiedRodriguesParameterElements(), and tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution().
convertModifiedRodriguesParametersToQuaternionElements()
Eigen::Vector4d tudat::orbital_element_conversions::convertModifiedRodriguesParametersToQuaternionElements (const Eigen::Vector4d & modifiedRodriguesParameterElements)
Convert modified Rodrigues parameters to quaternions. The conversion is slightly different for modified Rodrigues parameters (MRP) than for shadow modified Rodrigues parameters (SMRP). This difference is embodied by conversionSign.
Parameters
modifiedRodriguesParameterElements Vector of (shadow) modified Rodrigues parameters elements.
Returns
convertedQuaternionElements Vector of quaternion elements.
Definition at line 47 of file attitudeElementConversions.cpp.
References epsilon1QuaternionIndex, etaQuaternionIndex, shadowFlagModifiedRodriguesParametersIndex, and sigma1ModifiedRodriguesParametersIndex.
Referenced by tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), and convertUnifiedStateModelModifiedRodriguesParametersToCartesianElements().
convertQuaternionsToExponentialMapElements()
Eigen::Vector4d tudat::orbital_element_conversions::convertQuaternionsToExponentialMapElements (const Eigen::Vector4d & quaternionElements)
Convert quaternions to exponential map. The conversion is the same for both exponential map (EM) and shadow exponential map (SEM).
Parameters
quaternionElements Vector of quaternion elements.
Returns
convertedExponentialMapElements Vector of (shadow) exponential map elements.
Definition at line 74 of file attitudeElementConversions.cpp.
References e1ExponentialMapIndex, epsilon1QuaternionIndex, etaQuaternionIndex, tudat::mathematical_constants::PI, and shadowFlagExponentialMapIndex.
Referenced by convertCartesianToUnifiedStateModelExponentialMapElements(), and tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution().
convertExponentialMapToQuaternionElements()
Eigen::Vector4d tudat::orbital_element_conversions::convertExponentialMapToQuaternionElements (const Eigen::Vector4d & exponentialMapElements)
Convert exponential map to quaternions. The conversion is the same for both exponential map (EM) and shadow exponential map (SEM).
Parameters
exponentialMapElements Vector of (shadow) exponential map elements.
Returns
convertedQuaternionElements Vector of quaternion elements.
Definition at line 106 of file attitudeElementConversions.cpp.
References e1ExponentialMapIndex, epsilon1QuaternionIndex, etaQuaternionIndex, and shadowFlagExponentialMapIndex.
Referenced by tudat::propagators::computeStateDerivativeForUnifiedStateModelExponentialMap(), tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), and convertUnifiedStateModelExponentialMapToCartesianElements().
computeKeplersFunctionForEllipticalOrbits()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::computeKeplersFunctionForEllipticalOrbits (const ScalarType eccentricAnomaly, const ScalarType eccentricity, const ScalarType meanAnomaly)
Computes Kepler's function, given as:
for elliptical orbits, where is the eccentric anomaly, is the eccentricity, is the mean anomaly. All eccentricities >= 0.0 and < 1.0 are valid.
Parameters
eccentricAnomaly Eccentric anomaly.
eccentricity Eccentricity.
meanAnomaly Mean anomaly.
Returns
Value of Kepler's function for elliptical orbits.
Definition at line 68 of file convertMeanToEccentricAnomalies.h.
References tudat::input_output::field_types::state::eccentricity, and tudat::input_output::field_types::state::meanAnomaly.
computeFirstDerivativeKeplersFunctionForEllipticalOrbits()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::computeFirstDerivativeKeplersFunctionForEllipticalOrbits (const ScalarType eccentricAnomaly, const ScalarType eccentricity)
Computes the first-derivative of Kepler's function, given as:
for elliptical orbits, where is the eccentric anomaly, and is the eccentricity. All eccentricities >= 0.0 and < 1.0 are valid.
Parameters
eccentricAnomaly Eccentric anomaly.
eccentricity Eccentricity.
Returns
Value of first-derivative of Kepler's function for elliptical orbits.
Definition at line 88 of file convertMeanToEccentricAnomalies.h.
References tudat::input_output::field_types::state::eccentricity.
computeKeplersFunctionForHyperbolicOrbits()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::computeKeplersFunctionForHyperbolicOrbits (const ScalarType hyperbolicEccentricAnomaly, const ScalarType eccentricity, const ScalarType hyperbolicMeanAnomaly)
Computes Kepler's function, given as:
for hyperbolic orbits, where is the hyperbolic eccentric anomaly, is the eccentricity, is the mean anomaly. All eccentricities > 1.0 are valid.
Parameters
hyperbolicEccentricAnomaly Hyperbolic eccentric anomaly.
eccentricity Eccentricity.
hyperbolicMeanAnomaly Hyperbolic mean anomaly..
Returns
Value of Kepler's function for hyperbolic orbits.
Definition at line 110 of file convertMeanToEccentricAnomalies.h.
References tudat::input_output::field_types::state::eccentricity.
computeFirstDerivativeKeplersFunctionForHyperbolicOrbits()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::computeFirstDerivativeKeplersFunctionForHyperbolicOrbits (const ScalarType hyperbolicEccentricAnomaly, const ScalarType eccentricity)
Computes the first-derivative of Kepler's function, given as:
for hyperbolic orbits, where is the hyperbolic eccentric anomaly, and is the eccentricity. All eccentricities > 1.0 are valid.
Parameters
hyperbolicEccentricAnomaly Hyperbolic eccentric anomaly
eccentricity Eccentricity.
Returns
Value of first-derivative of Kepler's function for hyperbolic orbits.
Definition at line 131 of file convertMeanToEccentricAnomalies.h.
References tudat::input_output::field_types::state::eccentricity.
convertMeanAnomalyToEccentricAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertMeanAnomalyToEccentricAnomaly (const ScalarType eccentricity, const ScalarType aMeanAnomaly, const bool useDefaultInitialGuess = true, const ScalarType userSpecifiedInitialGuess = TUDAT_NAN, std::shared_ptr< root_finders::RootFinderCore< ScalarType > > rootFinder = std::shared_ptr< root_finders::RootFinderCore< ScalarType > >())
Converts mean anomaly to eccentric anomaly for elliptical orbits for all eccentricities >= 0.0 and < 1.0. If the conversion fails or the eccentricity falls outside the valid range, then ScalarType::NaN is returned. Calculated with an accuracy of 1.0e-13 for all cases, except for some near-parabolic cases in which macine precision problems occur. These are tested against an accuracy of 1.0e-9. Near-parabolic in this sense means e > 1.0-1.0e-11. Also note that your mean anomaly is automatically transformed to fit within the 0 to 2.0*PI spectrum. Numerical tests performed using double ScalarType.
Parameters
eccentricity Eccentricity of the orbit [-].
aMeanAnomaly Mean anomaly to convert to eccentric anomaly [rad].
useDefaultInitialGuess Boolean specifying whether to use default initial guess [-].
userSpecifiedInitialGuess Initial guess for rootfinder [rad].
rootFinder Shared-pointer to the rootfinder that is to be used. Default is Newton-Raphson using 1000 iterations as maximum and apprximately 1.0e-13 absolute X-tolerance (for doubles; 500 times ScalarType resolution). Higher precision may invoke machine precision problems for some values.
Returns
Eccentric anomaly [rad].
Definition at line 158 of file convertMeanToEccentricAnomalies.h.
References tudat::input_output::field_types::state::eccentricity, tudat::input_output::field_types::state::meanAnomaly, and TUDAT_NAN.
Referenced by tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), tudat::ephemerides::KeplerStateExtractor::extract(), tudat::json_interface::getCartesianState(), tudat::ephemerides::KeplerEphemeris::getCartesianState(), and tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris().
convertMeanAnomalyToHyperbolicEccentricAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertMeanAnomalyToHyperbolicEccentricAnomaly (const ScalarType eccentricity, const ScalarType hyperbolicMeanAnomaly, const bool useDefaultInitialGuess = true, const ScalarType userSpecifiedInitialGuess = TUDAT_NAN, std::shared_ptr< root_finders::RootFinderCore< ScalarType > > aRootFinder = std::shared_ptr< root_finders::RootFinderCore< ScalarType > >())
Converts mean anomaly to hyperbolic eccentric anomaly for hyperbolic orbits for all eccentricities > 1.0. If the conversion fails or the eccentricity falls outside the valid range, then double::NaN is returned. Calculated with an accuracy of 1.0e-14 for all reasonable cases (eccentricities up to 1.0e15, mean anomalies -1.2e12 to 1.2e12, test cases using doubles).
Parameters
eccentricity Eccentricity of the orbit [-].
hyperbolicMeanAnomaly Hyperbolic mean anomaly to convert to eccentric anomaly [rad].
useDefaultInitialGuess Boolean specifying whether to use default initial guess [-].
userSpecifiedInitialGuess Initial guess for rootfinder [rad].
aRootFinder Shared-pointer to the rootfinder that is to be used. Default is Newton-Raphson using 1000 iterations as maximum and apprximately 5.0e-15 absolute X-tolerance (for doubles; 25 times ScalarType resolution). Higher precision may invoke machine precision problems for some values.
Returns
Hyperbolic eccentric anomaly.
Definition at line 304 of file convertMeanToEccentricAnomalies.h.
References tudat::input_output::field_types::state::eccentricity, and TUDAT_NAN.
Referenced by tudat::ephemerides::KeplerEphemeris::getCartesianState(), and propagateKeplerOrbit().
propagateKeplerOrbit()
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::propagateKeplerOrbit (const Eigen::Matrix< ScalarType, 6, 1 > & initialStateInKeplerianElements, const ScalarType propagationTime, const ScalarType centralBodyGravitationalParameter, std::shared_ptr< root_finders::RootFinderCore< ScalarType > > aRootFinder = std::shared_ptr< root_finders::RootFinderCore< ScalarType > >())
Propagates Kepler orbit. This function essentially takes a state in classical Keplerian elements at an initial epoch and propagates it to a final state at a given final epoch. Currently both elliptic and hyperbolic orbits are supported. Parabolic orbits are not supported and will result in an error message. IMPORTANT! Note that the true anomaly is returned within the -PI to PI spectrum. If the user desires a different spectrum (possibly including the number of revolutions), these should be added by the user a posteriori.
Parameters
initialStateInKeplerianElements Initial state vector in classical Keplerian elements. Order is important! initialStateInKeplerianElements(0) = semiMajorAxis, [m] initialStateInKeplerianElements(1) = eccentricity, [-] initialStateInKeplerianElements(2) = inclination, [rad] initialStateInKeplerianElements(3) = argument of periapsis, [rad] initialStateInKeplerianElements(4) = longitude of ascending node, [rad] initialStateInKeplerianElements(5) = true anomaly. [rad]
propagationTime Propagation time. [s]
centralBodyGravitationalParameter Gravitational parameter of central body [m^3 s^-2]
aRootFinder Shared-pointer to the root-finder that is used to solve the conversion from mean to eccentric anomaly. Default is Newton-Raphson using 5.0e-14 absolute X-tolerance and 1000 iterations as maximum. Higher precision may invoke machine precision problems for some values.
Returns
finalStateInKeplerianElements Final state vector in classical Keplerian elements. Order is important! finalStateInKeplerianElements(0) = semiMajorAxis, [m] finalStateInKeplerianElements(1) = eccentricity, [-] finalStateInKeplerianElements(2) = inclination, [rad] finalStateInKeplerianElements(3) = argument of periapsis, [rad] finalStateInKeplerianElements(4) = longitude of ascending node, [rad] finalStateInKeplerianElements(5) = true anomaly. [rad]
Definition at line 65 of file keplerPropagator.h.
References convertElapsedTimeToHyperbolicMeanAnomalyChange(), convertHyperbolicEccentricAnomalyToMeanAnomaly(), convertHyperbolicEccentricAnomalyToTrueAnomaly(), convertMeanAnomalyToHyperbolicEccentricAnomaly(), convertTrueAnomalyToHyperbolicEccentricAnomaly(), eccentricityIndex, semiMajorAxisIndex, trueAnomalyIndex, and TUDAT_NAN.
Referenced by tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::calculateLeg(), tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::calculateLeg(), and tudat::transfer_trajectories::returnTrajectory().
convertKeplerianToModifiedEquinoctialElements() [1/4]
Eigen::Vector6d tudat::orbital_element_conversions::convertKeplerianToModifiedEquinoctialElements (const Eigen::Vector6d & keplerianElements)
Definition at line 39 of file modifiedEquinoctialElementConversions.cpp.
References tudat::mission_geometry::isOrbitRetrograde(), and tudat::json_interface::keplerianElements.
Referenced by convertCartesianToModifiedEquinoctialElements(), and convertKeplerianToModifiedEquinoctialElements().
convertKeplerianToModifiedEquinoctialElements() [2/4]
Eigen::Vector6d tudat::orbital_element_conversions::convertKeplerianToModifiedEquinoctialElements (const Eigen::Vector6d & keplerianElements, const bool avoidSingularityAtPiInclination)
Definition at line 53 of file modifiedEquinoctialElementConversions.cpp.
References argumentOfPeriapsisIndex, tudat::basic_mathematics::computeModulo(), tudat::input_output::field_types::state::eccentricity, eccentricityIndex, fElementIndex, gElementIndex, hElementIndex, tudat::input_output::field_types::state::inclination, inclinationIndex, kElementIndex, tudat::json_interface::keplerianElements, longitudeOfAscendingNodeIndex, tudat::mathematical_constants::PI, semiLatusRectumIndex, semiMajorAxisIndex, trueAnomalyIndex, and trueLongitudeIndex.
convertModifiedEquinoctialToKeplerianElements() [1/2]
Eigen::Vector6d tudat::orbital_element_conversions::convertModifiedEquinoctialToKeplerianElements (const Eigen::Vector6d & modifiedEquinoctialElements, const bool avoidSingularityAtPiInclination)
Definition at line 151 of file modifiedEquinoctialElementConversions.cpp.
References argumentOfPeriapsisIndex, tudat::basic_mathematics::computeModulo(), tudat::input_output::field_types::state::eccentricity, eccentricityIndex, fElementIndex, gElementIndex, hElementIndex, inclinationIndex, kElementIndex, tudat::input_output::field_types::state::longitudeOfAscendingNode, longitudeOfAscendingNodeIndex, tudat::mathematical_constants::PI, semiLatusRectumIndex, semiMajorAxisIndex, trueAnomalyIndex, and trueLongitudeIndex.
Referenced by convertModifiedEquinoctialToCartesianElements(), and convertModifiedEquinoctialToCartesianElementsViaKeplerElements().
convertCartesianToModifiedEquinoctialElements() [1/4]
Eigen::Vector6d tudat::orbital_element_conversions::convertCartesianToModifiedEquinoctialElements (const Eigen::Vector6d & cartesianElements, const double centralBodyGravitationalParameter)
Definition at line 251 of file modifiedEquinoctialElementConversions.cpp.
References tudat::json_interface::cartesianElements, convertCartesianToKeplerianElements(), convertKeplerianToModifiedEquinoctialElements(), tudat::mission_geometry::isOrbitRetrograde(), tudat::json_interface::keplerianElements, and tudat::mathematical_constants::PI.
Referenced by convertCartesianToModifiedEquinoctialElementsFromStateFunction(), and tudat::propulsion::MeeCostateBasedThrustGuidance::updateForceDirection().
convertCartesianToModifiedEquinoctialElements() [2/4]
Eigen::Vector6d tudat::orbital_element_conversions::convertCartesianToModifiedEquinoctialElements (const Eigen::Vector6d & cartesianElements, const double centralBodyGravitationalParameter, const bool avoidSingularityAtPiInclination)
Definition at line 271 of file modifiedEquinoctialElementConversions.cpp.
References tudat::json_interface::cartesianElements, convertCartesianToKeplerianElements(), and convertKeplerianToModifiedEquinoctialElements().
convertModifiedEquinoctialToCartesianElements() [1/2]
Eigen::Vector6d tudat::orbital_element_conversions::convertModifiedEquinoctialToCartesianElements (const Eigen::Vector6d & modifiedEquinoctialElements, const double centralBodyGravitationalParameter, const bool avoidSingularityAtPiInclination)
Definition at line 284 of file modifiedEquinoctialElementConversions.cpp.
References convertKeplerianToCartesianElements(), convertModifiedEquinoctialToKeplerianElements(), fElementIndex, gElementIndex, hElementIndex, kElementIndex, semiLatusRectumIndex, trueLongitudeIndex, xCartesianPositionIndex, xCartesianVelocityIndex, yCartesianPositionIndex, yCartesianVelocityIndex, zCartesianPositionIndex, and zCartesianVelocityIndex.
convertKeplerianToModifiedEquinoctialElements() [3/4]
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertKeplerianToModifiedEquinoctialElements (const Eigen::Matrix< ScalarType, 6, 1 > & keplerianElements, const bool flipSingularityToZeroInclination)
Converts Keplerian to modified equinoctial elements using the prograde/retrograde equation determined by the values of the input Kepler elements. If input exceeds allowable ranges, an error is thrown. NOTE: This function automatically selects the boolean parameter that defines the location of the singularity, depending on whether the orbit is prograde or retrograde.
Parameters
keplerianElements Vector containing Keplerian elements. Order of elements is important! keplerianElements(0) = semi-major axis, [m] keplerianElements(1) = eccentricity, [-] keplerianElements(2) = inclination (in range [0,PI]), [rad] keplerianElements(3) = argument of periapsis, [rad] keplerianElements(4) = longitude of ascending node, [rad] keplerianElements(5) = true anomaly. [rad]
flipSingularityToZeroInclination Boolean flag to indicate whether the set of equations for the inclination = 180 degrees (false) or 0 degrees (true) singular case are to be used. Take note: the same set of equations is required for conversion back to Keplerian elements to retrieve original state!
Returns
Converted state in modified equinoctial elements. The order of elements is fixed! modifiedEquinoctialElements(0) = semi-latus rectum, [m] modifiedEquinoctialElements(1) = f-element, [-] modifiedEquinoctialElements(2) = g-element, [-] modifiedEquinoctialElements(3) = h-element, [-] modifiedEquinoctialElements(4) = k-element, [-] modifiedEquinoctialElements(5) = true longitude. [rad]
Definition at line 63 of file modifiedEquinoctialElementConversions.h.
References argumentOfPeriapsisIndex, tudat::basic_mathematics::computeModulo(), tudat::input_output::field_types::state::eccentricity, eccentricityIndex, fElementIndex, gElementIndex, tudat::mathematical_constants::getFloatingInteger(), tudat::mathematical_constants::getPi(), hElementIndex, tudat::input_output::field_types::state::inclination, inclinationIndex, kElementIndex, tudat::json_interface::keplerianElements, longitudeOfAscendingNodeIndex, semiLatusRectumIndex, semiMajorAxisIndex, trueAnomalyIndex, and trueLongitudeIndex.
convertKeplerianToModifiedEquinoctialElements() [4/4]
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertKeplerianToModifiedEquinoctialElements (const Eigen::Matrix< ScalarType, 6, 1 > & keplerianElements)
Converts Keplerian to modified equinoctial elements using the prograde/retrograde equation determined by the values of the input Kepler elements. If input exceeds allowable ranges, an error is thrown.
Parameters
keplerianElements Vector containing Keplerian elements. Order of elements is important! keplerianElements(0) = semi-major axis, [m] keplerianElements(1) = eccentricity, [-] keplerianElements(2) = inclination (in range [0,PI]), [rad] keplerianElements(3) = argument of periapsis, [rad] keplerianElements(4) = longitude of ascending node, [rad] keplerianElements(5) = true anomaly. [rad]
Returns
Converted state in modified equinoctial elements. The order of elements is fixed! modifiedEquinoctialElements(0) = semi-latus rectum, [m] modifiedEquinoctialElements(1) = f-element, [-] modifiedEquinoctialElements(2) = g-element, [-] modifiedEquinoctialElements(3) = h-element, [-] modifiedEquinoctialElements(4) = k-element, [-] modifiedEquinoctialElements(5) = true longitude. [rad]
Definition at line 178 of file modifiedEquinoctialElementConversions.h.
References convertKeplerianToModifiedEquinoctialElements(), tudat::mission_geometry::isOrbitRetrograde(), and tudat::json_interface::keplerianElements.
convertModifiedEquinoctialToKeplerianElements() [2/2]
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertModifiedEquinoctialToKeplerianElements (const Eigen::Matrix< ScalarType, 6, 1 > & modifiedEquinoctialElements, const bool flipSingularityToZeroInclination)
Converts modified equinoctial elements to Keplerian using one of two sets of equations specified by the user.
Parameters
modifiedEquinoctialElements Vector containing modified equinoctial elements. Order of elements is important! modifiedEquinoctialElements(0) = semi-latus rectum, [m] modifiedEquinoctialElements(1) = f-element, [-] modifiedEquinoctialElements(2) = g-element, [-] modifiedEquinoctialElements(3) = h-element, [-] modifiedEquinoctialElements(4) = k-element, [-] modifiedEquinoctialElements(5) = true longitude. [rad]
flipSingularityToZeroInclination Boolean flag to indicate whether the set of equations for the inclination = 180 degrees (false) or 0 degrees (true) singular case are to be used. Take note: the same set of equations is required for conversion back to modified equinoctial elements to retrieve original state!
Returns
Converted state in Keplerian elements. The order of elements is fixed! keplerianElements(0) = semi-major axis, [m] keplerianElements(1) = eccentricity, [-] keplerianElements(2) = inclination [0, 180], [rad] keplerianElements(3) = argument of periapsis, [rad] keplerianElements(4) = longitude of ascending node, [rad] keplerianElements(5) = true anomaly. [rad]
Note
Using unknown source pdf, code archive E. Heeren and personal derivation based on Hintz 2008.
Definition at line 218 of file modifiedEquinoctialElementConversions.h.
References argumentOfPeriapsisIndex, tudat::basic_mathematics::computeModulo(), tudat::input_output::field_types::state::eccentricity, eccentricityIndex, fElementIndex, gElementIndex, tudat::mathematical_constants::getFloatingInteger(), tudat::mathematical_constants::getPi(), hElementIndex, inclinationIndex, kElementIndex, tudat::input_output::field_types::state::longitudeOfAscendingNode, longitudeOfAscendingNodeIndex, semiLatusRectumIndex, semiMajorAxisIndex, trueAnomalyIndex, and trueLongitudeIndex.
convertCartesianToModifiedEquinoctialElements() [3/4]
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertCartesianToModifiedEquinoctialElements (const Eigen::Matrix< ScalarType, 6, 1 > & cartesianElements, const ScalarType centralBodyGravitationalParameter)
Converts Cartesian to modified equinoctial elements using one of two sets of equations implicitly determined from intermediate inclination. NOTE: This function automatically selects the boolean parameter that defines the location of the singularity, depending on whether the orbit is prograde or retrograde.
Parameters
cartesianElements Vector containing Cartesian elements. Order of elements is important! cartesianElements(0) = x-position coordinate, [m] cartesianElements(1) = y-position coordinate, [m] cartesianElements(2) = z-position coordinate, [m] cartesianElements(3) = x-velocity coordinate, [m/s] cartesianElements(4) = y-velocity coordinate, [m/s] cartesianElements(5) = z-velocity coordinate. [m/s]
centralBodyGravitationalParameter Gravitational parameter of central body.
Returns
Converted state in modified equinoctial elements. The order of elements is fixed! modifiedEquinoctialElements(0) = semi-latus rectum, [m] modifiedEquinoctialElements(1) = f-element, [-] modifiedEquinoctialElements(2) = g-element, [-] modifiedEquinoctialElements(3) = h-element, [-] modifiedEquinoctialElements(4) = k-element, [-] modifiedEquinoctialElements(5) = true longitude. [rad]
Definition at line 341 of file modifiedEquinoctialElementConversions.h.
References tudat::json_interface::cartesianElements, convertCartesianToKeplerianElements(), convertKeplerianToModifiedEquinoctialElements(), tudat::mission_geometry::isOrbitRetrograde(), and tudat::json_interface::keplerianElements.
convertCartesianToModifiedEquinoctialElementsFromStateFunction()
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertCartesianToModifiedEquinoctialElementsFromStateFunction (const std::function< Eigen::Matrix< ScalarType, 6, 1 >() > & cartesianElementsFunction, const std::function< ScalarType() > centralBodyGravitationalParameterFunction)
Definition at line 360 of file modifiedEquinoctialElementConversions.h.
References convertCartesianToModifiedEquinoctialElements().
convertCartesianToModifiedEquinoctialElements() [4/4]
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertCartesianToModifiedEquinoctialElements (const Eigen::Matrix< ScalarType, 6, 1 > & cartesianElements, const ScalarType centralBodyGravitationalParameter, const bool flipSingularityToZeroInclination)
Converts Cartesian to modified equinoctial elements using one of two sets of equations specified by the user.
Parameters
cartesianElements Vector containing Cartesian elements. Order of elements is important! cartesianElements(0) = x-position coordinate, [m] cartesianElements(1) = y-position coordinate, [m] cartesianElements(2) = z-position coordinate, [m] cartesianElements(3) = x-velocity coordinate, [m/s] cartesianElements(4) = y-velocity coordinate, [m/s] cartesianElements(5) = z-velocity coordinate. [m/s]
centralBodyGravitationalParameter Gravitational parameter of central body.
flipSingularityToZeroInclination Boolean flag to indicate whether the set of equations for the inclination = 180 degrees (false) or 0 degrees (true) singular case are to be used. Take note: the same set of equations is required for conversion back to Cartesian elements to retrieve original state!
Returns
Converted state in modified equinoctial elements. The order of elements is fixed! modifiedEquinoctialElements(0) = semi-latus rectum, [m] modifiedEquinoctialElements(1) = f-element, [-] modifiedEquinoctialElements(2) = g-element, [-] modifiedEquinoctialElements(3) = h-element, [-] modifiedEquinoctialElements(4) = k-element, [-] modifiedEquinoctialElements(5) = true longitude. [rad]
Definition at line 393 of file modifiedEquinoctialElementConversions.h.
References tudat::json_interface::cartesianElements.
convertModifiedEquinoctialToCartesianElementsViaKeplerElements()
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertModifiedEquinoctialToCartesianElementsViaKeplerElements (const Eigen::Matrix< ScalarType, 6, 1 > & modifiedEquinoctialElements, const ScalarType centralBodyGravitationalParameter, const bool flipSingularityToZeroInclination)
Converts modified equinoctial elements to Cartesian orbital elements using one of two sets of equations specified by the user. This function first converts to Keplerian elements, and then to Cartesian elements.
Parameters
modifiedEquinoctialElements Vector containing modified equinoctial elements. Order of elements is important! modifiedEquinoctialElements(0) = semi-latus rectum, [m] modifiedEquinoctialElements(1) = f-element, [-] modifiedEquinoctialElements(2) = g-element, [-] modifiedEquinoctialElements(3) = h-element, [-] modifiedEquinoctialElements(4) = k-element, [-] modifiedEquinoctialElements(5) = true longitude. [rad]
centralBodyGravitationalParameter Gravitational parameter of central body.
flipSingularityToZeroInclination Boolean flag to indicate whether the set of equations for the inclination = 180 degrees (false) or 0 degrees (true) singular case are to be used. Take note: the same set of equations is required for conversion back to modified equinoctial elements to retrieve original state!
Returns
Converted state in Cartesian elements. The order of elements is fixed! cartesianElements(0) = x-position coordinate, [m] cartesianElements(1) = y-position coordinate, [m] cartesianElements(2) = z-position coordinate, [m] cartesianElements(3) = x-velocity coordinate, [m/s] cartesianElements(4) = y-velocity coordinate, [m/s] cartesianElements(5) = z-velocity coordinate. [m/s]
Definition at line 433 of file modifiedEquinoctialElementConversions.h.
References convertKeplerianToCartesianElements(), convertModifiedEquinoctialToKeplerianElements(), fElementIndex, gElementIndex, tudat::mathematical_constants::getFloatingInteger(), hElementIndex, kElementIndex, semiLatusRectumIndex, trueLongitudeIndex, xCartesianPositionIndex, xCartesianVelocityIndex, yCartesianPositionIndex, yCartesianVelocityIndex, zCartesianPositionIndex, and zCartesianVelocityIndex.
convertModifiedEquinoctialToCartesianElements() [2/2]
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertModifiedEquinoctialToCartesianElements (const Eigen::Matrix< ScalarType, 6, 1 > & modifiedEquinoctialElements, const ScalarType centralBodyGravitationalParameter, const bool flipSingularityToZeroInclination)
Converts modified equinoctial elements to Cartesian orbital elements using one of two sets of equations specified by the user.
Parameters
modifiedEquinoctialElements Vector containing modified equinoctial elements. Order of elements is important! modifiedEquinoctialElements(0) = semi-latus rectum, [m] modifiedEquinoctialElements(1) = f-element, [-] modifiedEquinoctialElements(2) = g-element, [-] modifiedEquinoctialElements(3) = h-element, [-] modifiedEquinoctialElements(4) = k-element, [-] modifiedEquinoctialElements(5) = true longitude. [rad]
centralBodyGravitationalParameter Gravitational parameter of central body.
flipSingularityToZeroInclination Boolean flag to indicate whether the set of equations for the inclination = 180 degrees (false) or 0 degrees (true) singular case are to be used. Take note: the same set of equations is required for conversion back to modified equinoctial elements to retrieve original state!
Returns
Converted state in Cartesian elements. The order of elements is fixed! cartesianElements(0) = x-position coordinate, [m] cartesianElements(1) = y-position coordinate, [m] cartesianElements(2) = z-position coordinate, [m] cartesianElements(3) = x-velocity coordinate, [m/s] cartesianElements(4) = y-velocity coordinate, [m/s] cartesianElements(5) = z-velocity coordinate. [m/s]
Definition at line 544 of file modifiedEquinoctialElementConversions.h.
References tudat::json_interface::cartesianElements, fElementIndex, gElementIndex, tudat::mathematical_constants::getFloatingInteger(), hElementIndex, kElementIndex, semiParameterIndex, and trueLongitudeIndex.
computeSemiLatusRectum()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::computeSemiLatusRectum (const ScalarType eccentricity, const ScalarType semiMajorAxis, const ScalarType tolerance)
Function to compute orbit semi-latus rectum.
Parameters
eccentricity Eccentricity of orbit
semiMajorAxis Semi-major axis of orbit (in Tudat, this input must equal semi-latus rectum for parabolic orbits)
tolerance Eccentricity tolerance for which orbit is deemed to be parabolic.
Returns
Orbit semi-latus rectum
Definition at line 50 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity, and tudat::input_output::field_types::state::semiMajorAxis.
Referenced by tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements().
computeOrbitalAngularMomentumPerUnitMass()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::computeOrbitalAngularMomentumPerUnitMass (const ScalarType semiLatusRectum, const ScalarType centralBodyGravitationalParameter)
Function to compute orbit angular momentum per unit mass
Parameters
semiLatusRectum Semi-latus rectum of orbit
centralBodyGravitationalParameter Gravitational parameter of central body
Returns
Orbital angular momentum
Definition at line 84 of file orbitalElementConversions.h.
Referenced by tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements().
convertKeplerianToCartesianElements()
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertKeplerianToCartesianElements (const Eigen::Matrix< ScalarType, 6, 1 > & keplerianElements, const ScalarType centralBodyGravitationalParameter)
Converts Keplerian to Cartesian orbital elements (Chobotov, 2002). Use the CartesianElementVectorIndices enum to access the individual orbital element components in the storage vector.
Parameters
keplerianElements Vector containing Keplerian elements.
Order of elements is important!
keplerianElements(0) = semiMajorAxis, [m]
keplerianElements(1) = eccentricity, [-]
keplerianElements(2) = inclination, [rad]
keplerianElements(3) = argument of periapsis, [rad]
keplerianElements(4) = longitude of ascending node, [rad]
keplerianElements(5) = true anomaly. [rad]
WARNING: If eccentricity is 1.0 within machine precision, keplerianElements(0) = semi-latus rectum.
centralBodyGravitationalParameter Gravitational parameter of central body [m^3 s^-2].
Returns
Converted state in Cartesian elements.
Order of elements is important!
cartesianElements(0) = x-position coordinate, [m]
cartesianElements(1) = y-position coordinate, [m]
cartesianElements(2) = z-position coordinate, [m]
cartesianElements(3) = x-velocity coordinate, [m/s]
cartesianElements(4) = y-velocity coordinate, [m/s]
cartesianElements(5) = z-velocity coordinate. [m/s]
See also
CartesianElementVectorIndices()
Definition at line 126 of file orbitalElementConversions.h.
References argumentOfPeriapsisIndex, eccentricityIndex, inclinationIndex, tudat::json_interface::keplerianElements, longitudeOfAscendingNodeIndex, semiMajorAxisIndex, and trueAnomalyIndex.
Referenced by tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::calculateLeg(), tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::calculateLeg(), convertModifiedEquinoctialToCartesianElements(), convertModifiedEquinoctialToCartesianElementsViaKeplerElements(), tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), tudat::unit_tests::executeEarthOrbiterBiasEstimation(), tudat::unit_tests::executeEarthOrbiterParameterEstimation(), tudat::ephemerides::ApproximatePlanetPositions::getCartesianState(), tudat::json_interface::getCartesianState(), and tudat::transfer_trajectories::returnTrajectory().
convertCartesianToKeplerianElements()
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertCartesianToKeplerianElements (const Eigen::Matrix< ScalarType, 6, 1 > & cartesianElements, const ScalarType centralBodyGravitationalParameter)
Converts Cartesian to Keplerian orbital elements.
Parameters
cartesianElements Vector containing Cartesian elements. Order of elements is important! cartesianElements(0) = x-position coordinate, [m] cartesianElements(1) = y-position coordinate, [m] cartesianElements(2) = z-position coordinate, [m] cartesianElements(3) = x-velocity coordinate, [m/s] cartesianElements(4) = y-velocity coordinate, [m/s] cartesianElements(5) = z-velocity coordinate. [m/s]
centralBodyGravitationalParameter Gravitational parameter of central body.
Returns
Converted state in Keplerian elements. The order of elements is fixed! keplerianElements(0) = semiMajorAxis, [m] keplerianElements(1) = eccentricity, [-] keplerianElements(2) = inclination, [rad] keplerianElements(3) = argument of periapsis, [rad] keplerianElements(4) = longitude of ascending node, [rad] keplerianElements(5) = true anomaly. [rad] WARNING: If eccentricity is 1.0 within 1.0e-15, keplerianElements(0) = semi-latus rectum, since the orbit is parabolic. WARNING: If eccentricity is 0.0 within 1.0e-15, argument of periapsis is set to 0.0, since the orbit is circular. WARNING: If inclination is 0.0 within 1.0e-15, longitude of ascending node is set to 0.0, since the orbit is equatorial. The tolerance 1.0e-15 is hard-coded, as it should not be changed for performance reasons, unless required for specific scenarios. In those cases, users are expected to update the internal tolerance to the required value. Below these tolerance values for eccentricity and inclination, the orbit is considered to be a limit case. Essentially, special solutions are then used for parabolic, circular inclined, non-circular equatorial, and circular equatorial orbits. These special solutions are required because of singularities in the classical Keplerian elements. If high precision is required near these singularities, users are encouraged to consider using other elements, such as modified equinoctial elements. It should be noted that modified equinoctial elements also suffer from singularities, but not for zero eccentricity and inclination.
Definition at line 246 of file orbitalElementConversions.h.
References argumentOfPeriapsisIndex, tudat::json_interface::cartesianElements, eccentricityIndex, inclinationIndex, longitudeOfAscendingNodeIndex, semiLatusRectumIndex, semiMajorAxisIndex, and trueAnomalyIndex.
Referenced by tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::calculateLeg(), tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::calculateLeg(), tudat::acceleration_partials::calculateNumericalPartialOfTrueAnomalyWrtState(), tudat::basic_astrodynamics::computePeriapsisAltitudeFromCartesianState(), convertCartesianToKeplerianElementsFromFunctions(), convertCartesianToModifiedEquinoctialElements(), tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::transfer_trajectories::returnTrajectory(), and tudat::basic_astrodynamics::EmpiricalAcceleration::updateMembers().
convertCartesianToKeplerianElementsFromFunctions()
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 6, 1 > tudat::orbital_element_conversions::convertCartesianToKeplerianElementsFromFunctions (const std::function< Eigen::Matrix< ScalarType, 6, 1 >() > cartesianElementsFunction, const std::function< ScalarType() > centralBodyGravitationalParameterFunction)
Converts Cartesian to Keplerian orbital elements, using function pointers to retrieve the cartesian state and gravitational parameter.
Parameters
cartesianElementsFunction Function that returns vector containing Cartesian elements.
centralBodyGravitationalParameterFunction Function that returns gravitational parameter of central body.
Returns
Converted state in Keplerian elements.
See also
convertCartesianToKeplerianElements
Definition at line 449 of file orbitalElementConversions.h.
References convertCartesianToKeplerianElements().
convertTrueAnomalyToEllipticalEccentricAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertTrueAnomalyToEllipticalEccentricAnomaly (const ScalarType trueAnomaly, const ScalarType eccentricity)
Converts true anomaly to eccentric anomaly for elliptical orbits (0 <= eccentricity < 1.0). The equations used can be found in (Chobotov, 2002).
Parameters
trueAnomaly True anomaly. [rad]
eccentricity Eccentricity. [-]
Returns
(Elliptical) Eccentric anomaly. [rad]
Definition at line 466 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity, and tudat::input_output::field_types::state::trueAnomaly.
convertTrueAnomalyToHyperbolicEccentricAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertTrueAnomalyToHyperbolicEccentricAnomaly (const ScalarType trueAnomaly, const ScalarType eccentricity)
Converts true anomaly to hyperbolic eccentric anomaly for hyperbolic orbits (eccentricity > 1.0). The equations used can be found in (Chobotov, 2002).
Parameters
trueAnomaly True anomaly. [rad]
eccentricity Eccentricity. [-]
Returns
Hyperbolic eccentric anomaly. [rad]
Definition at line 505 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity, and tudat::input_output::field_types::state::trueAnomaly.
Referenced by tudat::ephemerides::KeplerEphemeris::KeplerEphemeris(), and propagateKeplerOrbit().
convertTrueAnomalyToEccentricAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertTrueAnomalyToEccentricAnomaly (const ScalarType trueAnomaly, const ScalarType eccentricity)
Converts true anomaly to eccentric anomaly for elliptical and hyperbolic orbits (eccentricity < 1.0 && eccentricity > 1.0). This function is essentially a wrapper for convertTrueAnomalyToEllipticalEccentricAnomaly() and convertTrueAnomalyToHyperbolicEccentricAnomaly(). It should be used in cases where the eccentricity of the orbit is not known a priori. Currently, this implementation performs a check on the eccentricity and throws an error for eccentricity < 0.0 and parabolic orbits, which have not been implemented. The equations used can be found in (Chobotov, 2002).
Parameters
trueAnomaly True anomaly. [rad]
eccentricity Eccentricity. [-]
Returns
Eccentric anomaly. [rad]
Definition at line 550 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity, and tudat::input_output::field_types::state::trueAnomaly.
Referenced by tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), and tudat::ephemerides::KeplerEphemeris::KeplerEphemeris().
convertEllipticalEccentricAnomalyToTrueAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertEllipticalEccentricAnomalyToTrueAnomaly (const ScalarType ellipticEccentricAnomaly, const ScalarType eccentricity)
Converts eccentric anomaly to true anomaly for elliptical orbits (0 <= eccentricity < 1.0). The equations used can be found in (Chobotov, 2002).
Parameters
ellipticEccentricAnomaly Elliptical eccentric anomaly. [rad]
eccentricity Eccentricity. [-]
Returns
True anomaly. [rad]
Definition at line 597 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity.
Referenced by convertEccentricAnomalyToTrueAnomaly().
convertHyperbolicEccentricAnomalyToTrueAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertHyperbolicEccentricAnomalyToTrueAnomaly (const ScalarType hyperbolicEccentricAnomaly, const ScalarType eccentricity)
Converts hyperbolic eccentric anomaly to true anomaly for hyperbolic orbits (eccentricity > 1.0). The equations used can be found in (Chobotov, 2002).
Parameters
hyperbolicEccentricAnomaly Hyperbolic eccentric anomaly. [rad]
eccentricity Eccentricity. [-]
Returns
True anomaly. [rad]
Definition at line 638 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity.
Referenced by convertEccentricAnomalyToTrueAnomaly(), and propagateKeplerOrbit().
convertEccentricAnomalyToTrueAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertEccentricAnomalyToTrueAnomaly (const ScalarType eccentricAnomaly, const ScalarType eccentricity)
Converts eccentric anomaly to true anomaly for elliptical and hyperbolic orbits (eccentricity < 1.0 && eccentricity > 1.0). This function is essentially a wrapper for convertEllipticalEccentricAnomalyToTrueAnomaly() and convertHyperbolicEccentricAnomalyToTrueAnomaly(). It should be used in cases where the eccentricity of the orbit is not known a priori. Currently, this implementation performs a check on the eccentricity and throws an error for eccentricity < 0.0 and parabolic orbits, which have not been implemented. The equations used can be found in (Chobotov, 2002).
Parameters
eccentricAnomaly Eccentric anomaly. [rad]
eccentricity Eccentricity. [-]
Returns
True anomaly. [rad]
Definition at line 685 of file orbitalElementConversions.h.
References convertEllipticalEccentricAnomalyToTrueAnomaly(), convertHyperbolicEccentricAnomalyToTrueAnomaly(), and tudat::input_output::field_types::state::eccentricity.
Referenced by tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), tudat::ephemerides::KeplerStateExtractor::extract(), tudat::json_interface::getCartesianState(), tudat::ephemerides::KeplerEphemeris::getCartesianState(), and tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris().
convertEllipticalEccentricAnomalyToMeanAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertEllipticalEccentricAnomalyToMeanAnomaly (const ScalarType ellipticalEccentricAnomaly, const ScalarType eccentricity)
Converts eccentric anomaly to mean anomaly for elliptical orbits (0 <= eccentricity < 1.0). The equations used can be found in (Chobotov, 2002).
Parameters
eccentricity Eccentricity. [-]
ellipticalEccentricAnomaly (Elliptical) eccentric anomaly [rad].
Returns
Mean anomaly [rad].
Definition at line 733 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity.
convertHyperbolicEccentricAnomalyToMeanAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertHyperbolicEccentricAnomalyToMeanAnomaly (const ScalarType hyperbolicEccentricAnomaly, const ScalarType eccentricity)
Converts hyperbolic eccentric anomaly to mean anomaly for hyperbolic orbits (eccentricity > 1.0). The equations used can be found in (Chobotov, 2002).
Parameters
hyperbolicEccentricAnomaly Hyperbolic eccentric anomaly. [rad]
eccentricity Eccentricity. [-]
Returns
Mean anomaly. [rad]
Definition at line 750 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity.
Referenced by tudat::ephemerides::KeplerEphemeris::KeplerEphemeris(), and propagateKeplerOrbit().
convertEccentricAnomalyToMeanAnomaly()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertEccentricAnomalyToMeanAnomaly (const ScalarType eccentricAnomaly, const ScalarType eccentricity)
Converts eccentric anomaly to mean anomaly for elliptical and hyperbolic orbits (eccentricity < 1.0 && eccentricity > 1.0). This function is essentially a wrapper for convertEllipticalEccentricAnomalyToMeanAnomaly() and convertHyperbolicEccentricAnomalyToMeanAnomaly(). It should be used in cases where the eccentricity of the orbit is not known a priori. Currently, this implementation performs a check on the eccentricity and throws an error for eccentricity < 0.0 and parabolic orbits, which have not been implemented. The equations used can be found in (Chobotov, 2002).
Parameters
eccentricity Eccentricity. [-]
eccentricAnomaly Eccentric anomaly. [rad]
Returns
Mean anomaly. [rad]
Definition at line 771 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::eccentricity.
Referenced by tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), and tudat::ephemerides::KeplerEphemeris::KeplerEphemeris().
convertElapsedTimeToEllipticalMeanAnomalyChange()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertElapsedTimeToEllipticalMeanAnomalyChange (const ScalarType elapsedTime, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Converts elapsed time to mean anomaly change for elliptical orbits (0 <= eccentricity < 1.0). The semi-major axis must be non-negative; this function will throw an error to indicate if the semi-major axis is invalid. The equation used can be found in (Chobotov, 2002).
Parameters
elapsedTime Elapsed time. [s]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
semiMajorAxis Semi-major axis. [m]
Returns
(Elliptical) Mean anomaly change. [rad]
Definition at line 823 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::semiMajorAxis.
Referenced by convertElapsedTimeToMeanAnomalyChange(), and tudat::ephemerides::KeplerEphemeris::getCartesianState().
convertElapsedTimeToHyperbolicMeanAnomalyChange()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertElapsedTimeToHyperbolicMeanAnomalyChange (const ScalarType elapsedTime, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Converts elapsed time to mean anomaly change for hyperbolic orbits (eccentricity > 1.0). The semi-major axis must be non-positive; this function will throw an error to indicate if the semi-major axis is invalid. The equation used can be found in (Chobotov, 2002).
Parameters
elapsedTime Elapsed time. [s]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
semiMajorAxis Semi-major axis. [m]
Returns
Mean anomaly change. [rad]
Definition at line 853 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::semiMajorAxis.
Referenced by convertElapsedTimeToMeanAnomalyChange(), tudat::ephemerides::KeplerEphemeris::getCartesianState(), and propagateKeplerOrbit().
convertElapsedTimeToMeanAnomalyChange()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertElapsedTimeToMeanAnomalyChange (const ScalarType elapsedTime, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Converts elapsed time to mean anomaly change for elliptical and hyperbolic orbits (eccentricity < 1.0 && eccentricity > 1.0). This function is essentially a wrapper for convertElapsedTimeToEllipticalMeanAnomalyChange() and convertElapsedTimeToHyperbolicMeanAnomalyChange(). It should be used in cases where the eccentricity of the orbit is not known a priori. The equations used can be found in (Wertz, 2001).
Parameters
elapsedTime Elapsed time. [s]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
semiMajorAxis Semi-major axis. [m]
Returns
Mean anomaly change. [rad]
Definition at line 886 of file orbitalElementConversions.h.
References convertElapsedTimeToEllipticalMeanAnomalyChange(), convertElapsedTimeToHyperbolicMeanAnomalyChange(), and tudat::input_output::field_types::state::semiMajorAxis.
convertEllipticalMeanAnomalyChangeToElapsedTime()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertEllipticalMeanAnomalyChangeToElapsedTime (const ScalarType ellipticalMeanAnomalyChange, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Converts mean anomaly change to elapsed time for elliptical orbits (0 <= eccentricity < 1.0). The equation used can be found in (Wertz, 2001). This function checks if the semi-major axis is non-negative and throws an error if it not.
Parameters
ellipticalMeanAnomalyChange (Elliptical) Mean anomaly change. [rad]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
semiMajorAxis Semi-major axis. [m]
Returns
Elapsed time. [s]
Definition at line 923 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::semiMajorAxis.
convertHyperbolicMeanAnomalyChangeToElapsedTime()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertHyperbolicMeanAnomalyChangeToElapsedTime (const ScalarType hyperbolicMeanAnomalyChange, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Converts mean anomaly change to elapsed time for hyperbolic orbits (eccentricity > 1.0). The equation used can be found in (Wertz, 2001). This function checks if the semi-major axis is non-positive and throws an error if it not.
Parameters
hyperbolicMeanAnomalyChange Hyperbolic mean anomaly change. [rad]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
semiMajorAxis Semi-major axis. [m]
Returns
Elapsed time. [s]
Definition at line 954 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::semiMajorAxis.
convertMeanAnomalyChangeToElapsedTime()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertMeanAnomalyChangeToElapsedTime (const ScalarType meanAnomalyChange, const ScalarType centralBodyGravitationalParameter, const ScalarType semiMajorAxis)
Converts mean anomaly change to elapsed time for elliptical and hyperbolic orbits (eccentricity < 1.0 && eccentricity > 1.0). This function is essentially a wrapper for convertEllipticalMeanAnomalyChangeToElapsedTime() and convertHyperbolicMeanAnomalyChangeToElapsedTime(). It should be used in cases where the eccentricity of the orbit is not known a priori. The equations used can be found in (Wertz, 2001).
Parameters
meanAnomalyChange Mean anomaly change. [rad]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
semiMajorAxis Semi-major axis. [m]
Returns
Elapsed time. [s]
Definition at line 987 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::semiMajorAxis.
convertEllipticalMeanMotionToSemiMajorAxis()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertEllipticalMeanMotionToSemiMajorAxis (const ScalarType ellipticalMeanMotion, const ScalarType centralBodyGravitationalParameter)
Converts mean motion to semi-major axis for elliptical orbits.
Parameters
ellipticalMeanMotion (Elliptical) Mean motion. [rad/s]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
semiMajorAxis Semi-major axis. [m]
Definition at line 1020 of file orbitalElementConversions.h.
Referenced by tudat::input_output::TwoLineElementsTextFileReader::storeTwoLineElementData().
convertSemiMajorAxisToEllipticalMeanMotion()
template<typename ScalarType = double> ScalarType tudat::orbital_element_conversions::convertSemiMajorAxisToEllipticalMeanMotion (const ScalarType semiMajorAxis, const ScalarType centralBodyGravitationalParameter)
Converts semi-major axis to elliptical mean motion.
Parameters
semiMajorAxis Semi-major axis. [m]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
ellipticalMeanMotion (Elliptical) Mean motion. [rad/s]
Definition at line 1036 of file orbitalElementConversions.h.
References tudat::input_output::field_types::state::semiMajorAxis.
calculateHeadingAngle()
double tudat::orbital_element_conversions::calculateHeadingAngle (const Eigen::Vector3d & velocityInVerticalFrame)
Calculate heading angle from velocity in vertical (LVLH) frame. NOTE: This function can be used for both ground- and airspeed-based variables, with both the input and output always w.r.t. the same velocity vector.
Parameters
velocityInVerticalFrame Current Cartesian velocity in vertical frame.
Returns
Current heading angle.
Definition at line 25 of file sphericalStateConversions.cpp.
Referenced by convertCartesianToSphericalOrbitalState().
calculateFlightPathAngle()
double tudat::orbital_element_conversions::calculateFlightPathAngle (const Eigen::Vector3d & velocityInVerticalFrame)
Calculate current flight path angle. Angle is defined positive upwards.
Calculate flight path angle from velocity in vertical (LVLH) frame. Angle is defined positive upwards. NOTE: This function can be used for both ground- and airspeed-based variables, with both the input and output always w.r.t. the same velocity vector.
Parameters
velocityInVerticalFrame Current Cartesian velocity in vertical frame.
Returns
Current flight path angle.
Definition at line 31 of file sphericalStateConversions.cpp.
Referenced by convertCartesianToSphericalOrbitalState().
convertCartesianToSphericalOrbitalState()
Eigen::Vector6d tudat::orbital_element_conversions::convertCartesianToSphericalOrbitalState (const Eigen::Vector6d & bodyFixedCartesianState)
Function to convert a Cartesian to a spherical orbital state. We define the spherical orbital position by the radius, latitude and longitude. The spherical orbital velocity is defined by the speed, flight path angle (positive upwards) and the heading angle. Note that this is distinct from a 'mathematical' spherical state, where the velocity is denoted by the radius rate, latitude rate and longitude rate. The spherical orbital state is often used to define entry (initial) conditions. The order of the entries in the return vector are defined by the SphericalOrbitalStateElementIndices enum. NOTE: This function can be used for both ground- and airspeed-based variables, with both the input and output always w.r.t. the same velocity vector.
Parameters
bodyFixedCartesianState Vehicle state in a frame fixed to the body w.r.t. which the state is to be computed.
Returns
Spherical orbital state representation of bodyFixedCartesianState
Definition at line 37 of file sphericalStateConversions.cpp.
References calculateFlightPathAngle(), calculateHeadingAngle(), flightPathIndex, tudat::reference_frames::getRotatingPlanetocentricToLocalVerticalFrameTransformationQuaternion(), headingAngleIndex, latitudeIndex, longitudeIndex, tudat::mathematical_constants::PI, radiusIndex, and speedIndex.
convertSphericalOrbitalToCartesianState()
Eigen::Vector6d tudat::orbital_element_conversions::convertSphericalOrbitalToCartesianState (const Eigen::Vector6d & sphericalOrbitalState)
Function to convert a spherical orbital to a Cartesian state. We define the spherical orbital position by the radius, latitude and longitude. The spherical orbital velocity is defined by the speed, flight path angle (positive upwards) and the heading angle. Note that this is distinct from a 'mathematical' spherical state, where the velocity is denoted by the radius rate, latitude rate and longitude rate. The spherical orbital state is often used to define entry (initial) conditions. The order of the entries in the return vector are defined by the SphericalOrbitalStateElementIndices enum.
Parameters
sphericalOrbitalState Vehicle spherical orbital state in a frame fixed to the body w.r.t. which the state is to be computed. NOTE: This function can be used for both ground- and airspeed-based variables, with both the input and output always w.r.t. the same velocity vector.
Returns
Cartesian state representation of sphericalOrbitalState (in same frame).
Definition at line 65 of file sphericalStateConversions.cpp.
References tudat::coordinate_conversions::convertSphericalToCartesian(), flightPathIndex, tudat::reference_frames::getLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion(), headingAngleIndex, latitudeIndex, longitudeIndex, tudat::mathematical_constants::PI, and speedIndex.
Referenced by tudat::json_interface::getCartesianState().
convertKeplerianToUnifiedStateModelExponentialMapElements()
Eigen::Matrix< double, 7, 1 > tudat::orbital_element_conversions::convertKeplerianToUnifiedStateModelExponentialMapElements (const Eigen::Matrix< double, 6, 1 > & keplerianElements, const double centralBodyGravitationalParameter)
Convert Keplerian to unified state model elements with exponential map.
Converts Keplerian to unified state model elements with exponential map.
Parameters
keplerianElements Vector containing Keplerian elements. Order of elements is important! keplerianElements(0) = semi-major axis, [m] keplerianElements(1) = eccentricity, [-] keplerianElements(2) = inclination (in range [0,PI]), [rad] keplerianElements(3) = argument of periapsis, [rad] keplerianElements(4) = longitude of ascending node, [rad] keplerianElements(5) = true anomaly. [rad]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedUnifiedStateModelElements Converted state in unified state model elements with exponential map. The order of elements is fixed convertedUnifiedStateModelElements(0) = C hodograph element, [m/s] convertedUnifiedStateModelElements(1) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(2) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(3) = e1 exponential map element, [-] convertedUnifiedStateModelElements(4) = e2 exponential map element, [-] convertedUnifiedStateModelElements(5) = e3 exponential map element, [-] convertedUnifiedStateModelElements(6) = shadow exponential map flag. [-]
Definition at line 34 of file unifiedStateModelExponentialMapElementConversions.cpp.
References argumentOfPeriapsisIndex, CHodographUSMEMIndex, e1USMEMIndex, e2USMEMIndex, e3USMEMIndex, eccentricityIndex, inclinationIndex, tudat::json_interface::keplerianElements, longitudeOfAscendingNodeIndex, tudat::mathematical_constants::PI, Rf1HodographUSMEMIndex, Rf2HodographUSMEMIndex, semiLatusRectumIndex, semiMajorAxisIndex, shadowFlagUSMEMIndex, and trueAnomalyIndex.
convertUnifiedStateModelExponentialMapToKeplerianElements()
Eigen::Matrix< double, 6, 1 > tudat::orbital_element_conversions::convertUnifiedStateModelExponentialMapToKeplerianElements (const Eigen::Matrix< double, 7, 1 > & unifiedStateModelElements, const double centralBodyGravitationalParameter)
Converts unified state model elements with exponential map to Keplerian elements.
Parameters
unifiedStateModelElements Vector containing unified state model elements with exponential map. Order of elements is important! unifiedStateModelElements(0) = C hodograph element, [m/s] unifiedStateModelElements(1) = Rf1 hodograph element, [m/s] unifiedStateModelElements(2) = Rf1 hodograph element, [m/s] unifiedStateModelElements(3) = e1 exponential map element, [-] unifiedStateModelElements(4) = e2 exponential map element, [-] unifiedStateModelElements(5) = e3 exponential map element, [-] unifiedStateModelElements(6) = shadow exponential map flag. [-]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedKeplerianElements Converted state in Keplerian elements. The order of elements is fixed! convertedKeplerianElements(0) = semi-major axis, [m] convertedKeplerianElements(1) = eccentricity, [-] convertedKeplerianElements(2) = inclination (in range [0,PI]), [rad] convertedKeplerianElements(3) = argument of periapsis, [rad] convertedKeplerianElements(4) = longitude of ascending node, [rad] convertedKeplerianElements(5) = true anomaly. [rad]
Definition at line 247 of file unifiedStateModelExponentialMapElementConversions.cpp.
References argumentOfPeriapsisIndex, CHodographUSMEMIndex, e1USMEMIndex, e2USMEMIndex, e3USMEMIndex, eccentricityIndex, inclinationIndex, longitudeOfAscendingNodeIndex, tudat::mathematical_constants::PI, Rf1HodographUSMEMIndex, Rf2HodographUSMEMIndex, semiLatusRectumIndex, semiMajorAxisIndex, and trueAnomalyIndex.
convertCartesianToUnifiedStateModelExponentialMapElements()
Eigen::Matrix< double, 7, 1 > tudat::orbital_element_conversions::convertCartesianToUnifiedStateModelExponentialMapElements (const Eigen::Matrix< double, 6, 1 > & cartesianElements, const double centralBodyGravitationalParameter)
Converts Cartesian to unified state model elements with exponential map.
Parameters
cartesianElements Converted state in Cartesian elements. The order of elements is fixed! cartesianElements(0) = x-position coordinate, [m] cartesianElements(1) = y-position coordinate, [m] cartesianElements(2) = z-position coordinate, [m] cartesianElements(3) = x-velocity coordinate, [m/s] cartesianElements(4) = y-velocity coordinate, [m/s] cartesianElements(5) = z-velocity coordinate. [m/s]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedUnifiedStateModelElements Converted state in unified state model elements with exponential map. The order of elements is fixed convertedUnifiedStateModelElements(0) = C hodograph element, [m/s] convertedUnifiedStateModelElements(1) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(2) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(3) = e1 exponential map element, [-] convertedUnifiedStateModelElements(4) = e2 exponential map element, [-] convertedUnifiedStateModelElements(5) = e3 exponential map element, [-] convertedUnifiedStateModelElements(6) = shadow exponential map flag. [-]
Definition at line 447 of file unifiedStateModelExponentialMapElementConversions.cpp.
References tudat::json_interface::cartesianElements, CHodographUSM7Index, CHodographUSMEMIndex, convertCartesianToUnifiedStateModelQuaternionsElements(), convertQuaternionsToExponentialMapElements(), e1USMEMIndex, and etaUSM7Index.
Referenced by tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution().
convertUnifiedStateModelExponentialMapToCartesianElements()
Eigen::Matrix< double, 6, 1 > tudat::orbital_element_conversions::convertUnifiedStateModelExponentialMapToCartesianElements (const Eigen::Matrix< double, 7, 1 > & unifiedStateModelElements, const double centralBodyGravitationalParameter)
Converts unified state model elements with exponential map to Cartesian elements.
Parameters
unifiedStateModelElements Vector containing unified state model elements with exponential map. Order of elements is important! unifiedStateModelElements(0) = C hodograph element, [m/s] unifiedStateModelElements(1) = Rf1 hodograph element, [m/s] unifiedStateModelElements(2) = Rf1 hodograph element, [m/s] unifiedStateModelElements(3) = e1 exponential map element, [-] unifiedStateModelElements(4) = e2 exponential map element, [-] unifiedStateModelElements(5) = e3 exponential map element, [-] unifiedStateModelElements(6) = shadow exponential map flag. [-]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedCartesianElements Converted state in Cartesian elements. The order of elements is fixed! convertedCartesianElements(0) = x-position coordinate, [m] convertedCartesianElements(1) = y-position coordinate, [m] convertedCartesianElements(2) = z-position coordinate, [m] convertedCartesianElements(3) = x-velocity coordinate, [m/s] convertedCartesianElements(4) = y-velocity coordinate, [m/s] convertedCartesianElements(5) = z-velocity coordinate. [m/s]
Definition at line 472 of file unifiedStateModelExponentialMapElementConversions.cpp.
References CHodographUSM7Index, CHodographUSMEMIndex, convertExponentialMapToQuaternionElements(), convertUnifiedStateModelQuaternionsToCartesianElements(), e1USMEMIndex, and etaUSM7Index.
Referenced by tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::convertToOutputSolution().
convertKeplerianToUnifiedStateModelModifiedRodriguesParameterElements()
Eigen::Matrix< double, 7, 1 > tudat::orbital_element_conversions::convertKeplerianToUnifiedStateModelModifiedRodriguesParameterElements (const Eigen::Matrix< double, 6, 1 > & keplerianElements, const double centralBodyGravitationalParameter)
Convert Keplerian to unified state model elements with modified rodrigues parameters.
Converts Keplerian to unified state model elements with modified rodrigues parameters.
Parameters
keplerianElements Vector containing Keplerian elements. Order of elements is important! keplerianElements(0) = semi-major axis, [m] keplerianElements(1) = eccentricity, [-] keplerianElements(2) = inclination (in range [0,PI]), [rad] keplerianElements(3) = argument of periapsis, [rad] keplerianElements(4) = longitude of ascending node, [rad] keplerianElements(5) = true anomaly. [rad]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedUnifiedStateModelElements Converted state in unified state model elements with modified rodrigues parameters. The order of elements is fixed convertedUnifiedStateModelElements(0) = C hodograph element, [m/s] convertedUnifiedStateModelElements(1) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(2) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(3) = sigma1 modified rodrigues parameters element, [-] convertedUnifiedStateModelElements(4) = sigma2 modified rodrigues parameters element, [-] convertedUnifiedStateModelElements(5) = sigma3 modified rodrigues parameters element, [-] convertedUnifiedStateModelElements(6) = shadow modified rodrigues parameters flag. [-]
Definition at line 34 of file unifiedStateModelModifiedRodriguesParameterElementConversions.cpp.
References argumentOfPeriapsisIndex, CHodographUSM6Index, eccentricityIndex, inclinationIndex, tudat::json_interface::keplerianElements, longitudeOfAscendingNodeIndex, tudat::mathematical_constants::PI, Rf1HodographUSM6Index, Rf2HodographUSM6Index, semiLatusRectumIndex, semiMajorAxisIndex, shadowFlagUSM6Index, sigma1USM6Index, sigma2USM6Index, sigma3USM6Index, and trueAnomalyIndex.
convertUnifiedStateModelModifiedRodriguesParametersToKeplerianElements()
Eigen::Matrix< double, 6, 1 > tudat::orbital_element_conversions::convertUnifiedStateModelModifiedRodriguesParametersToKeplerianElements (const Eigen::Matrix< double, 7, 1 > & unifiedStateModelElements, const double centralBodyGravitationalParameter)
Convert unified state model elements with modified rodrigues parameters to Keplerian elements.
Converts unified state model elements with modified rodrigues parameters to Keplerian elements.
Parameters
unifiedStateModelElements Vector containing unified state model elements with modified rodrigues parameters. Order of elements is important! unifiedStateModelElements(0) = C hodograph element, [m/s] unifiedStateModelElements(1) = Rf1 hodograph element, [m/s] unifiedStateModelElements(2) = Rf1 hodograph element, [m/s] unifiedStateModelElements(3) = sigma1 modified rodrigues parameters element, [-] unifiedStateModelElements(4) = sigma2 modified rodrigues parameters element, [-] unifiedStateModelElements(5) = sigma3 modified rodrigues parameters element. [-] unifiedStateModelElements(6) = shadow modified rodrigues parameters flag. [-]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedKeplerianElements Converted state in Keplerian elements. The order of elements is fixed! convertedKeplerianElements(0) = semi-major axis, [m] convertedKeplerianElements(1) = eccentricity, [-] convertedKeplerianElements(2) = inclination (in range [0,PI]), [rad] convertedKeplerianElements(3) = argument of periapsis, [rad] convertedKeplerianElements(4) = longitude of ascending node, [rad] convertedKeplerianElements(5) = true anomaly. [rad]
Definition at line 230 of file unifiedStateModelModifiedRodriguesParameterElementConversions.cpp.
References argumentOfPeriapsisIndex, CHodographUSM6Index, eccentricityIndex, inclinationIndex, longitudeOfAscendingNodeIndex, tudat::mathematical_constants::PI, Rf1HodographUSM6Index, Rf2HodographUSM6Index, semiLatusRectumIndex, semiMajorAxisIndex, shadowFlagUSM6Index, sigma1USM6Index, and trueAnomalyIndex.
convertCartesianToUnifiedStateModelModifiedRodriguesParameterElements()
Eigen::Matrix< double, 7, 1 > tudat::orbital_element_conversions::convertCartesianToUnifiedStateModelModifiedRodriguesParameterElements (const Eigen::Matrix< double, 6, 1 > & cartesianElements, const double centralBodyGravitationalParameter)
Converts Cartesian to unified state model elements with modified rodrigues parameters.
Parameters
cartesianElements Converted state in Cartesian elements. The order of elements is fixed! cartesianElements(0) = x-position coordinate, [m] cartesianElements(1) = y-position coordinate, [m] cartesianElements(2) = z-position coordinate, [m] cartesianElements(3) = x-velocity coordinate, [m/s] cartesianElements(4) = y-velocity coordinate, [m/s] cartesianElements(5) = z-velocity coordinate. [m/s]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedUnifiedStateModelElements Converted state in unified state model elements with modified rodrigues parameters. The order of elements is fixed convertedUnifiedStateModelElements(0) = C hodograph element, [m/s] convertedUnifiedStateModelElements(1) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(2) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(3) = sigma1 modified rodrigues parameters element, [-] convertedUnifiedStateModelElements(4) = sigma2 modified rodrigues parameters element, [-] convertedUnifiedStateModelElements(5) = sigma3 modified rodrigues parameters element, [-] convertedUnifiedStateModelElements(6) = shadow modified rodrigues parameters flag. [-]
Definition at line 442 of file unifiedStateModelModifiedRodriguesParameterElementConversions.cpp.
References tudat::json_interface::cartesianElements, CHodographUSM6Index, CHodographUSM7Index, convertCartesianToUnifiedStateModelQuaternionsElements(), convertQuaternionsToModifiedRodriguesParameterElements(), etaUSM7Index, and sigma1USM6Index.
Referenced by tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution().
convertUnifiedStateModelModifiedRodriguesParametersToCartesianElements()
Eigen::Matrix< double, 6, 1 > tudat::orbital_element_conversions::convertUnifiedStateModelModifiedRodriguesParametersToCartesianElements (const Eigen::Matrix< double, 7, 1 > & unifiedStateModelElements, const double centralBodyGravitationalParameter)
Convert unified state model elements with modified rodrigues parameters to Cartesian elements.
Converts unified state model elements with modified rodrigues parameters to Cartesian elements.
Parameters
unifiedStateModelElements Vector containing unified state model elements with modified rodrigues parameters. Order of elements is important! unifiedStateModelElements(0) = C hodograph element, [m/s] unifiedStateModelElements(1) = Rf1 hodograph element, [m/s] unifiedStateModelElements(2) = Rf1 hodograph element, [m/s] unifiedStateModelElements(3) = sigma1 modified rodrigues parameters element, [-] unifiedStateModelElements(4) = sigma2 modified rodrigues parameters element, [-] unifiedStateModelElements(5) = sigma3 modified rodrigues parameters element. [-] unifiedStateModelElements(6) = shadow modified rodrigues parameters flag. [-]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedCartesianElements Converted state in Cartesian elements. The order of elements is fixed! convertedCartesianElements(0) = x-position coordinate, [m] convertedCartesianElements(1) = y-position coordinate, [m] convertedCartesianElements(2) = z-position coordinate, [m] convertedCartesianElements(3) = x-velocity coordinate, [m/s] convertedCartesianElements(4) = y-velocity coordinate, [m/s] convertedCartesianElements(5) = z-velocity coordinate. [m/s]
Definition at line 467 of file unifiedStateModelModifiedRodriguesParameterElementConversions.cpp.
References CHodographUSM7Index, CHodographUSMEMIndex, convertModifiedRodriguesParametersToQuaternionElements(), convertUnifiedStateModelQuaternionsToCartesianElements(), etaUSM7Index, and sigma1USM6Index.
Referenced by tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::convertToOutputSolution().
convertKeplerianToUnifiedStateModelQuaternionsElements()
Eigen::Matrix< double, 7, 1 > tudat::orbital_element_conversions::convertKeplerianToUnifiedStateModelQuaternionsElements (const Eigen::Matrix< double, 6, 1 > & keplerianElements, const double centralBodyGravitationalParameter)
Convert Keplerian to unified state model elements with quaternions.
Converts Keplerian to unified state model elements with quaternions.
Parameters
keplerianElements Vector containing Keplerian elements. Order of elements is important! keplerianElements(0) = semi-major axis, [m] keplerianElements(1) = eccentricity, [-] keplerianElements(2) = inclination (in range [0,PI]), [rad] keplerianElements(3) = argument of periapsis, [rad] keplerianElements(4) = longitude of ascending node, [rad] keplerianElements(5) = true anomaly. [rad]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedUnifiedStateModelElements Converted state in unified state model elements with quaternions. The order of elements is fixed convertedUnifiedStateModelElements(0) = C hodograph element, [m/s] convertedUnifiedStateModelElements(1) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(2) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(3) = epsilon1 quaternion element, [-] convertedUnifiedStateModelElements(4) = epsilon2 quaternion element, [-] convertedUnifiedStateModelElements(5) = epsilon3 quaternion element, [-] convertedUnifiedStateModelElements(6) = eta quaternion element. [-]
Definition at line 31 of file unifiedStateModelQuaternionElementConversions.cpp.
References argumentOfPeriapsisIndex, CHodographUSM7Index, eccentricityIndex, epsilon1USM7Index, epsilon2USM7Index, epsilon3USM7Index, etaUSM7Index, inclinationIndex, tudat::json_interface::keplerianElements, longitudeOfAscendingNodeIndex, tudat::mathematical_constants::PI, Rf1HodographUSM7Index, Rf2HodographUSM7Index, semiLatusRectumIndex, semiMajorAxisIndex, and trueAnomalyIndex.
convertUnifiedStateModelQuaternionsToKeplerianElements()
Eigen::Matrix< double, 6, 1 > tudat::orbital_element_conversions::convertUnifiedStateModelQuaternionsToKeplerianElements (const Eigen::Matrix< double, 7, 1 > & unifiedStateModelElements, const double centralBodyGravitationalParameter, const bool forceQuaternionNormalization = false)
Converts unified state model elements with quaternions to Keplerian elements.
Parameters
unifiedStateModelElements Vector containing unified state model elements with quaternions. Order of elements is important! unifiedStateModelElements(0) = C hodograph element, [m/s] unifiedStateModelElements(1) = Rf1 hodograph element, [m/s] unifiedStateModelElements(2) = Rf1 hodograph element, [m/s] unifiedStateModelElements(3) = epsilon1 quaternion element, [-] unifiedStateModelElements(4) = epsilon2 quaternion element, [-] unifiedStateModelElements(5) = epsilon3 quaternion element, [-] unifiedStateModelElements(6) = eta quaternion element. [-]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
forceQuaternionNormalization Boolean denoting whether the normalization of the quaternion vector has to be forced.
Returns
convertedKeplerianElements Converted state in Keplerian elements. The order of elements is fixed! convertedKeplerianElements(0) = semi-major axis, [m] convertedKeplerianElements(1) = eccentricity, [-] convertedKeplerianElements(2) = inclination (in range [0,PI]), [rad] convertedKeplerianElements(3) = argument of periapsis, [rad] convertedKeplerianElements(4) = longitude of ascending node, [rad] convertedKeplerianElements(5) = true anomaly. [rad]
Definition at line 219 of file unifiedStateModelQuaternionElementConversions.cpp.
References argumentOfPeriapsisIndex, CHodographUSM7Index, eccentricityIndex, epsilon1QuaternionIndex, epsilon2QuaternionIndex, epsilon3QuaternionIndex, etaQuaternionIndex, etaUSM7Index, inclinationIndex, longitudeOfAscendingNodeIndex, tudat::mathematical_constants::PI, Rf1HodographUSM7Index, Rf2HodographUSM7Index, semiLatusRectumIndex, semiMajorAxisIndex, and trueAnomalyIndex.
convertCartesianToUnifiedStateModelQuaternionsElements()
Eigen::Matrix< double, 7, 1 > tudat::orbital_element_conversions::convertCartesianToUnifiedStateModelQuaternionsElements (const Eigen::Matrix< double, 6, 1 > & cartesianElements, const double centralBodyGravitationalParameter)
Converts Cartesian to unified state model elements with quaternions.
Parameters
cartesianElements Converted state in Cartesian elements. The order of elements is fixed! cartesianElements(0) = x-position coordinate, [m] cartesianElements(1) = y-position coordinate, [m] cartesianElements(2) = z-position coordinate, [m] cartesianElements(3) = x-velocity coordinate, [m/s] cartesianElements(4) = y-velocity coordinate, [m/s] cartesianElements(5) = z-velocity coordinate. [m/s]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
Returns
convertedUnifiedStateModelElements Converted state in unified state model elements with quaternions. The order of elements is fixed convertedUnifiedStateModelElements(0) = C hodograph element, [m/s] convertedUnifiedStateModelElements(1) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(2) = Rf1 hodograph element, [m/s] convertedUnifiedStateModelElements(3) = epsilon1 quaternion element, [-] convertedUnifiedStateModelElements(4) = epsilon2 quaternion element, [-] convertedUnifiedStateModelElements(5) = epsilon3 quaternion element, [-] convertedUnifiedStateModelElements(6) = eta quaternion element. [-]
Definition at line 435 of file unifiedStateModelQuaternionElementConversions.cpp.
References tudat::json_interface::cartesianElements, CHodographUSM7Index, epsilon1USM7Index, epsilon2USM7Index, epsilon3USM7Index, etaUSM7Index, tudat::mathematical_constants::PI, Rf1HodographUSM7Index, Rf2HodographUSM7Index, xCartesianPositionIndex, and xCartesianVelocityIndex.
Referenced by convertCartesianToUnifiedStateModelExponentialMapElements(), convertCartesianToUnifiedStateModelModifiedRodriguesParameterElements(), and tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution().
convertUnifiedStateModelQuaternionsToCartesianElements()
Eigen::Matrix< double, 6, 1 > tudat::orbital_element_conversions::convertUnifiedStateModelQuaternionsToCartesianElements (const Eigen::Matrix< double, 7, 1 > & unifiedStateModelElements, const double centralBodyGravitationalParameter, const bool forceQuaternionNormalization = false)
Converts unified state model elements with quaternions to Cartesian elements.
Parameters
unifiedStateModelElements Vector containing unified state model elements with quaternions. Order of elements is important! unifiedStateModelElements(0) = C hodograph element, [m/s] unifiedStateModelElements(1) = Rf1 hodograph element, [m/s] unifiedStateModelElements(2) = Rf1 hodograph element, [m/s] unifiedStateModelElements(3) = epsilon1 quaternion element, [-] unifiedStateModelElements(4) = epsilon2 quaternion element, [-] unifiedStateModelElements(5) = epsilon3 quaternion element, [-] unifiedStateModelElements(6) = eta quaternion element. [-]
centralBodyGravitationalParameter Gravitational parameter of central body. [m^3/s^2]
forceQuaternionNormalization Boolean denoting whether the normalization of the quaternion vector has to be forced.
Returns
convertedCartesianElements Converted state in Cartesian elements. The order of elements is fixed! convertedCartesianElements(0) = x-position coordinate, [m] convertedCartesianElements(1) = y-position coordinate, [m] convertedCartesianElements(2) = z-position coordinate, [m] convertedCartesianElements(3) = x-velocity coordinate, [m/s] convertedCartesianElements(4) = y-velocity coordinate, [m/s] convertedCartesianElements(5) = z-velocity coordinate. [m/s]
Definition at line 612 of file unifiedStateModelQuaternionElementConversions.cpp.
References CHodographUSM7Index, tudat::linear_algebra::convertVectorToQuaternionFormat(), epsilon3QuaternionIndex, etaQuaternionIndex, etaUSM7Index, tudat::mathematical_constants::PI, Rf1HodographUSM7Index, Rf2HodographUSM7Index, xCartesianPositionIndex, and xCartesianVelocityIndex.
Referenced by tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), convertUnifiedStateModelExponentialMapToCartesianElements(), and convertUnifiedStateModelModifiedRodriguesParametersToCartesianElements().