Tudat: tudat::ephemerides::RotationalEphemeris Class Reference
tudat::ephemerides::RotationalEphemeris Class Reference abstract
Base class for rotational ephemerides of bodies.
#include <rotationalEphemeris.h>
Public Member Functions
RotationalEphemeris (const std::string &baseFrameOrientation="", const std::string &targetFrameOrientation="")
Constructor.
virtual ~RotationalEphemeris ()
Virtual destructor.
std::string getBaseFrameOrientation ()
Get base reference frame orientation.
virtual Eigen::Matrix3d getDerivativeOfRotationToBaseFrame (const double secondsSinceEpoch)=0
Function to calculate the derivative of the rotation matrix from target frame to original frame.
virtual Eigen::Matrix3d getDerivativeOfRotationToBaseFrameFromExtendedTime (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame in Time precision.
template<>
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const double timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame.
template<>
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame.
template<typename TimeType >
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const TimeType timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame in templated precision.
virtual Eigen::Matrix3d getDerivativeOfRotationToTargetFrame (const double secondsSinceEpoch)=0
Function to calculate the derivative of the rotation matrix from original frame to target frame.
virtual Eigen::Matrix3d getDerivativeOfRotationToTargetFrameFromExtendedTime (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from original frame to target frame in Time precision.
template<>
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix to target frame from original frame.
template<>
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const Time secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix to target frame from original frame.
template<typename TimeType >
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const TimeType secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from original frame to target frame in templated precision.
virtual void getFullRotationalQuantitiesToTargetFrame (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const double secondsSinceEpoch)
Function to calculate the full rotational state at given time.
virtual void getFullRotationalQuantitiesToTargetFrameFromExtendedTime (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const Time timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<>
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const double timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<>
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const Time timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<typename TimeType >
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const TimeType timeSinceEpoch)
Function to calculate the full rotational state at given time.
virtual Eigen::Vector3d getRotationalVelocityVectorInBaseFrame (const double secondsSinceEpoch)
Function to retrieve the angular velocity vector, expressed in base frame.
virtual Eigen::Vector3d getRotationalVelocityVectorInTargetFrame (const double secondsSinceEpoch)
Function to retrieve the angular velocity vector, expressed in target frame.
virtual Eigen::Quaterniond getRotationToBaseFrame (const double secondsSinceEpoch)=0
Get rotation quaternion from target frame to base frame.
virtual Eigen::Quaterniond getRotationToBaseFrameFromExtendedTime (const Time timeSinceEpoch)
Get rotation quaternion from target frame to base frame in Time precision.
template<>
Eigen::Quaterniond getRotationToBaseFrameTemplated (const double timeSinceEpoch)
Get rotation quaternion from target frame to base frame.
template<>
Eigen::Quaterniond getRotationToBaseFrameTemplated (const Time timeSinceEpoch)
Get rotation quaternion from target frame to base frame.
template<typename TimeType >
Eigen::Quaterniond getRotationToBaseFrameTemplated (const TimeType timeSinceEpoch)
Get rotation quaternion from target frame to base frame in templated precision.
virtual Eigen::Quaterniond getRotationToTargetFrame (const double secondsSinceEpoch)=0
Get rotation quaternion to target frame from base frame.
virtual Eigen::Quaterniond getRotationToTargetFrameFromExtendedTime (const Time timeSinceEpoch)
Get rotation quaternion to target frame from base frame in Time precision.
template<>
Eigen::Quaterniond getRotationToTargetFrameTemplated (const double secondsSinceEpoch)
Get rotation quaternion to target frame from base frame.
template<>
Eigen::Quaterniond getRotationToTargetFrameTemplated (const Time secondsSinceEpoch)
Get rotation quaternion to target frame from base frame.
template<typename TimeType >
Eigen::Quaterniond getRotationToTargetFrameTemplated (const TimeType secondsSinceEpoch)
Get rotation quaternion to target frame from base frame in templated precision.
std::string getTargetFrameOrientation ()
Get target reference frame orientation.
Protected Attributes
const std::string baseFrameOrientation_
Base reference frame orientation.
const std::string targetFrameOrientation_
Target reference frame orientation.
Detailed Description
Base class for rotational ephemerides of bodies. The rotation (quaternion) between two frames specified by member variable ids can be calculated as a function of time in the manner determined by the derived class.
Definition at line 166 of file rotationalEphemeris.h.
Constructor & Destructor Documentation
tudat::ephemerides::RotationalEphemeris::RotationalEphemeris (const std::string & baseFrameOrientation = "", const std::string & targetFrameOrientation = "") inline
Constructor, sets frames between which rotation is determined.
Parameters
baseFrameOrientation Base frame identifier.
targetFrameOrientation Target frame identifier.
Definition at line 176 of file rotationalEphemeris.h.
virtual tudat::ephemerides::RotationalEphemeris::~RotationalEphemeris () inline virtual
Virtual destructor.
Definition at line 186 of file rotationalEphemeris.h.
References getRotationToBaseFrame().
Member Function Documentation
virtual Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToBaseFrame (const double secondsSinceEpoch) pure virtual
Pure virtual function to calculate and return the rotation quaternion from target frame to base frame at specified time.
Parameters
secondsSinceEpoch Seconds since Julian day reference epoch.
Returns
Rotation quaternion computed.
Implemented in tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >, tudat::ephemerides::SimpleRotationalEphemeris, and tudat::ephemerides::SpiceRotationalEphemeris.
Referenced by getRotationToBaseFrameFromExtendedTime(), and ~RotationalEphemeris().
virtual Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToBaseFrameFromExtendedTime (const Time timeSinceEpoch) inline virtual
Pure virtual function to calculate and return the rotation quaternion from target frame to base frame at specified time.
Parameters
timeSinceEpoch Seconds since Julian day reference epoch.
Returns
Rotation quaternion computed.
Definition at line 205 of file rotationalEphemeris.h.
References getRotationToBaseFrame(), getRotationToBaseFrameTemplated(), getRotationToTargetFrame(), and tudat::Time::getSeconds().
template<typename TimeType > Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToBaseFrameTemplated (const TimeType timeSinceEpoch)
Pure virtual function to calculate and return the rotation quaternion from target frame to base frame at specified time.
Parameters
timeSinceEpoch Seconds since Julian day reference epoch.
Returns
Rotation quaternion computed.
Referenced by getRotationToBaseFrameFromExtendedTime().
virtual Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrame (const double secondsSinceEpoch) pure virtual
Pure virtual function to calculate and return the rotation quaternion to target frame from base frame at specified time.
Parameters
secondsSinceEpoch Seconds since Julian day reference epoch.
Returns
Rotation quaternion computed.
Implemented in tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >, tudat::ephemerides::SimpleRotationalEphemeris, and tudat::ephemerides::SpiceRotationalEphemeris.
Referenced by tudat::simulation_setup::createGravityFieldVariationsModel(), tudat::simulation_setup::createGroundStation(), getFullRotationalQuantitiesToTargetFrame(), getRotationalVelocityVectorInBaseFrame(), getRotationalVelocityVectorInTargetFrame(), getRotationToBaseFrameFromExtendedTime(), getRotationToTargetFrameFromExtendedTime(), and tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure().
virtual Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrameFromExtendedTime (const Time timeSinceEpoch) inline virtual
Pure virtual function to calculate and return the rotation quaternion to target frame from base frame at specified time.
Parameters
timeSinceEpoch Seconds since Julian day reference epoch.
Returns
Rotation quaternion computed.
Definition at line 239 of file rotationalEphemeris.h.
References getDerivativeOfRotationToBaseFrame(), getRotationToTargetFrame(), getRotationToTargetFrameTemplated(), and tudat::Time::getSeconds().
Referenced by getFullRotationalQuantitiesToTargetFrameFromExtendedTime().
template<typename TimeType > Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrameTemplated (const TimeType secondsSinceEpoch)
Pure virtual function to calculate and return the rotation quaternion to target frame from base frame at specified time.
Parameters
secondsSinceEpoch Seconds since Julian day reference epoch.
Returns
Rotation quaternion computed.
Referenced by getRotationToTargetFrameFromExtendedTime().
virtual Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToBaseFrame (const double secondsSinceEpoch) pure virtual
Function to calculate the derivative of the rotation matrix from target frame to original frame at specified time, to be implemented by derived class.
Parameters
secondsSinceEpoch Seconds since Julian day reference epoch.
Returns
Derivative of rotation from target (typically local) to original (typically global) frame at specified time.
Implemented in tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >, tudat::ephemerides::SimpleRotationalEphemeris, and tudat::ephemerides::SpiceRotationalEphemeris.
Referenced by getDerivativeOfRotationToBaseFrameFromExtendedTime(), getRotationalVelocityVectorInBaseFrame(), and getRotationToTargetFrameFromExtendedTime().
virtual Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToBaseFrameFromExtendedTime (const Time timeSinceEpoch) inline virtual
Function to calculate the derivative of the rotation matrix from target frame to original frame at specified time, to be implemented by derived class.
Parameters
timeSinceEpoch Seconds since Julian day reference epoch.
Returns
Derivative of rotation from target (typically local) to original (typically global) frame at specified time.
Definition at line 275 of file rotationalEphemeris.h.
References getDerivativeOfRotationToBaseFrame(), getDerivativeOfRotationToBaseFrameTemplated(), getDerivativeOfRotationToTargetFrame(), and tudat::Time::getSeconds().
template<typename TimeType > Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToBaseFrameTemplated (const TimeType timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame at specified time, to be implemented by derived class.
Parameters
timeSinceEpoch Seconds since Julian day reference epoch.
Returns
Derivative of rotation from target (typically local) to original (typically global) frame at specified time.
Referenced by getDerivativeOfRotationToBaseFrameFromExtendedTime().
virtual Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToTargetFrame (const double secondsSinceEpoch) pure virtual
Function to calculate the derivative of the rotation matrix from original frame to target frame at specified time, to be implemented by derived class.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Derivative of rotation from original (typically global) to target (typically local) frame at specified time.
Implemented in tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >, tudat::ephemerides::SimpleRotationalEphemeris, and tudat::ephemerides::SpiceRotationalEphemeris.
Referenced by getDerivativeOfRotationToBaseFrameFromExtendedTime(), getDerivativeOfRotationToTargetFrameFromExtendedTime(), and getFullRotationalQuantitiesToTargetFrame().
virtual Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToTargetFrameFromExtendedTime (const Time timeSinceEpoch) inline virtual
Function to calculate the derivative of the rotation matrix from original frame to target frame at specified time, to be implemented by derived class.
Parameters
timeSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Derivative of rotation from original (typically global) to target (typically local) frame at specified time.
Definition at line 312 of file rotationalEphemeris.h.
References getDerivativeOfRotationToTargetFrame(), getDerivativeOfRotationToTargetFrameTemplated(), and tudat::Time::getSeconds().
Referenced by getFullRotationalQuantitiesToTargetFrameFromExtendedTime().
template<typename TimeType > Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToTargetFrameTemplated (const TimeType secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from original frame to target frame at specified time, to be implemented by derived class.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Derivative of rotation from original (typically global) to target (typically local) frame at specified time.
Referenced by getDerivativeOfRotationToTargetFrameFromExtendedTime().
virtual Eigen::Vector3d tudat::ephemerides::RotationalEphemeris::getRotationalVelocityVectorInBaseFrame (const double secondsSinceEpoch) inline virtual
Function to retrieve the angular velocity vector, expressed in base frame. Thsi function uses the functions that calculate the rotation matrix and its time derivative. It may be redefined in a derived class, to calculate the angular velocity vector directly
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Angular velocity vector, expressed in base frame.
Reimplemented in tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >.
Definition at line 338 of file rotationalEphemeris.h.
References getDerivativeOfRotationToBaseFrame(), tudat::ephemerides::getRotationalVelocityVectorInBaseFrameFromMatrices(), and getRotationToTargetFrame().
Referenced by getRotationalVelocityVectorInTargetFrame().
virtual Eigen::Vector3d tudat::ephemerides::RotationalEphemeris::getRotationalVelocityVectorInTargetFrame (const double secondsSinceEpoch) inline virtual
Function to retrieve the angular velocity vector, expressed in target frame. This function calls the function that calculates the angular velocioty vector in the base frame, and rotates it to teh target frame. It may be redefined in a derived class, to calculate the angular velocity vector directly
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Angular velocity vector, expressed in target frame.
Reimplemented in tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >.
Definition at line 354 of file rotationalEphemeris.h.
References getRotationalVelocityVectorInBaseFrame(), and getRotationToTargetFrame().
virtual void tudat::ephemerides::RotationalEphemeris::getFullRotationalQuantitiesToTargetFrame (Eigen::Quaterniond & currentRotationToLocalFrame, Eigen::Matrix3d & currentRotationToLocalFrameDerivative, Eigen::Vector3d & currentAngularVelocityVectorInGlobalFrame, const double secondsSinceEpoch) inline virtual
Function to calculate the full rotational state at given time (rotation matrix, derivative of rotation matrix and angular velocity vector).
Parameters
currentRotationToLocalFrame Current rotation to local frame (returned by reference)
currentRotationToLocalFrameDerivative Current derivative of rotation matrix to local frame (returned by reference)
currentAngularVelocityVectorInGlobalFrame Current angular velocity vector, expressed in global frame (returned by reference)
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Reimplemented in tudat::ephemerides::SpiceRotationalEphemeris.
Definition at line 372 of file rotationalEphemeris.h.
References getDerivativeOfRotationToTargetFrame(), tudat::ephemerides::getRotationalVelocityVectorInBaseFrameFromMatrices(), and getRotationToTargetFrame().
virtual void tudat::ephemerides::RotationalEphemeris::getFullRotationalQuantitiesToTargetFrameFromExtendedTime (Eigen::Quaterniond & currentRotationToLocalFrame, Eigen::Matrix3d & currentRotationToLocalFrameDerivative, Eigen::Vector3d & currentAngularVelocityVectorInGlobalFrame, const Time timeSinceEpoch) inline virtual
Function to calculate the full rotational state at given time (rotation matrix, derivative of rotation matrix and angular velocity vector).
Parameters
currentRotationToLocalFrame Current rotation to local frame (returned by reference)
currentRotationToLocalFrameDerivative Current derivative of rotation matrix to local frame (returned by reference)
currentAngularVelocityVectorInGlobalFrame Current angular velocity vector, expressed in global frame (returned by reference)
timeSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Definition at line 395 of file rotationalEphemeris.h.
References getDerivativeOfRotationToTargetFrameFromExtendedTime(), getFullRotationalQuantitiesToTargetFrameTemplated(), tudat::ephemerides::getRotationalVelocityVectorInBaseFrameFromMatrices(), and getRotationToTargetFrameFromExtendedTime().
template<typename TimeType > void tudat::ephemerides::RotationalEphemeris::getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond & currentRotationToLocalFrame, Eigen::Matrix3d & currentRotationToLocalFrameDerivative, Eigen::Vector3d & currentAngularVelocityVectorInGlobalFrame, const TimeType timeSinceEpoch)
Function to calculate the full rotational state at given time (rotation matrix, derivative of rotation matrix and angular velocity vector).
Parameters
currentRotationToLocalFrame Current rotation to local frame (returned by reference)
currentRotationToLocalFrameDerivative Current derivative of rotation matrix to local frame (returned by reference)
currentAngularVelocityVectorInGlobalFrame Current angular velocity vector, expressed in global frame (returned by reference)
timeSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Referenced by getFullRotationalQuantitiesToTargetFrameFromExtendedTime().
std::string tudat::ephemerides::RotationalEphemeris::getBaseFrameOrientation () inline
Function to retrieve the base reference frame orientation.
Returns
Base reference frame orientation.
Definition at line 430 of file rotationalEphemeris.h.
References baseFrameOrientation_.
std::string tudat::ephemerides::RotationalEphemeris::getTargetFrameOrientation () inline
Function to retrieve the target reference frame orientation.
Returns
Target reference frame orientation.
Definition at line 437 of file rotationalEphemeris.h.
References targetFrameOrientation_.
template<> Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToBaseFrameTemplated (const double timeSinceEpoch)
Definition at line 43 of file rotationalEphemeris.cpp.
template<> Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToBaseFrameTemplated (const Time timeSinceEpoch)
Definition at line 51 of file rotationalEphemeris.cpp.
template<> Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrameTemplated (const double secondsSinceEpoch)
Definition at line 59 of file rotationalEphemeris.cpp.
template<> Eigen::Quaterniond tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrameTemplated (const Time secondsSinceEpoch)
Definition at line 67 of file rotationalEphemeris.cpp.
template<> Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToBaseFrameTemplated (const double timeSinceEpoch)
Definition at line 75 of file rotationalEphemeris.cpp.
template<> Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToBaseFrameTemplated (const Time timeSinceEpoch)
Definition at line 83 of file rotationalEphemeris.cpp.
template<> Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToTargetFrameTemplated (const double secondsSinceEpoch)
Definition at line 92 of file rotationalEphemeris.cpp.
template<> Eigen::Matrix3d tudat::ephemerides::RotationalEphemeris::getDerivativeOfRotationToTargetFrameTemplated (const Time secondsSinceEpoch)
Definition at line 100 of file rotationalEphemeris.cpp.
template<> void tudat::ephemerides::RotationalEphemeris::getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond & currentRotationToLocalFrame, Eigen::Matrix3d & currentRotationToLocalFrameDerivative, Eigen::Vector3d & currentAngularVelocityVectorInGlobalFrame, const double timeSinceEpoch)
Definition at line 108 of file rotationalEphemeris.cpp.
template<> void tudat::ephemerides::RotationalEphemeris::getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond & currentRotationToLocalFrame, Eigen::Matrix3d & currentRotationToLocalFrameDerivative, Eigen::Vector3d & currentAngularVelocityVectorInGlobalFrame, const Time timeSinceEpoch)
Definition at line 121 of file rotationalEphemeris.cpp.
Member Data Documentation
const std::string tudat::ephemerides::RotationalEphemeris::baseFrameOrientation_ protected
Base reference frame orientation.
Definition at line 445 of file rotationalEphemeris.h.
Referenced by getBaseFrameOrientation(), tudat::ephemerides::SpiceRotationalEphemeris::getDerivativeOfRotationToBaseFrame(), tudat::ephemerides::SpiceRotationalEphemeris::getFullRotationalQuantitiesToTargetFrame(), and tudat::ephemerides::SpiceRotationalEphemeris::getRotationToBaseFrame().
const std::string tudat::ephemerides::RotationalEphemeris::targetFrameOrientation_ protected
Target reference frame orientation.
Definition at line 451 of file rotationalEphemeris.h.
Referenced by tudat::ephemerides::SpiceRotationalEphemeris::getDerivativeOfRotationToBaseFrame(), tudat::ephemerides::SpiceRotationalEphemeris::getFullRotationalQuantitiesToTargetFrame(), tudat::ephemerides::SpiceRotationalEphemeris::getRotationToBaseFrame(), and getTargetFrameOrientation().
The documentation for this class was generated from the following files:
Astrodynamics/Ephemerides/rotationalEphemeris.h
Astrodynamics/Ephemerides/rotationalEphemeris.cpp