Tudat: tudat::reference_frames::AerodynamicAnglesClosure Class Reference
tudat::reference_frames::AerodynamicAnglesClosure Class Reference
Wrapper class to set closure between an imposed orientation of a body and its bank, sideslip and attack angles.
#include <aerodynamicAngleCalculator.h>
Public Member Functions
AerodynamicAnglesClosure (const std::function< Eigen::Quaterniond(const double) > imposedRotationFromInertialToBodyFixedFrame, const std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Constructor.
double getCurrentAngleOfAttack ()
Function returning the current angle of attack, as computed by last call to updateAngles function.
double getCurrentAngleOfSideslip ()
Function returning the current angle of sideslip, as computed by last call to updateAngles function.
double getCurrentBankAngle ()
Function returning the current bank angle, as computed by last call to updateAngles function.
void updateAngles (const double currentTime)
Function to update the aerodynamic angles to current time.
Private Attributes
std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator_
Object from which the aerodynamic angles are computed.
double currentAngleOfAttack_
Current angle of attack, as computed by last call to updateAngles function.
double currentAngleOfSideslip_
Current angle of sideslip, as computed by last call to updateAngles function.
double currentBankAngle_
Current bank angle, as computed by last call to updateAngles function.
Eigen::Matrix3d currentRotationFromBodyToTrajectoryFrame_
Current rotation matrix from body-fixed to trajectory, as computed by last call to updateAngles function.
std::function< Eigen::Quaterniond(const double) > imposedRotationFromInertialToBodyFixedFrame_
Inertial to body-fixed frame rotation to which the aerodynamicAngleCalculator_ object is to be made consistent.
Detailed Description
Wrapper class to set closure between an imposed orientation of a body and its bank, sideslip and attack angles. Based on a given rotation matrix function and AerodynamicAngleCalculator, this class computes the required values for the ank, sideslip and attack angles so that the output from AerodynamicAngleCalculator is consistent with the given rotation matrix.
Definition at line 374 of file aerodynamicAngleCalculator.h.
Constructor & Destructor Documentation
AerodynamicAnglesClosure()
tudat::reference_frames::AerodynamicAnglesClosure::AerodynamicAnglesClosure (const std::function< Eigen::Quaterniond(const double) > imposedRotationFromInertialToBodyFixedFrame, const std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator) inline
Constructor
Parameters
imposedRotationFromInertialToBodyFixedFrame Inertial to body-fixed frame rotation to which the aerodynamicAngleCalculator object is to be made consistent
aerodynamicAngleCalculator Object from which the aerodynamic angles are computed.
Definition at line 385 of file aerodynamicAngleCalculator.h.
Member Function Documentation
updateAngles()
void tudat::reference_frames::AerodynamicAnglesClosure::updateAngles (const double currentTime)
Function to update the aerodynamic angles to current time, using closure between imposedRotationFromInertialToBodyFixedFrame_ and aerodynamicAngleCalculator_.
Parameters
currentTime Time to which angles are to be updated.
Definition at line 482 of file aerodynamicAngleCalculator.cpp.
References aerodynamicAngleCalculator_, currentAngleOfAttack_, currentAngleOfSideslip_, currentBankAngle_, currentRotationFromBodyToTrajectoryFrame_, tudat::reference_frames::get132EulerAnglesFromRotationMatrix(), imposedRotationFromInertialToBodyFixedFrame_, tudat::reference_frames::inertial_frame, and tudat::reference_frames::trajectory_frame.
Referenced by tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure().
getCurrentAngleOfAttack()
double tudat::reference_frames::AerodynamicAnglesClosure::getCurrentAngleOfAttack () inline
Function returning the current angle of attack, as computed by last call to updateAngles function.
Returns
Current angle of attack, as computed by last call to updateAngles function.
Definition at line 405 of file aerodynamicAngleCalculator.h.
References currentAngleOfAttack_.
Referenced by tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure().
getCurrentAngleOfSideslip()
double tudat::reference_frames::AerodynamicAnglesClosure::getCurrentAngleOfSideslip () inline
Function returning the current angle of sideslip, as computed by last call to updateAngles function.
Returns
Current angle of sideslip, as computed by last call to updateAngles function.
Definition at line 415 of file aerodynamicAngleCalculator.h.
References currentAngleOfSideslip_.
Referenced by tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure().
getCurrentBankAngle()
double tudat::reference_frames::AerodynamicAnglesClosure::getCurrentBankAngle () inline
Function returning the current bank angle, as computed by last call to updateAngles function.
Returns
Current bank angle, as computed by last call to updateAngles function.
Definition at line 425 of file aerodynamicAngleCalculator.h.
References currentBankAngle_.
Referenced by tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure().
Member Data Documentation
imposedRotationFromInertialToBodyFixedFrame_
std::function< Eigen::Quaterniond(const double) > tudat::reference_frames::AerodynamicAnglesClosure::imposedRotationFromInertialToBodyFixedFrame_ private
Definition at line 433 of file aerodynamicAngleCalculator.h.
Referenced by updateAngles().
aerodynamicAngleCalculator_
std::shared_ptr< AerodynamicAngleCalculator > tudat::reference_frames::AerodynamicAnglesClosure::aerodynamicAngleCalculator_ private
Definition at line 436 of file aerodynamicAngleCalculator.h.
Referenced by updateAngles().
currentAngleOfAttack_
double tudat::reference_frames::AerodynamicAnglesClosure::currentAngleOfAttack_ private
Definition at line 439 of file aerodynamicAngleCalculator.h.
Referenced by getCurrentAngleOfAttack(), and updateAngles().
currentAngleOfSideslip_
double tudat::reference_frames::AerodynamicAnglesClosure::currentAngleOfSideslip_ private
Definition at line 442 of file aerodynamicAngleCalculator.h.
Referenced by getCurrentAngleOfSideslip(), and updateAngles().
currentBankAngle_
double tudat::reference_frames::AerodynamicAnglesClosure::currentBankAngle_ private
Definition at line 445 of file aerodynamicAngleCalculator.h.
Referenced by getCurrentBankAngle(), and updateAngles().
currentRotationFromBodyToTrajectoryFrame_
Eigen::Matrix3d tudat::reference_frames::AerodynamicAnglesClosure::currentRotationFromBodyToTrajectoryFrame_ private
Definition at line 448 of file aerodynamicAngleCalculator.h.
Referenced by updateAngles().
The documentation for this class was generated from the following files:
Astrodynamics/ReferenceFrames/aerodynamicAngleCalculator.h
Astrodynamics/ReferenceFrames/aerodynamicAngleCalculator.cpp