Tudat: tudat::ground_stations::PointingAnglesCalculator Class Reference
tudat::ground_stations::PointingAnglesCalculator Class Reference
Class to calculate the pointing angles (azimuth elevation) from a topocentric frame.
#include <pointingAnglesCalculator.h>
Public Member Functions
PointingAnglesCalculator (const boost::function< Eigen::Quaterniond(const double) > rotationFromInertialToBodyFixedFrame, const boost::function< Eigen::Quaterniond(const double) > rotationFromBodyFixedToTopoCentricFrame)
Constructor, takes functions defininf the sub-rotations from inertial to topocentric frame.
double calculateElevationAngle (const Eigen::Vector3d inertialVectorAwayFromStation, const double time)
Function to calculate the elevation angle from body-fixed point to given point.
std::pair< double, double > calculatePointingAngles (const Eigen::Vector3d inertialVectorAwayFromStation, const double time)
Function to calculate the elevation and azimuth angles from body-fixed point to given point.
double calculationAzimuthAngle (const Eigen::Vector3d inertialVectorAwayFromStation, const double time)
Function to calculate the azimuth angle from body-fixed point to given point.
Eigen::Vector3d convertVectorFromInertialToTopocentricFrame (const Eigen::Vector3d &inertialVector, const double time)
Function to convert vector in inertial frame to topocentric frame.
Private Attributes
const boost::function< Eigen::Quaterniond(const double) > rotationFromBodyFixedToTopoCentricFrame_
Function returning the rotation from the body-fixed to the topocentric frame.
const boost::function< Eigen::Quaterniond(const double) > rotationFromInertialToBodyFixedFrame_
Function returning the rotation from the inertial to the body-fixed frame at a specified time.
Detailed Description
Class to calculate the pointing (i.e. viewing) angles (azimuth elevation) from a topocentric frame. The rotations between an inertial and body-fixed and body-fixed and tropocentric are provided to the constructor. <ember functions can be used to calculate the pointing angles from the ground station to a vector in an inertial frame and a time.
Definition at line 36 of file pointingAnglesCalculator.h.
Constructor & Destructor Documentation
tudat::ground_stations::PointingAnglesCalculator::PointingAnglesCalculator (const boost::function< Eigen::Quaterniond(const double) > rotationFromInertialToBodyFixedFrame, const boost::function< Eigen::Quaterniond(const double) > rotationFromBodyFixedToTopoCentricFrame) inline
Constructor, takes functions defininf the sub-rotations from inertial to topocentric frame.
Parameters
rotationFromInertialToBodyFixedFrame Function returning the rotation from the inertial to the body-fixed frame at a specified time.
rotationFromBodyFixedToTopoCentricFrame Function returning the rotation from the body-fixed to the topocentric frame at a specified time (note that this rotation is typically time-independent).
Definition at line 48 of file pointingAnglesCalculator.h.
References calculateElevationAngle(), calculatePointingAngles(), calculationAzimuthAngle(), and convertVectorFromInertialToTopocentricFrame().
Member Function Documentation
double tudat::ground_stations::PointingAnglesCalculator::calculateElevationAngle (const Eigen::Vector3d inertialVectorAwayFromStation, const double time)
Function to calculate the elevation angle from body-fixed reference point (typically ground station) to given point. The elevation angle is calculatwed w.r.t. the shape of the body on which the reference point is located.
Parameters
inertialVectorAwayFromStation Vector from reference point to target point (i.e. to which elevation angle is to be calculated), expressed in inertial frame.
time Time at which elevation angle is to be calculated.
Returns
Elevation angle from reference point to input point (inertialVectorAwayFromStation)
Definition at line 21 of file pointingAnglesCalculator.cpp.
References tudat::linear_algebra::computeAngleBetweenVectors(), convertVectorFromInertialToTopocentricFrame(), and tudat::mathematical_constants::PI.
Referenced by PointingAnglesCalculator().
double tudat::ground_stations::PointingAnglesCalculator::calculationAzimuthAngle (const Eigen::Vector3d inertialVectorAwayFromStation, const double time)
Function to calculate the azimuth angle from body-fixed reference point (typically ground station) to given point. The azimuth angle is calculatwed w.r.t. the shape of the body on which the reference point is located.
Parameters
inertialVectorAwayFromStation Vector from reference point to target point (i.e. to which azimuth angle is to be calculated), expressed in inertial frame.
time Time at which azimuth angle is to be calculated.
Returns
Azimuth angle from reference point to input point (inertialVectorAwayFromStation)
Definition at line 35 of file pointingAnglesCalculator.cpp.
References convertVectorFromInertialToTopocentricFrame().
Referenced by PointingAnglesCalculator().
std::pair< double, double > tudat::ground_stations::PointingAnglesCalculator::calculatePointingAngles (const Eigen::Vector3d inertialVectorAwayFromStation, const double time)
Function to calculate the azimuth and elevationangle from body-fixed reference point to given point.
Parameters
inertialVectorAwayFromStation Vector from reference point to target point expressed in inertial frame.
time Time at which angles are to be calculated.
Returns
Elevation and azimuth angle (in that order) from reference point to input point (inertialVectorAwayFromStation)
Definition at line 47 of file pointingAnglesCalculator.cpp.
References tudat::linear_algebra::computeAngleBetweenVectors(), convertVectorFromInertialToTopocentricFrame(), and tudat::mathematical_constants::PI.
Referenced by PointingAnglesCalculator().
Eigen::Vector3d tudat::ground_stations::PointingAnglesCalculator::convertVectorFromInertialToTopocentricFrame (const Eigen::Vector3d & inertialVector, const double time)
Function to convert vector in inertial frame to topocentric frame, with unit vectors in ENU (Earth-North-Up) order.
Parameters
inertialVector Vector in inertial frame that is to be transformed to topocentric frame.
time Time at which rotation is to be calculated.
Returns
Vector expressed in topocentric frame.
Definition at line 66 of file pointingAnglesCalculator.cpp.
References rotationFromBodyFixedToTopoCentricFrame_, and rotationFromInertialToBodyFixedFrame_.
Referenced by calculateElevationAngle(), calculatePointingAngles(), calculationAzimuthAngle(), and PointingAnglesCalculator().
Member Data Documentation
const boost::function< Eigen::Quaterniond(const double) > tudat::ground_stations::PointingAnglesCalculator::rotationFromInertialToBodyFixedFrame_ private
Definition at line 97 of file pointingAnglesCalculator.h.
Referenced by convertVectorFromInertialToTopocentricFrame().
const boost::function< Eigen::Quaterniond(const double) > tudat::ground_stations::PointingAnglesCalculator::rotationFromBodyFixedToTopoCentricFrame_ private
Function returning the rotation from the body-fixed to the topocentric frame at a specified time (note that this rotation is typically time-independent).
Definition at line 104 of file pointingAnglesCalculator.h.
Referenced by convertVectorFromInertialToTopocentricFrame().
The documentation for this class was generated from the following files:
Astrodynamics/GroundStations/pointingAnglesCalculator.h
Astrodynamics/GroundStations/pointingAnglesCalculator.cpp