Tudat: tudat::propulsion::ThrustAcceleration Class Reference
tudat::propulsion::ThrustAcceleration Class Reference
Class used for computing an acceleration due to a continuous thrust.
#include <thrustAccelerationModel.h>
Public Member Functions
ThrustAcceleration (const boost::function< double() > thrustMagnitudeFunction, const boost::function< Eigen::Vector3d() > thrustDirectionFunction, const boost::function< double() > bodyMassFunction, const boost::function< double() > massRateFunction, const std::string associatedThrustSource="", const boost::function< void(const double) > thrustUpdateFunction=boost::function< void(const double) >(), const boost::function< void(const double) > timeResetFunction=boost::function< void(const double) >(), const std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > &requiredModelUpdates=std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > >())
Constructor.
~ThrustAcceleration ()
Destructor.
Eigen::Vector3d getAcceleration ()
Function to retrieve the current acceleration, as set by last call to updateMembers function.
std::string getAssociatedThrustSource ()
Function to retreieve the ID associated with the source of the thrust (i.e. engine name).
double getCurrentMassRate ()
Function to retreieve the current propellant mass rate, as computed by last call to updateMembers function.
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > getRequiredModelUpdates ()
Function to retreieve the list of environment models that are to be updated before computing the acceleration.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
void setThrustUpdateFunction (const boost::function< void(const double) > thrustUpdateFunction)
Function to set or add a thrust update function.
void updateMembers (const double currentTime=TUDAT_NAN)
Update member variables used by the thrust acceleration model.
Public Member Functions inherited from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >
AccelerationModel ()
Constructor.
virtual ~AccelerationModel ()
Virtual destructor.
Protected Attributes
std::string associatedThrustSource_
ID associated with the source of the thrust (i.e. engine name).
boost::function< double() > bodyMassFunction_
Function returning the current mass of the body being propagated.
Eigen::Vector3d currentAcceleration_
Current acceleration, as computed by last call to updateMembers function.
Eigen::Vector3d currentAccelerationDirection_
Current acceleration direction, as computed by last call to updateMembers function.
double currentMassRate_
Current propellant mass rate, as computed by last call to updateMembers function.
double currentThrustMagnitude_
Current thrust magnitude, as computed by last call to updateMembers function.
boost::function< double() > massRateFunction_
Function returning total propellant mass rate from the thrust system.
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > requiredModelUpdates_
List of environment models that are to be updated before computing the acceleration,.
boost::function< Eigen::Vector3d() > thrustDirectionFunction_
Function returning the direction of the thrust (as a unit vector).
boost::function< double() > thrustMagnitudeFunction_
Function returning the current magnitude of the thrust.
boost::function< void(const double) > thrustUpdateFunction_
Function used to update the thrust magnitude and direction to current time.
const boost::function< void(const double) > timeResetFunction_
Function to reset the time in the classes to which the thrustUpdateFunction function directs.
Protected Attributes inherited from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >
double currentTime_
Previous time to which acceleration model was updated.
Detailed Description
Class used for computing an acceleration due to a continuous thrust. The thrust magnitude and direction (in the propagation frame) are retrieved from separate functions provided by tye user.
Definition at line 52 of file thrustAccelerationModel.h.
Constructor & Destructor Documentation
tudat::propulsion::ThrustAcceleration::ThrustAcceleration (const boost::function< double() > thrustMagnitudeFunction, const boost::function< Eigen::Vector3d() > thrustDirectionFunction, const boost::function< double() > bodyMassFunction, const boost::function< double() > massRateFunction, const std::string associatedThrustSource = "", const boost::function< void(const double) > thrustUpdateFunction = boost::function< void(const double) >(), const boost::function< void(const double) > timeResetFunction = boost::function< void(const double) >(), const std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > & requiredModelUpdates = std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > >()) inline
Parameters
thrustMagnitudeFunction Function returning the current magnitude of the thrust. Any dependencies of the thrust on (in)dependent variables is to be handled by the thrustUpdateFunction.
thrustDirectionFunction Function returning the direction of the thrust (as a unit vector). Any dependencies of the thrust on (in)dependent variables is to be handled by the thrustUpdateFunction.
bodyMassFunction Function returning the current mass of the body being propagated.
massRateFunction Function returning total propellant mass rate from the thrust system.
associatedThrustSource ID associated with the source of the thrust (i.e. engine name).
thrustUpdateFunction Function used to update the thrust magnitude and direction to current time (default empty)
timeResetFunction Function to reset the time in the classes to which the thrustUpdateFunction function directs, default empty.
requiredModelUpdates List of environment models that are to be updated before computing the acceleration, list is included here to account for versatility of dependencies of thrust model (guidance) algorithms. Default empty.
Definition at line 71 of file thrustAccelerationModel.h.
tudat::propulsion::ThrustAcceleration::~ThrustAcceleration () inline
Definition at line 92 of file thrustAccelerationModel.h.
Member Function Documentation
Eigen::Vector3d tudat::propulsion::ThrustAcceleration::getAcceleration () inline virtual
Function to retrieve the current acceleration, as set by last call to updateMembers function.
Returns
Current thrust acceleration.
Implements tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 99 of file thrustAccelerationModel.h.
References currentAcceleration_.
virtual void tudat::propulsion::ThrustAcceleration::resetTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the current time of the acceleration model.
Parameters
currentTime Current time (default NaN).
Reimplemented from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 109 of file thrustAccelerationModel.h.
References tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >::currentTime_, and timeResetFunction_.
void tudat::propulsion::ThrustAcceleration::updateMembers (const double currentTime = TUDAT_NAN) inline virtual
Updates member variables used by the thrust acceleration model. Function pointers to retrieve the current values of quantities from which the acceleration is to be calculated are set by constructor. This function calls and combines their output to compute the acceleration.
Parameters
currentTime Time at which acceleration model is to be updated.
Implements tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 127 of file thrustAccelerationModel.h.
References bodyMassFunction_, currentAcceleration_, currentAccelerationDirection_, currentMassRate_, currentThrustMagnitude_, tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >::currentTime_, massRateFunction_, thrustDirectionFunction_, thrustMagnitudeFunction_, and thrustUpdateFunction_.
double tudat::propulsion::ThrustAcceleration::getCurrentMassRate () inline
Function to retreieve the current propellant mass rate, as computed by last call to updateMembers function.
Returns
ICurrent propellant mass rate, as computed by last call to updateMembers function.
Definition at line 166 of file thrustAccelerationModel.h.
References currentMassRate_.
std::string tudat::propulsion::ThrustAcceleration::getAssociatedThrustSource () inline
Function to retreieve the ID associated with the source of the thrust (i.e. engine name).
Returns
ID associated with the source of the thrust (i.e. engine name).
Definition at line 176 of file thrustAccelerationModel.h.
References associatedThrustSource_.
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propulsion::ThrustAcceleration::getRequiredModelUpdates () inline
Function to retreieve the list of environment models that are to be updated before computing the acceleration.
Returns
List of environment models that are to be updated before computing the acceleration.
Definition at line 186 of file thrustAccelerationModel.h.
References requiredModelUpdates_.
void tudat::propulsion::ThrustAcceleration::setThrustUpdateFunction (const boost::function< void(const double) > thrustUpdateFunction) inline
Function to set or add a thrust update function
Parameters
thrustUpdateFunction Update function that is to be added to class
Definition at line 196 of file thrustAccelerationModel.h.
References tudat::propulsion::mergeUpdateFunctions(), and thrustUpdateFunction_.
Member Data Documentation
boost::function< double() > tudat::propulsion::ThrustAcceleration::thrustMagnitudeFunction_ protected
Function returning the current magnitude of the thrust. Any dependencies of the thrust on (in)dependent variables is to be handled by the thrustUpdateFunction.
Definition at line 216 of file thrustAccelerationModel.h.
Referenced by updateMembers().
boost::function< Eigen::Vector3d() > tudat::propulsion::ThrustAcceleration::thrustDirectionFunction_ protected
Function returning the direction of the thrust (as a unit vector). Any dependencies of the thrust on (in)dependent variables is to be handled by the thrustUpdateFunction.
Definition at line 223 of file thrustAccelerationModel.h.
Referenced by updateMembers().
boost::function< double() > tudat::propulsion::ThrustAcceleration::bodyMassFunction_ protected
Definition at line 226 of file thrustAccelerationModel.h.
Referenced by updateMembers().
boost::function< double() > tudat::propulsion::ThrustAcceleration::massRateFunction_ protected
Definition at line 229 of file thrustAccelerationModel.h.
Referenced by updateMembers().
std::string tudat::propulsion::ThrustAcceleration::associatedThrustSource_ protected
Definition at line 232 of file thrustAccelerationModel.h.
Referenced by getAssociatedThrustSource().
boost::function< void(const double) > tudat::propulsion::ThrustAcceleration::thrustUpdateFunction_ protected
Definition at line 235 of file thrustAccelerationModel.h.
Referenced by setThrustUpdateFunction(), and updateMembers().
Eigen::Vector3d tudat::propulsion::ThrustAcceleration::currentAcceleration_ protected
Definition at line 238 of file thrustAccelerationModel.h.
Referenced by getAcceleration(), and updateMembers().
Eigen::Vector3d tudat::propulsion::ThrustAcceleration::currentAccelerationDirection_ protected
Definition at line 241 of file thrustAccelerationModel.h.
Referenced by updateMembers().
double tudat::propulsion::ThrustAcceleration::currentThrustMagnitude_ protected
Definition at line 244 of file thrustAccelerationModel.h.
Referenced by updateMembers().
double tudat::propulsion::ThrustAcceleration::currentMassRate_ protected
Definition at line 247 of file thrustAccelerationModel.h.
Referenced by getCurrentMassRate(), and updateMembers().
const boost::function< void(const double) > tudat::propulsion::ThrustAcceleration::timeResetFunction_ protected
Definition at line 250 of file thrustAccelerationModel.h.
Referenced by resetTime().
std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > tudat::propulsion::ThrustAcceleration::requiredModelUpdates_ protected
List of environment models that are to be updated before computing the acceleration, list is included here to account for versatility of dependencies of thrust model (guidance) algorithms.
Definition at line 257 of file thrustAccelerationModel.h.
Referenced by getRequiredModelUpdates().
The documentation for this class was generated from the following file:
Astrodynamics/Propulsion/thrustAccelerationModel.h