Tudat: tudat::input_output::TextParser Class Reference
tudat::input_output::TextParser Class Reference
A TextParser is a Parser that specialized in parsing text files.
#include <textParser.h>
Public Member Functions
TextParser ()
Create the default TextParser with processAsStream == false.
TextParser (bool processAsStream)
Create the TextParser in the given process mode.
virtual ~TextParser ()
Default destructor, no new objects besides smart ones.
parsed_data_vector_utilities::ParsedDataVectorPtr parse (std::string &string)
Implementation of parse for strings.
parsed_data_vector_utilities::ParsedDataVectorPtr parse (std::istream &stream)
Implementation of parse for an istream.
Public Member Functions inherited from tudat::input_output::Parser
Parser ()
Default constructor, interface therefore empty.
virtual ~Parser ()
Default destructor, interface therefore empty.
Protected Member Functions
virtual void parseLine (std::string &line)
Parse the given line content and append the resulting data lines to parsedData.
virtual void parseStream (std::istream &stream)
Parse the given stream content and append the resulting data lines to parsedData.
Protected Attributes
bool parseAsStream
Flag to identify either stream parsing or line based parsing.
parsed_data_vector_utilities::ParsedDataVectorPtr parsedData
Data container of the parsed data.
Detailed Description
A TextParser provides a set of functions to streamline parsing to simplify the parsing process. The inheriting parsers can chose there prefered way of processing by calling TextParser(bool).
NOTE: This TextParser works with the FieldValue/FieldType architecture. For simpler file reading, use, for instance, matrixTextFileReader.
Definition at line 35 of file textParser.h.
Constructor & Destructor Documentation
tudat::input_output::TextParser::TextParser () inline
The default constructor for TextParser causes the parser to behave as a line based parser.
Definition at line 43 of file textParser.h.
tudat::input_output::TextParser::TextParser (bool processAsStream) inline
Create a Textparser that deligates parsing either as stream or on a line-by-line basis.
Parameters
processAsStream Boolean that determines whether the parsing should be done as a stream (string is default).
Definition at line 54 of file textParser.h.
virtual tudat::input_output::TextParser::~TextParser () inline virtual
Definition at line 60 of file textParser.h.
References parse().
Member Function Documentation
ParsedDataVectorPtr tudat::input_output::TextParser::parse (std::string & string) virtual
Parameters
string String that is to be parsed.
Returns
Parsed line data, stored in a ParsedDataVectorPtr object.
See also
Parser::parse(std::string& string).
Implements tudat::input_output::Parser.
Definition at line 23 of file textParser.cpp.
Referenced by tudat::input_output::solar_activity::ParseSolarActivityData::parseStream(), tudat::input_output::solar_activity::readSolarActivityData(), and ~TextParser().
ParsedDataVectorPtr tudat::input_output::TextParser::parse (std::istream & stream) virtual
Parameters
stream Stream that is to be parsed.
Returns
Parsed line data, stored in a ParsedDataVectorPtr object.
See also
Parser::parse(std::istream& stream).
Implements tudat::input_output::Parser.
Definition at line 33 of file textParser.cpp.
virtual void tudat::input_output::TextParser::parseLine (std::string & line) inline protected virtual
Parse all lines/fields from the passed string and store (append) them to parsedData.
Needs to be overwritten if parseAsStream==false otherwise an exception will be thrown!
Parameters
line String to parse
Reimplemented in tudat::input_output::SeparatedParser, and tudat::input_output::FixedWidthParser.
Definition at line 102 of file textParser.h.
virtual void tudat::input_output::TextParser::parseStream (std::istream & stream) inline protected virtual
Parse all lines/fields from the passed stream and store (append) them to parsedData.
Needs to be overwritten if parseAsStream==true otherwise an exception will be thrown!
Parameters
stream Stream to parse
Reimplemented in tudat::input_output::solar_activity::ParseSolarActivityData.
Definition at line 115 of file textParser.h.
Member Data Documentation
parsed_data_vector_utilities::ParsedDataVectorPtr tudat::input_output::TextParser::parsedData protected
Cleared and refilled on every call to parse(string) or parse(stream).
Definition at line 84 of file textParser.h.
Referenced by tudat::input_output::FixedWidthParser::parseLine(), tudat::input_output::SeparatedParser::parseLine(), and tudat::input_output::solar_activity::ParseSolarActivityData::parseStream().
bool tudat::input_output::TextParser::parseAsStream protected
Clients doing stream based parsing must override parseStream! Clients doing line based parsing must override parseLine! Clients doing both parsing techniques must override parseLine and parseStream.
Definition at line 92 of file textParser.h.
The documentation for this class was generated from the following files:
InputOutput/textParser.h
InputOutput/textParser.cpp