Tudat: tudat::json_interface::KeyPath Class Reference
tudat::json_interface::KeyPath Class Reference
Class for specifying a key pat used to access data from json objects.
#include <keys.h>
Public Member Functions
KeyPath ()
Empty constructor.
KeyPath (const std::vector< std::string > &vector)
Constructor from vector.
KeyPath (const std::string &keyPathStringRepresentation)
Constructor with a single key path string representation.
KeyPath (const char *key)
Constructor with a single char key.
KeyPath (unsigned int vectorIndex)
Constructor with an element index.
KeyPath canonical (const KeyPath &basePath) const
Get the canonical representation of the key path.
bool isAbsolute () const
Get whether the key path is absolute.
Detailed Description
Class for specifying a key path (key.subkey.subsubkey ...) used to access data from json objects.
Definition at line 445 of file keys.h.
Constructor & Destructor Documentation
KeyPath() [1/5]
tudat::json_interface::KeyPath::KeyPath () inline
Definition at line 449 of file keys.h.
KeyPath() [2/5]
tudat::json_interface::KeyPath::KeyPath (const std::vector< std::string > & vector) inline
Definition at line 452 of file keys.h.
KeyPath() [3/5]
tudat::json_interface::KeyPath::KeyPath (const std::string & keyPathStringRepresentation)
Constructor with a single key path string representation.
Parameters
keyPathStringRepresentation The key path string representation, such as "key", "key.subkey", "key[1]".
Definition at line 418 of file keys.cpp.
References tudat::json_interface::SpecialKeys::dot, and tudat::json_interface::split().
KeyPath() [4/5]
tudat::json_interface::KeyPath::KeyPath (const char * key) inline
Constructor with a single char key.
Parameters
key The key to be accessed.
Definition at line 472 of file keys.h.
KeyPath() [5/5]
tudat::json_interface::KeyPath::KeyPath (unsigned int vectorIndex) inline
Constructor with an element index.
Parameters
vectorIndex The index of the element to be accessed.
Definition at line 479 of file keys.h.
Member Function Documentation
isAbsolute()
bool tudat::json_interface::KeyPath::isAbsolute () const inline
Get whether the key path is absolute. Absolute key paths begin with SpecialKeys::root.
Returns
Whether the key path is absolute.
Definition at line 486 of file keys.h.
References tudat::json_interface::SpecialKeys::root.
Referenced by canonical(), and tudat::json_interface::getValue().
canonical()
KeyPath tudat::json_interface::KeyPath::canonical (const KeyPath & basePath) const
Get the canonical representation of the key path, optionally relative to basePath. This method is used to construct absolute paths, also navigating up and removing SpecialKeys::up.
Parameters
basePath Key path with respect to which the path is to be constructed.
Returns
Canonical representation of the key path.
Definition at line 468 of file keys.cpp.
References isAbsolute(), and tudat::json_interface::SpecialKeys::up.
Referenced by tudat::json_interface::getValue().
The documentation for this class was generated from the following files:
JsonInterface/Support/keys.h
JsonInterface/Support/keys.cpp