Tudat: tudat::transfer_trajectories::DepartureLegMga Class Reference
tudat::transfer_trajectories::DepartureLegMga Class Reference
Departure Leg class of an MGA trajectory model.
#include <departureLegMga.h>
Public Member Functions
DepartureLegMga (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, const double departureBodyGravitationalParameter, const double semiMajorAxis, const double eccentricity, const bool includeDepartureDeltaV=true)
Constructor with immediate definition of parameters.
void calculateLeg (Eigen::Vector3d &velocityBeforeArrivalBody, double &deltaV)
Calculate the leg.
void intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, const double startingTime=0.0)
Calculate intermediate positions and their corresponding times.
void maneuvers (std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, std::vector< double > &deltaVVector, const double startingTime=0.)
Return maneuvres along the leg.
void updateDefiningVariables (const Eigen::VectorXd &variableVector)
Update the defining variables.
Public Member Functions inherited from tudat::transfer_trajectories::DepartureLeg
DepartureLeg (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, const double departureBodyGravitationalParameter, const double semiMajorAxis, const double eccentricity, const bool includeDepartureDeltaV=true)
Constructor with immediate definition of parameters.
void getEscapeDeltaV (double &escapeDeltaV)
Function to retrieve the value of the escape Delta V.
Public Member Functions inherited from tudat::transfer_trajectories::SpaceLeg
SpaceLeg (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~SpaceLeg ()
void updateEphemeris (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const Eigen::Vector3d &departureBodyVelocity)
Update the ephemeris.
Public Member Functions inherited from tudat::transfer_trajectories::MissionLeg
MissionLeg (const Eigen::Vector3d &departureBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~MissionLeg ()
virtual destructor.
void returnDepartureVariables (Eigen::Vector3d &departureBodyPosition, Eigen::Vector3d &departureBodyVelocity, Eigen::Vector3d &velocityAfterDeparture)
Return Departure Variables.
Additional Inherited Members
Protected Attributes inherited from tudat::transfer_trajectories::DepartureLeg
double departureBodyGravitationalParameter_
The departure body gravitational parameter.
double eccentricity_
The eccentricity of the departure orbit.
double escapeDeltaV_
Double denoting the value of the escape Delta V.
bool includeDepartureDeltaV_
Boolean denoting whether to include the Delta V of arrival.
double semiMajorAxis_
The semi-major axis of the departure orbit.
Protected Attributes inherited from tudat::transfer_trajectories::SpaceLeg
Eigen::Vector3d arrivalBodyPosition_
The arrival body position.
Protected Attributes inherited from tudat::transfer_trajectories::MissionLeg
double centralBodyGravitationalParameter_
The central body gravitational parameter.
double deltaV_
The total deltaV of the leg.
Eigen::Vector3d departureBodyPosition_
The departure body position.
Eigen::Vector3d departureBodyVelocity_
The departure body velocity.
double timeOfFlight_
The time of flight.
Eigen::Vector3d velocityAfterDeparture_
The velocity after departure.
Detailed Description
A class that calculates the required impulses for a departure leg for an MGA high-thrust, patched-conics trajectory model. It extends the departure leg base class and uses a lambert targeter for finding the required departure and arrival velocities of the spacecraft.
Definition at line 39 of file departureLegMga.h.
Constructor & Destructor Documentation
DepartureLegMga()
tudat::transfer_trajectories::DepartureLegMga::DepartureLegMga (const Eigen::Vector3d & departureBodyPosition, const Eigen::Vector3d & arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d & departureBodyVelocity, const double centralBodyGravitationalParameter, const double departureBodyGravitationalParameter, const double semiMajorAxis, const double eccentricity, const bool includeDepartureDeltaV = true) inline
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
Parameters
departureBodyPosition location of the departure body.
arrivalBodyPosition position of the target body.
timeOfFlight Length of the leg.
departureBodyVelocity velocity of the departure body.
centralBodyGravitationalParameter gravitational parameter of the cebtral body (most cases the Sun).
departureBodyGravitationalParameter gravitational parameter of the departure body.
semiMajorAxis semi-major axis of the orbit after the capture is performed.
eccentricity eccentricity of the orbit after the capture is performed.
includeDepartureDeltaV Boolean denoting whether to include the Delta V of departure.
Definition at line 57 of file departureLegMga.h.
References TUDAT_NAN, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
Member Function Documentation
calculateLeg()
void tudat::transfer_trajectories::DepartureLegMga::calculateLeg (Eigen::Vector3d & velocityBeforeArrivalBody, double & deltaV) virtual
Calculate the leg and update the Delta V and the velocity before the next body.
Performs all calculations required for this leg.
Parameters
velocityBeforeArrivalBody the velocity of the spacecraft before it arrives at the target body.
deltaV the delta V required to perform the leg.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 16 of file departureLegMga.cpp.
References tudat::transfer_trajectories::SpaceLeg::arrivalBodyPosition_, tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::mission_segments::computeEscapeOrCaptureDeltaV(), tudat::transfer_trajectories::MissionLeg::deltaV_, tudat::transfer_trajectories::DepartureLeg::departureBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, tudat::transfer_trajectories::MissionLeg::departureBodyVelocity_, tudat::transfer_trajectories::DepartureLeg::eccentricity_, tudat::transfer_trajectories::DepartureLeg::escapeDeltaV_, tudat::transfer_trajectories::DepartureLeg::includeDepartureDeltaV_, tudat::transfer_trajectories::DepartureLeg::semiMajorAxis_, tudat::mission_segments::solveLambertProblemIzzo(), tudat::transfer_trajectories::MissionLeg::timeOfFlight_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
Referenced by intermediatePoints(), and maneuvers().
intermediatePoints()
void tudat::transfer_trajectories::DepartureLegMga::intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, const double startingTime = 0.0) virtual
Calculates intermediate positions and their corresponding times in the leg, based on a maximum time between two points.
Parameters
maximumTimeStep the maximum time between two points along the trajectory.
positionVector Vector of positions along the orbit, space according to the maximum time step.
timeVector The times corresponding to the positions.
startingTime the initial time from which the intermediate points are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 43 of file departureLegMga.cpp.
References calculateLeg(), tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, tudat::transfer_trajectories::returnTrajectory(), tudat::transfer_trajectories::MissionLeg::timeOfFlight_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
maneuvers()
void tudat::transfer_trajectories::DepartureLegMga::maneuvers (std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, std::vector< double > & deltaVVector, const double startingTime = 0.) virtual
Returns the maneuver points, times and sizes along the trajectory.
Parameters
positionVector Vector of the positions of the maneuvers.
timeVector The times corresponding to the positions.
deltaVVector the delta V required for each maneuver.
startingTime the initial time from which the maneuvers are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 69 of file departureLegMga.cpp.
References calculateLeg(), tudat::transfer_trajectories::MissionLeg::deltaV_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
updateDefiningVariables()
void tudat::transfer_trajectories::DepartureLegMga::updateDefiningVariables (const Eigen::VectorXd & variableVector) virtual
Sets the trajectory defining variables to the newly specified values. Required for re-using the class, without re-initializing it. For this leg: time of flight.
Parameters
variableVector the new variable vector.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 96 of file departureLegMga.cpp.
References tudat::transfer_trajectories::MissionLeg::timeOfFlight_.
The documentation for this class was generated from the following files:
Astrodynamics/TrajectoryDesign/departureLegMga.h
Astrodynamics/TrajectoryDesign/departureLegMga.cpp