Tudat: tudat::propulsion::BodyFixedForceDirectionGuidance Class Reference
tudat::propulsion::BodyFixedForceDirectionGuidance Class Reference abstract
Base class for computing the direction of a given force/acceleration.
#include <thrustGuidance.h>
Public Member Functions
BodyFixedForceDirectionGuidance (const boost::function< Eigen::Vector3d() > bodyFixedForceDirection)
Constructor.
virtual ~BodyFixedForceDirectionGuidance ()
Destructor.
virtual Eigen::Vector3d getCurrentForceDirectionInPropagationFrame ()=0
Function to get the force/acceleration direction in the propagation frame.
Eigen::Quaterniond getRotationToLocalFrame ()
Function to compute the rotation from the propagation frame to the body-fixed frame.
void updateCalculator (const double time)
Function to update the object to the current time.
Public Member Functions inherited from tudat::reference_frames::DependentOrientationCalculator
DependentOrientationCalculator ()
Constructor.
virtual ~DependentOrientationCalculator ()
Destructor.
virtual Eigen::Quaterniond getRotationToGlobalFrame ()=0
Function to get the current rotation from the local (body-fixed) to the global (propagation/inertial) frame.
Eigen::Quaterniond getRotationToGlobalFrame (const double currentTime)
Function to update the object to teh current time and retrieve the rotation to the global frame.
Eigen::Quaterniond getRotationToLocalFrame (const double currentTime)
Function to update the object to teh current time and retrieve the rotation to the local frame.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the object.
virtual void resetDerivedClassTime (const double currentTime=TUDAT_NAN)
Function to reset the current time in the derived class.
Protected Member Functions
virtual void updateForceDirection (const double time)=0
Function to update the force/acceleration direction to the current time.
Protected Attributes
boost::function< Eigen::Vector3d() > bodyFixedForceDirection_
Function returning the direction of the force in the body-fixed frame.
Eigen::Vector3d currentBodyFixedForceDirection_
Current direction of the force in the body-fixed frame as set by last call to updateCalculator function.
Protected Attributes inherited from tudat::reference_frames::DependentOrientationCalculator
double currentTime_
Current simulation time.
Detailed Description
Base class for computing the direction of a given force/acceleration. The computation is done directly from some a priori imposed rule, possibly as a function of dependent, independent or state variables. A derived class for using the current orientation of the vehicle (as computed by some other method and retrieved from the body class) may be set using the OrientationBasedForceGuidance class.
Definition at line 36 of file thrustGuidance.h.
Constructor & Destructor Documentation
tudat::propulsion::BodyFixedForceDirectionGuidance::BodyFixedForceDirectionGuidance (const boost::function< Eigen::Vector3d() > bodyFixedForceDirection) inline
Constructor, sets the direction of the force in the body-fixed frame.
Parameters
bodyFixedForceDirection Function returning the direction of the force in the body-fixed frame.
Definition at line 45 of file thrustGuidance.h.
virtual tudat::propulsion::BodyFixedForceDirectionGuidance::~BodyFixedForceDirectionGuidance () inline virtual
Definition at line 50 of file thrustGuidance.h.
References getCurrentForceDirectionInPropagationFrame().
Member Function Documentation
virtual Eigen::Vector3d tudat::propulsion::BodyFixedForceDirectionGuidance::getCurrentForceDirectionInPropagationFrame () pure virtual
Function to get the force/acceleration direction in the propagation frame. Function is pure virtual and to be implemented in derived class.
Returns
Direction of force (as unit vector) expressed in propagation frame.
Implemented in tudat::propulsion::OrientationBasedForceGuidance, and tudat::propulsion::DirectionBasedForceGuidance.
Referenced by tudat::simulation_setup::createThrustAcceleratioModel(), and ~BodyFixedForceDirectionGuidance().
Eigen::Quaterniond tudat::propulsion::BodyFixedForceDirectionGuidance::getRotationToLocalFrame () inline virtual
Function to compute the rotation from the propagation frame to the body-fixed frame using the algorithm implemented in the derived class. The derived class must implement the function for the inverse rotation (getRotationToGlobalFrame).
Returns
Quaternion that provides the rotation from the propagation frame to the body-fixed frame.
Implements tudat::reference_frames::DependentOrientationCalculator.
Definition at line 67 of file thrustGuidance.h.
References tudat::reference_frames::DependentOrientationCalculator::getRotationToGlobalFrame().
void tudat::propulsion::BodyFixedForceDirectionGuidance::updateCalculator (const double time) inline virtual
Function to update the object to the current time. This function updates only this base class, derived class must implement the updateForceDirection function that obdates the full object.
Parameters
time Time to which object is to be updated.
Implements tudat::reference_frames::DependentOrientationCalculator.
Definition at line 78 of file thrustGuidance.h.
References bodyFixedForceDirection_, currentBodyFixedForceDirection_, and updateForceDirection().
virtual void tudat::propulsion::BodyFixedForceDirectionGuidance::updateForceDirection (const double time) protected pure virtual
Function to update the force/acceleration direction to the current time. This function is to be implemented in the derived class.
Parameters
time Time to which object is to be updated.
Implemented in tudat::propulsion::OrientationBasedForceGuidance, and tudat::propulsion::DirectionBasedForceGuidance.
Referenced by updateCalculator().
Member Data Documentation
boost::function< Eigen::Vector3d() > tudat::propulsion::BodyFixedForceDirectionGuidance::bodyFixedForceDirection_ protected
Definition at line 95 of file thrustGuidance.h.
Referenced by updateCalculator().
Eigen::Vector3d tudat::propulsion::BodyFixedForceDirectionGuidance::currentBodyFixedForceDirection_ protected
Definition at line 98 of file thrustGuidance.h.
Referenced by tudat::propulsion::OrientationBasedForceGuidance::getCurrentForceDirectionInPropagationFrame(), and updateCalculator().
The documentation for this class was generated from the following file:
Astrodynamics/Propulsion/thrustGuidance.h