Tudat: tudat::input_output::field_types::general Namespace Reference
tudat::input_output::field_types::general Namespace Reference
Variables
static const FieldType id = hash_constructor("General: Object_id")
Object identification code [-].
static const FieldType name = hash_constructor("General: Object_name")
Object name [-].
static const FieldType parameterName = hash_constructor("General: Parameter_name")
Parameter name [-].
static const FieldType parameterValue = hash_constructor("General: Parameter_value")
Parameter value [-].
Variable Documentation
name
const FieldType tudat::input_output::field_types::general::name = hash_constructor("General: Object_name") static
Definition at line 65 of file fieldType.h.
Referenced by tudat::geometric_shapes::LawgsPartGeometry::setName().
id
const FieldType tudat::input_output::field_types::general::id = hash_constructor("General: Object_id") static
Definition at line 68 of file fieldType.h.
Referenced by tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getConcatenatedDeformingBodies().
parameterName
const FieldType tudat::input_output::field_types::general::parameterName = hash_constructor("General: Parameter_name") static
Definition at line 71 of file fieldType.h.
Referenced by tudat::input_output::dictionary::addEntry(), tudat::input_output::dictionary::findEntry(), and tudat::input_output::dictionary::DictionaryComparer::operator()().
parameterValue
const FieldType tudat::input_output::field_types::general::parameterValue = hash_constructor("General: Parameter_value") static
Definition at line 74 of file fieldType.h.
Referenced by tudat::input_output::dictionary::extractParameterValue(), tudat::estimatable_parameters::EquivalencePrincipleLpiViolationParameter::setParameterValue(), tudat::estimatable_parameters::PPNParameterGamma::setParameterValue(), tudat::estimatable_parameters::GravitationalParameter::setParameterValue(), tudat::estimatable_parameters::InitialTranslationalStateParameter< InitialStateParameterType >::setParameterValue(), tudat::estimatable_parameters::RotationRate::setParameterValue(), tudat::estimatable_parameters::ConstantRotationalOrientation::setParameterValue(), tudat::estimatable_parameters::ConstantDragCoefficient::setParameterValue(), tudat::estimatable_parameters::RadiationPressureCoefficient::setParameterValue(), tudat::estimatable_parameters::GroundStationPosition::setParameterValue(), tudat::estimatable_parameters::DirectTidalTimeLag::setParameterValue(), tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::setParameterValue(), tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::setParameterValue(), tudat::estimatable_parameters::ConstantObservationBiasParameter::setParameterValue(), tudat::estimatable_parameters::PPNParameterBeta::setParameterValue(), tudat::estimatable_parameters::EmpiricalAccelerationCoefficientsParameter::setParameterValue(), tudat::estimatable_parameters::ArcWiseRadiationPressureCoefficient::setParameterValue(), tudat::estimatable_parameters::ArcWiseInitialTranslationalStateParameter< InitialStateParameterType >::setParameterValue(), tudat::estimatable_parameters::FullDegreeTidalLoveNumber::setParameterValue(), tudat::estimatable_parameters::ArcWiseObservationBiasParameter::setParameterValue(), tudat::estimatable_parameters::SingleDegreeVariableTidalLoveNumber::setParameterValue(), and tudat::estimatable_parameters::ArcWiseEmpiricalAccelerationCoefficientsParameter::setParameterValue().