Tudat: tudat::input_output::MultiArrayFileReader< NumberOfDimensions > Class Template Reference
tudat::input_output::MultiArrayFileReader< NumberOfDimensions > Class Template Reference
Interface class for reading coefficients as a function of N independent variables from a file.
#include <multiDimensionalArrayReader.h>
Static Public Member Functions
static boost::multi_array< double, static_cast< size_t > NumberOfDimensions) > readMultiArray (const std::string fileName)
Function to read only a multi-array from the file.
static std::pair< boost::multi_array< double, 1 >, std::vector< std::vector< double > > > readMultiArrayAndIndependentVariables (const std::string fileName)
Function to read a multi-array from the file, and the values of the independent variables at which it is defined.
Detailed Description
template<unsigned int NumberOfDimensions>
class tudat::input_output::MultiArrayFileReader< NumberOfDimensions >
Interface class for reading coefficients as a function of N independent variables from a file. This class is used instead of a single templated free function to allow multi-arrays of different sizes to be created using the same interface. NOTE: The possibility of using a single templated implementation for arbitrary multi-array size should be investigated in the future.
Definition at line 102 of file multiDimensionalArrayReader.h.
Member Function Documentation
readMultiArray()
template<unsigned int NumberOfDimensions> static boost::multi_array< double, static_cast< size_t > NumberOfDimensions) > tudat::input_output::MultiArrayFileReader< NumberOfDimensions >::readMultiArray (const std::string fileName) static
Function to read only a multi-array from the file, not saving the values of the independent variables it is defined.
Parameters
fileName Name of the coefficient file
Returns
Multi-array containing file contents.
readMultiArrayAndIndependentVariables()
template<unsigned int NumberOfDimensions> static std::pair< boost::multi_array< double, 1 >, std::vector< std::vector< double > > > tudat::input_output::MultiArrayFileReader< NumberOfDimensions >::readMultiArrayAndIndependentVariables (const std::string fileName) static
Function to read a multi-array from the file, and the values of the independent variables at which it is defined
Parameters
fileName Name of the coefficient file
Returns
Pair: first entry containing multi-array of double coefficients, second containing list of independent variables at which coefficients are defined.
Referenced by tudat::simulation_setup::readCoefficientInterpolatorFromFile(), tudat::input_output::MultiArrayFileReader< 1 >::readMultiArray(), tudat::input_output::MultiArrayFileReader< 2 >::readMultiArray(), tudat::input_output::MultiArrayFileReader< 3 >::readMultiArray(), and tudat::input_output::MultiArrayFileReader< 4 >::readMultiArray().
The documentation for this class was generated from the following file:
InputOutput/multiDimensionalArrayReader.h