Tudat: tudat::observation_partials::AngularPositionPartial Class Reference
tudat::observation_partials::AngularPositionPartial Class Reference
Class to compute the partial derivatives of a angular position observation partial.
#include <angularPositionPartial.h>
Public Types
typedef std::vector< std::pair< Eigen::Matrix< double, 2, Eigen::Dynamic >, double > > AngularPositionPartialReturnType
typedef std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > SingleOneWayRangePartialReturnType
Public Member Functions
AngularPositionPartial (const std::shared_ptr< AngularPositionScaling > angularPositionScaler, const std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > &positionPartialList, const estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lighTimeCorrectionPartials=std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Constructor.
~AngularPositionPartial ()
Destructor.
AngularPositionPartialReturnType calculatePartial (const std::vector< Eigen::Vector6d > &states, const std::vector< double > &times, const observation_models::LinkEndType linkEndOfFixedTime, const Eigen::Vector2d &currentObservation=Eigen::Vector2d::Constant(TUDAT_NAN))
Function to calculate the observation partial(s) at required time and state.
int getNumberOfLighTimeCorrectionPartialsFunctions ()
Function to get the number of light-time correction partial functions.
Public Member Functions inherited from tudat::observation_partials::ObservationPartial< 2 >
ObservationPartial (const estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier)
Constructor.
virtual ~ObservationPartial ()
Virtual destructor.
virtual std::vector< std::pair< Eigen::Matrix< double, ObservationSize, Eigen::Dynamic >, double > > calculatePartial (const std::vector< Eigen::Vector6d > &states, const std::vector< double > &times, const observation_models::LinkEndType linkEndOfFixedTime=observation_models::receiver, const Eigen::Matrix< double, ObservationSize, 1 > &currentObservation=Eigen::Matrix< double, ObservationSize, 1 >::Constant(TUDAT_NAN))=0
Pure virtual function to calculate the observation partial(s) at required time(s) and state(s)
estimatable_parameters::EstimatebleParameterIdentifier getParameterIdentifier ()
Function to get parameter id of for specifc parameter of which partial is computed by object.
Protected Attributes
std::shared_ptr< AngularPositionScaling > angularPositionScaler_
Scaling object used for mapping partials of positions to partials of observable.
std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > currentLinkTimeCorrectionPartial_
Pre-declare partial for current link end.
Eigen::Vector6d currentState_
Pre-declared state variable to be used in calculatePartial function.
double currentTime_
Pre-declared time variable to be used in calculatePartial function.
std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > lighTimeCorrectionPartials_
List of light-time correction partial objects.
std::vector< std::function< SingleOneWayRangePartialReturnType(const std::vector< Eigen::Vector6d > &, const std::vector< double > &) > > lighTimeCorrectionPartialsFunctions_
List of light-time correction partial functions.
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > >::iterator positionPartialIterator_
Iterator over list of position partials per link end.
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > positionPartialList_
List of position partials per link end.
Protected Attributes inherited from tudat::observation_partials::ObservationPartial< 2 >
estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier_
Parameter id of for specifc parameter of which partial is computed by object.
Detailed Description
Definition at line 137 of file angularPositionPartial.h.
Member Typedef Documentation
AngularPositionPartialReturnType
typedef std::vector< std::pair< Eigen::Matrix< double, 2, Eigen::Dynamic >, double > > tudat::observation_partials::AngularPositionPartial::AngularPositionPartialReturnType
Definition at line 140 of file angularPositionPartial.h.
SingleOneWayRangePartialReturnType
typedef std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > tudat::observation_partials::AngularPositionPartial::SingleOneWayRangePartialReturnType
Definition at line 141 of file angularPositionPartial.h.
Constructor & Destructor Documentation
AngularPositionPartial()
tudat::observation_partials::AngularPositionPartial::AngularPositionPartial (const std::shared_ptr< AngularPositionScaling > angularPositionScaler, const std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > & positionPartialList, const estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lighTimeCorrectionPartials = std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >()) inline
Constructor
Parameters
angularPositionScaler Scaling object used for mapping partials of positions to partials of observable
positionPartialList List of position partials per link end.
parameterIdentifier Id of parameter for which instance of class computes partial derivatives.
lighTimeCorrectionPartials List if light-time correction partial objects.
Definition at line 151 of file angularPositionPartial.h.
References tudat::observation_partials::getLightTimeParameterPartialFunction, and lighTimeCorrectionPartialsFunctions_.
~AngularPositionPartial()
tudat::observation_partials::AngularPositionPartial::~AngularPositionPartial () inline
Definition at line 178 of file angularPositionPartial.h.
Member Function Documentation
calculatePartial()
AngularPositionPartial::AngularPositionPartialReturnType tudat::observation_partials::AngularPositionPartial::calculatePartial (const std::vector< Eigen::Vector6d > & states, const std::vector< double > & times, const observation_models::LinkEndType linkEndOfFixedTime, const Eigen::Vector2d & currentObservation = Eigen::Vector2d::Constant(TUDAT_NAN))
Function to calculate the observation partial(s) at required time and state. State and time are typically obtained from evaluation of observation model.
Parameters
states Link end states. Index maps to link end for a given ObsevableType through getLinkEndIndex function.
times Link end time.
linkEndOfFixedTime Link end that is kept fixed when computing the observable.
currentObservation Value of the observation for which the partial is to be computed (default NaN for compatibility purposes)
Returns
Vector of pairs containing partial values and associated times.
Definition at line 106 of file angularPositionPartial.cpp.
References angularPositionScaler_, currentLinkTimeCorrectionPartial_, currentState_, currentTime_, lighTimeCorrectionPartialsFunctions_, positionPartialIterator_, positionPartialList_, tudat::observation_models::receiver, tudat::physical_constants::SPEED_OF_LIGHT, and tudat::observation_models::transmitter.
getNumberOfLighTimeCorrectionPartialsFunctions()
int tudat::observation_partials::AngularPositionPartial::getNumberOfLighTimeCorrectionPartialsFunctions () inline
Number of light-time correction partial functions.
Returns
Number of light-time correction partial functions.
Definition at line 202 of file angularPositionPartial.h.
References lighTimeCorrectionPartialsFunctions_.
Member Data Documentation
angularPositionScaler_
std::shared_ptr< AngularPositionScaling > tudat::observation_partials::AngularPositionPartial::angularPositionScaler_ protected
Definition at line 210 of file angularPositionPartial.h.
Referenced by calculatePartial().
positionPartialList_
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > tudat::observation_partials::AngularPositionPartial::positionPartialList_ protected
Definition at line 213 of file angularPositionPartial.h.
Referenced by calculatePartial().
positionPartialIterator_
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > >::iterator tudat::observation_partials::AngularPositionPartial::positionPartialIterator_ protected
Definition at line 216 of file angularPositionPartial.h.
Referenced by calculatePartial().
lighTimeCorrectionPartialsFunctions_
std::vector< std::function< SingleOneWayRangePartialReturnType(const std::vector< Eigen::Vector6d >&, const std::vector< double >&) > > tudat::observation_partials::AngularPositionPartial::lighTimeCorrectionPartialsFunctions_ protected
Definition at line 221 of file angularPositionPartial.h.
Referenced by AngularPositionPartial(), calculatePartial(), and getNumberOfLighTimeCorrectionPartialsFunctions().
lighTimeCorrectionPartials_
std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > tudat::observation_partials::AngularPositionPartial::lighTimeCorrectionPartials_ protected
Definition at line 224 of file angularPositionPartial.h.
currentLinkTimeCorrectionPartial_
std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > tudat::observation_partials::AngularPositionPartial::currentLinkTimeCorrectionPartial_ protected
Definition at line 227 of file angularPositionPartial.h.
Referenced by calculatePartial().
currentState_
Eigen::Vector6d tudat::observation_partials::AngularPositionPartial::currentState_ protected
Definition at line 230 of file angularPositionPartial.h.
Referenced by calculatePartial().
currentTime_
double tudat::observation_partials::AngularPositionPartial::currentTime_ protected
Definition at line 233 of file angularPositionPartial.h.
Referenced by calculatePartial().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/ObservationPartials/angularPositionPartial.h
Astrodynamics/OrbitDetermination/ObservationPartials/angularPositionPartial.cpp