Tudat: tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > Class Template Reference
tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > Class Template Reference
Class for performing full numerical integration of a dynamical system in a single arc.
#include <dynamicsSimulator.h>
Public Member Functions
SingleArcDynamicsSimulator (const simulation_setup::NamedBodyMap &bodyMap, const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const boost::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const bool areEquationsOfMotionToBeIntegrated=true, const bool clearNumericalSolutions=false, const bool setIntegratedResult=false)
Constructor of simulator.
~SingleArcDynamicsSimulator ()
Destructor.
std::map< TimeType, Eigen::VectorXd > getDependentVariableHistory ()
Function to return the map of dependent variable history that was saved during numerical propagation.
std::vector< std::map< TimeType, Eigen::VectorXd > > getDependentVariableNumericalSolutionBase ()
boost::function< Eigen::VectorXd() > getDependentVariablesFunctions ()
boost::function< Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > const double, const Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > &) > getDoubleStateDerivativeFunction ()
Function to get the function that performs a single state derivative function evaluation with double precision.
boost::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > getDynamicsStateDerivative ()
Function to get the object that updates and returns state derivative.
boost::shared_ptr< EnvironmentUpdater< StateScalarType, TimeType > > getEnvironmentUpdater ()
Function to get the object that updates the environment.
std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > getEquationsOfMotionNumericalSolution ()
Function to return the map of state history of numerically integrated bodies.
std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > getEquationsOfMotionNumericalSolutionBase ()
double getInitialPropagationTime ()
Function to retrieve initial time of propagation.
std::map< IntegratedStateType, std::vector< boost::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > getIntegratedStateProcessors ()
boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > getIntegratorSettings ()
Function to get the settings for the numerical integrator.
boost::shared_ptr< PropagationTerminationCondition > getPropagationTerminationCondition ()
Function to retrieve the Object defining when the propagation is to be terminated.
PropagationTerminationReason getPropagationTerminationReason ()
Function to retrieve the event that triggered the termination of the last propagation.
boost::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > getPropagatorSettings ()
Function to get the settings for the propagator.
boost::function< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > const TimeType, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &) > getStateDerivativeFunction ()
Function to get the function that performs a single state derivative function evaluation.
void integrateEquationsOfMotion (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &initialStates)
This function numerically (re-)integrates the equations of motion.
void manuallySetAndProcessRawNumericalEquationsOfMotionSolution (const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &equationsOfMotionNumericalSolution, const std::map< TimeType, Eigen::VectorXd > &dependentVariableHistory)
Function to reset the environment from an externally generated state history.
Public Member Functions inherited from tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >
DynamicsSimulator (const simulation_setup::NamedBodyMap &bodyMap, const bool clearNumericalSolutions=true, const bool setIntegratedResult=true)
Constructor of simulator.
virtual ~DynamicsSimulator ()
Virtual destructor.
simulation_setup::NamedBodyMap getNamedBodyMap ()
Function to get the map of named bodies involved in simulation.
void resetSetIntegratedResult (const bool setIntegratedResult)
Protected Member Functions
void processNumericalEquationsOfMotionSolution ()
This function updates the environment with the numerical solution of the propagation.
Protected Attributes
std::map< TimeType, Eigen::VectorXd > dependentVariableHistory_
Map of dependent variable history that was saved during numerical propagation.
std::map< int, std::string > dependentVariableIds_
Map listing starting entry of dependent variables in output vector, along with associated ID.
boost::function< Eigen::VectorXd() > dependentVariablesFunctions_
Function returning dependent variables (during numerical propagation)
boost::function< Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > const double, const Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > &) > doubleStateDerivativeFunction_
Function that performs a single state derivative function evaluation with double precision.
boost::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > dynamicsStateDerivative_
Interface object that updates current environment and returns state derivative from single function call.
boost::shared_ptr< EnvironmentUpdater< StateScalarType, TimeType > > environmentUpdater_
Object responsible for updating the environment based on the current state and time.
std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > equationsOfMotionNumericalSolution_
Map of state history of numerically integrated bodies.
boost::shared_ptr< ephemerides::ReferenceFrameManager > frameManager_
Object for retrieving ephemerides for transformation of reference frame (origins)
double initialPropagationTime_
Initial time of propagation.
std::map< IntegratedStateType, std::vector< boost::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > integratedStateProcessors_
List of object (per dynamics type) that process the integrated numerical solution by updating the environment.
boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings_
Settings for numerical integrator.
boost::shared_ptr< PropagationTerminationCondition > propagationTerminationCondition_
Object defining when the propagation is to be terminated.
PropagationTerminationReason propagationTerminationReason_
Event that triggered the termination of the propagation.
boost::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings_
Settings for propagator.
boost::function< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > const TimeType, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &) > stateDerivativeFunction_
Function that performs a single state derivative function evaluation.
Protected Attributes inherited from tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >
simulation_setup::NamedBodyMap bodyMap_
Map of bodies (with names) of all bodies in integration.
bool clearNumericalSolutions_
bool setIntegratedResult_
Boolean to determine whether to automatically use the integrated results to set ephemerides.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >
Class for performing full numerical integration of a dynamical system in a single arc, i.e. the equations of motion have a single initial time, and are propagated once for the full prescribed time interval. This is in contrast to multi-arc dynamics, where the time interval si cut into pieces. In this class, the governing equations are set once, but can be re-integrated for different initial conditions using the same instance of the class.
Definition at line 259 of file dynamicsSimulator.h.
Constructor & Destructor Documentation
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::SingleArcDynamicsSimulator (const simulation_setup::NamedBodyMap & bodyMap, const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const boost::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const bool areEquationsOfMotionToBeIntegrated = true, const bool clearNumericalSolutions = false, const bool setIntegratedResult = false) inline
Constructor of simulator, constructs integrator and object for calculating each time step of integration.
Parameters
bodyMap Map of bodies (with names) of all bodies in integration.
integratorSettings Settings for numerical integrator.
propagatorSettings Settings for propagator.
areEquationsOfMotionToBeIntegrated Boolean to denote whether equations of motion should be integrated immediately at the end of the contructor or not (default true).
clearNumericalSolutions Boolean to determine whether to clear the raw numerical solution member variables after propagation and resetting ephemerides (default false).
setIntegratedResult Boolean to determine whether to automatically use the integrated results to set ephemerides (default false).
Definition at line 282 of file dynamicsSimulator.h.
References tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::bodyMap_, tudat::propagators::createFrameManager(), tudat::propagators::createPropagationTerminationConditions(), tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::utilities::printMapContents(), and tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::setIntegratedResult_.
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::~SingleArcDynamicsSimulator () inline
Definition at line 360 of file dynamicsSimulator.h.
Member Function Documentation
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & initialStates) inline virtual
This function numerically (re-)integrates the equations of motion, using the settings set through the constructor and a new initial state vector provided here. The raw results are set in the equationsOfMotionNumericalSolution_
Parameters
initialStates Initial state vector that is to be used for numerical integration. Note that this state should be in the correct frame (i.e. corresponding to centralBodies in propagatorSettings_), but not in the propagator- specific form (i.e Encke, Gauss, etc. for translational dynamics)
See also
SingleStateTypeDerivative::convertToOutputSolution
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 372 of file dynamicsSimulator.h.
References tudat::propagators::PropagationTerminationCondition::checkStopCondition(), tudat::propagators::convertNumericalStateSolutionsToOutputSolutions(), tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution(), and tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::setIntegratedResult_.
template<typename StateScalarType = double, typename TimeType = double> std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolution () inline
Function to return the map of state history of numerically integrated bodies.
Returns
Map of state history of numerically integrated bodies.
Definition at line 408 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> std::map< TimeType, Eigen::VectorXd > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableHistory () inline
Function to return the map of dependent variable history that was saved during numerical propagation.
Returns
Map of dependent variable history that was saved during numerical propagation.
Definition at line 418 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolutionBase () inline virtual
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 423 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< TimeType, Eigen::VectorXd > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariableNumericalSolutionBase () inline virtual
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 429 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::manuallySetAndProcessRawNumericalEquationsOfMotionSolution (const std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & equationsOfMotionNumericalSolution, const std::map< TimeType, Eigen::VectorXd > & dependentVariableHistory) inline
Function to reset the environment from an externally generated state history, the order of the entries in the state vectors are proscribed by propagatorSettings
Parameters
equationsOfMotionNumericalSolution Externally generated state history.
Definition at line 442 of file dynamicsSimulator.h.
References tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution().
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getIntegratorSettings () inline
Function to get the settings for the numerical integrator.
Returns
The settings for the numerical integrator.
Definition at line 457 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::function< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > const TimeType, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic >&) > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getStateDerivativeFunction () inline
Function to get the function that performs a single state derivative function evaluation.
Returns
Function that performs a single state derivative function evaluation.
Definition at line 469 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::function< Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > const double, const Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic >&) > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDoubleStateDerivativeFunction () inline
Function to get the function that performs a single state derivative function evaluation with double precision, regardless of template arguments.
Returns
Function that performs a single state derivative function evaluation with double precision.
Definition at line 481 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getPropagatorSettings () inline
Function to get the settings for the propagator.
Returns
The settings for the propagator.
Definition at line 491 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< EnvironmentUpdater< StateScalarType, TimeType > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getEnvironmentUpdater () inline
Function to get the object responsible for updating the environment based on the current state and time.
Returns
Object responsible for updating the environment based on the current state and time.
Definition at line 501 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDynamicsStateDerivative () inline
Function to get the object that updates current environment and returns state derivative from single function call
Returns
Object that updates current environment and returns state derivative from single function call
Definition at line 511 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< PropagationTerminationCondition > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getPropagationTerminationCondition () inline
Function to retrieve the Object defining when the propagation is to be terminated.
Returns
Object defining when the propagation is to be terminated.
Definition at line 522 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> std::map< IntegratedStateType, std::vector< boost::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getIntegratedStateProcessors () inline
Definition at line 528 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> PropagationTerminationReason tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getPropagationTerminationReason () inline
Function to retrieve the event that triggered the termination of the last propagation
Returns
Event that triggered the termination of the last propagation
Definition at line 539 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> double tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getInitialPropagationTime () inline
Function to retrieve initial time of propagation
Returns
Initial time of propagation
Definition at line 549 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::function< Eigen::VectorXd() > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::getDependentVariablesFunctions () inline
Definition at line 554 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution () inline protected virtual
This function updates the environment with the numerical solution of the propagation. It sets the propagated translational dynamics solution as the new input for the Ephemeris object of the body that was propagated.
Implements tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >.
Definition at line 570 of file dynamicsSimulator.h.
References tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::bodyMap_, tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::clearNumericalSolutions_, and tudat::propagators::resetIntegratedStates().
Member Data Documentation
template<typename StateScalarType = double, typename TimeType = double> std::map< IntegratedStateType, std::vector< boost::shared_ptr< IntegratedStateProcessor< TimeType, StateScalarType > > > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::integratedStateProcessors_ protected
Definition at line 593 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< EnvironmentUpdater< StateScalarType, TimeType > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::environmentUpdater_ protected
Object responsible for updating the environment based on the current state and time. Calling the updateEnvironment function automatically updates all dependent variables that are needed to calulate the state derivative.
Definition at line 600 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::dynamicsStateDerivative_ protected
Definition at line 603 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::function< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > const TimeType, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic >&) > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::stateDerivativeFunction_ protected
Function that performs a single state derivative function evaluation, will typically be set to DynamicsStateDerivativeModel< TimeType, StateScalarType >::computeStateDerivative function. Calling this function will first update the environment (using environmentUpdater_) and then calculate the full system state derivative.
Definition at line 613 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::function< Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > const double, const Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic >&) > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::doubleStateDerivativeFunction_ protected
Function that performs a single state derivative function evaluation with double precision
See also
stateDerivativeFunction_
Definition at line 621 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::integratorSettings_ protected
Definition at line 625 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::propagatorSettings_ protected
Definition at line 628 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< PropagationTerminationCondition > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::propagationTerminationCondition_ protected
Definition at line 631 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::function< Eigen::VectorXd() > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariablesFunctions_ protected
Definition at line 634 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> std::map< int, std::string > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariableIds_ protected
Definition at line 637 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< ephemerides::ReferenceFrameManager > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::frameManager_ protected
Definition at line 640 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::equationsOfMotionNumericalSolution_ protected
Map of state history of numerically integrated bodies, i.e. the result of the numerical integration, transformed into the 'conventional form' (
See also
SingleStateTypeDerivative::convertToOutputSolution). Key of map denotes time, values are concatenated vectors of integrated body states (order defined by propagatorSettings_). NOTE: this map is empty if clearNumericalSolutions_ is set to true.
Definition at line 649 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> std::map< TimeType, Eigen::VectorXd > tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::dependentVariableHistory_ protected
Definition at line 652 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> double tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::initialPropagationTime_ protected
Definition at line 655 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> PropagationTerminationReason tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::propagationTerminationReason_ protected
Definition at line 658 of file dynamicsSimulator.h.
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/dynamicsSimulator.h