Tudat: tudat::gravitation Namespace Reference
tudat::gravitation Namespace Reference
Namespaces
circular_restricted_three_body_problem
Classes
class BasicSolidBodyTideGravityFieldVariations
class CentralGravitationalAccelerationModel
Template class for central gravitational acceleration model.
class CentralJ2GravitationalAccelerationModel
Central + J2 gravitational acceleration model class.
class CentralJ2J3GravitationalAccelerationModel
Central + J2 + J3 gravitational acceleration model class.
class CentralJ2J3J4GravitationalAccelerationModel
Central + J2 + J3 + J4 gravitational acceleration model class.
class DirectTidalDissipationAcceleration
Class to compute the acceleration due to tidal dissipation caused by/on this satellite on/by host planet.
class GravityFieldModel
GravityFieldModel class.
class GravityFieldVariations
Virual base class for spherical harmonic gravity field variations (i.e.
class GravityFieldVariationsSet
Container class containing all gravity field variations for a single Body (and TimeDependentSphericalHarmonicsGravityField).
class MutualSphericalHarmonicsGravitationalAccelerationModel
Class to calculate the mutual spherical harmonic gravitational acceleration between two bodies.
class PairInterpolationInterface
Interface class between GravityFieldVariations objects that are interpolated and TimeDependentSphericalHarmonicsGravityField, the getCosineSinePair function mimics the addSphericalHarmonicsCorrections function of GravityFieldVariations.
class SecondDegreeGravitationalTorqueModel
Class to compute the second degree gravitational torque.
class SphericalHarmonicsGravitationalAccelerationModel
Template class for general spherical harmonics gravitational acceleration model.
class SphericalHarmonicsGravitationalAccelerationModelBase
Template base class for spherical harmonics gravitational acceleration models.
class SphericalHarmonicsGravityField
Class to represent a spherical harmonic gravity field expansion.
class TabulatedGravityFieldVariations
Class for variations in spherical harmonic coefficients, directly interpolated from tables.
class ThirdBodyAcceleration
Class for calculating third-body (gravitational) accelerations.
class TimeDependentSphericalHarmonicsGravityField
Class for time dependent spherical harmonic gravity field.
Typedefs
typedef CentralGravitationalAccelerationModel< > CentralGravitationalAccelerationModel3d
Typedef for CentralGravitationalAccelerationModel3d.
typedef std::shared_ptr< CentralGravitationalAccelerationModel3d > CentralGravitationalAccelerationModel3dPointer
Typedef for shared-pointer to CentralGravitationalAccelerationModel3d.
typedef std::shared_ptr< CentralJ2GravitationalAccelerationModel > CentralJ2GravitationalAccelerationModelPointer
Typedef for shared-pointer to CentralJ2GravitationalAccelerationModel.
typedef std::shared_ptr< CentralJ2J3GravitationalAccelerationModel > CentralJ2J3GravitationalAccelerationModelPointer
Typedef for shared-pointer to CentralJ2J3GravitationalAccelerationModel3d.
typedef std::shared_ptr< CentralJ2J3J4GravitationalAccelerationModel > CentralJ2J3J4GravitationalAccelerationModelPointer
Typedef for shared-pointer to CentralJ2J3J4GravitationalAccelerationModel.
typedef std::shared_ptr< GravityFieldModel > GravityFieldModelPointer
Typedef for shared-pointer to GravityFieldModel object.
typedef std::shared_ptr< SphericalHarmonicsGravitationalAccelerationModel > SphericalHarmonicsGravitationalAccelerationModelPointer
Typedef for shared-pointer to SphericalHarmonicsGravitationalAccelerationModel.
typedef ThirdBodyAcceleration< CentralGravitationalAccelerationModel3d > ThirdBodyCentralGravityAcceleration
Typedef for third body central gravity acceleration.
typedef ThirdBodyAcceleration< MutualSphericalHarmonicsGravitationalAccelerationModel > ThirdBodyMutualSphericalHarmonicsGravitationalAccelerationModel
Typedef for third body mutual spherical harmonic gravity acceleration.
typedef ThirdBodyAcceleration< SphericalHarmonicsGravitationalAccelerationModel > ThirdBodySphericalHarmonicsGravitationalAccelerationModel
Typedef for third body spherical harmonic gravity acceleration.
Enumerations
enum BodiesWithPredefinedCentralGravityFields {
sun, mercury, venus, earth,
moon, mars, jupiter, saturn,
uranus, neptune
}
enum BodyDeformationTypes { basic_solid_body, tabulated_variation }
Functions
double calculateCosineTermForTriaxialEllipsoidSphericalHarmonicGravity (const double aSquaredMinusCSquared, const double bSquaredMinusCSquared, const double referenceRadius, const int degree, const int order)
Function to calculate (non-normalized) cosine spherical harmonic coefficient for a homogeneous triaxial ellipsoid, from method of Boyce (1997) at a given degree and order.
Eigen::Vector3d calculateSecondDegreeGravitationalTorque (const Eigen::Vector3d &relativePositionOfBodySubjectToTorque, const double gravitationalParameterOfAttractingBody, const Eigen::Matrix3d &inertiaTensorOfRotatingBody)
Function to calculate the gravitational torque exerted by a point mass on a body with degree two gravity field.
std::complex< double > calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude (const std::complex< double > loveNumber, const double massRatio, const double radiusRatioPowerN, const double amplitude, const std::complex< double > tideArgument, const int degree, const int order)
Function to calculate solid body tide gravity field variations due to single body at single degree and order, (frequency-independent part), after (Petit et al.
std::complex< double > calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude (const std::complex< double > loveNumber, const double massRatio, const double referenceRadius, const Eigen::Vector3d &relativeBodyFixedPosition, const int degree, const int order)
Function to calculate solid body tide gravity field variations due to single body at single degree and order, (frequency-independent part), after (Petit et al.
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude (const std::vector< std::vector< std::complex< double > > > loveNumbers, const double massRatio, const double referenceRadius, const Eigen::Vector3d &relativeBodyFixedPosition, const int maximumDegree, const int maximumOrder)
Function to calculate solid body tide gravity field variations due to single body at a set of degrees and orders (frequency-independent part), after (Petit et al.
double calculateSphericalHarmonicGravitationalPotential (const Eigen::Vector3d &bodyFixedPosition, const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd &cosineCoefficients, const Eigen::MatrixXd &sineCoefficients, std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const int minimumumDegree, const int minimumumOrder)
Function to calculate the gravitational potential from a spherical harmonic field expansion.
double calculateTriAxialEllipsoidReferenceRadius (const double axisA, const double axisB, const double axisC)
Function to calculate triaxial ellipsoid reference radius.
double calculateTriAxialEllipsoidVolume (const double axisA, const double axisB, const double axisC)
Function to calculate triaxial ellipsoid volume.
Eigen::Vector3d computeDirectTidalAccelerationDueToTideOnPlanet (const Eigen::Vector6d relativeStateOfBodyExertingTide, const Eigen::Vector3d planetAngularVelocityVector, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute the acceleration acting on a satellite due to tidal deformation caused by this satellite on host planet.
Eigen::Vector3d computeDirectTidalAccelerationDueToTideOnSatellite (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute the acceleration acting on a satellite due to tidal deformation caused in this satellite by host planet.
Eigen::Vector3d computeGeodesyNormalizedGravitationalAccelerationSum (const Eigen::Vector3d &positionOfBodySubjectToAcceleration, const double gravitationalParameter, const double equatorialRadius, const Eigen::MatrixXd &cosineHarmonicCoefficients, const Eigen::MatrixXd &sineHarmonicCoefficients, std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, std::map< std::pair< int, int >, Eigen::Vector3d > &accelerationPerTerm, const bool saveSeparateTerms, const Eigen::Matrix3d &accelerationRotation)
Compute gravitational acceleration due to multiple spherical harmonics terms, defined using geodesy-normalization.
Eigen::Vector3d computeGravitationalAcceleration (const double universalGravitationalConstant, const Eigen::Vector3d &positionOfBodySubjectToAcceleration, const double massOfBodyExertingAcceleration, const Eigen::Vector3d &positionOfBodyExertingAcceleration)
Compute gravitational acceleration.
Eigen::Vector3d computeGravitationalAcceleration (const Eigen::Vector3d &positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const Eigen::Vector3d &positionOfBodyExertingAcceleration)
Compute gravitational acceleration.
Eigen::Vector3d computeGravitationalAccelerationDueToJ2 (const Eigen::Vector3d &positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const double equatorialRadiusOfBodyExertingAcceleration, const double j2CoefficientOfGravityField, const Eigen::Vector3d &positionOfBodyExertingAcceleration)
Compute gravitational acceleration due to J2.
Eigen::Vector3d computeGravitationalAccelerationDueToJ3 (const Eigen::Vector3d &positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const double equatorialRadiusOfBodyExertingAcceleration, const double j3CoefficientOfGravityField, const Eigen::Vector3d &positionOfBodyExertingAcceleration)
Compute gravitational acceleration due to J3.
Eigen::Vector3d computeGravitationalAccelerationDueToJ4 (const Eigen::Vector3d &positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const double equatorialRadiusOfBodyExertingAcceleration, const double j4CoefficientOfGravityField, const Eigen::Vector3d &positionOfBodyExertingAcceleration)
Compute gravitational acceleration due to J4.
Eigen::Vector3d computeGravitationalAccelerationZonalSum (const Eigen::Vector3d &positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const double equatorialRadiusOfBodyExertingAcceleration, const std::map< int, double > zonalCoefficientsOfGravityField, const Eigen::Vector3d &positionOfBodyExertingAcceleration)
Compute gravitational acceleration zonal sum.
Eigen::Vector3d computeGravitationalForce (const double universalGravitationalParameter, const double massOfBodySubjectToForce, const Eigen::Vector3d &positionOfBodySubjectToForce, const double massOfBodyExertingForce, const Eigen::Vector3d &positionOfBodyExertingForce)
Compute gravitational force.
Eigen::Vector3d computeGravitationalForce (const double massOfBodySubjectToForce, const Eigen::Vector3d &positionOfBodySubjectToForce, const double gravitationalParameterOfBodyExertingForce, const Eigen::Vector3d &positionOfBodyExertingForce)
Compute gravitational force.
double computeJacobiEnergy (const double massParameter, const Eigen::VectorXd &stateInNormalizedUnits)
Compute Jacobi energy.
Eigen::Vector3d computeSingleGeodesyNormalizedGravitationalAcceleration (const Eigen::Vector3d &positionOfBodySubjectToAcceleration, const double gravitationalParameter, const double equatorialRadius, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Compute gravitational acceleration due to single spherical harmonics term.
Eigen::Vector3d computeThirdBodyPerturbingAcceleration (const double gravitationalParameterOfPerturbingBody, const Eigen::Vector3d &positionOfPerturbingBody, const Eigen::Vector3d &positionOfAffectedBody, const Eigen::Vector3d &positionOfCentralBody)
Compute perturbing acceleration by third body.
std::function< void(const double, Eigen::MatrixXd &, Eigen::MatrixXd &) > createInterpolatedSphericalHarmonicCorrectionFunctions (std::shared_ptr< GravityFieldVariations > variationObject, const double initialTime, const double finalTime, const double timeStep, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings)
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > createTriAxialEllipsoidNormalizedSphericalHarmonicCoefficients (const double axisA, const double axisB, const double axisC, const int maximumDegree, const int maximumOrder)
Function to calculate (normalized) cosine and sinespherical harmonic coefficients for a homogeneous triaxial ellipsoid, from method of Boyce (1997) up to given degree and order.
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > createTriAxialEllipsoidSphericalHarmonicCoefficients (const double axisA, const double axisB, const double axisC, const int maximumDegree, const int maximumOrder)
Function to calculate (non-normalized) cosine and sinespherical harmonic coefficients for a homogeneous triaxial ellipsoid, from method of Boyce (1997) up to given degree and order.
Eigen::MatrixXd createTriAxialEllipsoidSphericalHarmonicCosineCoefficients (const double axisA, const double axisB, const double axisC, const int maximumDegree, const int maximumOrder)
Function to calculate (non-normalized) cosine spherical harmonic coefficients for a homogeneous triaxial ellipsoid, from method of Boyce (1997) up to given degree and order.
void from_json (const nlohmann::json &jsonObject, BodyDeformationTypes &bodyDeformationType)
Convert json to BodyDeformationTypes.
std::vector< std::vector< std::complex< double > > > getFullLoveNumbersVector (const std::complex< double > constantLoveNumber, const int maximumDegree, const int maximumOrder)
Function to create constant complex Love number list for a range of degrees and orders.
std::vector< std::vector< std::complex< double > > > getFullLoveNumbersVector (const double constantLoveNumber, const int maximumDegree, const int maximumOrder)
Function to create constant real Love number list for a range of degrees and orders.
std::shared_ptr< GravityFieldModel > getPredefinedCentralGravityField (BodiesWithPredefinedCentralGravityFields bodyWithPredefinedCentralGravityField)
Set predefined central gravity field settings.
std::vector< std::shared_ptr< DirectTidalDissipationAcceleration > > getTidalDissipationAccelerationModels (const basic_astrodynamics::AccelerationMap accelerationModelList, const std::string bodyBeingDeformed, const std::vector< std::string > &bodiesCausingDeformation)
Function to retrieve all DirectTidalDissipationAcceleration from an AccelerationMap, for specific deformed/deforming bodies.
Eigen::MatrixXd setDegreeAndOrderCoefficientToZero (const std::function< Eigen::MatrixXd() > originalCosineCoefficientFunction)
Function to manually remove the C(0,0) term from cosine coefficients,.
void to_json (nlohmann::json &jsonObject, const BodyDeformationTypes &bodyDeformationType)
Convert BodyDeformationTypes to json.
Variables
static std::map< BodyDeformationTypes, std::string > bodyDeformationTypes
Map of BodyDeformationTypes string representations.
std::function< void(const double, Eigen::MatrixXd &, Eigen::MatrixXd &) > createInterpolatedSphericalHarmonicCorrectionFunctions (std::shared_ptr< GravityFieldVariations > variationObject, const double initialTime, const double finalTime, const double timeStep, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings=std::make_shared< interpolators::InterpolatorSettings >(interpolators::linear_interpolator, interpolators::huntingAlgorithm))
Function to create a function linearly interpolating the sine and cosine correction coefficients produced by an object of GravityFieldVariations type.
static std::vector< BodyDeformationTypes > unsupportedBodyDeformationTypes = { }
BodyDeformationTypes not supported by json_interface.
Typedef Documentation
CentralGravitationalAccelerationModel3d
typedef CentralGravitationalAccelerationModel< > tudat::gravitation::CentralGravitationalAccelerationModel3d
Definition at line 251 of file centralGravityModel.h.
CentralGravitationalAccelerationModel3dPointer
typedef std::shared_ptr< CentralGravitationalAccelerationModel3d > tudat::gravitation::CentralGravitationalAccelerationModel3dPointer
Definition at line 255 of file centralGravityModel.h.
CentralJ2GravitationalAccelerationModelPointer
typedef std::shared_ptr< CentralJ2GravitationalAccelerationModel > tudat::gravitation::CentralJ2GravitationalAccelerationModelPointer
Definition at line 159 of file centralJ2GravityModel.h.
CentralJ2J3GravitationalAccelerationModelPointer
typedef std::shared_ptr< CentralJ2J3GravitationalAccelerationModel > tudat::gravitation::CentralJ2J3GravitationalAccelerationModelPointer
Definition at line 171 of file centralJ2J3GravityModel.h.
CentralJ2J3J4GravitationalAccelerationModelPointer
typedef std::shared_ptr< CentralJ2J3J4GravitationalAccelerationModel > tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModelPointer
Definition at line 227 of file centralJ2J3J4GravityModel.h.
GravityFieldModelPointer
typedef std::shared_ptr< GravityFieldModel > tudat::gravitation::GravityFieldModelPointer
Definition at line 112 of file gravityFieldModel.h.
SphericalHarmonicsGravitationalAccelerationModelPointer
typedef std::shared_ptr< SphericalHarmonicsGravitationalAccelerationModel > tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModelPointer
Definition at line 628 of file sphericalHarmonicsGravityModel.h.
ThirdBodyCentralGravityAcceleration
typedef ThirdBodyAcceleration< CentralGravitationalAccelerationModel3d > tudat::gravitation::ThirdBodyCentralGravityAcceleration
Definition at line 199 of file thirdBodyPerturbation.h.
ThirdBodySphericalHarmonicsGravitationalAccelerationModel
typedef ThirdBodyAcceleration< SphericalHarmonicsGravitationalAccelerationModel > tudat::gravitation::ThirdBodySphericalHarmonicsGravitationalAccelerationModel
Definition at line 203 of file thirdBodyPerturbation.h.
ThirdBodyMutualSphericalHarmonicsGravitationalAccelerationModel
typedef ThirdBodyAcceleration< MutualSphericalHarmonicsGravitationalAccelerationModel > tudat::gravitation::ThirdBodyMutualSphericalHarmonicsGravitationalAccelerationModel
Definition at line 207 of file thirdBodyPerturbation.h.
Enumeration Type Documentation
BodiesWithPredefinedCentralGravityFields
enum tudat::gravitation::BodiesWithPredefinedCentralGravityFields
List of bodies for which predefined central gravity fields may be created through the getPredefinedCentralGravityField function.
Enumerator
sun
mercury
venus
earth
moon
mars
jupiter
saturn
uranus
neptune
Definition at line 106 of file gravityFieldModel.h.
BodyDeformationTypes
enum tudat::gravitation::BodyDeformationTypes
Enumerator
basic_solid_body
tabulated_variation
Definition at line 26 of file gravityFieldVariations.h.
Function Documentation
getFullLoveNumbersVector() [1/2]
std::vector< std::vector< std::complex< double > > > tudat::gravitation::getFullLoveNumbersVector (const std::complex< double > constantLoveNumber, const int maximumDegree, const int maximumOrder)
Function to create constant complex Love number list for a range of degrees and orders, maximum degree and order are given as input, minimum degree and order are 2 and 0, respectively.
Parameters
constantLoveNumber Love number to be set at each degree and order
maximumDegree Maximum degree for Love numbers.
maximumOrder Maximum order for Love numbers.
Returns
List of Love numbers with requested settings.
Definition at line 22 of file basicSolidBodyTideGravityFieldVariations.cpp.
Referenced by getFullLoveNumbersVector().
getFullLoveNumbersVector() [2/2]
std::vector< std::vector< std::complex< double > > > tudat::gravitation::getFullLoveNumbersVector (const double constantLoveNumber, const int maximumDegree, const int maximumOrder)
Function to create constant real Love number list for a range of degrees and orders, maximum degree and order are given as input, minimum degree and order are 2 and 0, respectively.
Parameters
constantLoveNumber Love number to be set at each degree and order
maximumDegree Maximum degree for Love numbers.
maximumOrder Maximum order for Love numbers.
Returns
List of Love numbers with requested settings.
Definition at line 50 of file basicSolidBodyTideGravityFieldVariations.cpp.
References getFullLoveNumbersVector().
calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude() [1/3]
std::complex< double > tudat::gravitation::calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude (const std::complex< double > loveNumber, const double massRatio, const double radiusRatioPowerN, const double amplitude, const std::complex< double > tideArgument, const int degree, const int order)
Function to calculate solid body tide gravity field variation due to single body at single degree and order.
Function to calculate solid body tide gravity field variations due to single body at single degree and order from precomputed quantaties.
2010, eq. 6.6), using complex tidal love numbers. Using this function requires the computation of a number of precomputed quantities (as is done by the BasicSolidBodyTideGravityFieldVariations class).
Parameters
loveNumber Complex Love number for given degree and order.
massRatio Ratio of masses of body causing deformation to body being deformed.
radiusRatioPowerN Ratio of equatorial radius of body being deformed over distance between center of body being deformed to center of body causing deformation to the power (n+1).
amplitude Amplitude of the tide.
tideArgument Argument of the tide.
degree Degree of current coefficients
order Order of current coefficients
Returns
Combined variation in cosine (Delta C_{n,m}) and sine (Delta S_{n,m}) coefficients as: Delta C_{n,m} - i * Delta S_{n,m}
Definition at line 58 of file basicSolidBodyTideGravityFieldVariations.cpp.
References tudat::basic_mathematics::calculateLegendreGeodesyNormalizationFactor().
Referenced by tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::addBasicSolidBodyTideCorrections(), tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateCoefficientPartialWrtRealTidalLoveNumber(), and calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude().
calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude() [2/3]
std::complex< double > tudat::gravitation::calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude (const std::complex< double > loveNumber, const double massRatio, const double referenceRadius, const Eigen::Vector3d & relativeBodyFixedPosition, const int degree, const int order)
Function to calculate solid body tide gravity field variations due to single body at single degree and order directly from perturbing body's Cartesian state.
Function to calculate solid body tide gravity field variations due to single body at single degree and order directly from perturbing body's Cartesian state.
2010, eq. 6.6), using complex tidal love numbers. This function directly uses the perturbing body's Cartesian state, and should be used for 'external' computations. The BasicSolidBodyTideGravityFieldVariations uses the alternative overloaded function.
Parameters
loveNumber Complex Love number for given degree and order.
massRatio Ratio of masses of body causing deformation to body being deformed.
referenceRadius Equatorial radius of body being deformed.
relativeBodyFixedPosition Cartesian position of body causing deformation in a frame centered on and fixed to the body that is being deformed.
degree Degree of current coefficients
order Order of current coefficients
Returns
Combined variation in cosine (Delta C_{n,m}) and sine (Delta S_{n,m}) coefficients as: Delta C_{n,m} - i * Delta S_{n,m}
Definition at line 73 of file basicSolidBodyTideGravityFieldVariations.cpp.
References tudat::basic_mathematics::calculateLegendreGeodesyNormalizationFactor(), tudat::basic_mathematics::computeLegendrePolynomialExplicit(), tudat::coordinate_conversions::convertCartesianToSpherical(), and tudat::mathematical_constants::PI.
calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude() [3/3]
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > tudat::gravitation::calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude (const std::vector< std::vector< std::complex< double > > > loveNumbers, const double massRatio, const double referenceRadius, const Eigen::Vector3d & relativeBodyFixedPosition, const int maximumDegree, const int maximumOrder)
Function to calculate solid body tide gravity field variations due to single body at a set of degrees and orders from perturbing body's Cartesian state.
Function to calculate solid body tide gravity field variations due to single body at a set of degrees and orders from perturbing body's Cartesian state.
2010, eq. 6.6), using complex tidal love numbers. This function directly uses the perturbing body's Cartesian state, and should be used for 'external' computations. The BasicSolidBodyTideGravityFieldVariations uses the alternative overloaded function. This function defines the maximum degree and order, and always starts at degree 2 and order 0
Parameters
loveNumbers Complex Love numbers for each degree and order (index of first vector is degree-2; index of second vector is order.
massRatio Ratio of masses of body causing deformation to body being deformed.
referenceRadius Equatorial radius of body being deformed.
relativeBodyFixedPosition Cartesian position of body causing deformation in a frame centered on and fixed to the body that is being deformed.
maximumDegree Maximum degree of current coefficient corrections.
maximumOrder Maximum order of current coefficient corrections.
Returns
Combined variation in cosine (Delta C_{n,m}) and sine (Delta S_{n,m}) matrices as first and second entry of pair, respectively. Both matrices start at degree and order 0.
Definition at line 96 of file basicSolidBodyTideGravityFieldVariations.cpp.
References calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude().
computeGravitationalAcceleration() [1/2]
Eigen::Vector3d tudat::gravitation::computeGravitationalAcceleration (const double universalGravitationalConstant, const Eigen::Vector3d & positionOfBodySubjectToAcceleration, const double massOfBodyExertingAcceleration, const Eigen::Vector3d & positionOfBodyExertingAcceleration = Eigen::Vector3d::Zero())
Computes gravitational acceleration experienced by body1, due to its interaction with body2. The basis for this gravitational acceleration is that body2 is a point mass, generating acceleration due to Newton's gravitational force:
where is the universal gravitational constant, is the mass of body2, and is the relative position vector from body1 to body 2, with respect to an inertial (barycentric) reference frame.
Parameters
universalGravitationalConstant Universal gravitational constant [m^3 kg^-1 s^-2].
positionOfBodySubjectToAcceleration Position vector of body subject to acceleration (body1) [m].
massOfBodyExertingAcceleration Mass of body exerting acceleration (body2) [kg].
positionOfBodyExertingAcceleration Position vector of body exerting acceleration (body2) [m].
Returns
Gravitational acceleration exerted on body1 [m s^-2].
See also
computeGravitationalForce.
Definition at line 22 of file centralGravityModel.cpp.
Referenced by computeGravitationalAccelerationZonalSum(), computeGravitationalForce(), computeThirdBodyPerturbingAcceleration(), tudat::gravitation::CentralJ2GravitationalAccelerationModel::getAcceleration(), tudat::gravitation::CentralJ2J3GravitationalAccelerationModel::getAcceleration(), tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::getAcceleration(), tudat::gravitation::CentralGravitationalAccelerationModel< StateMatrix >::getAcceleration(), and tudat::gravitation::GravityFieldModel::getGradientOfPotential().
computeGravitationalAcceleration() [2/2]
Eigen::Vector3d tudat::gravitation::computeGravitationalAcceleration (const Eigen::Vector3d & positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const Eigen::Vector3d & positionOfBodyExertingAcceleration = Eigen::Vector3d::Zero())
Computes gravitational acceleration experienced by body1, due to its interaction with body2. The basis for this gravitational acceleration is that body2 is a point mass, generating acceleration due to Newton's gravitational force:
where is the gravitational parameter of the body exerting acceleration, and is the relative position vector from body1 to body 2, with respect to an inertial (barycentric) reference frame.
Parameters
positionOfBodySubjectToAcceleration Position vector of body subject to acceleration (body1) [m].
gravitationalParameterOfBodyExertingAcceleration Gravitational parameter of body exerting acceleration (body2) [m^3 s^-2].
positionOfBodyExertingAcceleration Position vector of body exerting acceleration (body2) [m].
Returns
Gravitational acceleration exerted on body1 [m s^-2].
See also
computeGravitationalForce.
Definition at line 35 of file centralGravityModel.cpp.
computeGravitationalForce() [1/2]
Eigen::Vector3d tudat::gravitation::computeGravitationalForce (const double universalGravitationalParameter, const double massOfBodySubjectToForce, const Eigen::Vector3d & positionOfBodySubjectToForce, const double massOfBodyExertingForce, const Eigen::Vector3d & positionOfBodyExertingForce = Eigen::Vector3d::Zero())
Computes gravitational force experienced by body1, due to its interaction with body2. The basis for this gravitational force is that both body1 and body2 are point masses, generating Newton's gravitational force:
where is the universal gravitational constant, is the mass of body1, is the mass of body2, and is the relative position vector from body1 to body 2, with respect to an inertial (barycentric) reference frame.
Parameters
universalGravitationalParameter Universal gravitational constant [m^3 kg^-1 s^-2].
massOfBodySubjectToForce Mass of body subject to force (body1) [kg].
positionOfBodySubjectToForce Position vector of body subject to force (body1) [m].
massOfBodyExertingForce Mass of body exerting force (body2) [kg].
positionOfBodyExertingForce Position vector of body exerting force (body2) [m].
Returns
Gravitational force exerted on body1 [N].
See also
computeGravitationalAcceleration.
Definition at line 47 of file centralGravityModel.cpp.
References computeGravitationalAcceleration().
computeGravitationalForce() [2/2]
Eigen::Vector3d tudat::gravitation::computeGravitationalForce (const double massOfBodySubjectToForce, const Eigen::Vector3d & positionOfBodySubjectToForce, const double gravitationalParameterOfBodyExertingForce, const Eigen::Vector3d & positionOfBodyExertingForce = Eigen::Vector3d::Zero())
Computes gravitational force experienced by body1, due to its interaction with another body (body2) The basis for this gravitational force is that both body1 and body2 are point masses, generating Newton's gravitational force:
where is the mass of body1, is the gravitational parameter of the central body (body2), and is the relative position vector from body1 to the body exerting the force (body2), with respect to an inertial (barycentric) reference frame.
Parameters
massOfBodySubjectToForce Mass of body subject to force (body1) [kg].
positionOfBodySubjectToForce Position vector of body subject to force (body1) [m].
gravitationalParameterOfBodyExertingForce Gravitational parameter of body exerting force (body2) [m^3 s^-2].
positionOfBodyExertingForce Position vector of body exerting force (body2) [m].
Returns
Gravitational force exerted on body1 [N].
See also
computeGravitationalAcceleration.
Definition at line 60 of file centralGravityModel.cpp.
References computeGravitationalAcceleration().
computeGravitationalAccelerationDueToJ2()
Eigen::Vector3d tudat::gravitation::computeGravitationalAccelerationDueToJ2 (const Eigen::Vector3d & positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const double equatorialRadiusOfBodyExertingAcceleration, const double j2CoefficientOfGravityField, const Eigen::Vector3d & positionOfBodyExertingAcceleration)
Computes gravitational acceleration experienced by body1, due to its interaction with another body (body2) with an irregular gravity field. The body exerting the acceleration has an irregular gravity field. The acceleration due to the J2-coefficient is given by (Melman, 2012):
where is the gravitational parameter of the body exerting acceleration, , , and are the Cartesian position components, is the radial position, and is the second zonal coefficient of the gravity field of body2. The positions and accelerations are given with respect to an inertial (barycentric) reference frame.
Parameters
positionOfBodySubjectToAcceleration Position vector of body subject to J2-acceleration (body1) [m].
gravitationalParameterOfBodyExertingAcceleration Gravitational parameter of body exerting acceleration (body2) [m^3 s^-2].
equatorialRadiusOfBodyExertingAcceleration Equatorial radius of body exerting acceleration (body2), in formulation of spherical harmonics expansion [m].
j2CoefficientOfGravityField J2-coefficient, describing irregularity of the gravity field of body2 [-].
positionOfBodyExertingAcceleration Position vector of body exerting acceleration (body2) [m].
Returns
Gravitational acceleration exerted on body1 due to J2-effect [m s^-2].
Definition at line 23 of file centralJ2GravityModel.cpp.
References tudat::orbital_element_conversions::xCartesianPositionIndex, tudat::orbital_element_conversions::yCartesianPositionIndex, and tudat::orbital_element_conversions::zCartesianPositionIndex.
Referenced by computeGravitationalAccelerationZonalSum(), tudat::gravitation::CentralJ2GravitationalAccelerationModel::getAcceleration(), tudat::gravitation::CentralJ2J3GravitationalAccelerationModel::getAcceleration(), and tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::getAcceleration().
computeGravitationalAccelerationDueToJ3()
Eigen::Vector3d tudat::gravitation::computeGravitationalAccelerationDueToJ3 (const Eigen::Vector3d & positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const double equatorialRadiusOfBodyExertingAcceleration, const double j3CoefficientOfGravityField, const Eigen::Vector3d & positionOfBodyExertingAcceleration)
Computes gravitational acceleration experienced by body1, due to its interaction with another body (body2) with an irregular gravity field. The body exerting the acceleration has an irregular gravity field. The acceleration due to the J3-coefficient is given by (Melman, 2012):
where is the gravitational parameter of the body exerting acceleration, , , and are the Cartesian position components, is the radial position, and is the third zonal coefficient of the gravity field of body2. The positions and accelerations are given with respect to an inertial (barycentric) reference frame.
Parameters
positionOfBodySubjectToAcceleration Position vector of body subject to J3-acceleration (body1) [m].
gravitationalParameterOfBodyExertingAcceleration Gravitational parameter of body exerting acceleration (body2) [m^3 s^-2].
equatorialRadiusOfBodyExertingAcceleration Equatorial radius of body exerting acceleration (body2), in formulation of spherical harmonics expansion [m].
j3CoefficientOfGravityField J3-coefficient, describing irregularity of the gravity field of body2 [-].
positionOfBodyExertingAcceleration Position vector of body exerting acceleration (body2) [m].
Returns
Gravitational acceleration exerted on body1 due to J3-effect [m s^-2].
Definition at line 22 of file centralJ2J3GravityModel.cpp.
References tudat::orbital_element_conversions::xCartesianPositionIndex, tudat::orbital_element_conversions::yCartesianPositionIndex, and tudat::orbital_element_conversions::zCartesianPositionIndex.
Referenced by computeGravitationalAccelerationZonalSum(), tudat::gravitation::CentralJ2J3GravitationalAccelerationModel::getAcceleration(), and tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::getAcceleration().
computeGravitationalAccelerationDueToJ4()
Eigen::Vector3d tudat::gravitation::computeGravitationalAccelerationDueToJ4 (const Eigen::Vector3d & positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const double equatorialRadiusOfBodyExertingAcceleration, const double j4CoefficientOfGravityField, const Eigen::Vector3d & positionOfBodyExertingAcceleration)
Computes gravitational acceleration experienced by body1, due to its interaction with another body (body2) with an irregular gravity field. The body exerting the acceleration has an irregular gravity field. The acceleration due to the J4-coefficient is given by (Melman, 2012):
where is the gravitational parameter of the body exerting acceleration, , , and are the Cartesian position components, is the radial position, and is the fourth zonal coefficient of the gravity field of body2. The positions and accelerations are given with respect to an inertial (barycentric) reference frame.
Parameters
positionOfBodySubjectToAcceleration Position vector of body subject to J4-acceleration (body1) [m].
gravitationalParameterOfBodyExertingAcceleration Gravitational parameter of body exerting acceleration (body2) [m^3 s^-2].
equatorialRadiusOfBodyExertingAcceleration Equatorial radius of body exerting acceleration (body2), in formulation of spherical harmonics expansion [m].
j4CoefficientOfGravityField J4-coefficient, describing irregularity of the gravity field of body2 [-].
positionOfBodyExertingAcceleration Position vector of body exerting acceleration (body2) [m].
Returns
Gravitational acceleration exerted on body1 due to J4-effect [m s^-2].
Definition at line 25 of file centralJ2J3J4GravityModel.cpp.
References tudat::orbital_element_conversions::xCartesianPositionIndex, tudat::orbital_element_conversions::yCartesianPositionIndex, and tudat::orbital_element_conversions::zCartesianPositionIndex.
Referenced by computeGravitationalAccelerationZonalSum(), and tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::getAcceleration().
computeGravitationalAccelerationZonalSum()
Eigen::Vector3d tudat::gravitation::computeGravitationalAccelerationZonalSum (const Eigen::Vector3d & positionOfBodySubjectToAcceleration, const double gravitationalParameterOfBodyExertingAcceleration, const double equatorialRadiusOfBodyExertingAcceleration, const std::map< int, double > zonalCoefficientsOfGravityField, const Eigen::Vector3d & positionOfBodyExertingAcceleration)
Computes sum of gravitational acceleration for given zonal terms experienced by body1, due to its interaction with another body (body2) with an irregular gravity field. The body exerting the acceleration has an irregular gravity field. This function essentially serves as a wrapper to compute the total gravitational acceleration up to a certain zonal terms (specified as input parameter). So given as the maximum order of the zonal terms, the total acceleration is computed as:
where is the coefficient describing the irregularity of the gravity field of body2 due to the nth zonal term. All accelerations are given with respect to an inertial (barycentric) reference frame. NOTE: Currently, this algorithm only computes accelerations up to .
Parameters
positionOfBodySubjectToAcceleration Position vector of body subject to J4-acceleration (body1) [m].
gravitationalParameterOfBodyExertingAcceleration Gravitational parameter of body exerting acceleration (body2) [m^3 s^-2].
equatorialRadiusOfBodyExertingAcceleration Equatorial radius of body exerting acceleration (body2), in formulation of spherical harmonics expansion [m].
zonalCoefficientsOfGravityField Coefficients of zonal terms, describing irregularity of the gravity field of body2 [-]. The map key contains the degree, and the map value contains the coefficient value. At the moment, the only degrees supported are 2 (), 3 (), and 4 () etc. An error is thrown for any other values.
positionOfBodyExertingAcceleration Position vector of body exerting acceleration (body2) [m].
Returns
Total gravitational acceleration exerted on body1 due to given zonal terms [m s^-2].
Definition at line 71 of file centralJ2J3J4GravityModel.cpp.
References computeGravitationalAcceleration(), computeGravitationalAccelerationDueToJ2(), computeGravitationalAccelerationDueToJ3(), and computeGravitationalAccelerationDueToJ4().
computeDirectTidalAccelerationDueToTideOnPlanet()
Eigen::Vector3d tudat::gravitation::computeDirectTidalAccelerationDueToTideOnPlanet (const Eigen::Vector6d relativeStateOfBodyExertingTide, const Eigen::Vector3d planetAngularVelocityVector, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent = true)
Function to compute the acceleration acting on a satellite due to tidal deformation caused by this satellite on host planet. The computation is according to Lainey et al. (2007, 2009, 2012, etc.) and uses a single (degree 2) real Love number and a single time lag to include the dissipation in the host planet.
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
planetAngularVelocityVector Angular velocity vector ogf host planet
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
includeDirectRadialComponent True if term independent of time lag is to be included, false otherwise
Returns
Value of acceleration vector according to tidal model
Definition at line 23 of file directTidalDissipationAcceleration.cpp.
Referenced by tudat::gravitation::DirectTidalDissipationAcceleration::updateMembers().
computeDirectTidalAccelerationDueToTideOnSatellite()
Eigen::Vector3d tudat::gravitation::computeDirectTidalAccelerationDueToTideOnSatellite (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute the acceleration acting on a satellite due to tidal deformation caused in this satellite by host planet. The computation is according to Lainey et al. (2007, 2009, 2012, etc.) and uses a single (degree 2) real Love number and a single time lag to include the dissipation in the host planet.
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007), modified according to tide on satellite).
timeLag Time lag of tidal bulge
includeDirectRadialComponent True if term independent of time lag is to be included, false otherwise
Returns
Value of acceleration vector according to tidal model
Definition at line 43 of file directTidalDissipationAcceleration.cpp.
Referenced by tudat::gravitation::DirectTidalDissipationAcceleration::updateMembers().
getTidalDissipationAccelerationModels()
std::vector< std::shared_ptr< DirectTidalDissipationAcceleration > > tudat::gravitation::getTidalDissipationAccelerationModels (const basic_astrodynamics::AccelerationMap accelerationModelList, const std::string bodyBeingDeformed, const std::vector< std::string > & bodiesCausingDeformation)
Function to retrieve all DirectTidalDissipationAcceleration from an AccelerationMap, for specific deformed/deforming bodies
Parameters
accelerationModelList Total list of acceleration models for which DirectTidalDissipationAcceleration objects are to be retrieved
bodyBeingDeformed Name of body being deformed, for which DirectTidalDissipationAcceleration objects are to be retrieved
bodiesCausingDeformation List of bodies causing deformation, for which DirectTidalDissipationAcceleration objects are to be retrieved. If this list is empty, the selection is made only on the basis of the bodyBeingDeformed input.
Returns
All DirectTidalDissipationAcceleration from an accelerationModelList, for specific bodyBeingDeformed and bodiesCausingDeformation
Definition at line 62 of file directTidalDissipationAcceleration.cpp.
Referenced by tudat::simulation_setup::createDoubleParameterToEstimate().
getPredefinedCentralGravityField()
std::shared_ptr< GravityFieldModel > tudat::gravitation::getPredefinedCentralGravityField (BodiesWithPredefinedCentralGravityFields bodyWithPredefinedCentralGravityField)
Function to create a central gravity field model of one of the planets, moon or sun.
Function to create a central gravity field model of one of the planets, moon or sun.
Parameters
bodyWithPredefinedCentralGravityField Identified determining for which body a gravity field is to be created.
Returns
Central gravity field model of requested body.
Definition at line 21 of file gravityFieldModel.cpp.
References earth, jupiter, mars, mercury, moon, neptune, saturn, sun, uranus, and venus.
createInterpolatedSphericalHarmonicCorrectionFunctions()
std::function< void(const double, Eigen::MatrixXd&, Eigen::MatrixXd&) > tudat::gravitation::createInterpolatedSphericalHarmonicCorrectionFunctions (std::shared_ptr< GravityFieldVariations > variationObject, const double initialTime, const double finalTime, const double timeStep, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings)
Function to create a function linearly interpolating the sine and cosine correction coefficients produced by an object of GravityFieldVariations type.
Definition at line 123 of file gravityFieldVariations.cpp.
References tudat::gravitation::PairInterpolationInterface::getCosineSinePair().
computeJacobiEnergy()
double tudat::gravitation::computeJacobiEnergy (const double massParameter, const Eigen::VectorXd & stateInNormalizedUnits)
Returns the value of the Jacobi energy in normalized units of the CRTBP, given in the following equation (Wakker, 2007):
where is the Jacobi energy, and are Cartesian position coordinates of the third body, is the gravitational parameter of the secondary, and are the distances from the third body to the primaries, and is the magnitude of the velocity of the third body. This equation assumes that the system has been normalized such that the mean motion of the primiaries, and their mutual distance is equal to 1.
Parameters
massParameter Mass parameter of three-body system.
stateInNormalizedUnits State of third body in normalized units.
Returns
Jacobi energy in normalized units.
Definition at line 26 of file jacobiEnergy.cpp.
References tudat::orbital_element_conversions::xCartesianPositionIndex, tudat::orbital_element_conversions::xCartesianVelocityIndex, tudat::orbital_element_conversions::yCartesianPositionIndex, and tudat::orbital_element_conversions::zCartesianPositionIndex.
setDegreeAndOrderCoefficientToZero()
Eigen::MatrixXd tudat::gravitation::setDegreeAndOrderCoefficientToZero (const std::function< Eigen::MatrixXd() > originalCosineCoefficientFunction)
Function to manually remove the C(0,0) term from cosine coefficients, used by MutualSphericalHarmonicsGravitationalAccelerationModel. By using this function, the original function returning the sh coefficients is left untouched, not compromising the environment model, while the C(0,0) term is not calculated doubly by the MutualSphericalHarmonicsGravitationalAccelerationModel class.
Definition at line 19 of file mutualSphericalHarmonicGravityModel.cpp.
Referenced by tudat::gravitation::MutualSphericalHarmonicsGravitationalAccelerationModel::MutualSphericalHarmonicsGravitationalAccelerationModel().
calculateSecondDegreeGravitationalTorque()
Eigen::Vector3d tudat::gravitation::calculateSecondDegreeGravitationalTorque (const Eigen::Vector3d & relativePositionOfBodySubjectToTorque, const double gravitationalParameterOfAttractingBody, const Eigen::Matrix3d & inertiaTensorOfRotatingBody)
Function to calculate the gravitational torque exerted by a point mass on a body with degree two gravity field, which is provided here as an inertia tensor. Higher order terms of the torque are omitted.
Parameters
relativePositionOfBodySubjectToTorque Position of body exerting torque, w.r.t. body undergoing torque (typically expressed in frame fixed to body undergoing torque).
gravitationalParameterOfAttractingBody Tha gravitational parameter of the body that exerts the torque
inertiaTensorOfRotatingBody The inertia tensor of the body undergoing the torqie, in the same frame as relativePositionOfBodySubjectToTorque (typically frame fixed to body undergoing torque)
Returns
Gravitational torque of point mass on second-degree body.
Definition at line 20 of file secondDegreeGravitationalTorque.cpp.
Referenced by tudat::gravitation::SecondDegreeGravitationalTorqueModel::updateMembers().
calculateSphericalHarmonicGravitationalPotential()
double tudat::gravitation::calculateSphericalHarmonicGravitationalPotential (const Eigen::Vector3d & bodyFixedPosition, const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd & cosineCoefficients, const Eigen::MatrixXd & sineCoefficients, std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const int minimumumDegree = 0, const int minimumumOrder = 0)
Function to calculate the gravitational potential from a spherical harmonic field expansion.
Parameters
bodyFixedPosition Position of point at which potential is to be calculated wrt the massive body, in the frame in which the expansion is defined (typically body-fixed).
gravitationalParameter Gravitational parameter of massive body.
referenceRadius Reference radius of spherical harmonic field expansion.
cosineCoefficients Cosine spherical harmonic coefficients (geodesy normalized).
sineCoefficients Sine spherical harmonic coefficients (geodesy normalized).
sphericalHarmonicsCache Cache object containing current values of trigonometric funtions of latitude anf longitude, as well as legendre polynomials at current state.
minimumumDegree Maximum degree of spherical harmonic expansion.
minimumumOrder Maximum order of spherical harmonic expansion.
Returns
Gravitational potential at position defined by bodyFixedPosition
Definition at line 28 of file sphericalHarmonicsGravityField.cpp.
References tudat::basic_mathematics::computeGeodesyLegendrePolynomialFromCache(), tudat::coordinate_conversions::convertCartesianToSpherical(), tudat::mathematical_constants::PI, and tudat::basic_mathematics::LegendreCache::update().
Referenced by tudat::gravitation::SphericalHarmonicsGravityField::getGravitationalPotential().
computeGeodesyNormalizedGravitationalAccelerationSum()
Eigen::Vector3d tudat::gravitation::computeGeodesyNormalizedGravitationalAccelerationSum (const Eigen::Vector3d & positionOfBodySubjectToAcceleration, const double gravitationalParameter, const double equatorialRadius, const Eigen::MatrixXd & cosineHarmonicCoefficients, const Eigen::MatrixXd & sineHarmonicCoefficients, std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, std::map< std::pair< int, int >, Eigen::Vector3d > & accelerationPerTerm, const bool saveSeparateTerms = 0, const Eigen::Matrix3d & accelerationRotation = Eigen::Matrix3d::Identity())
This function computes the acceleration caused by gravitational spherical harmonics, with the coefficients expressed using a geodesy-normalization.
Compute gravitational acceleration due to multiple spherical harmonics terms, defined using geodesy-normalization.
This acceleration is the summation of all harmonic terms from degree and order zero, up to a user-specified highest degree and order. The harmonic coefficients for the function must be provided in geodesy-normalized format. This geodesy-normalization is defined as:
in which and are a geodesy-normalized cosine and sine harmonic coefficient respectively (of degree and order). The unnormalized harmonic coefficients are represented by and . The normalization factor is given by Heiskanen & Moritz [1967] as:
in which is the degree, is the order and is the Kronecker delta.
Parameters
positionOfBodySubjectToAcceleration Cartesian position vector with respect to the reference frame that is associated with the harmonic coefficients. The order is important! position(0) = x coordinate [m], position(1) = y coordinate [m], position(2) = z coordinate [m].
gravitationalParameter Gravitational parameter associated with the spherical harmonics [m^3 s^-2].
equatorialRadius Reference radius of the spherical harmonics [m].
cosineHarmonicCoefficients Matrix with geodesy-normalized cosine harmonic coefficients. The row index indicates the degree and the column index indicates the order of coefficients.
sineHarmonicCoefficients Matrix with geodesy-normalized sine harmonic coefficients. The row index indicates the degree and the column index indicates the order of coefficients. The matrix must be equal in size to cosineHarmonicCoefficients.
sphericalHarmonicsCache Cache object for computing/retrieving repeated terms in spherical harmonics potential gradient calculation.
accelerationPerTerm List of contributions to accelerations at given degrees/orders, represented by first/second entry of map key pair. List is returned by reference only if saveSeparateTerms is set to true.
saveSeparateTerms Boolean to denote whether the separate terms in the acceleration are to be stored term by term (in accelerationPerTerm map) by reference
accelerationRotation Rotation from body-fixed frame (in which coefficients are defined) to inertial frame.
Returns
Cartesian acceleration vector resulting from the summation of all harmonic terms. The order is important! acceleration(0) = x acceleration [m s^-2], acceleration(1) = y acceleration [m s^-2], acceleration(2) = z acceleration [m s^-2].
Definition at line 38 of file sphericalHarmonicsGravityModel.cpp.
References tudat::basic_mathematics::computePotentialGradient(), tudat::coordinate_conversions::convertCartesianToSpherical(), tudat::coordinate_conversions::getSphericalToCartesianGradientMatrix(), and tudat::mathematical_constants::PI.
Referenced by tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel::getAccelerationComponentsWithAlternativeCoefficients(), tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel::getAccelerationWithAlternativeCoefficients(), tudat::gravitation::SphericalHarmonicsGravityField::getGradientOfPotential(), and tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel::updateMembers().
computeSingleGeodesyNormalizedGravitationalAcceleration()
Eigen::Vector3d tudat::gravitation::computeSingleGeodesyNormalizedGravitationalAcceleration (const Eigen::Vector3d & positionOfBodySubjectToAcceleration, const double gravitationalParameter, const double equatorialRadius, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
This function computes the acceleration caused by a single gravitational spherical harmonics term, with the coefficients expressed using a geodesy-normalization. The harmonic coefficients for the function must be provided in geodesy-normalized format. This geodesy-normalization is defined as:
in which and are a geodesy-normalized cosine and sine harmonic coefficient respectively (of degree and order). The unnormalized harmonic coefficients are represented by and . The normalization factor is given by Heiskanen & Moritz [1967] as:
in which is the degree, is the order and is the Kronecker delta.
Parameters
positionOfBodySubjectToAcceleration Cartesian position vector with respect to the reference frame that is associated with the harmonic coefficients. The order is important! position(0) = x coordinate [m], position(1) = y coordinate [m], position(2) = z coordinate [m].
degree Degree of the harmonic term.
order Order of the harmonic term.
cosineHarmonicCoefficient Geodesy-normalized cosine harmonic coefficient.
sineHarmonicCoefficient Geodesy-normalized sine harmonic coefficient.
gravitationalParameter Gravitational parameter associated with the spherical harmonic [m^3 s^-2].
equatorialRadius Reference radius of the spherical harmonic [m].
sphericalHarmonicsCache Cache object for computing/retrieving repeated terms in spherical harmonics potential gradient calculation.
Returns
Cartesian acceleration vector resulting from the spherical harmonic term. The order is important! acceleration(0) = x acceleration [m s^-2], acceleration(1) = y acceleration [m s^-2], acceleration(2) = z acceleration [m s^-2].
Definition at line 131 of file sphericalHarmonicsGravityModel.cpp.
References tudat::basic_mathematics::computePotentialGradient(), tudat::coordinate_conversions::convertCartesianToSpherical(), tudat::coordinate_conversions::convertSphericalToCartesianGradient(), and tudat::mathematical_constants::PI.
computeThirdBodyPerturbingAcceleration()
Eigen::Vector3d tudat::gravitation::computeThirdBodyPerturbingAcceleration (const double gravitationalParameterOfPerturbingBody, const Eigen::Vector3d & positionOfPerturbingBody, const Eigen::Vector3d & positionOfAffectedBody, const Eigen::Vector3d & positionOfCentralBody = Eigen::Vector3d::Zero())
Computes the perturbing acceleration on a point mass in orbit about a central body (point mass), caused by a third body (point mass). This acceleration is expressed with respect to a pseudo-inertial reference frame centered at the central body body, i.e, a non-rotating frame aligned with an inertial reference frame. This acceleration may be summed with other third body accelerations in order to get the total gravitational perturbation acceleration of N bodies (Wakker, 2010; Montenbruck & Gill, 2005).
Parameters
gravitationalParameterOfPerturbingBody The gravitational parameter of the perturbing body, i.e., the third body. [m^3/s^2]
positionOfPerturbingBody The position of the third body, the body that causes the perturbations, in Cartesian coordinates. positionOfPerturbingBody(0) = x-position [m] positionOfPerturbingBody(1) = y-position [m] positionOfPerturbingBody(2) = z-position [m]
positionOfAffectedBody The position of the second body, the body that experiences the perturbation, in Cartesian coordinates. positionOfAffectedBody(0) = x-position [m] positionOfAffectedBody(1) = y-position [m] positionOfAffectedBody(2) = z-position [m]
positionOfCentralBody The position of the central body, the body w.r.t. which the acceleration is calculated the perturbation, in Cartesian coordinates (default=origin). positionOfAffectedBody(0) = x-position [m] positionOfAffectedBody(1) = y-position [m] positionOfAffectedBody(2) = z-position [m]
Returns
perturbingAcceleration The perturbing acceleration in Cartesian components, that gives the difference of the total acceleration with the central two-body acceleration. perturbingAcceleration(0) = x-acceleration [m/s^2] perturbingAcceleration(1) = y-acceleration [m/s^2] perturbingAcceleration(2) = z-acceleration [m/s^2]
Definition at line 25 of file thirdBodyPerturbation.cpp.
References computeGravitationalAcceleration().
calculateCosineTermForTriaxialEllipsoidSphericalHarmonicGravity()
double tudat::gravitation::calculateCosineTermForTriaxialEllipsoidSphericalHarmonicGravity (const double aSquaredMinusCSquared, const double bSquaredMinusCSquared, const double referenceRadius, const int degree, const int order)
Function to calculate (non-normalized) cosine spherical harmonic coefficient for a homogeneous triaxial ellipsoid
Function to calculate (non-normalized) cosine spherical harmonic coefficient for a homogeneous triaxial ellipsoid
X-axis is alligned with largest axis, y-axis with middle axis and z-axis with smallest axis
Parameters
aSquaredMinusCSquared Square of largest axis minus square of shortest axis
bSquaredMinusCSquared Square of middle axis minus square of shortest axis
referenceRadius Reference radius of spherical harmonic gravity field.
degree Degree of coefficient
order Order of coefficient
Returns
Spherical harmonic cosine coefficient (non-normalized) of triaxial ellipsoid at requested degree and order.
Definition at line 25 of file triAxialEllipsoidGravity.cpp.
Referenced by createTriAxialEllipsoidSphericalHarmonicCosineCoefficients().
calculateTriAxialEllipsoidReferenceRadius()
double tudat::gravitation::calculateTriAxialEllipsoidReferenceRadius (const double axisA, const double axisB, const double axisC)
Function to calculate triaxial ellipsoid reference radius of spherical harmonic expansion, per Balmino (1994)
Parameters
axisA Largest axis of triaxial ellipsoid
axisB Middle axis of triaxial ellipsoid
axisC Smallest axis of triaxial ellipsoid
Returns
Triaxial ellipsoid reference radius of spherical harmonic expansion
Definition at line 70 of file triAxialEllipsoidGravity.cpp.
Referenced by createTriAxialEllipsoidSphericalHarmonicCosineCoefficients().
calculateTriAxialEllipsoidVolume()
double tudat::gravitation::calculateTriAxialEllipsoidVolume (const double axisA, const double axisB, const double axisC)
Function to calculate triaxial ellipsoid volume
Parameters
axisA Largest axis of triaxial ellipsoid
axisB Middle axis of triaxial ellipsoid
axisC Smallest axis of triaxial ellipsoid
Returns
Volume of triaxial ellipsoid.
Definition at line 78 of file triAxialEllipsoidGravity.cpp.
References tudat::mathematical_constants::PI.
Referenced by tudat::simulation_setup::createHomogeneousTriAxialEllipsoidGravitySettings().
createTriAxialEllipsoidSphericalHarmonicCosineCoefficients()
Eigen::MatrixXd tudat::gravitation::createTriAxialEllipsoidSphericalHarmonicCosineCoefficients (const double axisA, const double axisB, const double axisC, const int maximumDegree, const int maximumOrder)
Function to calculate (non-normalized) cosine spherical harmonic coefficients for a homogeneous triaxial ellipsoid
Function to calculate (non-normalized) cosine spherical harmonic coefficients for a homogeneous triaxial ellipsoid
X-axis is aligned with largest axis, y-axis with middle axis and z-axis with smallest axis
Parameters
axisA Largest axis of triaxial ellipsoid
axisB Middle axis of triaxial ellipsoid
axisC Smallest axis of triaxial ellipsoid
maximumDegree Maximum degree of expansion
maximumOrder Maximum oredr of expansion
Returns
Spherical harmonic cosine coefficient matrix (non-normalized) of triaxial ellipsoid up to requested degree and order.
Definition at line 86 of file triAxialEllipsoidGravity.cpp.
References calculateCosineTermForTriaxialEllipsoidSphericalHarmonicGravity(), and calculateTriAxialEllipsoidReferenceRadius().
Referenced by createTriAxialEllipsoidSphericalHarmonicCoefficients().
createTriAxialEllipsoidSphericalHarmonicCoefficients()
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > tudat::gravitation::createTriAxialEllipsoidSphericalHarmonicCoefficients (const double axisA, const double axisB, const double axisC, const int maximumDegree, const int maximumOrder)
Function to calculate (non-normalized) cosine and sine spherical harmonic coefficients for a homogeneous triaxial ellipsoid
Function to calculate (non-normalized) cosine and sine spherical harmonic coefficients for a homogeneous triaxial ellipsoid
X-axis is alligned with largest axis, y-axis with middle axis and z-axis with smallest axis. Note that all sine coefficients are zero for all homogeneous triaxila ellipsoids (in given frame).
Parameters
axisA Largest axis of triaxial ellipsoid
axisB Middle axis of triaxial ellipsoid
axisC Smallest axis of triaxial ellipsoid
maximumDegree Maximum degree of expansion
maximumOrder Maximum oredr of expansion
Returns
Spherical harmonic cosine and coefficient matrix (non-normalized) pair of triaxial ellipsoid up to requested degree and order.
Definition at line 121 of file triAxialEllipsoidGravity.cpp.
References createTriAxialEllipsoidSphericalHarmonicCosineCoefficients().
Referenced by createTriAxialEllipsoidNormalizedSphericalHarmonicCoefficients().
createTriAxialEllipsoidNormalizedSphericalHarmonicCoefficients()
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > tudat::gravitation::createTriAxialEllipsoidNormalizedSphericalHarmonicCoefficients (const double axisA, const double axisB, const double axisC, const int maximumDegree, const int maximumOrder)
Function to calculate (normalized) cosine and sine spherical harmonic coefficients for a homogeneous triaxial ellipsoid
Function to calculate (normalized) cosine and sine spherical harmonic coefficients for a homogeneous triaxial ellipsoid
X-axis is alligned with largest axis, y-axis with middle axis and z-axis with smallest axis. Note that all sine coefficients are zero for all homogeneous triaxila ellipsoids (in given frame).
Parameters
axisA Largest axis of triaxial ellipsoid
axisB Middle axis of triaxial ellipsoid
axisC Smallest axis of triaxial ellipsoid
maximumDegree Maximum degree of expansion
maximumOrder Maximum oredr of expansion
Returns
Spherical harmonic cosine and coefficient matrix (normalized) pair of triaxial ellipsoid up to requested degree and order.
Definition at line 134 of file triAxialEllipsoidGravity.cpp.
References tudat::basic_mathematics::calculateLegendreGeodesyNormalizationFactor(), and createTriAxialEllipsoidSphericalHarmonicCoefficients().
Referenced by tudat::simulation_setup::createHomogeneousTriAxialEllipsoidGravitySettings().
to_json()
void tudat::gravitation::to_json (nlohmann::json & jsonObject, const BodyDeformationTypes & bodyDeformationType) inline
Definition at line 35 of file gravityFieldVariation.h.
References bodyDeformationTypes, and tudat::json_interface::stringFromEnum().
from_json()
void tudat::gravitation::from_json (const nlohmann::json & jsonObject, BodyDeformationTypes & bodyDeformationType) inline
Definition at line 41 of file gravityFieldVariation.h.
References bodyDeformationTypes, and tudat::json_interface::enumFromString().
Variable Documentation
createInterpolatedSphericalHarmonicCorrectionFunctions
std::function< void(const double, Eigen::MatrixXd&, Eigen::MatrixXd&) > tudat::gravitation::createInterpolatedSphericalHarmonicCorrectionFunctions(std::shared_ptr< GravityFieldVariations > variationObject, const double initialTime, const double finalTime, const double timeStep, const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings=std::make_shared< interpolators::InterpolatorSettings >(interpolators::linear_interpolator, interpolators::huntingAlgorithm))
Function to create a function linearly interpolating the sine and cosine correction coefficients produced by an object of GravityFieldVariations type.
The function creates a function pointer to the getCosineSinePair function of PairInterpolationInterface. The object of type PairInterpolationInterface is created by generating an interpolator for sine/cosine coefficients from the variationObject object and the initial/final time and time step that are passed.
Parameters
variationObject Object generating cosine and sine coefficient corrections.
initialTime Start time of interpolator.
finalTime End time of interpolator.
timeStep Time step between subsequent evaluations of coefficient corrections
Returns
Function pointer to function mimicing the addSphericalHarmonicsCorrections function of GravityFieldVariations.
Definition at line 326 of file gravityFieldVariations.h.
Referenced by tudat::gravitation::GravityFieldVariationsSet::getVariationFunctions().
bodyDeformationTypes
std::map< BodyDeformationTypes, std::string > tudat::gravitation::bodyDeformationTypes static
Initial value:
=
{
    { basic_solid_body, "basicSolidBody" },
    { tabulated_variation, "tabulatedVariation" }
}
Definition at line 25 of file gravityFieldVariation.h.
Referenced by from_json(), tudat::simulation_setup::from_json(), tudat::simulation_setup::to_json(), and to_json().
unsupportedBodyDeformationTypes
std::vector< BodyDeformationTypes > tudat::gravitation::unsupportedBodyDeformationTypes = { } static
Definition at line 32 of file gravityFieldVariation.h.
Referenced by tudat::simulation_setup::from_json(), and tudat::simulation_setup::to_json().