Tudat: tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType > Class Template Reference
tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType > Class Template Reference
Class for computing the state derivative for rotational dynamics of N bodies.
#include <rotationalMotionModifiedRodriguesParametersStateDerivative.h>
Public Member Functions
RotationalMotionModifiedRodriguesParametersStateDerivative (const basic_astrodynamics::TorqueModelMap &torqueModelsPerBody, const std::vector< std::string > &bodiesToPropagate, std::vector< std::function< Eigen::Matrix3d() > > bodyInertiaTensorFunctions, std::vector< std::function< Eigen::Matrix3d() > > bodyInertiaTensorTimeDerivativeFunctions=std::vector< std::function< Eigen::Matrix3d() > >())
Constructor.
~RotationalMotionModifiedRodriguesParametersStateDerivative ()
Destructor.
void calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative)
Calculates the state derivative of the rotational motion of the system.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &outputSolution, const TimeType &time)
Function to convert the state in the conventional form to the propagator-specific form.
void convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentLocalSolution)
Function to convert the propagator-specific form of the state to the conventional form.
bool isStateToBePostProcessed ()
Function to return whether the state needs to be post-processed.
void postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState)
Function to process the state during propagation.
Public Member Functions inherited from tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >
RotationalMotionStateDerivative (const basic_astrodynamics::TorqueModelMap &torqueModelsPerBody, const RotationalPropagatorType propagatorType, const std::vector< std::string > &bodiesToPropagate, std::vector< std::function< Eigen::Matrix3d() > > bodyInertiaTensorFunctions, std::vector< std::function< Eigen::Matrix3d() > > bodyInertiaTensorTimeDerivativeFunctions=std::vector< std::function< Eigen::Matrix3d() > >())
Constructor.
virtual ~RotationalMotionStateDerivative ()
Destructor.
virtual void clearDerivedRotationalStateDerivativeModel ()
Function to clear any reference/cached values of state derivative model.
void clearRotationalStateDerivativeModel ()
Function to clear reference/cached values of acceleration models.
void clearStateDerivativeModel ()
Function to clear reference/cached values of translational state derivative model.
void convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentRotationalState)
Function to convert the propagator-specific form of the state to the conventional form in the global frame.
std::vector< std::string > getBodiesToBeIntegratedNumerically ()
Function to get list of names of bodies that are to be integrated numerically.
int getConventionalStateSize ()
Function to return the size of the state handled by the object.
RotationalPropagatorType getRotationalPropagatorType ()
Function to get type of propagator that is to be used (i.e., quaternions, etc.).
basic_astrodynamics::TorqueModelMap getTorquesMap ()
Function to get map of torques acting on each body.
Eigen::Vector3d getTotalTorqueForBody (const std::string &bodyName)
Function to get total torque acting on specific body.
void updateStateDerivativeModel (const TimeType currentTime)
Function to update the state derivative model to the current time.
Public Member Functions inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
SingleStateTypeDerivative (const IntegratedStateType integratedStateType)
Constructor.
virtual ~SingleStateTypeDerivative ()
Virtual destructor.
IntegratedStateType getIntegratedStateType ()
Function to return the type of dynamics for which the state derivative is calculated.
virtual int getPropagatedStateSize ()
Function to return the size of the propagated state handled by the object.
virtual void postProcessState (Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &unprocessedState)
Additional Inherited Members
Protected Member Functions inherited from tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >
std::vector< Eigen::Vector3d > sumTorquesPerBody ()
Function to get the total torques acting on each body, expressed in the body-fixed frames.
Protected Attributes inherited from tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >
std::vector< std::string > bodiesToPropagate_
List of names of bodies for which rotational state is to be propagated.
std::vector< std::function< Eigen::Matrix3d() > > bodyInertiaTensorFunctions_
List of functions returning inertia tensors of bodiesToPropagate (in same order)
std::vector< std::function< Eigen::Matrix3d() > > bodyInertiaTensorTimeDerivativeFunctions_
List of functions returning time derivatives of inertia tensors of bodiesToPropagate (in same order)
basic_astrodynamics::SingleBodyTorqueModelMap::iterator innerTorqueIterator
Predefined iterator to save (de-)allocation time.
RotationalPropagatorType propagatorType_
Type of propagator that is to be used (i.e., quaternions, etc.)
basic_astrodynamics::TorqueModelMap::iterator torqueModelMapIterator
Predefined iterator to save (de-)allocation time.
basic_astrodynamics::TorqueModelMap torqueModelsPerBody_
A map containing the list of torques acting on each body,.
Protected Attributes inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
IntegratedStateType integratedStateType_
Type of dynamics for which the state derivative is calculated.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > unprocessedState_
Vector used during post-processing of state.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >
Class for computing the state derivative for rotational dynamics of N bodies, using modified Rodrigues parameters from body-fixed to inertial frame (in modified Rodrigues parameters format) and angular velocity-vector of body expressed in body-fixed frame as the rotational state of a single body
Definition at line 43 of file rotationalMotionModifiedRodriguesParametersStateDerivative.h.
Constructor & Destructor Documentation
RotationalMotionModifiedRodriguesParametersStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::RotationalMotionModifiedRodriguesParametersStateDerivative (const basic_astrodynamics::TorqueModelMap & torqueModelsPerBody, const std::vector< std::string > & bodiesToPropagate, std::vector< std::function< Eigen::Matrix3d() > > bodyInertiaTensorFunctions, std::vector< std::function< Eigen::Matrix3d() > > bodyInertiaTensorTimeDerivativeFunctions = std::vector< std::function< Eigen::Matrix3d() > >()) inline
Constructor.
Parameters
torqueModelsPerBody List of torque models (first map key body undergoing acceleration, second map key body exerting acceleration).
bodiesToPropagate List of names of bodies for which rotational state is to be propagated.
bodyInertiaTensorFunctions List of functions returning inertia tensors of bodiesToPropagate (in same order).
bodyInertiaTensorTimeDerivativeFunctions List of functions returning time derivatives of inertia tensors of bodiesToPropagate (in same order). Default empty, denoting time-invariant inertia tensors.
Definition at line 57 of file rotationalMotionModifiedRodriguesParametersStateDerivative.h.
~RotationalMotionModifiedRodriguesParametersStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::~RotationalMotionModifiedRodriguesParametersStateDerivative () inline
Definition at line 69 of file rotationalMotionModifiedRodriguesParametersStateDerivative.h.
Member Function Documentation
calculateSystemStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative) inline virtual
Calculates the state derivative of the rotational motion of the system at the given time and rotational state.
Parameters
time Time (seconds since reference epoch) at which the system is to be updated.
stateOfSystemToBeIntegrated List of 7 * bodiesToPropagate_.size(), containing rotation modified Rodrigues parameters and angular velocity of the bodies being propagated. The order of the values is defined by the order of bodies in bodiesToPropagate_.
stateDerivative Current state derivative (modified Rodrigues parameters rate + angular acceleration) of system of bodies integrated numerically (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 81 of file rotationalMotionModifiedRodriguesParametersStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodyInertiaTensorFunctions_, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodyInertiaTensorTimeDerivativeFunctions_, tudat::propagators::calculateModifiedRodriguesParametersDerivative(), tudat::propagators::evaluateRotationalEquationsOfMotion(), and tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::sumTorquesPerBody().
convertFromOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & outputSolution, const TimeType & time) inline virtual
Function to convert the state in the conventional form to the propagator-specific form.
Parameters
outputSolution State in 'conventional form'.
time Current time at which the state is valid (not used in this class).
Returns
State (outputSolution), converted to the 'propagator-specific form'.
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 112 of file rotationalMotionModifiedRodriguesParametersStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_, tudat::orbital_element_conversions::convertQuaternionsToModifiedRodriguesParameterElements(), and tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getPropagatedStateSize().
convertToOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentLocalSolution) inline virtual
Function to convert the propagator-specific form of the state to the conventional form.
Parameters
internalSolution State in propagator-specific form.
time Current time at which the state is valid (not used in this class).
currentLocalSolution State (internalSolution), converted to the 'conventional form' (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 137 of file rotationalMotionModifiedRodriguesParametersStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_, and tudat::orbital_element_conversions::convertModifiedRodriguesParametersToQuaternionElements().
postProcessState()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState) inline virtual
Function to process the state during propagation. For modified Rodrigues parameters (MRP), this function converts to/from shadow modified Rodrigues parameters (SMRP), in case the magnitude of the (S)MRP vector is larger than 1.0.
Parameters
unprocessedState State computed after propagation.
Returns
Processed state (returned by reference).
Reimplemented from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 158 of file rotationalMotionModifiedRodriguesParametersStateDerivative.h.
References tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::bodiesToPropagate_.
isStateToBePostProcessed()
template<typename StateScalarType = double, typename TimeType = double> bool tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::isStateToBePostProcessed () inline virtual
Function to return whether the state needs to be post-processed. For (shadow) modified Rodrigues parameters this is true.
Returns
Boolean confirming that the state needs to be post-processed.
Reimplemented from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 189 of file rotationalMotionModifiedRodriguesParametersStateDerivative.h.
The documentation for this class was generated from the following file:
Astrodynamics/Propagators/rotationalMotionModifiedRodriguesParametersStateDerivative.h