Tudat: tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType > Class Template Reference
tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType > Class Template Reference
Class for managing JSON-based simulations.
#include <jsonInterface.h>
Public Member Functions
JsonSimulationManager (const std::string &inputFilePath, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())
Constructor from JSON file.
JsonSimulationManager (const nlohmann::json &jsonObject, const std::chrono::steady_clock::time_point initialClockTime=std::chrono::steady_clock::now())
Constructor from JSON object.
virtual ~JsonSimulationManager ()
void addBody (const std::string &bodyName)
Add a body named bodyName.
nlohmann::json at (const std::string &key) const
void exportAsJson (const boost::filesystem::path &exportPath, const unsigned int tabSize=2)
Export this as a json object to the file exportPath.
virtual void exportResults ()
Export the results of the dynamics simulation according to the export settings.
std::shared_ptr< ApplicationOptions > getApplicationOptions () const
Get application options.
nlohmann::json getAsJson ()
Export this as a json object.
std::shared_ptr< simulation_setup::Body > getBody (const std::string &bodyName) const
Get body named bodyName.
simulation_setup::NamedBodyMap getBodyMap () const
Get body map.
std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > getBodySettingsMap () const
Get map of body settings.
std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > getDynamicsSimulator () const
Get dynamics simulator.
TimeType getEndEpoch () const
Get maximum simulation end epoch. Returns TUDAT_NAN if there is no time termination condition.
std::shared_ptr< ExportSettings > getExportSettings (const unsigned int index) const
Get export settings at index.
std::vector< std::shared_ptr< ExportSettings > > getExportSettingsVector () const
Get vector of export settings (each element corresponds to an output file).
std::string getGlobalFrameOrientation () const
Get global frame orientation.
std::string getGlobalFrameOrigin () const
Get global frame origin.
std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > getIntegratorSettings () const
Get integrator settings.
nlohmann::json getJsonObject () const
Get the JSON object.
nlohmann::json getOriginalJsonObject () const
Get original JSON object (defined at construction or last time setInputFile was called).
std::shared_ptr< propagators::MultiTypePropagatorSettings< StateScalarType > > getPropagatorSettings () const
Get propagator settings.
std::shared_ptr< SpiceSettings > getSpiceSettings () const
Get Spice settings (nullptr if Spice is not used).
TimeType getStartEpoch () const
Get simulation start epoch.
nlohmann::json & operator[] (const std::string &key)
void resetInputFile (const std::string &inputFilePath)
Reset the root JSON input file.
void resetJsonObject (const nlohmann::json &jsonObject)
Reset the json object.
virtual void runPropagation ()
Run the propagation.
virtual void updateSettings ()
Update all the settings (objects) from the JSON object.
Protected Member Functions
virtual void resetApplicationOptions ()
Reset applicationOptions_ from the current jsonObject_.
virtual void resetBodies ()
Reset bodySettingsMap_ and bodyMap_ from the current jsonObject_.
virtual void resetDynamicsSimulator ()
Reset dynamicsSimulator_ for the current bodyMap_, integratorSettings_ and propagatorSettings_.
virtual void resetExportSettings ()
Reset exportSettingsVector_ from the current jsonObject_.
virtual void resetIntegratorSettings ()
Reset integratorSettings_ from the current jsonObject_.
virtual void resetPropagatorSettings ()
Reset propagatorSettings_ from the current jsonObject_.
virtual void resetSpice ()
Reset spiceSettings_ from the current jsonObject_.
Protected Attributes
std::shared_ptr< ApplicationOptions > applicationOptions_
Application options.
simulation_setup::NamedBodyMap bodyMap_
Body map.
std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > bodySettingsMap_
Map of body settings.
std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > dynamicsSimulator_
Dynamics simulator.
std::vector< std::shared_ptr< ExportSettings > > exportSettingsVector_
Vector of export settings (each element corresponds to an output file).
std::string globalFrameOrientation_
Global frame orientation.
std::string globalFrameOrigin_
Global frame origin.
std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings_
Integrator settings.
std::shared_ptr< propagators::MultiTypePropagatorSettings< StateScalarType > > propagatorSettings_
Propagation settings.
std::shared_ptr< SpiceSettings > spiceSettings_
Spice settings (nullptr if Spice is not used).
Private Member Functions
void updateJsonObjectFromSettings ()
Update the JSON object with all the data from the current settings (objests).
Private Attributes
std::chrono::steady_clock::time_point initialClockTime_
Absolute path to the input file.
boost::filesystem::path inputFilePath_
Absolute path to the input file.
nlohmann::json jsonObject_
JSON object with the current settings.
nlohmann::json originalJsonObject_
Original JSON object with all the settings read directly from the input file.
bool profiling = false
Detailed Description
template<typename TimeType = double, typename StateScalarType = double>
class tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >
Definition at line 34 of file jsonInterface.h.
Constructor & Destructor Documentation
JsonSimulationManager() [1/2]
template<typename TimeType = double, typename StateScalarType = double> tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::JsonSimulationManager (const std::string & inputFilePath, const std::chrono::steady_clock::time_point initialClockTime = std::chrono::steady_clock::now()) inline
Constructor.
Parameters
inputFilePath Path to the root JSON input file. Can be absolute or relative (to the working directory).
initialClockTime Initial clock time from which the cumulative CPU time during the propagation will be computed. Default is the moment at which the constructor was called.
Definition at line 47 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetInputFile().
JsonSimulationManager() [2/2]
template<typename TimeType = double, typename StateScalarType = double> tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::JsonSimulationManager (const nlohmann::json & jsonObject, const std::chrono::steady_clock::time_point initialClockTime = std::chrono::steady_clock::now()) inline
Constructor.
Parameters
jsonObject The root JSON object.
initialClockTime Initial clock time from which the cumulative CPU time during the propagation will be computed. Default is the moment at which the constructor was called.
Definition at line 62 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetJsonObject().
~JsonSimulationManager()
template<typename TimeType = double, typename StateScalarType = double> virtual tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::~JsonSimulationManager () inline virtual
Definition at line 70 of file jsonInterface.h.
Member Function Documentation
resetInputFile()
template<typename TimeType = double, typename StateScalarType = double> void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetInputFile (const std::string & inputFilePath) inline
Reset the root JSON input file.
Parameters
inputFilePath Path to the root JSON input file. Can be absolute or relative (to the working directory).
Definition at line 77 of file jsonInterface.h.
References tudat::json_interface::getDeserializedJSON(), tudat::json_interface::getPathForJSONFile(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::inputFilePath_, and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetJsonObject().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::JsonSimulationManager().
resetJsonObject()
template<typename TimeType = double, typename StateScalarType = double> void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetJsonObject (const nlohmann::json & jsonObject) inline
Reset the json object.
Parameters
jsonObject The new json object to be used for creating the simulation settings.
Definition at line 89 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::originalJsonObject_.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::JsonSimulationManager(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetInputFile().
updateSettings()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings () inline virtual
Definition at line 96 of file jsonInterface.h.
References tudat::json_interface::clearAccessHistory(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetApplicationOptions(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetDynamicsSimulator(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetExportSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetIntegratorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetSpice().
Referenced by main().
runPropagation()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation () inline virtual
Run the propagation.
Before running the simulation, the JSON representation of this will be exported if requested in applicationOptions_, and a message will be printed if requested in applicationOptions_.
If some of the keys in jsonObject_ haven't been used, a message may be printed or an error may be thrown depending on applicationOptions_.
After running the simulation, a message will be printed if requested in applicationOptions_.
Definition at line 129 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::applicationOptions_, tudat::json_interface::checkUnusedKeys(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::dynamicsSimulator_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportAsJson(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::inputFilePath_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_.
Referenced by main().
exportResults()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults () inline virtual
Export the results of the dynamics simulation according to the export settings.
Definition at line 183 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::applicationOptions_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::dynamicsSimulator_, tudat::json_interface::exportResultsOfDynamicsSimulator(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportSettingsVector_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling.
Referenced by main().
getAsJson()
template<typename TimeType = double, typename StateScalarType = double> nlohmann::json tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getAsJson () inline
Export this as a json object.
Returns
JSON representation of this.
Definition at line 210 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateJsonObjectFromSettings().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportAsJson().
exportAsJson()
template<typename TimeType = double, typename StateScalarType = double> void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportAsJson (const boost::filesystem::path & exportPath, const unsigned int tabSize = 2) inline
Export this as a json object to the file exportPath.
Parameters
exportPath Path to which the contents of the JSON object are to be exported.
tabSize Size of tabulations in the exported file (default = 2, i.e. 2 spaces). If set to 0, no indentantion or line breaks will be used, so the exported file will contain just one line.
Definition at line 223 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getAsJson().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation().
getOriginalJsonObject()
template<typename TimeType = double, typename StateScalarType = double> nlohmann::json tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getOriginalJsonObject () const inline
Get original JSON object (defined at construction or last time setInputFile was called).
Remarks
The returned JSON object is the result of combining all the JSON files that may be included in the root JSON file into one single object containing all the settings, but before default values have been loaded or unit conversions have been applied.
Returns
The original JSON object.
Definition at line 242 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::originalJsonObject_.
getJsonObject()
template<typename TimeType = double, typename StateScalarType = double> nlohmann::json tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getJsonObject () const inline
Get the JSON object.
Remarks
The returned JSON object is the result of combining all the JSON files that may be included in the root JSON file into one single object containing all the settings.
Returns
The JSON object.
Definition at line 254 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_.
at()
template<typename TimeType = double, typename StateScalarType = double> nlohmann::json tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::at (const std::string & key) const inline
Definition at line 259 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, and tudat::json_interface::valueAt().
operator[]()
template<typename TimeType = double, typename StateScalarType = double> nlohmann::json& tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::operator[] (const std::string & key) inline
Definition at line 264 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, and tudat::json_interface::valueAt().
getStartEpoch()
template<typename TimeType = double, typename StateScalarType = double> TimeType tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getStartEpoch () const inline
Definition at line 270 of file jsonInterface.h.
References tudat::json_interface::Keys::initialEpoch, tudat::json_interface::Keys::Integrator::initialTime, tudat::json_interface::Keys::integrator, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::integratorSettings_, and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_.
getEndEpoch()
template<typename TimeType = double, typename StateScalarType = double> TimeType tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getEndEpoch () const inline
Definition at line 284 of file jsonInterface.h.
References tudat::json_interface::Keys::finalEpoch, tudat::json_interface::isNaN(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_, and TUDAT_NAN.
getIntegratorSettings()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getIntegratorSettings () const inline
Definition at line 298 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::integratorSettings_.
getSpiceSettings()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< SpiceSettings > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getSpiceSettings () const inline
Definition at line 304 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::spiceSettings_.
getGlobalFrameOrigin()
template<typename TimeType = double, typename StateScalarType = double> std::string tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getGlobalFrameOrigin () const inline
Definition at line 310 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::globalFrameOrigin_.
getGlobalFrameOrientation()
template<typename TimeType = double, typename StateScalarType = double> std::string tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getGlobalFrameOrientation () const inline
Definition at line 316 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::globalFrameOrientation_.
getBodySettingsMap()
template<typename TimeType = double, typename StateScalarType = double> std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getBodySettingsMap () const inline
Definition at line 322 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodySettingsMap_.
getBodyMap()
template<typename TimeType = double, typename StateScalarType = double> simulation_setup::NamedBodyMap tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getBodyMap () const inline
Definition at line 328 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_.
addBody()
template<typename TimeType = double, typename StateScalarType = double> void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::addBody (const std::string & bodyName) inline
Definition at line 334 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_.
getBody()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< simulation_setup::Body > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getBody (const std::string & bodyName) const inline
Definition at line 340 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_.
getPropagatorSettings()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< propagators::MultiTypePropagatorSettings< StateScalarType > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getPropagatorSettings () const inline
Definition at line 346 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_.
getExportSettingsVector()
template<typename TimeType = double, typename StateScalarType = double> std::vector< std::shared_ptr< ExportSettings > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getExportSettingsVector () const inline
Definition at line 352 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportSettingsVector_.
getExportSettings()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< ExportSettings > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getExportSettings (const unsigned int index) const inline
Definition at line 358 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportSettingsVector_.
getApplicationOptions()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< ApplicationOptions > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getApplicationOptions () const inline
Definition at line 364 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::applicationOptions_.
getDynamicsSimulator()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getDynamicsSimulator () const inline
Definition at line 370 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::dynamicsSimulator_.
resetIntegratorSettings()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetIntegratorSettings () inline protected virtual
Reset integratorSettings_ from the current jsonObject_.
Definition at line 382 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::Keys::integrator, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::integratorSettings_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, and tudat::json_interface::updateFromJSON().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
resetSpice()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetSpice () inline protected virtual
Reset spiceSettings_ from the current jsonObject_. Loads the requested kernels in Tudat (if any).
Definition at line 399 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::loadSpiceKernels(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, tudat::json_interface::Keys::spice, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::spiceSettings_, and tudat::json_interface::updateFromJSONIfDefined().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
resetBodies()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies () inline protected virtual
Reset bodySettingsMap_ and bodyMap_ from the current jsonObject_.
Definition at line 417 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodySettingsMap_, tudat::json_interface::Keys::globalFrameOrientation, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::globalFrameOrientation_, tudat::json_interface::Keys::globalFrameOrigin, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::globalFrameOrigin_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::integratorSettings_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::spiceSettings_, and tudat::json_interface::updateBodiesFromJSON().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
resetExportSettings()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetExportSettings () inline protected virtual
Reset exportSettingsVector_ from the current jsonObject_.
Definition at line 436 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportSettingsVector_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, tudat::json_interface::updateFromJSONIfDefined(), and tudat::json_interface::Keys::xport.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
resetPropagatorSettings()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings () inline protected virtual
Reset propagatorSettings_ from the current jsonObject_. Tries to infer the initial states from the body ephemeris if not provided. Creates the integrated state models using bodyMap_
Definition at line 455 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportSettingsVector_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::integratorSettings_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_, tudat::json_interface::resetDependentVariableSaveSettings(), and tudat::json_interface::updateFromJSON().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
resetApplicationOptions()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetApplicationOptions () inline protected virtual
Reset applicationOptions_ from the current jsonObject_.
Definition at line 504 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::applicationOptions_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_, tudat::json_interface::Keys::options, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, and tudat::json_interface::updateFromJSONIfDefined().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
resetDynamicsSimulator()
template<typename TimeType = double, typename StateScalarType = double> virtual void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetDynamicsSimulator () inline protected virtual
Reset dynamicsSimulator_ for the current bodyMap_, integratorSettings_ and propagatorSettings_.
Definition at line 521 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::dynamicsSimulator_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::integratorSettings_, tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling, and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
updateJsonObjectFromSettings()
template<typename TimeType = double, typename StateScalarType = double> void tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateJsonObjectFromSettings () inline private
Definition at line 570 of file jsonInterface.h.
References tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getAsJson().
Member Data Documentation
profiling
template<typename TimeType = double, typename StateScalarType = double> bool tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::profiling = false private
Definition at line 37 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetApplicationOptions(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetDynamicsSimulator(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetExportSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetIntegratorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetSpice(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
integratorSettings_
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::integratorSettings_ protected
Definition at line 537 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getIntegratorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getStartEpoch(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetDynamicsSimulator(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetIntegratorSettings(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings().
spiceSettings_
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< SpiceSettings > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::spiceSettings_ protected
Definition at line 540 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getSpiceSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetSpice().
globalFrameOrigin_
template<typename TimeType = double, typename StateScalarType = double> std::string tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::globalFrameOrigin_ protected
Definition at line 543 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getGlobalFrameOrigin(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies().
globalFrameOrientation_
template<typename TimeType = double, typename StateScalarType = double> std::string tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::globalFrameOrientation_ protected
Definition at line 546 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getGlobalFrameOrientation(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies().
bodySettingsMap_
template<typename TimeType = double, typename StateScalarType = double> std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodySettingsMap_ protected
Definition at line 549 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getBodySettingsMap(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies().
bodyMap_
template<typename TimeType = double, typename StateScalarType = double> simulation_setup::NamedBodyMap tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::bodyMap_ protected
Definition at line 552 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::addBody(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getBody(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getBodyMap(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetDynamicsSimulator(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings().
propagatorSettings_
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< propagators::MultiTypePropagatorSettings< StateScalarType > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::propagatorSettings_ protected
Definition at line 555 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getEndEpoch(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getPropagatorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetDynamicsSimulator(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation().
exportSettingsVector_
template<typename TimeType = double, typename StateScalarType = double> std::vector< std::shared_ptr< ExportSettings > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportSettingsVector_ protected
Definition at line 558 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getExportSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getExportSettingsVector(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetExportSettings(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings().
applicationOptions_
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< ApplicationOptions > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::applicationOptions_ protected
Definition at line 561 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getApplicationOptions(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetApplicationOptions(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation().
dynamicsSimulator_
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::dynamicsSimulator_ protected
Definition at line 564 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getDynamicsSimulator(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetDynamicsSimulator(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation().
initialClockTime_
template<typename TimeType = double, typename StateScalarType = double> std::chrono::steady_clock::time_point tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::initialClockTime_ private
Definition at line 576 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetApplicationOptions(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetDynamicsSimulator(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetExportSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetIntegratorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetSpice(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
inputFilePath_
template<typename TimeType = double, typename StateScalarType = double> boost::filesystem::path tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::inputFilePath_ private
Definition at line 579 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetInputFile(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation().
originalJsonObject_
template<typename TimeType = double, typename StateScalarType = double> nlohmann::json tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::originalJsonObject_ private
Definition at line 582 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getOriginalJsonObject(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetJsonObject().
jsonObject_
template<typename TimeType = double, typename StateScalarType = double> nlohmann::json tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::jsonObject_ private
Definition at line 585 of file jsonInterface.h.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::at(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getAsJson(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getEndEpoch(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getJsonObject(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getStartEpoch(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::operator[](), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetApplicationOptions(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetExportSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetIntegratorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetJsonObject(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetSpice(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateJsonObjectFromSettings().
The documentation for this class was generated from the following file:
JsonInterface/jsonInterface.h