Tudat: tudat::aerodynamics::FlightConditions Class Reference
tudat::aerodynamics::FlightConditions Class Reference
Class for calculating aerodynamic flight characteristics of a vehicle during numerical integration.
#include <flightConditions.h>
Public Member Functions
FlightConditions (const boost::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel, const boost::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel, const boost::shared_ptr< AerodynamicCoefficientInterface > aerodynamicCoefficientInterface, const boost::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator=boost::shared_ptr< reference_frames::AerodynamicAngleCalculator >(), const boost::function< double(const std::string &)> controlSurfaceDeflectionFunction=boost::function< double(const std::string &)>())
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
boost::shared_ptr< reference_frames::AerodynamicAngleCalculator > getAerodynamicAngleCalculator ()
Function to return aerodynamic angle calculator object.
std::vector< double > getAerodynamicCoefficientIndependentVariables ()
Function to return list of independent variables of the aerodynamic coefficient interface.
boost::shared_ptr< AerodynamicCoefficientInterface > getAerodynamicCoefficientInterface ()
Function to return object from which the aerodynamic coefficients are obtained.
boost::shared_ptr< aerodynamics::AtmosphereModel > getAtmosphereModel () const
Function to return atmosphere model object.
std::map< std::string, std::vector< double > > getControlSurfaceAerodynamicCoefficientIndependentVariables ()
Function to return list of independent variables of the control surface aerodynamic coefficient interface.
double getCurrentAirspeed ()
Function to retrieve (and compute if necessary) the current airspeed.
Eigen::Vector3d getCurrentAirspeedBasedVelocity ()
Function to return current central body-fixed velocity of vehicle.
double getCurrentAltitude ()
Function to retrieve (and compute if necessary) the current altitude.
Eigen::Vector6d getCurrentBodyCenteredBodyFixedState ()
Function to return current central body-fixed state of vehicle.
double getCurrentDensity ()
Function to retrieve (and compute if necessary) the current freestream density.
double getCurrentDynamicPressure ()
Function to retrieve (and compute if necessary) the current freestream dynamic pressure.
double getCurrentFreestreamTemperature ()
Function to retrieve (and compute if necessary) the current freestream temperature.
double getCurrentGeodeticLatitude ()
Function to retrieve (and compute if necessary) the current geodetic latitude.
double getCurrentMachNumber ()
Function to retrieve (and compute if necessary) the current Mach number.
double getCurrentPressure ()
Function to retrieve (and compute if necessary) the current freestream pressure.
double getCurrentSpeedOfSound ()
Function to retrieve (and compute if necessary) the current speed of sound.
double getCurrentTime ()
Function to return the current time of the FlightConditions.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the flight conditions.
void setAerodynamicAngleCalculator (const boost::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Function to (re)set aerodynamic angle calculator object.
void setAerodynamicCoefficientsIndependentVariableFunction (const AerodynamicCoefficientsIndependentVariables independentVariable, const boost::function< double() > coefficientDependency)
Function to set custom dependency of aerodynamic coefficients.
void updateConditions (const double currentTime)
Function to update all flight conditions.
Private Types
enum FlightConditionVariables {
altitude_flight_condition, density_flight_condition, pressure_flight_condition, temperature_flight_condition,
latitude_flight_condition, longitude_flight_condition, mach_number_flight_condition, speed_of_sound_flight_condition,
airspeed_flight_condition, geodetic_latitude_condition, dynamic_pressure_condition
}
List of variables that can be computed by flight condition.
Private Member Functions
void computeAirspeed ()
Function to compute and set the current airspeed.
void computeAltitude ()
Function to compute and set the current altitude.
void computeDensity ()
Function to compute and set the current freestream density.
void computeDynamicPressure ()
Function to compute and set the current freestream dynamic pressure.
void computeFreestreamPressure ()
Function to compute and set the current freestream pressure.
void computeGeodeticLatitude ()
Function to compute and set the current geodetic latitude.
void computeLatitudeAndLongitude ()
Function to compute and set the current latitude and longitude.
void computeMachNumber ()
Function to compute and set the current Mach number.
void computeSpeedOfSound ()
Function to compute and set the current speed of sound.
void computeTemperature ()
Function to compute and set the current freestream temperature.
double getAerodynamicCoefficientIndependentVariable (const AerodynamicCoefficientsIndependentVariables independentVariableType, const std::string &secondaryIdentifier="")
Function to (compute and) retrieve the value of an independent variable of aerodynamic coefficients.
void updateAerodynamicCoefficientInput ()
Function to update the independent variables of the aerodynamic coefficient interface.
void updateAtmosphereInput ()
Function to update input to atmosphere model (altitude, as well as latitude and longitude if needed).
Private Attributes
boost::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator_
Object from which the aerodynamic/trajectory angles of the vehicle are calculated.
std::vector< double > aerodynamicCoefficientIndependentVariables_
Current list of independent variables of the aerodynamic coefficient interface.
boost::shared_ptr< AerodynamicCoefficientInterface > aerodynamicCoefficientInterface_
Object from which the aerodynamic coefficients are obtained.
boost::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel_
Atmosphere model of atmosphere through which vehicle is flying.
boost::function< Eigen::Vector6d() > bodyCenteredPseudoBodyFixedStateFunction_
Function to return the current state of the vehicle in a body-fixed frame.
std::string centralBody_
Name of central body (i.e. body with the atmosphere)
std::map< std::string, std::vector< double > > controlSurfaceAerodynamicCoefficientIndependentVariables_
boost::function< double(const std::string &) > controlSurfaceDeflectionFunction_
Function returning control surface deflection, with input the control surface identifier.
Eigen::Vector6d currentBodyCenteredAirspeedBasedBodyFixedState_
Current state of vehicle in body-fixed frame.
Eigen::Vector6d currentBodyCenteredState_
Current state of vehicle in base frame for Body objects.
double currentTime_
Current time of propagation.
std::map< AerodynamicCoefficientsIndependentVariables, boost::function< double() > > customCoefficientDependencies_
List of custom functions for aerodynamic coefficient dependencies.
boost::function< double(const Eigen::Vector3d &) > geodeticLatitudeFunction_
bool isLatitudeAndLongitudeSet_
Boolean denoting whether the current latitude and longitude have been computed at current time step.
std::map< FlightConditionVariables, double > scalarFlightConditions_
List of atmospheric/flight properties computed at current time step.
const boost::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel_
Model describing the shape of the body w.r.t. which the flight is taking place.
bool updateLatitudeAndLongitudeForAtmosphere_
Boolean setting whether latitude and longitude are to be updated by updateConditions().
Detailed Description
Class for calculating aerodynamic flight characteristics of a vehicle during numerical integration.
Class is used to ensure that dependent variables such as density, altitude, etc. are only calculated once during each numerical integration step. The get functions of this class are linked to the various models in the code that subsequently require these values.
Definition at line 40 of file flightConditions.h.
Member Enumeration Documentation
enum tudat::aerodynamics::FlightConditions::FlightConditionVariables private
Enumerator
altitude_flight_condition
density_flight_condition
pressure_flight_condition
temperature_flight_condition
latitude_flight_condition
longitude_flight_condition
mach_number_flight_condition
speed_of_sound_flight_condition
airspeed_flight_condition
geodetic_latitude_condition
dynamic_pressure_condition
Definition at line 45 of file flightConditions.h.
Constructor & Destructor Documentation
tudat::aerodynamics::FlightConditions::FlightConditions (const boost::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel, const boost::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel, const boost::shared_ptr< AerodynamicCoefficientInterface > aerodynamicCoefficientInterface, const boost::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator = boost::shared_ptr< reference_frames::AerodynamicAngleCalculator >(), const boost::function< double(const std::string &)> controlSurfaceDeflectionFunction = boost::function< double(const std::string&)>())
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
Parameters
atmosphereModel Atmosphere model of atmosphere through which vehicle is flying
shapeModel Model describing the shape of the body w.r.t. which the flight is taking place.
aerodynamicCoefficientInterface Class from which the aerodynamic (force and moment) coefficients are retrieved
aerodynamicAngleCalculator Object from which the aerodynamic/trajectory angles of the vehicle are calculated.
controlSurfaceDeflectionFunction Function returning control surface deflection, with input the control surface identifier.
Definition at line 28 of file flightConditions.cpp.
References aerodynamicAngleCalculator_, atmosphereModel_, bodyCenteredPseudoBodyFixedStateFunction_, tudat::mathematical_constants::E, geodeticLatitudeFunction_, tudat::reference_frames::AerodynamicAngleCalculator::getCurrentAirspeedBasedBodyFixedState(), tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getGeodeticLatitude(), isLatitudeAndLongitudeSet_, and updateLatitudeAndLongitudeForAtmosphere_.
Member Function Documentation
void tudat::aerodynamics::FlightConditions::updateConditions (const double currentTime)
Function to update all flight conditions (altitude, density, force coefficients) to current state of vehicle and central body.
Parameters
currentTime Time to which conditions are to be updated.
Definition at line 94 of file flightConditions.cpp.
References aerodynamicAngleCalculator_, aerodynamicCoefficientIndependentVariables_, aerodynamicCoefficientInterface_, bodyCenteredPseudoBodyFixedStateFunction_, controlSurfaceAerodynamicCoefficientIndependentVariables_, currentBodyCenteredAirspeedBasedBodyFixedState_, currentTime_, and updateAerodynamicCoefficientInput().
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions().
double tudat::aerodynamics::FlightConditions::getCurrentAltitude () inline
Function to retrieve (and compute if necessary) the current altitude
Returns
Current altitude
Definition at line 98 of file flightConditions.h.
References altitude_flight_condition, computeAltitude(), and scalarFlightConditions_.
Referenced by getAerodynamicCoefficientIndependentVariable(), tudat::propagators::getDoubleDependentVariableFunction(), and tudat::simulation_setup::getPropulsionInputVariables().
double tudat::aerodynamics::FlightConditions::getCurrentDensity () inline
Function to retrieve (and compute if necessary) the current freestream density
Returns
Current freestream density
Definition at line 111 of file flightConditions.h.
References computeDensity(), density_flight_condition, and scalarFlightConditions_.
Referenced by computeDynamicPressure(), tudat::simulation_setup::createAerodynamicAcceleratioModel(), tudat::simulation_setup::createAerodynamicTorqueModel(), tudat::propagators::getDoubleDependentVariableFunction(), and tudat::simulation_setup::getPropulsionInputVariables().
double tudat::aerodynamics::FlightConditions::getCurrentFreestreamTemperature () inline
Function to retrieve (and compute if necessary) the current freestream temperature
Returns
Current freestream temperature
Definition at line 125 of file flightConditions.h.
References computeTemperature(), scalarFlightConditions_, and temperature_flight_condition.
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
double tudat::aerodynamics::FlightConditions::getCurrentDynamicPressure () inline
Function to retrieve (and compute if necessary) the current freestream dynamic pressure
Returns
Current freestream dynamic pressure
Definition at line 139 of file flightConditions.h.
References computeDynamicPressure(), dynamic_pressure_condition, and scalarFlightConditions_.
Referenced by tudat::simulation_setup::getPropulsionInputVariables().
double tudat::aerodynamics::FlightConditions::getCurrentPressure () inline
Function to retrieve (and compute if necessary) the current freestream pressure
Returns
Current freestream dynamic pressure
Definition at line 153 of file flightConditions.h.
References computeFreestreamPressure(), pressure_flight_condition, and scalarFlightConditions_.
Referenced by tudat::simulation_setup::getPropulsionInputVariables().
double tudat::aerodynamics::FlightConditions::getCurrentAirspeed () inline
Returns
Current airspeed
Definition at line 166 of file flightConditions.h.
References airspeed_flight_condition, computeAirspeed(), and scalarFlightConditions_.
Referenced by computeDynamicPressure(), computeMachNumber(), tudat::simulation_setup::createAerodynamicAcceleratioModel(), tudat::simulation_setup::createAerodynamicTorqueModel(), and tudat::propagators::getDoubleDependentVariableFunction().
double tudat::aerodynamics::FlightConditions::getCurrentSpeedOfSound () inline
Function to retrieve (and compute if necessary) the current speed of sound
Returns
Current speed of sound
Definition at line 180 of file flightConditions.h.
References computeSpeedOfSound(), scalarFlightConditions_, and speed_of_sound_flight_condition.
Referenced by computeMachNumber(), and tudat::propagators::getDoubleDependentVariableFunction().
double tudat::aerodynamics::FlightConditions::getCurrentMachNumber () inline
Function to retrieve (and compute if necessary) the current Mach number
Returns
Current Mach number
Definition at line 194 of file flightConditions.h.
References computeMachNumber(), mach_number_flight_condition, and scalarFlightConditions_.
Referenced by getAerodynamicCoefficientIndependentVariable(), and tudat::simulation_setup::getPropulsionInputVariables().
double tudat::aerodynamics::FlightConditions::getCurrentGeodeticLatitude () inline
Function to retrieve (and compute if necessary) the current geodetic latitude
Returns
Current geodetic latitude
Definition at line 208 of file flightConditions.h.
References computeGeodeticLatitude(), geodetic_latitude_condition, and scalarFlightConditions_.
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
double tudat::aerodynamics::FlightConditions::getCurrentTime () inline
Function to return the current time of the FlightConditions.
Returns
Current time of the FlightConditions
Definition at line 222 of file flightConditions.h.
References currentTime_.
boost::shared_ptr< aerodynamics::AtmosphereModel > tudat::aerodynamics::FlightConditions::getAtmosphereModel () const inline
Function to return atmosphere model object
Returns
Atmosphere model object
Definition at line 231 of file flightConditions.h.
References atmosphereModel_.
void tudat::aerodynamics::FlightConditions::setAerodynamicAngleCalculator (const boost::shared_ptr< reference_frames::AerodynamicAngleCalculator > aerodynamicAngleCalculator) inline
Function to (re)set aerodynamic angle calculator object
Parameters
aerodynamicAngleCalculator Aerodynamic angle calculator object to set.
Definition at line 241 of file flightConditions.h.
References aerodynamicAngleCalculator_, bodyCenteredPseudoBodyFixedStateFunction_, tudat::reference_frames::AerodynamicAngleCalculator::getCurrentAirspeedBasedBodyFixedState(), and setAerodynamicCoefficientsIndependentVariableFunction().
void tudat::aerodynamics::FlightConditions::setAerodynamicCoefficientsIndependentVariableFunction (const AerodynamicCoefficientsIndependentVariables independentVariable, const boost::function< double() > coefficientDependency)
Function to set custom dependency of aerodynamic coefficients. If needed, the AerodynamicCoefficientsIndependentVariables enum may be expanded to include e.g. control surface deflections, the values of which will then be retrieved from the function set here
Parameters
independentVariable Identifier of independent variable
coefficientDependency Function returning the current value of the independent variable.
Definition at line 73 of file flightConditions.cpp.
References tudat::aerodynamics::altitude_dependent, tudat::aerodynamics::angle_of_attack_dependent, tudat::aerodynamics::angle_of_sideslip_dependent, customCoefficientDependencies_, and tudat::aerodynamics::mach_number_dependent.
Referenced by setAerodynamicAngleCalculator().
Eigen::Vector6d tudat::aerodynamics::FlightConditions::getCurrentBodyCenteredBodyFixedState () inline
Function to return central body-fixed state of vehicle.
Returns
Current central body-fixed state of vehicle.
Definition at line 267 of file flightConditions.h.
References currentBodyCenteredAirspeedBasedBodyFixedState_.
Eigen::Vector3d tudat::aerodynamics::FlightConditions::getCurrentAirspeedBasedVelocity () inline
Function to return central body-fixed velocity of vehicle.
Returns
Current central body-fixed velocity of vehicle.
Definition at line 277 of file flightConditions.h.
References currentBodyCenteredAirspeedBasedBodyFixedState_.
Referenced by tudat::propagators::getVectorDependentVariableFunction().
boost::shared_ptr< reference_frames::AerodynamicAngleCalculator > tudat::aerodynamics::FlightConditions::getAerodynamicAngleCalculator () inline
Function to return aerodynamic angle calculator object
Returns
Aerodynamic angle calculator object
Definition at line 289 of file flightConditions.h.
References aerodynamicAngleCalculator_.
boost::shared_ptr< AerodynamicCoefficientInterface > tudat::aerodynamics::FlightConditions::getAerodynamicCoefficientInterface () inline
Function to return object from which the aerodynamic coefficients are obtained.
Returns
Object from which the aerodynamic coefficients are obtained.
Definition at line 299 of file flightConditions.h.
References aerodynamicCoefficientInterface_.
std::vector< double > tudat::aerodynamics::FlightConditions::getAerodynamicCoefficientIndependentVariables () inline
Function to return list of independent variables of the aerodynamic coefficient interface
Returns
List of independent variables of the aerodynamic coefficient interface
Definition at line 309 of file flightConditions.h.
References aerodynamicCoefficientIndependentVariables_, aerodynamicCoefficientInterface_, and updateAerodynamicCoefficientInput().
Referenced by tudat::simulation_setup::setTrimmedConditions(), and tudat::aerodynamics::setTrimmedConditions().
std::map< std::string, std::vector< double > > tudat::aerodynamics::FlightConditions::getControlSurfaceAerodynamicCoefficientIndependentVariables () inline
Function to return list of independent variables of the control surface aerodynamic coefficient interface
Returns
List of independent variables of the control surface aerodynamic coefficient interface, with map key the control surface identifiers.
Definition at line 326 of file flightConditions.h.
References aerodynamicCoefficientInterface_, controlSurfaceAerodynamicCoefficientIndependentVariables_, and updateAerodynamicCoefficientInput().
Referenced by tudat::simulation_setup::setTrimmedConditions(), and tudat::aerodynamics::setTrimmedConditions().
void tudat::aerodynamics::FlightConditions::resetCurrentTime (const double currentTime = TUDAT_NAN) inline
Function to reset the current time of the flight conditions. This function is typically sused to set the current time to NaN, indicating the need to recompute all quantities for the next time computation.
Parameters
currentTime
Definition at line 344 of file flightConditions.h.
References aerodynamicAngleCalculator_, aerodynamicCoefficientIndependentVariables_, controlSurfaceAerodynamicCoefficientIndependentVariables_, currentTime_, getAerodynamicCoefficientIndependentVariable(), isLatitudeAndLongitudeSet_, and scalarFlightConditions_.
double tudat::aerodynamics::FlightConditions::getAerodynamicCoefficientIndependentVariable (const AerodynamicCoefficientsIndependentVariables independentVariableType, const std::string & secondaryIdentifier = "") private
Function to (compute and) retrieve the value of an independent variable of aerodynamic coefficients
Parameters
independentVariableType Identifier for type of independent variable
secondaryIdentifier String used as secondary identifier of independent variable (e.g. control surface name).
Returns
Current value of requested independent variable.
Definition at line 125 of file flightConditions.cpp.
References aerodynamicAngleCalculator_, tudat::aerodynamics::altitude_dependent, tudat::reference_frames::angle_of_attack, tudat::aerodynamics::angle_of_attack_dependent, tudat::reference_frames::angle_of_sideslip, tudat::aerodynamics::angle_of_sideslip_dependent, tudat::aerodynamics::control_surface_deflection_dependent, controlSurfaceDeflectionFunction_, customCoefficientDependencies_, getCurrentAltitude(), getCurrentMachNumber(), and tudat::aerodynamics::mach_number_dependent.
Referenced by resetCurrentTime(), and updateAerodynamicCoefficientInput().
void tudat::aerodynamics::FlightConditions::computeLatitudeAndLongitude () inline private
Definition at line 370 of file flightConditions.h.
References aerodynamicAngleCalculator_, isLatitudeAndLongitudeSet_, tudat::reference_frames::latitude_angle, latitude_flight_condition, tudat::reference_frames::longitude_angle, longitude_flight_condition, and scalarFlightConditions_.
Referenced by computeGeodeticLatitude(), and updateAtmosphereInput().
void tudat::aerodynamics::FlightConditions::computeAltitude () inline private
Definition at line 380 of file flightConditions.h.
References altitude_flight_condition, currentBodyCenteredAirspeedBasedBodyFixedState_, scalarFlightConditions_, and shapeModel_.
Referenced by getCurrentAltitude(), and updateAtmosphereInput().
void tudat::aerodynamics::FlightConditions::updateAtmosphereInput () inline private
Definition at line 387 of file flightConditions.h.
References altitude_flight_condition, computeAltitude(), computeLatitudeAndLongitude(), latitude_flight_condition, longitude_flight_condition, scalarFlightConditions_, and updateLatitudeAndLongitudeForAtmosphere_.
Referenced by computeDensity(), computeFreestreamPressure(), computeSpeedOfSound(), and computeTemperature().
void tudat::aerodynamics::FlightConditions::computeDensity () inline private
Definition at line 410 of file flightConditions.h.
References altitude_flight_condition, atmosphereModel_, currentTime_, density_flight_condition, latitude_flight_condition, longitude_flight_condition, scalarFlightConditions_, and updateAtmosphereInput().
Referenced by getCurrentDensity().
void tudat::aerodynamics::FlightConditions::computeTemperature () inline private
Definition at line 421 of file flightConditions.h.
References altitude_flight_condition, atmosphereModel_, currentTime_, latitude_flight_condition, longitude_flight_condition, scalarFlightConditions_, temperature_flight_condition, and updateAtmosphereInput().
Referenced by getCurrentFreestreamTemperature().
void tudat::aerodynamics::FlightConditions::computeFreestreamPressure () inline private
Definition at line 433 of file flightConditions.h.
References altitude_flight_condition, atmosphereModel_, currentTime_, latitude_flight_condition, longitude_flight_condition, pressure_flight_condition, scalarFlightConditions_, and updateAtmosphereInput().
Referenced by getCurrentPressure().
void tudat::aerodynamics::FlightConditions::computeSpeedOfSound () inline private
Definition at line 446 of file flightConditions.h.
References altitude_flight_condition, atmosphereModel_, currentTime_, latitude_flight_condition, longitude_flight_condition, scalarFlightConditions_, speed_of_sound_flight_condition, and updateAtmosphereInput().
Referenced by getCurrentSpeedOfSound().
void tudat::aerodynamics::FlightConditions::computeAirspeed () inline private
Definition at line 457 of file flightConditions.h.
References airspeed_flight_condition, currentBodyCenteredAirspeedBasedBodyFixedState_, and scalarFlightConditions_.
Referenced by getCurrentAirspeed().
void tudat::aerodynamics::FlightConditions::computeDynamicPressure () inline private
Definition at line 463 of file flightConditions.h.
References dynamic_pressure_condition, getCurrentAirspeed(), getCurrentDensity(), and scalarFlightConditions_.
Referenced by getCurrentDynamicPressure().
void tudat::aerodynamics::FlightConditions::computeMachNumber () inline private
Definition at line 471 of file flightConditions.h.
References getCurrentAirspeed(), getCurrentSpeedOfSound(), mach_number_flight_condition, and scalarFlightConditions_.
Referenced by getCurrentMachNumber().
void tudat::aerodynamics::FlightConditions::computeGeodeticLatitude () inline private
Definition at line 478 of file flightConditions.h.
References computeLatitudeAndLongitude(), currentBodyCenteredAirspeedBasedBodyFixedState_, geodetic_latitude_condition, geodeticLatitudeFunction_, isLatitudeAndLongitudeSet_, latitude_flight_condition, scalarFlightConditions_, and updateAerodynamicCoefficientInput().
Referenced by getCurrentGeodeticLatitude().
void tudat::aerodynamics::FlightConditions::updateAerodynamicCoefficientInput () private
Definition at line 191 of file flightConditions.cpp.
References aerodynamicCoefficientIndependentVariables_, aerodynamicCoefficientInterface_, controlSurfaceAerodynamicCoefficientIndependentVariables_, and getAerodynamicCoefficientIndependentVariable().
Referenced by computeGeodeticLatitude(), getAerodynamicCoefficientIndependentVariables(), getControlSurfaceAerodynamicCoefficientIndependentVariables(), and updateConditions().
Member Data Documentation
std::string tudat::aerodynamics::FlightConditions::centralBody_ private
Definition at line 499 of file flightConditions.h.
boost::shared_ptr< aerodynamics::AtmosphereModel > tudat::aerodynamics::FlightConditions::atmosphereModel_ private
Definition at line 502 of file flightConditions.h.
Referenced by computeDensity(), computeFreestreamPressure(), computeSpeedOfSound(), computeTemperature(), FlightConditions(), and getAtmosphereModel().
const boost::shared_ptr< basic_astrodynamics::BodyShapeModel > tudat::aerodynamics::FlightConditions::shapeModel_ private
Definition at line 505 of file flightConditions.h.
Referenced by computeAltitude().
boost::function< Eigen::Vector6d() > tudat::aerodynamics::FlightConditions::bodyCenteredPseudoBodyFixedStateFunction_ private
Definition at line 508 of file flightConditions.h.
Referenced by FlightConditions(), setAerodynamicAngleCalculator(), and updateConditions().
boost::shared_ptr< AerodynamicCoefficientInterface > tudat::aerodynamics::FlightConditions::aerodynamicCoefficientInterface_ private
Definition at line 511 of file flightConditions.h.
Referenced by getAerodynamicCoefficientIndependentVariables(), getAerodynamicCoefficientInterface(), getControlSurfaceAerodynamicCoefficientIndependentVariables(), updateAerodynamicCoefficientInput(), and updateConditions().
boost::shared_ptr< reference_frames::AerodynamicAngleCalculator > tudat::aerodynamics::FlightConditions::aerodynamicAngleCalculator_ private
Definition at line 514 of file flightConditions.h.
Referenced by computeLatitudeAndLongitude(), FlightConditions(), getAerodynamicAngleCalculator(), getAerodynamicCoefficientIndependentVariable(), resetCurrentTime(), setAerodynamicAngleCalculator(), and updateConditions().
boost::function< double(const std::string&) > tudat::aerodynamics::FlightConditions::controlSurfaceDeflectionFunction_ private
Definition at line 517 of file flightConditions.h.
Referenced by getAerodynamicCoefficientIndependentVariable().
Eigen::Vector6d tudat::aerodynamics::FlightConditions::currentBodyCenteredState_ private
Definition at line 520 of file flightConditions.h.
Eigen::Vector6d tudat::aerodynamics::FlightConditions::currentBodyCenteredAirspeedBasedBodyFixedState_ private
Definition at line 523 of file flightConditions.h.
Referenced by computeAirspeed(), computeAltitude(), computeGeodeticLatitude(), getCurrentAirspeedBasedVelocity(), getCurrentBodyCenteredBodyFixedState(), and updateConditions().
std::map< FlightConditionVariables, double > tudat::aerodynamics::FlightConditions::scalarFlightConditions_ private
Definition at line 526 of file flightConditions.h.
Referenced by computeAirspeed(), computeAltitude(), computeDensity(), computeDynamicPressure(), computeFreestreamPressure(), computeGeodeticLatitude(), computeLatitudeAndLongitude(), computeMachNumber(), computeSpeedOfSound(), computeTemperature(), getCurrentAirspeed(), getCurrentAltitude(), getCurrentDensity(), getCurrentDynamicPressure(), getCurrentFreestreamTemperature(), getCurrentGeodeticLatitude(), getCurrentMachNumber(), getCurrentPressure(), getCurrentSpeedOfSound(), resetCurrentTime(), and updateAtmosphereInput().
double tudat::aerodynamics::FlightConditions::currentTime_ private
Definition at line 529 of file flightConditions.h.
Referenced by computeDensity(), computeFreestreamPressure(), computeSpeedOfSound(), computeTemperature(), getCurrentTime(), resetCurrentTime(), and updateConditions().
std::map< AerodynamicCoefficientsIndependentVariables, boost::function< double() > > tudat::aerodynamics::FlightConditions::customCoefficientDependencies_ private
Definition at line 532 of file flightConditions.h.
Referenced by getAerodynamicCoefficientIndependentVariable(), and setAerodynamicCoefficientsIndependentVariableFunction().
bool tudat::aerodynamics::FlightConditions::updateLatitudeAndLongitudeForAtmosphere_ private
Definition at line 535 of file flightConditions.h.
Referenced by FlightConditions(), and updateAtmosphereInput().
bool tudat::aerodynamics::FlightConditions::isLatitudeAndLongitudeSet_ private
Definition at line 538 of file flightConditions.h.
Referenced by computeGeodeticLatitude(), computeLatitudeAndLongitude(), FlightConditions(), and resetCurrentTime().
boost::function< double(const Eigen::Vector3d&) > tudat::aerodynamics::FlightConditions::geodeticLatitudeFunction_ private
Function from which to compute the geodetic latitude as function of body-fixed position (empty if equal to geographic latitude).
Definition at line 542 of file flightConditions.h.
Referenced by computeGeodeticLatitude(), and FlightConditions().
std::vector< double > tudat::aerodynamics::FlightConditions::aerodynamicCoefficientIndependentVariables_ private
Definition at line 545 of file flightConditions.h.
Referenced by getAerodynamicCoefficientIndependentVariables(), resetCurrentTime(), updateAerodynamicCoefficientInput(), and updateConditions().
std::map< std::string, std::vector< double > > tudat::aerodynamics::FlightConditions::controlSurfaceAerodynamicCoefficientIndependentVariables_ private
List of independent variables of the control surface aerodynamic coefficient interface, with map key control surface identifiers.
Definition at line 549 of file flightConditions.h.
Referenced by getControlSurfaceAerodynamicCoefficientIndependentVariables(), resetCurrentTime(), updateAerodynamicCoefficientInput(), and updateConditions().
The documentation for this class was generated from the following files:
Astrodynamics/Aerodynamics/flightConditions.h
Astrodynamics/Aerodynamics/flightConditions.cpp