Tudat: tudat::simulation_setup::ParameterizedThrustMagnitudeSettings Class Reference
tudat::simulation_setup::ParameterizedThrustMagnitudeSettings Class Reference
Class to define the thrust magnitude and specific impulse as an interpolated function of N independent variables.
#include <thrustSettings.h>
Public Member Functions
ParameterizedThrustMagnitudeSettings (const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::shared_ptr< interpolators::Interpolator< double, double > > specificImpulseInterpolator, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables, const std::vector< std::function< double() > > thrustGuidanceInputVariables=std::vector< std::function< double() > >(), const std::vector< std::function< double() > > specificImpulseGuidanceInputVariables=std::vector< std::function< double() > >(), const std::function< void(const double) > inputUpdateFunction=std::function< void(const double) >(), const Eigen::Vector3d bodyFixedThrustDirection=Eigen::Vector3d::UnitX())
Constructor for parameterized thrust and specific impulse.
ParameterizedThrustMagnitudeSettings (const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double constantSpecificImpulse, const std::vector< std::function< double() > > thrustGuidanceInputVariables=std::vector< std::function< double() > >(), const std::function< void(const double) > inputUpdateFunction=std::function< void(const double) >(), const Eigen::Vector3d bodyFixedThrustDirection=Eigen::Vector3d::UnitX())
Constructor for parameterized thrust and constant specific impulse.
Public Member Functions inherited from tudat::simulation_setup::ThrustMagnitudeSettings
ThrustMagnitudeSettings (const ThrustMagnitudeTypes thrustMagnitudeGuidanceType, const std::string &thrustOriginId)
Constructor.
virtual ~ThrustMagnitudeSettings ()
Destructor.
Public Attributes
Eigen::Vector3d bodyFixedThrustDirection_
Direction of the thrust vector in the body-fixed frame.
std::function< void(const double) > inputUpdateFunction_
Function that is called to update the user-defined guidance to the current time.
std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables_
List of identifiers for the physical meaning of each of the entries of the input to specificImpulseDependentVariables_.
std::function< double(const std::vector< double > &) > specificImpulseFunction_
Function returning the specific impulse as a function of the independent variables.
std::vector< std::function< double() > > specificImpulseGuidanceInputVariables_
List of functions returning user-defined guidance input variables for the specific impulse.
std::vector< std::function< double() > > thrustGuidanceInputVariables_
List of functions returning user-defined guidance input variables for the thrust.
std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables_
List of identifiers for the physical meaning of each of the entries of the input to thrustMagnitudeFunction_.
std::function< double(const std::vector< double > &) > thrustMagnitudeFunction_
Function returning the thrust as a function of the independent variables.
Public Attributes inherited from tudat::simulation_setup::ThrustMagnitudeSettings
ThrustMagnitudeTypes thrustMagnitudeGuidanceType_
Type of thrust magnitude guidance that is to be used.
std::string thrustOriginId_
Reference id of thrust origin that is to be used (empty if N/A).
Private Member Functions
void parseInputDataAndCheckConsistency (const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::shared_ptr< interpolators::Interpolator< double, double > > specificImpulseInterpolator)
Function to check the validity of the input data, and process the maximum thrust multiplier if provided.
Detailed Description
Class to define the thrust magnitude and specific impulse as an interpolated function of N independent variables. The physical meaning of the variables must be defined here, selecting from the options in the ThrustIndependentVariables enum, and they are automatically retrieved from the relevant environment models during the propagation. Note that any number of user-specific functions may be included, as a guidance_input_dependent_thrust type or throttle_dependent_thrust. In the case of the throttle_dependent_thrust, the thrustMagnitudeInterpolator input variable is assumed to define the maximum possible thrust, which is then multiplied by the function defining the throttle_dependent_thrust.
Definition at line 733 of file thrustSettings.h.
Constructor & Destructor Documentation
ParameterizedThrustMagnitudeSettings() [1/2]
tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::ParameterizedThrustMagnitudeSettings (const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::shared_ptr< interpolators::Interpolator< double, double > > specificImpulseInterpolator, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables, const std::vector< std::function< double() > > thrustGuidanceInputVariables = std::vector< std::function< double() > >(), const std::vector< std::function< double() > > specificImpulseGuidanceInputVariables = std::vector< std::function< double() > >(), const std::function< void(const double) > inputUpdateFunction = std::function< void(const double) >(), const Eigen::Vector3d bodyFixedThrustDirection = Eigen::Vector3d::UnitX()) inline
Constructor, defines the interpolators for thrust and specific impulse, as well as the physical meaning of each of the independent variables.
Parameters
thrustMagnitudeInterpolator Interpolator returning the current thrust (or maximum thrust if thrustIndependentVariables contains an throttle_dependent_thrust entry) as a function of the independent variables.
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of thrustMagnitudeInterpolator.
specificImpulseInterpolator Interpolator returning the current specific impulse as a function of the independent variables.
specificImpulseDependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of specificImpulseInterpolator.
thrustGuidanceInputVariables List of functions returning user-defined guidance input variables for the thrust (default none). The order of the functions in this vector is passed to the thrustMagnitudeInterpolator in the order of the throttle_dependent_thrust and guidance_input_dependent_thrust in the thrustIndependentVariables vector
specificImpulseGuidanceInputVariables List of functions returning user-defined guidance input variables for the specific impulse (default none). The order of the functions in this vector is passed to the specificImpulseInterpolator in the order of the and guidance_input_dependent_thrust in the thrustIndependentVariables vector
inputUpdateFunction Function that is called to update the user-defined guidance to the current time (empty by default).
bodyFixedThrustDirection Direction of the thrust vector in the body-fixed frame (default in x-direction; to vehicle front).
Definition at line 762 of file thrustSettings.h.
References parseInputDataAndCheckConsistency().
ParameterizedThrustMagnitudeSettings() [2/2]
tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::ParameterizedThrustMagnitudeSettings (const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const double constantSpecificImpulse, const std::vector< std::function< double() > > thrustGuidanceInputVariables = std::vector< std::function< double() > >(), const std::function< void(const double) > inputUpdateFunction = std::function< void(const double) >(), const Eigen::Vector3d bodyFixedThrustDirection = Eigen::Vector3d::UnitX()) inline
Constructor, defines a constant thrust and an interpolator for thrust, as well as the physical meaning of each of the independent variables.
Parameters
thrustMagnitudeInterpolator Interpolator returning the current thrust (or maximum thrust if thrustIndependentVariables contains an throttle_dependent_thrust entry) as a function of the independent variables.
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the 'interpolate' function of thrustMagnitudeInterpolator.
constantSpecificImpulse Constant specific impulse
thrustGuidanceInputVariables List of functions returning user-defined guidance input variables for the thrust (default none). The order of the functions in this vector is passed to the thrustMagnitudeInterpolator in the order of the throttle_dependent_thrust and guidance_input_dependent_thrust in the thrustIndependentVariables vector
inputUpdateFunction Function that is called to update the user-defined guidance to the current time (empty by default).
bodyFixedThrustDirection Direction of the thrust vector in the body-fixed frame (default in x-direction; to vehicle front).
Definition at line 806 of file thrustSettings.h.
Member Function Documentation
parseInputDataAndCheckConsistency()
void tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::parseInputDataAndCheckConsistency (const std::shared_ptr< interpolators::Interpolator< double, double > > thrustMagnitudeInterpolator, const std::shared_ptr< interpolators::Interpolator< double, double > > specificImpulseInterpolator) private
Function to check the validity of the input data, and process the maximum thrust multiplier if provided.
Parameters
thrustMagnitudeInterpolator Interpolator for the (maximum) thrust provided to the constructor
specificImpulseInterpolator Interpolator for the specific impulse provided to the constructor
Definition at line 115 of file thrustSettings.cpp.
References tudat::propulsion::guidance_input_dependent_thrust, tudat::simulation_setup::multiplyMaximumThrustByScalingFactor(), specificImpulseDependentVariables_, specificImpulseGuidanceInputVariables_, tudat::propulsion::throttle_dependent_thrust, thrustGuidanceInputVariables_, thrustIndependentVariables_, and thrustMagnitudeFunction_.
Referenced by ParameterizedThrustMagnitudeSettings().
Member Data Documentation
thrustMagnitudeFunction_
std::function< double(const std::vector< double >&) > tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::thrustMagnitudeFunction_
Definition at line 828 of file thrustSettings.h.
Referenced by parseInputDataAndCheckConsistency().
specificImpulseFunction_
std::function< double(const std::vector< double >&) > tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::specificImpulseFunction_
Definition at line 831 of file thrustSettings.h.
thrustIndependentVariables_
std::vector< propulsion::ThrustIndependentVariables > tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::thrustIndependentVariables_
Definition at line 834 of file thrustSettings.h.
Referenced by parseInputDataAndCheckConsistency().
specificImpulseDependentVariables_
std::vector< propulsion::ThrustIndependentVariables > tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::specificImpulseDependentVariables_
Definition at line 837 of file thrustSettings.h.
Referenced by parseInputDataAndCheckConsistency().
thrustGuidanceInputVariables_
std::vector< std::function< double() > > tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::thrustGuidanceInputVariables_
Definition at line 840 of file thrustSettings.h.
Referenced by parseInputDataAndCheckConsistency().
specificImpulseGuidanceInputVariables_
std::vector< std::function< double() > > tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::specificImpulseGuidanceInputVariables_
Definition at line 843 of file thrustSettings.h.
Referenced by parseInputDataAndCheckConsistency().
inputUpdateFunction_
std::function< void(const double) > tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::inputUpdateFunction_
Definition at line 846 of file thrustSettings.h.
bodyFixedThrustDirection_
Eigen::Vector3d tudat::simulation_setup::ParameterizedThrustMagnitudeSettings::bodyFixedThrustDirection_
Definition at line 849 of file thrustSettings.h.
The documentation for this class was generated from the following files:
SimulationSetup/PropagationSetup/thrustSettings.h
SimulationSetup/PropagationSetup/thrustSettings.cpp