Tudat: tudat::ephemerides::SimpleRotationalEphemeris Class Reference
tudat::ephemerides::SimpleRotationalEphemeris Class Reference
Class to model the rotation of bodies with constant rotation axis and rate.
#include <simpleRotationalEphemeris.h>
Public Member Functions
SimpleRotationalEphemeris (const Eigen::Quaterniond &initialRotationToTargetFrame, const double rotationRate, const double initialSecondsSinceEpoch, const std::string &baseFrameOrientation="", const std::string &targetFrameOrientation="")
Constructor from initial rotational state.
SimpleRotationalEphemeris (const double poleRightAscension, const double poleDeclination, const double primeMeridianOfDate, const double rotationRate, const double initialSecondsSinceEpoch, const std::string &baseFrameOrientation="", const std::string &targetFrameOrientation="")
Constructor from rotation state angles.
~SimpleRotationalEphemeris ()
Destructor.
Eigen::Matrix3d getDerivativeOfRotationToBaseFrame (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame at specified time.
Eigen::Matrix3d getDerivativeOfRotationToTargetFrame (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from original frame to target frame at specified time.
Eigen::Vector3d getInitialEulerAngles ()
Function to get vector of euler angles at initialSecondsSinceEpoch_.
Eigen::Quaterniond getInitialRotationToTargetFrame ()
Get rotation from target to base frame at initial time.
double getInitialSecondsSinceEpoch ()
Get seconds since epoch at which initialRotationToTargetFrame_ is valid.
double getRotationRate ()
Get rotation rate of body.
Eigen::Quaterniond getRotationToBaseFrame (const double secondsSinceEpoch)
Calculate rotation quaternion from target frame to base frame.
Eigen::Quaterniond getRotationToTargetFrame (const double secondsSinceEpoch)
Get rotation quaternion to target frame from base frame.
void resetInitialPoleRightAscensionAndDeclination (const double rightAscension, const double declination)
Function to reset the right ascension and declination of body's north pole.
void resetRotationRate (const double rotationRate)
Function to reset the rotation rate of the body.
Public Member Functions inherited from tudat::ephemerides::RotationalEphemeris
RotationalEphemeris (const std::string &baseFrameOrientation="", const std::string &targetFrameOrientation="")
Constructor.
virtual ~RotationalEphemeris ()
Virtual destructor.
std::string getBaseFrameOrientation ()
Get base reference frame orientation.
virtual Eigen::Matrix3d getDerivativeOfRotationToBaseFrameFromExtendedTime (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame in Time precision.
template<>
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const double timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame.
template<>
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame.
template<typename TimeType >
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const TimeType timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame in templated precision.
virtual Eigen::Matrix3d getDerivativeOfRotationToTargetFrameFromExtendedTime (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from original frame to target frame in Time precision.
template<>
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix to target frame from original frame.
template<>
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const Time secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix to target frame from original frame.
template<typename TimeType >
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const TimeType secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from original frame to target frame in templated precision.
virtual void getFullRotationalQuantitiesToTargetFrame (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const double secondsSinceEpoch)
Function to calculate the full rotational state at given time.
virtual void getFullRotationalQuantitiesToTargetFrameFromExtendedTime (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const Time timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<>
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const double timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<>
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const Time timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<typename TimeType >
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const TimeType timeSinceEpoch)
Function to calculate the full rotational state at given time.
virtual Eigen::Vector3d getRotationalVelocityVectorInBaseFrame (const double secondsSinceEpoch)
Function to retrieve the angular velocity vector, expressed in base frame.
virtual Eigen::Vector3d getRotationalVelocityVectorInTargetFrame (const double secondsSinceEpoch)
Function to retrieve the angular velocity vector, expressed in target frame.
virtual Eigen::Quaterniond getRotationToBaseFrameFromExtendedTime (const Time timeSinceEpoch)
Get rotation quaternion from target frame to base frame in Time precision.
template<>
Eigen::Quaterniond getRotationToBaseFrameTemplated (const double timeSinceEpoch)
Get rotation quaternion from target frame to base frame.
template<>
Eigen::Quaterniond getRotationToBaseFrameTemplated (const Time timeSinceEpoch)
Get rotation quaternion from target frame to base frame.
template<typename TimeType >
Eigen::Quaterniond getRotationToBaseFrameTemplated (const TimeType timeSinceEpoch)
Get rotation quaternion from target frame to base frame in templated precision.
virtual Eigen::Quaterniond getRotationToTargetFrameFromExtendedTime (const Time timeSinceEpoch)
Get rotation quaternion to target frame from base frame in Time precision.
template<>
Eigen::Quaterniond getRotationToTargetFrameTemplated (const double secondsSinceEpoch)
Get rotation quaternion to target frame from base frame.
template<>
Eigen::Quaterniond getRotationToTargetFrameTemplated (const Time secondsSinceEpoch)
Get rotation quaternion to target frame from base frame.
template<typename TimeType >
Eigen::Quaterniond getRotationToTargetFrameTemplated (const TimeType secondsSinceEpoch)
Get rotation quaternion to target frame from base frame in templated precision.
std::string getTargetFrameOrientation ()
Get target reference frame orientation.
Private Attributes
Eigen::Vector3d initialEulerAngles_
Initial Euler angles describing the rotational state of the body at initialSecondsSinceEpoch_.
Eigen::Quaterniond initialRotationToTargetFrame_
Rotation from target to base frame at initial time.
double initialSecondsSinceEpoch_
Seconds since epoch at which initialRotationToTargetFrame_ is valid.
double rotationRate_
Rotation rate of body (about local z-axis).
Additional Inherited Members
Protected Attributes inherited from tudat::ephemerides::RotationalEphemeris
const std::string baseFrameOrientation_
Base reference frame orientation.
const std::string targetFrameOrientation_
Target reference frame orientation.
Detailed Description
Class to model the rotation of bodies with constant rotation axis and rate, i.e., those for which the angular momentum vector remains constant in time (according to an inertial observer).
Definition at line 28 of file simpleRotationalEphemeris.h.
Constructor & Destructor Documentation
SimpleRotationalEphemeris() [1/2]
tudat::ephemerides::SimpleRotationalEphemeris::SimpleRotationalEphemeris (const Eigen::Quaterniond & initialRotationToTargetFrame, const double rotationRate, const double initialSecondsSinceEpoch, const std::string & baseFrameOrientation = "", const std::string & targetFrameOrientation = "") inline
Constructor from initial rotational state that is empty because all member variables are initialized through the constructor arguments.
Parameters
initialRotationToTargetFrame Rotation from base to target frame at initial time (specified by 2nd and 3rd parameter).
rotationRate Constant rotation rate of body.
initialSecondsSinceEpoch Seconds since epoch at which primeMeridianOfDate is valid.
baseFrameOrientation Base frame identifier.
targetFrameOrientation Target frame identifier.
Definition at line 43 of file simpleRotationalEphemeris.h.
References tudat::reference_frames::calculateInertialToPlanetFixedRotationAnglesFromMatrix(), initialEulerAngles_, and initialRotationToTargetFrame_.
SimpleRotationalEphemeris() [2/2]
tudat::ephemerides::SimpleRotationalEphemeris::SimpleRotationalEphemeris (const double poleRightAscension, const double poleDeclination, const double primeMeridianOfDate, const double rotationRate, const double initialSecondsSinceEpoch, const std::string & baseFrameOrientation = "", const std::string & targetFrameOrientation = "") inline
Constructor from rotation state angles, i.e., right ascension and declination of pole (both assumuned constant) and the position of the prime meridian at a given epoch (reference Julian day and seconds since that Julian day). Calculates member variables from constructor arguments.
Parameters
poleRightAscension Right ascension of body's pole in base frame.
poleDeclination Declination of body's pole in base frame.
primeMeridianOfDate Position of prime meridian at given time.
rotationRate Constant rotation rate of body.
initialSecondsSinceEpoch Seconds since epoch at which primeMeridianOfDate is valid.
baseFrameOrientation Base frame identifier.
targetFrameOrientation Target frame identifier.
Definition at line 71 of file simpleRotationalEphemeris.h.
References initialEulerAngles_.
~SimpleRotationalEphemeris()
tudat::ephemerides::SimpleRotationalEphemeris::~SimpleRotationalEphemeris () inline
Definition at line 92 of file simpleRotationalEphemeris.h.
Member Function Documentation
getRotationToBaseFrame()
Eigen::Quaterniond tudat::ephemerides::SimpleRotationalEphemeris::getRotationToBaseFrame (const double secondsSinceEpoch) inline virtual
Pure virtual function that calculates the rotation quaternion from target frame to base frame at specified time.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Rotation quaternion computed.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 101 of file simpleRotationalEphemeris.h.
References getRotationToTargetFrame().
getRotationToTargetFrame()
Eigen::Quaterniond tudat::ephemerides::SimpleRotationalEphemeris::getRotationToTargetFrame (const double secondsSinceEpoch) virtual
Returns the rotation quaternion to target frame from base frame at specified time.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Rotation quaternion computed.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 23 of file simpleRotationalEphemeris.cpp.
References tudat::basic_mathematics::computeModulo(), tudat::reference_frames::getInertialToPlanetocentricFrameTransformationQuaternion(), initialRotationToTargetFrame_, initialSecondsSinceEpoch_, tudat::mathematical_constants::PI, and rotationRate_.
Referenced by getRotationToBaseFrame().
getDerivativeOfRotationToBaseFrame()
Eigen::Matrix3d tudat::ephemerides::SimpleRotationalEphemeris::getDerivativeOfRotationToBaseFrame (const double secondsSinceEpoch) inline virtual
Function to calculate the derivative of the rotation matrix from target frame to original frame.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Derivative of rotation from target (typically local) to original (typically global) frame at specified time.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 125 of file simpleRotationalEphemeris.h.
References getDerivativeOfRotationToTargetFrame().
getDerivativeOfRotationToTargetFrame()
Eigen::Matrix3d tudat::ephemerides::SimpleRotationalEphemeris::getDerivativeOfRotationToTargetFrame (const double secondsSinceEpoch) virtual
Function to calculate the derivative of the rotation matrix from target frame to original frame.
Function to calculate the derivative of the rotation matrix from original frame to target frame.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
Derivative of rotation from original (typically global) to target (typically local) frame at specified time.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 37 of file simpleRotationalEphemeris.cpp.
References tudat::basic_mathematics::computeModulo(), tudat::reference_frames::getInertialToPlanetocentricFrameTransformationQuaternion(), initialRotationToTargetFrame_, initialSecondsSinceEpoch_, tudat::mathematical_constants::PI, rotationRate_, and tudat::reference_frames::Z_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER.
Referenced by getDerivativeOfRotationToBaseFrame().
getInitialRotationToTargetFrame()
Eigen::Quaterniond tudat::ephemerides::SimpleRotationalEphemeris::getInitialRotationToTargetFrame () inline
Returns rotation from target to base frame at initial time.
Returns
Rotation quaternion at initial time.
Definition at line 149 of file simpleRotationalEphemeris.h.
References initialRotationToTargetFrame_.
getInitialSecondsSinceEpoch()
double tudat::ephemerides::SimpleRotationalEphemeris::getInitialSecondsSinceEpoch () inline
Returns seconds since epoch at which initialRotationToTargetFrame_ is valid.
Returns
Seconds since Julian day epoch [s].
Definition at line 156 of file simpleRotationalEphemeris.h.
References initialSecondsSinceEpoch_.
getRotationRate()
double tudat::ephemerides::SimpleRotationalEphemeris::getRotationRate () inline
Returns rotation rate of body.
Returns
Rotation rate [rad/s].
Definition at line 163 of file simpleRotationalEphemeris.h.
References rotationRate_.
resetRotationRate()
void tudat::ephemerides::SimpleRotationalEphemeris::resetRotationRate (const double rotationRate) inline
Function to reset the rotation rate of the body.
Parameters
rotationRate New rotation rate [rad/s].
Definition at line 170 of file simpleRotationalEphemeris.h.
References rotationRate_.
getInitialEulerAngles()
Eigen::Vector3d tudat::ephemerides::SimpleRotationalEphemeris::getInitialEulerAngles () inline
Function to get vector of euler angles at initialSecondsSinceEpoch_, in order right ascension, declination, prime meridian.
Returns
Vector of euler angles at initialSecondsSinceEpoch_, in order right ascension, declination, prime meridian.
Definition at line 178 of file simpleRotationalEphemeris.h.
References initialEulerAngles_.
resetInitialPoleRightAscensionAndDeclination()
void tudat::ephemerides::SimpleRotationalEphemeris::resetInitialPoleRightAscensionAndDeclination (const double rightAscension, const double declination)
Function to reset the right ascension and declination of body's north pole, recalculates the initialRotationToOriginalFrame_ member.
Parameters
rightAscension New right ascension of north pole.
declination New declination of north pole.
Definition at line 53 of file simpleRotationalEphemeris.cpp.
References tudat::reference_frames::getInertialToPlanetocentricFrameTransformationQuaternion(), initialEulerAngles_, and initialRotationToTargetFrame_.
Member Data Documentation
rotationRate_
double tudat::ephemerides::SimpleRotationalEphemeris::rotationRate_ private
Rotation rate of body (about local z-axis).
Definition at line 200 of file simpleRotationalEphemeris.h.
Referenced by getDerivativeOfRotationToTargetFrame(), getRotationRate(), getRotationToTargetFrame(), and resetRotationRate().
initialRotationToTargetFrame_
Eigen::Quaterniond tudat::ephemerides::SimpleRotationalEphemeris::initialRotationToTargetFrame_ private
Rotation from target to base frame at initial time.
Definition at line 206 of file simpleRotationalEphemeris.h.
Referenced by getDerivativeOfRotationToTargetFrame(), getInitialRotationToTargetFrame(), getRotationToTargetFrame(), resetInitialPoleRightAscensionAndDeclination(), and SimpleRotationalEphemeris().
initialSecondsSinceEpoch_
double tudat::ephemerides::SimpleRotationalEphemeris::initialSecondsSinceEpoch_ private
Seconds since epoch at which initialRotationToTargetFrame is valid.
Definition at line 212 of file simpleRotationalEphemeris.h.
Referenced by getDerivativeOfRotationToTargetFrame(), getInitialSecondsSinceEpoch(), and getRotationToTargetFrame().
initialEulerAngles_
Eigen::Vector3d tudat::ephemerides::SimpleRotationalEphemeris::initialEulerAngles_ private
Initial Euler angles describing the rotational state of the body at initialSecondsSinceEpoch_. Order of the vector is: right ascension (alpha), declination (delta), prime meridian of date (W)
Definition at line 220 of file simpleRotationalEphemeris.h.
Referenced by getInitialEulerAngles(), resetInitialPoleRightAscensionAndDeclination(), and SimpleRotationalEphemeris().
The documentation for this class was generated from the following files:
Astrodynamics/Ephemerides/simpleRotationalEphemeris.h
Astrodynamics/Ephemerides/simpleRotationalEphemeris.cpp