Tudat: tudat::utilities Namespace Reference
tudat::utilities Namespace Reference
Functions
template<typename Argument >
std::vector< Argument > addScalarToVector (const std::vector< Argument > &vector, const double scalar)
Function to add a double to all entries in an STL vector.
template<typename S , typename T , typename U , typename V , int Rows, int Columns>
void castMatrixMap (const std::map< S, Eigen::Matrix< T, Rows, Columns > > &originalMap, std::map< U, Eigen::Matrix< V, Rows, Columns > > &newTypesMap)
Function to cast a map of Eigen matrices from one key/matrix scalar type set to another set.
template<typename T >
std::vector< T > convertEigenVectorToStlVector (const Eigen::Matrix< T, Eigen::Dynamic, 1 > &eigenVector)
template<typename MapKey , typename ScalarType >
std::map< MapKey, Eigen::Array< ScalarType, Eigen::Dynamic, 1 > > convertSTLVectorMapToEigenVectorMap (std::map< MapKey, std::vector< ScalarType > > stlVectorMap)
Transform from map of std::vector (output of text file reader) to map of Eigen::Array.
template<typename T >
Eigen::Matrix< T, Eigen::Dynamic, 1 > convertStlVectorToEigenVector (const std::vector< T > &stlVector)
template<typename S , int NumberOfDimensions>
void copyMultiArray (const boost::multi_array< S, NumberOfDimensions > &arrayToCopy, boost::multi_array< S, NumberOfDimensions > &targetArray)
Function to copy a multi-array into another multi-array.
template<typename KeyType , typename ScalarType , int NumberOfRows, int NumberOfColumns = 1>
Eigen::Matrix< ScalarType, Eigen::Dynamic, NumberOfColumns > createConcatenatedEigenMatrixFromMapValues (const std::map< KeyType, Eigen::Matrix< ScalarType, NumberOfRows, NumberOfColumns > > &inputMap)
template<typename S , typename T >
void createVectorBlockMatrixHistory (const std::map< S, Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > > &matrixHistory, std::map< S, Eigen::Matrix< T, Eigen::Dynamic, 1 > > &blockMatrixHistory, const std::pair< int, int > startIndices, const int segmentSize)
Function to create a vector block history from full matrix history.
template<typename VectorArgument , typename KeyType >
std::vector< KeyType > createVectorFromMapKeys (const std::map< KeyType, VectorArgument > &inputMap)
Function to create a vector from the keys of a map.
template<typename VectorArgument , typename KeyType >
std::vector< VectorArgument > createVectorFromMapValues (const std::map< KeyType, VectorArgument > &inputMap)
Function to create a vector from the values of a map.
template<typename VectorArgument , typename KeyType >
std::vector< KeyType > createVectorFromMultiMapKeys (const std::multimap< KeyType, VectorArgument > &inputMap)
Function to create a vector from the keys of a multimap.
template<typename VectorArgument , typename KeyType >
std::vector< VectorArgument > createVectorFromMultiMapValues (const std::multimap< KeyType, VectorArgument > &inputMap)
Function to create a vector from the values of a multimap.
template<typename S , typename T >
std::vector< S > createVectorFromVectorOfPairFirsts (const std::vector< std::pair< S, T > > inputVector)
template<typename T >
bool doStlVectorContentsMatch (const std::vector< T > &vectorA, const std::vector< T > &vectorB)
template<typename S , typename T >
std::vector< boost::shared_ptr< T > > dynamicCastSVectorToTVector (const std::vector< boost::shared_ptr< S > > &originalVector)
Function to dynamic cast vector of shared pointers of one type to shared pointers of another type.
template<typename T , typename S >
T evaluateFunctionWithoutInputArgumentDependency (boost::function< T() > inputFreeFunction, const S dummyInput)
template<unsigned int NumberOfDimensions>
boost::multi_array< double,NumberOfDimensions >::index getMultiArrayIndex (const typename boost::multi_array< double, NumberOfDimensions > &multiArray, const double *requestedElement, const unsigned short int direction)
Get index in nth direction of pointer to single entry in multi-array of doubles.
boost::array< boost::multi_array< double, 1 >::index, 1 > getMultiArrayIndexArray (const boost::multi_array< double, 1 > &multiArray, const double *requestedElement)
Get indices of pointer to single entry in multi-array (size 1) of doubles.
boost::array< boost::multi_array< double, 2 >::index, 2 > getMultiArrayIndexArray (const boost::multi_array< double, 2 > &multiArray, const double *requestedElement)
Get indices of pointer to single entry in multi-array (size 2) of doubles.
boost::array< boost::multi_array< double, 3 >::index, 3 > getMultiArrayIndexArray (const boost::multi_array< double, 3 > &multiArray, const double *requestedElement)
Get indices of pointer to single entry in multi-array (size 3) of doubles.
template<typename T >
std::vector< int > getSortOrderOfVector (const std::vector< T > unsortedVector)
Function to get the order in which the input vector would be sorted (in ascending order)
template<typename T >
std::pair< std::vector< int >, std::vector< T > > getSortOrderOfVectorAndSortedVector (const std::vector< T > unsortedVector)
Function to get sorted vector of an input vector, as well as the order in which this input has been be sorted (ascending)
template<typename S , typename T >
void printMapContents (const std::map< S, T > &mapToPrint)
Function to print the contents of a map, line by line.
template<typename S >
S subtractFunctionReturn (const boost::function< S() > function1, const boost::function< S() > function2)
Function to subtract the return values of two boost function with empty input argument list.
template<typename S >
S sumFunctionReturn (const boost::function< S() > function1, const boost::function< S() > function2)
Function to sum the return values of two boost function with empty input argument list.
Function Documentation
boost::array< boost::multi_array< double, 1 >::index, 1 > tudat::utilities::getMultiArrayIndexArray (const boost::multi_array< double, 1 > & multiArray, const double * requestedElement)
Get indices of pointer to single entry in multi-array (size 1) of doubles
Parameters
multiArray Multi-array for which the index is to be retrieved
requestedElement Pointer to element for which index is to be retrieved
Returns
Indices of pointer to single entry in multi-array of doubles
Definition at line 20 of file utilities.cpp.
Referenced by getMultiArrayIndex(), and tudat::input_output::mergeNDimensionalCoefficients().
boost::array< boost::multi_array< double, 2 >::index, 2 > tudat::utilities::getMultiArrayIndexArray (const boost::multi_array< double, 2 > & multiArray, const double * requestedElement)
Get indices of pointer to single entry in multi-array (size 2) of doubles
Parameters
multiArray Multi-array for which the index is to be retrieved
requestedElement Pointer to element for which index is to be retrieved
Returns
Indices of pointer to single entry in multi-array of doubles
Definition at line 35 of file utilities.cpp.
boost::array< boost::multi_array< double, 3 >::index, 3 > tudat::utilities::getMultiArrayIndexArray (const boost::multi_array< double, 3 > & multiArray, const double * requestedElement)
Get indices of pointer to single entry in multi-array (size 3) of doubles
Parameters
multiArray Multi-array for which the index is to be retrieved
requestedElement Pointer to element for which index is to be retrieved
Returns
Indices of pointer to single entry in multi-array of doubles
Definition at line 50 of file utilities.cpp.
template<typename VectorArgument , typename KeyType > std::vector< VectorArgument > tudat::utilities::createVectorFromMapValues (const std::map< KeyType, VectorArgument > & inputMap)
Function to create a vector from the values of a map. The output vector is in the order of the map entries, i.e. as provided by a forward iterator. The map keys are not used for the return vector.
Parameters
inputMap Original map from which the vector is to be created
Returns
Vector created from the map values
Definition at line 39 of file utilities.h.
Referenced by tudat::linear_algebra::getLeastSquaresPolynomialFit(), and tudat::ephemerides::MultiArcEphemeris::resetSingleArcEphemerides().
template<typename VectorArgument , typename KeyType > std::vector< KeyType > tudat::utilities::createVectorFromMapKeys (const std::map< KeyType, VectorArgument > & inputMap)
Function to create a vector from the keys of a map. The output vector is in the order of the map entries, i.e. as provided by a forward iterator. The map values are not used for the return vector.
Parameters
inputMap Original map from which the vector is to be created
Returns
Vector created from the map keys
Definition at line 66 of file utilities.h.
Referenced by tudat::observation_partials::ObservationPartialCreator< 1, ObservationScalarType, TimeType >::createObservationPartials(), tudat::observation_partials::ObservationPartialCreator< 2, ObservationScalarType, TimeType >::createObservationPartials(), tudat::observation_partials::ObservationPartialCreator< 3, ObservationScalarType, TimeType >::createObservationPartials(), tudat::linear_algebra::getLeastSquaresPolynomialFit(), tudat::ephemerides::MultiArcEphemeris::resetSingleArcEphemerides(), tudat::aerodynamics::AerodynamicCoefficientInterface::setControlSurfaceIncrements(), tudat::propagators::setPropagatorSettingsMultiArcStatesInEstimatedDynamicalParameters(), and tudat::observation_models::simulateObservationsWithCheck().
template<typename S > S tudat::utilities::sumFunctionReturn (const boost::function< S() > function1, const boost::function< S() > function2)
Function to sum the return values of two boost function with empty input argument list.
Parameters
function1 First function to be added.
function2 Second function to be added.
Returns
Sum of return values of function1 and function2
Definition at line 92 of file utilities.h.
template<typename S > S tudat::utilities::subtractFunctionReturn (const boost::function< S() > function1, const boost::function< S() > function2)
Function to subtract the return values of two boost function with empty input argument list.
Parameters
function1 First function to be subtracted from.
function2 Second function to be subtracted.
Returns
Return values of function1 - return value of function2
Definition at line 105 of file utilities.h.
template<typename S , typename T > void tudat::utilities::createVectorBlockMatrixHistory (const std::map< S, Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > > & matrixHistory, std::map< S, Eigen::Matrix< T, Eigen::Dynamic, 1 > > & blockMatrixHistory, const std::pair< int, int > startIndices, const int segmentSize)
Function to create a vector matrix block history from full matrix history.
Parameters
matrixHistory Full matrix history
blockMatrixHistory Block vector history (return by reference).
startIndices Starting point (row,column) in matrix of return vector blocks.
segmentSize Number of rows in vector.
Definition at line 119 of file utilities.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
template<typename S , typename T > void tudat::utilities::printMapContents (const std::map< S, T > & mapToPrint)
Function to print the contents of a map, line by line. Both the key and value types must have the << operator defined
Parameters
mapToPrint Map that is to be printed.
Definition at line 142 of file utilities.h.
Referenced by tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::SingleArcDynamicsSimulator().
template<typename S , typename T , typename U , typename V , int Rows, int Columns> void tudat::utilities::castMatrixMap (const std::map< S, Eigen::Matrix< T, Rows, Columns > > & originalMap, std::map< U, Eigen::Matrix< V, Rows, Columns > > & newTypesMap)
Function to produce a map of Eigen matrices, cast from one set of key/matrix scalar type set to another set.
Parameters
originalMap Map in original types
newTypesMap Map that is to be created (returned by reference).
Definition at line 158 of file utilities.h.
template<typename S , typename T > std::vector< boost::shared_ptr< T > > tudat::utilities::dynamicCastSVectorToTVector (const std::vector< boost::shared_ptr< S > > & originalVector)
Function to dynamic cast vector of shared pointers of one type (S) to shared pointers of another type (T). The dynamic cast must be permissible, i.e. an S pointer must succesfully dynamic cast to a T pointer (T shoudl typically derive from S).
Parameters
originalVector Vector of S shared pointers.
Returns
Dynamic casted vector of T shared pointers.
Definition at line 177 of file utilities.h.
Referenced by tudat::simulation_setup::createTidalLoveNumberInterfaces().
template<typename KeyType , typename ScalarType , int NumberOfRows, int NumberOfColumns = 1> Eigen::Matrix< ScalarType, Eigen::Dynamic, NumberOfColumns > tudat::utilities::createConcatenatedEigenMatrixFromMapValues (const std::map< KeyType, Eigen::Matrix< ScalarType, NumberOfRows, NumberOfColumns > > & inputMap)
Definition at line 192 of file utilities.h.
Referenced by tudat::observation_models::ObservationManager< ObservationSize, ObservationScalarType, TimeType >::computeObservationsWithPartials(), and tudat::observation_models::simulateObservationsWithCheck().
template<typename T > std::vector< T > tudat::utilities::convertEigenVectorToStlVector (const Eigen::Matrix< T, Eigen::Dynamic, 1 > & eigenVector)
Definition at line 247 of file utilities.h.
Referenced by tudat::linear_algebra::getLeastSquaresPolynomialFit().
template<typename T > Eigen::Matrix< T, Eigen::Dynamic, 1 > tudat::utilities::convertStlVectorToEigenVector (const std::vector< T > & stlVector)
Definition at line 260 of file utilities.h.
Referenced by tudat::linear_algebra::getLeastSquaresPolynomialFit().
template<typename Argument > std::vector< Argument > tudat::utilities::addScalarToVector (const std::vector< Argument > & vector, const double scalar)
Function to add a double to all entries in an STL vector (addition of a double must be defined for Argument type).
Parameters
vector Vector to which a double is to be added.
scalar Value that is to be added to vector
Returns
New vector with scalar added to all entries of input vector.
Definition at line 278 of file utilities.h.
template<typename S , int NumberOfDimensions> void tudat::utilities::copyMultiArray (const boost::multi_array< S, NumberOfDimensions > & arrayToCopy, boost::multi_array< S, NumberOfDimensions > & targetArray)
Function to copy a multi-array into another multi-array, resizing the new multi-array accordingly
Parameters
arrayToCopy Multi-array that is to be copied
targetArray New multi-array into which arrayToCopy is to be copied (returned by reference).
Definition at line 302 of file utilities.h.
template<unsigned int NumberOfDimensions> boost::multi_array< double ,NumberOfDimensions >::index tudat::utilities::getMultiArrayIndex (const typename boost::multi_array< double, NumberOfDimensions > & multiArray, const double * requestedElement, const unsigned short int direction)
Get index in nth direction of pointer to single entry in multi-array of doubles
Parameters
multiArray Multi-array for which the index is to be retrieved
requestedElement Pointer to element for which index is to be retrieved
direction Dimension of multi-array for which index is to be retrieved
Returns
Index in nth direction of pointer to single entry in multi-array of doubles
Definition at line 321 of file utilities.h.
References getMultiArrayIndexArray().
template<typename S , typename T > std::vector< S > tudat::utilities::createVectorFromVectorOfPairFirsts (const std::vector< std::pair< S, T > > inputVector)
Definition at line 362 of file utilities.h.
template<typename T , typename S > T tudat::utilities::evaluateFunctionWithoutInputArgumentDependency (boost::function< T() > inputFreeFunction, const S dummyInput)
Definition at line 374 of file utilities.h.
template<typename T > std::vector< int > tudat::utilities::getSortOrderOfVector (const std::vector< T > unsortedVector)
Function to get the order in which the input vector would be sorted (in ascending order). Example: for inout vector (5,2,6,7,4,0), output would be (5,1,4,0,2,3).
Parameters
unsortedVector Vector of which the sort order is to be determined
Returns
Order in which the input vector would be sorted (in ascending order)
Definition at line 387 of file utilities.h.
References getSortOrderOfVectorAndSortedVector().
template<typename VectorArgument , typename KeyType > std::vector< VectorArgument > tudat::utilities::createVectorFromMultiMapValues (const std::multimap< KeyType, VectorArgument > & inputMap)
Function to create a vector from the values of a multimap. The output vector is in the order of the multimap entries, i.e. as provided by a forward iterator. The multimap keys are not used for the return vector.
Parameters
inputMap Original multimap from which the vector is to be created
Returns
Vector created from the multimap values
Definition at line 400 of file utilities.h.
Referenced by getSortOrderOfVectorAndSortedVector().
template<typename VectorArgument , typename KeyType > std::vector< KeyType > tudat::utilities::createVectorFromMultiMapKeys (const std::multimap< KeyType, VectorArgument > & inputMap)
Function to create a vector from the keys of a multimap. The output vector is in the order of the multimap entries, i.e. as provided by a forward iterator. The multimap values are not used for the return vector.
Parameters
inputMap Original multimap from which the vector is to be created
Returns
Vector created from the multimap keys
Definition at line 427 of file utilities.h.
Referenced by getSortOrderOfVectorAndSortedVector().
template<typename T > std::pair< std::vector< int >, std::vector< T > > tudat::utilities::getSortOrderOfVectorAndSortedVector (const std::vector< T > unsortedVector)
Function to get sorted vector of an input vector, as well as the order in which this input has been be sorted (ascending)). Example: for inout vector (5,2,6,7,4,0), output would be [(5,1,4,0,2,3), (0,2,4,5,6,7)].
Parameters
unsortedVector Vector that is to be sorted
Returns
Parit, with first: order in which the input vector is sorted (in ascending order), second: sorted input vector
Definition at line 453 of file utilities.h.
References createVectorFromMultiMapKeys(), and createVectorFromMultiMapValues().
Referenced by getSortOrderOfVector(), and tudat::simulation_setup::getTimeOrderedInformationMatrix().
template<typename T > bool tudat::utilities::doStlVectorContentsMatch (const std::vector< T > & vectorA, const std::vector< T > & vectorB)
Definition at line 465 of file utilities.h.
Referenced by tudat::gravitation::GravityFieldVariationsSet::getDirectTidalGravityFieldVariation().
template<typename MapKey , typename ScalarType > std::map< MapKey, Eigen::Array< ScalarType, Eigen::Dynamic, 1 > > tudat::utilities::convertSTLVectorMapToEigenVectorMap (std::map< MapKey, std::vector< ScalarType > > stlVectorMap)
Definition at line 490 of file utilities.h.