Tudat: tudat::ephemerides::SpiceRotationalEphemeris Class Reference
tudat::ephemerides::SpiceRotationalEphemeris Class Reference
Class to directly calculate rotational state of body from spice kernel(s)
#include <spiceRotationalEphemeris.h>
Public Member Functions
SpiceRotationalEphemeris (const std::string &baseFrameOrientation="ECLIPJ2000", const std::string &targetFrameOrientation="", const double referenceJulianDay=basic_astrodynamics::JULIAN_DAY_ON_J2000)
Constructor for spice ephemeris.
~SpiceRotationalEphemeris ()
Destructor.
Eigen::Matrix3d getDerivativeOfRotationToBaseFrame (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame at specified time, calculated by SPICE sx_form function.
Eigen::Matrix3d getDerivativeOfRotationToTargetFrame (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame at specified time, calculated by SPICE sx_form function.
void getFullRotationalQuantitiesToTargetFrame (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const double secondsSinceEpoch)
Function to calculate the full rotational state at given time.
Eigen::Quaterniond getRotationToBaseFrame (const double secondsSinceEpoch)
Function to calculate the rotation quaternion from target frame to original frame.
Eigen::Quaterniond getRotationToTargetFrame (const double secondsSinceEpoch)
Function to calculate the rotation quaternion from original frame to target frame.
Public Member Functions inherited from tudat::ephemerides::RotationalEphemeris
RotationalEphemeris (const std::string &baseFrameOrientation="", const std::string &targetFrameOrientation="")
Constructor.
virtual ~RotationalEphemeris ()
Virtual destructor.
std::string getBaseFrameOrientation ()
Get base reference frame orientation.
virtual Eigen::Vector3d getRotationalVelocityVectorInBaseFrame (const double secondsSinceEpoch)
Function to retrieve the angular velocity vector, expressed in base frame.
virtual Eigen::Vector3d getRotationalVelocityVectorInTargetFrame (const double secondsSinceEpoch)
Function to retrieve the angular velocity vector, expressed in target frame.
std::string getTargetFrameOrientation ()
Get target reference frame orientation.
Private Attributes
double referenceDayOffSet_
Offset of reference julian day (from J2000) w.r.t. which ephemeris is evaluated.
Additional Inherited Members
Protected Attributes inherited from tudat::ephemerides::RotationalEphemeris
const std::string baseFrameOrientation_
Base reference frame orientation.
const std::string targetFrameOrientation_
Target reference frame orientation.
Detailed Description
Class to directly calculate rotational state of body from spice kernel(s). Note that if an object of this class is called often, it may become a performance bottleneck, using the an interpolated rotation will generally be more efficient, but at the expense of interpolation errors.
Definition at line 33 of file spiceRotationalEphemeris.h.
Constructor & Destructor Documentation
tudat::ephemerides::SpiceRotationalEphemeris::SpiceRotationalEphemeris (const std::string & baseFrameOrientation = "ECLIPJ2000", const std::string & targetFrameOrientation = "", const double referenceJulianDay = basic_astrodynamics::JULIAN_DAY_ON_J2000) inline
Constructor for spice ephemeris, sets frames between which rotation is determined.
Parameters
baseFrameOrientation Base frame identifier.
targetFrameOrientation Target frame identifier.
referenceJulianDay Reference julian day w.r.t. which ephemeris is evaluated.
Definition at line 43 of file spiceRotationalEphemeris.h.
References tudat::physical_constants::JULIAN_DAY, tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000, and referenceDayOffSet_.
tudat::ephemerides::SpiceRotationalEphemeris::~SpiceRotationalEphemeris () inline
Destructor.
Definition at line 56 of file spiceRotationalEphemeris.h.
References getRotationToBaseFrame().
Member Function Documentation
Eigen::Quaterniond tudat::ephemerides::SpiceRotationalEphemeris::getRotationToBaseFrame (const double secondsSinceEpoch) virtual
Function to calculate the rotation quaternion from target frame to original frame at specified time, calculated by call to pxform_c spice function (through computeRotationQuaternionBetweenFrames function)
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated...
Returns
Rotation from target (typically local) to original (typically global) frame at specified time.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 28 of file spiceRotationalEphemeris.cpp.
References tudat::ephemerides::RotationalEphemeris::baseFrameOrientation_, tudat::spice_interface::computeRotationQuaternionBetweenFrames(), referenceDayOffSet_, and tudat::ephemerides::RotationalEphemeris::targetFrameOrientation_.
Referenced by getRotationToTargetFrame(), and ~SpiceRotationalEphemeris().
Eigen::Quaterniond tudat::ephemerides::SpiceRotationalEphemeris::getRotationToTargetFrame (const double secondsSinceEpoch) inline virtual
Function to calculate the rotation quaternion from original frame to target frame at specified time, calculated by call to pxform_c spice function (through computeRotationQuaternionBetweenFrames function)
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated..
Returns
Rotation from original (typically global) to target (typically local) frame at specified time.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 79 of file spiceRotationalEphemeris.h.
References getDerivativeOfRotationToBaseFrame(), and getRotationToBaseFrame().
Eigen::Matrix3d tudat::ephemerides::SpiceRotationalEphemeris::getDerivativeOfRotationToBaseFrame (const double secondsSinceEpoch) virtual
Function to calculate the derivative of the rotation matrix from target frame to original frame.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated..
Returns
Derivative of rotation from target (typically local) to original (typically global) frame at specified time.
Function to calculate the derivative of the rotation matrix from target frame to original frame.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 38 of file spiceRotationalEphemeris.cpp.
References tudat::ephemerides::RotationalEphemeris::baseFrameOrientation_, tudat::spice_interface::computeRotationMatrixDerivativeBetweenFrames(), referenceDayOffSet_, and tudat::ephemerides::RotationalEphemeris::targetFrameOrientation_.
Referenced by getDerivativeOfRotationToTargetFrame(), and getRotationToTargetFrame().
Eigen::Matrix3d tudat::ephemerides::SpiceRotationalEphemeris::getDerivativeOfRotationToTargetFrame (const double secondsSinceEpoch) inline virtual
Function to calculate the derivative of the rotation matrix from original frame to target frame.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated..
Returns
Derivative of rotation from original (typically global) to target (typically local) frame at specified time.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 107 of file spiceRotationalEphemeris.h.
References getDerivativeOfRotationToBaseFrame(), and getFullRotationalQuantitiesToTargetFrame().
void tudat::ephemerides::SpiceRotationalEphemeris::getFullRotationalQuantitiesToTargetFrame (Eigen::Quaterniond & currentRotationToLocalFrame, Eigen::Matrix3d & currentRotationToLocalFrameDerivative, Eigen::Vector3d & currentAngularVelocityVectorInGlobalFrame, const double secondsSinceEpoch) virtual
Function to calculate the full rotational state at given time (rotation matrix, derivative of rotation matrix and angular velocity vector).
Parameters
currentRotationToLocalFrame Current rotation to local frame (returned by reference)
currentRotationToLocalFrameDerivative Current derivative of rotation matrix to local frame (returned by reference)
currentAngularVelocityVectorInGlobalFrame Current angular velocity vector, expressed in global frame (returned by reference)
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated...
Reimplemented from tudat::ephemerides::RotationalEphemeris.
Definition at line 47 of file spiceRotationalEphemeris.cpp.
References tudat::ephemerides::RotationalEphemeris::baseFrameOrientation_, tudat::spice_interface::computeRotationQuaternionAndRotationMatrixDerivativeBetweenFrames(), tudat::ephemerides::getRotationalVelocityVectorInBaseFrameFromMatrices(), referenceDayOffSet_, and tudat::ephemerides::RotationalEphemeris::targetFrameOrientation_.
Referenced by getDerivativeOfRotationToTargetFrame().
Member Data Documentation
double tudat::ephemerides::SpiceRotationalEphemeris::referenceDayOffSet_ private
Definition at line 133 of file spiceRotationalEphemeris.h.
Referenced by getDerivativeOfRotationToBaseFrame(), getFullRotationalQuantitiesToTargetFrame(), getRotationToBaseFrame(), and SpiceRotationalEphemeris().
The documentation for this class was generated from the following files:
External/SpiceInterface/spiceRotationalEphemeris.h
External/SpiceInterface/spiceRotationalEphemeris.cpp