Tudat: tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType > Class Template Reference
tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType > Class Template Reference
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with MEE.
#include <nBodyGaussModifiedEquinoctialStateDerivative.h>
Public Member Functions
NBodyGaussModifiedEquinictialStateDerivative (const basic_astrodynamics::AccelerationMap &accelerationModelsPerBody, const boost::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const std::vector< std::string > &bodiesToIntegrate, const std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > &initialKeplerElements)
Constructor.
~NBodyGaussModifiedEquinictialStateDerivative ()
Destructor.
void calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative)
Calculates the state derivative of the translational motion of the system, using the Gauss equations for MEE.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &cartesianSolution, const TimeType &time)
Function to convert the state in the conventional form to the Modified Equinoctial Elements form.
void convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton)
Function to convert the MEE states of the bodies to the conventional form.
basic_astrodynamics::AccelerationMap getFullAccelerationsMap ()
Function to get the acceleration models.
Public Member Functions inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
NBodyStateDerivative (const basic_astrodynamics::AccelerationMap &accelerationModelsPerBody, const boost::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const TranslationalPropagatorType propagatorType, const std::vector< std::string > &bodiesToIntegrate)
From this constructor, the object for generating the state derivative is created.
virtual ~NBodyStateDerivative ()
Destructor.
virtual void clearDerivedTranslationalStateDerivativeModel ()
Function to clear any reference/cached values of state derivative model.
void clearStateDerivativeModel ()
Function to clear reference/cached values of translational state derivative model.
void clearTranslationalStateDerivativeModel ()
Function to clear reference/cached values of acceleration models.
void convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton)
Function to convert the propagator-specific form of the state to the conventional form in the global frame.
basic_astrodynamics::AccelerationMap getAccelerationsMap ()
Function to retrieve the map containing the list of accelerations acting on each body.
std::vector< std::string > getBodiesToBeIntegratedNumerically ()
Function to get list of names of bodies that are to be integrated numerically.
boost::shared_ptr< CentralBodyData< StateScalarType, TimeType > > getCentralBodyData ()
Function to get object providing the current integration origins.
TranslationalPropagatorType getPropagatorType ()
Function to get type of propagator that is to be used (i.e. Cowell, Encke, etc.)
int getStateSize ()
Function to return the size of the state handled by the object.
Eigen::Vector3d getTotalAccelerationForBody (const std::string &bodyName)
Function to retrieve the total acceleration acting on a given body.
void updateStateDerivativeModel (const TimeType currentTime)
Function to update the state derivative model to the current time.
Public Member Functions inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
SingleStateTypeDerivative (const IntegratedStateType integratedStateType)
Constructor.
virtual ~SingleStateTypeDerivative ()
Virtual destructor.
IntegratedStateType getIntegratedStateType ()
Function to return the type of dynamics for which the state derivative is calculated.
Private Attributes
std::vector< boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > centralAccelerations_
Central body accelerations for each propagated body, which has been removed from accelerationModelsPerBody_.
std::vector< boost::function< double() > > centralBodyGravitationalParameters_
Gravitational parameters of central bodies used to convert Cartesian to Keplerian orbits, and vice versa.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > currentCartesianLocalSoluton_
Current full Cartesian state of the propagated bodies, w.r.t. trhe central bodies.
std::vector< bool > flipSingularities_
basic_astrodynamics::AccelerationMap originalAccelerationModelsPerBody_
List of acceleration models, including the central body accelerations thta are removed in this propagation scheme.
Additional Inherited Members
Protected Member Functions inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
void createAccelerationModelList ()
void sumStateDerivativeContributions (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative, const bool addPositionDerivatives=true)
Function to get the state derivative of the system in Cartesian coordinates.
Protected Attributes inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
std::vector< boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > accelerationModelList_
Vector of acceleration models, containing all entries of accelerationModelsPerBody_.
basic_astrodynamics::AccelerationMap accelerationModelsPerBody_
A map containing the list of accelerations acting on each body,.
std::vector< std::string > bodiesToBeIntegratedNumerically_
List of names of bodies that are to be integrated numerically.
std::vector< int > bodyOrder_
boost::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData_
Object responsible for providing the current integration origins from the global origins.
std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > centralBodyInertialStates_
List of states of teh central bodies of the propagated bodies.
std::unordered_map< std::string, std::vector< boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > >::iterator innerAccelerationIterator
Predefined iterator to save (de-)allocation time.
std::unordered_map< std::string, std::unordered_map< std::string, std::vector< boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > > >::iterator outerAccelerationIterator
Predefined iterator to save (de-)allocation time.
TranslationalPropagatorType propagatorType_
Type of propagator that is to be used (i.e. Cowell, Encke, etc.)
Protected Attributes inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
IntegratedStateType integratedStateType_
Type of dynamics for whichh the state derivative is calculated.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with Modified Equinoctial elements (MEE). In this method, the derivative of the MEE are computed from the total Cartesian accelerations, with the MEE of the bodies the states being numerically propagated.
Definition at line 46 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
Constructor & Destructor Documentation
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::NBodyGaussModifiedEquinictialStateDerivative (const basic_astrodynamics::AccelerationMap & accelerationModelsPerBody, const boost::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const std::vector< std::string > & bodiesToIntegrate, const std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > & initialKeplerElements) inline
Constructor
Parameters
accelerationModelsPerBody A map containing the list of accelerations acting on each body, identifying the body being acted on and the body acted on by an acceleration. The map has as key a string denoting the name of the body the list of accelerations, provided as the value corresponding to a key, is acting on. This map-value is again a map with string as key, denoting the body exerting the acceleration, and as value a pointer to an acceleration model.
centralBodyData Object responsible for providing the current integration origins from the global origins.
bodiesToIntegrate List of names of bodies that are to be integrated numerically.
initialKeplerElements Kepler elements of bodiesToIntegrate, at initial propagation time
Definition at line 64 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::accelerationModelsPerBody_, tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::createAccelerationModelList(), tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::flipSingularities_, tudat::orbital_element_conversions::inclinationIndex, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_, tudat::mathematical_constants::PI, and tudat::propagators::removeCentralGravityAccelerations().
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::~NBodyGaussModifiedEquinictialStateDerivative () inline
Definition at line 107 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
Member Function Documentation
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative) inline virtual
Calculates the state derivative of the translational motion of the system, using the Gauss equations for modified equinoctial elements. The input is the current state in modified equinoctial elememts. The state derivate of this set is computed. TO do so the accelerations are internally transformed into the RSW frame, using the current Cartesian state as set by the last call to the convertToOutputSolution function
Parameters
time Time (TDB seconds since J2000) at which the system is to be updated.
stateOfSystemToBeIntegrated List of 6 * bodiesToBeIntegratedNumerically_.size(), containing modified equinoctial elements of the bodies being integrated. The order of the values is defined by the order of bodies in bodiesToBeIntegratedNumerically_
stateDerivative Current derivative of the modified equinoctial elements of the system of bodies integrated numerically (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 122 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::computeGaussPlanetaryEquationsForModifiedEquinoctialElements(), tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSoluton_, tudat::reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrx(), and tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::sumStateDerivativeContributions().
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & cartesianSolution, const TimeType & time) inline virtual
Function to convert the state in the conventional form to the propagator-specific form. For the Gauss-MEE propagator, this transforms the Cartesian state w.r.t. the central body (conventional form) to the Modified Equinoctial Elements
Parameters
cartesianSolution State in 'conventional form'
time Current time at which the state is valid, used to computed Kepler orbits
Returns
State (outputSolution), converted to the Modified Equinoctial Elements
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 154 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, and tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::flipSingularities_.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton) inline virtual
Function to convert the Modified Equinoctial Elements state to the conventional form. For the Gauss-MEE propagator, this transforms Modfied Equinoctial Elements w.r.t. the central bodies to the Cartesian states w.r.t. these same central bodies: In contrast to the convertCurrentStateToGlobalRepresentation function, this function does not provide the state in the inertial frame, but instead provides it in the frame in which it is propagated.
Parameters
internalSolution State in Modified Equinoctial Elemements (i.e. form that is used in numerical integration)
time Current time at which the state is valid
currentCartesianLocalSoluton State (internalSolution, which is Encke-formulation), converted to the 'conventional form' (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 187 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSoluton_, and tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::flipSingularities_.
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::AccelerationMap tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::getFullAccelerationsMap () inline virtual
Function to get the acceleration models, including the central body accelerations that are removed for the Gauss propagation scheme
Returns
List of acceleration models, including the central body accelerations that are removed in this propagation scheme.
Reimplemented from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >.
Definition at line 209 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
References tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_.
Member Data Documentation
template<typename StateScalarType = double, typename TimeType = double> std::vector< boost::function< double() > > tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_ private
Definition at line 217 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
Referenced by tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), and tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::NBodyGaussModifiedEquinictialStateDerivative().
template<typename StateScalarType = double, typename TimeType = double> std::vector< boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::centralAccelerations_ private
Definition at line 221 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::AccelerationMap tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_ private
Definition at line 224 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
Referenced by tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::getFullAccelerationsMap(), and tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::NBodyGaussModifiedEquinictialStateDerivative().
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSoluton_ private
Current full Cartesian state of the propagated bodies, w.r.t. trhe central bodies. These variables are set when calling the convertToOutputSolution function.
Definition at line 231 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
Referenced by tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::convertToOutputSolution().
template<typename StateScalarType = double, typename TimeType = double> std::vector< bool > tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::flipSingularities_ private
List of booleans to denote, per propagated body, if the singularity in the MEE equations it o be flipped to 0 inclination (if true) or if it remains at 180 degree inclination (if false)
Definition at line 235 of file nBodyGaussModifiedEquinoctialStateDerivative.h.
Referenced by tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), and tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::NBodyGaussModifiedEquinictialStateDerivative().
The documentation for this class was generated from the following file:
Astrodynamics/Propagators/nBodyGaussModifiedEquinoctialStateDerivative.h