Tudat: tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType > Class Template Reference
tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType > Class Template Reference
Cubic spline interpolator, implementation from (Press W.H., et al., 2002).
#include <cubicSplineInterpolator.h>
Public Member Functions
CubicSplineInterpolator (const std::vector< IndependentVariableType > &independentVariables, const std::vector< DependentVariableType > &dependentVariables, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Cubic spline interpolator constructor.
CubicSplineInterpolator (const std::vector< IndependentVariableType > &independentVariables, const std::vector< DependentVariableType > &dependentVariables, const AvailableLookupScheme selectedLookupScheme, const BoundaryInterpolationType boundaryHandling, const DependentVariableType &defaultExtrapolationValue)
Cubic spline interpolator constructor.
CubicSplineInterpolator (const std::map< IndependentVariableType, DependentVariableType > dataMap, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Cubic spline interpolator constructor.
CubicSplineInterpolator (const std::map< IndependentVariableType, DependentVariableType > dataMap, const AvailableLookupScheme selectedLookupScheme, const BoundaryInterpolationType boundaryHandling, const DependentVariableType &defaultExtrapolationValue)
Cubic spline interpolator constructor.
~CubicSplineInterpolator ()
Destructor.
DependentVariableType interpolate (const IndependentVariableType targetIndependentVariableValue)
Interpolate.
Public Member Functions inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
OneDimensionalInterpolator (const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Constructor.
OneDimensionalInterpolator (const BoundaryInterpolationType boundaryHandling, const DependentVariableType &defaultExtrapolationValue)
Constructor.
virtual ~OneDimensionalInterpolator ()
Destructor.
std::vector< DependentVariableType > getDependentValues ()
Function to return the ector with dependent variables used by the interpolator.
std::vector< IndependentVariableType > getIndependentValues ()
Function to return the ector with independent variables used by the interpolator.
std::shared_ptr< LookUpScheme< IndependentVariableType > > getLookUpScheme ()
Function to return the lookup scheme used by the interpolator.
int getNumberOfDimensions ()
Function to return the number of independent variables of the interpolation.
virtual DependentVariableType interpolate (const std::vector< IndependentVariableType > &independentVariableValues)
Function to perform interpolation.
DependentVariableType interpolateNonConst (IndependentVariableType independentVariableValue)
Function to perform interpolation, with non-const input argument.
Public Member Functions inherited from tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >
virtual ~Interpolator ()
Destructor.
Private Member Functions
void calculateSecondDerivatives ()
Calculates the second derivatives of the curve.
Private Attributes
unsigned int numberOfDataPoints_
The number of datapoints.
std::vector< DependentVariableType > secondDerivativeOfCurve_
Vector filled with second derivative of curvature of each point.
DependentVariableType zeroValue_
Zero value of independent variable type.
Additional Inherited Members
Protected Member Functions inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
void checkBoundaryCase (DependentVariableType &dependentVariable, bool &useValue, const IndependentVariableType &targetIndependentVariable)
Function to check whether boundary handling needs to be applied, depending on method chosen.
int checkInterpolationBoundary (const IndependentVariableType &targetIndependentVariable)
Function to return the condition of the current independent variable.
void makeLookupScheme (const AvailableLookupScheme selectedScheme)
Make look-up scheme that is to be used.
Protected Attributes inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
BoundaryInterpolationType boundaryHandling_
Behavior of interpolator when independent variable is outside range.
std::pair< DependentVariableType, DependentVariableType > defaultExtrapolationValue_
Default value to be used for extrapolation.
std::vector< DependentVariableType > dependentValues_
Vector with dependent variables.
std::vector< IndependentVariableType > independentValues_
Vector with independent variables.
std::shared_ptr< LookUpScheme< IndependentVariableType > > lookUpScheme_
Pointer to look up scheme.
Detailed Description
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType>
class tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >
Cubic spline interpolator, implementation from (Press W.H., et al., 2002). Natural boundary conditions are imposed, meaning zero second derivatives (curvature) at end points. Continuity of first derivatives is imposed.
Template Parameters
IndependentVariableType Type of independent variables.
DependentVariableType Type of dependent variables.
Definition at line 107 of file cubicSplineInterpolator.h.
Constructor & Destructor Documentation
CubicSplineInterpolator() [1/4]
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::CubicSplineInterpolator (const std::vector< IndependentVariableType > & independentVariables, const std::vector< DependentVariableType > & dependentVariables, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm, const BoundaryInterpolationType boundaryHandling = extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > & defaultExtrapolationValue = std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >())) inline
Cubic spline interpolator constructor taking separate vectors of dependent and independent variable values.
Parameters
independentVariables Vector with the independent variable values, must be sorted in ascending order.
dependentVariables Vector with the dependent variable values.
selectedLookupScheme Look-up scheme that is to be used when finding interval of requested independent variable value.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 134 of file cubicSplineInterpolator.h.
References tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::calculateSecondDerivatives(), tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::makeLookupScheme(), and tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::zeroValue_.
CubicSplineInterpolator() [2/4]
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::CubicSplineInterpolator (const std::vector< IndependentVariableType > & independentVariables, const std::vector< DependentVariableType > & dependentVariables, const AvailableLookupScheme selectedLookupScheme, const BoundaryInterpolationType boundaryHandling, const DependentVariableType & defaultExtrapolationValue) inline
Cubic spline interpolator constructor taking separate vectors of dependent and independent variable values. This constructor takes a single default value, instead of a pair.
Parameters
independentVariables Vector with the independent variable values, must be sorted in ascending order.
dependentVariables Vector with the dependent variable values.
selectedLookupScheme Look-up scheme that is to be used when finding interval of requested independent variable value.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Default value to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 189 of file cubicSplineInterpolator.h.
CubicSplineInterpolator() [3/4]
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::CubicSplineInterpolator (const std::map< IndependentVariableType, DependentVariableType > dataMap, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm, const BoundaryInterpolationType boundaryHandling = extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > & defaultExtrapolationValue = std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >())) inline
Cubic spline interpolator constructor taking single map of independent and dependent variable values.
Parameters
dataMap Map with the independent variable values as keys and corresponding dependent variable values as values.
selectedLookupScheme Lookup scheme that is to be used when finding interval of requested independent variable value.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 211 of file cubicSplineInterpolator.h.
References tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::calculateSecondDerivatives(), tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::makeLookupScheme(), and tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::zeroValue_.
CubicSplineInterpolator() [4/4]
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::CubicSplineInterpolator (const std::map< IndependentVariableType, DependentVariableType > dataMap, const AvailableLookupScheme selectedLookupScheme, const BoundaryInterpolationType boundaryHandling, const DependentVariableType & defaultExtrapolationValue) inline
Cubic spline interpolator constructor taking single map of independent and dependent variable values. This constructor takes a single default value, instead of a pair.
Parameters
dataMap Map with the independent variable values as keys and corresponding dependent variable values as values.
selectedLookupScheme Lookup scheme that is to be used when finding interval of requested independent variable value.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Default value to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 262 of file cubicSplineInterpolator.h.
~CubicSplineInterpolator()
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::~CubicSplineInterpolator () inline
Definition at line 272 of file cubicSplineInterpolator.h.
Member Function Documentation
interpolate()
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> DependentVariableType tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::interpolate (const IndependentVariableType targetIndependentVariableValue) inline virtual
Executes interpolation of data at a given target value of the independent variable, to yield an interpolated value of the dependent variable.
Parameters
targetIndependentVariableValue Target independent variable value at which point the interpolation is performed.
Returns
Interpolated dependent variable value.
Implements tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >.
Definition at line 282 of file cubicSplineInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::checkBoundaryCase(), tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::lookUpScheme_, and tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::secondDerivativeOfCurve_.
calculateSecondDerivatives()
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> void tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::calculateSecondDerivatives () inline private
This function calculates the second derivatives of the curve at the nodes, assuming the first derivatives to be continuous at the nodes and imposing natural spline conditions (zero curvature at endpoints). The methodology is described in (Press W.H., et al., 2002).
Definition at line 334 of file cubicSplineInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::numberOfDataPoints_, tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::secondDerivativeOfCurve_, and tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::zeroValue_.
Referenced by tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::CubicSplineInterpolator().
Member Data Documentation
secondDerivativeOfCurve_
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> std::vector< DependentVariableType > tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::secondDerivativeOfCurve_ private
Definition at line 404 of file cubicSplineInterpolator.h.
Referenced by tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::calculateSecondDerivatives(), and tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::interpolate().
numberOfDataPoints_
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> unsigned int tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::numberOfDataPoints_ private
Definition at line 407 of file cubicSplineInterpolator.h.
Referenced by tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::calculateSecondDerivatives().
zeroValue_
template<typename IndependentVariableType, typename DependentVariableType, typename ScalarType = IndependentVariableType> DependentVariableType tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::zeroValue_ private
Definition at line 410 of file cubicSplineInterpolator.h.
Referenced by tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::calculateSecondDerivatives(), and tudat::interpolators::CubicSplineInterpolator< IndependentVariableType, DependentVariableType, ScalarType >::CubicSplineInterpolator().
The documentation for this class was generated from the following file:
Mathematics/Interpolators/cubicSplineInterpolator.h