Tudat: tudat::basic_astrodynamics Namespace Reference
tudat::basic_astrodynamics Namespace Reference
Classes
class AccelerationModel
Base class for (translational) acceleration models.
class BodyShapeModel
Base class for body shape models.
class CustomMassRateModel
Derived class for determining the rate of change of a body's mass, user-defined by a function pointer.
class CustomTorque
Class to link the a custom torque model to a body.
class EmpiricalAcceleration
Class for calculating an empirical acceleration, based on a once per orbit model, (Montenbruck and Gill, 2000)
class MassRateModel
Base class for determining the rate of change of a body's mass, to be used in numerical integration.
class OblateSpheroidBodyShapeModel
Body shape model for an oblate spheroid.
class SphericalBodyShapeModel
Body shape model defined as a sphere.
class TorqueModel
Pure virtual base class for a model that computes the torque acting on a body.
Typedefs
typedef std::unordered_map< std::string, SingleBodyAccelerationMap > AccelerationMap
typedef AccelerationModel< Eigen::Vector2d > AccelerationModel2d
Typedef to a 2D acceleration model.
typedef std::shared_ptr< AccelerationModel2d > AccelerationModel2dPointer
Typedef for shared-pointer to a 2D acceleration model.
typedef AccelerationModel< > AccelerationModel3d
Typedef to a 3D acceleration model.
typedef std::shared_ptr< AccelerationModel3d > AccelerationModel3dPointer
Typedef for shared-pointer to a 3D acceleration model.
typedef std::map< std::string, std::vector< std::shared_ptr< MassRateModel > > > MassRateModelMap
Typedef for the massrate model map.
typedef std::unordered_map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > > SingleBodyAccelerationMap
typedef std::map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::TorqueModel > > > SingleBodyTorqueModelMap
Typedef for list of torques acting on a body (map key is body exerting torque).
typedef std::map< std::string, SingleBodyTorqueModelMap > TorqueModelMap
Typedef for list of torques acting on a set of bodies (map key is body undergoing torque).
Enumerations
enum AvailableAcceleration {
undefined_acceleration, point_mass_gravity, central_gravity = point_mass_gravity, aerodynamic,
cannon_ball_radiation_pressure, spherical_harmonic_gravity, mutual_spherical_harmonic_gravity, third_body_point_mass_gravity,
third_body_central_gravity = third_body_point_mass_gravity, third_body_spherical_harmonic_gravity, third_body_mutual_spherical_harmonic_gravity, thrust_acceleration,
relativistic_correction_acceleration, empirical_acceleration, direct_tidal_dissipation_in_central_body_acceleration, direct_tidal_dissipation_in_orbiting_body_acceleration
}
List of accelerations available in simulations.
enum AvailableMassRateModels { undefined_mass_rate_model, custom_mass_rate_model, from_thrust_mass_rate_model }
List of model types for body mass rates.
enum AvailableTorque { underfined_torque = -1, second_order_gravitational_torque = 0, aerodynamic_torque = 1 }
List of torques available in simulations.
enum EmpiricalAccelerationComponents { radial_empirical_acceleration_component = 0, along_track_empirical_acceleration_component = 1, across_track_empirical_acceleration_component = 2 }
Enum defining component of empirical accelerations.
enum EmpiricalAccelerationFunctionalShapes { constant_empirical = 0, sine_empirical = 1, cosine_empirical = 2 }
Enum defining shape of empirical accelerations.
enum IAUConventions { iau_2000_a, iau_2000_b, iau_2006 }
Enum of IAU conventions for Earth rotation.
enum TimeScales {
dummy_scale = -1, tai_scale = 0, tt_scale = 1, tdb_scale = 2,
utc_scale = 3, ut1_scale = 4, body_centered_coordinate_time_scale = 5, barycentric_coordinate_time_scale = 6,
local_proper_time_scale = 7
}
List of time scales available.
Functions
double approximateConvertTTtoTDB (const double ttSecondsSinceJ2000)
Perform apprixmate conversion of TT to TDB.
template<typename TimeScalarType >
TimeScalarType calculateJulianDaySinceEpoch (const boost::gregorian::date calendarDate, const TimeScalarType fractionOfDay, const TimeScalarType epochSinceJulianDayZero=JULIAN_DAY_ON_J2000)
Function to convert gregorian calendar date and fraction of day to a number of julian days since a reference epoch.
double calculateSecondsInCurrentJulianDay (const double julianDay)
Determine number of seconds into current day of given time.
double computeKeplerAngularMomentum (const double semiMajorAxis, const double eccentricity, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody)
Compute Kepler angular momentum.
double computeKeplerEnergy (const double semiMajorAxis, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody)
Compute Kepler orbital energy.
double computeKeplerMeanMotion (const double semiMajorAxis, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody)
Compute Kepler mean motion.
double computeKeplerOrbitalPeriod (const double semiMajorAxis, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody)
Compute Kepler orbital period.
double computeKeplerOrbitalVelocity (const double semiMajorAxis, const double eccentricity, const double trueAnomaly, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody)
Compute two-body orbital velocity with vis-viva equation.
double computeKeplerOrbitalVelocity (const Eigen::Vector6d &keplerianElements, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody)
Compute two-body orbital velocity with vis-viva equation.
double computeKeplerRadialDistance (const double semiMajorAxis, const double eccentricity, const double trueAnomaly)
Compute two-body radial distance.
double computeKeplerRadialDistance (const Eigen::Vector6d &keplerianElements)
Compute two-body radial distance.
double computePeriapsisAltitudeFromCartesianState (const Eigen::Vector6d &state, const double centralBodyGravitationalParameter, const double centralBodyRadius)
Compute periapsis altitude from Cartesian state for spherical central body.
double computePeriapsisAltitudeFromKeplerianState (const Eigen::Vector6d &state, const double centralBodyRadius)
Compute periapsis altitude from Keplerian state for spherical central body.
double computeSynodicPeriod (const double orbitalPeriodBody1, const double orbitalPeriodBody2)
Compute synodic period.
template<typename TimeScalarType = double>
TimeScalarType convertCalendarDateToJulianDay (const int calendarYear, const int calendarMonth, const int calendarDay, const int calendarHour, const int calendarMinutes, const TimeScalarType calendarSeconds)
Compute Julian day from given date and time.
template<typename TimeScalarType = double>
TimeScalarType convertCalendarDateToJulianDaysSinceEpoch (const int calendarYear, const int calendarMonth, const int calendarDay, const int calendarHour, const int calendarMinutes, const TimeScalarType calendarSeconds, const TimeScalarType referenceJulianDay)
Compute Julian day from given date and time.
int convertDayMonthYearToDayOfYear (const int day, const int month, const int year)
Determine number of full days that have passed in current year.
int convertDayMonthYearToDayOfYear (const boost::gregorian::date calendarDate)
Determine number of full days that have passed in current year.
boost::gregorian::date convertJulianDayToCalendarDate (const double julianDay)
Function to convert julian day to gregorian calendar date.
template<typename TimeScalarType >
TimeScalarType convertJulianDayToModifiedJulianDay (const TimeScalarType julianDay)
Function to convert julian day to modified julian day.
template<typename TimeScalarType = double>
TimeScalarType convertJulianDayToSecondsSinceEpoch (const TimeScalarType julianDay, const TimeScalarType epochSinceJulianDayZero=getJulianDayOnJ2000< TimeScalarType >())
Compute number of seconds since a reference Julian day.
template<typename TimeScalarType >
TimeScalarType convertModifiedJulianDayToJulianDay (const TimeScalarType modifiedJulianDay)
Function to convert modified julian dat to julian day.
template<typename TimeScalarType = double>
TimeScalarType convertSecondsSinceEpochToJulianCenturiesSinceEpoch (const TimeScalarType secondsSinceEpoch)
Function to convert the number of seconds since some reference julian day to a julian century since that epoch.
template<typename TimeScalarType = double>
TimeScalarType convertSecondsSinceEpochToJulianDay (const TimeScalarType secondsSinceEpoch, const TimeScalarType epochSinceJulianDayZero=getJulianDayOnJ2000< TimeScalarType >())
Compute Julian day from seconds since reference Julian day epoch.
template<typename TimeScalarType = double>
TimeScalarType convertSecondsSinceEpochToJulianYearsSinceEpoch (const TimeScalarType secondsSinceEpoch)
Function to convert the number of seconds since some reference julian day to a julian day since that epoch.
template<typename TimeType >
TimeType convertTAItoTT (const TimeType taiTime)
Function to convert TAI to TT.
template<typename TimeType >
TimeType convertTcbToTdb (const TimeType tcbTime)
Function to convert TCB to TDB times scale.
template<typename TimeType >
TimeType convertTcgToTt (const TimeType tcgTime)
Function to convert TCG to TT times scale.
template<typename TimeType >
TimeType convertTdbToTcb (const TimeType tdbTime)
Function to convert TDB to TCB times scale.
template<typename TimeType >
TimeType convertTTtoTAI (const TimeType ttTime)
Function to convert TT to TAI.
template<typename TimeType >
TimeType convertTtToTcg (const TimeType ttTime)
Function to convert TT to TCG times scale.
boost::gregorian::date convertYearAndDaysInYearToDate (const int year, const int daysInYear)
Function to create the calendar date from the year and the number of days in the year.
void from_json (const nlohmann::json &jsonObject, AvailableTorque &torqueType)
Convert json to AvailableTorque.
void from_json (const nlohmann::json &jsonObject, AvailableMassRateModels &massRateType)
Convert json to AvailableMassRateModels.
void from_json (const nlohmann::json &jsonObject, AvailableAcceleration &accelerationType)
Convert json to AvailableAcceleration.
void from_json (const nlohmann::json &jsonObject, IAUConventions &conventionType)
Convert json to IAUConventions.
std::string getAccelerationModelName (const AvailableAcceleration accelerationType)
Function to get a string representing a 'named identification' of an acceleration type.
std::vector< std::shared_ptr< AccelerationModel3d > > getAccelerationModelsOfType (const std::vector< std::shared_ptr< AccelerationModel3d > > &fullList, const AvailableAcceleration modelType)
Function to get all acceleration models of a given type from a list of models.
AvailableAcceleration getAccelerationModelType (const std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel)
Function to identify the derived class type of an acceleration model.
double getAltitudeFromNonBodyFixedPosition (const std::shared_ptr< BodyShapeModel > bodyShapeModel, const Eigen::Vector3d &position, const Eigen::Vector3d &bodyPosition, const Eigen::Quaterniond &toBodyFixedFrame)
Function to calculate the altitude of a point over a central body from positions of both the point and the body (in any frame).
double getAltitudeFromNonBodyFixedPositionFunctions (const std::shared_ptr< BodyShapeModel > bodyShapeModel, const Eigen::Vector3d &position, const std::function< Eigen::Vector3d() > bodyPositionFunction, const std::function< Eigen::Quaterniond() > toBodyFixedFrameFunction)
Function to calculate the altitude of a point over a central body from positions of both the point and the body (in any frame).
AvailableAcceleration getAssociatedThirdBodyAcceleration (const AvailableAcceleration accelerationType)
Function to get the third-body counterpart of a direct gravitational acceleration type.
int getDaysInMonth (const int month, const int year)
Function that returns number of days in given month number.
std::string getEmpiricalAccelerationFunctionalShapeString (const EmpiricalAccelerationFunctionalShapes functionalShape)
template<typename TimeType >
TimeType getJulianDayOnJ2000 ()
Function to get the Julian day on J2000.
template<>
double getJulianDayOnJ2000< double > ()
Function to get the Julian day on J2000, in double precision.
template<>
long double getJulianDayOnJ2000< long double > ()
Function to get the Julian day on J2000, in long double precision.
template<typename TimeType >
TimeType getJulianDayOnMjd0 ()
Function to get the Julian day on zero modified Julian day.
template<>
double getJulianDayOnMjd0< double > ()
Function to get the Julian day on zero modified Julian day, in double precision.
template<>
long double getJulianDayOnMjd0< long double > ()
Function to get the Julian day on zero modified Julian day, in long double precision.
AvailableMassRateModels getMassRateModelType (const std::shared_ptr< MassRateModel > massRateModel)
Function to identify the type of a mass rate model.
template<typename TimeType >
TimeType getTdbSecondsOffsetAtSynchronization ()
Function to get the difference between TDB and (TT, TCB and TCB) at TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION.
template<>
double getTdbSecondsOffsetAtSynchronization< double > ()
template<>
long double getTdbSecondsOffsetAtSynchronization< long double > ()
template<typename TimeType >
TimeType getTimeOfTaiSynchronizationJulianDay ()
Function to get the synchronization Julian day of TT, TCG, and TCB.
template<>
double getTimeOfTaiSynchronizationJulianDay< double > ()
Function to get the synchronization Julian day of TT, TCG, and TCB, in double precision.
template<>
long double getTimeOfTaiSynchronizationJulianDay< long double > ()
Function to get the synchronization Julian day of TT, TCG, and TCB, in long double precision.
template<typename TimeType >
TimeType getTimeOfTaiSynchronizationSinceJ2000 ()
Function to get the synchronization time of TT, TCG, and TCB, in seconds since J2000.
std::string getTorqueModelName (const AvailableTorque torqueType)
Function to get a string representing a 'named identification' of an torque type.
std::vector< std::shared_ptr< TorqueModel > > getTorqueModelsOfType (const std::vector< std::shared_ptr< TorqueModel > > &fullList, const AvailableTorque modelType)
Function to get all torque models of a given type from a list of models.
AvailableTorque getTorqueModelType (std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel)
Function to identify the derived class type of a torque model.
template<typename TimeType >
TimeType getTTMinusTai ()
Function to get the offset of TT from TAI (constant by definition)
template<>
double getTTMinusTai< double > ()
Function to get the offset of TT from TAI (constant by definition), in double precision.
template<>
long double getTTMinusTai< long double > ()
Function to get the offset of TT from TAI (constant by definition), in long double precision.
template<>
Time getTTMinusTai< Time > ()
Function to get the offset of TT from TAI (constant by definition), in Time format.
bool isAccelerationDirectGravitational (const AvailableAcceleration accelerationType)
Function to check whether an acceleration type is a direct gravitational acceleration.
bool isAccelerationFromThirdBody (const AvailableAcceleration accelerationType)
Function to check whether an acceleration type is a third-body gravitational acceleration.
bool isLeapYear (const int year)
Function to determine whether the given year is a leap year (i.e. has 366 days)
Eigen::Vector6d propagateClohessyWiltshire (const Eigen::Vector6d &initialState, const double propagationDuration, const double centralBodyGravitationalParameter, const double referenceOrbitRadius)
Propagate linearized relative motion.
void to_json (nlohmann::json &jsonObject, const AvailableTorque &torqueType)
Convert AvailableTorque to json.
void to_json (nlohmann::json &jsonObject, const AvailableMassRateModels &massRateType)
Convert AvailableMassRateModels to json.
void to_json (nlohmann::json &jsonObject, const AvailableAcceleration &accelerationType)
Convert AvailableAcceleration to json.
void to_json (nlohmann::json &jsonObject, const IAUConventions &conventionType)
Convert IAUConventions to json.
template<typename AccelerationDataType >
AccelerationDataType updateAndGetAcceleration (const std::shared_ptr< AccelerationModel< AccelerationDataType > > accelerationModel, const double currentTime=TUDAT_NAN)
Update the members of an acceleration model and evaluate the acceleration.
Variables
static std::map< AvailableAcceleration, std::string > accelerationTypes
Map of AvailableAccelerations string representations.
static const double JULIAN_DAY_AT_0_MJD = 2400000.5
Julian day at Modified Julain Date 0, i.e. Nov 17, 1858, 00:00.
static const long double JULIAN_DAY_AT_0_MJD_LONG = 2400000.5L
Julian day at Modified Julain Date 0, i.e. Nov 17, 1858, 00:00, in long double precision.
static const double JULIAN_DAY_ON_J2000 = 2451545.0
Julian day at J2000, i.e. 01-01-2000, at 12:00 (in TT).
static const long double JULIAN_DAY_ON_J2000_LONG = 2451545.0L
Julian day at J2000, i.e. 01-01-2000, at 12:00 (in TT), in long double precision.
static std::map< AvailableMassRateModels, std::string > massRateTypes
Map of AvailableMassRateModels string representations.
static std::map< IAUConventions, std::string > precessionNutationConventions
Map of RotationModelTypes string representations.
static const double TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION = 2443144.5003725
Julian day at which TT, TCG, and TCB all show exact same time (1977 January 1, 00:00:32.184)
static const long double TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION_LONG = 2443144.5003725L
Julian day at which TT, TCG, and TCB all show exact same time (1977 January 1, 00:00:32.184), in long double precision.
static const double TDB_SECONDS_OFFSET_AT_SYNCHRONIZATION = -6.55E-5
Difference between TDB and (TT, TCB and TCB) at TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION.
static const double TDB_SECONDS_OFFSET_AT_SYNCHRONIZATION_LONG = -6.55E-5L
Difference between TDB and (TT, TCB and TCB) at TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION, in the requested time type.
static std::map< AvailableTorque, std::string > torqueTypes
Map of AvailableTorques string representations.
static const double TT_MINUS_TAI = 32.184
Offset of TT from TAI (constant by definition).
static const double TT_MINUS_TAI_LONG = 32.184L
Offset of TT from TAI (constant by definition), in long double precision.
static std::vector< AvailableAcceleration > unsupportedAccelerationTypes
AvailableAccelerations not supported by json_interface.
static std::vector< AvailableMassRateModels > unsupportedMassRateType
AvailableMassRateModels not supported by json_interface.
static std::vector< AvailableTorque > unsupportedTorqueTypes = { }
AvailableTorques not supported by json_interface.
Typedef Documentation
AccelerationModel3d
typedef AccelerationModel< > tudat::basic_astrodynamics::AccelerationModel3d
Definition at line 100 of file accelerationModel.h.
AccelerationModel3dPointer
typedef std::shared_ptr< AccelerationModel3d > tudat::basic_astrodynamics::AccelerationModel3dPointer
Definition at line 103 of file accelerationModel.h.
AccelerationModel2d
typedef AccelerationModel< Eigen::Vector2d > tudat::basic_astrodynamics::AccelerationModel2d
Definition at line 107 of file accelerationModel.h.
AccelerationModel2dPointer
typedef std::shared_ptr< AccelerationModel2d > tudat::basic_astrodynamics::AccelerationModel2dPointer
Definition at line 110 of file accelerationModel.h.
SingleBodyAccelerationMap
typedef std::unordered_map< std::string, std::vector<std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > > tudat::basic_astrodynamics::SingleBodyAccelerationMap
Typedef defining a list of accelerations acting on a single body, key is the name of each body exerting a acceletation, value is a list of accelerations exerted by that body.
Definition at line 142 of file accelerationModel.h.
AccelerationMap
typedef std::unordered_map< std::string, SingleBodyAccelerationMap > tudat::basic_astrodynamics::AccelerationMap
Typedef defining a list of accelerations acting on a set of bodies, key is the name of each body undergoing an acceletation, value is SingleBodyAccelerationMap, defining all accelerations acting on it.
Definition at line 148 of file accelerationModel.h.
MassRateModelMap
typedef std::map< std::string, std::vector< std::shared_ptr< MassRateModel > > > tudat::basic_astrodynamics::MassRateModelMap
Definition at line 131 of file massRateModel.h.
SingleBodyTorqueModelMap
typedef std::map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::TorqueModel > > > tudat::basic_astrodynamics::SingleBodyTorqueModelMap
Definition at line 89 of file torqueModel.h.
TorqueModelMap
typedef std::map< std::string, SingleBodyTorqueModelMap > tudat::basic_astrodynamics::TorqueModelMap
Definition at line 92 of file torqueModel.h.
Enumeration Type Documentation
AvailableAcceleration
enum tudat::basic_astrodynamics::AvailableAcceleration
List of accelerations available in simulations. Acceleration models not defined by this given enum cannot be used for automatic acceleration model setup.
Enumerator
undefined_acceleration
point_mass_gravity
central_gravity
aerodynamic
cannon_ball_radiation_pressure
spherical_harmonic_gravity
mutual_spherical_harmonic_gravity
third_body_point_mass_gravity
third_body_central_gravity
third_body_spherical_harmonic_gravity
third_body_mutual_spherical_harmonic_gravity
thrust_acceleration
relativistic_correction_acceleration
empirical_acceleration
direct_tidal_dissipation_in_central_body_acceleration
direct_tidal_dissipation_in_orbiting_body_acceleration
Definition at line 42 of file accelerationModelTypes.h.
AvailableMassRateModels
enum tudat::basic_astrodynamics::AvailableMassRateModels
List of model types for body mass rates available in simulations. Mass rate models not defined by this given enum cannot be used for automatic mass rate model setup.
Enumerator
undefined_mass_rate_model
custom_mass_rate_model
from_thrust_mass_rate_model
Definition at line 75 of file accelerationModelTypes.h.
EmpiricalAccelerationFunctionalShapes
enum tudat::basic_astrodynamics::EmpiricalAccelerationFunctionalShapes
Enumerator
constant_empirical
sine_empirical
cosine_empirical
Definition at line 35 of file empiricalAcceleration.h.
EmpiricalAccelerationComponents
enum tudat::basic_astrodynamics::EmpiricalAccelerationComponents
Enumerator
radial_empirical_acceleration_component
along_track_empirical_acceleration_component
across_track_empirical_acceleration_component
Definition at line 65 of file empiricalAcceleration.h.
TimeScales
enum tudat::basic_astrodynamics::TimeScales
List of time scales available. Two types of scales are included, earth-based time scales (which can be handled, in part, by SOFA), which represent a unique specific scale, and three relativistic scales, of which only barycentric is unique. The bodycentric and topocentric scales require additional identifiers to fully determine.
Enumerator
dummy_scale
tai_scale
tt_scale
tdb_scale
utc_scale
ut1_scale
body_centered_coordinate_time_scale
barycentric_coordinate_time_scale
local_proper_time_scale
Definition at line 30 of file timeConversions.h.
AvailableTorque
enum tudat::basic_astrodynamics::AvailableTorque
List of torques available in simulations. Torque models not defined by this given enum cannot be used for automatic torque model setup.
Enumerator
underfined_torque
second_order_gravitational_torque
aerodynamic_torque
Definition at line 28 of file torqueModelTypes.h.
IAUConventions
enum tudat::basic_astrodynamics::IAUConventions
Enumerator
iau_2000_a
iau_2000_b
iau_2006
Definition at line 33 of file earthOrientation.h.
Function Documentation
updateAndGetAcceleration()
template<typename AccelerationDataType > AccelerationDataType tudat::basic_astrodynamics::updateAndGetAcceleration (const std::shared_ptr< AccelerationModel< AccelerationDataType > > accelerationModel, const double currentTime = TUDAT_NAN)
Updates the member variables of an acceleration model and subsequently evaluates the acceleration. This allows the user to suffice with a single function call to both update the members and evaluate the acceleration.
Template Parameters
AccelerationDataType Data type used to represent accelerations (default=Eigen::Vector3d).
Parameters
accelerationModel Acceleration model that is to be evaluated.
currentTime Time at which acceleration model is to be updated.
Returns
Acceleration that is obtained following the member update.
Definition at line 127 of file accelerationModel.h.
getAccelerationModelName()
std::string tudat::basic_astrodynamics::getAccelerationModelName (const AvailableAcceleration accelerationType)
Function to get a string representing a 'named identification' of an acceleration type
Parameters
accelerationType Type of acceleration model.
Returns
String with acceleration id.
Definition at line 21 of file accelerationModelTypes.cpp.
References aerodynamic, cannon_ball_radiation_pressure, central_gravity, direct_tidal_dissipation_in_central_body_acceleration, direct_tidal_dissipation_in_orbiting_body_acceleration, empirical_acceleration, mutual_spherical_harmonic_gravity, relativistic_correction_acceleration, spherical_harmonic_gravity, third_body_central_gravity, third_body_mutual_spherical_harmonic_gravity, third_body_spherical_harmonic_gravity, and thrust_acceleration.
Referenced by tudat::propagators::getDependentVariableId().
getAccelerationModelType()
AvailableAcceleration tudat::basic_astrodynamics::getAccelerationModelType (const std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel)
Function to identify the derived class type of an acceleration model. The type must be defined in the AvailableAcceleration enum to be recognized by this function.
Parameters
accelerationModel Acceleration model of which the type is to be identified.
Returns
Type of the accelerationModel, as identified by AvailableAcceleration enum.
Definition at line 75 of file accelerationModelTypes.cpp.
References aerodynamic, cannon_ball_radiation_pressure, central_gravity, direct_tidal_dissipation_in_central_body_acceleration, direct_tidal_dissipation_in_orbiting_body_acceleration, empirical_acceleration, mutual_spherical_harmonic_gravity, relativistic_correction_acceleration, spherical_harmonic_gravity, third_body_central_gravity, third_body_mutual_spherical_harmonic_gravity, third_body_spherical_harmonic_gravity, thrust_acceleration, and undefined_acceleration.
Referenced by tudat::simulation_setup::createAnalyticalAccelerationPartial(), tudat::propagators::createTranslationalEquationsOfMotionEnvironmentUpdaterSettings(), tudat::simulation_setup::createVectorParameterToEstimate(), getAccelerationModelsOfType(), tudat::propagators::removeCentralGravityAccelerations(), and tudat::propagators::setMultiTypePropagationClosure().
getMassRateModelType()
AvailableMassRateModels tudat::basic_astrodynamics::getMassRateModelType (const std::shared_ptr< MassRateModel > massRateModel)
Function to identify the type of a mass rate model. The type must be defined in the AvailableMassRateModels enum to be recognized by this function.
Parameters
massRateModel Mass rate model of which the type is to be identified.
Returns
Type of the massRateModel, as identified by AvailableMassRateModels enum.
Definition at line 165 of file accelerationModelTypes.cpp.
References custom_mass_rate_model, from_thrust_mass_rate_model, and undefined_mass_rate_model.
Referenced by tudat::propagators::createMassPropagationEnvironmentUpdaterSettings().
getAccelerationModelsOfType()
std::vector< std::shared_ptr< AccelerationModel3d > > tudat::basic_astrodynamics::getAccelerationModelsOfType (const std::vector< std::shared_ptr< AccelerationModel3d > > & fullList, const AvailableAcceleration modelType)
Function to get all acceleration models of a given type from a list of models
Parameters
fullList List of acceleration models
modelType Type for which all models are to be retrieved
Returns
Subset of fullList for which the acceleration model type is modelType
Definition at line 190 of file accelerationModelTypes.cpp.
References getAccelerationModelType().
Referenced by tudat::simulation_setup::createMassRateModel(), and tudat::propagators::getAccelerationBetweenBodies().
isAccelerationDirectGravitational()
bool tudat::basic_astrodynamics::isAccelerationDirectGravitational (const AvailableAcceleration accelerationType)
Function to check whether an acceleration type is a direct gravitational acceleration, e.g. a gravitational acceleration that is not from a third-body.
Parameters
accelerationType Acceleration type for which it is to be checked whether it is direct gravitational.
Returns
True if acceleration type is direct gravitational, false otherwise.
Definition at line 206 of file accelerationModelTypes.cpp.
References central_gravity, mutual_spherical_harmonic_gravity, and spherical_harmonic_gravity.
Referenced by getAssociatedThirdBodyAcceleration(), tudat::propagators::getDoubleDependentVariableFunction(), and tudat::propagators::getVectorDependentVariableFunction().
isAccelerationFromThirdBody()
bool tudat::basic_astrodynamics::isAccelerationFromThirdBody (const AvailableAcceleration accelerationType)
Function to check whether an acceleration type is a third-body gravitational acceleration
Parameters
accelerationType Acceleration type for which it is to be checked whether it is third-body gravitational.
Returns
True if acceleration type is third-body gravitational, false otherwise.
Definition at line 220 of file accelerationModelTypes.cpp.
References third_body_mutual_spherical_harmonic_gravity, third_body_point_mass_gravity, and third_body_spherical_harmonic_gravity.
Referenced by tudat::acceleration_partials::getCentralBodyNameFromThirdBodyAccelerationPartial().
getAssociatedThirdBodyAcceleration()
AvailableAcceleration tudat::basic_astrodynamics::getAssociatedThirdBodyAcceleration (const AvailableAcceleration accelerationType)
Function to get the third-body counterpart of a direct gravitational acceleration type, e.g. a third_body_central_gravity for a central_gravity input. Function throws an exception is input is not direct gravitational
Parameters
accelerationType Acceleration type for which the third-body counterpart is to be determined.
Returns
Third-body counterpart of accelerationType.
Definition at line 235 of file accelerationModelTypes.cpp.
References central_gravity, isAccelerationDirectGravitational(), mutual_spherical_harmonic_gravity, spherical_harmonic_gravity, third_body_central_gravity, third_body_mutual_spherical_harmonic_gravity, and third_body_spherical_harmonic_gravity.
Referenced by tudat::propagators::getDoubleDependentVariableFunction(), tudat::propagators::getSphericalHarmonicAccelerationForDependentVariables(), and tudat::propagators::getVectorDependentVariableFunction().
computeKeplerOrbitalPeriod()
double tudat::basic_astrodynamics::computeKeplerOrbitalPeriod (const double semiMajorAxis, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody = 0.0)
Compute two-body orbital period.
Computes the two-body orbital period of an orbiting body that follows a closed conic section (circle or ellipse Kepler orbit). The mass of the orbiting body is set to that of a test particle by default.
Parameters
semiMajorAxis Semi-major axis of Kepler orbit (circle or ellipse).
gravitationalParameterOfCentralBody Gravitational parameter of central body.
massOfOrbitingBody Mass of orbiting body.
Returns
Two-body orbital period.
Definition at line 29 of file astrodynamicsFunctions.cpp.
References tudat::physical_constants::GRAVITATIONAL_CONSTANT, tudat::mathematical_constants::PI, and tudat::input_output::field_types::state::semiMajorAxis.
computeKeplerRadialDistance() [1/2]
double tudat::basic_astrodynamics::computeKeplerRadialDistance (const double semiMajorAxis, const double eccentricity, const double trueAnomaly)
Compute two-body radial distance.
Parameters
semiMajorAxis Semi-major axis of Kepler orbit (circle or ellipse).
eccentricity Eccentricity of Kepler orbit (circle or ellipse).
trueAnomaly True anomaly of Kepler orbit (circle or ellipse).
Returns
Two-body radial distance at specified true anomaly.
Definition at line 40 of file astrodynamicsFunctions.cpp.
References tudat::input_output::field_types::state::eccentricity, tudat::input_output::field_types::state::semiMajorAxis, and tudat::input_output::field_types::state::trueAnomaly.
Referenced by computeKeplerOrbitalVelocity().
computeKeplerRadialDistance() [2/2]
double tudat::basic_astrodynamics::computeKeplerRadialDistance (const Eigen::Vector6d & keplerianElements)
Compute two-body radial distance.
Parameters
keplerianElements Vector denoting the Keplerian elements (circle or ellipse).
Returns
Two-body radial distance at specified true anomaly.
Definition at line 48 of file astrodynamicsFunctions.cpp.
References tudat::orbital_element_conversions::eccentricityIndex, tudat::json_interface::keplerianElements, tudat::orbital_element_conversions::semiMajorAxisIndex, and tudat::orbital_element_conversions::trueAnomalyIndex.
computeKeplerOrbitalVelocity() [1/2]
double tudat::basic_astrodynamics::computeKeplerOrbitalVelocity (const double semiMajorAxis, const double eccentricity, const double trueAnomaly, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody = 0.0)
Compute two-body orbital velocity with vis-viva equation.
Parameters
semiMajorAxis Semi-major axis of Kepler orbit (circle or ellipse).
eccentricity Eccentricity of Kepler orbit (circle or ellipse).
trueAnomaly True anomaly of Kepler orbit (circle or ellipse).
gravitationalParameterOfCentralBody Gravitational parameter of central body.
massOfOrbitingBody Mass of orbiting body.
Returns
Two-body orbital velocity at current conditions.
Definition at line 58 of file astrodynamicsFunctions.cpp.
References computeKeplerRadialDistance(), tudat::input_output::field_types::state::eccentricity, tudat::physical_constants::GRAVITATIONAL_CONSTANT, tudat::input_output::field_types::state::semiMajorAxis, and tudat::input_output::field_types::state::trueAnomaly.
computeKeplerOrbitalVelocity() [2/2]
double tudat::basic_astrodynamics::computeKeplerOrbitalVelocity (const Eigen::Vector6d & keplerianElements, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody = 0.0)
Compute two-body orbital velocity with vis-viva equation.
Parameters
keplerianElements Vector denoting the Keplerian elements (circle or ellipse).
gravitationalParameterOfCentralBody Gravitational parameter of central body.
massOfOrbitingBody Mass of orbiting body.
Returns
Two-body orbital velocity at current conditions.
Definition at line 71 of file astrodynamicsFunctions.cpp.
References computeKeplerRadialDistance(), tudat::physical_constants::GRAVITATIONAL_CONSTANT, tudat::json_interface::keplerianElements, and tudat::orbital_element_conversions::semiMajorAxisIndex.
computeKeplerAngularMomentum()
double tudat::basic_astrodynamics::computeKeplerAngularMomentum (const double semiMajorAxis, const double eccentricity, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody = 0.0)
Compute two-body angular momentum.
Computes the angular momentum of an orbiting body that follows a conic section (Kepler orbit), relative to the center-of-mass of the central body. The default mass value is for the angular momentum per unit mass.
Parameters
semiMajorAxis Semi-major axis of Kepler orbit.
eccentricity Eccentricity of Kepler orbit.
gravitationalParameterOfCentralBody Gravitational parameter of central body.
massOfOrbitingBody Mass of orbiting body.
Returns
Two-body angular momentum.
Definition at line 82 of file astrodynamicsFunctions.cpp.
References tudat::input_output::field_types::state::eccentricity, and tudat::input_output::field_types::state::semiMajorAxis.
computeKeplerMeanMotion()
double tudat::basic_astrodynamics::computeKeplerMeanMotion (const double semiMajorAxis, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody = 0.0)
Compute two-body mean motion.
Computes the two-body mean motion of an orbiting body that follows a conic section (Kepler orbit). The mass of the orbiting body is set to that of a test particle by default.
Parameters
semiMajorAxis Semi-major axis of Kepler orbit.
gravitationalParameterOfCentralBody Gravitational parameter of central body.
massOfOrbitingBody Mass of orbiting body.
Returns
Two-body mean motion.
Definition at line 91 of file astrodynamicsFunctions.cpp.
References tudat::physical_constants::GRAVITATIONAL_CONSTANT, and tudat::input_output::field_types::state::semiMajorAxis.
Referenced by tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements().
computeKeplerEnergy()
double tudat::basic_astrodynamics::computeKeplerEnergy (const double semiMajorAxis, const double gravitationalParameterOfCentralBody, const double massOfOrbitingBody = 1.0)
Compute Kepler energy.
Computes the energy of an orbiting body that follows a conic section (Kepler orbit). The default mass value is for the two-body orbital energy per unit mass. For closed conic sections (circles, ellipses), the semi-major axis is positive, and for open sections (hyperbolas) the semi-major axis is negative.
Parameters
semiMajorAxis Semi-major axis of Kepler orbit.
gravitationalParameterOfCentralBody Gravitational parameter of central body.
massOfOrbitingBody Mass of orbiting body.
Returns
Kepler orbital energy.
Definition at line 100 of file astrodynamicsFunctions.cpp.
References tudat::input_output::field_types::state::semiMajorAxis.
computeSynodicPeriod()
double tudat::basic_astrodynamics::computeSynodicPeriod (const double orbitalPeriodBody1, const double orbitalPeriodBody2)
Computes synodic period between two bodies in different Kepler orbits (closed conic sections). The orbital periods must be positive values for the synodic period to be sensible.
Parameters
orbitalPeriodBody1 Orbital period of Body 1.
orbitalPeriodBody2 Orbital period of Body 2.
Returns
Synodic period.
Definition at line 108 of file astrodynamicsFunctions.cpp.
computePeriapsisAltitudeFromKeplerianState()
double tudat::basic_astrodynamics::computePeriapsisAltitudeFromKeplerianState (const Eigen::Vector6d & state, const double centralBodyRadius)
Compute periapsis altitude from Keplerian state for spherical central body.
Parameters
state Keplerian state of the propagated body.
centralBodyRadius Radius of the central body (assumed spherical).
Returns
The distance from the propagated body to the central body's spherical surface at periapsis.
Definition at line 115 of file astrodynamicsFunctions.cpp.
References tudat::orbital_element_conversions::eccentricityIndex, and tudat::orbital_element_conversions::semiMajorAxisIndex.
Referenced by computePeriapsisAltitudeFromCartesianState().
computePeriapsisAltitudeFromCartesianState()
double tudat::basic_astrodynamics::computePeriapsisAltitudeFromCartesianState (const Eigen::Vector6d & state, const double centralBodyGravitationalParameter, const double centralBodyRadius)
Compute periapsis altitude from Cartesian state for spherical central body.
Parameters
state Cartesian state of the propagated body.
centralBodyGravitationalParameter Gravitational parameter of the central body.
centralBodyRadius Radius of the central body (assumed spherical).
Returns
The distance from the propagated body to the central body's spherical surface at periapsis.
Definition at line 123 of file astrodynamicsFunctions.cpp.
References computePeriapsisAltitudeFromKeplerianState(), and tudat::orbital_element_conversions::convertCartesianToKeplerianElements().
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
getAltitudeFromNonBodyFixedPosition()
double tudat::basic_astrodynamics::getAltitudeFromNonBodyFixedPosition (const std::shared_ptr< BodyShapeModel > bodyShapeModel, const Eigen::Vector3d & position, const Eigen::Vector3d & bodyPosition, const Eigen::Quaterniond & toBodyFixedFrame)
Function to calculate the altitude of a point over a central body from positions of both the point and the body (in any frame)
Function to calculate the altitude of a point over a central body from positions of both the point and the body (in any frame)
The rotation to the body-fixed frame is provided to calculate the input for the altitude function of the bodyShapeModel, which is to be in a body-fixed frame.
Parameters
bodyShapeModel Shape model of central body
position Position of point of which altitude is to be calculated
bodyPosition Position of central body above which altitude is to be calculated
toBodyFixedFrame Rotation from frame in which input vectors are given to body-fixed frame.
Returns
Altitude above body shape.
Definition at line 25 of file bodyShapeModel.cpp.
Referenced by getAltitudeFromNonBodyFixedPositionFunctions().
getAltitudeFromNonBodyFixedPositionFunctions()
double tudat::basic_astrodynamics::getAltitudeFromNonBodyFixedPositionFunctions (const std::shared_ptr< BodyShapeModel > bodyShapeModel, const Eigen::Vector3d & position, const std::function< Eigen::Vector3d() > bodyPositionFunction, const std::function< Eigen::Quaterniond() > toBodyFixedFrameFunction)
Function to calculate the altitude of a point over a central body from positions of both the point and the body (in any frame)
Function to calculate the altitude of a point over a central body from positions of both the point and the body (in any frame)
The rotation to the body-fixed frame is provided to calculate the input for the altitude function of the bodyShapeModel. The position of the central body and rotation are not provided directly, but as function pointers to allow easy binding with e.g. a Body class.
Parameters
bodyShapeModel Shape model of central body
position Position of point of which altitude is to be calculated
bodyPositionFunction Function returning position of central body above which altitude is to be calculated
toBodyFixedFrameFunction Function returning rotation from frame in which input vectors are given to body-fixed frame.
Returns
Altitude above body shape.
Definition at line 34 of file bodyShapeModel.cpp.
References getAltitudeFromNonBodyFixedPosition().
propagateClohessyWiltshire()
Eigen::Vector6d tudat::basic_astrodynamics::propagateClohessyWiltshire (const Eigen::Vector6d & initialState, const double propagationDuration, const double centralBodyGravitationalParameter, const double referenceOrbitRadius)
Propagate Clohessy-Wilshire equations (linearized relative motion).
This function propagates linearized relative motion, based on the Clohessy-Wiltshire equations. It calculates the motion of a point mass A with respect to a local-vertical-local-horizontal reference frame centered on a point mass B.
The following assumptions apply: (1) Masses A and B are negligable compared to the central body mass (e.g. mass A is a daughter spacecraft, mass B is a mother spacecraft, and the central body is planet Earth). (2) Orbit perturbations are negligable (i.e. massses A and B follow Kepler orbits about the central body). (3) The orbit of mass B is circular. (4) The separation between mass A and mass B is very small compared to the circumference of the orbit of mass B.
The Clohessy-Wilthsire equations are given by Vallado [2001] as:
in which , and are the radial, along-track and cross-track position respectively, of mass A. Parameters , and are the initial radial, along-track and cross-track position respectively. Parameter is the mean angular motion of the circular orbit of mass B. Finally, parameter is time.
Parameters
initialState Initial state vector in Cartesian elements. The order is important! initialState(0) = radial position [m], initialState(1) = along-track position [m], initialState(2) = cross-track position [m], initialState(3) = radial velocity [m/s], initialstate(4) = along-track velocity [m/s], initialState(5) = cross-track velocity [m/s],
propagationDuration Duration of propagation [s].
centralBodyGravitationalParameter Gravitational parameter of central body [m^3 s^-2].
referenceOrbitRadius Radius of circular orbit of mass B [m].
Returns
Final state vector in Cartesian elements. The order is important! finalState(0) = radial position [m], finalState(1) = along-track position [m], finalState(2) = cross-track position [m], finalState(3) = radial velocity [m/s], finalState(4) = along-track velocity [m/s], finalState(5) = cross-track velocity [m/s].
Definition at line 30 of file clohessyWiltshirePropagator.cpp.
getEmpiricalAccelerationFunctionalShapeString()
std::string tudat::basic_astrodynamics::getEmpiricalAccelerationFunctionalShapeString (const EmpiricalAccelerationFunctionalShapes functionalShape) inline
Definition at line 42 of file empiricalAcceleration.h.
References constant_empirical, cosine_empirical, and sine_empirical.
Referenced by tudat::estimatable_parameters::EmpiricalAccelerationCoefficientsParameter::getParameterDescription().
getJulianDayOnJ2000< double >()
template<> double tudat::basic_astrodynamics::getJulianDayOnJ2000< double > ()
Definition at line 25 of file timeConversions.cpp.
References JULIAN_DAY_ON_J2000.
getJulianDayOnJ2000< long double >()
template<> long double tudat::basic_astrodynamics::getJulianDayOnJ2000< long double > ()
Definition at line 32 of file timeConversions.cpp.
References JULIAN_DAY_ON_J2000_LONG.
getJulianDayOnMjd0< double >()
template<> double tudat::basic_astrodynamics::getJulianDayOnMjd0< double > ()
Definition at line 39 of file timeConversions.cpp.
References JULIAN_DAY_AT_0_MJD.
getJulianDayOnMjd0< long double >()
template<> long double tudat::basic_astrodynamics::getJulianDayOnMjd0< long double > ()
Definition at line 46 of file timeConversions.cpp.
References JULIAN_DAY_AT_0_MJD_LONG.
getTimeOfTaiSynchronizationJulianDay< double >()
template<> double tudat::basic_astrodynamics::getTimeOfTaiSynchronizationJulianDay< double > ()
Definition at line 53 of file timeConversions.cpp.
References TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION.
getTimeOfTaiSynchronizationJulianDay< long double >()
template<> long double tudat::basic_astrodynamics::getTimeOfTaiSynchronizationJulianDay< long double > ()
Definition at line 60 of file timeConversions.cpp.
References TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION_LONG.
getTdbSecondsOffsetAtSynchronization< double >()
template<> double tudat::basic_astrodynamics::getTdbSecondsOffsetAtSynchronization< double > ()
Function to get the difference between TDB and (TT, TCB and TCB) at TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION, in double precision.
Definition at line 68 of file timeConversions.cpp.
References TDB_SECONDS_OFFSET_AT_SYNCHRONIZATION.
getTdbSecondsOffsetAtSynchronization< long double >()
template<> long double tudat::basic_astrodynamics::getTdbSecondsOffsetAtSynchronization< long double > ()
Function to get the difference between TDB and (TT, TCB and TCB) at TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION, in long double precision.
Definition at line 76 of file timeConversions.cpp.
References TDB_SECONDS_OFFSET_AT_SYNCHRONIZATION_LONG.
getTTMinusTai< double >()
template<> double tudat::basic_astrodynamics::getTTMinusTai< double > ()
Definition at line 83 of file timeConversions.cpp.
References TT_MINUS_TAI.
getTTMinusTai< long double >()
template<> long double tudat::basic_astrodynamics::getTTMinusTai< long double > ()
Definition at line 90 of file timeConversions.cpp.
References TT_MINUS_TAI_LONG.
getTTMinusTai< Time >()
template<> Time tudat::basic_astrodynamics::getTTMinusTai< Time > ()
Definition at line 97 of file timeConversions.cpp.
References TT_MINUS_TAI_LONG.
convertJulianDayToCalendarDate()
boost::gregorian::date tudat::basic_astrodynamics::convertJulianDayToCalendarDate (const double julianDay)
Function to convert julian day to gregorian calendar date. Algorithm from (Wertz, 2009, Eq. 4.3)
Parameters
julianDay Julian day to convert to gregorian calendar date.
Returns
Gregorian calendar date at given julian day.
Definition at line 104 of file timeConversions.cpp.
References tudat::input_output::field_types::time::day, tudat::input_output::field_types::time::month, and tudat::input_output::field_types::time::year.
isLeapYear()
bool tudat::basic_astrodynamics::isLeapYear (const int year)
Function to determine whether the given year is a leap year (i.e. has 366 days)
Parameters
year Year for which it is to be determined whether it is a leap year.
Returns
True if year is a leap year, false otherwise.
Definition at line 159 of file timeConversions.cpp.
References tudat::input_output::field_types::time::year.
Referenced by getDaysInMonth().
getDaysInMonth()
int tudat::basic_astrodynamics::getDaysInMonth (const int month, const int year)
Function that returns number of days in given month number (January = 1, December = 12)
Parameters
month Month number
year Year
Returns
Number of days in given month
Definition at line 170 of file timeConversions.cpp.
References isLeapYear(), tudat::input_output::field_types::time::month, and tudat::input_output::field_types::time::year.
Referenced by convertYearAndDaysInYearToDate().
convertDayMonthYearToDayOfYear() [1/2]
int tudat::basic_astrodynamics::convertDayMonthYearToDayOfYear (const int day, const int month, const int year)
Determine number of full days that have passed in current year (i.e. 0 to 364 or 0 to 365 for leap year) This function creates a boost::gregorian::date object and calls the overloaded function.
Parameters
day Day in current year (1 is first day)
month Month in current year (1 is first month)
year Current year (for leap year purposes)
Returns
Number of full days that have passed in current year
Definition at line 198 of file timeConversions.cpp.
References tudat::input_output::field_types::time::day, tudat::input_output::field_types::time::month, and tudat::input_output::field_types::time::year.
convertDayMonthYearToDayOfYear() [2/2]
int tudat::basic_astrodynamics::convertDayMonthYearToDayOfYear (const boost::gregorian::date calendarDate)
Determine number of full days that have passed in current year (i.e. 0 to 364 or 0 to 365 for leap year)
Parameters
calendarDate Gregorian calendat date object containing current date information.
Returns
Number of full days that have passed in current year
Definition at line 206 of file timeConversions.cpp.
calculateSecondsInCurrentJulianDay()
double tudat::basic_astrodynamics::calculateSecondsInCurrentJulianDay (const double julianDay)
Determine number of seconds into current day of given time
Parameters
julianDay Current julian day
Returns
Number of seconds into current day.
Definition at line 213 of file timeConversions.cpp.
References tudat::physical_constants::JULIAN_DAY.
convertYearAndDaysInYearToDate()
boost::gregorian::date tudat::basic_astrodynamics::convertYearAndDaysInYearToDate (const int year, const int daysInYear)
Function to create the calendar date from the year and the number of days in the year, where Jan. 1 is day in year 0.
Parameters
year Year in which days in year are given
daysInYear Number of days in current year, note that day must be in current year (i.e <= 365 of 366 for leap year)
Returns
Gregorian date object as generated from input
Definition at line 220 of file timeConversions.cpp.
References getDaysInMonth(), and tudat::input_output::field_types::time::year.
approximateConvertTTtoTDB()
double tudat::basic_astrodynamics::approximateConvertTTtoTDB (const double ttSecondsSinceJ2000)
Perform apprixmate conversion of TT to TDB, in which only the once-per-orbit sinusoidal effect of O(e) is taken into account. Accurate conversions are calculated usinf Sofa
Parameters
ttSecondsSinceJ2000 Terrestrial time in seconds since J2000
Returns
TDB in seconds since J2000
Definition at line 265 of file timeConversions.cpp.
References tudat::physical_constants::JULIAN_YEAR.
getJulianDayOnJ2000()
template<typename TimeType > TimeType tudat::basic_astrodynamics::getJulianDayOnJ2000 ()
Function to get the Julian day on J2000, in the requested time representation type
Returns
Julian day on J2000
getJulianDayOnMjd0()
template<typename TimeType > TimeType tudat::basic_astrodynamics::getJulianDayOnMjd0 ()
Function to get the Julian day on on zero modified Julian day, in the requested time representation type
Returns
Julian day on zero modified Julian day.
getTimeOfTaiSynchronizationJulianDay()
template<typename TimeType > TimeType tudat::basic_astrodynamics::getTimeOfTaiSynchronizationJulianDay ()
Function to get the synchronization Julian day of TT, TCG, and TCB, in the requested time representation type
Returns
Synchronization Julian day of TT, TCG, and TCB.
getTimeOfTaiSynchronizationSinceJ2000()
template<typename TimeType > TimeType tudat::basic_astrodynamics::getTimeOfTaiSynchronizationSinceJ2000 ()
Function to get the synchronization time of TT, TCG, and TCB, in seconds since J2000 (constant by definition).
Returns
Synchronization time of TT, TCG, and TCB, in seconds since J2000.
Definition at line 91 of file timeConversions.h.
getTdbSecondsOffsetAtSynchronization()
template<typename TimeType > TimeType tudat::basic_astrodynamics::getTdbSecondsOffsetAtSynchronization ()
Function to get the difference between TDB and (TT, TCB and TCB) at TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION, in the requested time representation type
Returns
Difference between TDB and (TT, TCB and TCB) at TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION (constant by definition).
getTTMinusTai()
template<typename TimeType > TimeType tudat::basic_astrodynamics::getTTMinusTai ()
Function to get the offset of TT from TAI (constant by definition), in the requested time representation type
Returns
Offset of TT from TAI (constant by definition).
convertJulianDayToSecondsSinceEpoch()
template<typename TimeScalarType = double> TimeScalarType tudat::basic_astrodynamics::convertJulianDayToSecondsSinceEpoch (const TimeScalarType julianDay, const TimeScalarType epochSinceJulianDayZero = getJulianDayOnJ2000< TimeScalarType >())
Computes the number of seconds since a reference Julian day from Julian day.
Parameters
julianDay Julian day at which number of seconds since epoch is to be determined.
epochSinceJulianDayZero Epoch in Julian day.
Returns
Number of seconds since epoch.
Definition at line 135 of file timeConversions.h.
Referenced by tudat::aerodynamics::nrlmsiseInputFunction(), and tudat::transfer_trajectories::returnSingleRevolutionPlanetTrajectory().
convertSecondsSinceEpochToJulianDay()
template<typename TimeScalarType = double> TimeScalarType tudat::basic_astrodynamics::convertSecondsSinceEpochToJulianDay (const TimeScalarType secondsSinceEpoch, const TimeScalarType epochSinceJulianDayZero = getJulianDayOnJ2000< TimeScalarType >())
Computes the Julian day bsaed on seconds since reference Julian day epoch provided.
Parameters
secondsSinceEpoch Seconds since epoch.
epochSinceJulianDayZero Epoch in Julian day.
Returns
Number of Julian days since epoch.
Definition at line 150 of file timeConversions.h.
Referenced by tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris(), and tudat::aerodynamics::nrlmsiseInputFunction().
convertCalendarDateToJulianDaysSinceEpoch()
template<typename TimeScalarType = double> TimeScalarType tudat::basic_astrodynamics::convertCalendarDateToJulianDaysSinceEpoch (const int calendarYear, const int calendarMonth, const int calendarDay, const int calendarHour, const int calendarMinutes, const TimeScalarType calendarSeconds, const TimeScalarType referenceJulianDay)
Computes the Julian day from given year, month, day, hour, minutes, seconds as used in everyday life. The function uses the internal calcualtions of the boost::date_time::gregorian class.
Parameters
calendarYear Year of the standard calendar in years.
calendarMonth Month of the standard calendar in months.
calendarDay Day of the standard calendar in days.
calendarHour Hour of the time of this day in hours.
calendarMinutes Minutes of the time of this day in minutes.
calendarSeconds Seconds of the time of this day in seconds.
referenceJulianDay Reference Julian day (i.e. t=0) for input time.
Returns
Seconds since referenceJulianDay for input date/time.
Definition at line 173 of file timeConversions.h.
convertCalendarDateToJulianDay()
template<typename TimeScalarType = double> TimeScalarType tudat::basic_astrodynamics::convertCalendarDateToJulianDay (const int calendarYear, const int calendarMonth, const int calendarDay, const int calendarHour, const int calendarMinutes, const TimeScalarType calendarSeconds)
Computes the Julian day from given year, month, day, hour, minutes, seconds as used in everyday life. The function uses the internal calcualtions of the boost::date_time::gregorian class.
Parameters
calendarYear Year of the standard calendar in years.
calendarMonth Month of the standard calendar in months.
calendarDay Day of the standard calendar in days.
calendarHour Hour of the time of this day in hours.
calendarMinutes Minutes of the time of this day in minutes.
calendarSeconds Seconds of the time of this day in seconds.
Definition at line 212 of file timeConversions.h.
Referenced by tudat::aerodynamics::nrlmsiseInputFunction(), and tudat::input_output::solar_activity::readSolarActivityData().
convertJulianDayToModifiedJulianDay()
template<typename TimeScalarType > TimeScalarType tudat::basic_astrodynamics::convertJulianDayToModifiedJulianDay (const TimeScalarType julianDay)
Function to convert julian day to modified julian day.
Parameters
julianDay Julian day to convert
Returns
Modified julian day as obtained from julian day.
Definition at line 231 of file timeConversions.h.
convertModifiedJulianDayToJulianDay()
template<typename TimeScalarType > TimeScalarType tudat::basic_astrodynamics::convertModifiedJulianDayToJulianDay (const TimeScalarType modifiedJulianDay)
Function to convert modified julian dat to julian day.
Parameters
modifiedJulianDay Modified julian day to convert
Returns
Julian day as obtained from modified julian day.
Definition at line 243 of file timeConversions.h.
Referenced by tudat::transfer_trajectories::returnSingleRevolutionPlanetTrajectory().
convertSecondsSinceEpochToJulianYearsSinceEpoch()
template<typename TimeScalarType = double> TimeScalarType tudat::basic_astrodynamics::convertSecondsSinceEpochToJulianYearsSinceEpoch (const TimeScalarType secondsSinceEpoch)
Function to convert the number of seconds since some reference julian day to a julian year since that epoch.
Parameters
secondsSinceEpoch Seconds since some reference epoch to convert to julian year.
Returns
Number of julian years since epoch
Definition at line 255 of file timeConversions.h.
Referenced by convertSecondsSinceEpochToJulianCenturiesSinceEpoch().
convertSecondsSinceEpochToJulianCenturiesSinceEpoch()
template<typename TimeScalarType = double> TimeScalarType tudat::basic_astrodynamics::convertSecondsSinceEpochToJulianCenturiesSinceEpoch (const TimeScalarType secondsSinceEpoch)
Function to convert the number of seconds since some reference julian day to a julian century since that epoch.
Parameters
secondsSinceEpoch Seconds since some reference epoch to convert to julian year.
Returns
Number of julian centuries since epoch
Definition at line 268 of file timeConversions.h.
References convertSecondsSinceEpochToJulianYearsSinceEpoch().
Referenced by tudat::sofa_interface::calculateDelaunayFundamentalArguments(), and tudat::sofa_interface::calculateDoodsonFundamentalArguments().
calculateJulianDaySinceEpoch()
template<typename TimeScalarType > TimeScalarType tudat::basic_astrodynamics::calculateJulianDaySinceEpoch (const boost::gregorian::date calendarDate, const TimeScalarType fractionOfDay, const TimeScalarType epochSinceJulianDayZero = JULIAN_DAY_ON_J2000)
Function to convert gregorian calendar date and fraction of day to a number of julian days since a reference epoch.
Parameters
calendarDate Calendar date at which conversion is to be performed.
fractionOfDay Fraction of day in current gregorian date.
epochSinceJulianDayZero Reference epoch since which number of julian days is to be determined.
Returns
Number of julian days since a reference epoch.
Definition at line 290 of file timeConversions.h.
convertTcbToTdb()
template<typename TimeType > TimeType tudat::basic_astrodynamics::convertTcbToTdb (const TimeType tcbTime)
Function to convert TCB to TDB times scale, with both input and output referenced to the J2000 reference time.
Parameters
tcbTime Input time in TCB scale
Returns
Converted time in TDB scale
Definition at line 362 of file timeConversions.h.
convertTdbToTcb()
template<typename TimeType > TimeType tudat::basic_astrodynamics::convertTdbToTcb (const TimeType tdbTime)
Function to convert TDB to TCB times scale, with both input and output referenced to the J2000 reference time.
Parameters
tdbTime Input time in TDB scale
Returns
Converted time in TCB scale
Definition at line 376 of file timeConversions.h.
convertTcgToTt()
template<typename TimeType > TimeType tudat::basic_astrodynamics::convertTcgToTt (const TimeType tcgTime)
Function to convert TCG to TT times scale, with both input and output referenced to the J2000 reference time.
Parameters
tcgTime Input time in TCG scale
Returns
Converted time in TT scale
Definition at line 392 of file timeConversions.h.
convertTtToTcg()
template<typename TimeType > TimeType tudat::basic_astrodynamics::convertTtToTcg (const TimeType ttTime)
Function to convert TT to TCG times scale, with both input and output referenced to the J2000 reference time.
Parameters
ttTime Input time in TT scale
Returns
Converted time in TCG scale
Definition at line 405 of file timeConversions.h.
convertTAItoTT()
template<typename TimeType > TimeType tudat::basic_astrodynamics::convertTAItoTT (const TimeType taiTime)
Function to convert TAI (International Atomic Time) to TT (Terrestrial Time) by adding bias as defined by Sofa.
Parameters
taiTime Time in TAI
Returns
Time in TT
Definition at line 420 of file timeConversions.h.
Referenced by tudat::sofa_interface::convertUTCtoTT().
convertTTtoTAI()
template<typename TimeType > TimeType tudat::basic_astrodynamics::convertTTtoTAI (const TimeType ttTime)
Function to convert TT (Terrestrial Time) to TAI (International Atomic Time) by subtracting bias as defined by Sofa.
Parameters
ttTime Time in TT
Returns
Time in TAI
Definition at line 433 of file timeConversions.h.
Referenced by tudat::sofa_interface::convertTTtoUTC().
getTorqueModelType()
AvailableTorque tudat::basic_astrodynamics::getTorqueModelType (std::shared_ptr< basic_astrodynamics::TorqueModel > torqueModel)
Function to identify the derived class type of a torque model. The type must be defined in the AvailableTorque enum to be recognized by this function.
Parameters
torqueModel Torque model of which the type is to be identified.
Returns
Type of the torqueModel, as identified by AvailableTorque enum.
Definition at line 26 of file torqueModelTypes.cpp.
References aerodynamic_torque, second_order_gravitational_torque, and underfined_torque.
Referenced by tudat::propagators::createRotationalEquationsOfMotionEnvironmentUpdaterSettings(), and getTorqueModelsOfType().
getTorqueModelName()
std::string tudat::basic_astrodynamics::getTorqueModelName (const AvailableTorque torqueType)
Function to get a string representing a 'named identification' of an torque type
Parameters
torqueType Type of torque model.
Returns
String with torque id.
Definition at line 46 of file torqueModelTypes.cpp.
References aerodynamic_torque, and second_order_gravitational_torque.
Referenced by tudat::propagators::getDependentVariableId().
getTorqueModelsOfType()
std::vector< std::shared_ptr< TorqueModel > > tudat::basic_astrodynamics::getTorqueModelsOfType (const std::vector< std::shared_ptr< TorqueModel > > & fullList, const AvailableTorque modelType)
Function to get all torque models of a given type from a list of models
Parameters
fullList List of torque models
modelType Type for which all models are to be retrieved
Returns
Subset of fullList for which the torque model type is modelType
Definition at line 67 of file torqueModelTypes.cpp.
References getTorqueModelType().
Referenced by tudat::propagators::getTorqueBetweenBodies().
to_json() [1/4]
void tudat::basic_astrodynamics::to_json (nlohmann::json & jsonObject, const IAUConventions & conventionType) inline
Definition at line 68 of file rotationModel.h.
References precessionNutationConventions, and tudat::json_interface::stringFromEnum().
from_json() [1/4]
void tudat::basic_astrodynamics::from_json (const nlohmann::json & jsonObject, IAUConventions & conventionType) inline
Definition at line 74 of file rotationModel.h.
References tudat::json_interface::enumFromString(), and precessionNutationConventions.
to_json() [2/4]
void tudat::basic_astrodynamics::to_json (nlohmann::json & jsonObject, const AvailableAcceleration & accelerationType) inline
Definition at line 62 of file acceleration.h.
References accelerationTypes, and tudat::json_interface::stringFromEnum().
from_json() [2/4]
void tudat::basic_astrodynamics::from_json (const nlohmann::json & jsonObject, AvailableAcceleration & accelerationType) inline
Definition at line 68 of file acceleration.h.
References accelerationTypes, and tudat::json_interface::enumFromString().
to_json() [3/4]
void tudat::basic_astrodynamics::to_json (nlohmann::json & jsonObject, const AvailableMassRateModels & massRateType) inline
Definition at line 40 of file massRateModel.h.
References massRateTypes, and tudat::json_interface::stringFromEnum().
from_json() [3/4]
void tudat::basic_astrodynamics::from_json (const nlohmann::json & jsonObject, AvailableMassRateModels & massRateType) inline
Definition at line 46 of file massRateModel.h.
References tudat::json_interface::enumFromString(), and massRateTypes.
to_json() [4/4]
void tudat::basic_astrodynamics::to_json (nlohmann::json & jsonObject, const AvailableTorque & torqueType) inline
Definition at line 36 of file torque.h.
References tudat::json_interface::stringFromEnum(), and torqueTypes.
from_json() [4/4]
void tudat::basic_astrodynamics::from_json (const nlohmann::json & jsonObject, AvailableTorque & torqueType) inline
Definition at line 42 of file torque.h.
References tudat::json_interface::enumFromString(), and torqueTypes.
Variable Documentation
JULIAN_DAY_ON_J2000
const double tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000 = 2451545.0 static
Definition at line 44 of file timeConversions.h.
Referenced by tudat::sofa_interface::calculateDelaunayFundamentalArgumentsWithGmst(), tudat::sofa_interface::calculateDoodsonFundamentalArguments(), tudat::sofa_interface::calculateEarthRotationAngleTemplated< double >(), tudat::sofa_interface::calculateEarthRotationAngleTemplated< Time >(), tudat::observation_partials::createCartesianStatePartialsWrtParameter(), tudat::earth_orientation::getApproximateTioLocator(), tudat::earth_orientation::EOPReader::getCipInGcrsCorrectionMapInSecondsSinceJ2000(), tudat::earth_orientation::EOPReader::getCipInItrsMapInSecondsSinceJ2000(), tudat::sofa_interface::getDeltaAtFromTai(), tudat::sofa_interface::getDeltaAtFromUtc(), getJulianDayOnJ2000< double >(), tudat::earth_orientation::EOPReader::getLengthOfDayMapInSecondsSinceJ2000(), tudat::ground_stations::GroundStation::getStateInPlanetFixedFrame(), tudat::sofa_interface::getTDBminusTT(), tudat::earth_orientation::EOPReader::getUt1MinusUtcMapInSecondsSinceJ2000(), tudat::aerodynamics::nrlmsiseInputFunction(), tudat::earth_orientation::PrecessionNutationCalculator::PrecessionNutationCalculator(), tudat::ephemerides::SpiceEphemeris::SpiceEphemeris(), and tudat::ephemerides::SpiceRotationalEphemeris::SpiceRotationalEphemeris().
JULIAN_DAY_ON_J2000_LONG
const long double tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000_LONG = 2451545.0L static
Definition at line 47 of file timeConversions.h.
Referenced by getJulianDayOnJ2000< long double >().
JULIAN_DAY_AT_0_MJD
const double tudat::basic_astrodynamics::JULIAN_DAY_AT_0_MJD = 2400000.5 static
Definition at line 58 of file timeConversions.h.
Referenced by tudat::earth_orientation::EOPReader::getCipInGcrsCorrectionMapInSecondsSinceJ2000(), tudat::earth_orientation::EOPReader::getCipInItrsMapInSecondsSinceJ2000(), getJulianDayOnMjd0< double >(), tudat::earth_orientation::EOPReader::getLengthOfDayMapInSecondsSinceJ2000(), and tudat::earth_orientation::EOPReader::getUt1MinusUtcMapInSecondsSinceJ2000().
JULIAN_DAY_AT_0_MJD_LONG
const long double tudat::basic_astrodynamics::JULIAN_DAY_AT_0_MJD_LONG = 2400000.5L static
Definition at line 61 of file timeConversions.h.
Referenced by getJulianDayOnMjd0< long double >().
TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION
const double tudat::basic_astrodynamics::TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION = 2443144.5003725 static
Definition at line 72 of file timeConversions.h.
Referenced by getTimeOfTaiSynchronizationJulianDay< double >().
TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION_LONG
const long double tudat::basic_astrodynamics::TAI_JULIAN_DAY_AT_TIME_SYNCHRONIZATION_LONG = 2443144.5003725L static
Definition at line 75 of file timeConversions.h.
Referenced by getTimeOfTaiSynchronizationJulianDay< long double >().
TDB_SECONDS_OFFSET_AT_SYNCHRONIZATION
const double tudat::basic_astrodynamics::TDB_SECONDS_OFFSET_AT_SYNCHRONIZATION = -6.55E-5 static
Definition at line 98 of file timeConversions.h.
Referenced by getTdbSecondsOffsetAtSynchronization< double >().
TDB_SECONDS_OFFSET_AT_SYNCHRONIZATION_LONG
const double tudat::basic_astrodynamics::TDB_SECONDS_OFFSET_AT_SYNCHRONIZATION_LONG = -6.55E-5L static
Definition at line 101 of file timeConversions.h.
Referenced by getTdbSecondsOffsetAtSynchronization< long double >().
TT_MINUS_TAI
const double tudat::basic_astrodynamics::TT_MINUS_TAI = 32.184 static
Definition at line 113 of file timeConversions.h.
Referenced by getTTMinusTai< double >().
TT_MINUS_TAI_LONG
const double tudat::basic_astrodynamics::TT_MINUS_TAI_LONG = 32.184L static
Definition at line 116 of file timeConversions.h.
Referenced by getTTMinusTai< long double >(), and getTTMinusTai< Time >().
precessionNutationConventions
std::map< IAUConventions, std::string > tudat::basic_astrodynamics::precessionNutationConventions static
Initial value:
=
{
    { iau_2000_a, "IAU2000a" },
    { iau_2000_b, "IAU2000b" },
    { iau_2006, "IAU2006" }
}
Definition at line 60 of file rotationModel.h.
Referenced by from_json(), and to_json().
accelerationTypes
std::map< AvailableAcceleration, std::string > tudat::basic_astrodynamics::accelerationTypes static
Initial value:
=
{
    { undefined_acceleration, "undefined" },
    { point_mass_gravity, "pointMassGravity" },
    { aerodynamic, "aerodynamic" },
    { cannon_ball_radiation_pressure, "cannonBallRadiationPressure" },
    { spherical_harmonic_gravity, "sphericalHarmonicGravity" },
    { mutual_spherical_harmonic_gravity, "mutualSphericalHarmonicGravity" },
    { third_body_point_mass_gravity, "thirdBodyPointMassGravity" },
    { third_body_spherical_harmonic_gravity, "thirdBodySphericalHarmonicGravity" },
    { third_body_mutual_spherical_harmonic_gravity, "thirdBodyMutualSphericalHarmonicGravity" },
    { thrust_acceleration, "thrust" },
    { relativistic_correction_acceleration, "relativisticCorrection" },
    { empirical_acceleration, "empirical" }
}
Map of AvailableAccelerations string representations.
There is a naming inconsistency between "pointMassGravity" and central_gravity, and between "thirdBodyPointMassGravity" and third_body_central_gravity.
The values "thirdBodyPointMassGravity", "thirdBodySphericalHarmonicGravity" and "thirdBodyMutualSphericalHarmonicGravity" are supported by the JSON interface, and are equivalent to "pointMassGravity", "sphericalHarmonicGravity" and "mutualSphericalHarmonicGravity", respectively. However, a warning will be printed indicating that the body causing the acceleration may not be treated as a third body, requesting the user to remove the part "thridBody" in order to silence the warning.
Definition at line 37 of file acceleration.h.
Referenced by from_json(), tudat::simulation_setup::from_json(), tudat::simulation_setup::to_json(), and to_json().
unsupportedAccelerationTypes
std::vector< AvailableAcceleration > tudat::basic_astrodynamics::unsupportedAccelerationTypes static
Initial value:
=
{
    third_body_point_mass_gravity,
    third_body_spherical_harmonic_gravity,
    third_body_mutual_spherical_harmonic_gravity
}
Definition at line 54 of file acceleration.h.
Referenced by tudat::simulation_setup::from_json(), and tudat::simulation_setup::to_json().
massRateTypes
std::map< AvailableMassRateModels, std::string > tudat::basic_astrodynamics::massRateTypes static
Initial value:
=
{
    { undefined_mass_rate_model, "undefined" },
    { custom_mass_rate_model, "custom" },
    { from_thrust_mass_rate_model, "fromThrust" }
}
Definition at line 25 of file massRateModel.h.
Referenced by from_json(), tudat::simulation_setup::from_json(), tudat::simulation_setup::to_json(), and to_json().
unsupportedMassRateType
std::vector< AvailableMassRateModels > tudat::basic_astrodynamics::unsupportedMassRateType static
Initial value:
=
{
    undefined_mass_rate_model,
    custom_mass_rate_model
}
Definition at line 33 of file massRateModel.h.
Referenced by tudat::simulation_setup::from_json(), and tudat::simulation_setup::to_json().
torqueTypes
std::map< AvailableTorque, std::string > tudat::basic_astrodynamics::torqueTypes static
Initial value:
=
{
    { underfined_torque, "undefined" },
    { second_order_gravitational_torque, "secondOrderGravitational" },
    { aerodynamic_torque, "aerodynamic" }
}
Definition at line 25 of file torque.h.
Referenced by from_json(), tudat::simulation_setup::from_json(), tudat::simulation_setup::to_json(), and to_json().
unsupportedTorqueTypes
std::vector< AvailableTorque > tudat::basic_astrodynamics::unsupportedTorqueTypes = { } static
Definition at line 33 of file torque.h.
Referenced by tudat::simulation_setup::from_json(), and tudat::simulation_setup::to_json().