Tudat: tudat::acceleration_partials::RelativisticAccelerationPartial Class Reference
tudat::acceleration_partials::RelativisticAccelerationPartial Class Reference
Class to calculate the partials of the relativistic acceleration correction w.r.t. parameters and states.
#include <relativisticAccelerationPartial.h>
Public Member Functions
RelativisticAccelerationPartial (const std::shared_ptr< relativity::RelativisticAccelerationCorrection > accelerationModel, const std::string &acceleratedBody, const std::string &acceleratingBody)
Constructor.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter.
bool isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the acceleration is dependent on a non-translational integrated state.
void update (const double currentTime=TUDAT_NAN)
Function for updating partial w.r.t. the bodies' states.
void wrtGravitationalParameterOfCentralBody (Eigen::MatrixXd &partialMatrix)
Function to compute partial derivative of relativistic acceleration correction w.r.t. central body gravitational patameter.
void wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration.
void wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body exerting acceleration.
void wrtPpnParameterBeta (Eigen::MatrixXd &partialMatrix)
Function to compute partial derivative of relativistic acceleration correction w.r.t. PPN parameter beta.
void wrtPpnParameterGamma (Eigen::MatrixXd &partialMatrix)
Function to compute partial derivative of relativistic acceleration correction w.r.t. PPN parameter gamma.
void wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration.
void wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body exerting acceleration.
Public Member Functions inherited from tudat::acceleration_partials::AccelerationPartial
AccelerationPartial (const std::string &acceleratedBody, const std::string &acceleratingBody, const basic_astrodynamics::AvailableAcceleration accelerationType)
Base class constructor.
virtual ~AccelerationPartial ()
Virtual destructor.
std::string getAcceleratedBody ()
Function to retrieve the name of the body undergoing acceleration.
std::string getAcceleratingBody ()
Function to retrieve the name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration getAccelerationType ()
Function to retrieve the type of acceleration w.r.t. which partial is taken..
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
virtual bool isAccelerationPartialWrtAdditionalBodyNonnullptr (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the translational state of a third body is non-zero.
bool isStateDerivativeDependentOnIntegratedState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to check whether a partial w.r.t. some integrated state is non-zero.
virtual void wrtNonTranslationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the acceleration w.r.t. a non-translational integrated state.
virtual void wrtPositionOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of the third body.
void wrtStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body undergoing acceleration.
void wrtStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body exerting acceleration.
void wrtStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the third body.
virtual void wrtVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Private Attributes
std::function< Eigen::Vector6d() > acceleratedBodyState_
Function to retrieve current state of body undergoing acceleration.
std::function< double() > centralBodyGravitationalParameterFunction_
Function to retrieve current gravitational parameter of central body.
std::function< Eigen::Vector6d() > centralBodyState_
Function to retrieve current state of body exerting acceleration.
Eigen::Vector3d currentAcceleration_
Current relativistic acceleration correction.
std::function< Eigen::Vector3d() > currentAccelerationFunction_
Function to retrieve current relativistic acceleration correction.
Eigen::Matrix3d currentPartialWrtPosition_
Current partial of relativistic acceleration correction w.r.t. position of body undergoing acceleration.
Eigen::Matrix3d currentPartialWrtVelocity_
Current partial of relativistic acceleration correction w.r.t. velocity of body undergoing acceleration.
Eigen::Vector6d currentRelativeState_
Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
std::function< double() > ppnBetaParameterFunction_
Function to retrieve PPN parameter beta.
std::function< double() > ppnGammaParameterFunction_
Function to retrieve PPN parameter gamma.
Additional Inherited Members
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Protected Attributes inherited from tudat::acceleration_partials::AccelerationPartial
std::string acceleratedBody_
Name of the body undergoing acceleration.
std::string acceleratingBody_
Name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration accelerationType_
Type of acceleration w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Definition at line 92 of file relativisticAccelerationPartial.h.
Constructor & Destructor Documentation
RelativisticAccelerationPartial()
tudat::acceleration_partials::RelativisticAccelerationPartial::RelativisticAccelerationPartial (const std::shared_ptr< relativity::RelativisticAccelerationCorrection > accelerationModel, const std::string & acceleratedBody, const std::string & acceleratingBody) inline
Constructor.
Parameters
accelerationModel Relativistic acceleration correction w.r.t. which partials are to be taken.
acceleratedBody Body undergoing acceleration.
acceleratingBody Body exerting acceleration.
Definition at line 103 of file relativisticAccelerationPartial.h.
References acceleratedBodyState_, centralBodyGravitationalParameterFunction_, centralBodyState_, currentAccelerationFunction_, tudat::relativity::RelativisticAccelerationCorrection::getAcceleration(), ppnBetaParameterFunction_, and ppnGammaParameterFunction_.
Member Function Documentation
wrtPositionOfAcceleratedBody()
void tudat::acceleration_partials::RelativisticAccelerationPartial::wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 135 of file relativisticAccelerationPartial.h.
References currentPartialWrtPosition_.
wrtPositionOfAcceleratingBody()
void tudat::acceleration_partials::RelativisticAccelerationPartial::wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body exerting acceleration and adding it to the existing partial block. The update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 160 of file relativisticAccelerationPartial.h.
References currentPartialWrtPosition_.
wrtVelocityOfAcceleratedBody()
void tudat::acceleration_partials::RelativisticAccelerationPartial::wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 184 of file relativisticAccelerationPartial.h.
References currentPartialWrtVelocity_.
wrtVelocityOfAcceleratingBody()
void tudat::acceleration_partials::RelativisticAccelerationPartial::wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body exerting acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 209 of file relativisticAccelerationPartial.h.
References currentPartialWrtVelocity_.
isStateDerivativeDependentOnIntegratedNonTranslationalState()
bool tudat::acceleration_partials::RelativisticAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline virtual
Function for determining if the acceleration is dependent on a non-translational integrated state. No dependency is implemented, but a warning is provided if partial w.r.t. mass of body exerting acceleration (and undergoing acceleration if mutual attraction is used) is requested.
Parameters
stateReferencePoint Reference point id of propagated state
integratedStateType Type of propagated state for which dependency is to be determined.
Returns
True if dependency exists (non-zero partial), false otherwise.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 232 of file relativisticAccelerationPartial.h.
References tudat::acceleration_partials::AccelerationPartial::acceleratedBody_, tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, and tudat::propagators::body_mass_state.
getParameterPartialFunction() [1/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::RelativisticAccelerationPartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency, 1 otherwise).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 99 of file relativisticAccelerationPartial.cpp.
References tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, tudat::estimatable_parameters::gravitational_parameter, tudat::estimatable_parameters::ppn_parameter_beta, tudat::estimatable_parameters::ppn_parameter_gamma, wrtGravitationalParameterOfCentralBody(), wrtPpnParameterBeta(), and wrtPpnParameterGamma().
getParameterPartialFunction() [2/2]
std::pair< std::function< void(Eigen::MatrixXd&) >, int > tudat::acceleration_partials::RelativisticAccelerationPartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) inline virtual
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 263 of file relativisticAccelerationPartial.h.
wrtGravitationalParameterOfCentralBody()
void tudat::acceleration_partials::RelativisticAccelerationPartial::wrtGravitationalParameterOfCentralBody (Eigen::MatrixXd & partialMatrix) inline
Function to compute partial derivative of relativistic acceleration correction w.r.t. central body gravitational patameter.
Parameters
partialMatrix Requested (returnd by reference)
Definition at line 274 of file relativisticAccelerationPartial.h.
References centralBodyGravitationalParameterFunction_, tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtGravitationalParameter(), currentRelativeState_, ppnBetaParameterFunction_, and ppnGammaParameterFunction_.
Referenced by getParameterPartialFunction().
wrtPpnParameterGamma()
void tudat::acceleration_partials::RelativisticAccelerationPartial::wrtPpnParameterGamma (Eigen::MatrixXd & partialMatrix) inline
Function to compute partial derivative of relativistic acceleration correction w.r.t. PPN parameter gamma
Parameters
partialMatrix Requested (returnd by reference)
Definition at line 286 of file relativisticAccelerationPartial.h.
References centralBodyGravitationalParameterFunction_, tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterGamma(), and currentRelativeState_.
Referenced by getParameterPartialFunction().
wrtPpnParameterBeta()
void tudat::acceleration_partials::RelativisticAccelerationPartial::wrtPpnParameterBeta (Eigen::MatrixXd & partialMatrix) inline
Function to compute partial derivative of relativistic acceleration correction w.r.t. PPN parameter beta
Parameters
partialMatrix Requested (returnd by reference)
Definition at line 297 of file relativisticAccelerationPartial.h.
References centralBodyGravitationalParameterFunction_, tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterBeta(), and currentRelativeState_.
Referenced by getParameterPartialFunction().
update()
void tudat::acceleration_partials::RelativisticAccelerationPartial::update (const double currentTime = TUDAT_NAN) virtual
Function for updating common blocks of partial to current state. For the this acceleration, position and velocity partials is computed and set. Also, member variables are updated to current time/state.
Parameters
currentTime Time at which partials are to be calculated
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 139 of file relativisticAccelerationPartial.cpp.
References acceleratedBodyState_, centralBodyGravitationalParameterFunction_, centralBodyState_, tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPosition(), tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtVelocity(), currentAcceleration_, currentAccelerationFunction_, currentPartialWrtPosition_, currentPartialWrtVelocity_, currentRelativeState_, tudat::orbit_determination::StateDerivativePartial::currentTime_, ppnBetaParameterFunction_, and ppnGammaParameterFunction_.
Member Data Documentation
centralBodyState_
std::function< Eigen::Vector6d() > tudat::acceleration_partials::RelativisticAccelerationPartial::centralBodyState_ private
Definition at line 315 of file relativisticAccelerationPartial.h.
Referenced by RelativisticAccelerationPartial(), and update().
acceleratedBodyState_
std::function< Eigen::Vector6d() > tudat::acceleration_partials::RelativisticAccelerationPartial::acceleratedBodyState_ private
Definition at line 318 of file relativisticAccelerationPartial.h.
Referenced by RelativisticAccelerationPartial(), and update().
ppnGammaParameterFunction_
std::function< double() > tudat::acceleration_partials::RelativisticAccelerationPartial::ppnGammaParameterFunction_ private
Definition at line 321 of file relativisticAccelerationPartial.h.
Referenced by RelativisticAccelerationPartial(), update(), and wrtGravitationalParameterOfCentralBody().
ppnBetaParameterFunction_
std::function< double() > tudat::acceleration_partials::RelativisticAccelerationPartial::ppnBetaParameterFunction_ private
Definition at line 324 of file relativisticAccelerationPartial.h.
Referenced by RelativisticAccelerationPartial(), update(), and wrtGravitationalParameterOfCentralBody().
centralBodyGravitationalParameterFunction_
std::function< double() > tudat::acceleration_partials::RelativisticAccelerationPartial::centralBodyGravitationalParameterFunction_ private
Definition at line 327 of file relativisticAccelerationPartial.h.
Referenced by RelativisticAccelerationPartial(), update(), wrtGravitationalParameterOfCentralBody(), wrtPpnParameterBeta(), and wrtPpnParameterGamma().
currentAccelerationFunction_
std::function< Eigen::Vector3d() > tudat::acceleration_partials::RelativisticAccelerationPartial::currentAccelerationFunction_ private
Definition at line 330 of file relativisticAccelerationPartial.h.
Referenced by RelativisticAccelerationPartial(), and update().
currentPartialWrtPosition_
Eigen::Matrix3d tudat::acceleration_partials::RelativisticAccelerationPartial::currentPartialWrtPosition_ private
Current partial of relativistic acceleration correction w.r.t. position of body undergoing acceleration (= -partial of central gravity acceleration w.r.t. position of body exerting acceleration), calculated and set by update() function.
Definition at line 338 of file relativisticAccelerationPartial.h.
Referenced by update(), wrtPositionOfAcceleratedBody(), and wrtPositionOfAcceleratingBody().
currentPartialWrtVelocity_
Eigen::Matrix3d tudat::acceleration_partials::RelativisticAccelerationPartial::currentPartialWrtVelocity_ private
Current partial of relativistic acceleration correction w.r.t. velocity of body undergoing acceleration (= -partial of central gravity acceleration w.r.t. velocity of body exerting acceleration), calculated and set by update() function.
Definition at line 346 of file relativisticAccelerationPartial.h.
Referenced by update(), wrtVelocityOfAcceleratedBody(), and wrtVelocityOfAcceleratingBody().
currentRelativeState_
Eigen::Vector6d tudat::acceleration_partials::RelativisticAccelerationPartial::currentRelativeState_ private
Definition at line 349 of file relativisticAccelerationPartial.h.
Referenced by update(), wrtGravitationalParameterOfCentralBody(), wrtPpnParameterBeta(), and wrtPpnParameterGamma().
currentAcceleration_
Eigen::Vector3d tudat::acceleration_partials::RelativisticAccelerationPartial::currentAcceleration_ private
Definition at line 352 of file relativisticAccelerationPartial.h.
Referenced by update().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/AccelerationPartials/relativisticAccelerationPartial.h
Astrodynamics/OrbitDetermination/AccelerationPartials/relativisticAccelerationPartial.cpp