Tudat: tudat::estimatable_parameters::EstimatableParameter< ParameterType > Class Template Reference
tudat::estimatable_parameters::EstimatableParameter< ParameterType > Class Template Reference abstract
Base class for a parameter that is to be estimated.
#include <estimatableParameter.h>
Public Member Functions
EstimatableParameter (const EstimatebleParametersEnum parameterName, const std::string &associatedBody, const std::string &pointOnBodyId="")
Constructor.
virtual ~EstimatableParameter ()
Virtual destructor.
virtual std::string getParameterDescription ()
EstimatebleParameterIdentifier getParameterName ()
Function to retrieve the type and associated body of the parameter.
virtual int getParameterSize ()=0
Function to retrieve the size of the parameter.
virtual ParameterType getParameterValue ()=0
Pure virtual function to retrieve the value of the parameter.
virtual std::string getSecondaryIdentifier ()
Function to return additional identifier for parameter.
virtual void setParameterValue (const ParameterType parameterValue)=0
Pure virtual function to (re)set the value of the parameter.
Protected Attributes
EstimatebleParameterIdentifier parameterName_
Identifier of parameter.
Detailed Description
template<typename ParameterType>
class tudat::estimatable_parameters::EstimatableParameter< ParameterType >
Base class for a parameter that is to be estimated. A separate derived class is to be made for each type of parameter (i.e. gravitational parameter, initial translational state, etc.).
Definition at line 112 of file estimatableParameter.h.
Constructor & Destructor Documentation
template<typename ParameterType> tudat::estimatable_parameters::EstimatableParameter< ParameterType >::EstimatableParameter (const EstimatebleParametersEnum parameterName, const std::string & associatedBody, const std::string & pointOnBodyId = "") inline
Constructor taking parameter name and associated body. All parameters are identified by a these two variables. Any additional information that may be required for uniquely defining a parameter is to be defined in the derived class.
Parameters
parameterName Enum value defining the type of the parameter.
associatedBody Name of body associated with patameters
pointOnBodyId Reference point on body associated with parameter (empty by default).
Definition at line 124 of file estimatableParameter.h.
template<typename ParameterType> virtual tudat::estimatable_parameters::EstimatableParameter< ParameterType >::~EstimatableParameter () inline virtual
Definition at line 130 of file estimatableParameter.h.
Member Function Documentation
template<typename ParameterType> virtual ParameterType tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterValue () pure virtual
Pure virtual function to retrieve the value of the parameter
Returns
Current value of parameter.
Implemented in tudat::estimatable_parameters::ArcWiseEmpiricalAccelerationCoefficientsParameter, tudat::estimatable_parameters::SingleDegreeVariableTidalLoveNumber, tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter, tudat::estimatable_parameters::FullDegreeTidalLoveNumber, tudat::estimatable_parameters::ArcWiseInitialTranslationalStateParameter< InitialStateParameterType >, tudat::estimatable_parameters::ArcWiseRadiationPressureCoefficient, tudat::estimatable_parameters::PPNParameterBeta, tudat::estimatable_parameters::EmpiricalAccelerationCoefficientsParameter, tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients, tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients, tudat::estimatable_parameters::DirectTidalTimeLag, tudat::estimatable_parameters::ConstantObservationBiasParameter, tudat::estimatable_parameters::GroundStationPosition, tudat::estimatable_parameters::ConstantDragCoefficient, tudat::estimatable_parameters::RadiationPressureCoefficient, tudat::estimatable_parameters::ConstantRotationalOrientation, tudat::estimatable_parameters::RotationRate, tudat::estimatable_parameters::InitialTranslationalStateParameter< InitialStateParameterType >, tudat::estimatable_parameters::GravitationalParameter, tudat::estimatable_parameters::PPNParameterGamma, and tudat::estimatable_parameters::EquivalencePrincipleLpiViolationParameter.
Referenced by tudat::estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > >::~EstimatableParameter().
template<typename ParameterType> virtual void tudat::estimatable_parameters::EstimatableParameter< ParameterType >::setParameterValue (const ParameterType parameterValue) pure virtual
Pure virtual function to (re)set the value of the parameter.
Parameters
parameterValue to which the parameter is to be set.
Implemented in tudat::estimatable_parameters::ArcWiseEmpiricalAccelerationCoefficientsParameter, tudat::estimatable_parameters::SingleDegreeVariableTidalLoveNumber, tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter, tudat::estimatable_parameters::FullDegreeTidalLoveNumber, tudat::estimatable_parameters::ArcWiseInitialTranslationalStateParameter< InitialStateParameterType >, tudat::estimatable_parameters::ArcWiseRadiationPressureCoefficient, tudat::estimatable_parameters::EmpiricalAccelerationCoefficientsParameter, tudat::estimatable_parameters::PPNParameterBeta, tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients, tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients, tudat::estimatable_parameters::DirectTidalTimeLag, tudat::estimatable_parameters::ConstantObservationBiasParameter, tudat::estimatable_parameters::GroundStationPosition, tudat::estimatable_parameters::ConstantDragCoefficient, tudat::estimatable_parameters::RadiationPressureCoefficient, tudat::estimatable_parameters::ConstantRotationalOrientation, tudat::estimatable_parameters::RotationRate, tudat::estimatable_parameters::InitialTranslationalStateParameter< InitialStateParameterType >, tudat::estimatable_parameters::GravitationalParameter, tudat::estimatable_parameters::PPNParameterGamma, and tudat::estimatable_parameters::EquivalencePrincipleLpiViolationParameter.
Referenced by tudat::estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > >::~EstimatableParameter().
template<typename ParameterType> EstimatebleParameterIdentifier tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterName () inline
Function to retrieve the type and associated body of the parameter.
Returns
Identifier of parameter as a pair of parameter type and body of which parameter is a property.
Definition at line 151 of file estimatableParameter.h.
Referenced by tudat::observation_partials::createAngularPositionPartials(), tudat::observation_partials::createOneWayDopplerPartials(), and tudat::observation_partials::createOneWayRangePartials().
template<typename ParameterType> virtual std::string tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterDescription () inline virtual
Reimplemented in tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter, tudat::estimatable_parameters::EmpiricalAccelerationCoefficientsParameter, tudat::estimatable_parameters::ConstantObservationBiasParameter, tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients, and tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients.
Definition at line 153 of file estimatableParameter.h.
Referenced by tudat::estimatable_parameters::printEstimatableParameterEntries().
template<typename ParameterType> virtual int tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getParameterSize () pure virtual
Pure virtual function to retrieve the size of the parameter (i.e. 1 for double parameters)
Returns
Size of parameter value.
Implemented in tudat::estimatable_parameters::ArcWiseEmpiricalAccelerationCoefficientsParameter, tudat::estimatable_parameters::ConstantRelativeObservationBiasParameter, tudat::estimatable_parameters::ArcWiseInitialTranslationalStateParameter< InitialStateParameterType >, tudat::estimatable_parameters::ArcWiseRadiationPressureCoefficient, tudat::estimatable_parameters::EmpiricalAccelerationCoefficientsParameter, tudat::estimatable_parameters::PPNParameterBeta, tudat::estimatable_parameters::DirectTidalTimeLag, tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients, tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients, tudat::estimatable_parameters::ConstantObservationBiasParameter, tudat::estimatable_parameters::ConstantDragCoefficient, tudat::estimatable_parameters::GroundStationPosition, tudat::estimatable_parameters::ConstantRotationalOrientation, tudat::estimatable_parameters::RadiationPressureCoefficient, tudat::estimatable_parameters::TidalLoveNumber< ParameterScalar >, tudat::estimatable_parameters::TidalLoveNumber< Eigen::VectorXd >, tudat::estimatable_parameters::RotationRate, tudat::estimatable_parameters::InitialTranslationalStateParameter< InitialStateParameterType >, tudat::estimatable_parameters::GravitationalParameter, tudat::estimatable_parameters::PPNParameterGamma, and tudat::estimatable_parameters::EquivalencePrincipleLpiViolationParameter.
Referenced by tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::EstimatableParameterSet(), tudat::estimatable_parameters::EstimatableParameterSet< InitialStateParameterType >::getFullParameterValues(), tudat::estimatable_parameters::getInitialStateVectorOfBodiesToEstimate(), and tudat::estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > >::getParameterDescription().
template<typename ParameterType> virtual std::string tudat::estimatable_parameters::EstimatableParameter< ParameterType >::getSecondaryIdentifier () inline virtual
Function to return additional identifier for parameter, beyond information stored in parameterName_, default none.
Returns
Additional identifier for parameter (default empty string).
Definition at line 180 of file estimatableParameter.h.
Member Data Documentation
template<typename ParameterType> EstimatebleParameterIdentifier tudat::estimatable_parameters::EstimatableParameter< ParameterType >::parameterName_ protected
Definition at line 188 of file estimatableParameter.h.
Referenced by tudat::estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > >::getParameterDescription(), and tudat::estimatable_parameters::EstimatableParameter< Eigen::Matrix< InitialStateParameterType, Eigen::Dynamic, 1 > >::getParameterName().
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/EstimatableParameters/estimatableParameter.h