Tudat: tudat::interpolators Namespace Reference
tudat::interpolators Namespace Reference
Interpolators namespace.
Classes
class BinarySearchLookupScheme
Look-up scheme class for nearest left neighbour search using binary search algorithm.
class CubicSplineInterpolator
Cubic spline interpolator, implementation from (Press W.H., et al., 2002).
class DataInterpolationSettings
Constructor.
class DataMapSettings
Class defening the settings to be used to create a map of data (used for interpolation).
class FromFileDataMapSettings
Class defening the settings to be used to create a map of data (used for interpolation).
class HermiteCubicSplineInterpolator
Hermite Cubic Spline Interpolator.
class HermiteDataSettings
Class defening the settings to be used to create a map of data (used for interpolation).
class HuntingAlgorithmLookupScheme
Look-up scheme class for nearest left neighbour search using hunting algorithm.
class IndependentDependentDataMapSettings
Class defening the settings to be used to create a map of data (used for interpolation).
class Interpolator
Base class for interpolator.
class InterpolatorSettings
Base class for providing settings for creating an interpolator.
class JumpDataLinearInterpolator
Linear interpolation class with discrete jumps in data.
class LagrangeInterpolator
Class to perform Lagrange polynomial interpolation.
class LagrangeInterpolatorSettings
Class for providing settings to creating a Lagrange interpolator.
class LinearInterpolator
Linear interpolator class.
class LookUpScheme
Look-up scheme class for nearest left neighbour search.
class MultiDimensionalInterpolator
Base class for interpolator with multiple independent variables.
class MultiLinearInterpolator
Class for performing multi-linear interpolation for arbitrary number of independent variables.
class OneDimensionalInterpolator
Base class for interpolator with one independent variable.
class PiecewiseConstantInterpolator
Piecewise constant interpolator class.
Typedefs
typedef std::shared_ptr< BinarySearchLookupScheme< double > > BinarySearchLookupSchemeDoublePointer
Typedef for shared-pointer to BinarySearchLookupScheme object with double-type entries.
typedef CubicSplineInterpolator< double, double > CubicSplineInterpolatorDouble
Typedef for cubic spline interpolator with (in)dependent = double.
typedef std::shared_ptr< CubicSplineInterpolatorDouble > CubicSplineInterpolatorDoublePointer
Typedef for shared-pointer to cubic spline interpolator with (in)dependent = double.
typedef HermiteCubicSplineInterpolator< double, double > HermiteCubicSplineInterpolatorDouble
Typede for cubic hermite spline with double (in)dependent variables.
typedef std::shared_ptr< HuntingAlgorithmLookupScheme< double > > HuntingAlgorithmLookupSchemeDoublePointer
Typedef for shared-pointer to HuntingAlgorithmLookupScheme object with double-type entries.
typedef LagrangeInterpolator< double, double > LagrangeInterpolatorDouble
Typedef for LagrangeInterpolator with double as both its dependent and independent data type.
typedef LinearInterpolator< double, double > LinearInterpolatorDouble
Typedef for linear interpolator with (in)dependent variable = double.
typedef std::shared_ptr< LinearInterpolatorDouble > LinearInterpolatorDoublePointer
Typedef for shared-pointer to linear interpolator with (in)dependent variable = double.
typedef std::shared_ptr< LookUpScheme< double > > LookUpSchemeDoublePointer
Typedef for shared-pointer to LookUpScheme object with double-type entries.
Enumerations
enum AvailableLookupScheme { huntingAlgorithm, binarySearch }
Enum of available lookup schemes.
enum BoundaryInterpolationType {
throw_exception_at_boundary = 0, use_boundary_value = 1, use_boundary_value_with_warning = 2, extrapolate_at_boundary = 3,
extrapolate_at_boundary_with_warning = 4, use_default_value = 5, use_default_value_with_warning = 6
}
Enumeration for types of boundary interpolation methods.
enum InterpolatorTypes {
linear_interpolator = 0, multi_linear_interpolator = 1, cubic_spline_interpolator = 2, lagrange_interpolator = 3,
hermite_spline_interpolator = 4, piecewise_constant_interpolator = 5
}
Enumeration of available interpolator types.
enum LagrangeInterpolatorBoundaryHandling { lagrange_cubic_spline_boundary_interpolation = 0, lagrange_no_boundary_interpolation = 1 }
Enum defining the manner in which to handle the edges of the Lagrange interpolator.
Functions
double computeLinearInterpolation (const Eigen::VectorXd &sortedIndependentVariables, const Eigen::VectorXd &associatedDependentVariables, const double targetIndependentVariableValue)
Compute linear interpolation.
Eigen::VectorXd computeLinearInterpolation (const std::map< double, Eigen::VectorXd > &sortedIndepedentAndDependentVariables, const double targetIndependentVariableValue)
Compute linear interpolation.
template<typename IndependentVariableType , typename DependentVariableType , unsigned int NumberOfDimensions>
std::shared_ptr< MultiDimensionalInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions > > createMultiDimensionalInterpolator (const std::vector< std::vector< IndependentVariableType > > &independentValues, const boost::multi_array< DependentVariableType, static_cast< size_t >(NumberOfDimensions) > &dependentData, const std::shared_ptr< InterpolatorSettings > interpolatorSettings, const std::vector< std::pair< DependentVariableType, DependentVariableType > > &defaultExtrapolationValue=std::vector< std::pair< DependentVariableType, DependentVariableType > >(NumberOfDimensions, std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >())))
Function to create a multi-dimensional interpolator.
template<typename IndependentVariableType , typename DependentVariableType >
std::shared_ptr< OneDimensionalInterpolator< IndependentVariableType, DependentVariableType > > createOneDimensionalInterpolator (const std::map< IndependentVariableType, DependentVariableType > dataToInterpolate, const std::shared_ptr< InterpolatorSettings > interpolatorSettings, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()), const std::vector< DependentVariableType > firstDerivativeOfDependentVariables=std::vector< DependentVariableType >())
Function to create a one-dimensional interpolator.
template<typename IndependentType , typename DependentType >
std::shared_ptr< OneDimensionalInterpolator< IndependentType, DependentType > > createOneDimensionalInterpolator (const std::shared_ptr< DataInterpolationSettings< IndependentType, DependentType > > dataInterpolationSettings, const std::pair< DependentType, DependentType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentType >(), IdentityElement::getAdditionIdentity< DependentType >()))
Function to create an interpolator from DataInterpolationSettings.
void from_json (const nlohmann::json &jsonObject, InterpolatorTypes &oneDimensionalInterpolatorType)
Convert json to InterpolatorTypes.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< InterpolatorSettings > &interpolatorSettings)
Create a shared pointer to a InterpolatorSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, AvailableLookupScheme &availableLookupScheme)
Convert json to AvailableLookupScheme.
void from_json (const nlohmann::json &jsonObject, BoundaryInterpolationType &boundaryHandling)
Convert json to BoundaryInterpolationType.
void from_json (const nlohmann::json &jsonObject, LagrangeInterpolatorBoundaryHandling &lagrangeInterpolatorBoundaryHandling)
Convert json to LagrangeInterpolatorBoundaryHandling.
template<typename I , typename D >
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< DataMapSettings< I, D > > &dataMapSettings)
Create a shared pointer to a DataMapSettings object from a json object.
template<typename I , typename D >
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< DataInterpolationSettings< I, D > > &dataInterpolationSettings)
Create a shared pointer to a DataInterpolationSettings object from a json object.
template<typename IndependentVariableType , typename DependentVariableType >
std::vector< DependentVariableType > solveTridiagonalMatrixEquation (const std::vector< IndependentVariableType > &subDiagonal, const std::vector< IndependentVariableType > &diagonal, const std::vector< IndependentVariableType > &superDiagonal, const std::vector< DependentVariableType > &rightHandSide)
Solve efficiently tri-diagonal matrix equation.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< InterpolatorSettings > &interpolatorSettings)
Create a json object from a shared pointer to a InterpolatorSettings object.
void to_json (nlohmann::json &jsonObject, const InterpolatorTypes &oneDimensionalInterpolatorType)
Convert InterpolatorTypes to json.
void to_json (nlohmann::json &jsonObject, const AvailableLookupScheme &availableLookupScheme)
Convert AvailableLookupScheme to json.
void to_json (nlohmann::json &jsonObject, const BoundaryInterpolationType &boundaryHandling)
Convert BoundaryInterpolationType to json.
void to_json (nlohmann::json &jsonObject, const LagrangeInterpolatorBoundaryHandling &lagrangeInterpolatorBoundaryHandling)
Convert LagrangeInterpolatorBoundaryHandling to json.
template<typename I , typename D >
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< DataMapSettings< I, D > > &dataMapSettings)
Create a json object from a shared pointer to a DataMapSettings object.
template<typename I , typename D >
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< DataInterpolationSettings< I, D > > &dataInterpolationSettings)
Create a json object from a shared pointer to a DataInterpolationSettings object.
Variables
static std::map< BoundaryInterpolationType, std::string > boundaryInterpolationTypes
Map of AvailableLookupSchemes string representations.
static std::map< LagrangeInterpolatorBoundaryHandling, std::string > lagrangeInterpolatorBoundaryHandlings
Map of LagrangeInterpolatorBoundaryHandlings string representations.
static std::map< AvailableLookupScheme, std::string > lookupSchemeTypes
Map of AvailableLookupSchemes string representations.
static std::map< InterpolatorTypes, std::string > oneDimensionalInterpolatorTypes
Map of InterpolatorTypes string representations.
static std::vector< BoundaryInterpolationType > unsupportedBoundaryInterpolationTypes
BoundaryInterpolationTypes not supported by json_interface.
static std::vector< LagrangeInterpolatorBoundaryHandling > unsupportedLagrangeInterpolatorBoundaryHandlings = { }
LagrangeInterpolatorBoundaryHandlings not supported by json_interface.
static std::vector< AvailableLookupScheme > unsupportedLookupSchemeTypes = { }
AvailableLookupSchemes not supported by json_interface.
static std::vector< InterpolatorTypes > unsupportedOneDimensionalInterpolatorTypes = { }
InterpolatorTypes not supported by json_interface.
Detailed Description
The interpolators namespace.
Typedef Documentation
CubicSplineInterpolatorDouble
typedef CubicSplineInterpolator< double, double > tudat::interpolators::CubicSplineInterpolatorDouble
Definition at line 434 of file cubicSplineInterpolator.h.
CubicSplineInterpolatorDoublePointer
typedef std::shared_ptr< CubicSplineInterpolatorDouble > tudat::interpolators::CubicSplineInterpolatorDoublePointer
Definition at line 437 of file cubicSplineInterpolator.h.
HermiteCubicSplineInterpolatorDouble
typedef HermiteCubicSplineInterpolator< double, double > tudat::interpolators::HermiteCubicSplineInterpolatorDouble
Definition at line 232 of file hermiteCubicSplineInterpolator.h.
LagrangeInterpolatorDouble
typedef LagrangeInterpolator< double, double > tudat::interpolators::LagrangeInterpolatorDouble
Definition at line 507 of file lagrangeInterpolator.h.
LinearInterpolatorDouble
typedef LinearInterpolator< double, double > tudat::interpolators::LinearInterpolatorDouble
Definition at line 258 of file linearInterpolator.h.
LinearInterpolatorDoublePointer
typedef std::shared_ptr< LinearInterpolatorDouble > tudat::interpolators::LinearInterpolatorDoublePointer
Definition at line 261 of file linearInterpolator.h.
LookUpSchemeDoublePointer
typedef std::shared_ptr< LookUpScheme< double > > tudat::interpolators::LookUpSchemeDoublePointer
Definition at line 218 of file lookupScheme.h.
HuntingAlgorithmLookupSchemeDoublePointer
typedef std::shared_ptr< HuntingAlgorithmLookupScheme< double > > tudat::interpolators::HuntingAlgorithmLookupSchemeDoublePointer
Definition at line 222 of file lookupScheme.h.
BinarySearchLookupSchemeDoublePointer
typedef std::shared_ptr< BinarySearchLookupScheme< double > > tudat::interpolators::BinarySearchLookupSchemeDoublePointer
Definition at line 226 of file lookupScheme.h.
Enumeration Type Documentation
InterpolatorTypes
enum tudat::interpolators::InterpolatorTypes
Enumerator
linear_interpolator
multi_linear_interpolator
cubic_spline_interpolator
lagrange_interpolator
hermite_spline_interpolator
piecewise_constant_interpolator
Definition at line 36 of file createInterpolator.h.
BoundaryInterpolationType
enum tudat::interpolators::BoundaryInterpolationType
Enumeration for types of boundary interpolation methods, i.e., for when the independent variable requested for interpolation is outside the domain of the independent variables input in the interpolator constructor.
Enumerator
throw_exception_at_boundary
use_boundary_value
use_boundary_value_with_warning
extrapolate_at_boundary
extrapolate_at_boundary_with_warning
use_default_value
use_default_value_with_warning
Definition at line 32 of file interpolator.h.
LagrangeInterpolatorBoundaryHandling
enum tudat::interpolators::LagrangeInterpolatorBoundaryHandling
Enumerator
lagrange_cubic_spline_boundary_interpolation
lagrange_no_boundary_interpolation
Definition at line 36 of file lagrangeInterpolator.h.
AvailableLookupScheme
enum tudat::interpolators::AvailableLookupScheme
Enum of available lookup schemes.
Enumerator
huntingAlgorithm
binarySearch
Definition at line 30 of file lookupScheme.h.
Function Documentation
to_json() [1/7]
void tudat::interpolators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< InterpolatorSettings > & interpolatorSettings)
Definition at line 23 of file interpolation.cpp.
References tudat::json_interface::assertNonnullptrPointer(), cubic_spline_interpolator, tudat::json_interface::handleUnimplementedEnumValue(), hermite_spline_interpolator, lagrange_interpolator, linear_interpolator, oneDimensionalInterpolatorTypes, piecewise_constant_interpolator, and unsupportedOneDimensionalInterpolatorTypes.
from_json() [1/7]
void tudat::interpolators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< InterpolatorSettings > & interpolatorSettings)
Definition at line 61 of file interpolation.cpp.
References cubic_spline_interpolator, tudat::interpolators::InterpolatorSettings::getBoundaryHandling(), tudat::interpolators::LagrangeInterpolatorSettings::getLagrangeBoundaryHandling(), tudat::interpolators::InterpolatorSettings::getSelectedLookupScheme(), tudat::interpolators::InterpolatorSettings::getUseLongDoubleTimeStep(), tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), hermite_spline_interpolator, lagrange_interpolator, linear_interpolator, oneDimensionalInterpolatorTypes, piecewise_constant_interpolator, and unsupportedOneDimensionalInterpolatorTypes.
to_json() [2/7]
void tudat::interpolators::to_json (nlohmann::json & jsonObject, const InterpolatorTypes & oneDimensionalInterpolatorType) inline
Definition at line 40 of file interpolation.h.
References oneDimensionalInterpolatorTypes, and tudat::json_interface::stringFromEnum().
from_json() [2/7]
void tudat::interpolators::from_json (const nlohmann::json & jsonObject, InterpolatorTypes & oneDimensionalInterpolatorType) inline
Definition at line 46 of file interpolation.h.
References tudat::json_interface::enumFromString(), and oneDimensionalInterpolatorTypes.
to_json() [3/7]
void tudat::interpolators::to_json (nlohmann::json & jsonObject, const AvailableLookupScheme & availableLookupScheme) inline
Definition at line 66 of file interpolation.h.
References lookupSchemeTypes, and tudat::json_interface::stringFromEnum().
from_json() [3/7]
void tudat::interpolators::from_json (const nlohmann::json & jsonObject, AvailableLookupScheme & availableLookupScheme) inline
Definition at line 72 of file interpolation.h.
References tudat::json_interface::enumFromString(), and lookupSchemeTypes.
to_json() [4/7]
void tudat::interpolators::to_json (nlohmann::json & jsonObject, const BoundaryInterpolationType & boundaryHandling) inline
Definition at line 95 of file interpolation.h.
References boundaryInterpolationTypes, and tudat::json_interface::stringFromEnum().
from_json() [4/7]
void tudat::interpolators::from_json (const nlohmann::json & jsonObject, BoundaryInterpolationType & boundaryHandling) inline
Definition at line 101 of file interpolation.h.
References boundaryInterpolationTypes, and tudat::json_interface::enumFromString().
to_json() [5/7]
void tudat::interpolators::to_json (nlohmann::json & jsonObject, const LagrangeInterpolatorBoundaryHandling & lagrangeInterpolatorBoundaryHandling) inline
Definition at line 120 of file interpolation.h.
References lagrangeInterpolatorBoundaryHandlings, and tudat::json_interface::stringFromEnum().
from_json() [5/7]
void tudat::interpolators::from_json (const nlohmann::json & jsonObject, LagrangeInterpolatorBoundaryHandling & lagrangeInterpolatorBoundaryHandling) inline
Definition at line 128 of file interpolation.h.
References tudat::json_interface::enumFromString(), and lagrangeInterpolatorBoundaryHandlings.
to_json() [6/7]
template<typename I , typename D > void tudat::interpolators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< DataMapSettings< I, D > > & dataMapSettings)
Definition at line 140 of file interpolation.h.
References tudat::interpolators::DataMapSettings< IndependentType, DependentType >::getDataMap(), and tudat::interpolators::IndependentDependentDataMapSettings< IndependentType, DependentType >::independentVariableValues_.
from_json() [6/7]
template<typename I , typename D > void tudat::interpolators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< DataMapSettings< I, D > > & dataMapSettings)
Definition at line 181 of file interpolation.h.
References tudat::json_interface::getValue(), and tudat::json_interface::isDefined().
to_json() [7/7]
template<typename I , typename D > void tudat::interpolators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< DataInterpolationSettings< I, D > > & dataInterpolationSettings)
Definition at line 228 of file interpolation.h.
from_json() [7/7]
template<typename I , typename D > void tudat::interpolators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< DataInterpolationSettings< I, D > > & dataInterpolationSettings)
Definition at line 244 of file interpolation.h.
References tudat::json_interface::getValue().
createOneDimensionalInterpolator() [1/2]
template<typename IndependentVariableType , typename DependentVariableType > std::shared_ptr< OneDimensionalInterpolator< IndependentVariableType, DependentVariableType > > tudat::interpolators::createOneDimensionalInterpolator (const std::map< IndependentVariableType, DependentVariableType > dataToInterpolate, const std::shared_ptr< InterpolatorSettings > interpolatorSettings, const std::pair< DependentVariableType, DependentVariableType > & defaultExtrapolationValue = std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()), const std::vector< DependentVariableType > firstDerivativeOfDependentVariables = std::vector< DependentVariableType >())
Function to create a one-dimensional interpolator from the data that is to be interpolated, as well as the settings that are to be used to create the interpolator.
Parameters
dataToInterpolate Map providing data that is to be interpolated (key = independent variables, value = dependent variables).
interpolatorSettings Settings that are to be used to create interpolator.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
firstDerivativeOfDependentVariables First derivative of dependent variables w.r.t. independent variable at independent variables values in values of dataToInterpolate. By default, this vector is empty, it only needs to be supplied if the selected interpolator requires this data (e.g. Hermite spline).
Returns
Interpolator created from dataToInterpolate using interpolatorSettings.
Definition at line 449 of file createInterpolator.h.
References cubic_spline_interpolator, hermite_spline_interpolator, lagrange_interpolator, linear_interpolator, and piecewise_constant_interpolator.
Referenced by tudat::earth_orientation::createInterpolatorsForItrsToGcrsAngles(), createOneDimensionalInterpolator(), tudat::simulation_setup::createUnivariateTabulatedCoefficientAerodynamicCoefficientInterface(), and tudat::simulation_setup::ThrustAccelerationSettings::ThrustAccelerationSettings().
createOneDimensionalInterpolator() [2/2]
template<typename IndependentType , typename DependentType > std::shared_ptr< OneDimensionalInterpolator< IndependentType, DependentType > > tudat::interpolators::createOneDimensionalInterpolator (const std::shared_ptr< DataInterpolationSettings< IndependentType, DependentType > > dataInterpolationSettings, const std::pair< DependentType, DependentType > & defaultExtrapolationValue = std::make_pair(IdentityElement::getAdditionIdentity< DependentType >(), IdentityElement::getAdditionIdentity< DependentType >()))
Function to create an interpolator from DataInterpolationSettings
Parameters
dataInterpolationSettings Object containing the data that is to be interpolated and settings that are to be used to create the interpolator.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Returns
Interpolator created from dataToInterpolate using interpolatorSettings.
Definition at line 568 of file createInterpolator.h.
References createOneDimensionalInterpolator().
createMultiDimensionalInterpolator()
template<typename IndependentVariableType , typename DependentVariableType , unsigned int NumberOfDimensions> std::shared_ptr< MultiDimensionalInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions > > tudat::interpolators::createMultiDimensionalInterpolator (const std::vector< std::vector< IndependentVariableType > > & independentValues, const boost::multi_array< DependentVariableType, static_cast< size_t >(NumberOfDimensions) > & dependentData, const std::shared_ptr< InterpolatorSettings > interpolatorSettings, const std::vector< std::pair< DependentVariableType, DependentVariableType > > & defaultExtrapolationValue = std::vector< std::pair< DependentVariableType, DependentVariableType > > (NumberOfDimensions, std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >())))
Function to create a multi-dimensional interpolator from the data that is to be interpolated, as well as the settings that are to be used to create the interpolator.
Parameters
independentValues Vector of vectors containing data points of independent variables, each must be sorted in ascending order.
dependentData Multi-dimensional array of dependent data at each point of hyper-rectangular grid formed by independent variable points.
interpolatorSettings Settings that are to be used to create interpolator.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Returns
Interpolator created from independentValues and dependentData using interpolatorSettings.
Definition at line 603 of file createInterpolator.h.
References extrapolate_at_boundary, and multi_linear_interpolator.
solveTridiagonalMatrixEquation()
template<typename IndependentVariableType , typename DependentVariableType > std::vector< DependentVariableType > tudat::interpolators::solveTridiagonalMatrixEquation (const std::vector< IndependentVariableType > & subDiagonal, const std::vector< IndependentVariableType > & diagonal, const std::vector< IndependentVariableType > & superDiagonal, const std::vector< DependentVariableType > & rightHandSide)
This functions efficiently solves the matrix equation Ax = b for b, where A is tri-diagonal. The required input are the diagonal and sub/super diagonals of A, as well as the vector b. Input is given as STL vectors. The input diagonals must be at least the same size as right-hand-side. Any additional entries (at end) will be ignored in the algorithm.
Template Parameters
IndependentVariableType Type of independent variables.
DependentVariableType Type of dependent variables.
Parameters
subDiagonal Sub-diagonal of matrix A.
superDiagonal Super-diagonal of matrix A.
diagonal Diagonal of matrix A.
rightHandSide Right-hand-side of matrix equation.
Returns
Solution to matrix equation.
Definition at line 49 of file cubicSplineInterpolator.h.
computeLinearInterpolation() [1/2]
double tudat::interpolators::computeLinearInterpolation (const Eigen::VectorXd & sortedIndependentVariables, const Eigen::VectorXd & associatedDependentVariables, const double targetIndependentVariableValue)
Compute linear interpolation free function.
Computes linear interpolation of data provided in the form of a vector of sorted indepedent variables and an associated vector of dependent variables. The linear interpolation equation used is:
where and .
Parameters
sortedIndependentVariables Vector of independent variables sorted. in ascending/descending order.
associatedDependentVariables Vector of dependent variables associated with sorted vector of independent variables.
targetIndependentVariableValue Target independent variable value in vector of sorted independent variables.
Returns
Value of dependent variable associated with target independent value in vector of sorted independent variables.
Definition at line 26 of file linearInterpolator.cpp.
References tudat::basic_mathematics::computeNearestLeftNeighborUsingBinarySearch().
computeLinearInterpolation() [2/2]
Eigen::VectorXd tudat::interpolators::computeLinearInterpolation (const std::map< double, Eigen::VectorXd > & sortedIndepedentAndDependentVariables, const double targetIndependentVariableValue)
Compute linear interpolation free function.
Computes linear interpolation of data provided in the form of a map of independent variables and associated vectors of dependent variables. The linear interpolation equation used is:
where and .
Parameters
sortedIndepedentAndDependentVariables Map of sorted independent variables, in ascending/descending order, and associated dependent variables.
targetIndependentVariableValue Target independent variable value in vector of sorted independent variables.
Returns
Vector of dependent variable associated with target independent value in vector of sorted independent variables.
Definition at line 56 of file linearInterpolator.cpp.
References tudat::basic_mathematics::computeNearestLeftNeighborUsingBinarySearch().
Variable Documentation
oneDimensionalInterpolatorTypes
std::map< InterpolatorTypes, std::string > tudat::interpolators::oneDimensionalInterpolatorTypes static
Initial value:
=
{
    { linear_interpolator, "linear" },
    { cubic_spline_interpolator, "cubicSpline" },
    { lagrange_interpolator, "lagrange" },
    { hermite_spline_interpolator, "hermiteSpline" },
    { piecewise_constant_interpolator, "piecewiseConstant" }
}
Definition at line 27 of file interpolation.h.
Referenced by from_json(), and to_json().
unsupportedOneDimensionalInterpolatorTypes
std::vector< InterpolatorTypes > tudat::interpolators::unsupportedOneDimensionalInterpolatorTypes = { } static
Definition at line 37 of file interpolation.h.
Referenced by from_json(), and to_json().
lookupSchemeTypes
std::map< AvailableLookupScheme, std::string > tudat::interpolators::lookupSchemeTypes static
Initial value:
=
{
    { huntingAlgorithm, "huntingAlgorithm" },
    { binarySearch, "binarySearch" }
}
Definition at line 56 of file interpolation.h.
Referenced by from_json(), and to_json().
unsupportedLookupSchemeTypes
std::vector< AvailableLookupScheme > tudat::interpolators::unsupportedLookupSchemeTypes = { } static
Definition at line 63 of file interpolation.h.
boundaryInterpolationTypes
std::map< BoundaryInterpolationType, std::string > tudat::interpolators::boundaryInterpolationTypes static
Initial value:
=
{
    { throw_exception_at_boundary, "throwException" },
    { use_boundary_value, "boundaryValue" },
    { use_boundary_value_with_warning, "boundaryValueWithWarning" },
    { extrapolate_at_boundary, "extrapolate" },
    { extrapolate_at_boundary_with_warning, "extrapolateWithWarning" }
}
Definition at line 81 of file interpolation.h.
Referenced by from_json(), and to_json().
unsupportedBoundaryInterpolationTypes
std::vector< BoundaryInterpolationType > tudat::interpolators::unsupportedBoundaryInterpolationTypes static
Initial value:
=
{ use_default_value, use_default_value_with_warning }
Definition at line 91 of file interpolation.h.
lagrangeInterpolatorBoundaryHandlings
std::map< LagrangeInterpolatorBoundaryHandling, std::string > tudat::interpolators::lagrangeInterpolatorBoundaryHandlings static
Initial value:
=
{
    { lagrange_cubic_spline_boundary_interpolation, "cubicSplineBoundary" },
    { lagrange_no_boundary_interpolation, "noBoundary" }
}
Definition at line 110 of file interpolation.h.
Referenced by from_json(), and to_json().
unsupportedLagrangeInterpolatorBoundaryHandlings
std::vector< LagrangeInterpolatorBoundaryHandling > tudat::interpolators::unsupportedLagrangeInterpolatorBoundaryHandlings = { } static
Definition at line 117 of file interpolation.h.