Tudat: tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo Class Reference
tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo Class Reference
Izzo Lambert targeting algorithm class (zero revolution).
#include <zeroRevolutionLambertTargeterIzzo.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW ZeroRevolutionLambertTargeterIzzo (const Eigen::Vector3d &aCartesianPositionAtDeparture, const Eigen::Vector3d &aCartesianPositionAtArrival, const double aTimeOfFlight, const double aGravitationalParameter, const bool aIsRetrograde=false, const double aConvergenceTolerance=1.0e-9, const int aMaximumNumberOfIterations=50)
Zero revolution Lambert problem constructor for problem definition.
double getRadialVelocityAtArrival ()
Get radial velocity at arrival.
double getRadialVelocityAtDeparture ()
Get radial velocity at departure.
double getSemiMajorAxis ()
Get semi-major axis.
double getTransverseVelocityAtArrival ()
Get transverse velocity at arrival.
double getTransverseVelocityAtDeparture ()
Get transverse velocity at departure.
Public Member Functions inherited from tudat::mission_segments::LambertTargeter
EIGEN_MAKE_ALIGNED_OPERATOR_NEW LambertTargeter (const Eigen::Vector3d &aCartesianPositionAtDeparture, const Eigen::Vector3d &aCartesianPositionAtArrival, const double aTimeOfFlight, const double aGravitationalParameter)
Default constructor.
virtual ~LambertTargeter ()
Default destructor.
Eigen::Vector3d getInertialVelocityAtArrival ()
Get inertial velocity at arrival.
Eigen::Vector3d getInertialVelocityAtDeparture ()
Get inertial velocity at departure.
std::pair< Eigen::Vector3d, Eigen::Vector3d > getInertialVelocityVectors ()
Get inertial velocity vectors.
Protected Member Functions
virtual double computeRootTimeOfFlight ()
Solve the time of flight equation for x.
virtual double computeTimeOfFlight (const double xParameter)
Compute time-of-flight using Lagrange's equation.
void computeVelocities (const double xParameter)
Compute velocities at departure and arrival.
virtual void execute ()
Execute the solving procedure.
void sanityCheckGravitationalParameter ()
Sanity check gravitational parameter.
void sanityCheckTimeOfFlight ()
Sanity check time of flight.
void transformDimensions ()
Transform input to sub results in adimensional units.
Protected Attributes
const double convergenceTolerance
Convergence tolerance.
bool isLongway
Longway flag.
const bool isRetrograde
Retrograde motion flag.
double lambdaParameter
Lambda parameter.
const double maximumNumberOfIterations
Maximum number of iterations.
double normalizedChord
Normalized chord.
double normalizedMinimumEnergySemiMajorAxis
Normalized semi-major axis of minimum energy ellipse.
double normalizedRadiusAtArrival
Normalized radius at arrival.
double normalizedSemiPerimeter
Normalized semi-perimeter.
double normalizedTimeOfFlight
Normalized time-of-flight.
double transferAngle
Transfer angle.
bool transformed
Transformed flag.
double velocityNormalizingValue
Normalizing value for velocity.
Protected Attributes inherited from tudat::mission_segments::LambertTargeter
const Eigen::Vector3d cartesianPositionAtArrival
Cartesian position at arrival.
const Eigen::Vector3d cartesianPositionAtDeparture
Cartesian position at departure.
Eigen::Vector3d cartesianVelocityAtArrival
Cartesian velocity at arrival.
Eigen::Vector3d cartesianVelocityAtDeparture
Cartesian velocity at departure.
const double gravitationalParameter
Gravitational parameter.
bool solved
Solved boolean flag.
const double timeOfFlight
Time-of-flight.
Detailed Description
Solves the zero revolution Lambert problem using Izzo's algorithms, i.e. the two point boundary value problem of what kind of unperturbed Keplerian orbit connects two positions in a certain time of flight.
This class uses lazy evaluation, solving the algorithm is postponed until the function call relying on the computations.
The algorithm used is based on the algorithm used in Izzo's PyKEP Keplerian toolbox, but is implemented such that only one solution gets computed at a time. The approach from Izzo transforms the problem into dimensionless parameters in terms of the initial position and computes the solution in a 2D plane solving for Battin's x-variable. Contrasting the Izzo approach, the non-dimensionalized parameters are stored internally in order to speed up future recalculations.
Exceptions
std::runtime_error For negative time of flight and gravitational parameter values.
basic_mathematics::ConvergenceException When the internal rootfinding algorithm fails to converge within a reasonable amount of iterations.
Definition at line 56 of file zeroRevolutionLambertTargeterIzzo.h.
Constructor & Destructor Documentation
ZeroRevolutionLambertTargeterIzzo()
EIGEN_MAKE_ALIGNED_OPERATOR_NEW tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::ZeroRevolutionLambertTargeterIzzo (const Eigen::Vector3d & aCartesianPositionAtDeparture, const Eigen::Vector3d & aCartesianPositionAtArrival, const double aTimeOfFlight, const double aGravitationalParameter, const bool aIsRetrograde = false, const double aConvergenceTolerance = 1.0e-9, const int aMaximumNumberOfIterations = 50) inline
Constructs a lambert problem with all relevant parameters for a zero revolution problem (i.e. without a full revolution in the solution). Constructor does not compute a solution in order to save on computations; solving is done on first member function call by user.
Parameters
aCartesianPositionAtDeparture The initial position in xyz-coordinates. [m]
aCartesianPositionAtArrival The final position in xyz-coordinates. [m]
aTimeOfFlight The time-of-flight between the two positions. [s]
aGravitationalParameter The gravitational parameter of the central body for the computed solution orbit. [m^3/s^2]
aIsRetrograde A boolean flag to indicate retrograde motion with (default false). [-]
aConvergenceTolerance The required tolerance for the root solving procedure. [-]
aMaximumNumberOfIterations The required number of iterations the root solving procedure is allowed to go through (default 50). [-]
Definition at line 78 of file zeroRevolutionLambertTargeterIzzo.h.
Member Function Documentation
getRadialVelocityAtDeparture()
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::getRadialVelocityAtDeparture ()
Calculates the radial velocity at departure position in S.I. units.
Returns
radialVelocityAtDeparture Radial velocity at departure. [m/s]
Definition at line 38 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::cartesianPositionAtDeparture, tudat::mission_segments::LambertTargeter::cartesianVelocityAtDeparture, execute(), and tudat::mission_segments::LambertTargeter::solved.
getTransverseVelocityAtDeparture()
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::getTransverseVelocityAtDeparture ()
Calculates and returns transverse velocity at departure position in S.I. units.
Returns
transverseVelocityAtDeparture Transverse velocity at departure. [m/s]
Definition at line 52 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::cartesianPositionAtDeparture, tudat::mission_segments::LambertTargeter::cartesianVelocityAtDeparture, execute(), and tudat::mission_segments::LambertTargeter::solved.
getRadialVelocityAtArrival()
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::getRadialVelocityAtArrival ()
Calculates and returns radial velocity at arrival position in S.I. units.
Returns
radialVelocityAtArrival Radial velocity at arrival. [m/s]
Definition at line 77 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::cartesianPositionAtArrival, tudat::mission_segments::LambertTargeter::cartesianVelocityAtArrival, execute(), and tudat::mission_segments::LambertTargeter::solved.
getTransverseVelocityAtArrival()
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::getTransverseVelocityAtArrival ()
Calculates and returns transverse velocity at arrival position in S.I. units.
Returns
transverseVelocityAtDeparture Transverse velocity at departure. [m/s]
Definition at line 91 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::cartesianPositionAtArrival, tudat::mission_segments::LambertTargeter::cartesianVelocityAtArrival, execute(), and tudat::mission_segments::LambertTargeter::solved.
getSemiMajorAxis()
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::getSemiMajorAxis ()
Calculates and returns semi-major axis in S.I. units.
Returns
semiMajorAxis Semi-major axis of the problem's solution. [m/s]
Definition at line 116 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::cartesianPositionAtDeparture, tudat::mission_segments::LambertTargeter::cartesianVelocityAtDeparture, execute(), tudat::mission_segments::LambertTargeter::gravitationalParameter, and tudat::mission_segments::LambertTargeter::solved.
execute()
void tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::execute () protected virtual
Solves the problem using dimensionless parameters by finding the root for the x-paramater and recovering the dimensions of the corresponding orbit parameters.
Implements tudat::mission_segments::LambertTargeter.
Reimplemented in tudat::mission_segments::MultiRevolutionLambertTargeterIzzo.
Definition at line 133 of file zeroRevolutionLambertTargeterIzzo.cpp.
References computeRootTimeOfFlight(), computeVelocities(), sanityCheckGravitationalParameter(), sanityCheckTimeOfFlight(), tudat::mission_segments::LambertTargeter::solved, transformDimensions(), and transformed.
Referenced by tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::execute(), getRadialVelocityAtArrival(), getRadialVelocityAtDeparture(), getSemiMajorAxis(), getTransverseVelocityAtArrival(), and getTransverseVelocityAtDeparture().
sanityCheckTimeOfFlight()
void tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::sanityCheckTimeOfFlight () protected
Checks whether time of flight is positive: if negative, throws an error.
Definition at line 153 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::timeOfFlight.
Referenced by execute(), and tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::execute().
sanityCheckGravitationalParameter()
void tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::sanityCheckGravitationalParameter () protected
Checks whether gravitational parameter is positive: if negative, throws an error.
Definition at line 167 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::gravitationalParameter.
Referenced by execute(), and tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::execute().
transformDimensions()
void tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::transformDimensions () protected
Transforms the input to the adimensional units required for the Izzo theory. It also stores relevant (no longer changing) sub results for recovering velocities.
Definition at line 181 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::cartesianPositionAtArrival, tudat::mission_segments::LambertTargeter::cartesianPositionAtDeparture, tudat::mission_segments::LambertTargeter::gravitationalParameter, isLongway, isRetrograde, lambdaParameter, normalizedChord, normalizedMinimumEnergySemiMajorAxis, normalizedRadiusAtArrival, normalizedSemiPerimeter, normalizedTimeOfFlight, tudat::mathematical_constants::PI, tudat::mission_segments::LambertTargeter::timeOfFlight, transferAngle, transformed, and velocityNormalizingValue.
Referenced by execute(), tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::execute(), and tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::getMaximumNumberOfRevolutions().
computeTimeOfFlight()
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::computeTimeOfFlight (const double xParameter) protected virtual
Computes the time-of-flight according to Lagrange's equation as a function of the x-parameter as used by Battin, using the problem's sub results.
Parameters
xParameter x-parameter in Izzo's theory.
Returns
timeOfFlight Computed dimensionless time-of-flight.
Reimplemented in tudat::mission_segments::MultiRevolutionLambertTargeterIzzo.
Definition at line 244 of file zeroRevolutionLambertTargeterIzzo.cpp.
References isLongway, normalizedChord, normalizedMinimumEnergySemiMajorAxis, normalizedSemiPerimeter, tudat::input_output::field_types::state::semiMajorAxis, and tudat::mission_segments::LambertTargeter::timeOfFlight.
Referenced by computeRootTimeOfFlight().
computeRootTimeOfFlight()
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::computeRootTimeOfFlight () protected virtual
Initializes and finds the root of the equation , where is a function to compute the time-of-flight as a function of , for a zero revolution solution.
Returns
xParameter Computed x parameter.
Reimplemented in tudat::mission_segments::MultiRevolutionLambertTargeterIzzo.
Definition at line 314 of file zeroRevolutionLambertTargeterIzzo.cpp.
References computeTimeOfFlight(), convergenceTolerance, maximumNumberOfIterations, and normalizedTimeOfFlight.
Referenced by execute().
computeVelocities()
void tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::computeVelocities (const double xParameter) protected
Computes the inertial departure and arrival velocities according to Izzo's theory and reassigns the dimensions of the input to the velocities.
Parameters
xParameter x-parameter in Izzo's theory.
Definition at line 370 of file zeroRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::LambertTargeter::cartesianPositionAtArrival, tudat::mission_segments::LambertTargeter::cartesianPositionAtDeparture, tudat::mission_segments::LambertTargeter::cartesianVelocityAtArrival, tudat::mission_segments::LambertTargeter::cartesianVelocityAtDeparture, isLongway, lambdaParameter, normalizedChord, normalizedMinimumEnergySemiMajorAxis, normalizedRadiusAtArrival, normalizedSemiPerimeter, tudat::input_output::field_types::state::semiMajorAxis, transferAngle, and velocityNormalizingValue.
Referenced by execute(), and tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::execute().
Member Data Documentation
isRetrograde
const bool tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::isRetrograde protected
Boolean indicator for retrograde motion.
Definition at line 190 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by transformDimensions().
convergenceTolerance
const double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::convergenceTolerance protected
Convergence tolerance for the root-finding process.
Definition at line 196 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeRootTimeOfFlight(), and computeRootTimeOfFlight().
maximumNumberOfIterations
const double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::maximumNumberOfIterations protected
Maximum number of iterations allowed for the root-finding process.
Definition at line 202 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeRootTimeOfFlight(), and computeRootTimeOfFlight().
transformed
bool tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::transformed protected
Boolean flag to indicate whether transformation of input dimensions has already been performed or not.
Definition at line 209 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by execute(), and transformDimensions().
velocityNormalizingValue
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::velocityNormalizingValue protected
Calculated parameter to make velocities dimensionless.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 218 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by computeVelocities(), and transformDimensions().
normalizedTimeOfFlight
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedTimeOfFlight protected
Calculated parameter expressing time-of-flight in dimensionless units.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 227 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeRootTimeOfFlight(), computeRootTimeOfFlight(), tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::sanityCheckNumberOfRevolutions(), and transformDimensions().
normalizedRadiusAtArrival
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedRadiusAtArrival protected
Calculated parameter expressing radius at arrival in dimensionless units.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 236 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by computeVelocities(), and transformDimensions().
normalizedChord
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedChord protected
Calculated parameter expressing chord (norm of difference between both position vectors) in dimensionless units.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 246 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeTimeOfFlight(), computeTimeOfFlight(), computeVelocities(), and transformDimensions().
normalizedSemiPerimeter
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedSemiPerimeter protected
Calculated parameter expressing semi-perimeter of the triangle departure position, arrival position and orbit focus in dimensionless units.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 256 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeTimeOfFlight(), computeTimeOfFlight(), computeVelocities(), tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::sanityCheckNumberOfRevolutions(), and transformDimensions().
isLongway
bool tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::isLongway protected
Calculated boolean flag to indicate long or short transfer angle between positions.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 265 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeTimeOfFlight(), computeTimeOfFlight(), computeVelocities(), and transformDimensions().
normalizedMinimumEnergySemiMajorAxis
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedMinimumEnergySemiMajorAxis protected
Calculated parameter expressing the problem's minimum energy ellipse semi-major axis in dimensionless units.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 275 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeTimeOfFlight(), computeTimeOfFlight(), computeVelocities(), and transformDimensions().
transferAngle
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::transferAngle protected
Calculated angle between arrival and departure position.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 284 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by computeVelocities(), and transformDimensions().
lambdaParameter
double tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::lambdaParameter protected
Calculated parameter necessary for recovering velocities.
NB: This is calculated as a function of specified problem geometry, and therefore not declared const.
Definition at line 293 of file zeroRevolutionLambertTargeterIzzo.h.
Referenced by computeVelocities(), and transformDimensions().
The documentation for this class was generated from the following files:
Astrodynamics/MissionSegments/zeroRevolutionLambertTargeterIzzo.h
Astrodynamics/MissionSegments/zeroRevolutionLambertTargeterIzzo.cpp