Tudat: tudat::acceleration_partials Namespace Reference
tudat::acceleration_partials Namespace Reference
Classes
class AccelerationPartial
Base class for objects calculating partial derivatives of accelerations w.r.t. states, model parameters.
class AerodynamicAccelerationPartial
Class to calculate the partials of the aerodynamic acceleration w.r.t. parameters and states.
class CannonBallRadiationPressurePartial
Class to calculate the partials of the cannnonball radiation pressure acceleration w.r.t. parameters and states.
class CentralGravitationPartial
Class to calculate the partials of the central gravitational acceleration w.r.t. parameters and states.
class DirectTidalDissipationAccelerationPartial
Class to calculate the partials of the direct tidal acceleration model (e.g. Lainey et al. 2007) w.r.t. parameters and states.
class EmpiricalAccelerationPartial
class MutualSphericalHarmonicsGravityPartial
Class for calculating partial derivatives of a mutual spherical harmonic gravitational acceleration.
class RelativisticAccelerationPartial
Class to calculate the partials of the relativistic acceleration correction w.r.t. parameters and states.
class SphericalHarmonicsGravityPartial
Class for calculating partial derivatives of a spherical harmonic gravitational acceleration.
class ThirdBodyGravityPartial
Class to calculate the partials of a third-body gravitational acceleration w.r.t. parameters and states.
Functions
Eigen::Vector3d calculateAccelerationWrtParameterPartials (boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, double parameterPerturbation, boost::function< void() > updateDependentVariables, const double currentTime, boost::function< void(const double) > timeDependentUpdateDependentVariables)
Function to numerical compute the partial derivative of an acceleration w.r.t. a double parameter.
Eigen::Matrix< double, 3, Eigen::Dynamic > calculateAccelerationWrtParameterPartials (boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, Eigen::VectorXd parameterPerturbation, boost::function< void() > updateDependentVariables, const double currentTime, boost::function< void(const double) > timeDependentUpdateDependentVariables)
Function to numerical compute the partial derivative of an acceleration w.r.t. a vector parameter.
Eigen::Matrix3d calculateAccelerationWrtStatePartials (boost::function< void(Eigen::Vector6d) > setBodyState, boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, Eigen::Vector6d originalState, Eigen::Vector3d statePerturbation, int startIndex, boost::function< void() > updateFunction, const double evaluationTime)
Function to numerical compute the partial derivative of an acceleration w.r.t. a body state.
Eigen::Matrix< double, 1, 6 > calculateNumericalPartialOfTrueAnomalyWrtState (const Eigen::Vector6d &cartesianElements, const double gravitationalParameter, const Eigen::Vector6d &cartesianStateElementPerturbations)
Function determine the numerical partial derivative of the true anomaly wrt the elements of the Cartesian state.
Eigen::Matrix3d calculatePartialOfPointMassGravityWrtPositionOfAcceleratedBody (const Eigen::Vector3d &acceleratedBodyPosition, const Eigen::Vector3d &acceleratingBodyPositions, double gravitationalParameter)
Calculates partial derivative of point mass gravitational acceleration wrt the position of body undergoing acceleration.
void calculateSphericalHarmonicGravityWrtCCoefficients (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double gravitionalParameter, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const std::vector< std::pair< int, int > > &blockIndices, const Eigen::Matrix3d &sphericalToCartesianGradientMatrix, const Eigen::Matrix3d &bodyFixedToIntegrationFrame, Eigen::MatrixXd &partialsMatrix)
Calculate partial of spherical harmonic acceleration w.r.t. a set of cosine coefficients.
void calculateSphericalHarmonicGravityWrtSCoefficients (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double gravitionalParameter, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const std::vector< std::pair< int, int > > &blockIndices, const Eigen::Matrix3d &sphericalToCartesianGradientMatrix, const Eigen::Matrix3d &bodyFixedToIntegrationFrame, Eigen::MatrixXd &partialsMatrix)
Calculate partial of spherical harmonic acceleration w.r.t. a set of sine coefficients.
Eigen::Matrix3d computeCumulativeSphericalHessian (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Function to compute the spherical Hessian of a full spherical harmonic potential.
Eigen::Matrix3d computeDirectTidalAccelerationDueToTideOnPlanetWrtPosition (const Eigen::Vector6d relativeStateOfBodyExertingTide, const Eigen::Vector3d planetAngularVelocityVector, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. position of satellite.
Eigen::Matrix3d computeDirectTidalAccelerationDueToTideOnPlanetWrtVelocity (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag)
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. velocity of satellite/.
Eigen::Matrix3d computeDirectTidalAccelerationDueToTideOnSatelliteWrtPosition (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute partial derivative of direct tidal acceleration due to tide on satellite w.r.t. position of satellite.
Eigen::Matrix3d computeDirectTidalAccelerationDueToTideOnSatelliteWrtVelocity (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag)
Function to compute partial derivative of direct tidal acceleration due to tide on satellite w.r.t. velocity of satellite.
Eigen::Matrix3d computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration (const Eigen::Vector3d &cartesianPosition, const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const Eigen::Vector3d &sphericalPotentialGradient, const Eigen::Matrix3d &sphericalToCartesianGradientMatrix)
Calculate partial of spherical harmonic acceleration w.r.t.
Eigen::Matrix3d computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration (const Eigen::Vector3d &cartesianPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Calculate partial of spherical harmonic acceleration w.r.t.
Eigen::Vector3d computePartialOfCannonBallRadiationPressureAccelerationWrtRadiationPressureCoefficient (const double radiationPressure, const double area, const double bodyMass, const Eigen::Vector3d &vectorToSource)
Calculates partial derivative of cannon ball radiation pressure acceleration wrt radiation pressure coefficient.
Eigen::Vector3d computePartialOfCentralGravityWrtGravitationalParameter (const Eigen::Vector3d &acceleratedBodyPosition, const Eigen::Vector3d &acceleratingBodyPosition)
Calculates partial derivative of point mass gravitational acceleration wrt gravitational parameter of the central body.
Eigen::Vector3d computePartialOfCentralGravityWrtGravitationalParameter (const Eigen::Vector3d &gravitationalAcceleration, const double gravitationalParameter)
Calculates partial derivative of point mass gravitational acceleration wrt gravitational parameter of the central body.
void computePartialOfSchwarzschildAccelerationCorrectionWrtGravitationalParameter (const Eigen::Vector6d &relativeState, const double gravitationalParameter, Eigen::MatrixXd &partialMatrix, const double ppnParameterGamma, const double ppnParameterBeta)
Function to compute partial derivative of Schwarzschild acceleration correction w.r.t. central body gravitational patameter.
void computePartialOfSchwarzschildAccelerationCorrectionWrtPosition (const Eigen::Vector6d &relativeState, Eigen::Vector3d &currentAcceleration, Eigen::Matrix3d &partialMatrix, const double gravitationalParameter, const double ppnParameterGamma, const double ppnParameterBeta)
Function to compute partial of Schwarzschild acceleration correction w.r.t. position of body undergoing acceleration.
void computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterBeta (const Eigen::Vector6d &relativeState, const double gravitationalParameter, Eigen::MatrixXd &partialMatrix)
Function to compute the partial derivative of Schwarzschild acceleration correction w.r.t. PPN parameter beta.
void computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterGamma (const Eigen::Vector6d &relativeState, const double gravitationalParameter, Eigen::MatrixXd &partialMatrix)
Function to compute the partial derivative of Schwarzschild acceleration correction w.r.t. PPN parameter gamma.
void computePartialOfSchwarzschildAccelerationCorrectionWrtVelocity (const Eigen::Vector6d &relativeState, Eigen::Matrix3d &partialMatrix, const double gravitationalParameter, const double ppnParameterGamma)
Function to compute partial of Schwarzschild acceleration correction w.r.t. velocity of body undergoing acceleration.
void computePotentialSphericalHessian (const double distance, const double radiusPowerTerm, const double cosineOfOrderLongitude, const double sineOfOrderLongitude, const double cosineOfLatitude, const double sineOfLatitude, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const double legendrePolynomialSecondDerivative, Eigen::Matrix3d &sphericalHessian)
Function to compute the spherical Hessian of a single term of a spherical harmonic potential.
void computePotentialSphericalHessian (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const double legendrePolynomialSecondDerivative, Eigen::Matrix3d &sphericalHessian)
Function to compute the spherical Hessian of a single term of a spherical harmonic potential.
void computePotentialSphericalHessian (const Eigen::Vector3d &sphericalPosition, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, Eigen::Matrix3d &sphericalHessian)
Function to compute the spherical Hessian of a single term of a spherical harmonic potential.
void emptyFunction ()
Dummy function used for update, performs no calculations.
void emptyTimeFunction (const double time)
Dummy function used for update, performs no calculations.
template<typename DirectGravityPartial >
basic_astrodynamics::AvailableAcceleration getAccelerationTypeOfThirdBodyGravity (const boost::shared_ptr< DirectGravityPartial > directGravityPartial)
Function to get the third body acceleration type from the direct acceleration partial object.
Function Documentation
Eigen::Matrix3d tudat::acceleration_partials::calculatePartialOfPointMassGravityWrtPositionOfAcceleratedBody (const Eigen::Vector3d & acceleratedBodyPosition, const Eigen::Vector3d & acceleratingBodyPosition, const double gravitationalParameter)
Calculates partial derivative of point mass gravitational acceleration wrt the position of body undergoing acceleration.
Parameters
acceleratedBodyPosition Cartesian state of body being accelerated.
acceleratingBodyPosition Cartesian state of body exerting acceleration.
gravitationalParameter Gravitational parameter of gravitating body.
Returns
Matrix with the Jacobian of the acceleration vector w.r.t. the position vector.
Definition at line 21 of file centralGravityAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::CentralGravitationPartial::update().
Eigen::Vector3d tudat::acceleration_partials::computePartialOfCentralGravityWrtGravitationalParameter (const Eigen::Vector3d & acceleratedBodyPosition, const Eigen::Vector3d & acceleratingBodyPosition)
Calculates partial derivative of point mass gravitational acceleration wrt gravitational parameter of the central body.
Parameters
acceleratedBodyPosition Cartesian state of body being accelerated.
acceleratingBodyPosition Cartesian state of body exerting acceleration.
Returns
Vector with the partial of the acceleration vector w.r.t. ational parameter of the central body.
Definition at line 41 of file centralGravityAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::CentralGravitationPartial::wrtGravitationalParameterOfCentralBody().
Eigen::Vector3d tudat::acceleration_partials::computePartialOfCentralGravityWrtGravitationalParameter (const Eigen::Vector3d & gravitationalAcceleration, const double gravitationalParameter)
Calculates partial derivative of point mass gravitational acceleration wrt gravitational parameter of the central body.
Parameters
gravitationalAcceleration Gravitational acceleration vector for which partial is to be computed.
gravitationalParameter Gravitational parameter of gravitating body.
Returns
Vector with the partial of the acceleration vector w.r.t. ational parameter of the central body.
Definition at line 54 of file centralGravityAccelerationPartial.cpp.
Eigen::Matrix3d tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnPlanetWrtPosition (const Eigen::Vector6d relativeStateOfBodyExertingTide, const Eigen::Vector3d planetAngularVelocityVector, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. position of satellite (equal to -1 * partial w.r.t. position of planet)
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
planetAngularVelocityVector Angular velocity vector ogf host planet
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
includeDirectRadialComponent True if term independent of time lag is to be included, false otherwise
Returns
Partial derivative of direct tidal acceleration due to tide on planet w.r.t. position of satellite
Definition at line 22 of file directTidalDissipationAccelerationPartial.cpp.
References tudat::linear_algebra::getCrossProductMatrix().
Referenced by tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update().
Eigen::Matrix3d tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnPlanetWrtVelocity (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag)
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. velocity of satellite.
Function to compute partial derivative of direct tidal acceleration due to tide on planet w.r.t. velocity of satellite (equal to -1 * partial w.r.t. velocity of planet)
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
Returns
Partial derivative of direct tidal acceleration due to tide on planet w.r.t. velocity of satellite
Definition at line 49 of file directTidalDissipationAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update().
Eigen::Matrix3d tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnSatelliteWrtPosition (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag, const bool includeDirectRadialComponent)
Function to compute partial derivative of direct tidal acceleration due to tide on satellite w.r.t. position of satellite (equal to -1 * partial w.r.t. position of planet)
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
includeDirectRadialComponent True if term independent of time lag is to be included, false otherwise
Returns
Partial derivative of direct tidal acceleration due to tide on satellite w.r.t. position of satellite
Definition at line 62 of file directTidalDissipationAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update().
Eigen::Matrix3d tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnSatelliteWrtVelocity (const Eigen::Vector6d relativeStateOfBodyExertingTide, const double currentTidalAccelerationMultiplier, const double timeLag)
Function to compute partial derivative of direct tidal acceleration due to tide on satellite w.r.t. velocity of satellite (equal to -1 * partial w.r.t. velocity of planet)
Parameters
relativeStateOfBodyExertingTide State of satellite w.r.t. host planet.
currentTidalAccelerationMultiplier Scalar multiplier that is common to all vector terms (term outside of brackets in Eq. (3) of Lainey et al. (2007)).
timeLag Time lag of tidal bulge
Returns
Partial derivative of direct tidal acceleration due to tide on satellite w.r.t. velocity of satellite
Definition at line 85 of file directTidalDissipationAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update().
Eigen::Matrix< double, 1, 6 > tudat::acceleration_partials::calculateNumericalPartialOfTrueAnomalyWrtState (const Eigen::Vector6d & cartesianElements, const double gravitationalParameter, const Eigen::Vector6d & cartesianStateElementPerturbations)
unction determine the numerical partial derivative of the true anomaly wrt the elements of the Cartesian state, from the Cartesian state as input. A first-order central difference with a user-defined Cartesian state perturbation vector is used.
Parameters
cartesianElements Nominal Cartesian elements at which the partials are to be computed
gravitationalParameter Gravitational parameter of central body around which Keplerian orbit is given
cartesianStateElementPerturbations Numerical perturbations of Cartesian state that are to be used
Returns
Partial of Cartesian state wrt true anomaly of orbit.
Definition at line 23 of file empiricalAccelerationPartial.cpp.
References tudat::json_interface::cartesianElements, tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), and tudat::orbital_element_conversions::trueAnomalyIndex.
Referenced by tudat::acceleration_partials::EmpiricalAccelerationPartial::update().
void tudat::acceleration_partials::emptyFunction ()
Dummy function used for update, performs no calculations.
Definition at line 20 of file numericalAccelerationPartial.cpp.
void tudat::acceleration_partials::emptyTimeFunction (const double time)
Dummy function used for update, performs no calculations.
Parameters
time Input parameter, not used by function.
Definition at line 23 of file numericalAccelerationPartial.cpp.
Eigen::Matrix3d tudat::acceleration_partials::calculateAccelerationWrtStatePartials (boost::function< void(Eigen::Vector6d) > setBodyState, boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, Eigen::Vector6d originalState, Eigen::Vector3d statePerturbation, int startIndex, boost::function< void() > updateFunction = emptyFunction, const double evaluationTime = TUDAT_NAN)
Function to numerical compute the partial derivative of an acceleration w.r.t. a body state (position or velocity), using a first-order central difference method.
Parameters
setBodyState Function to reset the current state w.r.t. which the partial is to be computed.
accelerationModel Acceleration model for which the partial derivative is to be computed.
originalState Nominal state at which the partial derivative is to be computed.
statePerturbation Perturbation to the position or velocity that is to be used
startIndex Start index in the state vector from where the statePerturbation is to be added (i.e. 0 if function is to compute partial w.r.t. position, 3 if w.r.t velocity).
updateFunction Function to update the required environment models following the change of the body state.
evaluationTime Time at which partial is to be evaluated (default NaN).
Returns
Numerical partial of the acceleration w.r.t. position or velocity (depending on function input).
Definition at line 26 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN.
Eigen::Vector3d tudat::acceleration_partials::calculateAccelerationWrtParameterPartials (boost::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, double parameterPerturbation, boost::function< void() > updateDependentVariables = emptyFunction, const double currentTime = 0.0, boost::function< void(const double) > timeDependentUpdateDependentVariables = emptyTimeFunction)
Function to numerical compute the partial derivative of an acceleration w.r.t. a double parameter, using a first-order central difference method.
Parameters
parameter Object describing the parameter w.r.t. which teh partial is to be taken.
accelerationModel Acceleration model for which the partial derivative is to be computed.
parameterPerturbation Perturbation to be used for parameter value.
updateDependentVariables Function to update the required environment models following the change in parameter, for models that do not explicitly depend on the current time.
currentTime Time at which partial is to be computed.
timeDependentUpdateDependentVariables Function to update the required environment models following the change in parameters for models that do explicitly depend on the current time.
Returns
Numerical partial of the acceleration w.r.t. given parameter.
Definition at line 85 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN.
Eigen::Matrix< double, 3, Eigen::Dynamic > tudat::acceleration_partials::calculateAccelerationWrtParameterPartials (boost::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, boost::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > accelerationModel, Eigen::VectorXd parameterPerturbation, boost::function< void() > updateDependentVariables = emptyFunction, const double currentTime = 0.0, boost::function< void(const double) > timeDependentUpdateDependentVariables = emptyTimeFunction)
Function to numerical compute the partial derivative of an acceleration w.r.t. a vector parameter, using a first-order central difference method.
Parameters
parameter Object describing the parameter w.r.t. which teh partial is to be taken.
accelerationModel Acceleration model for which the partial derivative is to be computed.
parameterPerturbation Perturbations to be used for parameter value.
updateDependentVariables Function to update the required environment models following the change in parameter, for models that do not explicitly depend on the current time.
currentTime Time at which partial is to be computed.
timeDependentUpdateDependentVariables Function to update the required environment models following the change in parameters for models that do explicitly depend on the current time.
Returns
Numerical partial of the acceleration w.r.t. given parameter.
Definition at line 133 of file numericalAccelerationPartial.cpp.
References TUDAT_NAN.
Eigen::Vector3d tudat::acceleration_partials::computePartialOfCannonBallRadiationPressureAccelerationWrtRadiationPressureCoefficient (const double radiationPressure, const double area, const double bodyMass, const Eigen::Vector3d & vectorToSource)
Calculates partial derivative of cannon ball radiation pressure acceleration wrt radiation pressure coefficient.
Parameters
radiationPressure Current radiation pressure (in N/m^2)
area (Reference) area for radiation pressure acceleration.
bodyMass Mass of body undergoing acceleration.
vectorToSource Vector from body undergoing acceleration to source of radiation.
Returns
Partial derivative of cannon ball radiation pressure acceleration wrt radiation pressure coefficient.
Definition at line 21 of file radiationPressureAccelerationPartial.cpp.
Referenced by tudat::acceleration_partials::CannonBallRadiationPressurePartial::wrtRadiationPressureCoefficient().
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPosition (const Eigen::Vector6d & relativeState, Eigen::Vector3d & currentAcceleration, Eigen::Matrix3d & partialMatrix, const double gravitationalParameter, const double ppnParameterGamma = 1.0, const double ppnParameterBeta = 1.0)
Function to compute partial of Schwarzschild acceleration correction w.r.t. position of body undergoing acceleration
Parameters
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
currentAcceleration Current Schwarzschild acceleration correction
partialMatrix Requested (returnd by reference)
gravitationalParameter Gravitational parameter of body exerting acceleration.
ppnParameterGamma PPN parameter gamma
ppnParameterBeta PPN parameter beta
Definition at line 20 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::update().
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtVelocity (const Eigen::Vector6d & relativeState, Eigen::Matrix3d & partialMatrix, const double gravitationalParameter, const double ppnParameterGamma = 1.0)
Function to compute partial of Schwarzschild acceleration correction w.r.t. velocity of body undergoing acceleration
Parameters
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
relativeState Current Schwarzschild acceleration correction
partialMatrix Requested (returnd by reference)
gravitationalParameter Gravitational parameter of body exerting acceleration.
ppnParameterGamma PPN parameter gamma
Definition at line 37 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::update().
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtGravitationalParameter (const Eigen::Vector6d & relativeState, const double gravitationalParameter, Eigen::MatrixXd & partialMatrix, const double ppnParameterGamma = 1.0, const double ppnParameterBeta = 1.0)
Function to compute partial derivative of Schwarzschild acceleration correction w.r.t. central body gravitational patameter.
Parameters
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
gravitationalParameter Gravitational parameter of body exerting acceleration.
partialMatrix Requested (returnd by reference)
ppnParameterGamma PPN parameter gamma
ppnParameterBeta PPN parameter bet
Definition at line 53 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::wrtGravitationalParameterOfCentralBody().
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterGamma (const Eigen::Vector6d & relativeState, const double gravitationalParameter, Eigen::MatrixXd & partialMatrix)
Function to compute the partial derivative of Schwarzschild acceleration correction w.r.t. PPN parameter gamma
Parameters
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
gravitationalParameter Gravitational parameter of body exerting acceleration.
partialMatrix Requested (returnd by reference)
Definition at line 71 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::wrtPpnParameterGamma().
void tudat::acceleration_partials::computePartialOfSchwarzschildAccelerationCorrectionWrtPpnParameterBeta (const Eigen::Vector6d & relativeState, const double gravitationalParameter, Eigen::MatrixXd & partialMatrix)
Function to compute the partial derivative of Schwarzschild acceleration correction w.r.t. PPN parameter beta
Parameters
relativeState Position of body undergoing, w.r.t. body exerting, acceleration.
gravitationalParameter Gravitational parameter of body exerting acceleration.
partialMatrix Requested (returnd by reference)
Definition at line 85 of file relativisticAccelerationPartial.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by tudat::acceleration_partials::RelativisticAccelerationPartial::wrtPpnParameterBeta().
void tudat::acceleration_partials::computePotentialSphericalHessian (const double distance, const double radiusPowerTerm, const double cosineOfOrderLongitude, const double sineOfOrderLongitude, const double cosineOfLatitude, const double sineOfLatitude, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const double legendrePolynomialSecondDerivative, Eigen::Matrix3d & sphericalHessian)
Function to compute the spherical Hessian (i.e. matrix of second derivatives w.r.t. spherical components radius, latitude and longitude) of a single term of a spherical harmonic potential.
Parameters
distance Distance to center of body with gravity field at which the partials are to be calculated
radiusPowerTerm Distance divided by the reference radius of the gravity field, to the power (degree + 1)
cosineOfOrderLongitude Cosine of order times the longitude at which the potential is to be calculated
sineOfOrderLongitude Sine of order times the longitude at which the potential is to be calculated
cosineOfLatitude Cosine of the latitude at which the potential is to be calculated
sineOfLatitude Sine of the latitude at which the potential is to be calculated
preMultiplier Pre-multiplier of potential (gravitational parametere divided by reference radius in normal representation)
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
legendrePolynomial Value of associated Legendre polynomial with the same degree and order as the to be computed harmonic, and with the sine of the latitude coordinate as polynomial parameter.
legendrePolynomialDerivative Value of the derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
legendrePolynomialSecondDerivative Value of second derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
sphericalHessian Hessian of potential term in spherical coordinates (returned by reference).
Definition at line 29 of file sphericalHarmonicPartialFunctions.cpp.
Referenced by computeCumulativeSphericalHessian(), and computePotentialSphericalHessian().
void tudat::acceleration_partials::computePotentialSphericalHessian (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const double legendrePolynomialSecondDerivative, Eigen::Matrix3d & sphericalHessian)
Function to compute the spherical Hessian (i.e. matrix of second derivatives w.r.t. spherical components radius, latitude and longitude) of a single term of a spherical harmonic potential.
Parameters
sphericalPosition Spherical position (radius, ,latitude, longitude) at which potential partials are to be evaluated
referenceRadius Reference radius of spherical harmonic potential.
preMultiplier Pre-multiplier of potential (gravitational parametere divided by reference radius in normal representation)
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
legendrePolynomial Value of associated Legendre polynomial with the same degree and order as the to be computed harmonic, and with the sine of the latitude coordinate as polynomial parameter.
legendrePolynomialDerivative Value of the derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
legendrePolynomialSecondDerivative Value of second derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
sphericalHessian Hessian of potential term in spherical coordinates (returned by reference).
Definition at line 75 of file sphericalHarmonicPartialFunctions.cpp.
References computePotentialSphericalHessian(), tudat::orbital_element_conversions::latitudeIndex, tudat::orbital_element_conversions::longitudeIndex, tudat::orbital_element_conversions::radiusIndex, and tudat::basic_mathematics::raiseToIntegerPower().
void tudat::acceleration_partials::computePotentialSphericalHessian (const Eigen::Vector3d & sphericalPosition, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, Eigen::Matrix3d & sphericalHessian)
Function to compute the spherical Hessian (i.e. matrix of second derivatives w.r.t. spherical components radius, latitude and longitude) of a single term of a spherical harmonic potential.
Parameters
sphericalPosition Spherical position (radius, ,latitude, longitude) at which potential partials are to be evaluated
preMultiplier Pre-multiplier of potential (gravitational parametere divided by reference radius in normal representation)
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
sphericalHessian Hessian of potential term in spherical coordinates (returned by reference).
Definition at line 100 of file sphericalHarmonicPartialFunctions.cpp.
References computePotentialSphericalHessian().
Eigen::Matrix3d tudat::acceleration_partials::computeCumulativeSphericalHessian (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Function to compute the spherical Hessian (i.e. matrix of second derivatives w.r.t. spherical components radius, latitude and longitude) of a full spherical harmonic potential.
Parameters
sphericalPosition Spherical position (radius, ,latitude, longitude) at which potential partials are to be evaluated
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
cosineHarmonicCoefficients Matrix of coefficient which characterize the relative strengh of cosine harmonic terms.
sineHarmonicCoefficients Matrix of coefficient which characterize the relative strengh of sine harmonic terms.
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
Returns
Hessian of potential in spherical coordinates (returned by reference).
Definition at line 125 of file sphericalHarmonicPartialFunctions.cpp.
References computePotentialSphericalHessian().
Referenced by computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration().
Eigen::Matrix3d tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration (const Eigen::Vector3d & cartesianPosition, const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const Eigen::Vector3d & sphericalPotentialGradient, const Eigen::Matrix3d & sphericalToCartesianGradientMatrix)
Calculate partial of spherical harmonic acceleration w.r.t. position of body undergoing acceleration (in the body-fixed frame)
Calculate partial of spherical harmonic acceleration w.r.t. position of body undergoing acceleration (in the body-fixed frame)
position of body undergoing acceleration (in the body-fixed frame)
Parameters
cartesianPosition Cartesian position at which potential partials are to be evaluated
sphericalPosition Spherical position (radius, ,latitude, longitude) at which potential partials are to be evaluated
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
cosineHarmonicCoefficients Cosine spherical harmonic coefficients.
sineHarmonicCoefficients Sine spherical harmonic coefficients
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
sphericalPotentialGradient Potential gradient in spherical coordinates
sphericalToCartesianGradientMatrix Matrix to convert (by premultiplication) a spherical gradient to a Cartesian gradient
Returns
Partial of spherical harmonic acceleration w.r.t. position of body undergoinng acceleration (equals minus partial of spherical harmonic acceleration w.r.t. position of body exerting acceleration) with both acceleration and position in body-fixed frame.
Definition at line 154 of file sphericalHarmonicPartialFunctions.cpp.
References computeCumulativeSphericalHessian(), and tudat::coordinate_conversions::getDerivativeOfSphericalToCartesianGradient().
Referenced by computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::update().
Eigen::Matrix3d tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration (const Eigen::Vector3d & cartesianPosition, const double referenceRadius, const double gravitionalParameter, const Eigen::MatrixXd cosineHarmonicCoefficients, const Eigen::MatrixXd sineHarmonicCoefficients, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache)
Calculate partial of spherical harmonic acceleration w.r.t. position of body undergoing acceleration (in the body-fixed frame)
Calculate partial of spherical harmonic acceleration w.r.t. position of body undergoing acceleration (in the body-fixed frame)
position of body undergoing acceleration (in the body-fixed frame)
Parameters
cartesianPosition Cartesian position at which potential partials are to be evaluated
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
cosineHarmonicCoefficients Cosine spherical harmonic coefficients.
sineHarmonicCoefficients Sine spherical harmonic coefficients
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
Returns
Partial of spherical harmonic acceleration w.r.t. position of body undergoinng acceleration (equals minus partial of spherical harmonic acceleration w.r.t. position of body exerting acceleration) with both acceleration and position in body-fixed frame.
Definition at line 183 of file sphericalHarmonicPartialFunctions.cpp.
References tudat::gravitation::computeGeodesyNormalizedGravitationalAccelerationSum(), computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), tudat::coordinate_conversions::convertCartesianToSpherical(), tudat::coordinate_conversions::getSphericalToCartesianGradientMatrix(), and tudat::mathematical_constants::PI.
void tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtCCoefficients (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double gravitionalParameter, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const std::vector< std::pair< int, int > > & blockIndices, const Eigen::Matrix3d & sphericalToCartesianGradientMatrix, const Eigen::Matrix3d & bodyFixedToIntegrationFrame, Eigen::MatrixXd & partialsMatrix)
Calculate partial of spherical harmonic acceleration w.r.t. a set of cosine coefficients
Parameters
sphericalPosition Spherical coordinate of body undergoing acceleration in frame fixed to body exerting acceleration, as radius, latitude, longitude.
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
blockIndices List of cosine coefficient indices wrt which the partials are to be taken (first and second are degree and order for each vector entry).
sphericalToCartesianGradientMatrix Matrix to convert (by premultiplication) a spherical gradient to a Cartesian gradient
bodyFixedToIntegrationFrame Matrix to rotate from body-fixed to integration frame.
partialsMatrix Partials of spherical harmonic acceleration w.r.t. to requested set of cosine coefficients (returned by reference).
Definition at line 213 of file sphericalHarmonicPartialFunctions.cpp.
References tudat::basic_mathematics::computePotentialGradient(), and tudat::orbital_element_conversions::radiusIndex.
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtCosineCoefficientBlock(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtTidalModelParameter().
void tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtSCoefficients (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double gravitionalParameter, const boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache, const std::vector< std::pair< int, int > > & blockIndices, const Eigen::Matrix3d & sphericalToCartesianGradientMatrix, const Eigen::Matrix3d & bodyFixedToIntegrationFrame, Eigen::MatrixXd & partialsMatrix)
Calculate partial of spherical harmonic acceleration w.r.t. a set of sine coefficients
Parameters
sphericalPosition Spherical coordinate of body undergoing acceleration in frame fixed to body exerting acceleration, as radius, latitude, longitude.
referenceRadius Reference radius of spherical harmonic potential.
gravitionalParameter Gravitational parameter used for spherical harmonic expansion
sphericalHarmonicsCache Cache object containing precomputed spherical harmonics terms.
blockIndices List of cosine coefficient indices wrt which the partials are to be taken (first and second are degree and order for each vector entry).
sphericalToCartesianGradientMatrix Matrix to convert (by premultiplication) a spherical gradient to a Cartesian gradient
bodyFixedToIntegrationFrame Matrix to rotate from body-fixed to integration frame.
partialsMatrix Partials of spherical harmonic acceleration w.r.t. to requested set of sine coefficients (returned by reference).
Definition at line 251 of file sphericalHarmonicPartialFunctions.cpp.
References tudat::basic_mathematics::computePotentialGradient(), and tudat::orbital_element_conversions::radiusIndex.
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtSineCoefficientBlock(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtTidalModelParameter().
template<typename DirectGravityPartial > basic_astrodynamics::AvailableAcceleration tudat::acceleration_partials::getAccelerationTypeOfThirdBodyGravity (const boost::shared_ptr< DirectGravityPartial > directGravityPartial)
Function to get the third body acceleration type from the direct acceleration partial object.
Parameters
directGravityPartial Partial derivative of direct acceleration.
Returns
Type of acceleration for third body acceleration for which direct acceleration partial is given by directGravityPartial (i.e. third_body_central_gravity if input is of type CentralGravitationPartial).
Definition at line 36 of file thirdBodyGravityPartial.h.
References tudat::basic_astrodynamics::third_body_central_gravity, tudat::basic_astrodynamics::third_body_mutual_spherical_harmonic_gravity, and tudat::basic_astrodynamics::third_body_spherical_harmonic_gravity.