Tudat: tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling Class Reference
tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling Class Reference
Class to compute the state partial scaling factors for first-order proper time component of one-way Doppler observables.
#include <oneWayDopplerPartial.h>
Public Member Functions
OneWayDopplerDirectFirstOrderProperTimeComponentScaling (const boost::shared_ptr< observation_models::DirectFirstOrderDopplerProperTimeRateInterface > properTimeRateModel, const observation_models::LinkEndType linkEndWithPartial, const bool computeStatePartials)
Constructor.
double getEquivalencePrincipleViolationParameterPartial ()
Function to compute partial of proper time rate w.r.t. equivalence principle violation parameter.
int getParameterDependencySize (const estimatable_parameters::EstimatebleParameterIdentifier parameterType)
Function to get the size of the direct dependency of proper time rate on parameter.
Eigen::Matrix< double, 1, 3 > getPositionScalingFactor (const observation_models::LinkEndType linkEndType)
Function to retrieve the scaling factor for the derivative w.r.t. the position of a given link end.
std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > getProperTimeParameterPartial (const estimatable_parameters::EstimatebleParameterIdentifier parameterType)
Function to get the direct partial derivative, and associated time, of proper time.
Eigen::Matrix< double, 1, 3 > getVelocityScalingFactor (const observation_models::LinkEndType linkEndType)
Function to retrieve the scaling factor for the derivative w.r.t. the velocity of a given link end.
void update (const std::vector< Eigen::Vector6d > &linkEndStates, const std::vector< double > &times, const observation_models::LinkEndType fixedLinkEnd, const Eigen::VectorXd currentObservation)
Update the scaling object to the current times and states.
Public Member Functions inherited from tudat::observation_partials::OneWayDopplerProperTimeComponentScaling
OneWayDopplerProperTimeComponentScaling (const observation_models::LinkEndType linkEndWithPartial)
Constructor.
virtual ~OneWayDopplerProperTimeComponentScaling ()
Destructor.
Public Member Functions inherited from tudat::observation_partials::PositionPartialScaling
virtual ~PositionPartialScaling ()
Destructor.
Private Attributes
bool computeStatePartials_
Boolean to denote whether state partials are to be computed.
double currentDistance_
Current distance between perturbing body center of mass and computation point.
double currentGravitationalParameter_
Current value of gravitational parameter of central body.
double currentLinkEndTime_
Current time at link end for which this object computes proper time ratre partials.
Eigen::Matrix< double, 1, 3 > partialWrPosition_
Partial of proper time rate w.r.t. position, as computed by last call to update function.
Eigen::Matrix< double, 1, 3 > partialWrtVelocity_
Partial of proper time rate w.r.t. velocity, as computed by last call to update function.
boost::shared_ptr< observation_models::DirectFirstOrderDopplerProperTimeRateInterface > properTimeRateModel_
Object used to compute proper time rate.
Additional Inherited Members
Protected Attributes inherited from tudat::observation_partials::OneWayDopplerProperTimeComponentScaling
observation_models::LinkEndType linkEndWithPartial_
Link end for which this object computes partials.
Detailed Description
Definition at line 96 of file oneWayDopplerPartial.h.
Constructor & Destructor Documentation
tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::OneWayDopplerDirectFirstOrderProperTimeComponentScaling (const boost::shared_ptr< observation_models::DirectFirstOrderDopplerProperTimeRateInterface > properTimeRateModel, const observation_models::LinkEndType linkEndWithPartial, const bool computeStatePartials) inline
Constructor
Parameters
properTimeRateModel Object used to compute proper time rate
linkEndWithPartial Link end for which this partial is created
computeStatePartials Boolean to denote whether state partials are to be computed. It is false if the link end for which this object computes the proper time partials is fixed to the perturbing body.
Definition at line 108 of file oneWayDopplerPartial.h.
References tudat::observation_partials::OneWayDopplerProperTimeComponentScaling::getPositionScalingFactor(), tudat::observation_partials::OneWayDopplerProperTimeComponentScaling::getVelocityScalingFactor(), and tudat::observation_partials::PositionPartialScaling::update().
Member Function Documentation
void tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::update (const std::vector< Eigen::Vector6d > & linkEndStates, const std::vector< double > & times, const observation_models::LinkEndType fixedLinkEnd, const Eigen::VectorXd currentObservation) virtual
Update the scaling object to the current times and states
Parameters
linkEndStates List of states at each link end during observation.
times List of times at each link end during observation.
fixedLinkEnd Link end at which observation time is defined, i.e. link end for which associated time is kept constant when computing observable.
currentObservation Value of observation (proper time rate) for which partial scaling is to be computed
Implements tudat::observation_partials::PositionPartialScaling.
Definition at line 48 of file oneWayDopplerPartial.cpp.
References computeStatePartials_, currentDistance_, currentGravitationalParameter_, currentLinkEndTime_, tudat::relativity::equivalencePrincipleLpiViolationParameter, tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT, tudat::observation_partials::OneWayDopplerProperTimeComponentScaling::linkEndWithPartial_, partialWrPosition_, partialWrtVelocity_, properTimeRateModel_, and tudat::observation_models::transmitter.
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::getPositionScalingFactor (const observation_models::LinkEndType linkEndType) virtual
Function to retrieve the scaling factor for the derivative w.r.t. the position of a given link end
Parameters
linkEndType Link end position for which partial scaling is to be retrieved.
Returns
The scaling factor for the derivative w.r.t. the position of a given link end
Implements tudat::observation_partials::OneWayDopplerProperTimeComponentScaling.
Definition at line 74 of file oneWayDopplerPartial.cpp.
References computeStatePartials_, partialWrPosition_, and properTimeRateModel_.
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::getVelocityScalingFactor (const observation_models::LinkEndType linkEndType) virtual
Function to retrieve the scaling factor for the derivative w.r.t. the velocity of a given link end
Parameters
linkEndType Link end velocity for which partial scaling is to be retrieved.
Returns
The scaling factor for the derivative w.r.t. the velocity of a given link end
Implements tudat::observation_partials::OneWayDopplerProperTimeComponentScaling.
Definition at line 91 of file oneWayDopplerPartial.cpp.
References computeStatePartials_, partialWrtVelocity_, and properTimeRateModel_.
double tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::getEquivalencePrincipleViolationParameterPartial () inline
Function to compute partial of proper time rate w.r.t. equivalence principle violation parameter
Returns
Partial of proper time rate w.r.t. equivalence principle violation parameter
Definition at line 151 of file oneWayDopplerPartial.h.
References tudat::observation_partials::OneWayDopplerProperTimeComponentScaling::getParameterDependencySize(), tudat::observation_partials::OneWayDopplerProperTimeComponentScaling::getProperTimeParameterPartial(), and tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by getProperTimeParameterPartial().
std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::getProperTimeParameterPartial (const estimatable_parameters::EstimatebleParameterIdentifier parameterType) virtual
Function to get the direct partial derivative (e.g. independent of state partials), and associated time, of proper time, w.r.t. parameter defined by parameterType.
Parameters
parameterType Parameter for which partial is to be checked
Returns
Direct partial derivative, and associated time, of proper time rate
Implements tudat::observation_partials::OneWayDopplerProperTimeComponentScaling.
Definition at line 107 of file oneWayDopplerPartial.cpp.
References currentLinkEndTime_, tudat::estimatable_parameters::equivalence_principle_lpi_violation_parameter, getEquivalencePrincipleViolationParameterPartial(), and TUDAT_NAN.
int tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::getParameterDependencySize (const estimatable_parameters::EstimatebleParameterIdentifier parameterType) virtual
Function to get the size of the direct dependency (e.g. independent of state dependency) of proper time rate on parameter. Returns zero for no dependency.
Parameters
parameterType Parameter for which dependency is to be checked.
Returns
Number of columns in direct partial derivative of proper time rates w.r.t. parameterType
Implements tudat::observation_partials::OneWayDopplerProperTimeComponentScaling.
Definition at line 122 of file oneWayDopplerPartial.cpp.
References tudat::estimatable_parameters::equivalence_principle_lpi_violation_parameter.
Member Data Documentation
boost::shared_ptr< observation_models::DirectFirstOrderDopplerProperTimeRateInterface > tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::properTimeRateModel_ private
Definition at line 178 of file oneWayDopplerPartial.h.
Referenced by getPositionScalingFactor(), getVelocityScalingFactor(), and update().
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::partialWrPosition_ private
Definition at line 181 of file oneWayDopplerPartial.h.
Referenced by getPositionScalingFactor(), and update().
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::partialWrtVelocity_ private
Definition at line 184 of file oneWayDopplerPartial.h.
Referenced by getVelocityScalingFactor(), and update().
double tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::currentLinkEndTime_ private
Definition at line 187 of file oneWayDopplerPartial.h.
Referenced by getProperTimeParameterPartial(), and update().
double tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::currentDistance_ private
Definition at line 190 of file oneWayDopplerPartial.h.
Referenced by update().
double tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::currentGravitationalParameter_ private
Definition at line 193 of file oneWayDopplerPartial.h.
Referenced by update().
bool tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::computeStatePartials_ private
Boolean to denote whether state partials are to be computed. It is false if the link end for whicj this object computes the proper time partials is fixed to the perturbing body.
Definition at line 200 of file oneWayDopplerPartial.h.
Referenced by getPositionScalingFactor(), getVelocityScalingFactor(), and update().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/ObservationPartials/oneWayDopplerPartial.h
Astrodynamics/OrbitDetermination/ObservationPartials/oneWayDopplerPartial.cpp