Tudat: tudat::gravitation::SecondDegreeGravitationalTorqueModel Class Reference
tudat::gravitation::SecondDegreeGravitationalTorqueModel Class Reference
Class to compute the second degree gravitational torque.
#include <secondDegreeGravitationalTorque.h>
Public Member Functions
SecondDegreeGravitationalTorqueModel (const std::function< Eigen::Vector3d() > positionOfBodySubjectToTorqueFunction, const std::function< double() > gravitationalParameterOfAttractingBodyFunction, const std::function< Eigen::Matrix3d() > inertiaTensorOfRotatingBodyFunction, const std::function< Eigen::Vector3d() > positionOfBodyExertingTorqueFunction=[](){ return Eigen::Vector3d::Zero();}, const std::function< Eigen::Quaterniond() > rotationToBodyFixedFrameFunction=[](){ return Eigen::Quaterniond(Eigen::Matrix3d::Identity());})
Constructor.
Eigen::Vector3d getTorque ()
Get gravitational torque.
void updateMembers (const double currentTime)
Update member variables used by the gravitational torque model.
Public Member Functions inherited from tudat::basic_astrodynamics::TorqueModel
TorqueModel ()
Constructor.
virtual ~TorqueModel ()
Destructor.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
Private Attributes
double currentGravitationalParameterOfAttractingBody_
Current gravitational parameter of the body that is exerting the torque, as set by updateMembers function.
Eigen::Matrix3d currentInertiaTensorOfRotatingBody_
Eigen::Vector3d currentRelativePositionOfBodySubjectToTorque_
Eigen::Quaterniond currentRotationToBodyFixedFrameFunction_
Rotation from inertial frame to frame fixed to body undergoing torque, as set by updateMembers function.
Eigen::Vector3d currentTorque_
Current gravitational torque, as set by updateMembers function.
std::function< double() > gravitationalParameterOfAttractingBodyFunction_
Function returning the gravitational parameter of the body that is exerting the torque.
std::function< Eigen::Matrix3d() > inertiaTensorOfRotatingBodyFunction_
Function returning the inertia tensor of the body that is subject to the torque, in the frame fixed to that body.
std::function< Eigen::Vector3d() > positionOfBodyExertingTorqueFunction_
Function returning the position of the body that is exerting to the torque, in inertial frame.
std::function< Eigen::Vector3d() > positionOfBodySubjectToTorqueFunction_
Function returning the position of the body that is subject to the torque, in inertial frame.
const std::function< Eigen::Quaterniond() > rotationToBodyFixedFrameFunction_
Function returning the rotation from inertial frame to frame fixed to body undergoing torque.
Additional Inherited Members
Protected Attributes inherited from tudat::basic_astrodynamics::TorqueModel
double currentTime_
Last time at which the updateMembers was evaluated (or NaN if next call is to recompute torque).
Detailed Description
Class to compute the second degree gravitational torque: the gravitational torque exerted by a point mass on a body with degree two gravity field (parameterized by inertia tensor).
Definition at line 48 of file secondDegreeGravitationalTorque.h.
Constructor & Destructor Documentation
SecondDegreeGravitationalTorqueModel()
tudat::gravitation::SecondDegreeGravitationalTorqueModel::SecondDegreeGravitationalTorqueModel (const std::function< Eigen::Vector3d() > positionOfBodySubjectToTorqueFunction, const std::function< double() > gravitationalParameterOfAttractingBodyFunction, const std::function< Eigen::Matrix3d() > inertiaTensorOfRotatingBodyFunction, const std::function< Eigen::Vector3d() > positionOfBodyExertingTorqueFunction = [ ](){ return Eigen::Vector3d::Zero(); }, const std::function< Eigen::Quaterniond() > rotationToBodyFixedFrameFunction = [ ](){ return Eigen::Quaterniond(Eigen::Matrix3d::Identity()); }) inline
Constructor
Parameters
positionOfBodySubjectToTorqueFunction Function returning the position of the body that is subject to the torque, in inertial frame.
gravitationalParameterOfAttractingBodyFunction Function returning the gravitational parameter of the body that is exerting the torque.
inertiaTensorOfRotatingBodyFunction Function returning the inertia tensor of the body that is subject to the torque, in the frame fixed to that body.
positionOfBodyExertingTorqueFunction Function returning the position of the body that is exerting to the torque, in inertial frame.
rotationToBodyFixedFrameFunction Function returning the rotation from inertial frame to frame fixed to body undergoing torque.
Definition at line 66 of file secondDegreeGravitationalTorque.h.
Member Function Documentation
getTorque()
Eigen::Vector3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::getTorque () inline virtual
Returns the gravitational torque. All data required for the computation is taken from member variables, which are set to their latest values by the last call of the updateMembers function.
Returns
Gravitational torque.
See also
updateMembers().
Implements tudat::basic_astrodynamics::TorqueModel.
Definition at line 88 of file secondDegreeGravitationalTorque.h.
References currentTorque_.
updateMembers()
void tudat::gravitation::SecondDegreeGravitationalTorqueModel::updateMembers (const double currentTime) inline virtual
Updates member variables used by the gravitational accfeleration model. Function pointers to retrieve the current values of quantities from which the torque is to be calculated are set by constructor. This function calls them to update the associated variables to their current state.
Parameters
currentTime Time at which torque model is to be updated.
Implements tudat::basic_astrodynamics::TorqueModel.
Definition at line 101 of file secondDegreeGravitationalTorque.h.
References tudat::gravitation::calculateSecondDegreeGravitationalTorque(), currentGravitationalParameterOfAttractingBody_, currentInertiaTensorOfRotatingBody_, currentRelativePositionOfBodySubjectToTorque_, currentRotationToBodyFixedFrameFunction_, currentTorque_, gravitationalParameterOfAttractingBodyFunction_, inertiaTensorOfRotatingBodyFunction_, positionOfBodyExertingTorqueFunction_, positionOfBodySubjectToTorqueFunction_, and rotationToBodyFixedFrameFunction_.
Member Data Documentation
positionOfBodySubjectToTorqueFunction_
std::function< Eigen::Vector3d() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::positionOfBodySubjectToTorqueFunction_ private
Definition at line 120 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
gravitationalParameterOfAttractingBodyFunction_
std::function< double() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::gravitationalParameterOfAttractingBodyFunction_ private
Definition at line 123 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
inertiaTensorOfRotatingBodyFunction_
std::function< Eigen::Matrix3d() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::inertiaTensorOfRotatingBodyFunction_ private
Definition at line 126 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
positionOfBodyExertingTorqueFunction_
std::function< Eigen::Vector3d() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::positionOfBodyExertingTorqueFunction_ private
Definition at line 129 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
rotationToBodyFixedFrameFunction_
const std::function< Eigen::Quaterniond() > tudat::gravitation::SecondDegreeGravitationalTorqueModel::rotationToBodyFixedFrameFunction_ private
Definition at line 132 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
currentRelativePositionOfBodySubjectToTorque_
Eigen::Vector3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentRelativePositionOfBodySubjectToTorque_ private
Current [osition of body exerting torque, w.r.t. body undergoing torque in frame fixed to body undergoing torque, as set by updateMembers function.
Definition at line 136 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
currentGravitationalParameterOfAttractingBody_
double tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentGravitationalParameterOfAttractingBody_ private
Definition at line 139 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
currentInertiaTensorOfRotatingBody_
Eigen::Matrix3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentInertiaTensorOfRotatingBody_ private
Current inertia tensor of the body that is subject to the torque, in the frame fixed to that body, as set by updateMembers function.
Definition at line 143 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
currentRotationToBodyFixedFrameFunction_
Eigen::Quaterniond tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentRotationToBodyFixedFrameFunction_ private
Definition at line 146 of file secondDegreeGravitationalTorque.h.
Referenced by updateMembers().
currentTorque_
Eigen::Vector3d tudat::gravitation::SecondDegreeGravitationalTorqueModel::currentTorque_ private
Definition at line 149 of file secondDegreeGravitationalTorque.h.
Referenced by getTorque(), and updateMembers().
The documentation for this class was generated from the following file:
Astrodynamics/Gravitation/secondDegreeGravitationalTorque.h