Tudat: tudat::statistics Namespace Reference
tudat::statistics Namespace Reference
Classes
class BoostContinuousProbabilityDistribution
Interface for continuous random variable calculations using distributions implemented in boost.
class ContinuousProbabilityDistribution
Base class for a continuous random variable.
class ContinuousRandomVariableGenerator
Random number generator generated directly from inverse cdf function of probability distribution.
class EpanechnikovKernelDistribution
Class for Probability distribution using a single Epanechnikov kernel.
class GaussianCopulaDistributionXd
Implementation of Gaussian Copula Distribution.
class GaussianDistributionXd
Implementation of multi-dimensional Gaussian Probability Distribution.
class InvertibleContinuousProbabilityDistribution
Derived class of ContinuousProbabilityDistribution that includes inverse cdf computation.
class KernelDensityDistribution
Class that uses random samples to generate a multivariate probability distribution using Kernel Density distribution.
class RandomVariableGenerator
Base class for random number generation.
class SimpleLinearRegression
Simple linear regression class.
Typedefs
typedef std::shared_ptr< KernelDensityDistribution > KernelDensityDistributionPointer
Pointer to Kernel Density distribution class.
typedef std::shared_ptr< SimpleLinearRegression > SimpleLinearRegressionPointer
Typedef for shared-pointer to SimpleLinearRegression object.
Enumerations
enum ContinuousBoostStatisticalDistributions {
uniform_boost_distribution = 0, normal_boost_distribution = 1, exponential_boost_distribution = 2, gamma_boost_distribution = 3,
lognormal_boost_distribution = 4, beta_boost_distribution = 5
}
Enum defining implemented continuous boost distributions.
enum KernelType { gaussian_kernel = 0, epanechnikov_kernel = 1 }
Kernel type that is used in the Kernel Density Estimate.
Functions
double calculateGaussianCdf (const double independentVariable, const double mean, const double standardDeviation)
Function to evaluate cdf of Gaussian distribution.
double computeAverageOfVectorComponents (const Eigen::VectorXd &vectorOfData)
Compute average of the components of a vector.
Eigen::VectorXd computeMovingAverage (const Eigen::VectorXd &sampleData, const unsigned int numberOfAveragingPoints)
Compute moving average of an Eigen vector.
std::vector< Eigen::Vector3d > computeMovingAverage (const std::vector< Eigen::Vector3d > &sampleData, const unsigned int numberOfAveragingPoints)
Compute moving average of a set of Eigen vectors in a STL vector.
std::map< double, Eigen::VectorXd > computeMovingAverage (const std::map< double, Eigen::VectorXd > &sampleData, const unsigned int numberOfAveragingPoints)
Compute moving average of a set of Eigen vectors in a map.
double computeSampleMean (const std::vector< double > &sampleData)
Compute sample mean.
Eigen::VectorXd computeSampleMean (const std::vector< Eigen::VectorXd > &sampleData)
Compute sample mean for a sample of VectorXd.
double computeSampleMedian (std::vector< double > sampleData)
Compute Sample median.
double computeSampleVariance (const std::vector< double > &sampleData)
Compute sample variance.
Eigen::VectorXd computeSampleVariance (const std::vector< Eigen::VectorXd > &sampleData)
Compute sample variance for a sample of VectorXd.
double computeStandardDeviationOfVectorComponents (const Eigen::VectorXd &vectorOfData)
Compute standard deviation of the components of a vector.
std::shared_ptr< RandomVariableGenerator< double > > createBoostContinuousRandomVariableGenerator (const ContinuousBoostStatisticalDistributions boostDistribution, const std::vector< double > &parameters, const double seed)
Function to create a random number generator from a continuous univariate distribution implemented in boost.
std::function< double() > createBoostContinuousRandomVariableGeneratorFunction (const ContinuousBoostStatisticalDistributions boostDistribution, const std::vector< double > &parameters, const double seed)
Function to create a random number generating function from a continuous univariate distribution implemented in boost.
std::shared_ptr< InvertibleContinuousProbabilityDistribution< double > > createBoostRandomVariable (const ContinuousBoostStatisticalDistributions boostDistribution, const std::vector< double > &parameters)
Function to create a random variable class of BoostContinuousProbabilityDistribution type.
double evaluateGaussianPdf (const double independentVariable, const double mean, const double standardDeviation)
Function to evaluate pdf of Gaussian distribution.
std::vector< Eigen::VectorXd > generateGaussianRandomSample (const int seed, const int numberOfSamples, const Eigen::VectorXd &mean, const Eigen::VectorXd &standardDeviation)
Generator random vector using pseudo random generator with gaussian distribution (without correlation)
std::vector< Eigen::VectorXd > generateGaussianRandomSample (const int seed, const int numberOfSamples, const int numberOfDimensions, const double mean, const double standardDeviation)
Generator random vector using pseudo random generator with gaussian distribution (without correlation)
std::vector< Eigen::VectorXd > generateRandomSampleFromGenerator (const int numberOfSamples, const std::vector< std::shared_ptr< RandomVariableGenerator< double > > > randomVariableGenerators)
Generate sample of random vectors, with entries of each vector independently, but not identically, distributed.
std::vector< Eigen::VectorXd > generateRandomSampleFromGenerator (const int numberOfSamples, const int numberOfDimensions, const std::shared_ptr< RandomVariableGenerator< double > > randomVariableGenerator)
Generate sample of random vectors, with entries of each vector independently and identically distributed.
std::vector< Eigen::VectorXd > generateUniformRandomSample (const int seed, const int numberOfSamples, const Eigen::VectorXd &lowerBound, const Eigen::VectorXd &upperBound)
Generator random vector using pseudo random generator.
std::vector< Eigen::VectorXd > generateUniformRandomSample (const int seed, const int numberOfSamples, const int numberOfDimensions, const double lowerBound, const double upperBound)
Generator random vector using pseudo random generator.
Typedef Documentation
KernelDensityDistributionPointer
typedef std::shared_ptr< KernelDensityDistribution > tudat::statistics::KernelDensityDistributionPointer
Definition at line 370 of file kernelDensityDistribution.h.
SimpleLinearRegressionPointer
typedef std::shared_ptr< SimpleLinearRegression > tudat::statistics::SimpleLinearRegressionPointer
Definition at line 212 of file simpleLinearRegression.h.
Enumeration Type Documentation
ContinuousBoostStatisticalDistributions
enum tudat::statistics::ContinuousBoostStatisticalDistributions
Enumerator
uniform_boost_distribution
normal_boost_distribution
exponential_boost_distribution
gamma_boost_distribution
lognormal_boost_distribution
beta_boost_distribution
Definition at line 26 of file continuousProbabilityDistributions.h.
KernelType
enum tudat::statistics::KernelType
Enumerator
gaussian_kernel
epanechnikov_kernel
Definition at line 68 of file kernelDensityDistribution.h.
Function Documentation
computeAverageOfVectorComponents()
double tudat::statistics::computeAverageOfVectorComponents (const Eigen::VectorXd & vectorOfData)
Computes the average (arithmetic mean) of the components of a vector.
Parameters
vectorOfData Vector containing data to be averaged.
Returns
Average of data in vector.
Definition at line 26 of file basicStatistics.cpp.
Referenced by computeMovingAverage(), and computeStandardDeviationOfVectorComponents().
computeStandardDeviationOfVectorComponents()
double tudat::statistics::computeStandardDeviationOfVectorComponents (const Eigen::VectorXd & vectorOfData)
Computes the standard deviation of the components of a vector.
Parameters
vectorOfData Vector containing data to be averaged.
Returns
Standard deviation of data in vector.
Definition at line 32 of file basicStatistics.cpp.
References computeAverageOfVectorComponents().
computeSampleMean() [1/2]
double tudat::statistics::computeSampleMean (const std::vector< double > & sampleData)
Computes sample mean based on the following unbiased estimator (Spiegel and Stephens, 2008):
where is the unbiased estimate of the sample mean, is the number of samples, and is the sample value.
Parameters
sampleData Sample data.
Returns
Sample mean.
Definition at line 53 of file basicStatistics.cpp.
Referenced by computeSampleVariance().
computeSampleMean() [2/2]
Eigen::VectorXd tudat::statistics::computeSampleMean (const std::vector< Eigen::VectorXd > & sampleData)
Computes sample mean for a sample of VectorXd based on the following unbiased estimator (Spiegel and Stephens, 2008):
where is the unbiased estimate of the sample mean, is the number of samples, and is the sample value.
Parameters
sampleData Sample data.
Returns
Sample mean.
Definition at line 61 of file basicStatistics.cpp.
computeSampleVariance() [1/2]
double tudat::statistics::computeSampleVariance (const std::vector< double > & sampleData)
Compute sample variance .
Computes sample variance based on the following unbiased estimator (Spiegel and Stephens, 2008):
where is the unbiased estimate of the sample variance, is the number of samples, is the sample value, and is the sample mean.
Parameters
sampleData Map containing sample data.
Returns
Sample variance.
Definition at line 70 of file basicStatistics.cpp.
References computeSampleMean().
computeSampleMedian()
double tudat::statistics::computeSampleMedian (std::vector< double > sampleData)
Computes the median of a set of data samples. (Montgomery, D. C. & Runger, G. C. Applied Statistics and Probability for engineers Wiley, 2014)
Parameters
sampleData Map containing sample data.
Returns
Sample variance.
Definition at line 90 of file basicStatistics.cpp.
References tudat::basic_mathematics::computeModulo().
Referenced by tudat::statistics::KernelDensityDistribution::getMedian().
computeSampleVariance() [2/2]
Eigen::VectorXd tudat::statistics::computeSampleVariance (const std::vector< Eigen::VectorXd > & sampleData)
Computes sample variance for a sample of VectorXd based on the following unbiased estimator (Spiegel and Stephens, 2008):
where is the unbiased estimate of the sample variance, is the number of samples, is the sample value, and is the sample mean.
Parameters
sampleData Map containing sample data.
Returns
Sample variance.
Definition at line 118 of file basicStatistics.cpp.
References computeSampleMean().
computeMovingAverage() [1/3]
Eigen::VectorXd tudat::statistics::computeMovingAverage (const Eigen::VectorXd & sampleData, const unsigned int numberOfAveragingPoints = 5)
Compute moving average of vector.
Compute moving average of vector, where the moving average is computed by sliding a window of the specified length along the data. Note that since the window is centered at the current element, the window size (numberOfAveragingPoints) has to be odd.
Parameters
sampleData Vector of sample data.
numberOfAveragingPoints Number of points (including the center point) to be used to compute the moving average. Needs to be an odd number.
Returns
Vector containing the moving average of the data.
Definition at line 138 of file basicStatistics.cpp.
References computeAverageOfVectorComponents().
Referenced by computeMovingAverage().
computeMovingAverage() [2/3]
std::vector< Eigen::Vector3d > tudat::statistics::computeMovingAverage (const std::vector< Eigen::Vector3d > & sampleData, const unsigned int numberOfAveragingPoints = 5)
Compute moving average of a set of Eigen vectors in a STL vector.
Parameters
sampleData Vector of sample data.
numberOfAveragingPoints Number of points (including the center point) to be used to compute the moving average. Needs to be an odd number.
Returns
Vector containing the moving average of the data.
Definition at line 165 of file basicStatistics.cpp.
References computeMovingAverage().
computeMovingAverage() [3/3]
std::map< double, Eigen::VectorXd > tudat::statistics::computeMovingAverage (const std::map< double, Eigen::VectorXd > & sampleData, const unsigned int numberOfAveragingPoints = 5)
Compute moving average of a set of Eigen vectors in a map. The moving average is computed by first combining the map values into a matrix, and then the moving average along each row is taken. Note that since the computeMovingAverage function is used, the window size (numberOfAveragingPoints) has to be odd.
Parameters
sampleData Map of sample data.
numberOfAveragingPoints Number of points (including the center point) to be used to compute the moving average. Needs to be an odd number.
Returns
Map of data after moving average is applied.
Definition at line 191 of file basicStatistics.cpp.
References computeMovingAverage().
createBoostRandomVariable()
std::shared_ptr< InvertibleContinuousProbabilityDistribution< double > > tudat::statistics::createBoostRandomVariable (const ContinuousBoostStatisticalDistributions boostDistribution, const std::vector< double > & parameters)
Function to create a random variable class of BoostContinuousProbabilityDistribution type, which links random variable interfaces of this architecture to implementations from boost.
Parameters
boostDistribution Type of distribution of which a random variable class is to be generated
parameters Free parameters of requested distribution (for instance mean and standard deviation for Gaussian distribution, see implementation for order of parameter, if relevant)
Returns
Random variable class of BoostContinuousProbabilityDistribution type
Definition at line 23 of file boostProbabilityDistributions.cpp.
References beta_boost_distribution, exponential_boost_distribution, gamma_boost_distribution, lognormal_boost_distribution, normal_boost_distribution, and uniform_boost_distribution.
Referenced by tudat::statistics::KernelDensityDistribution::constructKernel(), and createBoostContinuousRandomVariableGenerator().
evaluateGaussianPdf()
double tudat::statistics::evaluateGaussianPdf (const double independentVariable, const double mean, const double standardDeviation)
Function to evaluate probability distribution function of Gaussian distribution
Parameters
independentVariable Value of indpendent variable at which pdf it is to be evaluated
mean Mean of Gaussian distribution
standardDeviation Standard deviation of Gaussian distribution
Returns
Value of given pdf at requested independent variable value
Definition at line 23 of file continuousProbabilityDistributions.cpp.
References tudat::propagators::independentVariable, and tudat::mathematical_constants::PI.
calculateGaussianCdf()
double tudat::statistics::calculateGaussianCdf (const double independentVariable, const double mean, const double standardDeviation)
Function to evaluate cumulative distribution function of Gaussian distribution
Parameters
independentVariable Value of indpendent variable at which cdf it is to be evaluated
mean Mean of Gaussian distribution
standardDeviation Standard deviation of Gaussian distribution
Returns
Value of given cdf at requested independent variable value
Definition at line 31 of file continuousProbabilityDistributions.cpp.
References tudat::propagators::independentVariable.
generateRandomSampleFromGenerator() [1/2]
std::vector< Eigen::VectorXd > tudat::statistics::generateRandomSampleFromGenerator (const int numberOfSamples, const std::vector< std::shared_ptr< RandomVariableGenerator< double > > > randomVariableGenerators)
Function to generate sample of random vectors, with entries of each vector independently, but not identically, distributed according to probability distributions provided as input. Size of each sample is define by size of vector randomVariableGenerators.
Parameters
numberOfSamples Number of samples that are to be generated.
randomVariableGenerators Probability distributions for the entries of the random vectors (i.e. entry i of this vector is distribution of entry i of each sample).
Returns
Set of samples according to given distribution settings.
Definition at line 28 of file randomSampling.cpp.
Referenced by generateGaussianRandomSample(), generateRandomSampleFromGenerator(), and generateUniformRandomSample().
generateRandomSampleFromGenerator() [2/2]
std::vector< Eigen::VectorXd > tudat::statistics::generateRandomSampleFromGenerator (const int numberOfSamples, const int numberOfDimensions, const std::shared_ptr< RandomVariableGenerator< double > > randomVariableGenerator)
Function to generate sample of random vectors, with entries of each vector independently and identically, distributed according to probability distribution provided as input.
Parameters
numberOfSamples Number of samples that are to be generated.
numberOfDimensions Size of each sample.
randomVariableGenerator Probability distribution used for each of the entries of the random vectors.
Returns
Set of samples according to given distribution settings.
Definition at line 49 of file randomSampling.cpp.
References generateRandomSampleFromGenerator().
generateUniformRandomSample() [1/2]
std::vector< Eigen::VectorXd > tudat::statistics::generateUniformRandomSample (const int seed, const int numberOfSamples, const Eigen::VectorXd & lowerBound, const Eigen::VectorXd & upperBound)
Generate sample of random vectors, with entries of each vector independently, but not identically, uniformly distributed.
Function to generate sample of random vectors, with entries of each vector independently, but not identically, uniformly distributed. The size of each sample is defined by the size of the lowerBound and upperBound vectors (which must have identical size).
Parameters
seed Seed of random number generator.
numberOfSamples Number of samples that are to be generated.
lowerBound Vector of lower bounds for the distributions for the entries of the random vectors (i.e. entry i of this vector is lower bound for distribution of entry i of each sample).
upperBound Vector of upper bounds for the distributions for the entries of the random vectors (i.e. entry i of this vector is upper bound for distribution of entry i of each sample).
Returns
Set of samples according to given distribution settings.
Definition at line 65 of file randomSampling.cpp.
References createBoostContinuousRandomVariableGenerator(), generateRandomSampleFromGenerator(), and uniform_boost_distribution.
Referenced by generateUniformRandomSample().
generateUniformRandomSample() [2/2]
std::vector< Eigen::VectorXd > tudat::statistics::generateUniformRandomSample (const int seed, const int numberOfSamples, const int numberOfDimensions, const double lowerBound = 0.0, const double upperBound = 1.0)
Generate sample of random vectors, with entries of each vector independently and identically uniformly distributed.
Function to generate sample of random vectors, with entries of each vector independently and identically uniformly distributed.
Parameters
seed Seed of random number generator.
numberOfSamples Number of samples that are to be generated.
numberOfDimensions Size of each sample.
lowerBound Lower bound for the distributions for the entries of the random vectors
upperBound Upper bound for the distributions for the entries of the random vectors
Returns
Set of samples according to given distribution settings.
Definition at line 90 of file randomSampling.cpp.
References generateUniformRandomSample().
generateGaussianRandomSample() [1/2]
std::vector< Eigen::VectorXd > tudat::statistics::generateGaussianRandomSample (const int seed, const int numberOfSamples, const Eigen::VectorXd & mean, const Eigen::VectorXd & standardDeviation)
Generate sample of random vectors, with entries of each vector independently, but not identically, Gaussian distributed.
Function to generate sample of random vectors, with entries of each vector independently, but not identically, Gaussian distributed. The size of each sample is defined by the size of the lowerBound and upperBound vectors (which must have identical size).
Parameters
seed Seed of random number generator.
numberOfSamples Number of samples that are to be generated.
mean Vector of mean values for the distributions for the entries of the random vectors (i.e. entry i of this vector is mean for distribution of entry i of each sample).
standardDeviation Vector of standard deviations for the distributions for the entries of the random vectors (i.e. entry i of this vector is standard deviation for distribution of entry i of each sample). *
Returns
Set of samples according to given distribution settings.
Definition at line 103 of file randomSampling.cpp.
References createBoostContinuousRandomVariableGenerator(), generateRandomSampleFromGenerator(), and normal_boost_distribution.
Referenced by generateGaussianRandomSample().
generateGaussianRandomSample() [2/2]
std::vector< Eigen::VectorXd > tudat::statistics::generateGaussianRandomSample (const int seed, const int numberOfSamples, const int numberOfDimensions, const double mean = 0.0, const double standardDeviation = 1.0)
Generate sample of random vectors, with entries of each vector independently and identically Gaussian distributed.
Function to generate sample of random vectors, with entries of each vector independently and identically Gaussian distributed.
Parameters
seed Seed of random number generator.
numberOfSamples Number of samples that are to be generated.
numberOfDimensions Size of each samples
mean Mean value for the distributions for the entries of the random vectors
standardDeviation Standard deviation for the distributions for the entries of the random vectors
Returns
Set of samples according to given distribution settings.
Definition at line 129 of file randomSampling.cpp.
References generateGaussianRandomSample().
createBoostContinuousRandomVariableGeneratorFunction()
std::function< double() > tudat::statistics::createBoostContinuousRandomVariableGeneratorFunction (const ContinuousBoostStatisticalDistributions boostDistribution, const std::vector< double > & parameters, const double seed)
Function to create a random number generating function from a continuous univariate distribution implemented in boost
Parameters
boostDistribution Type of distribution of which a random variable class is to be generated
parameters Free parameters of requested distribution (for instance mean and standard deviation for Gaussian distribution, see implementation for order of parameters, if relevant).
seed Seed of random number generator.
Returns
Random number generator according to given distribution.
Definition at line 24 of file randomVariableGenerator.cpp.
References createBoostContinuousRandomVariableGenerator().
createBoostContinuousRandomVariableGenerator()
std::shared_ptr< RandomVariableGenerator< double > > tudat::statistics::createBoostContinuousRandomVariableGenerator (const ContinuousBoostStatisticalDistributions boostDistribution, const std::vector< double > & parameters, const double seed)
Function to create a random number generator from a continuous univariate distribution implemented in boost
Parameters
boostDistribution Type of distribution of which a random variable class is to be generated
parameters Free parameters of requested distribution (for instance mean and standard deviation for Gaussian distribution, see implementation for order of parameters, if relevant).
seed Seed of random number generator.
Returns
Random number generator according to given distribution.
Definition at line 34 of file randomVariableGenerator.cpp.
References createBoostRandomVariable().
Referenced by createBoostContinuousRandomVariableGeneratorFunction(), generateGaussianRandomSample(), tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::generateNoiseDistributions(), and generateUniformRandomSample().