Tudat: tudat::ephemerides::ReferenceFrameManager Class Reference
tudat::ephemerides::ReferenceFrameManager Class Reference
Class to retrieve translation functions between different frames.
#include <frameManager.h>
Public Member Functions
ReferenceFrameManager (const std::map< std::string, std::shared_ptr< Ephemeris > > &ephemerisMap)
Constructor from named list of ephemerides.
std::string getBaseFrameNameOfBody (const std::string &bodyName)
Get name of the base frame for a given body.
template<typename StateScalarType = double, typename TimeType = double>
std::shared_ptr< Ephemeris > getEphemeris (const std::string &origin, const std::string &body)
Function to retrieve the ephemeris of a body with a requested frame origin.
std::vector< std::string > getEphemerisOrigins (const std::vector< std::string > &bodyList)
Get ephemeris origins (base frame names) for a list of bodies.
std::pair< int, bool > getFrameLevel (const std::string &frame)
Return the level at which the requested ephemeris is in the hierarchy.
std::pair< std::string, int > getNearestCommonFrame (std::vector< std::string > frameList)
Returns the nearest common frame between frames.
Private Member Functions
std::vector< std::shared_ptr< Ephemeris > > getDirectEphemerisFromLowerToUpperFrame (const std::string &lowerFrame, const std::string &upperFrame)
Returns an ephemeris along a single line of the hierarchy tree.
void setEphemerides (const std::map< std::string, std::shared_ptr< Ephemeris > > &additionalEphemerides)
Function to determine frame levels and base frames of all frames.
Private Attributes
std::map< std::string, std::shared_ptr< Ephemeris > > availableEphemerides_
Map of ephemerides (values) of bodies (keys)
std::vector< std::map< std::string, std::string > > baseFrameList_
Vector of frames with associated base frames, ordered by frame level.
std::map< std::string, int > frameIndexList_
Map giving the frame level for each frame name.
Detailed Description
Class to retrieve translation functions between different frames, as calculated from a list of ephemeris objects. Using this class, the various Ephemeris objects may be 'pasted' together to obtain the state of one body w.r.t. any other body.
Definition at line 55 of file frameManager.h.
Constructor & Destructor Documentation
ReferenceFrameManager()
tudat::ephemerides::ReferenceFrameManager::ReferenceFrameManager (const std::map< std::string, std::shared_ptr< Ephemeris > > & ephemerisMap)
Constructor from named list of ephemerides.
Parameters
ephemerisMap List of ephemerides per body.
Definition at line 39 of file frameManager.cpp.
References frameIndexList_, tudat::ephemerides::getBaseFrameName(), and setEphemerides().
Member Function Documentation
getEphemeris()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< Ephemeris > tudat::ephemerides::ReferenceFrameManager::getEphemeris (const std::string & origin, const std::string & body) inline
Function to retrieve the ephemeris of a body with a requested frame origin. Both the body and the origin must be loaded into the frame manager.
Parameters
origin Origin of ephemeris
body Body for which ephemeris is requested.
Returns
Ephemeris of requested body qith requested frame origin
Definition at line 76 of file frameManager.h.
References getDirectEphemerisFromLowerToUpperFrame(), getNearestCommonFrame(), and tudat::ephemerides::Ephemeris::getTemplatedStateFromEphemeris().
getFrameLevel()
std::pair< int, bool > tudat::ephemerides::ReferenceFrameManager::getFrameLevel (const std::string & frame)
Return the level at which the requested ephemeris is in the hierarchy.
Parameters
frame Frame for which the frame level is requested.
Returns
Pair of frame level and boolean. Boolean is true if frame exists, false if not (and frame level NAN).
Definition at line 207 of file frameManager.cpp.
References frameIndexList_, and TUDAT_NAN.
getNearestCommonFrame()
std::pair< std::string, int > tudat::ephemerides::ReferenceFrameManager::getNearestCommonFrame (std::vector< std::string > frameList)
Returns the nearest common frame between frames.
Parameters
frameList Vector of frame names for which the nearest common frame is to be found.
Returns
Nearest common frame, with its frame level.
Definition at line 229 of file frameManager.cpp.
References baseFrameList_, frameIndexList_, and tudat::ephemerides::getBaseFrameName().
Referenced by getEphemeris().
getBaseFrameNameOfBody()
std::string tudat::ephemerides::ReferenceFrameManager::getBaseFrameNameOfBody (const std::string & bodyName)
Get name of the base frame for a given body.
Parameters
bodyName Name of body for which the base frame is to be returned.
Returns
Name od base frame of bodyName.
Definition at line 322 of file frameManager.cpp.
References availableEphemerides_.
Referenced by getEphemerisOrigins().
getEphemerisOrigins()
std::vector< std::string > tudat::ephemerides::ReferenceFrameManager::getEphemerisOrigins (const std::vector< std::string > & bodyList)
Get ephemeris origins (base frame names) for a list of bodies, calls getBaseFrameNameOfBody for each entry of bodyList.
Parameters
bodyList List of bodies for which ephemeris origins are to be calculated.
Returns
Ephemeris origins of bodyList
Definition at line 339 of file frameManager.cpp.
References getBaseFrameNameOfBody().
getDirectEphemerisFromLowerToUpperFrame()
std::vector< std::shared_ptr< Ephemeris > > tudat::ephemerides::ReferenceFrameManager::getDirectEphemerisFromLowerToUpperFrame (const std::string & lowerFrame, const std::string & upperFrame) private
Returns an ephemeris along a single line of the hierarchy tree, i.e. returned ephemeris constituent frame levels must be continuously increasing
Definition at line 162 of file frameManager.cpp.
References availableEphemerides_, baseFrameList_, and frameIndexList_.
Referenced by getEphemeris().
setEphemerides()
void tudat::ephemerides::ReferenceFrameManager::setEphemerides (const std::map< std::string, std::shared_ptr< Ephemeris > > & additionalEphemerides) private
Function to determine frame levels and base frames of all frames; called by constructor.
Definition at line 50 of file frameManager.cpp.
References availableEphemerides_, baseFrameList_, frameIndexList_, and tudat::ephemerides::getBaseFrameName().
Referenced by ReferenceFrameManager().
Member Data Documentation
baseFrameList_
std::vector< std::map< std::string, std::string > > tudat::ephemerides::ReferenceFrameManager::baseFrameList_ private
Vector of frames with associated base frames, ordered by frame level. Index of vector indicates at which frame level the frames in the maps at that index are. The map contains frame names (key) with their associated base frames (value). Each base frame must be a frame of one level lower; base frame of level 0 frames must be global base frame.
Definition at line 210 of file frameManager.h.
Referenced by getDirectEphemerisFromLowerToUpperFrame(), getNearestCommonFrame(), and setEphemerides().
availableEphemerides_
std::map< std::string, std::shared_ptr< Ephemeris > > tudat::ephemerides::ReferenceFrameManager::availableEphemerides_ private
Map of ephemerides (values) of bodies (keys). The frame origins and orientations of these ephemerides can be retrievd from the objects themselves.
Definition at line 217 of file frameManager.h.
Referenced by getBaseFrameNameOfBody(), getDirectEphemerisFromLowerToUpperFrame(), and setEphemerides().
frameIndexList_
std::map< std::string, int > tudat::ephemerides::ReferenceFrameManager::frameIndexList_ private
Map giving the frame level for each frame name.
Definition at line 223 of file frameManager.h.
Referenced by getDirectEphemerisFromLowerToUpperFrame(), getFrameLevel(), getNearestCommonFrame(), ReferenceFrameManager(), and setEphemerides().
The documentation for this class was generated from the following files:
Astrodynamics/Ephemerides/frameManager.h
Astrodynamics/Ephemerides/frameManager.cpp