Tudat: tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel Class Reference
tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel Class Reference
Central + J2 + J3 + J4 gravitational acceleration model class.
#include <centralJ2J3J4GravityModel.h>
Public Member Functions
CentralJ2J3J4GravitationalAccelerationModel (const StateFunction positionOfBodySubjectToAccelerationFunction, const double aGravitationalParameter, const double anEquatorialRadius, const double aJ2GravityCoefficient, const double aJ3GravityCoefficient, const double aJ4GravityCoefficient, const StateFunction positionOfBodyExertingAccelerationFunction=boost::lambda::constant(Eigen::Vector3d::Zero()))
Constructor taking a pointer to a function returning the position of the body subject to gravitational acceleration, constant gravitational parameter, J2-, J3-, and J4-coefficients, and equatorial radius of the body exerting the acceleration, and a pointer to a function returning the position of the body exerting the gravitational acceleration (typically the central body).
Eigen::Vector3d getAcceleration ()
Get gravitational acceleration.
void updateMembers (const double currentTime=TUDAT_NAN)
Update members.
Public Member Functions inherited from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >
AccelerationModel ()
Constructor.
virtual ~AccelerationModel ()
Virtual destructor.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
Public Member Functions inherited from tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d >
SphericalHarmonicsGravitationalAccelerationModelBase (const StateFunction positionOfBodySubjectToAccelerationFunction, const double aGravitationalParameter, const StateFunction positionOfBodyExertingAccelerationFunction, const bool isMutualAttractionUsed)
Constructor taking a pointer to a function returning the position of the body subject to gravitational acceleration, a pointer to a function returning the gravitational parameter of the body exerting the acceleration, and a pointer to a function returning the position of the body exerting the gravitational acceleration (typically the central body).
SphericalHarmonicsGravitationalAccelerationModelBase (const StateFunction positionOfBodySubjectToAccelerationFunction, const boost::function< double() > aGravitationalParameterFunction, const StateFunction positionOfBodyExertingAccelerationFunction, const bool isMutualAttractionUsed)
Constructor taking a pointer to a function returning the position of the body subject to gravitational acceleration, a pointer to a function returning the gravitational parameter of the body exerting the acceleration, and a pointer to a function returning the position of the body exerting the gravitational acceleration (typically the central body).
virtual ~SphericalHarmonicsGravitationalAccelerationModelBase ()
Virtual destructor.
double getCurrentGravitationalParameter ()
Function to return the current gravitational paramter.
Eigen::Vector3d getCurrentPositionOfBodyExertingAcceleration ()
Function to return current position vector of body undergoing gravitational acceleration in inertial frame.
Eigen::Vector3d getCurrentPositionOfBodySubjectToAcceleration ()
Function to return current position vector of body exerting gravitational acceleration in inertial frame.
boost::function< double() > getGravitationalParameterFunction ()
Function to return the function returning the relevant gravitational parameter.
bool getIsMutualAttractionUsed ()
Function to return whether the mutual attraction is used.
boost::function< Eigen::Vector3d() > getStateFunctionOfBodyExertingAcceleration ()
Function to return the function returning position of body exerting acceleration.
boost::function< Eigen::Vector3d() > getStateFunctionOfBodyUndergoingAcceleration ()
Function to return the function returning position of body subject to acceleration.
void updateBaseMembers ()
Update base class members.
Protected Attributes
const double equatorialRadius
Equatorial radius [m].
const double j2GravityCoefficient
J2 gravity coefficient.
const double j3GravityCoefficient
J3 gravity coefficient.
const double j4GravityCoefficient
J4 gravity coefficient.
Protected Attributes inherited from tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >
double currentTime_
Previous time to which acceleration model was updated.
Protected Attributes inherited from tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d >
double gravitationalParameter
Gravitational parameter [m^3 s^-2].
const boost::function< double() > gravitationalParameterFunction
Function returning a gravitational parameter [m^3 s^-2].
bool isMutualAttractionUsed_
Variable denoting whether mutual acceleration between bodies is included.
Eigen::Vector3d positionOfBodyExertingAcceleration
Position of body exerting acceleration.
Eigen::Vector3d positionOfBodySubjectToAcceleration
Position of body subject to acceleration.
const StateFunction sourcePositionFunction
Pointer to function returning position of body exerting acceleration.
const StateFunction subjectPositionFunction
Pointer to function returning position of body subject to acceleration.
Private Types
typedef SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d > Base
Typedef for base class.
Additional Inherited Members
Protected Types inherited from tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d >
typedef boost::function< Eigen::Vector3d() > StateFunction
Typedef for a position-returning function.
Detailed Description
This class implements a gravitational acceleration model that includes the central, J2, J3, and J4 (unnormalized coefficient of general spherical harmonics expansion) terms.
Definition at line 118 of file centralJ2J3J4GravityModel.h.
Member Typedef Documentation
typedef SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d > tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::Base private
Definition at line 125 of file centralJ2J3J4GravityModel.h.
Constructor & Destructor Documentation
tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::CentralJ2J3J4GravitationalAccelerationModel (const StateFunction positionOfBodySubjectToAccelerationFunction, const double aGravitationalParameter, const double anEquatorialRadius, const double aJ2GravityCoefficient, const double aJ3GravityCoefficient, const double aJ4GravityCoefficient, const StateFunction positionOfBodyExertingAccelerationFunction = boost::lambda::constant(Eigen::Vector3d::Zero())) inline
Constructor taking position-functions for bodies, and constant parameters of spherical harmonics expansion.
This constructor uses the Boost::lambda library to create a function on-the-fly that returns the constant gravitational parameter, J2-, J3-, and J4-coefficients, and equatorial radius provided. The constructor also updates all the internal members. The position of the body exerting the gravitational acceleration is an optional parameter; the default position is the origin.
Parameters
positionOfBodySubjectToAccelerationFunction Pointer to function returning position of body subject to gravitational acceleration.
aGravitationalParameter A (constant) gravitational parameter [m^2 s^-3].
anEquatorialRadius A (constant) equatorial radius [m].
aJ2GravityCoefficient A (constant) J2-coefficient.
aJ3GravityCoefficient A (constant) J3-coefficient.
aJ4GravityCoefficient A (constant) J4-coefficient.
positionOfBodyExertingAccelerationFunction Pointer to function returning position of body exerting gravitational acceleration (default = (0,0,0)).
Definition at line 151 of file centralJ2J3J4GravityModel.h.
References getAcceleration(), and updateMembers().
Member Function Documentation
Eigen::Vector3d tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::getAcceleration () virtual
Returns the gravitational acceleration computed using the input parameters provided to the class. This function serves as a wrapper for the computeGravitationalAcceleration(), computeGravitationalAccelerationDueToJ2(), and computeGravitationalAccelerationDueToJ3() functions.
Returns
Computed gravitational acceleration vector.
Implements tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 155 of file centralJ2J3J4GravityModel.cpp.
References tudat::gravitation::computeGravitationalAcceleration(), tudat::gravitation::computeGravitationalAccelerationDueToJ2(), tudat::gravitation::computeGravitationalAccelerationDueToJ3(), tudat::gravitation::computeGravitationalAccelerationDueToJ4(), equatorialRadius, tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d >::gravitationalParameter, j2GravityCoefficient, j3GravityCoefficient, j4GravityCoefficient, tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d >::positionOfBodyExertingAcceleration, and tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d >::positionOfBodySubjectToAcceleration.
Referenced by CentralJ2J3J4GravitationalAccelerationModel().
void tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::updateMembers (const double currentTime = TUDAT_NAN) inline virtual
Updates class members relevant for computing the central gravitational acceleration. In this case the function simply updates the members in the base class.
See also
SphericalHarmonicsGravitationalAccelerationModelBase.
Parameters
currentTime Time at which acceleration model is to be updated.
Implements tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >.
Definition at line 188 of file centralJ2J3J4GravityModel.h.
References tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >::currentTime_, and tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModelBase< Eigen::Vector3d >::updateBaseMembers().
Referenced by CentralJ2J3J4GravitationalAccelerationModel().
Member Data Documentation
const double tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::equatorialRadius protected
Equatorial radius of unnormalized spherical harmonics gravity field representation [m].
Definition at line 202 of file centralJ2J3J4GravityModel.h.
Referenced by getAcceleration().
const double tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::j2GravityCoefficient protected
J2 coefficient of unnormalized spherical harmonics gravity field representation.
Definition at line 208 of file centralJ2J3J4GravityModel.h.
Referenced by getAcceleration().
const double tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::j3GravityCoefficient protected
J3 coefficient of unnormalized spherical harmonics gravity field representation.
Definition at line 214 of file centralJ2J3J4GravityModel.h.
Referenced by getAcceleration().
const double tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel::j4GravityCoefficient protected
J4 coefficient of unnormalized spherical harmonics gravity field representation.
Definition at line 220 of file centralJ2J3J4GravityModel.h.
Referenced by getAcceleration().
The documentation for this class was generated from the following files:
Astrodynamics/Gravitation/centralJ2J3J4GravityModel.h
Astrodynamics/Gravitation/centralJ2J3J4GravityModel.cpp