Tudat: tudat::observation_partials::NWayRangeScaling Class Reference
tudat::observation_partials::NWayRangeScaling Class Reference
Derived class for scaling three-dimensional position partial to n-way range observable partial.
#include <nWayRangePartial.h>
Public Member Functions
NWayRangeScaling (const std::map< int, boost::shared_ptr< OneWayRangeScaling > > &constituentRangeScalings, const int numberOfLinkEnds)
Constructor.
double getProjectedRelativeVelocityRatio (const int linkIndex)
Function to get value by which to scale a constituent one-way ranges partial for it to be put into n-way range partial.
void update (const std::vector< Eigen::Vector6d > &linkEndStates, const std::vector< double > &times, const observation_models::LinkEndType fixedLinkEnd, const Eigen::VectorXd currentObservation)
Update the scaling object to the current times and states.
Public Member Functions inherited from tudat::observation_partials::PositionPartialScaling
virtual ~PositionPartialScaling ()
Destructor.
Private Attributes
std::map< int, boost::shared_ptr< OneWayRangeScaling > >::iterator constituentRangeScalingIterator_
Predeclared iterator (for efficiencty)
std::map< int, boost::shared_ptr< OneWayRangeScaling > > constituentRangeScalings_
Map of consitutent one-way range scaling objects, with link index as map key.
int numberOfLinkEnds_
Number of link ends in observation.
std::map< int, double > projectedRelativeVelocityRatios_
List of values by which to scale constituent one-way ranges partials for it to be put into n-way range partial.
Detailed Description
Derived class for scaling three-dimensional position partial to n-way range observable partial. Implementation is taken from Moyer(2000) for constituent one-way ranges, whicha re scaled (at O(v/c)) to n-way range implementation
Definition at line 41 of file nWayRangePartial.h.
Constructor & Destructor Documentation
tudat::observation_partials::NWayRangeScaling::NWayRangeScaling (const std::map< int, boost::shared_ptr< OneWayRangeScaling > > & constituentRangeScalings, const int numberOfLinkEnds) inline
Constructor
Parameters
constituentRangeScalings Map of consitutent one-way range scaling objects, with link end index as map key
numberOfLinkEnds Number of link ends in observable
Definition at line 51 of file nWayRangePartial.h.
References update().
Member Function Documentation
void tudat::observation_partials::NWayRangeScaling::update (const std::vector< Eigen::Vector6d > & linkEndStates, const std::vector< double > & times, const observation_models::LinkEndType fixedLinkEnd, const Eigen::VectorXd currentObservation) virtual
Update the scaling object to the current times and states
Parameters
linkEndStates List of states at each link end during observation Index of vector maps to link end for a given ObsevableType through getLinkEndIndex function.
times List of times at each link end during observation.
fixedLinkEnd Link end at which observation time is defined, i.e. link end for which associated time is kept constant when computing observable.
currentObservation Value of observation for which partial scaling is to be computed
Implements tudat::observation_partials::PositionPartialScaling.
Definition at line 21 of file nWayRangePartial.cpp.
References constituentRangeScalingIterator_, constituentRangeScalings_, tudat::observation_models::getNWayLinkIndexFromLinkEndType(), numberOfLinkEnds_, projectedRelativeVelocityRatios_, tudat::observation_models::receiver, tudat::physical_constants::SPEED_OF_LIGHT, and tudat::observation_models::transmitter.
Referenced by NWayRangeScaling().
double tudat::observation_partials::NWayRangeScaling::getProjectedRelativeVelocityRatio (const int linkIndex) inline
Function to get value by which to scale a constituent one-way ranges partial for it to be put into n-way range partial, for a single constituent one-way range (as compiuuted by last call to update function).
Parameters
linkIndex Index of link for which scaling is to be returned.
Returns
Value by which to scale a constituent one-way ranges partial for it to be put into n-way range partial.
Definition at line 78 of file nWayRangePartial.h.
References projectedRelativeVelocityRatios_.
Member Data Documentation
std::map< int, boost::shared_ptr< OneWayRangeScaling > > tudat::observation_partials::NWayRangeScaling::constituentRangeScalings_ private
Definition at line 86 of file nWayRangePartial.h.
Referenced by update().
std::map< int, boost::shared_ptr< OneWayRangeScaling > >::iterator tudat::observation_partials::NWayRangeScaling::constituentRangeScalingIterator_ private
Definition at line 89 of file nWayRangePartial.h.
Referenced by update().
std::map< int, double > tudat::observation_partials::NWayRangeScaling::projectedRelativeVelocityRatios_ private
Definition at line 92 of file nWayRangePartial.h.
Referenced by getProjectedRelativeVelocityRatio(), and update().
int tudat::observation_partials::NWayRangeScaling::numberOfLinkEnds_ private
Definition at line 95 of file nWayRangePartial.h.
Referenced by tudat::observation_partials::NWayRangePartial::calculatePartial(), and update().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/ObservationPartials/nWayRangePartial.h
Astrodynamics/OrbitDetermination/ObservationPartials/nWayRangePartial.cpp