Tudat: tudat::json_interface Namespace Reference
tudat::json_interface Namespace Reference
Classes
class ApplicationOptions
Class containing the application options for Tudat apps that use json_interface.
class AutoReportableBugError
Class for errors that print a report bug link to open an issue on GitHub (optionally pre-filled).
class ExportSettings
class IllegalValueError
Class for errors generated when trying to convert a json object to another type.
class JsonSimulationManager
Class for managing JSON-based simulations.
class KeyPath
Class for specifying a key pat used to access data from json objects.
struct Keys
Keys recognised by json_interface.
class nullptrPointerError
Class for errors generated when a pointer that should not be nullptr is nullptr.
class ReportableBugError
Class for errors that print a report bug link.
struct SpecialKeys
Special keys (used internally by json_interface, can't be used in JSON files).
class SpiceSettings
Class containing the settings for Spice used in a simulation.
class UndefinedKeyError
Class for errors generated when trying to access a key from a json object that does not exist.
class UnimplementedEnumError
Class for errors generated when trying to use a value for an enum of type EnumType that is marked as supported by json_interface but for which no implementation was found.
class UnknownEnumError
Class for errors generated when trying to convert between enum and std::string.
class UnrecognizedValueAccessError
Class for unrecognized errors generated during the retrieval of a value from a json object.
class UnsupportedEnumError
Class for errors generated when trying to use a value for an enum of type T that is not supported by json_interface.
class ValueAccessError
Class for errors generated during the retrieval of a value from a json object.
Typedefs
template<typename T >
using BodyToBodyMap = std::unordered_map< std::string, SingleBodyMap< T > >
template<typename T >
using NoPointerBodyToBodyMap = std::unordered_map< std::string, NoPointerSingleBodyMap< T > >
template<typename T >
using NoPointerSingleBodyMap = std::unordered_map< std::string, std::vector< T > >
template<typename T >
using SingleBodyMap = std::unordered_map< std::string, std::vector< std::shared_ptr< T > > >
Enumerations
enum ExceptionResponseType { continueSilently, printWarning, throwError }
Possible responses to an exception during validation phase in Tudat apps that use json_interface.
enum StateType { cartesianElements, keplerianElements, sphericalElements }
Possible ways of providing initial translational states.
Functions
bool arrayContainsObjects (nlohmann::json &jsonArray)
Returns whether any of the elements in jsonArray (and their subelements) are of type object.
template<typename T >
void assertNonnullptrPointer (const std::shared_ptr< T > &pointer)
Check that a pointer is not nullptr.
template<typename ContainerType >
void assignIfNotEmpty (nlohmann::json &jsonObject, const std::string &key, const ContainerType &container)
Assign object to jsonObject[ key ] if container is not empty.
template<typename EquatableType >
void assignIfNotNaN (nlohmann::json &jsonObject, const std::string &key, const EquatableType &value)
Assign value to jsonObject[ key ] if value is not NaN.
template<typename T >
void assignIfNotnullptr (nlohmann::json &jsonObject, const std::string &key, const std::shared_ptr< T > &object)
Assign object to jsonObject[ key ] if object is not nullptr.
void checkUnusedKeys (const nlohmann::json &jsonObject, const ExceptionResponseType response)
Check for key paths that are defined in jsonObject but not contained by the global variable accessedKeyPaths.
void clearAccessHistory ()
Clear the global variable accessedKeyPaths.
template<typename T >
bool contains (const std::vector< T > &vector, const T &value)
Whether vector contains value.
template<typename T >
bool containsAllOf (const std::vector< T > &vector, std::vector< T > values)
Whether vector contains all of values.
template<typename T >
bool containsAnyOf (const std::vector< T > &vector, std::vector< T > values)
Whether vector contains any of values.
void convertToObjectIfContainsObjects (nlohmann::json &j)
Convert j to object if j is an array containing objects.
std::shared_ptr< simulation_setup::BodySettings > createBodySettings (const nlohmann::json &jsonObject)
Create a simulation_setup::BodySettings object with the settings from jsonObject.
template<typename TimeType , typename StateScalarType >
void determineInitialStates (nlohmann::json &jsonObject, const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > &integratorSettings)
Determine initial states for the propagator object contained in jsonObject (if not provided).
template<typename EnumType >
EnumType enumFromString (const std::string &stringValue, const std::map< EnumType, std::string > &stringValues)
Get an enum value of type EnumType from a std::string.
template<typename TimeType = double, typename StateScalarType = double>
void exportResultsOfDynamicsSimulator (const std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > &singleArcDynamicsSimulator, const std::vector< std::shared_ptr< ExportSettings > > &exportSettingsVector)
Export results of dynamicsSimulator according to the settings specified in exportSettingsVector.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< ApplicationOptions > &applicationOptions)
Create a shared pointer to a ApplicationOptions object from a json object.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< ExportSettings > &exportSettings)
Create a shared pointer to a ExportSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, ExceptionResponseType &exceptionResponseType)
Convert json to ExceptionResponseType.
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< SpiceSettings > &spiceSettings)
Create a shared pointer to a SpiceSettings object from a json object.
void from_json (const nlohmann::json &jsonObject, StateType &stateType)
Convert json to StateType.
template<typename ValueType >
ValueType getAs (const nlohmann::json &jsonObject)
Convert jsonObject to ValueType.
nlohmann::json getAsArray (const nlohmann::json &jsonObject)
Convert jsonObject to a json array.
std::string getAssociatedKey (const propagators::IntegratedStateType integratedStateType)
Get the associated key (defined in a body JSON object) for an integrated state.
template<typename StateScalarType >
Eigen::Matrix< StateScalarType, 6, 1 > getCartesianState (const nlohmann::json &jsonObject, const KeyPath &keyPath=KeyPath(), const std::shared_ptr< simulation_setup::Body > &centralBody=nullptr, double epoch=TUDAT_NAN)
Get a Cartesian state from a JSON object.
nlohmann::json getDeserializedJSON (const boost::filesystem::path &filePath)
Read and parse a (normal) json object from a file, and then parse its imported modular files.
template<template< typename ... > class MapType, typename KeyType , typename ValueType >
std::vector< ValueType > getFlattenedMapValues (const MapType< KeyType, std::vector< ValueType > > &map)
Get a vector containing the concatenated values of the vectors of an (un)ordered map.
KeyPath getKeyPath (const nlohmann::json &jsonObject)
Get the absolute key path from which jsonObject was retrieved.
std::set< KeyPath > getKeyPaths (const nlohmann::json &jsonObject, const KeyPath &baseKeyPath=SpecialKeys::root)
Get all the key paths defined for jsonObject.
template<typename K , typename V >
K getKeyWithValue (const std::map< K, V > &map, const V &value)
The key of map containing value.
std::pair< unsigned int, unsigned int > getLineAndCol (std::ifstream &stream, const std::streampos position)
Get the corresponding line and column for a certain (byte) position in a std::ifstream.
template<template< typename ... > class MapType, typename KeyType , typename ValueType >
std::vector< KeyType > getMapKeys (const MapType< KeyType, ValueType > &map)
Get a vector containing the keys of an (un)ordered map.
template<template< typename ... > class MapType, typename KeyType , typename ValueType >
std::vector< ValueType > getMapValues (const MapType< KeyType, ValueType > &map)
Get a vector containing the values of an (un)ordered map.
std::string getParentKey (const nlohmann::json &jsonObject, const std::string &errorMessage)
Get the key at which jsonObject was obtained.
boost::filesystem::path getPathForJSONFile (const std::string &file, const boost::filesystem::path &basePath)
Get the path for a JSON file.
ExceptionResponseType getResponseToEvent (const nlohmann::json &jsonObject, const std::string &eventName, const ExceptionResponseType defaultResponse)
Get the response type to an event for a json object.
nlohmann::json getRootObject (const nlohmann::json &jsonObject)
Get the a shared pointer to jsonObject at key SpecialKeys::rootObject.
template<typename TimeType >
TimeType getTerminationEpoch (const std::shared_ptr< propagators::PropagationTerminationSettings > &terminationSettings)
Get end epoch for propagator. Returns TUDAT_NAN if there is no time termination condition.
template<typename ValueType >
ValueType getValue (const nlohmann::json &jsonObject, const KeyPath &keyPath)
Get the value of jsonObject at keyPath.
template<typename ValueType >
ValueType getValue (const nlohmann::json &jsonObject, const KeyPath &keyPath, const ValueType &defaultValue)
Get the value of jsonObject at keyPath, or return optionalValue if not defined.
template<typename ValueType >
ValueType getValue (const nlohmann::json &jsonObject, const std::vector< KeyPath > &keyPaths)
Get the value of jsonObject at the first defined key path in keyPaths.
template<typename EnumType >
void handleUnimplementedEnumValue (const EnumType enumValue, const std::map< EnumType, std::string > &stringValues, const std::vector< EnumType > &unssupportedValues)
Handle an unimplemented enum value of type EnumType.
int indexFromKey (const std::string &key)
Get the int-value of an int-convertible key.
bool isConvertibleToArray (const nlohmann::json &j)
Whether j is convertible to a json array.
bool isDefined (const nlohmann::json &jsonObject, const KeyPath &keyPath)
Whether the key at keyPath is defined for jsonObject.
template<typename T >
bool isNaN (const T &value)
Whether value is NaN.
template<template< typename ... > class MapType, typename KeyType , typename ValueType >
nlohmann::json jsonFromMap (const MapType< KeyType, ValueType > &map)
void loadSpiceKernels (const std::shared_ptr< SpiceSettings > &spiceSettings)
Load in Tudat the Spice kernels specified in spiceSettings.
template<template< typename ... > class MapType, typename KeyType , typename ValueType >
MapType< KeyType, ValueType > mapFromJson (const nlohmann::json &jsonObject)
void mergeJSON (nlohmann::json &jsonObject, const boost::filesystem::path &filePath)
Merge an array of JSON input objects.
KeyPath operator/ (KeyPath path1, const KeyPath &path2)
KeyPath operator/ (const KeyPath &path, const std::string &str)
KeyPath operator/ (const std::string &str, const KeyPath &path)
KeyPath operator/ (const std::string &str1, const std::string &str2)
KeyPath operator/ (const KeyPath &path, const char *str)
KeyPath operator/ (const char *str, const KeyPath &path)
KeyPath operator/ (const KeyPath &path, const unsigned int vectorIndex)
KeyPath operator/ (const unsigned int vectorIndex, const KeyPath &path)
KeyPath operator/ (const std::string &str, const unsigned int vectorIndex)
KeyPath operator/ (const unsigned int vectorIndex, const std::string &str)
KeyPath operator/ (const KeyPath &path, const int vectorIndex)
KeyPath operator/ (const int vectorIndex, const KeyPath &path)
KeyPath operator/ (const std::string &str, const int vectorIndex)
KeyPath operator/ (const int vectorIndex, const std::string &str)
KeyPath operator/ (const char *str1, const std::string &str2)
KeyPath operator/ (const std::string &str1, const char *str2)
std::ostream & operator<< (std::ostream &stringRepresentation, const KeyPath &keyPath)
String representation for KeyPath, as key.subkey.vectorIndex.subsubkey ...
void parseModularJSON (nlohmann::json &jsonObject, const boost::filesystem::path &filePath, nlohmann::json parentObject=nlohmann::json(), boost::filesystem::path rootFilePath=boost::filesystem::path())
Parse a modular json object.
std::string pathAddingPlaceholders (std::string path)
Return path with the recognized paths replaced by placeholders (such as ${TUDAT_ROOT_PATH}).
std::string pathRemovingPlaceholders (std::string path)
Return path with the recognized path placeholders (such as ${TUDAT_ROOT_PATH}) replaced by the actual paths.
nlohmann::json readJSON (const boost::filesystem::path &filePath, const boost::filesystem::path &parentFilePath, const boost::filesystem::path &rootFilePath)
Read a JSON file into a json object.
template<typename K , typename V >
void reduceToLast (std::map< K, V > map)
Remove all entries of map except the last one.
template<typename StateScalarType >
void resetDependentVariableSaveSettings (std::shared_ptr< propagators::MultiTypePropagatorSettings< StateScalarType > > &propagatorSettings, const std::vector< std::shared_ptr< ExportSettings > > &exportSettingsVector)
Update dependent variable save settings of propagator from export settings object.
template<typename T >
void split (const std::string &string, const char delimiter, const bool trimSpaces, T result)
Split string using delimiter.
std::vector< std::string > split (const std::string &string, const char delimiter, const bool trim=true)
Get a vector containing the parts resulting from splitting string using delimiter.
template<typename EnumType >
std::string stringFromEnum (const EnumType enumValue, const std::map< EnumType, std::string > &stringValues)
Get a std::string from an enum value of type EnumType.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< ApplicationOptions > &applicationOptions)
Create a json object from a shared pointer to a ApplicationOptions object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< ExportSettings > &exportSettings)
Create a json object from a shared pointer to a ExportSettings object.
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< SpiceSettings > &spiceSettings)
Create a json object from a shared pointer to a SpiceSettings object.
void to_json (nlohmann::json &jsonObject, const ExceptionResponseType &exceptionResponseType)
Convert ExceptionResponseType to json.
void to_json (nlohmann::json &jsonObject, const StateType &stateType)
Convert StateType to json.
template<typename TimeType , typename StateScalarType >
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< JsonSimulationManager< TimeType, StateScalarType > > &jsonSimulationManager)
Function to create a json object from a Simulation object.
template<typename TimeType >
void updateBodiesFromJSON (const nlohmann::json &jsonObject, simulation_setup::NamedBodyMap &bodyMap, std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > &bodySettingsMap, const std::string globalFrameOrigin, const std::string globalFrameOrientation, const std::shared_ptr< SpiceSettings > &spiceSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > &integratorSettings)
Update bodyMap and bodySettingsMap from jsonObject (using spiceSettings for default settings and initial time from integratorSettings).
void updateBodySettings (std::shared_ptr< simulation_setup::BodySettings > &bodySettings, const nlohmann::json &jsonObject)
Update bodySettings with the settings from jsonObject.
template<typename T >
void updateFromJSON (T &value, const nlohmann::json &jsonObject, const KeyPath &keyPath={ })
Set value to be the value of jsonObject at keyPath.
template<typename T >
void updateFromJSONIfDefined (T &value, const nlohmann::json &jsonObject, const KeyPath &keyPath={ })
Set value to be the value of jsonObject at keyPath if defined.
void updatePaths (nlohmann::json &jsonObject, const boost::filesystem::path &filePath, const boost::filesystem::path &parentFilePath, const boost::filesystem::path &rootFilePath)
Update paths for a JSON object.
std::string url_encode (const std::string &value)
Encode a string for use in an URL.
nlohmann::json & valueAt (nlohmann::json &jsonObject, const std::string &key, const bool mutator)
Access/mutate a key of a json object or array.
nlohmann::json valueAt (nlohmann::json jsonObject, const KeyPath &keyPath)
Access a key path of a json object or array.
Variables
std::set< KeyPath > accessedKeyPaths = { }
static std::map< ExceptionResponseType, std::string > exceptionResponseTypes
Map of ExceptionResponseType string representations.
static std::vector< std::pair< std::string, std::string > > pathPlaceholders
static std::map< StateType, std::string > stateTypes
Map of StateType string representations.
static std::vector< StateType > unsupportedStateTypes = { }
StateType not supported by json_interface.
Typedef Documentation
SingleBodyMap
template<typename T > using tudat::json_interface::SingleBodyMap = typedef std::unordered_map< std::string, std::vector< std::shared_ptr< T > > >
Definition at line 476 of file valueAccess.h.
BodyToBodyMap
template<typename T > using tudat::json_interface::BodyToBodyMap = typedef std::unordered_map< std::string, SingleBodyMap< T > >
Definition at line 479 of file valueAccess.h.
NoPointerSingleBodyMap
template<typename T > using tudat::json_interface::NoPointerSingleBodyMap = typedef std::unordered_map< std::string, std::vector< T > >
Definition at line 482 of file valueAccess.h.
NoPointerBodyToBodyMap
template<typename T > using tudat::json_interface::NoPointerBodyToBodyMap = typedef std::unordered_map< std::string, NoPointerSingleBodyMap< T > >
Definition at line 485 of file valueAccess.h.
Enumeration Type Documentation
StateType
enum tudat::json_interface::StateType
Enumerator
cartesianElements
keplerianElements
sphericalElements
Definition at line 30 of file state.h.
ExceptionResponseType
enum tudat::json_interface::ExceptionResponseType
Enumerator
continueSilently
printWarning
throwError
Definition at line 32 of file errorHandling.h.
Function Documentation
createBodySettings()
std::shared_ptr< simulation_setup::BodySettings > tudat::json_interface::createBodySettings (const nlohmann::json & jsonObject)
Create a simulation_setup::BodySettings object with the settings from jsonObject.
Parameters
jsonObject The json object containing the settings for one body.
Returns
Body settings object.
Definition at line 57 of file body.cpp.
References updateBodySettings().
Referenced by updateBodiesFromJSON().
updateBodySettings()
void tudat::json_interface::updateBodySettings (std::shared_ptr< simulation_setup::BodySettings > & bodySettings, const nlohmann::json & jsonObject)
Update bodySettings with the settings from jsonObject. Does not change the values already defined in bodySettings that are not specified in jsonObject.
Parameters
bodySettings Body settings object to be updated.
jsonObject The json object containing only the settings for one body.
Definition at line 66 of file body.cpp.
References updateFromJSONIfDefined().
Referenced by createBodySettings(), and updateBodiesFromJSON().
updateBodiesFromJSON()
template<typename TimeType > void tudat::json_interface::updateBodiesFromJSON (const nlohmann::json & jsonObject, simulation_setup::NamedBodyMap & bodyMap, std::map< std::string, std::shared_ptr< simulation_setup::BodySettings > > & bodySettingsMap, const std::string globalFrameOrigin, const std::string globalFrameOrientation, const std::shared_ptr< SpiceSettings > & spiceSettings, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > & integratorSettings)
Update bodyMap and bodySettingsMap from jsonObject (using spiceSettings for default settings and initial time from integratorSettings).
Parameters
jsonObject The root json object containing all the relevant fields ("bodies" mandatory, "finalEpoch" mandatory if Spice kernels should be preloaded, "globalFrameOrigin" and "globalFrameOrientation" optional).
bodyMap The named body map to be updated (returned by reference).
bodySettingsMap The map of body settings created from jsonObject and used to create bodyMap (returned by reference).
globalFrameOrigin Name of the global frame origin.
globalFrameOrientation Name of the global frame orientation.
spiceSettings The settings for Spice (nullptr if Spice not used).
integratorSettings The settings for the integrator (nullptr if Spice not used).
Exceptions
std::runtime_error If any body is configured to be created using default settings and either spiceSettings is nullptr or integratorSettings is nullptr and Spice is configured to preload kernels.
Definition at line 71 of file body.h.
References tudat::json_interface::Keys::bodies, tudat::simulation_setup::createBodies(), createBodySettings(), tudat::json_interface::Keys::finalEpoch, tudat::simulation_setup::getDefaultBodySettings(), getValue(), tudat::simulation_setup::setGlobalFrameBodyEphemerides(), updateBodySettings(), and tudat::json_interface::Keys::Body::useDefaultSettings.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetBodies().
to_json() [1/6]
void tudat::json_interface::to_json (nlohmann::json & jsonObject, const std::shared_ptr< SpiceSettings > & spiceSettings)
Definition at line 21 of file spice.cpp.
References assignIfNotEmpty().
from_json() [1/5]
void tudat::json_interface::from_json (const nlohmann::json & jsonObject, std::shared_ptr< SpiceSettings > & spiceSettings)
Definition at line 49 of file spice.cpp.
References getValue(), updateFromJSON(), and updateFromJSONIfDefined().
loadSpiceKernels()
void tudat::json_interface::loadSpiceKernels (const std::shared_ptr< SpiceSettings > & spiceSettings)
Load in Tudat the Spice kernels specified in spiceSettings.
Remarks
Clears any Spice kernel loaded previously.
If spiceSettings is nullptr, no kernels are loaded.
Parameters
spiceSettings The Spice settings containing the paths to the kernels to be loaded.
Definition at line 77 of file spice.cpp.
References tudat::spice_interface::clearSpiceKernels(), tudat::spice_interface::loadSpiceKernelInTudat(), and tudat::spice_interface::loadStandardSpiceKernels().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetSpice().
to_json() [2/6]
template<typename TimeType , typename StateScalarType > void tudat::json_interface::to_json (nlohmann::json & jsonObject, const std::shared_ptr< JsonSimulationManager< TimeType, StateScalarType > > & jsonSimulationManager)
Definition at line 599 of file jsonInterface.h.
References assignIfNotEmpty(), assignIfNotnullptr(), tudat::json_interface::Keys::bodies, tudat::json_interface::Keys::globalFrameOrientation, tudat::json_interface::Keys::globalFrameOrigin, tudat::json_interface::Keys::integrator, tudat::json_interface::Keys::options, tudat::json_interface::Keys::spice, tudat::propagators::to_json(), and tudat::json_interface::Keys::xport.
to_json() [3/6]
void tudat::json_interface::to_json (nlohmann::json & jsonObject, const std::shared_ptr< ExportSettings > & exportSettings)
Definition at line 21 of file export.cpp.
References assignIfNotEmpty().
from_json() [2/5]
void tudat::json_interface::from_json (const nlohmann::json & jsonObject, std::shared_ptr< ExportSettings > & exportSettings)
Definition at line 39 of file export.cpp.
References getValue(), and updateFromJSONIfDefined().
exportResultsOfDynamicsSimulator()
template<typename TimeType = double, typename StateScalarType = double> void tudat::json_interface::exportResultsOfDynamicsSimulator (const std::shared_ptr< propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType > > & singleArcDynamicsSimulator, const std::vector< std::shared_ptr< ExportSettings > > & exportSettingsVector)
Export results of dynamicsSimulator according to the settings specified in exportSettingsVector.
Parameters
singleArcDynamicsSimulator The dynamics simulator containing the results.
exportSettingsVector The vector containing export settings (each element represents a file to be exported).
Exceptions
std::exception If any of the requested variables is not recognized or was not stored in the results of dynamicsSimulator.
Definition at line 83 of file export.h.
References assertNonnullptrPointer(), tudat::propagators::cpuTimeVariable, tudat::propagators::dependentVariable, tudat::input_output::field_types::time::epoch, tudat::propagators::getDependentVariableId(), tudat::propagators::getDependentVariableSaveSize(), getKeyWithValue(), tudat::propagators::independentVariable, tudat::propagators::stateVariable, tudat::input_output::writeDataMapToTextFile(), and tudat::input_output::writeMatrixToFile().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::exportResults().
getAssociatedKey()
std::string tudat::json_interface::getAssociatedKey (const propagators::IntegratedStateType integratedStateType) inline
Get the associated key (defined in a body JSON object) for an integrated state.
Parameters
integratedStateType The integrated state type for which the associated key is requested.
Returns
The associated key for the integrated state.
Definition at line 38 of file propagator.h.
References tudat::propagators::body_mass_state, tudat::json_interface::Keys::Body::initialState, tudat::json_interface::Keys::Body::mass, tudat::propagators::rotational_state, tudat::json_interface::Keys::Body::rotationalState, and tudat::propagators::translational_state.
Referenced by determineInitialStates().
determineInitialStates()
template<typename TimeType , typename StateScalarType > void tudat::json_interface::determineInitialStates (nlohmann::json & jsonObject, const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > & integratorSettings)
Determine initial states for the propagator object contained in jsonObject (if not provided). The initial states can be inferred either from the state properties of the body settings (e.g. body.initialState, body.mass, etc.) or from the ephemeris of the body objects in bodyMap at the initial time determined from integratorSettings. If the initial states cannot be inferred, the initialStates of the propagators in jsonObject won't be updated.
Parameters
jsonObject The root json object to be updated with the inferred initial states (returned by reference).
bodyMap Body map containing only bodies to be propagated with valid ephemeris.
integratorSettings Integrator settings containing the initial epoch for the ephemeris to be used.
Definition at line 66 of file propagator.h.
References tudat::json_interface::Keys::bodies, getAssociatedKey(), tudat::propagators::getSingleIntegrationSize(), getValue(), isDefined(), tudat::json_interface::Keys::propagators, and tudat::propagators::translational_state.
resetDependentVariableSaveSettings()
template<typename StateScalarType > void tudat::json_interface::resetDependentVariableSaveSettings (std::shared_ptr< propagators::MultiTypePropagatorSettings< StateScalarType > > & propagatorSettings, const std::vector< std::shared_ptr< ExportSettings > > & exportSettingsVector)
Update dependent variable save settings of propagator from export settings object.
Parameters
propagatorSettings The propagator settings object to be updated (passed by reference).
exportSettingsVector The export settings settings object containing the variables to be saved.
Definition at line 168 of file propagator.h.
References contains(), tudat::propagators::dependentVariable, and tudat::propagators::getVariableId().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings().
getTerminationEpoch()
template<typename TimeType > TimeType tudat::json_interface::getTerminationEpoch (const std::shared_ptr< propagators::PropagationTerminationSettings > & terminationSettings)
Definition at line 201 of file propagator.h.
References isNaN(), and TUDAT_NAN.
to_json() [4/6]
void tudat::json_interface::to_json (nlohmann::json & jsonObject, const StateType & stateType) inline
Definition at line 49 of file state.h.
References stateTypes, and stringFromEnum().
from_json() [3/5]
void tudat::json_interface::from_json (const nlohmann::json & jsonObject, StateType & stateType) inline
Definition at line 55 of file state.h.
References enumFromString(), and stateTypes.
getCartesianState()
template<typename StateScalarType > Eigen::Matrix< StateScalarType, 6, 1 > tudat::json_interface::getCartesianState (const nlohmann::json & jsonObject, const KeyPath & keyPath = KeyPath(), const std::shared_ptr< simulation_setup::Body > & centralBody = nullptr, double epoch = TUDAT_NAN)
Get a Cartesian state from a JSON object. The jsonObject can be either an array of 6 numbers (in which case it is assumed to be directly the Cartesian state) or an object with different keys (such as vx, eccentricity, etc.) and different possible types (Cartesian, Keplerian, spherical).
Parameters
jsonObject The JSON object.
keyPath The key path at which the state array/object can be retrieved from jsonObject. Empty if jsonObject is already the array/object (default value).
centralBody Associated central body from which the central gravitational parameter, average radius, ephemeris, etc. are retrieved when converting certain elements types to Cartesian. This information can also be provided in the jsonObject, in which case this can be set to nullptr (default value).
epoch The associated epoch for converting from spherical to Cartesian elements. This information can also be provided in the jsonObject, in which case this can be set to TUDAT_NAN (default value).
Definition at line 75 of file state.h.
References tudat::input_output::field_types::state::apoapsisDistance, tudat::input_output::field_types::state::argumentOfPeriapsis, tudat::orbital_element_conversions::argumentOfPeriapsisIndex, assertNonnullptrPointer(), cartesianElements, tudat::orbital_element_conversions::convertEccentricAnomalyToTrueAnomaly(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::orbital_element_conversions::convertMeanAnomalyToEccentricAnomaly(), tudat::orbital_element_conversions::convertSphericalOrbitalToCartesianState(), tudat::input_output::field_types::state::eccentricity, tudat::orbital_element_conversions::eccentricityIndex, tudat::input_output::field_types::time::epoch, tudat::orbital_element_conversions::flightPathIndex, handleUnimplementedEnumValue(), tudat::orbital_element_conversions::headingAngleIndex, tudat::input_output::field_types::state::inclination, tudat::orbital_element_conversions::inclinationIndex, isDefined(), isNaN(), keplerianElements, tudat::orbital_element_conversions::latitudeIndex, tudat::orbital_element_conversions::longitudeIndex, tudat::input_output::field_types::state::longitudeOfAscendingNode, tudat::orbital_element_conversions::longitudeOfAscendingNodeIndex, tudat::input_output::field_types::state::meanAnomaly, tudat::input_output::field_types::state::meanMotion, tudat::input_output::field_types::state::periapsisDistance, tudat::mathematical_constants::PI, tudat::orbital_element_conversions::radiusIndex, tudat::input_output::field_types::state::semiMajorAxis, tudat::orbital_element_conversions::semiMajorAxisIndex, tudat::orbital_element_conversions::speedIndex, sphericalElements, stateTypes, tudat::ephemerides::transformStateToGlobalFrame(), tudat::input_output::field_types::state::trueAnomaly, tudat::orbital_element_conversions::trueAnomalyIndex, TUDAT_NAN, unsupportedStateTypes, updateFromJSONIfDefined(), tudat::orbital_element_conversions::xCartesianPositionIndex, tudat::orbital_element_conversions::xCartesianVelocityIndex, tudat::orbital_element_conversions::yCartesianPositionIndex, tudat::orbital_element_conversions::yCartesianVelocityIndex, tudat::orbital_element_conversions::zCartesianPositionIndex, and tudat::orbital_element_conversions::zCartesianVelocityIndex.
getPathForJSONFile()
boost::filesystem::path tudat::json_interface::getPathForJSONFile (const std::string & file, const boost::filesystem::path & basePath = boost::filesystem::current_path())
Get the path for a JSON file. This function will first try to locate the file "basePath/file". If this fails, and file contains no extension, the function will try to locate the file "basePath/file/main.json". If this also fails, the function will then try to locate the file "basePath/file.json". If this also fails, an error will be thrown.
Parameters
file Name of the JSON file (with extension) or directory at which a "main.json" file is located.
basePath Parent directory in which to look for the requested file.
Returns
Path for the JSON file.
Exceptions
Error if the file does not exist.
Definition at line 26 of file deserialization.cpp.
Referenced by parseModularJSON(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetInputFile().
getLineAndCol()
std::pair< unsigned int, unsigned int > tudat::json_interface::getLineAndCol (std::ifstream & stream, const std::streampos position)
Get the corresponding line and column for a certain (byte) position in a std::ifstream.
Parameters
stream The stream (passed by reference, its current byte position will be set to zero and then reset to the original one before returning, so effectively this function does not modify the stream).
position The byte position (or character index) of interest.
Returns
Line and column for the character at position in stream.
Definition at line 72 of file deserialization.cpp.
Referenced by readJSON().
updatePaths()
void tudat::json_interface::updatePaths (nlohmann::json & jsonObject, const boost::filesystem::path & filePath, const boost::filesystem::path & parentFilePath, const boost::filesystem::path & rootFilePath)
Update paths for a JSON object.
Looks for expressions ${FILE_STEM}, ${FILE_NAME}, ${PARENT_FILE_STEM}, ${PARENT_FILE_NAME}, ${ROOT_FILE_STEM} and ${ROOT_FILE_NAME} in all the strings of jsonObject, replacing them, respetively, bu the stem of filename of the file in which it is defined, in which it was included, or in the root input file (the one provided to the command line app as argument).
Then, it fixes paths in included files by searching string matching the expressions "@path(myPath)", only when myPath is a relative path. This is necessary because myPath must be relative to the root file, but in input files the user provides paths relative to the directory in which the definition file is located.
This feature can be "turned off" by providing paths directly without the "@path" keyword (e.g. "myPath"). This is safe when no modular files are included, but can result in problems otherwise. If paths are provided directly without the "@path" keyword, then the user is responsible for defining them always relative to the root file in which they are going to be included (and not relative to the file in which they are defined).
Parameters
jsonObject The json object containing / being a string.
filePath Path to the file in which the path is defined.
parentFilePath Path to the file in which the file in which the path is defined was included (equal to filePath if jsonObject was defined at parentFilePath).
rootFilePath Path to the root file that was passed as command-line argument to the application. (equal to filePath if jsonObject was defined at rootFilePath).
Definition at line 121 of file deserialization.cpp.
Referenced by readJSON().
readJSON()
nlohmann::json tudat::json_interface::readJSON (const boost::filesystem::path & filePath, const boost::filesystem::path & parentFilePath = boost::filesystem::path(), const boost::filesystem::path & rootFilePath = boost::filesystem::path())
Read a JSON file into a json object. If inclusionFile is not empty, the strings matching the expression "#path(relativePath)" are replaced by the corresponding relative path relative to the file in which it is being included.
Parameters
filePath Path to the JSON file.
parentFilePath File from which the contents of filePath are being read (empty if filePath is equal to parentFilePath).
rootFilePath Path to the root file that was passed as command-line argument to the application (empty if filePath is equal to rootFilePath).
Returns
Read json object.
Definition at line 169 of file deserialization.cpp.
References getLineAndCol(), and updatePaths().
Referenced by getDeserializedJSON(), and parseModularJSON().
mergeJSON()
void tudat::json_interface::mergeJSON (nlohmann::json & jsonObject, const boost::filesystem::path & filePath)
Merge an array of JSON input objects.
If jsonObject is not an array, this function will do nothing.
If jsonObject is an array of objects, the first object will be used to create the initial json object. Then, the subsequent objects will be used to create this initial object, by updating (or settings) the keys defined in these subsequent objects with the provided objects.
Parameters
jsonObject The json containing an object (no merging will be applied) or an array of objects (the elements will be merged).
filePath The file from which jsonObject was retrieved.
Definition at line 202 of file deserialization.cpp.
References valueAt().
Referenced by getDeserializedJSON().
parseModularJSON()
void tudat::json_interface::parseModularJSON (nlohmann::json & jsonObject, const boost::filesystem::path & filePath, nlohmann::json parentObject = nlohmann::json(), boost::filesystem::path rootFilePath = boost::filesystem::path())
Parse a modular json object containing strings (or being equal to a string) of matching the expression "$(path){key}", which will be replaced with the value for the key "key" in the file at "path".
"path" can be absolute or relative (to the parent directory of filePath).
If the part "(path)" is not provided, the key "key" will be searched in parentObject (or in jsonObject if parentObject is not defined).
If the part "{key}" is not provided, the whole json object contained in the file at "path" will be used.
"key" can be a single key, or a key path separated by dots (e.g. "key.subkey.subsubkey"). Elements of arrays can be accessed by indicating their index, starting from 0 (e.g. "key[2].subkey[0]").
"key" can contain a single key (path) or many, separated by commas (e.g. "key1,key2.subkey"). If the character "," is found in "key", jsonObject will be converted to an array. The key "key1," creates an array with one element.
"key" can contain colons, in which case jsonObject will be converted to an object/map (e.g. "a:keyA,b:keyB[0]").
Illegal characters in referenced file paths: (){}
Illegal characters in referenced keys: (){}.:,
Remarks
This function results in a recursive loop when a key value references itself, making the app terminate without providing an informative error message.
Parameters
jsonObject The json object to be parsed (passed by reference).
filePath Path of the file from which jsonObject was retrieved.
parentObject The json object form which jsonObject was retrieved, if any (default is nullptr json).
rootFilePath Path to the root file that was passed as command-line argument to the application (empty if filePath is equal to rootFilePath).
Definition at line 285 of file deserialization.cpp.
References getPathForJSONFile(), readJSON(), split(), and valueAt().
Referenced by getDeserializedJSON().
getDeserializedJSON()
nlohmann::json tudat::json_interface::getDeserializedJSON (const boost::filesystem::path & inputFilePath)
Read and parse a (normal) json object from a file, and then parse its imported modular files using parseModularJSON().
Parameters
inputFilePath Path to the root JSON file.
Returns
Object containing the keys defined in the original file and all the imported files.
Definition at line 465 of file deserialization.cpp.
References mergeJSON(), parseModularJSON(), and readJSON().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetInputFile().
assertNonnullptrPointer()
template<typename T > void tudat::json_interface::assertNonnullptrPointer (const std::shared_ptr< T > & pointer)
Check that a pointer to an object of type T is not nullptr.
Parameters
pointer The pointer that is not allowed to be nullptr.
Exceptions
nullptrPointerError< T > If pointer is nullptr.
Definition at line 350 of file errorHandling.h.
Referenced by exportResultsOfDynamicsSimulator(), tudat::propagators::from_json(), getCartesianState(), tudat::simulation_setup::to_json(), tudat::interpolators::to_json(), tudat::numerical_integrators::to_json(), and tudat::propagators::to_json().
enumFromString()
template<typename EnumType > EnumType tudat::json_interface::enumFromString (const std::string & stringValue, const std::map< EnumType, std::string > & stringValues)
Get an enum value of type EnumType from a std::string.
Parameters
stringValue The string to be converted to EnumType.
stringValues Map containing the string representation for the values of EnumType.
Returns
The EnumType corresponding to stringValue.
Exceptions
UnknownEnumError If no entry with value stringValue is found in stringValues.
Definition at line 392 of file errorHandling.h.
Referenced by tudat::gravitation::from_json(), tudat::numerical_integrators::from_json(), tudat::basic_astrodynamics::from_json(), tudat::interpolators::from_json(), tudat::reference_frames::from_json(), tudat::aerodynamics::from_json(), tudat::ephemerides::from_json(), from_json(), tudat::simulation_setup::from_json(), and tudat::propagators::from_json().
stringFromEnum()
template<typename EnumType > std::string tudat::json_interface::stringFromEnum (const EnumType enumValue, const std::map< EnumType, std::string > & stringValues)
Get a std::string from an enum value of type EnumType.
Parameters
enumValue The EnumType to be converted to string.
stringValues Map containing the string representation for the values of EnumType.
Returns
The std::string corresponding to enumValue.
Exceptions
UnknownEnumError If no entry with key enumValue is found in stringValues.
Definition at line 420 of file errorHandling.h.
Referenced by tudat::gravitation::to_json(), tudat::numerical_integrators::to_json(), tudat::basic_astrodynamics::to_json(), tudat::interpolators::to_json(), tudat::reference_frames::to_json(), tudat::aerodynamics::to_json(), tudat::ephemerides::to_json(), to_json(), tudat::simulation_setup::to_json(), tudat::propagators::to_json(), and tudat::json_interface::UnimplementedEnumError< EnumType >::UnimplementedEnumError().
handleUnimplementedEnumValue()
template<typename EnumType > void tudat::json_interface::handleUnimplementedEnumValue (const EnumType enumValue, const std::map< EnumType, std::string > & stringValues, const std::vector< EnumType > & unssupportedValues)
Handle an unimplemented enum value of type EnumType.
Parameters
enumValue The enum value of type T that is not implemented.
stringValues Map containing the string representation for the values of EnumType (including enumValue).
unssupportedValues Vector of values of EnumType that are not supported by json_interface.
Exceptions
UnsupportedEnumError<EnumType> If enumValue is contained in unssupportedValues.
UnimplementedEnumError<EnumType> If enumValue is not contained in unssupportedValues.
Definition at line 508 of file errorHandling.h.
References contains(), and tudat::json_interface::ReportableBugError::what().
Referenced by tudat::interpolators::from_json(), tudat::simulation_setup::from_json(), tudat::numerical_integrators::from_json(), tudat::propagators::from_json(), getCartesianState(), tudat::interpolators::to_json(), tudat::simulation_setup::to_json(), tudat::numerical_integrators::to_json(), and tudat::propagators::to_json().
indexFromKey()
int tudat::json_interface::indexFromKey (const std::string & key)
Get the int-value of an int-convertible key.
Parameters
key The int-convertible key, of the type "@0", "@1", etc.
Returns
The array index, or -1 if the key is not convertible to integer.
Definition at line 402 of file keys.cpp.
Referenced by getAsArray(), operator<<(), and valueAt().
operator<<()
std::ostream & tudat::json_interface::operator<< (std::ostream & stringRepresentation, const KeyPath & keyPath)
Definition at line 440 of file keys.cpp.
References tudat::json_interface::SpecialKeys::dot, indexFromKey(), and tudat::json_interface::SpecialKeys::root.
operator/() [1/16]
KeyPath tudat::json_interface::operator/ (KeyPath path1, const KeyPath & path2) inline
Definition at line 508 of file keys.h.
operator/() [2/16]
KeyPath tudat::json_interface::operator/ (const KeyPath & path, const std::string & str) inline
Definition at line 517 of file keys.h.
operator/() [3/16]
KeyPath tudat::json_interface::operator/ (const std::string & str, const KeyPath & path) inline
Definition at line 522 of file keys.h.
operator/() [4/16]
KeyPath tudat::json_interface::operator/ (const std::string & str1, const std::string & str2) inline
Definition at line 527 of file keys.h.
operator/() [5/16]
KeyPath tudat::json_interface::operator/ (const KeyPath & path, const char * str) inline
Definition at line 532 of file keys.h.
operator/() [6/16]
KeyPath tudat::json_interface::operator/ (const char * str, const KeyPath & path) inline
Definition at line 537 of file keys.h.
operator/() [7/16]
KeyPath tudat::json_interface::operator/ (const KeyPath & path, const unsigned int vectorIndex) inline
Definition at line 542 of file keys.h.
operator/() [8/16]
KeyPath tudat::json_interface::operator/ (const unsigned int vectorIndex, const KeyPath & path) inline
Definition at line 547 of file keys.h.
operator/() [9/16]
KeyPath tudat::json_interface::operator/ (const std::string & str, const unsigned int vectorIndex) inline
Definition at line 552 of file keys.h.
operator/() [10/16]
KeyPath tudat::json_interface::operator/ (const unsigned int vectorIndex, const std::string & str) inline
Definition at line 557 of file keys.h.
operator/() [11/16]
KeyPath tudat::json_interface::operator/ (const KeyPath & path, const int vectorIndex) inline
Definition at line 562 of file keys.h.
operator/() [12/16]
KeyPath tudat::json_interface::operator/ (const int vectorIndex, const KeyPath & path) inline
Definition at line 567 of file keys.h.
operator/() [13/16]
KeyPath tudat::json_interface::operator/ (const std::string & str, const int vectorIndex) inline
Definition at line 572 of file keys.h.
operator/() [14/16]
KeyPath tudat::json_interface::operator/ (const int vectorIndex, const std::string & str) inline
Definition at line 577 of file keys.h.
operator/() [15/16]
KeyPath tudat::json_interface::operator/ (const char * str1, const std::string & str2) inline
Definition at line 582 of file keys.h.
operator/() [16/16]
KeyPath tudat::json_interface::operator/ (const std::string & str1, const char * str2) inline
Definition at line 587 of file keys.h.
to_json() [5/6]
void tudat::json_interface::to_json (nlohmann::json & jsonObject, const std::shared_ptr< ApplicationOptions > & applicationOptions)
Definition at line 21 of file options.cpp.
References assignIfNotEmpty().
from_json() [4/5]
void tudat::json_interface::from_json (const nlohmann::json & jsonObject, std::shared_ptr< ApplicationOptions > & applicationOptions)
Definition at line 38 of file options.cpp.
References updateFromJSONIfDefined().
to_json() [6/6]
void tudat::json_interface::to_json (nlohmann::json & jsonObject, const ExceptionResponseType & exceptionResponseType) inline
Definition at line 34 of file options.h.
References exceptionResponseTypes, and stringFromEnum().
from_json() [5/5]
void tudat::json_interface::from_json (const nlohmann::json & jsonObject, ExceptionResponseType & exceptionResponseType) inline
Definition at line 40 of file options.h.
References enumFromString(), and exceptionResponseTypes.
pathAddingPlaceholders()
std::string tudat::json_interface::pathAddingPlaceholders (std::string path)
Return path with the recognized paths replaced by placeholders (such as ${TUDAT_ROOT_PATH}).
Parameters
path Path without placeholders.
Returns
Path with placeholders.
Definition at line 23 of file path.cpp.
References pathPlaceholders.
pathRemovingPlaceholders()
std::string tudat::json_interface::pathRemovingPlaceholders (std::string path)
Return path with the recognized path placeholders (such as ${TUDAT_ROOT_PATH}) replaced by the actual paths. If any of the placeholders is not recognized, it will not be replaced and no warning or error will be generated.
Parameters
path Path with placeholders.
Returns
Path without placeholders.
Definition at line 41 of file path.cpp.
References pathPlaceholders.
split() [1/2]
template<typename T > void tudat::json_interface::split (const std::string & string, const char delimiter, const bool trimSpaces, T result)
Definition at line 35 of file utilities.h.
Referenced by tudat::input_output::getNumberOfIndependentVariablesInCoefficientFile(), tudat::json_interface::KeyPath::KeyPath(), parseModularJSON(), tudat::input_output::readCoefficientsFile(), tudat::earth_orientation::EOPReader::readEopFile(), tudat::simulation_setup::readGravityFieldFile(), tudat::input_output::readMatrixFromFile(), tudat::input_output::readStlVectorMapFromFile(), and split().
split() [2/2]
std::vector< std::string > tudat::json_interface::split (const std::string & string, const char delimiter, const bool trim = true) inline
Get a vector containing the parts resulting from splitting string using delimiter.
Parameters
string The string to be splitted.
delimiter The delimiter to be used.
trim Whether to remove leading and trailing spaces from the returned strings.
Returns
Vector containing the parts resulting from splitting string using delimiter.
Definition at line 54 of file utilities.h.
References split().
reduceToLast()
template<typename K , typename V > void tudat::json_interface::reduceToLast (std::map< K, V > map)
Remove all entries of map except the last one. If map is empty, this function does nothing.
Definition at line 66 of file utilities.h.
getKeyWithValue()
template<typename K , typename V > K tudat::json_interface::getKeyWithValue (const std::map< K, V > & map, const V & value)
Returns
The key of map containing value.
Exceptions
std::runtime_error If map does not contain value.
Definition at line 80 of file utilities.h.
Referenced by exportResultsOfDynamicsSimulator().
isNaN()
template<typename T > bool tudat::json_interface::isNaN (const T & value)
Returns
Whether value is NaN.
Definition at line 97 of file utilities.h.
Referenced by assignIfNotNaN(), getCartesianState(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::getEndEpoch(), tudat::json_interface::SpiceSettings::getFinalOffset(), tudat::json_interface::SpiceSettings::getInitialOffset(), getTerminationEpoch(), tudat::json_interface::UndefinedKeyError::rethrowIfNaNNotAllowed(), tudat::simulation_setup::to_json(), and tudat::propagators::to_json().
contains()
template<typename T > bool tudat::json_interface::contains (const std::vector< T > & vector, const T & value)
Returns
Whether vector contains value.
Definition at line 107 of file utilities.h.
Referenced by containsAllOf(), containsAnyOf(), getAsArray(), getValue(), handleUnimplementedEnumValue(), mapFromJson(), and resetDependentVariableSaveSettings().
containsAnyOf()
template<typename T > bool tudat::json_interface::containsAnyOf (const std::vector< T > & vector, std::vector< T > values)
Returns
Whether vector contains any of values.
Definition at line 117 of file utilities.h.
References contains().
Referenced by getValue(), and tudat::json_interface::UndefinedKeyError::handleUseOfDefaultValue().
containsAllOf()
template<typename T > bool tudat::json_interface::containsAllOf (const std::vector< T > & vector, std::vector< T > values)
Returns
Whether vector contains all of values.
Definition at line 134 of file utilities.h.
References contains().
getMapKeys()
template<template< typename ... > class MapType, typename KeyType , typename ValueType > std::vector< KeyType > tudat::json_interface::getMapKeys (const MapType< KeyType, ValueType > & map)
Get a vector containing the keys of an (un)ordered map.
Definition at line 151 of file utilities.h.
getMapValues()
template<template< typename ... > class MapType, typename KeyType , typename ValueType > std::vector< ValueType > tudat::json_interface::getMapValues (const MapType< KeyType, ValueType > & map)
Get a vector containing the values of an (un)ordered map.
Definition at line 166 of file utilities.h.
getFlattenedMapValues()
template<template< typename ... > class MapType, typename KeyType , typename ValueType > std::vector< ValueType > tudat::json_interface::getFlattenedMapValues (const MapType< KeyType, std::vector< ValueType > > & map)
Get a vector containing the concatenated values of the vectors of an (un)ordered map.
Definition at line 181 of file utilities.h.
Referenced by tudat::propagators::to_json().
url_encode()
std::string tudat::json_interface::url_encode (const std::string & value) inline
Encode a string for use in an URL. Reference: https://stackoverflow.com/questions/154536/encode-decode-urls-in-c
Definition at line 198 of file utilities.h.
Referenced by tudat::json_interface::AutoReportableBugError::updateReportURL().
valueAt() [1/2]
nlohmann::json & tudat::json_interface::valueAt (nlohmann::json & jsonObject, const std::string & key, const bool mutator = false)
Access/mutate a key of a json object or array. jsonObject is passed by reference and the returned value is a reference, so this method can be used to mutate a jsonObject (e.g. valueAt(jsonObject, myKey, true) = newValue). This only works if the third argument is true. If it isn't, and the key does not exist, an error will be thrown. Supports json arrays. If the field "key" does not exist, this function will try to convert it to integer and access jsonObject at that index.
Parameters
jsonObject The json object.
key The key to access.
mutator Whether to use mutator or accessor methods.
Returns
A reference to the value of the accessed key (will be a nullptr json if the key did not exist).
Definition at line 25 of file valueAccess.cpp.
References indexFromKey().
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::at(), getResponseToEvent(), getValue(), isDefined(), mergeJSON(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::operator[](), parseModularJSON(), and valueAt().
valueAt() [2/2]
nlohmann::json tudat::json_interface::valueAt (nlohmann::json jsonObject, const KeyPath & keyPath)
Access a key path of a json object or array. jsonObject is constant, so the returned value cannot be modified. Supports json arrays. If the any key in keyPath does not exist, this function will try to convert it to integer and access jsonObject at that index.
Parameters
jsonObject The constant json object.
keyPath The key path to access.
Returns
The value at the accessed key path.
Definition at line 53 of file valueAccess.cpp.
References valueAt().
isDefined()
bool tudat::json_interface::isDefined (const nlohmann::json & jsonObject, const KeyPath & keyPath)
Whether the key at keyPath is defined for jsonObject.
Parameters
jsonObject The json object.
keyPath The key path specifying to key to be checked.
Returns
Whether the key at keyPath is defined for jsonObject.
Definition at line 63 of file valueAccess.cpp.
References valueAt().
Referenced by determineInitialStates(), tudat::simulation_setup::from_json(), tudat::interpolators::from_json(), tudat::propagators::from_json(), getCartesianState(), and getValue().
getRootObject()
nlohmann::json tudat::json_interface::getRootObject (const nlohmann::json & jsonObject)
Get the jsonObject at key SpecialKeys::rootObject.
copybrief getRootObject
Parameters
jsonObject The json object.
Returns
JSON representation of the root object of jsonObject.
Exceptions
UndefinedKeyError If the key SpecialKeys::rootObject is not defined for jsonObject.
Definition at line 80 of file valueAccess.cpp.
References tudat::json_interface::SpecialKeys::rootObject.
getKeyPath()
KeyPath tudat::json_interface::getKeyPath (const nlohmann::json & jsonObject)
copybrief getKeyPath
Parameters
jsonObject The json object.
Returns
Absolute key path from which jsonObject was retrieved.
Exceptions
UndefinedKeyError If the key SpecialKeys::keyPath is not defined for jsonObject.
Definition at line 86 of file valueAccess.cpp.
References getValue(), tudat::json_interface::SpecialKeys::keyPath, and tudat::json_interface::SpecialKeys::root.
Referenced by getParentKey(), and getValue().
getParentKey()
std::string tudat::json_interface::getParentKey (const nlohmann::json & jsonObject, const std::string & errorMessage = "Could not determine parent key: context is missing.")
copybrief getParentKey
Parameters
jsonObject The json object.
errorMessage Error message to be printed if jsonObject has no key SpecialKeys::keyPath.
Returns
Key at which jsonObject was obtained.
Exceptions
UndefinedKeyError If the key SpecialKeys::keyPath is not defined for jsonObject.
Definition at line 92 of file valueAccess.cpp.
References getKeyPath().
Referenced by tudat::simulation_setup::from_json().
getResponseToEvent()
ExceptionResponseType tudat::json_interface::getResponseToEvent (const nlohmann::json & jsonObject, const std::string & eventName, const ExceptionResponseType defaultResponse = continueSilently)
Get the response type to an event for a json object.
Parameters
jsonObject The json object in which the type of response to the event is defined, or a json object with a root object containing this information.
eventName The name of the event.
defaultResponse Default response if the response to the event is not defined. By default, continueSilently.
Returns
Response type to the event.
Definition at line 106 of file valueAccess.cpp.
References tudat::json_interface::Keys::options, tudat::json_interface::SpecialKeys::rootObject, and valueAt().
Referenced by getValue().
getKeyPaths()
std::set< KeyPath > tudat::json_interface::getKeyPaths (const nlohmann::json & jsonObject, const KeyPath & baseKeyPath = SpecialKeys::root)
Get all the key paths defined for jsonObject.
Parameters
jsonObject The json object.
baseKeyPath The key path in which to look for sub-key paths. Default is SpecialKeys::root, i.e. a key path will be added to the returned std::set for each key defined in jsonObject.
Returns
A set containing a key path for each key defined in jsonObject at baseKeyPath.
Definition at line 139 of file valueAccess.cpp.
References convertToObjectIfContainsObjects().
Referenced by checkUnusedKeys().
checkUnusedKeys()
void tudat::json_interface::checkUnusedKeys (const nlohmann::json & jsonObject, const ExceptionResponseType response)
Check for key paths that are defined in jsonObject but not contained by the global variable accessedKeyPaths.
Parameters
jsonObject The json object.
response Response type when finding unused keys in jsonObject.
Exceptions
std::runtime_error If response is set to ExceptionResponseType::throwError and at least one unsued key was found in jsonObject.
Definition at line 162 of file valueAccess.cpp.
References accessedKeyPaths, getKeyPaths(), printWarning, and throwError.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::runPropagation().
arrayContainsObjects()
bool tudat::json_interface::arrayContainsObjects (nlohmann::json & jsonArray)
Definition at line 187 of file valueAccess.cpp.
Referenced by convertToObjectIfContainsObjects().
convertToObjectIfContainsObjects()
void tudat::json_interface::convertToObjectIfContainsObjects (nlohmann::json & j)
Convert j to object if j is an array containing objects. This method does nothing if j is not an array, if j is empty, or if the elements (and subelements) of j are not of type object.
Parameters
j json object to be converted, or the original j.
Definition at line 208 of file valueAccess.cpp.
References arrayContainsObjects().
Referenced by getKeyPaths(), and getValue().
getAsArray()
nlohmann::json tudat::json_interface::getAsArray (const nlohmann::json & jsonObject)
Convert jsonObject to a json array. Does nothing if jsonObject is already an array. If jsonObject is an object whose (non-special) keys are all convertible to unsigned int, the equivalent json array will be returned. Otherise, the original jsonObject is returned.
Parameters
jsonObject The json object to be converted.
Returns
jsonObject as a json array, or the original jsonObject if it is not convertible to array.
Definition at line 228 of file valueAccess.cpp.
References tudat::json_interface::SpecialKeys::all, contains(), and indexFromKey().
Referenced by std::from_json(), and isConvertibleToArray().
isConvertibleToArray()
bool tudat::json_interface::isConvertibleToArray (const nlohmann::json & j)
Whether j is convertible to a json array. True if j is an array or an object whose (non-special) keys are all convertible to unsigned int.
Parameters
j The json object to be checked.
Returns
Whether j is convertible to a json array.
Definition at line 278 of file valueAccess.cpp.
References getAsArray().
clearAccessHistory()
void tudat::json_interface::clearAccessHistory () inline
Clear the global variable accessedKeyPaths.
Definition at line 125 of file valueAccess.h.
References accessedKeyPaths.
Referenced by tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::updateSettings().
getValue() [1/3]
template<typename ValueType > ValueType tudat::json_interface::getValue (const nlohmann::json & jsonObject, const KeyPath & keyPath)
Get the value of jsonObject at keyPath.
Parameters
jsonObject The json object.
keyPath Key path from which to retrieve the value.
Returns
Value at the requested key path.
Exceptions
UndefinedKeyError If the requested key path is not defined.
UndefinedKeyError If some of the subkeys needed to create the shared pointer of ValueType are missing (only when jsonObject at keyPath is of type object).
IllegalValueError<ValueType> If the obtained value for the requested key path is not convertible to ValueType.
IllegalValueError<SubvalueType> If some of the subkeys needed to create the shared pointer of ValueType are not convertible to SubvalueType (only when jsonObject at keyPath is of type object).
Definition at line 188 of file valueAccess.h.
References accessedKeyPaths, tudat::json_interface::SpecialKeys::all, tudat::json_interface::KeyPath::canonical(), contains(), containsAnyOf(), convertToObjectIfContainsObjects(), getKeyPath(), tudat::json_interface::KeyPath::isAbsolute(), isDefined(), tudat::json_interface::SpecialKeys::keyPath, tudat::json_interface::SpecialKeys::root, tudat::json_interface::SpecialKeys::rootObject, tudat::json_interface::SpecialKeys::up, and valueAt().
Referenced by determineInitialStates(), from_json(), tudat::interpolators::from_json(), tudat::simulation_setup::from_json(), tudat::numerical_integrators::from_json(), tudat::propagators::from_json(), getKeyPath(), and updateBodiesFromJSON().
getAs()
template<typename ValueType > ValueType tudat::json_interface::getAs (const nlohmann::json & jsonObject)
Convert jsonObject to ValueType.
Parameters
jsonObject The json object.
Returns
jsonObject as ValueType.
Exceptions
IllegalValueError<ValueType> If jsonObject is not convertible to ValueType.
IllegalValueError<SubvalueType> If some of the subkeys needed to create the shared pointer of ValueType are not convertible to SubvalueType (only when jsonObject at keyPath is of type object).
Definition at line 294 of file valueAccess.h.
getValue() [2/3]
template<typename ValueType > ValueType tudat::json_interface::getValue (const nlohmann::json & jsonObject, const KeyPath & keyPath, const ValueType & defaultValue)
Get the value of jsonObject at keyPath, or return optionalValue if not defined.
Parameters
jsonObject The json object.
keyPath Key path from which to retrieve the value.
defaultValue The default value to be returned if the key is not defined.
Returns
Value at the requested key path, or optionalValue if not defined.
Exceptions
UndefinedKeyError If some of the subkeys needed to create the shared pointer of ValueType are missing (only when jsonObject at keyPath is of type object).
IllegalValueError<ValueType> If the obtained value for the requested key path is not convertible to ValueType.
IllegalValueError<SubvalueType> If some of the subkeys needed to create the shared pointer of ValueType are not convertible to SubvalueType (only when jsonObject at keyPath is of type object).
Definition at line 314 of file valueAccess.h.
References tudat::json_interface::Keys::Options::defaultValueUsedForMissingKey, getResponseToEvent(), tudat::json_interface::UndefinedKeyError::handleUseOfDefaultValue(), and tudat::json_interface::ValueAccessError::rethrowIfNotTriggeredByMissingValueAt().
getValue() [3/3]
template<typename ValueType > ValueType tudat::json_interface::getValue (const nlohmann::json & jsonObject, const std::vector< KeyPath > & keyPaths)
Get the value of jsonObject at the first defined key path in keyPaths.
Parameters
jsonObject The json object.
keyPaths Vector of key paths from which the value can be retrieved.
Returns
Value at the first defined key path in keyPaths.
Exceptions
UndefinedKeyError If all the key paths in keyPaths are not defined for jsonObject. The printed message will indicate the key path corresponding to the last of keyPaths.
UndefinedKeyError If some of the subkeys needed to create the shared pointer of ValueType are missing (only when jsonObject at keyPaths is of type object).
IllegalValueError<ValueType> If the obtained value for the requested key path is not convertible to ValueType.
IllegalValueError<SubvalueType> If some of the subkeys needed to create the shared pointer of ValueType are not convertible to SubvalueType (only when jsonObject at keyPaths is of type object).
Definition at line 345 of file valueAccess.h.
References tudat::json_interface::ValueAccessError::rethrowIfNotTriggeredByMissingValueAt().
updateFromJSON()
template<typename T > void tudat::json_interface::updateFromJSON (T & value, const nlohmann::json & jsonObject, const KeyPath & keyPath = { })
Set value to be the value of jsonObject at keyPath.
Parameters
value The value to be updated (i.e. re-initialized).
jsonObject The json object.
keyPath Key path from which to retrieve the value.
Exceptions
UndefinedKeyError If the requested key path is not defined.
UndefinedKeyError If some of the subkeys needed to create the shared pointer of ValueType are missing (only when jsonObject at keyPath is of type object).
IllegalValueError<ValueType> If the obtained value for the requested key path is not convertible to ValueType.
IllegalValueError<SubvalueType> If some of the subkeys needed to create the shared pointer of ValueType are not convertible to SubvalueType (only when jsonObject at keyPath is of type object).
Definition at line 383 of file valueAccess.h.
Referenced by from_json(), tudat::simulation_setup::from_json(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetIntegratorSettings(), and tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetPropagatorSettings().
updateFromJSONIfDefined()
template<typename T > void tudat::json_interface::updateFromJSONIfDefined (T & value, const nlohmann::json & jsonObject, const KeyPath & keyPath = { })
Set value to be the value of jsonObject at keyPath if defined.
Remarks
This function does nothing if jsonObject is not defined at keyPath.
Parameters
value The value to be updated (i.e. re-initialized).
jsonObject The json object.
keyPath Key path from which to retrieve the value.
Exceptions
UndefinedKeyError If some of the subkeys needed to create the shared pointer of ValueType are missing (only when jsonObject at keyPath is of type object).
IllegalValueError<ValueType> If the obtained value for the requested key path is not convertible to ValueType.
IllegalValueError<SubvalueType> If some of the subkeys needed to create the shared pointer of ValueType are not convertible to SubvalueType (only when jsonObject at keyPath is of type object).
Definition at line 403 of file valueAccess.h.
Referenced by from_json(), tudat::simulation_setup::from_json(), getCartesianState(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetApplicationOptions(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetExportSettings(), tudat::json_interface::JsonSimulationManager< TimeType, StateScalarType >::resetSpice(), and updateBodySettings().
assignIfNotNaN()
template<typename EquatableType > void tudat::json_interface::assignIfNotNaN (nlohmann::json & jsonObject, const std::string & key, const EquatableType & value)
Assign value to jsonObject[ key ] if value is not NaN.
Remarks
This function does nothing if value is NaN.
The comparison operator must be defined for EquatableType.
Parameters
jsonObject The json object being updated.
key The key of jsonObject being updated.
value The value to be used for updating jsonObject[ key ].
Definition at line 428 of file valueAccess.h.
References isNaN().
Referenced by tudat::simulation_setup::to_json().
assignIfNotnullptr()
template<typename T > void tudat::json_interface::assignIfNotnullptr (nlohmann::json & jsonObject, const std::string & key, const std::shared_ptr< T > & object)
Assign object to jsonObject[ key ] if object is not nullptr.
Remarks
This function does nothing if object is nullptr.
Parameters
jsonObject The json object being updated.
key The key of jsonObject being updated.
object Shared pointer to the object that is being to be used to update jsonObject[ key ].
Definition at line 445 of file valueAccess.h.
Referenced by tudat::simulation_setup::to_json(), and to_json().
assignIfNotEmpty()
template<typename ContainerType > void tudat::json_interface::assignIfNotEmpty (nlohmann::json & jsonObject, const std::string & key, const ContainerType & container)
Assign object to jsonObject[ key ] if container is not empty.
Remarks
This function does nothing if container is empty.
The method empty() must be defined for ContainerType.
Parameters
jsonObject The json object being updated.
key The key of jsonObject being updated.
container Container (e.g. std::vector, std::set, std::map or std::unordered_map) that is being to be used to update jsonObject[ key ].
Definition at line 464 of file valueAccess.h.
Referenced by to_json(), tudat::simulation_setup::to_json(), and tudat::propagators::to_json().
jsonFromMap()
template<template< typename ... > class MapType, typename KeyType , typename ValueType > nlohmann::json tudat::json_interface::jsonFromMap (const MapType< KeyType, ValueType > & map)
Template used by to_json methods for std::unodered_map and std::map. Use of this function outside those methods is discouraged.
Definition at line 32 of file valueConversions.h.
mapFromJson()
template<template< typename ... > class MapType, typename KeyType , typename ValueType > MapType< KeyType, ValueType > tudat::json_interface::mapFromJson (const nlohmann::json & jsonObject)
Template used by from_json methods for std::unodered_map and std::map. Use of this function outside those methods is discouraged.
Definition at line 45 of file valueConversions.h.
References tudat::json_interface::SpecialKeys::all, and contains().
Variable Documentation
stateTypes
std::map< StateType, std::string > tudat::json_interface::stateTypes static
Initial value:
=
{
    { cartesianElements, "cartesian" },
    { keplerianElements, "keplerian" },
    { sphericalElements, "spherical" }
}
Definition at line 38 of file state.h.
Referenced by from_json(), getCartesianState(), and to_json().
unsupportedStateTypes
std::vector< StateType > tudat::json_interface::unsupportedStateTypes = { } static
Definition at line 46 of file state.h.
Referenced by getCartesianState().
exceptionResponseTypes
std::map< ExceptionResponseType, std::string > tudat::json_interface::exceptionResponseTypes static
Initial value:
=
{
    { continueSilently, "continueSilently" },
    { printWarning, "printWarning" },
    { throwError, "throwError" }
}
Definition at line 26 of file options.h.
Referenced by from_json(), and to_json().
pathPlaceholders
std::vector< std::pair< std::string, std::string > > tudat::json_interface::pathPlaceholders static
Initial value:
=
{
    std::make_pair( "TUDAT_ROOT_PATH", input_output::getTudatRootPath( ) ),
    std::make_pair( "ATMOSPHERE_TABLES_PATH", input_output::getAtmosphereTablesPath( ) ),
    std::make_pair( "GRAVITY_MODELS_PATH", input_output::getGravityModelsPath( ) ),
    std::make_pair( "SPICE_KERNELS_PATH", input_output::getSpiceKernelPath( ) )
}
Names for replacable paths in JSON files. E.g., the text "${TUDAT_ROOT_PATH}" will be replaced with the actual path when reading JSON files.
Definition at line 27 of file path.h.
Referenced by pathAddingPlaceholders(), and pathRemovingPlaceholders().
accessedKeyPaths
std::set< KeyPath > tudat::json_interface::accessedKeyPaths = { }
Global variable containing all the key paths that were accessed since clearAccessHistory() was called for the last time (or since this variable was initialized).
Definition at line 129 of file valueAccess.cpp.
Referenced by checkUnusedKeys(), clearAccessHistory(), and getValue().