Tudat: tudat::acceleration_partials::AccelerationPartial Class Reference
tudat::acceleration_partials::AccelerationPartial Class Reference abstract
Base class for objects calculating partial derivatives of accelerations w.r.t. states, model parameters.
#include <accelerationPartial.h>
Public Member Functions
AccelerationPartial (const std::string &acceleratedBody, const std::string &acceleratingBody, const basic_astrodynamics::AvailableAcceleration accelerationType)
Base class constructor.
virtual ~AccelerationPartial ()
Virtual destructor.
std::string getAcceleratedBody ()
Function to retrieve the name of the body undergoing acceleration.
std::string getAcceleratingBody ()
Function to retrieve the name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration getAccelerationType ()
Function to retrieve the type of acceleration w.r.t. which partial is taken..
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
virtual bool isAccelerationPartialWrtAdditionalBodyNonnullptr (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the translational state of a third body is non-zero.
virtual bool isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the acceleration is dependent on a non-translational integrated state (default none).
bool isStateDerivativeDependentOnIntegratedState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to check whether a partial w.r.t. some integrated state is non-zero.
virtual void wrtNonTranslationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the acceleration w.r.t. a non-translational integrated state.
virtual void wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)=0
Pure virtual function for calculating the partial of the acceleration w.r.t. the position of the accelerated body.
virtual void wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)=0
Pure virtual function for calculating the partial of the acceleration w.r.t. the position of the body exerting acceleration.
virtual void wrtPositionOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of the third body.
void wrtStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body undergoing acceleration.
void wrtStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body exerting acceleration.
void wrtStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the third body.
virtual void wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the accelerated body.
virtual void wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the body exerting acceleration.
virtual void wrtVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
virtual std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to retrieve the function that computes (by reference) a given double parameter partial.
virtual std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to retrieve the function that computes (by reference) a given vector parameter partial.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
virtual void update (const double currentTime)=0
Pure virtual for updating the common parts of the partial object to current state and time.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Protected Attributes
std::string acceleratedBody_
Name of the body undergoing acceleration.
std::string acceleratingBody_
Name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration accelerationType_
Type of acceleration w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Additional Inherited Members
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Detailed Description
Base class for objects calculating partial derivatives of accelerations w.r.t. states, model parameters. Such calculations are used in orbit determination, for the computation of the state transition; sensitivity matrices. Derived classes implement derivative-calculating models for specific acceleration models, so that the calculation of all partials of a single type acceleration model is encompassed in a single derived class.
Definition at line 39 of file accelerationPartial.h.
Constructor & Destructor Documentation
AccelerationPartial()
tudat::acceleration_partials::AccelerationPartial::AccelerationPartial (const std::string & acceleratedBody, const std::string & acceleratingBody, const basic_astrodynamics::AvailableAcceleration accelerationType) inline
Constructor of base class, sets the base class member variables identifying the body undergoing and exerting the acceleration.
Parameters
acceleratedBody Body undergoing acceleration.
acceleratingBody Body exerting acceleration.
accelerationType Type of acceleration w.r.t. which partial is taken.
Definition at line 51 of file accelerationPartial.h.
~AccelerationPartial()
virtual tudat::acceleration_partials::AccelerationPartial::~AccelerationPartial () inline virtual
Definition at line 57 of file accelerationPartial.h.
Member Function Documentation
getDerivativeFunctionWrtStateOfIntegratedBody()
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > tudat::acceleration_partials::AccelerationPartial::getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline virtual
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
Parameters
stateReferencePoint Reference point (id) for propagated state (i.e. body name for translational dynamics).
integratedStateType Type of propagated state.
Returns
Pair with function, returning partial derivative, and number of columns in partial vector,
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 67 of file accelerationPartial.h.
References acceleratedBody_, acceleratingBody_, tudat::propagators::body_mass_state, tudat::propagators::custom_state, isAccelerationPartialWrtAdditionalBodyNonnullptr(), isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::propagators::translational_state, wrtNonTranslationalStateOfAdditionalBody(), wrtStateOfAcceleratedBody(), wrtStateOfAcceleratingBody(), and wrtStateOfAdditionalBody().
isStateDerivativeDependentOnIntegratedNonTranslationalState()
virtual bool tudat::acceleration_partials::AccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline virtual
Function for determining if the acceleration is dependent on a non-translational integrated state. No dependency is implemented is returned in this base class function, but may be overriden by derived class.
Parameters
stateReferencePoint Reference point id of propagated state
integratedStateType Type of propagated state for which dependency is to be determined.
Returns
True if dependency exists (non-zero partial), false otherwise.
Implements tudat::orbit_determination::StateDerivativePartial.
Reimplemented in tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::AerodynamicAccelerationPartial, tudat::acceleration_partials::CannonBallRadiationPressurePartial, and tudat::acceleration_partials::CentralGravitationPartial.
Definition at line 138 of file accelerationPartial.h.
Referenced by getDerivativeFunctionWrtStateOfIntegratedBody(), and isStateDerivativeDependentOnIntegratedState().
isStateDerivativeDependentOnIntegratedState()
bool tudat::acceleration_partials::AccelerationPartial::isStateDerivativeDependentOnIntegratedState (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline
Function to check whether a partial w.r.t. some integrated state is non-zero.
Parameters
stateReferencePoint Reference point (id) for propagated state (i.e. body name for translational dynamics).
integratedStateType Type of propagated state.
Returns
True if dependency exists, false otherwise.
Definition at line 152 of file accelerationPartial.h.
References acceleratedBody_, acceleratingBody_, isAccelerationPartialWrtAdditionalBodyNonnullptr(), isStateDerivativeDependentOnIntegratedNonTranslationalState(), and tudat::propagators::translational_state.
wrtPositionOfAcceleratedBody()
virtual void tudat::acceleration_partials::AccelerationPartial::wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) pure virtual
Pure virtual function for calculating the partial of the acceleration w.r.t. the position of the accelerated body and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implemented in tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::CentralGravitationPartial, tudat::acceleration_partials::CannonBallRadiationPressurePartial, tudat::acceleration_partials::SphericalHarmonicsGravityPartial, tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial, tudat::acceleration_partials::AerodynamicAccelerationPartial, and tudat::acceleration_partials::EmpiricalAccelerationPartial.
Referenced by wrtStateOfAcceleratedBody().
wrtVelocityOfAcceleratedBody()
virtual void tudat::acceleration_partials::AccelerationPartial::wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 3) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of the accelerated body and adding it to the existing partial block. Function may be overridden in derived class, default dependency is none.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian velocity of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented in tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::EmpiricalAccelerationPartial, and tudat::acceleration_partials::AerodynamicAccelerationPartial.
Definition at line 208 of file accelerationPartial.h.
Referenced by wrtStateOfAcceleratedBody().
wrtStateOfAcceleratedBody()
void tudat::acceleration_partials::AccelerationPartial::wrtStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix) inline
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body undergoing acceleration and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian state of body undergoing acceleration where current partial is to be added.
Definition at line 220 of file accelerationPartial.h.
References wrtPositionOfAcceleratedBody(), and wrtVelocityOfAcceleratedBody().
Referenced by getDerivativeFunctionWrtStateOfIntegratedBody().
wrtPositionOfAcceleratingBody()
virtual void tudat::acceleration_partials::AccelerationPartial::wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) pure virtual
Pure virtual function for calculating the partial of the acceleration w.r.t. the position of the body exerting acceleration and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implemented in tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::AerodynamicAccelerationPartial, tudat::acceleration_partials::CentralGravitationPartial, tudat::acceleration_partials::CannonBallRadiationPressurePartial, tudat::acceleration_partials::SphericalHarmonicsGravityPartial, tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial, and tudat::acceleration_partials::EmpiricalAccelerationPartial.
Referenced by wrtStateOfAcceleratingBody().
wrtVelocityOfAcceleratingBody()
virtual void tudat::acceleration_partials::AccelerationPartial::wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 3) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of the body exerting a acceleration. . Function may be overridden in derived class, default dependency is none.
Parameters
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian velocity of body exerting acceleration where current partial is to be added.
Reimplemented in tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::AerodynamicAccelerationPartial, and tudat::acceleration_partials::EmpiricalAccelerationPartial.
Definition at line 250 of file accelerationPartial.h.
Referenced by wrtStateOfAcceleratingBody().
wrtStateOfAcceleratingBody()
void tudat::acceleration_partials::AccelerationPartial::wrtStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix) inline
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body exerting acceleration and adding it to the existing partial block.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian state of body exerting acceleration where current partial is to be added.
Definition at line 261 of file accelerationPartial.h.
References wrtPositionOfAcceleratingBody(), and wrtVelocityOfAcceleratingBody().
Referenced by getDerivativeFunctionWrtStateOfIntegratedBody().
wrtPositionOfAdditionalBody()
virtual void tudat::acceleration_partials::AccelerationPartial::wrtPositionOfAdditionalBody (const std::string & bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of the third body and adding it to the existing partial block. Function may be overridden in derived class, default dependency is none.
Parameters
bodyName Name of third body.
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of third body where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >.
Definition at line 278 of file accelerationPartial.h.
Referenced by wrtStateOfAdditionalBody().
wrtVelocityOfAdditionalBody()
virtual void tudat::acceleration_partials::AccelerationPartial::wrtVelocityOfAdditionalBody (const std::string & bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 3) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of the third body and adding it to the existing partial block. . Function may be overridden in derived class, default dependency is none.
Parameters
bodyName Name of third body.
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian velocity of third body where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >.
Definition at line 294 of file accelerationPartial.h.
Referenced by wrtStateOfAdditionalBody().
wrtStateOfAdditionalBody()
void tudat::acceleration_partials::AccelerationPartial::wrtStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string & bodyName) inline
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the third body and adding it to the existing partial block.
Parameters
bodyName Name of third body.
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian state of third body where current partial is to be added.
Definition at line 306 of file accelerationPartial.h.
References wrtPositionOfAdditionalBody(), and wrtVelocityOfAdditionalBody().
Referenced by getDerivativeFunctionWrtStateOfIntegratedBody().
wrtNonTranslationalStateOfAdditionalBody()
virtual void tudat::acceleration_partials::AccelerationPartial::wrtNonTranslationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline virtual
Function for calculating the partial of the acceleration w.r.t. a non-translational integrated state and adding it to the existing partial block. Function may be overridden in derived class, default dependency is none.
Parameters
partialMatrix Block of partial derivatives of where current partial is to be added.
stateReferencePoint Reference point id of propagated state
integratedStateType Type of propagated state for which partial is to be computed.
Reimplemented in tudat::acceleration_partials::CannonBallRadiationPressurePartial.
Definition at line 321 of file accelerationPartial.h.
Referenced by getDerivativeFunctionWrtStateOfIntegratedBody().
isAccelerationPartialWrtAdditionalBodyNonnullptr()
virtual bool tudat::acceleration_partials::AccelerationPartial::isAccelerationPartialWrtAdditionalBodyNonnullptr (const std::string & bodyName) inline virtual
Function to check whether the partial derivative w.r.t. the translational state of a third body is non-zero. This function returns false by default, should be redefined in derived class if any third-bodyd dependencies exist.
Parameters
bodyName Name of third body.
Returns
True if third body dependency exists, false otherwise.
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >.
Definition at line 333 of file accelerationPartial.h.
Referenced by getDerivativeFunctionWrtStateOfIntegratedBody(), and isStateDerivativeDependentOnIntegratedState().
getAcceleratedBody()
std::string tudat::acceleration_partials::AccelerationPartial::getAcceleratedBody () inline
Function to retrieve the name of the body undergoing acceleration.
Returns
Name of the body undergoing acceleration.
Definition at line 343 of file accelerationPartial.h.
References acceleratedBody_.
getAcceleratingBody()
std::string tudat::acceleration_partials::AccelerationPartial::getAcceleratingBody () inline
Function to retrieve the name of the body exerting acceleration.
Returns
Name of the body exerting acceleration.
Definition at line 350 of file accelerationPartial.h.
References acceleratingBody_.
getAccelerationType()
basic_astrodynamics::AvailableAcceleration tudat::acceleration_partials::AccelerationPartial::getAccelerationType () inline
Function to retrieve the type of acceleration w.r.t. which partial is taken..
Returns
Type of acceleration w.r.t. which partial is taken..
Definition at line 357 of file accelerationPartial.h.
References accelerationType_.
Member Data Documentation
acceleratedBody_
std::string tudat::acceleration_partials::AccelerationPartial::acceleratedBody_ protected
Definition at line 364 of file accelerationPartial.h.
Referenced by getAcceleratedBody(), getDerivativeFunctionWrtStateOfIntegratedBody(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getGravitationalParameterPartialFunction(), tudat::acceleration_partials::CentralGravitationPartial::getGravitationalParameterPartialFunction(), tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::getGravitationalParameterPartialFunction(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::getParameterPartialFunction(), tudat::acceleration_partials::CannonBallRadiationPressurePartial::getParameterPartialFunction(), tudat::acceleration_partials::AerodynamicAccelerationPartial::getParameterPartialFunction(), tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::getParameterPartialFunction(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::CentralGravitationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::CannonBallRadiationPressurePartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::AerodynamicAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::RelativisticAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), isStateDerivativeDependentOnIntegratedState(), tudat::acceleration_partials::CannonBallRadiationPressurePartial::wrtNonTranslationalStateOfAdditionalBody(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::wrtPositionOfAcceleratedBody(), and tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::wrtVelocityOfAcceleratedBody().
acceleratingBody_
std::string tudat::acceleration_partials::AccelerationPartial::acceleratingBody_ protected
Definition at line 367 of file accelerationPartial.h.
Referenced by getAcceleratingBody(), getDerivativeFunctionWrtStateOfIntegratedBody(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getGravitationalParameterPartialFunction(), tudat::acceleration_partials::CentralGravitationPartial::getGravitationalParameterPartialFunction(), tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::getGravitationalParameterPartialFunction(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::getParameterPartialFunction(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction(), tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::getParameterPartialFunction(), tudat::acceleration_partials::RelativisticAccelerationPartial::getParameterPartialFunction(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::CentralGravitationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::AerodynamicAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), tudat::acceleration_partials::RelativisticAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState(), and isStateDerivativeDependentOnIntegratedState().
accelerationType_
basic_astrodynamics::AvailableAcceleration tudat::acceleration_partials::AccelerationPartial::accelerationType_ protected
Definition at line 370 of file accelerationPartial.h.
Referenced by getAccelerationType().
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/AccelerationPartials/accelerationPartial.h