Tudat: tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface Class Reference
tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface Class Reference abstract
Base class for interface object of interpolation of numerically propagated state transition and sensitivity matrices.
#include <stateTransitionMatrixInterface.h>
Public Member Functions
CombinedStateTransitionAndSensitivityMatrixInterface (const int numberOfInitialDynamicalParameters, const int numberOfParameters)
Constructor.
virtual ~CombinedStateTransitionAndSensitivityMatrixInterface ()
Destructor.
virtual Eigen::MatrixXd getCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime)=0
Function to get the concatenated state transition and sensitivity matrix at a given time.
virtual Eigen::MatrixXd getFullCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime)=0
Function to get the concatenated state transition and sensitivity matrix at a given time, which includes zero values for parameters not active in current arc.
virtual int getFullParameterVectorSize ()=0
Function to get the size of the total parameter vector.
int getSensitivityMatrixSize ()
Function to get the number of columns of sensitivity matrix.
int getStateTransitionMatrixSize ()
Function to get the size of state transition matrix.
Protected Attributes
int sensitivityMatrixSize_
Number of columns of sensitivity matrix.
int stateTransitionMatrixSize_
Size of state transition matrix.
Detailed Description
Base class for interface object of interpolation of numerically propagated state transition and sensitivity matrices. Derived classes implement the case of single-arc/multi-arc/combined dynamics.
Definition at line 33 of file stateTransitionMatrixInterface.h.
Constructor & Destructor Documentation
tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::CombinedStateTransitionAndSensitivityMatrixInterface (const int numberOfInitialDynamicalParameters, const int numberOfParameters) inline
Constructor
Parameters
numberOfInitialDynamicalParameters Size of the estimated initial state vector (and size of square state transition matrix.
numberOfParameters Total number of estimated parameters (initial states and other parameters).
Definition at line 44 of file stateTransitionMatrixInterface.h.
References sensitivityMatrixSize_, and stateTransitionMatrixSize_.
virtual tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::~CombinedStateTransitionAndSensitivityMatrixInterface () inline virtual
Definition at line 53 of file stateTransitionMatrixInterface.h.
References getCombinedStateTransitionAndSensitivityMatrix(), and getFullCombinedStateTransitionAndSensitivityMatrix().
Member Function Documentation
virtual Eigen::MatrixXd tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::getCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime) pure virtual
Function to get the concatenated state transition and sensitivity matrix at a given time.
Parameters
evaluationTime Time at which to evaluate matrix interpolators
Returns
Concatenated state transition and sensitivity matrices.
Implemented in tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface, and tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface.
Referenced by tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullParameterVectorSize(), tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface::getSensitivityMatrixInterpolator(), and ~CombinedStateTransitionAndSensitivityMatrixInterface().
virtual Eigen::MatrixXd tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::getFullCombinedStateTransitionAndSensitivityMatrix (const double evaluationTime) pure virtual
Function to get the concatenated state transition and sensitivity matrix at a given time, which includes zero values for parameters not active in current arc.
Parameters
evaluationTime Time at which to evaluate matrix interpolators
Returns
Concatenated state transition and sensitivity matrices, including inactive parameters at evaluationTime.
Implemented in tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface, and tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface.
Referenced by tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullParameterVectorSize(), and ~CombinedStateTransitionAndSensitivityMatrixInterface().
int tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::getStateTransitionMatrixSize () inline
Function to get the size of state transition matrix
Returns
Size of state transition matrix
Definition at line 79 of file stateTransitionMatrixInterface.h.
References stateTransitionMatrixSize_.
int tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::getSensitivityMatrixSize () inline
Function to get the number of columns of sensitivity matrix.
Returns
Number of columns of sensitivity matrix.
Definition at line 89 of file stateTransitionMatrixInterface.h.
References getFullParameterVectorSize(), and sensitivityMatrixSize_.
virtual int tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::getFullParameterVectorSize () pure virtual
Function to get the size of the total parameter vector (both global and all local parameters).
Returns
Size of the total parameter vector.
Implemented in tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface, and tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface.
Referenced by getSensitivityMatrixSize().
Member Data Documentation
int tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::stateTransitionMatrixSize_ protected
Definition at line 104 of file stateTransitionMatrixInterface.h.
Referenced by CombinedStateTransitionAndSensitivityMatrixInterface(), tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface::getCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullParameterVectorSize(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullParameterVectorSize(), getStateTransitionMatrixSize(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface(), and tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface().
int tudat::propagators::CombinedStateTransitionAndSensitivityMatrixInterface::sensitivityMatrixSize_ protected
Definition at line 107 of file stateTransitionMatrixInterface.h.
Referenced by CombinedStateTransitionAndSensitivityMatrixInterface(), tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface::getCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullCombinedStateTransitionAndSensitivityMatrix(), tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullParameterVectorSize(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::getFullParameterVectorSize(), getSensitivityMatrixSize(), tudat::propagators::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface::MultiArcCombinedStateTransitionAndSensitivityMatrixInterface(), and tudat::propagators::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface::SingleArcCombinedStateTransitionAndSensitivityMatrixInterface().
The documentation for this class was generated from the following file:
Astrodynamics/Propagators/stateTransitionMatrixInterface.h