Tudat: tudat::propagators::SingleVariableLimitPropagationTerminationCondition Class Reference
tudat::propagators::SingleVariableLimitPropagationTerminationCondition Class Reference
Class for stopping the propagation when a dependent variable reaches a given value (either upper or lower bound)
#include <propagationTermination.h>
Public Member Functions
SingleVariableLimitPropagationTerminationCondition (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings, const std::function< double() > variableRetrievalFuntion, const double limitingValue, const bool useAsLowerBound, const bool terminateExactlyOnFinalCondition=false, const std::shared_ptr< root_finders::RootFinderSettings > terminationRootFinderSettings=nullptr)
Constructor.
~SingleVariableLimitPropagationTerminationCondition ()
Destructor.
bool checkStopCondition (const double time, const double cpuTime)
Function to check whether the propagation is to be be stopped.
double getStopConditionError ()
Function to return current difference between termination variable, and the value at which the propagation must terminate.
std::shared_ptr< root_finders::RootFinderSettings > getTerminationRootFinderSettings ()
Function to retrieve settings to create root finder used to converge on exact final condition.
Public Member Functions inherited from tudat::propagators::PropagationTerminationCondition
PropagationTerminationCondition (const PropagationTerminationTypes terminationType, const bool terminateExactlyOnFinalCondition=false)
Constructor.
virtual ~PropagationTerminationCondition ()
Destructor.
bool getTerminateExactlyOnFinalCondition ()
Function to retrieve boolean to denote whether the propagation is to terminate exactly on the final condition.
virtual PropagationTerminationTypes getTerminationType ()
Function to retrieve type of termination condition.
Private Attributes
std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings_
Settings for dependent variable that is to be checked.
double limitingValue_
Value at which the propagation is to be stopped.
std::shared_ptr< root_finders::RootFinderSettings > terminationRootFinderSettings_
Settings to create root finder used to converge on exact final condition.
bool useAsLowerBound_
std::function< double() > variableRetrievalFunction_
Function returning the dependent variable.
Additional Inherited Members
Protected Attributes inherited from tudat::propagators::PropagationTerminationCondition
bool terminateExactlyOnFinalCondition_
PropagationTerminationTypes terminationType_
Type of termination condition.
Detailed Description
Definition at line 186 of file propagationTermination.h.
Constructor & Destructor Documentation
SingleVariableLimitPropagationTerminationCondition()
tudat::propagators::SingleVariableLimitPropagationTerminationCondition::SingleVariableLimitPropagationTerminationCondition (const std::shared_ptr< SingleDependentVariableSaveSettings > dependentVariableSettings, const std::function< double() > variableRetrievalFuntion, const double limitingValue, const bool useAsLowerBound, const bool terminateExactlyOnFinalCondition = false, const std::shared_ptr< root_finders::RootFinderSettings > terminationRootFinderSettings = nullptr) inline
Constructor
Parameters
dependentVariableSettings Settings for dependent variable that is to be checked
variableRetrievalFuntion Function returning the dependent variable.
limitingValue Value at which the propagation is to be stopped
useAsLowerBound Boolean denoting whether the propagation should stop if the dependent variable goes below (if true) or above (if false) limitingValue
terminateExactlyOnFinalCondition Boolean to denote whether the propagation is to terminate exactly on the final condition, or whether it is to terminate on the first step where it is violated.
terminationRootFinderSettings Settings to create root finder used to converge on exact final condition.
Definition at line 202 of file propagationTermination.h.
References tudat::root_finders::doesRootFinderRequireDerivatives().
~SingleVariableLimitPropagationTerminationCondition()
tudat::propagators::SingleVariableLimitPropagationTerminationCondition::~SingleVariableLimitPropagationTerminationCondition () inline
Definition at line 228 of file propagationTermination.h.
Member Function Documentation
checkStopCondition()
bool tudat::propagators::SingleVariableLimitPropagationTerminationCondition::checkStopCondition (const double time, const double cpuTime) virtual
Function to check whether the propagation is to be be stopped, i.e. whether the given dependent variable has been reached or not.
Parameters
time Current time in propagation
cpuTime Current CPU time in propagation
Returns
True if propagation is to be stopped, false otherwise.
Implements tudat::propagators::PropagationTerminationCondition.
Definition at line 43 of file propagationTermination.cpp.
References limitingValue_, useAsLowerBound_, and variableRetrievalFunction_.
getStopConditionError()
double tudat::propagators::SingleVariableLimitPropagationTerminationCondition::getStopConditionError () inline
Function to return current difference between termination variable, and the value at which the propagation must terminate
Returns
Current difference between termination variable, and the value at which the propagation must terminate
Definition at line 245 of file propagationTermination.h.
References limitingValue_, and variableRetrievalFunction_.
getTerminationRootFinderSettings()
std::shared_ptr< root_finders::RootFinderSettings > tudat::propagators::SingleVariableLimitPropagationTerminationCondition::getTerminationRootFinderSettings () inline
Function to retrieve settings to create root finder used to converge on exact final condition.
Returns
Settings to create root finder used to converge on exact final condition.
Definition at line 255 of file propagationTermination.h.
References terminationRootFinderSettings_.
Member Data Documentation
dependentVariableSettings_
std::shared_ptr< SingleDependentVariableSaveSettings > tudat::propagators::SingleVariableLimitPropagationTerminationCondition::dependentVariableSettings_ private
Definition at line 263 of file propagationTermination.h.
variableRetrievalFunction_
std::function< double() > tudat::propagators::SingleVariableLimitPropagationTerminationCondition::variableRetrievalFunction_ private
Definition at line 266 of file propagationTermination.h.
Referenced by checkStopCondition(), and getStopConditionError().
limitingValue_
double tudat::propagators::SingleVariableLimitPropagationTerminationCondition::limitingValue_ private
Definition at line 269 of file propagationTermination.h.
Referenced by checkStopCondition(), and getStopConditionError().
useAsLowerBound_
bool tudat::propagators::SingleVariableLimitPropagationTerminationCondition::useAsLowerBound_ private
Boolean denoting whether the propagation should stop if the dependent variable goes below (if true) or above (if false) limitingValue
Definition at line 273 of file propagationTermination.h.
Referenced by checkStopCondition().
terminationRootFinderSettings_
std::shared_ptr< root_finders::RootFinderSettings > tudat::propagators::SingleVariableLimitPropagationTerminationCondition::terminationRootFinderSettings_ private
Definition at line 276 of file propagationTermination.h.
Referenced by getTerminationRootFinderSettings().
The documentation for this class was generated from the following files:
SimulationSetup/PropagationSetup/propagationTermination.h
SimulationSetup/PropagationSetup/propagationTermination.cpp