Tudat: tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions > Class Template Reference
tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions > Class Template Reference
Class for performing multi-linear interpolation for arbitrary number of independent variables.
#include <multiLinearInterpolator.h>
Public Member Functions
MultiLinearInterpolator (const std::vector< std::vector< IndependentVariableType > > independentValues, const boost::multi_array< DependentVariableType, static_cast< size_t >(NumberOfDimensions)> dependentData, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm)
Constructor taking independent and dependent variable data.
~MultiLinearInterpolator ()
Default destructor.
int getNumberOfDimensions ()
Function to return the number of independent variables of the interpolation.
DependentVariableType interpolate (const std::vector< IndependentVariableType > &independentValuesToInterpolate)
Function to perform interpolation.
Public Member Functions inherited from tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >
virtual ~Interpolator ()
Destructor.
Private Member Functions
void makeLookupSchemes (const AvailableLookupScheme selectedScheme)
Make the lookup scheme that is to be used.
DependentVariableType performRecursiveInterpolationStep (const unsigned int currentVariable, const std::vector< IndependentVariableType > &independentValuesToInterpolate, boost::array< int, NumberOfDimensions > currentArrayIndices, const std::vector< int > &nearestLowerIndices)
Perform the step in a single dimension of the interpolation process.
Private Attributes
boost::multi_array< DependentVariableType, static_cast< size_t > NumberOfDimensions)> dependentData_
Multi-dimensional array of dependent data.
std::vector< std::vector< IndependentVariableType > > independentValues_
Vector of vectors containing independent variables.
std::vector< boost::shared_ptr< LookUpScheme< IndependentVariableType > > > lookUpSchemes_
Vector with pointers to look-up scheme.
Detailed Description
template<typename IndependentVariableType, typename DependentVariableType, int NumberOfDimensions>
class tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >
Class for performing multi-linear interpolation for arbitrary number of independent variables. Interpolation is calculated recursively over all dimensions of independent variables. Note that the types (i.e. double, float) of all independent variables must be the same.
Template Parameters
IndependentVariableType Type for independent variables.
DependentVariableType Type for dependent variable.
NumberOfDimensions Number of independent variables.
Definition at line 58 of file multiLinearInterpolator.h.
Constructor & Destructor Documentation
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::MultiLinearInterpolator (const std::vector< std::vector< IndependentVariableType > > independentValues, const boost::multi_array< DependentVariableType, static_cast< size_t >(NumberOfDimensions)> dependentData, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm) inline
Parameters
independentValues Vector of vectors containing data points of independent variables, each must be sorted in ascending order.
dependentData Multi-dimensional array of dependent data at each point of hyper-rectangular grid formed by independent variable points.
selectedLookupScheme Identifier of lookupscheme from enum. This algorithm is used to find the nearest lower data point in the independent variables when requesting interpolation.
Definition at line 73 of file multiLinearInterpolator.h.
References tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::makeLookupSchemes().
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::~MultiLinearInterpolator () inline
Default destructor
Definition at line 105 of file multiLinearInterpolator.h.
Member Function Documentation
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> DependentVariableType tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::interpolate (const std::vector< IndependentVariableType > & independentValuesToInterpolate) inline virtual
This function performs the multilinear interpolation.
Parameters
independentValuesToInterpolate Vector of values of independent variables at which the value of the dependent variable is to be determined.
Returns
Interpolated value of dependent variable in all dimensions.
Implements tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >.
Definition at line 114 of file multiLinearInterpolator.h.
References tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::lookUpSchemes_, and tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::performRecursiveInterpolationStep().
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> int tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::getNumberOfDimensions () inline virtual
Function to return the number of independent variables of the interpolation, i.e. size that the vector used as input for Interpolator::interpolate should be.
Returns
Number of independent variables of the interpolation.
Implements tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >.
Definition at line 146 of file multiLinearInterpolator.h.
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> void tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::makeLookupSchemes (const AvailableLookupScheme selectedScheme) inline private
This function creates the look up scheme that is to be used in determining the interval of the independent variable grid where the interpolation is to be performed. It takes the type of lookup scheme as an enum and constructs the lookup scheme from the independentValues_ that have been set previously.
Parameters
selectedScheme Type of look-up scheme that is to be used
Definition at line 162 of file multiLinearInterpolator.h.
References tudat::interpolators::binarySearch, tudat::interpolators::huntingAlgorithm, tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::independentValues_, and tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::lookUpSchemes_.
Referenced by tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::MultiLinearInterpolator().
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> DependentVariableType tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::performRecursiveInterpolationStep (const unsigned int currentVariable, const std::vector< IndependentVariableType > & independentValuesToInterpolate, boost::array< int, NumberOfDimensions > currentArrayIndices, const std::vector< int > & nearestLowerIndices) inline private
Function calculates single dimension of the interpolation process. Function calls itself if final dimension not yet reached. Calling this function with currentVariable = 0 will result in 2^{NumberOfDimensions} number of calls to the function at currentVariable = NumberOfDimensions -1. As such, the complete series of calls, starting at currentVariable = 0, retrieves the dependent variable values at all edges of the grid hyper-rectangle and properly scales them.
Parameters
currentVariable Dimension in which this interpolation step is to be performed.
independentValuesToInterpolate Vector of values of independent variables at which interpolation is to be performed.
currentArrayIndices Array of indices modified at index = currentVariable at each call of function. Variable is passed to dependentData in highest step to return data for interpolation.
nearestLowerIndices Indices in subvectors of independentValues_ vector. That is, the n-th entry of nearestLowerIndices represent the nearest lower neighbour in the n-th interpolation dimension of the independent variable vectors.
Returns
Interpolated value in a single dimension
Definition at line 217 of file multiLinearInterpolator.h.
References tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::dependentData_, and tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::independentValues_.
Referenced by tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::interpolate().
Member Data Documentation
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> std::vector< boost::shared_ptr< LookUpScheme< IndependentVariableType > > > tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::lookUpSchemes_ private
Pointers to the look-up schemes that is used to determine in which interval the requested independent variable value falls.
Definition at line 278 of file multiLinearInterpolator.h.
Referenced by tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::interpolate(), and tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::makeLookupSchemes().
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> std::vector< std::vector< IndependentVariableType > > tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::independentValues_ private
Vector of vectors containing independent variables. The size of the outer vector is equal to the number of dimensions of the interpolator.
Definition at line 285 of file multiLinearInterpolator.h.
Referenced by tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::makeLookupSchemes(), and tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::performRecursiveInterpolationStep().
template<typename IndependentVariableType , typename DependentVariableType , int NumberOfDimensions> boost::multi_array< DependentVariableType, static_cast< size_t > NumberOfDimensions)> tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::dependentData_ private
Multi-dimensional array of dependent data at each point of hyper-rectangular grid formed by independent variable points.
Definition at line 292 of file multiLinearInterpolator.h.
Referenced by tudat::interpolators::MultiLinearInterpolator< IndependentVariableType, DependentVariableType, NumberOfDimensions >::performRecursiveInterpolationStep().
The documentation for this class was generated from the following file:
Mathematics/Interpolators/multiLinearInterpolator.h