Tudat: tudat::orbit_determination Namespace Reference
tudat::orbit_determination Namespace Reference
Classes
class StateDerivativePartial
Base class for computing the partial derivatives of a state derivative model.
class TidalLoveNumberPartialInterface
(Base) class for calculating the partial of a spherical harmonic acceleration w.r.t. a tidal love number.
Typedefs
typedef std::vector< std::vector< std::shared_ptr< orbit_determination::StateDerivativePartial > > > StateDerivativePartialsMap
Typedef for double vector of StateDerivativePartial objects.
Functions
std::pair< std::function< void(Eigen::MatrixXd &) >, int > createMergedParameterPartialFunction (const std::pair< std::function< void(Eigen::MatrixXd &) >, int > &partialFunctionOfAccelerationToAdd, const std::pair< std::function< void(Eigen::MatrixXd &) >, int > &partialFunctionOfAccelerationToSubtract)
Create a parameter partial function obtained from the subtraction of two such function results.
void evaluateAddedParameterPartialFunction (const std::function< void(Eigen::MatrixXd &) > firstParameterPartialFunction, const std::function< void(Eigen::MatrixXd &) > parameterPartialFunctionToAdd, Eigen::MatrixXd &partial)
Function to evaluate the addition of two parameter partials.
void evaluateNegativeParameterPartialFunction (const std::function< void(Eigen::MatrixXd &) > parameterPartialFunction, Eigen::MatrixXd &partial)
Function to evaluate the negative value of a parameter partial.
void evaluateSubtractedParameterPartialFunction (const std::function< void(Eigen::MatrixXd &) > firstParameterPartialFunction, const std::function< void(Eigen::MatrixXd &) > parameterPartialFunctionToSubtract, Eigen::MatrixXd &partial)
Function to evaluate the subtraction of two parameter partials.
std::function< void(Eigen::MatrixXd &) > getCombinedCurrentDoubleParameterFunction (const std::shared_ptr< StateDerivativePartial > firstPartial, const std::shared_ptr< StateDerivativePartial > secondPartial, const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameterObject, const int firstPartialSize, const int secondPartialSize, const bool subtractPartials)
std::function< void(Eigen::MatrixXd &) > getCombinedCurrentVectorParameterFunction (const std::shared_ptr< StateDerivativePartial > firstPartial, const std::shared_ptr< StateDerivativePartial > secondPartial, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterObject, const int firstPartialSize, const int secondPartialSize, const bool subtractPartials)
void getMaximumUsedDegreeAndOrder (const int maximumDegree, const int maximumOrder, const int evaluationDegree, int &maximumUsedDegree, int &maximumUsedOrder)
Variables
std::pair< std::function< void(Eigen::MatrixXd &) >, int > createMergedParameterPartialFunction (const std::pair< std::function< void(Eigen::MatrixXd &) >, int > &partialFunctionOfAccelerationToAdd, const std::pair< std::function< void(Eigen::MatrixXd &) >, int > &partialFunctionOfAccelerationToSubtract)
Create a parameter partial function obtained from the subtraction of two such function results.
std::function< void(Eigen::MatrixXd &) > getCombinedCurrentDoubleParameterFunction (const std::shared_ptr< StateDerivativePartial > firstPartial, const std::shared_ptr< StateDerivativePartial > secondPartial, const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameterObject, const int firstPartialSize, const int secondPartialSize, const bool subtractPartials=0)
Function to create a parameter partial evaluation function, obtained by adding or subtracting a given partial w.r.t.
std::function< void(Eigen::MatrixXd &) > getCombinedCurrentVectorParameterFunction (const std::shared_ptr< StateDerivativePartial > firstPartial, const std::shared_ptr< StateDerivativePartial > secondPartial, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterObject, const int firstPartialSize, const int secondPartialSize, const bool subtractPartials=0)
Function to create a parameter partial evaluation function, obtained by adding or subtracting a given partial w.r.t.
Typedef Documentation
StateDerivativePartialsMap
typedef std::vector< std::vector< std::shared_ptr< orbit_determination::StateDerivativePartial > > > tudat::orbit_determination::StateDerivativePartialsMap
Typedef for double vector of StateDerivativePartial objects. First (outer) vector is typically the bodies undergoing 'acceleration (and being estimated), the second (inner) vector is the list of partials being exerted on a single body.
Definition at line 533 of file stateDerivativePartial.h.
Function Documentation
getMaximumUsedDegreeAndOrder()
void tudat::orbit_determination::getMaximumUsedDegreeAndOrder (const int maximumDegree, const int maximumOrder, const int evaluationDegree, int & maximumUsedDegree, int & maximumUsedOrder)
Definition at line 23 of file tidalLoveNumberPartialInterface.cpp.
Referenced by tudat::orbit_determination::TidalLoveNumberPartialInterface::setParameterPartialFunction().
evaluateNegativeParameterPartialFunction()
void tudat::orbit_determination::evaluateNegativeParameterPartialFunction (const std::function< void(Eigen::MatrixXd &) > parameterPartialFunction, Eigen::MatrixXd & partial)
Function to evaluate the negative value of a parameter partial.
Parameters
parameterPartialFunction Function to compute the regular paramater partial (by reference).
partial Negative value of partial computed by parameterPartialFunction (returned by reference).
Definition at line 20 of file stateDerivativePartial.cpp.
Referenced by createMergedParameterPartialFunction(), getCombinedCurrentDoubleParameterFunction(), and getCombinedCurrentVectorParameterFunction().
evaluateSubtractedParameterPartialFunction()
void tudat::orbit_determination::evaluateSubtractedParameterPartialFunction (const std::function< void(Eigen::MatrixXd &) > firstParameterPartialFunction, const std::function< void(Eigen::MatrixXd &) > parameterPartialFunctionToSubtract, Eigen::MatrixXd & partial)
Function to evaluate the subtraction of two parameter partials.
Parameters
firstParameterPartialFunction Function to compute the first paramater partial (by reference), from which the value computed by parameterPartialFunctionToSubtract is subtracted.
parameterPartialFunctionToSubtract Function to compute the paramater partial (by reference) that is to be subtracted.
partial Value of partial returned by parameterPartialFunctionToSubtract, subtracted from value returned by firstParameterPartialFunction (returned by reference).
Definition at line 29 of file stateDerivativePartial.cpp.
Referenced by createMergedParameterPartialFunction(), getCombinedCurrentDoubleParameterFunction(), and getCombinedCurrentVectorParameterFunction().
evaluateAddedParameterPartialFunction()
void tudat::orbit_determination::evaluateAddedParameterPartialFunction (const std::function< void(Eigen::MatrixXd &) > firstParameterPartialFunction, const std::function< void(Eigen::MatrixXd &) > parameterPartialFunctionToAdd, Eigen::MatrixXd & partial)
Function to evaluate the addition of two parameter partials.
Parameters
firstParameterPartialFunction Function to compute the first paramater partial (by reference) that is to be added.
parameterPartialFunctionToAdd Function to compute the second paramater partial (by reference) that is to be added.
partial Value of partial returned by firstParameterPartialFunction, added to value returned by parameterPartialFunctionToAdd (returned by reference).
Definition at line 43 of file stateDerivativePartial.cpp.
Referenced by getCombinedCurrentDoubleParameterFunction(), and getCombinedCurrentVectorParameterFunction().
createMergedParameterPartialFunction()
std::pair< std::function< void(Eigen::MatrixXd&) >, int > tudat::orbit_determination::createMergedParameterPartialFunction (const std::pair< std::function< void(Eigen::MatrixXd &) >, int > & partialFunctionOfAccelerationToAdd, const std::pair< std::function< void(Eigen::MatrixXd &) >, int > & partialFunctionOfAccelerationToSubtract)
Definition at line 57 of file stateDerivativePartial.cpp.
References evaluateNegativeParameterPartialFunction(), and evaluateSubtractedParameterPartialFunction().
getCombinedCurrentDoubleParameterFunction()
std::function< void(Eigen::MatrixXd&) > tudat::orbit_determination::getCombinedCurrentDoubleParameterFunction (const std::shared_ptr< StateDerivativePartial > firstPartial, const std::shared_ptr< StateDerivativePartial > secondPartial, const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameterObject, const int firstPartialSize, const int secondPartialSize, const bool subtractPartials)
Function to create a parameter partial evaluation function, obtained by adding or subtracting a given partial w.r.t. a double parameter from 2 state derivative partial models.
Definition at line 98 of file stateDerivativePartial.cpp.
References evaluateAddedParameterPartialFunction(), evaluateNegativeParameterPartialFunction(), evaluateSubtractedParameterPartialFunction(), and tudat::orbit_determination::StateDerivativePartial::getCurrentDoubleParameterPartial().
getCombinedCurrentVectorParameterFunction()
std::function< void(Eigen::MatrixXd&) > tudat::orbit_determination::getCombinedCurrentVectorParameterFunction (const std::shared_ptr< StateDerivativePartial > firstPartial, const std::shared_ptr< StateDerivativePartial > secondPartial, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterObject, const int firstPartialSize, const int secondPartialSize, const bool subtractPartials)
Function to create a parameter partial evaluation function, obtained by adding or subtracting a given partial w.r.t. a vector parameter from 2 state derivative partial models.
Definition at line 161 of file stateDerivativePartial.cpp.
References evaluateAddedParameterPartialFunction(), evaluateNegativeParameterPartialFunction(), evaluateSubtractedParameterPartialFunction(), and tudat::orbit_determination::StateDerivativePartial::getCurrentVectorParameterPartial().
Variable Documentation
createMergedParameterPartialFunction
std::pair< std::function< void(Eigen::MatrixXd&) >, int > tudat::orbit_determination::createMergedParameterPartialFunction(const std::pair< std::function< void(Eigen::MatrixXd &) >, int > &partialFunctionOfAccelerationToAdd, const std::pair< std::function< void(Eigen::MatrixXd &) >, int > &partialFunctionOfAccelerationToSubtract)
Create a parameter partial function, as returned by the StateDerivativePartial::getParameterPartialFunction function The partial created here is obtained from the subtraction of two such function results. The two input variables may be both empty, both define a function, or only one of them may define a function.
Parameters
partialFunctionOfAccelerationToAdd Function and associated parameter size (first and second of pair) that are to be added to the total partial.
partialFunctionOfAccelerationToSubtract Function and associated parameter size (first and second of pair) that are to be subtracted from the total partial.
Returns
Function and parameter size obtained from 'subtracting' partialFunctionOfAccelerationToSubtract from partialFunctionOfAccelerationToAdd
Definition at line 587 of file stateDerivativePartial.h.
Referenced by tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::getParameterPartialFunction(), and tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::getParameterPartialFunction().
getCombinedCurrentDoubleParameterFunction
std::function< void(Eigen::MatrixXd&) > tudat::orbit_determination::getCombinedCurrentDoubleParameterFunction(const std::shared_ptr< StateDerivativePartial > firstPartial, const std::shared_ptr< StateDerivativePartial > secondPartial, const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameterObject, const int firstPartialSize, const int secondPartialSize, const bool subtractPartials=0)
Function to create a parameter partial evaluation function, obtained by adding or subtracting a given partial w.r.t. a double parameter from 2 state derivative partial models.
a double parameter from 2 state derivative partial models. Note that this function creates a merged function from two getCurrentDoubleParameterPartial functions of the two input partial objects. The automatic computation when updating the partial (done by call to setParameterPartialUpdateFunction) is not handled by this function.
Parameters
firstPartial First object for computing partial derivatives.
secondPartial Second object for computing partial derivatives.
parameterObject Parameter w.r.t. which a partial is to be taken.
firstPartialSize Size of partial from firstPartial object (only 0 and 1 are valid).
secondPartialSize Size of partial from secondPartial object (only 0 and 1 are valid).
subtractPartials Boolean denoting whether the second parameter is to be subtracted or added to the total partial.
Returns
Function computing and returning (by reference) the combined partial according to the required settings.
Definition at line 609 of file stateDerivativePartial.h.
Referenced by tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), and tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction().
getCombinedCurrentVectorParameterFunction
std::function< void(Eigen::MatrixXd&) > tudat::orbit_determination::getCombinedCurrentVectorParameterFunction(const std::shared_ptr< StateDerivativePartial > firstPartial, const std::shared_ptr< StateDerivativePartial > secondPartial, const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameterObject, const int firstPartialSize, const int secondPartialSize, const bool subtractPartials=0)
Function to create a parameter partial evaluation function, obtained by adding or subtracting a given partial w.r.t. a vector parameter from 2 state derivative partial models.
a vector parameter from 2 state derivative partial models. Note that this function creates a merged function from two getCurrentVectorParameterPartial functions of the two input partial objects. The automatic computation when updating the partial (done by call to setParameterPartialUpdateFunction) is not handled by this function.
Parameters
firstPartial First object for computing partial derivatives.
secondPartial Second object for computing partial derivatives.
parameterObject Parameter w.r.t. which a partial is to be taken.
firstPartialSize Size of partial from firstPartial object
secondPartialSize Size of partial from secondPartial object
subtractPartials Boolean denoting whether the second parameter is to be subtracted or added to the total partial.
Returns
Function computing and returning (by reference) the combined partial according to the required settings.
Definition at line 633 of file stateDerivativePartial.h.
Referenced by tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), and tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction().