Tudat: tudat::observation_partials::OneWayDopplerScaling Class Reference
tudat::observation_partials::OneWayDopplerScaling Class Reference
Derived class for scaling three-dimensional position partial to one-way doppler observable partial.
#include <oneWayDopplerPartial.h>
Public Member Functions
OneWayDopplerScaling (const boost::function< Eigen::Vector3d(const double) > transmitterAccelerationFunction, const boost::function< Eigen::Vector3d(const double) > receiverAccelerationFunction, const boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > transmitterProperTimePartials=NULL, const boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > receiverProperTimePartials=NULL)
Destructor.
~OneWayDopplerScaling ()
Destructor.
observation_models::LinkEndType getCurrentLinkEndType ()
Function to get the fixed link end for last computation of update() function.
double getLightTimeCorrectionPartialScaling ()
Function to return factor by which light-time correction state partial is to be scaled for one-way Doppler partial.
Eigen::Matrix< double, 1, 3 > getPositionScalingFactor (const observation_models::LinkEndType linkEndType)
Function to retrieve the position scaling factor for specific link end.
int getProperTimeParameterDependencySize (const estimatable_parameters::EstimatebleParameterIdentifier parameterType)
Function to get the size of the direct dependency of proper time rate on parameter.
std::vector< std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > > getProperTimeParameterPartial (const estimatable_parameters::EstimatebleParameterIdentifier parameterType)
Function to get the direct partial derivatives, and associated times, of proper time components of Doppler partials.
boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > getReceiverProperTimePartials ()
Function to return object used to compute the contribution of receiver proper time rate to the scaling.
boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > getTransmitterProperTimePartials ()
Function to return object used to compute the contribution of transmitter proper time rate to the scaling.
Eigen::Matrix< double, 1, 3 > getVelocityScalingFactor (const observation_models::LinkEndType linkEndType)
Function to retrieve the velocity scaling factor for specific link end.
void update (const std::vector< Eigen::Vector6d > &linkEndStates, const std::vector< double > &times, const observation_models::LinkEndType fixedLinkEnd, const Eigen::VectorXd currentObservation=Eigen::VectorXd::Constant(1, TUDAT_NAN))
Update the scaling object to the current times and states.
Public Member Functions inherited from tudat::observation_partials::PositionPartialScaling
virtual ~PositionPartialScaling ()
Destructor.
Private Attributes
observation_models::LinkEndType currentLinkEndType_
Fixed link end for last computation of update() function.
double lightTimeEffectPositionScalingFactor_
Factor by which light time correction state partial is to be scaled to be added to one-way Doppler partial.
Eigen::Matrix< double, 1, 3 > positionScalingFactor_
Computed position scaling factor, for relative position vector (transmitter to receiver)
boost::function< Eigen::Vector3d(const double) > receiverAccelerationFunction_
Function returning the Cartesian acceleration of the receiver as a function of time.
boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > receiverProperTimePartials_
Object used to compute the contribution of transmitter proper time rate to the scaling.
Eigen::Matrix< double, 1, 3 > receiverVelocityScalingFactor_
Computed scaling factor for receiver velocity partials.
boost::function< Eigen::Vector3d(const double) > transmitterAccelerationFunction_
Function returning the Cartesian acceleration of the transmitter as a function of time.
boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > transmitterProperTimePartials_
Object used to compute the contribution of receiver proper time rate to the scaling.
Eigen::Matrix< double, 1, 3 > transmitterVelocityScalingFactor_
Computed scaling factor for transmitter velocity partials.
Detailed Description
Derived class for scaling three-dimensional position partial to one-way doppler observable partial. Implementation is taken from Moyer(2000) and is separately implemented for fixed receiver and transmitter.
Definition at line 206 of file oneWayDopplerPartial.h.
Constructor & Destructor Documentation
tudat::observation_partials::OneWayDopplerScaling::OneWayDopplerScaling (const boost::function< Eigen::Vector3d(const double) > transmitterAccelerationFunction, const boost::function< Eigen::Vector3d(const double) > receiverAccelerationFunction, const boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > transmitterProperTimePartials = NULL, const boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > receiverProperTimePartials = NULL) inline
Destructor
Parameters
transmitterAccelerationFunction Function returning the Cartesian acceleration of the transmitter as a function of time.
receiverAccelerationFunction Function returning the Cartesian acceleration of the receiver as a function of time.
transmitterProperTimePartials Object used to compute the contribution of receiver proper time rate to the scaling
receiverProperTimePartials Object used to compute the contribution of transmitter proper time rate to the scaling
Definition at line 220 of file oneWayDopplerPartial.h.
tudat::observation_partials::OneWayDopplerScaling::~OneWayDopplerScaling () inline
Definition at line 231 of file oneWayDopplerPartial.h.
References tudat::observation_partials::OneWayDopplerProperTimeComponentScaling::getPositionScalingFactor(), tudat::observation_partials::OneWayDopplerProperTimeComponentScaling::getVelocityScalingFactor(), TUDAT_NAN, and tudat::observation_partials::PositionPartialScaling::update().
Member Function Documentation
void tudat::observation_partials::OneWayDopplerScaling::update (const std::vector< Eigen::Vector6d > & linkEndStates, const std::vector< double > & times, const observation_models::LinkEndType fixedLinkEnd, const Eigen::VectorXd currentObservation = Eigen::VectorXd::Constant(1, TUDAT_NAN)) virtual
Update the scaling object to the current times and states
Parameters
linkEndStates List of states at each link end during observation Index of vector maps to link end for a given ObsevableType through getLinkEndIndex function.
times List of times at each link end during observation.
fixedLinkEnd Link end at which observation time is defined, i.e. link end for which associated time is kept constant when computing observable.
currentObservation Value of observation for which partial scaling is to be computed
Implements tudat::observation_partials::PositionPartialScaling.
Definition at line 136 of file oneWayDopplerPartial.cpp.
References tudat::observation_partials::computePartialOfProjectedLinkEndVelocityWrtAssociatedTime(), tudat::observation_models::receiver, tudat::physical_constants::SPEED_OF_LIGHT, and tudat::observation_models::transmitter.
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerScaling::getPositionScalingFactor (const observation_models::LinkEndType linkEndType)
Function to retrieve the position scaling factor for specific link end
Parameters
linkEndType Link end for which scaling factor is to be returned
Returns
Position partial scaling factor at current link end
Definition at line 230 of file oneWayDopplerPartial.cpp.
References tudat::observation_models::receiver.
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerScaling::getVelocityScalingFactor (const observation_models::LinkEndType linkEndType)
Function to retrieve the velocity scaling factor for specific link end
Parameters
linkEndType Link end for which scaling factor is to be returned
Returns
Velocity partial scaling factor at current link end
Definition at line 249 of file oneWayDopplerPartial.cpp.
References tudat::observation_models::receiver.
observation_models::LinkEndType tudat::observation_partials::OneWayDopplerScaling::getCurrentLinkEndType () inline
Fixed link end for last computation of update() function.
Returns
Function to get the fixed link end for last computation of update() function.
Definition at line 270 of file oneWayDopplerPartial.h.
double tudat::observation_partials::OneWayDopplerScaling::getLightTimeCorrectionPartialScaling () inline
Function to return factor by which light-time correction state partial is to be scaled to be added to one-way
Returns
Factor by which light-time correction state partial is to be scaled for one-way Doppler partial
Definition at line 280 of file oneWayDopplerPartial.h.
boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > tudat::observation_partials::OneWayDopplerScaling::getTransmitterProperTimePartials () inline
Function to return object used to compute the contribution of transmitter proper time rate to the scaling
Returns
Object used to compute the contribution of transmitter proper time rate to the scaling
Definition at line 290 of file oneWayDopplerPartial.h.
boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > tudat::observation_partials::OneWayDopplerScaling::getReceiverProperTimePartials () inline
Function to return object used to compute the contribution of receiver proper time rate to the scaling
Returns
Object used to compute the contribution of receiver proper time rate to the scaling
Definition at line 300 of file oneWayDopplerPartial.h.
References tudat::observation_partials::OneWayDopplerProperTimeComponentScaling::getProperTimeParameterPartial().
int tudat::observation_partials::OneWayDopplerScaling::getProperTimeParameterDependencySize (const estimatable_parameters::EstimatebleParameterIdentifier parameterType)
Function to get the size of the direct dependency (e.g. independent of state dependency) of proper time rate on parameter. Returns zero for no dependency. Requires that the transmitter/receiver have the same size of dependency, or that one of them has dependency size zero (no dependency).
Parameters
parameterType Parameter for which dependency is to be checked.
Returns
Number of columns in direct partial derivative of proper time rates w.r.t. parameterType
Definition at line 269 of file oneWayDopplerPartial.cpp.
std::vector< std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > > tudat::observation_partials::OneWayDopplerScaling::getProperTimeParameterPartial (const estimatable_parameters::EstimatebleParameterIdentifier parameterType)
Function to get the direct partial derivatives (e.g. independent of state partials), and associated times, of proper time components of Doppler partials, w.r.t. parameter defined by parameterType.
Parameters
parameterType Parameter for which partial is to be checked
Returns
Direct partial derivatives, and associated times, of proper time components of Doppler partials
Definition at line 306 of file oneWayDopplerPartial.cpp.
Member Data Documentation
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerScaling::positionScalingFactor_ private
Definition at line 329 of file oneWayDopplerPartial.h.
double tudat::observation_partials::OneWayDopplerScaling::lightTimeEffectPositionScalingFactor_ private
Factor by which light time correction state partial is to be scaled to be added to one-way Doppler partial. ALso forms part of the total partial w.r.t. the relative position.
Definition at line 336 of file oneWayDopplerPartial.h.
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerScaling::receiverVelocityScalingFactor_ private
Definition at line 339 of file oneWayDopplerPartial.h.
Eigen::Matrix< double, 1, 3 > tudat::observation_partials::OneWayDopplerScaling::transmitterVelocityScalingFactor_ private
Definition at line 342 of file oneWayDopplerPartial.h.
observation_models::LinkEndType tudat::observation_partials::OneWayDopplerScaling::currentLinkEndType_ private
Definition at line 345 of file oneWayDopplerPartial.h.
boost::function< Eigen::Vector3d(const double) > tudat::observation_partials::OneWayDopplerScaling::transmitterAccelerationFunction_ private
Definition at line 348 of file oneWayDopplerPartial.h.
boost::function< Eigen::Vector3d(const double) > tudat::observation_partials::OneWayDopplerScaling::receiverAccelerationFunction_ private
Definition at line 351 of file oneWayDopplerPartial.h.
boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > tudat::observation_partials::OneWayDopplerScaling::transmitterProperTimePartials_ private
Definition at line 354 of file oneWayDopplerPartial.h.
boost::shared_ptr< OneWayDopplerProperTimeComponentScaling > tudat::observation_partials::OneWayDopplerScaling::receiverProperTimePartials_ private
Definition at line 357 of file oneWayDopplerPartial.h.
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/ObservationPartials/oneWayDopplerPartial.h
Astrodynamics/OrbitDetermination/ObservationPartials/oneWayDopplerPartial.cpp