Tudat: tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType > Class Template Reference
tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType > Class Template Reference abstract
Base class to manage and execute the numerical integration of equations of motion and variational equations.
#include <variationalEquationsSolver.h>
Public Types
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > MatrixType
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > VectorType
Public Member Functions
VariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool clearNumericalSolution=1)
Constructor.
virtual ~VariationalEquationsSolver ()
Destructor.
virtual boost::shared_ptr< DynamicsSimulator< StateScalarType, TimeType > > getDynamicsSimulatorBase ()=0
boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > getParametersToEstimate ()
Function to get the list of objects representing the parameters that are to be integrated.
boost::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > getStateTransitionMatrixInterface ()
Function to get the state transition matric interface object.
virtual void integrateDynamicalEquationsOfMotionOnly (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &initialStateEstimate)=0
Pure virtual function to integrate equations of motion only.
virtual void integrateVariationalAndDynamicalEquations (const VectorType &initialStateEstimate, const bool integrateEquationsConcurrently)=0
Pure virtual function to integrate variational equations and equations of motion.
virtual void resetParameterEstimate (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > newParameterEstimate, const bool areVariationalEquationsToBeIntegrated=true)=0
Function to reset parameter estimate and re-integrate equations of motion and, if desired, variational equations.
Protected Member Functions
MatrixType createInitialConditions (const VectorType initialStateEstimate)
Create initial matrix of numerical soluation to variational + dynamical equations.
Eigen::MatrixXd createInitialVariationalEquationsSolution ()
Create initial matrix of numerical soluation to variational equations.
Protected Attributes
simulation_setup::NamedBodyMap bodyMap_
Map of bodies (with names) of all bodies in integration.
bool clearNumericalSolution_
Boolean to determine whether to clear the raw numerical solution member variables after propagation.
boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate_
Object containing all parameters that are to be estimated and their current settings and values.
int parameterVectorSize_
Number of rows in sensitivity matrix.
boost::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface_
Object used for interpolating numerical results of state transition and sensitivity matrix.
int stateTransitionMatrixSize_
Size (rows and columns are equal) of state transition matrix.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
Base class to manage and execute the numerical integration of equations of motion and variational equations. Governing equations are set once, but can be re-integrated for different initial conditions using the same instance of the class. Derived classes define the specific kind of integration that is performed (single-arc/multi-arc; dynamics/variational equations, etc.)
Definition at line 46 of file variationalEquationsSolver.h.
Member Typedef Documentation
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::MatrixType
Definition at line 50 of file variationalEquationsSolver.h.
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::VectorType
Definition at line 51 of file variationalEquationsSolver.h.
Constructor & Destructor Documentation
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::VariationalEquationsSolver (const simulation_setup::NamedBodyMap & bodyMap, const boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool clearNumericalSolution = 1) inline
Constructor, sets up object for automatic evaluation and numerical integration of variational equations and equations of motion.
Parameters
bodyMap Map of bodies (with names) of all bodies in integration.
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values.
clearNumericalSolution Boolean to determine whether to clear the raw numerical solution member variables (default true) after propagation and resetting of state transition interface.
Definition at line 63 of file variationalEquationsSolver.h.
template<typename StateScalarType = double, typename TimeType = double> virtual tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::~VariationalEquationsSolver () inline virtual
Definition at line 75 of file variationalEquationsSolver.h.
References tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly(), and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
Member Function Documentation
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations (const VectorType & initialStateEstimate, const bool integrateEquationsConcurrently) pure virtual
Pure virtual function to integrate variational equations and equations of motion, to be implemented in derived class
Parameters
initialStateEstimate Initial state of the equations of motion that is to be used.
integrateEquationsConcurrently Variable determining whether the equations of motion are to be propagated concurrently with variational equations of motion (if true), or before variational equations (if false).
Implemented in tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >.
Referenced by tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver(), and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::~VariationalEquationsSolver().
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & initialStateEstimate) pure virtual
Pure virtual function to integrate equations of motion only, to be implemented in derived class
Parameters
initialStateEstimate Initial state of the equations of motion that is to be used.
Implemented in tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::~VariationalEquationsSolver().
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::getParametersToEstimate () inline
Function to get the list of objects representing the parameters that are to be integrated.
Returns
List of objects representing the parameters that are to be integrated.
Definition at line 103 of file variationalEquationsSolver.h.
References tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parametersToEstimate_, and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate().
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > newParameterEstimate, const bool areVariationalEquationsToBeIntegrated = true) pure virtual
Function to reset parameter estimate and re-integrate equations of motion and, if desired, variational equations using the new physical parameters/body initial states.
Parameters
newParameterEstimate New estimate of parameters that are to be estimated, in same order as defined in parametersToEstimate_ member.
areVariationalEquationsToBeIntegrated Boolean defining whether the variational equations are to be reintegrated with the new parameter values.
Implemented in tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >.
Referenced by tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::getParametersToEstimate().
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::getStateTransitionMatrixInterface () inline
Function to get the state transition matric interface object.
Returns
The state transition matric interface object.
Definition at line 125 of file variationalEquationsSolver.h.
References tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulatorBase(), and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionInterface_.
template<typename StateScalarType = double, typename TimeType = double> virtual boost::shared_ptr< DynamicsSimulator< StateScalarType, TimeType > > tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulatorBase () pure virtual
Implemented in tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >.
Referenced by tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::getStateTransitionMatrixInterface().
template<typename StateScalarType = double, typename TimeType = double> MatrixType tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialConditions (const VectorType initialStateEstimate) inline protected
Create initial matrix of numerical soluation to variational + dynamical equations. The structure of the matrix is [Phi;S;y], with Phi the state transition matrix, S the sensitivity matrix y the state vector.
Parameters
initialStateEstimate vector of initial state (position/velocity) of bodies to be integrated numerically. order determined by order of bodiesToIntegrate_.
Returns
Initial matrix of numerical soluation to variation + state equations.
Definition at line 145 of file variationalEquationsSolver.h.
References tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parameterVectorSize_, and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionMatrixSize_.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
template<typename StateScalarType = double, typename TimeType = double> Eigen::MatrixXd tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialVariationalEquationsSolution () inline protected
Create initial matrix of numerical soluation to variational equations, with structure [Phi;S]. Initial state transition matrix Phi is identity matrix. Initial sensitivity matrix S is all zeros.
Returns
Initial matrix solution to variational equations.
Definition at line 167 of file variationalEquationsSolver.h.
References tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parameterVectorSize_, and tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionMatrixSize_.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
Member Data Documentation
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parametersToEstimate_ protected
Definition at line 180 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::getParametersToEstimate(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
template<typename StateScalarType = double, typename TimeType = double> simulation_setup::NamedBodyMap tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::bodyMap_ protected
Definition at line 183 of file variationalEquationsSolver.h.
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionMatrixSize_ protected
Definition at line 186 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialConditions(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialVariationalEquationsSolution(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver().
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parameterVectorSize_ protected
Definition at line 189 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialConditions(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialVariationalEquationsSolution(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators().
template<typename StateScalarType = double, typename TimeType = double> bool tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::clearNumericalSolution_ protected
Boolean to determine whether to clear the raw numerical solution member variables after propagation and resetting of state transition interface.
Definition at line 196 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators().
template<typename StateScalarType = double, typename TimeType = double> boost::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionInterface_ protected
Definition at line 199 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::getStateTransitionMatrixInterface(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/variationalEquationsSolver.h