Tudat: tudat::aerodynamics::CustomConstantTemperatureAtmosphere Class Reference
tudat::aerodynamics::CustomConstantTemperatureAtmosphere Class Reference
Custom constant temperature atmosphere class.
#include <customConstantTemperatureAtmosphere.h>
Public Types
typedef std::function< double(const double, const double, const double, const double) > DensityFunction
Typedef for density function.
Public Member Functions
CustomConstantTemperatureAtmosphere (const DensityFunction &densityFunction, const double constantTemperature, const double specificGasConstant=physical_constants::SPECIFIC_GAS_CONSTANT_AIR, const double ratioOfSpecificHeats=1.4)
Default constructor.
CustomConstantTemperatureAtmosphere (const AvailableConstantTemperatureAtmosphereModels densityFunctionType, const double constantTemperature, const double specificGasConstant, const double ratioOfSpecificHeats, const std::vector< double > &modelSpecificParameters)
Constructor.
double getConstantTemperature ()
Get constant temperature.
double getDensity (const double altitude, const double longitude=0.0, const double latitude=0.0, const double time=0.0)
Get local density.
DensityFunction getDensityFunction ()
Get the function to compute the density at the current conditions.
double getPressure (const double altitude, const double longitude=0.0, const double latitude=0.0, const double time=0.0)
Get local pressure.
double getRatioOfSpecificHeats ()
Get ratio of specific heats.
double getSpecificGasConstant ()
Get specific gas constant.
double getSpeedOfSound (const double altitude, const double longitude=0.0, const double latitude=0.0, const double time=0.0)
Get local speed of sound in the atmosphere.
double getTemperature (const double altitude, const double longitude=0.0, const double latitude=0.0, const double time=0.0)
Get local temperature.
void setDensityFunction (DensityFunction &newDensityFunction)
Set the function to compute the density at the current conditions.
Public Member Functions inherited from tudat::aerodynamics::AtmosphereModel
virtual ~AtmosphereModel ()
Default destructor.
std::shared_ptr< WindModel > getWindModel ()
Function to retrieve the model describing the wind velocity vector of the atmosphere.
void setWindModel (const std::shared_ptr< WindModel > windModel)
Function to set the model describing the wind velocity vector of the atmosphere.
Private Attributes
const double constantTemperature_
Constant temperature.
DensityFunction densityFunction_
Function to compute the density at the current conditions.
const double ratioOfSpecificHeats_
Ratio of specific heats at constant pressure and constant volume.
const double specificGasConstant_
Specific gas constant.
Additional Inherited Members
Protected Attributes inherited from tudat::aerodynamics::AtmosphereModel
std::shared_ptr< WindModel > windModel_
Model describing the wind velocity vector of the atmosphere.
Detailed Description
Custom constant temperature atmosphere class. This atmosphere model is initialized by giving as input a function for the density which may depend on altitude, longitude, latitude and time. The pressure is then determined with the ideal gas law, and the temperature is assumed to be constant throughtout the atmosphere domain.
Definition at line 110 of file customConstantTemperatureAtmosphere.h.
Member Typedef Documentation
DensityFunction
typedef std::function< double(const double, const double, const double, const double) > tudat::aerodynamics::CustomConstantTemperatureAtmosphere::DensityFunction
Definition at line 116 of file customConstantTemperatureAtmosphere.h.
Constructor & Destructor Documentation
CustomConstantTemperatureAtmosphere() [1/2]
tudat::aerodynamics::CustomConstantTemperatureAtmosphere::CustomConstantTemperatureAtmosphere (const DensityFunction & densityFunction, const double constantTemperature, const double specificGasConstant = physical_constants::SPECIFIC_GAS_CONSTANT_AIR, const double ratioOfSpecificHeats = 1.4) inline
Default constructor setting all parameters manually.
Parameters
densityFunction Function to retireve the density at the current altitude, longitude, latitude and time.
constantTemperature Constant atmospheric temperature.
specificGasConstant The constant specific gas constant of the atmosphere.
ratioOfSpecificHeats The constant ratio of specific heats of the atmosphere.
Definition at line 127 of file customConstantTemperatureAtmosphere.h.
CustomConstantTemperatureAtmosphere() [2/2]
tudat::aerodynamics::CustomConstantTemperatureAtmosphere::CustomConstantTemperatureAtmosphere (const AvailableConstantTemperatureAtmosphereModels densityFunctionType, const double constantTemperature, const double specificGasConstant, const double ratioOfSpecificHeats, const std::vector< double > & modelSpecificParameters)
Constructor which uses one of the built-in density functions as input.
Constructor which uses one of the built-in density functions as input.
Parameters
densityFunctionType Enumeration denoting which density function to implement.
constantTemperature Constant atmospheric temperature.
specificGasConstant The constant specific gas constant of the atmosphere.
ratioOfSpecificHeats The constant ratio of specific heats of the atmosphere.
modelSpecificParameters Vector of parameters to be used to set up the density function. Both meaning and number of parameters depends on the model.
Definition at line 54 of file customConstantTemperatureAtmosphere.cpp.
References densityFunction_, tudat::aerodynamics::exponential_atmosphere_model, tudat::aerodynamics::exponentialAtmosphereModel(), tudat::aerodynamics::three_term_atmosphere_model, tudat::aerodynamics::three_wave_atmosphere_model, tudat::aerodynamics::threeTermAtmosphereModel(), and tudat::aerodynamics::threeWaveAtmosphereModel().
Member Function Documentation
getDensityFunction()
DensityFunction tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getDensityFunction () inline
Function to return the function to compute the density at the current conditions.
Returns
Function to compute the density at the current conditions.
Definition at line 160 of file customConstantTemperatureAtmosphere.h.
References densityFunction_.
setDensityFunction()
void tudat::aerodynamics::CustomConstantTemperatureAtmosphere::setDensityFunction (DensityFunction & newDensityFunction) inline
Function to reset the function to compute the density at the current conditions.
Parameters
newDensityFunction New function to compute the density at the current conditions.
Definition at line 167 of file customConstantTemperatureAtmosphere.h.
References densityFunction_.
getConstantTemperature()
double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getConstantTemperature () inline
Returns the atmospheric temperature (constant, property of exponential atmosphere) in Kelvin.
Returns
Constant atmospheric temperature in exponential atmosphere.
Definition at line 178 of file customConstantTemperatureAtmosphere.h.
References constantTemperature_.
getSpecificGasConstant()
double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getSpecificGasConstant () inline
Returns the specific gas constant of the atmosphere in J/(kg K), its value is assumed constant, due to the assumption of constant atmospheric composition.
Returns
Specific gas constant in exponential atmosphere.
Definition at line 186 of file customConstantTemperatureAtmosphere.h.
References specificGasConstant_.
getRatioOfSpecificHeats()
double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getRatioOfSpecificHeats () inline
Returns the ratio of specific hears of the atmosphere, its value is assumed constant, due to the assumption of constant atmospheric composition.
Returns
Ratio of specific heats exponential atmosphere.
Definition at line 194 of file customConstantTemperatureAtmosphere.h.
References ratioOfSpecificHeats_.
getDensity()
double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getDensity (const double altitude, const double longitude = 0.0, const double latitude = 0.0, const double time = 0.0) inline virtual
Returns the local density of the atmosphere in kg per meter^3.
Parameters
altitude Altitude at which density is to be computed.
longitude Longitude at which density is to be computed.
latitude Latitude at which density is to be computed.
time Time at which density is to be computed.
Returns
Atmospheric density at specified altitude.
Implements tudat::aerodynamics::StandardAtmosphere.
Definition at line 205 of file customConstantTemperatureAtmosphere.h.
References densityFunction_.
Referenced by getPressure().
getPressure()
double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getPressure (const double altitude, const double longitude = 0.0, const double latitude = 0.0, const double time = 0.0) inline virtual
Returns the local pressure of the atmosphere in Newton per meter^2.
Parameters
altitude Altitude at which pressure is to be computed.
longitude Longitude at which pressure is to be computed.
latitude Latitude at which pressure is to be computed.
time Time at which pressure is to be computed.
Returns
Atmospheric pressure at specified altitude.
Implements tudat::aerodynamics::StandardAtmosphere.
Definition at line 220 of file customConstantTemperatureAtmosphere.h.
References constantTemperature_, getDensity(), and specificGasConstant_.
getTemperature()
double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getTemperature (const double altitude, const double longitude = 0.0, const double latitude = 0.0, const double time = 0.0) inline virtual
Returns the local temperature of the atmosphere in Kelvin.
Parameters
altitude Altitude at which temperature is to be computed (not used since temperature is assumed to be constant).
longitude Longitude at which temperature is to be computed (not used but included for consistency with base class interface).
latitude Latitude at which temperature is to be computed (not used but included for consistency with base class interface).
time Time at which temperature is to be computed (not used but included for consistency with base class interface).
Returns
constantTemperature Atmospheric temperature at specified altitude.
Implements tudat::aerodynamics::StandardAtmosphere.
Definition at line 239 of file customConstantTemperatureAtmosphere.h.
References constantTemperature_, and TUDAT_UNUSED_PARAMETER.
Referenced by getSpeedOfSound().
getSpeedOfSound()
double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getSpeedOfSound (const double altitude, const double longitude = 0.0, const double latitude = 0.0, const double time = 0.0) inline virtual
Returns the speed of sound in the atmosphere in m/s.
Parameters
altitude Altitude at which speed of sounds is to be computed.
longitude Longitude at which speed of sounds is to be computed (not used but included for consistency with base class interface).
latitude Latitude at which speed of sounds is to be computed (not used but included for consistency with base class interface).
time Time at which speed of sounds is to be computed (not used but included for consistency with base class interface).
Returns
Atmospheric speed of sounds at specified altitude.
Implements tudat::aerodynamics::StandardAtmosphere.
Definition at line 261 of file customConstantTemperatureAtmosphere.h.
References tudat::aerodynamics::computeSpeedOfSound(), getTemperature(), ratioOfSpecificHeats_, and specificGasConstant_.
Member Data Documentation
densityFunction_
DensityFunction tudat::aerodynamics::CustomConstantTemperatureAtmosphere::densityFunction_ private
Function to compute the density at the current conditions. Note that the independent variables need to be altitude, longitude, latitude and time, in this precise order.
Definition at line 278 of file customConstantTemperatureAtmosphere.h.
Referenced by CustomConstantTemperatureAtmosphere(), getDensity(), getDensityFunction(), and setDensityFunction().
constantTemperature_
const double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::constantTemperature_ private
The atmospheric temperature (constant, property of exponential atmosphere) in Kelvin.
Definition at line 284 of file customConstantTemperatureAtmosphere.h.
Referenced by getConstantTemperature(), getPressure(), and getTemperature().
specificGasConstant_
const double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::specificGasConstant_ private
Specific gas constant of the atmosphere, its value is assumed constant, due to the assumption of constant atmospheric composition.
Definition at line 291 of file customConstantTemperatureAtmosphere.h.
Referenced by getPressure(), getSpecificGasConstant(), and getSpeedOfSound().
ratioOfSpecificHeats_
const double tudat::aerodynamics::CustomConstantTemperatureAtmosphere::ratioOfSpecificHeats_ private
Ratio of specific heats of the atmosphere at constant pressure and constant volume. This value is set to a constant, implying constant atmospheric composition.
Definition at line 298 of file customConstantTemperatureAtmosphere.h.
Referenced by getRatioOfSpecificHeats(), and getSpeedOfSound().
The documentation for this class was generated from the following files:
Astrodynamics/Aerodynamics/customConstantTemperatureAtmosphere.h
Astrodynamics/Aerodynamics/customConstantTemperatureAtmosphere.cpp