Tudat: tudat::mission_geometry Namespace Reference
tudat::mission_geometry Namespace Reference
Functions
double computeShadowFunction (const Eigen::Vector3d &occultedBodyPosition, const double occultedBodyRadius, const Eigen::Vector3d &occultingBodyPosition, const double occultingBodyRadius, const Eigen::Vector3d &satellitePosition)
Compute the shadow function.
double computeSphereOfInfluence (const double distanceToCentralBody, const double ratioOfOrbitingToCentralBodyMass)
Compute the radius of the sphere of influence.
double computeSphereOfInfluence (const double distanceToCentralBody, const double massOrbitingBody, const double massCentralBody)
Compute the sphere of influence.
bool isOrbitRetrograde (const double inclination)
Compute whether an orbit is retrograde based on inclination.
bool isOrbitRetrograde (const Eigen::Vector6d &keplerElements)
Compute whether an orbit is retrograde based on Keplerian state.
Function Documentation
isOrbitRetrograde() [1/2]
bool tudat::mission_geometry::isOrbitRetrograde (const double inclination)
Determines whether an orbit is retrograde, based on its inclination. The orbit is defined to be retrograde if its inclination is >90 and <180 degrees, prograde if >0 and <=90 degrees. Values outside [0, 180] degrees are not allowed for this function. The longitude of the ascending node does not influence whether the orbit is retrograde.
N.B: The inclination must be given in radians!
Parameters
inclination Inclination of the orbit [rad].
Returns
true if orbit is retrograde, false if prograde.
Definition at line 30 of file missionGeometry.cpp.
References tudat::input_output::field_types::state::inclination, and tudat::mathematical_constants::PI.
Referenced by tudat::orbital_element_conversions::convertCartesianToModifiedEquinoctialElements(), tudat::orbital_element_conversions::convertKeplerianToModifiedEquinoctialElements(), and isOrbitRetrograde().
isOrbitRetrograde() [2/2]
bool tudat::mission_geometry::isOrbitRetrograde (const Eigen::Vector6d & keplerElements)
Determines whether an orbit is retrograde, based on the kepler elements. The orbit is defined to be retrograde if its inclination is >90 and <180 degrees, prograde if >0 and <=90 degrees. Values for the inclination outside [0, 180] degrees are not allowed for this function. The right ascension of the ascending node does not influence whether the orbit is retrograde.
N.B: The inclination must be given in radians!
Parameters
keplerElements Vector of keplerian elements.
Returns
true if orbit is retrograde, false if prograde.
Definition at line 53 of file missionGeometry.cpp.
References tudat::orbital_element_conversions::inclinationIndex, and isOrbitRetrograde().
computeShadowFunction()
double tudat::mission_geometry::computeShadowFunction (const Eigen::Vector3d & occultedBodyPosition, const double occultedBodyRadius, const Eigen::Vector3d & occultingBodyPosition, const double occultingBodyRadius, const Eigen::Vector3d & satellitePosition)
Returns the value of of the shadow function. Returns 0 if the satellite is in umbra, 1 if the satellite is fully exposed and a value between 0 and 1 if the satellite is in penumbra.
The point of view is from the satellite. The occulting body (for example the Earth) is the body that blocks the light from the occulting body (for example the Sun).
Reference: Section 3.4 from (Montebruck O, Gill E., 2005).
Parameters
occultedBodyPosition Vector containing Cartesian coordinates of the occulted body.
occultedBodyRadius Mean radius of occulted body.
occultingBodyPosition Vector containing Cartesian coordinates of the occulting body.
occultingBodyRadius Mean radius of occulting body.
satellitePosition Vector containing Cartesian coordinates of the satellite.
Returns
Shadow function value.
Definition at line 62 of file missionGeometry.cpp.
References tudat::mathematical_constants::PI.
Referenced by tudat::observation_models::OccultationCalculator::isObservationViable(), and tudat::electro_magnetism::RadiationPressureInterface::updateInterface().
computeSphereOfInfluence() [1/2]
double tudat::mission_geometry::computeSphereOfInfluence (const double distanceToCentralBody, const double ratioOfOrbitingToCentralBodyMass)
Returns the radius of the the Sphere of Influence (SOI) for a body orbiting a central body.
Reference: Section 7.4 from (Fundamentals of Astrodynamics, R. Bate, 1971).
Parameters
distanceToCentralBody Distance from the orbiting body to the central body [m].
ratioOfOrbitingToCentralBodyMass ratio of mass of orbiting body (i.e. Earth) to that of central body (i.e. Sun).
Returns
Radius of sphere of influence [m].
Definition at line 148 of file missionGeometry.cpp.
Referenced by computeSphereOfInfluence().
computeSphereOfInfluence() [2/2]
double tudat::mission_geometry::computeSphereOfInfluence (const double distanceToCentralBody, const double massOrbitingBody, const double massCentralBody)
Compute the radius of the sphere of influence.
Returns the radius of the the Sphere of Influence (SOI) for a body orbiting a central body.
Reference: Section 7.4 from (Fundamentals of Astrodynamics, R. Bate, 1971).
Parameters
distanceToCentralBody Distance from the orbiting body to the central body.
massOrbitingBody Mass of orbiting body (i.e. Earth) [kg].
massCentralBody Mass of central body (i.e. Sun) [kg].
Returns
Radius of sphere of influence [m].
Definition at line 156 of file missionGeometry.cpp.
References computeSphereOfInfluence().