Tudat: tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType > Class Template Reference
tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType > Class Template Reference
Class to manage and execute the numerical integration of variational equations of a dynamical system in a single arc.
#include <variationalEquationsSolver.h>
Public Types
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > MatrixType
Local typedefs for vector and matrix of given scalar type.
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > VectorType
Public Types inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > MatrixType
typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > VectorType
Public Member Functions
SingleArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool integrateDynamicalAndVariationalEquationsConcurrently=1, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > variationalOnlyIntegratorSettings=std::shared_ptr< numerical_integrators::IntegratorSettings< double > >(), const bool clearNumericalSolution=1, const bool integrateEquationsOnCreation=1)
Constructor.
~SingleArcVariationalEquationsSolver ()
Destructor.
std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > getDynamicsSimulator ()
Function to return object used for numerically propagating and managing the solution of the equations of motion.
std::shared_ptr< DynamicsSimulator< StateScalarType, TimeType > > getDynamicsSimulatorBase ()
Function to retrieve the dynamics simulator object (as base-class pointer)
std::vector< std::map< double, Eigen::MatrixXd > > & getNumericalVariationalEquationsSolution ()
Function to return the numerical solution history of numerically integrated variational equations.
void integrateDynamicalEquationsOfMotionOnly (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &initialStateEstimate)
Function to integrate equations of motion only.
void integrateVariationalAndDynamicalEquations (const VectorType &initialStateEstimate, const bool integrateEquationsConcurrently)
Function to integrate variational equations and equations of motion.
void resetParameterEstimate (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > newParameterEstimate, const bool areVariationalEquationsToBeIntegrated=true)
Function to reset parameter estimate and re-integrate equations of motion and, if desired, variational equations.
Public Member Functions inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
VariationalEquationsSolver (const simulation_setup::NamedBodyMap &bodyMap, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool clearNumericalSolution=1)
Constructor.
virtual ~VariationalEquationsSolver ()
Destructor.
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > getParametersToEstimate ()
Function to get the list of objects representing the parameters that are to be integrated.
std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > getStateTransitionMatrixInterface ()
Function to get the state transition matric interface object.
Private Member Functions
void resetVariationalEquationsInterpolators ()
Reset solutions of variational equations.
Private Attributes
std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > dynamicsSimulator_
Object used for numerically propagating and managing the solution of the equations of motion.
std::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > dynamicsStateDerivative_
Object used to compute the full state derivative in equations of motion and variational equations.
std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings_
Settings for numerical integrator of combined propagation of variational equations and equations of motion.
std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > propagatorSettings_
Settings for propagation of equations of motion.
std::function< void(Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &) > statePostProcessingFunction_
std::shared_ptr< VariationalEquations > variationalEquationsObject_
Object that is used to evaluate the variational equations at the given state and time.
std::vector< std::map< double, Eigen::MatrixXd > > variationalEquationsSolution_
Map of history of numerically integrated variational equations.
std::shared_ptr< numerical_integrators::IntegratorSettings< double > > variationalOnlyIntegratorSettings_
Settings for numerical integrator when integrating only variational equations.
Additional Inherited Members
Protected Member Functions inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
MatrixType createInitialConditions (const VectorType initialStateEstimate)
Create initial matrix of numerical soluation to variational + dynamical equations.
Eigen::MatrixXd createInitialVariationalEquationsSolution ()
Create initial matrix of numerical soluation to variational equations.
Protected Attributes inherited from tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >
simulation_setup::NamedBodyMap bodyMap_
Map of bodies (with names) of all bodies in integration.
bool clearNumericalSolution_
Boolean to determine whether to clear the raw numerical solution member variables after propagation.
std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate_
Object containing all parameters that are to be estimated and their current settings and values.
int parameterVectorSize_
Number of rows in sensitivity matrix.
std::shared_ptr< CombinedStateTransitionAndSensitivityMatrixInterface > stateTransitionInterface_
Object used for interpolating numerical results of state transition and sensitivity matrix.
int stateTransitionMatrixSize_
Size (rows and columns are equal) of state transition matrix.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >
Class to manage and execute the numerical integration of variational equations of a dynamical system, in addition to the dynamics itself, in a single arc: i.e. the governing equations a single initial time, and are propagated once for the full prescribed time interval. This is in contrast to multi-arc dynamics, where the time interval is cut into pieces. In this class, the governing equations are set once, but can be re-integrated for different initial conditions using the same instance of the class.
Definition at line 489 of file variationalEquationsSolver.h.
Member Typedef Documentation
MatrixType
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::MatrixType
Definition at line 494 of file variationalEquationsSolver.h.
VectorType
template<typename StateScalarType = double, typename TimeType = double> typedef Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::VectorType
Definition at line 495 of file variationalEquationsSolver.h.
Constructor & Destructor Documentation
SingleArcVariationalEquationsSolver()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver (const simulation_setup::NamedBodyMap & bodyMap, const std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings, const std::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings, const std::shared_ptr< estimatable_parameters::EstimatableParameterSet< StateScalarType > > parametersToEstimate, const bool integrateDynamicalAndVariationalEquationsConcurrently = 1, const std::shared_ptr< numerical_integrators::IntegratorSettings< double > > variationalOnlyIntegratorSettings = std::shared_ptr< numerical_integrators::IntegratorSettings< double > >(), const bool clearNumericalSolution = 1, const bool integrateEquationsOnCreation = 1) inline
Constructor, sets up object for automatic evaluation and numerical integration of variational equations and equations of motion.
Parameters
bodyMap Map of bodies (with names) of all bodies in integration.
integratorSettings Settings for numerical integrator of combined propagation of variational equations and equations of motion.
propagatorSettings Settings for propagation of equations of motion.
parametersToEstimate Object containing all parameters that are to be estimated and their current settings and values.
integrateDynamicalAndVariationalEquationsConcurrently Boolean defining whether variational and dynamical equations are to be propagated concurrently (if true) or sequentially (of false)
variationalOnlyIntegratorSettings Settings for numerical integrator when integrating only variational equations.
clearNumericalSolution Boolean to determine whether to clear the raw numerical solution member variables (default true) after propagation and resetting of state transition interface.
integrateEquationsOnCreation Boolean to denote whether equations should be integrated immediately at the end of this contructor.
Definition at line 523 of file variationalEquationsSolver.h.
References tudat::propagators::createStateDerivativeModels(), tudat::simulation_setup::createStateDerivativePartials(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsStateDerivative_, tudat::propagators::getStateDerivativeModelMapFromVector(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integratorSettings_, tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parametersToEstimate_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::statePostProcessingFunction_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsObject_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_.
~SingleArcVariationalEquationsSolver()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::~SingleArcVariationalEquationsSolver () inline
Definition at line 605 of file variationalEquationsSolver.h.
Member Function Documentation
integrateDynamicalEquationsOfMotionOnly()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & initialStateEstimate) inline virtual
Function to integrate equations of motion only (in single arc). If dynamical solution is to be processed, the environment is also updated to the new solution.
Parameters
initialStateEstimate Initial state of the equations of motion that is to be used (in same order as in parametersToEstimate_)
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 614 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsStateDerivative_.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate().
integrateVariationalAndDynamicalEquations()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations (const VectorType & initialStateEstimate, const bool integrateEquationsConcurrently) inline virtual
Function to integrate variational equations and equations of motion (in single arc). At the end of this function, the stateTransitionInterface_ is reset with the new state transition and sensitivity matrices. If dynamical solution is to be processed, the environment is also updated to the new solution.
Parameters
initialStateEstimate Initial state of the equations of motion that is to be used (in same order as in parametersToEstimate_).
integrateEquationsConcurrently Variable determining whether the equations of motion are to be propagated concurrently with variational equations of motion (if true), or before variational equations (if false).
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 631 of file variationalEquationsSolver.h.
References tudat::propagators::convertNumericalStateSolutionsToOutputSolutions(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialConditions(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::createInitialVariationalEquationsSolution(), tudat::utilities::createVectorBlockMatrixHistory(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsStateDerivative_, tudat::propagators::EquationIntegrationInterface< StateType, TimeType >::integrateEquations(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integratorSettings_, tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parameterVectorSize_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::statePostProcessingFunction_, tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionMatrixSize_, tudat::propagators::translational_state, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalOnlyIntegratorSettings_.
Referenced by tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
getNumericalVariationalEquationsSolution()
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< double, Eigen::MatrixXd > >& tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::getNumericalVariationalEquationsSolution () inline
Function to return the numerical solution history of numerically integrated variational equations.
Returns
Vector of mapa of state transition matrix history (first vector entry) and sensitivity matrix history (second vector entry)
Definition at line 719 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_.
getDynamicsSimulator()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulator () inline
Function to return object used for numerically propagating and managing the solution of the equations of motion.
Returns
Object used for numerically propagating and managing the solution of the equations of motion.
Definition at line 729 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulatorBase(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulatorBase().
getDynamicsSimulatorBase()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< DynamicsSimulator< StateScalarType, TimeType > > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulatorBase () inline virtual
Function to retrieve the dynamics simulator object (as base-class pointer)
Returns
Dynamics simulator object (as base-class pointer)
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 739 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulator().
resetParameterEstimate()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > newParameterEstimate, const bool areVariationalEquationsToBeIntegrated = true) inline virtual
Function to reset parameter estimate and re-integrate equations of motion and, if desired, variational equations using the new physical parameters/body initial states.
Parameters
newParameterEstimate New estimate of parameters that are to be estimated, in same order as defined in parametersToEstimate_ member.
areVariationalEquationsToBeIntegrated Boolean defining whether the variational equations are to be reintegrated with the new parameter values.
Implements tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >.
Definition at line 753 of file variationalEquationsSolver.h.
References tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsStateDerivative_, tudat::estimatable_parameters::getInitialStateVectorOfBodiesToEstimate(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parametersToEstimate_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_.
resetVariationalEquationsInterpolators()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators () inline private
Reset solutions of variational equations (stateTransitionMatrixInterpolator_ and sensitivityMatrixInterpolator_), i.e. use numerical integration results to create new look-up tables and interpolators of state transition and sensitivity matrix through the createInterpolatorsForVariationalSolution function
Definition at line 788 of file variationalEquationsSolver.h.
References tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::clearNumericalSolution_, tudat::propagators::createStateTransitionAndSensitivityMatrixInterpolator(), tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::parameterVectorSize_, tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_, tudat::propagators::VariationalEquationsSolver< StateScalarType, TimeType >::stateTransitionInterface_, and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
Member Data Documentation
dynamicsSimulator_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleArcDynamicsSimulator< StateScalarType, TimeType > > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsSimulator_ private
Definition at line 818 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulator(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::getDynamicsSimulator(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
variationalEquationsObject_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< VariationalEquations > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsObject_ private
Definition at line 821 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
variationalEquationsSolution_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::map< double, Eigen::MatrixXd > > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalEquationsSolution_ private
Map of history of numerically integrated variational equations. Key of map denotes time, values are state transition matrix Phi (first vector entry) and sensitivity matrix S (second vector entry)
Definition at line 828 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::getNumericalVariationalEquationsSolution(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::getNumericalVariationalEquationsSolution(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
statePostProcessingFunction_
template<typename StateScalarType = double, typename TimeType = double> std::function< void(Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic >&) > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::statePostProcessingFunction_ private
Definition at line 830 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
integratorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integratorSettings_ private
Definition at line 834 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
propagatorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< SingleArcPropagatorSettings< StateScalarType > > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::propagatorSettings_ private
Definition at line 837 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::MultiArcVariationalEquationsSolver(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::resetVariationalEquationsInterpolators(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
variationalOnlyIntegratorSettings_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< numerical_integrators::IntegratorSettings< double > > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::variationalOnlyIntegratorSettings_ private
Definition at line 840 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().
dynamicsStateDerivative_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< DynamicsStateDerivativeModel< TimeType, StateScalarType > > tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::dynamicsStateDerivative_ private
Object used to compute the full state derivative in equations of motion and variational equations, including relevant updates of environment from current state and time. Object may be used for either full or separate propagation of equations.
Definition at line 848 of file variationalEquationsSolver.h.
Referenced by tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateDynamicalEquationsOfMotionOnly(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::resetParameterEstimate(), and tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::SingleArcVariationalEquationsSolver().
The documentation for this class was generated from the following file:
SimulationSetup/EstimationSetup/variationalEquationsSolver.h