Tudat: tudat::simulation_setup::AccelerationLimitedThrottleGuidance Class Reference
tudat::simulation_setup::AccelerationLimitedThrottleGuidance Class Reference
Class to compute throttling law for the parameterized thrust magnitude, where the throttle is determined from a maximum, the user must provide the interpolator for the (maximum) thrust, as well as the associated physical meaning of the independent variables.
#include <thrustSettings.h>
Public Member Functions
AccelerationLimitedThrottleGuidance (const NamedBodyMap &bodyMap, const std::string nameOfBodyWithGuidance, const std::string nameOfCentralBody, const std::vector< propulsion::ThrustIndependentVariables > independentVariables, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustInterpolator, const double maximumAcceleration)
Constructor.
void updateGuidanceParameters ()
Function that updates the guidance algorithm to the current time/state: sets the throttle value based on axia.
Public Member Functions inherited from tudat::simulation_setup::ThrustInputParameterGuidance
ThrustInputParameterGuidance (const int numberOfThrustInputParameters, const int numberOfSpecificImpulseInputParameters, const bool includeThrottleSetting=false, const int throttleSettingIndex=-1)
Constructor.
virtual ~ThrustInputParameterGuidance ()
Destructor.
bool getIncludeThrottleSetting ()
Function to retrieve whether any of the guidance-input parameters for the thrust define a throttle setting.
int getNumberOfSpecificImpulseInputParameters ()
Function to retrieve the number of guidance-input parameters that are computed for the specific impulse.
int getNumberOfThrustInputParameters ()
Function to retrieve the number of guidance-input parameters that are computed for the thrust.
double getSpecificImpulseInputGuidanceParameter (const int inputParameterIndex)
Function to retrieve a guidance-input parameter that for the specific impulse.
int getThrottleSettingIndex ()
Function to retrieve the index in list of thrust guidance parameters that denotes the throttle setting.
double getThrustInputGuidanceParameter (const int inputParameterIndex)
Function to retrieve a guidance-input parameter that for the thrust.
void update (const double time)
Update function for the guidance algorithm.
Private Attributes
std::shared_ptr< simulation_setup::Body > bodyWithGuidance_
Body for which thrust guidance is used.
std::vector< double > currentThrustInput_
Pre-declared vector used as input to thrustInterpolator_.
double maximumAcceleration_
Maxmum allowable acceleration due to the thrust force.
std::vector< std::function< double() > > thrustInputFunctions_
Functions to compute the current entries of the input to thrustInterpolator_.
std::shared_ptr< interpolators::Interpolator< double, double > > thrustInterpolator_
Interpolator that computes the maximum thrust as a function of the independent variables.
Additional Inherited Members
Protected Attributes inherited from tudat::simulation_setup::ThrustInputParameterGuidance
std::vector< double > currentSpecificImpulseParameters_
Vector of guidance-input parameters that are computed for the specific impulse.
std::vector< double > currentThrustGuidanceParameters_
Vector of guidance-input parameters that are computed for the thrust.
double currentTime_
Current time of interface object (e.g. time to which object was last updated).
bool includeThrottleSetting_
Boolean that denotes whether any of the guidance-input parameters for the thrust define a throttle setting.
int numberOfSpecificImpulseInputParameters_
Number of guidance-input parameters that are computed for the specific impulse.
int numberOfThrustInputParameters_
Number of guidance-input parameters that are computed for the thrust.
int throttleSettingIndex_
Index in list of thrust guidance parameters that denotes the throttle setting (if any)
Detailed Description
Class to compute throttling law for the parameterized thrust magnitude, where the throttle is determined from a maximum axial g-load.
Also, a maximum axial acceleration must be provided. If the current thrust results in an acceleration less than this limit, the throttle is set to 1, if it is higher than the maximum, the throttle is set such that the acceleration is on this limit.
Definition at line 610 of file thrustSettings.h.
Constructor & Destructor Documentation
AccelerationLimitedThrottleGuidance()
tudat::simulation_setup::AccelerationLimitedThrottleGuidance::AccelerationLimitedThrottleGuidance (const NamedBodyMap & bodyMap, const std::string nameOfBodyWithGuidance, const std::string nameOfCentralBody, const std::vector< propulsion::ThrustIndependentVariables > independentVariables, const std::shared_ptr< interpolators::Interpolator< double, double > > thrustInterpolator, const double maximumAcceleration) inline
Constructor
Parameters
bodyMap List of pointers to body objects defining the full simulation environment.
nameOfBodyWithGuidance Name of body for which thrust guidance is to be created.
nameOfCentralBody Name of body w.r.t. which thrust guidance is computed (e.g. Earth if the altitude from Earth is used as an independent variable of the thrust).
independentVariables Physical meaning of each of the independent variables used as input to the thrustInterpolator.
thrustInterpolator Interpolator that computes the maximum thrust as a function of the independent variables.
maximumAcceleration Maxmum allowable acceleration due to the thrust force.
Definition at line 626 of file thrustSettings.h.
References bodyWithGuidance_, tudat::simulation_setup::createAtmosphericFlightConditions(), currentThrustInput_, tudat::simulation_setup::getPropulsionInputVariables(), tudat::propulsion::guidance_input_dependent_thrust, tudat::propulsion::throttle_dependent_thrust, and thrustInputFunctions_.
Member Function Documentation
updateGuidanceParameters()
void tudat::simulation_setup::AccelerationLimitedThrottleGuidance::updateGuidanceParameters () inline virtual
Function that updates the guidance algorithm to the current time/state: sets the throttle value based on axial acceleration when using the maximum thrust.
Implements tudat::simulation_setup::ThrustInputParameterGuidance.
Definition at line 681 of file thrustSettings.h.
References bodyWithGuidance_, tudat::simulation_setup::ThrustInputParameterGuidance::currentThrustGuidanceParameters_, currentThrustInput_, maximumAcceleration_, thrustInputFunctions_, and thrustInterpolator_.
Member Data Documentation
bodyWithGuidance_
std::shared_ptr< simulation_setup::Body > tudat::simulation_setup::AccelerationLimitedThrottleGuidance::bodyWithGuidance_ private
Definition at line 707 of file thrustSettings.h.
Referenced by AccelerationLimitedThrottleGuidance(), and updateGuidanceParameters().
thrustInterpolator_
std::shared_ptr< interpolators::Interpolator< double, double > > tudat::simulation_setup::AccelerationLimitedThrottleGuidance::thrustInterpolator_ private
Definition at line 710 of file thrustSettings.h.
Referenced by updateGuidanceParameters().
maximumAcceleration_
double tudat::simulation_setup::AccelerationLimitedThrottleGuidance::maximumAcceleration_ private
Definition at line 713 of file thrustSettings.h.
Referenced by updateGuidanceParameters().
thrustInputFunctions_
std::vector< std::function< double() > > tudat::simulation_setup::AccelerationLimitedThrottleGuidance::thrustInputFunctions_ private
Definition at line 716 of file thrustSettings.h.
Referenced by AccelerationLimitedThrottleGuidance(), and updateGuidanceParameters().
currentThrustInput_
std::vector< double > tudat::simulation_setup::AccelerationLimitedThrottleGuidance::currentThrustInput_ private
Definition at line 719 of file thrustSettings.h.
Referenced by AccelerationLimitedThrottleGuidance(), and updateGuidanceParameters().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/thrustSettings.h