Tudat: tudat::aerodynamics::TrimOrientationCalculator Class Reference
tudat::aerodynamics::TrimOrientationCalculator Class Reference
Class to determine the trimmed angle-of-attack for a given set of aerodynamic coefficients.
#include <trimOrientation.h>
Public Member Functions
TrimOrientationCalculator (const boost::shared_ptr< AerodynamicCoefficientInterface > coefficientInterface, const boost::shared_ptr< root_finders::RootFinderCore< double > > rootFinder=NULL)
Constructor.
double findTrimAngleOfAttack (const std::vector< double > untrimmedIndependentVariables, const std::map< std::string, std::vector< double > > untrimmedControlSurfaceIndependentVariables=std::map< std::string, std::vector< double > >())
Function to find the trimmed angle of attack for a given set of independent variables.
double findTrimAngleOfAttackFromFunction (const boost::function< std::vector< double >() > untrimmedIndependentVariablesFunction, const boost::function< std::map< std::string, std::vector< double > >() > untrimmedControlSurfaceIndependentVariablesFunction)
Function to find the trimmed angle of attack for a given set of independent variables.
Private Member Functions
double getPerturbedMomentCoefficient (const double perturbedAngleOfAttack, const std::vector< double > &unperturbedConditions, const std::map< std::string, std::vector< double > > unperturbedControlSurfaceIndependentVariables)
Function to get the moment coefficient for a given angle of attack.
Private Attributes
boost::shared_ptr< AerodynamicCoefficientInterface > coefficientInterface_
Object containing used to retrieve aerodynamic coefficients as function of independent variables.
std::map< std::string, int > controlSurfaceVariableIndex_
Index in list of each of the control surface interfaces corresponding to the angle of attack.
boost::shared_ptr< root_finders::RootFinderCore< double > > rootFinder_
int variableIndex_
Index in independent variable list of coefficientInterface_ corresponding to the angle of attack.
Detailed Description
Class to determine the trimmed angle-of-attack for a given set of aerodynamic coefficients. The coefficient interface provided as input must be dependent on the angle of attack for this class to function.
Definition at line 37 of file trimOrientation.h.
Constructor & Destructor Documentation
tudat::aerodynamics::TrimOrientationCalculator::TrimOrientationCalculator (const boost::shared_ptr< AerodynamicCoefficientInterface > coefficientInterface, const boost::shared_ptr< root_finders::RootFinderCore< double > > rootFinder = NULL)
Constructor
Parameters
coefficientInterface Object containing used to retrieve aerodynamic coefficients as function of independent variables.
rootFinder Object to iteratively find the root of the equations C_m(alpha)=0, i.e. to determine the angle of attack for which the pitch moment is zero.
Definition at line 23 of file trimOrientation.cpp.
References tudat::aerodynamics::angle_of_attack_dependent, controlSurfaceVariableIndex_, tudat::mathematical_constants::E, rootFinder_, and variableIndex_.
Member Function Documentation
double tudat::aerodynamics::TrimOrientationCalculator::findTrimAngleOfAttack (const std::vector< double > untrimmedIndependentVariables, const std::map< std::string, std::vector< double > > untrimmedControlSurfaceIndependentVariables = std::map< std::string, std::vector< double > >())
Function to find the trimmed angle of attack for a given set of independent variables. This function iteratively changes the angle of attack in the untrimmedIndependentVariables vector (keeping any other variables the same) and returns the value of the trimmed angle of attack. Note that this function will typically have some small numerical error in the result, as a result of the error tolerances in the root finder.
Parameters
untrimmedIndependentVariables Untrimmed list of independent variables (in order required as input for coefficientInterface_)
untrimmedControlSurfaceIndependentVariables Untrimmed list of independent variables for control surfaces with map key denoting the control surface name (in order required as input for coefficient interfaces)
Returns
Trimmed angle of attack.
Definition at line 77 of file trimOrientation.cpp.
References getPerturbedMomentCoefficient(), rootFinder_, TUDAT_NAN, and variableIndex_.
Referenced by findTrimAngleOfAttackFromFunction().
double tudat::aerodynamics::TrimOrientationCalculator::findTrimAngleOfAttackFromFunction (const boost::function< std::vector< double >() > untrimmedIndependentVariablesFunction, const boost::function< std::map< std::string, std::vector< double > >() > untrimmedControlSurfaceIndependentVariablesFunction) inline
Function to find the trimmed angle of attack for a given set of independent variables. This function iteratively changes the angle of attack in the untrimmedIndependentVariables vector (keeping any other variables the same) and returns the value of the trimmed angle of attack. Note that this function will typically have some small numerical error in the result, as a result of the error tolerances in the root finder.
Parameters
untrimmedIndependentVariablesFunction Function returning untrimmed list of independent variables (in order required as input for coefficientInterface_
untrimmedControlSurfaceIndependentVariablesFunction Function returning untrimmed list of independent variables for control surfaces with map key denoting the control surface name (in order required as input for coefficient interfaces)
Returns
Trimmed angle of attack.
Definition at line 83 of file trimOrientation.h.
References findTrimAngleOfAttack(), and getPerturbedMomentCoefficient().
Referenced by tudat::simulation_setup::setTrimmedConditions(), and tudat::aerodynamics::setTrimmedConditions().
double tudat::aerodynamics::TrimOrientationCalculator::getPerturbedMomentCoefficient (const double perturbedAngleOfAttack, const std::vector< double > & unperturbedConditions, const std::map< std::string, std::vector< double > > unperturbedControlSurfaceIndependentVariables) private
Function to get the moment coefficient for a given perturbed angle of attack, keeping all other independent variables constant. This function is used as input to the root finder to determine the trim point.
Parameters
perturbedAngleOfAttack Angle of attack to use
unperturbedConditions Untrimmed list of independent variables (in order required as input for coefficientInterface_
unperturbedControlSurfaceIndependentVariables Untrimmed list of independent variables for control surfaces with map key denoting the control surface name (in order required as input for coefficient interfaces)
Returns
Moment coefficient at given independent variables.
Definition at line 107 of file trimOrientation.cpp.
References coefficientInterface_, controlSurfaceVariableIndex_, and variableIndex_.
Referenced by findTrimAngleOfAttack(), and findTrimAngleOfAttackFromFunction().
Member Data Documentation
boost::shared_ptr< AerodynamicCoefficientInterface > tudat::aerodynamics::TrimOrientationCalculator::coefficientInterface_ private
Definition at line 111 of file trimOrientation.h.
Referenced by getPerturbedMomentCoefficient().
boost::shared_ptr< root_finders::RootFinderCore< double > > tudat::aerodynamics::TrimOrientationCalculator::rootFinder_ private
Object to iteratively find the root of the equations C_m(alpha)=0, i.e. to determine the angle of attack for which the pitch moment is zero.
Definition at line 115 of file trimOrientation.h.
Referenced by findTrimAngleOfAttack(), and TrimOrientationCalculator().
int tudat::aerodynamics::TrimOrientationCalculator::variableIndex_ private
Definition at line 118 of file trimOrientation.h.
Referenced by findTrimAngleOfAttack(), getPerturbedMomentCoefficient(), and TrimOrientationCalculator().
std::map< std::string, int > tudat::aerodynamics::TrimOrientationCalculator::controlSurfaceVariableIndex_ private
Definition at line 121 of file trimOrientation.h.
Referenced by getPerturbedMomentCoefficient(), and TrimOrientationCalculator().
The documentation for this class was generated from the following files:
Astrodynamics/Aerodynamics/trimOrientation.h
Astrodynamics/Aerodynamics/trimOrientation.cpp