Tudat: tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType > Class Template Reference
tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType > Class Template Reference abstract
Base class for (translational) acceleration models.
#include <accelerationModel.h>
Public Member Functions
AccelerationModel ()
Constructor.
virtual ~AccelerationModel ()
Virtual destructor.
virtual AccelerationDataType getAcceleration ()=0
Get acceleration.
virtual void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the current time.
virtual void updateMembers (const double currentTime=TUDAT_NAN)=0
Update member variables used by the acceleration model.
Protected Attributes
double currentTime_
Previous time to which acceleration model was updated.
Detailed Description
template<typename AccelerationDataType = Eigen::Vector3d>
class tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >
Base class for (translational) acceleration models. Derived classes should contain implementations to perform calculations of accelerations. Therefore, the getAcceleration() function has no arguments.
Template Parameters
AccelerationDataType Data type used to represent accelerations (default=Eigen::Vector3d).
Definition at line 39 of file accelerationModel.h.
Constructor & Destructor Documentation
template<typename AccelerationDataType = Eigen::Vector3d> tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >::AccelerationModel () inline
Definition at line 45 of file accelerationModel.h.
template<typename AccelerationDataType = Eigen::Vector3d> virtual tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >::~AccelerationModel () inline virtual
Virtual destructor, necessary to ensure that derived class destructors get called correctly.
Definition at line 52 of file accelerationModel.h.
Member Function Documentation
template<typename AccelerationDataType = Eigen::Vector3d> virtual AccelerationDataType tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >::getAcceleration () pure virtual
Returns the acceleration. No arguments are passed to this function for generality. Instead, all data required for computation is to be obtained from pointers to functions/ classes/structs, etc which are to be set in a derived class and evaluated by the updateMembers() function below.
Returns
Acceleration.
See also
updateMembers().
Implemented in tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel, tudat::relativity::RelativisticAccelerationCorrection, tudat::gravitation::CentralGravitationalAccelerationModel< StateMatrix >, tudat::reference_frames::ApparentAccelerationModel, tudat::gravitation::MutualSphericalHarmonicsGravitationalAccelerationModel, tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel, tudat::aerodynamics::AerodynamicAcceleration, tudat::electro_magnetism::CannonBallRadiationPressureAcceleration, tudat::gravitation::CentralJ2J3GravitationalAccelerationModel, tudat::basic_astrodynamics::EmpiricalAcceleration, tudat::gravitation::CentralJ2GravitationalAccelerationModel, tudat::gravitation::ThirdBodyAcceleration< DirectAccelerationModelType >, and tudat::propulsion::ThrustAcceleration.
Referenced by tudat::propagators::getDoubleDependentVariableFunction(), tudat::propagators::getVectorDependentVariableFunction(), and tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >::~AccelerationModel().
template<typename AccelerationDataType = Eigen::Vector3d> virtual void tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >::updateMembers (const double currentTime = TUDAT_NAN) pure virtual
Updates member variables used by the acceleration model. In the case of acceleration models containing varying parameters, function-pointers returning such a parameter (for instance the Cartesian state of a body) will be set as a member variable. This function evaluates such function-pointers and updates member variables to the 'current' values of these parameters. Only these current values, not the function-pointers are then used by the getAcceleration() function.
N.B.: This pure virtual function must be overridden by derived classes!
Parameters
currentTime Time at which acceleration model is to be updated.
Implemented in tudat::gravitation::SphericalHarmonicsGravitationalAccelerationModel, tudat::relativity::RelativisticAccelerationCorrection, tudat::gravitation::CentralGravitationalAccelerationModel< StateMatrix >, tudat::reference_frames::ApparentAccelerationModel, tudat::gravitation::CentralJ2J3J4GravitationalAccelerationModel, tudat::aerodynamics::AerodynamicAcceleration, tudat::electro_magnetism::CannonBallRadiationPressureAcceleration, tudat::gravitation::MutualSphericalHarmonicsGravitationalAccelerationModel, tudat::gravitation::CentralJ2J3GravitationalAccelerationModel, tudat::basic_astrodynamics::EmpiricalAcceleration, tudat::gravitation::CentralJ2GravitationalAccelerationModel, tudat::propulsion::ThrustAcceleration, and tudat::gravitation::ThirdBodyAcceleration< DirectAccelerationModelType >.
Referenced by tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >::~AccelerationModel().
template<typename AccelerationDataType = Eigen::Vector3d> virtual void tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >::resetTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the current time of the acceleration model.
Parameters
currentTime Current time (default NaN).
Reimplemented in tudat::gravitation::MutualSphericalHarmonicsGravitationalAccelerationModel, tudat::gravitation::ThirdBodyAcceleration< DirectAccelerationModelType >, and tudat::propulsion::ThrustAcceleration.
Definition at line 84 of file accelerationModel.h.
Member Data Documentation
template<typename AccelerationDataType = Eigen::Vector3d> double tudat::basic_astrodynamics::AccelerationModel< AccelerationDataType >::currentTime_ protected
Definition at line 92 of file accelerationModel.h.
Referenced by tudat::basic_astrodynamics::AccelerationModel< Eigen::Vector3d >::resetTime(), and tudat::electro_magnetism::CannonBallRadiationPressureAcceleration::updateMembers().
The documentation for this class was generated from the following file:
Astrodynamics/BasicAstrodynamics/accelerationModel.h