Tudat: tudat::propulsion::ThrustMagnitudeWrapper Class Reference
tudat::propulsion::ThrustMagnitudeWrapper Class Reference abstract
Base class for determining the current thrust magnitude from method defined in derived class.
#include <thrustMagnitudeWrapper.h>
Public Member Functions
ThrustMagnitudeWrapper ()
Constructor.
virtual ~ThrustMagnitudeWrapper ()
Destructor.
virtual double getCurrentMassRate ()=0
Pure virtual function to get the current mass rate.
virtual double getCurrentThrustMagnitude ()=0
Pure virtual function to get the current thrust magnitude.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the thrust model.
virtual void resetDerivedClassCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the thrust model derived class.
virtual void update (const double time)=0
Pure virtual function to update the thrust magnitude to the current time.
Protected Attributes
double currentTime_
Current time for model.
Detailed Description
Definition at line 28 of file thrustMagnitudeWrapper.h.
Constructor & Destructor Documentation
tudat::propulsion::ThrustMagnitudeWrapper::ThrustMagnitudeWrapper () inline
Definition at line 33 of file thrustMagnitudeWrapper.h.
virtual tudat::propulsion::ThrustMagnitudeWrapper::~ThrustMagnitudeWrapper () inline virtual
Definition at line 37 of file thrustMagnitudeWrapper.h.
References getCurrentMassRate(), getCurrentThrustMagnitude(), and update().
Member Function Documentation
virtual void tudat::propulsion::ThrustMagnitudeWrapper::update (const double time) pure virtual
Pure virtual function to update the thrust magnitude to the current time. Method of computation is to be implemented in the derived class.
Parameters
time Time at which the magitude is to be computed.
Implemented in tudat::propulsion::ParameterizedThrustMagnitudeWrapper, tudat::propulsion::ThrustMagnitudeFromEngineWrapper, and tudat::propulsion::CustomThrustMagnitudeWrapper.
Referenced by ~ThrustMagnitudeWrapper().
virtual double tudat::propulsion::ThrustMagnitudeWrapper::getCurrentThrustMagnitude () pure virtual
Pure virtual function to get the current thrust magnitude.
Returns
Current thrust magnitude.
Implemented in tudat::propulsion::ParameterizedThrustMagnitudeWrapper, tudat::propulsion::ThrustMagnitudeFromEngineWrapper, and tudat::propulsion::CustomThrustMagnitudeWrapper.
Referenced by tudat::simulation_setup::createThrustAcceleratioModel(), and ~ThrustMagnitudeWrapper().
virtual double tudat::propulsion::ThrustMagnitudeWrapper::getCurrentMassRate () pure virtual
Pure virtual function to get the current mass rate.
Returns
Current mass rate.
Implemented in tudat::propulsion::ParameterizedThrustMagnitudeWrapper, tudat::propulsion::ThrustMagnitudeFromEngineWrapper, and tudat::propulsion::CustomThrustMagnitudeWrapper.
Referenced by tudat::simulation_setup::createThrustAcceleratioModel(), and ~ThrustMagnitudeWrapper().
void tudat::propulsion::ThrustMagnitudeWrapper::resetCurrentTime (const double currentTime = TUDAT_NAN) inline
Function to reset the current time of the thrust model. Function is typically used to reset the time to NaN, signalling the need for a recomputation of all required quantities.
Parameters
currentTime New current time to be set in model.
Definition at line 67 of file thrustMagnitudeWrapper.h.
References currentTime_, and resetDerivedClassCurrentTime().
virtual void tudat::propulsion::ThrustMagnitudeWrapper::resetDerivedClassCurrentTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the current time of the thrust model derived class. Function is typically used to reset the time to NaN, signalling the need for a recomputation of all required quantities. This function can be redefined in derived class
Parameters
currentTime New current time to be set in model.
Reimplemented in tudat::propulsion::ParameterizedThrustMagnitudeWrapper, and tudat::propulsion::CustomThrustMagnitudeWrapper.
Definition at line 80 of file thrustMagnitudeWrapper.h.
Referenced by resetCurrentTime().
Member Data Documentation
double tudat::propulsion::ThrustMagnitudeWrapper::currentTime_ protected
Definition at line 89 of file thrustMagnitudeWrapper.h.
Referenced by resetCurrentTime(), tudat::propulsion::CustomThrustMagnitudeWrapper::update(), tudat::propulsion::ThrustMagnitudeFromEngineWrapper::update(), and tudat::propulsion::ParameterizedThrustMagnitudeWrapper::update().
The documentation for this class was generated from the following file:
Astrodynamics/Propulsion/thrustMagnitudeWrapper.h