Tudat: tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType > Class Template Reference
tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType > Class Template Reference
Object to calculate the short period variations in Earth orientaion parameters.
#include <shortPeriodEarthOrientationCorrectionCalculator.h>
Public Member Functions
ShortPeriodEarthOrientationCorrectionCalculator (const double conversionFactor, const double minimumAmplitude, const std::vector< std::string > &amplitudesFiles, const std::vector< std::string > &argumentMultipliersFile, const std::function< Eigen::Vector6d(const double) > argumentFunction=std::bind(&sofa_interface::calculateApproximateDelaunayFundamentalArgumentsWithGmst, std::placeholders::_1))
Constructor, requires files defining the amplitudes and fundamental argument multipliers of the variations.
OutputType getCorrections (const double &ephemerisTime)
Function to obtain short period corrections.
OutputType getCorrections (const Eigen::Vector6d &fundamentalArguments)
Function to obtain short period corrections.
Private Member Functions
template<>
double sumCorrectionTerms (const Eigen::Vector6d &arguments)
Function to sum all the corrcetion terms.
template<>
Eigen::Vector2d sumCorrectionTerms (const Eigen::Vector6d &arguments)
Function to sum all the corrcetion terms.
OutputType sumCorrectionTerms (const Eigen::Vector6d &arguments)
Function to sum all the corrcetion terms.
Private Attributes
std::vector< Eigen::MatrixXd > argumentAmplitudes_
Amplitudes of libration-induced variations.
std::function< Eigen::Vector6d(const double) > argumentFunction_
Fundamental argument functions associated with multipliers.
std::vector< Eigen::MatrixXd > argumentMultipliers_
Fundamental argument multipliers of libration-induced variations.
Detailed Description
template<typename OutputType>
class tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >
Object to calculate the short period variations in Earth orientaion parameters, e.g. taking into account variations due to both libration and ocean tides.
Definition at line 47 of file shortPeriodEarthOrientationCorrectionCalculator.h.
Constructor & Destructor Documentation
ShortPeriodEarthOrientationCorrectionCalculator()
template<typename OutputType > tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::ShortPeriodEarthOrientationCorrectionCalculator (const double conversionFactor, const double minimumAmplitude, const std::vector< std::string > & amplitudesFiles, const std::vector< std::string > & argumentMultipliersFile, const std::function< Eigen::Vector6d(const double) > argumentFunction = std::bind(&sofa_interface::calculateApproximateDelaunayFundamentalArgumentsWithGmst, std::placeholders::_1)) inline
Constructor, requires files defining the sine and cosine amplitudes and fundamental argument multipliers numbers of the variations for both ocean tide and libration variations. A cut-off amplitude (taken as the RSS of the amplitudes) below which amplitudes in the files are ignored can be provided.
Parameters
conversionFactor Conversion factor to be used for amplitudes, used to multiply input values, typically for unit conversion purposes.
minimumAmplitude Minimum amplitude that is read from files and considered in calculations.
amplitudesFiles List of files with amplitudes for corrections
argumentMultipliersFile Fundamental argument multiplier for corrections
argumentFunction Fundamental argument functions associated with multipliers, default Delaunay arguments with GMST
Definition at line 62 of file shortPeriodEarthOrientationCorrectionCalculator.h.
References tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::argumentAmplitudes_, tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::argumentMultipliers_, and tudat::earth_orientation::readAmplitudesAndFundamentalArgumentMultipliers().
Member Function Documentation
getCorrections() [1/2]
template<typename OutputType > OutputType tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::getCorrections (const double & ephemerisTime) inline
Function to obtain short period corrections, using time as input. Fundamental arguments are calculated internally.
Parameters
ephemerisTime Time (TDB seconds since J2000) at which corretions are to be determined
Returns
Short period corrections
Definition at line 93 of file shortPeriodEarthOrientationCorrectionCalculator.h.
References tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::argumentFunction_, and tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::sumCorrectionTerms().
getCorrections() [2/2]
template<typename OutputType > OutputType tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::getCorrections (const Eigen::Vector6d & fundamentalArguments) inline
Function to obtain short period corrections, using fundamental arguments as input.
Parameters
fundamentalArguments Fundamental arguments from which corretions are to be determined
Returns
Short period corrections
Definition at line 104 of file shortPeriodEarthOrientationCorrectionCalculator.h.
References tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::sumCorrectionTerms().
sumCorrectionTerms() [1/3]
template<typename OutputType > OutputType tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::sumCorrectionTerms (const Eigen::Vector6d & arguments) private
Function to sum all the corrcetion terms.
Parameters
arguments Values of fundamental arguments
Returns
Total correction at current fundamental arguments
Referenced by tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::getCorrections().
sumCorrectionTerms() [2/3]
template<> double tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< double >::sumCorrectionTerms (const Eigen::Vector6d & arguments) private
Definition at line 22 of file shortPeriodEarthOrientationCorrectionCalculator.cpp.
sumCorrectionTerms() [3/3]
template<> Eigen::Vector2d tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< Eigen::Vector2d >::sumCorrectionTerms (const Eigen::Vector6d & arguments) private
Definition at line 52 of file shortPeriodEarthOrientationCorrectionCalculator.cpp.
Member Data Documentation
argumentAmplitudes_
template<typename OutputType > std::vector< Eigen::MatrixXd > tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::argumentAmplitudes_ private
Definition at line 120 of file shortPeriodEarthOrientationCorrectionCalculator.h.
Referenced by tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::ShortPeriodEarthOrientationCorrectionCalculator().
argumentMultipliers_
template<typename OutputType > std::vector< Eigen::MatrixXd > tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::argumentMultipliers_ private
Definition at line 123 of file shortPeriodEarthOrientationCorrectionCalculator.h.
Referenced by tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::ShortPeriodEarthOrientationCorrectionCalculator().
argumentFunction_
template<typename OutputType > std::function< Eigen::Vector6d(const double) > tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::argumentFunction_ private
Definition at line 126 of file shortPeriodEarthOrientationCorrectionCalculator.h.
Referenced by tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::getCorrections().
The documentation for this class was generated from the following file:
Astrodynamics/EarthOrientation/shortPeriodEarthOrientationCorrectionCalculator.h