Tudat: tudat::ephemerides Namespace Reference
tudat::ephemerides Namespace Reference
Classes
class ApproximatePlanetPositions
Ephemeris class using JPL "Approximate Positions of Major Planets".
class ApproximatePlanetPositionsBase
Ephemeris base class using JPL "Approximate Positions of Major Planets".
class ApproximatePlanetPositionsCircularCoplanar
Ephemeris class for circular, coplanar orbits using Approximate Positions of Major Planets.
struct ApproximatePlanetPositionsDataContainer
JPL "Approximate Positions of Major Planets" data container class.
class CartesianStateExtractor
Cartesian State extractor class.
class CompositeEphemeris
Class that combines a series of translational and rotational ephemeris functions.
class ConstantEphemeris
Ephemeris class that gives a constant (i.e. time independent) state.
class CustomEphemeris
Ephemeris class that gives a custom (i.e. arbitrarily defined as a function of time) state.
class Ephemeris
Ephemeris base class.
class KeplerEphemeris
Ephemeris derived class that calculates the Cartesian position as a function of time assuming a Kepler orbit.
class KeplerStateExtractor
Keplerian State extractor class.
class MultiArcEphemeris
Class to define an ephemeris in an arc-wise manner.
class ReferenceFrameManager
Class to retrieve translation functions between different frames.
class RotationalEphemeris
Base class for rotational ephemerides of bodies.
class SimpleRotationalEphemeris
Class to model the rotation of bodies with constant rotation axis and rate.
class SpiceEphemeris
Ephemeris derived class which retrieves the state of a body directly from the SPICE library.
class SpiceRotationalEphemeris
Class to directly calculate rotational state of body from spice kernel(s)
class TabulatedCartesianEphemeris
Class that determines an ephemeris from tabulated data.
class TabulatedRotationalEphemeris
Class that computes the current rotational state from tabulated values of the rotational state with the use of an interpolator.
Typedefs
typedef std::shared_ptr< ApproximatePlanetPositionsBase > ApproximatePlanetPositionsBasePointer
Typedef for shared-pointer to ApproximatePlanetPositionsBase object.
typedef std::shared_ptr< ApproximatePlanetPositionsCircularCoplanar > ApproximatePlanetPositionsCircularCoplanarPointer
Typedef for shared-pointer to ApproximatePlanetPositionsCircularCoplanar object.
typedef std::shared_ptr< ApproximatePlanetPositionsDataContainer > ApproximatePlanetPositionsDataContainerPointer
Typedef for shared-pointer to ApproximatePlanetPositionsDataContainer object.
typedef std::shared_ptr< ApproximatePlanetPositions > ApproximatePlanetPositionsPointer
Typedef for shared-pointer to ApproximatePlanetPositions object.
typedef std::shared_ptr< CartesianStateExtractor > CartesianStateExtractorPointer
Typedef for shared-pointer to CartesianStateExtractor object.
typedef std::shared_ptr< Ephemeris > EphemerisPointer
Typedef for shared-pointer to Ephemeris object.
typedef std::shared_ptr< KeplerStateExtractor > KeplerStateExtractorPointer
Typedef for shared-pointer to KeplerStateExtractor object.
Functions
template<typename OldStateScalarType , typename NewStateScalarType , typename TimeType , int StateSize>
Eigen::Matrix< NewStateScalarType, StateSize, 1 > convertStateFunctionStateScalarOutput (const std::function< Eigen::Matrix< OldStateScalarType, StateSize, 1 >(const double &) > originalStateFunction, const TimeType currentTime)
Interface function used to change the state scalar type of the output of a state function.
template<typename StateScalarType = double, typename TimeType = double>
std::shared_ptr< Ephemeris > createEmptyTabulatedEphemeris (const std::string referenceFrameOrigin="SSB", const std::string referenceFrameOrientation="ECLIPJ2000")
Function to create an empty (dummy) tabulated ephemeris.
template<typename TimeType = double, typename StateScalarType = double>
std::shared_ptr< Ephemeris > createReferencePointEphemeris (std::shared_ptr< Ephemeris > bodyEphemeris, std::shared_ptr< RotationalEphemeris > bodyRotationModel, std::function< Eigen::Vector6d(const double &) > referencePointRelativeStateFunction)
Function to create the state function of a reference point.
void from_json (const nlohmann::json &jsonObject, ApproximatePlanetPositionsBase::BodiesWithEphemerisData &bodyWithEphemerisData)
Convert json to ApproximatePlanetPositionsBase::BodiesWithEphemerisData.
std::string getBaseFrameName ()
Function to return base frame.
Eigen::Matrix3d getDerivativeOfRotationMatrixToFrame (const Eigen::Matrix3d &rotationToTargetFrame, const Eigen::Vector3d &rotationalVelocityVectorOfTargetFrameInBaseFrame)
Function to calculate the time derivative of rotation matrix from frame A to frame B.
void getRelativeState (Eigen::Vector6d &relativeState, const std::function< Eigen::Vector6d() > stateFunctionOfBody, const std::function< Eigen::Vector6d() > stateFunctionOfCentralBody)
Function to compute the relative state from two state functions.
Eigen::Vector3d getRotationalVelocityVectorInBaseFrameFromMatrices (const Eigen::Matrix3d &rotationToTargetFrame, const Eigen::Matrix3d &rotationMatrixToGlobalFrameDerivative)
Function to calculate the rotational velocity vector of frame B w.r.t frame A.
std::pair< double, double > getTabulatedEphemerisSafeInterval (const std::shared_ptr< Ephemeris > ephemeris)
Function that retrieves the time interval at which a tabulated ephemeris can be safely interrogated.
template<typename StateScalarType = double, typename TimeType = double>
std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 > const TimeType) > > getTranslationFunctionsFromIntegrationFrameToEphemerisFrame (const std::vector< std::string > &centralBodies, const std::vector< std::string > &bodiesToIntegrate, const std::shared_ptr< ephemerides::ReferenceFrameManager > frameManager)
Function to get a list of translation functions from integration frames to ephemeris frames.
bool isFrameInertial (const std::string &frame)
Function to determine if a given frame is an inertial frame.
bool isTabulatedEphemeris (const std::shared_ptr< Ephemeris > ephemeris)
Function to check whether an ephemeris is a (type of) tabulated ephemeris.
void to_json (nlohmann::json &jsonObject, const ApproximatePlanetPositionsBase::BodiesWithEphemerisData &bodyWithEphemerisData)
Convert ApproximatePlanetPositionsBase::BodiesWithEphemerisData to json.
template<typename StateScalarType >
Eigen::Matrix< StateScalarType, 6, 1 > transformRelativeStateToFrame (const std::function< Eigen::Matrix< StateScalarType, 6, 1 >() > stateInBaseFrame, const std::function< Eigen::Matrix< StateScalarType, 6, 1 >() > centralBodyStateInBaseFrame, const std::function< Eigen::Quaterniond() > rotationToFrameFunction, const std::function< Eigen::Matrix3d() > rotationMatrixToFrameDerivativeFunction)
Transform a relative state (Cartesian position and velocity) from one frame to another.
template<typename StateScalarType >
Eigen::Matrix< StateScalarType, 6, 1 > transformStateToFrameFromRotationFunctions (const Eigen::Matrix< StateScalarType, 6, 1 > &stateInBaseFrame, const std::function< Eigen::Quaterniond() > rotationToFrameFunction, const std::function< Eigen::Matrix3d() > rotationMatrixToFrameDerivativeFunction)
Transform a state (Cartesian position and velocity) from one frame to another.
template<typename StateScalarType >
Eigen::Matrix< StateScalarType, 6, 1 > transformStateToFrameFromRotations (const Eigen::Matrix< StateScalarType, 6, 1 > &stateInBaseFrame, const Eigen::Quaterniond &rotationToFrame, const Eigen::Matrix3d &rotationMatrixToFrameDerivative)
Transform a state (Cartesian position and velocity) from one frame to another.
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > transformStateToFrameFromRotationTimeFunctions (const Eigen::Matrix< StateScalarType, 6, 1 > &stateInBaseFrame, const double currentTime, const std::function< Eigen::Quaterniond(const TimeType) > rotationToFrameFunction, const std::function< Eigen::Matrix3d(const TimeType) > rotationMatrixToFrameDerivativeFunction)
Transform a state (Cartesian position and velocity) from one frame to another.
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > transformStateToGlobalFrame (const Eigen::Matrix< StateScalarType, 6, 1 > &stateInLocalFrame, const TimeType currentTime, const std::shared_ptr< RotationalEphemeris > rotationalEphemeris)
Function to transform a state from the target to base frame of a rotational ephemeris.
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > transformStateToTargetFrame (const Eigen::Matrix< StateScalarType, 6, 1 > &stateInGlobalFrame, const TimeType currentTime, const std::shared_ptr< RotationalEphemeris > rotationalEphemeris)
Function to transform a state from the base to target frame of a rotational ephemeris.
Variables
static std::map< ApproximatePlanetPositionsBase::BodiesWithEphemerisData, std::string > bodiesWithEphemerisData
Map of ApproximatePlanetPositionsBase::BodiesWithEphemerisDatas string representations.
static std::vector< ApproximatePlanetPositionsBase::BodiesWithEphemerisData > unsupportedBodiesWithEphemerisData = { }
ApproximatePlanetPositionsBase::BodiesWithEphemerisData not supported by json_interface.
Typedef Documentation
ApproximatePlanetPositionsPointer
typedef std::shared_ptr< ApproximatePlanetPositions > tudat::ephemerides::ApproximatePlanetPositionsPointer
Definition at line 117 of file approximatePlanetPositions.h.
ApproximatePlanetPositionsBasePointer
typedef std::shared_ptr< ApproximatePlanetPositionsBase > tudat::ephemerides::ApproximatePlanetPositionsBasePointer
Definition at line 165 of file approximatePlanetPositionsBase.h.
ApproximatePlanetPositionsCircularCoplanarPointer
typedef std::shared_ptr< ApproximatePlanetPositionsCircularCoplanar > tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanarPointer
Definition at line 94 of file approximatePlanetPositionsCircularCoplanar.h.
ApproximatePlanetPositionsDataContainerPointer
typedef std::shared_ptr< ApproximatePlanetPositionsDataContainer > tudat::ephemerides::ApproximatePlanetPositionsDataContainerPointer
Definition at line 234 of file approximatePlanetPositionsDataContainer.h.
CartesianStateExtractorPointer
typedef std::shared_ptr< CartesianStateExtractor > tudat::ephemerides::CartesianStateExtractorPointer
Definition at line 52 of file cartesianStateExtractor.h.
EphemerisPointer
typedef std::shared_ptr< Ephemeris > tudat::ephemerides::EphemerisPointer
Definition at line 150 of file ephemeris.h.
KeplerStateExtractorPointer
typedef std::shared_ptr< KeplerStateExtractor > tudat::ephemerides::KeplerStateExtractorPointer
Definition at line 56 of file keplerStateExtractor.h.
Function Documentation
convertStateFunctionStateScalarOutput()
template<typename OldStateScalarType , typename NewStateScalarType , typename TimeType , int StateSize> Eigen::Matrix< NewStateScalarType, StateSize, 1 > tudat::ephemerides::convertStateFunctionStateScalarOutput (const std::function< Eigen::Matrix< OldStateScalarType, StateSize, 1 >(const double &) > originalStateFunction, const TimeType currentTime)
Interface function used to change the state scalar type of the output of a state function
Parameters
originalStateFunction State function with original scalar type
currentTime Time at which state function is to be evaluated.
Returns
State from originalStateFunction at currentTime, cast to NewStateScalarType.
Definition at line 335 of file compositeEphemeris.h.
createReferencePointEphemeris()
template<typename TimeType = double, typename StateScalarType = double> std::shared_ptr< Ephemeris > tudat::ephemerides::createReferencePointEphemeris (std::shared_ptr< Ephemeris > bodyEphemeris, std::shared_ptr< RotationalEphemeris > bodyRotationModel, std::function< Eigen::Vector6d(const double &) > referencePointRelativeStateFunction)
Function to create the state function of a reference point, for instance the state of a ground station in a barycentric frame.
Parameters
bodyEphemeris Global ephemeris of body on which reference point is located
bodyRotationModel Rotation model between global and body-fixed frame
referencePointRelativeStateFunction Function returning the body-fixed state of the reference point as a function of time
Returns
Ephemeris describbing the state of the local reference point in the global frame (expressed global frame's coordinates, i.e. same as bodyEphemeris).
Definition at line 355 of file compositeEphemeris.h.
getRelativeState()
void tudat::ephemerides::getRelativeState (Eigen::Vector6d & relativeState, const std::function< Eigen::Vector6d() > stateFunctionOfBody, const std::function< Eigen::Vector6d() > stateFunctionOfCentralBody)
Function to compute the relative state from two state functions.
Parameters
relativeState Relative state returned by stateFunctionOfBody w.r.t. state returned by stateFunctionOfCentralBody (returned by reference).
stateFunctionOfBody Function returning state of body for which relative state is to be computed.
stateFunctionOfCentralBody Function returning state of central body w.r.t. which the relative state is to be computed.
Definition at line 48 of file ephemeris.cpp.
Referenced by tudat::simulation_setup::createThrustGuidanceModel().
getBaseFrameName()
std::string tudat::ephemerides::getBaseFrameName ()
Function to return base frame, i.e. in which the states of the bodies are defined during the integration.
Returns
Base frame for simulations.
Definition at line 18 of file frameManager.cpp.
Referenced by tudat::ephemerides::ReferenceFrameManager::getNearestCommonFrame(), tudat::ephemerides::ReferenceFrameManager::ReferenceFrameManager(), and tudat::ephemerides::ReferenceFrameManager::setEphemerides().
isFrameInertial()
bool tudat::ephemerides::isFrameInertial (const std::string & frame)
Function to determine if a given frame is an inertial frame. Currently a frame identified as "SSB" (solar system barycenter), "inertial" or "" (empty) is recognized as inertial.
Parameters
frame Name of frame for which it is to be determined whether it is inertial.
Returns
True if inertial, false if not.
Definition at line 24 of file frameManager.cpp.
Referenced by tudat::simulation_setup::createAccelerationModelsMap(), tudat::simulation_setup::createGravitationalAccelerationModel(), tudat::simulation_setup::createThrustAcceleratioModel(), and tudat::propagators::getVectorDependentVariableFunction().
getTranslationFunctionsFromIntegrationFrameToEphemerisFrame()
template<typename StateScalarType = double, typename TimeType = double> std::map< std::string, std::function< Eigen::Matrix< StateScalarType, 6, 1 > const TimeType) > > tudat::ephemerides::getTranslationFunctionsFromIntegrationFrameToEphemerisFrame (const std::vector< std::string > & centralBodies, const std::vector< std::string > & bodiesToIntegrate, const std::shared_ptr< ephemerides::ReferenceFrameManager > frameManager)
Function to get a list of translation functions from integration frames to ephemeris frames. The output functions provide the state of the ephemeris origin in the integration origin.
Parameters
centralBodies List of integration origins.
bodiesToIntegrate List of bodies for which the origins are considered.
frameManager Object to retrieve translations between origins
Returns
List of translation functions from integration frames to ephemeris frames.
Definition at line 253 of file frameManager.h.
Referenced by tudat::propagators::TranslationalStateIntegratedStateProcessor< TimeType, StateScalarType >::TranslationalStateIntegratedStateProcessor().
getRotationalVelocityVectorInBaseFrameFromMatrices()
Eigen::Vector3d tudat::ephemerides::getRotationalVelocityVectorInBaseFrameFromMatrices (const Eigen::Matrix3d & rotationToTargetFrame, const Eigen::Matrix3d & rotationMatrixToGlobalFrameDerivative)
Function to calculate the rotational velocity vector of frame B (local) w.r.t frame A (global) from the rotation matrix between the frames, as well as its time derivative.
Parameters
rotationToTargetFrame Rotation matrix from frame A to frame B.
rotationMatrixToGlobalFrameDerivative Time derivative if rotation matrix from frame B to frame A.
Returns
Angular velocity vector of frame B, expressed in frame A.
Definition at line 20 of file rotationalEphemeris.cpp.
Referenced by tudat::ephemerides::SpiceRotationalEphemeris::getFullRotationalQuantitiesToTargetFrame(), tudat::ephemerides::RotationalEphemeris::getFullRotationalQuantitiesToTargetFrame(), tudat::ephemerides::RotationalEphemeris::getFullRotationalQuantitiesToTargetFrameFromExtendedTime(), and tudat::ephemerides::RotationalEphemeris::getRotationalVelocityVectorInBaseFrame().
getDerivativeOfRotationMatrixToFrame()
Eigen::Matrix3d tudat::ephemerides::getDerivativeOfRotationMatrixToFrame (const Eigen::Matrix3d & rotationToTargetFrame, const Eigen::Vector3d & rotationalVelocityVectorInTargetFrame)
Function to calculate the time derivative of rotation matrix from frame A (global) to frame B (local) from the rotation matrix between the frames, as well as the angular velocity vector of frame B w.r.t. frame A.
Parameters
rotationToTargetFrame Rotation matrix from frame A to frame B.
rotationalVelocityVectorInTargetFrame Angular velocity vector of frame B, expressed in frame A.
Returns
Time derivative if rotation matrix from frame A to frame B.
Definition at line 32 of file rotationalEphemeris.cpp.
References tudat::linear_algebra::getCrossProductMatrix().
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToTargetFrame().
transformStateToFrameFromRotations()
template<typename StateScalarType > Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::transformStateToFrameFromRotations (const Eigen::Matrix< StateScalarType, 6, 1 > & stateInBaseFrame, const Eigen::Quaterniond & rotationToFrame, const Eigen::Matrix3d & rotationMatrixToFrameDerivative)
Transform a state (Cartesian position and velocity) from one frame to another, taking into account both the instantaneous rotational state of the two frames, and the rotational rate of one frame w.r.t. the other.
Parameters
stateInBaseFrame State that is to be transformed from base to target frame.
rotationToFrame Rotation from base to target frame.
rotationMatrixToFrameDerivative Time derivative of rotation matrix from base to target frame.
Returns
State (Cartesian position and velocity) in target frame.
Definition at line 71 of file rotationalEphemeris.h.
Referenced by transformStateToFrameFromRotationTimeFunctions().
transformStateToFrameFromRotationFunctions()
template<typename StateScalarType > Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::transformStateToFrameFromRotationFunctions (const Eigen::Matrix< StateScalarType, 6, 1 > & stateInBaseFrame, const std::function< Eigen::Quaterniond() > rotationToFrameFunction, const std::function< Eigen::Matrix3d() > rotationMatrixToFrameDerivativeFunction)
Transform a state (Cartesian position and velocity) from one frame to another, taking into account both the instantaneous rotational state of the two frames, and the rotational rate of one frame w.r.t. the other.
Parameters
stateInBaseFrame State that is to be transformed from base to target frame.
rotationToFrameFunction Function returning rotation from base to target frame.
rotationMatrixToFrameDerivativeFunction Function returning time derivative of rotation matrix from base to target frame.
Returns
State (Cartesian position and velocity) in target frame.
Definition at line 97 of file rotationalEphemeris.h.
transformRelativeStateToFrame()
template<typename StateScalarType > Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::transformRelativeStateToFrame (const std::function< Eigen::Matrix< StateScalarType, 6, 1 >() > stateInBaseFrame, const std::function< Eigen::Matrix< StateScalarType, 6, 1 >() > centralBodyStateInBaseFrame, const std::function< Eigen::Quaterniond() > rotationToFrameFunction, const std::function< Eigen::Matrix3d() > rotationMatrixToFrameDerivativeFunction)
Transform a relative state (Cartesian position and velocity) from one frame to another, taking into account both the instantaneous rotational state of the two frames, and the rotational rate of one frame w.r.t. the other.
Parameters
stateInBaseFrame State that is to be transformed from base to target frame.
centralBodyStateInBaseFrame State of central body w.r.t. which returned state is to be computed. State returned by this function must be in frame with same orientation as that returned by stateInBaseFrame.
rotationToFrameFunction Function returning rotation from base to target frame.
rotationMatrixToFrameDerivativeFunction Function returning time derivative of rotation matrix from base to target frame.
Returns
State (Cartesian position and velocity) in target frame.
Definition at line 121 of file rotationalEphemeris.h.
transformStateToFrameFromRotationTimeFunctions()
template<typename StateScalarType , typename TimeType > Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::transformStateToFrameFromRotationTimeFunctions (const Eigen::Matrix< StateScalarType, 6, 1 > & stateInBaseFrame, const double currentTime, const std::function< Eigen::Quaterniond(const TimeType) > rotationToFrameFunction, const std::function< Eigen::Matrix3d(const TimeType) > rotationMatrixToFrameDerivativeFunction)
Transform a state (Cartesian position and velocity) from one frame to another, taking into account both the instantaneous rotational state of the two frames, and the rotational rate of one frame w.r.t. the other.
Parameters
stateInBaseFrame State that is to be transformed from base to target frame.
currentTime Input time for rotationToFrameFunction and rotationMatrixToFrameDerivativeFunction
rotationToFrameFunction Function returning rotation from base to target frame.
rotationMatrixToFrameDerivativeFunction Function returning time derivative of rotation matrix from base to target frame.
Returns
State (Cartesian position and velocity) in target frame.
Definition at line 149 of file rotationalEphemeris.h.
References transformStateToFrameFromRotations().
transformStateToGlobalFrame()
template<typename StateScalarType , typename TimeType > Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::transformStateToGlobalFrame (const Eigen::Matrix< StateScalarType, 6, 1 > & stateInLocalFrame, const TimeType currentTime, const std::shared_ptr< RotationalEphemeris > rotationalEphemeris)
Function to transform a state from the target (body-fixed) to base (inertial) frame of a rotational ephemeris
Parameters
stateInLocalFrame State in body-fixed frame (target frame of rotational ephemeris)
currentTime Time at which rotational ephemeris is to be evaluated
rotationalEphemeris Rotational ephemeris object to compute the rotation.
Returns
stateInLocalFrame State in inertial frame (base frame of rotational ephemeris)
Definition at line 464 of file rotationalEphemeris.h.
Referenced by tudat::observation_models::createReferencePointEphemeris(), and tudat::json_interface::getCartesianState().
transformStateToTargetFrame()
template<typename StateScalarType , typename TimeType > Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::transformStateToTargetFrame (const Eigen::Matrix< StateScalarType, 6, 1 > & stateInGlobalFrame, const TimeType currentTime, const std::shared_ptr< RotationalEphemeris > rotationalEphemeris)
Function to transform a state from the base (inertial) to target (body-fixed) frame of a rotational ephemeris
Parameters
stateInGlobalFrame State in inertial frame (base frame of rotational ephemeris)
currentTime Time at which rotational ephemeris is to be evaluated
rotationalEphemeris Rotational ephemeris object to compute the rotation.
Returns
State in body-fixed frame (target frame of rotational ephemeris)
Definition at line 484 of file rotationalEphemeris.h.
isTabulatedEphemeris()
bool tudat::ephemerides::isTabulatedEphemeris (const std::shared_ptr< Ephemeris > ephemeris)
Function to check whether an ephemeris is a (type of) tabulated ephemeris, it checks all typical combinations of class template arguments are returns true if a dynamic cast is succesful
Parameters
ephemeris Ephemeris pointer for which it is to be checked whether it is a tabulated ephemeris
Returns
True if ephemeris is a tabulated ephemeris
Definition at line 155 of file tabulatedEphemeris.cpp.
Referenced by tudat::simulation_setup::getSafeInterpolationInterval(), getTabulatedEphemerisSafeInterval(), and tudat::propagators::resetIntegratedEphemerisOfBody().
getTabulatedEphemerisSafeInterval()
std::pair< double, double > tudat::ephemerides::getTabulatedEphemerisSafeInterval (const std::shared_ptr< Ephemeris > ephemeris)
Function that retrieves the time interval at which a tabulated ephemeris can be safely interrogated. The interval on which the interpolator inside this object is valid is checked and returned
Parameters
ephemeris Ephemeris model for which the interval is to be determined. AN exception is thrown if this is not a tabulated ephemeris
Returns
The time interval at which the tabulated ephemeris can be safely interrogated
Definition at line 169 of file tabulatedEphemeris.cpp.
References tudat::simulation_setup::getSafeInterpolationInterval(), isTabulatedEphemeris(), and TUDAT_NAN.
Referenced by tudat::simulation_setup::determinePostfitParameterInfluence(), and tudat::simulation_setup::getSafeInterpolationInterval().
createEmptyTabulatedEphemeris()
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< Ephemeris > tudat::ephemerides::createEmptyTabulatedEphemeris (const std::string referenceFrameOrigin = "SSB", const std::string referenceFrameOrientation = "ECLIPJ2000")
Function to create an empty (dummy) tabulated ephemeris. This is used when for instance propagating a body for which the propagated result shopuld be saved in the epehemris, but no a priori ephemeris is available
Parameters
referenceFrameOrigin Origin of reference frame in which state is defined.
referenceFrameOrientation Orientation of reference frame in which state is defined.
Returns
Empty tabulated ephemeris with given reference frame settings
Definition at line 222 of file tabulatedEphemeris.h.
to_json()
void tudat::ephemerides::to_json (nlohmann::json & jsonObject, const ApproximatePlanetPositionsBase::BodiesWithEphemerisData & bodyWithEphemerisData) inline
Definition at line 43 of file ephemeris.h.
References bodiesWithEphemerisData, and tudat::json_interface::stringFromEnum().
from_json()
void tudat::ephemerides::from_json (const nlohmann::json & jsonObject, ApproximatePlanetPositionsBase::BodiesWithEphemerisData & bodyWithEphemerisData) inline
Definition at line 50 of file ephemeris.h.
References bodiesWithEphemerisData, and tudat::json_interface::enumFromString().
Variable Documentation
bodiesWithEphemerisData
std::map< ApproximatePlanetPositionsBase::BodiesWithEphemerisData, std::string > tudat::ephemerides::bodiesWithEphemerisData static
Initial value:
=
{
    { ApproximatePlanetPositionsBase::mercury, "mercury" },
    { ApproximatePlanetPositionsBase::venus, "venus" },
    { ApproximatePlanetPositionsBase::earthMoonBarycenter, "earthMoonBarycenter" },
    { ApproximatePlanetPositionsBase::mars, "mars" },
    { ApproximatePlanetPositionsBase::jupiter, "jupiter" },
    { ApproximatePlanetPositionsBase::saturn, "saturn" },
    { ApproximatePlanetPositionsBase::uranus, "uranus" },
    { ApproximatePlanetPositionsBase::neptune, "neptune" },
    { ApproximatePlanetPositionsBase::pluto, "pluto" }
}
Definition at line 26 of file ephemeris.h.
Referenced by from_json(), and to_json().
unsupportedBodiesWithEphemerisData
std::vector< ApproximatePlanetPositionsBase::BodiesWithEphemerisData > tudat::ephemerides::unsupportedBodiesWithEphemerisData = { } static
Definition at line 40 of file ephemeris.h.