Tudat: tudat::gravitation::TabulatedGravityFieldVariations Class Reference
tudat::gravitation::TabulatedGravityFieldVariations Class Reference
Class for variations in spherical harmonic coefficients, directly interpolated from tables.
#include <tabulatedGravityFieldVariations.h>
Public Member Functions
TabulatedGravityFieldVariations (const std::map< double, Eigen::MatrixXd > &cosineCoefficientCorrections, const std::map< double, Eigen::MatrixXd > &sineCoefficientCorrections, const int minimumDegree, const int minimumOrder, const boost::shared_ptr< interpolators::InterpolatorSettings > interpolatorType=boost::make_shared< interpolators::InterpolatorSettings >(interpolators::linear_interpolator, interpolators::huntingAlgorithm))
Class constructor.
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > calculateSphericalHarmonicsCorrections (const double time)
Function for calculating corrections by interpolating tabulated corrections.
std::map< double, Eigen::MatrixXd > getCosineCoefficientCorrections ()
Function to return map of cosine coefficient variations, with associated times as map key.
boost::shared_ptr< interpolators::InterpolatorSettings > getInterpolatorSettings ()
Function to return type of interpolator to use for calculating coefficients.
std::map< double, Eigen::MatrixXd > getSineCoefficientCorrections ()
Function to return map of sine coefficient variations, with associated times as map key.
void resetCoefficientInterpolator (const std::map< double, Eigen::MatrixXd > &cosineCoefficientCorrections, const std::map< double, Eigen::MatrixXd > &sineCoefficientCorrections)
Function to (re)set the tabulated spherical harmonic coefficients.
Public Member Functions inherited from tudat::gravitation::GravityFieldVariations
GravityFieldVariations (const int minimumDegree, const int minimumOrder, const int maximumDegree, const int maximumOrder)
Base class constructor.
virtual ~GravityFieldVariations ()
Virtual destructor.
void addSphericalHarmonicsCorrections (const double time, Eigen::MatrixXd &sineCoefficients, Eigen::MatrixXd &cosineCoefficients)
Function to add sine and cosine corrections at given time to coefficient matrices.
int getMaximumDegree ()
Function to return the maximum degree of the corrections.
int getMaximumOrder ()
Function to return the maximum order of the corrections.
int getMinimumDegree ()
Function to return the minimum degree of the corrections.
int getMinimumOrder ()
Function to return the minimum order of the corrections.
int getNumberOfDegrees ()
Function to return the number of degrees of the corrections.
int getNumberOfOrders ()
Function to return the number of orders of the corrections.
Private Attributes
std::map< double, Eigen::MatrixXd > cosineCoefficientCorrections_
Map of cosine coefficient variations, with associated times as map key.
boost::shared_ptr< interpolators::InterpolatorSettings > interpolatorType_
Type of interpolator to use for calculating coefficients at any time.
std::map< double, Eigen::MatrixXd > sineCoefficientCorrections_
Map of sine coefficient variations, with associated times as map key.
boost::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::MatrixXd > > variationInterpolator_
Interpolator for determining concatenated [cosine|sine] coefficients from tabulated values at discrete times.
Additional Inherited Members
Protected Attributes inherited from tudat::gravitation::GravityFieldVariations
int maximumDegree_
Maximum degree of variations.
int maximumOrder_
Maximum order of variations.
int minimumDegree_
Minimum degree of variations.
int minimumOrder_
Minimum order of variations.
int numberOfDegrees_
Number of degrees of variations.
int numberOfOrders_
Number of orders of variations.
Detailed Description
Class for variations in spherical harmonic coefficients, directly interpolated from tables. Maps of variatons of cosine and sine coefficients as a function of time are provided, as well as the type of interpolator that is to be used, from which interpolated variations are then returned at any time. The class may also be used for defining the complete gravity field (i.e. not only the variations) as a function of time when the constant coefficient contribution (i.e. not from a GravityFieldVariations) is zero for all degrees and orders.
Definition at line 34 of file tabulatedGravityFieldVariations.h.
Constructor & Destructor Documentation
tudat::gravitation::TabulatedGravityFieldVariations::TabulatedGravityFieldVariations (const std::map< double, Eigen::MatrixXd > & cosineCoefficientCorrections, const std::map< double, Eigen::MatrixXd > & sineCoefficientCorrections, const int minimumDegree, const int minimumOrder, const boost::shared_ptr< interpolators::InterpolatorSettings > interpolatorType = boost::make_shared< interpolators::InterpolatorSettings >(interpolators::linear_interpolator, interpolators::huntingAlgorithm))
Class constructor, takes the maps of variations, as well as the minimum degree and order of the corrections, the corrections are applied as a rectangular block in degree and order, with the the size of the blocks determined by the contents of the maps. The matrix size of all map entries must be equal for both sine and cosine values.
Parameters
cosineCoefficientCorrections Map of cosine coefficient variations, with associated times as map key.
sineCoefficientCorrections Map of sine coefficient variations, with associated times as map key.
minimumDegree Minimum degree of correction block.
minimumOrder Minimum order of correction block.
interpolatorType Type of interpolator to use for calculating coefficients at any time between tabulated times.
Definition at line 22 of file tabulatedGravityFieldVariations.cpp.
References resetCoefficientInterpolator().
Member Function Documentation
void tudat::gravitation::TabulatedGravityFieldVariations::resetCoefficientInterpolator (const std::map< double, Eigen::MatrixXd > & cosineCoefficientCorrections, const std::map< double, Eigen::MatrixXd > & sineCoefficientCorrections)
Function to (re)set the tabulated spherical harmonic coefficients. Creates interpolator for returning the coefficients as a function of time.
Parameters
cosineCoefficientCorrections Map of cosine coefficient variations, with associated times as map key.
sineCoefficientCorrections Map of sine coefficient variations, with associated times as map key.
Definition at line 37 of file tabulatedGravityFieldVariations.cpp.
References calculateSphericalHarmonicsCorrections(), cosineCoefficientCorrections_, interpolatorType_, tudat::gravitation::GravityFieldVariations::numberOfDegrees_, tudat::gravitation::GravityFieldVariations::numberOfOrders_, sineCoefficientCorrections_, and variationInterpolator_.
Referenced by TabulatedGravityFieldVariations().
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > tudat::gravitation::TabulatedGravityFieldVariations::calculateSphericalHarmonicsCorrections (const double time) virtual
Function for calculating corrections by interpolating tabulated corrections.
Parameters
time Time at which variations are to be calculated.
Returns
Pair of matrices containing variations in (cosine, sine) coefficients at block positions in total matrices defined by minimumDegree_, minimumOrder_, numberOfDegrees_, numberOfOrders_;
Implements tudat::gravitation::GravityFieldVariations.
Definition at line 107 of file tabulatedGravityFieldVariations.cpp.
References tudat::gravitation::GravityFieldVariations::numberOfDegrees_, tudat::gravitation::GravityFieldVariations::numberOfOrders_, and variationInterpolator_.
Referenced by resetCoefficientInterpolator().
std::map< double, Eigen::MatrixXd > tudat::gravitation::TabulatedGravityFieldVariations::getCosineCoefficientCorrections () inline
Function to return map of cosine coefficient variations, with associated times as map key.
Returns
Map of cosine coefficient variations, with associated times as map key.
Definition at line 91 of file tabulatedGravityFieldVariations.h.
References cosineCoefficientCorrections_.
std::map< double, Eigen::MatrixXd > tudat::gravitation::TabulatedGravityFieldVariations::getSineCoefficientCorrections () inline
Function to return map of sine coefficient variations, with associated times as map key.
Returns
Map of sine coefficient variations, with associated times as map key.
Definition at line 101 of file tabulatedGravityFieldVariations.h.
References sineCoefficientCorrections_.
boost::shared_ptr< interpolators::InterpolatorSettings > tudat::gravitation::TabulatedGravityFieldVariations::getInterpolatorSettings () inline
Function to return type of interpolator to use for calculating coefficients at any time between tabulated times.
Returns
Type of interpolator to use for calculating coefficients
Definition at line 112 of file tabulatedGravityFieldVariations.h.
References interpolatorType_.
Member Data Documentation
boost::shared_ptr< interpolators::InterpolatorSettings > tudat::gravitation::TabulatedGravityFieldVariations::interpolatorType_ private
Definition at line 120 of file tabulatedGravityFieldVariations.h.
Referenced by getInterpolatorSettings(), and resetCoefficientInterpolator().
std::map< double, Eigen::MatrixXd > tudat::gravitation::TabulatedGravityFieldVariations::cosineCoefficientCorrections_ private
Definition at line 123 of file tabulatedGravityFieldVariations.h.
Referenced by getCosineCoefficientCorrections(), and resetCoefficientInterpolator().
std::map< double, Eigen::MatrixXd > tudat::gravitation::TabulatedGravityFieldVariations::sineCoefficientCorrections_ private
Definition at line 126 of file tabulatedGravityFieldVariations.h.
Referenced by getSineCoefficientCorrections(), and resetCoefficientInterpolator().
boost::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::MatrixXd > > tudat::gravitation::TabulatedGravityFieldVariations::variationInterpolator_ private
Interpolator for determining concatenated [cosine|sine] coefficients from tabulated values at discrete times.
The coefficients are interpolated concurrently and then split to reduce the number of calls to the interpolator.
Definition at line 136 of file tabulatedGravityFieldVariations.h.
Referenced by calculateSphericalHarmonicsCorrections(), and resetCoefficientInterpolator().
The documentation for this class was generated from the following files:
Astrodynamics/Gravitation/tabulatedGravityFieldVariations.h
Astrodynamics/Gravitation/tabulatedGravityFieldVariations.cpp