Tudat: tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType > Class Template Reference
tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType > Class Template Reference
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with unified state model with exponential map (USMEM).
#include <nBodyUnifiedStateModelExponentialMapStateDerivative.h>
Public Member Functions
NBodyUnifiedStateModelExponentialMapStateDerivative (const basic_astrodynamics::AccelerationMap &accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const std::vector< std::string > &bodiesToIntegrate)
Constructor.
~NBodyUnifiedStateModelExponentialMapStateDerivative ()
Destructor.
void calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative)
Calculates the state derivative of the translational motion of the system, using the equations of motion for the unified state model with exponential map (USMEM).
Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &cartesianSolution, const TimeType &time)
Function to convert the state in the conventional form to the USMEM elements form.
void convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSolution)
Function to convert the USMEM states of the bodies to the conventional form.
basic_astrodynamics::AccelerationMap getFullAccelerationsMap ()
Function to get the acceleration models.
int getPropagatedStateSize ()
Function to return the size of the state handled by the object.
bool isStateToBePostProcessed ()
Function to return whether the state needs to be post-processed.
void postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState)
Function to process the state during propagation.
Public Member Functions inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
NBodyStateDerivative (const basic_astrodynamics::AccelerationMap &accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const TranslationalPropagatorType propagatorType, const std::vector< std::string > &bodiesToIntegrate)
From this constructor, the object for generating the state derivative is created.
virtual ~NBodyStateDerivative ()
Destructor.
virtual void clearDerivedTranslationalStateDerivativeModel ()
Function to clear any reference/cached values of state derivative model.
void clearStateDerivativeModel ()
Function to clear reference/cached values of translational state derivative model.
void clearTranslationalStateDerivativeModel ()
Function to clear reference/cached values of acceleration models.
void convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton)
Function to convert the propagator-specific form of the state to the conventional form in the global frame.
basic_astrodynamics::AccelerationMap getAccelerationsMap ()
Function to retrieve the map containing the list of accelerations acting on each body.
std::vector< std::string > getBodiesToBeIntegratedNumerically ()
Function to get list of names of bodies that are to be integrated numerically.
std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > getCentralBodyData ()
Function to get object providing the current integration origins.
int getConventionalStateSize ()
Function to return the size of the state handled by the object.
Eigen::Vector3d getTotalAccelerationForBody (const std::string &bodyName)
Function to retrieve the total acceleration acting on a given body.
TranslationalPropagatorType getTranslationalPropagatorType ()
Function to get type of propagator that is to be used (i.e. Cowell, Encke, etc.)
void updateStateDerivativeModel (const TimeType currentTime)
Function to update the state derivative model to the current time.
Public Member Functions inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
SingleStateTypeDerivative (const IntegratedStateType integratedStateType)
Constructor.
virtual ~SingleStateTypeDerivative ()
Virtual destructor.
IntegratedStateType getIntegratedStateType ()
Function to return the type of dynamics for which the state derivative is calculated.
virtual void postProcessState (Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &unprocessedState)
Private Attributes
std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > centralAccelerations_
Central body accelerations for each propagated body, which has been removed from accelerationModelsPerBody_.
std::vector< std::function< double() > > centralBodyGravitationalParameters_
Gravitational parameters of central bodies used to convert Cartesian to Keplerian orbits, and vice versa.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > currentCartesianLocalSolution_
Current full Cartesian state of the propagated bodies, w.r.t. the central bodies.
basic_astrodynamics::AccelerationMap originalAccelerationModelsPerBody_
List of acceleration models, including the central body accelerations that are removed in this propagation scheme.
Additional Inherited Members
Protected Member Functions inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
void createAccelerationModelList ()
void sumStateDerivativeContributions (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative, const bool addPositionDerivatives=true)
Function to get the state derivative of the system in Cartesian coordinates.
void sumStateDerivativeContributions (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &stateDerivative, const bool addPositionDerivatives=true)
Function to get the state derivative of the system in Cartesian coordinates.
Protected Attributes inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > accelerationModelList_
Vector of acceleration models, containing all entries of accelerationModelsPerBody_.
basic_astrodynamics::AccelerationMap accelerationModelsPerBody_
A map containing the list of accelerations acting on each body,.
std::vector< std::string > bodiesToBeIntegratedNumerically_
List of names of bodies that are to be integrated numerically.
std::vector< int > bodyOrder_
std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData_
Object responsible for providing the current integration origins from the global origins.
std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > centralBodyStatesWrtGlobalOrigin_
List of states of the central bodies of the propagated bodies.
std::unordered_map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > >::iterator innerAccelerationIterator
Predefined iterator to save (de-)allocation time.
std::unordered_map< std::string, std::unordered_map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > > >::iterator outerAccelerationIterator
Predefined iterator to save (de-)allocation time.
TranslationalPropagatorType propagatorType_
Type of propagator that is to be used (i.e. Cowell, Encke, etc.)
Protected Attributes inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
IntegratedStateType integratedStateType_
Type of dynamics for which the state derivative is calculated.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > unprocessedState_
Vector used during post-processing of state.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with unified state model with exponential map (USMEM).
In this method, the derivative of the USMEM elements are computed from the total Cartesian accelerations, with the USMEM elements of the bodies the states being numerically propagated.
Definition at line 90 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
Constructor & Destructor Documentation
NBodyUnifiedStateModelExponentialMapStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelExponentialMapStateDerivative (const basic_astrodynamics::AccelerationMap & accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const std::vector< std::string > & bodiesToIntegrate) inline
Constructor
Parameters
accelerationModelsPerBody A map containing the list of accelerations acting on each body, identifying the body being acted on and the body acted on by an acceleration. The map has as key a string denoting the name of the body the list of accelerations, provided as the value corresponding to a key, is acting on. This map-value is again a map with string as key, denoting the body exerting the acceleration, and as value a pointer to an acceleration model.
centralBodyData Object responsible for providing the current integration origins from the global origins.
bodiesToIntegrate List of names of bodies that are to be integrated numerically.
Definition at line 107 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::accelerationModelsPerBody_, tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::createAccelerationModelList(), tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_, and tudat::propagators::removeCentralGravityAccelerations().
~NBodyUnifiedStateModelExponentialMapStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::~NBodyUnifiedStateModelExponentialMapStateDerivative () inline
Definition at line 125 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
Member Function Documentation
calculateSystemStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative) inline virtual
Calculates the state derivative of the translational motion of the system, using the equations of motion for the unified state model with exponential map (USMEM).
The input is the current state in USMEM elememts. The state derivate of this set is computed. To do so the accelerations are internally transformed into the RSW frame, using the current Cartesian state as set by the last call to the convertToOutputSolution function
Parameters
time Time (TDB seconds since J2000) at which the system is to be updated.
stateOfSystemToBeIntegrated List of 7 * bodiesToBeIntegratedNumerically_.size(), containing USMEM elements of the bodies being integrated. The order of the values is defined by the order of bodies in bodiesToBeIntegratedNumerically_
stateDerivative Current derivative of the USMEM elements of the system of bodies integrated numerically (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 141 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::computeStateDerivativeForUnifiedStateModelExponentialMap(), tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSolution_, tudat::reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix(), and tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::sumStateDerivativeContributions().
convertFromOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & cartesianSolution, const TimeType & time) inline virtual
Function to convert the state in the conventional form to the propagator-specific form. For the USMEM propagator, this transforms the Cartesian state w.r.t. the central body (conventional form) to the USMEM elements
Parameters
cartesianSolution State in 'conventional form'
time Current time at which the state is valid, used to computed Kepler orbits
Returns
State (outputSolution), converted to the USMEM elements
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 173 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::orbital_element_conversions::convertCartesianToUnifiedStateModelExponentialMapElements(), and tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::getPropagatedStateSize().
convertToOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSolution) inline virtual
Function to convert the USMEM elements state to the conventional form. For the USMEM propagator, this transforms USMEM elements w.r.t. the central bodies to the Cartesian states w.r.t. these same central bodies: In contrast to the convertCurrentStateToGlobalRepresentation function, this function does not provide the state in the inertial frame, but instead provides it in the frame in which it is propagated.
Parameters
internalSolution State in USMEM elemements (i.e. form that is used in numerical integration)
time Current time at which the state is valid
currentCartesianLocalSolution State (internalSolution, which is USMEM-formulation), converted to the 'conventional form' (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 203 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::orbital_element_conversions::convertUnifiedStateModelExponentialMapToCartesianElements(), and tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSolution_.
getFullAccelerationsMap()
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::AccelerationMap tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::getFullAccelerationsMap () inline virtual
Function to get the acceleration models, including the central body accelerations that are removed for the propagation scheme
Returns
List of acceleration models, including the central body accelerations that are removed in this propagation scheme.
Reimplemented from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >.
Definition at line 224 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
References tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_.
getPropagatedStateSize()
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::getPropagatedStateSize () inline virtual
Function to return the size of the state handled by the object.
Returns
Size of the state under consideration (7 times the number if integrated bodies).
Reimplemented from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 234 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_.
Referenced by tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution().
postProcessState()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState) inline virtual
Function to process the state during propagation. For exponential map (EM), this function converts to/from shadow exponential map (SEM), in case the rotation angle is larger than PI.
Parameters
unprocessedState State computed after propagation.
Returns
Processed state (returned by reference).
Reimplemented from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 246 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, and tudat::mathematical_constants::PI.
isStateToBePostProcessed()
template<typename StateScalarType = double, typename TimeType = double> bool tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::isStateToBePostProcessed () inline virtual
Function to return whether the state needs to be post-processed. For (shadow) exponential map this is true.
Returns
Boolean confirming that the state needs to be post-processed.
Reimplemented from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 276 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
Member Data Documentation
centralBodyGravitationalParameters_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::function< double() > > tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_ private
Definition at line 284 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
Referenced by tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), and tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelExponentialMapStateDerivative().
centralAccelerations_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::centralAccelerations_ private
Definition at line 288 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
originalAccelerationModelsPerBody_
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::AccelerationMap tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_ private
Definition at line 291 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
Referenced by tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::getFullAccelerationsMap(), and tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelExponentialMapStateDerivative().
currentCartesianLocalSolution_
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSolution_ private
Current full Cartesian state of the propagated bodies, w.r.t. the central bodies. These variables are set when calling the convertToOutputSolution function.
Definition at line 298 of file nBodyUnifiedStateModelExponentialMapStateDerivative.h.
Referenced by tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::convertToOutputSolution().
The documentation for this class was generated from the following file:
Astrodynamics/Propagators/nBodyUnifiedStateModelExponentialMapStateDerivative.h