Tudat: tudat::mission_segments Namespace Reference
tudat::mission_segments Namespace Reference
Classes
class EccentricityFindingFunctions
Eccentricity finding functions class.
class ImprovedInversePolynomialWall
This class contains an improved inverse polynomial function, and its exact first and second derivative w.r.t.
class LambertFunctionsGooding
Gooding Lambert functions class.
class LambertTargeter
Lambert targeting algorithm class.
class LambertTargeterGooding
Gooding Lambert targeting algorithm class.
class LambertTargeterIzzo
Izzo Lambert targeting algorithm class.
class MultiRevolutionLambertTargeterIzzo
Izzo Lambert targeting algorithm class (multiple revolution).
class OscillatingFunctionNovak
This class contains an oscillating function, and its exact first and second derivative w.r.t.
class PericenterFindingFunctions
Pericenter finding functions class.
class ZeroRevolutionLambertTargeterIzzo
Izzo Lambert targeting algorithm class (zero revolution).
Typedefs
typedef boost::shared_ptr< EccentricityFindingFunctions > EccentricityFindingFunctionsPointer
Typedef for shared-pointer to EccentricityFindingFunctions object.
typedef boost::shared_ptr< ImprovedInversePolynomialWall > ImprovedInversePolynomialWallPointer
Typedef for shared-pointer to ImprovedInversePolynomialWall object.
typedef boost::shared_ptr< LambertFunctionsGooding > LambertFunctionsGoodingPointer
Typedef for shared-pointer to LambertFunctionsGooding object.
typedef boost::shared_ptr< LambertTargeterGooding > LambertTargeterGoodingPointer
Typedef for shared-pointer to LambertTargeterGooding object.
typedef boost::shared_ptr< LambertTargeterIzzo > LambertTargeterIzzoPointer
Typedef for shared-pointer to LambertTargeterIzzo object.
typedef boost::shared_ptr< LambertTargeter > LambertTargeterPointer
Typedef for shared-pointer to LambertTargeter.
typedef boost::shared_ptr< OscillatingFunctionNovak > OscillatingFunctionNovakPointer
Typedef for shared-pointer to oscillatingFunctionNovak object.
typedef boost::shared_ptr< PericenterFindingFunctions > PericenterFindingFunctionsPointer
Typedef for shared-pointer to PericenterFindingFunctions object.
Functions
double computeEscapeOrCaptureDeltaV (const double gravitationalParameter, const double semiMajorAxis, const double eccentricity, const double excessVelocity)
Compute escape or capture deltaV budget.
double computeTimeOfFlightIzzo (const double xParameter, const double semiPerimeter, const double chord, const bool isLongway, const double semiMajorAxisOfTheMinimumEnergyEllipse)
Compute time-of-flight using Lagrange's equation.
double gravityAssist (const double centralBodyGravitationalParameter, const Eigen::Vector3d &centralBodyVelocity, const Eigen::Vector3d &incomingVelocity, const Eigen::Vector3d &outgoingVelocity, const double smallestPeriapsisDistance, const bool useEccentricityInsteadOfPericenter, const double speedTolerance, RootFinderPointer rootFinder)
Calculate deltaV of a gravity assist.
Eigen::Vector3d gravityAssist (const double centralBodyGravitationalParameter, const Eigen::Vector3d &centralBodyVelocity, const Eigen::Vector3d &incomingVelocity, const double rotationAngle, const double pericenterRadius)
Propagate an unpowered gravity assist.
Eigen::Vector3d gravityAssist (const double centralBodyGravitationalParameter, const Eigen::Vector3d &centralBodyVelocity, const Eigen::Vector3d &incomingVelocity, const double rotationAngle, const double pericenterRadius, const double deltaV)
Propagate a powered gravity assist.
void solveLambertProblemGooding (const Eigen::Vector3d &cartesianPositionAtDeparture, const Eigen::Vector3d &cartesianPositionAtArrival, const double timeOfFlight, const double gravitationalParameter, Eigen::Vector3d &cartesianVelocityAtDeparture, Eigen::Vector3d &cartesianVelocityAtArrival, RootFinderPointer rootFinder)
Solve Lambert Problem using Gooding's algorithm.
void solveLambertProblemIzzo (const Eigen::Vector3d &cartesianPositionAtDeparture, const Eigen::Vector3d &cartesianPositionAtArrival, const double timeOfFlight, const double gravitationalParameter, Eigen::Vector3d &cartesianVelocityAtDeparture, Eigen::Vector3d &cartesianVelocityAtArrival, const bool isRetrograde, const double convergenceTolerance, const unsigned int maximumNumberOfIterations)
Solve Lambert Problem using Izzo's algorithm.
Typedef Documentation
typedef boost::shared_ptr< PericenterFindingFunctions > tudat::mission_segments::PericenterFindingFunctionsPointer
Definition at line 183 of file gravityAssist.h.
typedef boost::shared_ptr< EccentricityFindingFunctions > tudat::mission_segments::EccentricityFindingFunctionsPointer
Definition at line 256 of file gravityAssist.h.
typedef boost::shared_ptr< ImprovedInversePolynomialWall > tudat::mission_segments::ImprovedInversePolynomialWallPointer
Definition at line 237 of file improvedInversePolynomialWall.h.
typedef boost::shared_ptr< LambertFunctionsGooding > tudat::mission_segments::LambertFunctionsGoodingPointer
Definition at line 198 of file lambertRoutines.h.
typedef boost::shared_ptr< LambertTargeter > tudat::mission_segments::LambertTargeterPointer
Definition at line 173 of file lambertTargeter.h.
typedef boost::shared_ptr< LambertTargeterGooding > tudat::mission_segments::LambertTargeterGoodingPointer
Definition at line 107 of file lambertTargeterGooding.h.
typedef boost::shared_ptr< LambertTargeterIzzo > tudat::mission_segments::LambertTargeterIzzoPointer
Definition at line 144 of file lambertTargeterIzzo.h.
typedef boost::shared_ptr< OscillatingFunctionNovak > tudat::mission_segments::OscillatingFunctionNovakPointer
Definition at line 190 of file oscillatingFunctionNovak.h.
Function Documentation
double tudat::mission_segments::computeEscapeOrCaptureDeltaV (const double gravitationalParameter, const double semiMajorAxis, const double eccentricity, const double excessVelocity)
Calculates the required deltaV to perform a certain escape or capture maneuver to/from the specified orbit from/to the specified excessVelocity.
Parameters
gravitationalParameter Gravitational parameter of the escape/capture body. [m^3 s^-2]
semiMajorAxis Semi major axis of the parking orbit. [m]
eccentricity Eccentricity of the parking orbit. [-]
excessVelocity Excess velocity after the escape or before the capture maneuver. [m s^-1]
Returns
deltaV The deltaV required for the escape or capture maneuver. [m s^-1]
Definition at line 25 of file escapeAndCapture.cpp.
References tudat::input_output::field_types::state::eccentricity.
double tudat::mission_segments::gravityAssist (const double centralBodyGravitationalParameter, const Eigen::Vector3d & centralBodyVelocity, const Eigen::Vector3d & incomingVelocity, const Eigen::Vector3d & outgoingVelocity, const double smallestPeriapsisDistance, const bool useEccentricityInsteadOfPericenter = true, const double speedTolerance = 1.0e-6, root_finders::RootFinderPointer rootFinder = boost::make_shared< root_finders::NewtonRaphson >(1.0e-12, 1000))
Calculates the deltaV required to perform a certain gravity assist. This function essentially tries to patch the incoming and outgoing velocity using an unpowered gravity assist. If however the required bending angle cannot be obtained, the deltaV required to patch this is calculated. Likewise the deltaV required to patch the hyperbolic excess velocities is calculated. The sum of the two is the total deltaV required to perform the maneuver and is returned.
Parameters
centralBodyGravitationalParameter Gravitational parameter of the swing-by body.[m^3 s^-2]
centralBodyVelocity Heliocentric velocity of the swing-by body. [m s^-1]
incomingVelocity Heliocentric velocity of the spacecraft before the swing-by. [m s^-1]
outgoingVelocity Heliocentric velocity of the spacecraft after the swing-by. [m s^-1]
smallestPeriapsisDistance Closest allowable distance to the swing-by body. [m]
useEccentricityInsteadOfPericenter Flag to indicate the iteration procedure for matching the bending angle. [-]
speedTolerance Tolerance at which the velocity effect deltaV is deemed 0.0. [-]
rootFinder Shared-pointer to the rootfinder that is to be used. Default is Newton-Raphson using 1000 iterations as maximum and 1.0e-12 relative X-tolerance.
Returns
deltaV The deltaV required for the gravity assist maneuver. [m s^-1]
Definition at line 58 of file gravityAssist.cpp.
References tudat::linear_algebra::computeAngleBetweenVectors(), tudat::mission_segments::PericenterFindingFunctions::computePericenterRadiusFunction(), and TUDAT_NAN.
Eigen::Vector3d tudat::mission_segments::gravityAssist (const double centralBodyGravitationalParameter, const Eigen::Vector3d & centralBodyVelocity, const Eigen::Vector3d & incomingVelocity, const double rotationAngle, const double pericenterRadius)
Calculates the outgoing velocity of an unpowered gravity assist. The gravity assist is defined by a 3D rotation angle and the pericenter radius of the swing-by maneuver.
Parameters
centralBodyGravitationalParameter Gravitational parameter of the swing-by body.[m^3 s^-2]
centralBodyVelocity Heliocentric velocity of the swing-by body. [m s^-1]
incomingVelocity Heliocentric velocity of the spacecraft before the swing-by. [m s^-1]
rotationAngle Angle defining the rotation due to the swing-by in the 3D plane. [rad]
pericenterRadius Pericenter radius of the swing-by maneuver. [m]
Returns
outgoingVelocity Heliocentric velocity of the spacecraft after the swing-by. [m s^-1]
Definition at line 274 of file gravityAssist.cpp.
References tudat::input_output::field_types::state::eccentricity.
Eigen::Vector3d tudat::mission_segments::gravityAssist (const double centralBodyGravitationalParameter, const Eigen::Vector3d & centralBodyVelocity, const Eigen::Vector3d & incomingVelocity, const double rotationAngle, const double pericenterRadius, const double deltaV)
Calculates the outgoing velocity of a powered gravity assist. The gravity assist is defined by a 3D rotation angle, the pericenter radius of the swing-by maneuver and the deltaV magnitude that is applied at the pericenter passage of the gravity assist.
Parameters
centralBodyGravitationalParameter Gravitational parameter of the swing-by body.[m^3 s^-2]
centralBodyVelocity Heliocentric velocity of the swing-by body. [m s^-1]
incomingVelocity Heliocentric velocity of the spacecraft before the swing-by. [m s^-1]
rotationAngle Angle defining the rotation due to the swing-by in the 3D plane. [rad]
pericenterRadius Pericenter radius of the swing-by maneuver. [m]
deltaV DeltaV magnitude of the gravity assist that is applied at pericenter [m s^-1]
Returns
outgoingVelocity Heliocentric velocity of the spacecraft after the swing-by. [m s^-1]
Definition at line 306 of file gravityAssist.cpp.
void tudat::mission_segments::solveLambertProblemIzzo (const Eigen::Vector3d & cartesianPositionAtDeparture, const Eigen::Vector3d & cartesianPositionAtArrival, const double timeOfFlight, const double gravitationalParameter, Eigen::Vector3d & cartesianVelocityAtDeparture, Eigen::Vector3d & cartesianVelocityAtArrival, const bool isRetrograde = false, const double convergenceTolerance = 1e-9, const unsigned int maximumNumberOfIterations = 50)
Solves the Lambert Problem using Izzo's algorithm. This code is an implementation of the method developed by Dario Izzo from ESA/ACT and publicly available at: http://keptoolbox.sourceforge.net/ After verification and validation, it was proven that this algorithm is faster and more robust than the implemented Lancaster & Blanchard and Gooding method. Notably, this method does not suffer from the near-pi singularity (pi-transfers are by nature singular). This method works in adimensional units, meaning that position, time-of-flight and gravitational parameter can be provided in any units, as long as they are coherent across all quantities. Results will be returned in the same units as the input variables. Note that while this implementation does not support multi-revolution transfers, the original algorithm (see link above) does. The root-finder (Secant Method) is currently hard-coded.
Parameters
cartesianPositionAtDeparture Cartesian position at departure. [Input]
cartesianPositionAtArrival Cartesian position at arrival. [Input]
timeOfFlight Time-of-flight between departure and arrival. [Input]
gravitationalParameter Gravitational parameter of the central body. [Input]
cartesianVelocityAtDeparture Velocity at departure. [Output]
cartesianVelocityAtArrival Velocity at arrival. [Output]
isRetrograde Boolean flag to indicate direction of motion. [Input, Optional]
convergenceTolerance Convergence tolerance for the root-finding process. [Input, Optional]
maximumNumberOfIterations Maximum number of iterations of the root-finding process. [Input, Optional]
Definition at line 43 of file lambertRoutines.cpp.
References computeTimeOfFlightIzzo(), tudat::mathematical_constants::PI, and tudat::input_output::field_types::state::semiMajorAxis.
Referenced by tudat::mission_segments::LambertTargeterIzzo::execute().
double tudat::mission_segments::computeTimeOfFlightIzzo (const double xParameter, const double semiPerimeter, const double chord, const bool isLongway, const double semiMajorAxisOfTheMinimumEnergyEllipse)
Computes the time-of-flight according to Lagrange's equation as a function of the x-parameter.
Parameters
xParameter x parameter in Izzo's algorithm.
semiPerimeter Semi-perimeter: .
chord Chord: .
isLongway Boolean flag to indicate if the transfer is long-way () or short-way ().
semiMajorAxisOfTheMinimumEnergyEllipse Semi-major axis of the minimum energy ellipse: .
Returns
timeOfFlight Computed time-of-flight.
Definition at line 299 of file lambertRoutines.cpp.
References tudat::input_output::field_types::state::semiMajorAxis.
Referenced by solveLambertProblemIzzo().
void tudat::mission_segments::solveLambertProblemGooding (const Eigen::Vector3d & cartesianPositionAtDeparture, const Eigen::Vector3d & cartesianPositionAtArrival, const double timeOfFlight, const double gravitationalParameter, Eigen::Vector3d & cartesianVelocityAtDeparture, Eigen::Vector3d & cartesianVelocityAtArrival, root_finders::RootFinderPointer rootFinder = root_finders::RootFinderPointer())
Solves the Lambert Problem using Lancaster and Blanchard's algorithm with further improvements by Gooding. The number of revolutions from departure to arrival body is zero by definition in this routine. This can be made user-defined later on. The resulting trajectories are in anti-clockwise (prograde) direction.
Parameters
cartesianPositionAtDeparture Cartesian position at departure [m]. [Input]
cartesianPositionAtArrival Cartesian position at arrival [m]. [Input]
timeOfFlight Time-of-flight between departure and arrival [s]. [Input]
gravitationalParameter Gravitational parameter of the central body [m^3/s^2]. [Input]
cartesianVelocityAtDeparture Velocity at departure [m]. [Output]
cartesianVelocityAtArrival Velocity at arrival [m]. [Output]
rootFinder Shared-pointer to the rootfinder that is to be used. Default is Newton-Raphson using 1000 iterations as maximum and 1.0e-12 relative X-tolerance. [Input, optional]
Definition at line 356 of file lambertRoutines.cpp.
References tudat::linear_algebra::computeAngleBetweenVectors(), tudat::mission_segments::LambertFunctionsGooding::computeLambertFunctionGooding(), tudat::mathematical_constants::PI, and TUDAT_NAN.
Referenced by tudat::mission_segments::LambertTargeterGooding::execute().