Tudat: tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType > Class Template Reference
tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType > Class Template Reference
Extended Kalman filter class.
#include <extendedKalmanFilter.h>
Public Types
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix DependentMatrix
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentVector DependentVector
Inherit typedefs from base class.
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::Function Function
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::Integrator Integrator
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings IntegratorSettings
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction MatrixFunction
Public Types inherited from tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >
typedef FilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix DependentMatrix
typedef FilterBase< IndependentVariableType, DependentVariableType >::DependentVector DependentVector
Inherit typedefs from base class.
typedef FilterBase< IndependentVariableType, DependentVariableType >::Function Function
typedef FilterBase< IndependentVariableType, DependentVariableType >::Integrator Integrator
typedef FilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings IntegratorSettings
typedef FilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction MatrixFunction
Public Types inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
typedef Eigen::Matrix< DependentVariableType, Eigen::Dynamic, Eigen::Dynamic > DependentMatrix
Typedef of the state and measurement matrices.
typedef Eigen::Matrix< DependentVariableType, Eigen::Dynamic, 1 > DependentVector
Typedef of the state and measurement vectors.
typedef std::function< DependentVector(const IndependentVariableType, const DependentVector &) > Function
Typedef of the function describing the system and the measurements.
typedef numerical_integrators::NumericalIntegrator< IndependentVariableType, DependentVector, DependentVector, IndependentVariableType > Integrator
Typedef of the integrator.
typedef numerical_integrators::IntegratorSettings< IndependentVariableType > IntegratorSettings
Typedef of the integrator settings.
typedef std::function< DependentMatrix(const IndependentVariableType, const DependentVector &) > MatrixFunction
Typedefs for system and measurement matrix functions.
Public Member Functions
ExtendedKalmanFilter (const Function &systemFunction, const Function &measurementFunction, const MatrixFunction &stateJacobianFunction, const MatrixFunction &stateNoiseJacobianFunction, const MatrixFunction &measurementJacobianFunction, const MatrixFunction &measurementNoiseJacobianFunction, const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings=nullptr)
Default constructor.
~ExtendedKalmanFilter ()
Destructor.
void updateFilter (const DependentVector &currentMeasurementVector)
Function to update the filter with the new step data.
Public Member Functions inherited from tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >
KalmanFilterBase (const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings)
Constructor.
virtual ~KalmanFilterBase ()
Destructor.
Public Member Functions inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
FilterBase (const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings)
Constructor.
virtual ~FilterBase ()
Destructor.
void clearFilterHistory ()
Function to clear the history of stored variables.
DependentMatrix getCurrentCovarianceEstimate ()
Function to retrieve current covariance estimate.
DependentVector getCurrentStateEstimate ()
Function to retrieve current state estimate.
IndependentVariableType getCurrentTime ()
Function to retrieve current time.
std::map< IndependentVariableType, DependentMatrix > getEstimatedCovarianceHistory ()
Function to retrieve the history of estimated covariance matrices.
std::map< IndependentVariableType, DependentVector > getEstimatedStateHistory ()
Function to retrieve the history of estimated states.
IndependentVariableType getFilteringStepSize ()
Function to retrieve step-size for filtering.
IndependentVariableType getInitialTime ()
Function to retrieve initial time.
std::pair< std::vector< DependentVector >, std::vector< DependentVector > > getNoiseHistory ()
Function to retrieve the history of system and measurement noise used by the updateFilter function.
void modifyCurrentStateAndCovarianceEstimates (const DependentVector &newStateEstimate, const DependentMatrix &newCovarianceEstimate=DependentMatrix::Zero())
Function to update the a-posteriori estimates of state and covariance with external data.
void modifyCurrentTime (const double newCurrentTime)
Function to modify the current time.
void modifyFilteringStepSize (const double newFilteringStepSize)
Function to modify the step size for filtering.
DependentVector produceMeasurementNoise ()
Function to produce measurement noise.
DependentVector produceSystemNoise ()
Function to produce system noise.
void revertToPreviousTimeStep (const double timeToBeRemoved)
Function to revert to the previous time step.
Private Member Functions
DependentVector createMeasurementFunction (const IndependentVariableType currentTime, const DependentVector &currentStateVector)
Function to create the function that defines the system model.
DependentVector createSystemFunction (const IndependentVariableType currentTime, const DependentVector &currentStateVector)
Function to create the function that defines the system model.
std::pair< DependentMatrix, DependentMatrix > generateDiscreteTimeSystemJacobians (const DependentVector &currentStateVector)
Function to generate the discrete-time version of the system Jacobians.
Private Attributes
std::function< std::pair< DependentMatrix, DependentMatrix > const DependentVector &) > discreteTimeStateJacobians_
Function to return the discrete-time state Jacobians.
Function inputMeasurementFunction_
Measurement function input by user.
Function inputSystemFunction_
System function input by user.
MatrixFunction measurementJacobianFunction_
Measurement Jacobian matrix function.
MatrixFunction measurementNoiseJacobianFunction_
Measurement noise Jacobian matrix function.
MatrixFunction stateJacobianFunction_
State Jacobian matrix function.
MatrixFunction stateNoiseJacobianFunction_
State noise Jacobian matrix function.
Additional Inherited Members
Protected Member Functions inherited from tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >
virtual void correctCovariance (const DependentMatrix &aPrioriCovarianceEstimate, const DependentMatrix &currentMeasurementMatrix, const DependentMatrix &kalmanGain)
Function to correct the covariance for the next time step.
DependentVector predictState ()
Function to predict the state for the next time step.
DependentVector predictState (const DependentVector &currentStateVector)
Function to predict the state for the next time step, by overwriting previous state.
Protected Member Functions inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
virtual void clearSpecificFilterHistory ()
Function to clear the history of stored variables for derived class-specific variables.
void correctState (const DependentVector &aPrioriStateEstimate, const DependentVector &currentMeasurementVector, const DependentVector &measurementEstimate, const DependentMatrix &gainMatrix)
Function to correct the state for the next time step.
virtual void specificRevertToPreviousTimeStep (const double timeToBeRemoved)
Function to revert to the previous time step for derived class-specific variables.
Protected Attributes inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
DependentMatrix aPosterioriCovarianceEstimate_
Matrix representing the a-posteriori estimated covariance.
DependentVector aPosterioriStateEstimate_
Vector representing the a-posteriori estimated state.
IndependentVariableType currentTime_
Scalar representing the current time.
IndependentVariableType filteringStepSize_
Scalar representing step-size for filtering process.
std::map< IndependentVariableType, DependentMatrix > historyOfCovarianceEstimates_
Map of estimated covariance matrices history.
std::map< IndependentVariableType, DependentVector > historyOfStateEstimates_
Map of estimated states vectors history.
DependentMatrix identityMatrix_
Indentity matrix.
const IndependentVariableType initialTime_
Scalar representing the initial time.
std::shared_ptr< Integrator > integrator_
Pointer to the integrator.
bool isStateToBeIntegrated_
Boolean specifying whether the state needs to be integrated.
Function measurementFunction_
Measurement function.
const DependentMatrix measurementUncertainty_
Matrix representing the uncertainty in measurement modeling.
Function systemFunction_
System function.
const DependentMatrix systemUncertainty_
Matrix representing the uncertainty in system modeling.
Detailed Description
template<typename IndependentVariableType = double, typename DependentVariableType = double>
class tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >
Class for the set up and use of the extended Kalman filter.
Template Parameters
IndependentVariableType Type of independent variable. Default is double.
DependentVariableType Type of dependent variable. Default is double.
Definition at line 32 of file extendedKalmanFilter.h.
Member Typedef Documentation
DependentVector
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentVector tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::DependentVector
Definition at line 37 of file extendedKalmanFilter.h.
DependentMatrix
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::DependentMatrix
Definition at line 38 of file extendedKalmanFilter.h.
Function
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::Function tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::Function
Definition at line 39 of file extendedKalmanFilter.h.
MatrixFunction
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::MatrixFunction
Definition at line 40 of file extendedKalmanFilter.h.
IntegratorSettings
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::IntegratorSettings
Definition at line 41 of file extendedKalmanFilter.h.
Integrator
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::Integrator tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::Integrator
Definition at line 42 of file extendedKalmanFilter.h.
Constructor & Destructor Documentation
ExtendedKalmanFilter()
template<typename IndependentVariableType = double, typename DependentVariableType = double> tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::ExtendedKalmanFilter (const Function & systemFunction, const Function & measurementFunction, const MatrixFunction & stateJacobianFunction, const MatrixFunction & stateNoiseJacobianFunction, const MatrixFunction & measurementJacobianFunction, const MatrixFunction & measurementNoiseJacobianFunction, const DependentMatrix & systemUncertainty, const DependentMatrix & measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector & initialStateVector, const DependentMatrix & initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings = nullptr) inline
Default constructor. This constructor takes state and measurement functions and their respective Jacobian functions as inputs. These functions can be a function of time and state vector.
Parameters
systemFunction Function returning the state as a function of time and state vector. Can be a differential equation if the integratorSettings is set (i.e., if it is not a nullptr).
measurementFunction Function returning the measurement as a function of time and state.
stateJacobianFunction Function returning the Jacobian of the system w.r.t. the state. The input values can be time and state vector.
stateNoiseJacobianFunction Function returning the Jacobian of the system function w.r.t. the system noise. The input values can be time and state vector.
measurementJacobianFunction Function returning the Jacobian of the measurement function w.r.t. the state. The input values can be time and state vector.
measurementNoiseJacobianFunction Function returning the Jacobian of the measurement function w.r.t. the measurement noise. The input values can be time and state vector.
systemUncertainty Matrix defining the uncertainty in modeling of the system.
measurementUncertainty Matrix defining the uncertainty in modeling of the measurements.
filteringStepSize Scalar representing the value of the constant filtering time step.
initialTime Scalar representing the value of the initial time.
initialStateVector Vector representing the initial (estimated) state of the system. It is used as first a-priori estimate of the state vector.
initialCovarianceMatrix Matrix representing the initial (estimated) covariance of the system. It is used as first a-priori estimate of the covariance matrix.
integratorSettings Pointer to integration settings defining the integrator to be used to propagate the state.
Definition at line 69 of file extendedKalmanFilter.h.
References tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::discreteTimeStateJacobians_, tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::generateDiscreteTimeSystemJacobians(), and tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::isStateToBeIntegrated_.
~ExtendedKalmanFilter()
template<typename IndependentVariableType = double, typename DependentVariableType = double> tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::~ExtendedKalmanFilter () inline
Definition at line 99 of file extendedKalmanFilter.h.
Member Function Documentation
updateFilter()
template<typename IndependentVariableType = double, typename DependentVariableType = double> void tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter (const DependentVector & currentMeasurementVector) inline virtual
Function to update the filter with the new step data.
Parameters
currentMeasurementVector Vector representing current measurement.
Implements tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >.
Definition at line 106 of file extendedKalmanFilter.h.
References tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::aPosterioriCovarianceEstimate_, tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::correctCovariance(), tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::correctState(), tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::currentTime_, tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::discreteTimeStateJacobians_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::filteringStepSize_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::isStateToBeIntegrated_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::measurementFunction_, tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::measurementJacobianFunction_, tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::measurementNoiseJacobianFunction_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::measurementUncertainty_, tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::predictState(), tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::stateJacobianFunction_, tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::stateNoiseJacobianFunction_, and tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::systemUncertainty_.
createSystemFunction()
template<typename IndependentVariableType = double, typename DependentVariableType = double> DependentVector tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::createSystemFunction (const IndependentVariableType currentTime, const DependentVector & currentStateVector) inline private virtual
Function to create the function that defines the system model. The output of this function is then bound to the systemFunction_ variable, via the std::bind command.
Parameters
currentTime Scalar representing the current time.
currentStateVector Vector representing the current state.
Returns
Vector representing the estimated state.
Implements tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >.
Definition at line 157 of file extendedKalmanFilter.h.
References tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::inputSystemFunction_.
createMeasurementFunction()
template<typename IndependentVariableType = double, typename DependentVariableType = double> DependentVector tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::createMeasurementFunction (const IndependentVariableType currentTime, const DependentVector & currentStateVector) inline private virtual
Function to create the function that defines the system model. The output of this function is then bound to the measurementFunction_ variable, via the std::bind command.
Parameters
currentTime Scalar representing the current time.
currentStateVector Vector representing the current state.
Returns
Vector representing the estimated measurement.
Implements tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >.
Definition at line 171 of file extendedKalmanFilter.h.
References tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::inputMeasurementFunction_.
generateDiscreteTimeSystemJacobians()
template<typename IndependentVariableType = double, typename DependentVariableType = double> std::pair< DependentMatrix, DependentMatrix > tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::generateDiscreteTimeSystemJacobians (const DependentVector & currentStateVector) inline private
Function to generate the discrete-time version of the system Jacobians, from the continuous-time versions. The transformation is carried out by using the matrix exponential.
Parameters
currentStateVector Vector representing the current state.
Returns
Pair of discrete-time state and noise Jacobians.
Definition at line 184 of file extendedKalmanFilter.h.
References tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::currentTime_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::filteringStepSize_, tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::stateJacobianFunction_, and tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::stateNoiseJacobianFunction_.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::ExtendedKalmanFilter().
Member Data Documentation
inputSystemFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> Function tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::inputSystemFunction_ private
Definition at line 209 of file extendedKalmanFilter.h.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::createSystemFunction().
inputMeasurementFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> Function tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::inputMeasurementFunction_ private
Definition at line 212 of file extendedKalmanFilter.h.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::createMeasurementFunction().
stateJacobianFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> MatrixFunction tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::stateJacobianFunction_ private
Function returning the continuous-time Jacobian of the systemFunction_ w.r.t. the state vector. The input values can be time and state vector.
Definition at line 219 of file extendedKalmanFilter.h.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::generateDiscreteTimeSystemJacobians(), and tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
stateNoiseJacobianFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> MatrixFunction tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::stateNoiseJacobianFunction_ private
Function returning the continuous-time Jacobian of the systemFunction_ w.r.t. the state noise. The input values can be time and state vector.
Definition at line 226 of file extendedKalmanFilter.h.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::generateDiscreteTimeSystemJacobians(), and tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
measurementJacobianFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> MatrixFunction tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::measurementJacobianFunction_ private
Function returning the continuous-time Jacobian of the measurementFunction_ w.r.t. the state vector. The input values can be time and state vector.
Definition at line 233 of file extendedKalmanFilter.h.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
measurementNoiseJacobianFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> MatrixFunction tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::measurementNoiseJacobianFunction_ private
Function returning the continuous-time Jacobian of the measurementFunction_ w.r.t. the measurement noise. The input values can be time and state vector.
Definition at line 240 of file extendedKalmanFilter.h.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
discreteTimeStateJacobians_
template<typename IndependentVariableType = double, typename DependentVariableType = double> std::function< std::pair< DependentMatrix, DependentMatrix > const DependentVector&) > tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::discreteTimeStateJacobians_ private
Function to return the discrete-time state Jacobians, i.e., the Jacobians of the stateFunction_ w.r.t. the state itself and the state noise. Transformation to discrete-time is done with the function generateDiscreteTimeSystemJacobians.
Definition at line 248 of file extendedKalmanFilter.h.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::ExtendedKalmanFilter(), and tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
The documentation for this class was generated from the following file:
Mathematics/Filters/extendedKalmanFilter.h