Tudat: tudat::observation_partials::OneWayRangePartial Class Reference
tudat::observation_partials::OneWayRangePartial Class Reference
Class to compute the partial derivatives of a one-way range observation partial.
#include <oneWayRangePartial.h>
Public Types
typedef std::vector< std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > > OneWayRangePartialReturnType
typedef std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > SingleOneWayRangePartialReturnType
Public Member Functions
OneWayRangePartial (const std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler, const std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > &positionPartialList, const estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > &lighTimeCorrectionPartials=std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >())
Constructor.
~OneWayRangePartial ()
Destructor.
virtual OneWayRangePartialReturnType calculatePartial (const std::vector< Eigen::Vector6d > &states, const std::vector< double > &times, const observation_models::LinkEndType linkEndOfFixedTime, const Eigen::Vector1d &currentObservation=Eigen::Vector1d::Constant(TUDAT_NAN))
Function to calculate the observation partial(s) at required time and state.
int getNumberOfLighTimeCorrectionPartialsFunctions ()
Function to get the number of light-time correction partial functions.
std::shared_ptr< OneWayRangeScaling > getOneWayRangeScaler ()
Function to get scaling object used for mapping partials of positions to partials of observable.
Public Member Functions inherited from tudat::observation_partials::ObservationPartial< 1 >
ObservationPartial (const estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier)
Constructor.
virtual ~ObservationPartial ()
Virtual destructor.
virtual std::vector< std::pair< Eigen::Matrix< double, ObservationSize, Eigen::Dynamic >, double > > calculatePartial (const std::vector< Eigen::Vector6d > &states, const std::vector< double > &times, const observation_models::LinkEndType linkEndOfFixedTime=observation_models::receiver, const Eigen::Matrix< double, ObservationSize, 1 > &currentObservation=Eigen::Matrix< double, ObservationSize, 1 >::Constant(TUDAT_NAN))=0
Pure virtual function to calculate the observation partial(s) at required time(s) and state(s)
estimatable_parameters::EstimatebleParameterIdentifier getParameterIdentifier ()
Function to get parameter id of for specifc parameter of which partial is computed by object.
Protected Attributes
Eigen::Vector6d currentState_
Pre-declared state variable to be used in calculatePartial function.
double currentTime_
Pre-declared time variable to be used in calculatePartial function.
std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > lighTimeCorrectionPartials_
List of light-time correction partial objects.
std::vector< std::function< SingleOneWayRangePartialReturnType(const std::vector< Eigen::Vector6d > &, const std::vector< double > &) > > lighTimeCorrectionPartialsFunctions_
List of light-time correction partial functions.
std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler_
Scaling object used for mapping partials of positions to partials of observable.
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > >::iterator positionPartialIterator_
Iterator over list of position partials per link end.
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > positionPartialList_
List of position partials per link end.
Protected Attributes inherited from tudat::observation_partials::ObservationPartial< 1 >
estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier_
Parameter id of for specifc parameter of which partial is computed by object.
Detailed Description
Definition at line 104 of file oneWayRangePartial.h.
Member Typedef Documentation
OneWayRangePartialReturnType
typedef std::vector< std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > > tudat::observation_partials::OneWayRangePartial::OneWayRangePartialReturnType
Definition at line 109 of file oneWayRangePartial.h.
SingleOneWayRangePartialReturnType
typedef std::pair< Eigen::Matrix< double, 1, Eigen::Dynamic >, double > tudat::observation_partials::OneWayRangePartial::SingleOneWayRangePartialReturnType
Definition at line 110 of file oneWayRangePartial.h.
Constructor & Destructor Documentation
OneWayRangePartial()
tudat::observation_partials::OneWayRangePartial::OneWayRangePartial (const std::shared_ptr< OneWayRangeScaling > oneWayRangeScaler, const std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > & positionPartialList, const estimatable_parameters::EstimatebleParameterIdentifier parameterIdentifier, const std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > & lighTimeCorrectionPartials = std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > >()) inline
Constructor
Parameters
oneWayRangeScaler Scaling object used for mapping partials of positions to partials of observable
positionPartialList List of position partials per link end.
parameterIdentifier Id of parameter for which instance of class computes partial derivatives.
lighTimeCorrectionPartials List if light-time correction partial objects.
Definition at line 120 of file oneWayRangePartial.h.
References tudat::observation_partials::getLightTimeParameterPartialFunction, and lighTimeCorrectionPartialsFunctions_.
~OneWayRangePartial()
tudat::observation_partials::OneWayRangePartial::~OneWayRangePartial () inline
Definition at line 147 of file oneWayRangePartial.h.
Member Function Documentation
calculatePartial()
OneWayRangePartial::OneWayRangePartialReturnType tudat::observation_partials::OneWayRangePartial::calculatePartial (const std::vector< Eigen::Vector6d > & states, const std::vector< double > & times, const observation_models::LinkEndType linkEndOfFixedTime, const Eigen::Vector1d & currentObservation = Eigen::Vector1d::Constant(TUDAT_NAN)) virtual
Function to calculate the observation partial(s) at required time and state. State and time are typically obtained from evaluation of observation model.
Parameters
states Link end states. Index maps to link end for a given ObsevableType through getLinkEndIndex function.
times Link end time.
linkEndOfFixedTime Link end that is kept fixed when computing the observable.
currentObservation Value of the observation for which the partial is to be computed (default NaN for compatibility purposes)
Returns
Vector of pairs containing partial values and associated times.
Definition at line 51 of file oneWayRangePartial.cpp.
References currentState_, currentTime_, lighTimeCorrectionPartialsFunctions_, oneWayRangeScaler_, positionPartialIterator_, positionPartialList_, tudat::observation_models::receiver, tudat::physical_constants::SPEED_OF_LIGHT, and tudat::observation_models::transmitter.
getOneWayRangeScaler()
std::shared_ptr< OneWayRangeScaling > tudat::observation_partials::OneWayRangePartial::getOneWayRangeScaler () inline
Function to get scaling object used for mapping partials of positions to partials of observable
Returns
Definition at line 171 of file oneWayRangePartial.h.
References oneWayRangeScaler_.
getNumberOfLighTimeCorrectionPartialsFunctions()
int tudat::observation_partials::OneWayRangePartial::getNumberOfLighTimeCorrectionPartialsFunctions () inline
Number of light-time correction partial functions.
Returns
Number of light-time correction partial functions.
Definition at line 181 of file oneWayRangePartial.h.
References lighTimeCorrectionPartialsFunctions_.
Member Data Documentation
oneWayRangeScaler_
std::shared_ptr< OneWayRangeScaling > tudat::observation_partials::OneWayRangePartial::oneWayRangeScaler_ protected
Definition at line 189 of file oneWayRangePartial.h.
Referenced by calculatePartial(), and getOneWayRangeScaler().
positionPartialList_
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > > tudat::observation_partials::OneWayRangePartial::positionPartialList_ protected
Definition at line 192 of file oneWayRangePartial.h.
Referenced by calculatePartial().
positionPartialIterator_
std::map< observation_models::LinkEndType, std::shared_ptr< CartesianStatePartial > >::iterator tudat::observation_partials::OneWayRangePartial::positionPartialIterator_ protected
Definition at line 195 of file oneWayRangePartial.h.
Referenced by calculatePartial().
lighTimeCorrectionPartialsFunctions_
std::vector< std::function< SingleOneWayRangePartialReturnType(const std::vector< Eigen::Vector6d >&, const std::vector< double >&) > > tudat::observation_partials::OneWayRangePartial::lighTimeCorrectionPartialsFunctions_ protected
Definition at line 200 of file oneWayRangePartial.h.
Referenced by calculatePartial(), getNumberOfLighTimeCorrectionPartialsFunctions(), and OneWayRangePartial().
lighTimeCorrectionPartials_
std::vector< std::shared_ptr< observation_partials::LightTimeCorrectionPartial > > tudat::observation_partials::OneWayRangePartial::lighTimeCorrectionPartials_ protected
Definition at line 203 of file oneWayRangePartial.h.
currentState_
Eigen::Vector6d tudat::observation_partials::OneWayRangePartial::currentState_ protected
Definition at line 206 of file oneWayRangePartial.h.
Referenced by calculatePartial().
currentTime_
double tudat::observation_partials::OneWayRangePartial::currentTime_ protected
Definition at line 209 of file oneWayRangePartial.h.
Referenced by calculatePartial().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/ObservationPartials/oneWayRangePartial.h
Astrodynamics/OrbitDetermination/ObservationPartials/oneWayRangePartial.cpp