Tudat: tudat::sofa_interface Namespace Reference
tudat::sofa_interface Namespace Reference
Functions
Eigen::Vector6d calculateApproximateDelaunayFundamentalArgumentsWithGmst (const double tdbTime)
Function to calculate the Delaunay fundamental arguments and (GMST + pi) at the requested time.
Eigen::Matrix< double, 5, 1 > calculateDelaunayFundamentalArguments (const double tdbTime)
Function to calculate the Delaunay fundamental arguments at the requested time.
Eigen::Vector6d calculateDelaunayFundamentalArgumentsWithGmst (const double tdbTime, const double terrestrialTime, const double universalTime1)
Function to calculate the Delaunay fundamental arguments and (GMST + pi) at the requested time.
Eigen::Vector6d calculateDoodsonFundamentalArguments (const double tdbTime, const double terrestrialTime, const double universalTime1)
Function to calculate the Doodson arguments at the requested time.
Eigen::Vector6d calculateDoodsonFundamentalArguments (const double tdbTime)
Function to calculate the Doodson arguments at the requested time.
double calculateEarthRotationAngle (const double ut1, const double julianDaysEpochShift)
Function to calculate ERA (earth rotation angle)
template<typename TimeType >
double calculateEarthRotationAngleTemplated (const TimeType currentUt1)
Function to calculate ERA (earth rotation angle) in templated precision.
template<>
double calculateEarthRotationAngleTemplated< double > (const double currentUt1)
Function to calculate ERA (earth rotation angle) in double precision.
template<>
double calculateEarthRotationAngleTemplated< Time > (const Time currentUt1)
Function to calculate ERA (earth rotation angle) in Time precision.
double calculateGreenwichMeanSiderealTime (const double terrestrialTime, const double universalTime1, const double referenceJulianDay, const basic_astrodynamics::IAUConventions iauConvention)
Function to calculate GMST according to requested IAU conventions.
double calculateLongitudeOfMoonsAscendingNode (const double julianCenturiesSinceJ2000)
Function to calculate longitude of the Moon's ascending node.
double calculateMeanAnomalyOfMoon (const double julianCenturiesSinceJ2000)
Function to calculate mean anomaly of the Moon.
double calculateMeanAnomalyOfSun (const double julianCenturiesSinceJ2000)
Function to calculate mean anomaly of the Sun.
double calculateMeanArgumentOfLatitudeOfMoon (const double julianCenturiesSinceJ2000)
Function to calculate mean argument of latitude of the Moon.
double calculateMeanElongationOfMoonFromSun (const double julianCenturiesSinceJ2000)
Function to calculate mean elongation of the Moon from the Sun.
template<typename TimeType >
TimeType convertTAItoUTC (const TimeType taiSeconds)
Function to convert TAI to UTC.
template<typename TimeType >
TimeType convertTTtoUTC (const TimeType tt)
Function to convert TT to UTC.
template<typename TimeType >
TimeType convertUTCtoTAI (const TimeType utcSeconds)
Function to convert UTC to TAI.
template<typename TimeType >
TimeType convertUTCtoTT (const TimeType utc)
Function to convert UTC to TT.
double getDeltaAtFromTai (const double taiInJulianDays)
Function to calculate number of leap seconds from TAI input.
double getDeltaAtFromUtc (const double utcInJulianDays)
Function to calculate number of leap seconds from UTC input.
Eigen::Matrix3d getFrameBias (const double julianDaysSinceReference, const basic_astrodynamics::IAUConventions precessionNutationTheory, const double referenceJulianDay)
Function to compute the rotation matrix from GCRS to J2000 at epoch.
std::pair< Eigen::Vector2d, double > getPositionOfCipInGcrs (const double terrestrialTime, const double julianDaysEpochShift, const basic_astrodynamics::IAUConventions precessionNutationTheory)
Function to calculate CIP and CIO locator according to requested IAU conventions.
double getTDBminusTT (const double tdbTime, const double universalTimeFractionOfDay, const double stationLongitude, const double distanceFromSpinAxis, const double distanceFromEquatorialPlane)
Function to calculate difference between TDB and TT.
double getTDBminusTT (const double tdbTime, const double universalTimeFractionOfDay, const Eigen::Vector3d &stationCartesianPosition)
Function to calculate difference between TDB and TT.
double getTDBminusTT (const double ttOrTdbSinceJ2000, const double stationLongitude, const double distanceFromSpinAxis, const double distanceFromEquatorialPlane)
Function to calculate difference between TDB and TT.
double getTDBminusTT (const double ttOrTdbSinceJ2000, const Eigen::Vector3d &stationCartesianPosition)
Function to calculate difference between TDB and TT.
Variables
static const Eigen::Matrix< double, 5, 5 > delaunayToDoodsonArguments
Matrix to convert 5 Doodson arguments (without GMST) to Delaunay arguments.
static const Eigen::Matrix< double, 5, 5 > doodsonToDelaunayArguments
Matrix to convert delaunay arguments to 5 Doodson arguments (without GMST).
Function Documentation
getPositionOfCipInGcrs()
std::pair< Eigen::Vector2d, double > tudat::sofa_interface::getPositionOfCipInGcrs (const double terrestrialTime, const double referenceJulianDay = basic_astrodynamics::JULIAN_DAY_ON_J2000, const basic_astrodynamics::IAUConventions precessionNutationTheory = basic_astrodynamics::iau_2000_b)
Function to calculate CIP (Celestial Intermediate Pole, typically denoted as X and Y) and CIO locator (Celestial Intermediate Origin, typically denoted s) according to requested IAU conventions using Sofa implementation. See Petit et al. (2010), chap. 5 for more details on requested variables. Note that this function does not include empirical corrections, published as daily values by the IERS.
Parameters
terrestrialTime Time in TT in seconds since referenceJulianDay julianDay.
referenceJulianDay Julian day wrt which tt is referenced (default = J2000)
precessionNutationTheory IAU conventions that are to be used for calculation (i.e. determining which Sofa function to call)
Returns
Pair of first: Vector of entries X, Y (in that order) CIP values and second: CIO locator.
Definition at line 23 of file earthOrientation.cpp.
References tudat::basic_astrodynamics::iau_2000_a, tudat::basic_astrodynamics::iau_2000_b, tudat::basic_astrodynamics::iau_2006, and tudat::physical_constants::JULIAN_DAY.
Referenced by tudat::earth_orientation::PrecessionNutationCalculator::PrecessionNutationCalculator().
calculateGreenwichMeanSiderealTime()
double tudat::sofa_interface::calculateGreenwichMeanSiderealTime (const double terrestrialTime, const double universalTime1, const double referenceJulianDay = basic_astrodynamics::JULIAN_DAY_ON_J2000, const basic_astrodynamics::IAUConventions iauConvention = basic_astrodynamics::iau_2000_b)
Function to calculate GMST (Greenwich Mean Sidereal Time) according to requested IAU conventions using Sofa implementation. Note that this function does not include empirical corrections, as published as daily values by IERS.
Parameters
terrestrialTime Time in TT in seconds since reference julian day.
universalTime1 Time in UT1 in seconds since reference julian day.
referenceJulianDay Julian day wrt which input times are referenced (default = J2000)
iauConvention IAU conventions that are to be used for calculation (i.e. determining which Sofa function to call)
Returns
Current GMST (normalized to [0,2 pi]).
Definition at line 60 of file earthOrientation.cpp.
References tudat::basic_astrodynamics::iau_2000_a, tudat::basic_astrodynamics::iau_2000_b, tudat::basic_astrodynamics::iau_2006, tudat::physical_constants::JULIAN_DAY, and TUDAT_NAN.
calculateEarthRotationAngle()
double tudat::sofa_interface::calculateEarthRotationAngle (const double ut1, const double referenceJulianDay)
Function to calculate ERA (earth rotation angle) from current UT1. The ERA represents one of the Euler angles (between CIO and TIO) for transforming from ITRS to GCRS, see Petit et al. chap. 5
Parameters
ut1 Time in UT1 in seconds since referenceJulianDay julianDay.
referenceJulianDay Julian day wrt which ut1 is referenced (default = J2000)
Returns
Current Earth rotation angle (normalized to [0,2 pi]).
Definition at line 94 of file earthOrientation.cpp.
References tudat::physical_constants::JULIAN_DAY.
Referenced by calculateEarthRotationAngleTemplated< double >(), and calculateEarthRotationAngleTemplated< Time >().
calculateEarthRotationAngleTemplated< double >()
template<> double tudat::sofa_interface::calculateEarthRotationAngleTemplated< double > (const double currentUt1)
Definition at line 101 of file earthOrientation.cpp.
References calculateEarthRotationAngle(), and tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000.
calculateEarthRotationAngleTemplated< Time >()
template<> double tudat::sofa_interface::calculateEarthRotationAngleTemplated< Time > (const Time currentUt1)
Definition at line 109 of file earthOrientation.cpp.
References calculateEarthRotationAngle(), and tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000.
getFrameBias()
Eigen::Matrix3d tudat::sofa_interface::getFrameBias (const double julianDaysSinceReference, const basic_astrodynamics::IAUConventions precessionNutationTheory = basic_astrodynamics::iau_2006, const double referenceJulianDay = basic_astrodynamics::JULIAN_DAY_ON_J2000)
Function to compute the rotation matrix from GCRS to J2000 at epoch, e.g. frame bias
Parameters
julianDaysSinceReference Days since reference epoch at which the frame bias is to be determined
precessionNutationTheory IAU precession theory to use
referenceJulianDay Reference Julian day for julianDaysSinceReference
Returns
Definition at line 123 of file earthOrientation.cpp.
References tudat::basic_astrodynamics::iau_2006.
calculateEarthRotationAngleTemplated()
template<typename TimeType > double tudat::sofa_interface::calculateEarthRotationAngleTemplated (const TimeType currentUt1)
Function to calculate ERA (earth rotation angle) from current UT1 in templated precision. The ERA represents one of the Euler angles (between CIO and TIO) for transforming from ITRS to GCRS, see Petit et al. chap. 5
Parameters
currentUt1 Time in UT1
Returns
Current Earth rotation angle (normalized to [0,2 pi]).
calculateMeanElongationOfMoonFromSun()
double tudat::sofa_interface::calculateMeanElongationOfMoonFromSun (const double julianCenturiesSinceJ2000)
Function to calculate mean elongation of the Moon from the Sun fundamental argument using Sofa implementation
Parameters
julianCenturiesSinceJ2000 Julian centuries (period of 36525 days of 86400 seconds) since J2000
Returns
Mean elongation of the Moon from the Sun
Definition at line 21 of file fundamentalArguments.cpp.
Referenced by calculateDelaunayFundamentalArguments(), and calculateDoodsonFundamentalArguments().
calculateMeanArgumentOfLatitudeOfMoon()
double tudat::sofa_interface::calculateMeanArgumentOfLatitudeOfMoon (const double julianCenturiesSinceJ2000)
Function to calculate mean argument of latitude of the Moon fundamental argument using Sofa implementation
Parameters
julianCenturiesSinceJ2000 Julian centuries (period of 36525 days of 86400 seconds) since J2000
Returns
Mean argument of latitude of the Moon
Definition at line 27 of file fundamentalArguments.cpp.
Referenced by calculateDelaunayFundamentalArguments(), and calculateDoodsonFundamentalArguments().
calculateMeanAnomalyOfMoon()
double tudat::sofa_interface::calculateMeanAnomalyOfMoon (const double julianCenturiesSinceJ2000)
Function to calculate mean anomaly of the Moon fundamental argument using Sofa implementation
Parameters
julianCenturiesSinceJ2000 Julian centuries (period of 36525 days of 86400 seconds) since J2000
Returns
Mean anomaly of the Moon
Definition at line 33 of file fundamentalArguments.cpp.
Referenced by calculateDelaunayFundamentalArguments(), and calculateDoodsonFundamentalArguments().
calculateMeanAnomalyOfSun()
double tudat::sofa_interface::calculateMeanAnomalyOfSun (const double julianCenturiesSinceJ2000)
Function to calculate mean anomaly of the Sun fundamental argument using Sofa implementation
Parameters
julianCenturiesSinceJ2000 Julian centuries (period of 36525 days of 86400 seconds) since J2000
Returns
Mean anomaly of the Sun
Definition at line 39 of file fundamentalArguments.cpp.
Referenced by calculateDelaunayFundamentalArguments(), and calculateDoodsonFundamentalArguments().
calculateLongitudeOfMoonsAscendingNode()
double tudat::sofa_interface::calculateLongitudeOfMoonsAscendingNode (const double julianCenturiesSinceJ2000)
Function to calculate longitude of the Moon's ascending node fundamental argument using Sofa implementation
Parameters
julianCenturiesSinceJ2000 Julian centuries (period of 36525 days of 86400 seconds) since J2000
Returns
Longitude of the Moon's ascending node
Definition at line 45 of file fundamentalArguments.cpp.
Referenced by calculateDelaunayFundamentalArguments(), and calculateDoodsonFundamentalArguments().
calculateDelaunayFundamentalArguments()
Eigen::Matrix< double, 5, 1 > tudat::sofa_interface::calculateDelaunayFundamentalArguments (const double tdbTime)
Function to calculate the Delaunay fundamental arguments at the requested time, using Sofa implementation of angle calculations. Using the typical notation of the angles, the output order is: l, l', F, D, Omega.
Parameters
tdbTime Time in TDB at which the arguments are to be calculated.
Returns
Delaunay fundamental arguments at the requested time.
Definition at line 51 of file fundamentalArguments.cpp.
References calculateLongitudeOfMoonsAscendingNode(), calculateMeanAnomalyOfMoon(), calculateMeanAnomalyOfSun(), calculateMeanArgumentOfLatitudeOfMoon(), calculateMeanElongationOfMoonFromSun(), and tudat::basic_astrodynamics::convertSecondsSinceEpochToJulianCenturiesSinceEpoch().
Referenced by calculateDelaunayFundamentalArgumentsWithGmst().
calculateDelaunayFundamentalArgumentsWithGmst()
Eigen::Vector6d tudat::sofa_interface::calculateDelaunayFundamentalArgumentsWithGmst (const double tdbTime, const double terrestrialTime, const double universalTime1)
Function to calculate the Delaunay fundamental arguments and (GMST + pi) at the requested time, using Sofa implementation of angle calculations. Using the typical notation of the angles, the output order is: (GMST + pi), l, l', F, D, Omega. We stress that the first argument is GMST with a 180 degree phase shift
Parameters
tdbTime Time in TDB at which the arguments are to be calculated, in seconds since J2000.
terrestrialTime Time in TT at which the arguments are to be calculated, in seconds since J2000.
universalTime1 Time in UT1 at which the arguments are to be calculated, in seconds since J2000.
Returns
Delaunay fundamental arguments and (GMST + pi) at the requested time.
Definition at line 66 of file fundamentalArguments.cpp.
References calculateDelaunayFundamentalArguments(), tudat::physical_constants::JULIAN_DAY, tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000, and tudat::mathematical_constants::PI.
Referenced by calculateApproximateDelaunayFundamentalArgumentsWithGmst().
calculateApproximateDelaunayFundamentalArgumentsWithGmst()
Eigen::Vector6d tudat::sofa_interface::calculateApproximateDelaunayFundamentalArgumentsWithGmst (const double tdbTime)
Function to calculate the Delaunay fundamental arguments and (GMST + pi) at the requested time, using Sofa implementation of angle calculations. When using this function, TT and TDB are assumed equal, as are UTC and UT1, for the purposes of calculating GMST (which requires TT and UT1). Using the typical notation of the angles, the output order is: (GMST + pi), l, l', F, D, Omega. We stress that the first argument is GMST with a 180 degree phase shift
Parameters
tdbTime Time in TDB at which the arguments are to be calculated, in seconds since J2000.
Returns
Delaunay fundamental arguments and (GMST + pi) at the requested time.
Definition at line 83 of file fundamentalArguments.cpp.
References calculateDelaunayFundamentalArgumentsWithGmst(), and convertTTtoUTC().
Referenced by tudat::earth_orientation::getDefaultPolarMotionCorrectionCalculator(), and tudat::earth_orientation::getDefaultUT1CorrectionCalculator().
calculateDoodsonFundamentalArguments() [1/2]
Eigen::Vector6d tudat::sofa_interface::calculateDoodsonFundamentalArguments (const double tdbTime, const double terrestrialTime, const double universalTime1)
Function to calculate the Doodson arguments at the requested time, using Sofa implementation of angle calculations. Using the typical notation of the angles, the output order is: (GMST + pi - s), s, h, p, N', p_{s}.
Parameters
tdbTime Time in TDB at which the arguments are to be calculated, in seconds since J2000.
terrestrialTime Time in TT at which the arguments are to be calculated, in seconds since J2000.
universalTime1 Time in UT1 at which the arguments are to be calculated, in seconds since J2000.
Returns
Doodson arguments and at the requested time.
Definition at line 90 of file fundamentalArguments.cpp.
References calculateLongitudeOfMoonsAscendingNode(), calculateMeanAnomalyOfMoon(), calculateMeanAnomalyOfSun(), calculateMeanArgumentOfLatitudeOfMoon(), calculateMeanElongationOfMoonFromSun(), tudat::basic_astrodynamics::convertSecondsSinceEpochToJulianCenturiesSinceEpoch(), tudat::physical_constants::JULIAN_DAY, tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000, and tudat::mathematical_constants::PI.
Referenced by calculateDoodsonFundamentalArguments().
calculateDoodsonFundamentalArguments() [2/2]
Eigen::Vector6d tudat::sofa_interface::calculateDoodsonFundamentalArguments (const double tdbTime)
Function to calculate the Doodson arguments at the requested time, using Sofa implementation of angle calculations. he Delaunay fundamental arguments and (GMST + pi) at the requested time, using Sofa implementation of angle calculations. When using this function, TT and TDB are assumed equal, as are UTC and UT1, for the purposes of calculating GMST (which requires TT and UT1). Using the typical notation of the angles, the output order is: (GMST + pi - s), s, h, p, N', p_{s}.
Parameters
tdbTime Time in TDB at which the arguments are to be calculated, in seconds since J2000.
Returns
Doodson arguments and at the requested time.
Definition at line 123 of file fundamentalArguments.cpp.
References calculateDoodsonFundamentalArguments(), and convertTTtoUTC().
getDeltaAtFromUtc()
double tudat::sofa_interface::getDeltaAtFromUtc (const double utcInJulianDays)
Function to calculate number of leap seconds from UTC (Universal Coordinated Time) input.
Parameters
utcInJulianDays Time in UTC; in julianDays since J2000.
Returns
Number of leap seconds at requested time.
Definition at line 24 of file sofaTimeConversions.cpp.
References tudat::input_output::field_types::time::day, tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000, tudat::input_output::field_types::time::month, and tudat::input_output::field_types::time::year.
Referenced by convertTAItoUTC(), convertUTCtoTAI(), and getDeltaAtFromTai().
getDeltaAtFromTai()
double tudat::sofa_interface::getDeltaAtFromTai (const double taiInJulianDays)
Function to calculate number of leap seconds from UTC (International Atomic Time) input. Note: this function will not work properly near the introduction of a leap second (specifically if TAI is less than the number of leap seconds from the leap second introduction) . In case of incorrect conversion, an error message is produced.
Parameters
taiInJulianDays Time in TAI; in seconds since J2000.
Returns
Number of leap seconds at requested time.
Definition at line 55 of file sofaTimeConversions.cpp.
References tudat::input_output::field_types::time::day, getDeltaAtFromUtc(), tudat::physical_constants::JULIAN_DAY, tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000, tudat::input_output::field_types::time::month, and tudat::input_output::field_types::time::year.
getTDBminusTT() [1/4]
double tudat::sofa_interface::getTDBminusTT (const double tdbTime, const double universalTimeFractionOfDay, const double stationLongitude, const double distanceFromSpinAxis, const double distanceFromEquatorialPlane)
Function to calculate difference between TDB (Dynamical Barycentric Time) and TT (Terrestrial Time), from Sofa function, which is based on decomposition of time ephemeris generated by Fairhead an Bretagnon (1990). Note that the time ephemeris should be generated by the direct solution of differential equations of proper time using custom ephemerides that, if very high consistency is required.
Parameters
tdbTime TDB in seconds since J2000.
universalTimeFractionOfDay UT1 in fraction of current day.
stationLongitude Longitude of point on Earth where difference is to be calculated
distanceFromSpinAxis Distance from Earth spin axis where difference is to be calculated
distanceFromEquatorialPlane Distance from Earth equatorial plane where difference is to be calculated
Returns
Difference between TDB and TT at requested position and TDB
Definition at line 89 of file sofaTimeConversions.cpp.
References tudat::physical_constants::JULIAN_DAY, and tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000.
Referenced by getTDBminusTT(), and tudat::earth_orientation::TerrestrialTimeScaleConverter::updateTimes().
getTDBminusTT() [2/4]
double tudat::sofa_interface::getTDBminusTT (const double tdbTime, const double universalTimeFractionOfDay, const Eigen::Vector3d & stationCartesianPosition)
Function to calculate difference between TDB (Dynamical Barycentric Time) and TT (Terrestrial Time), from Sofa function, which is based on decomposition of time ephemeris generated by Fairhead an Bretagnon (1990). Note that the time ephemeris should be generated by the direct solution of differential equations of proper time using custom ephemerides that, if very high consistency is required.
Parameters
tdbTime TDB in seconds since J2000.
universalTimeFractionOfDay UT1 in fraction of current day.
stationCartesianPosition Earth-fixed Cartesian position of evaluation point
Returns
Difference between TDB and TT at requested position and TDB
Definition at line 98 of file sofaTimeConversions.cpp.
References getTDBminusTT().
getTDBminusTT() [3/4]
double tudat::sofa_interface::getTDBminusTT (const double ttOrTdbSinceJ2000, const double stationLongitude, const double distanceFromSpinAxis, const double distanceFromEquatorialPlane)
Function to calculate difference between TDB (Dynamical Barycentric Time) and TT (Terrestrial Time), from Sofa function, which is based on decomposition of time ephemeris generated by Fairhead an Bretagnon (1990). This function uses a simplification for the input to the algorithm: it is assumed that UTC and UT1 coincide for the purposes of the time difference calculation (as needed for the topocentric term of the time conversion). Also, the first input argument may be TDB or TT and the difference between the two is neglected in the internal calculations (TDB is formally required). These simplifications make this function unsuitable for moderately high precision applications.
Parameters
ttOrTdbSinceJ2000 TDB or TT in seconds since J2000.
stationLongitude Longitude of point on Earth where difference is to be calculated
distanceFromSpinAxis Distance from Earth spin axis where difference is to be calculated
distanceFromEquatorialPlane Distance from Earth equatorial plane where difference is to be calculated
Returns
Difference between TDB and TT at requested position and TDB
Definition at line 110 of file sofaTimeConversions.cpp.
References getTDBminusTT(), and tudat::physical_constants::JULIAN_DAY.
getTDBminusTT() [4/4]
double tudat::sofa_interface::getTDBminusTT (const double ttOrTdbSinceJ2000, const Eigen::Vector3d & stationCartesianPosition)
Function to calculate difference between TDB (Dynamical Barycentric Time) and TT (Terrestrial Time), from Sofa function, which is based on decomposition of time ephemeris generated by Fairhead an Bretagnon (1990). This function uses a simplification for the input to the algorithm: it is assumed that UTC and UT1 coincide for the purposes of the time difference calculation (as needed for the topocentric term of the time conversion). Also, the first input argument may be TDB or TT and the difference between the two is neglected in the internal calculations (TDB is formally required). These simplifications make this function unsuitable for moderately high precision applications.
Parameters
ttOrTdbSinceJ2000 TDB or TT in seconds since J2000.
stationCartesianPosition Earth-fixed Cartesian position of evaluation point
Returns
Difference between TDB and TT at requested position and TDB
Definition at line 127 of file sofaTimeConversions.cpp.
References getTDBminusTT().
convertTAItoUTC()
template<typename TimeType > TimeType tudat::sofa_interface::convertTAItoUTC (const TimeType taiSeconds)
Function to convert TAI (International Atomic Time) to UTC (Universal Coordinated Time) by subtracting bias (i.e. number of leap seconds since reference epoch) as determined by Sofa. Note: this function will not work properly near the introduction of a leap second,
See also
getDeltaAtFromTai
Parameters
taiSeconds Time in TAI; in seconds since J2000.
Returns
Time in UTC; in seconds since J2000
Definition at line 63 of file sofaTimeConversions.h.
References getDeltaAtFromUtc(), and tudat::physical_constants::JULIAN_DAY.
Referenced by convertTTtoUTC().
convertUTCtoTAI()
template<typename TimeType > TimeType tudat::sofa_interface::convertUTCtoTAI (const TimeType utcSeconds)
Function to convert UTC (Universal Coordinated Time) to TAI (International Atomic Time) by adding bias (i.e. number of leap seconds since reference epoch) as determined by Sofa.
Parameters
utcSeconds Time in UTC; in seconds since J2000
Returns
Time in TAI; in seconds since J2000
Definition at line 84 of file sofaTimeConversions.h.
References getDeltaAtFromUtc(), and tudat::physical_constants::JULIAN_DAY.
Referenced by convertUTCtoTT().
convertTTtoUTC()
template<typename TimeType > TimeType tudat::sofa_interface::convertTTtoUTC (const TimeType tt)
Function to convert TT (Terrestrial Time) to UTC (Universal Coordinated Time) by determining bias (i.e. number of leap seconds since reference epoch and constant bias of TAI wrt TT) as determined by Sofa. Note: this function will not work properly near the introduction of a leap second,
See also
getDeltaAtFromTai
Parameters
tt Time in TT; in seconds since J2000
Returns
Time in UTC; in seconds since J2000
Definition at line 101 of file sofaTimeConversions.h.
References convertTAItoUTC(), and tudat::basic_astrodynamics::convertTTtoTAI().
Referenced by calculateApproximateDelaunayFundamentalArgumentsWithGmst(), calculateDoodsonFundamentalArguments(), and tudat::earth_orientation::PrecessionNutationCalculator::getPositionOfCipInGcrs().
convertUTCtoTT()
template<typename TimeType > TimeType tudat::sofa_interface::convertUTCtoTT (const TimeType utc)
Function to convert UTC (Universal Coordinated Time) to TT (Terrestrial Time) by determining bias (i.e. number of leap seconds since reference epoch and constant bias of TAI wrt TT) as determined by Sofa.
Parameters
utc Time in UTC in seconds since J2000
Returns
Time in TT; in seconds since J2000
Definition at line 114 of file sofaTimeConversions.h.
References tudat::basic_astrodynamics::convertTAItoTT(), and convertUTCtoTAI().
Variable Documentation
delaunayToDoodsonArguments
const Eigen::Matrix< double, 5, 5 > tudat::sofa_interface::delaunayToDoodsonArguments static
Initial value:
=
        ( Eigen::Matrix< double, 5, 5 >( ) <<
           0.0,  0.0, 1.0,  0.0,  1.0,
           0.0,  0.0, 1.0, -1.0,  1.0,
          -1.0,  0.0, 1.0,  0.0,  1.0,
           0.0,  0.0, 0.0,  0.0, -1.0,
           0.0, -1.0, 1.0, -1.0,  1.0 ).finished( )
Matrix to convert 5 Doodson arguments (without GMST) to Delaunay arguments. For order:
See also
calculateDoodsonFundamentalArguments
calculateDelaunayFundamentalArguments
Definition at line 39 of file fundamentalArguments.h.
doodsonToDelaunayArguments
const Eigen::Matrix< double, 5, 5 > tudat::sofa_interface::doodsonToDelaunayArguments static
Initial value:
=
        ( Eigen::Matrix< double, 5, 5 >( ) <<
          1.0,  0.0, -1.0,  0.0,  0.0,
          0.0,  1.0,  0.0,  0.0, -1.0,
          1.0,  0.0,  0.0,  1.0,  0.0,
          1.0, -1.0,  0.0,  0.0,  0.0,
          0.0,  0.0,  0.0, -1.0,  0.0 ).finished( )
Matrix to convert delaunay arguments to 5 Doodson arguments (without GMST). For order:
See also
calculateDoodsonFundamentalArguments
calculateDelaunayFundamentalArguments
Definition at line 53 of file fundamentalArguments.h.