Tudat: tudat::root_finders::termination_conditions Namespace Reference
tudat::root_finders::termination_conditions Namespace Reference
Classes
class MaximumIterationsTerminationCondition
Maximum iterations termination condition.
class RootAbsoluteOrRelativeToleranceTerminationCondition
Absolute or relative tolerance for root termination condition.
class RootAbsoluteToleranceTerminationCondition
Absolute tolerance for root termination condition.
class RootRelativeToleranceTerminationCondition
Relative tolerance for root termination condition.
class TerminationConditionBase
Termination condition base class.
Typedefs
typedef std::shared_ptr< MaximumIterationsTerminationCondition > MaximumIterationsTerminationConditionPointer
Typedef for shared-pointer to MaximumIterationsTerminationCondition object.
Functions
bool checkMaximumIterationsExceeded (const unsigned int numberOfIterations, const unsigned int maximumNumberOfIterations, const bool throwRunTimeException=true)
Check if maximum number of iterations specified has been exceeded.
template<typename ScalarType >
bool checkRootAbsoluteTolerance (const ScalarType currentRootGuess, const ScalarType previousRootGuess, const ScalarType absoluteTolerance)
Check if absolute tolerance for root value has been achieved.
template<typename ScalarType = double>
bool checkRootFunctionValueCondition (const ScalarType currentRootGuess, const ScalarType previousRootGuess, const ScalarType currentRootFunctionValue, const ScalarType previousRootFunctionValue, const unsigned int numberOfIterations, const ScalarType rootToleranceValue)
Check termination condition (required maximum absolute value of root function)
template<typename ScalarType >
bool checkRootRelativeTolerance (const ScalarType currentRootGuess, const ScalarType previousRootGuess, const ScalarType relativeTolerance)
Check if relative tolerance for root value has been achieved.
Typedef Documentation
MaximumIterationsTerminationConditionPointer
typedef std::shared_ptr< MaximumIterationsTerminationCondition > tudat::root_finders::termination_conditions::MaximumIterationsTerminationConditionPointer
Definition at line 421 of file terminationConditions.h.
Function Documentation
checkMaximumIterationsExceeded()
bool tudat::root_finders::termination_conditions::checkMaximumIterationsExceeded (const unsigned int numberOfIterations, const unsigned int maximumNumberOfIterations, const bool throwRunTimeException = true) inline
Checks if maximum number of iterations specified has been exceeded. If the throwRunTimeException, a run-time exception will be triggered, otherwise, the function will return a false value.
Parameters
numberOfIterations Number of iterations that have been completed.
maximumNumberOfIterations Maximum number of iterations specified.
throwRunTimeException Flag that indicates if run-time error should be triggered if maximum number of iterations is exceeded (default=true).
Returns
Flag indicating if maximum number of iterations have been exceeded.
Definition at line 40 of file terminationConditions.h.
Referenced by tudat::root_finders::termination_conditions::MaximumIterationsTerminationCondition::checkTerminationCondition(), tudat::root_finders::termination_conditions::RootAbsoluteToleranceTerminationCondition< ScalarType >::checkTerminationCondition(), tudat::root_finders::termination_conditions::RootRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition(), and tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition().
checkRootAbsoluteTolerance()
template<typename ScalarType > bool tudat::root_finders::termination_conditions::checkRootAbsoluteTolerance (const ScalarType currentRootGuess, const ScalarType previousRootGuess, const ScalarType absoluteTolerance) inline
Checks if absolute tolerance has been achieved for successive root values, compared against the specified absolute tolerance.
Parameters
currentRootGuess Current value of root.
previousRootGuess Previous value of root.
absoluteTolerance Absolute tolerance.
Returns
Flag indicating if absolute tolerance has been achieved.
Definition at line 70 of file terminationConditions.h.
Referenced by tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition().
checkRootRelativeTolerance()
template<typename ScalarType > bool tudat::root_finders::termination_conditions::checkRootRelativeTolerance (const ScalarType currentRootGuess, const ScalarType previousRootGuess, const ScalarType relativeTolerance) inline
Checks if relative tolerance has been achieved for successive root values, compared against the specified relative tolerance.
Parameters
currentRootGuess Current value of root.
previousRootGuess Previous value of root.
relativeTolerance Relative tolerance.
Returns
Flag indicating if relative tolerance has been achieved.
Definition at line 87 of file terminationConditions.h.
Referenced by tudat::root_finders::termination_conditions::RootRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition(), and tudat::root_finders::termination_conditions::RootAbsoluteOrRelativeToleranceTerminationCondition< ScalarType >::checkTerminationCondition().
checkRootFunctionValueCondition()
template<typename ScalarType = double> bool tudat::root_finders::termination_conditions::checkRootFunctionValueCondition (const ScalarType currentRootGuess, const ScalarType previousRootGuess, const ScalarType currentRootFunctionValue, const ScalarType previousRootFunctionValue, const unsigned int numberOfIterations, const ScalarType rootToleranceValue)
Check termination condition (required maximum absolute value of root function)
Parameters
currentRootGuess Current root value.
previousRootGuess Previous root value.
currentRootFunctionValue Current root function value (not used, included for base class compatibility).
previousRootFunctionValue Previous root function value (not used, included for base class compatibility).
numberOfIterations Number of iterations that have been completed.
rootToleranceValue Maximum allowed value fo root function
Returns
Flag indicating if termination condition has been reached.
Definition at line 409 of file terminationConditions.h.