Tudat: tudat::spice_interface Namespace Reference
tudat::spice_interface Namespace Reference
Functions
bool checkBodyPropertyInKernelPool (const std::string &bodyName, const std::string &bodyProperty)
Check if a certain property of a body is in the kernel pool.
void clearSpiceKernels ()
Clear all Spice kernels.
Eigen::Matrix3d computeRotationMatrixDerivativeBetweenFrames (const std::string &originalFrame, const std::string &newFrame, const double ephemerisTime)
Computes time derivative of rotation matrix between two frames.
std::pair< Eigen::Quaterniond, Eigen::Matrix3d > computeRotationQuaternionAndRotationMatrixDerivativeBetweenFrames (const std::string &originalFrame, const std::string &newFrame, const double ephemerisTime)
Eigen::Quaterniond computeRotationQuaternionBetweenFrames (const std::string &originalFrame, const std::string &newFrame, const double ephemerisTime)
Compute quaternion of rotation between two frames.
int convertBodyNameToNaifId (const std::string &bodyName)
Convert a body name to its NAIF identification number.
double convertDateStringToEphemerisTime (const std::string &dateString)
Converts a date string to ephemeris time.
double convertEphemerisTimeToJulianDate (const double ephemerisTime)
Convert ephemeris time (equivalent to TDB) to a Julian date.
double convertJulianDateToEphemerisTime (const double julianDate)
Convert a Julian date to ephemeris time (equivalent to TDB in Spice).
Eigen::Vector3d getAngularVelocityVectorOfFrameInOriginalFrame (const std::string &originalFrame, const std::string &newFrame, const double ephemerisTime)
Computes the angular velocity of one frame w.r.t. to another frame.
double getAverageRadius (const std::string &body)
Get the (arithmetic) mean of the three principal axes of the tri-axial ellipsoid shape.
Eigen::Vector3d getBodyCartesianPositionAtEpoch (const std::string &targetBodyName, const std::string &observerBodyName, const std::string &referenceFrameName, const std::string &abberationCorrections, const double ephemerisTime)
Get Cartesian position of a body, as observed from another body.
Vector6d getBodyCartesianStateAtEpoch (const std::string &targetBodyName, const std::string &observerBodyName, const std::string &referenceFrameName, const std::string &abberationCorrections, const double ephemerisTime)
Get Cartesian state of a body, as observed from another body.
double getBodyGravitationalParameter (const std::string &body)
Get gravitational parameter of a body.
std::vector< double > getBodyProperties (const std::string &body, const std::string &property, const int maximumNumberOfValues)
Get property of a body from Spice.
int getTotalCountOfKernelsLoaded ()
Get the amount of loaded Spice kernels.
void loadSpiceKernelInTudat (const std::string &fileName)
Load a Spice kernel.
void loadStandardSpiceKernels (const std::vector< std::string > alternativeEphemerisKernels)
Function Documentation
double tudat::spice_interface::convertJulianDateToEphemerisTime (const double julianDate)
Function to convert a Julian date to ephemeris time, which is equivalent to barycentric dynamical time. A leap second kernel must have been loaded to use this function.
Parameters
julianDate Julian date that is to be converted to ephemeris time.
Returns
Ephemeris time calculated from Julian date.
Definition at line 27 of file spiceInterface.cpp.
double tudat::spice_interface::convertEphemerisTimeToJulianDate (const double ephemerisTime)
Function to convert ephemeris time, which is nearly equal to barycentric dynamical time, to the Julian date. A leap second kernel must have been loaded to use this function.
Parameters
ephemerisTime Ephemeris time that is to be converted to Julian date.
Returns
Julian date calculated from ephemeris time.
Definition at line 33 of file spiceInterface.cpp.
double tudat::spice_interface::convertDateStringToEphemerisTime (const std::string & dateString)
Function to convert a date string, for instance 1988 June 13, 3:29:48 to ephemeris time, wrapper for str2et_c spice function.
Parameters
dateString String representing the date. See documentation of spice function str2et_c for details on supported formats.
Returns
Ephemeris time corresponding to given dateString.
Definition at line 39 of file spiceInterface.cpp.
Eigen::Vector6d tudat::spice_interface::getBodyCartesianStateAtEpoch (const std::string & targetBodyName, const std::string & observerBodyName, const std::string & referenceFrameName, const std::string & abberationCorrections, const double ephemerisTime)
This function returns the state of a body, relative to another body, in a frame specified by the user. Corrections for light-time correction and stellar aberration can be applied to obtain the state of one of the bodies, as observed from the other. Wrapper for spkezr_c spice function.
Parameters
targetBodyName Name of the body of which the state is to be obtained. A kernel with the ephemeris of this body must have been loaded. The string must be a spice-recognized name or ID.
observerBodyName Name of the body relative to which the state is to be obtained. A kernel with theephemeris of this body must have been loaded. The string must be a spice-recognized name or ID.
referenceFrameName The spize-revognized name of the reference frame in which the state is to be returned. Spice kernel(s) required to perform the neccesary conversion from the states of the target and observer bodies to this frame need to have been loaded.
abberationCorrections Setting for correction for setting corrections. See Spice documentation for extended discussion. Short summary: NONE: none, LT: light time corrected (one iteration for calculation), CN: light time corrected (multiple iterations, max 3) for calculation, S: Stellar abberation corrected. XLT and XCN can be provided to make the ephemerisTime input argument the transmission time, instead of receptionTime. Arguments can be combined (i.e."LT+S" or "XCN+S").
ephemerisTime Observation time (or transmission time of observed light, see description of abberationCorrections).
Returns
Cartesian state vector (x,y,z, position+velocity).
Definition at line 47 of file spiceInterface.cpp.
Referenced by tudat::ephemerides::SpiceEphemeris::getCartesianState().
Eigen::Vector3d tudat::spice_interface::getBodyCartesianPositionAtEpoch (const std::string & targetBodyName, const std::string & observerBodyName, const std::string & referenceFrameName, const std::string & abberationCorrections, const double ephemerisTime)
This function returns the position of a body, relative to another body, in a frame specified by the user. Corrections for light-time correction and stellar aberration can be applied to obtain the state of one of the bodies, as observed from the other. Wrapper for spkpos_c spice function.
Parameters
targetBodyName Name of the body of which the position is to be obtained. A kernel with the ephemeris of this body must have been loaded. The string must be a spice-recognized name or ID.
observerBodyName Name of the body relative to which the position is to be obtained. A kernel with theephemeris of this body must have been loaded. The string must be a spice-recognized name or ID.
referenceFrameName The spice-revognized name of the reference frame in which the state is to be returned. Spice kernel(s) required to perform the neccesary conversion from the states of the target and observer bodies to this frame need to have been loaded.
abberationCorrections Setting for correction for setting corrections. See Spice documentation for extended discussion. Short summary: NONE: none, LT: light time corrected (one iteration for calculation), CN: light time corrected (multiple iterations, max 3) for calculation, S: Stellar abberation corrected. XLT and XCN can be provided to make the ephemerisTime input argument the transmission time, instead of receptionTime. Arguments can be combined (i.e."LT+S" or "XCN+S").
ephemerisTime Observation time (or transmission time of observed light, see description of abberationCorrections).
Returns
Cartesian position vector (x,y,z, position).
Definition at line 75 of file spiceInterface.cpp.
Eigen::Quaterniond tudat::spice_interface::computeRotationQuaternionBetweenFrames (const std::string & originalFrame, const std::string & newFrame, const double ephemerisTime)
This function computes the quaternion of rotation between two frames at a given time instant. Kernels defining the two frames, as well as any required intermediate frames, at the requested time must have been loaded. Wrapper for pxform_c spice function.
Parameters
originalFrame Reference frame from which the rotation is made.
newFrame Reference frame to which the rotation is made.
ephemerisTime Value of ephemeris time at which rotation is to be determined.
Returns
Rotation quaternion from original to new frame at given time.
Definition at line 103 of file spiceInterface.cpp.
Referenced by tudat::ephemerides::SpiceRotationalEphemeris::getRotationToBaseFrame().
Eigen::Matrix3d tudat::spice_interface::computeRotationMatrixDerivativeBetweenFrames (const std::string & originalFrame, const std::string & newFrame, const double ephemerisTime)
This function computes the derivative of the rotation matrix between two frames at a given time instant. Kernels defining the two frames, as well as any required intermediate frames, at the requested time must have been loaded. Wrapper for (part of) sxform_c spice function.
Parameters
originalFrame Reference frame from which the rotation is made.
newFrame Reference frame to which the rotation is made.
ephemerisTime Value of ephemeris time at which rotation is to be determined.
Returns
Time derivative of rotation matrix from original to new frame at given time.
Definition at line 128 of file spiceInterface.cpp.
Referenced by tudat::ephemerides::SpiceRotationalEphemeris::getDerivativeOfRotationToBaseFrame().
Eigen::Vector3d tudat::spice_interface::getAngularVelocityVectorOfFrameInOriginalFrame (const std::string & originalFrame, const std::string & newFrame, const double ephemerisTime)
Computes the angular velocity of one frame w.r.t. to another frame. at a given time instant. Kernels defining the two frames, as well as any required intermediate frames, at the requested time must have been loaded. Wrapper for xf2rav_c spice function (utilizing sxform_c).
Parameters
originalFrame Reference frame from which the rotation is made.
newFrame Reference frame to which the rotation is made.
ephemerisTime Value of ephemeris time at which rotation is to be determined.
Returns
Angular velocity of newFrame w.r.t. originalFrame, expressed in originalFrame.
Definition at line 151 of file spiceInterface.cpp.
std::pair< Eigen::Quaterniond, Eigen::Matrix3d > tudat::spice_interface::computeRotationQuaternionAndRotationMatrixDerivativeBetweenFrames (const std::string & originalFrame, const std::string & newFrame, const double ephemerisTime)
Definition at line 170 of file spiceInterface.cpp.
Referenced by tudat::ephemerides::SpiceRotationalEphemeris::getFullRotationalQuantitiesToTargetFrame().
std::vector< double > tudat::spice_interface::getBodyProperties (const std::string & body, const std::string & property, const int maximumNumberOfValues = 1)
Function to retrieve a property of a body from Spice, wraps the bodvrd_c Spice function. NOTE: Function returns values with distance unit km, not m!
Parameters
body Name of the body of which the property is to be retrieved.
property Name of the property that is to be retrieved. Naming conventions can be found in the bodvrd_c function documentation.
maximumNumberOfValues Number of values by which the property is expressed (i.e. 1 for gravitational parameter, 3 for tri-axial ellipsoid principal axes).
Returns
Property value(s) expressed in an STL vector of doubles.
Definition at line 192 of file spiceInterface.cpp.
double tudat::spice_interface::getBodyGravitationalParameter (const std::string & body)
This function retrieves the gravitational parameter of a body. Wraps the bodvrd_c spice function with "GM" as property type.
Parameters
body Name of the body of which the parameter is to be retrieved.
Returns
Gravitational parameter of requested body.
Definition at line 214 of file spiceInterface.cpp.
Referenced by tudat::simulation_setup::createGravityFieldModel().
double tudat::spice_interface::getAverageRadius (const std::string & body)
Returns the (arithmetic) mean of the three principal axes of the tri-axial ellipsoid shapen of the requested body. Uses the bodvrd_c spice function with "RADII" as property type.
Parameters
body Name of the body of which the average radius is to be retrieved.
Returns
Arithmetic mean of principal axes of tri-axial ellipsoid shape model of body.
Definition at line 231 of file spiceInterface.cpp.
Referenced by tudat::coordinate_conversions::convertPositionElements(), tudat::simulation_setup::createBodyShapeModel(), and tudat::simulation_setup::getDefaultBodyShapeSettings().
int tudat::spice_interface::convertBodyNameToNaifId (const std::string & bodyName)
This function converts a body name to its NAIF identification number.The NAIF id number is required for a number of spice functions, whereas the name is easily interpretable by the user. Wrapper for the bods2c_c function.
Parameters
bodyName Name of the body for which NAIF id is to be retrieved.
Returns
NAIF id number for the body with bodyName.
Definition at line 246 of file spiceInterface.cpp.
Referenced by checkBodyPropertyInKernelPool().
bool tudat::spice_interface::checkBodyPropertyInKernelPool (const std::string & bodyName, const std::string & bodyProperty)
This function checks if a certain property of a body is in the kernel pool. These properties are defined in PCK kernels. Their names are given in the kernel file, typical names can be found in the Spice documentation. Wrapper for the bodfnd_c function.
Parameters
bodyName Name of the body of which the property is to be checked.
bodyProperty Name of the property of which the presence is to be checked, not case- sensitive.
Returns
True if property is in pool, false if not.
Definition at line 258 of file spiceInterface.cpp.
References convertBodyNameToNaifId().
void tudat::spice_interface::loadSpiceKernelInTudat (const std::string & fileName)
This function loads a Spice kernel into the kernel pool, from which it can be used by the various internal spice routines. Matters regarding the manner in which Spice handles different kernels containing the same information can be found in the spice required reading documentation, kernel section. Wrapper for the furnsh_c function.
Parameters
fileName The file name of the Kernel to be loaded.
Definition at line 269 of file spiceInterface.cpp.
Referenced by loadStandardSpiceKernels().
int tudat::spice_interface::getTotalCountOfKernelsLoaded ()
This function returns the amount of Spice kernels that are loaded into the kernel pool. The same kernel can be loaded multple times. Wrapper for the ktotal_c function.
Returns
Total amount of loaded Spice kernels.
Definition at line 275 of file spiceInterface.cpp.
void tudat::spice_interface::clearSpiceKernels ()
This function removes all Spice kernels from the kernel pool. Wrapper for the kclear_c function.
Definition at line 283 of file spiceInterface.cpp.
void tudat::spice_interface::loadStandardSpiceKernels (const std::vector< std::string > alternativeEphemerisKernels)
Definition at line 285 of file spiceInterface.cpp.
References tudat::input_output::getSpiceKernelPath(), and loadSpiceKernelInTudat().