Tudat: tudat::linear_algebra Namespace Reference
tudat::linear_algebra Namespace Reference
Functions
Eigen::MatrixXd calculateInverseOfUpdatedCovarianceMatrix (const Eigen::MatrixXd &informationMatrix, const Eigen::VectorXd &diagonalOfWeightMatrix, const Eigen::MatrixXd &inverseOfAPrioriCovarianceMatrix)
Function to compute inverse of covariance matrix at current iteration, including influence of a priori information.
Eigen::MatrixXd calculateInverseOfUpdatedCovarianceMatrix (const Eigen::MatrixXd &informationMatrix, const Eigen::VectorXd &diagonalOfWeightMatrix)
Function to compute inverse of covariance matrix at current iteration.
Eigen::Matrix3d calculatePartialOfNormalizedVector (const Eigen::Matrix3d &partialOfUnnormalizedVector, const Eigen::Vector3d &unnormalizedVector)
Function to calculate the jacobian of a normalized vector, from the partial of the unnormalized vector.
double computeAngleBetweenVectors (const Eigen::VectorXd &vector0, const Eigen::VectorXd &vector1)
Compute angle between two vectors.
double computeCosineOfAngleBetweenVectors (const Eigen::VectorXd &vector0, const Eigen::VectorXd &vector1)
Compute cosine of the angle between two vectors.
double computeNormOfVectorDifference (const Eigen::Vector3d &vector0, const Eigen::Vector3d &vector1)
Computes norm of the the difference between two 3d vectors.
template<int VectorSize>
Eigen::Matrix< double, VectorSize, 1 > computeVectorDifference (const Eigen::Matrix< double, VectorSize, 1 > &vector0, const Eigen::Matrix< double, VectorSize, 1 > &vector1)
Computes the difference between two 3d vectors.
Eigen::Vector4d convertQuaternionToVectorFormat (const Eigen::Quaterniond &quaternion)
Function to put a quaternion in 'vector format', e.g. a Vector4d with entries (w,x,y,z) of the quaternion.
Eigen::Quaterniond convertVectorToQuaternionFormat (const Eigen::Vector4d &vector)
Function to put a vector in 'quaternion format', i.e. a Quaterniond.
template<typename StateScalarType , int NumberOfRows, int NumberOfColumns>
bool doesMatrixHaveNanEntries (const Eigen::Matrix< StateScalarType, NumberOfRows, NumberOfColumns > matrixToCheck)
Function to check whether an Eigen Matrix has any NaN entries.
Eigen::Vector3d evaluateSecondBlockInStateVector (const std::function< Eigen::Vector6d(const double) > stateFunction, const double time)
static void flipMatrixRows (Eigen::MatrixXd &matrixToFlip)
Flip matrix rows.
double getConditionNumberOfDecomposedMatrix (const Eigen::JacobiSVD< Eigen::MatrixXd > &singularValueDecomposition)
Function to get condition number of matrix from SVD decomposition.
double getConditionNumberOfInformationMatrix (const Eigen::MatrixXd informationMatrix)
Function to get condition number of matrix (using SVD decomposition)
Eigen::Matrix3d getCrossProductMatrix (const Eigen::Vector3d &vector)
Function that returns that 'cross-product matrix'.
Eigen::VectorXd getLeastSquaresPolynomialFit (const Eigen::VectorXd &independentValues, const Eigen::VectorXd &dependentValues, const std::vector< double > &polynomialPowers)
Function to fit a univariate polynomial through a set of data.
std::vector< double > getLeastSquaresPolynomialFit (const std::map< double, double > &independentDependentValueMap, const std::vector< double > &polynomialPowers)
Function to fit a univariate polynomial through a set of data.
double getVectorEntryRootMeanSquare (const Eigen::VectorXd &inputVector)
Function to compute the root mean square value of the entries in an Eigen vector.
double getVectorNorm (const Eigen::Vector3d &vector)
Computes the norm of a 3d vector.
double getVectorNormFromFunction (const std::function< Eigen::Vector3d() > vectorFunction)
Computes the norm of a 3d vector from a vector-returning function.
void invertQuaternion (Eigen::Vector4d &quaternionVector)
Function to invert a quaternion.
Eigen::MatrixXd multiplyInformationMatrixByDiagonalWeightMatrix (const Eigen::MatrixXd &informationMatrix, const Eigen::VectorXd &diagonalOfWeightMatrix)
Function to multiply information matrix by diagonal weights matrix.
Eigen::VectorXd nonLinearLeastSquaresFit (const std::function< std::pair< Eigen::VectorXd, Eigen::MatrixXd >(const Eigen::VectorXd &) > &observationAndJacobianFunctions, const Eigen::VectorXd &initialEstimate, const Eigen::VectorXd &actualObservations, const double initialScaling, const double convergenceTolerance, const unsigned int maximumNumberOfIterations)
Function to perform a non-linear least squares estimation with the Levenberg-Marquardt method.
std::pair< Eigen::VectorXd, Eigen::MatrixXd > performLeastSquaresAdjustmentFromInformationMatrix (const Eigen::MatrixXd &informationMatrix, const Eigen::VectorXd &observationResiduals, const Eigen::VectorXd &diagonalOfWeightMatrix, const Eigen::MatrixXd &inverseOfAPrioriCovarianceMatrix, const bool checkConditionNumber=1, const double maximumAllowedConditionNumber=1.0E8)
Function to perform an iteration least squares estimation from information matrix, weights and residuals and a priori information, as is typically done in orbit determination.
std::pair< Eigen::VectorXd, Eigen::MatrixXd > performLeastSquaresAdjustmentFromInformationMatrix (const Eigen::MatrixXd &informationMatrix, const Eigen::VectorXd &observationResiduals, const Eigen::VectorXd &diagonalOfWeightMatrix, const bool checkConditionNumber, const double maximumAllowedConditionNumber)
Function to perform an iteration least squares estimation from information matrix, weights and residuals.
std::pair< Eigen::VectorXd, Eigen::MatrixXd > performLeastSquaresAdjustmentFromInformationMatrix (const Eigen::MatrixXd &informationMatrix, const Eigen::VectorXd &observationResiduals, const bool checkConditionNumber, const double maximumAllowedConditionNumber)
Function to perform an iteration of least squares estimation from information matrix and residuals.
Eigen::Vector4d quaternionProduct (const Eigen::Vector4d &firstQuaternion, const Eigen::Vector4d &secondQuaternion)
Function to take the product of two quaternions.
Eigen::VectorXd solveSystemOfEquationsWithSvd (const Eigen::MatrixXd matrixToInvert, const Eigen::VectorXd rightHandSideVector, const bool checkConditionNumber, const double maximumAllowedConditionNumber)
Solve system of equations with SVD decomposition, checking condition number in the process.
Function Documentation
getConditionNumberOfInformationMatrix()
double tudat::linear_algebra::getConditionNumberOfInformationMatrix (const Eigen::MatrixXd informationMatrix)
Function to get condition number of matrix (using SVD decomposition)
Parameters
informationMatrix Matrix for which condition number is to be computed
Returns
Condition number of matrix
Definition at line 27 of file leastSquaresEstimation.cpp.
References getConditionNumberOfDecomposedMatrix().
getConditionNumberOfDecomposedMatrix()
double tudat::linear_algebra::getConditionNumberOfDecomposedMatrix (const Eigen::JacobiSVD< Eigen::MatrixXd > & singularValueDecomposition)
Function to get condition number of matrix from SVD decomposition
Parameters
singularValueDecomposition SVD decomposition of matrix
Returns
Condition number of matrix
Definition at line 34 of file leastSquaresEstimation.cpp.
Referenced by getConditionNumberOfInformationMatrix(), and solveSystemOfEquationsWithSvd().
solveSystemOfEquationsWithSvd()
Eigen::VectorXd tudat::linear_algebra::solveSystemOfEquationsWithSvd (const Eigen::MatrixXd matrixToInvert, const Eigen::VectorXd rightHandSideVector, const bool checkConditionNumber = 1, const double maximumAllowedConditionNumber = 1.0E-8)
Solve system of equations with SVD decomposition, checking condition number in the process. This function solves A*x = b for the vector x.
Parameters
matrixToInvert Matrix A that is to be inverted to solve the equation
rightHandSideVector Vector on the righthandside of the matrix equation that is to be solved
checkConditionNumber Boolean to denote whether the condition number is checked when estimating (warning is printed when value exceeds maximumAllowedConditionNumber)
maximumAllowedConditionNumber Maximum value of the condition number of the covariance matrix that is allowed (warning printed when exceeded)
Returns
Solution x of matrix equation A*x=b
Definition at line 41 of file leastSquaresEstimation.cpp.
References getConditionNumberOfDecomposedMatrix().
Referenced by performLeastSquaresAdjustmentFromInformationMatrix().
multiplyInformationMatrixByDiagonalWeightMatrix()
Eigen::MatrixXd tudat::linear_algebra::multiplyInformationMatrixByDiagonalWeightMatrix (const Eigen::MatrixXd & informationMatrix, const Eigen::VectorXd & diagonalOfWeightMatrix)
Function to multiply information matrix by diagonal weights matrix
Parameters
informationMatrix Matrix containing partial derivatives of observations (rows) w.r.t. estimated parameters (columns)
diagonalOfWeightMatrix Diagonal of observation weights matrix (assumes all weights to be uncorrelated)
Returns
informationMatrix, premultiplied by square matrix with diagonalOfWeightMatrix as diagonal elements
Definition at line 61 of file leastSquaresEstimation.cpp.
Referenced by calculateInverseOfUpdatedCovarianceMatrix().
calculateInverseOfUpdatedCovarianceMatrix() [1/2]
Eigen::MatrixXd tudat::linear_algebra::calculateInverseOfUpdatedCovarianceMatrix (const Eigen::MatrixXd & informationMatrix, const Eigen::VectorXd & diagonalOfWeightMatrix, const Eigen::MatrixXd & inverseOfAPrioriCovarianceMatrix)
Function to compute inverse of covariance matrix at current iteration, including influence of a priori information
Parameters
informationMatrix Matrix containing partial derivatives of observations (rows) w.r.t. estimated parameters (columns)
diagonalOfWeightMatrix Diagonal of observation weights matrix (assumes all weights to be uncorrelated)
inverseOfAPrioriCovarianceMatrix Inverse of a priori covariance matrix (warning printed when exceeded)
Returns
Inverse of covariance matrix at current iteration
Definition at line 77 of file leastSquaresEstimation.cpp.
References multiplyInformationMatrixByDiagonalWeightMatrix().
Referenced by tudat::simulation_setup::calculateCovarianceMatrixAsFunctionOfTime(), calculateInverseOfUpdatedCovarianceMatrix(), and performLeastSquaresAdjustmentFromInformationMatrix().
calculateInverseOfUpdatedCovarianceMatrix() [2/2]
Eigen::MatrixXd tudat::linear_algebra::calculateInverseOfUpdatedCovarianceMatrix (const Eigen::MatrixXd & informationMatrix, const Eigen::VectorXd & diagonalOfWeightMatrix)
Function to compute inverse of covariance matrix at current iteration
Parameters
informationMatrix Matrix containing partial derivatives of observations (rows) w.r.t. estimated parameters (columns)
diagonalOfWeightMatrix Diagonal of observation weights matrix (assumes all weights to be uncorrelated)
Returns
Inverse of covariance matrix at current iteration
Definition at line 87 of file leastSquaresEstimation.cpp.
References calculateInverseOfUpdatedCovarianceMatrix().
performLeastSquaresAdjustmentFromInformationMatrix() [1/3]
std::pair< Eigen::VectorXd, Eigen::MatrixXd > tudat::linear_algebra::performLeastSquaresAdjustmentFromInformationMatrix (const Eigen::MatrixXd & informationMatrix, const Eigen::VectorXd & observationResiduals, const Eigen::VectorXd & diagonalOfWeightMatrix, const Eigen::MatrixXd & inverseOfAPrioriCovarianceMatrix, const bool checkConditionNumber, const double maximumAllowedConditionNumber)
Function to perform an iteration least squares estimation from information matrix, weights and residuals and a priori information
Function to perform an iteration least squares estimation from information matrix, weights and residuals and a priori information
This function also takes an inverse if the a priori covariance matrix to constrain/stabilize the inversion.
Parameters
informationMatrix Matrix containing partial derivatives of observations (rows) w.r.t. estimated parameters (columns)
observationResiduals Difference between measured and simulated observations
diagonalOfWeightMatrix Diagonal of observation weights matrix (assumes all weights to be uncorrelated)
inverseOfAPrioriCovarianceMatrix Inverse of a priori covariance matrix (warning printed when exceeded)
checkConditionNumber Boolean to denote whether the condition number is checked when estimating (warning is printed when value exceeds maximumAllowedConditionNumber)
maximumAllowedConditionNumber Maximum value of the condition number of the covariance matrix that is allowed
Returns
Pair containing: (first: parameter adjustment, second: inverse covariance)
Definition at line 98 of file leastSquaresEstimation.cpp.
References calculateInverseOfUpdatedCovarianceMatrix(), and solveSystemOfEquationsWithSvd().
Referenced by tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::estimateParameters(), getLeastSquaresPolynomialFit(), nonLinearLeastSquaresFit(), and performLeastSquaresAdjustmentFromInformationMatrix().
performLeastSquaresAdjustmentFromInformationMatrix() [2/3]
std::pair< Eigen::VectorXd, Eigen::MatrixXd > tudat::linear_algebra::performLeastSquaresAdjustmentFromInformationMatrix (const Eigen::MatrixXd & informationMatrix, const Eigen::VectorXd & observationResiduals, const Eigen::VectorXd & diagonalOfWeightMatrix, const bool checkConditionNumber = 1, const double maximumAllowedConditionNumber = 1.0E8)
Function to perform an iteration of least squares estimation from information matrix, weights and residuals.
Function to perform an iteration of least squares estimation from information matrix, weights and residuals, as is typically done in orbit determination
Parameters
informationMatrix Matrix containing partial derivatives of observations (rows) w.r.t. estimated parameters (columns)
observationResiduals Difference between measured and simulated observations
diagonalOfWeightMatrix Diagonal of observation weights matrix (assumes all weights to be uncorrelated)
checkConditionNumber Boolean to denote whether the condition number is checked when estimating (warning is printed when value exceeds maximumAllowedConditionNumber)
maximumAllowedConditionNumber Maximum value of the condition number of the covariance matrix that is allowed (warning printed when exceeded)
Returns
Pair containing: (first: parameter adjustment, second: inverse covariance)
Definition at line 116 of file leastSquaresEstimation.cpp.
References performLeastSquaresAdjustmentFromInformationMatrix().
performLeastSquaresAdjustmentFromInformationMatrix() [3/3]
std::pair< Eigen::VectorXd, Eigen::MatrixXd > tudat::linear_algebra::performLeastSquaresAdjustmentFromInformationMatrix (const Eigen::MatrixXd & informationMatrix, const Eigen::VectorXd & observationResiduals, const bool checkConditionNumber = 1, const double maximumAllowedConditionNumber = 1.0E8)
Function to perform an iteration of least squares estimation from information matrix and residuals, with all weights fixed to 1.0.
Parameters
informationMatrix Matrix containing partial derivatives of observations (rows) w.r.t. estimated parameters (columns)
observationResiduals Difference between measured and simulated observations
checkConditionNumber Boolean to denote whether the condition number is checked when estimating (warning is printed when value exceeds maximumAllowedConditionNumber)
maximumAllowedConditionNumber Maximum value of the condition number of the covariance matrix that is allowed (warning printed when exceeded)
Returns
Pair containing: (first: parameter adjustment, second: inverse covariance)
Definition at line 130 of file leastSquaresEstimation.cpp.
References performLeastSquaresAdjustmentFromInformationMatrix().
getLeastSquaresPolynomialFit() [1/2]
Eigen::VectorXd tudat::linear_algebra::getLeastSquaresPolynomialFit (const Eigen::VectorXd & independentValues, const Eigen::VectorXd & dependentValues, const std::vector< double > & polynomialPowers)
Function to fit a univariate polynomial through a set of data. User must provide independent variables and observations (dependent variables), as well as a list of polynomial powers for which the coefficients are to be estimated.
Parameters
independentValues Independent variables of input data (e.g. time for observations as a function fo time). This variable becomes the polynomial argument.
dependentValues Observations through which the polynomial is to be fitted, with entries defined at the corresponding entries of independentValues
polynomialPowers List of powers of indepent variables for which coefficients are to be estimated.
Returns
Coefficients of the polynomial powers, as estimated from the input data (in same order as polynomialPowers).
Definition at line 142 of file leastSquaresEstimation.cpp.
References performLeastSquaresAdjustmentFromInformationMatrix().
Referenced by getLeastSquaresPolynomialFit().
getLeastSquaresPolynomialFit() [2/2]
std::vector< double > tudat::linear_algebra::getLeastSquaresPolynomialFit (const std::map< double, double > & independentDependentValueMap, const std::vector< double > & polynomialPowers)
Function to fit a univariate polynomial through a set of data. User must provide independent variables and observations (dependent variables), as well as a list of polynomial powers for which the coefficients are to be estimated.
Parameters
independentDependentValueMap Map with key: independent variables of input data (e.g. time for observations as a function fo time), this variable becomes the polynomial argument. Map value: Observations through which the polynomial is to be fitted.
polynomialPowers List of powers of indepent variables for which coefficients are to be estimated.
Returns
Coefficients of the polynomial powers, as estimated from the input data (in same order as polynomialPowers).
Definition at line 168 of file leastSquaresEstimation.cpp.
References tudat::utilities::convertEigenVectorToStlVector(), tudat::utilities::convertStlVectorToEigenVector(), tudat::utilities::createVectorFromMapKeys(), tudat::utilities::createVectorFromMapValues(), and getLeastSquaresPolynomialFit().
nonLinearLeastSquaresFit()
Eigen::VectorXd tudat::linear_algebra::nonLinearLeastSquaresFit (const std::function< std::pair< Eigen::VectorXd, Eigen::MatrixXd >(const Eigen::VectorXd &) > & observationAndJacobianFunctions, const Eigen::VectorXd & initialEstimate, const Eigen::VectorXd & actualObservations, const double initialScaling = 1.0e-6, const double convergenceTolerance = 1.0e-8, const unsigned int maximumNumberOfIterations = 25)
Function to perform a non-linear least squares estimation. The non-linear least squares method is an iterative process, which uses the information from the actual and estimated observations, to estimate the model parameters, with the aid of a design matrix. The initial estimate of the model parameters is updated every iteration with the result of the least squares equation. The iterative process is halted whenever the norm of the update is below the user-provided threshold or when the maximum number of iterations is reached. The method used in this application is the Levenberg-Marquardt method, which uses a damping parameter to make the iterative process more stable and accurate. The reference for this implementation is (Madsen, K., et al.).
Parameters
observationAndJacobianFunctions Function returning a pair of expected observations and Jacobian of the observation function w.r.t. the model parameters (i.e., the design matrix), where the input is the current estimate of the model parameters.
initialEstimate Initial estimate of the model parameters.
actualObservations Vector containing the actual observations that need to be fitted by the model.
initialScaling Double denoting the multiplicative factor to determine the damping parameter during the first iteration.
convergenceTolerance Double denoting the convergence criterion for the norm of the update vector.
maximumNumberOfIterations Integer denoting the maximum number of iterations.
Returns
Optimal value of the model parameters that minimize the least squares error between expected and actual observations.
Definition at line 182 of file leastSquaresEstimation.cpp.
References performLeastSquaresAdjustmentFromInformationMatrix().
convertQuaternionToVectorFormat()
Eigen::Vector4d tudat::linear_algebra::convertQuaternionToVectorFormat (const Eigen::Quaterniond & quaternion)
Function to put a quaternion in 'vector format', e.g. a Vector4d with entries (w,x,y,z) of the quaternion.
Parameters
quaternion Quaternion that is to be put into vector format.
Returns
Vector format of input quaternion.
Definition at line 26 of file linearAlgebra.cpp.
Referenced by tudat::simulation_setup::Body::getCurrentRotationalState().
convertVectorToQuaternionFormat()
Eigen::Quaterniond tudat::linear_algebra::convertVectorToQuaternionFormat (const Eigen::Vector4d & vector)
Function to put a vector in 'quaternion format', i.e. a Quaterniond.
Parameters
vector Vector format of input quaternion.
Returns
Quaternion that is to be put into vector format.
Definition at line 37 of file linearAlgebra.cpp.
Referenced by tudat::orbital_element_conversions::convertUnifiedStateModelQuaternionsToCartesianElements().
quaternionProduct()
Eigen::Vector4d tudat::linear_algebra::quaternionProduct (const Eigen::Vector4d & firstQuaternion, const Eigen::Vector4d & secondQuaternion)
Function to take the product of two quaternions, both expressed as vectors.
Parameters
firstQuaternion First quaternion expressed as vector.
secondQuaternion Second quaternion expressed as vector.
Returns
Product of the two quaternions.
Definition at line 48 of file linearAlgebra.cpp.
References getCrossProductMatrix().
invertQuaternion()
void tudat::linear_algebra::invertQuaternion (Eigen::Vector4d & quaternionVector)
Function to invert a quaternion.
Parameters
quaternionVector Quaternion expressed as vector.
Definition at line 60 of file linearAlgebra.cpp.
getCrossProductMatrix()
Eigen::Matrix3d tudat::linear_algebra::getCrossProductMatrix (const Eigen::Vector3d & leftHandVector)
Function that returns that 'cross-product matrix', i.e. for vectors a,b and c, with c = a x b, the matrix A such that c = Ab.
Parameters
leftHandVector The left-multiplying vector (a in above example)
Returns
The matrix by which to premultiply the right-multiplying vector to obtain the cross product of the two matrices.
Definition at line 66 of file linearAlgebra.cpp.
Referenced by tudat::propagators::calculateModifiedRodriguesParametersDerivative(), tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnPlanetWrtPosition(), tudat::ephemerides::getDerivativeOfRotationMatrixToFrame(), quaternionProduct(), tudat::simulation_setup::Body::setCurrentRotationalStateToLocalFrame(), and tudat::acceleration_partials::EmpiricalAccelerationPartial::update().
computeCosineOfAngleBetweenVectors()
double tudat::linear_algebra::computeCosineOfAngleBetweenVectors (const Eigen::VectorXd & vector0, const Eigen::VectorXd & vector1)
Computes the cosine of the angle between two vectors; both vectors must have non-zero norm.
Parameters
vector0 First vector.
vector1 Second vector.
Returns
Cosine of angle between vectors.
Definition at line 79 of file linearAlgebra.cpp.
Referenced by computeAngleBetweenVectors(), and tudat::observation_models::BodyAvoidanceAngleCalculator::isObservationViable().
computeAngleBetweenVectors()
double tudat::linear_algebra::computeAngleBetweenVectors (const Eigen::VectorXd & vector0, const Eigen::VectorXd & vector1)
Computes the angle between two vectors; both vectors must have non-zero norm.
Parameters
vector0 First vector.
vector1 Second vector.
Returns
Angle between vectors.
Definition at line 108 of file linearAlgebra.cpp.
References computeCosineOfAngleBetweenVectors().
Referenced by tudat::ground_stations::PointingAnglesCalculator::calculateElevationAngle(), tudat::ground_stations::PointingAnglesCalculator::calculatePointingAngles(), tudat::mission_segments::gravityAssist(), and tudat::mission_segments::solveLambertProblemGooding().
computeNormOfVectorDifference()
double tudat::linear_algebra::computeNormOfVectorDifference (const Eigen::Vector3d & vector0, const Eigen::Vector3d & vector1)
Computes the norm of the difference between two 3d vectors (i.e. distance between vectors)
Parameters
vector0 First vector.
vector1 Second vector.
Returns
Norm of difference between vectors
Definition at line 118 of file linearAlgebra.cpp.
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
getVectorNorm()
double tudat::linear_algebra::getVectorNorm (const Eigen::Vector3d & vector)
Computes the norm of a 3d vector
Parameters
vector Vector for which the norm is to be computed
Returns
Vector norm
Definition at line 125 of file linearAlgebra.cpp.
Referenced by getVectorNormFromFunction().
evaluateSecondBlockInStateVector()
Eigen::Vector3d tudat::linear_algebra::evaluateSecondBlockInStateVector (const std::function< Eigen::Vector6d(const double) > stateFunction, const double time)
Definition at line 130 of file linearAlgebra.cpp.
Referenced by tudat::observation_partials::createOneWayDopplerPartials().
getVectorNormFromFunction()
double tudat::linear_algebra::getVectorNormFromFunction (const std::function< Eigen::Vector3d() > vectorFunction)
Computes the norm of a 3d vector from a vector-returning function.
Parameters
vectorFunction Function returning the vector for which the norm is to be computed
Returns
Vector norm
Definition at line 138 of file linearAlgebra.cpp.
References getVectorNorm().
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
calculatePartialOfNormalizedVector()
Eigen::Matrix3d tudat::linear_algebra::calculatePartialOfNormalizedVector (const Eigen::Matrix3d & partialOfUnnormalizedVector, const Eigen::Vector3d & unnormalizedVector)
Function to calculate the jacobian of a normalized vector, from the jacobian of the unnormalized vector.
Function to calculate the jacobian (partial matrix) of a normalized vector, from the jacobian (partial matrix) of the unnormalized vector and the unnormalized vector itself, i.e. d/dp(x/|x|) from d/dp(x) and x, with p and x 3d vectors.
Parameters
partialOfUnnormalizedVector The jacobian of the unnormalized vector
unnormalizedVector Unnormalized vector wrt which partialOfUnnormalizedVector is taken
Returns
The jacobian of the normalized vector.
Definition at line 144 of file linearAlgebra.cpp.
Referenced by tudat::acceleration_partials::EmpiricalAccelerationPartial::update().
getVectorEntryRootMeanSquare()
double tudat::linear_algebra::getVectorEntryRootMeanSquare (const Eigen::VectorXd & inputVector)
Function to compute the root mean square (RMS) value of the entries in an Eigen vector
Parameters
inputVector Vector for which the RMS is to be computed
Returns
RMS of input vector
Definition at line 154 of file linearAlgebra.cpp.
Referenced by tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::estimateParameters().
computeVectorDifference()
template<int VectorSize> Eigen::Matrix< double, VectorSize, 1 > tudat::linear_algebra::computeVectorDifference (const Eigen::Matrix< double, VectorSize, 1 > & vector0, const Eigen::Matrix< double, VectorSize, 1 > & vector1)
Computes the difference between two 3d vectors (first input minus second input, i.e vector from second input to first input).
Parameters
vector0 First vector.
vector1 Second vector.
Returns
Difference between vectors
Definition at line 103 of file linearAlgebra.h.
flipMatrixRows()
static void tudat::linear_algebra::flipMatrixRows (Eigen::MatrixXd & matrixToFlip) inline static
Flips all rows of an Eigen-matrix, i.e., order of rows is reversed.
Parameters
matrixToFlip Matrix that should be flipped. The flipping is done in place, i.e. the input matrix is modified directly (no copies are made).
Definition at line 142 of file linearAlgebra.h.
doesMatrixHaveNanEntries()
template<typename StateScalarType , int NumberOfRows, int NumberOfColumns> bool tudat::linear_algebra::doesMatrixHaveNanEntries (const Eigen::Matrix< StateScalarType, NumberOfRows, NumberOfColumns > matrixToCheck)
Function to check whether an Eigen Matrix has any NaN entries
Parameters
matrixToCheck Eigen Matrix to check for any NaN entries
Returns
True if matrix has NaN entries, false otherwise
Definition at line 185 of file linearAlgebra.h.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), and tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations().