Tudat: tudat::mission_segments::MultiRevolutionLambertTargeterIzzo Class Reference
tudat::mission_segments::MultiRevolutionLambertTargeterIzzo Class Reference
Izzo Lambert targeting algorithm class (multiple revolution).
#include <multiRevolutionLambertTargeterIzzo.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW MultiRevolutionLambertTargeterIzzo (const Eigen::Vector3d &aCartesianPositionAtDeparture, const Eigen::Vector3d &aCartesianPositionAtArrival, const double aTimeOfFlight, const double aGravitationalParameter, const int aNumberOfRevolutions=0, const bool aIsRightBranch=false, const bool aIsRetrograde=false, const double aConvergenceTolerance=1e-9, const int aMaximumNumberOfIterations=50)
Multiple revolution Lambert problem constructor for problem definition.
void computeForRevolutionsAndBranch (const int aNumberOfRevolutions, const bool aIsRightBranch)
Compute solution for N revolutions and branch.
int getMaximumNumberOfRevolutions ()
Get maximum number of revolutions calculated.
Public Member Functions inherited from tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo
EIGEN_MAKE_ALIGNED_OPERATOR_NEW ZeroRevolutionLambertTargeterIzzo (const Eigen::Vector3d &aCartesianPositionAtDeparture, const Eigen::Vector3d &aCartesianPositionAtArrival, const double aTimeOfFlight, const double aGravitationalParameter, const bool aIsRetrograde=false, const double aConvergenceTolerance=1.0e-9, const int aMaximumNumberOfIterations=50)
Zero revolution Lambert problem constructor for problem definition.
double getRadialVelocityAtArrival ()
Get radial velocity at arrival.
double getRadialVelocityAtDeparture ()
Get radial velocity at departure.
double getSemiMajorAxis ()
Get semi-major axis.
double getTransverseVelocityAtArrival ()
Get transverse velocity at arrival.
double getTransverseVelocityAtDeparture ()
Get transverse velocity at departure.
Public Member Functions inherited from tudat::mission_segments::LambertTargeter
EIGEN_MAKE_ALIGNED_OPERATOR_NEW LambertTargeter (const Eigen::Vector3d &aCartesianPositionAtDeparture, const Eigen::Vector3d &aCartesianPositionAtArrival, const double aTimeOfFlight, const double aGravitationalParameter)
Default constructor.
virtual ~LambertTargeter ()
Default destructor.
Eigen::Vector3d getInertialVelocityAtArrival ()
Get inertial velocity at arrival.
Eigen::Vector3d getInertialVelocityAtDeparture ()
Get inertial velocity at departure.
std::pair< Eigen::Vector3d, Eigen::Vector3d > getInertialVelocityVectors ()
Get inertial velocity vectors.
Static Public Attributes
static const int NO_MAXIMUM_REVOLUTIONS = -1
Flag indicating that the maximum number of revolutions has not yet been calculated!
Protected Member Functions
double computeRootTimeOfFlight ()
Solve the time of flight equation for x (for multiple revolutions).
virtual double computeTimeOfFlight (const double xParameter)
Compute time-of-flight using Lagrange's equation (for multiple revolutions).
void execute ()
Execute the solving procedure (for multiple revolutions).
void sanityCheckNumberOfRevolutions ()
Sanity check number of revolutions.
Protected Member Functions inherited from tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo
void computeVelocities (const double xParameter)
Compute velocities at departure and arrival.
void sanityCheckGravitationalParameter ()
Sanity check gravitational parameter.
void sanityCheckTimeOfFlight ()
Sanity check time of flight.
void transformDimensions ()
Transform input to sub results in adimensional units.
Protected Attributes
bool isRightBranch
Left/right branch flag.
int maximumNumberOfRevolutions
Maximum number of revolutions possible in problem.
int numberOfRevolutions
Number of revolutions in problem.
Protected Attributes inherited from tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo
const double convergenceTolerance
Convergence tolerance.
bool isLongway
Longway flag.
const bool isRetrograde
Retrograde motion flag.
double lambdaParameter
Lambda parameter.
const double maximumNumberOfIterations
Maximum number of iterations.
double normalizedChord
Normalized chord.
double normalizedMinimumEnergySemiMajorAxis
Normalized semi-major axis of minimum energy ellipse.
double normalizedRadiusAtArrival
Normalized radius at arrival.
double normalizedSemiPerimeter
Normalized semi-perimeter.
double normalizedTimeOfFlight
Normalized time-of-flight.
double transferAngle
Transfer angle.
bool transformed
Transformed flag.
double velocityNormalizingValue
Normalizing value for velocity.
Protected Attributes inherited from tudat::mission_segments::LambertTargeter
const Eigen::Vector3d cartesianPositionAtArrival
Cartesian position at arrival.
const Eigen::Vector3d cartesianPositionAtDeparture
Cartesian position at departure.
Eigen::Vector3d cartesianVelocityAtArrival
Cartesian velocity at arrival.
Eigen::Vector3d cartesianVelocityAtDeparture
Cartesian velocity at departure.
const double gravitationalParameter
Gravitational parameter.
bool solved
Solved boolean flag.
const double timeOfFlight
Time-of-flight.
Detailed Description
Solves the multi revolution (input parameter) Lambert problem using Izzo's algorithms, i.e., the two point boundary value problem of what kind of unperturbed Keplerian orbit connects two positions in a certain time of flight.
This class uses lazy evaluation, solving the algorithm is postponed until the function call relying on the computations.
The algorithm used is the same algorithms as the zero revolution base class (Izzo's method): only the computation of the time of flight (based on Battin's x-variable) now includes the number of revolutions. The branch is required for specifying the neighborhood of the two roots of the problem. Furthermore, the non-dimensionalized parameters are stored internally and reused for new calculations of new solutions for the same object.
Exceptions
std::runtime_error For negative time of flight and gravitational parameter values. Also, the number of revolutions is checked for feasibility: no negative values are allowed and is checked against an automatic computation of the maximum number of revolutions.
basic_mathematics::ConvergenceException When the internal rootfinding algorithm fails to converge within a reasonable amount of iterations.
Definition at line 55 of file multiRevolutionLambertTargeterIzzo.h.
Constructor & Destructor Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::MultiRevolutionLambertTargeterIzzo (const Eigen::Vector3d & aCartesianPositionAtDeparture, const Eigen::Vector3d & aCartesianPositionAtArrival, const double aTimeOfFlight, const double aGravitationalParameter, const int aNumberOfRevolutions = 0, const bool aIsRightBranch = false, const bool aIsRetrograde = false, const double aConvergenceTolerance = 1e-9, const int aMaximumNumberOfIterations = 50) inline
Constructs a lambert problem with all relevant parameters for a multiple revolution problem (i.e. allowing multiple full revolutions in the solution). Constructor does not compute a solution in order to save on computations; solving is done on first member function call by user.
Parameters
aCartesianPositionAtDeparture The initial position in xyz-coordinates. [m]
aCartesianPositionAtArrival The final position in xyz-coordinates. [m]
aTimeOfFlight The time-of-flight between the two positions. [s]
aGravitationalParameter The gravitational parameter of the central body for the computed solution orbit. [m^3/s^2]
aNumberOfRevolutions The required number of revolutions in the problem solution (default 0). [-]
aIsRightBranch A boolean flag to indicate whether the right or left branch (corresponding to a low or high energy transfer arc) should be used in the solution (default false). [-]
aIsRetrograde A boolean flag to indicate retrograde motion with (default false). [-]
aConvergenceTolerance The required tolerance for the root solving procedure. [-]
aMaximumNumberOfIterations The required number of iterations the root solving procedure is allowed to go through (default 50). [-]
Definition at line 83 of file multiRevolutionLambertTargeterIzzo.h.
Member Function Documentation
void tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeForRevolutionsAndBranch (const int aNumberOfRevolutions, const bool aIsRightBranch)
Using the constants from the problem specified in the constructor, this calculates an alternative solution specified by the number of revolutions and branch selected.
Parameters
aNumberOfRevolutions Number of revolutions for the alternative solution. [-]
aIsRightBranch A boolean flag to indicate retrograde motion. [-]
Definition at line 34 of file multiRevolutionLambertTargeterIzzo.cpp.
References execute(), isRightBranch, numberOfRevolutions, and sanityCheckNumberOfRevolutions().
int tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::getMaximumNumberOfRevolutions ()
Returns the maximum number of revolutions possible in a solution to the problem specified.
Returns
maximumNumberOfRevolutions Maximum number of revolutions possible for the problem.
Definition at line 49 of file multiRevolutionLambertTargeterIzzo.cpp.
References maximumNumberOfRevolutions, sanityCheckNumberOfRevolutions(), tudat::mission_segments::LambertTargeter::solved, and tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::transformDimensions().
void tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::sanityCheckNumberOfRevolutions () protected
Computes (if not done before) the maximum number of revolutions possible and checks whether the number of revolutions specified is within this solution space. This only yields a proper outcome after dimensions have been transformed.
Definition at line 61 of file multiRevolutionLambertTargeterIzzo.cpp.
References computeRootTimeOfFlight(), maximumNumberOfRevolutions, NO_MAXIMUM_REVOLUTIONS, tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedSemiPerimeter, tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedTimeOfFlight, numberOfRevolutions, and tudat::mathematical_constants::PI.
Referenced by computeForRevolutionsAndBranch(), and getMaximumNumberOfRevolutions().
void tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::execute () protected virtual
Execute solving procedure (for multiple revolutions).
Executes the de-dimensionalization of the input parameter, solves the root for the time of flight equation, and subsequently reconstructs the inertial velocities to obtain a solution to the Lambert problem specified by the constructor of the class. If the number of revolutions specified is zero, it automatically calls to the base class function to calculate for zero revolutions.
Reimplemented from tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo.
Definition at line 123 of file multiRevolutionLambertTargeterIzzo.cpp.
References computeRootTimeOfFlight(), tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::computeVelocities(), tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::execute(), numberOfRevolutions, tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::sanityCheckGravitationalParameter(), tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::sanityCheckTimeOfFlight(), tudat::mission_segments::LambertTargeter::solved, and tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::transformDimensions().
Referenced by computeForRevolutionsAndBranch().
double tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeTimeOfFlight (const double xParameter) protected virtual
Computes the time-of-flight according to Lagrange's equation as a function of the x-parameter as used by Battin, using the class's sub results, including multiple revolutions.
Parameters
xParameter x parameter in Izzo's algorithm.
Returns
timeOfFlight Computed time-of-flight.
Reimplemented from tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo.
Definition at line 153 of file multiRevolutionLambertTargeterIzzo.cpp.
References tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::isLongway, tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedChord, tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedMinimumEnergySemiMajorAxis, tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedSemiPerimeter, numberOfRevolutions, tudat::mathematical_constants::PI, tudat::input_output::field_types::state::semiMajorAxis, and tudat::mission_segments::LambertTargeter::timeOfFlight.
Referenced by computeRootTimeOfFlight().
double tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::computeRootTimeOfFlight () protected virtual
Initializes and finds the root of the equation , where is a function to compute the time-of-flight as a function of , for a multiple revolution solution.
Returns
xParameter Computed x parameter.
Reimplemented from tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo.
Definition at line 226 of file multiRevolutionLambertTargeterIzzo.cpp.
References computeTimeOfFlight(), tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::convergenceTolerance, isRightBranch, tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::maximumNumberOfIterations, tudat::mission_segments::ZeroRevolutionLambertTargeterIzzo::normalizedTimeOfFlight, and tudat::mathematical_constants::PI.
Referenced by execute(), and sanityCheckNumberOfRevolutions().
Member Data Documentation
const int tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::NO_MAXIMUM_REVOLUTIONS = -1 static
When maximumNumberOfRevolutions is this amount of revolutions, it has not yet been initialized. Initialization is done automatically for the user.
Definition at line 112 of file multiRevolutionLambertTargeterIzzo.h.
Referenced by sanityCheckNumberOfRevolutions().
int tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::numberOfRevolutions protected
Number of full revolutions needed in the solution to the problem specified.
NB: the following parameters can be readjusted by the appropriate public function and therefore not declared const.
Definition at line 176 of file multiRevolutionLambertTargeterIzzo.h.
Referenced by computeForRevolutionsAndBranch(), computeTimeOfFlight(), execute(), and sanityCheckNumberOfRevolutions().
bool tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::isRightBranch protected
Boolean indicator for left or right branch solution, corresponding to a low or high energy transfer of the multiple solutions.
Definition at line 183 of file multiRevolutionLambertTargeterIzzo.h.
Referenced by computeForRevolutionsAndBranch(), and computeRootTimeOfFlight().
int tudat::mission_segments::MultiRevolutionLambertTargeterIzzo::maximumNumberOfRevolutions protected
Number of full revolutions possible as a solution in the problem specified.
NB: The following parameter is calculated on construction of the object and therefore not declared const.
Definition at line 192 of file multiRevolutionLambertTargeterIzzo.h.
Referenced by getMaximumNumberOfRevolutions(), and sanityCheckNumberOfRevolutions().
The documentation for this class was generated from the following files:
Astrodynamics/MissionSegments/multiRevolutionLambertTargeterIzzo.h
Astrodynamics/MissionSegments/multiRevolutionLambertTargeterIzzo.cpp