Tudat: tudat::mission_segments::OscillatingFunctionNovak Class Reference
tudat::mission_segments::OscillatingFunctionNovak Class Reference
This class contains an oscillating function, and its exact first and second derivative w.r.t.
#include <oscillatingFunctionNovak.h>
Public Member Functions
OscillatingFunctionNovak (const boost::function< std::pair< Eigen::Vector2d, const Eigen::Vector2d >() > aSetOfBoundaryParameters)
Default constructor with immediate definition of parameters.
~OscillatingFunctionNovak ()
Default destructor.
double computeDefiniteIntegral (const unsigned int order, const double lowerBound, const double upperBound)
Compute the definite integral of the function.
double computeDerivative (const unsigned int order, const double anAzimuthalAngle)
Compute the derivative of the function.
double evaluate (const double anAzimuthalAngle)
Evaluate the function value for a given (in-plane) azimuthal angle.
Public Member Functions inherited from tudat::basic_mathematics::Function< >
virtual ~Function ()
Default destructor.
double operator() (const double inputValue)
Alias for evaluate(double).
Private Attributes
boost::function< std::pair< Eigen::Vector2d, Eigen::Vector2d >) > boundaryParameters_
The parameters of the function, related to the boundary conditions.
Detailed Description
Oscillating function approximating the (out-of-plane) elevation angle of a thrusting spacecraft.
the azimuthal angle . It is a mathematical function, and can be used to approximate the out-of-plane motion of a thrusting spacecraft. The function is documented by Novak and Vasile [2011]. It approximates the (out-of-plane) elevation angle of the spacecraft. The (out-of-plane) elevation angle is parameterized in terms of an independent variable, the (in-plane) azimuthal angle . The first and second derivative are taken with respect to this independent variable.
The function is completely described by the independent variable and a set of four parameters. These parameters are related to the boundary conditions of the problem: two initial conditions and two final conditions. These parameters are passed to this class as boost::functions to facilitate the flexible external manipulation of their values.
Definition at line 62 of file oscillatingFunctionNovak.h.
Constructor & Destructor Documentation
tudat::mission_segments::OscillatingFunctionNovak::OscillatingFunctionNovak (const boost::function< std::pair< Eigen::Vector2d, const Eigen::Vector2d >() > aSetOfBoundaryParameters) inline
Default constructor with immediate definition of parameters through boost::functions. This setup allows for a flexible external manipulation of the values of the parameters.
Parameters
aSetOfBoundaryParameters A set of four parameters, related to the boundary conditions. These parameters are equivalent to the parameters b0, b1, b2, and b3 from Novak and Vasile [2011]. The order is important! aSetOfBoundaryParameters.first(0) = b0 aSetOfBoundaryParameters.first(1) = b1 aSetOfBoundaryParameters.second(0) = b2 aSetOfBoundaryParameters.second(1) = b3
Definition at line 79 of file oscillatingFunctionNovak.h.
tudat::mission_segments::OscillatingFunctionNovak::~OscillatingFunctionNovak () inline
Default destructor.
Definition at line 87 of file oscillatingFunctionNovak.h.
References computeDefiniteIntegral(), computeDerivative(), and evaluate().
Member Function Documentation
double tudat::mission_segments::OscillatingFunctionNovak::evaluate (const double anAzimuthalAngle) virtual
Evaluates the oscillating function for a given (in-plane) azimuthal angle .
The function is given by Novak and Vasile [2011] as:
in which is the (out-of-plane) elevation angle of the spacecraft, is the (in-plane) azimuthal angle and are parameters that define the shape of the trajectory.
Parameters
anAzimuthalAngle Value of the (in-plane) azimuthal angle [rad].
Returns
The (out-of-plane) elevation angle at [m].
Implements tudat::basic_mathematics::Function< >.
Definition at line 40 of file oscillatingFunctionNovak.cpp.
References boundaryParameters_.
Referenced by computeDerivative(), and ~OscillatingFunctionNovak().
double tudat::mission_segments::OscillatingFunctionNovak::computeDerivative (const unsigned int order, const double anAzimuthalAngle) virtual
Computes the derivative of a given order of the function, for a given (in-plane) azimuthal angle . It only evaluates the first, second or third derivative, therefore the order should be 1, 2 or 3.
The first derivative of the function is:
The second derivative of the function is:
The third derivative of the function is:
In these formulas is the (out-of-plane) elevation angle of the spacecraft, is the (in-plane) azimuthal angle, the prime indicates the derivative with respect to , and are parameters that define the shape of the trajectory.
Parameters
order Order of the derivative to evaluate. Can be either 1, 2 or 3.
anAzimuthalAngle Value of the (in-plane) azimuthal angle [rad].
Returns
Value of the derivative of order 1, 2 or 3 of the function [-, rad^-1, rad^-2].
Implements tudat::basic_mathematics::Function< >.
Definition at line 55 of file oscillatingFunctionNovak.cpp.
References boundaryParameters_, and evaluate().
Referenced by ~OscillatingFunctionNovak().
double tudat::mission_segments::OscillatingFunctionNovak::computeDefiniteIntegral (const unsigned int order, const double lowerBound, const double upperBound) virtual
This function throws a runtime error when it is called. The integral of the inverse polynomial function is not part of the shape-based method.
Parameters
order Order of the integral to evaluate.
lowerBound Integration lower bound (integrate from this point).
upperBound Integration upper bound (integrate to this point).
Returns
Value of the integral.
Exceptions
std::runtime_error when this function is used.
Implements tudat::basic_mathematics::Function< >.
Definition at line 121 of file oscillatingFunctionNovak.cpp.
References TUDAT_UNUSED_PARAMETER.
Referenced by ~OscillatingFunctionNovak().
Member Data Documentation
boost::function< std::pair< Eigen::Vector2d, Eigen::Vector2d >) > tudat::mission_segments::OscillatingFunctionNovak::boundaryParameters_ private
The four parameters of the function. These parameters determine the shape of the trajectory and are dependent on the initial and final boundary conditions.
The first two parameters are dependent on the initial boundary conditions and the last two parameters are dependent on the final boundary conditions. The parameters correspond to Novak and Vasile [2011] in the following manner: the first two parameters are and ; the last two parameters are and .
The order is important! boundaryParameters_.first(0) = b_0 boundaryParameters_.first(1) = b_1 boundaryParameters_.second(0) = b_2 boundaryParameters_.second(1) = b_3
Definition at line 186 of file oscillatingFunctionNovak.h.
Referenced by computeDerivative(), and evaluate().
The documentation for this class was generated from the following files:
Astrodynamics/MissionSegments/oscillatingFunctionNovak.h
Astrodynamics/MissionSegments/oscillatingFunctionNovak.cpp