Tudat: tudat::numerical_derivatives Namespace Reference
tudat::numerical_derivatives Namespace Reference
Enumerations
enum CentralDifferenceOrders { order2 = 2, order4 = 4, order6 = 6, order8 = 8 }
Enum with list of available orders.
Functions
Eigen::MatrixXd computeCentralDifference (const Eigen::VectorXd &input, const boost::function< Eigen::VectorXd(const Eigen::VectorXd &) > &function, double minimumStep=0.0, double relativeStepSize=0.0, CentralDifferenceOrders order=order2)
Compute a full numerical derivative using a central difference method.
template<typename InputType , typename ResultType >
ResultType computeCentralDifference (const InputType &input, const int derivativeIndex, const boost::function< ResultType(const InputType &) > &function, double minimumStep=0.0, double relativeStepSize=0.0, CentralDifferenceOrders order=order2)
Compute a numerical derivative using a central difference method.
template<typename DependentVariableType , typename IndependentVariableType >
DependentVariableType computeCentralDifference (const boost::function< DependentVariableType(const IndependentVariableType) > &dependentVariableFunction, const IndependentVariableType nominalIndependentVariable, const IndependentVariableType independentVariableStepSize, CentralDifferenceOrders order=order2)
const std::map< int, double > & getCentralDifferenceCoefficients (CentralDifferenceOrders order)
Get coefficients of a certain order for central difference numerical derivatives.
Enumeration Type Documentation
enum tudat::numerical_derivatives::CentralDifferenceOrders
List of available orders: 2, 4, 6, 8.
Enumerator
order2
order4
order6
order8
Definition at line 37 of file numericalDerivative.h.
Function Documentation
const std::map< int, double > & tudat::numerical_derivatives::getCentralDifferenceCoefficients (CentralDifferenceOrders order)
Get coefficients of a certain order for central difference numerical derivatives as a map of position versus weight. Coefficients are from (Fornberg, B., 1988).
Parameters
order The order of the coeffients.
Returns
Map of position versus weight.
Definition at line 27 of file numericalDerivative.cpp.
References order2, order4, order6, and order8.
Referenced by computeCentralDifference().
Eigen::MatrixXd tudat::numerical_derivatives::computeCentralDifference (const Eigen::VectorXd & input, const boost::function< Eigen::VectorXd(const Eigen::VectorXd &) > & function, double minimumStep = 0.0, double relativeStepSize = 0.0, CentralDifferenceOrders order = order2)
Computes a Jacobian numerically using a central difference method for a vector function with vector output. The implemented orders are 2nd, 4th and 8th.
Parameters
input Input vector
function The function to call with signature void(const VectorXd& input, VectorXd& result).
minimumStep The absolute minimum step size to take. By default 2^-13.
relativeStepSize The relative step size to take. By default 2^-26.
order The order of the algorithm to use. Will yield an assertion failure if not 2 or 4.
Returns
Numerical derivative calculated from input
Definition at line 66 of file numericalDerivative.cpp.
Referenced by computeCentralDifference(), and tudat::simulation_setup::getBodyAccelerationInBaseFramefromNumericalDifferentiation().
template<typename InputType , typename ResultType > ResultType tudat::numerical_derivatives::computeCentralDifference (const InputType & input, const int derivativeIndex, const boost::function< ResultType(const InputType &) > & function, double minimumStep = 0.0, double relativeStepSize = 0.0, CentralDifferenceOrders order = order2)
Computes a specified numerical derivative using a central difference method for a vector function with vector output. The implemented orders are 2nd, 4th and 8th. This function needs to be fully implemented in the header file because it is a template function.
Parameters
input Input vector.
derivativeIndex The index of the entry of the input vector with respect to which to take the derivative.
function The function to call with signature void(const VectorXd& input, VectorXd& result).
minimumStep The absolute minimum step size to take. By default 2^-13.
relativeStepSize The relative step size to take. By default 2^-26.
order The order of the algorithm to use.
Returns
Numerical derivative calculated from input
Definition at line 72 of file numericalDerivative.h.
References computeCentralDifference(), getCentralDifferenceCoefficients(), and order2.
template<typename DependentVariableType , typename IndependentVariableType > DependentVariableType tudat::numerical_derivatives::computeCentralDifference (const boost::function< DependentVariableType(const IndependentVariableType) > & dependentVariableFunction, const IndependentVariableType nominalIndependentVariable, const IndependentVariableType independentVariableStepSize, CentralDifferenceOrders order = order2)
Definition at line 144 of file numericalDerivative.h.
References getCentralDifferenceCoefficients().