Tudat: tudat::input_output::parsed_data_vector_utilities Namespace Reference
tudat::input_output::parsed_data_vector_utilities Namespace Reference
Typedefs
typedef boost::shared_ptr< FieldValue > FieldValuePtr
Pointer to a field value (string).
typedef std::map< FieldType, FieldValuePtr > ParsedDataLineMap
typedef boost::shared_ptr< ParsedDataLineMap > ParsedDataLineMapPtr
Pointer to a parsed data line (see ParsedDataLineMap).
typedef std::vector< ParsedDataLineMapPtr > ParsedDataVector
typedef boost::shared_ptr< ParsedDataVector > ParsedDataVectorPtr
Pointer to the data map pointer vectors (see ParsedDataVector).
Functions
std::ostream & dump (std::ostream &stream, ParsedDataLineMapPtr data, bool showTransformed)
Dump the content of a data map to an ostream.
std::ostream & dump (std::ostream &stream, ParsedDataVectorPtr data, bool showTransformed)
Dump the content of a data vector to an ostream (eg std::cout).
ParsedDataVectorPtr filterMapKey (ParsedDataVectorPtr datavector, int nrFields,...)
Filter the data vector for entries containing a given FieldType.
ParsedDataVectorPtr filterMapKeyValue (ParsedDataVectorPtr datavector, int nrFields,...)
This allows for filtering of a parsed data vector, based on the requirement that each of the datamaps MUST include each passed FieldType and its value MUST have at least one match for the passed regex for each respective field.
template<typename T >
T getField (ParsedDataLineMapPtr data, FieldType field)
Get the value of a given field from the map containing data.
template<typename T >
boost::shared_ptr< T > getFieldPointer (ParsedDataLineMapPtr data, FieldType field)
Get a shared-pointer to the value of a given field from the map containing data.
Typedef Documentation
typedef boost::shared_ptr< FieldValue > tudat::input_output::parsed_data_vector_utilities::FieldValuePtr
Definition at line 34 of file parsedDataVectorUtilities.h.
typedef std::map< FieldType, FieldValuePtr > tudat::input_output::parsed_data_vector_utilities::ParsedDataLineMap
Map containing field value pointers (mapped value), identified by their field type (key value). Such maps contain the information from one parsed line.
Definition at line 38 of file parsedDataVectorUtilities.h.
typedef boost::shared_ptr< ParsedDataLineMap > tudat::input_output::parsed_data_vector_utilities::ParsedDataLineMapPtr
Definition at line 41 of file parsedDataVectorUtilities.h.
typedef std::vector< ParsedDataLineMapPtr > tudat::input_output::parsed_data_vector_utilities::ParsedDataVector
Vector of data map pointers (see ParsedDataLineMapPtr). Each entry of the vector points to parsed data line.
Definition at line 45 of file parsedDataVectorUtilities.h.
typedef boost::shared_ptr< ParsedDataVector > tudat::input_output::parsed_data_vector_utilities::ParsedDataVectorPtr
Definition at line 48 of file parsedDataVectorUtilities.h.
Function Documentation
ParsedDataVectorPtr tudat::input_output::parsed_data_vector_utilities::filterMapKey (ParsedDataVectorPtr datavector, int nrFields, ...)
This allows for filtering of a parsed data vector, based on the requirement that each of the datamaps MUST include each passed FieldTypes.
Example usage: ParsedDataVectorPtr datavector; filterMapKey(datavector, 2, fieldtypes::general::name, fieldtypes::time::epoch);
This return a new data vector that contains data maps only with the name FieldType and the epoch FieldType.
Parameters
datavector Data vector to be checked for all the requested FieldTypes.
nrFields Number of field that each entry must contain
... Fieldtypes that each entry must contain.
Returns
newdatavector A copy of the data vector with only the entries that contain the passed FieldTypes.
Definition at line 27 of file parsedDataVectorUtilities.cpp.
Referenced by getFieldPointer().
ParsedDataVectorPtr tudat::input_output::parsed_data_vector_utilities::filterMapKeyValue (ParsedDataVectorPtr datavector, int nrFields, ...)
Filter the data vector vector for entries containing a given FieldType and a matching FieldValue regex.
Filter the data vector vector for entries containing a given FieldType and a matching FieldValue regex.
Example usage: ParsedDataVectorPtr datavector; filterMapKeyValue(datavector, 2, fieldtypes::general::name, "Venus", fieldtypes::time::epoch, "2451545[\.0-9]*");
This filter would create a new vector, where each data line is about Venus, and the epoch for that dataline is on the date of 2000-1-1 (J2000). This means epoch can range from 2000-1-1 00h to 2000-1-1 23h59m59.999...
Note: the regular expression is in the form of char* and not boost::regex because that yields the followong stdargs incompatibility: error: cannot receive objects of non-trivially-copyable type 'boost::regex {aka struct boost::basic_regex<char, boost::regex_traits<char> >}' through '...';
Parameters
datavector Data vector to be checked for all the requested FieldTypes.
nrFields Number of field that each entry must contain.
... List of FieltType and Regex (char*) entries that must match to be addmited in the filtered vector.
Returns
newdatavector A copy of the data vector with only the entries that contain the passed FieldTypes.
Definition at line 86 of file parsedDataVectorUtilities.cpp.
Referenced by getFieldPointer().
std::ostream & tudat::input_output::parsed_data_vector_utilities::dump (std::ostream & stream, ParsedDataLineMapPtr data, bool showTransformed)
This method allows users to quickly visualize the content of a datamap (single line) by dumping its raw or transformed content to a given output stream (eg std::cout).
Example usage: ParsedDataLineMapPtr datamap; dump(std::cout, datamap, false);
This dumps untransformed content of datamap to std::cout
Parameters
stream Stream to dump the content to.
data Datamap content to dump.
showTransformed Flag to show if it should dump raw values (false) or transformed values (true).
Returns
stream A reference to the ostream.
Definition at line 160 of file parsedDataVectorUtilities.cpp.
Referenced by dump(), and getFieldPointer().
std::ostream & tudat::input_output::parsed_data_vector_utilities::dump (std::ostream & stream, ParsedDataVectorPtr data, bool showTransformed)
Dump the content of a data vector to an ostream (eg std::cout)
This method allows users to quickly visualize the content of a data vector by dumping its raw or transformed content to a given output stream.
Example usage: ParsedDataVectorPtr datavector; dump(std::cout, datavector, false);
This dump untransformed content of datavector to std::cout.
Parameters
stream Stream to dump the content to.
data Datavector content to dump.
showTransformed Flag to show if it should dump raw values (false) or transformed values (true)
Returns
A reference to the ostream
Definition at line 190 of file parsedDataVectorUtilities.cpp.
References dump().
template<typename T > T tudat::input_output::parsed_data_vector_utilities::getField (ParsedDataLineMapPtr data, FieldType field) inline
Returns the transformed (calls FieldValue::get()) value of a field in a data map.
Note: You must be sure that that the key exists in the data map or otherwise, segfaults will occur.
Example usage: ParsedDataLineMapPtr datamap; string planetName = getField<string>(datamap, fieldtypes::general::name); int planetID = getField< int >(datamap, fieldtypes::general::id); double planetEccentricity = getField<double>(datamap, fieldtypes::state::eccentricity);
Parameters
data Check this datamap for all the requested FieldTypes.
field Fieldtype to search for.
Returns
FieldValue The FieldValue string converted to the given type.
Definition at line 68 of file parsedDataVectorUtilities.h.
template<typename T > boost::shared_ptr< T > tudat::input_output::parsed_data_vector_utilities::getFieldPointer (ParsedDataLineMapPtr data, FieldType field) inline
Returns the transformed (calls FieldValue::getPointer()) value of a field in a data map.
Note: You must be sure that that the key exists in the data map or otherwise, segfaults will occur.
Example usage: ParsedDataLineMapPtr datamap; boost::shared_ptr<string> planetName = getField<string>(datamap, fieldtypes::general::name); boost::shared_ptr<int> planetID = getField< int >(datamap, fieldtypes::general::id); boost::shared_ptr<double> planetEccentricity = getField<double>(datamap, fieldtypes::state::eccentricity);
Parameters
data Check this datamap for all the requested FieldTypes.
field Fieldtype to search for.
Returns
FieldValue The FieldValue string converted to the given type.
Definition at line 95 of file parsedDataVectorUtilities.h.
References dump(), filterMapKey(), and filterMapKeyValue().