Tudat: tudat::ground_stations Namespace Reference
tudat::ground_stations Namespace Reference
Classes
class GroundStation
Class to store properties of a ground station (i.e. reference point with associated systems on a celestial body)
class GroundStationState
Class storing and computing the (time-variable) state of a ground station in a body-fixed frame.
class PointingAnglesCalculator
Class to calculate the pointing angles (azimuth elevation) from a topocentric frame.
Functions
std::vector< Eigen::Vector3d > getGeocentricLocalUnitVectors (const Eigen::Matrix3d &toPlanetFixedFrameMatrix)
Function to generate unit vectors of topocentric frame.
std::vector< Eigen::Vector3d > getGeocentricLocalUnitVectors (const double latitude, const double longitude)
Function to generate unit vectors of topocentric frame.
Eigen::Quaterniond getRotationQuaternionFromBodyFixedToTopocentricFrame (const std::shared_ptr< basic_astrodynamics::BodyShapeModel > bodyShapeModel, const double geocentricLatitude, const double geocentricLongitude, const Eigen::Vector3d localPoint)
Function to calculate the rotation from a body-fixed to a topocentric frame.
bool isTargetInView (const double time, const Eigen::Vector3d targetRelativeState, const std::shared_ptr< PointingAnglesCalculator > pointingAngleCalculator, const double minimumElevationAngle)
Function to check whether a target is visible from a ground station, based on minimum allowed elevation angle.
Function Documentation
isTargetInView()
bool tudat::ground_stations::isTargetInView (const double time, const Eigen::Vector3d targetRelativeState, const std::shared_ptr< PointingAnglesCalculator > pointingAngleCalculator, const double minimumElevationAngle)
Function to check whether a target is visible from a ground station, based on minimum allowed elevation angle, and the vector from ground station to target expressed in inertial coordinates
Parameters
time Time at which visibility is to be checked.
targetRelativeState Inertial state vector from ground station to target
pointingAngleCalculator Object that computes the pointing angles (azimuth/elevation) for a given ground station
minimumElevationAngle Minimum elevation angle above which the target is considered 'visible'
Returns
True if target is visible, false if not.
Definition at line 21 of file groundStation.cpp.
Referenced by tudat::observation_models::MinimumElevationAngleCalculator::isObservationViable().
getGeocentricLocalUnitVectors() [1/2]
std::vector< Eigen::Vector3d > tudat::ground_stations::getGeocentricLocalUnitVectors (const Eigen::Matrix3d & topocentricToPlanetFixedFrameMatrix)
Function to generate unit vectors of topocentric frame. The set of unit vectors of topocentric frame is expressed in body-fixed frame, in ENU (Earth-North-Up) order.
Parameters
topocentricToPlanetFixedFrameMatrix Rotation matrix from topocentric to body-fixed frame.
Returns
Unit vectors of topocentric frame, expressed in body-fixed frame.
Definition at line 26 of file groundStationState.cpp.
Referenced by getGeocentricLocalUnitVectors(), getRotationQuaternionFromBodyFixedToTopocentricFrame(), and tudat::ground_stations::GroundStationState::setTransformationAndUnitVectors().
getGeocentricLocalUnitVectors() [2/2]
std::vector< Eigen::Vector3d > tudat::ground_stations::getGeocentricLocalUnitVectors (const double latitude, const double longitude)
Function to generate unit vectors of topocentric frame. The set of unit vectors of topocentric frame is expressed in body-fixed frame, in ENU (Earth-North-Up) order.
Parameters
latitude Latitude of point for which topocentric frame is to be created.
longitude Longitude of point for which topocentric frame is to be created.
Returns
Unit vectors of topocentric frame, expressed in body-fixed frame
Definition at line 39 of file groundStationState.cpp.
References tudat::reference_frames::getEnuLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion(), and getGeocentricLocalUnitVectors().
getRotationQuaternionFromBodyFixedToTopocentricFrame()
Eigen::Quaterniond tudat::ground_stations::getRotationQuaternionFromBodyFixedToTopocentricFrame (const std::shared_ptr< basic_astrodynamics::BodyShapeModel > bodyShapeModel, const double geocentricLatitude, const double geocentricLongitude, const Eigen::Vector3d localPoint)
Function to calculate the rotation from a body-fixed to a topocentric frame at a given point (localPoint), based on the geocentric latitude and longitude (i.e. angles based on line from center of body to localPoint. The topocentric calculation differs per type of body shape wrt which the point is located. The rotation is calculated by concatenating the unit vectors of the topocentric frame, expresse in the body-fixed frame.
Parameters
bodyShapeModel Shape model of body on which point is located.
geocentricLatitude Geocentric latitude of point, i.e. angle between equatorial planet and line from center of body to localPoint
geocentricLongitude Geocentric longitude of point, i.e. angle between positive x-axis and line from center of body to localPoint, projected on equatorial plane, measured positive in +y direction
localPoint Cartesian position of point in body-fixed frame.
Returns
The rotation from the body-fixed to the topocentric frame at localPoint.
Definition at line 103 of file groundStationState.cpp.
References tudat::coordinate_conversions::calculateGeodeticLatitude(), tudat::mathematical_constants::E, tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getFlattening(), and getGeocentricLocalUnitVectors().
Referenced by tudat::ground_stations::GroundStationState::setTransformationAndUnitVectors().