Tudat: tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType > Class Template Reference
tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType > Class Template Reference abstract
Virtual base class for the observation simulator class.
#include <observationSimulator.h>
Public Member Functions
ObservationSimulatorBase (const ObservableType observableType)
Constructor.
std::vector< boost::shared_ptr< ObservationViabilityCalculator > > getLinkViabilityCalculators (const LinkEnds &linkEnds)
Function to retrieve observation viability calculators for a single set of link ends.
ObservableType getObservableType ()
Function to get the type of observable for which this object computes observations.
virtual int getObservationSize (const LinkEnds &linkEnds)=0
Function to get the observation model for a given set of link ends.
void setViabilityCalculators (const std::map< LinkEnds, std::vector< boost::shared_ptr< ObservationViabilityCalculator > > > &viabilityCalculators)
Function to set observation viability calculators.
virtual Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > simulateObservation (const TimeType observationTime, const LinkEnds linkEnds, const LinkEndType linkEndAssociatedWithTime, std::vector< double > &linkEndTimes, std::vector< Eigen::Matrix< double, 6, 1 > > &linkEndStates)=0
Function (pure virtual) to simulate a single observation between specified link ends.
virtual std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::vector< TimeType > > simulateObservations (const std::vector< TimeType > &observationTimes, const LinkEnds linkEnds, const LinkEndType linkEndAssociatedWithTime, const bool checkTimes=true)=0
Function (pure virtual) to simulate observations between specified link ends.
virtual std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > simulateObservationsWithLinkEndId (const std::vector< TimeType > &observationTimes, const LinkEnds linkEnds, const LinkEndType linkEndAssociatedWithTime, const bool checkTimes=true)=0
Function (pure virtual) to simulate observations between specified link ends.
Protected Attributes
ObservableType observableType_
Type of observable for which this object computes observations.
std::map< LinkEnds, std::vector< boost::shared_ptr< ObservationViabilityCalculator > > > viabilityCalculators_
List of observation viability calculators, sorted by LinkEnds.
Detailed Description
template<typename ObservationScalarType = double, typename TimeType = double>
class tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >
Virtual base class for the observation simulator class, which is used to compute observable values of a single type of observable This base class is used for practical purposes, as the derived class has a template argument for the observable size, precluding the possibility of making a list of objects for all observation simulators (e.g. one for each observable type)
Definition at line 139 of file observationSimulator.h.
Constructor & Destructor Documentation
template<typename ObservationScalarType = double, typename TimeType = double> tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::ObservationSimulatorBase (const ObservableType observableType) inline
Constructor
Parameters
observableType Type of observable for which this object computes observations.
Definition at line 148 of file observationSimulator.h.
Member Function Documentation
template<typename ObservationScalarType = double, typename TimeType = double> ObservableType tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getObservableType () inline
Function to get the type of observable for which this object computes observations
Returns
Type of observable for which this object computes observations
Definition at line 157 of file observationSimulator.h.
References tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getObservationSize(), tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::observableType_, tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::simulateObservation(), tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::simulateObservations(), and tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::simulateObservationsWithLinkEndId().
template<typename ObservationScalarType = double, typename TimeType = double> virtual int tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getObservationSize (const LinkEnds & linkEnds) pure virtual
Function to get the observation model for a given set of link ends
Returns
Observation model for a given set of link ends
Implemented in tudat::observation_models::ObservationSimulator< ObservationSize, ObservationScalarType, TimeType >.
Referenced by tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getObservableType().
template<typename ObservationScalarType = double, typename TimeType = double> virtual Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::simulateObservation (const TimeType observationTime, const LinkEnds linkEnds, const LinkEndType linkEndAssociatedWithTime, std::vector< double > & linkEndTimes, std::vector< Eigen::Matrix< double, 6, 1 > > & linkEndStates) pure virtual
Function (pure virtual) to simulate a single observation between specified link ends. Function is provided to have an interface to simulate a single observation from an ObservationModel object (in ObservationSimulator derived class) without the need for a ObservationSize template argument.
Parameters
observationTime Time at which observable is to be evaluated.
linkEnds Set of stations, S/C etc. in link, with specifiers of type of link end.
linkEndAssociatedWithTime Link end at which given time is valid, i.e. link end for which associated time is kept constant (to input value)
linkEndTimes List of times at each link end during observation.
linkEndStates List of states at each link end during observation.
Returns
Simulated observation at requested time and link ends.
Implemented in tudat::observation_models::ObservationSimulator< ObservationSize, ObservationScalarType, TimeType >.
Referenced by tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getObservableType().
template<typename ObservationScalarType = double, typename TimeType = double> virtual std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::vector< TimeType > > tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::simulateObservations (const std::vector< TimeType > & observationTimes, const LinkEnds linkEnds, const LinkEndType linkEndAssociatedWithTime, const bool checkTimes = true) pure virtual
Function (pure virtual) to simulate observations between specified link ends. Users can specify whether to check for availability of link at given reception time.
Parameters
observationTimes Vector of times at which observations taked place (i.e. reception time)
linkEnds Set of stations, S/C etc. in link, with specifiers of type of link end.
linkEndAssociatedWithTime Reference link end for observable
checkTimes Boolean denoting whether the observation times are to be checked for viability
Returns
Observations at given times (concatenated in an Eigen vector), with associated times
Implemented in tudat::observation_models::ObservationSimulator< ObservationSize, ObservationScalarType, TimeType >.
Referenced by tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getObservableType(), and tudat::observation_models::ObservationSimulator< ObservationSize, ObservationScalarType, TimeType >::simulateObservationsWithLinkEndId().
template<typename ObservationScalarType = double, typename TimeType = double> virtual std::pair< Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 >, std::pair< std::vector< TimeType >, LinkEndType > > tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::simulateObservationsWithLinkEndId (const std::vector< TimeType > & observationTimes, const LinkEnds linkEnds, const LinkEndType linkEndAssociatedWithTime, const bool checkTimes = true) pure virtual
Function (pure virtual) to simulate observations between specified link ends. Users can specify whether to check for availability of link at given reception time.
Parameters
observationTimes Vector of times at which observations taked place (i.e. reception time)
linkEnds Set of stations, S/C etc. in link, with specifiers of type of link end.
linkEndAssociatedWithTime Reference link end for observable
checkTimes Boolean denoting whether the observation times are to be checked for viability
Returns
Observations at given times (concatenated in an Eigen vector), with associated times and reference link end.
Implemented in tudat::observation_models::ObservationSimulator< ObservationSize, ObservationScalarType, TimeType >.
Referenced by tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getObservableType().
template<typename ObservationScalarType = double, typename TimeType = double> void tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::setViabilityCalculators (const std::map< LinkEnds, std::vector< boost::shared_ptr< ObservationViabilityCalculator > > > & viabilityCalculators) inline
Function to set observation viability calculators, a different list must be provided for each set of link ends.
Parameters
viabilityCalculators List of observation viability calculators, sorted by LinkEnds.
Definition at line 227 of file observationSimulator.h.
References tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::viabilityCalculators_.
template<typename ObservationScalarType = double, typename TimeType = double> std::vector< boost::shared_ptr< ObservationViabilityCalculator > > tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getLinkViabilityCalculators (const LinkEnds & linkEnds) inline
Function to retrieve observation viability calculators for a single set of link ends
Parameters
linkEnds Link ends for which observation viability calculators are to be retrieved
Returns
Observation viability calculators for requestred single set of link ends (empty vector if no calculators for requested link ends are given in this object)
Definition at line 241 of file observationSimulator.h.
References tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::viabilityCalculators_.
Member Data Documentation
template<typename ObservationScalarType = double, typename TimeType = double> ObservableType tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::observableType_ protected
Definition at line 258 of file observationSimulator.h.
Referenced by tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getObservableType().
template<typename ObservationScalarType = double, typename TimeType = double> std::map< LinkEnds, std::vector< boost::shared_ptr< ObservationViabilityCalculator > > > tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::viabilityCalculators_ protected
Definition at line 261 of file observationSimulator.h.
Referenced by tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::getLinkViabilityCalculators(), tudat::observation_models::ObservationSimulatorBase< ObservationScalarType, TimeType >::setViabilityCalculators(), tudat::observation_models::ObservationSimulator< ObservationSize, ObservationScalarType, TimeType >::simulateObservations(), and tudat::observation_models::ObservationSimulator< ObservationSize, ObservationScalarType, TimeType >::simulateObservationsWithLinkEndId().
The documentation for this class was generated from the following file:
Astrodynamics/ObservationModels/observationSimulator.h