Tudat: tudat::basic_mathematics::Function< IndependentVariable, DependentVariable > Class Template Reference
tudat::basic_mathematics::Function< IndependentVariable, DependentVariable > Class Template Reference abstract
Function interface to allow evaluation of a mathematical function.
#include <function.h>
Public Member Functions
virtual ~Function ()
Default destructor.
virtual DependentVariable computeDefiniteIntegral (const unsigned int order, const IndependentVariable lowerBound, const IndependentVariable upperbound)=0
Evaluate the definite integral of the function.
virtual DependentVariable computeDerivative (const unsigned int order, const IndependentVariable independentVariable)=0
Evaluate the derivative of the function. This implementation is a pure virtual function.
virtual DependentVariable evaluate (const IndependentVariable inputValue)=0
Compute mathematical function value. This implementation is a pure virtual function.
DependentVariable operator() (const double inputValue)
Alias for evaluate(double).
Detailed Description
template<typename IndependentVariable = double, typename DependentVariable = double>
class tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >
This class adds the ability to a class to be evaluated as a mathematical function.
Template Parameters
IndependentVariable Mathematical variable for independent input (e.g., x).
DependentVariable Mathematical variable for dependent output (e.g., y=f(x)).
Definition at line 29 of file function.h.
Constructor & Destructor Documentation
template<typename IndependentVariable = double, typename DependentVariable = double> virtual tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >::~Function () inline virtual
Definition at line 34 of file function.h.
Member Function Documentation
template<typename IndependentVariable = double, typename DependentVariable = double> virtual DependentVariable tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >::evaluate (const IndependentVariable inputValue) pure virtual
Computes the value of the mathematical function used for the root-finder algorithm being used.
Parameters
inputValue Input value.
Returns
Computed mathematical function value.
Implemented in tudat::mission_segments::ImprovedInversePolynomialWall, tudat::mission_segments::OscillatingFunctionNovak, tudat::basic_mathematics::FunctionProxy< IndependentVariable, DependentVariable >, and tudat::aerodynamics::EquilibriumTemperatureFunction.
Referenced by tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::computeDerivative(), tudat::basic_mathematics::Function< double, double >::operator()(), and tudat::basic_mathematics::Function< double, double >::~Function().
template<typename IndependentVariable = double, typename DependentVariable = double> DependentVariable tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >::operator() (const double inputValue) inline
Definition at line 46 of file function.h.
template<typename IndependentVariable = double, typename DependentVariable = double> virtual DependentVariable tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >::computeDerivative (const unsigned int order, const IndependentVariable independentVariable) pure virtual
This evaluates the derivative of a given order of this function.
Parameters
order Order of the derivative to evaluate.
independentVariable Location where to evaluate the derivative.
Returns
the derivative of the function
Implemented in tudat::mission_segments::ImprovedInversePolynomialWall, tudat::mission_segments::OscillatingFunctionNovak, tudat::basic_mathematics::FunctionProxy< IndependentVariable, DependentVariable >, tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >, and tudat::aerodynamics::EquilibriumTemperatureFunction.
Referenced by tudat::basic_mathematics::Function< double, double >::operator()().
template<typename IndependentVariable = double, typename DependentVariable = double> virtual DependentVariable tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >::computeDefiniteIntegral (const unsigned int order, const IndependentVariable lowerBound, const IndependentVariable upperbound) pure virtual
This evaluates the definite integral of a given order of this function. This implementation is a pure virtual function.
Parameters
order Order of the integral to evaluate.
lowerBound Integration lower bound (integrate from this point).
upperbound Integration upper bound (integrate to this point).
Returns
the definite numerical integral of this function
Implemented in tudat::mission_segments::ImprovedInversePolynomialWall, tudat::mission_segments::OscillatingFunctionNovak, tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >, and tudat::aerodynamics::EquilibriumTemperatureFunction.
Referenced by tudat::basic_mathematics::Function< double, double >::operator()().
The documentation for this class was generated from the following file:
Mathematics/BasicMathematics/function.h