Tudat: tudat::propulsion::CustomThrustMagnitudeWrapper Class Reference
tudat::propulsion::CustomThrustMagnitudeWrapper Class Reference
Class for custom computations of thrust magnitude and mass rate.
#include <thrustMagnitudeWrapper.h>
Public Member Functions
CustomThrustMagnitudeWrapper (const std::function< double(const double) > thrustMagnitudeFunction, const std::function< double(const double) > specificImpulseFunction, const std::function< bool(const double) > isEngineOnFunction=[](const double){ return true;}, const std::function< void(const double) > customThrustResetFunction=std::function< void(const double) >())
Constructor.
~CustomThrustMagnitudeWrapper ()
Destructor.
double getCurrentMassRate ()
Function to return the current mass rate.
double getCurrentThrustMagnitude ()
Function to return the current thrust magnitude.
virtual void resetDerivedClassCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the thrust model derived class.
void update (const double time)
Function to update the thrust magnitude to the current time.
Public Member Functions inherited from tudat::propulsion::ThrustMagnitudeWrapper
ThrustMagnitudeWrapper ()
Constructor.
virtual ~ThrustMagnitudeWrapper ()
Destructor.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the thrust model.
Private Attributes
double currentSpecificImpulse_
Current specific impulse, as computed by last call to update member function.
double currentThrustMagnitude_
Current thrust magnitude, as computed by last call to update member function.
std::function< void(const double) > customThrustResetFunction_
std::function< bool(const double) > isEngineOnFunction_
Function returning whether the function is on (returns true if so) at a given time.
std::function< double(const double) > specificImpulseFunction_
Function returning specific impulse as a function of time.
std::function< double(const double) > thrustMagnitudeFunction_
Function returning thrust as a function of time..
Additional Inherited Members
Protected Attributes inherited from tudat::propulsion::ThrustMagnitudeWrapper
double currentTime_
Current time for model.
Detailed Description
Class for custom computations of thrust magnitude and mass rate. Both the magnitude and specific impulse are parameterized as a function of time and provided as input, providing a flexible interface for user-defined thrust magnitude profiles.
Definition at line 98 of file thrustMagnitudeWrapper.h.
Constructor & Destructor Documentation
CustomThrustMagnitudeWrapper()
tudat::propulsion::CustomThrustMagnitudeWrapper::CustomThrustMagnitudeWrapper (const std::function< double(const double) > thrustMagnitudeFunction, const std::function< double(const double) > specificImpulseFunction, const std::function< bool(const double) > isEngineOnFunction = [ ](const double){ return true; }, const std::function< void(const double) > customThrustResetFunction = std::function< void(const double) >()) inline
Constructor
Parameters
thrustMagnitudeFunction Function returning thrust as a function of time.
specificImpulseFunction Function returning specific impulse as a function of time.
isEngineOnFunction Function returning whether the function is on (returns true if so) at a given time.
customThrustResetFunction Custom function that is to be called when signalling that a new time step is being started (empty by default)
Definition at line 111 of file thrustMagnitudeWrapper.h.
~CustomThrustMagnitudeWrapper()
tudat::propulsion::CustomThrustMagnitudeWrapper::~CustomThrustMagnitudeWrapper () inline
Definition at line 124 of file thrustMagnitudeWrapper.h.
Member Function Documentation
update()
void tudat::propulsion::CustomThrustMagnitudeWrapper::update (const double time) inline virtual
Function to update the thrust magnitude to the current time.
Parameters
time Time to which the model is to be updated.
Implements tudat::propulsion::ThrustMagnitudeWrapper.
Definition at line 131 of file thrustMagnitudeWrapper.h.
References currentSpecificImpulse_, currentThrustMagnitude_, tudat::propulsion::ThrustMagnitudeWrapper::currentTime_, isEngineOnFunction_, specificImpulseFunction_, thrustMagnitudeFunction_, and TUDAT_NAN.
getCurrentThrustMagnitude()
double tudat::propulsion::CustomThrustMagnitudeWrapper::getCurrentThrustMagnitude () inline virtual
Function to return the current thrust magnitude, as computed by last call to update member function.
Returns
Current thrust magnitude
Implements tudat::propulsion::ThrustMagnitudeWrapper.
Definition at line 156 of file thrustMagnitudeWrapper.h.
References currentThrustMagnitude_.
getCurrentMassRate()
double tudat::propulsion::CustomThrustMagnitudeWrapper::getCurrentMassRate () inline virtual
Function to return the current mass rate, computed from quantities set by last call to update member function.
Returns
Current mass rate.
Implements tudat::propulsion::ThrustMagnitudeWrapper.
Definition at line 166 of file thrustMagnitudeWrapper.h.
References tudat::propulsion::computePropellantMassRateFromSpecificImpulse(), currentSpecificImpulse_, and currentThrustMagnitude_.
resetDerivedClassCurrentTime()
virtual void tudat::propulsion::CustomThrustMagnitudeWrapper::resetDerivedClassCurrentTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the current time of the thrust model derived class. Function is typically used to reset the time to NaN, signalling the need for a recomputation of all required quantities.
Parameters
currentTime New current time to be set in model.
Reimplemented from tudat::propulsion::ThrustMagnitudeWrapper.
Definition at line 186 of file thrustMagnitudeWrapper.h.
References customThrustResetFunction_.
Member Data Documentation
thrustMagnitudeFunction_
std::function< double(const double) > tudat::propulsion::CustomThrustMagnitudeWrapper::thrustMagnitudeFunction_ private
Definition at line 197 of file thrustMagnitudeWrapper.h.
Referenced by update().
specificImpulseFunction_
std::function< double(const double) > tudat::propulsion::CustomThrustMagnitudeWrapper::specificImpulseFunction_ private
Definition at line 200 of file thrustMagnitudeWrapper.h.
Referenced by update().
isEngineOnFunction_
std::function< bool(const double) > tudat::propulsion::CustomThrustMagnitudeWrapper::isEngineOnFunction_ private
Definition at line 203 of file thrustMagnitudeWrapper.h.
Referenced by update().
currentThrustMagnitude_
double tudat::propulsion::CustomThrustMagnitudeWrapper::currentThrustMagnitude_ private
Definition at line 206 of file thrustMagnitudeWrapper.h.
Referenced by getCurrentMassRate(), getCurrentThrustMagnitude(), and update().
currentSpecificImpulse_
double tudat::propulsion::CustomThrustMagnitudeWrapper::currentSpecificImpulse_ private
Definition at line 209 of file thrustMagnitudeWrapper.h.
Referenced by getCurrentMassRate(), and update().
customThrustResetFunction_
std::function< void(const double) > tudat::propulsion::CustomThrustMagnitudeWrapper::customThrustResetFunction_ private
Definition at line 211 of file thrustMagnitudeWrapper.h.
Referenced by resetDerivedClassCurrentTime().
The documentation for this class was generated from the following file:
Astrodynamics/Propulsion/thrustMagnitudeWrapper.h