Tudat: tudat::transfer_trajectories::SwingbyLegMga Class Reference
tudat::transfer_trajectories::SwingbyLegMga Class Reference
Swingby Leg class of an MGA trajectory model.
#include <swingbyLegMga.h>
Public Member Functions
SwingbyLegMga (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, double swingbyBodyGravitationalParameter, std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr, const double minimumPericenterRadius)
Constructor with immediate definition of parameters.
~SwingbyLegMga ()
void calculateLeg (Eigen::Vector3d &velocityBeforeArrivalBody, double &deltaV)
Calculate the leg.
void intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, const double startingTime=0.)
Calculate intermediate positions and their corresponding times.
void maneuvers (std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, std::vector< double > &deltaVVector, const double startingTime=0.)
Return maneuvres along the leg.
void updateDefiningVariables (const Eigen::VectorXd &variableVector)
Update the defining variables.
Public Member Functions inherited from tudat::transfer_trajectories::SpaceLeg
SpaceLeg (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~SpaceLeg ()
void updateEphemeris (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const Eigen::Vector3d &departureBodyVelocity)
Update the ephemeris.
Public Member Functions inherited from tudat::transfer_trajectories::MissionLeg
MissionLeg (const Eigen::Vector3d &departureBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~MissionLeg ()
virtual destructor.
void returnDepartureVariables (Eigen::Vector3d &departureBodyPosition, Eigen::Vector3d &departureBodyVelocity, Eigen::Vector3d &velocityAfterDeparture)
Return Departure Variables.
Private Attributes
double minimumPericenterRadius_
The minimum pericenter radius.
Additional Inherited Members
Protected Member Functions inherited from tudat::transfer_trajectories::SwingbyLeg
SwingbyLeg (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, double swingbyBodyGravitationalParameter, std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr)
Constructor with immediate definition of parameters.
virtual ~SwingbyLeg ()
Protected Attributes inherited from tudat::transfer_trajectories::SwingbyLeg
double swingbyBodyGravitationalParameter_
The swing-by body gravitational parameter.
std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr_
The velocity of the spacecraft at departure.
Protected Attributes inherited from tudat::transfer_trajectories::SpaceLeg
Eigen::Vector3d arrivalBodyPosition_
The arrival body position.
Protected Attributes inherited from tudat::transfer_trajectories::MissionLeg
double centralBodyGravitationalParameter_
The central body gravitational parameter.
double deltaV_
The total deltaV of the leg.
Eigen::Vector3d departureBodyPosition_
The departure body position.
Eigen::Vector3d departureBodyVelocity_
The departure body velocity.
double timeOfFlight_
The time of flight.
Eigen::Vector3d velocityAfterDeparture_
The velocity after departure.
Detailed Description
A class that calculates the required impulses for a swingby leg for an MGA trajectory model. It extends the swingby leg base class and uses a lambert targeter for finding the required departure and arrival velocities of the spacecraft.
Definition at line 37 of file swingbyLegMga.h.
Constructor & Destructor Documentation
SwingbyLegMga()
tudat::transfer_trajectories::SwingbyLegMga::SwingbyLegMga (const Eigen::Vector3d & departureBodyPosition, const Eigen::Vector3d & arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d & departureBodyVelocity, const double centralBodyGravitationalParameter, double swingbyBodyGravitationalParameter, std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr, const double minimumPericenterRadius) inline
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
Parameters
departureBodyPosition location of the departure body.
arrivalBodyPosition position of the target body.
timeOfFlight Length of the leg.
departureBodyVelocity velocity of the departure body.
centralBodyGravitationalParameter gravitational parameter of the cebtral body (most cases the Sun).
swingbyBodyGravitationalParameter gravitational parameter of the swing-by body.
velocityBeforeDepartureBodyPtr pointer to the velocity before the swing-by.
minimumPericenterRadius the minimum pericenter radius for the swing-by body.
Definition at line 54 of file swingbyLegMga.h.
References TUDAT_NAN, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
~SwingbyLegMga()
tudat::transfer_trajectories::SwingbyLegMga::~SwingbyLegMga () inline
Definition at line 75 of file swingbyLegMga.h.
Member Function Documentation
calculateLeg()
void tudat::transfer_trajectories::SwingbyLegMga::calculateLeg (Eigen::Vector3d & velocityBeforeArrivalBody, double & deltaV) virtual
Calculate the leg and update the Delta V and the velocity before the next body.
Performs all calculations required for this leg.
Parameters
velocityBeforeArrivalBody the velocity of the spacecraft before it arrives at the target body.
deltaV the delta V required to perform the leg.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 16 of file swingbyLegMga.cpp.
References tudat::transfer_trajectories::SpaceLeg::arrivalBodyPosition_, tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::deltaV_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, tudat::transfer_trajectories::MissionLeg::departureBodyVelocity_, tudat::mission_segments::gravityAssist(), minimumPericenterRadius_, tudat::mission_segments::solveLambertProblemIzzo(), tudat::transfer_trajectories::SwingbyLeg::swingbyBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::timeOfFlight_, tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_, and tudat::transfer_trajectories::SwingbyLeg::velocityBeforeDepartureBodyPtr_.
Referenced by intermediatePoints(), and maneuvers().
intermediatePoints()
void tudat::transfer_trajectories::SwingbyLegMga::intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, const double startingTime = 0.) virtual
Calculates intermediate positions and their corresponding times in the leg, based on a maximum time between two points.
Parameters
maximumTimeStep the maximum time between two points along the trajectory.
positionVector Vector of positions along the orbit, space according to the maximum time step.
timeVector The times corresponding to the positions.
startingTime the initial time from which the intermediate points are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 40 of file swingbyLegMga.cpp.
References calculateLeg(), tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, tudat::transfer_trajectories::returnTrajectory(), tudat::transfer_trajectories::MissionLeg::timeOfFlight_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
maneuvers()
void tudat::transfer_trajectories::SwingbyLegMga::maneuvers (std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, std::vector< double > & deltaVVector, const double startingTime = 0.) virtual
Returns the maneuver points, times and sizes along the trajectory.
Parameters
positionVector Vector of the positions of the maneuvers.
timeVector The times corresponding to the positions.
deltaVVector the delta V required for each maneuver.
startingTime the initial time from which the maneuvers are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 66 of file swingbyLegMga.cpp.
References calculateLeg(), tudat::transfer_trajectories::MissionLeg::deltaV_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
updateDefiningVariables()
void tudat::transfer_trajectories::SwingbyLegMga::updateDefiningVariables (const Eigen::VectorXd & variableVector) virtual
Sets the trajectory defining variables to the newly specified values. Required for re-using the class, without re-initializing it. For this leg: time of flight.
Parameters
variableVector the new variable vector.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 93 of file swingbyLegMga.cpp.
References tudat::transfer_trajectories::MissionLeg::timeOfFlight_.
Member Data Documentation
minimumPericenterRadius_
double tudat::transfer_trajectories::SwingbyLegMga::minimumPericenterRadius_ private
The minimum allowable pericenter radius for the swing-by.
Definition at line 129 of file swingbyLegMga.h.
Referenced by calculateLeg().
The documentation for this class was generated from the following files:
Astrodynamics/TrajectoryDesign/swingbyLegMga.h
Astrodynamics/TrajectoryDesign/swingbyLegMga.cpp