Tudat: tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType > Class Template Reference
tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType > Class Template Reference
Class that computes the current rotational state from tabulated values of the rotational state with the use of an interpolator.
#include <tabulatedRotationalEphemeris.h>
Public Types
typedef Eigen::Matrix< StateScalarType, 4, 1 > OrientationType
typedef Eigen::Matrix< StateScalarType, 7, 1 > StateType
Public Member Functions
TabulatedRotationalEphemeris (const std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > interpolator, const std::string &baseFrameOrientation="ECLIPJ2000", const std::string &targetFrameOrientation="")
Constructor, sets rotational state interpolator and frame data.
~TabulatedRotationalEphemeris ()
Destructor.
Eigen::Matrix3d getDerivativeOfRotationToBaseFrame (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to base frame.
Eigen::Matrix3d getDerivativeOfRotationToTargetFrame (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from base frame to target frame.
std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > getInterpolator ()
Function to retrieve the rotational state interpolator.
Eigen::Vector3d getRotationalVelocityVectorInBaseFrame (const double secondsSinceEpoch)
Function to retrieve the angular velocity vector of the body, expressed in the base frame.
Eigen::Vector3d getRotationalVelocityVectorInTargetFrame (const double secondsSinceEpoch)
Function to retrieve the angular velocity vector of the body, expressed in the target (body-fixed) frame.
Eigen::Quaterniond getRotationToBaseFrame (const double secondsSinceEpoch)
Get rotation quaternion from target frame to base frame.
Eigen::Quaterniond getRotationToTargetFrame (const double secondsSinceEpoch)
Get rotation quaternion from base frame to target frame.
void reset (const std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > interpolator)
Function to reset the rotational state interpolator.
Public Member Functions inherited from tudat::ephemerides::RotationalEphemeris
RotationalEphemeris (const std::string &baseFrameOrientation="", const std::string &targetFrameOrientation="")
Constructor.
virtual ~RotationalEphemeris ()
Virtual destructor.
std::string getBaseFrameOrientation ()
Get base reference frame orientation.
virtual Eigen::Matrix3d getDerivativeOfRotationToBaseFrameFromExtendedTime (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame in Time precision.
template<>
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const double timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame.
template<>
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame.
template<typename TimeType >
Eigen::Matrix3d getDerivativeOfRotationToBaseFrameTemplated (const TimeType timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from target frame to original frame in templated precision.
virtual Eigen::Matrix3d getDerivativeOfRotationToTargetFrameFromExtendedTime (const Time timeSinceEpoch)
Function to calculate the derivative of the rotation matrix from original frame to target frame in Time precision.
template<>
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const double secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix to target frame from original frame.
template<>
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const Time secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix to target frame from original frame.
template<typename TimeType >
Eigen::Matrix3d getDerivativeOfRotationToTargetFrameTemplated (const TimeType secondsSinceEpoch)
Function to calculate the derivative of the rotation matrix from original frame to target frame in templated precision.
virtual void getFullRotationalQuantitiesToTargetFrame (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const double secondsSinceEpoch)
Function to calculate the full rotational state at given time.
virtual void getFullRotationalQuantitiesToTargetFrameFromExtendedTime (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const Time timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<>
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const double timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<>
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const Time timeSinceEpoch)
Function to calculate the full rotational state at given time.
template<typename TimeType >
void getFullRotationalQuantitiesToTargetFrameTemplated (Eigen::Quaterniond &currentRotationToLocalFrame, Eigen::Matrix3d &currentRotationToLocalFrameDerivative, Eigen::Vector3d &currentAngularVelocityVectorInGlobalFrame, const TimeType timeSinceEpoch)
Function to calculate the full rotational state at given time.
virtual Eigen::Quaterniond getRotationToBaseFrameFromExtendedTime (const Time timeSinceEpoch)
Get rotation quaternion from target frame to base frame in Time precision.
template<>
Eigen::Quaterniond getRotationToBaseFrameTemplated (const double timeSinceEpoch)
Get rotation quaternion from target frame to base frame.
template<>
Eigen::Quaterniond getRotationToBaseFrameTemplated (const Time timeSinceEpoch)
Get rotation quaternion from target frame to base frame.
template<typename TimeType >
Eigen::Quaterniond getRotationToBaseFrameTemplated (const TimeType timeSinceEpoch)
Get rotation quaternion from target frame to base frame in templated precision.
virtual Eigen::Quaterniond getRotationToTargetFrameFromExtendedTime (const Time timeSinceEpoch)
Get rotation quaternion to target frame from base frame in Time precision.
template<>
Eigen::Quaterniond getRotationToTargetFrameTemplated (const double secondsSinceEpoch)
Get rotation quaternion to target frame from base frame.
template<>
Eigen::Quaterniond getRotationToTargetFrameTemplated (const Time secondsSinceEpoch)
Get rotation quaternion to target frame from base frame.
template<typename TimeType >
Eigen::Quaterniond getRotationToTargetFrameTemplated (const TimeType secondsSinceEpoch)
Get rotation quaternion to target frame from base frame in templated precision.
std::string getTargetFrameOrientation ()
Get target reference frame orientation.
Private Member Functions
void updateInterpolator (const double time)
Function to retrieve the current rotational state from the interpolator.
Private Attributes
StateType currentRotationalState_
Vector retrieved from interpolator_ on last call to updateInterpolator.
Eigen::Matrix< StateScalarType, 3, 1 > currentRotationalVelocityVectorInTargetFrame_
Angular velocity vector of body in body-fixed frame obtained at last call to updateInterpolator.
Eigen::Quaternion< StateScalarType > currentRotationToBaseFrame_
Rotation from body-fixed frame to base frame obtained at last call to updateInterpolator.
double currentTime_
Last time at which the updateInterpolator function was called.
std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > interpolator_
Interpolator that returns the interpolated rotational state as a function of time.
Additional Inherited Members
Protected Attributes inherited from tudat::ephemerides::RotationalEphemeris
const std::string baseFrameOrientation_
Base reference frame orientation.
const std::string targetFrameOrientation_
Target reference frame orientation.
Detailed Description
template<typename StateScalarType, typename TimeType>
class tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >
Class that computes the current rotational state from tabulated values of the rotational state with the use of an interpolator The interpolated data consists of the four entries (w,x,y,z) of the quaternion from the target frame to the base frame, and body's angular velocity vector, expressed in its body-fixed frame (target frame). The quaternion is normalized to 1 before being set as the current rotation. Other properties of the rotation are derived from these two quantities.
Definition at line 43 of file tabulatedRotationalEphemeris.h.
Member Typedef Documentation
StateType
template<typename StateScalarType , typename TimeType > typedef Eigen::Matrix< StateScalarType, 7, 1 > tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::StateType
Definition at line 47 of file tabulatedRotationalEphemeris.h.
OrientationType
template<typename StateScalarType , typename TimeType > typedef Eigen::Matrix< StateScalarType, 4, 1 > tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::OrientationType
Definition at line 48 of file tabulatedRotationalEphemeris.h.
Constructor & Destructor Documentation
TabulatedRotationalEphemeris()
template<typename StateScalarType , typename TimeType > tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::TabulatedRotationalEphemeris (const std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > interpolator, const std::string & baseFrameOrientation = "ECLIPJ2000", const std::string & targetFrameOrientation = "") inline
Constructor, sets rotational state interpolator and frame data.
Parameters
interpolator Interpolator that returns the interpolated rotational state as a function of time. The interpolated data must consist of the four entries (w,x,y,z) of the quaternion from the target frame to the base frame, and body's angular velocity vector, expressed in its body-fixed frame (target frame).The quaternion is normalized to 1 before being set as the current rotation. Other properties of the rotation are derived from these two quantities.
baseFrameOrientation Base frame identifier.
targetFrameOrientation Target frame identifier.
Definition at line 60 of file tabulatedRotationalEphemeris.h.
~TabulatedRotationalEphemeris()
template<typename StateScalarType , typename TimeType > tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::~TabulatedRotationalEphemeris () inline
Definition at line 68 of file tabulatedRotationalEphemeris.h.
Member Function Documentation
reset()
template<typename StateScalarType , typename TimeType > void tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::reset (const std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > interpolator) inline
Function to reset the rotational state interpolator, for instance following an update of the rotational state of the body after a new numerical propagation of rotational equations of motion.
Parameters
interpolator New interpolator that returns the interpolated rotational state as a function of time. The interpolated data must consist of the four entries (w,x,y,z) of the quaternion from the target frame to the base frame, and body's angular velocity vector, expressed in its body-fixed frame (target frame).The quaternion is normalized to 1 before being set as the current rotation. Other properties of the rotation are derived from these two quantities.
Definition at line 79 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::interpolator_.
Referenced by tudat::propagators::resetIntegratedRotationalEphemerisOfBody().
getInterpolator()
template<typename StateScalarType , typename TimeType > std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getInterpolator () inline
Function to retrieve the rotational state interpolator.
Returns
Interpolator that returns the interpolated rotational state as a function of time. The interpolated data must consist of the four entries (w,x,y,z) of the quaternion from the target frame to the base frame, and body's angular velocity vector, expressed in its body-fixed frame (target frame).
Definition at line 91 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::interpolator_.
getRotationToBaseFrame()
template<typename StateScalarType , typename TimeType > Eigen::Quaterniond tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationToBaseFrame (const double secondsSinceEpoch) inline virtual
Function to calculate and return the rotation quaternion from target frame to base frame at specified time.
Parameters
secondsSinceEpoch Seconds since epoch at which rotational ephemeris is to be evaluated.
Returns
Rotation quaternion computed from target frame to base frame
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 102 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationToBaseFrame_, and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationToTargetFrame().
getRotationToTargetFrame()
template<typename StateScalarType , typename TimeType > Eigen::Quaterniond tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationToTargetFrame (const double secondsSinceEpoch) inline virtual
Function to calculate and return the rotation quaternion from base frame to target frame at specified time.
Parameters
secondsSinceEpoch Seconds since epoch at which rotational ephemeris is to be evaluated.
Returns
Rotation quaternion computed from base frame to target frame
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 114 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationToBaseFrame().
getRotationalVelocityVectorInBaseFrame()
template<typename StateScalarType , typename TimeType > Eigen::Vector3d tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationalVelocityVectorInBaseFrame (const double secondsSinceEpoch) inline virtual
Function to retrieve the angular velocity vector of the body, expressed in the base frame.
Parameters
secondsSinceEpoch Seconds since epoch at which rotational ephemeris is to be evaluated.
Returns
Angular velocity vector of body, expressed in base frame.
Reimplemented from tudat::ephemerides::RotationalEphemeris.
Definition at line 125 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationalVelocityVectorInTargetFrame_, tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationToBaseFrame_, and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
getRotationalVelocityVectorInTargetFrame()
template<typename StateScalarType , typename TimeType > Eigen::Vector3d tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationalVelocityVectorInTargetFrame (const double secondsSinceEpoch) inline virtual
Function to retrieve the angular velocity vector of the body, expressed in the target (body-fixed) frame.
Parameters
secondsSinceEpoch Seconds since epoch at which rotational ephemeris is to be evaluated.
Returns
Angular velocity vector of body, expressed in target (body-fixed) frame.
Reimplemented from tudat::ephemerides::RotationalEphemeris.
Definition at line 138 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationalVelocityVectorInTargetFrame_, and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
getDerivativeOfRotationToTargetFrame()
template<typename StateScalarType , typename TimeType > Eigen::Matrix3d tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToTargetFrame (const double secondsSinceEpoch) inline virtual
Function to calculate the derivative of the rotation matrix from base frame to target frame at specified time.
Parameters
secondsSinceEpoch Seconds since epoch at which rotational ephemeris is to be evaluated.
Returns
Derivative of rotation from base to target (body-fixed) frame at specified time.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 151 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationalVelocityVectorInTargetFrame_, tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationToBaseFrame_, tudat::ephemerides::getDerivativeOfRotationMatrixToFrame(), and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToBaseFrame().
getDerivativeOfRotationToBaseFrame()
template<typename StateScalarType , typename TimeType > Eigen::Matrix3d tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToBaseFrame (const double secondsSinceEpoch) inline virtual
Function to calculate the derivative of the rotation matrix from target frame to base frame at specified time.
Parameters
secondsSinceEpoch Seconds since epoch at which rotational ephemeris is to be evaluated.
Returns
Derivative of rotation from target (body-fixed) to base frame at specified time.
Implements tudat::ephemerides::RotationalEphemeris.
Definition at line 166 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToTargetFrame(), and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
updateInterpolator()
template<typename StateScalarType , typename TimeType > void tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator (const double time) inline private
Function to retrieve the current rotational state from the interpolator
Parameters
time Time at which to evaluate the interpoaltor
Definition at line 181 of file tabulatedRotationalEphemeris.h.
References tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationalState_, tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationalVelocityVectorInTargetFrame_, tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationToBaseFrame_, tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentTime_, and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::interpolator_.
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToBaseFrame(), tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToTargetFrame(), tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationalVelocityVectorInBaseFrame(), tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationalVelocityVectorInTargetFrame(), and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationToBaseFrame().
Member Data Documentation
interpolator_
template<typename StateScalarType , typename TimeType > std::shared_ptr< interpolators::OneDimensionalInterpolator< TimeType, StateType > > tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::interpolator_ private
Interpolator that returns the interpolated rotational state as a function of time. The interpolated data must consist of the four entries (w,x,y,z) of the quaternion from the target frame to the base frame, and body's angular velocity vector, expressed in its body-fixed frame (target frame).
Definition at line 209 of file tabulatedRotationalEphemeris.h.
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getInterpolator(), tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::reset(), and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
currentTime_
template<typename StateScalarType , typename TimeType > double tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentTime_ private
Definition at line 212 of file tabulatedRotationalEphemeris.h.
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
currentRotationalState_
template<typename StateScalarType , typename TimeType > StateType tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationalState_ private
Definition at line 215 of file tabulatedRotationalEphemeris.h.
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
currentRotationalVelocityVectorInTargetFrame_
template<typename StateScalarType , typename TimeType > Eigen::Matrix< StateScalarType, 3, 1 > tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationalVelocityVectorInTargetFrame_ private
Definition at line 218 of file tabulatedRotationalEphemeris.h.
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToTargetFrame(), tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationalVelocityVectorInBaseFrame(), tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationalVelocityVectorInTargetFrame(), and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
currentRotationToBaseFrame_
template<typename StateScalarType , typename TimeType > Eigen::Quaternion< StateScalarType > tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::currentRotationToBaseFrame_ private
Definition at line 221 of file tabulatedRotationalEphemeris.h.
Referenced by tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getDerivativeOfRotationToTargetFrame(), tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationalVelocityVectorInBaseFrame(), tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::getRotationToBaseFrame(), and tudat::ephemerides::TabulatedRotationalEphemeris< StateScalarType, TimeType >::updateInterpolator().
The documentation for this class was generated from the following file:
Astrodynamics/Ephemerides/tabulatedRotationalEphemeris.h