Tudat: tudat::simulation_setup::TabulatedAtmosphereSettings Class Reference
tudat::simulation_setup::TabulatedAtmosphereSettings Class Reference
AtmosphereSettings for defining an atmosphere with tabulated data from file.
#include <createAtmosphereModel.h>
Public Member Functions
TabulatedAtmosphereSettings (const std::map< int, std::string > &atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > &independentVariablesNames={ altitude_dependent_atmosphere }, const std::vector< AtmosphereDependentVariables > &dependentVariablesNames={ density_dependent_atmosphere, pressure_dependent_atmosphere, temperature_dependent_atmosphere }, const double specificGasConstant=physical_constants::SPECIFIC_GAS_CONSTANT_AIR, const double ratioOfSpecificHeats=1.4, const std::vector< interpolators::BoundaryInterpolationType > &boundaryHandling={ }, const std::vector< std::vector< std::pair< double, double > > > &defaultExtrapolationValue={ })
Default constructor.
TabulatedAtmosphereSettings (const std::map< int, std::string > &atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > &independentVariablesNames, const std::vector< AtmosphereDependentVariables > &dependentVariablesNames, const double specificGasConstant, const double ratioOfSpecificHeats, const interpolators::BoundaryInterpolationType boundaryHandling, const double defaultExtrapolationValue=IdentityElement::getAdditionIdentity< double >())
Constructor with single boundary handling parameters.
TabulatedAtmosphereSettings (const std::string &atmosphereTableFile, const std::vector< AtmosphereDependentVariables > &dependentVariablesNames={ density_dependent_atmosphere, pressure_dependent_atmosphere, temperature_dependent_atmosphere }, const double specificGasConstant=physical_constants::SPECIFIC_GAS_CONSTANT_AIR, const double ratioOfSpecificHeats=1.4, const interpolators::BoundaryInterpolationType boundaryHandling=interpolators::use_boundary_value, const double defaultExtrapolationValue=IdentityElement::getAdditionIdentity< double >())
Constructor compatible with old version.
TabulatedAtmosphereSettings (const std::map< int, std::string > &atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > &independentVariablesNames, const std::vector< AtmosphereDependentVariables > &dependentVariablesNames, const std::vector< interpolators::BoundaryInterpolationType > &boundaryHandling, const std::vector< std::vector< std::pair< double, double > > > &defaultExtrapolationValue={ })
Constructor with no specific gas constant nor ratio of specific heats.
TabulatedAtmosphereSettings (const std::map< int, std::string > &atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > &independentVariablesNames, const std::vector< AtmosphereDependentVariables > &dependentVariablesNames, const std::vector< interpolators::BoundaryInterpolationType > &boundaryHandling, const std::vector< double > &defaultExtrapolationValue)
Constructor with no specific gas constant nor ratio of specific heats.
TabulatedAtmosphereSettings (const std::map< int, std::string > &atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > &independentVariablesNames, const std::vector< AtmosphereDependentVariables > &dependentVariablesNames, const interpolators::BoundaryInterpolationType boundaryHandling, const double defaultExtrapolationValue=IdentityElement::getAdditionIdentity< double >())
Constructor with no specific gas constant nor ratio of specific heats.
std::map< int, std::string > getAtmosphereFile ()
Function to return file containing atmospheric properties.
std::string getAtmosphereFile (const unsigned int fileIndex)
Function to return file containing atmospheric properties.
std::vector< interpolators::BoundaryInterpolationType > getBoundaryHandling ()
Function to return boundary handling method.
std::vector< std::vector< std::pair< double, double > > > getDefaultExtrapolationValue ()
Function to return default extrapolation value.
std::vector< AtmosphereDependentVariables > getDependentVariables ()
Function to return dependent variables names.
std::vector< AtmosphereIndependentVariables > getIndependentVariables ()
Function to return independent variables names.
double getRatioOfSpecificHeats ()
Function to return ratio of specific heats of the atmosphere.
double getSpecificGasConstant ()
Function to return specific gas constant of the atmosphere.
Public Member Functions inherited from tudat::simulation_setup::AtmosphereSettings
AtmosphereSettings (const AtmosphereTypes atmosphereType)
Constructor, sets type of atmosphere model.
virtual ~AtmosphereSettings ()
Destructor.
AtmosphereTypes getAtmosphereType ()
Function to return type of atmosphere model that is to be created.
std::shared_ptr< WindModelSettings > getWindSettings ()
Function to return settings for the atmosphere's wind model.
void setWindSettings (const std::shared_ptr< WindModelSettings > windSettings)
Function to (re)set settings for the atmosphere's wind model.
Private Attributes
std::map< int, std::string > atmosphereFile_
File containing atmospheric properties.
std::vector< interpolators::BoundaryInterpolationType > boundaryHandling_
Behavior of interpolator when independent variable is outside range.
std::vector< std::vector< std::pair< double, double > > > defaultExtrapolationValue_
Default value to be used for extrapolation.
std::vector< AtmosphereDependentVariables > dependentVariables_
A vector of strings containing the names of the variables contained in the atmosphere file.
std::vector< AtmosphereIndependentVariables > independentVariables_
A vector of strings containing the names of the independent variables contained in the atmosphere file.
double ratioOfSpecificHeats_
Ratio of specific heats of the atmosphere at constant pressure and constant volume.
double specificGasConstant_
Specific gas constant of the atmosphere.
Detailed Description
Definition at line 493 of file createAtmosphereModel.h.
Constructor & Destructor Documentation
TabulatedAtmosphereSettings() [1/6]
tudat::simulation_setup::TabulatedAtmosphereSettings::TabulatedAtmosphereSettings (const std::map< int, std::string > & atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > & independentVariablesNames = { altitude_dependent_atmosphere }, const std::vector< AtmosphereDependentVariables > & dependentVariablesNames = { density_dependent_atmosphere, pressure_dependent_atmosphere, temperature_dependent_atmosphere }, const double specificGasConstant = physical_constants::SPECIFIC_GAS_CONSTANT_AIR, const double ratioOfSpecificHeats = 1.4, const std::vector< interpolators::BoundaryInterpolationType > & boundaryHandling = { }, const std::vector< std::vector< std::pair< double, double > > > & defaultExtrapolationValue = { }) inline
Default constructor.
Parameters
atmosphereTableFile Map of files containing information on the atmosphere. The order of both independent and dependent parameters needs to be specified in the independentVariablesNames and dependentVariablesNames vectors, respectively. Note that specific gas constant and specific heat ratio will be given the default constant values for Earth, unless they are included in the file map.
independentVariablesNames List of independent parameters describing the atmosphere.
dependentVariablesNames List of dependent parameters output by the atmosphere.
specificGasConstant The constant specific gas constant of the atmosphere.
ratioOfSpecificHeats The constant ratio of specific heats of the atmosphere.
boundaryHandling List of methods for interpolation behavior when independent variable is out of range.
defaultExtrapolationValue List of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 512 of file createAtmosphereModel.h.
References tudat::aerodynamics::altitude_dependent_atmosphere.
TabulatedAtmosphereSettings() [2/6]
tudat::simulation_setup::TabulatedAtmosphereSettings::TabulatedAtmosphereSettings (const std::map< int, std::string > & atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > & independentVariablesNames, const std::vector< AtmosphereDependentVariables > & dependentVariablesNames, const double specificGasConstant, const double ratioOfSpecificHeats, const interpolators::BoundaryInterpolationType boundaryHandling, const double defaultExtrapolationValue = IdentityElement::getAdditionIdentity< double >()) inline
Constructor with single boundary handling parameters. The specifier is assumed to be the same for each (in)dependent variable.
Parameters
atmosphereTableFile Map of files containing information on the atmosphere. The order of both independent and dependent parameters needs to be specified in the independentVariablesNames and dependentVariablesNames vectors, respectively. Note that specific gas constant and specific heat ratio will be given the default constant values for Earth, unless they are included in the file map.
independentVariablesNames List of independent parameters describing the atmosphere.
dependentVariablesNames List of dependent parameters output by the atmosphere.
specificGasConstant The constant specific gas constant of the atmosphere.
ratioOfSpecificHeats The constant ratio of specific heats of the atmosphere.
boundaryHandling Method for interpolation behavior when independent variable is out of range.
defaultExtrapolationValue Default value to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 543 of file createAtmosphereModel.h.
TabulatedAtmosphereSettings() [3/6]
tudat::simulation_setup::TabulatedAtmosphereSettings::TabulatedAtmosphereSettings (const std::string & atmosphereTableFile, const std::vector< AtmosphereDependentVariables > & dependentVariablesNames = { density_dependent_atmosphere, pressure_dependent_atmosphere, temperature_dependent_atmosphere }, const double specificGasConstant = physical_constants::SPECIFIC_GAS_CONSTANT_AIR, const double ratioOfSpecificHeats = 1.4, const interpolators::BoundaryInterpolationType boundaryHandling = interpolators::use_boundary_value, const double defaultExtrapolationValue = IdentityElement::getAdditionIdentity< double >()) inline
Constructor compatible with old version.
Parameters
atmosphereTableFile File containing atmospheric properties. The file name of the atmosphere table. The file should contain four columns of data, containing altitude (first column), and the associated density, pressure and density values in the second, third and fourth columns.
dependentVariablesNames List of dependent parameters output by the atmosphere.
specificGasConstant The constant specific gas constant of the atmosphere.
ratioOfSpecificHeats The constant ratio of specific heats of the atmosphere.
boundaryHandling Method for interpolation behavior when independent variable is out of range.
defaultExtrapolationValue Default value to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 573 of file createAtmosphereModel.h.
References tudat::aerodynamics::density_dependent_atmosphere, tudat::aerodynamics::pressure_dependent_atmosphere, and tudat::aerodynamics::temperature_dependent_atmosphere.
TabulatedAtmosphereSettings() [4/6]
tudat::simulation_setup::TabulatedAtmosphereSettings::TabulatedAtmosphereSettings (const std::map< int, std::string > & atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > & independentVariablesNames, const std::vector< AtmosphereDependentVariables > & dependentVariablesNames, const std::vector< interpolators::BoundaryInterpolationType > & boundaryHandling, const std::vector< std::vector< std::pair< double, double > > > & defaultExtrapolationValue = { }) inline
Constructor with no specific gas constant nor ratio of specific heats.
Parameters
atmosphereTableFile Map of files containing information on the atmosphere. The order of both independent and dependent parameters needs to be specified in the independentVariablesNames and dependentVariablesNames vectors, respectively. Note that specific gas constant and specific heat ratio will be given the default constant values for Earth, unless they are included in the file map.
independentVariablesNames List of independent parameters describing the atmosphere.
dependentVariablesNames List of dependent parameters output by the atmosphere.
boundaryHandling List of methods for interpolation behavior when independent variable is out of range.
defaultExtrapolationValue List of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 602 of file createAtmosphereModel.h.
TabulatedAtmosphereSettings() [5/6]
tudat::simulation_setup::TabulatedAtmosphereSettings::TabulatedAtmosphereSettings (const std::map< int, std::string > & atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > & independentVariablesNames, const std::vector< AtmosphereDependentVariables > & dependentVariablesNames, const std::vector< interpolators::BoundaryInterpolationType > & boundaryHandling, const std::vector< double > & defaultExtrapolationValue) inline
Constructor with no specific gas constant nor ratio of specific heats. These two values will be given the default Earth value, or are specified inside the atmosphere table file (and thus, inside the dependent variables vector).
Parameters
atmosphereTableFile Map of files containing information on the atmosphere. The order of both independent and dependent parameters needs to be specified in the independentVariablesNames and dependentVariablesNames vectors, respectively. Note that specific gas constant and specific heat ratio will be given the default constant values for Earth, unless they are included in the file map.
independentVariablesNames List of independent parameters describing the atmosphere.
dependentVariablesNames List of dependent parameters output by the atmosphere.
boundaryHandling List of methods for interpolation behavior when independent variable is out of range.
defaultExtrapolationValue List of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 629 of file createAtmosphereModel.h.
References tudat::interpolators::use_default_value, and tudat::interpolators::use_default_value_with_warning.
TabulatedAtmosphereSettings() [6/6]
tudat::simulation_setup::TabulatedAtmosphereSettings::TabulatedAtmosphereSettings (const std::map< int, std::string > & atmosphereTableFile, const std::vector< AtmosphereIndependentVariables > & independentVariablesNames, const std::vector< AtmosphereDependentVariables > & dependentVariablesNames, const interpolators::BoundaryInterpolationType boundaryHandling, const double defaultExtrapolationValue = IdentityElement::getAdditionIdentity< double >()) inline
Constructor with no specific gas constant nor ratio of specific heats, and with single boundary handling parameters.
These two values will be given the default Earth value, or are specified inside the atmosphere table file (and thus, inside the dependent variables vector). Only one boundary handling parameter is specified, which is then repeated for dimension.
Parameters
atmosphereTableFile Map of files containing information on the atmosphere. The order of both independent and dependent parameters needs to be specified in the independentVariablesNames and dependentVariablesNames vectors, respectively. Note that specific gas constant and specific heat ratio will be given the default constant values for Earth, unless they are included in the file map.
independentVariablesNames List of independent parameters describing the atmosphere.
dependentVariablesNames List of dependent parameters output by the atmosphere.
boundaryHandling Method for interpolation behavior when independent variable is out of range.
defaultExtrapolationValue Default value to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 677 of file createAtmosphereModel.h.
Member Function Documentation
getAtmosphereFile() [1/2]
std::map< int, std::string > tudat::simulation_setup::TabulatedAtmosphereSettings::getAtmosphereFile () inline
Function to return file containing atmospheric properties.
Returns
Map of filenames containing atmospheric properties.
Definition at line 697 of file createAtmosphereModel.h.
getAtmosphereFile() [2/2]
std::string tudat::simulation_setup::TabulatedAtmosphereSettings::getAtmosphereFile (const unsigned int fileIndex) inline
Function to return file containing atmospheric properties.
Returns
Filename containing atmospheric properties.
Definition at line 704 of file createAtmosphereModel.h.
getIndependentVariables()
std::vector< AtmosphereIndependentVariables > tudat::simulation_setup::TabulatedAtmosphereSettings::getIndependentVariables () inline
Function to return independent variables names.
Returns
Independent variables.
Definition at line 714 of file createAtmosphereModel.h.
Referenced by tudat::simulation_setup::from_json().
getDependentVariables()
std::vector< AtmosphereDependentVariables > tudat::simulation_setup::TabulatedAtmosphereSettings::getDependentVariables () inline
Function to return dependent variables names.
Returns
Dependent variables.
Definition at line 721 of file createAtmosphereModel.h.
Referenced by tudat::simulation_setup::from_json().
getSpecificGasConstant()
double tudat::simulation_setup::TabulatedAtmosphereSettings::getSpecificGasConstant () inline
Function to return specific gas constant of the atmosphere.
Returns
Specific gas constant of the atmosphere.
Definition at line 728 of file createAtmosphereModel.h.
Referenced by tudat::simulation_setup::from_json().
getRatioOfSpecificHeats()
double tudat::simulation_setup::TabulatedAtmosphereSettings::getRatioOfSpecificHeats () inline
Function to return ratio of specific heats of the atmosphere.
Returns
Ratio of specific heats of the atmosphere at constant pressure and constant volume.
Definition at line 735 of file createAtmosphereModel.h.
Referenced by tudat::simulation_setup::from_json().
getBoundaryHandling()
std::vector< interpolators::BoundaryInterpolationType > tudat::simulation_setup::TabulatedAtmosphereSettings::getBoundaryHandling () inline
Function to return boundary handling method.
Returns
Boundary handling method for when independent variables are outside specified range.
Definition at line 742 of file createAtmosphereModel.h.
Referenced by tudat::simulation_setup::from_json().
getDefaultExtrapolationValue()
std::vector< std::vector< std::pair< double, double > > > tudat::simulation_setup::TabulatedAtmosphereSettings::getDefaultExtrapolationValue () inline
Function to return boundary handling method.
Returns
Boundary handling method for when independent variables are outside specified range.
Definition at line 749 of file createAtmosphereModel.h.
Member Data Documentation
atmosphereFile_
std::map< int, std::string > tudat::simulation_setup::TabulatedAtmosphereSettings::atmosphereFile_ private
File containing atmospheric properties, file should contain columns of atmospheric data with at least density, pressure and temperature, (whose order is specified in dependentVariables), and with at least one indendent variables.
Definition at line 760 of file createAtmosphereModel.h.
independentVariables_
std::vector< AtmosphereIndependentVariables > tudat::simulation_setup::TabulatedAtmosphereSettings::independentVariables_ private
A vector of strings containing the names of the independent variables contained in the atmosphere file, in the correct order (from left, being the first entry in the vector, to the right).
Definition at line 767 of file createAtmosphereModel.h.
dependentVariables_
std::vector< AtmosphereDependentVariables > tudat::simulation_setup::TabulatedAtmosphereSettings::dependentVariables_ private
A vector of strings containing the names of the variables contained in the atmosphere file, in the correct order (from left, being the first entry in the vector, to the right).
Definition at line 774 of file createAtmosphereModel.h.
specificGasConstant_
double tudat::simulation_setup::TabulatedAtmosphereSettings::specificGasConstant_ private
Specific gas constant of the atmosphere.
Definition at line 780 of file createAtmosphereModel.h.
ratioOfSpecificHeats_
double tudat::simulation_setup::TabulatedAtmosphereSettings::ratioOfSpecificHeats_ private
Ratio of specific heats of the atmosphere at constant pressure and constant volume.
Definition at line 786 of file createAtmosphereModel.h.
boundaryHandling_
std::vector< interpolators::BoundaryInterpolationType > tudat::simulation_setup::TabulatedAtmosphereSettings::boundaryHandling_ private
Behavior of interpolator when independent variable is outside range.
Definition at line 792 of file createAtmosphereModel.h.
defaultExtrapolationValue_
std::vector< std::vector< std::pair< double, double > > > tudat::simulation_setup::TabulatedAtmosphereSettings::defaultExtrapolationValue_ private
Default value to be used for extrapolation.
Definition at line 798 of file createAtmosphereModel.h.
The documentation for this class was generated from the following file:
SimulationSetup/EnvironmentSetup/createAtmosphereModel.h