Tudat: tudat::earth_orientation Namespace Reference
tudat::earth_orientation Namespace Reference
Classes
struct CurrentTimes
Data structure to save the current time in several time scales (TAI, TT, TDB, UTC, UT1)
class EarthOrientationAnglesCalculator
Class to calculate earth orientation angles, i.e. those used for transforming from ITRS to GCRS.
class EOPReader
Class used to read Earth Orientation Parameters (EOP) from file.
class PolarMotionCalculator
Object to compute polar motion variables x_{p} and y_{p}.
class PrecessionNutationCalculator
Function to compute precession/nutation angles,.
class ShortPeriodEarthOrientationCorrectionCalculator
Object to calculate the short period variations in Earth orientaion parameters.
class TerrestrialTimeScaleConverter
Class used to convert between terrestrial time scales TAI, TT, TDB, UTC ans UT1.
Functions
Eigen::Quaterniond calculateRotationFromCirsToGcrs (const double celestialPoleXPosition, const double celestialPoleYPosition, const double cioLocator)
Function to calculate rotation from CIRS to GCRS, i.e. applying CIO-based rotations due to nutation and precession.
template<typename TimeType >
Eigen::Quaterniond calculateRotationFromItrsToGcrs (const double celestialPoleXPosition, const double celestialPoleYPosition, const double cioLocator, const TimeType ut1, const double xPolePosition, const double yPolePosition, const double tioLocator)
Calculate rotation from ITRS to GCRS.
template<typename TimeType >
Eigen::Quaterniond calculateRotationFromItrsToGcrs (const Eigen::Vector5d &rotationAngles, const TimeType ut1, const double secondsSinceJ2000)
Calculate rotation from ITRS to GCRS.
template<typename TimeType >
Eigen::Quaterniond calculateRotationFromItrsToGcrs (const std::pair< Eigen::Vector5d, TimeType > rotationAnglesAndUt1, const double secondsSinceJ2000)
Eigen::Quaterniond calculateRotationFromItrsToTirs (const double xPolePosition, const double yPolePosition, const double tioLocator)
Calculate rotation from ITRS to TIRS.
Eigen::Quaterniond calculateRotationFromTirsToCirs (const double earthRotationAngle)
Calculate rotation from TIRS to CIRS.
template<typename TimeType >
Eigen::Matrix3d calculateRotationRateFromItrsToGcrs (const double celestialPoleXPosition, const double celestialPoleYPosition, const double cioLocator, const TimeType ut1, const double xPolePosition, const double yPolePosition, const double tioLocator)
Calculate time-derivative of rotation matrix from ITRS to GCRS.
template<typename TimeType >
Eigen::Matrix3d calculateRotationRateFromItrsToGcrs (const Eigen::Vector5d &rotationAngles, const TimeType ut1, const double secondsSinceJ2000)
Calculate time-derivative of rotation matrix from ITRS to GCRS.
template<typename TimeType >
Eigen::Matrix3d calculateRotationRateFromItrsToGcrs (const std::pair< Eigen::Vector5d, TimeType > rotationAnglesAndUt1, const double secondsSinceJ2000)
std::shared_ptr< TerrestrialTimeScaleConverter > createDefaultTimeConverter (const std::shared_ptr< EOPReader > eopReader)
Function to create the default Earth time scales conversion object.
template<typename UT1ScalarType >
std::pair< std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< double, 5, 1 > > >, std::shared_ptr< interpolators::OneDimensionalInterpolator< double, UT1ScalarType > > > createInterpolatorsForItrsToGcrsAngles (const double intervalStart, const double intervalEnd, const double timeStep, const basic_astrodynamics::TimeScales timeScale=basic_astrodynamics::tdb_scale, const std::shared_ptr< EarthOrientationAnglesCalculator > earthOrientationCalculator=createStandardEarthOrientationCalculator(), const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings=std::make_shared< interpolators::LagrangeInterpolatorSettings >(6))
Function to create an interpolator for the Earth orientation angles and UT1.
std::shared_ptr< EarthOrientationAnglesCalculator > createStandardEarthOrientationCalculator (const std::shared_ptr< EOPReader > eopReader)
Function to create an EarthOrientationAnglesCalculator object, with default settings.
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > filterRawDataForAmplitudes (const Eigen::MatrixXd rawAmplitudes, const Eigen::MatrixXd rawFundamentalArgumentMultipliers, const double minimumAmplitude)
Function to filter tidal corrections based on RSS amplitude criteria.
double getApproximateTioLocator (const double secondsSinceJ2000)
Function to get the value of the TIO locator, approximated as described in IERS 2010 conventions.
std::shared_ptr< ShortPeriodEarthOrientationCorrectionCalculator< Eigen::Vector2d > > getDefaultPolarMotionCorrectionCalculator (const double minimumAmplitude)
Function to retrieve the default polar motion short-period correction calculator.
std::shared_ptr< ShortPeriodEarthOrientationCorrectionCalculator< double > > getDefaultUT1CorrectionCalculator (const double minimumAmplitude)
Function to retrieve the default UT1 short-period correction calculator.
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > readAmplitudesAndFundamentalArgumentMultipliers (const std::string amplitudesFile, const std::string fundamentalArgumentMultipliersFile, const double minimumAmplitude)
Function to read the amplitudes and fundamental argument multiplers for tidal corrections.
Function Documentation
getApproximateTioLocator()
double tudat::earth_orientation::getApproximateTioLocator (const double secondsSinceJ2000)
Function to get the value of the TIO locator, approximated as described in IERS 2010 conventions, Eq. (5.13), evaluated using iauSp00 SOFA function.
Parameters
secondsSinceJ2000 Time at which TIO locator is to be computed. Formally, input should be in TT, but may be provided in any common time scale, as variations in TIO are slow.
Returns
Value of TIO locator
Definition at line 22 of file earthOrientationCalculator.cpp.
References tudat::physical_constants::JULIAN_DAY, and tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000.
Referenced by calculateRotationFromItrsToGcrs(), and calculateRotationRateFromItrsToGcrs().
calculateRotationFromCirsToGcrs()
Eigen::Quaterniond tudat::earth_orientation::calculateRotationFromCirsToGcrs (const double celestialPoleXPosition, const double celestialPoleYPosition, const double cioLocator)
Function to calculate rotation from CIRS to GCRS, i.e. applying CIO-based rotations due to nutation and precession, as described by IERS Conventions, Eq. (5.10)
Parameters
celestialPoleXPosition Parameter X in IERS Conventions 2010, Section 5.4.4
celestialPoleYPosition Parameter X in IERS Conventions 2010, Section 5.4.4
cioLocator Celestial intermediate origin locator; parameter s in IERS Conventions 2010, Section 5.4.4
Returns
Rotation from CIRS to GCRS
Definition at line 28 of file earthOrientationCalculator.cpp.
Referenced by calculateRotationFromItrsToGcrs(), and calculateRotationRateFromItrsToGcrs().
calculateRotationFromTirsToCirs()
Eigen::Quaterniond tudat::earth_orientation::calculateRotationFromTirsToCirs (const double earthRotationAngle)
Calculate rotation from TIRS to CIRS, i.e. rotating over earth rotation angle. Implementes Eq. (5.5) of IERS 2010 Conventions
Parameters
earthRotationAngle Current Earth Rotation angle
Returns
Rotation from TIRS to CIRS
Definition at line 47 of file earthOrientationCalculator.cpp.
Referenced by calculateRotationFromItrsToGcrs(), and calculateRotationRateFromItrsToGcrs().
calculateRotationFromItrsToTirs()
Eigen::Quaterniond tudat::earth_orientation::calculateRotationFromItrsToTirs (const double xPolePosition, const double yPolePosition, const double tioLocator)
Calculate rotation from ITRS to TIRS,.
Calculate rotation from ITRS to TIRS, according to Eq. (5.3) of IERS 2010 Conventions. Applies the effect of polar motion.
Parameters
xPolePosition Polar motion parameter in x-direction (typically denoted x_{p})
yPolePosition Polar motion parameter in y-direction (typically denoted x_{p})
tioLocator TIO locator.
Returns
Rotation from ITRS to TIRS
Definition at line 53 of file earthOrientationCalculator.cpp.
Referenced by calculateRotationFromItrsToGcrs(), and calculateRotationRateFromItrsToGcrs().
createStandardEarthOrientationCalculator()
std::shared_ptr< EarthOrientationAnglesCalculator > tudat::earth_orientation::createStandardEarthOrientationCalculator (const std::shared_ptr< EOPReader > eopReader = std::make_shared< EOPReader >())
Function to create an EarthOrientationAnglesCalculator object, with default settings: IAU 2006 theory for precession/nutation, all (sub-)diurnal corrections to UTC-UT1 and polar motion according to IERS 2010, polar motion/nutation/UT1 daily corrections published by IERS (linearly interpolated in time)
Returns
Default Earth rotation parameter object.
Definition at line 62 of file earthOrientationCalculator.cpp.
References createDefaultTimeConverter(), getDefaultPolarMotionCorrectionCalculator(), and tudat::basic_astrodynamics::iau_2006.
calculateRotationRateFromItrsToGcrs() [1/3]
template<typename TimeType > Eigen::Matrix3d tudat::earth_orientation::calculateRotationRateFromItrsToGcrs (const double celestialPoleXPosition, const double celestialPoleYPosition, const double cioLocator, const TimeType ut1, const double xPolePosition, const double yPolePosition, const double tioLocator)
Calculate time-derivative of rotation matrix from ITRS to GCRS. Function approximates derivative by only including derivative of Earth rotation sub-matrix
Parameters
celestialPoleXPosition Parameter X in IERS Conventions 2010, Section 5.4.4
celestialPoleYPosition Parameter X in IERS Conventions 2010, Section 5.4.4
cioLocator Celestial intermediate origin locator; parameter s in IERS Conventions 2010, Section 5.4.4
ut1 Current UT1 time, used to compute Earth Rotation angle
xPolePosition Polar motion parameter in x-direction (typically denoted x_{p})
yPolePosition Polar motion parameter in y-direction (typically denoted x_{p})
tioLocator TIO locator.
Returns
Time-derivative of rotation matrix from ITRS to GCRS
Definition at line 87 of file earthOrientationCalculator.h.
References calculateRotationFromCirsToGcrs(), calculateRotationFromItrsToTirs(), calculateRotationFromTirsToCirs(), tudat::mathematical_constants::PI, and tudat::reference_frames::Z_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER.
Referenced by calculateRotationRateFromItrsToGcrs().
calculateRotationRateFromItrsToGcrs() [2/3]
template<typename TimeType > Eigen::Matrix3d tudat::earth_orientation::calculateRotationRateFromItrsToGcrs (const Eigen::Vector5d & rotationAngles, const TimeType ut1, const double secondsSinceJ2000)
Calculate time-derivative of rotation matrix from ITRS to GCRS. Function approximates derivative by only including derivative of Earth rotation sub-matrix
Parameters
rotationAngles Vector containing quantities (in IERS Conventions 2010 notation): X, Y, s, xp, yp.
ut1 Current UT1 time, used to compute Earth Rotation angle
secondsSinceJ2000 Current time in seconds since J2000, used for computing TIO locator.
Returns
Time-derivative of rotation matrix from ITRS to GCRS
Definition at line 111 of file earthOrientationCalculator.h.
References calculateRotationRateFromItrsToGcrs(), and getApproximateTioLocator().
calculateRotationRateFromItrsToGcrs() [3/3]
template<typename TimeType > Eigen::Matrix3d tudat::earth_orientation::calculateRotationRateFromItrsToGcrs (const std::pair< Eigen::Vector5d, TimeType > rotationAnglesAndUt1, const double secondsSinceJ2000)
Definition at line 121 of file earthOrientationCalculator.h.
References calculateRotationRateFromItrsToGcrs(), and getApproximateTioLocator().
calculateRotationFromItrsToGcrs() [1/3]
template<typename TimeType > Eigen::Quaterniond tudat::earth_orientation::calculateRotationFromItrsToGcrs (const double celestialPoleXPosition, const double celestialPoleYPosition, const double cioLocator, const TimeType ut1, const double xPolePosition, const double yPolePosition, const double tioLocator)
Calculate rotation from ITRS to GCRS.
Parameters
celestialPoleXPosition Parameter X in IERS Conventions 2010, Section 5.4.4
celestialPoleYPosition Parameter X in IERS Conventions 2010, Section 5.4.4
cioLocator Celestial intermediate origin locator; parameter s in IERS Conventions 2010, Section 5.4.4
ut1 Current UT1 time, used to compute Earth Rotation angle
xPolePosition Polar motion parameter in x-direction (typically denoted x_{p})
yPolePosition Polar motion parameter in y-direction (typically denoted x_{p})
tioLocator TIO locator.
Returns
Rotation from ITRS to GCRS
Definition at line 143 of file earthOrientationCalculator.h.
References calculateRotationFromCirsToGcrs(), calculateRotationFromItrsToTirs(), and calculateRotationFromTirsToCirs().
Referenced by calculateRotationFromItrsToGcrs().
calculateRotationFromItrsToGcrs() [2/3]
template<typename TimeType > Eigen::Quaterniond tudat::earth_orientation::calculateRotationFromItrsToGcrs (const Eigen::Vector5d & rotationAngles, const TimeType ut1, const double secondsSinceJ2000)
Calculate rotation from ITRS to GCRS. Function approximates derivative by only including derivative of Earth rotation sub-matrix
Parameters
rotationAngles Vector containing quantities (in IERS Conventions 2010 notation): X, Y, s, xp, yp.
ut1 Current UT1 time, used to compute Earth Rotation angle
secondsSinceJ2000 Current time in seconds since J2000, used for computing TIO locator.
Returns
Rotation from ITRS to GCRS
Definition at line 164 of file earthOrientationCalculator.h.
References calculateRotationFromItrsToGcrs(), and getApproximateTioLocator().
calculateRotationFromItrsToGcrs() [3/3]
template<typename TimeType > Eigen::Quaterniond tudat::earth_orientation::calculateRotationFromItrsToGcrs (const std::pair< Eigen::Vector5d, TimeType > rotationAnglesAndUt1, const double secondsSinceJ2000)
Definition at line 174 of file earthOrientationCalculator.h.
References calculateRotationFromItrsToGcrs(), and getApproximateTioLocator().
createInterpolatorsForItrsToGcrsAngles()
template<typename UT1ScalarType > std::pair< std::shared_ptr< interpolators::OneDimensionalInterpolator< double, Eigen::Matrix< double, 5, 1 > > >,std::shared_ptr< interpolators::OneDimensionalInterpolator< double, UT1ScalarType > > > tudat::earth_orientation::createInterpolatorsForItrsToGcrsAngles (const double intervalStart, const double intervalEnd, const double timeStep, const basic_astrodynamics::TimeScales timeScale = basic_astrodynamics::tdb_scale, const std::shared_ptr< EarthOrientationAnglesCalculator > earthOrientationCalculator = createStandardEarthOrientationCalculator(), const std::shared_ptr< interpolators::InterpolatorSettings > interpolatorSettings = std::make_shared< interpolators::LagrangeInterpolatorSettings >(6))
Function to create an interpolator for the Earth orientation angles and UT1, to reduce computation time of Earth rotation during orbit propagation/estimation
Parameters
intervalStart Start of time interval where interpolation data is to be generated
intervalEnd End of time interval where interpolation data is to be generated
timeStep Time step between evaluations of rotation data
timeScale Time scale for evaluation data
earthOrientationCalculator Object from which Earth orientation data is to be retrieved
interpolatorSettings Settings for the interpolation proces (default Lagrange 6 point)
Returns
Interpolators for the Earth orientation angles (first) and for UT1 (second). Interpolated angle vector contains quantities (in IERS Conventions 2010 notation): X, Y, s, xp, yp.
Definition at line 317 of file earthOrientationCalculator.h.
References tudat::interpolators::createOneDimensionalInterpolator().
readAmplitudesAndFundamentalArgumentMultipliers()
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > tudat::earth_orientation::readAmplitudesAndFundamentalArgumentMultipliers (const std::string amplitudesFile, const std::string fundamentalArgumentMultipliersFile, const double minimumAmplitude = 0.0)
Function to read the amplitudes and fundamental argument multipliers for tidal corrections.
Function to read the amplitudes and fundamental argument multipliers for tidal corrections to earth orientation etc. Two file names are required, one containing the fundamental argument multipliers (one set per row) and one file containing the amplitudes (number of entries dependent on correction that is calculated). Function can filter amplitudes, so that only those entries with an RSS higher than a certain value are included in the return type.
Parameters
amplitudesFile File name of file containing correction amplitudes.
fundamentalArgumentMultipliersFile File name of file containing fundamental argument multipliers for corrections.
minimumAmplitude Minimum value of RSS of amplitudes for single entry for which entry is accepted.
Returns
Pair of Matrices with 1: fundamental argument multipliers and 2: Amplitudes. A single entry is stored on a single row with same index for fundamental argument multipliers and amplitude.
Definition at line 24 of file readAmplitudeAndArgumentMultipliers.cpp.
References filterRawDataForAmplitudes(), and tudat::input_output::readMatrixFromFile().
Referenced by tudat::earth_orientation::ShortPeriodEarthOrientationCorrectionCalculator< OutputType >::ShortPeriodEarthOrientationCorrectionCalculator().
filterRawDataForAmplitudes()
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > tudat::earth_orientation::filterRawDataForAmplitudes (const Eigen::MatrixXd rawAmplitudes, const Eigen::MatrixXd rawFundamentalArgumentMultipliers, const double minimumAmplitude)
Function to filter tidal corrections based on RSS amplitude criteria. Only those entries with an RSS higher than a provided value are returned.
Parameters
rawAmplitudes Matrix of amplitudes, one correction set per row.
rawFundamentalArgumentMultipliers Matrix of fundamental argument multipliers, one correction set per row.
minimumAmplitude Minimum value of RSS of amplitudes for single entry for which entry is accepted.
Returns
Pair of Matrices with 1: fundamental argument multipliers and 2: Amplitudes for which RSS amplitude is sufficient. A single entry is stored on a single row with same index for fundamental argument multipliers and amplitude.
Definition at line 69 of file readAmplitudeAndArgumentMultipliers.cpp.
Referenced by readAmplitudesAndFundamentalArgumentMultipliers().
getDefaultUT1CorrectionCalculator()
std::shared_ptr< ShortPeriodEarthOrientationCorrectionCalculator< double > > tudat::earth_orientation::getDefaultUT1CorrectionCalculator (const double minimumAmplitude = 0.0)
Function to retrieve the default UT1 short-period correction calculator, from Tables 5.1, 8.2 and 8.2. of IERS 2010 Conventions. An amplitude cutoff may be provided.
Parameters
minimumAmplitude Variation amplitude below which corrections are not taken into account.
Returns
Default UT1 short-period correction calculator
Definition at line 85 of file shortPeriodEarthOrientationCorrectionCalculator.cpp.
References tudat::sofa_interface::calculateApproximateDelaunayFundamentalArgumentsWithGmst(), and tudat::input_output::getEarthOrientationDataFilesPath().
Referenced by createDefaultTimeConverter().
getDefaultPolarMotionCorrectionCalculator()
std::shared_ptr< ShortPeriodEarthOrientationCorrectionCalculator< Eigen::Vector2d > > tudat::earth_orientation::getDefaultPolarMotionCorrectionCalculator (const double minimumAmplitude = 0.0)
Function to retrieve the default polar motion short-period correction calculator, from Tables 5.1, 8.2 and 8.2. of IERS 2010 Conventions. An amplitude cutoff may be provided.
Parameters
minimumAmplitude Variation amplitude below which corrections are not taken into account.
Returns
Default polar motion short-period correction calculator
Definition at line 100 of file shortPeriodEarthOrientationCorrectionCalculator.cpp.
References tudat::sofa_interface::calculateApproximateDelaunayFundamentalArgumentsWithGmst(), and tudat::input_output::getEarthOrientationDataFilesPath().
Referenced by createStandardEarthOrientationCalculator().
createDefaultTimeConverter()
std::shared_ptr< TerrestrialTimeScaleConverter > tudat::earth_orientation::createDefaultTimeConverter (const std::shared_ptr< EOPReader > eopReader = std::make_shared< EOPReader >())
Function to create the default Earth time scales conversion object. All (sub-)diurnal corrections to UTC-UT1 according to IERS 2010, and UT1 daily corrections published by IERS (read from input EOPReader).
Parameters
eopReader Object that reads an Earth Orientation Parameters file.
Returns
Default Earth time scales conversion object
Definition at line 67 of file terrestrialTimeScaleConverter.cpp.
References getDefaultUT1CorrectionCalculator().
Referenced by createStandardEarthOrientationCalculator().