Tudat: tudat::input_output::solar_activity Namespace Reference
tudat::input_output::solar_activity Namespace Reference
Classes
class ExtractSolarActivityData
Solar activity extractor class.
class ParseSolarActivityData
Solar activity parser class.
struct SolarActivityData
Solar activity data class.
Typedefs
typedef std::map< double, SolarActivityDataPtr > SolarActivityDataMap
Data map of SolarActivityData structure Pointers.
typedef std::shared_ptr< SolarActivityData > SolarActivityDataPtr
Pointer to a SolarActivityData structure.
Functions
std::ostream & operator<< (std::ostream &stream, SolarActivityData &solarActivityData)
Overload ostream to print class information.
SolarActivityDataMap readSolarActivityData (std::string filePath)
This function reads a SpaceWeather data file and returns a map with SolarActivityData.
Typedef Documentation
SolarActivityDataPtr
typedef std::shared_ptr< SolarActivityData > tudat::input_output::solar_activity::SolarActivityDataPtr
Definition at line 164 of file solarActivityData.h.
SolarActivityDataMap
typedef std::map< double , SolarActivityDataPtr > tudat::input_output::solar_activity::SolarActivityDataMap
Definition at line 167 of file solarActivityData.h.
Function Documentation
operator<<()
std::ostream& tudat::input_output::solar_activity::operator<< (std::ostream & stream, SolarActivityData & solarActivityData)
Overloaded ostream to print class information.
Overloaded ostream to print class information; prints all converted Solar Activity variables listed in the http://celestrak.com/SpaceData/sw19571001.txt file.
Definition at line 49 of file solarActivityData.cpp.
References tudat::input_output::solar_activity::SolarActivityData::bartelsSolarRotationNumber, tudat::input_output::solar_activity::SolarActivityData::centered81DaySolarRadioFlux107Adjusted, tudat::input_output::solar_activity::SolarActivityData::centered81DaySolarRadioFlux107Observed, tudat::input_output::solar_activity::SolarActivityData::dataType, tudat::input_output::solar_activity::SolarActivityData::day, tudat::input_output::solar_activity::SolarActivityData::dayOfBartelsCycle, tudat::input_output::solar_activity::SolarActivityData::fluxQualifier, tudat::input_output::solar_activity::SolarActivityData::internationalSunspotNumber, tudat::input_output::solar_activity::SolarActivityData::last81DaySolarRadioFlux107Adjusted, tudat::input_output::solar_activity::SolarActivityData::last81DaySolarRadioFlux107Observed, tudat::input_output::solar_activity::SolarActivityData::month, tudat::input_output::solar_activity::SolarActivityData::planetaryDailyCharacterFigure, tudat::input_output::solar_activity::SolarActivityData::planetaryDailyCharacterFigureConverted, tudat::input_output::solar_activity::SolarActivityData::planetaryEquivalentAmplitudeAverage, tudat::input_output::solar_activity::SolarActivityData::planetaryEquivalentAmplitudeVector, tudat::input_output::solar_activity::SolarActivityData::planetaryRangeIndexSum, tudat::input_output::solar_activity::SolarActivityData::planetaryRangeIndexVector, tudat::input_output::solar_activity::SolarActivityData::solarRadioFlux107Adjusted, tudat::input_output::solar_activity::SolarActivityData::solarRadioFlux107Observed, and tudat::input_output::solar_activity::SolarActivityData::year.
readSolarActivityData()
SolarActivityDataMap tudat::input_output::solar_activity::readSolarActivityData (std::string filePath)
Function that reads a SpaceWeather data file.
This function reads a SpaceWeather data file and returns a map with SolarActivityData
Parameters
filePath std::string
Returns
solarActivityDataMap std::map< double , SolarActivityDataPtr >
Definition at line 95 of file solarActivityData.cpp.
References tudat::basic_astrodynamics::convertCalendarDateToJulianDay(), tudat::input_output::field_types::time::day, tudat::input_output::solar_activity::ExtractSolarActivityData::extract(), tudat::input_output::field_types::time::month, tudat::input_output::TextParser::parse(), TUDAT_NAN, and tudat::input_output::field_types::time::year.
Referenced by tudat::simulation_setup::createAtmosphereModel().