Tudat: tudat::transfer_trajectories Namespace Reference
tudat::transfer_trajectories Namespace Reference
Classes
class CaptureLeg
Capture leg class.
class DepartureLeg
Departure Leg base class.
class DepartureLegMga
Departure Leg class of an MGA trajectory model.
class DepartureLegMga1DsmPosition
Departure Leg class of an MGA-1DSM position formulation trajectory model.
class DepartureLegMga1DsmVelocity
Departure Leg class of an MGA-1DSM velocity formulation trajectory model.
class MissionLeg
Mission Leg base class.
class SpaceLeg
Space Leg base class.
class SwingbyLeg
Swingby Leg base class.
class SwingbyLegMga
Swingby Leg class of an MGA trajectory model.
class SwingbyLegMga1DsmPosition
Swingby Leg class of an MGA-1DSM position formulation trajectory model.
class SwingbyLegMga1DsmVelocity
Swingby Leg class of an MGA-1DSM velocity formulation trajectory model.
class Trajectory
Base class for computation of trajectories.
Enumerations
enum legTypes {
mga_Departure = 1, mga_Swingby, mga1DsmPosition_Departure, mga1DsmPosition_Swingby,
mga1DsmVelocity_Departure, mga1DsmVelocity_Swingby, capture
}
Functions
void returnCircularTrajectory (double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, double semiMajorAxis, double centralGravitationalParamater, double startingTime)
Return a vector of positions and times corresponding to a 2D circular trajectory.
void returnPlanetTrajectory (const ephemerides::EphemerisPointer &ephemerisPtr, const double centralBodyGravitationalParameter, const double startingEpochMJD2000, const double duration, const double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, const double startingTime)
Return a vector of positions and times from ephemeris data for a certain epoch and duration.
void returnPlanetTrajectory (const ephemerides::EphemerisPointer &ephemerisPtr, const double duration, const double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, const double startingTime)
Return a vector of positions and times from ephemeris data for a certain epoch and duration.
void returnSingleRevolutionPlanetTrajectory (const ephemerides::EphemerisPointer &ephemerisPtr, const double centralBodyGravitationalParameter, const double startingEpochMJD2000, const double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, const double startingTime=0.)
Return a propagated vector of positions and times from ephemeris data for one revolution.
void returnTrajectory (Eigen::VectorXd initialCartesianState, double centralBodyGravitationalParameter, double duration, double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, double startingTime)
Return a vector of positions and times corresponding to a trajectory at a certain epoch.
void writeManeuversToFile (std::vector< Eigen::Vector3d > positionVector, std::vector< double > timeVector, std::vector< double > deltaVVector, const char *fileName)
Write a trajectory to a data file.
void writeTrajectoryToFile (std::vector< Eigen::Vector3d > positionVector, std::vector< double > timeVector, const std::string fileName)
Write a trajectory to a data file.
Enumeration Type Documentation
legTypes
enum tudat::transfer_trajectories::legTypes
Enumerator
mga_Departure
mga_Swingby
mga1DsmPosition_Departure
mga1DsmPosition_Swingby
mga1DsmVelocity_Departure
mga1DsmVelocity_Swingby
capture
Definition at line 53 of file trajectory.h.
Function Documentation
returnTrajectory()
void tudat::transfer_trajectories::returnTrajectory (Eigen::VectorXd initialCartesianState, double centralBodyGravitationalParameter, double duration, double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, double startingTime = 0.)
returns the trajectory of the spacecraft.
Parameters
initialCartesianState initial cartesian state of the spacecraft.
centralBodyGravitationalParameter central body gravitational paremeter.
duration duration of the exported trajectory
maximumTimeStep maximum time step between the positions that are returned
positionVector vector of positions along the trajectory.
timeVector vector of times corresponding to the positions.
startingTime initial time of the trajectory.
Definition at line 19 of file exportTrajectory.cpp.
References tudat::json_interface::cartesianElements, tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::json_interface::keplerianElements, and tudat::orbital_element_conversions::propagateKeplerOrbit().
Referenced by tudat::transfer_trajectories::SwingbyLegMga::intermediatePoints(), tudat::transfer_trajectories::DepartureLegMga::intermediatePoints(), tudat::transfer_trajectories::CaptureLeg::intermediatePoints(), tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::intermediatePoints(), tudat::transfer_trajectories::SwingbyLegMga1DsmPosition::intermediatePoints(), tudat::transfer_trajectories::DepartureLegMga1DsmPosition::intermediatePoints(), tudat::transfer_trajectories::DepartureLegMga1DsmVelocity::intermediatePoints(), and returnSingleRevolutionPlanetTrajectory().
returnCircularTrajectory()
void tudat::transfer_trajectories::returnCircularTrajectory (double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, double semiMajorAxis, double centralGravitationalParamater, double startingTime = 0.)
Return a vector of positions and times corresponding to a 2D circular trajectory.
Parameters
maximumTimeStep maximum time step between the positions that are returned.
positionVector vector of positions along the trajectory.
timeVector vector of times corresponding to the positions.
semiMajorAxis semi-major axis of the circular orbit.
centralGravitationalParamater central body gravitational paremeter.
startingTime initial time of the circular trajectory.
Definition at line 75 of file exportTrajectory.cpp.
References tudat::input_output::field_types::state::meanMotion, tudat::input_output::field_types::state::orbitalPeriod, tudat::mathematical_constants::PI, and tudat::input_output::field_types::state::semiMajorAxis.
writeTrajectoryToFile()
void tudat::transfer_trajectories::writeTrajectoryToFile (std::vector< Eigen::Vector3d > positionVector, std::vector< double > timeVector, const std::string fileName)
Write a trajectory to a data file.
Parameters
positionVector vector of positions along the trajectory.
timeVector vector of times corresponding to the positions.
fileName name of the exported file
Definition at line 105 of file exportTrajectory.cpp.
writeManeuversToFile()
void tudat::transfer_trajectories::writeManeuversToFile (std::vector< Eigen::Vector3d > positionVector, std::vector< double > timeVector, std::vector< double > deltaVVector, const char * fileName)
Write a trajectory to a data file.
Parameters
positionVector vector of positions of the manuevers
timeVector vector of times corresponding to the positions.
deltaVVector vector of delta V's of the maneuvers.
fileName name of the exported file.
Definition at line 120 of file exportTrajectory.cpp.
returnPlanetTrajectory() [1/2]
void tudat::transfer_trajectories::returnPlanetTrajectory (const ephemerides::EphemerisPointer & ephemerisPtr, const double centralBodyGravitationalParameter, const double startingEpochMJD2000, const double duration, const double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, const double startingTime)
Definition at line 21 of file planetTrajectory.cpp.
References tudat::physical_constants::JULIAN_DAY.
returnSingleRevolutionPlanetTrajectory()
void tudat::transfer_trajectories::returnSingleRevolutionPlanetTrajectory (const ephemerides::EphemerisPointer & ephemerisPtr, const double centralBodyGravitationalParameter, const double startingEpochMJD2000, const double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, const double startingTime = 0.)
Return a propagated vector of positions and times from ephemeris data for one revolution.
Parameters
ephemerisPtr pointer to the ephemeris of the planet.
centralBodyGravitationalParameter central body gravitational parameter.
startingEpochMJD2000 starting epoch in MJD2000.
maximumTimeStep maximum time between points along the trajectory.
positionVector vector of positions along the trajectory.
timeVector times corresponding to the positions.
startingTime initial time of the trajectory.
Definition at line 72 of file planetTrajectory.cpp.
References tudat::basic_astrodynamics::convertJulianDayToSecondsSinceEpoch(), tudat::basic_astrodynamics::convertModifiedJulianDayToJulianDay(), tudat::mathematical_constants::PI, and returnTrajectory().
Referenced by tudat::transfer_trajectories::Trajectory::planetaryOrbits().
returnPlanetTrajectory() [2/2]
void tudat::transfer_trajectories::returnPlanetTrajectory (const ephemerides::EphemerisPointer & ephemerisPtr, const double duration, const double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, const double startingTime)
Return a vector of positions and times from ephemeris data for a certain epoch and duration.
Parameters
ephemerisPtr pointer to the ephemeris of the planet.
duration duration for which the planet trajectory is given.
maximumTimeStep maximum time between points along the trajectory.
positionVector vector of positions along the trajectory.
timeVector times corresponding to the positions.
startingTime initial time of the trajectory.