Tudat: tudat::propagators::PropagationTerminationCondition Class Reference
tudat::propagators::PropagationTerminationCondition Class Reference abstract
Base class for checking whether the numerical propagation is to be stopped at current time step or not.
#include <propagationTermination.h>
Public Member Functions
PropagationTerminationCondition ()
Constructor.
virtual ~PropagationTerminationCondition ()
Destructor.
virtual bool checkStopCondition (const double time, const double cpuTime)=0
(Pure virtual) function to check whether the propagation should be stopped
Detailed Description
Base class for checking whether the numerical propagation is to be stopped at current time step or not. Derived classes implement the various types of conditions (and associated threshold values) under which the propagation is to be stopped.
Definition at line 40 of file propagationTermination.h.
Constructor & Destructor Documentation
tudat::propagators::PropagationTerminationCondition::PropagationTerminationCondition () inline
Definition at line 45 of file propagationTermination.h.
virtual tudat::propagators::PropagationTerminationCondition::~PropagationTerminationCondition () inline virtual
Definition at line 48 of file propagationTermination.h.
References checkStopCondition().
Member Function Documentation
virtual bool tudat::propagators::PropagationTerminationCondition::checkStopCondition (const double time, const double cpuTime) pure virtual
(Pure virtual) function to check whether the propagation should be stopped. Note that the accelerations and environment must be updated (done automatically during numerical propagation) to check the stopping condition.
Parameters
time Current time in propagation
cpuTime Current CPU time in propagation
Returns
True if propagation is to be stopped, false otherwise.
Implemented in tudat::propagators::HybridPropagationTerminationCondition, tudat::propagators::SingleVariableLimitPropagationTerminationCondition, tudat::propagators::FixedCPUTimePropagationTerminationCondition, and tudat::propagators::FixedTimePropagationTerminationCondition.
Referenced by tudat::propagators::FixedCPUTimePropagationTerminationCondition::FixedCPUTimePropagationTerminationCondition(), tudat::propagators::FixedTimePropagationTerminationCondition::FixedTimePropagationTerminationCondition(), tudat::propagators::HybridPropagationTerminationCondition::HybridPropagationTerminationCondition(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::SingleArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), tudat::propagators::MultiArcVariationalEquationsSolver< StateScalarType, TimeType >::integrateVariationalAndDynamicalEquations(), ~PropagationTerminationCondition(), and tudat::propagators::SingleVariableLimitPropagationTerminationCondition::~SingleVariableLimitPropagationTerminationCondition().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/propagationTermination.h