Tudat: tudat::input_output::field_types::time Namespace Reference
tudat::input_output::field_types::time Namespace Reference
Variables
static const FieldType day = hash_constructor("Time: Day")
static const FieldType epoch = hash_constructor("Time: Julian_date_epoch[UT1]")
Epoch Julian Date [JD, UT1].
static const FieldType month = hash_constructor("Time: Month")
static const FieldType year = hash_constructor("Time: Year")
Variable Documentation
epoch
const FieldType tudat::input_output::field_types::time::epoch = hash_constructor("Time: Julian_date_epoch[UT1]") static
Definition at line 83 of file fieldType.h.
Referenced by tudat::json_interface::exportResultsOfDynamicsSimulator(), and tudat::json_interface::getCartesianState().
year
const FieldType tudat::input_output::field_types::time::year = hash_constructor("Time: Year") static
Definition at line 98 of file parseSolarActivityData.h.
Referenced by tudat::basic_astrodynamics::convertDayMonthYearToDayOfYear(), tudat::basic_astrodynamics::convertJulianDayToCalendarDate(), tudat::basic_astrodynamics::convertYearAndDaysInYearToDate(), tudat::input_output::solar_activity::ExtractSolarActivityData::extract(), tudat::basic_astrodynamics::getDaysInMonth(), tudat::sofa_interface::getDeltaAtFromTai(), tudat::sofa_interface::getDeltaAtFromUtc(), tudat::basic_astrodynamics::isLeapYear(), tudat::input_output::solar_activity::ParseSolarActivityData::parseStream(), and tudat::input_output::solar_activity::readSolarActivityData().
month
const FieldType tudat::input_output::field_types::time::month = hash_constructor("Time: Month") static
Definition at line 99 of file parseSolarActivityData.h.
Referenced by tudat::basic_astrodynamics::convertDayMonthYearToDayOfYear(), tudat::basic_astrodynamics::convertJulianDayToCalendarDate(), tudat::input_output::solar_activity::ExtractSolarActivityData::extract(), tudat::basic_astrodynamics::getDaysInMonth(), tudat::sofa_interface::getDeltaAtFromTai(), tudat::sofa_interface::getDeltaAtFromUtc(), tudat::input_output::solar_activity::ParseSolarActivityData::parseStream(), and tudat::input_output::solar_activity::readSolarActivityData().
day
const FieldType tudat::input_output::field_types::time::day = hash_constructor("Time: Day") static
Definition at line 100 of file parseSolarActivityData.h.
Referenced by tudat::basic_astrodynamics::convertDayMonthYearToDayOfYear(), tudat::basic_astrodynamics::convertJulianDayToCalendarDate(), tudat::input_output::solar_activity::ExtractSolarActivityData::extract(), tudat::sofa_interface::getDeltaAtFromTai(), tudat::sofa_interface::getDeltaAtFromUtc(), tudat::input_output::solar_activity::ParseSolarActivityData::parseStream(), and tudat::input_output::solar_activity::readSolarActivityData().