Tudat: tudat::basic_mathematics Namespace Reference
tudat::basic_mathematics Namespace Reference
Classes
class BasicFunction
Function with basic implementations for derivatives and integrals.
struct ConvergenceException
Exception indicating that an algorithm could not complete convergence to a solution.
class Function
Function interface to allow evaluation of a mathematical function.
class FunctionProxy
Function interface to allow evaluation of a mathematical function.
class LegendreCache
Class for creating and accessing a back-end cache of Legendre polynomials.
class SphericalHarmonicsCache
Cache object in which variables that are required for the computation of spherical harmonic potential are stored.
Typedefs
typedef boost::shared_ptr< BasicFunction< double, double > > BasicFunctionPointer
typedef boost::shared_ptr< Function< > > FunctionPointer
Typedef for shared-pointer to Function object.
typedef boost::mt19937 GlobalRandomNumberGeneratorType
Random number generator typedef.
typedef FunctionProxy< double, double > UnivariateProxy
typedef UnivariateProxy::FunctionProxyPointer UnivariateProxyPointer
typedef UnivariateProxy::FunctionSignature UnivariateSignature
Enumerations
enum SphericalCoordinatesIndices { radiusIndex, latitudeIndex, longitudeIndex }
Spherical coordinate indices.
Functions
double calculateLegendreGeodesyNormalizationFactor (const int degree, const int order)
Function to calculate the normalization factor for Legendre polynomials to geodesy-normalized.
double computeGeodesyLegendrePolynomial (const int degree, const int order, const double legendreParameter)
Compute geodesy-normalized associated Legendre polynomial.
double computeGeodesyLegendrePolynomialDerivative (const int degree, const int order, const double polynomialParameter, const double currentLegendrePolynomial, const double incrementedLegendrePolynomial, const double normalizationCorrection)
Compute derivative of geodesy-normalized Legendre polynomial.
double computeGeodesyLegendrePolynomialDerivative (const int degree, const int order, const double polynomialParameter, const double currentLegendrePolynomial, const double incrementedLegendrePolynomial)
Compute derivative of geodesy-normalized Legendre polynomial.
double computeGeodesyLegendrePolynomialDiagonal (const int degree, const double degreeOneOrderOnePolynomial, const double priorSectoralPolynomial)
Compute geodesy-normalized Legendre polynomial through sectoral recursion.
double computeGeodesyLegendrePolynomialExplicit (const int degree, const int order, const double polynomialParameter)
Compute low degree/order geodesy-normalized Legendre polynomials explicitly.
double computeGeodesyLegendrePolynomialFromCache (const int degree, const int order, LegendreCache &geodesyLegendreCache)
Compute geodesy-normalized associated Legendre polynomial.
double computeGeodesyLegendrePolynomialSecondDerivative (const int degree, const int order, const double polynomialParameter, const double currentLegendrePolynomial, const double incrementedLegendrePolynomial, const double currentLegendrePolynomialDerivative, const double incrementedLegendrePolynomialDerivative, const double normalizationCorrection)
Compute second derivative of geodesy-normalized associated Legendre polynomial.
double computeGeodesyLegendrePolynomialVertical (const int degree, const int order, const double polynomialParameter, const double oneDegreePriorPolynomial, const double twoDegreesPriorPolynomial)
Compute geodesy-normalized Legendre polynomial through degree recursion.
double computeLegendrePolynomial (const int degree, const int order, const double legendreParameter)
Compute unnormalized associated Legendre polynomial.
double computeLegendrePolynomialDerivative (const int order, const double polynomialParameter, const double currentLegendrePolynomial, const double incrementedLegendrePolynomial)
Compute derivative of unnormalized Legendre polynomial.
double computeLegendrePolynomialDiagonal (const int degree, const double degreeOneOrderOnePolynomial, const double priorSectoralPolynomial)
Compute unnormalized Legendre polynomial through sectoral recursion.
double computeLegendrePolynomialExplicit (const int degree, const int order, const double polynomialParameter)
Compute low degree/order unnormalized Legendre polynomial explicitly.
double computeLegendrePolynomialFromCache (const int degree, const int order, LegendreCache &legendreCache)
Compute unnormalized associated Legendre polynomial.
double computeLegendrePolynomialVertical (const int degree, const int order, const double polynomialParameter, const double oneDegreePriorPolynomial, const double twoDegreesPriorPolynomial)
Compute unnormalized Legendre polynomial through degree recursion.
template<typename ScalarType = double>
ScalarType computeModulo (const ScalarType dividend, const ScalarType divisor)
Compute modulo of floating-point number (default double).
template<typename ScalarType >
void computeModuloAndRemainder (const ScalarType dividend, const ScalarType divisor, ScalarType &moduloValue, int &numberOfDivisors)
Compute modulo of floating-point number (default double).
int computeNearestLeftNeighborUsingBinarySearch (const Eigen::VectorXd &vectorOfSortedData, const double targetValueInVectorOfSortedData)
Nearest left neighbor binary search.
template<typename IndependentVariableType >
int computeNearestLeftNeighborUsingBinarySearch (const std::vector< IndependentVariableType > vectorOfSortedData, const IndependentVariableType targetValueInVectorOfSortedData)
Templated nearest left neighbor binary search.
int computeNearestLeftNeighborUsingBinarySearch (const std::map< double, Eigen::VectorXd > &sortedIndepedentAndDependentVariables, const double targetValueInMapOfData)
Nearest left neighbor binary search.
int computeNearestNeighborUsingBinarySearch (const Eigen::VectorXd &vectorOfSortedData, const double targetValueInVectorOfSortedData)
Nearest neighbor binary search.
Eigen::Vector3d computePotentialGradient (const double distance, const double radiusPowerTerm, const double cosineOfOrderLongitude, const double sineOfOrderLongitude, const double cosineOfLatitude, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative)
Compute the gradient of a single term of a spherical harmonics potential field.
Eigen::Vector3d computePotentialGradient (const Eigen::Vector3d &sphericalPosition, const double referenceRadius, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative)
Compute the gradient of a single term of a spherical harmonics potential field.
Eigen::Vector3d computePotentialGradient (const Eigen::Vector3d &sphericalPosition, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const boost::shared_ptr< SphericalHarmonicsCache > sphericalHarmonicsCache)
Compute the gradient of a single term of a spherical harmonics potential field.
Eigen::Vector3d computeRotationOfPointAboutArbitraryAxis (const Eigen::Vector3d &originOfRotation, const double angleOfRotation, const Eigen::Vector3d &axisOfRotation, const Eigen::Vector3d &initialPositionOfPoint)
Compute rotation of point about arbitrary axis.
Eigen::Vector3d computeRotationOfVectorAboutArbitraryAxis (const Eigen::Vector3d &originOfRotation, const double angleOfRotation, const Eigen::Vector3d &axisOfRotation, const Eigen::Vector3d &initialPositionOfVectorTail, const Eigen::Vector3d &initialVector)
Compute rotation of vector about arbitrary axis.
template<typename IndependentVariableType >
int findNearestLeftNeighbourUsingHuntingAlgorithm (const IndependentVariableType independentVariableValue, const int previousNearestLowerIndex_, const std::vector< IndependentVariableType > &independentValues_)
Nearest left leighbour search using hunting algorithm.
GlobalRandomNumberGeneratorType & getGlobalRandomNumberGenerator ()
Get global random number generator.
template<typename IndependentVariableType >
bool isIndependentVariableInInterval (const int lowerIndex, const IndependentVariableType independentVariableValue, const std::vector< IndependentVariableType > &independentValues)
This function checks whether a value is in a given interval of a sorted vector.
template<typename ScalarType >
ScalarType raiseToIntegerPower (const ScalarType baseValue, const int integerPower)
Raise floating point variable to integer power.
UnivariateProxyPointer univariateProxy (UnivariateSignature function)
Factory for creating a UnivariateProxyPointer from a C++ function UnivariateSignature.
UnivariateProxyPointer univariateProxy (UnivariateSignature function, const int order1, UnivariateSignature function1)
UnivariateProxyPointer univariateProxy (UnivariateSignature function, const int order1, UnivariateSignature function1, const int order2, UnivariateSignature function2)
UnivariateProxyPointer univariateProxy (UnivariateSignature function, const int order1, UnivariateSignature function1, const int order2, UnivariateSignature function2, const int order3, UnivariateSignature function3)
Variables
static const LegendreCache::LegendrePolynomialFunction geodesyNormalizedLegendrePolynomialFunction
Predefine boost function for geodesy-normalized Legendre polynomial.
const LegendreCache::LegendrePolynomialFunction regularLegendrePolynomialFunction
Predefine boost function for unnormalized Legendre polynomial.
Typedef Documentation
typedef boost::shared_ptr< BasicFunction< double, double > > tudat::basic_mathematics::BasicFunctionPointer
Definition at line 138 of file basicFunction.h.
typedef boost::mt19937 tudat::basic_mathematics::GlobalRandomNumberGeneratorType
Random number generator typedef. This can be modified to any other Boost random number generator type (http://www.boost.org/doc/libs/1_47_0/doc/html/boost_random/reference.html).
Definition at line 37 of file basicMathematicsFunctions.h.
typedef boost::shared_ptr< Function< > > tudat::basic_mathematics::FunctionPointer
Typedef for shared-pointer to Function object with IndependentVariable=double, DependentVariable=double.
Definition at line 79 of file function.h.
typedef FunctionProxy< double, double > tudat::basic_mathematics::UnivariateProxy
Definition at line 138 of file functionProxy.h.
typedef UnivariateProxy::FunctionSignature tudat::basic_mathematics::UnivariateSignature
Definition at line 139 of file functionProxy.h.
typedef UnivariateProxy::FunctionProxyPointer tudat::basic_mathematics::UnivariateProxyPointer
Definition at line 140 of file functionProxy.h.
Enumeration Type Documentation
enum tudat::basic_mathematics::SphericalCoordinatesIndices
Enumerator
radiusIndex
latitudeIndex
longitudeIndex
Definition at line 250 of file sphericalHarmonics.h.
Function Documentation
GlobalRandomNumberGeneratorType & tudat::basic_mathematics::getGlobalRandomNumberGenerator ()
Returns global random number generator. The default seed is set to the current time.
Returns
Global random number generator.
Definition at line 23 of file basicMathematicsFunctions.cpp.
template<typename ScalarType = double> ScalarType tudat::basic_mathematics::computeModulo (const ScalarType dividend, const ScalarType divisor)
Computes the remainder of division of one floating-point number by another. The modulo computation is based on the mathematical definition of congruence, which is different from the implementation of std::fmod() in the cmath standard library. For a description of congruence see: http://mathworld.wolfram.com/Congruence.html. The remainder is in the range [ 0, divisor).
Parameters
dividend Number to be divided.
divisor Number that is divided by.
Returns
Remainder of division of dividend by divisor.
Definition at line 58 of file basicMathematicsFunctions.h.
Referenced by tudat::reference_frames::calculateInertialToPlanetFixedRotationAnglesFromMatrix(), tudat::statistics::computeSampleMedian(), tudat::coordinate_conversions::convertCartesianToCylindrical(), tudat::orbital_element_conversions::convertKeplerianToModifiedEquinoctialElements(), tudat::orbital_element_conversions::convertModifiedEquinoctialToKeplerianElements(), tudat::ephemerides::SimpleRotationalEphemeris::getDerivativeOfRotationToTargetFrame(), tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris(), and tudat::ephemerides::SimpleRotationalEphemeris::getRotationToTargetFrame().
template<typename ScalarType > void tudat::basic_mathematics::computeModuloAndRemainder (const ScalarType dividend, const ScalarType divisor, ScalarType & moduloValue, int & numberOfDivisors) inline
Computes the remainder of division of one floating-point number by another. The modulo computation is based on the mathematical definition of congruence, which is different from the implementation of std::fmod() in the cmath standard library. For a description of congruence see: http://mathworld.wolfram.com/Congruence.html. The remainder is in the range [ 0, divisor). This function also returns (by reference) the number of times divisor goes into dividend, i.e. the division from which the moduloValue is the remainder.
Parameters
dividend Number to be divided.
divisor Number that is divided by.
moduloValue Remainder of division of dividend by divisor (returned by reference).
numberOfDivisors Number of times divisor goes into dividend (returned by reference).
Definition at line 77 of file basicMathematicsFunctions.h.
template<typename ScalarType > ScalarType tudat::basic_mathematics::raiseToIntegerPower (const ScalarType baseValue, const int integerPower)
Definition at line 87 of file basicMathematicsFunctions.h.
Referenced by tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateCoefficientPartialWrtRealTidalLoveNumber(), computePotentialGradient(), and tudat::acceleration_partials::computePotentialSphericalHessian().
UnivariateProxyPointer tudat::basic_mathematics::univariateProxy (UnivariateSignature function) inline
Parameters
function C++ function representing the mathematical function.
Definition at line 146 of file functionProxy.h.
UnivariateProxyPointer tudat::basic_mathematics::univariateProxy (UnivariateSignature function, const int order1, UnivariateSignature function1) inline
Factory for creating a UnivaritateProxyPtr from a C++ function UnivariateSignature, with one additional binding.
Parameters
function C++ function representing the mathematical function.
order1 Order of the additional derivative or integral function, i.e. order of function1.
function1 Additional derivative or integral representation to bind.
Definition at line 160 of file functionProxy.h.
UnivariateProxyPointer tudat::basic_mathematics::univariateProxy (UnivariateSignature function, const int order1, UnivariateSignature function1, const int order2, UnivariateSignature function2) inline
Factory for creating a UnivariateProxyPointer from a C++ function UnivariateSignature, with two additional binding.
Parameters
function C++ function representing the mathematical function.
order1 Order of the first additional derivative or integral function, i.e. order of function1.
function1 First additional derivative or integral representation to bind.
order2 Order of the second additional derivative or integral function, i.e. order of function2.
function2 Second additional derivative or integral representation to bind.
Definition at line 184 of file functionProxy.h.
UnivariateProxyPointer tudat::basic_mathematics::univariateProxy (UnivariateSignature function, const int order1, UnivariateSignature function1, const int order2, UnivariateSignature function2, const int order3, UnivariateSignature function3) inline
Factory for creating a UnivariateProxyPointer from a C++ function UnivariateSignature, with three additional binding.
Parameters
function C++ function representing the mathematical function.
order1 Order of the first additional derivative or integral function, i.e. order of function1.
function1 First additional derivative or integral representation to bind.
order2 Order of the second additional derivative or integral function, i.e. order of function2.
function2 Second additional derivative or integral representation to bind.
order3 Order of the third additional derivative or integral function, i.e. order of function3.
function3 Third additional derivative or integral representation to bind.
Definition at line 213 of file functionProxy.h.
double tudat::basic_mathematics::computeLegendrePolynomialFromCache (const int degree, const int order, LegendreCache & legendreCache)
This function returns an unnormalized associated Legendre polynomial with degree , order and polynomial parameter . obeys the definition given by Vallado [2001]:
in which is the ordinary Legendre polynomial with degree , order and polynomial parameter .
For the has been defined here as follows:
This function has been optimized for repeated calls with varying 'degree' and 'order' arguments (but with identical 'polynomialParameter' argument). To this end the function maintains a back-end cache with intermediate results which is automatically carried over between calls.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
legendreCache Legendre cache from which to retrieve Legendre polynomial.
Returns
Unnormalized Legendre polynomial.
Definition at line 310 of file legendrePolynomials.cpp.
References computeLegendrePolynomialDiagonal(), computeLegendrePolynomialExplicit(), computeLegendrePolynomialVertical(), tudat::basic_mathematics::LegendreCache::getCurrentPolynomialParameter(), tudat::basic_mathematics::LegendreCache::getLegendrePolynomial(), and tudat::basic_mathematics::LegendreCache::getUseGeodesyNormalization().
Referenced by computeLegendrePolynomial().
double tudat::basic_mathematics::computeLegendrePolynomial (const int degree, const int order, const double legendreParameter)
This function returns an unnormalized associated Legendre polynomial with degree , order and polynomial parameter . obeys the definition given by Vallado [2001]:
in which is the ordinary Legendre polynomial with degree , order and polynomial parameter .
For the has been defined here as follows:
This function has been optimized for repeated calls with varying 'degree' and 'order' arguments (but with identical 'polynomialParameter' argument). To this end the function maintains a back-end cache with intermediate results which is automatically carried over between calls.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
legendreParameter Free variable of requested Legendre polynomial.
Returns
Unnormalized Legendre polynomial.
Definition at line 382 of file legendrePolynomials.cpp.
References computeLegendrePolynomialFromCache(), and tudat::basic_mathematics::LegendreCache::update().
double tudat::basic_mathematics::computeGeodesyLegendrePolynomialFromCache (const int degree, const int order, LegendreCache & geodesyLegendreCache)
This function returns a normalized associated Legendre polynomial with degree , order and polynomial parameter . The normalization obeys the definition:
in which is the normalization factor which is commonly used in geodesy and is given by Heiskanen & Moritz [1967] as:
in which is the degree, is the order and is the Kronecker delta.
obeys the definition given by Vallado [2001]:
in which is the ordinary Legendre polynomial with degree , order and polynomial parameter .
For the has been defined here as follows:
This function has been optimized for repeated calls with varying 'degree' and 'order' arguments (but with identical 'polynomialParameter' argument). To this end the function maintains a back-end cache with intermediate results which is automatically carried over between calls.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
geodesyLegendreCache Legendre cache from which to retrieve Legendre polynomial.
Returns
Geodesy-normalized Legendre polynomial.
Definition at line 393 of file legendrePolynomials.cpp.
References computeGeodesyLegendrePolynomialDiagonal(), computeGeodesyLegendrePolynomialExplicit(), computeGeodesyLegendrePolynomialVertical(), tudat::basic_mathematics::LegendreCache::getCurrentPolynomialParameter(), tudat::basic_mathematics::LegendreCache::getLegendrePolynomial(), and tudat::basic_mathematics::LegendreCache::getUseGeodesyNormalization().
Referenced by tudat::gravitation::calculateSphericalHarmonicGravitationalPotential(), and computeGeodesyLegendrePolynomial().
double tudat::basic_mathematics::computeGeodesyLegendrePolynomial (const int degree, const int order, const double legendreParameter)
This function returns a normalized associated Legendre polynomial with degree , order and polynomial parameter . The normalization obeys the definition:
in which is the normalization factor which is commonly used in geodesy and is given by Heiskanen & Moritz [1967] as:
in which is the degree, is the order and is the Kronecker delta.
obeys the definition given by Vallado [2001]:
in which is the ordinary Legendre polynomial with degree , order and polynomial parameter .
For the has been defined here as follows:
This function has been optimized for repeated calls with varying 'degree' and 'order' arguments (but with identical 'polynomialParameter' argument). To this end the function maintains a back-end cache with intermediate results which is automatically carried over between calls.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
legendreParameter Free variable of requested Legendre polynomial.
Returns
Geodesy-normalized Legendre polynomial.
Definition at line 466 of file legendrePolynomials.cpp.
References computeGeodesyLegendrePolynomialFromCache(), and tudat::basic_mathematics::LegendreCache::update().
double tudat::basic_mathematics::computeLegendrePolynomialDerivative (const int order, const double polynomialParameter, const double currentLegendrePolynomial, const double incrementedLegendrePolynomial)
The derivative is computed as:
in which is the degree, is the order, is the polynomial parameter, is an associated Legendre polynomial, and is an associated Legendre polynomial.
Parameters
order Order of requested Legendre polynomial derivative.
polynomialParameter Free variable of requested Legendre polynomial derivative.
currentLegendrePolynomial Unnormalized Legendre polynomial with the same degree, order and polynomial parameter as the requested Legendre polynomial derivative.
incrementedLegendrePolynomial Unnormalized Legendre polynomial with the same degree and polynomial parameter as the requested Legendre polynomial derivative, but with an order of one more.
Returns
Unnormalized Legendre polynomial derivative with respect to the polynomial parameter.
Definition at line 476 of file legendrePolynomials.cpp.
Referenced by tudat::basic_mathematics::LegendreCache::update().
double tudat::basic_mathematics::computeGeodesyLegendrePolynomialDerivative (const int degree, const int order, const double polynomialParameter, const double currentLegendrePolynomial, const double incrementedLegendrePolynomial, const double normalizationCorrection)
Compute derivative of geodesy-normalized associated Legendre polynomial.
Compute derivative of geodesy-normalized associated Legendre polynomial.
Parameters
degree Degree of requested Legendre polynomial derivative.
order Order of requested Legendre polynomial derivative.
polynomialParameter Free variable of requested Legendre polynomial derivative.
currentLegendrePolynomial Geodesy-normalized Legendre polynomial with the same degree, order and polynomial parameter as the requested Legendre polynomial derivative.
incrementedLegendrePolynomial Geodesy-normalized Legendre polynomial with the same degree and polynomial parameter as the requested Legendre polynomial derivative, but with an order of one more.
normalizationCorrection Pre-computed scaling term used for part of computations.
Returns
Geodesy-normalized Legendre polynomial derivative with respect to the polynomial parameter.
Definition at line 490 of file legendrePolynomials.cpp.
Referenced by computeGeodesyLegendrePolynomialDerivative(), and tudat::basic_mathematics::LegendreCache::update().
double tudat::basic_mathematics::computeGeodesyLegendrePolynomialDerivative (const int degree, const int order, const double polynomialParameter, const double currentLegendrePolynomial, const double incrementedLegendrePolynomial)
The derivative is computed as:
in which is the degree, is the order, is the polynomial parameter, is the Kronecker delta, is an associated Legendre polynomial, and is an associated Legendre polynomial.
Parameters
degree Degree of requested Legendre polynomial derivative.
order Order of requested Legendre polynomial derivative.
polynomialParameter Free variable of requested Legendre polynomial derivative.
currentLegendrePolynomial Geodesy-normalized Legendre polynomial with the same degree, order and polynomial parameter as the requested Legendre polynomial derivative.
incrementedLegendrePolynomial Geodesy-normalized Legendre polynomial with the same degree and polynomial parameter as the requested Legendre polynomial derivative, but with an order of one more.
Returns
Geodesy-normalized Legendre polynomial derivative with respect to the polynomial parameter.
Definition at line 506 of file legendrePolynomials.cpp.
References computeGeodesyLegendrePolynomialDerivative().
double tudat::basic_mathematics::computeGeodesyLegendrePolynomialSecondDerivative (const int degree, const int order, const double polynomialParameter, const double currentLegendrePolynomial, const double incrementedLegendrePolynomial, const double currentLegendrePolynomialDerivative, const double incrementedLegendrePolynomialDerivative, const double normalizationCorrection)
Compute second derivative of geodesy-normalized associated Legendre polynomial.
Parameters
degree Degree of requested Legendre polynomial derivative.
order Order of requested Legendre polynomial derivative.
polynomialParameter Free variable of requested Legendre polynomial derivative.
currentLegendrePolynomial Geodesy-normalized Legendre polynomial with the same degree, order and polynomial parameter as the requested Legendre polynomial derivative.
incrementedLegendrePolynomial Geodesy-normalized Legendre polynomial with the same degree and polynomial parameter as the requested Legendre polynomial derivative, but with an order of one more.
currentLegendrePolynomialDerivative Geodesy-normalized derivative of Legendre polynomial with the same degree, order and polynomial parameter as the requested Legendre polynomial derivative.
incrementedLegendrePolynomialDerivative Geodesy-normalized derivative of Legendre polynomial with the same degree and polynomial parameter as the requested Legendre polynomial derivative, but with an order of one more.
normalizationCorrection Pre-computed scaling term used for part of computations.
Returns
Geodesy-normalized Legendre polynomial derivative with respect to the polynomial parameter.
Definition at line 530 of file legendrePolynomials.cpp.
Referenced by tudat::basic_mathematics::LegendreCache::update().
double tudat::basic_mathematics::computeLegendrePolynomialExplicit (const int degree, const int order, const double polynomialParameter)
The associated Legendre polynomial with degree , order and polynomial parameter is calculated using explicit formulas given by Eberly [2008]:
Calculation up to and is supported by this function.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
polynomialParameter Free variable of requested Legendre polynomial.
Returns
Unnormalized Legendre polynomial.
Definition at line 552 of file legendrePolynomials.cpp.
References TUDAT_NAN.
Referenced by tudat::orbit_determination::TidalLoveNumberPartialInterface::calculateCoefficientPartialWrtRealTidalLoveNumber(), tudat::gravitation::calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude(), computeLegendrePolynomialFromCache(), and tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::updateTidalAmplitudeAndArgument().
double tudat::basic_mathematics::computeGeodesyLegendrePolynomialExplicit (const int degree, const int order, const double polynomialParameter)
Compute low degree/order geodesy-normalized Legendre polynomial explicitly.
The normalized associated Legendre polynomial with degree , order and polynomial parameter is calculated using explicit formulas:
Calculation up to and is supported by this function.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
polynomialParameter Free variable of requested Legendre polynomial.
Returns
Geodesy-normalized Legendre polynomial.
Definition at line 673 of file legendrePolynomials.cpp.
Referenced by computeGeodesyLegendrePolynomialFromCache().
double tudat::basic_mathematics::computeLegendrePolynomialDiagonal (const int degree, const double degreeOneOrderOnePolynomial, const double priorSectoralPolynomial)
The associated Legendre polynomial with degree , order and polynomial parameter is calculated through degree recursion as given by Vallado [2001]:
Parameters
degree Degree of requested Legendre polynomial.
degreeOneOrderOnePolynomial Unnormalized Legendre polynomial with the same polynomial parameter as the requested Legendre polynomial, but with a degree and order of one.
priorSectoralPolynomial Unnormalized Legendre polynomial with the same polynomial parameter as the requested Legendre polynomial, but with a degree and order of one less.
Returns
Unnormalized Legendre polynomial.
Definition at line 709 of file legendrePolynomials.cpp.
Referenced by computeLegendrePolynomialFromCache().
double tudat::basic_mathematics::computeGeodesyLegendrePolynomialDiagonal (const int degree, const double degreeOneOrderOnePolynomial, const double priorSectoralPolynomial)
The associated Legendre polynomial with degree , order and polynomial parameter is calculated through degree recursion as given by Holmes & Featherstone [2002]:
Parameters
degree Degree of requested Legendre polynomial.
degreeOneOrderOnePolynomial Unnormalized Legendre polynomial with the same polynomial parameter as the requested Legendre polynomial, but with a degree and order of one.
priorSectoralPolynomial Legendre polynomial with the same polynomial parameter as the requested Legendre polynomial, but with a degree and order of one less.
Returns
Geodesy-normalized Legendre polynomial.
Definition at line 720 of file legendrePolynomials.cpp.
Referenced by computeGeodesyLegendrePolynomialFromCache().
double tudat::basic_mathematics::computeLegendrePolynomialVertical (const int degree, const int order, const double polynomialParameter, const double oneDegreePriorPolynomial, const double twoDegreesPriorPolynomial)
The associated Legendre polynomial with degree , order and polynomial parameter is calculated through degree recursion as given by Weisstein [2012]:
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
polynomialParameter Free variable of requested Legendre polynomial.
oneDegreePriorPolynomial Unnormalized Legendre polynomial with the same order and polynomial parameter as the requested Legendre polynomial, but with a degree of one less.
twoDegreesPriorPolynomial Geodesy-normalized Legendre polynomial with the same order and polynomial parameter as the requested Legendre polynomial, but with a degree of two less.
Returns
Unnormalized Legendre polynomial.
Definition at line 731 of file legendrePolynomials.cpp.
Referenced by computeLegendrePolynomialFromCache().
double tudat::basic_mathematics::computeGeodesyLegendrePolynomialVertical (const int degree, const int order, const double polynomialParameter, const double oneDegreePriorPolynomial, const double twoDegreesPriorPolynomial)
The normalized associated Legendre polynomial with degree , order and polynomial parameter is calculated through degree recursion as given by Holmes & Featherstone [2002]:
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
polynomialParameter Free variable of requested Legendre polynomial.
oneDegreePriorPolynomial Geodesy-normalized Legendre polynomial with the same polynomial parameter as the requested Legendre polynomial, but with a degree of one less.
twoDegreesPriorPolynomial Geodesy-normalized Legendre polynomial with the same polynomial parameter as the requested Legendre polynomial, but with a degree of two less.
Returns
Geodesy-normalized Legendre polynomial.
Definition at line 744 of file legendrePolynomials.cpp.
Referenced by computeGeodesyLegendrePolynomialFromCache().
double tudat::basic_mathematics::calculateLegendreGeodesyNormalizationFactor (const int degree, const int order)
Function to calculate the normalization factor K_nm to convert regular Legendre polynomials P_nm to geodesy-normalized Legendre polynomials bar{P}_nm, so that bar{P}_nm=K_nm*P_nm. Note that the same conversion for spherical harmonic coefficients from regular to geodesy- normalized requires the inverse factor: 1/K_nm: C_nm=K_nm* bar{C}_nm.
Parameters
degree Degree of Legendre polynomial
order Order of Legendre polynomial
Returns
Normalization factor K_nm
Definition at line 761 of file legendrePolynomials.cpp.
Referenced by tudat::gravitation::calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude(), and tudat::gravitation::createTriAxialEllipsoidNormalizedSphericalHarmonicCoefficients().
int tudat::basic_mathematics::computeNearestLeftNeighborUsingBinarySearch (const Eigen::VectorXd & vectorOfSortedData, const double targetValueInVectorOfSortedData)
Searches for the nearest left neighbor in a vector of sorted data using a binary algorithm (Press W.H., et al., 2002).
Parameters
vectorOfSortedData Vector of data sorted in ascending/descending order.
targetValueInVectorOfSortedData Target value in vector of sorted data.
Returns
Index of nearest left neighbor to target value.
Definition at line 29 of file nearestNeighbourSearch.cpp.
Referenced by tudat::interpolators::computeLinearInterpolation(), tudat::interpolators::HuntingAlgorithmLookupScheme< IndependentVariableType >::findNearestLowerNeighbour(), and tudat::interpolators::BinarySearchLookupScheme< IndependentVariableType >::findNearestLowerNeighbour().
int tudat::basic_mathematics::computeNearestNeighborUsingBinarySearch (const Eigen::VectorXd & vectorOfSortedData, const double targetValueInVectorOfSortedData)
Searches for the nearest neighbor in a vector of sorted data using a binary algorithm (Press W.H., et al., 2002).
Parameters
vectorOfSortedData Vector of data sorted in ascending/descending order.
targetValueInVectorOfSortedData Target value in vector of sorted data.
Returns
Index of nearest neighbor to target value.
Definition at line 80 of file nearestNeighbourSearch.cpp.
int tudat::basic_mathematics::computeNearestLeftNeighborUsingBinarySearch (const std::map< double, Eigen::VectorXd > & sortedIndepedentAndDependentVariables, const double targetValueInMapOfData)
Searches for the nearest left neighbor in a map of sorted data using a binary algorithm (Press W.H., et al., 2002).
Parameters
sortedIndepedentAndDependentVariables Map of independent and dependent data sorted in ascending/descending order.
targetValueInMapOfData Target value in map of sorted data.
Returns
Index of nearest left neighbor to target value.
Definition at line 141 of file nearestNeighbourSearch.cpp.
template<typename IndependentVariableType > int tudat::basic_mathematics::computeNearestLeftNeighborUsingBinarySearch (const std::vector< IndependentVariableType > vectorOfSortedData, const IndependentVariableType targetValueInVectorOfSortedData)
Templated nearest left neighbor binary search.
Template Parameters
IndependentVariableType Type of independent variables in which search is to be done.
Parameters
vectorOfSortedData STL vector, sorted in ascending order, containing independent variable values.
targetValueInVectorOfSortedData Value of independent variable of which the nearest left neighbour is to be determined.
Definition at line 75 of file nearestNeighbourSearch.h.
template<typename IndependentVariableType > bool tudat::basic_mathematics::isIndependentVariableInInterval (const int lowerIndex, const IndependentVariableType independentVariableValue, const std::vector< IndependentVariableType > & independentValues)
This function checks whether a value is in a given interval of an STL vector, sorted in ascending order of value of the entries. The interval is identified by the lower index of the entries of the vector defining the interval.
Template Parameters
IndependentVariableType Type of the independent variable values.
Parameters
lowerIndex Index of lower bound of interval under consideration.
independentVariableValue Value of which it is to be checked whether it is in the interval.
independentValues Vector of values, srted in ascending order.
Returns
True if value is in interval, false otherwise.
Definition at line 138 of file nearestNeighbourSearch.h.
template<typename IndependentVariableType > int tudat::basic_mathematics::findNearestLeftNeighbourUsingHuntingAlgorithm (const IndependentVariableType independentVariableValue, const int previousNearestLowerIndex_, const std::vector< IndependentVariableType > & independentValues_)
Nearest left leighbour search using hunting algorithm, using an initial guess to decrease the look-up time. Especially useful for long data vectors where the value for which the nearest neighbour is to be found changes slowly w.r.t. the data entries. Implementation is taken from (Press W.H., et al., 2002). Algorithm is at worst twice as slow as binary search and can be orders of magnitude faster in suitable cases.
Template Parameters
IndependentVariableType Type for entries of vector of in which nearest neighbour is sought.
Parameters
independentVariableValue Value of which the nearest left neighbour is to be calculated.
previousNearestLowerIndex_ Initial guess of nearest lft neighbour.
independentValues_ Vector of independent variables, sorted in ascending order, in which the nearest left (lower) neighbour is to be determined.
Returns
Index of independentValues_ that is the nearest left neighbour
Definition at line 170 of file nearestNeighbourSearch.h.
Referenced by tudat::interpolators::HuntingAlgorithmLookupScheme< IndependentVariableType >::findNearestLowerNeighbour().
Eigen::Vector3d tudat::basic_mathematics::computeRotationOfPointAboutArbitraryAxis (const Eigen::Vector3d & originOfRotation, const double angleOfRotation, const Eigen::Vector3d & axisOfRotation, const Eigen::Vector3d & initialPositionOfPoint)
Computes the rotation of a point about an arbitrary axis. This function computes the position of the rotated point by computing the displacement vector between the origin of rotation and the initalPosition of point and then applying a matrix as shown in section 6 of http://inside.mines.edu/~gmurray/ArbitraryAxisRotation/ArbitraryAxisRotation.html. A visualization of the computation being performed can be found at http://twist-and-shout.appspot.com/. Units for originOfRotation, and initialPositionOfPoint must be the same. All positions are assumed to be with respect to a common arbitrary origin. Note that this arbitrary origin is not necessarily the origin of rotation.
Parameters
originOfRotation Position of tail of axis of rotation vector with respect to a chosen arbitrary origin.
angleOfRotation Angle about which the point rotates with respect to the axis of rotation [rad].
axisOfRotation Unit vector pointed in the direction of rotation determined by the right-hand rule.
initialPositionOfPoint Position of point before rotation with respect to the same chosen arbitrary origin.
Returns
Position of point after rotation about the axis of rotation with respect to the same chosen arbitrary origin.
Definition at line 27 of file rotationAboutArbitraryAxis.cpp.
Referenced by computeRotationOfVectorAboutArbitraryAxis().
Eigen::Vector3d tudat::basic_mathematics::computeRotationOfVectorAboutArbitraryAxis (const Eigen::Vector3d & originOfRotation, const double angleOfRotation, const Eigen::Vector3d & axisOfRotation, const Eigen::Vector3d & initialPositionOfVectorTail, const Eigen::Vector3d & initialVector)
Compute rotation of vector about an arbitrary axis.
Computes rotation of vector about an arbitrary axis. This function uses computeRotationOfPointAboutArbitraryAxis to rotate the position of the head and tail of the vector and compute the resultant vector defined as the difference of the two rotated points. Units for originOfRotation, initialPositionOfVectorTail and initialVector must be the same.
Parameters
originOfRotation Position of tail of axis of rotation vector with respect to a chosen arbitrary origin.
angleOfRotation Angle over which the vector is rotated. A positive angle is determined using the right hand rule [rad].
axisOfRotation Unit vector pointing in the direction of rotation determined by the right-hand rule.
initialPositionOfVectorTail Initial position of tail of vector which will be rotated with respect to this same chosen arbitrary origin.
initialVector Vector to be rotated with respect to this same chosen arbitrary origin.
Returns
Vector after rotation about the arbitrary axis with respect to this same chosen arbitrary origin.
See also
computeRotationOfPointAboutArbitraryAxis.
Definition at line 55 of file rotationAboutArbitraryAxis.cpp.
References computeRotationOfPointAboutArbitraryAxis().
Eigen::Vector3d tudat::basic_mathematics::computePotentialGradient (const double distance, const double radiusPowerTerm, const double cosineOfOrderLongitude, const double sineOfOrderLongitude, const double cosineOfLatitude, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative)
This function returns a vector with the derivatives of a generic potential field (defined by spherical harmonics) from pre-computed quatities.
Parameters
distance Distance to center of body with gravity field at which the potential gradient is to be calculated
radiusPowerTerm Distance divided by the reference radius of the gravity field, to the power (degree + 1)
cosineOfOrderLongitude Cosine of order times the longitude at which the potential is to be calculated
sineOfOrderLongitude Sine of order times the longitude at which the potential is to be calculated
cosineOfLatitude Cosine of the latitude at which the potential is to be calculated
preMultiplier Generic multiplication factor.
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
legendrePolynomial Value of associated Legendre polynomial with the same degree and order as the to be computed harmonic, and with the sine of the latitude coordinate as polynomial parameter. Make sure that the Legendre polynomial has the same normalization as the harmonic coefficients.
legendrePolynomialDerivative Value of the derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
Returns
Vector with derivatives of potential field. The order is important! gradient(0) = derivative with respect to radial distance, gradient(1) = derivative with respect to latitude angle, gradient(2) = derivative with respect to longitude angle.
Definition at line 43 of file sphericalHarmonics.cpp.
Referenced by tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtCCoefficients(), tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtSCoefficients(), tudat::gravitation::computeGeodesyNormalizedGravitationalAccelerationSum(), computePotentialGradient(), and tudat::gravitation::computeSingleGeodesyNormalizedGravitationalAcceleration().
Eigen::Vector3d tudat::basic_mathematics::computePotentialGradient (const Eigen::Vector3d & sphericalPosition, const double referenceRadius, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative)
This function returns a vector with the derivatives of a generic potential field (defined by spherical harmonics). *
Parameters
sphericalPosition Vector with spherical coordinates. The order is important! sphericalPosition(0) = radial coordinate, sphericalPosition(1) = latitude coordinate, sphericalPosition(2) = longitude coordinate.
referenceRadius Radius of harmonics reference sphere.
preMultiplier Generic multiplication factor.
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
legendrePolynomial Value of associated Legendre polynomial with the same degree and order as the to be computed harmonic, and with the sine of the latitude coordinate as polynomial parameter. Make sure that the Legendre polynomial has the same normalization as the harmonic coefficients.
legendrePolynomialDerivative Value of the derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
Returns
Vector with derivatives of potential field. The order is important! gradient(0) = derivative with respect to radial distance, gradient(1) = derivative with respect to latitude angle, gradient(2) = derivative with respect to longitude angle.
Definition at line 75 of file sphericalHarmonics.cpp.
References computePotentialGradient(), latitudeIndex, longitudeIndex, radiusIndex, and raiseToIntegerPower().
Eigen::Vector3d tudat::basic_mathematics::computePotentialGradient (const Eigen::Vector3d & sphericalPosition, const double preMultiplier, const int degree, const int order, const double cosineHarmonicCoefficient, const double sineHarmonicCoefficient, const double legendrePolynomial, const double legendrePolynomialDerivative, const boost::shared_ptr< SphericalHarmonicsCache > sphericalHarmonicsCache)
This function returns a vector with the derivatives of a generic potential field (defined by spherical harmonics). It is assumed that the potential field of a single harmonic is characterized by:
in which is the generic multiplication factor, is the radius of the harmonics reference sphere, is the associated Legendre polynomial with as polynomial parameter, is the radial coordinate, is the latitude coordinate, is the longitude coordinate, is the harmonics degree, is the harmonics order, is the cosine harmonics coefficient, and is the sine harmonics coefficient.
The potential derivatives are calculated through:
Parameters
sphericalPosition Vector with spherical coordinates. The order is important! sphericalPosition(0) = radial coordinate, sphericalPosition(1) = latitude coordinate, sphericalPosition(2) = longitude coordinate.
preMultiplier Generic multiplication factor.
degree Degree of the harmonic for which the gradient is to be computed.
order Order of the harmonic for which the gradient is to be computed.
cosineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
sineHarmonicCoefficient Coefficient which characterizes relative strengh of a harmonic term.
legendrePolynomial Value of associated Legendre polynomial with the same degree and order as the to be computed harmonic, and with the sine of the latitude coordinate as polynomial parameter. Make sure that the Legendre polynomial has the same normalization as the harmonic coefficients.
legendrePolynomialDerivative Value of the derivative of parameter 'legendrePolynomial' with respect to the sine of the latitude angle.
sphericalHarmonicsCache Cache object containing current values of trigonometric funtions of latitude anf longitude, as well as legendre polynomials at current state.
Returns
Vector with derivatives of potential field. The order is important! gradient(0) = derivative with respect to radial distance, gradient(1) = derivative with respect to latitude angle, gradient(2) = derivative with respect to longitude angle.
Definition at line 97 of file sphericalHarmonics.cpp.
References computePotentialGradient(), and radiusIndex.
Variable Documentation
const LegendreCache::LegendrePolynomialFunction tudat::basic_mathematics::geodesyNormalizedLegendrePolynomialFunction static
Initial value:
=
        boost::bind( &computeGeodesyLegendrePolynomialFromCache, _1, _2, _3 )
Definition at line 621 of file legendrePolynomials.h.
Referenced by tudat::basic_mathematics::LegendreCache::LegendreCache().
const LegendreCache::LegendrePolynomialFunction tudat::basic_mathematics::regularLegendrePolynomialFunction
Initial value:
=
        boost::bind( &computeLegendrePolynomialFromCache, _1, _2, _3 )
Definition at line 637 of file legendrePolynomials.h.
Referenced by tudat::basic_mathematics::LegendreCache::LegendreCache().