Tudat: tudat::unit_tests Namespace Reference
tudat::unit_tests Namespace Reference
Functions
template<typename TimeType = double, typename StateScalarType = double>
std::pair< Eigen::VectorXd, bool > executeEarthOrbiterBiasEstimation (const bool estimateRangeBiases=true, const bool estimateTwoWayBiases=false, const bool useSingleBiasModel=true, const bool estimateAbsoluteBiases=true, const bool omitRangeData=false, const bool useMultiArcBiases=false)
Test the estimation of observation biases.
template std::pair< Eigen::VectorXd, bool > executeEarthOrbiterBiasEstimation< double, double > (const bool estimateRangeBiases, const bool estimateTwoWayBiases, const bool useSingleBiasModel, const bool estimateAbsoluteBiases, const bool omitRangeData, const bool useMultiArcBiases)
template<typename TimeType = double, typename StateScalarType = double>
Eigen::VectorXd executeEarthOrbiterParameterEstimation (std::pair< std::shared_ptr< PodOutput< StateScalarType > >, std::shared_ptr< PodInput< StateScalarType, TimeType > > > &podData, const TimeType startTime=TimeType(1.0E7), const int numberOfDaysOfData=3, const int numberOfIterations=5, const bool useFullParameterSet=true)
template Eigen::VectorXd executeEarthOrbiterParameterEstimation< double, double > (std::pair< std::shared_ptr< PodOutput< double > >, std::shared_ptr< PodInput< double, double > > > &podData, const double startTime, const int numberOfDaysOfData, const int numberOfIterations, const bool useFullParameterSet)
template<typename TimeType = double, typename StateScalarType = double>
std::pair< std::shared_ptr< PodOutput< StateScalarType > >, Eigen::VectorXd > executePlanetaryParameterEstimation (const int observableType=1, Eigen::VectorXd parameterPerturbation=getDefaultInitialParameterPerturbation(), Eigen::MatrixXd inverseAPrioriCovariance=Eigen::MatrixXd::Zero(7, 7), const double weight=1.0)
template std::pair< std::shared_ptr< PodOutput< double > >, Eigen::VectorXd > executePlanetaryParameterEstimation< double, double > (const int observableType, Eigen::VectorXd parameterPerturbation, Eigen::MatrixXd inverseAPrioriCovariance, const double weight)
Eigen::VectorXd getDefaultInitialParameterPerturbation ()
Function Documentation
getDefaultInitialParameterPerturbation()
Eigen::VectorXd tudat::unit_tests::getDefaultInitialParameterPerturbation ()
Definition at line 9 of file orbitDeterminationTestCases.cpp.
executePlanetaryParameterEstimation< double, double >()
template std::pair< std::shared_ptr< PodOutput< double > >, Eigen::VectorXd > tudat::unit_tests::executePlanetaryParameterEstimation< double, double > (const int observableType, Eigen::VectorXd parameterPerturbation, Eigen::MatrixXd inverseAPrioriCovariance, const double weight)
executeEarthOrbiterParameterEstimation< double, double >()
template Eigen::VectorXd tudat::unit_tests::executeEarthOrbiterParameterEstimation< double, double > (std::pair< std::shared_ptr< PodOutput< double > >, std::shared_ptr< PodInput< double, double > > > & podData, const double startTime, const int numberOfDaysOfData, const int numberOfIterations, const bool useFullParameterSet)
executeEarthOrbiterBiasEstimation< double, double >()
template std::pair< Eigen::VectorXd, bool > tudat::unit_tests::executeEarthOrbiterBiasEstimation< double, double > (const bool estimateRangeBiases, const bool estimateTwoWayBiases, const bool useSingleBiasModel, const bool estimateAbsoluteBiases, const bool omitRangeData, const bool useMultiArcBiases)
executePlanetaryParameterEstimation()
template<typename TimeType = double, typename StateScalarType = double> std::pair< std::shared_ptr< PodOutput< StateScalarType > >, Eigen::VectorXd > tudat::unit_tests::executePlanetaryParameterEstimation (const int observableType = 1, Eigen::VectorXd parameterPerturbation = getDefaultInitialParameterPerturbation(), Eigen::MatrixXd inverseAPrioriCovariance = Eigen::MatrixXd::Zero(7, 7), const double weight = 1.0)
Definition at line 45 of file orbitDeterminationTestCases.h.
References tudat::utilities::addScalarToVector(), tudat::observation_models::angular_position, tudat::basic_astrodynamics::central_gravity, tudat::propagators::cowell, tudat::simulation_setup::createAccelerationModelsMap(), tudat::simulation_setup::createBodies(), tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::estimateParameters(), tudat::simulation_setup::getDefaultBodySettings(), tudat::estimatable_parameters::getInitialStateVectorOfBodiesToEstimate(), tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::getObservationSimulators(), tudat::estimatable_parameters::gravitational_parameter, tudat::spice_interface::loadStandardSpiceKernels(), tudat::observation_models::observed_body, tudat::observation_models::one_way_doppler, tudat::observation_models::one_way_range, tudat::observation_models::position_observable, tudat::observation_models::receiver, tudat::numerical_integrators::rungeKutta4, tudat::simulation_setup::setGlobalFrameBodyEphemerides(), and tudat::observation_models::transmitter.
executeEarthOrbiterParameterEstimation()
template<typename TimeType = double, typename StateScalarType = double> Eigen::VectorXd tudat::unit_tests::executeEarthOrbiterParameterEstimation (std::pair< std::shared_ptr< PodOutput< StateScalarType > >, std::shared_ptr< PodInput< StateScalarType, TimeType > > > & podData, const TimeType startTime = TimeType(1.0E7), const int numberOfDaysOfData = 3, const int numberOfIterations = 5, const bool useFullParameterSet = true)
Definition at line 318 of file orbitDeterminationTestCases.h.
References tudat::basic_astrodynamics::aerodynamic, tudat::observation_models::angular_position, tudat::orbital_element_conversions::argumentOfPeriapsisIndex, tudat::basic_astrodynamics::cannon_ball_radiation_pressure, tudat::basic_astrodynamics::central_gravity, tudat::spice_interface::computeRotationQuaternionBetweenFrames(), tudat::estimatable_parameters::constant_drag_coefficient, tudat::unit_conversions::convertDegreesToRadians(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::propagators::cowell, tudat::simulation_setup::createAccelerationModelsMap(), tudat::simulation_setup::createAerodynamicCoefficientInterface(), tudat::simulation_setup::createBodies(), tudat::simulation_setup::createGroundStation(), tudat::simulation_setup::createParametersToEstimate(), tudat::simulation_setup::createRadiationPressureInterface(), tudat::mathematical_constants::E, tudat::orbital_element_conversions::eccentricityIndex, tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::estimateParameters(), tudat::coordinate_conversions::geodetic_position, tudat::simulation_setup::getDefaultBodySettings(), tudat::observation_models::getLinkEndsString(), tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::getObservationSimulators(), tudat::estimatable_parameters::ground_station_position, tudat::orbital_element_conversions::inclinationIndex, tudat::physical_constants::JULIAN_DAY, tudat::spice_interface::loadStandardSpiceKernels(), tudat::orbital_element_conversions::longitudeOfAscendingNodeIndex, tudat::observation_models::one_way_doppler, tudat::observation_models::one_way_range, tudat::mathematical_constants::PI, tudat::estimatable_parameters::printEstimatableParameterEntries(), tudat::estimatable_parameters::radiation_pressure_coefficient, tudat::observation_models::receiver, tudat::estimatable_parameters::rotation_pole_position, tudat::orbital_element_conversions::semiMajorAxisIndex, tudat::simulation_setup::setGlobalFrameBodyEphemerides(), tudat::estimatable_parameters::spherical_harmonics_cosine_coefficient_block, tudat::estimatable_parameters::spherical_harmonics_sine_coefficient_block, tudat::observation_models::transmitter, and tudat::orbital_element_conversions::trueAnomalyIndex.
executeEarthOrbiterBiasEstimation()
template<typename TimeType = double, typename StateScalarType = double> std::pair< Eigen::VectorXd, bool > tudat::unit_tests::executeEarthOrbiterBiasEstimation (const bool estimateRangeBiases = true, const bool estimateTwoWayBiases = false, const bool useSingleBiasModel = true, const bool estimateAbsoluteBiases = true, const bool omitRangeData = false, const bool useMultiArcBiases = false)
Definition at line 650 of file orbitDeterminationTestCases.h.
References tudat::orbital_element_conversions::argumentOfPeriapsisIndex, tudat::basic_astrodynamics::central_gravity, tudat::unit_conversions::convertDegreesToRadians(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::propagators::cowell, tudat::simulation_setup::createAccelerationModelsMap(), tudat::simulation_setup::createBodies(), tudat::simulation_setup::createGroundStation(), tudat::simulation_setup::createParametersToEstimate(), tudat::mathematical_constants::E, tudat::orbital_element_conversions::eccentricityIndex, tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::estimateParameters(), tudat::coordinate_conversions::geodetic_position, tudat::simulation_setup::getDefaultBodySettings(), tudat::simulation_setup::OrbitDeterminationManager< ObservationScalarType, TimeType, std::enable_if< is_state_scalar_and_time_type< ObservationScalarType, TimeType >::value, int >::type >::getObservationSimulators(), tudat::orbital_element_conversions::inclinationIndex, tudat::spice_interface::loadStandardSpiceKernels(), tudat::orbital_element_conversions::longitudeOfAscendingNodeIndex, tudat::observation_models::n_way_range, tudat::observation_models::one_way_doppler, tudat::observation_models::one_way_range, tudat::estimatable_parameters::printEstimatableParameterEntries(), tudat::observation_models::receiver, tudat::observation_models::reflector1, tudat::orbital_element_conversions::semiMajorAxisIndex, tudat::simulation_setup::setGlobalFrameBodyEphemerides(), tudat::observation_models::transmitter, tudat::orbital_element_conversions::trueAnomalyIndex, and tudat::observation_models::two_way_doppler.