Tudat: tudat::transfer_trajectories::CaptureLeg Class Reference
tudat::transfer_trajectories::CaptureLeg Class Reference
Capture leg class.
#include <captureLeg.h>
Public Member Functions
CaptureLeg (const Eigen::Vector3d &departureBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, const double captureBodyGravitationalParameter, std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr, const double semiMajorAxis, const double eccentricity, const bool includeArrivalDeltaV=true)
Constructor with immediate definition of parameters..
void calculateLeg (Eigen::Vector3d &velocityBeforeArrivalBody, double &deltaV)
Calculate the leg.
void getCaptureDeltaV (double &captureDeltaV)
Function to retrieve the value of the capture Delta V.
void intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, const double startingTime=0.)
Calculate intermediate positions and their corresponding times.
void maneuvers (std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, std::vector< double > &deltaVVector, const double startingTime=0.)
Return maneuvres along the leg.
void updateDefiningVariables (const Eigen::VectorXd &variableVector)
Update the defining variables.
void updateEphemeris (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const Eigen::Vector3d &departureBodyVelocity)
Update the ephemeris.
Public Member Functions inherited from tudat::transfer_trajectories::MissionLeg
MissionLeg (const Eigen::Vector3d &departureBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~MissionLeg ()
virtual destructor.
void returnDepartureVariables (Eigen::Vector3d &departureBodyPosition, Eigen::Vector3d &departureBodyVelocity, Eigen::Vector3d &velocityAfterDeparture)
Return Departure Variables.
Private Attributes
double captureBodyGravitationalParameter_
The capture body gravitational parameter.
double eccentricity_
The capture orbit eccentricity.
bool includeArrivalDeltaV_
Boolean denoting whether to include the Delta V of arrival.
double semiMajorAxis_
The capture orbit semi-major axis.
std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr_
The velocity of the spacecraft before capture.
Additional Inherited Members
Protected Attributes inherited from tudat::transfer_trajectories::MissionLeg
double centralBodyGravitationalParameter_
The central body gravitational parameter.
double deltaV_
The total deltaV of the leg.
Eigen::Vector3d departureBodyPosition_
The departure body position.
Eigen::Vector3d departureBodyVelocity_
The departure body velocity.
double timeOfFlight_
The time of flight.
Eigen::Vector3d velocityAfterDeparture_
The velocity after departure.
Detailed Description
A class that calculates capture maneuver of a spacecraft entering a specified orbit around a body. It also contains the same functionality as the space legs, meaning this class can also be used for a captured phase in a trajectory. For example to calculate a sample & return mission in one go.
Definition at line 39 of file captureLeg.h.
Constructor & Destructor Documentation
CaptureLeg()
tudat::transfer_trajectories::CaptureLeg::CaptureLeg (const Eigen::Vector3d & departureBodyPosition, const double timeOfFlight, const Eigen::Vector3d & departureBodyVelocity, const double centralBodyGravitationalParameter, const double captureBodyGravitationalParameter, std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr, const double semiMajorAxis, const double eccentricity, const bool includeArrivalDeltaV = true) inline
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
Parameters
departureBodyPosition Location of the departure body.
timeOfFlight Length of the leg.
departureBodyVelocity Velocity of the departure body.
centralBodyGravitationalParameter Gravitational parameter of the cebtral body (most cases the Sun).
captureBodyGravitationalParameter Gravitational parameter of the capture body.
velocityBeforeDepartureBodyPtr Pointer to the velocity before arriving at the departure body.
semiMajorAxis Semi-major axis of the orbit after the capture is performed.
eccentricity Eccentricity of the orbit after the capture is performed.
includeArrivalDeltaV Boolean denoting whether to include the Delta V of arrival.
Definition at line 57 of file captureLeg.h.
References TUDAT_NAN, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
Member Function Documentation
calculateLeg()
void tudat::transfer_trajectories::CaptureLeg::calculateLeg (Eigen::Vector3d & velocityBeforeArrivalBody, double & deltaV) virtual
Calculate the leg and update the Delta V and the velocity before the next body.
Performs all calculations required for this leg.
Parameters
velocityBeforeArrivalBody the velocity of the spacecraft before it arrives at the target body.
deltaV the delta V required to perform the capture manuever.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 12 of file captureLeg.cpp.
References captureBodyGravitationalParameter_, tudat::mission_segments::computeEscapeOrCaptureDeltaV(), tudat::transfer_trajectories::MissionLeg::deltaV_, tudat::transfer_trajectories::MissionLeg::departureBodyVelocity_, eccentricity_, includeArrivalDeltaV_, semiMajorAxis_, TUDAT_NAN, tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_, and velocityBeforeDepartureBodyPtr_.
Referenced by intermediatePoints(), and maneuvers().
intermediatePoints()
void tudat::transfer_trajectories::CaptureLeg::intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, const double startingTime = 0.) virtual
Calculates intermediate positions and their corresponding times in the leg, based on a maximum time between two points.
Parameters
maximumTimeStep the maximum time between two points along the trajectory.
positionVector Vector of positions along the orbit, space according to the maximum time step.
timeVector The times corresponding to the positions.
startingTime the initial time from which the intermediate points are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 39 of file captureLeg.cpp.
References calculateLeg(), tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, tudat::transfer_trajectories::returnTrajectory(), tudat::transfer_trajectories::MissionLeg::timeOfFlight_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
maneuvers()
void tudat::transfer_trajectories::CaptureLeg::maneuvers (std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, std::vector< double > & deltaVVector, const double startingTime = 0.) virtual
Returns the maneuver points, times and sizes along the trajectory.
Parameters
positionVector Vector of the positions of the maneuvers.
timeVector The times corresponding to the positions.
deltaVVector the delta V required for each maneuver.
startingTime the initial time from which the maneuvers are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 65 of file captureLeg.cpp.
References calculateLeg(), tudat::transfer_trajectories::MissionLeg::deltaV_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
updateEphemeris()
void tudat::transfer_trajectories::CaptureLeg::updateEphemeris (const Eigen::Vector3d & departureBodyPosition, const Eigen::Vector3d & arrivalBodyPosition, const Eigen::Vector3d & departureBodyVelocity) inline virtual
Sets the positions and the velocities to the newly specified values. Required for re-using the class, without re-initializing it.
Parameters
departureBodyPosition sets the new departure body position.
arrivalBodyPosition sets the new arrival body position.
departureBodyVelocity sets the new departure body velocity.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 123 of file captureLeg.h.
References tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, and tudat::transfer_trajectories::MissionLeg::departureBodyVelocity_.
updateDefiningVariables()
void tudat::transfer_trajectories::CaptureLeg::updateDefiningVariables (const Eigen::VectorXd & variableVector) virtual
Sets the trajectory defining variables to the newly specified values. Required for re-using the class, without re-initializing it. For this leg: time of flight.
Parameters
variableVector the new variable vector.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 91 of file captureLeg.cpp.
References tudat::transfer_trajectories::MissionLeg::timeOfFlight_.
getCaptureDeltaV()
void tudat::transfer_trajectories::CaptureLeg::getCaptureDeltaV (double & captureDeltaV) inline
Function to retrieve the value of the capture Delta V.
Parameters
captureDeltaV Double denoting the value of the capture Delta V.
Returns
Double denoting the value of the capture Delta V (returned by reference).
Definition at line 145 of file captureLeg.h.
References tudat::transfer_trajectories::MissionLeg::deltaV_.
Member Data Documentation
captureBodyGravitationalParameter_
double tudat::transfer_trajectories::CaptureLeg::captureBodyGravitationalParameter_ private
The gravitational parameter of the capture body in the leg.
Definition at line 158 of file captureLeg.h.
Referenced by calculateLeg().
velocityBeforeDepartureBodyPtr_
std::shared_ptr< Eigen::Vector3d > tudat::transfer_trajectories::CaptureLeg::velocityBeforeDepartureBodyPtr_ private
The heliocentric velocity before the capture maneuver. This is passed using a pointer, because this parameter is dependent on the previous leg. The result of the previous leg is not necessarily known when this leg is initiated.
Definition at line 166 of file captureLeg.h.
Referenced by calculateLeg().
semiMajorAxis_
double tudat::transfer_trajectories::CaptureLeg::semiMajorAxis_ private
The semi-major axis of the intended capture orbit.
Definition at line 172 of file captureLeg.h.
Referenced by calculateLeg().
eccentricity_
double tudat::transfer_trajectories::CaptureLeg::eccentricity_ private
The eccentricity of the intended capture orbit.
Definition at line 178 of file captureLeg.h.
Referenced by calculateLeg().
includeArrivalDeltaV_
bool tudat::transfer_trajectories::CaptureLeg::includeArrivalDeltaV_ private
Definition at line 181 of file captureLeg.h.
Referenced by calculateLeg().
The documentation for this class was generated from the following files:
Astrodynamics/TrajectoryDesign/captureLeg.h
Astrodynamics/TrajectoryDesign/captureLeg.cpp