Tudat: tudat::input_output::FieldValue Class Reference
tudat::input_output::FieldValue Class Reference
Field value class.
#include <fieldValue.h>
Public Member Functions
FieldValue (const FieldType &type, const std::string &field, const boost::shared_ptr< FieldTransform > transformer=boost::shared_ptr< FieldTransform >())
Create a FieldValue containing type, string content and transformation of field.
template<typename T >
T get ()
Get value of field content in SI units.
template<typename T >
boost::shared_ptr< T > getPointer ()
Get a shared pointer to the value of field content in SI units.
const std::string & getRaw ()
Get raw field content.
const std::string & getTransformed ()
Get transformed field content.
Public Attributes
const FieldType type
FieldType of the FieldValue.
Protected Member Functions
void loadTransformation ()
Load the transformed string if required.
Private Attributes
const std::string rawField
String of field value in raw data format.
FieldTransformPointer transform
Pointer to unit transformation equation.
std::string transformedField
String of field value in the transformed data format.
Detailed Description
Definition at line 30 of file fieldValue.h.
Constructor & Destructor Documentation
tudat::input_output::FieldValue::FieldValue (const FieldType & type, const std::string & field, const boost::shared_ptr< FieldTransform > transformer = boost::shared_ptr< FieldTransform >())
Create a FieldValue which contains the type, the content as a string and unit transformation of the field.
Parameters
type Field type.
field Field data.
transformer Transformation to apply to field data.
Definition at line 22 of file fieldValue.cpp.
Member Function Documentation
template<typename T > T tudat::input_output::FieldValue::get () inline
Definition at line 51 of file fieldValue.h.
References loadTransformation(), and transformedField.
template<typename T > boost::shared_ptr< T > tudat::input_output::FieldValue::getPointer () inline
Definition at line 59 of file fieldValue.h.
References getRaw(), getTransformed(), loadTransformation(), and transformedField.
const std::string & tudat::input_output::FieldValue::getTransformed ()
Definition at line 28 of file fieldValue.cpp.
References loadTransformation(), and transformedField.
Referenced by getPointer().
const std::string & tudat::input_output::FieldValue::getRaw ()
Definition at line 35 of file fieldValue.cpp.
References rawField.
Referenced by getPointer().
void tudat::input_output::FieldValue::loadTransformation () inline protected
Definition at line 74 of file fieldValue.h.
References rawField, transform, and transformedField.
Referenced by get(), getPointer(), and getTransformed().
Member Data Documentation
const FieldType tudat::input_output::FieldValue::type
Definition at line 47 of file fieldValue.h.
const std::string tudat::input_output::FieldValue::rawField private
Definition at line 88 of file fieldValue.h.
Referenced by getRaw(), and loadTransformation().
std::string tudat::input_output::FieldValue::transformedField private
Definition at line 91 of file fieldValue.h.
Referenced by get(), getPointer(), getTransformed(), and loadTransformation().
FieldTransformPointer tudat::input_output::FieldValue::transform private
Definition at line 94 of file fieldValue.h.
Referenced by loadTransformation().
The documentation for this class was generated from the following files:
InputOutput/fieldValue.h
InputOutput/fieldValue.cpp