Tudat: tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity Class Reference
tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity Class Reference
Swingby Leg class of an MGA-1DSM velocity formulation trajectory model.
#include <swingbyLegMga1DsmVelocity.h>
Public Member Functions
SwingbyLegMga1DsmVelocity (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, const double swingbyBodyGravitationalParameter, std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr, const double dsmTimeOfFlightFraction, const double rotationAngle, const double pericenterRadius, const double swingbyDeltaV)
Constructor with immediate definition of parameters.
void calculateLeg (Eigen::Vector3d &velocityBeforeArrivalBody, double &deltaV)
Calculate the leg.
void intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, const double startingTime=0.)
Calculate intermediate positions and their corresponding times.
void maneuvers (std::vector< Eigen::Vector3d > &positionVector, std::vector< double > &timeVector, std::vector< double > &deltaVVector, const double startingTime=0.)
Return maneuvres along the leg.
void updateDefiningVariables (const Eigen::VectorXd &variableVector)
Update the defining variables.
Public Member Functions inherited from tudat::transfer_trajectories::SpaceLeg
SpaceLeg (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~SpaceLeg ()
void updateEphemeris (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const Eigen::Vector3d &departureBodyVelocity)
Update the ephemeris.
Public Member Functions inherited from tudat::transfer_trajectories::MissionLeg
MissionLeg (const Eigen::Vector3d &departureBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter)
Constructor with immediate definition of parameters.
virtual ~MissionLeg ()
virtual destructor.
void returnDepartureVariables (Eigen::Vector3d &departureBodyPosition, Eigen::Vector3d &departureBodyVelocity, Eigen::Vector3d &velocityAfterDeparture)
Return Departure Variables.
Private Attributes
double deltaVDsm_
The deltaV of the DSM.
Eigen::Vector3d dsmLocation_
The DSM location.
double dsmTime_
The DSM time.
double dsmTimeOfFlightFraction_
The fraction of the time of flight of the DSM.
double pericenterRadius_
The pericenter radius.
double rotationAngle_
The rotation angle.
double swingbyDeltaV_
The swing-by deltaV.
Eigen::Vector3d velocityAfterDsm_
The velocity after the DSM.
Eigen::Vector3d velocityBeforeDsm_
The velocity before the DSM.
Additional Inherited Members
Protected Member Functions inherited from tudat::transfer_trajectories::SwingbyLeg
SwingbyLeg (const Eigen::Vector3d &departureBodyPosition, const Eigen::Vector3d &arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d &departureBodyVelocity, const double centralBodyGravitationalParameter, double swingbyBodyGravitationalParameter, std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr)
Constructor with immediate definition of parameters.
virtual ~SwingbyLeg ()
Protected Attributes inherited from tudat::transfer_trajectories::SwingbyLeg
double swingbyBodyGravitationalParameter_
The swing-by body gravitational parameter.
std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr_
The velocity of the spacecraft at departure.
Protected Attributes inherited from tudat::transfer_trajectories::SpaceLeg
Eigen::Vector3d arrivalBodyPosition_
The arrival body position.
Protected Attributes inherited from tudat::transfer_trajectories::MissionLeg
double centralBodyGravitationalParameter_
The central body gravitational parameter.
double deltaV_
The total deltaV of the leg.
Eigen::Vector3d departureBodyPosition_
The departure body position.
Eigen::Vector3d departureBodyVelocity_
The departure body velocity.
double timeOfFlight_
The time of flight.
Eigen::Vector3d velocityAfterDeparture_
The velocity after departure.
Detailed Description
A class that calculates the required impulses for a swinbgy leg for an MGA-1DSM velocity formulation trajectory model. This model specifies the trajectory by defining the initial hyperbolic excess velocity (in 3D) and the moment of application of the DSM. The leg is split in two sublegs. The first subleg is analyzed using a module that propagates the trajectory using the given gravity assist parameters and subsequently by a kepler propagator. The second leg is analyzed using a lambert targeter. Typically the user will be primarily interested in the total delta V and the arrival velocity of the spacecraft before the arrival planet. Note that often a MGA-1DSM velocity formulation trajectory model is used in which the gravity assist is assumed to be unpowered. Both the powered and unpowered versions can be simulated using this module.
Definition at line 45 of file swingbyLegMga1DsmVelocity.h.
Constructor & Destructor Documentation
SwingbyLegMga1DsmVelocity()
tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::SwingbyLegMga1DsmVelocity (const Eigen::Vector3d & departureBodyPosition, const Eigen::Vector3d & arrivalBodyPosition, const double timeOfFlight, const Eigen::Vector3d & departureBodyVelocity, const double centralBodyGravitationalParameter, const double swingbyBodyGravitationalParameter, std::shared_ptr< Eigen::Vector3d > velocityBeforeDepartureBodyPtr, const double dsmTimeOfFlightFraction, const double rotationAngle, const double pericenterRadius, const double swingbyDeltaV) inline
Constructor, sets objects and functions from which relevant environment and state variables are retrieved.
Parameters
departureBodyPosition location of the departure body.
arrivalBodyPosition position of the target body.
timeOfFlight Length of the leg.
departureBodyVelocity velocity of the departure body.
centralBodyGravitationalParameter gravitational parameter of the cebtral body (most cases the Sun).
swingbyBodyGravitationalParameter gravitational parameter of the swing-by body.
velocityBeforeDepartureBodyPtr pointer to the velocity before the swing-by.
dsmTimeOfFlightFraction the fraction of the TOF at which the DSM is performed.
rotationAngle The rotation angle of the gravity assist.
pericenterRadius the minimum pericenter radius for the swing-by body.
swingbyDeltaV the delta V for the swing-by manuever.
Definition at line 64 of file swingbyLegMga1DsmVelocity.h.
References TUDAT_NAN, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
Member Function Documentation
calculateLeg()
void tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::calculateLeg (Eigen::Vector3d & velocityBeforeArrivalBody, double & deltaV) virtual
Calculate the leg and update the Delta V and the velocity before the next body.
Performs all calculations required for this leg.
Parameters
velocityBeforeArrivalBody the velocity of the spacecraft before it arrives at the target body.
deltaV the delta V required to perform the leg.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 19 of file swingbyLegMga1DsmVelocity.cpp.
References tudat::transfer_trajectories::SpaceLeg::arrivalBodyPosition_, tudat::json_interface::cartesianElements, tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::orbital_element_conversions::convertCartesianToKeplerianElements(), tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), tudat::transfer_trajectories::MissionLeg::deltaV_, deltaVDsm_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, tudat::transfer_trajectories::MissionLeg::departureBodyVelocity_, dsmLocation_, dsmTime_, dsmTimeOfFlightFraction_, tudat::mission_segments::gravityAssist(), tudat::json_interface::keplerianElements, pericenterRadius_, tudat::orbital_element_conversions::propagateKeplerOrbit(), rotationAngle_, tudat::mission_segments::solveLambertProblemIzzo(), tudat::transfer_trajectories::SwingbyLeg::swingbyBodyGravitationalParameter_, swingbyDeltaV_, tudat::transfer_trajectories::MissionLeg::timeOfFlight_, tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_, velocityAfterDsm_, tudat::transfer_trajectories::SwingbyLeg::velocityBeforeDepartureBodyPtr_, and velocityBeforeDsm_.
Referenced by intermediatePoints(), and maneuvers().
intermediatePoints()
void tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::intermediatePoints (const double maximumTimeStep, std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, const double startingTime = 0.) virtual
Calculates intermediate positions and their corresponding times in the leg, based on a maximum time between two points.
Parameters
maximumTimeStep the maximum time between two points along the trajectory.
positionVector Vector of positions along the orbit, space according to the maximum time step.
timeVector The times corresponding to the positions.
startingTime the initial time from which the intermediate points are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 70 of file swingbyLegMga1DsmVelocity.cpp.
References calculateLeg(), tudat::transfer_trajectories::MissionLeg::centralBodyGravitationalParameter_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, dsmLocation_, dsmTime_, tudat::transfer_trajectories::returnTrajectory(), tudat::transfer_trajectories::MissionLeg::timeOfFlight_, tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_, and velocityAfterDsm_.
maneuvers()
void tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::maneuvers (std::vector< Eigen::Vector3d > & positionVector, std::vector< double > & timeVector, std::vector< double > & deltaVVector, const double startingTime = 0.) virtual
Returns the maneuver points, times and sizes along the trajectory.
Parameters
positionVector Vector of the positions of the maneuvers.
timeVector The times corresponding to the positions.
deltaVVector the delta V required for each maneuver.
startingTime the initial time from which the maneuvers are given.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 117 of file swingbyLegMga1DsmVelocity.cpp.
References calculateLeg(), deltaVDsm_, tudat::transfer_trajectories::MissionLeg::departureBodyPosition_, dsmLocation_, dsmTime_, swingbyDeltaV_, and tudat::transfer_trajectories::MissionLeg::velocityAfterDeparture_.
updateDefiningVariables()
void tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::updateDefiningVariables (const Eigen::VectorXd & variableVector) virtual
Sets the trajectory defining variables to the newly specified values. Required for re-using the class, without re-initializing it. For this leg: time of flight, DSM time of flight fraction, rotation angle, pericenter radius and the swing-by deltaV.
Parameters
variableVector the new variable vector.
Implements tudat::transfer_trajectories::MissionLeg.
Definition at line 147 of file swingbyLegMga1DsmVelocity.cpp.
References dsmTimeOfFlightFraction_, pericenterRadius_, rotationAngle_, swingbyDeltaV_, and tudat::transfer_trajectories::MissionLeg::timeOfFlight_.
Member Data Documentation
dsmTimeOfFlightFraction_
double tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::dsmTimeOfFlightFraction_ private
The fraction of the time of flight of the corresponding leg at which the DSM is performed.
Definition at line 142 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and updateDefiningVariables().
rotationAngle_
double tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::rotationAngle_ private
The rotation angle of the gravity assist. This angle defines the 3D orientation of the gravity assist.
Definition at line 149 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and updateDefiningVariables().
pericenterRadius_
double tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::pericenterRadius_ private
The pericenter radius of the gravity assist
Definition at line 155 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and updateDefiningVariables().
swingbyDeltaV_
double tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::swingbyDeltaV_ private
The swing-by deltaV that is used at pericenter of the gravity assist. (The Velocity effect deltaV)
Definition at line 162 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg(), maneuvers(), and updateDefiningVariables().
dsmLocation_
Eigen::Vector3d tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::dsmLocation_ private
The position at which the deep space maneuver is performed
Definition at line 168 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg(), intermediatePoints(), and maneuvers().
dsmTime_
double tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::dsmTime_ private
The time at which the deep space maneuver is performed
Definition at line 174 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg(), intermediatePoints(), and maneuvers().
velocityBeforeDsm_
Eigen::Vector3d tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::velocityBeforeDsm_ private
The velocity of the spacecraft just before the deep space maneuver is performed
Definition at line 180 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg().
velocityAfterDsm_
Eigen::Vector3d tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::velocityAfterDsm_ private
The velocity of the spacecraft just after the deep space maneuver is performed
Definition at line 186 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and intermediatePoints().
deltaVDsm_
double tudat::transfer_trajectories::SwingbyLegMga1DsmVelocity::deltaVDsm_ private
The deltaV of the deep Space Maneuver
Definition at line 192 of file swingbyLegMga1DsmVelocity.h.
Referenced by calculateLeg(), and maneuvers().
The documentation for this class was generated from the following files:
Astrodynamics/TrajectoryDesign/swingbyLegMga1DsmVelocity.h
Astrodynamics/TrajectoryDesign/swingbyLegMga1DsmVelocity.cpp