Tudat: tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial Class Reference
tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial Class Reference
Class to calculate the partials of the direct tidal acceleration model (e.g. Lainey et al. 2007) w.r.t. parameters and states.
#include <directTidalDissipationAccelerationPartial.h>
Public Member Functions
DirectTidalDissipationAccelerationPartial (const std::shared_ptr< gravitation::DirectTidalDissipationAcceleration > tidalAcceleration, const std::string acceleratedBody, const std::string acceleratingBody)
Constructor.
~DirectTidalDissipationAccelerationPartial ()
Destructor.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter.
bool isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the acceleration is dependent on a non-translational integrated state.
void update (const double currentTime=TUDAT_NAN)
Function for updating partial w.r.t. the bodies' positions and velocities.
void wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration..
void wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration..
void wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration..
void wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration..
Public Member Functions inherited from tudat::acceleration_partials::AccelerationPartial
AccelerationPartial (const std::string &acceleratedBody, const std::string &acceleratingBody, const basic_astrodynamics::AvailableAcceleration accelerationType)
Base class constructor.
virtual ~AccelerationPartial ()
Virtual destructor.
std::string getAcceleratedBody ()
Function to retrieve the name of the body undergoing acceleration.
std::string getAcceleratingBody ()
Function to retrieve the name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration getAccelerationType ()
Function to retrieve the type of acceleration w.r.t. which partial is taken..
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
virtual bool isAccelerationPartialWrtAdditionalBodyNonnullptr (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the translational state of a third body is non-zero.
bool isStateDerivativeDependentOnIntegratedState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to check whether a partial w.r.t. some integrated state is non-zero.
virtual void wrtNonTranslationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the acceleration w.r.t. a non-translational integrated state.
virtual void wrtPositionOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of the third body.
void wrtStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body undergoing acceleration.
void wrtStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body exerting acceleration.
void wrtStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the third body.
virtual void wrtVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Protected Member Functions
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getGravitationalParameterPartialFunction (const estimatable_parameters::EstimatebleParameterIdentifier &parameterId)
Function to create a function returning the current partial w.r.t. a gravitational parameter.
void wrtGravitationalParameterOfPlanet (Eigen::MatrixXd &gravitationalParameterPartial)
Function to compute derivative w.r.t. gravitational parameter of planet.
void wrtGravitationalParameterOfSatellite (Eigen::MatrixXd &gravitationalParameterPartial)
Function to compute derivative w.r.t. gravitational parameter of satellite.
void wrtTidalTimeLag (Eigen::MatrixXd &gravitationalParameterPartial)
Function to compute derivative w.r.t. tidal time lag parameter.
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Protected Attributes
Eigen::Matrix3d currentPartialWrtPosition_
Current partial of central gravity acceleration w.r.t. position of body undergoing acceleration.
Eigen::Matrix3d currentPartialWrtVelocity_
Current partial of central gravity acceleration w.r.t. velocity of body undergoing acceleration.
Eigen::Vector6d currentRelativeBodyState_
Current state of satellite w.r.t. planet.
std::shared_ptr< gravitation::DirectTidalDissipationAcceleration > tidalAcceleration_
Acceleration model of which partial derivatives are to be computed.
Protected Attributes inherited from tudat::acceleration_partials::AccelerationPartial
std::string acceleratedBody_
Name of the body undergoing acceleration.
std::string acceleratingBody_
Name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration accelerationType_
Type of acceleration w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Definition at line 84 of file directTidalDissipationAccelerationPartial.h.
Constructor & Destructor Documentation
DirectTidalDissipationAccelerationPartial()
tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::DirectTidalDissipationAccelerationPartial (const std::shared_ptr< gravitation::DirectTidalDissipationAcceleration > tidalAcceleration, const std::string acceleratedBody, const std::string acceleratingBody) inline
Constructor.
Parameters
tidalAcceleration Acceleration model of which partial derivatives are to be computed
acceleratedBody Body undergoing acceleration.
acceleratingBody Body exerting acceleration.
Definition at line 95 of file directTidalDissipationAccelerationPartial.h.
~DirectTidalDissipationAccelerationPartial()
tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::~DirectTidalDissipationAccelerationPartial () inline
Definition at line 105 of file directTidalDissipationAccelerationPartial.h.
Member Function Documentation
wrtPositionOfAcceleratedBody()
void tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 118 of file directTidalDissipationAccelerationPartial.h.
References currentPartialWrtPosition_.
wrtVelocityOfAcceleratedBody()
void tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian velocity of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 143 of file directTidalDissipationAccelerationPartial.h.
References currentPartialWrtVelocity_.
wrtPositionOfAcceleratingBody()
void tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration and adding it to the existing partial block. The update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 168 of file directTidalDissipationAccelerationPartial.h.
References currentPartialWrtPosition_.
wrtVelocityOfAcceleratingBody()
void tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the velocity of body undergoing acceleration and adding it to the existing partial block. The update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian velocity of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 193 of file directTidalDissipationAccelerationPartial.h.
References currentPartialWrtVelocity_.
isStateDerivativeDependentOnIntegratedNonTranslationalState()
bool tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline virtual
Function for determining if the acceleration is dependent on a non-translational integrated state. No dependency is implemented, but a warning is provided if partial w.r.t. mass of body exerting acceleration (and undergoing acceleration if mutual attraction is used) is requested.
Parameters
stateReferencePoint Reference point id of propagated state
integratedStateType Type of propagated state for which dependency is to be determined.
Returns
True if dependency exists (non-zero partial), false otherwise.
Reimplemented from tudat::acceleration_partials::AccelerationPartial.
Definition at line 215 of file directTidalDissipationAccelerationPartial.h.
References tudat::acceleration_partials::AccelerationPartial::acceleratedBody_, and tudat::acceleration_partials::AccelerationPartial::acceleratingBody_.
getParameterPartialFunction() [1/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) virtual
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency, 1 otherwise).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 97 of file directTidalDissipationAccelerationPartial.cpp.
References tudat::acceleration_partials::AccelerationPartial::acceleratedBody_, tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, tudat::estimatable_parameters::direct_dissipation_tidal_time_lag, getGravitationalParameterPartialFunction(), tudat::estimatable_parameters::gravitational_parameter, tidalAcceleration_, and wrtTidalTimeLag().
getParameterPartialFunction() [2/2]
std::pair< std::function< void(Eigen::MatrixXd&) >, int > tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) inline virtual
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 244 of file directTidalDissipationAccelerationPartial.h.
update()
void tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update (const double currentTime = TUDAT_NAN) virtual
Function for updating partial w.r.t. the bodies' positions and velocities
Parameters
currentTime Time at which partials are to be calculated
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 166 of file directTidalDissipationAccelerationPartial.cpp.
References tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnPlanetWrtPosition(), tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnPlanetWrtVelocity(), tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnSatelliteWrtPosition(), tudat::acceleration_partials::computeDirectTidalAccelerationDueToTideOnSatelliteWrtVelocity(), currentPartialWrtPosition_, currentPartialWrtVelocity_, currentRelativeBodyState_, tudat::orbit_determination::StateDerivativePartial::currentTime_, and tidalAcceleration_.
getGravitationalParameterPartialFunction()
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::getGravitationalParameterPartialFunction (const estimatable_parameters::EstimatebleParameterIdentifier & parameterId) protected
Function to create a function returning the current partial w.r.t. a gravitational parameter.
Parameters
parameterId Identifier of parameter for which the partial is to be created.
Returns
Pair with partial function and paramater partial size.
Definition at line 201 of file directTidalDissipationAccelerationPartial.cpp.
References tudat::acceleration_partials::AccelerationPartial::acceleratedBody_, tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, tudat::estimatable_parameters::gravitational_parameter, tidalAcceleration_, wrtGravitationalParameterOfPlanet(), and wrtGravitationalParameterOfSatellite().
Referenced by getParameterPartialFunction().
wrtGravitationalParameterOfPlanet()
void tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::wrtGravitationalParameterOfPlanet (Eigen::MatrixXd & gravitationalParameterPartial) protected
Function to calculate central gravity partial w.r.t. central body gravitational parameter.
Definition at line 236 of file directTidalDissipationAccelerationPartial.cpp.
References tidalAcceleration_.
Referenced by getGravitationalParameterPartialFunction().
wrtGravitationalParameterOfSatellite()
void tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::wrtGravitationalParameterOfSatellite (Eigen::MatrixXd & gravitationalParameterPartial) protected
Definition at line 243 of file directTidalDissipationAccelerationPartial.cpp.
References tidalAcceleration_.
Referenced by getGravitationalParameterPartialFunction().
wrtTidalTimeLag()
void tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::wrtTidalTimeLag (Eigen::MatrixXd & gravitationalParameterPartial) protected
Definition at line 255 of file directTidalDissipationAccelerationPartial.cpp.
References tidalAcceleration_.
Referenced by getParameterPartialFunction().
Member Data Documentation
tidalAcceleration_
std::shared_ptr< gravitation::DirectTidalDissipationAcceleration > tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::tidalAcceleration_ protected
Definition at line 279 of file directTidalDissipationAccelerationPartial.h.
Referenced by getGravitationalParameterPartialFunction(), getParameterPartialFunction(), update(), wrtGravitationalParameterOfPlanet(), wrtGravitationalParameterOfSatellite(), and wrtTidalTimeLag().
currentRelativeBodyState_
Eigen::Vector6d tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::currentRelativeBodyState_ protected
Definition at line 282 of file directTidalDissipationAccelerationPartial.h.
Referenced by update().
currentPartialWrtPosition_
Eigen::Matrix3d tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::currentPartialWrtPosition_ protected
Current partial of central gravity acceleration w.r.t. position of body undergoing acceleration (= -partial of central gravity acceleration w.r.t. position of body exerting acceleration), calculated and set by update() function.
Definition at line 290 of file directTidalDissipationAccelerationPartial.h.
Referenced by update(), wrtPositionOfAcceleratedBody(), and wrtPositionOfAcceleratingBody().
currentPartialWrtVelocity_
Eigen::Matrix3d tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::currentPartialWrtVelocity_ protected
Current partial of central gravity acceleration w.r.t. velocity of body undergoing acceleration (= -partial of central gravity acceleration w.r.t. velocity of body exerting acceleration), calculated and set by update() function.
Definition at line 299 of file directTidalDissipationAccelerationPartial.h.
Referenced by update(), wrtVelocityOfAcceleratedBody(), and wrtVelocityOfAcceleratingBody().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/AccelerationPartials/directTidalDissipationAccelerationPartial.h
Astrodynamics/OrbitDetermination/AccelerationPartials/directTidalDissipationAccelerationPartial.cpp