Tudat: tudat::geometric_shapes::Capsule Class Reference
tudat::geometric_shapes::Capsule Class Reference
Capsule class.
#include <capsule.h>
Public Member Functions
Capsule (const double noseRadius, const double middleRadius, const double rearLength, const double rearAngle, const double sideRadius)
Default constructor.
double getMiddleRadius ()
Get middle radius.
double getNoseRadius ()
Get nose radius.
double getRearAngle ()
Get rear angle.
double getRearLength ()
Get rear length.
double getSideRadius ()
Get side radius.
Public Member Functions inherited from tudat::geometric_shapes::CompositeSurfaceGeometry
CompositeSurfaceGeometry ()
Default constructor.
CompositeSurfaceGeometry (std::vector< std::shared_ptr< SingleSurfaceGeometry > > singleSurfaceGeometryList, std::vector< std::shared_ptr< CompositeSurfaceGeometry > > compositeSurfaceGeometryList)
Constructor, sets constituent surface geometries of objects.
virtual ~CompositeSurfaceGeometry ()
Default destructor.
std::shared_ptr< CompositeSurfaceGeometry > getCompositeSurfaceGeometry (const unsigned int index)
Get pointer to a stored CompositeSurfaceGeometry object.
unsigned int getNumberOfCompositeSurfaceGeometries ()
Get number of composite surface geometries.
unsigned int getNumberOfSingleSurfaceGeometries ()
Get number of single surface geometries.
std::shared_ptr< SingleSurfaceGeometry > getSingleSurfaceGeometry (const unsigned int index)
Get pointer to stored SingleSurfaceGeometry object.
Public Member Functions inherited from tudat::SurfaceGeometry
virtual ~SurfaceGeometry ()
Default destructor.
Private Attributes
double middleRadius_
Middle radius.
double noseRadius_
Nose radius.
double rearAngle_
Rear angle.
double rearLength_
Rear length.
double sideRadius_
Side radius.
Friends
std::ostream & operator<< (std::ostream &stream, Capsule &capsule)
Overload ostream to print class information.
Additional Inherited Members
Public Types inherited from tudat::geometric_shapes::CompositeSurfaceGeometry
typedef std::shared_ptr< CompositeSurfaceGeometry > CompositeSurfaceGeometryPointer
Typedef for shared-pointer to CompositeSurfaceGeometry object.
Protected Member Functions inherited from tudat::geometric_shapes::CompositeSurfaceGeometry
void setCompositeSurfaceGeometry (std::shared_ptr< CompositeSurfaceGeometry > compositeSurfaceGeometry, const unsigned int index)
Set pointer to a CompositeSurfaceGeometry object.
void setNumberOfCompositeSurfaceGeometries (const unsigned int numberOfCompositeSurfaceGeometries)
Set number of composite surface geometries.
void setNumberOfSingleSurfaceGeometries (const unsigned int numberOfSingleSurfaceGeometries)
Set number of single surface geometries.
void setSingleSurfaceGeometry (std::shared_ptr< SingleSurfaceGeometry > singleSurfaceGeometry, const unsigned int index)
Set pointer to SingleSurfaceGeometry object.
Protected Attributes inherited from tudat::geometric_shapes::CompositeSurfaceGeometry
std::vector< CompositeSurfaceGeometryPointer > compositeSurfaceGeometryList_
Array of pointers to CompositeSurfaceGeometries.
unsigned int numberOfCompositeSurfaceGeometries_
Size of compositeSurfaceGeometryList_.
unsigned int numberOfSingleSurfaceGeometries_
Size of singleSurfaceGeometryList_.
std::vector< SingleSurfaceGeometryPointer > singleSurfaceGeometryList_
Array of pointers to SingleSurfaceGeometries.
Detailed Description
Class that defines a Capsule shape, like that of the Apollo or ARD (Advanced Re-entry Demonstrator) capsule. The class derives from the CompositeSurfaceGeometry class, its constituent surface geometries are a SphereSegment object for the nose region, a ConicalFrustum object for the afterbody, a SphereSegment object for the rear cap, and a Torus object for the connection between the nose and torus parts. The setCapsule() function needs to be called after each of the parameters has been set to initialize the capsule.
Definition at line 41 of file capsule.h.
Constructor & Destructor Documentation
Capsule()
tudat::geometric_shapes::Capsule::Capsule (const double noseRadius, const double middleRadius, const double rearLength, const double rearAngle, const double sideRadius)
Default constructor, initializes single and composite surface lists.
Parameters
noseRadius Radius of curvature of capsule nose.
middleRadius Maximum radius of capsule
rearLength Length of frustum section
rearAngle Cone half angle of frustum part
sideRadius Radius of curvature of capsule shoulder.
Definition at line 39 of file capsule.cpp.
References middleRadius_, noseRadius_, tudat::geometric_shapes::CompositeSurfaceGeometry::numberOfSingleSurfaceGeometries_, tudat::mathematical_constants::PI, rearAngle_, rearLength_, tudat::geometric_shapes::CompositeSurfaceGeometry::setNumberOfCompositeSurfaceGeometries(), tudat::geometric_shapes::CompositeSurfaceGeometry::setNumberOfSingleSurfaceGeometries(), tudat::geometric_shapes::CompositeSurfaceGeometry::setSingleSurfaceGeometry(), sideRadius_, and tudat::geometric_shapes::CompositeSurfaceGeometry::singleSurfaceGeometryList_.
Member Function Documentation
getNoseRadius()
double tudat::geometric_shapes::Capsule::getNoseRadius () inline
Returns the nose radius of the capsule.
Returns
Nose radius.
Definition at line 65 of file capsule.h.
References noseRadius_.
Referenced by tudat::geometric_shapes::operator<<().
getMiddleRadius()
double tudat::geometric_shapes::Capsule::getMiddleRadius () inline
Returns the middle radius of the capsule.
Returns
Middle radius.
Definition at line 72 of file capsule.h.
References middleRadius_.
Referenced by tudat::geometric_shapes::operator<<().
getRearLength()
double tudat::geometric_shapes::Capsule::getRearLength () inline
Returns the rear length of the capsule.
Returns
Rear length.
Definition at line 79 of file capsule.h.
References rearLength_.
Referenced by tudat::geometric_shapes::operator<<().
getRearAngle()
double tudat::geometric_shapes::Capsule::getRearAngle () inline
Returns the rear angle.
Returns
Rear angle.
Definition at line 86 of file capsule.h.
References rearAngle_.
Referenced by tudat::geometric_shapes::operator<<().
getSideRadius()
double tudat::geometric_shapes::Capsule::getSideRadius () inline
Returns the side radius.
Returns
side radius.
Definition at line 93 of file capsule.h.
References sideRadius_.
Referenced by tudat::geometric_shapes::operator<<().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, Capsule & capsule) friend
Overloads ostream to print class information, prints the class type, and number defining parameters.
Parameters
stream Stream to which info is to be printed.
capsule Capsule of which info is to be printed.
Returns
Stream with printed info.
Definition at line 142 of file capsule.cpp.
Member Data Documentation
middleRadius_
double tudat::geometric_shapes::Capsule::middleRadius_ private
Middle radius.
Definition at line 113 of file capsule.h.
Referenced by Capsule(), and getMiddleRadius().
noseRadius_
double tudat::geometric_shapes::Capsule::noseRadius_ private
Nose radius.
Definition at line 119 of file capsule.h.
Referenced by Capsule(), and getNoseRadius().
rearLength_
double tudat::geometric_shapes::Capsule::rearLength_ private
Rear length.
Definition at line 125 of file capsule.h.
Referenced by Capsule(), and getRearLength().
sideRadius_
double tudat::geometric_shapes::Capsule::sideRadius_ private
Side radius.
Definition at line 131 of file capsule.h.
Referenced by Capsule(), and getSideRadius().
rearAngle_
double tudat::geometric_shapes::Capsule::rearAngle_ private
Rear angle.
Definition at line 137 of file capsule.h.
Referenced by Capsule(), and getRearAngle().
The documentation for this class was generated from the following files:
Mathematics/GeometricShapes/capsule.h
Mathematics/GeometricShapes/capsule.cpp