Tudat: tudat::simulation_setup::DirectSpiceEphemerisSettings Class Reference
tudat::simulation_setup::DirectSpiceEphemerisSettings Class Reference
EphemerisSettings derived class for defining settings of an ephemeris linked directly to Spice.
#include <createEphemeris.h>
Public Member Functions
DirectSpiceEphemerisSettings (const std::string frameOrigin="SSB", const std::string frameOrientation="ECLIPJ2000", const bool correctForStellarAberration=false, const bool correctForLightTimeAberration=false, const bool convergeLighTimeAberration=false, const EphemerisType ephemerisType=direct_spice_ephemeris)
Constructor.
virtual ~DirectSpiceEphemerisSettings ()
Destructor.
bool getConvergeLighTimeAberration ()
Returns whether to use single iteration or max. 3 iterations for calculating light time.
bool getCorrectForLightTimeAberration ()
Returns whether to correct for light time in retrieved values of (observed state).
bool getCorrectForStellarAberration ()
Returns whether to correct for stellar aberration in retrieved values of (observed state).
Public Member Functions inherited from tudat::simulation_setup::EphemerisSettings
EphemerisSettings (const EphemerisType ephemerisType, const std::string &frameOrigin="SSB", const std::string &frameOrientation="ECLIPJ2000")
Constructor, sets type of ephemeris model.
virtual ~EphemerisSettings ()
Destructor.
EphemerisType getEphemerisType ()
Function to return type of gravity field model that is to be created.
std::string getFrameOrientation ()
Function to return the orientation of frame in which ephemeris data is defined.
std::string getFrameOrigin ()
Function to return the origin of frame in which ephemeris data is defined.
bool getMakeMultiArcEphemeris ()
Function to retrieve boolean denoting whether the ephemeris that is to be created is a multi-arc ephemeris.
void resetFrameOrientation (const std::string &frameOrientation)
Function to rese the orientation of the frame.
void resetFrameOrigin (const std::string &frameOrigin)
Function to reset the origin of the frame.
void resetMakeMultiArcEphemeris (const bool makeMultiArcEphemeris)
Function to reset boolean denoting whether the ephemeris that is to be created is a multi-arc ephemeris.
Protected Attributes
bool convergeLighTimeAberration_
Boolean whether to use single iteration or max. 3 iterations for calculating light time.
bool correctForLightTimeAberration_
Boolean whether to correct for light time in retrieved values of (observed state).
bool correctForStellarAberration_
Boolean whether to correct for stellar aberration in retrieved values of (observed state).
Protected Attributes inherited from tudat::simulation_setup::EphemerisSettings
EphemerisType ephemerisType_
Type of ephemeris model that is to be created.
std::string frameOrientation_
Orientation of frame in which ephemeris data is defined.
std::string frameOrigin_
Origin of frame in which ephemeris data is defined.
bool makeMultiArcEphemeris_
Boolean denoting whether the ephemeris that is to be created is a multi-arc ephemeris.
Detailed Description
Definition at line 157 of file createEphemeris.h.
Constructor & Destructor Documentation
DirectSpiceEphemerisSettings()
tudat::simulation_setup::DirectSpiceEphemerisSettings::DirectSpiceEphemerisSettings (const std::string frameOrigin = "SSB", const std::string frameOrientation = "ECLIPJ2000", const bool correctForStellarAberration = false, const bool correctForLightTimeAberration = false, const bool convergeLighTimeAberration = false, const EphemerisType ephemerisType = direct_spice_ephemeris) inline
Constructor, sets the properties from which the Spice ephemeris is to be retrieved.
Parameters
frameOrigin Name of body relative to which the ephemeris is to be calculated (optional "SSB" by default).
correctForStellarAberration Boolean whether to correct for stellar Aberration in retrieved values of (observed state) (optional "ECLIPJ2000" by defalut).
correctForLightTimeAberration Boolean whether to correct for light time in retrieved values of (observed state) (optional false by default).
convergeLighTimeAberration Boolean whether to use single iteration or max. 3 iterations for calculating light time (optional false by default).
frameOrientation Orientatioan of the reference frame in which the epehemeris is to be calculated (optional false by default).
ephemerisType Type of ephemeris that is to be created, always set to direct_spice_ephemeris when using this class directly. The derived class InterpolatedSpiceEphemerisSettings sets this parameter to a different value. Not to be changed by used (optional direct_spice_ephemeris by default).
Definition at line 178 of file createEphemeris.h.
~DirectSpiceEphemerisSettings()
virtual tudat::simulation_setup::DirectSpiceEphemerisSettings::~DirectSpiceEphemerisSettings () inline virtual
Definition at line 191 of file createEphemeris.h.
Member Function Documentation
getCorrectForStellarAberration()
bool tudat::simulation_setup::DirectSpiceEphemerisSettings::getCorrectForStellarAberration () inline
Returns whether to correct for stellar aberration in retrieved values of (observed state).
Returns
Boolean defining whether to correct for stellar aberration in retrieved values of (observed state).
Definition at line 199 of file createEphemeris.h.
References correctForStellarAberration_.
Referenced by tudat::simulation_setup::from_json().
getCorrectForLightTimeAberration()
bool tudat::simulation_setup::DirectSpiceEphemerisSettings::getCorrectForLightTimeAberration () inline
Returns whether to correct for light time in retrieved values of (observed state).
Returns
Boolean defining whether to correct for light time in retrieved values of (observed state).
Definition at line 207 of file createEphemeris.h.
References correctForLightTimeAberration_.
Referenced by tudat::simulation_setup::from_json().
getConvergeLighTimeAberration()
bool tudat::simulation_setup::DirectSpiceEphemerisSettings::getConvergeLighTimeAberration () inline
Returns whether to use single iteration or max. 3 iterations for calculating light time.
Returns
Boolean defining whether to use single iteration or max. 3 iterations for calculating light time.
Definition at line 215 of file createEphemeris.h.
References convergeLighTimeAberration_.
Referenced by tudat::simulation_setup::from_json().
Member Data Documentation
correctForStellarAberration_
bool tudat::simulation_setup::DirectSpiceEphemerisSettings::correctForStellarAberration_ protected
Definition at line 219 of file createEphemeris.h.
Referenced by getCorrectForStellarAberration().
correctForLightTimeAberration_
bool tudat::simulation_setup::DirectSpiceEphemerisSettings::correctForLightTimeAberration_ protected
Definition at line 222 of file createEphemeris.h.
Referenced by getCorrectForLightTimeAberration().
convergeLighTimeAberration_
bool tudat::simulation_setup::DirectSpiceEphemerisSettings::convergeLighTimeAberration_ protected
Definition at line 225 of file createEphemeris.h.
Referenced by getConvergeLighTimeAberration().
The documentation for this class was generated from the following file:
SimulationSetup/EnvironmentSetup/createEphemeris.h