Tudat: tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType > Class Template Reference
tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType > Class Template Reference
Class for computing the state derivative of translational motion of N bodies, using an Encke propagator.
#include <nBodyEnckeStateDerivative.h>
Public Member Functions
NBodyEnckeStateDerivative (const basic_astrodynamics::AccelerationMap &accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const std::vector< std::string > &bodiesToIntegrate, const std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > &initialKeplerElements, const TimeType &initialTime)
Constructor, computes required reference quantities, and removes central gravity from acceleration list.
void calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative)
Calculates the state derivative of the translational motion of the system, using the Encke algorithm.
void clearDerivedStateDerivativeModel ()
Function to clear reference values of Encke state derivative model.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &cartesianSolution, const TimeType &time)
Function to convert the state in the conventional form to the Encke-propagator-specific form.
void convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton)
Function to convert the Encke-propagator-specific form of the state to the conventional form.
basic_astrodynamics::AccelerationMap getFullAccelerationsMap ()
Function to get map containing the list of accelerations acting on each body,.
Public Member Functions inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
NBodyStateDerivative (const basic_astrodynamics::AccelerationMap &accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const TranslationalPropagatorType propagatorType, const std::vector< std::string > &bodiesToIntegrate)
From this constructor, the object for generating the state derivative is created.
virtual ~NBodyStateDerivative ()
Destructor.
virtual void clearDerivedTranslationalStateDerivativeModel ()
Function to clear any reference/cached values of state derivative model.
void clearStateDerivativeModel ()
Function to clear reference/cached values of translational state derivative model.
void clearTranslationalStateDerivativeModel ()
Function to clear reference/cached values of acceleration models.
void convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton)
Function to convert the propagator-specific form of the state to the conventional form in the global frame.
basic_astrodynamics::AccelerationMap getAccelerationsMap ()
Function to retrieve the map containing the list of accelerations acting on each body.
std::vector< std::string > getBodiesToBeIntegratedNumerically ()
Function to get list of names of bodies that are to be integrated numerically.
std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > getCentralBodyData ()
Function to get object providing the current integration origins.
int getConventionalStateSize ()
Function to return the size of the state handled by the object.
Eigen::Vector3d getTotalAccelerationForBody (const std::string &bodyName)
Function to retrieve the total acceleration acting on a given body.
TranslationalPropagatorType getTranslationalPropagatorType ()
Function to get type of propagator that is to be used (i.e. Cowell, Encke, etc.)
void updateStateDerivativeModel (const TimeType currentTime)
Function to update the state derivative model to the current time.
Public Member Functions inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
SingleStateTypeDerivative (const IntegratedStateType integratedStateType)
Constructor.
virtual ~SingleStateTypeDerivative ()
Virtual destructor.
IntegratedStateType getIntegratedStateType ()
Function to return the type of dynamics for which the state derivative is calculated.
virtual int getPropagatedStateSize ()
Function to return the size of the propagated state handled by the object.
virtual bool isStateToBePostProcessed ()
Function to return whether the state needs to be post-processed.
virtual void postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState)
Function to process the state vector during propagation.
virtual void postProcessState (Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &unprocessedState)
Private Member Functions
void calculateKeplerTrajectoryCartesianState (const TimeType time, const int bodyIndex)
Function to calculate and set the reference Kepler orbit in Cartesian coordinates for given body.
void calculateKeplerTrajectoryCartesianStates (const TimeType time)
Function to calculate and set the reference Kepler orbit in Cartesian coordinates for all bodies.
Private Attributes
std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > centralAccelerations_
Central body accelerations for each propagated body, which has been removed from accelerationModelsPerBody_/.
std::vector< std::function< double() > > centralBodyGravitationalParameters_
Gravitational parameters of central bodies used to convert Cartesian to Keplerian orbits, and vice versa.
std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > currentKeplerianOrbitCartesianState_
TimeType currentKeplerOrbitTime_
std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > initialKeplerElements_
Kepler elements of bodiesToIntegrate, valid at initialTime_.
TimeType initialTime_
Time at which the initialKeplerElements provide the reference Keper orbit.
basic_astrodynamics::AccelerationMap originalAccelerationModelsPerBody_
std::shared_ptr< root_finders::RootFinderCore< StateScalarType > > rootFinder_
Root finder used to propagate Kepler orbit.
Additional Inherited Members
Protected Member Functions inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
void createAccelerationModelList ()
void sumStateDerivativeContributions (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative, const bool addPositionDerivatives=true)
Function to get the state derivative of the system in Cartesian coordinates.
void sumStateDerivativeContributions (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &stateDerivative, const bool addPositionDerivatives=true)
Function to get the state derivative of the system in Cartesian coordinates.
Protected Attributes inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > accelerationModelList_
Vector of acceleration models, containing all entries of accelerationModelsPerBody_.
basic_astrodynamics::AccelerationMap accelerationModelsPerBody_
A map containing the list of accelerations acting on each body,.
std::vector< std::string > bodiesToBeIntegratedNumerically_
List of names of bodies that are to be integrated numerically.
std::vector< int > bodyOrder_
std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData_
Object responsible for providing the current integration origins from the global origins.
std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > centralBodyStatesWrtGlobalOrigin_
List of states of the central bodies of the propagated bodies.
std::unordered_map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > >::iterator innerAccelerationIterator
Predefined iterator to save (de-)allocation time.
std::unordered_map< std::string, std::unordered_map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > > >::iterator outerAccelerationIterator
Predefined iterator to save (de-)allocation time.
TranslationalPropagatorType propagatorType_
Type of propagator that is to be used (i.e. Cowell, Encke, etc.)
Protected Attributes inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
IntegratedStateType integratedStateType_
Type of dynamics for which the state derivative is calculated.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > unprocessedState_
Vector used during post-processing of state.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >
Class for computing the state derivative of translational motion of N bodies, using an Encke propagator. The Encke propagator propagates the Cartesian deviation from an ideal (pre-defined) Keplerian orbit. See e.g. Wakker, Astrodynamics II for mathematical details.
Definition at line 50 of file nBodyEnckeStateDerivative.h.
Constructor & Destructor Documentation
NBodyEnckeStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::NBodyEnckeStateDerivative (const basic_astrodynamics::AccelerationMap & accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const std::vector< std::string > & bodiesToIntegrate, const std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > & initialKeplerElements, const TimeType & initialTime) inline
Constructor, computes required reference quantities, and removes central gravity from acceleration list. For a spherical harmonic central gravity, the C(0,0) coefficient is set to zero.
Parameters
accelerationModelsPerBody A map containing the list of accelerations acting on each body, identifying the body being acted on and the body acted on by an acceleration. The map has as key a string denoting the name of the body the list of accelerations, provided as the value corresponding to a key, is acting on. This map-value is again a map with string as key, denoting the body exerting the acceleration, and as value a pointer to an acceleration model.
centralBodyData Object responsible for providing the current integration origins from the global origins.
bodiesToIntegrate List of names of bodies that are to be integrated numerically.
initialKeplerElements Kepler elements of bodiesToIntegrate, valid at initialTime.
initialTime Time at which the initialKeplerElements provide the orbital state.
Definition at line 70 of file nBodyEnckeStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::accelerationModelsPerBody_, tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::createAccelerationModelList(), tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerianOrbitCartesianState_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_, tudat::propagators::removeCentralGravityAccelerations(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::rootFinder_.
Member Function Documentation
clearDerivedStateDerivativeModel()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::clearDerivedStateDerivativeModel () inline
Function to clear reference values of Encke state derivative model, in addition to those performed in the clearTranslationalStateDerivativeModel function. It resets the currentKeplerOrbitTime_ to ensure that the reference orbit is recomputed.
Definition at line 110 of file nBodyEnckeStateDerivative.h.
References tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerOrbitTime_, and TUDAT_NAN.
calculateSystemStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative) inline virtual
Calculates the state derivative the translational motion of the system at the given time and state of bodies. The velocity and acceleration of each body w.r.t. their reference Kepler orbits are computed by this function, i.e. the derivative of the Encke state.
Parameters
time Time (TDB seconds since J2000) at which the system is to be updated.
stateOfSystemToBeIntegrated List of 6 * bodiesToBeIntegratedNumerically_.size(), containing Cartesian position/velocity deviations from the reference Kepler orbits of the bodies being integrated. The order of the values is defined by the order of bodies in bodiesToBeIntegratedNumerically_
stateDerivative Current derivative of Encke state (velocity + acceleration w.r.t. reference Kepler orbit) of system of bodies integrated numerically (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 127 of file nBodyEnckeStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::calculateEnckeQFunction(), tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianStates(), tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerianOrbitCartesianState_, and tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::sumStateDerivativeContributions().
convertFromOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & cartesianSolution, const TimeType & time) inline virtual
Function to convert the state in the conventional form to the propagator-specific form. For the Encke propagator, this transforms the Cartesian state w.r.t. the central body (conventional form) to the Cartesian deviation from the Kepler orbit w.r.t. this central body (Encke form).
Parameters
cartesianSolution State in 'conventional form'
time Current time at which the state is valid, used to computed Kepler orbits
Returns
State (outputSolution), converted to the Encke-propagator-specific form
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 180 of file nBodyEnckeStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianStates(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerianOrbitCartesianState_.
convertToOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton) inline virtual
Function to convert the Encle-propagator-specific form of the state to the conventional form. For the Encke propagator, this transforms the Cartesian deviation from the Kepler orbit w.r.t. this central body (Encke form) to Cartesian state w.r.t. the central body (conventional form). In contrast to the convertCurrentStateToGlobalRepresentation function, this function does not provide the state in the inertial frame, but instead provides it in the frame in which it is propagated.
Parameters
internalSolution State in Encke-propagator-specific form (i.e. form that is used in numerical integration)/
time Current time at which the state is valid
currentCartesianLocalSoluton State (internalSolution, which is Encke-formulation), converted to the 'conventional form'.
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 213 of file nBodyEnckeStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianStates(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerianOrbitCartesianState_.
getFullAccelerationsMap()
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::AccelerationMap tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::getFullAccelerationsMap () inline virtual
Function to get map containing the list of accelerations acting on each body,
Returns
A map containing the list of accelerations acting on each body,
Reimplemented from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >.
Definition at line 228 of file nBodyEnckeStateDerivative.h.
References tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_.
calculateKeplerTrajectoryCartesianState()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianState (const TimeType time, const int bodyIndex) inline private
Function to calculate and set the reference Kepler orbit in Cartesian coordinates for given body.
Parameters
time Time at which Kepler orbit is to be computed.
bodyIndex Index in list of bodies for which Kepler orbit is to be computed.
Definition at line 241 of file nBodyEnckeStateDerivative.h.
References tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerianOrbitCartesianState_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::initialKeplerElements_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::initialTime_, and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::rootFinder_.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianStates().
calculateKeplerTrajectoryCartesianStates()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianStates (const TimeType time) inline private
Function to calculate and set the reference Kepler orbit in Cartesian coordinates for all bodies.
Parameters
time Time at which Kepler orbits are to be computed.
Definition at line 260 of file nBodyEnckeStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianState(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerOrbitTime_.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::convertToOutputSolution().
Member Data Documentation
centralBodyGravitationalParameters_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::function< double() > > tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_ private
Definition at line 276 of file nBodyEnckeStateDerivative.h.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianState(), tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::NBodyEnckeStateDerivative().
initialKeplerElements_
template<typename StateScalarType = double, typename TimeType = double> std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::initialKeplerElements_ private
Definition at line 279 of file nBodyEnckeStateDerivative.h.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianState().
initialTime_
template<typename StateScalarType = double, typename TimeType = double> TimeType tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::initialTime_ private
Definition at line 282 of file nBodyEnckeStateDerivative.h.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianState().
centralAccelerations_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::centralAccelerations_ private
Definition at line 286 of file nBodyEnckeStateDerivative.h.
rootFinder_
template<typename StateScalarType = double, typename TimeType = double> std::shared_ptr< root_finders::RootFinderCore< StateScalarType > > tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::rootFinder_ private
Definition at line 289 of file nBodyEnckeStateDerivative.h.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianState(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::NBodyEnckeStateDerivative().
currentKeplerianOrbitCartesianState_
template<typename StateScalarType = double, typename TimeType = double> std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerianOrbitCartesianState_ private
Current Cartesian states of reference Kepler orbits, valid at currentKeplerOrbitTime_, computed by calculateKeplerTrajectoryCartesianStates
Definition at line 293 of file nBodyEnckeStateDerivative.h.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianState(), tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::NBodyEnckeStateDerivative().
currentKeplerOrbitTime_
template<typename StateScalarType = double, typename TimeType = double> TimeType tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::currentKeplerOrbitTime_ private
Time at which the currentKeplerianOrbitCartesianState_ provide the Cartesian representation of the referfence Kepler state.
Definition at line 297 of file nBodyEnckeStateDerivative.h.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::calculateKeplerTrajectoryCartesianStates(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::clearDerivedStateDerivativeModel().
originalAccelerationModelsPerBody_
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::AccelerationMap tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_ private
Definition at line 299 of file nBodyEnckeStateDerivative.h.
Referenced by tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::getFullAccelerationsMap(), and tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >::NBodyEnckeStateDerivative().
The documentation for this class was generated from the following file:
Astrodynamics/Propagators/nBodyEnckeStateDerivative.h