Tudat: tudat::propagators::MassPropagatorSettings< StateScalarType > Class Template Reference
tudat::propagators::MassPropagatorSettings< StateScalarType > Class Template Reference
Class for defining settings for propagating the mass of a body.
#include <propagationSettings.h>
Public Member Functions
MassPropagatorSettings (const std::vector< std::string > bodiesWithMassToPropagate, const std::map< std::string, std::shared_ptr< basic_astrodynamics::MassRateModel > > &massRateModels, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &initialBodyMasses, const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave=std::shared_ptr< DependentVariableSaveSettings >(), const double printInterval=TUDAT_NAN)
Constructor of mass state propagator settings, with single mass rate model per body.
MassPropagatorSettings (const std::vector< std::string > bodiesWithMassToPropagate, const std::map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::MassRateModel > > > &massRateModels, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &initialBodyMasses, const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave=std::shared_ptr< DependentVariableSaveSettings >(), const double printInterval=TUDAT_NAN)
Constructor of mass state propagator settings, with already-created mass rate models.
MassPropagatorSettings (const std::vector< std::string > bodiesWithMassToPropagate, const simulation_setup::SelectedMassRateModelMap &massRateSettings, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &initialBodyMasses, const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave=std::shared_ptr< DependentVariableSaveSettings >(), const double printInterval=TUDAT_NAN)
Constructor of mass state propagator settings, with settings for mass rate models.
basic_astrodynamics::MassRateModelMap getMassRateModelsMap () const
Function to get the mass-rate models map.
simulation_setup::SelectedMassRateModelMap getMassRateSettingsMap () const
Function to get the mass-rate settings map.
void resetIntegratedStateModels (const simulation_setup::NamedBodyMap &bodyMap, const basic_astrodynamics::AccelerationMap &accelerationMap)
Function to create the mass-rate models with support for thrust-acceleration-based mass-rate models.
virtual void resetIntegratedStateModels (const simulation_setup::NamedBodyMap &bodyMap)
Function to create the mass-rate models.
Public Member Functions inherited from tudat::propagators::SingleArcPropagatorSettings< StateScalarType >
SingleArcPropagatorSettings (const IntegratedStateType stateType, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > initialBodyStates, const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave=std::shared_ptr< DependentVariableSaveSettings >(), const double printInterval=TUDAT_NAN)
Constructor.
virtual ~SingleArcPropagatorSettings ()
Virtual destructor.
std::shared_ptr< DependentVariableSaveSettings > getDependentVariablesToSave ()
Function to retrieve settings for the dependent variables that are to be saved during propagation (default none).
double getPrintInterval ()
Function to retrieve how often the current state and time are to be printed to console.
IntegratedStateType getStateType ()
Type of state being propagated.
std::shared_ptr< PropagationTerminationSettings > getTerminationSettings ()
Function to retrieve settings for creating the object that checks whether the propagation is finished.
void resetDependentVariablesToSave (const std::shared_ptr< DependentVariableSaveSettings > &dependentVariablesToSave)
Function to reset settings for the dependent variables that are to be saved during propagation.
void resetTerminationSettings (const std::shared_ptr< PropagationTerminationSettings > terminationSettings)
Function to reset settings for creating the object that checks whether the propagation is finished.
void setTerminationSettings (std::shared_ptr< PropagationTerminationSettings > terminationSettings)
Function to modify settings for creating the object that checks whether the propagation is finished.
Public Member Functions inherited from tudat::propagators::PropagatorSettings< StateScalarType >
PropagatorSettings (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > initialBodyStates, const bool isMultiArc)
Constructor.
virtual ~PropagatorSettings ()
Destructor.
int getConventionalStateSize ()
Get total size of the conventional state.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > getInitialStates ()
Function to retrieve the initial state used as input for numerical integration.
bool getIsMultiArc ()
Function to get boolean denoting whether the propagation settings are multi-arc (if true) or single arc (if false).
virtual int getPropagatedStateSize ()
Get total size of the propagated state.
virtual void resetInitialStates (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &initialBodyStates)
Function to reset the initial state used as input for numerical integration.
Public Attributes
std::vector< std::string > bodiesWithMassToPropagate_
List of bodies for which the mass is to be propagated.
Private Attributes
basic_astrodynamics::MassRateModelMap massRateModels_
List of mass rate models per propagated body.
simulation_setup::SelectedMassRateModelMap massRateSettingsMap_
List of mass rate settings per propagated body.
Additional Inherited Members
Protected Attributes inherited from tudat::propagators::SingleArcPropagatorSettings< StateScalarType >
std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave_
Settings for the dependent variables that are to be saved during propagation (default none).
double printInterval_
IntegratedStateType stateType_
Type of state being propagated.
std::shared_ptr< PropagationTerminationSettings > terminationSettings_
Settings for creating the object that checks whether the propagation is finished.
Protected Attributes inherited from tudat::propagators::PropagatorSettings< StateScalarType >
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > initialStates_
Initial state used as input for numerical integration.
bool isMultiArc_
Boolean denoting whether the propagation settings are multi-arc (if true) or single arc (if false).
int stateSize_
Total size of the propagated state.
Detailed Description
template<typename StateScalarType>
class tudat::propagators::MassPropagatorSettings< StateScalarType >
Class for defining settings for propagating the mass of a body. The body masses are propagated in their natural form (i.e. no choice of equations of motion as is the case for translational dynamics)l
Definition at line 810 of file propagationSettings.h.
Constructor & Destructor Documentation
MassPropagatorSettings() [1/3]
template<typename StateScalarType> tudat::propagators::MassPropagatorSettings< StateScalarType >::MassPropagatorSettings (const std::vector< std::string > bodiesWithMassToPropagate, const std::map< std::string, std::shared_ptr< basic_astrodynamics::MassRateModel > > & massRateModels, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & initialBodyMasses, const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave = std::shared_ptr< DependentVariableSaveSettings >(), const double printInterval = TUDAT_NAN) inline
Constructor of mass state propagator settings, with single mass rate model per body.
Parameters
bodiesWithMassToPropagate List of bodies for which the mass is to be propagated.
massRateModels List of mass rate models per propagated body.
initialBodyMasses Initial masses used as input for numerical integration.
terminationSettings Settings for creating the object that checks whether the propagation is finished.
dependentVariablesToSave Settings for the dependent variables that are to be saved during propagation (default none).
printInterval Variable indicating how often (once per printInterval_ seconds or propagation independenty variable) the current state and time are to be printed to console (default never).
Definition at line 826 of file propagationSettings.h.
References tudat::propagators::MassPropagatorSettings< StateScalarType >::massRateModels_.
MassPropagatorSettings() [2/3]
template<typename StateScalarType> tudat::propagators::MassPropagatorSettings< StateScalarType >::MassPropagatorSettings (const std::vector< std::string > bodiesWithMassToPropagate, const std::map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::MassRateModel > > > & massRateModels, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & initialBodyMasses, const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave = std::shared_ptr< DependentVariableSaveSettings >(), const double printInterval = TUDAT_NAN) inline
Constructor of mass state propagator settings, with already-created mass rate models.
Parameters
bodiesWithMassToPropagate List of bodies for which the mass is to be propagated.
massRateModels List of mass rate models per propagated body.
initialBodyMasses Initial masses used as input for numerical integration.
terminationSettings Settings for creating the object that checks whether the propagation is finished.
dependentVariablesToSave Settings for the dependent variables that are to be saved during propagation (default none).
printInterval Variable indicating how often (once per printInterval_ seconds or propagation independenty variable) the current state and time are to be printed to console (default never).
Definition at line 857 of file propagationSettings.h.
MassPropagatorSettings() [3/3]
template<typename StateScalarType> tudat::propagators::MassPropagatorSettings< StateScalarType >::MassPropagatorSettings (const std::vector< std::string > bodiesWithMassToPropagate, const simulation_setup::SelectedMassRateModelMap & massRateSettings, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & initialBodyMasses, const std::shared_ptr< PropagationTerminationSettings > terminationSettings, const std::shared_ptr< DependentVariableSaveSettings > dependentVariablesToSave = std::shared_ptr< DependentVariableSaveSettings >(), const double printInterval = TUDAT_NAN) inline
Constructor of mass state propagator settings, with settings for mass rate models.
Parameters
bodiesWithMassToPropagate List of bodies for which the mass is to be propagated.
massRateSettings List of settings for mass rate models per propagated body.
initialBodyMasses Initial masses used as input for numerical integration.
terminationSettings Settings for creating the object that checks whether the propagation is finished.
dependentVariablesToSave Settings for the dependent variables that are to be saved during propagation (default none).
printInterval Variable indicating how often (once per printInterval_ seconds or propagation independenty variable) the current state and time are to be printed to console (default never).
Definition at line 882 of file propagationSettings.h.
Member Function Documentation
resetIntegratedStateModels() [1/2]
template<typename StateScalarType> void tudat::propagators::MassPropagatorSettings< StateScalarType >::resetIntegratedStateModels (const simulation_setup::NamedBodyMap & bodyMap, const basic_astrodynamics::AccelerationMap & accelerationMap) inline
Function to create the mass-rate models, with the possibility to specify an acceleration map for setting up mass-rate models determined from thrust accelerations.
Parameters
bodyMap Map of bodies in the propagation, with keys the names of the bodies.
accelerationMap Map of accelerations in the propagation.
Definition at line 904 of file propagationSettings.h.
References tudat::simulation_setup::createMassRateModelsMap(), tudat::propagators::MassPropagatorSettings< StateScalarType >::massRateModels_, and tudat::propagators::MassPropagatorSettings< StateScalarType >::massRateSettingsMap_.
Referenced by tudat::propagators::MassPropagatorSettings< StateScalarType >::resetIntegratedStateModels().
resetIntegratedStateModels() [2/2]
template<typename StateScalarType> virtual void tudat::propagators::MassPropagatorSettings< StateScalarType >::resetIntegratedStateModels (const simulation_setup::NamedBodyMap & bodyMap) inline virtual
Function to create the mass-rate models.
Parameters
bodyMap Map of bodies in the propagation, with keys the names of the bodies.
Implements tudat::propagators::PropagatorSettings< StateScalarType >.
Definition at line 916 of file propagationSettings.h.
References tudat::propagators::MassPropagatorSettings< StateScalarType >::resetIntegratedStateModels().
getMassRateSettingsMap()
template<typename StateScalarType> simulation_setup::SelectedMassRateModelMap tudat::propagators::MassPropagatorSettings< StateScalarType >::getMassRateSettingsMap () const inline
Function to get the mass-rate settings map.
Returns
The mass-rate settings map.
Definition at line 926 of file propagationSettings.h.
References tudat::propagators::MassPropagatorSettings< StateScalarType >::massRateSettingsMap_.
getMassRateModelsMap()
template<typename StateScalarType> basic_astrodynamics::MassRateModelMap tudat::propagators::MassPropagatorSettings< StateScalarType >::getMassRateModelsMap () const inline
Function to get the mass-rate models map.
Returns
The mass-rate models map.
Definition at line 936 of file propagationSettings.h.
References tudat::propagators::MassPropagatorSettings< StateScalarType >::massRateModels_, and tudat::propagators::MassPropagatorSettings< StateScalarType >::massRateSettingsMap_.
Member Data Documentation
bodiesWithMassToPropagate_
template<typename StateScalarType> std::vector< std::string > tudat::propagators::MassPropagatorSettings< StateScalarType >::bodiesWithMassToPropagate_
Definition at line 895 of file propagationSettings.h.
massRateSettingsMap_
template<typename StateScalarType> simulation_setup::SelectedMassRateModelMap tudat::propagators::MassPropagatorSettings< StateScalarType >::massRateSettingsMap_ private
Definition at line 950 of file propagationSettings.h.
Referenced by tudat::propagators::MassPropagatorSettings< StateScalarType >::getMassRateModelsMap(), tudat::propagators::MassPropagatorSettings< StateScalarType >::getMassRateSettingsMap(), and tudat::propagators::MassPropagatorSettings< StateScalarType >::resetIntegratedStateModels().
massRateModels_
template<typename StateScalarType> basic_astrodynamics::MassRateModelMap tudat::propagators::MassPropagatorSettings< StateScalarType >::massRateModels_ private
Definition at line 953 of file propagationSettings.h.
Referenced by tudat::propagators::MassPropagatorSettings< StateScalarType >::getMassRateModelsMap(), tudat::propagators::MassPropagatorSettings< StateScalarType >::MassPropagatorSettings(), and tudat::propagators::MassPropagatorSettings< StateScalarType >::resetIntegratedStateModels().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/propagationSettings.h