Tudat: tudat::simulation_setup::Body Class Reference
tudat::simulation_setup::Body Class Reference
Body class representing the properties of a celestial body (natural or artificial).
#include <body.h>
Public Member Functions
Body (const Eigen::Vector6d &state=Eigen::Vector6d::Zero())
Constructor for a body.
void addGroundStation (const std::string &stationName, const std::shared_ptr< ground_stations::GroundStation > &station)
Function to add a ground station to the body.
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > getAerodynamicCoefficientInterface ()
Function to retrieve the aerodynamic coefficient model of body.
std::shared_ptr< aerodynamics::AtmosphereModel > getAtmosphereModel ()
Function to get the atmosphere model of the body.
Eigen::Matrix3d getBodyInertiaTensor ()
Function to retrieve the body moment-of-inertia tensor.
double getBodyMass ()
Function to retrieve the current body mass.
std::function< double(const double) > getBodyMassFunction ()
Function to get the function returning body mass as a function of time.
Eigen::Vector3d getCurrentAngularVelocityVectorInGlobalFrame ()
Get current angular velocity vector for body's rotation, expressed in the global frame.
Eigen::Vector3d getCurrentAngularVelocityVectorInLocalFrame ()
Get current angular velocity vector for body's rotation, expressed in the local frame.
Eigen::Vector7d getCurrentRotationalState ()
Get current rotational state.
Eigen::Matrix3d getCurrentRotationMatrixDerivativeToGlobalFrame ()
Get current rotation matrix derivative from body-fixed to global frame.
Eigen::Matrix3d getCurrentRotationMatrixDerivativeToLocalFrame ()
Get current rotation matrix derivative from global to body-fixed frame.
Eigen::Quaterniond getCurrentRotationToGlobalFrame ()
Get current rotation from body-fixed to inertial frame.
Eigen::Quaterniond getCurrentRotationToLocalFrame ()
Get current rotation from inertial to body-fixed frame.
std::shared_ptr< reference_frames::DependentOrientationCalculator > getDependentOrientationCalculator ()
Function to retrieve the model to compute the rotation of the body based on the current state of the environment.
std::shared_ptr< ephemerides::Ephemeris > getEphemeris ()
Function to get the ephemeris of the body.
std::shared_ptr< BaseStateInterface > getEphemerisFrameToBaseFrame ()
Function to retrieve the class returning the state of this body's ephemeris origin w.r.t. the global origin.
std::shared_ptr< aerodynamics::FlightConditions > getFlightConditions ()
Function to retrieve the body flight conditions.
template<typename StateScalarType = double, typename TimeType = double>
Eigen::Matrix< StateScalarType, 6, 1 > getGlobalFrameOriginBarycentricStateFromEphemeris (const TimeType time)
Templated function to get the current berycentric state of the body from its ephemeris andcglobal-to-ephemeris-frame function.
std::shared_ptr< gravitation::GravityFieldModel > getGravityFieldModel ()
Function to get the gravity field model of the body.
std::pair< bool, std::shared_ptr< gravitation::GravityFieldVariations > > getGravityFieldVariation (const gravitation::BodyDeformationTypes &deformationType, const std::string identifier="")
Function to retrieve a single object describing variation in the gravity field of this body.
std::shared_ptr< gravitation::GravityFieldVariationsSet > getGravityFieldVariationSet ()
Function to retrieve object containing all variations in the gravity field of this body.
std::shared_ptr< ground_stations::GroundStation > getGroundStation (const std::string &stationName) const
Function to retrieve a ground station.
std::map< std::string, std::shared_ptr< ground_stations::GroundStation > > getGroundStationMap () const
Function to retrieve full list of ground stations.
int getIsBodyGlobalFrameOrigin ()
Function to retrieve variable denoting whether this body is the global frame origin.
Eigen::Matrix< long double, 3, 1 > getLongPosition ()
Get current position, in long double precision.
Eigen::Matrix< long double, 6, 1 > getLongState ()
Get current state, in long double precision.
Eigen::Matrix< long double, 3, 1 > getLongVelocity ()
Get current velocity, in long double precision.
Eigen::Vector3d getPosition ()
Get current position.
std::map< std::string, std::shared_ptr< electro_magnetism::RadiationPressureInterface > > getRadiationPressureInterfaces ()
Function to retrieve the shape model of the body.
std::shared_ptr< ephemerides::RotationalEphemeris > getRotationalEphemeris ()
Function to get the rotation model of the body.
std::shared_ptr< basic_astrodynamics::BodyShapeModel > getShapeModel ()
Function to retrieve the shape model of body.
Eigen::Vector6d getState ()
Get current state.
template<typename StateScalarType = double, typename TimeType = double>
Eigen::Matrix< StateScalarType, 6, 1 > getStateInBaseFrameFromEphemeris (const TimeType time)
Templated function to get the current state of the body from its ephemeris and global-to-ephemeris-frame function.
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedState ()
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedState ()
template<typename ScalarStateType >
Eigen::Matrix< ScalarStateType, 6, 1 > getTemplatedState ()
Templated function to retrieve the state.
std::shared_ptr< system_models::VehicleSystems > getVehicleSystems ()
Function to retrieve container object with hardware systems present on/in body.
Eigen::Vector3d getVelocity ()
Get current velocity.
void recomputeStateOnNextCall ()
Function to indicate that the state needs to be recomputed on next call to setStateFromEphemeris.
void setAerodynamicCoefficientInterface (const std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > aerodynamicCoefficientInterface)
Function to set the aerodynamic coefficient interface of the body.
void setAtmosphereModel (const std::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel)
Function to set the atmosphere model of the body.
void setBodyInertiaTensor (const Eigen::Matrix3d &bodyInertiaTensor)
Function to (re)set the body moment-of-inertia tensor.
void setBodyMassFunction (const std::function< double(const double) > bodyMassFunction)
Function to set the function returning body mass as a function of time.
void setConstantBodyMass (const double bodyMass)
Function to set the body mass as being constant (i.e. time-independent)
void setCurrentAngularVelocityVectorInGlobalFrame (const double time)
Function to set the angular velocity vector in the global frame at given time.
void setCurrentRotationalStateToLocalFrame (const Eigen::Vector7d currentRotationalStateFromLocalToGlobalFrame)
Function to set the full rotational state directly.
template<typename TimeType >
void setCurrentRotationalStateToLocalFrameFromEphemeris (const TimeType time)
Function to set the full rotational state at given time.
void setCurrentRotationToLocalFrameDerivativeFromEphemeris (const double time)
Function to set the rotation matrix derivative from global to body-fixed frame at given time.
void setCurrentRotationToLocalFrameFromEphemeris (const double time)
Function to set the rotation from global to body-fixed frame at given time.
void setDependentOrientationCalculator (const std::shared_ptr< reference_frames::DependentOrientationCalculator > dependentOrientationCalculator)
Function to set a rotation model that is only valid during numerical propagation.
void setEphemeris (const std::shared_ptr< ephemerides::Ephemeris > bodyEphemeris)
Function to set the ephemeris of the body.
void setEphemerisFrameToBaseFrame (const std::shared_ptr< BaseStateInterface > ephemerisFrameToBaseFrame)
Function to set the class returning the state of this body's ephemeris origin w.r.t. the global origin.
void setFlightConditions (const std::shared_ptr< aerodynamics::FlightConditions > aerodynamicFlightConditions)
Function to set the body flight conditions.
void setGravityFieldModel (const std::shared_ptr< gravitation::GravityFieldModel > gravityFieldModel)
Function to set the gravity field of the body.
void setGravityFieldVariationSet (const std::shared_ptr< gravitation::GravityFieldVariationsSet > gravityFieldVariationSet)
Function to set object containing all variations in the gravity field of this body.
void setIsBodyGlobalFrameOrigin (const int bodyIsGlobalFrameOrigin)
Function to set variable denoting whether this body is the global frame origin.
void setLongState (const Eigen::Matrix< long double, 6, 1 > &longState)
Set current state of body manually in long double precision.
void setRadiationPressureInterface (const std::string &radiatingBody, const std::shared_ptr< electro_magnetism::RadiationPressureInterface > radiationPressureInterface)
Function to set the radiation pressure interface of the body, for a single radiation source.
void setRotationalEphemeris (const std::shared_ptr< ephemerides::RotationalEphemeris > rotationalEphemeris)
Function to set the rotation model of the body.
void setShapeModel (const std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel)
Function to set the shape model of the body.
void setState (const Eigen::Vector6d &state)
Set current state of body manually.
template<typename StateScalarType = double, typename TimeType = double>
void setStateFromEphemeris (const TimeType &time)
Templated function to set the current state of the body from its ephemeris and global-to-ephemeris-frame function.
template<>
void setTemplatedState (const Eigen::Matrix< double, 6, 1 > &state)
Templated function to set the state manually.
template<>
void setTemplatedState (const Eigen::Matrix< long double, 6, 1 > &state)
Templated function to set the state manually.
template<typename StateScalarType >
void setTemplatedState (const Eigen::Matrix< StateScalarType, 6, 1 > &state)
Templated function to set the state manually.
void setVehicleSystems (const std::shared_ptr< system_models::VehicleSystems > vehicleSystems)
Function to set container object with hardware systems present on/in body.
void updateConstantEphemerisDependentMemberQuantities ()
Function to recompute the internal variables of member variables that depend on the ephemerides bodies.
void updateMass (const double time)
Function to update the body mass to the current time.
Private Attributes
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > aerodynamicCoefficientInterface_
Aerodynamic coefficient model of body.
std::shared_ptr< aerodynamics::FlightConditions > aerodynamicFlightConditions_
Object used for calculating current aerodynamic angles, altitude, etc.
std::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel_
Atmosphere model of body.
std::shared_ptr< ephemerides::Ephemeris > bodyEphemeris_
Ephemeris of body.
Eigen::Matrix3d bodyInertiaTensor_
Body moment-of-inertia tensor.
int bodyIsGlobalFrameOrigin_
Variable denoting whether this body is the global frame origin (1 if true, 0 if false, -1 if not yet set)
std::function< double(const double) > bodyMassFunction_
Function returning body mass as a function of time.
Eigen::Vector3d currentAngularVelocityVectorInGlobalFrame_
Current angular velocity vector for body's rotation, expressed in the global frame.
Eigen::Matrix< long double, 6, 1 > currentBarycentricLongState_
Current state with long double precision.
Eigen::Vector6d currentBarycentricState_
Current state.
Eigen::Matrix< long double, 6, 1 > currentLongState_
Current state with long double precision.
double currentMass_
Mass of body (default set to zero, calculated from GravityFieldModel when it is set).
Eigen::Quaterniond currentRotationToLocalFrame_
Current rotation from the global to the body-fixed frame.
Eigen::Matrix3d currentRotationToLocalFrameDerivative_
Eigen::Vector6d currentState_
Current state.
std::shared_ptr< reference_frames::DependentOrientationCalculator > dependentOrientationCalculator_
Model to compute the rotation of the body based on the current state of the environment, only valid during propagation.
std::shared_ptr< BaseStateInterface > ephemerisFrameToBaseFrame_
std::shared_ptr< gravitation::GravityFieldModel > gravityFieldModel_
Gravity field model of body.
std::shared_ptr< gravitation::GravityFieldVariationsSet > gravityFieldVariationSet_
Object containing all variations in the gravity field of this body.
std::map< std::string, std::shared_ptr< ground_stations::GroundStation > > groundStationMap
List of ground station objects on Body.
std::map< std::string, std::shared_ptr< electro_magnetism::RadiationPressureInterface > > radiationPressureInterfaces_
List of radiation pressure models for the body, with the sources bodies as key.
std::map< std::string, std::shared_ptr< electro_magnetism::RadiationPressureInterface > >::iterator radiationPressureIterator_
Predefined iterator for efficiency purposes.
std::shared_ptr< ephemerides::RotationalEphemeris > rotationalEphemeris_
Rotation model of body.
std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel_
Shape model of body.
Time timeOfCurrentState_
Time at which state was last set from ephemeris.
std::shared_ptr< system_models::VehicleSystems > vehicleSystems_
Container object with hardware systems present on/in body (typically only non-nullptr for a vehicle).
Detailed Description
Body class representing the properties of a celestial body (natural or artificial). By storing all properties of bodies (ephemeris, rotation, gravity, etc.) in a set of body objects, the simulation environment can be defined in a clear and modular way. To create body objects, the createBodies.h function provides a range of functionality. The createAccelerationModels.h file provides functions to use body objects to create acceleration objects.
Definition at line 215 of file body.h.
Constructor & Destructor Documentation
Body()
tudat::simulation_setup::Body::Body (const Eigen::Vector6d & state = Eigen::Vector6d::Zero()) inline
Constructor for a body, sets current state (with zero default value).
Parameters
state Current state of body at initialization (default = zeroes).
Definition at line 224 of file body.h.
Member Function Documentation
getEphemerisFrameToBaseFrame()
std::shared_ptr< BaseStateInterface > tudat::simulation_setup::Body::getEphemerisFrameToBaseFrame () inline
Function to retrieve the class returning the state of this body's ephemeris origin w.r.t. the global origin
Returns
Class returning the state of this body's ephemeris origin w.r.t. the global origin
Definition at line 243 of file body.h.
References ephemerisFrameToBaseFrame_.
setEphemerisFrameToBaseFrame()
void tudat::simulation_setup::Body::setEphemerisFrameToBaseFrame (const std::shared_ptr< BaseStateInterface > ephemerisFrameToBaseFrame) inline
Function to set the class returning the state of this body's ephemeris origin w.r.t. the global origin
Parameters
ephemerisFrameToBaseFrame Class returning the state of this body's ephemeris origin w.r.t. the global origin
Definition at line 253 of file body.h.
References ephemerisFrameToBaseFrame_.
setState()
void tudat::simulation_setup::Body::setState (const Eigen::Vector6d & state) inline
Set current state of body manually, which must be in the global frame. Note that this function does not set the currentLongState_, use the setLongState when needing the use of the long precision current state.
Parameters
state Current state of the body that is set.
Definition at line 265 of file body.h.
References currentState_.
Referenced by tudat::simulation_setup::createAnalyticalAccelerationPartial(), and setTemplatedState().
setLongState()
void tudat::simulation_setup::Body::setLongState (const Eigen::Matrix< long double, 6, 1 > & longState) inline
Set current state of body manually in long double precision. State must be in the global frame. Note that this function sets both the currentState_ and currentLongState_ variables (currentLongState_ directly and currentState_ by casting the input to double entries).
Parameters
longState Current state of the body that is set, in long double precision.
Definition at line 277 of file body.h.
References currentLongState_, and currentState_.
Referenced by setTemplatedState().
setTemplatedState() [1/3]
template<typename StateScalarType > void tudat::simulation_setup::Body::setTemplatedState (const Eigen::Matrix< StateScalarType, 6, 1 > & state)
Templated function to set the state manually, calls either setState or setLongState function.
Parameters
state Current state of the body that is set, with StateScalarType precision.
setStateFromEphemeris()
template<typename StateScalarType = double, typename TimeType = double> void tudat::simulation_setup::Body::setStateFromEphemeris (const TimeType & time) inline
Templated function to set the current state of the body from its ephemeris and global-to-ephemeris-frame function.
It sets both the currentState_ and currentLongState_ variables. F FUndamental coputation is done on state with StateScalarType precision as a function of TimeType time
Parameters
time Time at which the global state is to be set.
Definition at line 300 of file body.h.
References bodyEphemeris_, bodyIsGlobalFrameOrigin_, currentBarycentricLongState_, currentBarycentricState_, currentLongState_, currentState_, ephemerisFrameToBaseFrame_, and timeOfCurrentState_.
getStateInBaseFrameFromEphemeris()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, 6, 1 > tudat::simulation_setup::Body::getStateInBaseFrameFromEphemeris (const TimeType time) inline
Templated function to get the current state of the body from its ephemeris and global-to-ephemeris-frame function.
It calls the setStateFromEphemeris state, resetting the currentState_ / currentLongState_ variables, and returning the state with the requested precision
Parameters
time Time at which to evaluate states.
Returns
State at requested time
Definition at line 366 of file body.h.
References currentLongState_, and currentState_.
Referenced by tudat::propagators::createCentralBodyData(), tudat::observation_models::ObservationModelCreator< 3, ObservationScalarType, TimeType >::createObservationModel(), and tudat::observation_models::createReferencePointEphemeris().
getGlobalFrameOriginBarycentricStateFromEphemeris()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, 6, 1 > tudat::simulation_setup::Body::getGlobalFrameOriginBarycentricStateFromEphemeris (const TimeType time) inline
Templated function to get the current berycentric state of the body from its ephemeris andcglobal-to-ephemeris-frame function.
It calls the setStateFromEphemeris state, resetting the currentBarycentricState_ / currentBarycentricLongState_ variables, and returning the state with the requested precision. This function can ONLY be called if this body is the global frame origin, otherwise an exception is thrown
Parameters
time Time at which to evaluate states.
Returns
Barycentric State at requested time
Definition at line 390 of file body.h.
References bodyIsGlobalFrameOrigin_, currentBarycentricLongState_, and currentBarycentricState_.
getState()
Eigen::Vector6d tudat::simulation_setup::Body::getState () inline
Returns the internally stored current state vector.
Returns
Current state.
Definition at line 414 of file body.h.
References currentState_.
Referenced by tudat::simulation_setup::createAnalyticalAccelerationPartial(), tudat::simulation_setup::createAtmosphericFlightConditions(), tudat::simulation_setup::createDirectTidalDissipationAcceleration(), tudat::simulation_setup::createEmpiricalAcceleration(), tudat::simulation_setup::createFlightConditions(), tudat::simulation_setup::createGravityFieldVariationsModel(), tudat::simulation_setup::createRelativisticCorrectionAcceleration(), tudat::simulation_setup::createThrustAcceleratioModel(), tudat::simulation_setup::createThrustGuidanceModel(), tudat::propagators::getDoubleDependentVariableFunction(), getTemplatedState(), and tudat::propagators::getVectorDependentVariableFunction().
getPosition()
Eigen::Vector3d tudat::simulation_setup::Body::getPosition () inline
Returns the internally stored current position vector.
Returns
Current position.
Definition at line 421 of file body.h.
References currentState_.
Referenced by tudat::simulation_setup::createCannonballRadiationPressureAcceleratioModel(), tudat::simulation_setup::createCentralGravityAcceleratioModel(), tudat::simulation_setup::createMutualSphericalHarmonicsGravityAcceleration(), tudat::simulation_setup::createRadiationPressureInterface(), tudat::simulation_setup::createSecondDegreeGravitationalTorqueModel(), tudat::simulation_setup::createSphericalHarmonicsGravityAcceleration(), tudat::simulation_setup::createTidalLoveNumberInterfaces(), tudat::propagators::getDoubleDependentVariableFunction(), tudat::simulation_setup::getOccultingBodiesInformation(), and tudat::propagators::getVectorDependentVariableFunction().
getVelocity()
Eigen::Vector3d tudat::simulation_setup::Body::getVelocity () inline
Returns the internally stored current velocity vector.
Returns
Current velocity.
Definition at line 428 of file body.h.
References currentState_.
Referenced by tudat::propagators::getDoubleDependentVariableFunction(), and tudat::propagators::getVectorDependentVariableFunction().
getLongState()
Eigen::Matrix< long double, 6, 1 > tudat::simulation_setup::Body::getLongState () inline
Returns the internally stored current state vector, in long double precision
Returns
Current state, in long double precisio
Definition at line 435 of file body.h.
References currentLongState_.
Referenced by getTemplatedState().
getLongPosition()
Eigen::Matrix< long double, 3, 1 > tudat::simulation_setup::Body::getLongPosition () inline
Returns the internally stored current position vector, in long double precision
Returns
Current position, in long double precision
Definition at line 442 of file body.h.
References currentLongState_.
getLongVelocity()
Eigen::Matrix< long double, 3, 1 > tudat::simulation_setup::Body::getLongVelocity () inline
Returns the internally stored current velocity vector.
Returns
Current velocity, in long double precision
Definition at line 449 of file body.h.
References currentLongState_.
getTemplatedState() [1/3]
template<typename ScalarStateType > Eigen::Matrix< ScalarStateType, 6, 1 > tudat::simulation_setup::Body::getTemplatedState ()
Templated function to retrieve the state, calls either getState or getLongState function.
Returns
Current state of the body, with StateScalarType precision.
setCurrentRotationToLocalFrameFromEphemeris()
void tudat::simulation_setup::Body::setCurrentRotationToLocalFrameFromEphemeris (const double time) inline
Function to set the rotation from global to body-fixed frame at given time, using the rotationalEphemeris_ member object
Parameters
time Time at which the rotation is to be retrieved.
Definition at line 465 of file body.h.
References currentRotationToLocalFrame_, dependentOrientationCalculator_, and rotationalEphemeris_.
setCurrentRotationToLocalFrameDerivativeFromEphemeris()
void tudat::simulation_setup::Body::setCurrentRotationToLocalFrameDerivativeFromEphemeris (const double time) inline
Function to set the rotation matrix derivative from global to body-fixed frame at given time, using the rotationalEphemeris_ member object
Parameters
time Time at which the rotation matrix derivative is to be retrieved.
Definition at line 488 of file body.h.
References currentRotationToLocalFrameDerivative_, dependentOrientationCalculator_, and rotationalEphemeris_.
setCurrentAngularVelocityVectorInGlobalFrame()
void tudat::simulation_setup::Body::setCurrentAngularVelocityVectorInGlobalFrame (const double time) inline
Function to set the angular velocity vector in the global frame at given time, using the rotationalEphemeris_ member object
Parameters
time Time at which the angular velocity vector in the global frame is to be retrieved.
Definition at line 512 of file body.h.
References currentAngularVelocityVectorInGlobalFrame_, dependentOrientationCalculator_, and rotationalEphemeris_.
setCurrentRotationalStateToLocalFrameFromEphemeris()
template<typename TimeType > void tudat::simulation_setup::Body::setCurrentRotationalStateToLocalFrameFromEphemeris (const TimeType time) inline
Function to set the full rotational state at (rotation from global to body-fixed frame rotation matrix derivative from global to body-fixed frame and angular velocity vector in the global frame) at given time, using the rotationalEphemeris_ member object.
Parameters
time Time at which the angular velocity vector in the global frame is to be retrieved.
Definition at line 538 of file body.h.
References currentAngularVelocityVectorInGlobalFrame_, currentRotationToLocalFrame_, currentRotationToLocalFrameDerivative_, dependentOrientationCalculator_, and rotationalEphemeris_.
setCurrentRotationalStateToLocalFrame()
void tudat::simulation_setup::Body::setCurrentRotationalStateToLocalFrame (const Eigen::Vector7d currentRotationalStateFromLocalToGlobalFrame) inline
Function to set the full rotational state directly (rotation from global to body-fixed frame rotation matrix derivative from global to body-fixed frame and angular velocity vector in the global frame) directly, by providing the current rotational state as input.
Parameters
currentRotationalStateFromLocalToGlobalFrame Quaternion from body-fixed to propagation frame (in vector form) and the body's angular velocity vector in body-fixed frame.
Definition at line 567 of file body.h.
References currentAngularVelocityVectorInGlobalFrame_, currentRotationToLocalFrame_, currentRotationToLocalFrameDerivative_, and tudat::linear_algebra::getCrossProductMatrix().
getCurrentRotationToGlobalFrame()
Eigen::Quaterniond tudat::simulation_setup::Body::getCurrentRotationToGlobalFrame () inline
Get current rotation from body-fixed to inertial frame, as set from the rotationalEphemeris_ by the setCurrentRotationalStateToLocalFrameFromEphemeris or setCurrentRotationToLocalFrameFromEphemeris function. If body has no rotational ephemeris, an identity quaternion (no rotation) is returned.
Returns
Current rotation from body-fixed to inertial frame.
Definition at line 593 of file body.h.
References currentRotationToLocalFrame_.
Referenced by tudat::simulation_setup::createAerodynamicAcceleratioModel(), tudat::simulation_setup::createAerodynamicTorqueModel(), tudat::simulation_setup::createAtmosphericFlightConditions(), tudat::simulation_setup::createFlightConditions(), tudat::simulation_setup::createMutualSphericalHarmonicsGravityAcceleration(), tudat::simulation_setup::createSphericalHarmonicsGravityAcceleration(), tudat::simulation_setup::createThrustGuidanceModel(), and getCurrentRotationalState().
getCurrentRotationToLocalFrame()
Eigen::Quaterniond tudat::simulation_setup::Body::getCurrentRotationToLocalFrame () inline
Get current rotation from inertial to body-fixed frame, as set from the rotationalEphemeris_ by the setCurrentRotationalStateToLocalFrameFromEphemeris or setCurrentRotationToLocalFrameFromEphemeris function. If body has no rotational ephemeris, an identity quaternion (no rotation) is returned.
Returns
Current rotation from inertial to body-fixed frame.
Definition at line 606 of file body.h.
References currentRotationToLocalFrame_.
Referenced by tudat::simulation_setup::createAtmosphericFlightConditions(), tudat::simulation_setup::createFlightConditions(), tudat::simulation_setup::createGravityFieldVariationsModel(), tudat::simulation_setup::createSecondDegreeGravitationalTorqueModel(), tudat::simulation_setup::createTidalLoveNumberInterfaces(), getCurrentAngularVelocityVectorInLocalFrame(), tudat::propagators::getVectorDependentVariableFunction(), and tudat::propagators::setMultiTypePropagationClosure().
getCurrentRotationalState()
Eigen::Vector7d tudat::simulation_setup::Body::getCurrentRotationalState () inline
Get current rotational state, expressed as a quaternion from global to body-fixed frame (in vector form) and the body's angular velocity vector in inertial frame.
Returns
Current rotational state in quaternions and rotational velocity.
Definition at line 617 of file body.h.
References tudat::linear_algebra::convertQuaternionToVectorFormat(), getCurrentAngularVelocityVectorInGlobalFrame(), and getCurrentRotationToGlobalFrame().
getCurrentRotationMatrixDerivativeToGlobalFrame()
Eigen::Matrix3d tudat::simulation_setup::Body::getCurrentRotationMatrixDerivativeToGlobalFrame () inline
Get current rotation matrix derivative from body-fixed frame to global, as set from the rotationalEphemeris_ by the setCurrentRotationalStateToLocalFrameFromEphemeris or setCurrentRotationToLocalFrameDerivativeFromEphemeris function. If body has no rotational ephemeris, an zero matrix (no rotation) is returned.
Returns
Current otation matrix derivative from global to body-fixed frame.
Definition at line 631 of file body.h.
References currentRotationToLocalFrameDerivative_.
getCurrentRotationMatrixDerivativeToLocalFrame()
Eigen::Matrix3d tudat::simulation_setup::Body::getCurrentRotationMatrixDerivativeToLocalFrame () inline
Get current rotation matrix derivative from global to body-fixed frame, as set from the rotationalEphemeris_ by the setCurrentRotationalStateToLocalFrameFromEphemeris or setCurrentRotationToLocalFrameDerivativeFromEphemeris function. If body has no rotational ephemeris, an zero matrix (no rotation) is returned.
Returns
Current otation matrix derivative from global to body-fixed frame.
Definition at line 644 of file body.h.
References currentRotationToLocalFrameDerivative_.
Referenced by tudat::simulation_setup::createAtmosphericFlightConditions(), and tudat::simulation_setup::createFlightConditions().
getCurrentAngularVelocityVectorInGlobalFrame()
Eigen::Vector3d tudat::simulation_setup::Body::getCurrentAngularVelocityVectorInGlobalFrame () inline
Get current angular velocity vector for body's rotation, expressed in the global frame.
Returns
Current angular velocity vector for body's rotation, expressed in the global frame.
Definition at line 654 of file body.h.
References currentAngularVelocityVectorInGlobalFrame_.
Referenced by tudat::simulation_setup::createDirectTidalDissipationAcceleration(), and getCurrentRotationalState().
getCurrentAngularVelocityVectorInLocalFrame()
Eigen::Vector3d tudat::simulation_setup::Body::getCurrentAngularVelocityVectorInLocalFrame () inline
Get current angular velocity vector for body's rotation, expressed in the local frame. Transformation from the global to the local frame is done by rotating the vector with the current quaternion to local frame.
Returns
Current angular velocity vector for body's rotation, expressed in the local frame.
Definition at line 666 of file body.h.
References currentAngularVelocityVectorInGlobalFrame_, and getCurrentRotationToLocalFrame().
setEphemeris()
void tudat::simulation_setup::Body::setEphemeris (const std::shared_ptr< ephemerides::Ephemeris > bodyEphemeris) inline
Function to set the ephemeris of the body, which is used to represent the (a priori) state history of the body.
Parameters
bodyEphemeris New ephemeris of the body.
Definition at line 677 of file body.h.
References bodyEphemeris_.
setGravityFieldModel()
void tudat::simulation_setup::Body::setGravityFieldModel (const std::shared_ptr< gravitation::GravityFieldModel > gravityFieldModel) inline
Function to set the gravity field of the body; input is also used to (re)set the mass of the body.
Parameters
gravityFieldModel New gravity field of the body.
Definition at line 688 of file body.h.
References bodyMassFunction_, currentMass_, tudat::physical_constants::GRAVITATIONAL_CONSTANT, and gravityFieldModel_.
setAtmosphereModel()
void tudat::simulation_setup::Body::setAtmosphereModel (const std::shared_ptr< aerodynamics::AtmosphereModel > atmosphereModel) inline
Function to set the atmosphere model of the body.
Parameters
atmosphereModel Atmosphere model of the body.
Definition at line 709 of file body.h.
References atmosphereModel_.
setRotationalEphemeris()
void tudat::simulation_setup::Body::setRotationalEphemeris (const std::shared_ptr< ephemerides::RotationalEphemeris > rotationalEphemeris) inline
Function to set the rotation model of the body.
Parameters
rotationalEphemeris Rotation model of the body.
Definition at line 720 of file body.h.
References dependentOrientationCalculator_, and rotationalEphemeris_.
setDependentOrientationCalculator()
void tudat::simulation_setup::Body::setDependentOrientationCalculator (const std::shared_ptr< reference_frames::DependentOrientationCalculator > dependentOrientationCalculator) inline
Function to set a rotation model that is only valid during numerical propagation, as it depends on the full state of the environment
Parameters
dependentOrientationCalculator Object from which the orientation is computed.
Definition at line 736 of file body.h.
References dependentOrientationCalculator_, and tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure().
setShapeModel()
void tudat::simulation_setup::Body::setShapeModel (const std::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel) inline
Function to set the shape model of the body.
Parameters
shapeModel Shape model of the body.
Definition at line 780 of file body.h.
References shapeModel_.
setAerodynamicCoefficientInterface()
void tudat::simulation_setup::Body::setAerodynamicCoefficientInterface (const std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > aerodynamicCoefficientInterface) inline
Function to set the aerodynamic coefficient interface of the body.
Parameters
aerodynamicCoefficientInterface Aerodynamic coefficient interface of the body.
Definition at line 790 of file body.h.
References aerodynamicCoefficientInterface_.
setFlightConditions()
void tudat::simulation_setup::Body::setFlightConditions (const std::shared_ptr< aerodynamics::FlightConditions > aerodynamicFlightConditions) inline
Function to set the body flight conditions, which calculates current aerodynamic angles, altitude, etc.
Parameters
aerodynamicFlightConditions Body flight conditions
Definition at line 803 of file body.h.
References aerodynamicFlightConditions_, dependentOrientationCalculator_, rotationalEphemeris_, and tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure().
setRadiationPressureInterface()
void tudat::simulation_setup::Body::setRadiationPressureInterface (const std::string & radiatingBody, const std::shared_ptr< electro_magnetism::RadiationPressureInterface > radiationPressureInterface) inline
Function to set the radiation pressure interface of the body, for a single radiation source
Parameters
radiatingBody Name of body that is the source of the radiation.
radiationPressureInterface Radiation pressure interface of the body.
Definition at line 833 of file body.h.
References radiationPressureInterfaces_.
setGravityFieldVariationSet()
void tudat::simulation_setup::Body::setGravityFieldVariationSet (const std::shared_ptr< gravitation::GravityFieldVariationsSet > gravityFieldVariationSet) inline
Function to set object containing all variations in the gravity field of this body.
Parameters
gravityFieldVariationSet Object containing all variations in the gravity field of this body.
Definition at line 846 of file body.h.
References gravityFieldVariationSet_.
getGravityFieldModel()
std::shared_ptr< gravitation::GravityFieldModel > tudat::simulation_setup::Body::getGravityFieldModel () inline
Function to get the gravity field model of the body.
Returns
Gravity field model of the body.
Definition at line 858 of file body.h.
References gravityFieldModel_.
getEphemeris()
std::shared_ptr< ephemerides::Ephemeris > tudat::simulation_setup::Body::getEphemeris () inline
Function to get the ephemeris of the body.
Returns
Ephemeris of the body.
Definition at line 868 of file body.h.
References bodyEphemeris_.
getAtmosphereModel()
std::shared_ptr< aerodynamics::AtmosphereModel > tudat::simulation_setup::Body::getAtmosphereModel () inline
Function to get the atmosphere model of the body.
Returns
Atmosphere model of the body.
Definition at line 878 of file body.h.
References atmosphereModel_.
getRotationalEphemeris()
std::shared_ptr< ephemerides::RotationalEphemeris > tudat::simulation_setup::Body::getRotationalEphemeris () inline
Function to get the rotation model of the body.
Returns
Rotation model of the body.
Definition at line 888 of file body.h.
References rotationalEphemeris_.
getDependentOrientationCalculator()
std::shared_ptr< reference_frames::DependentOrientationCalculator > tudat::simulation_setup::Body::getDependentOrientationCalculator () inline
Function to retrieve the model to compute the rotation of the body based on the current state of the environment (model is only valid during propagation).
Returns
Model to compute the rotation of the body based on the current state of the environment
Definition at line 899 of file body.h.
References dependentOrientationCalculator_.
getShapeModel()
std::shared_ptr< basic_astrodynamics::BodyShapeModel > tudat::simulation_setup::Body::getShapeModel () inline
Function to retrieve the shape model of body.
Returns
Shape model of body.
Definition at line 909 of file body.h.
References shapeModel_.
getAerodynamicCoefficientInterface()
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > tudat::simulation_setup::Body::getAerodynamicCoefficientInterface () inline
Function to retrieve the body aerodynamic coefficient model of body.
Returns
Aerodynamic coefficient model of body.
Definition at line 920 of file body.h.
References aerodynamicCoefficientInterface_.
getFlightConditions()
std::shared_ptr< aerodynamics::FlightConditions > tudat::simulation_setup::Body::getFlightConditions () inline
Function to retrieve the body flight conditions, which calculates current aerodynamic angles, altitude, etc.
Returns
Body flight conditions
Definition at line 931 of file body.h.
References aerodynamicFlightConditions_.
getRadiationPressureInterfaces()
std::map< std::string, std::shared_ptr< electro_magnetism::RadiationPressureInterface > > tudat::simulation_setup::Body::getRadiationPressureInterfaces () inline
Function to retrieve the shape model of the body.
Returns
Shape model of the body.
Definition at line 942 of file body.h.
References radiationPressureInterfaces_.
getGravityFieldVariation()
std::pair< bool, std::shared_ptr< gravitation::GravityFieldVariations > > tudat::simulation_setup::Body::getGravityFieldVariation (const gravitation::BodyDeformationTypes & deformationType, const std::string identifier = "") inline
Function to retrieve a single object describing variation in the gravity field of this body.
Parameters
deformationType Type of gravity field variation.
identifier Identifier of gravity field variation that is to be retrieved (empty by default; only required if multiple variations of same type are present)
Returns
Object describing requested variation in the gravity field of this body.
Definition at line 956 of file body.h.
References gravityFieldVariationSet_.
getGravityFieldVariationSet()
std::shared_ptr< gravitation::GravityFieldVariationsSet > tudat::simulation_setup::Body::getGravityFieldVariationSet () inline
Function to retrieve object containing all variations in the gravity field of this body.
Returns
Object containing all variations in the gravity field of this body.
Definition at line 968 of file body.h.
References gravityFieldVariationSet_.
getVehicleSystems()
std::shared_ptr< system_models::VehicleSystems > tudat::simulation_setup::Body::getVehicleSystems () inline
Function to retrieve container object with hardware systems present on/in body.
Returns
Container object with hardware systems present on/in body.
Definition at line 978 of file body.h.
References vehicleSystems_.
setVehicleSystems()
void tudat::simulation_setup::Body::setVehicleSystems (const std::shared_ptr< system_models::VehicleSystems > vehicleSystems) inline
Function to set container object with hardware systems present on/in body (typically only non-nullptr for a vehicle).
Parameters
vehicleSystems Container object with hardware systems present on/in body.
Definition at line 988 of file body.h.
References vehicleSystems_.
setBodyMassFunction()
void tudat::simulation_setup::Body::setBodyMassFunction (const std::function< double(const double) > bodyMassFunction) inline
Function to set the function returning body mass as a function of time
Parameters
bodyMassFunction Function returning body mass as a function of time
Definition at line 998 of file body.h.
References bodyMassFunction_.
setConstantBodyMass()
void tudat::simulation_setup::Body::setConstantBodyMass (const double bodyMass) inline
Function to set the body mass as being constant (i.e. time-independent)
Parameters
bodyMass New constant body mass
Definition at line 1008 of file body.h.
References bodyMassFunction_, and currentMass_.
getBodyMassFunction()
std::function< double(const double) > tudat::simulation_setup::Body::getBodyMassFunction () inline
Function to get the function returning body mass as a function of time
Returns
Function returning body mass as a function of time
Definition at line 1019 of file body.h.
References bodyMassFunction_.
updateMass()
void tudat::simulation_setup::Body::updateMass (const double time) inline
Function to update the body mass to the current time, using the bodyMassFunction_ function
Parameters
time Current time
Definition at line 1029 of file body.h.
References bodyMassFunction_, and currentMass_.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions().
getBodyMass()
double tudat::simulation_setup::Body::getBodyMass () inline
Function to retrieve the current body mass
Returns
Current body mass.
Definition at line 1046 of file body.h.
References currentMass_.
Referenced by tudat::simulation_setup::createAerodynamicAcceleratioModel(), tudat::simulation_setup::createCannonballRadiationPressureAcceleratioModel(), and tudat::simulation_setup::createThrustAcceleratioModel().
getBodyInertiaTensor()
Eigen::Matrix3d tudat::simulation_setup::Body::getBodyInertiaTensor () inline
Function to retrieve the body moment-of-inertia tensor.
Returns
Body moment-of-inertia tensor.
Definition at line 1056 of file body.h.
References bodyInertiaTensor_.
Referenced by tudat::propagators::createRotationalStateDerivativeModel(), and tudat::simulation_setup::createSecondDegreeGravitationalTorqueModel().
setBodyInertiaTensor()
void tudat::simulation_setup::Body::setBodyInertiaTensor (const Eigen::Matrix3d & bodyInertiaTensor) inline
Function to (re)set the body moment-of-inertia tensor.
Parameters
bodyInertiaTensor Body moment-of-inertia tensor.
Definition at line 1066 of file body.h.
References bodyInertiaTensor_.
addGroundStation()
void tudat::simulation_setup::Body::addGroundStation (const std::string & stationName, const std::shared_ptr< ground_stations::GroundStation > & station) inline
Function to add a ground station to the body
Parameters
stationName Name of ground station
station Ground station object that is to be set
Definition at line 1077 of file body.h.
References groundStationMap.
getGroundStation()
std::shared_ptr< ground_stations::GroundStation > tudat::simulation_setup::Body::getGroundStation (const std::string & stationName) const inline
Function to retrieve a ground station
Parameters
stationName Name of ground station
Returns
Ground station object that is retrieved
Definition at line 1089 of file body.h.
References groundStationMap.
getGroundStationMap()
std::map< std::string, std::shared_ptr< ground_stations::GroundStation > > tudat::simulation_setup::Body::getGroundStationMap () const inline
Function to retrieve full list of ground stations
Returns
Full list of ground stations
Definition at line 1104 of file body.h.
References groundStationMap.
updateConstantEphemerisDependentMemberQuantities()
void tudat::simulation_setup::Body::updateConstantEphemerisDependentMemberQuantities () inline
Function to recompute the internal variables of member variables that depend on the ephemerides of this and other bodies. This function is typically called after equations of motion have been computed and set in environment to ensure full model consistency.
Definition at line 1115 of file body.h.
References gravityFieldModel_.
recomputeStateOnNextCall()
void tudat::simulation_setup::Body::recomputeStateOnNextCall () inline
Function to reset the time to which the state was last updated using setStateFromEphemeris function to nan, thereby singalling that it needs to be recomputed upon next call.
Definition at line 1130 of file body.h.
References timeOfCurrentState_, and TUDAT_NAN.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions().
getIsBodyGlobalFrameOrigin()
int tudat::simulation_setup::Body::getIsBodyGlobalFrameOrigin () inline
Function to retrieve variable denoting whether this body is the global frame origin
Returns
Variable denoting whether this body is the global frame origin
Definition at line 1140 of file body.h.
References bodyIsGlobalFrameOrigin_.
setIsBodyGlobalFrameOrigin()
void tudat::simulation_setup::Body::setIsBodyGlobalFrameOrigin (const int bodyIsGlobalFrameOrigin) inline
Function to set variable denoting whether this body is the global frame origin
Parameters
bodyIsGlobalFrameOrigin Variable denoting whether this body is the global frame origin
Definition at line 1150 of file body.h.
References bodyIsGlobalFrameOrigin_.
getTemplatedState() [2/3]
template<> Eigen::Matrix< double, 6, 1 > tudat::simulation_setup::Body::getTemplatedState ()
Definition at line 57 of file body.cpp.
References getState().
getTemplatedState() [3/3]
template<> Eigen::Matrix< long double, 6, 1 > tudat::simulation_setup::Body::getTemplatedState ()
Definition at line 63 of file body.cpp.
References getLongState().
setTemplatedState() [2/3]
template<> void tudat::simulation_setup::Body::setTemplatedState (const Eigen::Matrix< double, 6, 1 > & state)
Definition at line 70 of file body.cpp.
References setState().
setTemplatedState() [3/3]
template<> void tudat::simulation_setup::Body::setTemplatedState (const Eigen::Matrix< long double, 6, 1 > & state)
Definition at line 77 of file body.cpp.
References setLongState().
Member Data Documentation
bodyIsGlobalFrameOrigin_
int tudat::simulation_setup::Body::bodyIsGlobalFrameOrigin_ private
Definition at line 1160 of file body.h.
Referenced by getGlobalFrameOriginBarycentricStateFromEphemeris(), getIsBodyGlobalFrameOrigin(), setIsBodyGlobalFrameOrigin(), and setStateFromEphemeris().
currentState_
Eigen::Vector6d tudat::simulation_setup::Body::currentState_ private
Definition at line 1163 of file body.h.
Referenced by getPosition(), getState(), getStateInBaseFrameFromEphemeris(), getVelocity(), setLongState(), setState(), and setStateFromEphemeris().
currentLongState_
Eigen::Matrix< long double, 6, 1 > tudat::simulation_setup::Body::currentLongState_ private
Definition at line 1166 of file body.h.
Referenced by getLongPosition(), getLongState(), getLongVelocity(), getStateInBaseFrameFromEphemeris(), setLongState(), and setStateFromEphemeris().
currentBarycentricState_
Eigen::Vector6d tudat::simulation_setup::Body::currentBarycentricState_ private
Definition at line 1169 of file body.h.
Referenced by getGlobalFrameOriginBarycentricStateFromEphemeris(), and setStateFromEphemeris().
currentBarycentricLongState_
Eigen::Matrix< long double, 6, 1 > tudat::simulation_setup::Body::currentBarycentricLongState_ private
Definition at line 1172 of file body.h.
Referenced by getGlobalFrameOriginBarycentricStateFromEphemeris(), and setStateFromEphemeris().
timeOfCurrentState_
Time tudat::simulation_setup::Body::timeOfCurrentState_ private
Definition at line 1175 of file body.h.
Referenced by recomputeStateOnNextCall(), and setStateFromEphemeris().
ephemerisFrameToBaseFrame_
std::shared_ptr< BaseStateInterface > tudat::simulation_setup::Body::ephemerisFrameToBaseFrame_ private
Class returning the state of this body's ephemeris origin w.r.t. the global origin (as typically created by setGlobalFrameBodyEphemerides function).
Definition at line 1179 of file body.h.
Referenced by getEphemerisFrameToBaseFrame(), setEphemerisFrameToBaseFrame(), and setStateFromEphemeris().
currentRotationToLocalFrame_
Eigen::Quaterniond tudat::simulation_setup::Body::currentRotationToLocalFrame_ private
Definition at line 1182 of file body.h.
Referenced by getCurrentRotationToGlobalFrame(), getCurrentRotationToLocalFrame(), setCurrentRotationalStateToLocalFrame(), setCurrentRotationalStateToLocalFrameFromEphemeris(), and setCurrentRotationToLocalFrameFromEphemeris().
currentRotationToLocalFrameDerivative_
Eigen::Matrix3d tudat::simulation_setup::Body::currentRotationToLocalFrameDerivative_ private
Current first derivative w.r.t. time of the rotation matrix from the global to the body-fixed frame.
Definition at line 1186 of file body.h.
Referenced by getCurrentRotationMatrixDerivativeToGlobalFrame(), getCurrentRotationMatrixDerivativeToLocalFrame(), setCurrentRotationalStateToLocalFrame(), setCurrentRotationalStateToLocalFrameFromEphemeris(), and setCurrentRotationToLocalFrameDerivativeFromEphemeris().
currentAngularVelocityVectorInGlobalFrame_
Eigen::Vector3d tudat::simulation_setup::Body::currentAngularVelocityVectorInGlobalFrame_ private
Definition at line 1189 of file body.h.
Referenced by getCurrentAngularVelocityVectorInGlobalFrame(), getCurrentAngularVelocityVectorInLocalFrame(), setCurrentAngularVelocityVectorInGlobalFrame(), setCurrentRotationalStateToLocalFrame(), and setCurrentRotationalStateToLocalFrameFromEphemeris().
currentMass_
double tudat::simulation_setup::Body::currentMass_ private
Definition at line 1192 of file body.h.
Referenced by getBodyMass(), setConstantBodyMass(), setGravityFieldModel(), and updateMass().
bodyMassFunction_
std::function< double(const double) > tudat::simulation_setup::Body::bodyMassFunction_ private
Definition at line 1195 of file body.h.
Referenced by getBodyMassFunction(), setBodyMassFunction(), setConstantBodyMass(), setGravityFieldModel(), and updateMass().
bodyInertiaTensor_
Eigen::Matrix3d tudat::simulation_setup::Body::bodyInertiaTensor_ private
Definition at line 1198 of file body.h.
Referenced by getBodyInertiaTensor(), and setBodyInertiaTensor().
bodyEphemeris_
std::shared_ptr< ephemerides::Ephemeris > tudat::simulation_setup::Body::bodyEphemeris_ private
Definition at line 1201 of file body.h.
Referenced by getEphemeris(), setEphemeris(), and setStateFromEphemeris().
gravityFieldModel_
std::shared_ptr< gravitation::GravityFieldModel > tudat::simulation_setup::Body::gravityFieldModel_ private
Definition at line 1204 of file body.h.
Referenced by getGravityFieldModel(), setGravityFieldModel(), and updateConstantEphemerisDependentMemberQuantities().
gravityFieldVariationSet_
std::shared_ptr< gravitation::GravityFieldVariationsSet > tudat::simulation_setup::Body::gravityFieldVariationSet_ private
Definition at line 1207 of file body.h.
Referenced by getGravityFieldVariation(), getGravityFieldVariationSet(), and setGravityFieldVariationSet().
atmosphereModel_
std::shared_ptr< aerodynamics::AtmosphereModel > tudat::simulation_setup::Body::atmosphereModel_ private
Definition at line 1210 of file body.h.
Referenced by getAtmosphereModel(), and setAtmosphereModel().
shapeModel_
std::shared_ptr< basic_astrodynamics::BodyShapeModel > tudat::simulation_setup::Body::shapeModel_ private
Definition at line 1213 of file body.h.
Referenced by getShapeModel(), and setShapeModel().
aerodynamicCoefficientInterface_
std::shared_ptr< aerodynamics::AerodynamicCoefficientInterface > tudat::simulation_setup::Body::aerodynamicCoefficientInterface_ private
Definition at line 1216 of file body.h.
Referenced by getAerodynamicCoefficientInterface(), and setAerodynamicCoefficientInterface().
aerodynamicFlightConditions_
std::shared_ptr< aerodynamics::FlightConditions > tudat::simulation_setup::Body::aerodynamicFlightConditions_ private
Definition at line 1219 of file body.h.
Referenced by getFlightConditions(), and setFlightConditions().
rotationalEphemeris_
std::shared_ptr< ephemerides::RotationalEphemeris > tudat::simulation_setup::Body::rotationalEphemeris_ private
Definition at line 1222 of file body.h.
Referenced by getRotationalEphemeris(), setCurrentAngularVelocityVectorInGlobalFrame(), setCurrentRotationalStateToLocalFrameFromEphemeris(), setCurrentRotationToLocalFrameDerivativeFromEphemeris(), setCurrentRotationToLocalFrameFromEphemeris(), setFlightConditions(), and setRotationalEphemeris().
dependentOrientationCalculator_
std::shared_ptr< reference_frames::DependentOrientationCalculator > tudat::simulation_setup::Body::dependentOrientationCalculator_ private
Definition at line 1225 of file body.h.
Referenced by getDependentOrientationCalculator(), setCurrentAngularVelocityVectorInGlobalFrame(), setCurrentRotationalStateToLocalFrameFromEphemeris(), setCurrentRotationToLocalFrameDerivativeFromEphemeris(), setCurrentRotationToLocalFrameFromEphemeris(), setDependentOrientationCalculator(), setFlightConditions(), and setRotationalEphemeris().
radiationPressureInterfaces_
std::map< std::string, std::shared_ptr< electro_magnetism::RadiationPressureInterface > > tudat::simulation_setup::Body::radiationPressureInterfaces_ private
Definition at line 1229 of file body.h.
Referenced by getRadiationPressureInterfaces(), and setRadiationPressureInterface().
radiationPressureIterator_
std::map< std::string, std::shared_ptr< electro_magnetism::RadiationPressureInterface > >::iterator tudat::simulation_setup::Body::radiationPressureIterator_ private
Definition at line 1234 of file body.h.
groundStationMap
std::map< std::string, std::shared_ptr< ground_stations::GroundStation > > tudat::simulation_setup::Body::groundStationMap private
Definition at line 1237 of file body.h.
Referenced by addGroundStation(), getGroundStation(), and getGroundStationMap().
vehicleSystems_
std::shared_ptr< system_models::VehicleSystems > tudat::simulation_setup::Body::vehicleSystems_ private
Definition at line 1240 of file body.h.
Referenced by getVehicleSystems(), and setVehicleSystems().
The documentation for this class was generated from the following files:
SimulationSetup/EnvironmentSetup/body.h
SimulationSetup/EnvironmentSetup/body.cpp