Tudat: tudat::basic_mathematics::LegendreCache Class Reference
tudat::basic_mathematics::LegendreCache Class Reference
Class for creating and accessing a back-end cache of Legendre polynomials.
#include <legendrePolynomials.h>
Public Types
typedef boost::function< double(int, int, LegendreCache &) > LegendrePolynomialFunction
Define Legendre polynomial function pointer.
Public Member Functions
LegendreCache (const bool useGeodesyNormalization=1)
Default constructor, initializes cache object with 0 maximum degree and order.
LegendreCache (const int maximumDegree, const int maximumOrder, const bool useGeodesyNormalization=1)
Constructor.
double getCurrentPolynomialParameter ()
Function to return the current polynomial parameter (typically sine of latitude)
double getCurrentPolynomialParameterComplement ()
Function to return the complement to the current polynomial parameter (typically cosine of latitude)
double getLegendrePolynomial (const int degree, const int order)
Get Legendre polynomial value from the cache.
double getLegendrePolynomialDerivative (const int degree, const int order)
Get first derivative of Legendre polynomial value from the cache.
double getLegendrePolynomialSecondDerivative (const int degree, const int order)
Get second derivative of Legendre polynomial value from the cache.
int getMaximumDegree ()
Function to get the maximum degree of cache.
int getMaximumOrder ()
Function to get the maximum order of cache.
bool getUseGeodesyNormalization ()
Function to get whether the Legendre polynomials are geodesy-normalized or unnormalized.
void resetMaximumDegreeAndOrder (const int maximumDegree, const int maximumOrder)
Update maximum degree and order of cache.
void setComputeSecondDerivatives (const bool computeSecondDerivatives)
Function to reset whether the second derivatives are to be computed when calling update function.
void update (const double polynomialParameter)
Update cache with new polynomial parameter (sine of latitude)
Private Attributes
bool computeSecondDerivatives_
double currentPolynomialParameter_
Current polynomial parameter (sine of latitude).
double currentPolynomialParameterComplement_
Current 'complement' to polynomial parameter (cosine of latitude).
std::vector< double > derivativeNormalizations_
Prec-computed normalization factors that are to be used for computation fo Legendre polynomial derivative.
std::vector< double > legendreDerivatives_
List of current values of first derivatives of Legendre polynomials at degree and order (n,m)
LegendrePolynomialFunction legendrePolynomialFunction_
Function from which to compute the Legendre polynomials.
std::vector< double > legendreSecondDerivatives_
List of current values of second derivatives of Legendre polynomials at degree and order (n,m)
std::vector< double > legendreValues_
List of current values of Legendre polynomials at degree and order (n,m)
int maximumDegree_
Maximum degree of cache.
int maximumOrder_
Maximum order of cache.
std::vector< double > referenceRadiusRatioPowers_
Vector of ratio of reference radius over current radius to power i, with i the entry in the vector.
bool useGeodesyNormalization_
Boolean denoting whether the Legendre polynomials are geodesy-normalized or unnormalized.
Detailed Description
Definition at line 50 of file legendrePolynomials.h.
Member Typedef Documentation
typedef boost::function< double (int, int, LegendreCache&) > tudat::basic_mathematics::LegendreCache::LegendrePolynomialFunction
Definition at line 56 of file legendrePolynomials.h.
Constructor & Destructor Documentation
tudat::basic_mathematics::LegendreCache::LegendreCache (const bool useGeodesyNormalization = 1)
Default constructor, initializes cache object with 0 mazimum degree and order.
Parameters
useGeodesyNormalization Parameter defining whether the cache is used for a normalized or unnormalized gravity field.
Definition at line 28 of file legendrePolynomials.cpp.
References computeSecondDerivatives_, tudat::basic_mathematics::geodesyNormalizedLegendrePolynomialFunction, legendrePolynomialFunction_, tudat::basic_mathematics::regularLegendrePolynomialFunction, resetMaximumDegreeAndOrder(), and useGeodesyNormalization_.
tudat::basic_mathematics::LegendreCache::LegendreCache (const int maximumDegree, const int maximumOrder, const bool useGeodesyNormalization = 1)
Constructor
Parameters
maximumDegree Maximum degree to which to update cache
maximumOrder Maximum order to which to update cache
useGeodesyNormalization Parameter defining whether the cache is used for a normalized or unnormalized gravity field.
Definition at line 47 of file legendrePolynomials.cpp.
References computeSecondDerivatives_, tudat::basic_mathematics::geodesyNormalizedLegendrePolynomialFunction, legendrePolynomialFunction_, tudat::basic_mathematics::regularLegendrePolynomialFunction, resetMaximumDegreeAndOrder(), and useGeodesyNormalization_.
Member Function Documentation
void tudat::basic_mathematics::LegendreCache::resetMaximumDegreeAndOrder (const int maximumDegree, const int maximumOrder)
Update maximum degree and order of cache
Parameters
maximumDegree Maximum degree to which to update cache
maximumOrder Maximum order to which to update cache
Definition at line 195 of file legendrePolynomials.cpp.
References currentPolynomialParameter_, currentPolynomialParameterComplement_, derivativeNormalizations_, legendreDerivatives_, legendreSecondDerivatives_, legendreValues_, maximumDegree_, maximumOrder_, and TUDAT_NAN.
Referenced by LegendreCache().
void tudat::basic_mathematics::LegendreCache::update (const double polynomialParameter)
Get Legendre polynomial from cache when possible, and from direct computation otherwise.
Update cache with new polynomial parameter (sine of latitude).
Parameters
polynomialParameter Parameter used as input argument for Legendre polynomials, in astrodynamics applications, this is typically the sine of the body-fixed latitude.
Definition at line 65 of file legendrePolynomials.cpp.
References tudat::basic_mathematics::computeGeodesyLegendrePolynomialDerivative(), tudat::basic_mathematics::computeGeodesyLegendrePolynomialSecondDerivative(), tudat::basic_mathematics::computeLegendrePolynomialDerivative(), computeSecondDerivatives_, currentPolynomialParameter_, currentPolynomialParameterComplement_, derivativeNormalizations_, legendreDerivatives_, legendrePolynomialFunction_, legendreSecondDerivatives_, legendreValues_, maximumDegree_, maximumOrder_, and useGeodesyNormalization_.
Referenced by tudat::gravitation::calculateSphericalHarmonicGravitationalPotential(), tudat::basic_mathematics::computeGeodesyLegendrePolynomial(), and tudat::basic_mathematics::computeLegendrePolynomial().
double tudat::basic_mathematics::LegendreCache::getCurrentPolynomialParameter () inline
Function to return the current polynomial parameter (typically sine of latitude)
Returns
Current polynomial parameter
Definition at line 97 of file legendrePolynomials.h.
References currentPolynomialParameter_.
Referenced by tudat::basic_mathematics::computeGeodesyLegendrePolynomialFromCache(), and tudat::basic_mathematics::computeLegendrePolynomialFromCache().
double tudat::basic_mathematics::LegendreCache::getCurrentPolynomialParameterComplement () inline
Function to return the complement to the current polynomial parameter (typically cosine of latitude)
Returns
Complement to the current polynomial parameter
Definition at line 107 of file legendrePolynomials.h.
References currentPolynomialParameterComplement_, getLegendrePolynomial(), getLegendrePolynomialDerivative(), and getLegendrePolynomialSecondDerivative().
double tudat::basic_mathematics::LegendreCache::getLegendrePolynomial (const int degree, const int order)
Get Legendre polynomial value from the cache, as computed by last call to update function.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
Returns
Legendre polynomial value.
Definition at line 234 of file legendrePolynomials.cpp.
References legendreValues_, maximumDegree_, maximumOrder_, and TUDAT_NAN.
Referenced by tudat::basic_mathematics::computeGeodesyLegendrePolynomialFromCache(), tudat::basic_mathematics::computeLegendrePolynomialFromCache(), and getCurrentPolynomialParameterComplement().
double tudat::basic_mathematics::LegendreCache::getLegendrePolynomialDerivative (const int degree, const int order)
Get first derivative of Legendre polynomial value from the cache, as computed by last call to update function.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
Returns
First derivative of Legendre polynomial value.
Definition at line 258 of file legendrePolynomials.cpp.
References legendreDerivatives_, maximumDegree_, maximumOrder_, and TUDAT_NAN.
Referenced by getCurrentPolynomialParameterComplement().
double tudat::basic_mathematics::LegendreCache::getLegendrePolynomialSecondDerivative (const int degree, const int order)
Get second derivative of Legendre polynomial value from the cache, as computed by last call to update function.
Parameters
degree Degree of requested Legendre polynomial.
order Order of requested Legendre polynomial.
Returns
Second derivative of Legendre polynomial value.
Definition at line 282 of file legendrePolynomials.cpp.
References computeSecondDerivatives_, legendreSecondDerivatives_, maximumDegree_, maximumOrder_, and TUDAT_NAN.
Referenced by getCurrentPolynomialParameterComplement().
int tudat::basic_mathematics::LegendreCache::getMaximumDegree () inline
Function to get the maximum degree of cache
Returns
Maximum degree of cache.
Definition at line 144 of file legendrePolynomials.h.
References maximumDegree_.
int tudat::basic_mathematics::LegendreCache::getMaximumOrder () inline
Function to get the maximum order of cache.
Returns
Maximum order of cache.
Definition at line 154 of file legendrePolynomials.h.
References maximumOrder_.
bool tudat::basic_mathematics::LegendreCache::getUseGeodesyNormalization () inline
Function to get whether the Legendre polynomials are geodesy-normalized or unnormalized
Returns
Boolean denoting to get whether the Legendre polynomials are geodesy-normalized or unnormalized
Definition at line 164 of file legendrePolynomials.h.
References useGeodesyNormalization_.
Referenced by tudat::basic_mathematics::computeGeodesyLegendrePolynomialFromCache(), and tudat::basic_mathematics::computeLegendrePolynomialFromCache().
void tudat::basic_mathematics::LegendreCache::setComputeSecondDerivatives (const bool computeSecondDerivatives) inline
Function to reset whether the second derivatives are to be computed when calling update function
Parameters
computeSecondDerivatives Boolean denoting whether the second derivatives of the Legendre polynomials are to be computed when calling update function.
Definition at line 175 of file legendrePolynomials.h.
References computeSecondDerivatives_, currentPolynomialParameter_, and TUDAT_NAN.
Member Data Documentation
int tudat::basic_mathematics::LegendreCache::maximumDegree_ private
Definition at line 186 of file legendrePolynomials.h.
Referenced by getLegendrePolynomial(), getLegendrePolynomialDerivative(), getLegendrePolynomialSecondDerivative(), getMaximumDegree(), resetMaximumDegreeAndOrder(), and update().
int tudat::basic_mathematics::LegendreCache::maximumOrder_ private
Definition at line 189 of file legendrePolynomials.h.
Referenced by getLegendrePolynomial(), getLegendrePolynomialDerivative(), getLegendrePolynomialSecondDerivative(), getMaximumOrder(), resetMaximumDegreeAndOrder(), and update().
double tudat::basic_mathematics::LegendreCache::currentPolynomialParameter_ private
Definition at line 192 of file legendrePolynomials.h.
Referenced by getCurrentPolynomialParameter(), resetMaximumDegreeAndOrder(), setComputeSecondDerivatives(), and update().
double tudat::basic_mathematics::LegendreCache::currentPolynomialParameterComplement_ private
Definition at line 195 of file legendrePolynomials.h.
Referenced by getCurrentPolynomialParameterComplement(), resetMaximumDegreeAndOrder(), and update().
std::vector< double > tudat::basic_mathematics::LegendreCache::legendreValues_ private
List of current values of Legendre polynomials at degree and order (n,m). The corresponding polynomial is at entry n * (maximumOrder_ + 1) + m.
Definition at line 202 of file legendrePolynomials.h.
Referenced by getLegendrePolynomial(), resetMaximumDegreeAndOrder(), and update().
std::vector< double > tudat::basic_mathematics::LegendreCache::legendreDerivatives_ private
List of current values of first derivatives of Legendre polynomials at degree and order (n,m). The corresponding polynomial is at entry n * (maximumOrder_ + 1) + m.
Definition at line 209 of file legendrePolynomials.h.
Referenced by getLegendrePolynomialDerivative(), resetMaximumDegreeAndOrder(), and update().
std::vector< double > tudat::basic_mathematics::LegendreCache::legendreSecondDerivatives_ private
List of current values of second derivatives of Legendre polynomials at degree and order (n,m). The corresponding polynomial is at entry n * (maximumOrder_ + 1) + m.
Definition at line 216 of file legendrePolynomials.h.
Referenced by getLegendrePolynomialSecondDerivative(), resetMaximumDegreeAndOrder(), and update().
LegendrePolynomialFunction tudat::basic_mathematics::LegendreCache::legendrePolynomialFunction_ private
Definition at line 219 of file legendrePolynomials.h.
Referenced by LegendreCache(), and update().
bool tudat::basic_mathematics::LegendreCache::useGeodesyNormalization_ private
Definition at line 222 of file legendrePolynomials.h.
Referenced by getUseGeodesyNormalization(), LegendreCache(), and update().
std::vector< double > tudat::basic_mathematics::LegendreCache::referenceRadiusRatioPowers_ private
Definition at line 225 of file legendrePolynomials.h.
std::vector< double > tudat::basic_mathematics::LegendreCache::derivativeNormalizations_ private
Definition at line 228 of file legendrePolynomials.h.
Referenced by resetMaximumDegreeAndOrder(), and update().
bool tudat::basic_mathematics::LegendreCache::computeSecondDerivatives_ private
Boolean denoting whether the second derivatives of the Legendre polynomials are to be computed when calling update function.
Definition at line 232 of file legendrePolynomials.h.
Referenced by getLegendrePolynomialSecondDerivative(), LegendreCache(), setComputeSecondDerivatives(), and update().
The documentation for this class was generated from the following files:
Mathematics/BasicMathematics/legendrePolynomials.h
Mathematics/BasicMathematics/legendrePolynomials.cpp