Tudat: tudat::interpolators::PiecewiseConstantInterpolator< IndependentVariableType, DependentVariableType > Class Template Reference
tudat::interpolators::PiecewiseConstantInterpolator< IndependentVariableType, DependentVariableType > Class Template Reference
Piecewise constant interpolator class.
#include <piecewiseConstantInterpolator.h>
Public Member Functions
PiecewiseConstantInterpolator (const std::vector< IndependentVariableType > independentVariables, const std::vector< DependentVariableType > dependentVariables, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Constructor from vectors of independent/dependent data.
PiecewiseConstantInterpolator (const std::map< IndependentVariableType, DependentVariableType > dataMap, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Constructor from map of independent/dependent data.
~PiecewiseConstantInterpolator ()
Destructor.
DependentVariableType interpolate (const IndependentVariableType targetIndependentVariableValue)
Function interpolates dependent variable value at given independent variable value.
void resetDependentValues (const std::vector< DependentVariableType > &dependentValues)
Function to reset the values of dependent variables used by interpolator.
Public Member Functions inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
OneDimensionalInterpolator (const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Constructor.
OneDimensionalInterpolator (const BoundaryInterpolationType boundaryHandling, const DependentVariableType &defaultExtrapolationValue)
Constructor.
virtual ~OneDimensionalInterpolator ()
Destructor.
std::vector< DependentVariableType > getDependentValues ()
Function to return the ector with dependent variables used by the interpolator.
std::vector< IndependentVariableType > getIndependentValues ()
Function to return the ector with independent variables used by the interpolator.
std::shared_ptr< LookUpScheme< IndependentVariableType > > getLookUpScheme ()
Function to return the lookup scheme used by the interpolator.
int getNumberOfDimensions ()
Function to return the number of independent variables of the interpolation.
virtual DependentVariableType interpolate (const std::vector< IndependentVariableType > &independentVariableValues)
Function to perform interpolation.
DependentVariableType interpolateNonConst (IndependentVariableType independentVariableValue)
Function to perform interpolation, with non-const input argument.
Public Member Functions inherited from tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >
virtual ~Interpolator ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
void checkBoundaryCase (DependentVariableType &dependentVariable, bool &useValue, const IndependentVariableType &targetIndependentVariable)
Function to check whether boundary handling needs to be applied, depending on method chosen.
int checkInterpolationBoundary (const IndependentVariableType &targetIndependentVariable)
Function to return the condition of the current independent variable.
void makeLookupScheme (const AvailableLookupScheme selectedScheme)
Make look-up scheme that is to be used.
Protected Attributes inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
BoundaryInterpolationType boundaryHandling_
Behavior of interpolator when independent variable is outside range.
std::pair< DependentVariableType, DependentVariableType > defaultExtrapolationValue_
Default value to be used for extrapolation.
std::vector< DependentVariableType > dependentValues_
Vector with dependent variables.
std::vector< IndependentVariableType > independentValues_
Vector with independent variables.
std::shared_ptr< LookUpScheme< IndependentVariableType > > lookUpScheme_
Pointer to look up scheme.
Detailed Description
template<typename IndependentVariableType, typename DependentVariableType>
class tudat::interpolators::PiecewiseConstantInterpolator< IndependentVariableType, DependentVariableType >
This class is used to perform piecewise constant interpolation in a single dimension from a set of data in independent and dependent variables. The interpolated values is equal to the dependent variable at the nearest lower neighbour at a given independent variable.
Definition at line 30 of file piecewiseConstantInterpolator.h.
Constructor & Destructor Documentation
PiecewiseConstantInterpolator() [1/2]
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::PiecewiseConstantInterpolator< IndependentVariableType, DependentVariableType >::PiecewiseConstantInterpolator (const std::vector< IndependentVariableType > independentVariables, const std::vector< DependentVariableType > dependentVariables, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm, const BoundaryInterpolationType boundaryHandling = extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > & defaultExtrapolationValue = std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >())) inline
This constructor initializes the interpolator from two vectors containing the independent variables and dependent variables. A look-up scheme can be provided to override the given default.
Parameters
independentVariables Vector of values of independent variables that are used, must be sorted in ascending order.
dependentVariables Vector of values of dependent variables that are used.
selectedLookupScheme Identifier of lookupscheme from enum. This algorithm is used to find the nearest lower data point in the independent variables when requesting interpolation.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 56 of file piecewiseConstantInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::makeLookupScheme().
PiecewiseConstantInterpolator() [2/2]
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::PiecewiseConstantInterpolator< IndependentVariableType, DependentVariableType >::PiecewiseConstantInterpolator (const std::map< IndependentVariableType, DependentVariableType > dataMap, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm, const BoundaryInterpolationType boundaryHandling = extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > & defaultExtrapolationValue = std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >())) inline
This constructor initializes the interpolator from a map containing independent variables as key and dependent variables as value. A look-up scheme can be provided to override the given default.
Parameters
dataMap Map containing independent variables as key and dependent variables as value.
selectedLookupScheme Identifier of lookupscheme from enum. This algorithm is used to find the nearest lower data point in the independent variables when requesting interpolation.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 93 of file piecewiseConstantInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::makeLookupScheme().
~PiecewiseConstantInterpolator()
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::PiecewiseConstantInterpolator< IndependentVariableType, DependentVariableType >::~PiecewiseConstantInterpolator () inline
Definition at line 126 of file piecewiseConstantInterpolator.h.
Member Function Documentation
interpolate()
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::interpolators::PiecewiseConstantInterpolator< IndependentVariableType, DependentVariableType >::interpolate (const IndependentVariableType targetIndependentVariableValue) inline virtual
Function interpolates dependent variable value at given independent variable value using piecewise constant algorithm.
Parameters
targetIndependentVariableValue Value of independent variable at which interpolation is to take place.
Returns
Interpolated value of dependent variable.
Implements tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >.
Definition at line 134 of file piecewiseConstantInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::checkBoundaryCase(), tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::lookUpScheme_.
resetDependentValues()
template<typename IndependentVariableType , typename DependentVariableType > void tudat::interpolators::PiecewiseConstantInterpolator< IndependentVariableType, DependentVariableType >::resetDependentValues (const std::vector< DependentVariableType > & dependentValues) inline
Function to reset the values of dependent variables used by interpolator
Parameters
dependentValues New list of values of dependent variables. List must be of same size as original list
Definition at line 169 of file piecewiseConstantInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_.
The documentation for this class was generated from the following file:
Mathematics/Interpolators/piecewiseConstantInterpolator.h