Tudat: tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType > Class Template Reference
tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType > Class Template Reference
Kalman filter class.
#include <kalmanFilter.h>
Public Types
typedef FilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix DependentMatrix
typedef FilterBase< IndependentVariableType, DependentVariableType >::DependentVector DependentVector
Inherit typedefs from base class.
typedef FilterBase< IndependentVariableType, DependentVariableType >::Function Function
typedef FilterBase< IndependentVariableType, DependentVariableType >::Integrator Integrator
typedef FilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings IntegratorSettings
typedef FilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction MatrixFunction
Public Types inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
typedef Eigen::Matrix< DependentVariableType, Eigen::Dynamic, Eigen::Dynamic > DependentMatrix
Typedef of the state and measurement matrices.
typedef Eigen::Matrix< DependentVariableType, Eigen::Dynamic, 1 > DependentVector
Typedef of the state and measurement vectors.
typedef std::function< DependentVector(const IndependentVariableType, const DependentVector &) > Function
Typedef of the function describing the system and the measurements.
typedef numerical_integrators::NumericalIntegrator< IndependentVariableType, DependentVector, DependentVector, IndependentVariableType > Integrator
Typedef of the integrator.
typedef numerical_integrators::IntegratorSettings< IndependentVariableType > IntegratorSettings
Typedef of the integrator settings.
typedef std::function< DependentMatrix(const IndependentVariableType, const DependentVector &) > MatrixFunction
Typedefs for system and measurement matrix functions.
Public Member Functions
KalmanFilterBase (const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings)
Constructor.
virtual ~KalmanFilterBase ()
Destructor.
Public Member Functions inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
FilterBase (const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings)
Constructor.
virtual ~FilterBase ()
Destructor.
void clearFilterHistory ()
Function to clear the history of stored variables.
DependentMatrix getCurrentCovarianceEstimate ()
Function to retrieve current covariance estimate.
DependentVector getCurrentStateEstimate ()
Function to retrieve current state estimate.
IndependentVariableType getCurrentTime ()
Function to retrieve current time.
std::map< IndependentVariableType, DependentMatrix > getEstimatedCovarianceHistory ()
Function to retrieve the history of estimated covariance matrices.
std::map< IndependentVariableType, DependentVector > getEstimatedStateHistory ()
Function to retrieve the history of estimated states.
IndependentVariableType getFilteringStepSize ()
Function to retrieve step-size for filtering.
IndependentVariableType getInitialTime ()
Function to retrieve initial time.
std::pair< std::vector< DependentVector >, std::vector< DependentVector > > getNoiseHistory ()
Function to retrieve the history of system and measurement noise used by the updateFilter function.
void modifyCurrentStateAndCovarianceEstimates (const DependentVector &newStateEstimate, const DependentMatrix &newCovarianceEstimate=DependentMatrix::Zero())
Function to update the a-posteriori estimates of state and covariance with external data.
void modifyCurrentTime (const double newCurrentTime)
Function to modify the current time.
void modifyFilteringStepSize (const double newFilteringStepSize)
Function to modify the step size for filtering.
DependentVector produceMeasurementNoise ()
Function to produce measurement noise.
DependentVector produceSystemNoise ()
Function to produce system noise.
void revertToPreviousTimeStep (const double timeToBeRemoved)
Function to revert to the previous time step.
virtual void updateFilter (const DependentVector &currentMeasurementVector)=0
Function to update the filter with the data from the new time step.
Protected Member Functions
virtual void correctCovariance (const DependentMatrix &aPrioriCovarianceEstimate, const DependentMatrix &currentMeasurementMatrix, const DependentMatrix &kalmanGain)
Function to correct the covariance for the next time step.
DependentVector predictState ()
Function to predict the state for the next time step.
DependentVector predictState (const DependentVector &currentStateVector)
Function to predict the state for the next time step, by overwriting previous state.
Protected Member Functions inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
virtual void clearSpecificFilterHistory ()
Function to clear the history of stored variables for derived class-specific variables.
void correctState (const DependentVector &aPrioriStateEstimate, const DependentVector &currentMeasurementVector, const DependentVector &measurementEstimate, const DependentMatrix &gainMatrix)
Function to correct the state for the next time step.
virtual DependentVector createMeasurementFunction (const IndependentVariableType currentTime, const DependentVector &currentStateVector)=0
Function to create the function that defines the measurement model.
virtual DependentVector createSystemFunction (const IndependentVariableType currentTime, const DependentVector &currentStateVector)=0
Function to create the function that defines the system model.
virtual void specificRevertToPreviousTimeStep (const double timeToBeRemoved)
Function to revert to the previous time step for derived class-specific variables.
Private Member Functions
DependentVector propagateState (const DependentVector &currentStateVector)
Function to propagate state to the next time step, by overwriting previous state.
Additional Inherited Members
Protected Attributes inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
DependentMatrix aPosterioriCovarianceEstimate_
Matrix representing the a-posteriori estimated covariance.
DependentVector aPosterioriStateEstimate_
Vector representing the a-posteriori estimated state.
IndependentVariableType currentTime_
Scalar representing the current time.
IndependentVariableType filteringStepSize_
Scalar representing step-size for filtering process.
std::map< IndependentVariableType, DependentMatrix > historyOfCovarianceEstimates_
Map of estimated covariance matrices history.
std::map< IndependentVariableType, DependentVector > historyOfStateEstimates_
Map of estimated states vectors history.
DependentMatrix identityMatrix_
Indentity matrix.
const IndependentVariableType initialTime_
Scalar representing the initial time.
std::shared_ptr< Integrator > integrator_
Pointer to the integrator.
bool isStateToBeIntegrated_
Boolean specifying whether the state needs to be integrated.
Function measurementFunction_
Measurement function.
const DependentMatrix measurementUncertainty_
Matrix representing the uncertainty in measurement modeling.
Function systemFunction_
System function.
const DependentMatrix systemUncertainty_
Matrix representing the uncertainty in system modeling.
Detailed Description
template<typename IndependentVariableType = double, typename DependentVariableType = double>
class tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >
Base class for the set up and use of Kalman filters.
Template Parameters
IndependentVariableType Type of independent variable. Default is double.
DependentVariableType Type of dependent variable. Default is double.
Definition at line 30 of file kalmanFilter.h.
Member Typedef Documentation
DependentVector
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef FilterBase< IndependentVariableType, DependentVariableType >::DependentVector tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentVector
Definition at line 35 of file kalmanFilter.h.
DependentMatrix
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef FilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix
Definition at line 36 of file kalmanFilter.h.
Function
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef FilterBase< IndependentVariableType, DependentVariableType >::Function tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::Function
Definition at line 37 of file kalmanFilter.h.
MatrixFunction
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef FilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction
Definition at line 38 of file kalmanFilter.h.
IntegratorSettings
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef FilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings
Definition at line 39 of file kalmanFilter.h.
Integrator
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef FilterBase< IndependentVariableType, DependentVariableType >::Integrator tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::Integrator
Definition at line 40 of file kalmanFilter.h.
Constructor & Destructor Documentation
KalmanFilterBase()
template<typename IndependentVariableType = double, typename DependentVariableType = double> tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::KalmanFilterBase (const DependentMatrix & systemUncertainty, const DependentMatrix & measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector & initialStateVector, const DependentMatrix & initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings) inline
Constructor.
Parameters
systemUncertainty Matrix defining the uncertainty in modeling of the system.
measurementUncertainty Matrix defining the uncertainty in modeling of the measurements.
filteringStepSize Scalar representing the value of the constant filtering time step.
initialTime Scalar representing the value of the initial time.
initialStateVector Vector representing the initial (estimated) state of the system. It is used as first a-priori estimate of the state vector.
initialCovarianceMatrix Matrix representing the initial (estimated) covariance of the system. It is used as first a-priori estimate of the covariance matrix.
integratorSettings Settings for the numerical integrator to be used to propagate state.
Definition at line 55 of file kalmanFilter.h.
~KalmanFilterBase()
template<typename IndependentVariableType = double, typename DependentVariableType = double> virtual tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::~KalmanFilterBase () inline virtual
Definition at line 68 of file kalmanFilter.h.
Member Function Documentation
predictState() [1/2]
template<typename IndependentVariableType = double, typename DependentVariableType = double> DependentVector tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::predictState () inline protected virtual
Function to predict the state for the next time step, with the either the use of the integrator provided in the integratorSettings, or the systemFunction_ input by the user.
Returns
Propagated state at the requested time.
Implements tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >.
Definition at line 78 of file kalmanFilter.h.
References tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::aPosterioriStateEstimate_.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter(), tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter(), and tudat::filters::UnscentedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
predictState() [2/2]
template<typename IndependentVariableType = double, typename DependentVariableType = double> DependentVector tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::predictState (const DependentVector & currentStateVector) inline protected
Function to predict the state for the next time step, by overwriting previous state, with the either the use of the integrator provided in the integratorSettings, or the systemFunction_ input by the user.
Parameters
currentStateVector Vector representing the current state (which overwrites the previous state).
Returns
Propagated state at the requested time.
Definition at line 90 of file kalmanFilter.h.
References tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::currentTime_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::isStateToBeIntegrated_, tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::propagateState(), and tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::systemFunction_.
correctCovariance()
template<typename IndependentVariableType = double, typename DependentVariableType = double> virtual void tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::correctCovariance (const DependentMatrix & aPrioriCovarianceEstimate, const DependentMatrix & currentMeasurementMatrix, const DependentMatrix & kalmanGain) inline protected virtual
Function to correct the covariance for the next time step.
Parameters
aPrioriCovarianceEstimate Matrix denoting the a-priori covariance estimate.
currentMeasurementMatrix Matrix denoting the innovation, i.e., the correlation between system and measurement.
kalmanGain Matrix denoting the Kalman gain, to be used to correct the state estimate with the external measurement data.
Implements tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >.
Reimplemented in tudat::filters::UnscentedKalmanFilter< IndependentVariableType, DependentVariableType >.
Definition at line 103 of file kalmanFilter.h.
References tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::aPosterioriCovarianceEstimate_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::currentTime_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::historyOfCovarianceEstimates_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::identityMatrix_, and tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::measurementUncertainty_.
Referenced by tudat::filters::ExtendedKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter(), and tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
propagateState()
template<typename IndependentVariableType = double, typename DependentVariableType = double> DependentVector tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::propagateState (const DependentVector & currentStateVector) inline private
Function to propagate state to the next time step, by overwriting previous state, with the use of the integrator provided in the integratorSettings.
Parameters
currentStateVector Vector representing the current state (which overwrites the previous state).
Returns
Propagated state at the requested time.
Definition at line 122 of file kalmanFilter.h.
References tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::currentTime_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::filteringStepSize_, and tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::integrator_.
Referenced by tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::predictState().
The documentation for this class was generated from the following file:
Mathematics/Filters/kalmanFilter.h