Tudat: tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable > Class Template Reference
tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable > Class Template Reference
Function with basic implementations for derivatives and integrals.
#include <basicFunction.h>
Public Member Functions
BasicFunction (unsigned int numberOfIntegrationSteps=1000)
Constructor with definition of the number of steps.
virtual ~BasicFunction ()
Default destructor.
virtual DependentVariable computeDefiniteIntegral (const unsigned int order, const IndependentVariable lowerBound, const IndependentVariable upperbound)
Generic calculation of the function integral using numerical techniques.
DependentVariable computeDefiniteIntegralMock (const unsigned int order, const IndependentVariable lowerBound, const IndependentVariable upperbound, const DependentVariable placeHolder)
Alias for computeDefiniteIntegral, but with an extra variable. Should not be used!
virtual DependentVariable computeDerivative (const unsigned int order, const IndependentVariable independentVariable)
Derivative (of a given order) of a function.
Public Member Functions inherited from tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >
virtual ~Function ()
Default destructor.
virtual DependentVariable evaluate (const IndependentVariable inputValue)=0
Compute mathematical function value. This implementation is a pure virtual function.
DependentVariable operator() (const double inputValue)
Alias for evaluate(double).
Public Attributes
unsigned int integrationSteps
Number of steps to take when performing numerical integration.
Static Protected Attributes
static const double sqrt_epsilon_double = std::numeric_limits< double >::epsilon()
Square root of double precision, used to scale the step size.
Private Types
typedef numerical_integrators::RungeKutta4Integrator< IndependentVariable, DependentVariable, DependentVariable > Integrator
typedef for a Runge-Kutta 4 integration scheme.
typedef Function< IndependentVariable, DependentVariable > Parent
typedef for a Function that relates a Dependent Variable to an IndependentVariable.
Detailed Description
template<typename IndependentVariable = double, typename DependentVariable = double>
class tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >
This class fills in the computeDerivative and computeDefiniteIntegral functionality using numerical differentiation and integration. These are slower than their analytical counterparts, but useful when a closed form expression is available.
Definition at line 43 of file basicFunction.h.
Member Typedef Documentation
template<typename IndependentVariable = double, typename DependentVariable = double> typedef Function< IndependentVariable, DependentVariable > tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::Parent private
Definition at line 126 of file basicFunction.h.
template<typename IndependentVariable = double, typename DependentVariable = double> typedef numerical_integrators::RungeKutta4Integrator< IndependentVariable, DependentVariable, DependentVariable > tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::Integrator private
Definition at line 129 of file basicFunction.h.
Constructor & Destructor Documentation
template<typename IndependentVariable = double, typename DependentVariable = double> tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::BasicFunction (unsigned int numberOfIntegrationSteps = 1000) inline
Definition at line 51 of file basicFunction.h.
template<typename IndependentVariable = double, typename DependentVariable = double> virtual tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::~BasicFunction () inline virtual
Definition at line 56 of file basicFunction.h.
Member Function Documentation
template<typename IndependentVariable = double, typename DependentVariable = double> virtual DependentVariable tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::computeDerivative (const unsigned int order, const IndependentVariable independentVariable) inline virtual
Generic calculation of the derivative of a function using numerical techniques.
See also
Function::derivative TODO: Use the external derivative code, this function is a basic/temporary implementation. for now this is the implementation:
Parameters
order The Order of the derivative
independentVariable The independent variable with respect to which the derivative is taken.
Returns
The numerical derivative of the function.
Implements tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >.
Reimplemented in tudat::basic_mathematics::FunctionProxy< IndependentVariable, DependentVariable >.
Definition at line 68 of file basicFunction.h.
References tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >::evaluate(), tudat::propagators::independentVariable, and tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::sqrt_epsilon_double.
template<typename IndependentVariable = double, typename DependentVariable = double> DependentVariable tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::computeDefiniteIntegralMock (const unsigned int order, const IndependentVariable lowerBound, const IndependentVariable upperbound, const DependentVariable placeHolder) inline
Definition at line 88 of file basicFunction.h.
References tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::computeDefiniteIntegral().
template<typename IndependentVariable = double, typename DependentVariable = double> virtual DependentVariable tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::computeDefiniteIntegral (const unsigned int order, const IndependentVariable lowerBound, const IndependentVariable upperbound) inline virtual
Integral (of a given order) of a function from a given lower bound to upper bound (without constants).
TODO: Fix this code, as it doesnt work.
Parameters
order Order of integral (i.e. integrate n times, with n = order)
lowerBound Lower integration bound
upperbound Upper integration bound
Returns
Nothing as yet; function not yet implemented
See also
Function::computeDefiniteIntegral.
Implements tudat::basic_mathematics::Function< IndependentVariable, DependentVariable >.
Definition at line 106 of file basicFunction.h.
Referenced by tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::computeDefiniteIntegralMock().
Member Data Documentation
template<typename IndependentVariable = double, typename DependentVariable = double> unsigned int tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::integrationSteps
Definition at line 48 of file basicFunction.h.
template<typename IndependentVariable = double, typename DependentVariable = double> const double tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::sqrt_epsilon_double = std::numeric_limits< double >::epsilon() static protected
The reason not to scale with epsilon itself is to limit the error due to floating point arithmetic with super small numbers: = sqrt(std::numeric_limits<double>::epsilon()). TODO: Remove when using external derivative code.
Definition at line 121 of file basicFunction.h.
Referenced by tudat::basic_mathematics::BasicFunction< IndependentVariable, DependentVariable >::computeDerivative().
The documentation for this class was generated from the following file:
Mathematics/BasicMathematics/basicFunction.h