Tudat: tudat::propulsion::MeeCostateBasedThrustGuidance Class Reference
tudat::propulsion::MeeCostateBasedThrustGuidance Class Reference
Derived class which calculates the thrust direction based on costates for modified equinoctial elements.
#include <costateBasedThrustGuidance.h>
Public Member Functions
MeeCostateBasedThrustGuidance (const std::function< Eigen::Vector6d() > thrustingBodyStateFunction, const std::function< Eigen::Vector6d() > centralBodyStateFunction, const std::function< double() > centralBodyGravitationalParameterFunction, const std::function< Eigen::VectorXd(const double) > costateFunction, const std::function< Eigen::Vector3d() > bodyFixedForceDirection=[](){ return Eigen::Vector3d::UnitX();})
Constructor.
~MeeCostateBasedThrustGuidance ()
Destructor.
Eigen::Vector3d getCurrentForceDirectionInPropagationFrame ()
Function returning the current force direction, as computed by last call to updateCalculator/updateForceDirection.
Eigen::Quaterniond getRotationToGlobalFrame ()
Function to get the rotation from body-fixed to inertial frame.
Public Member Functions inherited from tudat::propulsion::BodyFixedForceDirectionGuidance
BodyFixedForceDirectionGuidance (const std::function< Eigen::Vector3d() > bodyFixedForceDirection)
Constructor.
virtual ~BodyFixedForceDirectionGuidance ()
Destructor.
Eigen::Quaterniond getRotationToLocalFrame ()
Function to compute the rotation from the propagation frame to the body-fixed frame.
void updateCalculator (const double time)
Function to update the object to the current time.
Public Member Functions inherited from tudat::reference_frames::DependentOrientationCalculator
DependentOrientationCalculator ()
Constructor.
virtual ~DependentOrientationCalculator ()
Destructor.
Eigen::Quaterniond computeAndGetRotationToLocalFrame (const double currentTime)
Function to update the object to the current time and retrieve the rotation to the local frame.
Eigen::Quaterniond getRotationToGlobalFrame (const double currentTime)
Function to update the object to the current time and retrieve the rotation to the global frame.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the object.
virtual void resetDerivedClassTime (const double currentTime=TUDAT_NAN)
Function to reset the current time in the derived class.
Private Member Functions
void updateForceDirection (const double time)
Function to update the force direction to the current time.
Private Attributes
std::function< double() > centralBodyGravitationalParameterFunction_
Function returning the gravitational parameter of the central body as a function of time.
std::function< Eigen::Vector6d() > centralBodyStateFunction_
Function returning the state of the central body as a function of time.
std::function< Eigen::VectorXd(const double) > costateFunction_
General function which gives the costates vector as a function of time.
Eigen::Vector3d currentForceDirection_
Direction of thrust force in propagation frame, as computed by last call to updateForceDirection function.
std::function< Eigen::Vector6d() > thrustingBodyStateFunction_
Function returning the state of the body under thrust as a function of time.
Additional Inherited Members
Protected Attributes inherited from tudat::propulsion::BodyFixedForceDirectionGuidance
std::function< Eigen::Vector3d() > bodyFixedForceDirection_
Function returning the direction of the force in the body-fixed frame.
Eigen::Vector3d currentBodyFixedForceDirection_
Current direction of the force in the body-fixed frame as set by last call to updateCalculator function.
Protected Attributes inherited from tudat::reference_frames::DependentOrientationCalculator
double currentTime_
Current simulation time.
Detailed Description
Derived class which calculates the thrust direction based on costates for modified equinoctial elements. The values of the costates are provided as input to the class (as a function of time), and are used to determine the thrust direction, based on the algorithm by Kluever (2010), extended to Modified Equinoctial Elements by Boudestijn (2014)
Definition at line 42 of file costateBasedThrustGuidance.h.
Constructor & Destructor Documentation
MeeCostateBasedThrustGuidance()
tudat::propulsion::MeeCostateBasedThrustGuidance::MeeCostateBasedThrustGuidance (const std::function< Eigen::Vector6d() > thrustingBodyStateFunction, const std::function< Eigen::Vector6d() > centralBodyStateFunction, const std::function< double() > centralBodyGravitationalParameterFunction, const std::function< Eigen::VectorXd(const double) > costateFunction, const std::function< Eigen::Vector3d() > bodyFixedForceDirection = [ ](){ return Eigen::Vector3d::UnitX(); })
Constructor
Parameters
thrustingBodyStateFunction Function returning the state of the body under thrust as a function of time
centralBodyStateFunction Function returning the state of the central body as a function of time
centralBodyGravitationalParameterFunction Function returning the gravitational parameter of the central body as a function of time
costateFunction Function which returns the costates as a function of time.
bodyFixedForceDirection Function returning the direction of the force in the body-fixed frame.
Definition at line 18 of file costateBasedThrustGuidance.cpp.
~MeeCostateBasedThrustGuidance()
tudat::propulsion::MeeCostateBasedThrustGuidance::~MeeCostateBasedThrustGuidance () inline
Definition at line 66 of file costateBasedThrustGuidance.h.
Member Function Documentation
getCurrentForceDirectionInPropagationFrame()
Eigen::Vector3d tudat::propulsion::MeeCostateBasedThrustGuidance::getCurrentForceDirectionInPropagationFrame () inline virtual
Function returning the current force direction, as computed by last call to updateCalculator/updateForceDirection, computed based on the MEE costates provided by the costateFunction_ member variable
Returns
Current force direction, expressed in propagation frame.
Implements tudat::propulsion::BodyFixedForceDirectionGuidance.
Definition at line 74 of file costateBasedThrustGuidance.h.
References currentForceDirection_.
getRotationToGlobalFrame()
Eigen::Quaterniond tudat::propulsion::MeeCostateBasedThrustGuidance::getRotationToGlobalFrame () inline virtual
Function to get the rotation from body-fixed to inertial frame. NOT YET IMPLEMENTED IN THIS DERIVED CLASS.
Returns
NOT YET IMPLEMENTED IN THIS DERIVED CLASS.
Implements tudat::reference_frames::DependentOrientationCalculator.
Definition at line 84 of file costateBasedThrustGuidance.h.
updateForceDirection()
void tudat::propulsion::MeeCostateBasedThrustGuidance::updateForceDirection (const double time) private virtual
Function to update the force direction to the current time.
Parameters
time Time to which object is to be updated.
Implements tudat::propulsion::BodyFixedForceDirectionGuidance.
Definition at line 31 of file costateBasedThrustGuidance.cpp.
References centralBodyGravitationalParameterFunction_, centralBodyStateFunction_, tudat::orbital_element_conversions::convertCartesianToModifiedEquinoctialElements(), costateFunction_, currentForceDirection_, tudat::reference_frames::DependentOrientationCalculator::currentTime_, tudat::reference_frames::getVelocityBasedLvlhToInertialRotation(), and thrustingBodyStateFunction_.
Member Data Documentation
thrustingBodyStateFunction_
std::function< Eigen::Vector6d() > tudat::propulsion::MeeCostateBasedThrustGuidance::thrustingBodyStateFunction_ private
Definition at line 100 of file costateBasedThrustGuidance.h.
Referenced by updateForceDirection().
centralBodyStateFunction_
std::function< Eigen::Vector6d() > tudat::propulsion::MeeCostateBasedThrustGuidance::centralBodyStateFunction_ private
Definition at line 103 of file costateBasedThrustGuidance.h.
Referenced by updateForceDirection().
centralBodyGravitationalParameterFunction_
std::function< double() > tudat::propulsion::MeeCostateBasedThrustGuidance::centralBodyGravitationalParameterFunction_ private
Definition at line 106 of file costateBasedThrustGuidance.h.
Referenced by updateForceDirection().
costateFunction_
std::function< Eigen::VectorXd(const double) > tudat::propulsion::MeeCostateBasedThrustGuidance::costateFunction_ private
Definition at line 109 of file costateBasedThrustGuidance.h.
Referenced by updateForceDirection().
currentForceDirection_
Eigen::Vector3d tudat::propulsion::MeeCostateBasedThrustGuidance::currentForceDirection_ private
Definition at line 112 of file costateBasedThrustGuidance.h.
Referenced by getCurrentForceDirectionInPropagationFrame(), and updateForceDirection().
The documentation for this class was generated from the following files:
Astrodynamics/Propulsion/costateBasedThrustGuidance.h
Astrodynamics/Propulsion/costateBasedThrustGuidance.cpp