Tudat: tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface Class Reference
tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface Class Reference abstract
Base class to hold an aerodynamic coefficient interface for a vehicle control surface.
#include <controlSurfaceAerodynamicCoefficientInterface.h>
Public Member Functions
ControlSurfaceIncrementAerodynamicInterface (const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Constructor.
virtual ~ControlSurfaceIncrementAerodynamicInterface ()
Destructor.
Eigen::Matrix< double, 6, 1 > getCurrentAerodynamicCoefficients ()
Function for returning current aerodynamic force and moment coefficients.
Eigen::Vector3d getCurrentForceCoefficients ()
Function for returning current aerodynamic force coefficients.
Eigen::Vector3d getCurrentMomentCoefficients ()
Function for returning current aerodynamic moment coefficients.
AerodynamicCoefficientsIndependentVariables getIndependentVariableName (const unsigned int index)
Function to return a single identifier of the physical meaning of one independent variable.
std::vector< AerodynamicCoefficientsIndependentVariables > getIndependentVariableNames ()
Function to return the identifiers of the physical meaning of each independent variable.
unsigned int getNumberOfIndependentVariables ()
Function to return the number of independent variables upon which the coeficients depend.
virtual void updateCurrentCoefficients (std::vector< double > &independentVariables)=0
Compute the aerodynamic coefficient increments of the control surface.
Protected Attributes
Eigen::Vector3d currentForceCoefficients_
The current force coefficient increments.
Eigen::Vector3d currentMomentCoefficients_
The current moment coefficient increments.
std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames_
Vector with identifiers for the physical meaning of each independent variable of the aerodynamic coefficients.
unsigned int numberOfIndependentVariables_
Number of independent variables upon which the force and moment coefficient increments depend.
Detailed Description
Base class to hold an aerodynamic coefficient interface for a vehicle control surface. This interface can, for instance, be a database of coefficients or an aerodynamic analysis code which generates coefficients.The aerodynamic coefficients are defined as a function of any number of independent variables, the physical meaning of which is stored in the coefficient interface. The control surface increment interface is always stored in an AerodynamicCoefficientInterface, and never used independently in propagation. As such, the aerodynamic reference quantities of this interface are not stored here, but are instead implicitly assumed to be equal to the AerodynamicCoefficientInterface hosting it.
Definition at line 39 of file controlSurfaceAerodynamicCoefficientInterface.h.
Constructor & Destructor Documentation
tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::ControlSurfaceIncrementAerodynamicInterface (const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames) inline
Constructor
Parameters
independentVariableNames List of independent variable names. Note that an error is shown if not exactly one of these is a control_surface_deflection_dependent.
Definition at line 49 of file controlSurfaceAerodynamicCoefficientInterface.h.
References tudat::aerodynamics::control_surface_deflection_dependent, independentVariableNames_, and numberOfIndependentVariables_.
virtual tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::~ControlSurfaceIncrementAerodynamicInterface () inline virtual
Definition at line 75 of file controlSurfaceAerodynamicCoefficientInterface.h.
References updateCurrentCoefficients().
Member Function Documentation
virtual void tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::updateCurrentCoefficients (std::vector< double > & independentVariables) pure virtual
Computes the current force and moment coefficients increments of the control surface, and is to be implemented in derived classes. Input is a set of independent variables (doubles) which represent the variables from which the coefficients are calculated
Parameters
independentVariables Independent variables of force and moment coefficient determination implemented by derived class
Implemented in tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface.
Referenced by ~ControlSurfaceIncrementAerodynamicInterface().
Eigen::Vector3d tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::getCurrentForceCoefficients () inline
Function for returning current aerodynamic force coefficients.
Returns
Force coefficients at current independent variables
Definition at line 93 of file controlSurfaceAerodynamicCoefficientInterface.h.
References currentForceCoefficients_.
Referenced by getCurrentAerodynamicCoefficients().
Eigen::Vector3d tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::getCurrentMomentCoefficients () inline
Function for returning current aerodynamic moment coefficients.
Returns
Moment coefficients at current independent variables
Definition at line 103 of file controlSurfaceAerodynamicCoefficientInterface.h.
References currentMomentCoefficients_.
Referenced by getCurrentAerodynamicCoefficients().
Eigen::Matrix< double, 6, 1 > tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::getCurrentAerodynamicCoefficients () inline
Function for returning current aerodynamic force and moment coefficients
Returns
Force and moment coefficients at given independent variables
Definition at line 113 of file controlSurfaceAerodynamicCoefficientInterface.h.
References getCurrentForceCoefficients(), and getCurrentMomentCoefficients().
std::vector< AerodynamicCoefficientsIndependentVariables > tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::getIndependentVariableNames () inline
Function to return the identifiers of the physical meaning of each independent variable of the aerodynamic coefficient interface.
Returns
A vector with the identifiers of the physical meaning of each independent variable.
Definition at line 127 of file controlSurfaceAerodynamicCoefficientInterface.h.
References independentVariableNames_.
AerodynamicCoefficientsIndependentVariables tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::getIndependentVariableName (const unsigned int index) inline
Function to return a single identifier of the physical meaning of one of the independent independent variable of the coefficient interface. The index of the variable is defined by the input variable.
Parameters
index Index of list of identfiers to return
Returns
The identifiers of the physical meaning of the independent variable at the position of the input variable.
Definition at line 141 of file controlSurfaceAerodynamicCoefficientInterface.h.
References independentVariableNames_, and numberOfIndependentVariables_.
unsigned int tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::getNumberOfIndependentVariables () inline
Function to return the number of independent variables upon which the coeficients depend. The size of the vector used as input for updateCurrentCoefficients should always have the size returned by this variable.
Returns
Number of independent variables upon which the coeficients depend
Definition at line 164 of file controlSurfaceAerodynamicCoefficientInterface.h.
References numberOfIndependentVariables_.
Member Data Documentation
std::vector< AerodynamicCoefficientsIndependentVariables > tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::independentVariableNames_ protected
Definition at line 172 of file controlSurfaceAerodynamicCoefficientInterface.h.
Referenced by ControlSurfaceIncrementAerodynamicInterface(), getIndependentVariableName(), and getIndependentVariableNames().
unsigned int tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::numberOfIndependentVariables_ protected
Number of independent variables upon which the force and moment coefficient increments depend, i.e. the length of the vectors that should be used as input to updateCurrentCoefficients
Definition at line 179 of file controlSurfaceAerodynamicCoefficientInterface.h.
Referenced by ControlSurfaceIncrementAerodynamicInterface(), getIndependentVariableName(), getNumberOfIndependentVariables(), and tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::updateCurrentCoefficients().
Eigen::Vector3d tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::currentForceCoefficients_ protected
The force coefficients increments at the current flight condition.
Definition at line 185 of file controlSurfaceAerodynamicCoefficientInterface.h.
Referenced by getCurrentForceCoefficients(), and tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::updateCurrentCoefficients().
Eigen::Vector3d tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::currentMomentCoefficients_ protected
The moment coefficient increments at the current flight condition.
Definition at line 191 of file controlSurfaceAerodynamicCoefficientInterface.h.
Referenced by getCurrentMomentCoefficients(), and tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::updateCurrentCoefficients().
The documentation for this class was generated from the following file:
Astrodynamics/Aerodynamics/controlSurfaceAerodynamicCoefficientInterface.h