Tudat: tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType > Class Template Reference
tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType > Class Template Reference
Hermite Cubic Spline Interpolator.
#include <hermiteCubicSplineInterpolator.h>
Public Member Functions
HermiteCubicSplineInterpolator (const std::vector< IndependentVariableType > &independentValues, const std::vector< DependentVariableType > &dependentValues, const std::vector< DependentVariableType > &derivativeValues, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Constructor.
HermiteCubicSplineInterpolator (const std::map< IndependentVariableType, DependentVariableType > &dataMap, const std::vector< DependentVariableType > &derivativeValues, const AvailableLookupScheme selectedLookupScheme=huntingAlgorithm, const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Constructor.
~HermiteCubicSplineInterpolator ()
Destructor.
std::vector< std::vector< DependentVariableType > > GetCoefficients ()
Get coefficients.
DependentVariableType interpolate (const IndependentVariableType targetIndependentVariableValue)
Function interpolates dependent variable value at given independent variable value.
Public Member Functions inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
OneDimensionalInterpolator (const BoundaryInterpolationType boundaryHandling=extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > &defaultExtrapolationValue=std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >()))
Constructor.
OneDimensionalInterpolator (const BoundaryInterpolationType boundaryHandling, const DependentVariableType &defaultExtrapolationValue)
Constructor.
virtual ~OneDimensionalInterpolator ()
Destructor.
std::vector< DependentVariableType > getDependentValues ()
Function to return the ector with dependent variables used by the interpolator.
std::vector< IndependentVariableType > getIndependentValues ()
Function to return the ector with independent variables used by the interpolator.
std::shared_ptr< LookUpScheme< IndependentVariableType > > getLookUpScheme ()
Function to return the lookup scheme used by the interpolator.
int getNumberOfDimensions ()
Function to return the number of independent variables of the interpolation.
virtual DependentVariableType interpolate (const std::vector< IndependentVariableType > &independentVariableValues)
Function to perform interpolation.
DependentVariableType interpolateNonConst (IndependentVariableType independentVariableValue)
Function to perform interpolation, with non-const input argument.
Public Member Functions inherited from tudat::interpolators::Interpolator< IndependentVariableType, DependentVariableType >
virtual ~Interpolator ()
Destructor.
Protected Member Functions
void computeCoefficients ()
Compute coefficients of the splines.
Protected Member Functions inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
void checkBoundaryCase (DependentVariableType &dependentVariable, bool &useValue, const IndependentVariableType &targetIndependentVariable)
Function to check whether boundary handling needs to be applied, depending on method chosen.
int checkInterpolationBoundary (const IndependentVariableType &targetIndependentVariable)
Function to return the condition of the current independent variable.
void makeLookupScheme (const AvailableLookupScheme selectedScheme)
Make look-up scheme that is to be used.
Private Attributes
std::vector< std::vector< DependentVariableType > > coefficients_
Coefficients of splines.
std::vector< DependentVariableType > derivativeValues_
Derivatives of dependent variable to independent variable.
Additional Inherited Members
Protected Attributes inherited from tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >
BoundaryInterpolationType boundaryHandling_
Behavior of interpolator when independent variable is outside range.
std::pair< DependentVariableType, DependentVariableType > defaultExtrapolationValue_
Default value to be used for extrapolation.
std::vector< DependentVariableType > dependentValues_
Vector with dependent variables.
std::vector< IndependentVariableType > independentValues_
Vector with independent variables.
std::shared_ptr< LookUpScheme< IndependentVariableType > > lookUpScheme_
Pointer to look up scheme.
Detailed Description
template<typename IndependentVariableType, typename DependentVariableType>
class tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >
Definition at line 30 of file hermiteCubicSplineInterpolator.h.
Constructor & Destructor Documentation
HermiteCubicSplineInterpolator() [1/2]
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::HermiteCubicSplineInterpolator (const std::vector< IndependentVariableType > & independentValues, const std::vector< DependentVariableType > & dependentValues, const std::vector< DependentVariableType > & derivativeValues, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm, const BoundaryInterpolationType boundaryHandling = extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > & defaultExtrapolationValue = std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >())) inline
Constructor for the hermite cubic spline interpolator with (in)dependent data defined in a vector.
Parameters
independentValues Vector with the independent variable values, must be sorted in ascending order.
dependentValues Vector with the dependent variable values.
derivativeValues Vector with the derivative values.
selectedLookupScheme Look-up scheme that is to be used when finding interval of requested independent variable value.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 53 of file hermiteCubicSplineInterpolator.h.
References tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::computeCoefficients(), tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::derivativeValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::makeLookupScheme().
HermiteCubicSplineInterpolator() [2/2]
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::HermiteCubicSplineInterpolator (const std::map< IndependentVariableType, DependentVariableType > & dataMap, const std::vector< DependentVariableType > & derivativeValues, const AvailableLookupScheme selectedLookupScheme = huntingAlgorithm, const BoundaryInterpolationType boundaryHandling = extrapolate_at_boundary, const std::pair< DependentVariableType, DependentVariableType > & defaultExtrapolationValue = std::make_pair(IdentityElement::getAdditionIdentity< DependentVariableType >(), IdentityElement::getAdditionIdentity< DependentVariableType >())) inline
Constructor for the hermite cubic spline interpolator with (in)dependent data defined in a map.
Parameters
dataMap Map with the independent variable values as keys and corresponding dependent variable values as values.
derivativeValues
selectedLookupScheme Look-up scheme that is to be used when finding interval of requested independent variable value.
boundaryHandling Boundary handling method, in case the independent variable is outside the specified range.
defaultExtrapolationValue Pair of default values to be used for extrapolation, in case of use_default_value or use_default_value_with_warning as methods for boundaryHandling.
Definition at line 108 of file hermiteCubicSplineInterpolator.h.
References tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::computeCoefficients(), tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::derivativeValues_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::makeLookupScheme().
~HermiteCubicSplineInterpolator()
template<typename IndependentVariableType , typename DependentVariableType > tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::~HermiteCubicSplineInterpolator () inline
Definition at line 143 of file hermiteCubicSplineInterpolator.h.
Member Function Documentation
GetCoefficients()
template<typename IndependentVariableType , typename DependentVariableType > std::vector< std::vector< DependentVariableType > > tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::GetCoefficients () inline
Definition at line 149 of file hermiteCubicSplineInterpolator.h.
References tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::coefficients_.
interpolate()
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::interpolate (const IndependentVariableType targetIndependentVariableValue) inline virtual
Function interpolates dependent variable value at given independent variable value.
Parameters
targetIndependentVariableValue Value of independent variable at which interpolation is to take place.
Returns
Interpolated value of interpolated dependent variable.
Implements tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >.
Definition at line 161 of file hermiteCubicSplineInterpolator.h.
References tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::checkBoundaryCase(), tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::coefficients_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::lookUpScheme_.
computeCoefficients()
template<typename IndependentVariableType , typename DependentVariableType > void tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::computeCoefficients () inline protected
Definition at line 190 of file hermiteCubicSplineInterpolator.h.
References tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::coefficients_, tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::dependentValues_, tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::derivativeValues_, and tudat::interpolators::OneDimensionalInterpolator< IndependentVariableType, DependentVariableType >::independentValues_.
Referenced by tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::HermiteCubicSplineInterpolator().
Member Data Documentation
derivativeValues_
template<typename IndependentVariableType , typename DependentVariableType > std::vector< DependentVariableType > tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::derivativeValues_ private
Definition at line 224 of file hermiteCubicSplineInterpolator.h.
Referenced by tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::computeCoefficients(), and tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::HermiteCubicSplineInterpolator().
coefficients_
template<typename IndependentVariableType , typename DependentVariableType > std::vector< std::vector< DependentVariableType > > tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::coefficients_ private
Definition at line 227 of file hermiteCubicSplineInterpolator.h.
Referenced by tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::computeCoefficients(), tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::GetCoefficients(), and tudat::interpolators::HermiteCubicSplineInterpolator< IndependentVariableType, DependentVariableType >::interpolate().
The documentation for this class was generated from the following file:
Mathematics/Interpolators/hermiteCubicSplineInterpolator.h