Tudat: tudat::ephemerides::ApproximatePlanetPositionsBase Class Reference
tudat::ephemerides::ApproximatePlanetPositionsBase Class Reference
Ephemeris base class using JPL "Approximate Positions of Major Planets".
#include <approximatePlanetPositionsBase.h>
Public Types
enum BodiesWithEphemerisData {
mercury, venus, earthMoonBarycenter, mars,
jupiter, saturn, uranus, neptune,
pluto
}
Bodies with ephemeris data.
Public Member Functions
ApproximatePlanetPositionsBase (const double aSunGravitationalParameter)
Default constructor.
virtual ~ApproximatePlanetPositionsBase ()
Default destructor.
double getSunGravitationalParameter ()
Returns the gravitational parameter of the Sun.
void parseEphemerisLineData_ (const unsigned int &firstLineNumber)
Parse ephemeris line data.
void parseExtraTermsEphemerisLineData_ (const unsigned int &lineNumber)
Parse line data for extra terms for ephemeris.
void reloadData ()
Load in ephemeris data for planets.
Public Member Functions inherited from tudat::ephemerides::Ephemeris
Ephemeris (const std::string &referenceFrameOrigin="", const std::string &referenceFrameOrientation="")
Constructor.
virtual ~Ephemeris ()
Default destructor.
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get state from ephemeris (with long double as state scalar).
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with long double as state scalar and Time as time type).
virtual Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)=0
Get state from ephemeris.
virtual Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with double as state scalar and Time as time type).
std::string getReferenceFrameOrientation ()
Get reference frame orientation.
std::string getReferenceFrameOrigin ()
Get reference frame origin.
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (double specialization).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (long double specialization).
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (double specialization with Time input).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (long double specialization with Time input).
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > getTemplatedStateFromEphemeris (const TimeType &time)
Get state from ephemeris, with state scalar as template type.
Protected Member Functions
void setPlanet (BodiesWithEphemerisData bodyWithEphemerisData)
Set planet.
Protected Attributes
ApproximatePlanetPositionsDataContainer approximatePlanetPositionsDataContainer_
Approximate planet positions data container.
std::map< unsigned int, std::string > containerOfDataFromEphemerisFile_
Map container of data from ephemeris file.
std::stringstream ephemerisLineData_
String stream for ephemeris line data.
double julianDate_
Julian date.
double meanLongitudeAtGivenJulianDate_
Mean longitude at given Julian date.
double numberOfCenturiesPastJ2000_
Number of centuries passed J2000.
Eigen::Vector6d planetKeplerianElementsAtGivenJulianDate_
Keplerian elements of planet at given Julian date.
const double sunGravitationalParameter
Gravitational parameter of the Sun.
Protected Attributes inherited from tudat::ephemerides::Ephemeris
std::string referenceFrameOrientation_
Reference frame orientation.
std::string referenceFrameOrigin_
Reference frame origin.
Detailed Description
Ephemeris base class using JPL "Approximate Positions of Major Planets".
Definition at line 43 of file approximatePlanetPositionsBase.h.
Member Enumeration Documentation
enum tudat::ephemerides::ApproximatePlanetPositionsBase::BodiesWithEphemerisData
Enumerator
mercury
venus
earthMoonBarycenter
mars
jupiter
saturn
uranus
neptune
pluto
Definition at line 48 of file approximatePlanetPositionsBase.h.
Constructor & Destructor Documentation
tudat::ephemerides::ApproximatePlanetPositionsBase::ApproximatePlanetPositionsBase (const double aSunGravitationalParameter) inline
Default constructor of the base class, initializes the gravitational parameter of the Sun to the input value, and all other private base class members to default values.
Parameters
aSunGravitationalParameter The gravitational parameter of the Sun [m^3/s^2].
See also
ApproximatePlanetPositions, ApproximatePlanetPositionsCircularCoplanar.
Definition at line 61 of file approximatePlanetPositionsBase.h.
virtual tudat::ephemerides::ApproximatePlanetPositionsBase::~ApproximatePlanetPositionsBase () inline virtual
Definition at line 71 of file approximatePlanetPositionsBase.h.
References parseEphemerisLineData_(), parseExtraTermsEphemerisLineData_(), and reloadData().
Member Function Documentation
void tudat::ephemerides::ApproximatePlanetPositionsBase::parseEphemerisLineData_ (const unsigned int & firstLineNumber)
Parses ephemeris line data.
Parameters
firstLineNumber First line number.
Definition at line 93 of file approximatePlanetPositionsBase.cpp.
References approximatePlanetPositionsDataContainer_, containerOfDataFromEphemerisFile_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::eccentricity_, ephemerisLineData_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::inclination_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::longitudeOfAscendingNode_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::longitudeOfPerihelion_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::meanLongitude_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::planetName_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfEccentricity_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfInclination_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfLongitudeOfAscendingNode_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfLongitudeOfPerihelion_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfMeanLongitude_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfSemiMajorAxis_, and tudat::ephemerides::ApproximatePlanetPositionsDataContainer::semiMajorAxis_.
Referenced by setPlanet(), and ~ApproximatePlanetPositionsBase().
void tudat::ephemerides::ApproximatePlanetPositionsBase::parseExtraTermsEphemerisLineData_ (const unsigned int & lineNumber)
Parses ephemeris line data for necessary extra terms.
Parameters
lineNumber Line number.
Definition at line 138 of file approximatePlanetPositionsBase.cpp.
References tudat::ephemerides::ApproximatePlanetPositionsDataContainer::additionalTermB_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::additionalTermC_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::additionalTermF_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::additionalTermS_, approximatePlanetPositionsDataContainer_, containerOfDataFromEphemerisFile_, ephemerisLineData_, and tudat::ephemerides::ApproximatePlanetPositionsDataContainer::planetName_.
Referenced by setPlanet(), and ~ApproximatePlanetPositionsBase().
void tudat::ephemerides::ApproximatePlanetPositionsBase::reloadData ()
This method opens and parses the p_elem_t2.txt ephemeris files for the planet positions. The resulting data is stored in ApproximatePlanetPositionsBase::containerOfDataFromEphemerisFile_ to be used in the generation of planet ephemeris. This method is automatically invoked if you call ApproximatePlanetPositionsBase::setPlanet(BodiesWithEphemerisData).
Definition at line 155 of file approximatePlanetPositionsBase.cpp.
References containerOfDataFromEphemerisFile_, and tudat::input_output::getTudatRootPath().
Referenced by setPlanet(), and ~ApproximatePlanetPositionsBase().
double tudat::ephemerides::ApproximatePlanetPositionsBase::getSunGravitationalParameter () inline
Returns the gravitational parameter of the Sun that is used in the calculations.
Returns
Gravitational parameter of the Sun.
Definition at line 102 of file approximatePlanetPositionsBase.h.
References setPlanet(), and sunGravitationalParameter.
void tudat::ephemerides::ApproximatePlanetPositionsBase::setPlanet (BodiesWithEphemerisData bodyWithEphemerisData) protected
Sets planet to retrieve ephemeris data for.
Parameters
bodyWithEphemerisData Planet.
Definition at line 27 of file approximatePlanetPositionsBase.cpp.
References containerOfDataFromEphemerisFile_, earthMoonBarycenter, jupiter, mars, mercury, neptune, parseEphemerisLineData_(), parseExtraTermsEphemerisLineData_(), pluto, reloadData(), saturn, uranus, and venus.
Referenced by tudat::ephemerides::ApproximatePlanetPositions::ApproximatePlanetPositions(), tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::ApproximatePlanetPositionsCircularCoplanar(), and getSunGravitationalParameter().
Member Data Documentation
const double tudat::ephemerides::ApproximatePlanetPositionsBase::sunGravitationalParameter protected
Gravitational parameter of the Sun.
Definition at line 117 of file approximatePlanetPositionsBase.h.
Referenced by tudat::ephemerides::ApproximatePlanetPositions::getCartesianState(), tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), and getSunGravitationalParameter().
double tudat::ephemerides::ApproximatePlanetPositionsBase::julianDate_ protected
Julian date at which to obtain planet's orbital elements.
Definition at line 123 of file approximatePlanetPositionsBase.h.
Referenced by tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), and tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris().
double tudat::ephemerides::ApproximatePlanetPositionsBase::meanLongitudeAtGivenJulianDate_ protected
Mean longitude of planet at given Julian date.
Definition at line 129 of file approximatePlanetPositionsBase.h.
Referenced by tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), and tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris().
double tudat::ephemerides::ApproximatePlanetPositionsBase::numberOfCenturiesPastJ2000_ protected
Number of centuries passed J2000, computed using Julian date defined by user when retrieving state.
Definition at line 136 of file approximatePlanetPositionsBase.h.
Referenced by tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), and tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris().
std::map< unsigned int, std::string > tudat::ephemerides::ApproximatePlanetPositionsBase::containerOfDataFromEphemerisFile_ protected
Map container of string data from ephemeris data file.
Definition at line 142 of file approximatePlanetPositionsBase.h.
Referenced by parseEphemerisLineData_(), parseExtraTermsEphemerisLineData_(), reloadData(), and setPlanet().
ApproximatePlanetPositionsDataContainer tudat::ephemerides::ApproximatePlanetPositionsBase::approximatePlanetPositionsDataContainer_ protected
Approximate planet positions data container.
Definition at line 148 of file approximatePlanetPositionsBase.h.
Referenced by tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris(), parseEphemerisLineData_(), and parseExtraTermsEphemerisLineData_().
Eigen::Vector6d tudat::ephemerides::ApproximatePlanetPositionsBase::planetKeplerianElementsAtGivenJulianDate_ protected
Keplerian elements of planet at given Julian date.
Definition at line 154 of file approximatePlanetPositionsBase.h.
Referenced by tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris().
std::stringstream tudat::ephemerides::ApproximatePlanetPositionsBase::ephemerisLineData_ protected
String stream for ephemeris line data.
Definition at line 160 of file approximatePlanetPositionsBase.h.
Referenced by parseEphemerisLineData_(), and parseExtraTermsEphemerisLineData_().
The documentation for this class was generated from the following files:
Astrodynamics/Ephemerides/approximatePlanetPositionsBase.h
Astrodynamics/Ephemerides/approximatePlanetPositionsBase.cpp