Tudat: tudat::reference_frames Namespace Reference
tudat::reference_frames Namespace Reference
Classes
class AerodynamicAngleCalculator
Object to calculate aerodynamic orientation angles from current vehicle state.
class AerodynamicAnglesClosure
Wrapper class to set closure between an imposed orientation of a body and its bank, sideslip and attack angles.
class ApparentAccelerationModel
Apparent acceleration model class.
class DependentOrientationCalculator
Class that computes the orientation of a body as a function of the current state and time.
Typedefs
typedef std::shared_ptr< ApparentAccelerationModel > ApparentAccelerationModelPointer
Typedef for shared-pointer to ApparentAccelerationModel object.
Enumerations
enum AerodynamicsReferenceFrameAngles {
latitude_angle = 0, longitude_angle = 1, heading_angle = 2, flight_path_angle = 3,
angle_of_attack = 4, angle_of_sideslip = 5, bank_angle = 6
}
enum AerodynamicsReferenceFrames {
inertial_frame = -1, corotating_frame = 0, vertical_frame = 1, trajectory_frame = 2,
aerodynamic_frame = 3, body_frame = 4
}
Functions
double calculateFlightPathAngle (const Eigen::Vector3d &velocityInVerticalFrame)
Calculate current flight path angle.
double calculateHeadingAngle (const Eigen::Vector3d &velocityInVerticalFrame)
Calculate current heading angle.
Eigen::Vector3d calculateInertialToPlanetFixedRotationAnglesFromMatrix (const Eigen::Matrix3d &rotationMatrixFromInertialToPlanetFixedFrame)
Function to compute pole right ascension and declination, as well as prime meridian of date, from rotation matrix.
Eigen::Vector3d computeApparentAcceleration (const Eigen::Vector3d &accelerationOfNonInertialReferenceFrame, const Eigen::Vector3d &angularVelocityOfNonInertialReferenceFrame, const Eigen::Vector3d &angularAccelerationOfNonInertialReferenceFrame, const Eigen::Vector3d &positionOfBodyInNonInertialReferenceFrame, const Eigen::Vector3d &velocityOfBodyInNonInertialReferenceFrame)
Compute apparent acceleration due to non-inertiality of reference frame.
Eigen::Vector3d computeCentripetalAcceleration (const Eigen::Vector3d &angularVelocityOfNonInertialReferenceFrame, const Eigen::Vector3d &positionOfBodyInNonInertialReferenceFrame)
Compute centripetal acceleration due to non-inertiality of reference frame.
Eigen::Vector3d computeCoriolisAcceleration (const Eigen::Vector3d &angularVelocityOfNonInertialReferenceFrame, const Eigen::Vector3d &velocityOfBodyInNonInertialReferenceFrame)
Compute Coriolis acceleration due to non-inertiality of reference frame.
Eigen::Vector3d computeEulerAcceleration (const Eigen::Vector3d &angularAccelerationOfNonInertialReferenceFrame, const Eigen::Vector3d &positionOfBodyInNonInertialReferenceFrame)
Compute Euler acceleration due to non-inertiality of reference frame.
void from_json (const nlohmann::json &jsonObject, AerodynamicsReferenceFrames &aerodynamicsReferenceFrame)
Convert json to AerodynamicsReferenceFrames.
void from_json (const nlohmann::json &jsonObject, AerodynamicsReferenceFrameAngles &aerodynamicsReferenceFrameAngle)
Convert json to AerodynamicsReferenceFrameAngles.
Eigen::Vector3d get132EulerAnglesFromRotationMatrix (const Eigen::Matrix3d &rotationMatrix)
Get classical 1-3-2 Euler angles set from rotation matrix.
std::string getAerodynamicAngleName (const AerodynamicsReferenceFrameAngles angle)
Function to get a string representing a 'named identification' of an aerodynamic angle.
std::function< Eigen::Vector3d(const Eigen::Vector3d &) > getAerodynamicForceTransformationFunction (const std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator, const AerodynamicsReferenceFrames accelerationFrame, const std::function< Eigen::Quaterniond() > bodyFixedToInertialFrameFunction, const AerodynamicsReferenceFrames propagationFrame)
Get a function to transform aerodynamic force from local to propagation frame.
std::string getAerodynamicFrameName (const AerodynamicsReferenceFrames frame)
Function to get a string representing a 'named identification' of a reference frame.
Eigen::Matrix3d getAerodynamicToTrajectoryFrameTransformationMatrix (const double bankAngle)
Get transformation matrix from the AA- to the TA-frame.
Eigen::Quaterniond getAerodynamicToTrajectoryFrameTransformationQuaternion (const double bankAngle)
Get transformation quaternion from the AA- to the TA-frame.
Eigen::Matrix3d getAirspeedBasedAerodynamicToBodyFrameTransformationMatrix (const double angleOfAttack, const double angleOfSideslip)
Get transformation matrix fom the AA- to the B-frame.
Eigen::Quaterniond getAirspeedBasedAerodynamicToBodyFrameTransformationQuaternion (const double angleOfAttack, const double angleOfSideslip)
Get transformation quaternion fom the AA- to the B-frame.
Eigen::Vector3d getBodyFixedCartesianPosition (const std::function< Eigen::Vector3d() > positionFunctionOfCentralBody, const std::function< Eigen::Vector3d() > positionFunctionOfRelativeBody, const std::function< Eigen::Quaterniond() > orientationFunctionOfCentralBody)
Function to compute a body-fixed relative cartesian position.
Eigen::Vector3d getBodyFixedSphericalPosition (const std::function< Eigen::Vector3d() > positionFunctionOfCentralBody, const std::function< Eigen::Vector3d() > positionFunctionOfRelativeBody, const std::function< Eigen::Quaterniond() > orientationFunctionOfCentralBody)
Function to compute a body-fixed relative spherical position.
Eigen::Matrix3d getBodyToAirspeedBasedAerodynamicFrameTransformationMatrix (const double angleOfAttack, const double angleOfSideslip)
Get transformation matrix fom the B- to the AA-frame.
Eigen::Quaterniond getBodyToAirspeedBasedAerodynamicFrameTransformationQuaternion (const double angleOfAttack, const double angleOfSideslip)
Get transformation quaternion fom the B- to the AA-frame.
Eigen::Matrix3d getDerivativeOfXAxisRotationWrtAngle (const double angle)
Function to compute the derivative of a rotation about the x-axis w.r.t. the rotation angle.
Eigen::Matrix3d getDerivativeOfXAxisRotationWrtAngle (const Eigen::Matrix3d &rotationMatrix)
Function to compute the derivative of a rotation about the x-axis w.r.t. the rotation angle.
Eigen::Matrix3d getDerivativeOfYAxisRotationWrtAngle (const double angle)
Function to compute the derivative of a rotation about the y-axis w.r.t. the rotation angle.
Eigen::Matrix3d getDerivativeOfYAxisRotationWrtAngle (const Eigen::Matrix3d &rotationMatrix)
Function to compute the derivative of a rotation about the y-axis w.r.t. the rotation angle.
Eigen::Matrix3d getDerivativeOfZAxisRotationWrtAngle (const double angle)
Function to compute the derivative of a rotation about the z-axis w.r.t. the rotation angle.
Eigen::Matrix3d getDerivativeOfZAxisRotationWrtAngle (const Eigen::Matrix3d &rotationMatrix)
Function to compute the derivative of a rotation about the z-axis w.r.t. the rotation angle.
Eigen::Quaterniond getEnuLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion (double longitude, double latitude)
Get transformation quaternion between V-frame and ECEF.
Eigen::Matrix3d getInertialToPlanetocentricFrameTransformationMatrix (const double angleFromXItoXR)
Get inertial (I) to rotating planetocentric (R) reference frame transformtion matrix.
Eigen::Quaterniond getInertialToPlanetocentricFrameTransformationQuaternion (const double angleFromXItoXR)
Get inertial (I) to rotating planetocentric (R) reference frame transformtion quaternion.
Eigen::Quaterniond getInertialToPlanetocentricFrameTransformationQuaternion (const double declinationOfPole, const double rightAscensionOfPole, const double longitudeOfPrimeMeridian)
Get rotation from inertial to planet-fixed frame.
Eigen::Matrix3d getInertialToRswSatelliteCenteredFrameRotationMatrix (const Eigen::Vector6d bodyState)
Function to compute the rotation matrix to RSW frame, from the frame in which the input state is given.
Eigen::Matrix3d getLocalVerticalFrameToTrajectoryTransformationMatrix (const double flightPathAngle, const double headingAngle)
Get transformation matrix from the local V- to TA/TG-frame.
Eigen::Quaterniond getLocalVerticalFrameToTrajectoryTransformationQuaternion (const double flightPathAngle, const double headingAngle)
Get transformation quaternion from V- to the TA/TG-frame.
Eigen::Matrix3d getLocalVerticalToRotatingPlanetocentricFrameTransformationMatrix (const double longitude, const double latitude)
Get transformation matrix from local vertical (V) to the Planetocentric frame (R).
Eigen::Quaterniond getLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion (const double longitude, const double latitude)
Get transformation quaternion from local vertical (V) to the Planetocentric frame (R).
Eigen::Quaterniond getQuaternionObjectFromQuaternionValues (const Eigen::Vector4d &vectorWithQuaternion)
Create a Quaterniond rotation state object from four quaternion values in a Vector4d.
Eigen::Quaterniond getRotatingPlanetocentricToEnuLocalVerticalFrameTransformationQuaternion (double longitude, double latitude)
Get transformation quaternion ECEF to ENU V-frame.
Eigen::Matrix3d getRotatingPlanetocentricToInertialFrameTransformationMatrix (const double angleFromXItoXR)
Get rotating planetocentric (R) to inertial (I) reference frame transformation matrix.
Eigen::Quaterniond getRotatingPlanetocentricToInertialFrameTransformationQuaternion (const double angleFromXItoXR)
Get rotating planetocentric (R) to inertial (I) reference frame transformation quaternion.
Eigen::Quaterniond getRotatingPlanetocentricToInertialFrameTransformationQuaternion (const double declinationOfPole, const double rightAscensionOfPole, const double longitudeOfPrimeMeridian)
Get rotation from planet-fixed to inertial frame.
Eigen::Matrix3d getRotatingPlanetocentricToLocalVerticalFrameTransformationMatrix (const double longitude, const double latitude)
Get transformation matrix from Planetocentric (R) to the Local vertical (V) frame.
Eigen::Quaterniond getRotatingPlanetocentricToLocalVerticalFrameTransformationQuaternion (const double longitude, const double latitude)
Get transformation quaternion from Planetocentric (R) to the Local vertical (V) frame.
Eigen::Matrix3d getTrajectoryToAerodynamicFrameTransformationMatrix (const double bankAngle)
Get transformation matrix from the TA- to the AA-frame.
Eigen::Quaterniond getTrajectoryToAerodynamicFrameTransformationQuaternion (const double bankAngle)
Get transformation quaternion from the TA- to the AA-frame.
Eigen::Matrix3d getTrajectoryToLocalVerticalFrameTransformationMatrix (const double flightPathAngle, const double headingAngle)
Get transformation matrix from the TA/TG to the V-frame.
Eigen::Quaterniond getTrajectoryToLocalVerticalFrameTransformationQuaternion (const double flightPathAngle, const double headingAngle)
Get transformation quaternion from the TA/TG to the V-frame.
Eigen::Matrix3d getVelocityBasedLvlhToInertialRotation (const Eigen::Vector6d &vehicleState, const Eigen::Vector6d &centralBodyState, const bool doesNaxisPointAwayFromCentralBody)
Get rotation from velocity based LVLH frame to inertial frame (I) frame.
Eigen::Matrix3d getVelocityBasedLvlhToInertialRotationFromFunctions (const std::function< Eigen::Vector6d() > &vehicleStateFunction, const std::function< Eigen::Vector6d() > &centralBodyStateFunction, const bool doesNaxisPointAwayFromCentralBody)
Get rotation from velocity based LVLH frame to inertial frame (I) frame.
Eigen::Quaterniond getVelocityBasedLvlhToPlanetocentricRotationKeplerian (const Eigen::Matrix< double, 6, 1 > spacecraftKeplerianState)
Get rotation from velocity based LVLH frame to planetocentric frame.
void setAerodynamicDependentOrientationCalculatorClosure (const std::function< Eigen::Quaterniond(const double) > imposedRotationFromInertialToBodyFixedFrame, std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Function to make aerodynamic angle computation consistent with imposed body-fixed to inertial rotation.
void setAerodynamicDependentOrientationCalculatorClosure (std::shared_ptr< DependentOrientationCalculator > dependentOrientationCalculator, std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Function to make aerodynamic angle computation consistent with existing DependentOrientationCalculator.
void setAerodynamicDependentOrientationCalculatorClosure (std::shared_ptr< ephemerides::RotationalEphemeris > rotationalEphemeris, std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Function to make aerodynamic angle computation consistent with existing rotational ephemeris.
void to_json (nlohmann::json &jsonObject, const AerodynamicsReferenceFrames &aerodynamicsReferenceFrame)
Convert AerodynamicsReferenceFrames to json.
void to_json (nlohmann::json &jsonObject, const AerodynamicsReferenceFrameAngles &aerodynamicsReferenceFrameAngle)
Convert AerodynamicsReferenceFrameAngles to json.
Eigen::Vector3d transformVectorFromQuaternionFunction (const Eigen::Vector3d &originalVector, const std::function< Eigen::Quaterniond() > rotation)
Wrapper function to transform a vector to a different frame from a single rotation function.
Eigen::Vector3d transformVectorFromVectorFunctions (const Eigen::Vector3d &originalVector, const std::vector< std::function< Eigen::Vector3d(const Eigen::Vector3d &) > > &rotationsList)
Wrapper function to transform a vector to a different frame from a list of transformation function.
Eigen::Vector3d transformVectorFunctionFromVectorFunctions (const std::function< Eigen::Vector3d() > originalVector, const std::function< Eigen::Vector3d(const Eigen::Vector3d &) > transformationFunction)
Wrapper function to transform a vector to a different frame from a single transformation function.
Variables
static std::map< AerodynamicsReferenceFrameAngles, std::string > aerodynamicsReferenceFrameAngles
Map of AerodynamicsReferenceFrameAngles string representations.
static std::map< AerodynamicsReferenceFrames, std::string > aerodynamicsReferenceFrames
Map of AerodynamicsReferenceFrames string representations.
std::function< Eigen::Vector3d(const Eigen::Vector3d &) > getAerodynamicForceTransformationFunction (const std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator, const AerodynamicsReferenceFrames accelerationFrame, const std::function< Eigen::Quaterniond() > bodyFixedToInertialFrameFunction=[](){ return Eigen::Quaterniond(Eigen::Matrix3d::Identity());}, const AerodynamicsReferenceFrames propagationFrame=inertial_frame)
Get a function to transform aerodynamic force from local to propagation frame.
static std::vector< AerodynamicsReferenceFrameAngles > unsupportedAerodynamicsReferenceFrameAngles = { }
AerodynamicsReferenceFrameAngles not supported by json_interface.
static std::vector< AerodynamicsReferenceFrames > unsupportedAerodynamicsReferenceFrames = { }
AerodynamicsReferenceFrames not supported by json_interface.
static const Eigen::Matrix3d X_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER
Pre-multiplier used to take derivative of rotation matrix about x-axis w.r.t. the rotation angle.
static const Eigen::Matrix3d Y_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER
Pre-multiplier used to take derivative of rotation matrix about y-axis w.r.t. the rotation angle.
static const Eigen::Matrix3d Z_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER
Pre-multiplier used to take derivative of rotation matrix about z-axis w.r.t. the rotation angle.
Typedef Documentation
ApparentAccelerationModelPointer
typedef std::shared_ptr< ApparentAccelerationModel > tudat::reference_frames::ApparentAccelerationModelPointer
Definition at line 286 of file apparentAccelerationModel.h.
Enumeration Type Documentation
AerodynamicsReferenceFrames
enum tudat::reference_frames::AerodynamicsReferenceFrames
Enum to define ids for various reference frames for calculating between inertial and body-fixed frame, using transformation chain via aerodynamic frame.
Enumerator
inertial_frame
corotating_frame
vertical_frame
trajectory_frame
aerodynamic_frame
body_frame
Definition at line 39 of file aerodynamicAngleCalculator.h.
AerodynamicsReferenceFrameAngles
enum tudat::reference_frames::AerodynamicsReferenceFrameAngles
Enum to define ids for various angles needed for converting between inertial and body-fixed frame, using transformation chain via aerodynamic frame.
Enumerator
latitude_angle
longitude_angle
heading_angle
flight_path_angle
angle_of_attack
angle_of_sideslip
bank_angle
Definition at line 59 of file aerodynamicAngleCalculator.h.
Function Documentation
getAerodynamicFrameName()
std::string tudat::reference_frames::getAerodynamicFrameName (const AerodynamicsReferenceFrames frame)
Function to get a string representing a 'named identification' of a reference frame.
Parameters
frame Type of reference frame
Returns
String with reference frame id.
Definition at line 30 of file aerodynamicAngleCalculator.cpp.
References aerodynamic_frame, body_frame, corotating_frame, inertial_frame, trajectory_frame, and vertical_frame.
Referenced by tudat::propagators::getDependentVariableId().
getAerodynamicAngleName()
std::string tudat::reference_frames::getAerodynamicAngleName (const AerodynamicsReferenceFrameAngles angle)
Function to get a string representing a 'named identification' of an aerodynamic angle
Parameters
angle Type of aerodynamic angle
Returns
String withaerodynamic angle id.
Definition at line 63 of file aerodynamicAngleCalculator.cpp.
References angle_of_attack, angle_of_sideslip, bank_angle, flight_path_angle, heading_angle, latitude_angle, and longitude_angle.
Referenced by tudat::propagators::getDependentVariableId().
getAerodynamicForceTransformationFunction()
std::function< Eigen::Vector3d(const Eigen::Vector3d&) > tudat::reference_frames::getAerodynamicForceTransformationFunction (const std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator, const AerodynamicsReferenceFrames accelerationFrame, const std::function< Eigen::Quaterniond() > bodyFixedToInertialFrameFunction, const AerodynamicsReferenceFrames propagationFrame)
Definition at line 436 of file aerodynamicAngleCalculator.cpp.
References corotating_frame, tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames(), inertial_frame, transformVectorFromQuaternionFunction(), and transformVectorFromVectorFunctions().
setAerodynamicDependentOrientationCalculatorClosure() [1/3]
void tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure (const std::function< Eigen::Quaterniond(const double) > imposedRotationFromInertialToBodyFixedFrame, std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Function to make aerodynamic angle computation consistent with imposed body-fixed to inertial rotation.
Parameters
imposedRotationFromInertialToBodyFixedFrame Inertial to body-fixed frame rotation to which the aerodynamicAngleCalculator object is to be made consistent
aerodynamicAngleCalculator Object from which the aerodynamic angles are computed.
Definition at line 499 of file aerodynamicAngleCalculator.cpp.
References tudat::reference_frames::AerodynamicAnglesClosure::getCurrentAngleOfAttack(), tudat::reference_frames::AerodynamicAnglesClosure::getCurrentAngleOfSideslip(), tudat::reference_frames::AerodynamicAnglesClosure::getCurrentBankAngle(), and tudat::reference_frames::AerodynamicAnglesClosure::updateAngles().
Referenced by setAerodynamicDependentOrientationCalculatorClosure(), tudat::simulation_setup::Body::setDependentOrientationCalculator(), tudat::simulation_setup::Body::setFlightConditions(), and tudat::propagators::setMultiTypePropagationClosure().
setAerodynamicDependentOrientationCalculatorClosure() [2/3]
void tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure (std::shared_ptr< DependentOrientationCalculator > dependentOrientationCalculator, std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Function to make aerodynamic angle computation consistent with existing DependentOrientationCalculator
Parameters
dependentOrientationCalculator Object computing the current orientation based on the current state of the environment. Aerodynamic angles are to be computed from output given by this class.
aerodynamicAngleCalculator Object from which the aerodynamic angles are computed.
Definition at line 514 of file aerodynamicAngleCalculator.cpp.
References tudat::reference_frames::DependentOrientationCalculator::computeAndGetRotationToLocalFrame(), and setAerodynamicDependentOrientationCalculatorClosure().
setAerodynamicDependentOrientationCalculatorClosure() [3/3]
void tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure (std::shared_ptr< ephemerides::RotationalEphemeris > rotationalEphemeris, std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator)
Function to make aerodynamic angle computation consistent with existing rotational ephemeris
Parameters
rotationalEphemeris Object computing the current orientation of the body. Aerodynamic angles are to be computed from output given by this class.
aerodynamicAngleCalculator Object from which the aerodynamic angles are computed.
Definition at line 526 of file aerodynamicAngleCalculator.cpp.
References tudat::ephemerides::RotationalEphemeris::getRotationToTargetFrame(), and setAerodynamicDependentOrientationCalculatorClosure().
computeApparentAcceleration()
Eigen::Vector3d tudat::reference_frames::computeApparentAcceleration (const Eigen::Vector3d & accelerationOfNonInertialReferenceFrame, const Eigen::Vector3d & angularVelocityOfNonInertialReferenceFrame, const Eigen::Vector3d & angularAccelerationOfNonInertialReferenceFrame, const Eigen::Vector3d & positionOfBodyInNonInertialReferenceFrame, const Eigen::Vector3d & velocityOfBodyInNonInertialReferenceFrame)
Computes apparent acceleration experienced by an object, of which the position and velocity are provided in a non-inertial (i.e. rotating and/or accelerating) reference frame. The apparent acceleration of a particle due to the non-inertiality of the reference frame in which its state is given, is given by following equation:
where is the acceleration of the non-inertial frame with respect to an inertial reference frame, is the respective rotation rate and and are the object's position and velocity vector in the non-inertial frame in which the apparent acceleration is computed.
Parameters
accelerationOfNonInertialReferenceFrame Acceleration vector of the non-inertial frame with respect to an inertial reference frame [m s^-2].
angularVelocityOfNonInertialReferenceFrame Angular velocity vector of the non-inertial frame with respect to an inertial reference frame [rad s^-1].
angularAccelerationOfNonInertialReferenceFrame Angular acceleration vector of the non-inertial frame with respect to an inertial reference frame [rad s^-1].
positionOfBodyInNonInertialReferenceFrame Position vector of body in the non-inertial frame of reference in which the apparent acceleration is computed [m].
velocityOfBodyInNonInertialReferenceFrame Velocity vector of body in the non-inertial frame of reference in which the apparent acceleration is computed [m s^-1].
Returns
Apparent acceleration as seen by an observer in the rotating and accelerating frame.
Definition at line 23 of file apparentAccelerationModel.cpp.
References computeCentripetalAcceleration(), computeCoriolisAcceleration(), and computeEulerAcceleration().
Referenced by tudat::reference_frames::ApparentAccelerationModel::getAcceleration().
computeCentripetalAcceleration()
Eigen::Vector3d tudat::reference_frames::computeCentripetalAcceleration (const Eigen::Vector3d & angularVelocityOfNonInertialReferenceFrame, const Eigen::Vector3d & positionOfBodyInNonInertialReferenceFrame)
Computes centripetal acceleration experienced by an object, of which the position is provided in a rotating reference frame. The centripetal acceleration of a particle due to the non-inertiality of the reference frame in which its state is given, is given by following equation:
where is the rotation rate of the non-inertial frame with respect to an inertial reference frame and is the object's position in the non-inertial frame in which the apparent acceleration is computed.
Parameters
angularVelocityOfNonInertialReferenceFrame Angular velocity vector of the non-inertial frame with respect to an inertial reference frame [rad s^-1].
positionOfBodyInNonInertialReferenceFrame Position vector of body in the non-inertial frame of reference in which the apparent acceleration is computed [m].
Returns
Centripetal acceleration as seen by an observer in the rotating frame.
Definition at line 40 of file apparentAccelerationModel.cpp.
Referenced by computeApparentAcceleration().
computeCoriolisAcceleration()
Eigen::Vector3d tudat::reference_frames::computeCoriolisAcceleration (const Eigen::Vector3d & angularVelocityOfNonInertialReferenceFrame, const Eigen::Vector3d & velocityOfBodyInNonInertialReferenceFrame)
Computes Coriolis acceleration experienced by an object, of which the position is provided in a rotating reference frame. The Coriolis acceleration of a particle due to the non-inertiality of the reference frame in which its state is given, is given by following equation:
where is the rotation rate of the non-inertial frame with respect to an inertial reference frame and is the object's velocity in the non-inertial frame in which the apparent acceleration is computed.
Parameters
angularVelocityOfNonInertialReferenceFrame Angular velocity vector of the non-inertial frame with respect to an inertial reference frame [rad s^-1].
velocityOfBodyInNonInertialReferenceFrame Velocity vector of body in the non-inertial frame of reference in which the apparent acceleration is computed [m s^-1].
Returns
Coriolis acceleration as seen by an observer in the rotating frame.
Definition at line 50 of file apparentAccelerationModel.cpp.
Referenced by computeApparentAcceleration().
computeEulerAcceleration()
Eigen::Vector3d tudat::reference_frames::computeEulerAcceleration (const Eigen::Vector3d & angularAccelerationOfNonInertialReferenceFrame, const Eigen::Vector3d & positionOfBodyInNonInertialReferenceFrame)
Computes Euler acceleration experienced by an object, of which the position is provided in a rotationally accelerating reference frame. The Euler acceleration of a particle due to the non-inertiality of the reference frame in which its state is given, is given by following equation:
where is the rate of change of the rotation rate of the non-inertial frame with respect to an inertial reference frame and is the object's position in the non-inertial frame in which the apparent acceleration is computed.
Parameters
angularAccelerationOfNonInertialReferenceFrame Angular acceleration vector of the non-inertial frame with respect to an inertial reference frame [rad s^-1].
positionOfBodyInNonInertialReferenceFrame Position vector of body in the non-inertial frame of reference in which the apparent acceleration is computed [m].
Returns
Euler acceleration as seen by an observer in the rotationally accelerating frame.
Definition at line 59 of file apparentAccelerationModel.cpp.
Referenced by computeApparentAcceleration().
get132EulerAnglesFromRotationMatrix()
Eigen::Vector3d tudat::reference_frames::get132EulerAnglesFromRotationMatrix (const Eigen::Matrix3d & rotationMatrix)
Get classical 1-3-2 Euler angles set from rotation matrix R. That is, the Euler angles x, y, z are returned such that R = R_{1}(x)R_{3}(y)R_{2}(z)
Parameters
rotationMatrix Rotation matrix for which the equivalent Euler angles are to be computed.
Returns
Euler angles x,y,z (about 1, 3 and 2 axes, respectively).
Definition at line 34 of file referenceFrameTransformations.cpp.
Referenced by tudat::reference_frames::AerodynamicAnglesClosure::updateAngles().
calculateInertialToPlanetFixedRotationAnglesFromMatrix()
Eigen::Vector3d tudat::reference_frames::calculateInertialToPlanetFixedRotationAnglesFromMatrix (const Eigen::Matrix3d & rotationMatrixFromInertialToPlanetFixedFrame)
Function to compute pole right ascension and declination, as well as prime meridian of date, from rotation matrix
Parameters
rotationMatrixFromInertialToPlanetFixedFrame Rotation matrix from which Euler angles are to be determined.
Returns
Pole right ascension and declination, and prime meridian of date, from rotation matrix
Definition at line 45 of file referenceFrameTransformations.cpp.
References tudat::basic_mathematics::computeModulo(), and tudat::mathematical_constants::PI.
Referenced by tudat::ephemerides::SimpleRotationalEphemeris::SimpleRotationalEphemeris().
transformVectorFromQuaternionFunction()
Eigen::Vector3d tudat::reference_frames::transformVectorFromQuaternionFunction (const Eigen::Vector3d & originalVector, const std::function< Eigen::Quaterniond() > rotation)
Wrapper function to transform a vector to a different frame from a single rotation function.
Parameters
originalVector Vector that is to be rotated to a new frame
rotation Function returning the current rotation to the new frame
Returns
Vector originalVector, transformed to new frame.
Definition at line 60 of file referenceFrameTransformations.cpp.
Referenced by getAerodynamicForceTransformationFunction().
transformVectorFunctionFromVectorFunctions()
Eigen::Vector3d tudat::reference_frames::transformVectorFunctionFromVectorFunctions (const std::function< Eigen::Vector3d() > originalVector, const std::function< Eigen::Vector3d(const Eigen::Vector3d &) > transformationFunction)
Wrapper function to transform a vector to a different frame from a single transformation function.
Parameters
originalVector Vector that is to be transformed to a new frame
transformationFunction Function transforming a vector to a new frame
Returns
Vector originalVector, transformed to new frame.
Definition at line 68 of file referenceFrameTransformations.cpp.
Referenced by tudat::simulation_setup::createAerodynamicAcceleratioModel(), and tudat::simulation_setup::createAerodynamicTorqueModel().
transformVectorFromVectorFunctions()
Eigen::Vector3d tudat::reference_frames::transformVectorFromVectorFunctions (const Eigen::Vector3d & originalVector, const std::vector< std::function< Eigen::Vector3d(const Eigen::Vector3d &) > > & rotationsList)
Wrapper function to transform a vector to a different frame from a list of transformation function.
Parameters
originalVector Vector that is to be transformed to a new frame
rotationsList List of transformation function, each of which transforms a vector to a new frame. The functions in this list are called in descending order.
Returns
Vector originalVector, transformed to new frame.
Definition at line 76 of file referenceFrameTransformations.cpp.
Referenced by getAerodynamicForceTransformationFunction().
getRotatingPlanetocentricToInertialFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getRotatingPlanetocentricToInertialFrameTransformationMatrix (const double angleFromXItoXR)
Returns tranformation matrix from rotating planetocentric reference frame (R) to inertial reference frame (I).
Parameters
angleFromXItoXR Angle between X-axis of the planetocentric reference frame and X-axis of the inertial reference frame in [rad]. This angle is same as the rotational rate of the central body [rad/s] times the time from epoch [s].
Returns
Reference frame (R) to inertial reference frame (I) transformation matrix.
Definition at line 93 of file referenceFrameTransformations.cpp.
References getInertialToPlanetocentricFrameTransformationMatrix().
getRotatingPlanetocentricToInertialFrameTransformationQuaternion() [1/2]
Eigen::Quaterniond tudat::reference_frames::getRotatingPlanetocentricToInertialFrameTransformationQuaternion (const double angleFromXItoXR)
Returns tranformation quaternion from rotating planetocentric reference frame (R) to inertial reference frame (I). It's an eigen library transformation and can be applied directly to a vector Vector_new = Quaternion * Vector_old.
Parameters
angleFromXItoXR Angle between X-axis of the planetocentric reference frame and X-axis of the inertial reference frame in [rad]. This angle is same as the rotational rate of the central body [rad/s] times the time from epoch [s].
Returns
Reference frame (R) to inertial reference frame (I) transformation quaternion.
Definition at line 108 of file referenceFrameTransformations.cpp.
getRotatingPlanetocentricToInertialFrameTransformationQuaternion() [2/2]
Eigen::Quaterniond tudat::reference_frames::getRotatingPlanetocentricToInertialFrameTransformationQuaternion (const double declinationOfPole, const double rightAscensionOfPole, const double longitudeOfPrimeMeridian)
Retuns rotation from planet-fixed to inertial frame, assuming that the equatorial plane is not equal to x-y plane of inertial frame. Orientation of body-fixed frame is obtained from right ascension and declination of body's pole and the location of the prime meridian (Seidelmann et al. 2005).
Parameters
declinationOfPole Declination of body's pole in inertial frame.
rightAscensionOfPole Right ascension of body's pole in inertial frame.
longitudeOfPrimeMeridian Longitude of body prime meridian.
Returns
Rotation quaternion computed.
Definition at line 122 of file referenceFrameTransformations.cpp.
References tudat::mathematical_constants::PI.
getInertialToPlanetocentricFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getInertialToPlanetocentricFrameTransformationMatrix (const double angleFromXItoXR)
Returns transformation matrix from inertial referenceframe (I) to the rotating planetocentric reference frame (R).
Parameters
angleFromXItoXR Angle between X-axis of the planetocentric reference frame and X-axis of the inertial reference frame in [rad]. This angle is same as the rotational rate of the central body [rad/s] times the time from epoch [s].
Returns
Inertial (I) to planetocentric reference frame (R) transformation matrix.
Definition at line 144 of file referenceFrameTransformations.cpp.
Referenced by getRotatingPlanetocentricToInertialFrameTransformationMatrix().
getVelocityBasedLvlhToInertialRotation()
Eigen::Matrix3d tudat::reference_frames::getVelocityBasedLvlhToInertialRotation (const Eigen::Vector6d & vehicleState, const Eigen::Vector6d & centralBodyState, const bool doesNaxisPointAwayFromCentralBody = true)
Get rotation from velocity based LVLH frame to inertial (I) frame.
Returns rotation from inertial (i) to the velocity based LVLH frame. The velocity based LVLH frame is a right-handed orthogonal frame defined as follows: x-axis tangent to the velocity direction, y-axis in the orbital plane and pointing inwards (if doesNaxisPointAwayFromCentralBody is false), i.e. to the left when looking in velocity-direction, z-axis normal to the orbital plane.
Parameters
vehicleState State of the vehicle for which the LVLH frame is to be computed.
centralBodyState State of the central body w.r.t. which the LVLH frame is to be computed.
doesNaxisPointAwayFromCentralBody Boolean denoting whether the local y-axis points away from (if true) or towards (if false) central body.
Returns
Velocity based LVLH to inertial (I) frame transformation matrix.
Definition at line 157 of file referenceFrameTransformations.cpp.
Referenced by getVelocityBasedLvlhToInertialRotationFromFunctions(), and tudat::propulsion::MeeCostateBasedThrustGuidance::updateForceDirection().
getVelocityBasedLvlhToInertialRotationFromFunctions()
Eigen::Matrix3d tudat::reference_frames::getVelocityBasedLvlhToInertialRotationFromFunctions (const std::function< Eigen::Vector6d() > & vehicleStateFunction, const std::function< Eigen::Vector6d() > & centralBodyStateFunction, bool doesNaxisPointAwayFromCentralBody = true)
Get rotation from velocity based LVLH frame to inertial (I) frame.
Returns rotation from inertial (i) to the velocity based LVLH frame. The velocity based LVLH frame is a right-handed orthogonal frame defined as follows: x-axis tangent to the velocity direction, y-axis in the orbital plane and pointing inwards (if doesNaxisPointAwayFromCentralBody is false), i.e. to the left when looking in velocity-direction, z-axis normal to the orbital plane.
Parameters
vehicleStateFunction Function returning the state of the vehicle for which the LVLH frame is to be computed
centralBodyStateFunction Function returning the state of the central body w.r.t. which the LVLH frame is to be computed
doesNaxisPointAwayFromCentralBody Boolean denoting whether the local y-axis points away from (if true) or towards (if false) central body.
Returns
Velocity based LVLH to inertial (I) frame transformation matrix.
Definition at line 187 of file referenceFrameTransformations.cpp.
References getVelocityBasedLvlhToInertialRotation().
Referenced by tudat::simulation_setup::createThrustAcceleratioModel(), and tudat::propagators::getVectorDependentVariableFunction().
getVelocityBasedLvlhToPlanetocentricRotationKeplerian()
Eigen::Quaterniond tudat::reference_frames::getVelocityBasedLvlhToPlanetocentricRotationKeplerian (const Eigen::Matrix< double, 6, 1 > spacecraftKeplerianState)
Get rotation from velocity based LVLH frame to planet-fixed frame.
Returns rotation from the velocity based LVLH frame to the planet-fixed frame. The velocity based LVLH frame is a right-handed orthogonal frame defined as follows: x-axis tangent to the velocity direction, y-axis in the orbital plane and pointing inwards, i.e. to the left when looking in velocity-direction, z-axis normal to the orbital plane.
Parameters
spacecraftKeplerianState containging the following elements: semi-major axis -> not used eccentricity inclination argumentOfPeriapsis longitudeOfAscendingNode trueAnomaly
Returns
Computed rotation quaternion.Get rotation from velocity based LVLH frame to planetocentric frame.
Definition at line 197 of file referenceFrameTransformations.cpp.
References tudat::input_output::field_types::state::argumentOfPeriapsis, tudat::input_output::field_types::state::eccentricity, tudat::input_output::field_types::state::inclination, tudat::mathematical_constants::PI, and tudat::input_output::field_types::state::trueAnomaly.
getInertialToRswSatelliteCenteredFrameRotationMatrix()
Eigen::Matrix3d tudat::reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix (const Eigen::Vector6d bodyState)
Function to compute the rotation matrix to RSW frame, from the frame in which the input state is given.
Parameters
bodyState State for which the RSW frame rotation is to be computed.
Returns
Rotation matrix to RSW frame
Definition at line 228 of file referenceFrameTransformations.cpp.
Referenced by tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::computeGaussPlanetaryEquationsForKeplerElements(), tudat::propagators::computeStateDerivativeForUnifiedStateModelExponentialMap(), tudat::propagators::computeStateDerivativeForUnifiedStateModelModifiedRodriguesParameters(), tudat::propagators::computeStateDerivativeForUnifiedStateModelQuaternions(), and tudat::basic_astrodynamics::EmpiricalAcceleration::updateMembers().
getInertialToPlanetocentricFrameTransformationQuaternion() [1/2]
Eigen::Quaterniond tudat::reference_frames::getInertialToPlanetocentricFrameTransformationQuaternion (const double angleFromXItoXR)
Get inertial (I) to rotating planetocentric (R) reference frame transformation quaternion.
Returns transformation quaternion from inertial referenceframe (I) to the rotating planetocentric reference frame (R). It's an eigen library transformation and can be applied directly to a vector Vector_new = Quaternion * Vector_old.
Parameters
angleFromXItoXR Angle between X-axis of the planetocentric reference frame and X-axis of the inertial reference frame in [rad]. This angle is same as the rotational rate of the central body [rad/s] times the time from epoch [s].
Returns
Inertial (I) to planetocentric reference frame (R) transformation quaternion.
Definition at line 254 of file referenceFrameTransformations.cpp.
Referenced by tudat::ephemerides::SimpleRotationalEphemeris::getDerivativeOfRotationToTargetFrame(), tudat::ephemerides::SimpleRotationalEphemeris::getRotationToTargetFrame(), and tudat::ephemerides::SimpleRotationalEphemeris::resetInitialPoleRightAscensionAndDeclination().
getInertialToPlanetocentricFrameTransformationQuaternion() [2/2]
Eigen::Quaterniond tudat::reference_frames::getInertialToPlanetocentricFrameTransformationQuaternion (const double declinationOfPole, const double rightAscensionOfPole, const double longitudeOfPrimeMeridian)
Returns rotation from inertial to planet-fixed frame, assuming that the equatorial plane is not equal to x-y plane of inertial frame. Orientation of body-fixed frame is obtained from right ascension and declination of body's pole and the location of the prime meridian (Seidelmann et al. 2005).
Parameters
declinationOfPole Declination of body's pole in inertial frame.
rightAscensionOfPole Right ascension of body's pole in inertial frame.
longitudeOfPrimeMeridian Longitude of body prime meridian.
Returns
Rotation quaternion computed.
Definition at line 269 of file referenceFrameTransformations.cpp.
References tudat::mathematical_constants::PI.
getQuaternionObjectFromQuaternionValues()
Eigen::Quaterniond tudat::reference_frames::getQuaternionObjectFromQuaternionValues (const Eigen::Vector4d & vectorWithQuaternion)
Create a Quaterniond rotation state object from four quaternion values in vector 4d.
Creates a Quaterniond rotation state object from four quaternion values. This function is not related to any specific rotation matrix, but can be used for general purposes. It's an eigen library transformation and can be applied directly to a vector Vector_new = Quaternion * Vector_old. Note that is also possible to create a quaternion object directly from a Vector4d, but Eigen will rearrange the order of the coefficients ([q2 q3 q4 q1]). This function retreives the individual entries of the Vector4d an uses them as four doubles as input arguments for the constructor of the Quateriond. From the Eigen code documentation:
Warning
Note the order of the arguments: the real w coefficient first, while internally the coefficients are stored in the following order: [x, y, z, w]
Parameters
vectorWithQuaternion A vector containing the quaternions of the rotation state
Returns
Transformation quaternion.
Definition at line 291 of file referenceFrameTransformations.cpp.
getRotatingPlanetocentricToLocalVerticalFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getRotatingPlanetocentricToLocalVerticalFrameTransformationMatrix (const double longitude, const double latitude)
Returns the frame transformation matrix from the Planetocentric (R) to the Local vertical (V) reference frame. The Z-axis is aligned with the local gravity vector. Whether or not, this is in the direction of the center of the central body, depends which kind of latitude is provided (geocentric, geodetic, gravitation latitude). The X-axis is directed to the north.
Parameters
longitude The longitude in the planetocentric reference frame in [rad].
latitude The latitude in the planetocentric reference frame in [rad].
Returns
Transformation matrix from Planetocentric (R) to the local vertical (V) frame.
Definition at line 304 of file referenceFrameTransformations.cpp.
References getRotatingPlanetocentricToLocalVerticalFrameTransformationQuaternion().
Referenced by getLocalVerticalToRotatingPlanetocentricFrameTransformationMatrix().
getRotatingPlanetocentricToLocalVerticalFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getRotatingPlanetocentricToLocalVerticalFrameTransformationQuaternion (const double longitude, const double latitude)
Get transformation quaternion from Planetocentric (R) to the local vertical (V) frame.
Returns the frame transformation quaternion from the Planetocentric (R) to the Local vertical (V) reference frame. The Z-axis is aligned with the local gravity vector. Whether or not, this is in the direction of the center of the central body, depends which kind of latitude is provided (geocentric, geodetic, gravitation latitude). The X-axis is directed to the north.
Parameters
longitude The longitude in the planetocentric reference frame in [rad].
latitude The latitude in the planetocentric reference frame in [rad].
Returns
Transformation quaternion from Planetocentric (R) to the local vertical (V) frame.
Definition at line 312 of file referenceFrameTransformations.cpp.
References tudat::mathematical_constants::PI.
Referenced by tudat::orbital_element_conversions::convertCartesianToSphericalOrbitalState(), getLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion(), getRotatingPlanetocentricToLocalVerticalFrameTransformationMatrix(), tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames(), and tudat::reference_frames::AerodynamicAngleCalculator::update().
getLocalVerticalToRotatingPlanetocentricFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getLocalVerticalToRotatingPlanetocentricFrameTransformationMatrix (const double longitude, const double latitude)
Returns the frame transformation matrix from the local vertical (V) to the Planetocentric frame (R) reference frame. The Z-axis is aligned with the local gravity vector. Whether or not, this is in the direction of the center of the central body, depends which kind of latitude is provided (geocentric, geodetic, gravitation latitude). The X-axis is directed to the north.
Parameters
longitude The longitude in the planetocentric reference frame in [rad].
latitude The latitude in the planetocentric reference frame in [rad].
Returns
Transformation matrix from local vertical (V) to the Planetocentric (R) frame.
Definition at line 330 of file referenceFrameTransformations.cpp.
References getRotatingPlanetocentricToLocalVerticalFrameTransformationMatrix().
getLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion (const double longitude, const double latitude)
Returns the frame transformation quaternion from the local vertical (V) to the Planetocentric (R) reference frame. The Z-axis is aligned with the local gravity vector. Whether or not, this is in the direction of the center of the central body, depends which kind of latitude is provided (geocentric, geodetic, gravitation latitude). The X-axis is directed to the north.
Parameters
longitude The longitude in the planetocentric reference frame in [rad].
latitude The latitude in the planetocentric reference frame in [rad].
Returns
Transformation quaternion from local vertical (V) to the Planetocentric (R) frame.
Definition at line 338 of file referenceFrameTransformations.cpp.
References getRotatingPlanetocentricToLocalVerticalFrameTransformationQuaternion().
Referenced by tudat::orbital_element_conversions::convertSphericalOrbitalToCartesianState(), and tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames().
getTrajectoryToLocalVerticalFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getTrajectoryToLocalVerticalFrameTransformationMatrix (const double flightPathAngle, const double headingAngle)
Returns the frame transformation matrix from the trajectory frame (T) to the local vertical (V) reference frame. Depending on whether the flight-path angle and heading angle express the velocity relative to the rotating planetocentric frame or relative to the local atmosphere, the resulting rotation holds for the groundspeed-based trajectory (TG) or airspeed-based trajectory (TA) frame respectively.
Parameters
flightPathAngle The trajectory's flight-path angle, positive upwards, in [rad].
headingAngle The trajectory's heading angle with respect to the North in [rad].
Returns
Transformation matrix from trajectory frame (T) to the local vertical frame (V).
Definition at line 346 of file referenceFrameTransformations.cpp.
References getTrajectoryToLocalVerticalFrameTransformationQuaternion().
Referenced by getLocalVerticalFrameToTrajectoryTransformationMatrix().
getTrajectoryToLocalVerticalFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getTrajectoryToLocalVerticalFrameTransformationQuaternion (const double flightPathAngle, const double headingAngle)
Returns the frame transformation quaternion from the trajectory (T) to the local vertical (V) reference frame. Depending on whether the flight-path angle and heading angle express the velocity relative to the rotating planetocentric frame or relative to the local atmosphere, the resulting rotation holds for the groundspeed-based trajectory (TG) or airspeed-based trajectory (TA) frame respectively.
Parameters
flightPathAngle The trajectory's flight-path angle, positive upwards, in [rad].
headingAngle The trajectory's heading angle with respect to the North in [rad].
Returns
Transformation quaternion from trajectory frame (T) to the local vertical frame (V).
Definition at line 354 of file referenceFrameTransformations.cpp.
Referenced by getLocalVerticalFrameToTrajectoryTransformationQuaternion(), tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames(), and getTrajectoryToLocalVerticalFrameTransformationMatrix().
getLocalVerticalFrameToTrajectoryTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getLocalVerticalFrameToTrajectoryTransformationMatrix (const double flightPathAngle, const double headingAngle)
Returns the frame transformation matrix from the local vertical (V) to the trajectory (T) reference frame. Depending on whether the flight-path angle and heading angle express the velocity relative to the rotating planetocentric frame or relative to the local atmosphere, the resulting rotation holds for the groundspeed-based trajectory (TG) or airspeed-based trajectory (TA) frame respectively.
Parameters
flightPathAngle The trajectory's flight-path angle, positive upwards, in [rad].
headingAngle The trajectory's heading angle with respect to the North in [rad].
Returns
Transformation matrix from the local vertical (V) to the trajectory (T) frame.
Definition at line 368 of file referenceFrameTransformations.cpp.
References getTrajectoryToLocalVerticalFrameTransformationMatrix().
getLocalVerticalFrameToTrajectoryTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getLocalVerticalFrameToTrajectoryTransformationQuaternion (const double flightPathAngle, const double headingAngle)
Returns the transformation quaternion from the local vertical (V) to the trajectory (T) reference frame. Depending on whether the flight-path angle and heading angle express the velocity relative to the rotating planetocentric frame or relative to the local atmosphere, the resulting rotation holds for the groundspeed-based trajectory (TG) or airspeed-based trajectory (TA) frame respectively.
Parameters
flightPathAngle The trajectory's flight-path angle, positive upwards, in [rad].
headingAngle The trajectory's heading angle with respect to the North in [rad].
Returns
Transformation quaternion from the local vertical (V) to the trajectory (T) frame.
Definition at line 376 of file referenceFrameTransformations.cpp.
References getTrajectoryToLocalVerticalFrameTransformationQuaternion().
Referenced by tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames().
getTrajectoryToAerodynamicFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getTrajectoryToAerodynamicFrameTransformationMatrix (const double bankAngle)
Returns the transformation matrix from the airspeed-based trajectory (TA) to the airspeed-based aerodynamic frame (AA). These frames differ from each other only by the bank-angle, representing one Euler-rotation.
Parameters
bankAngle The object's bank angle in [rad].
Returns
Transformation matrix from the TA- to the AA-frame.
Definition at line 384 of file referenceFrameTransformations.cpp.
References getTrajectoryToAerodynamicFrameTransformationQuaternion().
Referenced by getAerodynamicToTrajectoryFrameTransformationMatrix().
getTrajectoryToAerodynamicFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getTrajectoryToAerodynamicFrameTransformationQuaternion (const double bankAngle)
Returns the transformation quaternion from the airspeed-based trajectory (TA) to the airspeed- based aerodynamic frame (AA). These frames differ from each other only by the bank-angle, representing one Euler-rotation.
Parameters
bankAngle The object's bank angle in [rad].
Returns
Transformation quaternion from the TA- to the AA-frame.
Definition at line 392 of file referenceFrameTransformations.cpp.
Referenced by getAerodynamicToTrajectoryFrameTransformationQuaternion(), tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames(), and getTrajectoryToAerodynamicFrameTransformationMatrix().
getAerodynamicToTrajectoryFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getAerodynamicToTrajectoryFrameTransformationMatrix (const double bankAngle)
Returns the transformation matrix from the airspeed-based aerodynamic (AA) to the airspeed-based trajectory frame (TA). These frames differ from each other only by the bank-angle, representing one Euler-rotation.
Parameters
bankAngle The object's bank angle in [rad].
Returns
Transformation matrix from the AA- to the TA-frame.
Definition at line 403 of file referenceFrameTransformations.cpp.
References getTrajectoryToAerodynamicFrameTransformationMatrix().
getAerodynamicToTrajectoryFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getAerodynamicToTrajectoryFrameTransformationQuaternion (const double bankAngle)
Returns the transformation quaternion from the airspeed-based aerodynamic (AA) to the airspeed- based trajectory frame (TA). These frames differ from each other only by the bank-angle, representing one Euler-rotation.
Parameters
bankAngle The object's bank angle in [rad].
Returns
Transformation quaternion from the AA- to the TA-frame.
Definition at line 410 of file referenceFrameTransformations.cpp.
References getTrajectoryToAerodynamicFrameTransformationQuaternion().
Referenced by tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames().
getBodyToAirspeedBasedAerodynamicFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getBodyToAirspeedBasedAerodynamicFrameTransformationMatrix (const double angleOfAttack, const double angleOfSideslip)
Returns the transformation matrix from the body-fixed (B) to the airspeed-based aerodynamic frame (AA).
Parameters
angleOfAttack The angle of attack in [rad].
angleOfSideslip The angle of sideslip in [rad].
Returns
Transformation matrix from the B- to the AA-frame.
Definition at line 417 of file referenceFrameTransformations.cpp.
References getBodyToAirspeedBasedAerodynamicFrameTransformationQuaternion().
Referenced by getAirspeedBasedAerodynamicToBodyFrameTransformationMatrix().
getBodyToAirspeedBasedAerodynamicFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getBodyToAirspeedBasedAerodynamicFrameTransformationQuaternion (const double angleOfAttack, const double angleOfSideslip)
Returns the transformation quaternion from the body-fixed (B) to the airspeed-based aerodynamic frame (AA).
Parameters
angleOfAttack The angle of attack in [rad].
angleOfSideslip The angle of sideslip in [rad].
Returns
Transformation quaternion from the B- to the AA-frame.
Definition at line 425 of file referenceFrameTransformations.cpp.
Referenced by getAirspeedBasedAerodynamicToBodyFrameTransformationQuaternion(), getBodyToAirspeedBasedAerodynamicFrameTransformationMatrix(), and tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames().
getAirspeedBasedAerodynamicToBodyFrameTransformationMatrix()
Eigen::Matrix3d tudat::reference_frames::getAirspeedBasedAerodynamicToBodyFrameTransformationMatrix (const double angleOfAttack, const double angleOfSideslip)
Returns the transformation matrix from the airspeed-based aerodynamic (AA) to the body-fixed frame (B).
Parameters
angleOfAttack The angle of attack in [rad].
angleOfSideslip The angle of sideslip in [rad].
Returns
Transformation matrix from the AA- to the B-frame.
Definition at line 439 of file referenceFrameTransformations.cpp.
References getBodyToAirspeedBasedAerodynamicFrameTransformationMatrix().
getAirspeedBasedAerodynamicToBodyFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getAirspeedBasedAerodynamicToBodyFrameTransformationQuaternion (const double angleOfAttack, const double angleOfSideslip)
Returns the transformation quaternion from the airspeed-based aerodynamic (AA) to the body-fixed frame (B).
Parameters
angleOfAttack The angle of attack in [rad].
angleOfSideslip The angle of sideslip in [rad].
Returns
Transformation quaternion from the AA- to the B-frame.
Definition at line 447 of file referenceFrameTransformations.cpp.
References getBodyToAirspeedBasedAerodynamicFrameTransformationQuaternion().
Referenced by tudat::reference_frames::AerodynamicAngleCalculator::getRotationQuaternionBetweenFrames().
calculateHeadingAngle()
double tudat::reference_frames::calculateHeadingAngle (const Eigen::Vector3d & velocityInVerticalFrame)
Calculate heading angle from velocity in vertical (LVLH) frame.
Parameters
velocityInVerticalFrame Current Cartesian velocity in vertical frame.
Returns
Current heading angle.
Definition at line 455 of file referenceFrameTransformations.cpp.
Referenced by tudat::reference_frames::AerodynamicAngleCalculator::update().
calculateFlightPathAngle()
double tudat::reference_frames::calculateFlightPathAngle (const Eigen::Vector3d & velocityInVerticalFrame)
Calculate current flight path angle. Angle is defined positive upwards.
Calculate flight path angle from velocity in vertical (LVLH) frame. Angle is defined positive upwards.
Parameters
velocityInVerticalFrame Current Cartesian velocity in vertical frame.
Returns
Current flight path angle.
Definition at line 461 of file referenceFrameTransformations.cpp.
Referenced by tudat::reference_frames::AerodynamicAngleCalculator::update().
getRotatingPlanetocentricToEnuLocalVerticalFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getRotatingPlanetocentricToEnuLocalVerticalFrameTransformationQuaternion (const double longitude, const double latitude)
Get ECEF to V-frame quaternion.
Get the transformation from the co-rotating planetocentric frame to local vertical.
Parameters
longitude Longitude of position.
latitude Latitude of position.
Returns
Transformation quaternion.
Definition at line 467 of file referenceFrameTransformations.cpp.
References getEnuLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion().
getEnuLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion()
Eigen::Quaterniond tudat::reference_frames::getEnuLocalVerticalToRotatingPlanetocentricFrameTransformationQuaternion (const double longitude, const double latitude)
Get V-frame to ECEF quaternion.
Get the transformation from the local vertical to the co-rotating planetocentric frame.
See also
http://www.navipedia.net/index.php/Transformations_between_ECEF_and_ENU_coordinates
Parameters
longitude Longitude of position.
latitude Latitude of position.
Returns
Transformation quaternion.
Definition at line 475 of file referenceFrameTransformations.cpp.
References tudat::mathematical_constants::PI.
Referenced by tudat::ground_stations::getGeocentricLocalUnitVectors(), and getRotatingPlanetocentricToEnuLocalVerticalFrameTransformationQuaternion().
getDerivativeOfXAxisRotationWrtAngle() [1/2]
Eigen::Matrix3d tudat::reference_frames::getDerivativeOfXAxisRotationWrtAngle (const double angle)
Function to compute the derivative of a rotation about the x-axis w.r.t. the rotation angle
Parameters
angle Angle about which rotation is taken.
Returns
Derivative of a rotation about the x-axis w.r.t. the rotation angle
Definition at line 494 of file referenceFrameTransformations.cpp.
Referenced by tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameWrtPoleOrientation().
getDerivativeOfXAxisRotationWrtAngle() [2/2]
Eigen::Matrix3d tudat::reference_frames::getDerivativeOfXAxisRotationWrtAngle (const Eigen::Matrix3d & rotationMatrix)
Function to compute the derivative of a rotation about the x-axis w.r.t. the rotation angle
Parameters
rotationMatrix Rotation matrix for which partial is to be computed
Returns
Derivative of a rotation about the x-axis w.r.t. the rotation angle
Definition at line 503 of file referenceFrameTransformations.cpp.
References X_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER.
getDerivativeOfYAxisRotationWrtAngle() [1/2]
Eigen::Matrix3d tudat::reference_frames::getDerivativeOfYAxisRotationWrtAngle (const double angle)
Function to compute the derivative of a rotation about the y-axis w.r.t. the rotation angle
Parameters
angle Angle about which rotation is taken.
Returns
Derivative of a rotation about the x-axis w.r.t. the rotation angle
Definition at line 509 of file referenceFrameTransformations.cpp.
getDerivativeOfYAxisRotationWrtAngle() [2/2]
Eigen::Matrix3d tudat::reference_frames::getDerivativeOfYAxisRotationWrtAngle (const Eigen::Matrix3d & rotationMatrix)
Function to compute the derivative of a rotation about the y-axis w.r.t. the rotation angle
Parameters
rotationMatrix Rotation matrix for which partial is to be computed
Returns
Derivative of a rotation about the x-axis w.r.t. the rotation angle
Definition at line 518 of file referenceFrameTransformations.cpp.
References Y_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER.
getDerivativeOfZAxisRotationWrtAngle() [1/2]
Eigen::Matrix3d tudat::reference_frames::getDerivativeOfZAxisRotationWrtAngle (const double angle)
Function to compute the derivative of a rotation about the z-axis w.r.t. the rotation angle
Parameters
angle Angle about which rotation is taken.
Returns
Derivative of a rotation about the x-axis w.r.t. the rotation angle
Definition at line 524 of file referenceFrameTransformations.cpp.
Referenced by tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameWrtPoleOrientation().
getDerivativeOfZAxisRotationWrtAngle() [2/2]
Eigen::Matrix3d tudat::reference_frames::getDerivativeOfZAxisRotationWrtAngle (const Eigen::Matrix3d & rotationMatrix)
Function to compute the derivative of a rotation about the z-axis w.r.t. the rotation angle
Parameters
rotationMatrix Rotation matrix for which partial is to be computed
Returns
Derivative of a rotation about the x-axis w.r.t. the rotation angle
Definition at line 533 of file referenceFrameTransformations.cpp.
References Z_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER.
getBodyFixedCartesianPosition()
Eigen::Vector3d tudat::reference_frames::getBodyFixedCartesianPosition (const std::function< Eigen::Vector3d() > positionFunctionOfCentralBody, const std::function< Eigen::Vector3d() > positionFunctionOfRelativeBody, const std::function< Eigen::Quaterniond() > orientationFunctionOfCentralBody)
Function to compute a body-fixed relative cartesian position
Parameters
positionFunctionOfCentralBody Position function of central body
positionFunctionOfRelativeBody Position function of point of which body-fixed state is to be computed
orientationFunctionOfCentralBody Function returning rotation from inertial to body-fixed frame.
Returns
Body-fixed relative cartesian position
Definition at line 539 of file referenceFrameTransformations.cpp.
Referenced by getBodyFixedSphericalPosition(), and tudat::propagators::getVectorDependentVariableFunction().
getBodyFixedSphericalPosition()
Eigen::Vector3d tudat::reference_frames::getBodyFixedSphericalPosition (const std::function< Eigen::Vector3d() > positionFunctionOfCentralBody, const std::function< Eigen::Vector3d() > positionFunctionOfRelativeBody, const std::function< Eigen::Quaterniond() > orientationFunctionOfCentralBody)
Function to compute a body-fixed relative sphericall position
Parameters
positionFunctionOfCentralBody Position function of central body
positionFunctionOfRelativeBody Position function of point of which body-fixed state is to be computed
orientationFunctionOfCentralBody Function returning rotation from inertial to body-fixed frame.
Returns
Body-fixed relative sphericall position
Definition at line 549 of file referenceFrameTransformations.cpp.
References tudat::coordinate_conversions::convertCartesianToSpherical(), getBodyFixedCartesianPosition(), and tudat::mathematical_constants::PI.
Referenced by tudat::propagators::getVectorDependentVariableFunction().
to_json() [1/2]
void tudat::reference_frames::to_json (nlohmann::json & jsonObject, const AerodynamicsReferenceFrames & aerodynamicsReferenceFrame) inline
Definition at line 41 of file referenceFrames.h.
References aerodynamicsReferenceFrames, and tudat::json_interface::stringFromEnum().
from_json() [1/2]
void tudat::reference_frames::from_json (const nlohmann::json & jsonObject, AerodynamicsReferenceFrames & aerodynamicsReferenceFrame) inline
Definition at line 47 of file referenceFrames.h.
References aerodynamicsReferenceFrames, and tudat::json_interface::enumFromString().
to_json() [2/2]
void tudat::reference_frames::to_json (nlohmann::json & jsonObject, const AerodynamicsReferenceFrameAngles & aerodynamicsReferenceFrameAngle) inline
Definition at line 72 of file referenceFrames.h.
References aerodynamicsReferenceFrameAngles, and tudat::json_interface::stringFromEnum().
from_json() [2/2]
void tudat::reference_frames::from_json (const nlohmann::json & jsonObject, AerodynamicsReferenceFrameAngles & aerodynamicsReferenceFrameAngle) inline
Definition at line 78 of file referenceFrames.h.
References aerodynamicsReferenceFrameAngles, and tudat::json_interface::enumFromString().
Variable Documentation
getAerodynamicForceTransformationFunction
std::function< Eigen::Vector3d(const Eigen::Vector3d&) > tudat::reference_frames::getAerodynamicForceTransformationFunction(const std::shared_ptr< AerodynamicAngleCalculator > aerodynamicAngleCalculator, const AerodynamicsReferenceFrames accelerationFrame, const std::function< Eigen::Quaterniond() > bodyFixedToInertialFrameFunction=[](){ return Eigen::Quaterniond(Eigen::Matrix3d::Identity());}, const AerodynamicsReferenceFrames propagationFrame=inertial_frame)
Get a function to transform aerodynamic force from local to propagation frame. The returned function takes the force in the accelerationFrame, and returns this force in the propagationFrame.
Parameters
aerodynamicAngleCalculator Object to calculate aerodynamic angles and rotation quaternions.
accelerationFrame Id of frame in which aerodynamic force is calculated
bodyFixedToInertialFrameFunction Function to get the central-body corotating frame to inertial frame quaternion.
propagationFrame Id of frame in which orbit propagation is done.
Returns
Aerodynamic force conversion function.
Definition at line 360 of file aerodynamicAngleCalculator.h.
Referenced by tudat::simulation_setup::createAerodynamicAcceleratioModel(), and tudat::simulation_setup::createAerodynamicTorqueModel().
X_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER
const Eigen::Matrix3d tudat::reference_frames::X_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER static
Initial value:
=
        ( Eigen::Matrix3d( ) <<
          0.0, 0.0, 0.0,
          0.0, 0.0, 1.0,
          0.0, -1.0, 0.0 ).finished( )
Definition at line 495 of file referenceFrameTransformations.h.
Referenced by getDerivativeOfXAxisRotationWrtAngle().
Y_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER
const Eigen::Matrix3d tudat::reference_frames::Y_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER static
Initial value:
=
        ( Eigen::Matrix3d( ) <<
          0.0, 0.0, -1.0,
          0.0, 0.0, 0.0,
          1.0, 0.0, 0.0 ).finished( )
Definition at line 502 of file referenceFrameTransformations.h.
Referenced by getDerivativeOfYAxisRotationWrtAngle().
Z_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER
const Eigen::Matrix3d tudat::reference_frames::Z_AXIS_ROTATION_MATRIX_DERIVATIVE_PREMULTIPLIER static
Initial value:
=
        ( Eigen::Matrix3d( ) <<
          0.0, 1.0, 0.0,
          -1.0, 0.0, 0.0,
          0.0, 0.0, 0.0 ).finished( )
Definition at line 509 of file referenceFrameTransformations.h.
Referenced by tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtConstantRotationRate(), tudat::observation_partials::calculatePartialOfRotationMatrixFromLocalFrameDerivativeWrtPoleOrientation(), tudat::earth_orientation::calculateRotationRateFromItrsToGcrs(), tudat::ephemerides::SimpleRotationalEphemeris::getDerivativeOfRotationToTargetFrame(), and getDerivativeOfZAxisRotationWrtAngle().
aerodynamicsReferenceFrames
std::map< AerodynamicsReferenceFrames, std::string > tudat::reference_frames::aerodynamicsReferenceFrames static
Initial value:
=
{
    { inertial_frame, "intertial" },
    { corotating_frame, "corotating" },
    { vertical_frame, "vertical" },
    { trajectory_frame, "trajectory" },
    { aerodynamic_frame, "aerodynamic" },
    { body_frame, "body" }
}
Definition at line 27 of file referenceFrames.h.
Referenced by from_json(), and to_json().
unsupportedAerodynamicsReferenceFrames
std::vector< AerodynamicsReferenceFrames > tudat::reference_frames::unsupportedAerodynamicsReferenceFrames = { } static
Definition at line 38 of file referenceFrames.h.
aerodynamicsReferenceFrameAngles
std::map< AerodynamicsReferenceFrameAngles, std::string > tudat::reference_frames::aerodynamicsReferenceFrameAngles static
Initial value:
=
{
    { latitude_angle, "latitude" },
    { longitude_angle, "longitude" },
    { heading_angle, "heading" },
    { flight_path_angle, "flightPath" },
    { angle_of_attack, "angleOfAttach" },
    { angle_of_sideslip, "sideslip" },
    { bank_angle, "bank" }
}
Definition at line 57 of file referenceFrames.h.
Referenced by from_json(), and to_json().
unsupportedAerodynamicsReferenceFrameAngles
std::vector< AerodynamicsReferenceFrameAngles > tudat::reference_frames::unsupportedAerodynamicsReferenceFrameAngles = { } static
Definition at line 69 of file referenceFrames.h.