Tudat: tudat::propagators::StateDerivativeCircularRestrictedThreeBodyProblem Class Reference
tudat::propagators::StateDerivativeCircularRestrictedThreeBodyProblem Class Reference
State derivative model class for CRTBP.
#include <stateDerivativeCircularRestrictedThreeBodyProblem.h>
Public Member Functions
StateDerivativeCircularRestrictedThreeBodyProblem (const double aMassParameter)
Default constructor.
Eigen::Vector6d computeStateDerivative (const double time, const Eigen::Vector6d &cartesianState)
Compute state derivative.
Private Attributes
double massParameter
Mass parameter.
Detailed Description
Class that contains the state derivative model for the CRTBP.
Definition at line 32 of file stateDerivativeCircularRestrictedThreeBodyProblem.h.
Constructor & Destructor Documentation
tudat::propagators::StateDerivativeCircularRestrictedThreeBodyProblem::StateDerivativeCircularRestrictedThreeBodyProblem (const double aMassParameter) inline
Default constructor that defines the state derivative for a given CRTBP system.
Parameters
aMassParameter A value for mass parameter of CRTBP.
Definition at line 41 of file stateDerivativeCircularRestrictedThreeBodyProblem.h.
References computeStateDerivative().
Member Function Documentation
Eigen::Vector6d tudat::propagators::StateDerivativeCircularRestrictedThreeBodyProblem::computeStateDerivative (const double time, const Eigen::Vector6d & cartesianState)
Computes the state derivative of CRTBP.
Parameters
time Time.
cartesianState Cartesian state.
Returns
State derivative.
Definition at line 28 of file stateDerivativeCircularRestrictedThreeBodyProblem.cpp.
References massParameter, TUDAT_UNUSED_PARAMETER, tudat::orbital_element_conversions::xCartesianPositionIndex, tudat::orbital_element_conversions::xCartesianVelocityIndex, tudat::orbital_element_conversions::yCartesianPositionIndex, tudat::orbital_element_conversions::yCartesianVelocityIndex, and tudat::orbital_element_conversions::zCartesianPositionIndex.
Referenced by tudat::propagators::createCR3BPIntegrator(), and StateDerivativeCircularRestrictedThreeBodyProblem().
Member Data Documentation
double tudat::propagators::StateDerivativeCircularRestrictedThreeBodyProblem::massParameter private
Value of mass parameter for the CRTBP.
Definition at line 63 of file stateDerivativeCircularRestrictedThreeBodyProblem.h.
Referenced by computeStateDerivative().
The documentation for this class was generated from the following files:
Astrodynamics/Propagators/stateDerivativeCircularRestrictedThreeBodyProblem.h
Astrodynamics/Propagators/stateDerivativeCircularRestrictedThreeBodyProblem.cpp