Tudat: tudat::ephemerides::Ephemeris Class Reference
tudat::ephemerides::Ephemeris Class Reference abstract
Ephemeris base class.
#include <ephemeris.h>
Public Member Functions
Ephemeris (const std::string &referenceFrameOrigin="", const std::string &referenceFrameOrientation="")
Constructor.
virtual ~Ephemeris ()
Default destructor.
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get state from ephemeris (with long double as state scalar).
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with long double as state scalar and Time as time type).
virtual Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)=0
Get state from ephemeris.
virtual Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with double as state scalar and Time as time type).
std::string getReferenceFrameOrientation ()
Get reference frame orientation.
std::string getReferenceFrameOrigin ()
Get reference frame origin.
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (double specialization).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (long double specialization).
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (double specialization with Time input).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (long double specialization with Time input).
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > getTemplatedStateFromEphemeris (const TimeType &time)
Get state from ephemeris, with state scalar as template type.
Protected Attributes
std::string referenceFrameOrientation_
Reference frame orientation.
std::string referenceFrameOrigin_
Reference frame origin.
Detailed Description
Ephemeris base class.
Definition at line 34 of file ephemeris.h.
Constructor & Destructor Documentation
tudat::ephemerides::Ephemeris::Ephemeris (const std::string & referenceFrameOrigin = "", const std::string & referenceFrameOrientation = "") inline
Constructor, sets reference frame associated with ephemeris (default empty).
Parameters
referenceFrameOrigin Origin of reference frame (string identifier).
referenceFrameOrientation Orientation of reference frame (string identifier).
Definition at line 44 of file ephemeris.h.
virtual tudat::ephemerides::Ephemeris::~Ephemeris () inline virtual
Default destructor.
Definition at line 54 of file ephemeris.h.
References getCartesianState().
Member Function Documentation
virtual Eigen::Vector6d tudat::ephemerides::Ephemeris::getCartesianState (const double secondsSinceEpoch) pure virtual
Returns state from ephemeris at given Julian date.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
State from ephemeris.
Implemented in tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar, tudat::ephemerides::KeplerEphemeris, tudat::ephemerides::ApproximatePlanetPositions, tudat::ephemerides::MultiArcEphemeris, tudat::ephemerides::SpiceEphemeris, tudat::ephemerides::ConstantEphemeris, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::CustomEphemeris, and tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >.
Referenced by getCartesianLongState(), getCartesianStateFromExtendedTime(), getTemplatedStateFromEphemeris(), and ~Ephemeris().
virtual Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::Ephemeris::getCartesianLongState (const double secondsSinceEpoch) inline virtual
Returns state from ephemeris with long double as state scalar at given time. By default, this function casts the double getCartesianState to long double. It may be overridden by derived classes to make use of full long double computations.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
State from ephemeris with long double as state scalar
Reimplemented in tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::MultiArcEphemeris, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, and tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >.
Definition at line 73 of file ephemeris.h.
References getCartesianState().
Referenced by getCartesianLongStateFromExtendedTime(), and getTemplatedStateFromEphemeris().
virtual Eigen::Vector6d tudat::ephemerides::Ephemeris::getCartesianStateFromExtendedTime (const Time & currentTime) inline virtual
Returns state from ephemeris with double as state scalar at given time (as custom Time type). By default, this function casts the double getCartesianState to double. It may be overridden by derived classes.
Parameters
currentTime Time at which state is to be evaluated
Returns
State from ephemeris with double as state scalar
Reimplemented in tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::MultiArcEphemeris, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, and tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >.
Definition at line 88 of file ephemeris.h.
References getCartesianState(), and tudat::Time::getSeconds().
Referenced by getTemplatedStateFromEphemeris().
virtual Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::Ephemeris::getCartesianLongStateFromExtendedTime (const Time & currentTime) inline virtual
Returns state from ephemeris with long double as state scalar at given time (as custom Time type). By default, this function casts the double getCartesianState to long double. It may be overridden by derived classes to make use of full long double computations.
Parameters
currentTime Time at which state is to be evaluated
Returns
State from ephemeris with long double as state scalar
Reimplemented in tudat::ephemerides::CompositeEphemeris< TimeType, StateScalarType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, tudat::ephemerides::MultiArcEphemeris, tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >, and tudat::ephemerides::TabulatedCartesianEphemeris< StateScalarType, TimeType >.
Definition at line 102 of file ephemeris.h.
References getCartesianLongState(), tudat::Time::getSeconds(), and getTemplatedStateFromEphemeris().
Referenced by getTemplatedStateFromEphemeris().
template<typename StateScalarType , typename TimeType > Eigen::Matrix< StateScalarType, 6, 1 > tudat::ephemerides::Ephemeris::getTemplatedStateFromEphemeris (const TimeType & time)
Returns state from ephemeris (state scalar as template type) at given time.
Parameters
time Time at which ephemeris is to be evaluated
Returns
State from ephemeris with requested state scalar type.
Referenced by getCartesianLongStateFromExtendedTime(), and tudat::ephemerides::ReferenceFrameManager::getEphemeris().
std::string tudat::ephemerides::Ephemeris::getReferenceFrameOrigin () inline
Returns reference frame origin as a string.
Returns
Reference frame origin.
Definition at line 122 of file ephemeris.h.
References referenceFrameOrigin_.
std::string tudat::ephemerides::Ephemeris::getReferenceFrameOrientation () inline
Returns the reference frame orientation as a string.
Returns
Reference frame orientation
Definition at line 129 of file ephemeris.h.
References referenceFrameOrientation_.
template<> Eigen::Matrix< double, 6, 1 > tudat::ephemerides::Ephemeris::getTemplatedStateFromEphemeris (const double & time)
Definition at line 19 of file ephemeris.cpp.
References getCartesianState().
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::Ephemeris::getTemplatedStateFromEphemeris (const double & time)
Definition at line 26 of file ephemeris.cpp.
References getCartesianLongState().
template<> Eigen::Matrix< double, 6, 1 > tudat::ephemerides::Ephemeris::getTemplatedStateFromEphemeris (const Time & time)
Definition at line 33 of file ephemeris.cpp.
References getCartesianStateFromExtendedTime().
template<> Eigen::Matrix< long double, 6, 1 > tudat::ephemerides::Ephemeris::getTemplatedStateFromEphemeris (const Time & time)
Definition at line 40 of file ephemeris.cpp.
References getCartesianLongStateFromExtendedTime().
Member Data Documentation
std::string tudat::ephemerides::Ephemeris::referenceFrameOrigin_ protected
Reference frame origin. This identifier gives only the origin of the reference frame, its orientation is defined by the referenceFrameOrientation_ variable.
Definition at line 138 of file ephemeris.h.
Referenced by tudat::ephemerides::SpiceEphemeris::getCartesianState(), and getReferenceFrameOrigin().
std::string tudat::ephemerides::Ephemeris::referenceFrameOrientation_ protected
Reference frame orientation. This identifier gives only the orientation of the reference frame, the origin is defined by the referenceFrameOrigin_ variable.
Definition at line 145 of file ephemeris.h.
Referenced by tudat::ephemerides::SpiceEphemeris::getCartesianState(), and getReferenceFrameOrientation().
The documentation for this class was generated from the following files:
Astrodynamics/Ephemerides/ephemeris.h
Astrodynamics/Ephemerides/ephemeris.cpp