Tudat: tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType > Class Template Reference
tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType > Class Template Reference
Linear Kalman filter class.
#include <linearKalmanFilter.h>
Public Types
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix DependentMatrix
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentVector DependentVector
Inherit typedefs from base class.
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::Function Function
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::Integrator Integrator
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings IntegratorSettings
typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction MatrixFunction
Public Types inherited from tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >
typedef FilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix DependentMatrix
typedef FilterBase< IndependentVariableType, DependentVariableType >::DependentVector DependentVector
Inherit typedefs from base class.
typedef FilterBase< IndependentVariableType, DependentVariableType >::Function Function
typedef FilterBase< IndependentVariableType, DependentVariableType >::Integrator Integrator
typedef FilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings IntegratorSettings
typedef FilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction MatrixFunction
Public Types inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
typedef Eigen::Matrix< DependentVariableType, Eigen::Dynamic, Eigen::Dynamic > DependentMatrix
Typedef of the state and measurement matrices.
typedef Eigen::Matrix< DependentVariableType, Eigen::Dynamic, 1 > DependentVector
Typedef of the state and measurement vectors.
typedef std::function< DependentVector(const IndependentVariableType, const DependentVector &) > Function
Typedef of the function describing the system and the measurements.
typedef numerical_integrators::NumericalIntegrator< IndependentVariableType, DependentVector, DependentVector, IndependentVariableType > Integrator
Typedef of the integrator.
typedef numerical_integrators::IntegratorSettings< IndependentVariableType > IntegratorSettings
Typedef of the integrator settings.
typedef std::function< DependentMatrix(const IndependentVariableType, const DependentVector &) > MatrixFunction
Typedefs for system and measurement matrix functions.
Public Member Functions
LinearKalmanFilter (const MatrixFunction &stateTransitionMatrixFunction, const MatrixFunction &controlMatrixFunction, const MatrixFunction &measurementMatrixFunction, const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings=nullptr)
Default constructor.
LinearKalmanFilter (const DependentMatrix &stateTransitionMatrix, const DependentMatrix &controlMatrix, const DependentMatrix &measurementMatrix, const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings=nullptr)
Constructor.
~LinearKalmanFilter ()
Destructor.
void updateFilter (const DependentVector &currentMeasurementVector)
Function to update the filter with the new step data.
Public Member Functions inherited from tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >
KalmanFilterBase (const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings)
Constructor.
virtual ~KalmanFilterBase ()
Destructor.
Public Member Functions inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
FilterBase (const DependentMatrix &systemUncertainty, const DependentMatrix &measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector &initialStateVector, const DependentMatrix &initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings)
Constructor.
virtual ~FilterBase ()
Destructor.
void clearFilterHistory ()
Function to clear the history of stored variables.
DependentMatrix getCurrentCovarianceEstimate ()
Function to retrieve current covariance estimate.
DependentVector getCurrentStateEstimate ()
Function to retrieve current state estimate.
IndependentVariableType getCurrentTime ()
Function to retrieve current time.
std::map< IndependentVariableType, DependentMatrix > getEstimatedCovarianceHistory ()
Function to retrieve the history of estimated covariance matrices.
std::map< IndependentVariableType, DependentVector > getEstimatedStateHistory ()
Function to retrieve the history of estimated states.
IndependentVariableType getFilteringStepSize ()
Function to retrieve step-size for filtering.
IndependentVariableType getInitialTime ()
Function to retrieve initial time.
std::pair< std::vector< DependentVector >, std::vector< DependentVector > > getNoiseHistory ()
Function to retrieve the history of system and measurement noise used by the updateFilter function.
void modifyCurrentStateAndCovarianceEstimates (const DependentVector &newStateEstimate, const DependentMatrix &newCovarianceEstimate=DependentMatrix::Zero())
Function to update the a-posteriori estimates of state and covariance with external data.
void modifyCurrentTime (const double newCurrentTime)
Function to modify the current time.
void modifyFilteringStepSize (const double newFilteringStepSize)
Function to modify the step size for filtering.
DependentVector produceMeasurementNoise ()
Function to produce measurement noise.
DependentVector produceSystemNoise ()
Function to produce system noise.
void revertToPreviousTimeStep (const double timeToBeRemoved)
Function to revert to the previous time step.
Private Member Functions
DependentVector createMeasurementFunction (const IndependentVariableType currentTime, const DependentVector &currentStateVector)
Function to create the function that defines the system model.
DependentVector createSystemFunction (const IndependentVariableType currentTime, const DependentVector &currentStateVector)
Function to create the function that defines the system model.
Private Attributes
MatrixFunction controlMatrixFunction_
Control matrix function.
MatrixFunction measurementMatrixFunction_
Measurement matrix function.
MatrixFunction stateTransitionMatrixFunction_
State transition matrix function.
Additional Inherited Members
Protected Member Functions inherited from tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >
virtual void correctCovariance (const DependentMatrix &aPrioriCovarianceEstimate, const DependentMatrix &currentMeasurementMatrix, const DependentMatrix &kalmanGain)
Function to correct the covariance for the next time step.
DependentVector predictState ()
Function to predict the state for the next time step.
DependentVector predictState (const DependentVector &currentStateVector)
Function to predict the state for the next time step, by overwriting previous state.
Protected Member Functions inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
virtual void clearSpecificFilterHistory ()
Function to clear the history of stored variables for derived class-specific variables.
void correctState (const DependentVector &aPrioriStateEstimate, const DependentVector &currentMeasurementVector, const DependentVector &measurementEstimate, const DependentMatrix &gainMatrix)
Function to correct the state for the next time step.
virtual void specificRevertToPreviousTimeStep (const double timeToBeRemoved)
Function to revert to the previous time step for derived class-specific variables.
Protected Attributes inherited from tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >
DependentMatrix aPosterioriCovarianceEstimate_
Matrix representing the a-posteriori estimated covariance.
DependentVector aPosterioriStateEstimate_
Vector representing the a-posteriori estimated state.
IndependentVariableType currentTime_
Scalar representing the current time.
IndependentVariableType filteringStepSize_
Scalar representing step-size for filtering process.
std::map< IndependentVariableType, DependentMatrix > historyOfCovarianceEstimates_
Map of estimated covariance matrices history.
std::map< IndependentVariableType, DependentVector > historyOfStateEstimates_
Map of estimated states vectors history.
DependentMatrix identityMatrix_
Indentity matrix.
const IndependentVariableType initialTime_
Scalar representing the initial time.
std::shared_ptr< Integrator > integrator_
Pointer to the integrator.
bool isStateToBeIntegrated_
Boolean specifying whether the state needs to be integrated.
Function measurementFunction_
Measurement function.
const DependentMatrix measurementUncertainty_
Matrix representing the uncertainty in measurement modeling.
Function systemFunction_
System function.
const DependentMatrix systemUncertainty_
Matrix representing the uncertainty in system modeling.
Detailed Description
template<typename IndependentVariableType = double, typename DependentVariableType = double>
class tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >
Class for the set up and use of the linear Kalman filter.
Template Parameters
IndependentVariableType Type of independent variable. Default is double.
DependentVariableType Type of dependent variable. Default is double.
Definition at line 32 of file linearKalmanFilter.h.
Member Typedef Documentation
DependentVector
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentVector tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::DependentVector
Definition at line 37 of file linearKalmanFilter.h.
DependentMatrix
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::DependentMatrix tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::DependentMatrix
Definition at line 38 of file linearKalmanFilter.h.
Function
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::Function tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::Function
Definition at line 39 of file linearKalmanFilter.h.
MatrixFunction
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::MatrixFunction tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::MatrixFunction
Definition at line 40 of file linearKalmanFilter.h.
IntegratorSettings
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::IntegratorSettings tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::IntegratorSettings
Definition at line 41 of file linearKalmanFilter.h.
Integrator
template<typename IndependentVariableType = double, typename DependentVariableType = double> typedef KalmanFilterBase< IndependentVariableType, DependentVariableType >::Integrator tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::Integrator
Definition at line 42 of file linearKalmanFilter.h.
Constructor & Destructor Documentation
LinearKalmanFilter() [1/2]
template<typename IndependentVariableType = double, typename DependentVariableType = double> tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::LinearKalmanFilter (const MatrixFunction & stateTransitionMatrixFunction, const MatrixFunction & controlMatrixFunction, const MatrixFunction & measurementMatrixFunction, const DependentMatrix & systemUncertainty, const DependentMatrix & measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector & initialStateVector, const DependentMatrix & initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings = nullptr) inline
Default constructor. This constructor takes state, control and measurement matrix functions as inputs. These functions can be a function of time, state and (for state and control matrices) control vector.
Parameters
stateTransitionMatrixFunction Function returning the state transition matrix, as a function of time and state vector.
controlMatrixFunction Function returning the control matrix, as a function of time and state vector.
measurementMatrixFunction Function returning the measurement matrix, as a function of time and state vector.
systemUncertainty Matrix defining the uncertainty in modeling of the system.
measurementUncertainty Matrix defining the uncertainty in modeling of the measurements.
filteringStepSize Scalar representing the value of the constant filtering time step.
initialTime Scalar representing the value of the initial time.
initialStateVector Vector representing the initial (estimated) state of the system. It is used as first a-priori estimate of the state vector.
initialCovarianceMatrix Matrix representing the initial (estimated) covariance of the system. It is used as first a-priori estimate of the covariance matrix.
integratorSettings Settings for the numerical integrator to be used to propagate state.
Definition at line 62 of file linearKalmanFilter.h.
LinearKalmanFilter() [2/2]
template<typename IndependentVariableType = double, typename DependentVariableType = double> tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::LinearKalmanFilter (const DependentMatrix & stateTransitionMatrix, const DependentMatrix & controlMatrix, const DependentMatrix & measurementMatrix, const DependentMatrix & systemUncertainty, const DependentMatrix & measurementUncertainty, const IndependentVariableType filteringStepSize, const IndependentVariableType initialTime, const DependentVector & initialStateVector, const DependentMatrix & initialCovarianceMatrix, const std::shared_ptr< IntegratorSettings > integratorSettings = nullptr) inline
Constructor taking constant state, control and measurement matrices as inputs.
Parameters
stateTransitionMatrix Constant matrix representing the state transition matrix.
controlMatrix Constant matrix representing the control matrix.
measurementMatrix Constant matrix representing the measurement matrix.
systemUncertainty Matrix defining the uncertainty in modeling of the system.
measurementUncertainty Matrix defining the uncertainty in modeling of the measurements.
filteringStepSize Scalar representing the value of the constant filtering time step.
initialTime Scalar representing the value of the initial time.
initialStateVector Vector representing the initial (estimated) state of the system. It is used as first a-priori estimate of the state vector.
initialCovarianceMatrix Matrix representing the initial (estimated) covariance of the system. It is used as first a-priori estimate of the covariance matrix.
integratorSettings Pointer to integration settings defining the integrator to be used to propagate the state.
Definition at line 102 of file linearKalmanFilter.h.
~LinearKalmanFilter()
template<typename IndependentVariableType = double, typename DependentVariableType = double> tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::~LinearKalmanFilter () inline
Definition at line 120 of file linearKalmanFilter.h.
Member Function Documentation
updateFilter()
template<typename IndependentVariableType = double, typename DependentVariableType = double> void tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter (const DependentVector & currentMeasurementVector) inline virtual
Function to update the filter with the new step data.
Parameters
currentMeasurementVector Vector representing current measurement.
Implements tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >.
Definition at line 127 of file linearKalmanFilter.h.
References tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::aPosterioriCovarianceEstimate_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::aPosterioriStateEstimate_, tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::correctCovariance(), tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::correctState(), tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::currentTime_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::filteringStepSize_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::measurementFunction_, tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::measurementMatrixFunction_, tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::measurementUncertainty_, tudat::filters::KalmanFilterBase< IndependentVariableType, DependentVariableType >::predictState(), tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::stateTransitionMatrixFunction_, and tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >::systemUncertainty_.
createSystemFunction()
template<typename IndependentVariableType = double, typename DependentVariableType = double> DependentVector tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::createSystemFunction (const IndependentVariableType currentTime, const DependentVector & currentStateVector) inline private virtual
Function to create the function that defines the system model. The output of this function is then bound to the systemFunction_ variable, via the std::bind command.
Parameters
currentTime Scalar representing the current time.
currentStateVector Vector representing the current state.
Returns
Vector representing the estimated state.
Implements tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >.
Definition at line 160 of file linearKalmanFilter.h.
References tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::stateTransitionMatrixFunction_.
createMeasurementFunction()
template<typename IndependentVariableType = double, typename DependentVariableType = double> DependentVector tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::createMeasurementFunction (const IndependentVariableType currentTime, const DependentVector & currentStateVector) inline private virtual
Function to create the function that defines the system model. The output of this function is then bound to the measurementFunction_ variable, via the std::bind command.
Parameters
currentTime Scalar representing the current time.
currentStateVector Vector representing the current state.
Returns
Vector representing the estimated measurement.
Implements tudat::filters::FilterBase< IndependentVariableType, DependentVariableType >.
Definition at line 174 of file linearKalmanFilter.h.
References tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::measurementMatrixFunction_.
Member Data Documentation
stateTransitionMatrixFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> MatrixFunction tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::stateTransitionMatrixFunction_ private
State transition matrix function, which will be used to generate the system function, together with the controlMatrixFunction_, by multiplying the matrices with the state and control vectors, respectively.
Definition at line 185 of file linearKalmanFilter.h.
Referenced by tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::createSystemFunction(), and tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
controlMatrixFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> MatrixFunction tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::controlMatrixFunction_ private
Control matrix function, which will be used to generate the system function, together with the stateTransitionMatrixFunction_, by multiplying the matrices with the control and state vectors, respectively.
Definition at line 192 of file linearKalmanFilter.h.
measurementMatrixFunction_
template<typename IndependentVariableType = double, typename DependentVariableType = double> MatrixFunction tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::measurementMatrixFunction_ private
Measurement matrix function, which will be used to generate the measurement function, by multiplying the matrix with the state vector.
Definition at line 199 of file linearKalmanFilter.h.
Referenced by tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::createMeasurementFunction(), and tudat::filters::LinearKalmanFilter< IndependentVariableType, DependentVariableType >::updateFilter().
The documentation for this class was generated from the following file:
Mathematics/Filters/linearKalmanFilter.h