Tudat: tudat::input_output::MissileDatcomReader Class Reference
tudat::input_output::MissileDatcomReader Class Reference
Class to read a for004.dat file generated by missile Datcom.
#include <missileDatcomReader.h>
Public Member Functions
MissileDatcomReader (const std::string &fileNameAndPath)
Class constructor, reads data file.
std::vector< double > getMissileDatcomData ()
Gets the split and parsed data from the 004 file.
Private Member Functions
void openFile (const std::string &fileNameAndPath)
Open data file.
void readAndStoreData (const std::string &skipKeyword)
Read and store data.
void readFor004 (const std::string &fileNameAndPath)
Function to read the for004.dat file and return one long std::vector.
void split (const std::string &dataString, char separator, std::vector< std::string > &dataVector)
Function to split a single std::string into a std::vector of std::strings.
double stringToDouble (std::string const &inputString)
Function to Convert a string to a double.
Private Attributes
std::map< unsigned int, std::string > containerOfDataFromFile_
Map container of data from file.
std::ifstream dataFile_
Data file stream.
std::vector< std::string > dataVector_
String to temporarilly store the a splitted std::string.
std::map< unsigned int, std::string >::iterator iteratorContainerOfData_
Iterator for std::map container of data from file.
std::vector< double > missileDatcomData_
Data std::vector with the rough split and parsed missileDatcom data.
std::map< unsigned int, std::string > missileDatcomDataContainer_
Map to store the read for004.dat file.
Detailed Description
Class to read a for004.dat file generated by missile Datcom. Based on the input cards FLC,1,145 (Flight Condition Data) SB1,1,220 (Static Coefficient and Derivative Data) DB1,1,400 (Dynamic Derivative Data)
Definition at line 39 of file missileDatcomReader.h.
Constructor & Destructor Documentation
tudat::input_output::MissileDatcomReader::MissileDatcomReader (const std::string & fileNameAndPath)
Default constructor.
Class constructor, reads data file to vector of doubles containing all data.
Parameters
fileNameAndPath Path and name of file containing missile datcom data
Definition at line 30 of file missileDatcomReader.cpp.
References readFor004().
Member Function Documentation
std::vector< double > tudat::input_output::MissileDatcomReader::getMissileDatcomData () inline
Gets the split and parsed data from the 004 file.
Returns
Vector of doubles, which have been sequentially read from 004 file.
Definition at line 55 of file missileDatcomReader.h.
References missileDatcomData_, openFile(), readAndStoreData(), readFor004(), and split().
Referenced by tudat::input_output::MissileDatcomData::MissileDatcomData().
void tudat::input_output::MissileDatcomReader::readFor004 (const std::string & fileNameAndPath) private
Function to read the for004.dat file and return one long vector.
Function to read the for004.dat file and return one long std::vector with first the FLC data, then the SB1 data, next the DB1 data, and then the same data again for the next machnumber. (see missile datcom user manual p88 and further).
Parameters
fileNameAndPath Path and name of the for004.dat file.
Definition at line 36 of file missileDatcomReader.cpp.
References containerOfDataFromFile_, dataFile_, dataVector_, iteratorContainerOfData_, missileDatcomData_, missileDatcomDataContainer_, openFile(), readAndStoreData(), split(), and stringToDouble().
Referenced by getMissileDatcomData(), and MissileDatcomReader().
void tudat::input_output::MissileDatcomReader::openFile (const std::string & fileNameAndPath) private
Opens the for004.dat data file.
Parameters
fileNameAndPath Path and name of the for004.dat file.
Definition at line 66 of file missileDatcomReader.cpp.
References dataFile_.
Referenced by getMissileDatcomData(), and readFor004().
void tudat::input_output::MissileDatcomReader::split (const std::string & dataString, char separator, std::vector< std::string > & dataVector) private
Function to split a string consisting of line of entries in smaller strings.
Function to split a single std::string into a std::vector of small std::strings. Entries are separated by a separator (which is also a std::string) WARNING: If multiple seperators are placed next to each other, the entry is skipped.
Parameters
dataString the long std::string which needs to be splitted.
separator the separator symbol
dataVector the std::vector with all the substd::strings.
Definition at line 80 of file missileDatcomReader.cpp.
Referenced by getMissileDatcomData(), and readFor004().
void tudat::input_output::MissileDatcomReader::readAndStoreData (const std::string & skipKeyword) private
Reads and stores data from input file.
Parameters
skipKeyword Keyword to skip in input file.
Definition at line 108 of file missileDatcomReader.cpp.
References containerOfDataFromFile_, and dataFile_.
Referenced by getMissileDatcomData(), and readFor004().
double tudat::input_output::MissileDatcomReader::stringToDouble (std::string const & inputString) private
Creates an istringstream object and converted the string to a double. Throws an exception if incorrect string is used.
Parameters
inputString string with the data to be converted
Returns
the converted string
Definition at line 137 of file missileDatcomReader.cpp.
Referenced by readFor004().
Member Data Documentation
std::map< unsigned int, std::string > tudat::input_output::MissileDatcomReader::missileDatcomDataContainer_ private
Map to store the read for004.dat file.
Definition at line 100 of file missileDatcomReader.h.
Referenced by readFor004().
std::map< unsigned int, std::string >::iterator tudat::input_output::MissileDatcomReader::iteratorContainerOfData_ private
Iterator for std::map container of std::string data from data file.
Definition at line 106 of file missileDatcomReader.h.
Referenced by readFor004().
std::vector< std::string > tudat::input_output::MissileDatcomReader::dataVector_ private
String to temporarilly store the a splitted std::string.
Definition at line 112 of file missileDatcomReader.h.
Referenced by readFor004().
std::vector< double > tudat::input_output::MissileDatcomReader::missileDatcomData_ private
Data std::vector with the rough split and parsed missileDatcom data.
Definition at line 118 of file missileDatcomReader.h.
Referenced by getMissileDatcomData(), and readFor004().
std::ifstream tudat::input_output::MissileDatcomReader::dataFile_ private
Data file stream.
Definition at line 124 of file missileDatcomReader.h.
Referenced by openFile(), readAndStoreData(), and readFor004().
std::map< unsigned int, std::string > tudat::input_output::MissileDatcomReader::containerOfDataFromFile_ private
Map container of string data from data file, obtained by reading each line of data from file using the getline() function. The key is the line number from the file and the value is line data.
Definition at line 132 of file missileDatcomReader.h.
Referenced by readAndStoreData(), and readFor004().
The documentation for this class was generated from the following files:
InputOutput/missileDatcomReader.h
InputOutput/missileDatcomReader.cpp