Tudat: tudat::simulation_setup::BaseStateInterface Class Reference
tudat::simulation_setup::BaseStateInterface Class Reference abstract
Base class used for the determination of the inertial state of a Body's ephemeris origin.
#include <body.h>
Public Member Functions
BaseStateInterface (const std::string baseFrameId)
Constructor.
virtual ~BaseStateInterface ()
Destructor.
template<>
Eigen::Matrix< double, 6, 1 > getBaseFrameState (const double time)
Function through which the state of baseFrameId_ in the inertial frame can be determined.
template<>
Eigen::Matrix< long double, 6, 1 > getBaseFrameState (const double time)
Function through which the state of baseFrameId_ in the inertial frame can be determined.
template<>
Eigen::Matrix< double, 6, 1 > getBaseFrameState (const Time time)
Function through which the state of baseFrameId_ in the inertial frame can be determined.
template<>
Eigen::Matrix< long double, 6, 1 > getBaseFrameState (const Time time)
Function through which the state of baseFrameId_ in the inertial frame can be determined.
template<typename OutputTimeType , typename OutputStateScalarType >
Eigen::Matrix< OutputStateScalarType, 6, 1 > getBaseFrameState (const OutputTimeType time)
Function through which the state of baseFrameId_ in the inertial frame can be determined.
Protected Member Functions
virtual Eigen::Matrix< double, 6, 1 > getBaseFrameDoubleState (const double time)=0
Pure virtual function through which the state of baseFrameId_ in the inertial frame can be determined.
virtual Eigen::Matrix< double, 6, 1 > getBaseFrameDoubleState (const Time &time)=0
Pure virtual function through which the state of baseFrameId_ in the inertial frame can be determined.
virtual Eigen::Matrix< long double, 6, 1 > getBaseFrameLongDoubleState (const double time)=0
Pure virtual function through which the state of baseFrameId_ in the inertial frame can be determined.
virtual Eigen::Matrix< long double, 6, 1 > getBaseFrameLongDoubleState (const Time &time)=0
Pure virtual function through which the state of baseFrameId_ in the inertial frame can be determined.
Protected Attributes
std::string baseFrameId_
Name of frame origin for which inertial state is computed by this class.
Detailed Description
Base class used for the determination of the inertial state of a Body's ephemeris origin. This base class is used to provide an untemplated interface class through which to call the base frame state. The state may be defined in a templated manner in the derived class.
Definition at line 52 of file body.h.
Constructor & Destructor Documentation
BaseStateInterface()
tudat::simulation_setup::BaseStateInterface::BaseStateInterface (const std::string baseFrameId) inline
Constructor
Parameters
baseFrameId Name of frame origin for which inertial state is computed by this class
Definition at line 61 of file body.h.
~BaseStateInterface()
virtual tudat::simulation_setup::BaseStateInterface::~BaseStateInterface () inline virtual
Definition at line 66 of file body.h.
Member Function Documentation
getBaseFrameState() [1/5]
template<typename OutputTimeType , typename OutputStateScalarType > Eigen::Matrix< OutputStateScalarType, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameState (const OutputTimeType time)
Function through which the state of baseFrameId_ in the inertial frame can be determined
Parameters
time Time at which state is to be computed
Returns
Inertial state of frame origin at requested time
getBaseFrameDoubleState() [1/2]
virtual Eigen::Matrix< double, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameDoubleState (const double time) protected pure virtual
Pure virtual function through which the state of baseFrameId_ in the inertial frame can be determined (double time and double state scalar).
Parameters
time Time at which state is to be computed
Returns
Inertial state of frame origin at requested time
Implemented in tudat::simulation_setup::BaseStateInterfaceImplementation< TimeType, StateScalarType >.
Referenced by getBaseFrameState().
getBaseFrameLongDoubleState() [1/2]
virtual Eigen::Matrix< long double, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameLongDoubleState (const double time) protected pure virtual
Pure virtual function through which the state of baseFrameId_ in the inertial frame can be determined (double time and double long state scalar).
Parameters
time Time at which state is to be computed
Returns
Inertial state of frame origin at requested time
Implemented in tudat::simulation_setup::BaseStateInterfaceImplementation< TimeType, StateScalarType >.
Referenced by getBaseFrameState().
getBaseFrameDoubleState() [2/2]
virtual Eigen::Matrix< double, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameDoubleState (const Time & time) protected pure virtual
Pure virtual function through which the state of baseFrameId_ in the inertial frame can be determined (Time object time and double state scalar).
Parameters
time Time at which state is to be computed
Returns
Inertial state of frame origin at requested time
Implemented in tudat::simulation_setup::BaseStateInterfaceImplementation< TimeType, StateScalarType >.
getBaseFrameLongDoubleState() [2/2]
virtual Eigen::Matrix< long double, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameLongDoubleState (const Time & time) protected pure virtual
Pure virtual function through which the state of baseFrameId_ in the inertial frame can be determined (Time object time and long double state scalar).
Parameters
time Time at which state is to be computed
Returns
Inertial state of frame origin at requested time
Implemented in tudat::simulation_setup::BaseStateInterfaceImplementation< TimeType, StateScalarType >.
getBaseFrameState() [2/5]
template<> Eigen::Matrix< double, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameState (const double time)
Definition at line 25 of file body.cpp.
References getBaseFrameDoubleState().
getBaseFrameState() [3/5]
template<> Eigen::Matrix< long double, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameState (const double time)
Definition at line 32 of file body.cpp.
References getBaseFrameLongDoubleState().
getBaseFrameState() [4/5]
template<> Eigen::Matrix< double, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameState (const Time time)
Definition at line 39 of file body.cpp.
References getBaseFrameDoubleState().
getBaseFrameState() [5/5]
template<> Eigen::Matrix< long double, 6, 1 > tudat::simulation_setup::BaseStateInterface::getBaseFrameState (const Time time)
Definition at line 46 of file body.cpp.
References getBaseFrameLongDoubleState().
Member Data Documentation
baseFrameId_
std::string tudat::simulation_setup::BaseStateInterface::baseFrameId_ protected
Definition at line 117 of file body.h.
The documentation for this class was generated from the following files:
SimulationSetup/EnvironmentSetup/body.h
SimulationSetup/EnvironmentSetup/body.cpp