Tudat: tudat::gravitation::SphericalHarmonicsGravityField Class Reference
tudat::gravitation::SphericalHarmonicsGravityField Class Reference
Class to represent a spherical harmonic gravity field expansion.
#include <sphericalHarmonicsGravityField.h>
Public Member Functions
SphericalHarmonicsGravityField (const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd &cosineCoefficients=Eigen::MatrixXd::Identity(1, 1), const Eigen::MatrixXd &sineCoefficients=Eigen::MatrixXd::Zero(1, 1), const std::string &fixedReferenceFrame="")
Class constructor.
virtual ~SphericalHarmonicsGravityField ()
Virtual destructor.
Eigen::MatrixXd getCosineCoefficients ()
Function to get the cosine spherical harmonic coefficients (geodesy normalized)
Eigen::MatrixXd getCosineCoefficients (const int maximumDegree, const int maximumOrder)
Function to get a cosine spherical harmonic coefficient block (geodesy normalized)
double getDegreeOfExpansion ()
Get maximum degree of spherical harmonics gravity field expansion.
std::string getFixedReferenceFrame ()
Function to retrieve the tdentifier for body-fixed reference frame.
Eigen::Vector3d getGradientOfPotential (const Eigen::Vector3d &bodyFixedPosition)
Get the gradient of the potential.
Eigen::Vector3d getGradientOfPotential (const Eigen::Vector3d &bodyFixedPosition, const double maximumDegree, const double maximumOrder)
Get the gradient of the potential.
double getGravitationalPotential (const Eigen::Vector3d &bodyFixedPosition)
Function to calculate the gravitational potential at a given point.
double getGravitationalPotential (const Eigen::Vector3d &bodyFixedPosition, const double maximumDegree, const double maximumOrder, const double minimumDegree=0, const double minimumOrder=0)
Function to calculate the gravitational potential due to terms up to given degree and order due to this body at a given point.
double getOrderOfExpansion ()
Get maximum order of spherical harmonics gravity field expansion.
double getReferenceRadius ()
Function to get the reference radius.
Eigen::MatrixXd getSineCoefficients ()
Function to get the sine spherical harmonic coefficients (geodesy normalized)
Eigen::MatrixXd getSineCoefficients (const int maximumDegree, const int maximumOrder)
Function to get a sine spherical harmonic coefficient block (geodesy normalized)
void setCosineCoefficients (const Eigen::MatrixXd &cosineCoefficients)
Function to reset the cosine spherical harmonic coefficients (geodesy normalized)
void setSineCoefficients (const Eigen::MatrixXd &sineCoefficients)
Function to reset the cosine spherical harmonic coefficients (geodesy normalized)
Public Member Functions inherited from tudat::gravitation::GravityFieldModel
GravityFieldModel (const double gravitationalParameter)
Default constructor.
virtual ~GravityFieldModel ()
Default destructor.
double getGravitationalParameter ()
Get the gravitational parameter.
double getGravitationalPotential (const Eigen::Vector3d &bodyFixedPosition)
Get the gravitational potential at given body-fixed position.
void resetGravitationalParameter (const double gravitationalParameter)
Set the gravitational parameter.
Protected Attributes
Eigen::MatrixXd cosineCoefficients_
Cosine spherical harmonic coefficients (geodesy normalized)
std::string fixedReferenceFrame_
Identifier for body-fixed reference frame.
double referenceRadius_
Reference radius of spherical harmonic field expansion.
Eigen::MatrixXd sineCoefficients_
Sine spherical harmonic coefficients (geodesy normalized)
boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicsCache_
Cache object for potential calculations.
Protected Attributes inherited from tudat::gravitation::GravityFieldModel
double gravitationalParameter_
Gravitational parameter.
Detailed Description
Class to represent a spherical harmonic gravity field expansion of a massive body with time-independent spherical harmonic gravity field coefficients.
Definition at line 67 of file sphericalHarmonicsGravityField.h.
Constructor & Destructor Documentation
tudat::gravitation::SphericalHarmonicsGravityField::SphericalHarmonicsGravityField (const double gravitationalParameter, const double referenceRadius, const Eigen::MatrixXd & cosineCoefficients = Eigen::MatrixXd::Identity(1, 1), const Eigen::MatrixXd & sineCoefficients = Eigen::MatrixXd::Zero(1, 1), const std::string & fixedReferenceFrame = "") inline
Class constructor.
Parameters
gravitationalParameter Gravitational parameter of massive body
referenceRadius Reference radius of spherical harmonic field expansion
cosineCoefficients Cosine spherical harmonic coefficients (geodesy normalized)
sineCoefficients Sine spherical harmonic coefficients (geodesy normalized)
fixedReferenceFrame Identifier for body-fixed reference frame to which the field is fixed (optional).
Definition at line 80 of file sphericalHarmonicsGravityField.h.
References cosineCoefficients_, and sphericalHarmonicsCache_.
virtual tudat::gravitation::SphericalHarmonicsGravityField::~SphericalHarmonicsGravityField () inline virtual
Virtual destructor.
Definition at line 100 of file sphericalHarmonicsGravityField.h.
Member Function Documentation
double tudat::gravitation::SphericalHarmonicsGravityField::getReferenceRadius () inline
Returns the reference radius used for the spherical harmonics expansion in meters.
Returns
Reference radius of spherical harmonic field expansion
Definition at line 107 of file sphericalHarmonicsGravityField.h.
References referenceRadius_.
Eigen::MatrixXd tudat::gravitation::SphericalHarmonicsGravityField::getCosineCoefficients () inline
Function to get the cosine spherical harmonic coefficients (geodesy normalized)
Returns
Cosine spherical harmonic coefficients (geodesy normalized)
Definition at line 117 of file sphericalHarmonicsGravityField.h.
References cosineCoefficients_.
Referenced by tudat::simulation_setup::createMutualSphericalHarmonicsGravityAcceleration(), tudat::simulation_setup::createSphericalHarmonicsGravityAcceleration(), and tudat::simulation_setup::createVectorParameterToEstimate().
Eigen::MatrixXd tudat::gravitation::SphericalHarmonicsGravityField::getSineCoefficients () inline
Function to get the sine spherical harmonic coefficients (geodesy normalized)
Returns
Sine spherical harmonic coefficients (geodesy normalized)
Definition at line 127 of file sphericalHarmonicsGravityField.h.
References sineCoefficients_.
Referenced by tudat::simulation_setup::createMutualSphericalHarmonicsGravityAcceleration(), tudat::simulation_setup::createSphericalHarmonicsGravityAcceleration(), and tudat::simulation_setup::createVectorParameterToEstimate().
void tudat::gravitation::SphericalHarmonicsGravityField::setCosineCoefficients (const Eigen::MatrixXd & cosineCoefficients) inline
Function to reset the cosine spherical harmonic coefficients (geodesy normalized)
Parameters
cosineCoefficients New cosine spherical harmonic coefficients (geodesy normalized)
Definition at line 137 of file sphericalHarmonicsGravityField.h.
References cosineCoefficients_.
Referenced by tudat::simulation_setup::createVectorParameterToEstimate().
void tudat::gravitation::SphericalHarmonicsGravityField::setSineCoefficients (const Eigen::MatrixXd & sineCoefficients) inline
Function to reset the cosine spherical harmonic coefficients (geodesy normalized)
Parameters
sineCoefficients New sine spherical harmonic coefficients (geodesy normalized)
Definition at line 147 of file sphericalHarmonicsGravityField.h.
References sineCoefficients_.
Referenced by tudat::simulation_setup::createVectorParameterToEstimate().
Eigen::MatrixXd tudat::gravitation::SphericalHarmonicsGravityField::getCosineCoefficients (const int maximumDegree, const int maximumOrder) inline
Function to get a cosine spherical harmonic coefficient block (geodesy normalized) up to a given degree and order
Parameters
maximumDegree Maximum degree of coefficient block
maximumOrder Maximum order of coefficient block
Returns
Cosine spherical harmonic coefficients (geodesy normalized) up to given degree and order
Definition at line 161 of file sphericalHarmonicsGravityField.h.
References cosineCoefficients_.
Eigen::MatrixXd tudat::gravitation::SphericalHarmonicsGravityField::getSineCoefficients (const int maximumDegree, const int maximumOrder) inline
Function to get a sine spherical harmonic coefficient block (geodesy normalized) up to a given degree and order
Parameters
maximumDegree Maximum degree of coefficient block
maximumOrder Maximum order of coefficient block
Returns
Sine spherical harmonic coefficients (geodesy normalized) up to given degree and order
Definition at line 175 of file sphericalHarmonicsGravityField.h.
References sineCoefficients_.
double tudat::gravitation::SphericalHarmonicsGravityField::getDegreeOfExpansion () inline
Returns the maximum degree of the spherical harmonics gravity field expansion.
Returns
Degree of spherical harmonics expansion.
Definition at line 185 of file sphericalHarmonicsGravityField.h.
References cosineCoefficients_.
double tudat::gravitation::SphericalHarmonicsGravityField::getOrderOfExpansion () inline
Returns the maximum order of the spherical harmonics gravity field expansion.
Returns
Order of spherical harmonics expansion.
Definition at line 195 of file sphericalHarmonicsGravityField.h.
References cosineCoefficients_.
double tudat::gravitation::SphericalHarmonicsGravityField::getGravitationalPotential (const Eigen::Vector3d & bodyFixedPosition) inline
Function to calculate the gravitational potential due to this body at a given point. Note that this function, which has the same interface as in the base class and expands the gravity field to its maximum degree and order.
Parameters
bodyFixedPosition of point at which potential is to be calculated, in body-fixed frame.
Returns
Gravitational potential at requested point.
Definition at line 209 of file sphericalHarmonicsGravityField.h.
References cosineCoefficients_, and sineCoefficients_.
double tudat::gravitation::SphericalHarmonicsGravityField::getGravitationalPotential (const Eigen::Vector3d & bodyFixedPosition, const double maximumDegree, const double maximumOrder, const double minimumDegree = 0, const double minimumOrder = 0) inline
Function to calculate the gravitational potential due to terms up to given degree and order at a given point
Parameters
bodyFixedPosition Position of point at which potential is to be calculate, in body-fixed frame.
maximumDegree Maximum degree of spherical harmonic coefficients to include.
maximumOrder Maximum order of spherical harmonic coefficients to include.
minimumDegree Minimum degree of spherical harmonic coefficients to include, default 0
minimumOrder Maximum order of spherical harmonic coefficients to include, default 0
Returns
Gravitational potential due to terms up to given degree and order at requested point.
Definition at line 229 of file sphericalHarmonicsGravityField.h.
References tudat::gravitation::calculateSphericalHarmonicGravitationalPotential(), cosineCoefficients_, tudat::gravitation::GravityFieldModel::gravitationalParameter_, referenceRadius_, sineCoefficients_, and sphericalHarmonicsCache_.
Eigen::Vector3d tudat::gravitation::SphericalHarmonicsGravityField::getGradientOfPotential (const Eigen::Vector3d & bodyFixedPosition) inline virtual
Returns the gradient of the potential for the gravity field selected. Note that this function, which has the same interface as in the base class and expands the gravity field to its maximum degree and order.
Parameters
bodyFixedPosition Position at which gradient of potential is to be determined
Returns
Gradient of potential.
Reimplemented from tudat::gravitation::GravityFieldModel.
Definition at line 251 of file sphericalHarmonicsGravityField.h.
References cosineCoefficients_, and sineCoefficients_.
Eigen::Vector3d tudat::gravitation::SphericalHarmonicsGravityField::getGradientOfPotential (const Eigen::Vector3d & bodyFixedPosition, const double maximumDegree, const double maximumOrder) inline
Returns the gradient of the potential for the gravity field selected.
Parameters
bodyFixedPosition Position at which gradient of potential is to be determined
maximumDegree Maximum degree of spherical harmonic coefficients to include.
maximumOrder Maximum order of spherical harmonic coefficients to include.
Returns
Gradient of potential.
Definition at line 265 of file sphericalHarmonicsGravityField.h.
References tudat::gravitation::computeGeodesyNormalizedGravitationalAccelerationSum(), cosineCoefficients_, tudat::gravitation::GravityFieldModel::gravitationalParameter_, referenceRadius_, sineCoefficients_, and sphericalHarmonicsCache_.
std::string tudat::gravitation::SphericalHarmonicsGravityField::getFixedReferenceFrame () inline
Function to retrieve the tdentifier for body-fixed reference frame
Returns
Function to retrieve the tdentifier for body-fixed reference frame.
Definition at line 280 of file sphericalHarmonicsGravityField.h.
References fixedReferenceFrame_.
Member Data Documentation
double tudat::gravitation::SphericalHarmonicsGravityField::referenceRadius_ protected
Reference radius of spherical harmonic field expansion
Definition at line 291 of file sphericalHarmonicsGravityField.h.
Referenced by getGradientOfPotential(), getGravitationalPotential(), and getReferenceRadius().
Eigen::MatrixXd tudat::gravitation::SphericalHarmonicsGravityField::cosineCoefficients_ protected
Cosine spherical harmonic coefficients (geodesy normalized)
Definition at line 297 of file sphericalHarmonicsGravityField.h.
Referenced by getCosineCoefficients(), getDegreeOfExpansion(), getGradientOfPotential(), getGravitationalPotential(), getOrderOfExpansion(), setCosineCoefficients(), SphericalHarmonicsGravityField(), and tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::update().
Eigen::MatrixXd tudat::gravitation::SphericalHarmonicsGravityField::sineCoefficients_ protected
Sine spherical harmonic coefficients (geodesy normalized)
Definition at line 303 of file sphericalHarmonicsGravityField.h.
Referenced by getGradientOfPotential(), getGravitationalPotential(), getSineCoefficients(), setSineCoefficients(), and tudat::gravitation::TimeDependentSphericalHarmonicsGravityField::update().
std::string tudat::gravitation::SphericalHarmonicsGravityField::fixedReferenceFrame_ protected
Identifier for body-fixed reference frame
Definition at line 309 of file sphericalHarmonicsGravityField.h.
Referenced by getFixedReferenceFrame().
boost::shared_ptr< basic_mathematics::SphericalHarmonicsCache > tudat::gravitation::SphericalHarmonicsGravityField::sphericalHarmonicsCache_ protected
Definition at line 312 of file sphericalHarmonicsGravityField.h.
Referenced by getGradientOfPotential(), getGravitationalPotential(), and SphericalHarmonicsGravityField().
The documentation for this class was generated from the following file:
Astrodynamics/Gravitation/sphericalHarmonicsGravityField.h