Tudat: tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType > Class Template Reference
tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType > Class Template Reference
Class used to update the environment during numerical integration.
#include <environmentUpdater.h>
Public Member Functions
EnvironmentUpdater (const simulation_setup::NamedBodyMap &bodyList, const std::map< EnvironmentModelsToUpdate, std::vector< std::string > > &updateSettings, const std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > &integratedStates=(std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > >()))
Constructor.
void updateEnvironment (const TimeType currentTime, const std::unordered_map< IntegratedStateType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &integratedStatesToSet, const std::vector< IntegratedStateType > &setIntegratedStatesFromEnvironment=std::vector< IntegratedStateType >())
Function to update the environment to the current state and time.
Private Member Functions
void setIntegratedStatesInEnvironment (const std::unordered_map< IntegratedStateType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > &integratedStatesToSet)
Function to set numerically integrated states in environment.
void setStatesFromEnvironment (const std::vector< IntegratedStateType > &statesToSet, const TimeType currentTime)
Function to explicitly use existing environment models to update current states of integrated bodies.
void setUpdateFunctionOrder (const int iterationNumber=0)
Function to set the order in which the updateFunctionVector_ is to be updated.
void setUpdateFunctions (const std::map< EnvironmentModelsToUpdate, std::vector< std::string > > &updateSettings)
Function to set the update functions for the environment from the required update settings.
Private Attributes
simulation_setup::NamedBodyMap bodyList_
List of body objects, this list encompasses all environment object in the simulation.
std::unordered_map< IntegratedStateType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > >::const_iterator integratedStateIterator_
Predefined state history iterator for computational efficiency.
std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > integratedStates_
list of identifiers for the numerically integrated states
std::vector< boost::tuple< EnvironmentModelsToUpdate, std::string, boost::function< void() > > > resetFunctionVector_
std::vector< boost::tuple< EnvironmentModelsToUpdate, std::string, boost::function< void(const double) > > > updateFunctionVector_
List of time-dependent functions to call to update the environment.
Detailed Description
template<typename StateScalarType, typename TimeType>
class tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >
Class used to update the environment during numerical integration. The class ensures that the current state of the numerical integration is properly set, and that all the environment models that are used during the numerical integration are updated to the current time and state in the correct order.
Definition at line 44 of file environmentUpdater.h.
Constructor & Destructor Documentation
template<typename StateScalarType , typename TimeType > tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::EnvironmentUpdater (const simulation_setup::NamedBodyMap & bodyList, const std::map< EnvironmentModelsToUpdate, std::vector< std::string > > & updateSettings, const std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > & integratedStates = (std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > >())) inline
Constructor, provides the required settings for updating the environment.
Parameters
bodyList List of body objects, this list encompasses all environment object in the simulation.
updateSettings List of updates of the environment models that are required. The list defines per model type (key) the bodies for which this environment model should be updated (values)
integratedStates This map provides the list of identifiers for the numerically integrated states. The type of integrated state (key) is defined for each reference (value). Note that for the numerical integration of translational motion, the entry in the pair will have a second entry that is empty (""), with the first entry defining the body that is integrated.
Definition at line 62 of file environmentUpdater.h.
References tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions().
Member Function Documentation
template<typename StateScalarType , typename TimeType > void tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateEnvironment (const TimeType currentTime, const std::unordered_map< IntegratedStateType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & integratedStatesToSet, const std::vector< IntegratedStateType > & setIntegratedStatesFromEnvironment = std::vector< IntegratedStateType >()) inline
Function to update the environment to the current state and time. This function calls the dependent variable functions set by the setUpdateFunctions function. By default, the numerically integrated states are set in the environment first. This may be overridden by using the setIntegratedStatesFromEnvironment variable, which forces the function to ignore specific integrated states and update them from the existing environment models instead.
Parameters
currentTime Current time.
integratedStatesToSet Current list of integrated states, with specific integrated states defined by integratedStates_ member variable. Note that these states must have been converted to the global state before input to this function, as is done by the convertCurrentStateToGlobalRepresentationPerType function of the DynamicsStateDerivativeModel.
setIntegratedStatesFromEnvironment Integrated state types which are not to be used for updating the environment, but which are to be set from existing environment models instead.
Definition at line 91 of file environmentUpdater.h.
References tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::integratedStates_, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::resetFunctionVector_, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setIntegratedStatesInEnvironment(), tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setStatesFromEnvironment(), and tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateFunctionVector_.
template<typename StateScalarType , typename TimeType > void tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setIntegratedStatesInEnvironment (const std::unordered_map< IntegratedStateType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > & integratedStatesToSet) inline private
Function to set numerically integrated states in environment. Note that these states must have been converted to the global state before input to this function, as is done by the convertCurrentStateToGlobalRepresentationPerType function of the DynamicsStateDerivativeModel.
Parameters
integratedStatesToSet Integrated states which are to be set in environment.
Definition at line 136 of file environmentUpdater.h.
References tudat::propagators::body_mass_state, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::bodyList_, tudat::propagators::custom_state, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::integratedStateIterator_, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::integratedStates_, tudat::propagators::rotational_state, and tudat::propagators::transational_state.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateEnvironment().
template<typename StateScalarType , typename TimeType > void tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setStatesFromEnvironment (const std::vector< IntegratedStateType > & statesToSet, const TimeType currentTime) inline private
Function to explicitly use existing environment models to update current states of integrated bodies, overriding the numerically integrated states.
Parameters
statesToSet Integrated state types which are not to be used for updating the environment, but which are to be set from existing environment models instead.
currentTime Time to which environment is to be updated.
Definition at line 200 of file environmentUpdater.h.
References tudat::propagators::body_mass_state, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::bodyList_, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::integratedStates_, tudat::propagators::rotational_state, and tudat::propagators::transational_state.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateEnvironment().
template<typename StateScalarType , typename TimeType > void tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctionOrder (const int iterationNumber = 0) inline private
Function to set the order in which the updateFunctionVector_ is to be updated. Order is determined recursively in this function, the variable iterationNumber keeps track of the number of nested calls to the function.
Parameters
iterationNumber Number of subsequent calls to this funtion
Definition at line 259 of file environmentUpdater.h.
References tudat::propagators::body_rotational_state_update, tudat::propagators::body_transational_state_update, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::bodyList_, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateFunctionVector_, and tudat::propagators::vehicle_flight_conditions_update.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions().
template<typename StateScalarType , typename TimeType > void tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions (const std::map< EnvironmentModelsToUpdate, std::vector< std::string > > & updateSettings) inline private
Function to set the update functions for the environment from the required update settings.
Parameters
updateSettings Settings for the environment updates.
Definition at line 397 of file environmentUpdater.h.
References tudat::propagators::body_mass_state, tudat::propagators::body_mass_update, tudat::propagators::body_rotational_state_update, tudat::propagators::body_transational_state_update, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::bodyList_, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::integratedStates_, tudat::propagators::radiation_pressure_interface_update, tudat::simulation_setup::Body::recomputeStateOnNextCall(), tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::resetFunctionVector_, tudat::propagators::rotational_state, tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctionOrder(), tudat::propagators::spherical_harmonic_gravity_field_update, tudat::propagators::transational_state, TUDAT_NAN, tudat::aerodynamics::FlightConditions::updateConditions(), tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateFunctionVector_, tudat::simulation_setup::Body::updateMass(), and tudat::propagators::vehicle_flight_conditions_update.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::EnvironmentUpdater().
Member Data Documentation
template<typename StateScalarType , typename TimeType > simulation_setup::NamedBodyMap tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::bodyList_ private
Definition at line 664 of file environmentUpdater.h.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setIntegratedStatesInEnvironment(), tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setStatesFromEnvironment(), tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctionOrder(), and tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions().
template<typename StateScalarType , typename TimeType > std::map< IntegratedStateType, std::vector< std::pair< std::string, std::string > > > tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::integratedStates_ private
This map provides the list of identifiers for the numerically integrated states. The type of integrated state (key) is defined for each reference (value). Note that for the numerical integration of translational motion, the entry in the pair will have a second entry that is empty (""), with the first entry defining the body that is integrated.
Definition at line 676 of file environmentUpdater.h.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setIntegratedStatesInEnvironment(), tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setStatesFromEnvironment(), tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions(), and tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateEnvironment().
template<typename StateScalarType , typename TimeType > std::vector< boost::tuple< EnvironmentModelsToUpdate, std::string, boost::function< void(const double) > > > tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateFunctionVector_ private
Definition at line 680 of file environmentUpdater.h.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctionOrder(), tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions(), and tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateEnvironment().
template<typename StateScalarType , typename TimeType > std::vector< boost::tuple< EnvironmentModelsToUpdate, std::string, boost::function< void() > > > tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::resetFunctionVector_ private
List of time-dependent functions to call to reset the time of the environment (to NaN signal recomputation for next time step).
Definition at line 684 of file environmentUpdater.h.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setUpdateFunctions(), and tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::updateEnvironment().
template<typename StateScalarType , typename TimeType > std::unordered_map< IntegratedStateType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > >::const_iterator tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::integratedStateIterator_ private
Definition at line 691 of file environmentUpdater.h.
Referenced by tudat::propagators::EnvironmentUpdater< StateScalarType, TimeType >::setIntegratedStatesInEnvironment().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/environmentUpdater.h