Tudat: tudat::acceleration_partials::SphericalHarmonicsGravityPartial Class Reference
tudat::acceleration_partials::SphericalHarmonicsGravityPartial Class Reference
Class for calculating partial derivatives of a spherical harmonic gravitational acceleration.
#include <sphericalHarmonicAccelerationPartial.h>
Public Member Functions
SphericalHarmonicsGravityPartial (const std::string &acceleratedBody, const std::string &acceleratingBody, const std::shared_ptr< gravitation::SphericalHarmonicsGravitationalAccelerationModel > accelerationModel, const observation_partials::RotationMatrixPartialNamedList &rotationMatrixPartials=observation_partials::RotationMatrixPartialNamedList(), const std::vector< std::shared_ptr< orbit_determination::TidalLoveNumberPartialInterface > > &tidalLoveNumberPartialInterfaces=std::vector< std::shared_ptr< orbit_determination::TidalLoveNumberPartialInterface > >())
Contructor.
~SphericalHarmonicsGravityPartial ()
Destructor.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getGravitationalParameterPartialFunction (const estimatable_parameters::EstimatebleParameterIdentifier &parameterId)
Function to create a function returning the current partial w.r.t. a gravitational parameter.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter.
std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter.
bool isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the acceleration is dependent on a non-translational integrated state.
virtual void update (const double currentTime=TUDAT_NAN)
Function for updating the partial object to current state and time.
void wrtGravitationalParameterOfCentralBody (Eigen::MatrixXd &partialMatrix, const int addPartial=0)
Function to calculate the partial wrt the gravitational parameter.
void wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration..
void wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of body exerting acceleration.
Public Member Functions inherited from tudat::acceleration_partials::AccelerationPartial
AccelerationPartial (const std::string &acceleratedBody, const std::string &acceleratingBody, const basic_astrodynamics::AvailableAcceleration accelerationType)
Base class constructor.
virtual ~AccelerationPartial ()
Virtual destructor.
std::string getAcceleratedBody ()
Function to retrieve the name of the body undergoing acceleration.
std::string getAcceleratingBody ()
Function to retrieve the name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration getAccelerationType ()
Function to retrieve the type of acceleration w.r.t. which partial is taken..
std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
virtual bool isAccelerationPartialWrtAdditionalBodyNonnullptr (const std::string &bodyName)
Function to check whether the partial derivative w.r.t. the translational state of a third body is non-zero.
virtual bool isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for determining if the acceleration is dependent on a non-translational integrated state (default none).
bool isStateDerivativeDependentOnIntegratedState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function to check whether a partial w.r.t. some integrated state is non-zero.
virtual void wrtNonTranslationalStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)
Function for calculating the partial of the acceleration w.r.t. a non-translational integrated state.
virtual void wrtPositionOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=0)
Function for calculating the partial of the acceleration w.r.t. the position of the third body.
void wrtStateOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body undergoing acceleration.
void wrtStateOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the body exerting acceleration.
void wrtStateOfAdditionalBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const std::string &bodyName)
Function for calculating the partial of the acceleration w.r.t. the Cartesian state of the third body.
virtual void wrtVelocityOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the accelerated body.
virtual void wrtVelocityOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the body exerting acceleration.
virtual void wrtVelocityOfAdditionalBody (const std::string &bodyName, Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution=1, const int startRow=0, const int startColumn=3)
Function for calculating the partial of the acceleration w.r.t. the velocity of the third body.
Public Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Protected Member Functions
void resetTimeOfMemberObjects ()
Function to reset the relevant member objects to the current time.
void updateParameterPartialsOfMemberObjects ()
Function to update the parameter partials of the relevant member objects to the current time.
void wrtCosineCoefficientBlock (const std::vector< std::pair< int, int > > &blockIndices, Eigen::MatrixXd &partialDerivatives)
Function to calculate the partial of the acceleration wrt a set of cosine coefficients.
void wrtRotationModelParameter (Eigen::MatrixXd &accelerationPartial, const estimatable_parameters::EstimatebleParametersEnum parameterType, const std::string &secondaryIdentifier)
Function to calculate an acceleration partial wrt a rotational parameter.
void wrtSineCoefficientBlock (const std::vector< std::pair< int, int > > &blockIndices, Eigen::MatrixXd &partialDerivatives)
Function to calculate the partial of the acceleration wrt a set of sine coefficients.
void wrtTidalModelParameter (const std::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >() > coefficientPartialFunctions, const int degree, const std::vector< int > &orders, const bool sumOrders, const int parameterSize, Eigen::MatrixXd &accelerationPartial)
Function to calculate an acceleration partial wrt a tidal parameter.
Protected Member Functions inherited from tudat::orbit_determination::StateDerivativePartial
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
Protected Attributes
std::function< Eigen::Matrix< double, 3, 1 >) > accelerationFunction_
Function to retrieve the current spherical harmonic acceleration.
bool accelerationUsesMutualAttraction_
Boolean denoting whether the mutual attraction between the bodies is taken into account.
Eigen::Vector3d bodyFixedPosition_
Current body-fixed (w.r.t body exerting acceleration) position of body undergoing acceleration.
Eigen::Vector3d bodyFixedSphericalPosition_
Current spherical coordinate of body undergoing acceleration.
std::function< double() > bodyReferenceRadius_
Function to return the reference radius used for calculating the acceleration.
std::function< Eigen::MatrixXd() > cosineCoefficients_
Function to return the current cosine coefficients of the spherical harmonic gravity field.
Eigen::Matrix3d currentBodyFixedPartialWrtPosition_
The current partial of the acceleration wrt the position of the body undergoing the acceleration.
Eigen::MatrixXd currentCosineCoefficients_
Current cosine coefficients of the spherical harmonic gravity field.
Eigen::Matrix3d currentPartialWrtPosition_
The current partial of the acceleration wrt the position of the body undergoing the acceleration.
Eigen::Matrix3d currentPartialWrtVelocity_
The current partial of the acceleration wrt the velocity of the body undergoing the acceleration.
Eigen::MatrixXd currentSineCoefficients_
Current sine coefficients of the spherical harmonic gravity field.
std::function< Eigen::Matrix3d() > fromBodyFixedToIntegrationFrameRotation_
Function return current rotation from inertial frame to frame fixed to body exerting acceleration.
std::function< double() > gravitationalParameterFunction_
Function to return the gravitational parameter used for calculating the acceleration.
int maximumDegree_
Maximum degree of spherical harmonic expansion.
int maximumOrder_
Maximum order of spherical harmonic expansion.
std::function< Eigen::Vector3d() > positionFunctionOfAcceleratedBody_
Function returning position of body undergoing acceleration.
std::function< Eigen::Vector3d() > positionFunctionOfAcceleratingBody_
Function returning position of body exerting acceleration.
observation_partials::RotationMatrixPartialNamedList rotationMatrixPartials_
Map of RotationMatrixPartial, one for each relevant rotation parameter.
std::function< Eigen::MatrixXd() > sineCoefficients_
Function to return the current sine coefficients of the spherical harmonic gravity field.
std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > sphericalHarmonicCache_
std::vector< std::shared_ptr< orbit_determination::TidalLoveNumberPartialInterface > > tidalLoveNumberPartialInterfaces_
List of objects to compute partials of tidal gravity field variations.
std::function< void(const double) > updateFunction_
Function to update the acceleration to the current state and time.
Protected Attributes inherited from tudat::acceleration_partials::AccelerationPartial
std::string acceleratedBody_
Name of the body undergoing acceleration.
std::string acceleratingBody_
Name of the body exerting acceleration.
basic_astrodynamics::AvailableAcceleration accelerationType_
Type of acceleration w.r.t. which partial is taken..
Protected Attributes inherited from tudat::orbit_determination::StateDerivativePartial
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Class for calculating partial derivatives of a spherical harmonic gravitational acceleration, as calculated by the SphericalHarmonicsGravitationalAccelerationModel class.
Definition at line 38 of file sphericalHarmonicAccelerationPartial.h.
Constructor & Destructor Documentation
SphericalHarmonicsGravityPartial()
tudat::acceleration_partials::SphericalHarmonicsGravityPartial::SphericalHarmonicsGravityPartial (const std::string & acceleratedBody, const std::string & acceleratingBody, const std::shared_ptr< gravitation::SphericalHarmonicsGravitationalAccelerationModel > accelerationModel, const observation_partials::RotationMatrixPartialNamedList & rotationMatrixPartials = observation_partials::RotationMatrixPartialNamedList(), const std::vector< std::shared_ptr< orbit_determination::TidalLoveNumberPartialInterface > > & tidalLoveNumberPartialInterfaces = std::vector< std::shared_ptr< orbit_determination::TidalLoveNumberPartialInterface > >())
Constructor, requires input on the acceleration model as of which partials are to be computed. If any partials of parameters of the rotation model of the body exerting acceleration are to be calculated, RotationMatrixPartial objects must be pre-constructed and passed here as a map, with one object for each parameter wrt which a partial is to be taken.
Parameters
acceleratedBody Name of body undergoing acceleration.
acceleratingBody Name of body exerting acceleration.
accelerationModel Spherical harmonic gravity acceleration model from which acceleration is calculated wrt which the object being constructed is to calculate partials.
rotationMatrixPartials Map of RotationMatrixPartial, one for each paramater representing a property of the rotation of the body exerting the acceleration wrt which an acceleration partial will be calculated.
tidalLoveNumberPartialInterfaces List of objects to compute partials of tidal gravity field variations, one per corresponding variation object in acceleratedBody.
Definition at line 25 of file sphericalHarmonicAccelerationPartial.cpp.
References cosineCoefficients_, maximumDegree_, maximumOrder_, sineCoefficients_, and sphericalHarmonicCache_.
~SphericalHarmonicsGravityPartial()
tudat::acceleration_partials::SphericalHarmonicsGravityPartial::~SphericalHarmonicsGravityPartial () inline
Definition at line 68 of file sphericalHarmonicAccelerationPartial.h.
Member Function Documentation
wrtPositionOfAcceleratedBody()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtPositionOfAcceleratedBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body undergoing acceleration and adding it to the existing partial block Update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body undergoing acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 81 of file sphericalHarmonicAccelerationPartial.h.
References currentPartialWrtPosition_.
wrtPositionOfAcceleratingBody()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtPositionOfAcceleratingBody (Eigen::Block< Eigen::MatrixXd > partialMatrix, const bool addContribution = 1, const int startRow = 0, const int startColumn = 0) inline virtual
Function for calculating the partial of the acceleration w.r.t. the position of body exerting acceleration and adding it to the existing partial block. The update() function must have been called during current time step before calling this function.
Parameters
partialMatrix Block of partial derivatives of acceleration w.r.t. Cartesian position of body exerting acceleration where current partial is to be added.
addContribution Variable denoting whether to return the partial itself (true) or the negative partial (false).
startRow First row in partialMatrix block where the computed partial is to be added.
startColumn First column in partialMatrix block where the computed partial is to be added.
Implements tudat::acceleration_partials::AccelerationPartial.
Definition at line 106 of file sphericalHarmonicAccelerationPartial.h.
References currentPartialWrtPosition_.
isStateDerivativeDependentOnIntegratedNonTranslationalState()
bool tudat::acceleration_partials::SphericalHarmonicsGravityPartial::isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) inline
Function for determining if the acceleration is dependent on a non-translational integrated state. No dependency is implemented, but a warning is provided if partial w.r.t. mass of body exerting acceleration (and undergoing acceleration if mutual attraction is used) is requested.
Parameters
stateReferencePoint Reference point id of propagated state
integratedStateType Type of propagated state for which dependency is to be determined.
Returns
True if dependency exists (non-zero partial), false otherwise.
Definition at line 128 of file sphericalHarmonicAccelerationPartial.h.
References tudat::acceleration_partials::AccelerationPartial::acceleratedBody_, tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, accelerationUsesMutualAttraction_, and tudat::propagators::body_mass_state.
getParameterPartialFunction() [1/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) virtual
Function to create a function returning a partial w.r.t. a double parameter.
Function for setting up and retrieving a function returning a partial w.r.t. a double parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency, 1 otherwise).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 68 of file sphericalHarmonicAccelerationPartial.cpp.
References tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, tudat::orbit_determination::TidalLoveNumberPartialInterface::getCurrentDoubleParameterPartial(), getGravitationalParameterPartialFunction(), tudat::estimatable_parameters::gravitational_parameter, tudat::estimatable_parameters::isParameterRotationMatrixProperty(), tudat::estimatable_parameters::isParameterTidalProperty(), maximumDegree_, maximumOrder_, rotationMatrixPartials_, tidalLoveNumberPartialInterfaces_, wrtRotationModelParameter(), and wrtTidalModelParameter().
getParameterPartialFunction() [2/2]
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) virtual
Function to create a function returning a partial w.r.t. a vector parameter.
Function for setting up and retrieving a function returning a partial w.r.t. a vector parameter. Function returns empty function and zero size indicator for parameters with no dependency for current acceleration.
Parameters
parameter Parameter w.r.t. which partial is to be taken.
Returns
Pair of parameter partial function and number of columns in partial (0 for no dependency).
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 162 of file sphericalHarmonicAccelerationPartial.cpp.
References tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, tudat::orbit_determination::TidalLoveNumberPartialInterface::getCurrentVectorParameterPartial(), tudat::estimatable_parameters::SphericalHarmonicsSineCoefficients::getParameterSize(), tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::getParameterSize(), tudat::estimatable_parameters::isParameterRotationMatrixProperty(), tudat::estimatable_parameters::isParameterTidalProperty(), maximumDegree_, maximumOrder_, rotationMatrixPartials_, tudat::estimatable_parameters::spherical_harmonics_cosine_coefficient_block, tudat::estimatable_parameters::spherical_harmonics_sine_coefficient_block, tidalLoveNumberPartialInterfaces_, wrtCosineCoefficientBlock(), wrtRotationModelParameter(), wrtSineCoefficientBlock(), and wrtTidalModelParameter().
getGravitationalParameterPartialFunction()
std::pair< std::function< void(Eigen::MatrixXd &) >, int > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getGravitationalParameterPartialFunction (const estimatable_parameters::EstimatebleParameterIdentifier & parameterId)
Function to create a function returning the current partial w.r.t. a gravitational parameter.
Parameters
parameterId Identifier of parameter for which the partial is to be created.
Returns
Pair with partial function and paramater partial size. The partial function is non-empty only if the parameterId input represents the gravitational parameter of acceleratingBody_ (or acceleratedBody_ if accelerationUsesMutualAttraction_ is true).
Definition at line 283 of file sphericalHarmonicAccelerationPartial.cpp.
References tudat::acceleration_partials::AccelerationPartial::acceleratedBody_, tudat::acceleration_partials::AccelerationPartial::acceleratingBody_, accelerationUsesMutualAttraction_, tudat::estimatable_parameters::gravitational_parameter, and wrtGravitationalParameterOfCentralBody().
Referenced by getParameterPartialFunction().
update()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::update (const double currentTime = TUDAT_NAN) virtual
Function for updating the partial object to current state and time. Calculates the variables that are used for the calculation of multple partials, to prevent multiple calculations of same function.
Parameters
currentTime Time to which object is to be updated (note that most update functions are time-independent, since the 'current' state of the bodies is typically updated globally by the NBodyStateDerivative class).
Implements tudat::orbit_determination::StateDerivativePartial.
Definition at line 314 of file sphericalHarmonicAccelerationPartial.cpp.
References bodyFixedPosition_, bodyFixedSphericalPosition_, bodyReferenceRadius_, tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), tudat::coordinate_conversions::convertCartesianToSpherical(), cosineCoefficients_, currentBodyFixedPartialWrtPosition_, currentCosineCoefficients_, currentPartialWrtPosition_, currentPartialWrtVelocity_, currentSineCoefficients_, tudat::orbit_determination::StateDerivativePartial::currentTime_, fromBodyFixedToIntegrationFrameRotation_, gravitationalParameterFunction_, tudat::mathematical_constants::PI, positionFunctionOfAcceleratedBody_, positionFunctionOfAcceleratingBody_, sineCoefficients_, sphericalHarmonicCache_, tidalLoveNumberPartialInterfaces_, and updateFunction_.
wrtGravitationalParameterOfCentralBody()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtGravitationalParameterOfCentralBody (Eigen::MatrixXd & partialMatrix, const int addPartial = 0) inline
Function to calculate the partial wrt the gravitational parameter of the central body. Note that in the case of mutual attraction (see SphericalHarmonicsGravitationalAccelerationModel), the partial wrt the gravitational parameter of the body exerting acceleration is equal to the partial wrt to the body undergoing the acceleration, which is zero otherwise.
Returns
Partial wrt the gravitational parameter of the central body.
Definition at line 189 of file sphericalHarmonicAccelerationPartial.h.
References accelerationFunction_, and gravitationalParameterFunction_.
Referenced by getGravitationalParameterPartialFunction().
resetTimeOfMemberObjects()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::resetTimeOfMemberObjects () inline protected virtual
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 219 of file sphericalHarmonicAccelerationPartial.h.
References tudat::orbit_determination::StateDerivativePartial::currentTime_, and tidalLoveNumberPartialInterfaces_.
updateParameterPartialsOfMemberObjects()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::updateParameterPartialsOfMemberObjects () inline protected virtual
Reimplemented from tudat::orbit_determination::StateDerivativePartial.
Definition at line 228 of file sphericalHarmonicAccelerationPartial.h.
References tidalLoveNumberPartialInterfaces_.
wrtCosineCoefficientBlock()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtCosineCoefficientBlock (const std::vector< std::pair< int, int > > & blockIndices, Eigen::MatrixXd & partialDerivatives) protected
Function to calculate the partial of the acceleration wrt a set of cosine coefficients. The set of coefficients wrt which a partial is to be taken is provided as input.
Parameters
blockIndices List of cosine coefficient indices wrt which the partials are to be taken (first and second are degree and order for each vector entry).
partialDerivatives Matrix of acceleration partials that is set by this function (returned by reference), with each column containg the partial wrt a single coefficient (in same order as blockIndices).
Definition at line 362 of file sphericalHarmonicAccelerationPartial.cpp.
References bodyFixedPosition_, bodyFixedSphericalPosition_, bodyReferenceRadius_, tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtCCoefficients(), fromBodyFixedToIntegrationFrameRotation_, tudat::coordinate_conversions::getSphericalToCartesianGradientMatrix(), gravitationalParameterFunction_, and sphericalHarmonicCache_.
Referenced by getParameterPartialFunction().
wrtSineCoefficientBlock()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtSineCoefficientBlock (const std::vector< std::pair< int, int > > & blockIndices, Eigen::MatrixXd & partialDerivatives) protected
Function to calculate the partial of the acceleration wrt a set of sine coefficients. The set of coefficients wrt which a partial is to be taken is provided as input.
Parameters
blockIndices List of sine coefficient indices wrt which the partials are to be taken (first and second are degree and order for each vector entry).
partialDerivatives Matrix of acceleration partials that is set by this function (returned by reference), with each column containg the partial wrt a single coefficient (in same order as blockIndices).
Definition at line 374 of file sphericalHarmonicAccelerationPartial.cpp.
References bodyFixedPosition_, bodyFixedSphericalPosition_, bodyReferenceRadius_, tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtSCoefficients(), fromBodyFixedToIntegrationFrameRotation_, tudat::coordinate_conversions::getSphericalToCartesianGradientMatrix(), gravitationalParameterFunction_, and sphericalHarmonicCache_.
Referenced by getParameterPartialFunction().
wrtRotationModelParameter()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtRotationModelParameter (Eigen::MatrixXd & accelerationPartial, const estimatable_parameters::EstimatebleParametersEnum parameterType, const std::string & secondaryIdentifier) protected
Function to calculate an acceleration partial wrt a rotational parameter of the rotation model of the body exerting the acceleration.
Parameters
accelerationPartial Matrix of partials of spherical harmonic acceleration wrt a rotational parameter that is set by this function (returned by reference)
parameterType Type of parameter wrt which a partial is to be calculated. An entry of the requested type must be present in the rotationMatrixPartials_ map.
secondaryIdentifier Identifier required to unambiguously define the parameter (in addition to information in parameterType.
Definition at line 386 of file sphericalHarmonicAccelerationPartial.cpp.
References accelerationFunction_, currentBodyFixedPartialWrtPosition_, tudat::orbit_determination::StateDerivativePartial::currentTime_, fromBodyFixedToIntegrationFrameRotation_, positionFunctionOfAcceleratedBody_, positionFunctionOfAcceleratingBody_, and rotationMatrixPartials_.
Referenced by getParameterPartialFunction().
wrtTidalModelParameter()
void tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtTidalModelParameter (const std::function< std::vector< Eigen::Matrix< double, 2, Eigen::Dynamic > >() > coefficientPartialFunctions, const int degree, const std::vector< int > & orders, const bool sumOrders, const int parameterSize, Eigen::MatrixXd & accelerationPartial) protected
Function to calculate an acceleration partial wrt a tidal parameter of the gravitu field of the body exerting the acceleration.
Parameters
coefficientPartialFunctions Function returning a list of partial derivatives of C,S spherical harmonic coefficients with the degree and order determined by corresponding input arguments of this function. Degree is fixed, and this vector order corresponds to order of 'orders' input parameter (one vector entry per order). Matrix rows denote C and S coefficient, respectively. Columns denote entries of tidal property (e.g. first entry for real Love number component, second for complex part)
degree Degree of property (e.g. Love number) w.r.t. which partials are to be computed
orders Orders of property (e.g. Love number) w.r.t. which partials are to be computed
sumOrders True of the contributions of the various orders are to be summed (i.e. assumed to be constant for all orders at given degree), or if they are handled separately
parameterSize Size of the parameter w.r.t. which the partials are to be computed
accelerationPartial Matrix of partials of spherical harmonic acceleration wrt a tidal parameter (returned by reference)
Definition at line 411 of file sphericalHarmonicAccelerationPartial.cpp.
References bodyFixedPosition_, bodyFixedSphericalPosition_, bodyReferenceRadius_, tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtCCoefficients(), tudat::acceleration_partials::calculateSphericalHarmonicGravityWrtSCoefficients(), fromBodyFixedToIntegrationFrameRotation_, tudat::coordinate_conversions::getSphericalToCartesianGradientMatrix(), gravitationalParameterFunction_, and sphericalHarmonicCache_.
Referenced by getParameterPartialFunction().
Member Data Documentation
gravitationalParameterFunction_
std::function< double() > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::gravitationalParameterFunction_ protected
Definition at line 304 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), wrtCosineCoefficientBlock(), wrtGravitationalParameterOfCentralBody(), wrtSineCoefficientBlock(), and wrtTidalModelParameter().
bodyReferenceRadius_
std::function< double() > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::bodyReferenceRadius_ protected
Definition at line 307 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), wrtCosineCoefficientBlock(), wrtSineCoefficientBlock(), and wrtTidalModelParameter().
cosineCoefficients_
std::function< Eigen::MatrixXd() > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::cosineCoefficients_ protected
Definition at line 310 of file sphericalHarmonicAccelerationPartial.h.
Referenced by SphericalHarmonicsGravityPartial(), and update().
sineCoefficients_
std::function< Eigen::MatrixXd() > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::sineCoefficients_ protected
Definition at line 313 of file sphericalHarmonicAccelerationPartial.h.
Referenced by SphericalHarmonicsGravityPartial(), and update().
sphericalHarmonicCache_
std::shared_ptr< basic_mathematics::SphericalHarmonicsCache > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::sphericalHarmonicCache_ protected
Cache object used for storing calculated values at current time and state for spherical harmonic gravity calculations.
Definition at line 317 of file sphericalHarmonicAccelerationPartial.h.
Referenced by SphericalHarmonicsGravityPartial(), update(), wrtCosineCoefficientBlock(), wrtSineCoefficientBlock(), and wrtTidalModelParameter().
positionFunctionOfAcceleratedBody_
std::function< Eigen::Vector3d() > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::positionFunctionOfAcceleratedBody_ protected
Definition at line 320 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), and wrtRotationModelParameter().
positionFunctionOfAcceleratingBody_
std::function< Eigen::Vector3d() > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::positionFunctionOfAcceleratingBody_ protected
Definition at line 323 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), and wrtRotationModelParameter().
fromBodyFixedToIntegrationFrameRotation_
std::function< Eigen::Matrix3d() > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::fromBodyFixedToIntegrationFrameRotation_ protected
Definition at line 326 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), wrtCosineCoefficientBlock(), wrtRotationModelParameter(), wrtSineCoefficientBlock(), and wrtTidalModelParameter().
accelerationFunction_
std::function< Eigen::Matrix< double, 3, 1 >) > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::accelerationFunction_ protected
Definition at line 329 of file sphericalHarmonicAccelerationPartial.h.
Referenced by wrtGravitationalParameterOfCentralBody(), and wrtRotationModelParameter().
updateFunction_
std::function< void(const double) > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::updateFunction_ protected
Function to update the acceleration to the current state and time. Called when updating an object of this class with the update(time) function, in case the partial is called before the acceleration model in the current iteration of the numerical integration.
Definition at line 337 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update().
currentCosineCoefficients_
Eigen::MatrixXd tudat::acceleration_partials::SphericalHarmonicsGravityPartial::currentCosineCoefficients_ protected
Current cosine coefficients of the spherical harmonic gravity field, set by update(time) function.
Definition at line 343 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update().
currentSineCoefficients_
Eigen::MatrixXd tudat::acceleration_partials::SphericalHarmonicsGravityPartial::currentSineCoefficients_ protected
Current sine coefficients of the spherical harmonic gravity field, set by update(time) function.
Definition at line 349 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update().
bodyFixedPosition_
Eigen::Vector3d tudat::acceleration_partials::SphericalHarmonicsGravityPartial::bodyFixedPosition_ protected
Current body-fixed (w.r.t body exerting acceleration) position of body undergoing acceleration, set by update(time) function.
Definition at line 356 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), wrtCosineCoefficientBlock(), wrtSineCoefficientBlock(), and wrtTidalModelParameter().
bodyFixedSphericalPosition_
Eigen::Vector3d tudat::acceleration_partials::SphericalHarmonicsGravityPartial::bodyFixedSphericalPosition_ protected
Current spherical coordinate of body undergoing acceleration, in reference frame fixed to body exerting acceleration. Order of components is radial distance (from center of body), latitude, longitude. Note that the the second entry differs from the direct output of the cartesian -> spherical coordinates, which produces a colatitude.
Definition at line 364 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), wrtCosineCoefficientBlock(), wrtSineCoefficientBlock(), and wrtTidalModelParameter().
currentPartialWrtPosition_
Eigen::Matrix3d tudat::acceleration_partials::SphericalHarmonicsGravityPartial::currentPartialWrtPosition_ protected
The current partial of the acceleration wrt the position of the body undergoing the acceleration. The partial wrt the position of the body exerting the acceleration is minus this value. Value is set by the update(time) function.
Definition at line 372 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), wrtPositionOfAcceleratedBody(), and wrtPositionOfAcceleratingBody().
currentBodyFixedPartialWrtPosition_
Eigen::Matrix3d tudat::acceleration_partials::SphericalHarmonicsGravityPartial::currentBodyFixedPartialWrtPosition_ protected
The current partial of the acceleration wrt the position of the body undergoing the acceleration, with both acceleration and position in body-fixed frame.
with both acceleration and position in body-fixed frame. Value is set by the update(time) function.
Definition at line 380 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update(), and wrtRotationModelParameter().
currentPartialWrtVelocity_
Eigen::Matrix3d tudat::acceleration_partials::SphericalHarmonicsGravityPartial::currentPartialWrtVelocity_ protected
The current partial of the acceleration wrt the velocity of the body undergoing the acceleration. The partial wrt the velocity of the body exerting the acceleration is minus this value. Value is set by the update(time) function.
Definition at line 388 of file sphericalHarmonicAccelerationPartial.h.
Referenced by update().
maximumDegree_
int tudat::acceleration_partials::SphericalHarmonicsGravityPartial::maximumDegree_ protected
Maximum degree of spherical harmonic expansion of body exerting acceleration used in the calculation of the acceleration.
Definition at line 395 of file sphericalHarmonicAccelerationPartial.h.
Referenced by getParameterPartialFunction(), and SphericalHarmonicsGravityPartial().
maximumOrder_
int tudat::acceleration_partials::SphericalHarmonicsGravityPartial::maximumOrder_ protected
Maximum order of spherical harmonic expansion of body exerting acceleration used in the calculation of the acceleration.
Definition at line 402 of file sphericalHarmonicAccelerationPartial.h.
Referenced by getParameterPartialFunction(), and SphericalHarmonicsGravityPartial().
rotationMatrixPartials_
observation_partials::RotationMatrixPartialNamedList tudat::acceleration_partials::SphericalHarmonicsGravityPartial::rotationMatrixPartials_ protected
Map of RotationMatrixPartial, one for each parameter representing a property of the rotation of the body exerting the acceleration wrt which an acceleration partial will be calculated. Map is pre-created and set through the constructor.
Definition at line 410 of file sphericalHarmonicAccelerationPartial.h.
Referenced by getParameterPartialFunction(), and wrtRotationModelParameter().
tidalLoveNumberPartialInterfaces_
std::vector< std::shared_ptr< orbit_determination::TidalLoveNumberPartialInterface > > tudat::acceleration_partials::SphericalHarmonicsGravityPartial::tidalLoveNumberPartialInterfaces_ protected
List of objects to compute partials of tidal gravity field variations, one per corresponding variation object in acceleratedBody.
Definition at line 417 of file sphericalHarmonicAccelerationPartial.h.
Referenced by getParameterPartialFunction(), resetTimeOfMemberObjects(), update(), and updateParameterPartialsOfMemberObjects().
accelerationUsesMutualAttraction_
bool tudat::acceleration_partials::SphericalHarmonicsGravityPartial::accelerationUsesMutualAttraction_ protected
Boolean denoting whether the mutual attraction between the bodies is taken into account, as is the case when integrting in a (non-rotating) frame centered on the body exerting the acceleration, in which case the gravitational acceleration of the body undergoing the acceleration on that exerting the acceleration must be taken into account as an inertial effect.
Definition at line 426 of file sphericalHarmonicAccelerationPartial.h.
Referenced by getGravitationalParameterPartialFunction(), and isStateDerivativeDependentOnIntegratedNonTranslationalState().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/AccelerationPartials/sphericalHarmonicAccelerationPartial.h
Astrodynamics/OrbitDetermination/AccelerationPartials/sphericalHarmonicAccelerationPartial.cpp