Tudat: tudat::gravitation::BasicSolidBodyTideGravityFieldVariations Class Reference
tudat::gravitation::BasicSolidBodyTideGravityFieldVariations Class Reference
#include <basicSolidBodyTideGravityFieldVariations.h>
Public Member Functions
BasicSolidBodyTideGravityFieldVariations (const std::function< Eigen::Vector6d(const double) > deformedBodyStateFunction, const std::function< Eigen::Quaterniond(const double) > deformedBodyOrientationFunction, const std::vector< std::function< Eigen::Vector6d(const double) > > deformingBodyStateFunctions, const double deformedBodyReferenceRadius, const std::function< double() > deformedBodyMass, const std::vector< std::function< double() > > deformingBodyMasses, const std::vector< std::vector< std::complex< double > > > loveNumbers, const std::vector< std::string > deformingBodies)
Constructor.
virtual ~BasicSolidBodyTideGravityFieldVariations ()
Destructor.
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > calculateBasicSphericalHarmonicsCorrections (const double time)
Function for calculating basic spherical harmonic coefficient corrections.
virtual std::pair< Eigen::MatrixXd, Eigen::MatrixXd > calculateSphericalHarmonicsCorrections (const double time)
Derived function for calculating spherical harmonic coefficient corrections.
std::string getConcatenatedDeformingBodies ()
Get a string with the concatenation of all the bodies causing the deformation.
Eigen::MatrixXd getCurrentCosineCorrections ()
Function to return the current corrections to the cosine coefficients.
Eigen::MatrixXd getCurrentSineCorrections ()
Function to return the current corrections to the sine coefficients.
std::function< double() > getDeformedBodyMassFunction ()
Function to return the mass function of the deformed body.
std::function< Eigen::Quaterniond(const double) > getDeformedBodyOrientationFunction ()
Function to return the orientation function (rotation to body-fixed frame) of the deformed body.
double getDeformedBodyReferenceRadius ()
Function to return reference radius the spherical harmonic gravity field of deformed body.
std::function< Eigen::Vector6d(const double) > getDeformedBodyStateFunction ()
Function to return the state function of the deformed body.
std::vector< std::string > getDeformingBodies ()
Function to return list of the names of the bodies causing the deformation.
std::vector< std::function< double() > > getDeformingBodyMasses ()
Function to return list of the mass functions of the bodies causing the deformation.
std::vector< std::function< Eigen::Vector6d(const double) > > getDeformingBodyStateFunctions ()
Function to return list of the state functions of the bodies causing the deformation.
std::vector< std::vector< std::complex< double > > > getLoveNumbers ()
Function to return all love numbers.
std::vector< std::complex< double > > getLoveNumbersOfDegree (const int degree)
Function to retrieve the love numbers at given degree.
void resetLoveNumbersOfDegree (const std::vector< std::complex< double > > loveNumbers, const int degree)
Function to reset the love numbers at given degree.
Public Member Functions inherited from tudat::gravitation::GravityFieldVariations
GravityFieldVariations (const int minimumDegree, const int minimumOrder, const int maximumDegree, const int maximumOrder)
Base class constructor.
virtual ~GravityFieldVariations ()
Virtual destructor.
void addSphericalHarmonicsCorrections (const double time, Eigen::MatrixXd &sineCoefficients, Eigen::MatrixXd &cosineCoefficients)
Function to add sine and cosine corrections at given time to coefficient matrices.
Eigen::MatrixXd getLastCosineCorrection ()
Function to retrieve correction to cosine coefficients, as computed by last call to addSphericalHarmonicsCorrections.
Eigen::MatrixXd getLastSineCorrection ()
Function to retrieve correction to sine coefficients, as computed by last call to addSphericalHarmonicsCorrections.
int getMaximumDegree ()
Function to return the maximum degree of the corrections.
int getMaximumOrder ()
Function to return the maximum order of the corrections.
int getMinimumDegree ()
Function to return the minimum degree of the corrections.
int getMinimumOrder ()
Function to return the minimum order of the corrections.
int getNumberOfDegrees ()
Function to return the number of degrees of the corrections.
int getNumberOfOrders ()
Function to return the number of orders of the corrections.
Protected Member Functions
virtual void addBasicSolidBodyTideCorrections (Eigen::MatrixXd &cTermCorrections, Eigen::MatrixXd &sTermCorrections)
Calculates basic solid body gravity field corrections due to single body.
virtual void setBodyGeometryParameters (const int bodyIndex, const double evaluationTime)
Sets current properties (mass state) of body causing tidal deformation.
virtual void updateTidalAmplitudeAndArgument (const int degree, const int order)
Calculate tidal amplitude and argument at current degree and order.
Protected Attributes
std::vector< std::function< void(Eigen::MatrixXd &, Eigen::MatrixXd &) > > correctionFunctions
List of functions to call for calculating spherical harmonic corrections.
Eigen::MatrixXd currentCosineCorrections_
Tidal corrections to cosine coefficients at current calculation step.
Eigen::MatrixXd currentSineCorrections_
Tidal corrections to sine coefficients at current calculation step.
std::function< double() > deformedBodyMass_
Function returning mass of body being deformed.
std::function< Eigen::Quaterniond(const double) > deformedBodyOrientationFunction_
Function providing rotation from inertial to body being deformed-fixed frame.
Eigen::Vector3d deformedBodyPosition
Current position of body being deformed.
double deformedBodyReferenceRadius_
Reference radius (typically equatorial) of body being deformed's spherical harmonic gravity field.
std::function< Eigen::Vector6d(const double) > deformedBodyStateFunction_
Function returning state of body being deformed.
std::vector< std::string > deformingBodies_
List of names of bodies causing deformation.
std::vector< std::function< double() > > deformingBodyMasses_
List of functions returning masses of bodies causing deformation.
std::vector< std::function< Eigen::Vector6d(const double) > > deformingBodyStateFunctions_
List of state functions of body causing deformations.
std::complex< double > iLongitude
Longitude of currently considered body times i in current calculation step.
std::vector< std::vector< std::complex< double > > > loveNumbers_
List of love numbers for each degree and order.
double massRatio
Ratio of masses in current calculation step.
double radiusRatio
Ratio of radii in current calculation step.
double radiusRatioPower
Ratio of radii in current calculation step to the power (degree+1).
double sineOfLatitude
Sine of latitude of currently considered body in current calculation step.
double tideAmplitude
Current amplitude of the tide.
std::complex< double > tideArgument
Current argument of the tide.
Eigen::Quaterniond toDeformedBodyFrameRotation
Current rotation to frame fixed to deformed body.
Protected Attributes inherited from tudat::gravitation::GravityFieldVariations
Eigen::MatrixXd lastCosineCorrection_
Latest correction to cosine coefficients, as computed by last call to addSphericalHarmonicsCorrections.
Eigen::MatrixXd lastSineCorrection_
Latest correction to sine coefficients, as computed by last call to addSphericalHarmonicsCorrections.
int maximumDegree_
Maximum degree of variations.
int maximumOrder_
Maximum order of variations.
int minimumDegree_
Minimum degree of variations.
int minimumOrder_
Minimum order of variations.
int numberOfDegrees_
Number of degrees of variations.
int numberOfOrders_
Number of orders of variations.
Detailed Description
Class to calculate first-order solid body tide gravity field variations on a single body raised by any number of bodies up to any degree and order.
Definition at line 131 of file basicSolidBodyTideGravityFieldVariations.h.
Constructor & Destructor Documentation
BasicSolidBodyTideGravityFieldVariations()
tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::BasicSolidBodyTideGravityFieldVariations (const std::function< Eigen::Vector6d(const double) > deformedBodyStateFunction, const std::function< Eigen::Quaterniond(const double) > deformedBodyOrientationFunction, const std::vector< std::function< Eigen::Vector6d(const double) > > deformingBodyStateFunctions, const double deformedBodyReferenceRadius, const std::function< double() > deformedBodyMass, const std::vector< std::function< double() > > deformingBodyMasses, const std::vector< std::vector< std::complex< double > > > loveNumbers, const std::vector< std::string > deformingBodies) inline
Contructor, sets Love numbers and properties of deformed and tide-raising bodies.
Parameters
deformedBodyStateFunction Function returning state of body being deformed.
deformedBodyOrientationFunction Function providing rotation from inertial to body being deformed-fixed frame
deformingBodyStateFunctions List of state functions of body causing deformations.
deformedBodyReferenceRadius Reference radius (typically equatorial) of body being deformed's spherical harmonic gravity field.
deformedBodyMass Function returning mass (or gravitational parameter) of body being deformed.
deformingBodyMasses List of functions returning masses (or gravitational parameters) of bodies causing deformation.
loveNumbers List of love numbers for each degree and order. First vector level denotes degree (index 0 = degree 2), second vector level denotes order and must be of maximum size (loveNumbers.size() + 2, i.e. maximum degree >= maximum order)
deformingBodies List of names of bodies causing deformation
Definition at line 152 of file basicSolidBodyTideGravityFieldVariations.h.
References addBasicSolidBodyTideCorrections(), correctionFunctions, currentCosineCorrections_, currentSineCorrections_, tudat::gravitation::GravityFieldVariations::maximumDegree_, tudat::gravitation::GravityFieldVariations::maximumOrder_, tudat::gravitation::GravityFieldVariations::minimumDegree_, and tudat::gravitation::GravityFieldVariations::minimumOrder_.
~BasicSolidBodyTideGravityFieldVariations()
virtual tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::~BasicSolidBodyTideGravityFieldVariations () inline virtual
Destructor
Definition at line 189 of file basicSolidBodyTideGravityFieldVariations.h.
Member Function Documentation
calculateBasicSphericalHarmonicsCorrections()
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::calculateBasicSphericalHarmonicsCorrections (const double time)
Function for calculating spherical harmonic coefficient corrections.
Function for calculating basic spherical harmonic coefficient corrections.
Parameters
time Time at which variations are to be calculated.
Returns
Pair of matrices containing variations in (cosine,sine) coefficients.
Definition at line 154 of file basicSolidBodyTideGravityFieldVariations.cpp.
References correctionFunctions, deformedBodyMass_, deformingBodyMasses_, deformingBodyStateFunctions_, massRatio, tudat::gravitation::GravityFieldVariations::numberOfDegrees_, tudat::gravitation::GravityFieldVariations::numberOfOrders_, and setBodyGeometryParameters().
Referenced by calculateSphericalHarmonicsCorrections().
calculateSphericalHarmonicsCorrections()
virtual std::pair< Eigen::MatrixXd, Eigen::MatrixXd > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::calculateSphericalHarmonicsCorrections (const double time) inline virtual
Derived function for calculating spherical harmonic coefficient corrections.
Parameters
time Time at which variations are to be calculated.
Returns
Pair of matrices containing variations in (cosine,sine) coefficients.
Implements tudat::gravitation::GravityFieldVariations.
Definition at line 206 of file basicSolidBodyTideGravityFieldVariations.h.
References calculateBasicSphericalHarmonicsCorrections().
getLoveNumbersOfDegree()
std::vector< std::complex< double > > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getLoveNumbersOfDegree (const int degree) inline
Function to retrieve the love numbers at given degree. Returns a vector containing (complex) love numbers at all orders in current degree.
Parameters
degree Degree from which love numbers are to be retrieved.
Returns
Vector of love numbers (i^{th} entry representing i^{th} order in requested degree) containing love numbers at current degree.
Definition at line 220 of file basicSolidBodyTideGravityFieldVariations.h.
References loveNumbers_.
getLoveNumbers()
std::vector< std::vector< std::complex< double > > > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getLoveNumbers () inline
Function to return all love numbers, i.e. at all degrees and orders.
Returns
Complete set of available love numbers.
Definition at line 230 of file basicSolidBodyTideGravityFieldVariations.h.
References loveNumbers_.
resetLoveNumbersOfDegree()
void tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::resetLoveNumbersOfDegree (const std::vector< std::complex< double > > loveNumbers, const int degree) inline
Function to reset the love numbers at given degree. Input requires a vector containing (complex) love numbers at all orders in current degree.
Parameters
degree Degree from which love numbers are to be retrieved.
loveNumbers Vector of love numbers (i^{th} entry representing i^{th} order in requested degree) containing new love numbers at current degree.
Definition at line 243 of file basicSolidBodyTideGravityFieldVariations.h.
References loveNumbers_.
getDeformedBodyReferenceRadius()
double tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getDeformedBodyReferenceRadius () inline
Function to return reference radius (typically equatorial) the spherical harmonic gravity field of deformed body.
Returns
Reference radius body being deformed's spherical harmonic gravity field.
Definition at line 275 of file basicSolidBodyTideGravityFieldVariations.h.
References deformedBodyReferenceRadius_.
getDeformedBodyMassFunction()
std::function< double() > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getDeformedBodyMassFunction () inline
Function to return the mass function of the deformed body.
Returns
Mass function of the deformed body.
Definition at line 285 of file basicSolidBodyTideGravityFieldVariations.h.
References deformedBodyMass_.
getDeformingBodyMasses()
std::vector< std::function< double() > > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getDeformingBodyMasses () inline
Function to return list of the mass functions of the bodies causing the deformation.
Returns
List of the mass functions of the bodies causing the deformation.
Definition at line 295 of file basicSolidBodyTideGravityFieldVariations.h.
References deformingBodyMasses_.
getDeformingBodies()
std::vector< std::string > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getDeformingBodies () inline
Function to return list of the names of the bodies causing the deformation
Returns
List of the names of the bodies causing the deformation
Definition at line 305 of file basicSolidBodyTideGravityFieldVariations.h.
References deformingBodies_.
getDeformedBodyStateFunction()
std::function< Eigen::Vector6d(const double) > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getDeformedBodyStateFunction () inline
Function to return the state function of the deformed body.
Returns
State function of the deformed body.
Definition at line 315 of file basicSolidBodyTideGravityFieldVariations.h.
References deformedBodyStateFunction_.
getDeformedBodyOrientationFunction()
std::function< Eigen::Quaterniond(const double) > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getDeformedBodyOrientationFunction () inline
Function to return the orientation function (rotation to body-fixed frame) of the deformed body.
Returns
Orientation function (rotation to body-fixed frame) of the deformed body.
Definition at line 327 of file basicSolidBodyTideGravityFieldVariations.h.
References deformedBodyOrientationFunction_.
getDeformingBodyStateFunctions()
std::vector< std::function< Eigen::Vector6d(const double) > > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getDeformingBodyStateFunctions () inline
Function to return list of the state functions of the bodies causing the deformation.
Returns
List of the state functions of the bodies causing the deformation.
Definition at line 338 of file basicSolidBodyTideGravityFieldVariations.h.
References deformingBodyStateFunctions_.
getConcatenatedDeformingBodies()
std::string tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getConcatenatedDeformingBodies () inline
Get a string with the concatenation of all the bodies causing the deformation.
Returns
A string with the concatenation of all the bodies causing the deformation.
Definition at line 348 of file basicSolidBodyTideGravityFieldVariations.h.
References deformingBodies_, and tudat::input_output::field_types::general::id.
getCurrentCosineCorrections()
Eigen::MatrixXd tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getCurrentCosineCorrections () inline
Function to return the current corrections to the cosine coefficients (as calculated by current instance of this class).
Returns
Current corrections to the cosine coefficients.
Definition at line 372 of file basicSolidBodyTideGravityFieldVariations.h.
References currentCosineCorrections_.
getCurrentSineCorrections()
Eigen::MatrixXd tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::getCurrentSineCorrections () inline
Function to return the current corrections to the sine coefficients (as calculated by current instance of this class).
Returns
Current corrections to the sine coefficients.
Definition at line 383 of file basicSolidBodyTideGravityFieldVariations.h.
References currentSineCorrections_.
addBasicSolidBodyTideCorrections()
void tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::addBasicSolidBodyTideCorrections (Eigen::MatrixXd & cTermCorrections, Eigen::MatrixXd & sTermCorrections) protected virtual
Calculates basic solid body gravity field corrections for all degrees and orders set. The arguments are modified as they are passed by reference, through which the corrections are returned. Class variables denoting properties of currently considered body must have been set before this function is called.
Parameters
cTermCorrections Corrections to cosine terms (passed by reference; correction added to input value).
sTermCorrections Corrections to sine terms.
(passed by reference; correction added to input value).
Definition at line 180 of file basicSolidBodyTideGravityFieldVariations.cpp.
References tudat::gravitation::calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude(), currentCosineCorrections_, currentSineCorrections_, loveNumbers_, massRatio, tudat::gravitation::GravityFieldVariations::maximumDegree_, tudat::gravitation::GravityFieldVariations::maximumOrder_, tudat::gravitation::GravityFieldVariations::minimumDegree_, tudat::gravitation::GravityFieldVariations::minimumOrder_, radiusRatio, radiusRatioPower, tideAmplitude, tideArgument, and updateTidalAmplitudeAndArgument().
Referenced by BasicSolidBodyTideGravityFieldVariations().
setBodyGeometryParameters()
void tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::setBodyGeometryParameters (const int bodyIndex, const double evaluationTime) protected virtual
Sets current properties (mass state) of body involved in tidal deformation.
Sets current properties (mass state) of body causing tidal deformation.
Parameters
bodyIndex Index of body causing deformation for which data is to be retrieved. Deformed body is also updated to bodyIndex = 0.
evaluationTime Time at which properties are to be evaluated.
Definition at line 128 of file basicSolidBodyTideGravityFieldVariations.cpp.
References tudat::mathematical_constants::COMPLEX_I, tudat::coordinate_conversions::convertCartesianToSpherical(), deformedBodyOrientationFunction_, deformedBodyPosition, deformedBodyReferenceRadius_, deformedBodyStateFunction_, deformingBodyStateFunctions_, iLongitude, tudat::mathematical_constants::PI, radiusRatio, sineOfLatitude, and toDeformedBodyFrameRotation.
Referenced by calculateBasicSphericalHarmonicsCorrections().
updateTidalAmplitudeAndArgument()
virtual void tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::updateTidalAmplitudeAndArgument (const int degree, const int order) inline protected virtual
Calculate tidal amplitude and argument at current degree and order.
Parameters
degree Degree of tide.
order Order of tide.
Definition at line 431 of file basicSolidBodyTideGravityFieldVariations.h.
References tudat::basic_mathematics::computeLegendrePolynomialExplicit(), iLongitude, sineOfLatitude, tideAmplitude, and tideArgument.
Referenced by addBasicSolidBodyTideCorrections().
Member Data Documentation
correctionFunctions
std::vector< std::function< void(Eigen::MatrixXd&, Eigen::MatrixXd&) > > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::correctionFunctions protected
List of functions to call for calculating spherical harmonic corrections. Each function modifies MatrixXd arguments (cosine, sine) as they are passed by reference, and adds the required (tidal) correction.
Definition at line 397 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by BasicSolidBodyTideGravityFieldVariations(), and calculateBasicSphericalHarmonicsCorrections().
deformedBodyStateFunction_
std::function< Eigen::Vector6d(const double) > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::deformedBodyStateFunction_ protected
Function returning state of body being deformed.
Definition at line 444 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by getDeformedBodyStateFunction(), and setBodyGeometryParameters().
deformedBodyOrientationFunction_
std::function< Eigen::Quaterniond(const double) > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::deformedBodyOrientationFunction_ protected
Function providing rotation from inertial to body being deformed-fixed frame.
Definition at line 450 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by getDeformedBodyOrientationFunction(), and setBodyGeometryParameters().
deformingBodyStateFunctions_
std::vector< std::function< Eigen::Vector6d(const double) > > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::deformingBodyStateFunctions_ protected
List of state functions of body causing deformations.
Definition at line 457 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by calculateBasicSphericalHarmonicsCorrections(), getDeformingBodyStateFunctions(), and setBodyGeometryParameters().
deformedBodyReferenceRadius_
double tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::deformedBodyReferenceRadius_ protected
Reference radius (typically equatorial) of body being deformed's spherical harmonic gravity field.
Definition at line 465 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by getDeformedBodyReferenceRadius(), and setBodyGeometryParameters().
deformedBodyMass_
std::function< double() > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::deformedBodyMass_ protected
Function returning mass of body being deformed.
Definition at line 471 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by calculateBasicSphericalHarmonicsCorrections(), and getDeformedBodyMassFunction().
deformingBodyMasses_
std::vector< std::function< double() > > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::deformingBodyMasses_ protected
List of functions returning masses of bodies causing deformation.
Definition at line 477 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by calculateBasicSphericalHarmonicsCorrections(), and getDeformingBodyMasses().
loveNumbers_
std::vector< std::vector< std::complex< double > > > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::loveNumbers_ protected
List of love numbers for each degree and order. First vector level denotes degree (index 0 = degree 2), second vector level must be of size (loveNumbers.size() + 2, i.e. maximum degree == maximum order.
Definition at line 485 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by addBasicSolidBodyTideCorrections(), getLoveNumbers(), getLoveNumbersOfDegree(), and resetLoveNumbersOfDegree().
deformingBodies_
std::vector< std::string > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::deformingBodies_ protected
List of names of bodies causing deformation.
Definition at line 492 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by getConcatenatedDeformingBodies(), and getDeformingBodies().
massRatio
double tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::massRatio protected
Ratio of masses of body causing deformation to body being deformed in current calculation step.
Definition at line 500 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by addBasicSolidBodyTideCorrections(), and calculateBasicSphericalHarmonicsCorrections().
radiusRatio
double tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::radiusRatio protected
Ratio of equatorial radius of body being deformed over distance between center of body being deformed to center of body causing deformation in current calculation step
Definition at line 507 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by addBasicSolidBodyTideCorrections(), and setBodyGeometryParameters().
radiusRatioPower
double tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::radiusRatioPower protected
Ratio of equatorial radius of body being deformed over distance between center of body being deformed to center of body causing deformation, to the power (degree+1), in current calculation step
Definition at line 515 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by addBasicSolidBodyTideCorrections().
sineOfLatitude
double tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::sineOfLatitude protected
Sine of latitude of body causing deformation in frame fixed to body being deformed in current calculation step.
Definition at line 522 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by setBodyGeometryParameters(), and updateTidalAmplitudeAndArgument().
iLongitude
std::complex< double > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::iLongitude protected
i (sqrt(-1)) times longitude of body causing deformation in frame fixed to body being deformed in current calculation step.
Definition at line 529 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by setBodyGeometryParameters(), and updateTidalAmplitudeAndArgument().
tideArgument
std::complex< double > tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::tideArgument protected
Current argument of the tide, to be used as input to calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude, modulates the tide as exp(-tideArgument).
Definition at line 537 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by addBasicSolidBodyTideCorrections(), and updateTidalAmplitudeAndArgument().
tideAmplitude
double tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::tideAmplitude protected
Current amplitude of the tide, to be used as input to calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude.
Definition at line 544 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by addBasicSolidBodyTideCorrections(), and updateTidalAmplitudeAndArgument().
deformedBodyPosition
Eigen::Vector3d tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::deformedBodyPosition protected
Definition at line 547 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by setBodyGeometryParameters().
toDeformedBodyFrameRotation
Eigen::Quaterniond tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::toDeformedBodyFrameRotation protected
Definition at line 550 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by setBodyGeometryParameters().
currentCosineCorrections_
Eigen::MatrixXd tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::currentCosineCorrections_ protected
Definition at line 553 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by addBasicSolidBodyTideCorrections(), BasicSolidBodyTideGravityFieldVariations(), and getCurrentCosineCorrections().
currentSineCorrections_
Eigen::MatrixXd tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::currentSineCorrections_ protected
Definition at line 556 of file basicSolidBodyTideGravityFieldVariations.h.
Referenced by addBasicSolidBodyTideCorrections(), BasicSolidBodyTideGravityFieldVariations(), and getCurrentSineCorrections().
The documentation for this class was generated from the following files:
Astrodynamics/Gravitation/basicSolidBodyTideGravityFieldVariations.h
Astrodynamics/Gravitation/basicSolidBodyTideGravityFieldVariations.cpp