Tudat: tudat::orbit_determination::StateDerivativePartial Class Reference
tudat::orbit_determination::StateDerivativePartial Class Reference abstract
Base class for computing the partial derivatives of a state derivative model.
#include <stateDerivativePartial.h>
Public Member Functions
StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > &integrationReferencePoint)
Constructor.
virtual ~StateDerivativePartial ()
Destructor.
void getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a double parameter.
void getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix)
Function to retrieve a partial w.r.t. a vector parameter.
void getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd &parameterPartial)
Function to retrieve a partial w.r.t. a vector parameter.
virtual std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)=0
Pure virtual function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
propagators::IntegratedStateType getIntegratedStateType ()
Function to get the type of state for which partials are to be computed.
std::pair< std::string, std::string > getIntegrationReferencePoint ()
Function to get the identifier for body/reference point for which propagation is performed.
virtual std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to retrieve the function that computes (by reference) a given double parameter partial.
virtual std::pair< std::function< void(Eigen::MatrixXd &) >, int > getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to retrieve the function that computes (by reference) a given vector parameter partial.
virtual bool isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > &stateReferencePoint, const propagators::IntegratedStateType integratedStateType)=0
Pure virtual function to check whether a partial w.r.t. some integrated state is non-zero.
void resetTime (const double currentTime=TUDAT_NAN)
Function to reset the object to the current time.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to set a dependency of this partial object w.r.t. a given double parameter.
virtual int setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to set a dependency of this partial object w.r.t. a given vector parameter.
virtual void update (const double currentTime)=0
Pure virtual for updating the common parts of the partial object to current state and time.
void updateParameterPartials ()
Function to update the values partial derivatives to current state and time.
Eigen::MatrixXd wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a double parameter.
Eigen::MatrixXd wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter)
Function to directly compute the partial of the state derivative w.r.t. a vector parameter.
Protected Member Functions
void resetCurrentParameterValues ()
Function to define all current parameter partials as 'not computed'.
virtual void resetTimeOfMemberObjects ()
Function to reset the member object to the current time.
virtual void updateParameterPartialsOfMemberObjects ()
Function to compute parameter partials of member objects.
Protected Attributes
int accelerationSize_
Size of the single order state derivative model (i.e. 3 for translational dynamics).
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > currentDoubleParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
double currentTime_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > currentVectorParameterPartials_
List of current values of partials w.r.t. double parameter values (emptied at beginning of every time step).
propagators::IntegratedStateType integratedStateType_
Type of state for which partials are to be computed.
std::pair< std::string, std::string > integrationReferencePoint_
Identifier for body/reference point for which propagation is performed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > isCurrentDoubleParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator isCurrentDoubleParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current double parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > isCurrentVectorParameterPartialSet_
List of booleans defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator isCurrentVectorParameterPartialSetIterator_
Iterator for list defining whether the partial w.r.t. the current vector parameter (key) has been computed.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterDoublePartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. double parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd &) > > parameterDoublePartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. doule parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > >::iterator parameterVectorPartialFunctionIterator_
Iterator over list of functions to compute values of partials w.r.t. vector parameter partials.
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd &) > > parameterVectorPartialFunctions_
List of functions to compute (return by reference) values of partials w.r.t. vector parameter partials.
Detailed Description
Base class for computing the partial derivatives of a state derivative model (i.e. acceleration model for translational dynamics, torque model for rottional dynamics, etc.). Typically, two levels of derived classes are required: one for the type of dynamics, and one for the type of model (e.g. one level for acceleration model, and one level for central gravitational, spherical harmonic model, etc.).
Definition at line 40 of file stateDerivativePartial.h.
Constructor & Destructor Documentation
StateDerivativePartial()
tudat::orbit_determination::StateDerivativePartial::StateDerivativePartial (const propagators::IntegratedStateType integratedStateType, const std::pair< std::string, std::string > & integrationReferencePoint) inline
Constructor
Parameters
integratedStateType Type of dynamics for which partials are to be computed
integrationReferencePoint Reference point (i.e. propagated body and point) for which the dynamics is propagated. First entry denotes the full body, second entry the reference point on the body that is propagated (empty for translational, rotational dynamics).
Definition at line 53 of file stateDerivativePartial.h.
References accelerationSize_, currentTime_, tudat::propagators::getSingleIntegrationDifferentialEquationOrder(), tudat::propagators::getSingleIntegrationSize(), integratedStateType_, and TUDAT_NAN.
~StateDerivativePartial()
virtual tudat::orbit_determination::StateDerivativePartial::~StateDerivativePartial () inline virtual
Definition at line 63 of file stateDerivativePartial.h.
Member Function Documentation
getDerivativeFunctionWrtStateOfIntegratedBody()
virtual std::pair< std::function< void(Eigen::Block< Eigen::MatrixXd >) >, int > tudat::orbit_determination::StateDerivativePartial::getDerivativeFunctionWrtStateOfIntegratedBody (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) pure virtual
Pure virtual function to retrieve the function that returns the partial derivative w.r.t. a propagated state.
Parameters
stateReferencePoint Reference point (id) for propagated state (i.e. body name for translational dynamics).
integratedStateType Type of propagated state.
Returns
Pair with function, returning partial derivative, and number of columns in partial vector,
Implemented in tudat::acceleration_partials::AccelerationPartial.
isStateDerivativeDependentOnIntegratedNonTranslationalState()
virtual bool tudat::orbit_determination::StateDerivativePartial::isStateDerivativeDependentOnIntegratedNonTranslationalState (const std::pair< std::string, std::string > & stateReferencePoint, const propagators::IntegratedStateType integratedStateType) pure virtual
Pure virtual function to check whether a partial w.r.t. some integrated state is non-zero.
Parameters
stateReferencePoint Reference point (id) for propagated state (i.e. body name for translational dynamics).
integratedStateType Type of propagated state.
Returns
True if dependency exists, false otherwise.
Implemented in tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::AerodynamicAccelerationPartial, tudat::acceleration_partials::CannonBallRadiationPressurePartial, tudat::acceleration_partials::AccelerationPartial, and tudat::acceleration_partials::CentralGravitationPartial.
wrtParameter() [1/2]
Eigen::MatrixXd tudat::orbit_determination::StateDerivativePartial::wrtParameter (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) inline
Function to directly compute the partial of the state derivative w.r.t. a double parameter. NOTE: This function is incldued for testing purposes, and is not to be used during propagation (highly inefficient).
Parameters
parameter Parameter w.r.t. which partial is to be computed
Returns
Partial of state derivative w.r.t. given parameter.
Definition at line 95 of file stateDerivativePartial.h.
References accelerationSize_, getParameterPartialFunction(), tudat::propagators::getSingleIntegrationDifferentialEquationOrder(), tudat::propagators::getSingleIntegrationSize(), and integratedStateType_.
getParameterPartialFunction() [1/2]
virtual std::pair< std::function< void(Eigen::MatrixXd&) >, int > tudat::orbit_determination::StateDerivativePartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) inline virtual
Function to retrieve the function that computes (by reference) a given double parameter partial. NOTE: this function is implemented in this base class with default no dependency. If any double parameter dependencioes exists, this function should be overriden in derived class.
Parameters
parameter Parameter w.r.t. which partial is to be computed
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::AerodynamicAccelerationPartial, tudat::acceleration_partials::CannonBallRadiationPressurePartial, tudat::acceleration_partials::CentralGravitationPartial, tudat::acceleration_partials::SphericalHarmonicsGravityPartial, and tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial.
Definition at line 127 of file stateDerivativePartial.h.
Referenced by setParameterPartialUpdateFunction(), and wrtParameter().
wrtParameter() [2/2]
Eigen::MatrixXd tudat::orbit_determination::StateDerivativePartial::wrtParameter (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) inline
Function to directly compute the partial of the state derivative w.r.t. a vector parameter. NOTE: This function is incldued for testing purposes, and is not to be used during propagation (highly inefficient).
Parameters
parameter Parameter w.r.t. which partial is to be computed
Returns
Partial of state derivative w.r.t. given parameter.
Definition at line 141 of file stateDerivativePartial.h.
References accelerationSize_, getParameterPartialFunction(), tudat::propagators::getSingleIntegrationSize(), and integratedStateType_.
getParameterPartialFunction() [2/2]
virtual std::pair< std::function< void(Eigen::MatrixXd&) >, int > tudat::orbit_determination::StateDerivativePartial::getParameterPartialFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) inline virtual
Function to retrieve the function that computes (by reference) a given vector parameter partial. NOTE: this function is implemented in this base class with default no dependency. If any double parameter dependencioes exists, this function should be overriden in derived class.
Parameters
parameter Parameter w.r.t. which partial is to be computed
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::AerodynamicAccelerationPartial, tudat::acceleration_partials::CannonBallRadiationPressurePartial, tudat::acceleration_partials::CentralGravitationPartial, tudat::acceleration_partials::EmpiricalAccelerationPartial, tudat::acceleration_partials::SphericalHarmonicsGravityPartial, and tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial.
Definition at line 171 of file stateDerivativePartial.h.
update()
virtual void tudat::orbit_determination::StateDerivativePartial::update (const double currentTime) pure virtual
Pure virtual for updating the common parts of the partial object to current state and time. Note that this function is distinct from the updateParameterPartials, which only updates the specific required partial derivatives w.r.t. required parameters. This function computes variables that are always required when the derived class partial is used.
Parameters
currentTime Time to which partials are to be updated.
Implemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::RelativisticAccelerationPartial, tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial, tudat::acceleration_partials::CannonBallRadiationPressurePartial, tudat::acceleration_partials::AerodynamicAccelerationPartial, tudat::acceleration_partials::SphericalHarmonicsGravityPartial, tudat::acceleration_partials::CentralGravitationPartial, tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial, and tudat::acceleration_partials::EmpiricalAccelerationPartial.
getIntegratedStateType()
propagators::IntegratedStateType tudat::orbit_determination::StateDerivativePartial::getIntegratedStateType () inline
Function to get the type of state for which partials are to be computed.
Returns
Type of state for which partials are to be computed.
Definition at line 193 of file stateDerivativePartial.h.
References integratedStateType_.
getIntegrationReferencePoint()
std::pair< std::string, std::string > tudat::orbit_determination::StateDerivativePartial::getIntegrationReferencePoint () inline
Function to get the identifier for body/reference point for which propagation is performed.
Returns
Identifier for body/reference point for which propagation is performed.
Definition at line 203 of file stateDerivativePartial.h.
References integrationReferencePoint_.
resetTime()
void tudat::orbit_determination::StateDerivativePartial::resetTime (const double currentTime = TUDAT_NAN) inline
Function to reset the object to the current time, recomputing partials to current state.
Parameters
currentTime Time to which partials are to be updated.
Definition at line 213 of file stateDerivativePartial.h.
References currentTime_, resetCurrentParameterValues(), and resetTimeOfMemberObjects().
getCurrentParameterPartial() [1/2]
void tudat::orbit_determination::StateDerivativePartial::getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix) inline
Function to retrieve a partial w.r.t. a double parameter. An error is thrown if there is no dependency w.r.t. the requested parameter. A warning is printed if the dependency exists, but has not yet been computed for the current time step.
Parameters
parameter Partial w.r.t. which a parameter is to be computed
partialMatrix Partial of state derivative w.r.t. given parameter (return by 'reference', amking use of Eigen::Block architecture).
Definition at line 235 of file stateDerivativePartial.h.
References currentDoubleParameterPartials_, and parameterDoublePartialFunctions_.
Referenced by tudat::propagators::VariationalEquations::addParameterPartialToList(), getCurrentDoubleParameterPartial(), and getCurrentVectorParameterPartial().
getCurrentDoubleParameterPartial()
void tudat::orbit_determination::StateDerivativePartial::getCurrentDoubleParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter, Eigen::MatrixXd & parameterPartial) inline
Function to retrieve a partial w.r.t. a double parameter. An error is thrown if there is no dependency w.r.t. the requested parameter. A warning is printed if the dependency exists, but has not yet been computed for the current time step.
Parameters
parameter Partial w.r.t. which a parameter is to be computed
parameterPartial Partial of state derivative w.r.t. given parameter (return by reference)
Definition at line 269 of file stateDerivativePartial.h.
References accelerationSize_, and getCurrentParameterPartial().
Referenced by tudat::orbit_determination::getCombinedCurrentDoubleParameterFunction().
getCurrentParameterPartial() [2/2]
void tudat::orbit_determination::StateDerivativePartial::getCurrentParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::Block< Eigen::MatrixXd > partialMatrix) inline
Function to retrieve a partial w.r.t. a vector parameter. An error is thrown if there is no dependency w.r.t. the requested parameter. A warning is printed if the dependency exists, but has not yet been computed for the current time step.
Parameters
parameter Partial w.r.t. which a parameter is to be computed
partialMatrix Partial of state derivative w.r.t. given parameter (return by 'reference', amking use of Eigen::Block architecture).
Definition at line 285 of file stateDerivativePartial.h.
References currentVectorParameterPartials_, and parameterVectorPartialFunctions_.
getCurrentVectorParameterPartial()
void tudat::orbit_determination::StateDerivativePartial::getCurrentVectorParameterPartial (const std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter, Eigen::MatrixXd & parameterPartial) inline
Function to retrieve a partial w.r.t. a vector parameter. An error is thrown if there is no dependency w.r.t. the requested parameter. A warning is printed if the dependency exists, but has not yet been computed for the current time step.
Parameters
parameter Partial w.r.t. which a parameter is to be computed
parameterPartial Partial of state derivative w.r.t. given parameter (return by reference)
Definition at line 317 of file stateDerivativePartial.h.
References accelerationSize_, and getCurrentParameterPartial().
Referenced by tudat::orbit_determination::getCombinedCurrentVectorParameterFunction().
setParameterPartialUpdateFunction() [1/2]
virtual int tudat::orbit_determination::StateDerivativePartial::setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< double > > parameter) inline virtual
Function to set a dependency of this partial object w.r.t. a given double parameter. If a dependency exists, the given partial is recomputed on every call of updateParameterPartials.
Parameters
parameter Partial w.r.t. which dependency is to be checked and set.
Returns
Size (number of columns) of parameter partial. Zero if no dependency, 1 otherwise.
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, and tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial.
Definition at line 332 of file stateDerivativePartial.h.
References accelerationSize_, currentDoubleParameterPartials_, getParameterPartialFunction(), isCurrentDoubleParameterPartialSet_, and parameterDoublePartialFunctions_.
setParameterPartialUpdateFunction() [2/2]
virtual int tudat::orbit_determination::StateDerivativePartial::setParameterPartialUpdateFunction (std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > > parameter) inline virtual
Function to set a dependency of this partial object w.r.t. a given vector parameter. If a dependency exists, the given partial is recomputed on every call of updateParameterPartials.
Parameters
parameter Partial w.r.t. which dependency is to be checked and set.
Returns
Size (number of columns) of parameter partial. Zero if no dependency, size of parameter otherwise.
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, and tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial.
Definition at line 361 of file stateDerivativePartial.h.
References accelerationSize_, currentVectorParameterPartials_, getParameterPartialFunction(), isCurrentVectorParameterPartialSet_, and parameterVectorPartialFunctions_.
updateParameterPartials()
void tudat::orbit_determination::StateDerivativePartial::updateParameterPartials () inline
Function to update the values partial derivatives to current state and time.
Definition at line 388 of file stateDerivativePartial.h.
References currentDoubleParameterPartials_, currentVectorParameterPartials_, isCurrentDoubleParameterPartialSet_, isCurrentVectorParameterPartialSet_, parameterDoublePartialFunctionIterator_, parameterDoublePartialFunctions_, parameterVectorPartialFunctionIterator_, parameterVectorPartialFunctions_, and updateParameterPartialsOfMemberObjects().
updateParameterPartialsOfMemberObjects()
virtual void tudat::orbit_determination::StateDerivativePartial::updateParameterPartialsOfMemberObjects () inline protected virtual
Function to compute parameter partials of member objects. By default (implemented here) no computations are performed. For certain derived classed (i.e. ThirdBodyGravityPartial), there are member StateDerivativePartial objects that need to be updated when calling updateParameterPartials, for which this function should be redefined.
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::SphericalHarmonicsGravityPartial, and tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial.
Definition at line 426 of file stateDerivativePartial.h.
Referenced by updateParameterPartials().
resetTimeOfMemberObjects()
virtual void tudat::orbit_determination::StateDerivativePartial::resetTimeOfMemberObjects () inline protected virtual
Function to reset the member object to the current time. By default (implemented here) no computations are performed. For certain derived classed (i.e. ThirdBodyGravityPartial), there are member StateDerivativePartial objects that need to be updated when calling resetTime, for which this function should be redefined.
Reimplemented in tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >, tudat::acceleration_partials::SphericalHarmonicsGravityPartial, and tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial.
Definition at line 437 of file stateDerivativePartial.h.
Referenced by resetTime().
resetCurrentParameterValues()
void tudat::orbit_determination::StateDerivativePartial::resetCurrentParameterValues () inline protected
Definition at line 443 of file stateDerivativePartial.h.
References isCurrentDoubleParameterPartialSet_, isCurrentDoubleParameterPartialSetIterator_, isCurrentVectorParameterPartialSet_, and isCurrentVectorParameterPartialSetIterator_.
Referenced by resetTime().
Member Data Documentation
integratedStateType_
propagators::IntegratedStateType tudat::orbit_determination::StateDerivativePartial::integratedStateType_ protected
Definition at line 461 of file stateDerivativePartial.h.
Referenced by getIntegratedStateType(), StateDerivativePartial(), and wrtParameter().
accelerationSize_
int tudat::orbit_determination::StateDerivativePartial::accelerationSize_ protected
Definition at line 464 of file stateDerivativePartial.h.
Referenced by getCurrentDoubleParameterPartial(), getCurrentVectorParameterPartial(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), setParameterPartialUpdateFunction(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction(), StateDerivativePartial(), and wrtParameter().
integrationReferencePoint_
std::pair< std::string, std::string > tudat::orbit_determination::StateDerivativePartial::integrationReferencePoint_ protected
Identifier for body/reference point for which propagation is performed. First entry represents the body being propagated. Second entry is empty for propagation of entire bodies (translational, rotational), but must be set for propagation of local dynamics (i.e. observer proper time).
Definition at line 472 of file stateDerivativePartial.h.
Referenced by getIntegrationReferencePoint().
isCurrentDoubleParameterPartialSet_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool > tudat::orbit_determination::StateDerivativePartial::isCurrentDoubleParameterPartialSet_ protected
Definition at line 477 of file stateDerivativePartial.h.
Referenced by resetCurrentParameterValues(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), setParameterPartialUpdateFunction(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction(), and updateParameterPartials().
isCurrentDoubleParameterPartialSetIterator_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, bool >::iterator tudat::orbit_determination::StateDerivativePartial::isCurrentDoubleParameterPartialSetIterator_ protected
Definition at line 481 of file stateDerivativePartial.h.
Referenced by resetCurrentParameterValues().
currentDoubleParameterPartials_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, Eigen::MatrixXd > tudat::orbit_determination::StateDerivativePartial::currentDoubleParameterPartials_ protected
Definition at line 487 of file stateDerivativePartial.h.
Referenced by getCurrentParameterPartial(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), setParameterPartialUpdateFunction(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction(), and updateParameterPartials().
parameterDoublePartialFunctions_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd&) > > tudat::orbit_determination::StateDerivativePartial::parameterDoublePartialFunctions_ protected
Definition at line 491 of file stateDerivativePartial.h.
Referenced by getCurrentParameterPartial(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), setParameterPartialUpdateFunction(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction(), and updateParameterPartials().
parameterDoublePartialFunctionIterator_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< double > >, std::function< void(Eigen::MatrixXd&) > >::iterator tudat::orbit_determination::StateDerivativePartial::parameterDoublePartialFunctionIterator_ protected
Definition at line 495 of file stateDerivativePartial.h.
Referenced by updateParameterPartials().
isCurrentVectorParameterPartialSet_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool > tudat::orbit_determination::StateDerivativePartial::isCurrentVectorParameterPartialSet_ protected
Definition at line 501 of file stateDerivativePartial.h.
Referenced by resetCurrentParameterValues(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), setParameterPartialUpdateFunction(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction(), and updateParameterPartials().
isCurrentVectorParameterPartialSetIterator_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, bool >::iterator tudat::orbit_determination::StateDerivativePartial::isCurrentVectorParameterPartialSetIterator_ protected
Definition at line 505 of file stateDerivativePartial.h.
Referenced by resetCurrentParameterValues().
currentVectorParameterPartials_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, Eigen::MatrixXd > tudat::orbit_determination::StateDerivativePartial::currentVectorParameterPartials_ protected
Definition at line 511 of file stateDerivativePartial.h.
Referenced by getCurrentParameterPartial(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), setParameterPartialUpdateFunction(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction(), and updateParameterPartials().
parameterVectorPartialFunctions_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd&) > > tudat::orbit_determination::StateDerivativePartial::parameterVectorPartialFunctions_ protected
Definition at line 515 of file stateDerivativePartial.h.
Referenced by getCurrentParameterPartial(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::setParameterPartialUpdateFunction(), setParameterPartialUpdateFunction(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::setParameterPartialUpdateFunction(), and updateParameterPartials().
parameterVectorPartialFunctionIterator_
std::map< std::shared_ptr< estimatable_parameters::EstimatableParameter< Eigen::VectorXd > >, std::function< void(Eigen::MatrixXd&) > >::iterator tudat::orbit_determination::StateDerivativePartial::parameterVectorPartialFunctionIterator_ protected
Definition at line 519 of file stateDerivativePartial.h.
Referenced by updateParameterPartials().
currentTime_
double tudat::orbit_determination::StateDerivativePartial::currentTime_ protected
Definition at line 522 of file stateDerivativePartial.h.
Referenced by resetTime(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::resetTimeOfMemberObjects(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::resetTimeOfMemberObjects(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::resetTimeOfMemberObjects(), StateDerivativePartial(), tudat::acceleration_partials::MutualSphericalHarmonicsGravityPartial::update(), tudat::acceleration_partials::CentralGravitationPartial::update(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::update(), tudat::acceleration_partials::CannonBallRadiationPressurePartial::update(), tudat::acceleration_partials::DirectTidalDissipationAccelerationPartial::update(), tudat::acceleration_partials::RelativisticAccelerationPartial::update(), tudat::acceleration_partials::ThirdBodyGravityPartial< DirectGravityPartial, type >::update(), tudat::acceleration_partials::CannonBallRadiationPressurePartial::wrtArcWiseRadiationPressureCoefficient(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtRotationModelParameter().
The documentation for this class was generated from the following file:
Astrodynamics/OrbitDetermination/stateDerivativePartial.h