Tudat: tudat::geometric_shapes Namespace Reference
tudat::geometric_shapes Namespace Reference
Classes
class Capsule
Capsule class.
class CompositeSurfaceGeometry
Composite surface geometry class.
class ConicalFrustum
ConicalFrustum class.
class LawgsPartGeometry
Class to define a mesh accoring to Lawgs standards.
class QuadrilateralMeshedSurfaceGeometry
Class for quadrilateral meshed surface geometry.
class SingleSurfaceGeometry
Surface geometry base class.
class SphereSegment
Sphere segment class.
class Torus
Torus class.
Typedefs
typedef std::shared_ptr< Capsule > CapsulePointer
Typedef for shared-pointer to Capsule object.
typedef CompositeSurfaceGeometry::CompositeSurfaceGeometryPointer CompositeSurfaceGeometryPointer
Typedef for shared-pointer to CompositeSurfaceGeometry object.
typedef std::shared_ptr< ConicalFrustum > ConicalFrustumPointer
Typedef for shared-pointer to ConicalFrustum object.
typedef std::shared_ptr< LawgsPartGeometry > LawgsPartGeometryPointer
Typedef for shared-pointer to LawgsPartGeometry object.
typedef std::shared_ptr< QuadrilateralMeshedSurfaceGeometry > QuadrilateralMeshedSurfaceGeometryPointer
Typedef for shared-pointer to QuadrilateralMeshedSurfaceGeometry object.
typedef std::shared_ptr< SingleSurfaceGeometry > SingleSurfaceGeometryPointer
Typedef for shared-pointer to SingleSurfaceGeometry object.
typedef std::shared_ptr< SphereSegment > SphereSegmentPointer
Typedef for shared-pointer to SphereSegment object.
typedef std::shared_ptr< Torus > TorusPointer
Typedef for shared-pointer to Torus object.
Functions
std::ostream & operator<< (std::ostream &stream, CompositeSurfaceGeometry &compositeSurfaceGeometry)
Overload ostream to print class information.
std::ostream & operator<< (std::ostream &stream, QuadrilateralMeshedSurfaceGeometry &quadrilateralMeshedSurfaceGeometry)
Overload ostream to print class information.
std::ostream & operator<< (std::ostream &stream, Capsule &capsule)
Overload ostream to print class information.
std::ostream & operator<< (std::ostream &stream, LawgsPartGeometry &lawgsPartGeometry)
Overload ostream to print class information.
std::ostream & operator<< (std::ostream &stream, ConicalFrustum &conicalFrustum)
Overload ostream to print class information.
std::ostream & operator<< (std::ostream &stream, SphereSegment &sphereSegment)
Overload ostream to print class information.
std::ostream & operator<< (std::ostream &stream, Torus &torus)
Overload ostream to print class information.
void writeCompositeSurfaceGeometryPointsToFile (geometric_shapes::CompositeSurfaceGeometryPointer compositeSurfaceGeometry, const std::vector< int > &arrayOfNumberOfLines, const std::vector< int > &arrayOfNumberOfPoints, const std::string &filename, const int writeType, const std::vector< bool > &isIndependentVariableInvertedArray)
Write composite surface geometry to a file.
void writeSingleSurfaceGeometryPointsToFile (geometric_shapes::SingleSurfaceGeometryPointer singleSurfaceGeometry, const int numberOfLines, const int numberOfPoints, const std::string &filename, const int writeType, const bool isIndependentVariableInverted)
Write single surface geometry to a file.
Typedef Documentation
CapsulePointer
typedef std::shared_ptr< Capsule > tudat::geometric_shapes::CapsulePointer
Definition at line 141 of file capsule.h.
CompositeSurfaceGeometryPointer
typedef CompositeSurfaceGeometry::CompositeSurfaceGeometryPointer tudat::geometric_shapes::CompositeSurfaceGeometryPointer
Definition at line 212 of file compositeSurfaceGeometry.h.
ConicalFrustumPointer
typedef std::shared_ptr< ConicalFrustum > tudat::geometric_shapes::ConicalFrustumPointer
Definition at line 172 of file conicalFrustum.h.
LawgsPartGeometryPointer
typedef std::shared_ptr< LawgsPartGeometry > tudat::geometric_shapes::LawgsPartGeometryPointer
Definition at line 154 of file lawgsPartGeometry.h.
QuadrilateralMeshedSurfaceGeometryPointer
typedef std::shared_ptr< QuadrilateralMeshedSurfaceGeometry > tudat::geometric_shapes::QuadrilateralMeshedSurfaceGeometryPointer
Definition at line 219 of file quadrilateralMeshedSurfaceGeometry.h.
SingleSurfaceGeometryPointer
typedef std::shared_ptr< SingleSurfaceGeometry > tudat::geometric_shapes::SingleSurfaceGeometryPointer
Definition at line 280 of file singleSurfaceGeometry.h.
SphereSegmentPointer
typedef std::shared_ptr< SphereSegment > tudat::geometric_shapes::SphereSegmentPointer
Definition at line 160 of file sphereSegment.h.
TorusPointer
typedef std::shared_ptr< Torus > tudat::geometric_shapes::TorusPointer
Definition at line 181 of file torus.h.
Function Documentation
operator<<() [1/7]
std::ostream& tudat::geometric_shapes::operator<< (std::ostream & stream, Capsule & capsule)
Overloads ostream to print class information, prints the class type, and number defining parameters.
Parameters
stream Stream to which info is to be printed.
capsule Capsule of which info is to be printed.
Returns
Stream with printed info.
Definition at line 142 of file capsule.cpp.
References tudat::geometric_shapes::Capsule::getMiddleRadius(), tudat::geometric_shapes::Capsule::getNoseRadius(), tudat::geometric_shapes::Capsule::getRearAngle(), tudat::geometric_shapes::Capsule::getRearLength(), and tudat::geometric_shapes::Capsule::getSideRadius().
operator<<() [2/7]
std::ostream& tudat::geometric_shapes::operator<< (std::ostream & stream, CompositeSurfaceGeometry & compositeSurfaceGeometry)
Overloads ostream to print class information, prints the class type, and number of constituent SingleSurfaceGeometry and compositeSurfaceGeometry objects.
Parameters
stream Stream object.
compositeSurfaceGeometry compositeSurfaceGeometry object.
Returns
Stream object.
Definition at line 40 of file compositeSurfaceGeometry.cpp.
References tudat::geometric_shapes::CompositeSurfaceGeometry::numberOfCompositeSurfaceGeometries_, and tudat::geometric_shapes::CompositeSurfaceGeometry::numberOfSingleSurfaceGeometries_.
operator<<() [3/7]
std::ostream& tudat::geometric_shapes::operator<< (std::ostream & stream, ConicalFrustum & conicalFrustum)
Overloaded ostream to print class information, prints the class type, the ranges for the azimuth angle, cone half angle, length and the start radius.
Parameters
stream Stream to which info is to be printed.
conicalFrustum Conical frustum of which info is to be printed.
Returns
Stream with printed info.
Definition at line 205 of file conicalFrustum.cpp.
References tudat::geometric_shapes::ConicalFrustum::getConeHalfAngle(), tudat::geometric_shapes::ConicalFrustum::getLength(), tudat::geometric_shapes::ConicalFrustum::getMaximumAzimuthAngle(), tudat::geometric_shapes::ConicalFrustum::getMinimumAzimuthAngle(), tudat::geometric_shapes::ConicalFrustum::getStartRadius(), and tudat::mathematical_constants::PI.
writeSingleSurfaceGeometryPointsToFile()
void tudat::geometric_shapes::writeSingleSurfaceGeometryPointsToFile (geometric_shapes::SingleSurfaceGeometryPointer singleSurfaceGeometry, const int numberOfLines, const int numberOfPoints, const std::string & filename, const int writeType, const bool isIndependentVariableInverted)
Writes the points on a SingleSurfaceGeometry object to a file. Each row contains the x, y and z coordinate of the point, each next row defines a single new point.
Parameters
singleSurfaceGeometry Geometry which is to be written.
numberOfLines Defines how many points are taken over the 1st independent variable.
numberOfPoints Defines how many points are taken over the 2nd independent variable.
filename Name of the file to which the points are written.
writeType Defines whether to append or write to the file given by filename, should be "a" for append and "w" for write.
isIndependentVariableInverted Boolean flag which if set to true inverts which independent variable is treated as 1st and which as 2nd.
Definition at line 22 of file geometricShapesToFile.cpp.
Referenced by writeCompositeSurfaceGeometryPointsToFile().
writeCompositeSurfaceGeometryPointsToFile()
void tudat::geometric_shapes::writeCompositeSurfaceGeometryPointsToFile (geometric_shapes::CompositeSurfaceGeometryPointer compositeSurfaceGeometry, const std::vector< int > & arrayOfNumberOfLines, const std::vector< int > & arrayOfNumberOfPoints, const std::string & filename, const int writeType, const std::vector< bool > & isIndependentVariableInvertedArray)
Writes the single surface geometries in a composite surface geometry to a file. The writeSingleGeometryPointsToFile() function is called for each surface geometry.
Parameters
compositeSurfaceGeometry Geometry from which there is to be written.
arrayOfNumberOfLines Array of how many points to take over the 1st independent variables of single surface geometries.
arrayOfNumberOfPoints Array of how many points to take over the 2nd independent variables of single surface geometries.
filename Name of the file to which the points are written.
writeType Defines whether to append or write to the file given by filename, should be "a" for append and "w" for write.
isIndependentVariableInvertedArray Array of booleans which if set to true invert which independent variable is treated as 1st and which as 2nd for each single surface geometry.
Definition at line 128 of file geometricShapesToFile.cpp.
References writeSingleSurfaceGeometryPointsToFile().
operator<<() [4/7]
std::ostream& tudat::geometric_shapes::operator<< (std::ostream & stream, LawgsPartGeometry & lawgsPartGeometry)
Overloads ostream to print class information, prints the number of lines and points, and the name of the part.
Parameters
stream Stream object.
lawgsPartGeometry Lawgs part geometry.
Returns
Stream object.
Definition at line 159 of file lawgsPartGeometry.cpp.
References tudat::geometric_shapes::LawgsPartGeometry::name_, tudat::geometric_shapes::QuadrilateralMeshedSurfaceGeometry::numberOfLines_, and tudat::geometric_shapes::QuadrilateralMeshedSurfaceGeometry::numberOfPoints_.
operator<<() [5/7]
std::ostream& tudat::geometric_shapes::operator<< (std::ostream & stream, QuadrilateralMeshedSurfaceGeometry & quadrilateralMeshedSurfaceGeometry)
Overloads ostream to print class information, prints the number of lines and points, and the name of the part.
Parameters
stream Stream object.
quadrilateralMeshedSurfaceGeometry Quadrilateral meshed surface geometry.
Returns
Stream object.
Definition at line 120 of file quadrilateralMeshedSurfaceGeometry.cpp.
References tudat::geometric_shapes::QuadrilateralMeshedSurfaceGeometry::numberOfLines_, and tudat::geometric_shapes::QuadrilateralMeshedSurfaceGeometry::numberOfPoints_.
operator<<() [6/7]
std::ostream& tudat::geometric_shapes::operator<< (std::ostream & stream, SphereSegment & sphereSegment)
Overloads ostream to print class information, prints the class type, the ranges for the azimuth and zenith angles and the radius.
Parameters
stream Stream object.
sphereSegment Sphere segment.
Returns
Stream object.
Definition at line 210 of file sphereSegment.cpp.
References tudat::unit_conversions::convertRadiansToDegrees(), tudat::geometric_shapes::SingleSurfaceGeometry::getMaximumIndependentVariable(), tudat::geometric_shapes::SingleSurfaceGeometry::getMinimumIndependentVariable(), and tudat::geometric_shapes::SphereSegment::getRadius().
operator<<() [7/7]
std::ostream& tudat::geometric_shapes::operator<< (std::ostream & stream, Torus & torus)
Overloads ostream to print class information, prints the class type, the ranges for the minor and major circumferential angles, and the major and minor radii.
Parameters
stream Stream to which info is to be printed.
torus Torus frustum of which info is to be printed.
Returns
Stream with printed info.
Definition at line 222 of file torus.cpp.
References tudat::geometric_shapes::Torus::getMajorRadius(), tudat::geometric_shapes::Torus::getMaximumMajorCircumferentialAngle(), tudat::geometric_shapes::Torus::getMaximumMinorCircumferentialAngle(), tudat::geometric_shapes::Torus::getMinimumMajorCircumferentialAngle(), tudat::geometric_shapes::Torus::getMinimumMinorCircumferentialAngle(), tudat::geometric_shapes::Torus::getMinorRadius(), and tudat::mathematical_constants::PI.