Tudat: tudat::json_interface::AutoReportableBugError Class Reference
tudat::json_interface::AutoReportableBugError Class Reference
Class for errors that print a report bug link to open an issue on GitHub (optionally pre-filled).
#include <errorHandling.h>
Public Member Functions
AutoReportableBugError (const std::string &errorMessage="Internal Tudat error. Please, report this bug by using this link: ", const std::string &issueTitle="", const std::string &issueBody="")
Constructor.
void setIssue (const std::string &title, const std::string &body)
Change the issue's title and body and update the report URL.
void setIssueBody (const std::string &body)
Change the issue's body and update the report URL.
void setIssueTitle (const std::string &title)
Change the issue's title and update the report URL.
Public Member Functions inherited from tudat::json_interface::ReportableBugError
ReportableBugError (const std::string &errorMessage="Internal Tudat error. Please, report this bug by using this link: ", const std::string &reportURL="https://github.com/Tudat/tudat/issues")
Constructor.
virtual const char * what () const throw ()
Full error message.
Private Member Functions
void updateReportURL ()
Update the report URL.
Private Attributes
std::string issueBody
Pre-filled title for the new issue to be opened on GitHub.
std::string issueTitle
Pre-filled title for the new issue to be opened on GitHub.
Additional Inherited Members
Protected Attributes inherited from tudat::json_interface::ReportableBugError
std::string errorMessage
The message to print before the error link.
std::string reportURL
The URL that can be used to report the error.
Detailed Description
Class for errors that print a report bug link to open an issue on GitHub (optionally pre-filled).
Definition at line 238 of file errorHandling.h.
Constructor & Destructor Documentation
AutoReportableBugError()
tudat::json_interface::AutoReportableBugError::AutoReportableBugError (const std::string & errorMessage = "Internal Tudat error. Please, report this bug by using this link: ", const std::string & issueTitle = "", const std::string & issueBody = "") inline
Constructor.
Parameters
errorMessage First part of the message.
issueTitle Pre-filled title for the new issue to be opened on GitHub.
issueBody Pre-filled title for the new issue to be opened on GitHub.
Definition at line 248 of file errorHandling.h.
References updateReportURL().
Member Function Documentation
setIssueTitle()
void tudat::json_interface::AutoReportableBugError::setIssueTitle (const std::string & title) inline
Change the issue's title and update the report URL.
Parameters
title New issue's title.
Definition at line 261 of file errorHandling.h.
References issueTitle, and updateReportURL().
setIssueBody()
void tudat::json_interface::AutoReportableBugError::setIssueBody (const std::string & body) inline
Change the issue's body and update the report URL.
Parameters
body New issue's body.
Definition at line 272 of file errorHandling.h.
References issueBody, and updateReportURL().
setIssue()
void tudat::json_interface::AutoReportableBugError::setIssue (const std::string & title, const std::string & body) inline
Change the issue's title and body and update the report URL.
Parameters
title New issue's title.
body New issue's body.
Definition at line 284 of file errorHandling.h.
References issueBody, issueTitle, and updateReportURL().
Referenced by tudat::json_interface::nullptrPointerError< T >::nullptrPointerError(), and tudat::json_interface::UnimplementedEnumError< EnumType >::UnimplementedEnumError().
updateReportURL()
void tudat::json_interface::AutoReportableBugError::updateReportURL () inline private
Update the report URL for the current issueTitle and issueBody.
Definition at line 302 of file errorHandling.h.
References issueBody, issueTitle, tudat::json_interface::ReportableBugError::reportURL, and tudat::json_interface::url_encode().
Referenced by AutoReportableBugError(), setIssue(), setIssueBody(), and setIssueTitle().
Member Data Documentation
issueTitle
std::string tudat::json_interface::AutoReportableBugError::issueTitle private
Definition at line 293 of file errorHandling.h.
Referenced by setIssue(), setIssueTitle(), and updateReportURL().
issueBody
std::string tudat::json_interface::AutoReportableBugError::issueBody private
Definition at line 296 of file errorHandling.h.
Referenced by setIssue(), setIssueBody(), and updateReportURL().
The documentation for this class was generated from the following file:
JsonInterface/Support/errorHandling.h