Tudat: tudat::unit_conversions Namespace Reference
tudat::unit_conversions Namespace Reference
Functions
template<typename T >
T convertArcminutesToArcseconds (T angleInArcminutes)
Convert angle in arcminutes to arcseconds.
template<typename T >
T convertArcSecondsToRadians (T angleInArcSeconds)
Convert arc seconds to degrees.
template<typename T >
T convertAstronomicalUnitsToMeters (T distanceInAstronomicalUnits)
Convert distance in astronomical units to meters.
template<typename T >
T convertDegreesToArcminutes (T angleInDegrees)
Convert angle in degrees to arcminutes.
template<typename T >
T convertDegreesToRadians (T angleInDegrees)
Convert angle in degrees to radians.
template<typename T >
T convertFeetToMeter (T distanceInFeet)
Convert distance in feet to meters.
template<typename T >
T convertHoursToSeconds (T timeInHours)
Convert time in hours to seconds.
template<typename T >
T convertJulianDaysToJulianYears (T timeInJulianDays)
Convert time in Julian days to Julian years.
template<typename T >
T convertJulianDaysToSeconds (T timeInJulianDays)
Convert time in Julian days to seconds.
template<typename T >
T convertJulianYearsToJulianDays (T timeInJulianYears)
Convert time in Julian years to Julian days.
template<typename T >
T convertKilometersToMeters (T distanceInKilometers)
Convert distance in kilometers to meters.
template<typename T >
T convertMetersToAstronomicalUnits (T distanceInMeters)
Convert distance in meters to astronomical units.
template<typename T >
T convertMetersToKilometers (T distanceInMeters)
Convert distance in meters to kilometers.
template<typename T >
T convertMinutesToSeconds (T timeInMinutes)
Convert time in minutes to seconds.
template<typename T >
T convertPoundPerSquareFeetToPascal (T pressureInPoundPerSquareFeet)
Convert pressure in pound per square feet to Newton per square meter.
template<typename T >
T convertRadiansToArcSeconds (T angleInRadians)
template<typename T >
T convertRadiansToDegrees (T angleInRadians)
Convert angle in radians to degrees.
template<typename T >
T convertRankineToKelvin (T temperatureInRankine)
Convert temperature in Rankine to Kelvin.
template<typename T >
T convertSecondsToHours (T timeInSeconds)
Convert time in seconds to hours.
template<typename T >
T convertSecondsToJulianDays (T timeInSeconds)
Convert time in seconds to Julian days.
template<typename T >
T convertSecondsToMinutes (T timeInSeconds)
Convert time in seconds to minutes.
template<typename T >
T convertSecondsToSiderealDays (T timeInSeconds)
Convert time in seconds to sidereal days.
template<typename T >
T convertSiderealDaysToSeconds (T timeInSiderealDays)
Convert time in sidereal days to seconds.
Function Documentation
template<typename T > T tudat::unit_conversions::convertRadiansToDegrees (T angleInRadians)
Converts angle given in radians to degrees.
Parameters
angleInRadians Angle in radians.
Returns
Angle in degrees.
Definition at line 46 of file unitConversions.h.
References tudat::mathematical_constants::PI.
Referenced by tudat::geometric_shapes::operator<<().
template<typename T > T tudat::unit_conversions::convertDegreesToRadians (T angleInDegrees)
Converts angle given in degrees to radians.
Parameters
angleInDegrees Angle in degrees.
Returns
Angle in radians.
Definition at line 56 of file unitConversions.h.
References tudat::mathematical_constants::PI.
Referenced by tudat::input_output::MissileDatcomData::convertDatcomData(), tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), and tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris().
template<typename T > T tudat::unit_conversions::convertDegreesToArcminutes (T angleInDegrees)
Converts angle given in degrees to arcminutes.
Parameters
angleInDegrees Angle in degrees.
Returns
Angle in arcminutes.
Definition at line 66 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertArcSecondsToRadians (T angleInArcSeconds)
Convert arc seconds to degrees
Parameters
angleInArcSeconds Angle in arc seconds.
Returns
Angle in degrees.
Definition at line 76 of file unitConversions.h.
References tudat::mathematical_constants::PI.
template<typename T > T tudat::unit_conversions::convertRadiansToArcSeconds (T angleInRadians)
Definition at line 80 of file unitConversions.h.
References tudat::mathematical_constants::PI.
template<typename T > T tudat::unit_conversions::convertArcminutesToArcseconds (T angleInArcminutes)
Converts angle given in arcminutes to arcseconds.
Parameters
angleInArcminutes Angle in arcminutes.
Returns
Angle in arcseconds.
Definition at line 92 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertMetersToKilometers (T distanceInMeters)
Converts distance given in meters to kilometers.
Parameters
distanceInMeters Distance in meters.
Returns
Distance in kilometers.
Definition at line 102 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertKilometersToMeters (T distanceInKilometers)
Converts distance given in kilometers to meters.
Parameters
distanceInKilometers Distance in kilometers.
Returns
Distance in meters.
Definition at line 112 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertMetersToAstronomicalUnits (T distanceInMeters)
Converts distance given in meters to astronomical units.
Parameters
distanceInMeters Distance in meters.
Returns
Distance in astronomical units.
Definition at line 122 of file unitConversions.h.
References tudat::physical_constants::ASTRONOMICAL_UNIT.
template<typename T > T tudat::unit_conversions::convertAstronomicalUnitsToMeters (T distanceInAstronomicalUnits)
Converts distance given in astronomical units to meters.
Parameters
distanceInAstronomicalUnits Distance in astronomical units.
Returns
Distance in meters.
Definition at line 132 of file unitConversions.h.
References tudat::physical_constants::ASTRONOMICAL_UNIT.
Referenced by tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), and tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris().
template<typename T > T tudat::unit_conversions::convertSecondsToMinutes (T timeInSeconds)
Converts time given in seconds to minutes.
Parameters
timeInSeconds Time in seconds.
Returns
Time in minutes.
Definition at line 142 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertMinutesToSeconds (T timeInMinutes)
Converts time given in minutes to seconds.
Parameters
timeInMinutes Time in minutes.
Returns
Time in seconds.
Definition at line 152 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertSecondsToHours (T timeInSeconds)
Converts time given in seconds to hours.
Parameters
timeInSeconds Time in seconds.
Returns
Time in hours.
Definition at line 162 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertHoursToSeconds (T timeInHours)
Converts time given in hours to seconds.
Parameters
timeInHours Time in hours.
Returns
Time in seconds.
Definition at line 172 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertSecondsToJulianDays (T timeInSeconds)
Converts time given in seconds to Julian days.
Parameters
timeInSeconds Time in seconds.
Returns
Time in Julian days.
Definition at line 182 of file unitConversions.h.
References tudat::physical_constants::JULIAN_DAY.
template<typename T > T tudat::unit_conversions::convertJulianDaysToSeconds (T timeInJulianDays)
Converts time given in Julian days to seconds.
Parameters
timeInJulianDays Time in Julian days.
Returns
Time in seconds.
Definition at line 192 of file unitConversions.h.
References tudat::physical_constants::JULIAN_DAY.
template<typename T > T tudat::unit_conversions::convertSecondsToSiderealDays (T timeInSeconds)
Converts time given in seconds to sidereal days.
Parameters
timeInSeconds Time in seconds.
Returns
Time in sidereal days.
Definition at line 202 of file unitConversions.h.
References tudat::physical_constants::SIDEREAL_DAY.
template<typename T > T tudat::unit_conversions::convertSiderealDaysToSeconds (T timeInSiderealDays)
Converts time given in sidereal days to seconds.
Parameters
timeInSiderealDays Time in sidereal days.
Returns
Time in seconds.
Definition at line 212 of file unitConversions.h.
References tudat::physical_constants::SIDEREAL_DAY.
template<typename T > T tudat::unit_conversions::convertJulianDaysToJulianYears (T timeInJulianDays)
Converts time given in Julian days to Julian years.
Parameters
timeInJulianDays Time in Julian days.
Returns
Time in Julian years.
Definition at line 222 of file unitConversions.h.
References tudat::physical_constants::JULIAN_YEAR_IN_DAYS.
template<typename T > T tudat::unit_conversions::convertJulianYearsToJulianDays (T timeInJulianYears)
Converts time given in Julian years to Julian days.
Parameters
timeInJulianYears Time in Julian years.
Returns
Time in Julian days.
Definition at line 232 of file unitConversions.h.
References tudat::physical_constants::JULIAN_YEAR_IN_DAYS.
template<typename T > T tudat::unit_conversions::convertRankineToKelvin (T temperatureInRankine)
Converts temperature given in Rankine to Kelvin (Wikipedia, 2012a).
Parameters
temperatureInRankine Temperature in Rankine.
Returns
Temperature in Kelvin.
Definition at line 242 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertFeetToMeter (T distanceInFeet)
Converts distance given in feet to meters (Wikipedia, 2012b).
Parameters
distanceInFeet Distance in feet.
Returns
Distance in meters.
Definition at line 252 of file unitConversions.h.
template<typename T > T tudat::unit_conversions::convertPoundPerSquareFeetToPascal (T pressureInPoundPerSquareFeet)
Converts pressure given in pound per square feet to Newton per square meter (Pascal) (Wikipedia, 2012c).
Parameters
pressureInPoundPerSquareFeet Pressure in pound per square feet.
Returns
Pressure in Newton per square meter (Pascal).
Definition at line 263 of file unitConversions.h.