Tudat: tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType > Class Template Reference
tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType > Class Template Reference
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with unified state model with quaternions (USM7).
#include <nBodyUnifiedStateModelQuaternionsStateDerivative.h>
Public Member Functions
NBodyUnifiedStateModelQuaternionsStateDerivative (const basic_astrodynamics::AccelerationMap &accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const std::vector< std::string > &bodiesToIntegrate)
Constructor.
~NBodyUnifiedStateModelQuaternionsStateDerivative ()
Destructor.
void calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative)
Calculates the state derivative of the translational motion of the system, using the equations of motion for the unified state model with quaternions (USM7).
Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &cartesianSolution, const TimeType &time)
Function to convert the state in the conventional form to the USM7 elements form.
void convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSolution)
Function to convert the USM7 states of the bodies to the conventional form.
basic_astrodynamics::AccelerationMap getFullAccelerationsMap ()
Function to get the acceleration models.
int getPropagatedStateSize ()
Function to return the size of the state handled by the object.
bool isStateToBePostProcessed ()
Function to return whether the state needs to be post-processed.
void postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState)
Function to process the state during propagation.
Public Member Functions inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
NBodyStateDerivative (const basic_astrodynamics::AccelerationMap &accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const TranslationalPropagatorType propagatorType, const std::vector< std::string > &bodiesToIntegrate)
From this constructor, the object for generating the state derivative is created.
virtual ~NBodyStateDerivative ()
Destructor.
virtual void clearDerivedTranslationalStateDerivativeModel ()
Function to clear any reference/cached values of state derivative model.
void clearStateDerivativeModel ()
Function to clear reference/cached values of translational state derivative model.
void clearTranslationalStateDerivativeModel ()
Function to clear reference/cached values of acceleration models.
void convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton)
Function to convert the propagator-specific form of the state to the conventional form in the global frame.
basic_astrodynamics::AccelerationMap getAccelerationsMap ()
Function to retrieve the map containing the list of accelerations acting on each body.
std::vector< std::string > getBodiesToBeIntegratedNumerically ()
Function to get list of names of bodies that are to be integrated numerically.
std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > getCentralBodyData ()
Function to get object providing the current integration origins.
int getConventionalStateSize ()
Function to return the size of the state handled by the object.
Eigen::Vector3d getTotalAccelerationForBody (const std::string &bodyName)
Function to retrieve the total acceleration acting on a given body.
TranslationalPropagatorType getTranslationalPropagatorType ()
Function to get type of propagator that is to be used (i.e. Cowell, Encke, etc.)
void updateStateDerivativeModel (const TimeType currentTime)
Function to update the state derivative model to the current time.
Public Member Functions inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
SingleStateTypeDerivative (const IntegratedStateType integratedStateType)
Constructor.
virtual ~SingleStateTypeDerivative ()
Virtual destructor.
IntegratedStateType getIntegratedStateType ()
Function to return the type of dynamics for which the state derivative is calculated.
virtual void postProcessState (Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &unprocessedState)
Private Attributes
std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > centralAccelerations_
Central body accelerations for each propagated body, which has been removed from accelerationModelsPerBody_.
std::vector< std::function< double() > > centralBodyGravitationalParameters_
Gravitational parameters of central bodies used to convert Cartesian to Keplerian orbits, and vice versa.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > currentCartesianLocalSolution_
Current full Cartesian state of the propagated bodies, w.r.t. the central bodies.
basic_astrodynamics::AccelerationMap originalAccelerationModelsPerBody_
List of acceleration models, including the central body accelerations that are removed in this propagation scheme.
Additional Inherited Members
Protected Member Functions inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
void createAccelerationModelList ()
void sumStateDerivativeContributions (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative, const bool addPositionDerivatives=true)
Function to get the state derivative of the system in Cartesian coordinates.
void sumStateDerivativeContributions (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &stateDerivative, const bool addPositionDerivatives=true)
Function to get the state derivative of the system in Cartesian coordinates.
Protected Attributes inherited from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >
std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > accelerationModelList_
Vector of acceleration models, containing all entries of accelerationModelsPerBody_.
basic_astrodynamics::AccelerationMap accelerationModelsPerBody_
A map containing the list of accelerations acting on each body,.
std::vector< std::string > bodiesToBeIntegratedNumerically_
List of names of bodies that are to be integrated numerically.
std::vector< int > bodyOrder_
std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData_
Object responsible for providing the current integration origins from the global origins.
std::vector< Eigen::Matrix< StateScalarType, 6, 1 > > centralBodyStatesWrtGlobalOrigin_
List of states of the central bodies of the propagated bodies.
std::unordered_map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > >::iterator innerAccelerationIterator
Predefined iterator to save (de-)allocation time.
std::unordered_map< std::string, std::unordered_map< std::string, std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > > >::iterator outerAccelerationIterator
Predefined iterator to save (de-)allocation time.
TranslationalPropagatorType propagatorType_
Type of propagator that is to be used (i.e. Cowell, Encke, etc.)
Protected Attributes inherited from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
IntegratedStateType integratedStateType_
Type of dynamics for which the state derivative is calculated.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > unprocessedState_
Vector used during post-processing of state.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >
Class for computing the state derivative of translational motion of N bodies, using a Gauss method with unified state model with quaternions (USM7).
In this method, the derivative of the USM7 elements are computed from the total Cartesian accelerations, with the USM7 elements of the bodies the states being numerically propagated.
Definition at line 88 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
Constructor & Destructor Documentation
NBodyUnifiedStateModelQuaternionsStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelQuaternionsStateDerivative (const basic_astrodynamics::AccelerationMap & accelerationModelsPerBody, const std::shared_ptr< CentralBodyData< StateScalarType, TimeType > > centralBodyData, const std::vector< std::string > & bodiesToIntegrate) inline
Constructor
Parameters
accelerationModelsPerBody A map containing the list of accelerations acting on each body, identifying the body being acted on and the body acted on by an acceleration. The map has as key a string denoting the name of the body the list of accelerations, provided as the value corresponding to a key, is acting on. This map-value is again a map with string as key, denoting the body exerting the acceleration, and as value a pointer to an acceleration model.
centralBodyData Object responsible for providing the current integration origins from the global origins.
bodiesToIntegrate List of names of bodies that are to be integrated numerically.
Definition at line 105 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::accelerationModelsPerBody_, tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::createAccelerationModelList(), tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_, and tudat::propagators::removeCentralGravityAccelerations().
~NBodyUnifiedStateModelQuaternionsStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::~NBodyUnifiedStateModelQuaternionsStateDerivative () inline
Definition at line 123 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
Member Function Documentation
calculateSystemStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative) inline virtual
Calculates the state derivative of the translational motion of the system, using the equations of motion for the unified state model with quaternions (USM7).
The input is the current state in USM7 elememts. The state derivate of this set is computed. To do so the accelerations are internally transformed into the RSW frame, using the current Cartesian state as set by the last call to the convertToOutputSolution function
Parameters
time Time (TDB seconds since J2000) at which the system is to be updated.
stateOfSystemToBeIntegrated List of 7 * bodiesToBeIntegratedNumerically_.size(), containing USM7 elements of the bodies being integrated. The order of the values is defined by the order of bodies in bodiesToBeIntegratedNumerically_
stateDerivative Current derivative of the USM7 elements of the system of bodies integrated numerically (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 139 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::propagators::computeStateDerivativeForUnifiedStateModelQuaternions(), tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSolution_, tudat::reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix(), and tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::sumStateDerivativeContributions().
convertFromOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & cartesianSolution, const TimeType & time) inline virtual
Function to convert the state in the conventional form to the propagator-specific form. For the USM7 propagator, this transforms the Cartesian state w.r.t. the central body (conventional form) to the UMS7 elements
Parameters
cartesianSolution State in 'conventional form'
time Current time at which the state is valid, used to computed Kepler orbits
Returns
State (outputSolution), converted to the USM7 elements
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 171 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::orbital_element_conversions::convertCartesianToUnifiedStateModelQuaternionsElements(), and tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::getPropagatedStateSize().
convertToOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSolution) inline virtual
Function to convert the USM7 elements state to the conventional form. For the USM7 propagator, this transforms USM7 elements w.r.t. the central bodies to the Cartesian states w.r.t. these same central bodies: In contrast to the convertCurrentStateToGlobalRepresentation function, this function does not provide the state in the inertial frame, but instead provides it in the frame in which it is propagated.
Parameters
internalSolution State in USM7 elemements (i.e. form that is used in numerical integration)
time Current time at which the state is valid
currentCartesianLocalSolution State (internalSolution, which is USM7-formulation), converted to the 'conventional form' (returned by reference).
Implements tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 201 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_, tudat::orbital_element_conversions::convertUnifiedStateModelQuaternionsToCartesianElements(), and tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSolution_.
getFullAccelerationsMap()
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::AccelerationMap tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::getFullAccelerationsMap () inline virtual
Function to get the acceleration models, including the central body accelerations that are removed for the propagation scheme
Returns
List of acceleration models, including the central body accelerations that are removed in this propagation scheme.
Reimplemented from tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >.
Definition at line 222 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
References tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_.
getPropagatedStateSize()
template<typename StateScalarType = double, typename TimeType = double> int tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::getPropagatedStateSize () inline virtual
Function to return the size of the state handled by the object.
Returns
Size of the state under consideration (7 times the number if integrated bodies).
Reimplemented from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 232 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_.
Referenced by tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution().
postProcessState()
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState) inline virtual
Function to process the state during propagation. For quaternions, this function normalizes the quaternion vector in case its magnitude differs from 1.0 by a value larger than the tolerance.
Parameters
unprocessedState State computed after propagation.
Returns
Processed state (returned by reference).
Reimplemented from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 244 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
References tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::bodiesToBeIntegratedNumerically_.
isStateToBePostProcessed()
template<typename StateScalarType = double, typename TimeType = double> bool tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::isStateToBePostProcessed () inline virtual
Function to return whether the state needs to be post-processed. For quaternions this is true.
Returns
Boolean confirming that the state needs to be post-processed.
Reimplemented from tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >.
Definition at line 271 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
Member Data Documentation
centralBodyGravitationalParameters_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::function< double() > > tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::centralBodyGravitationalParameters_ private
Definition at line 279 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
Referenced by tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::convertToOutputSolution(), and tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelQuaternionsStateDerivative().
centralAccelerations_
template<typename StateScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< basic_astrodynamics::AccelerationModel< Eigen::Vector3d > > > tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::centralAccelerations_ private
Definition at line 283 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
originalAccelerationModelsPerBody_
template<typename StateScalarType = double, typename TimeType = double> basic_astrodynamics::AccelerationMap tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::originalAccelerationModelsPerBody_ private
Definition at line 286 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
Referenced by tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::getFullAccelerationsMap(), and tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::NBodyUnifiedStateModelQuaternionsStateDerivative().
currentCartesianLocalSolution_
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::currentCartesianLocalSolution_ private
Current full Cartesian state of the propagated bodies, w.r.t. the central bodies. These variables are set when calling the convertToOutputSolution function.
Definition at line 293 of file nBodyUnifiedStateModelQuaternionsStateDerivative.h.
Referenced by tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative(), and tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >::convertToOutputSolution().
The documentation for this class was generated from the following file:
Astrodynamics/Propagators/nBodyUnifiedStateModelQuaternionsStateDerivative.h