Tudat: tudat::observation_models::LightTimeCorrection Class Reference
tudat::observation_models::LightTimeCorrection Class Reference abstract
Base class for computing deviations from the light-time w.r.t. straight-line propagation at constant velocity (c).
#include <lightTimeCorrection.h>
Public Member Functions
LightTimeCorrection (const LightTimeCorrectionType lightTimeCorrectionType)
Constructor.
virtual ~LightTimeCorrection ()
Destructor.
virtual double calculateLightTimeCorrection (const Eigen::Vector6d &transmitterState, const Eigen::Vector6d &receiverState, const double transmissionTime, const double receptionTime)=0
Pure virtual function to compute the light-time correction.
virtual double calculateLightTimeCorrectionDerivativeWrtLinkEndTime (const Eigen::Vector6d &transmitterState, const Eigen::Vector6d &receiverState, const double transmissionTime, const double receptionTime, const LinkEndType fixedLinkEnd, const LinkEndType linkEndAtWhichPartialIsEvaluated)
Function to compute the full derivative of the light-time correction w.r.t. observation time.
virtual Eigen::Matrix< double, 3, 1 > calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition (const Eigen::Vector6d &transmitterState, const Eigen::Vector6d &receiverState, const double transmissionTime, const double receptionTime, const LinkEndType linkEndAtWhichPartialIsEvaluated)=0
Pure virtual function to compute the partial derivative of the light-time correction w.r.t. link end position.
virtual double calculateLightTimeCorrectionPartialDerivativeWrtLinkEndTime (const Eigen::Vector6d &transmitterState, const Eigen::Vector6d &receiverState, const double transmissionTime, const double receptionTime, const LinkEndType fixedLinkEnd, const LinkEndType linkEndAtWhichPartialIsEvaluated)=0
Pure virtual function to compute the partial derivative of the light-time correction w.r.t. observation time.
LightTimeCorrectionType getLightTimeCorrectionType ()
Function to retrieve the type of light-time correction represented by instance of class.
Protected Attributes
LightTimeCorrectionType lightTimeCorrectionType_
Type of light-time correction represented by instance of class.
Detailed Description
Base class for computing deviations from the light-time w.r.t. straight-line propagation at constant velocity (c). This base class is non-functional, and each time of light-time correction must be defined in a dedicated derived class
Definition at line 36 of file lightTimeCorrection.h.
Constructor & Destructor Documentation
tudat::observation_models::LightTimeCorrection::LightTimeCorrection (const LightTimeCorrectionType lightTimeCorrectionType) inline
Constructor
Parameters
lightTimeCorrectionType Type of light-time correction represented by instance of class.
Definition at line 45 of file lightTimeCorrection.h.
virtual tudat::observation_models::LightTimeCorrection::~LightTimeCorrection () inline virtual
Definition at line 49 of file lightTimeCorrection.h.
References calculateLightTimeCorrection(), calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition(), and calculateLightTimeCorrectionPartialDerivativeWrtLinkEndTime().
Member Function Documentation
virtual double tudat::observation_models::LightTimeCorrection::calculateLightTimeCorrection (const Eigen::Vector6d & transmitterState, const Eigen::Vector6d & receiverState, const double transmissionTime, const double receptionTime) pure virtual
Pure virtual function to compute the light-time correction, function is to be implemented in derived class for specific correction model. The input is the states and times of the two link ends (at the current iteration of the solution of the implicit light-time equation), which is the information of the link already computed by the light time calculator, ensuring that no double computations are performed.
Parameters
transmitterState State of transmitted at transmission time
receiverState State of receiver at reception time
transmissionTime Time of signal transmission
receptionTime Time of singal reception
Returns
Light-time correction
Implemented in tudat::observation_models::FirstOrderLightTimeCorrectionCalculator, and tudat::observation_models::LightTimeCorrectionFunctionWrapper.
Referenced by ~LightTimeCorrection().
virtual double tudat::observation_models::LightTimeCorrection::calculateLightTimeCorrectionPartialDerivativeWrtLinkEndTime (const Eigen::Vector6d & transmitterState, const Eigen::Vector6d & receiverState, const double transmissionTime, const double receptionTime, const LinkEndType fixedLinkEnd, const LinkEndType linkEndAtWhichPartialIsEvaluated) pure virtual
Pure virtual function to compute the partial derivative of the light-time correction w.r.t. observation time. Function is to be implemented in derived class for specific correction model.
Parameters
transmitterState State of transmitted at transmission time
receiverState State of receiver at reception time
transmissionTime Time of signal transmission
receptionTime Time of singal reception
fixedLinkEnd Reference link end for observation
linkEndAtWhichPartialIsEvaluated Link end at which the time partial is to be taken
Returns
Light-time correction w.r.t. observation time
Implemented in tudat::observation_models::FirstOrderLightTimeCorrectionCalculator, and tudat::observation_models::LightTimeCorrectionFunctionWrapper.
Referenced by calculateLightTimeCorrectionDerivativeWrtLinkEndTime(), and ~LightTimeCorrection().
virtual Eigen::Matrix< double, 3, 1 > tudat::observation_models::LightTimeCorrection::calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition (const Eigen::Vector6d & transmitterState, const Eigen::Vector6d & receiverState, const double transmissionTime, const double receptionTime, const LinkEndType linkEndAtWhichPartialIsEvaluated) pure virtual
Pure virtual function to compute the partial derivative of the light-time correction w.r.t. link end position Function is to be implemented in derived class for specific correction model.
Parameters
transmitterState State of transmitted at transmission time
receiverState State of receiver at reception time
transmissionTime Time of signal transmission
receptionTime Time of singal reception
linkEndAtWhichPartialIsEvaluated Link end at which the position partial is to be taken
Returns
Light-time correction w.r.t. link end position
Implemented in tudat::observation_models::FirstOrderLightTimeCorrectionCalculator, and tudat::observation_models::LightTimeCorrectionFunctionWrapper.
Referenced by calculateLightTimeCorrectionDerivativeWrtLinkEndTime(), and ~LightTimeCorrection().
virtual double tudat::observation_models::LightTimeCorrection::calculateLightTimeCorrectionDerivativeWrtLinkEndTime (const Eigen::Vector6d & transmitterState, const Eigen::Vector6d & receiverState, const double transmissionTime, const double receptionTime, const LinkEndType fixedLinkEnd, const LinkEndType linkEndAtWhichPartialIsEvaluated) inline virtual
Function to compute the full derivative of the light-time correction w.r.t. observation time. The function as implemented here combines the position and time partial derivatives into the full time-derivative. The function is virtual and may be overridden in derived class for specific correction model.
Parameters
transmitterState State of transmitted at transmission time
receiverState State of receiver at reception time
transmissionTime Time of signal transmission
receptionTime Time of singal reception
fixedLinkEnd Reference link end for observation
linkEndAtWhichPartialIsEvaluated Link end at which the time partial is to be taken
Returns
Light-time correction w.r.t. observation time
Definition at line 120 of file lightTimeCorrection.h.
References calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition(), calculateLightTimeCorrectionPartialDerivativeWrtLinkEndTime(), and tudat::observation_models::transmitter.
LightTimeCorrectionType tudat::observation_models::LightTimeCorrection::getLightTimeCorrectionType () inline
Function to retrieve the type of light-time correction represented by instance of class.
Returns
Type of light-time correction represented by instance of class.
Definition at line 143 of file lightTimeCorrection.h.
References lightTimeCorrectionType_.
Member Data Documentation
LightTimeCorrectionType tudat::observation_models::LightTimeCorrection::lightTimeCorrectionType_ protected
Definition at line 151 of file lightTimeCorrection.h.
Referenced by getLightTimeCorrectionType().
The documentation for this class was generated from the following file:
Astrodynamics/ObservationModels/ObservableCorrections/lightTimeCorrection.h