Tudat: tudat::aerodynamics Namespace Reference
tudat::aerodynamics Namespace Reference
Classes
class AerodynamicAcceleration
Class for calculation of aerodynamic accelerations.
class AerodynamicCoefficientGenerator
Base class for aerodynamic coefficient generator.
class AerodynamicCoefficientInterface
Base class to hold an aerodynamic coefficient interface.
class AerodynamicGuidance
class AerodynamicTorque
Class for calculation of aerodynamic torques.
class AtmosphereModel
Atmosphere model class.
class AtmosphericFlightConditions
Class for calculating aerodynamic flight characteristics of a vehicle during numerical integration.
class ControlSurfaceIncrementAerodynamicInterface
Base class to hold an aerodynamic coefficient interface for a vehicle control surface.
class CustomAerodynamicCoefficientInterface
Aerodynamic coefficient interface taking function pointers providing aerodynamics coefficients as a function of independent variables (doubles).
class CustomConstantTemperatureAtmosphere
Custom constant temperature atmosphere class.
class CustomControlSurfaceIncrementAerodynamicInterface
Control surface aerodynamic coefficient interface taking function pointers providing aerodynamic coefficient increments as a function of independent variables (doubles).
class CustomWindModel
Class for computing the wind velocity vector from a custom, user-defined function.
class EquilibriumTemperatureFunction
Function that is used to compute the net heat flux from a given heat input and wall temperature.
class ExponentialAtmosphere
Exponential atmosphere class.
class FlightConditions
Class for calculating aerodynamic flight characteristics of a vehicle during numerical integration, in the absence of an atmosphere.
struct GasComponentProperties
Gas component properties data structure.
class HypersonicLocalInclinationAnalysis
Class for inviscid hypersonic aerodynamic analysis using local inclination methods.
class NRLMSISE00Atmosphere
NRLMSISE-00 atmosphere model class.
struct NRLMSISE00Input
Struct for Solar Activity data.
class StandardAtmosphere
Standard atmosphere model class.
class TabulatedAtmosphere
Tabulated atmosphere class.
class TrimOrientationCalculator
Class to determine the trimmed angle-of-attack for a given set of aerodynamic coefficients.
class WindModel
Base class for a wind model.
Typedefs
typedef std::shared_ptr< AerodynamicAcceleration > AerodynamicAccelerationPointer
Typedef for shared-pointer to AerodynamicAcceleration object.
typedef std::shared_ptr< AerodynamicCoefficientInterface > AerodynamicCoefficientInterfacePointer
Typedef for shared-pointer to AerodynamicCoefficientInterface object.
typedef std::shared_ptr< AtmosphereModel > AtmosphereModelPointer
Typedef for shared-pointer to AtmosphereModel object.
typedef std::shared_ptr< CustomConstantTemperatureAtmosphere > CustomConstantTemperatureAtmospherePointer
Typedef for shared-pointer to CustomConstantTemperatureAtmosphere object.
typedef std::shared_ptr< ExponentialAtmosphere > ExponentialAtmospherePointer
Typedef for shared-pointer to ExponentialAtmosphere object.
typedef std::shared_ptr< HypersonicLocalInclinationAnalysis > HypersonicLocalInclinationAnalysisPointer
Typedef for shared-pointer to HypersonicLocalInclinationAnalysis object.
typedef std::shared_ptr< StandardAtmosphere > StandardAtmospherePointer
Typedef for shared-pointer to StandardAtmosphere object.
typedef std::shared_ptr< TabulatedAtmosphere > TabulatedAtmospherePointer
Typedef for shared-pointer to TabulatedAtmosphere object.
Enumerations
enum AerodynamicCoefficientsIndependentVariables {
mach_number_dependent = 0, angle_of_attack_dependent = 1, angle_of_sideslip_dependent = 2, altitude_dependent = 3,
control_surface_deflection_dependent = 4, undefined_independent_variable = 5
}
Enum defining a list of independent variables on which the aerodynamic coefficients can depend.
enum AtmosphereDependentVariables {
density_dependent_atmosphere = 0, pressure_dependent_atmosphere = 1, temperature_dependent_atmosphere = 2, gas_constant_dependent_atmosphere = 3,
specific_heat_ratio_dependent_atmosphere = 4, molar_mass_dependent_atmosphere = 5
}
Enum of all the possible dependent variables that an atmosphere can describe.
enum AtmosphereIndependentVariables { altitude_dependent_atmosphere = 0, longitude_dependent_atmosphere = 1, latitude_dependent_atmosphere = 2, time_dependent_atmosphere = 3 }
Enum of all the possible independent variables on which the atmosphere can depend.
enum AvailableConstantTemperatureAtmosphereModels { exponential_atmosphere_model = 0, three_wave_atmosphere_model = 1, three_term_atmosphere_model = 2 }
enum BodiesWithPredefinedExponentialAtmospheres { undefined_body = -1, earth = 0, mars = 1 }
Bodies with predefined exponential atmospheres.
Functions
template<typename VariableType >
void checkVariableUniqueness (std::vector< VariableType > variables)
Check uniqueness of input.
double computeAcmEmpiricalPressureCoefficient (double inclinationAngle, double machNumber)
Compute pressure coefficient using the ACM empirical method.
double computeAdiabaticWallTemperature (const double airTemperature, const double machNumber, const double ratioSpecificHeats, const double recoveryFactor)
Compute the adiabatic wall temperature experienced by a vehicle.
Eigen::Vector3d computeAerodynamicAcceleration (const double dynamicPressure, const double referenceArea, const Eigen::Vector3d &aerodynamicCoefficients, const double vehicleMass)
Compute the aerodynamic acceleration in same reference frame as input coefficients.
Eigen::Vector3d computeAerodynamicAcceleration (const double dynamicPressure, AerodynamicCoefficientInterfacePointer coefficientInterface, const double vehicleMass)
Compute the aerodynamic acceleration in same reference frame as input coefficients.
Eigen::Vector3d computeAerodynamicForce (const double dynamicPressure, const double referenceArea, const Eigen::Vector3d &aerodynamicCoefficients)
Compute the aerodynamic force in same reference frame as input coefficients.
Eigen::Vector3d computeAerodynamicForce (const double dynamicPressure, AerodynamicCoefficientInterfacePointer coefficientInterface)
Compute the aerodynamic force in same reference frame as input coefficients.
double computeAerodynamicLoad (const double airDensity, const double airSpeed, const double referenceArea, const double vehicleMass, const Eigen::Vector3d &aerodynamicForceCoefficients)
Compute the aerodynamic load experienced by a vehicle.
double computeAerodynamicLoadFromAcceleration (const Eigen::Vector3d &aerodynamicAccelerationVector)
Function to compute the aerodynamic load experienced by a vehicle.
Eigen::Vector3d computeAerodynamicMoment (const double dynamicPressure, const double referenceArea, const double referenceLength, const Eigen::Vector3d &momentCoefficients)
Compute the aerodynamic moment in same reference frame as input coefficients.
Eigen::Vector3d computeAerodynamicMoment (const double dynamicPressure, const double referenceArea, const Eigen::Vector3d &referenceLengths, const Eigen::Vector3d &momentCoefficients)
Compute the aerodynamic moment in same reference frame as input coefficients.
Eigen::Vector3d computeAerodynamicMoment (const double dynamicPressure, AerodynamicCoefficientInterfacePointer coefficientInterface)
Calculates the aerodynamic moment in same reference frame as input coefficients.
double computeEmpiricalTangentConePressureCoefficient (double inclinationAngle, double machNumber)
Compute pressure coefficient using empirical tangent cone method.
double computeEmpiricalTangentWedgePressureCoefficient (double inclinationAngle, double machNumber)
Compute pressure coefficient using empirical tangent wedge method.
double computeEquilibiumWallTemperature (const std::function< double(const double) > heatTransferFunction, const double wallEmmisivity, const double adiabaticWallTemperature)
Function to compute the equilibrium wall temperature from the heat input and emmisivity.
double computeEquilibriumFayRiddellHeatFlux (const double airDensity, const double airSpeed, const double airTemperature, const double machNumber, const double noseRadius, const double wallEmissivity)
Function to compute the heat flux experienced by a vehicle, assuming an equlibrium wall temperature.
double computeEquilibriumHeatflux (const std::function< double(const double) > heatTransferFunction, const double wallEmmisivity, const double adiabaticWallTemperature)
Funtion to compute the equilibrium heat flux experienced by a vehicle.
double computeFayRiddellHeatFlux (const double airDensity, const double airSpeed, const double airTemperature, const double noseRadius, const double wallTemperature)
Function to compute the heat flux experienced by a vehicle.
double computeHankeyFlatSurfacePressureCoefficient (double inclinationAngle, double machNumber)
Compute pressure coefficient using the Hankey flat surface method.
double computeHighMachBasePressure (double machNumber)
Compute high Mach base pressure coefficient.
double computeInversePrandtlMeyerFunction (double prandtlMeyerFunctionValue)
Compute Mach number from Prandtl-Meyer function.
double computeLocalToStaticPressureRatio (double machNumber, double ratioOfSpecificHeats)
Compute local-to-static pressure ratio.
double computeMachNumber (const double speed, const double speedOfSound)
Compute Mach number.
double computeMeanFreePath (const double weightedAverageCollisionDiameter, const double averageNumberDensity)
Function to compute the mean free path of a particle.
double computeModifiedDahlemBuckPressureCoefficient (double inclinationAngle, double machNumber)
Compute pressure coefficient using modified Dahlem-Buck method.
double computeModifiedNewtonianPressureCoefficient (double inclinationAngle, double stagnationPressureCoefficient)
Compute pressure coefficient based on modified Newtonian theory.
double computeNewtonianPressureCoefficient (double inclinationAngle)
Compute pressure coefficient based on Newtonian theory.
double computePrandtlMeyerFreestreamPressureCoefficient (double inclinationAngle, double machNumber, double ratioOfSpecificHeats, double freestreamPrandtlMeyerFunction)
Compute pressure coefficient using Prandtl-Meyer expansion.
double computePrandtlMeyerFunction (double machNumber, double ratioOfSpecificHeats)
Compute Prandtl-Meyer function.
double computeShockDeflectionAngle (double shockAngle, double machNumber, double ratioOfSpecificHeats)
Compute shock deflection angle.
double computeShockDensityRatio (double normalMachNumber, double ratioOfSpecificHeats)
Compute ratio of post- to pre-shock density.
double computeShockEntropyJump (double normalMachNumber, double ratioOfSpecificHeats, double specificGasConstant)
Compute jump in entropy across a shock wave.
double computeShockPressureRatio (double normalMachNumber, double ratioOfSpecificHeats)
Compute ratio of post- to pre-shock pressure.
double computeShockTemperatureRatio (double normalMachNumber, double ratioOfSpecificHeats)
Compute ratio of post- to pre-shock temperature.
double computeShockTotalPressureRatio (double normalMachNumber, double ratioOfSpecificHeats, double specificGasConstant)
Compute post- to pre-shock total pressure ratio.
double computeSmythDeltaWingPressureCoefficient (double inclinationAngle, double machNumber)
Compute pressure coefficient using the Smyth delta wing method.
double computeSpeedOfSound (const double temperature, const double ratioOfSpecificHeats, const double specificGasConstant)
Function to compute the speed of sound in a gas.
double computeStagnationPressure (double machNumber, double ratioOfSpecificHeats)
Compute stagnation pressure coefficient in supersonic flow.
double computeVacuumPressureCoefficient (double machNumber, double ratioOfSpecificHeats)
Compute pressure coefficient at vacuum.
double computeVanDykeUnifiedPressureCoefficient (double inclinationAngle, double machNumber, double ratioOfSpecificHeats, int type)
Compute pressure coefficient using the van Dyke unified method.
Eigen::Vector6d concatenateForceAndMomentCoefficients (const std::function< Eigen::Vector3d(const std::vector< double > &) > &forceCoefficientFunction, const std::function< Eigen::Vector3d(const std::vector< double > &) > &momentCoefficientFunction, const std::vector< double > &independentVariables)
Function to combined the force and moment coefficients from separate function pointers.
std::vector< double > eigenToStlVector (const Eigen::VectorXd &vector)
Function to convert Eigen::VectorXd to std::vector<double>
double exponentialAtmosphereModel (const double altitude, const double longitude, const double latitude, const double time, const double referenceAltitude, const double densityAtReferenceAltitude, const double scaleHeight)
First atmosphere model, based on exponential atmosphere.
void from_json (const nlohmann::json &jsonObject, AtmosphereIndependentVariables &atmosphereIndependentVariable)
Convert json to AtmosphereIndependentVariables.
void from_json (const nlohmann::json &jsonObject, AerodynamicCoefficientsIndependentVariables &aerodynamicVariable)
Convert json to AerodynamicCoefficientsIndependentVariables.
void from_json (const nlohmann::json &jsonObject, AtmosphereDependentVariables &atmosphereDependentVariable)
Convert json to AtmosphereDependentVariables.
std::vector< double > getDefaultHypersonicLocalInclinationAngleOfAttackPoints ()
Returns default values of angle of attack for use in HypersonicLocalInclinationAnalysis.
std::vector< double > getDefaultHypersonicLocalInclinationAngleOfSideslipPoints ()
Returns default values of angle of sideslip for use in HypersonicLocalInclinationAnalysis.
std::vector< double > getDefaultHypersonicLocalInclinationMachPoints (const std::string &machRegime)
Returns default values of mach number for use in HypersonicLocalInclinationAnalysis.
void informUserOnSavedCoefficient (std::vector< unsigned int > coefficientIndices)
Function to print to console which aerodynamic coefficients are being saved.
NRLMSISE00Input nrlmsiseInputFunction (const double altitude, const double longitude, const double latitude, const double time, const tudat::input_output::solar_activity::SolarActivityDataMap &solarActivityMap, const bool adjustSolarTime, const double localSolarTime)
NRLMSISE00Input function.
std::ostream & operator<< (std::ostream &stream, NRLMSISE00Input &nrlmsiseInput)
Overloaded ostream to print class information.
std::shared_ptr< TrimOrientationCalculator > setTrimmedConditions (const std::shared_ptr< AtmosphericFlightConditions > flightConditions)
Function to set the angle of attack to trimmed conditions.
double threeTermAtmosphereModel (const double altitude, const double longitude, const double latitude, const double time, const double referenceAltitude, const double densityAtReferenceAltitude, const double scaleHeight, const std::vector< double > &modelWeights)
Third atmosphere model, based on three constant scale height atmospheres.
double threeWaveAtmosphereModel (const double altitude, const double longitude, const double latitude, const double time, const double referenceAltitude, const double densityAtReferenceAltitude, const double scaleHeight, const double uncertaintyFactor, const double dustStormFactor)
Second atmosphere model, based on a three longitudinal waves model.
void to_json (nlohmann::json &jsonObject, const AtmosphereIndependentVariables &atmosphereIndependentVariable)
Convert AtmosphereIndependentVariables to json.
void to_json (nlohmann::json &jsonObject, const AerodynamicCoefficientsIndependentVariables &aerodynamicVariable)
Convert AerodynamicCoefficientsIndependentVariables to json.
void to_json (nlohmann::json &jsonObject, const AtmosphereDependentVariables &atmosphereDependentVariable)
Convert AtmosphereDependentVariables to json.
Variables
static std::map< AerodynamicCoefficientsIndependentVariables, std::string > aerodynamicVariables
Map of AerodynamicCoefficientsIndependentVariables string representations.
static std::map< AtmosphereDependentVariables, std::string > atmosphereDependentVariables
Map of AtmosphereDependentVariables string representations.
static std::map< AtmosphereIndependentVariables, std::string > atmosphereIndependentVariables
Map of AtmosphereIndependentVariables string representations.
static const double FAY_RIDDEL_HEAT_FLUX_CONSTANT = 3.53E-4
static const double maximumPrandtlMeyerFunctionValue
Maximum Prandtl-Meyer function value.
static const double PrandtlMeyerParameter1 = 1.3604
Constant for use in inverse Prandtl-Meyer function calculation.
static const double PrandtlMeyerParameter2 = 0.0962
Constant for use in inverse Prandtl-Meyer function calculation.
static const double PrandtlMeyerParameter3 = -0.5127
Constant for use in inverse Prandtl-Meyer function calculation.
static const double PrandtlMeyerParameter4 = -0.6722
Constant for use in inverse Prandtl-Meyer function calculation.
static const double PrandtlMeyerParameter5 = -0.3278
Constant for use in inverse Prandtl-Meyer function calculation.
static std::vector< AerodynamicCoefficientsIndependentVariables > unsupportedAerodynamicVariables = { }
AerodynamicCoefficientsIndependentVariables not supported by json_interface.
static std::vector< AtmosphereDependentVariables > unsupportedAtmosphereDependentVariables = { }
AtmosphereDependentVariables not supported by json_interface.
static std::vector< AtmosphereIndependentVariables > unsupportedAtmosphereIndependentVariables = { }
AtmosphereIndependentVariables not supported by json_interface.
Typedef Documentation
AerodynamicAccelerationPointer
typedef std::shared_ptr< AerodynamicAcceleration > tudat::aerodynamics::AerodynamicAccelerationPointer
Definition at line 231 of file aerodynamicAcceleration.h.
AerodynamicCoefficientInterfacePointer
typedef std::shared_ptr< AerodynamicCoefficientInterface > tudat::aerodynamics::AerodynamicCoefficientInterfacePointer
Definition at line 461 of file aerodynamicCoefficientInterface.h.
AtmosphereModelPointer
typedef std::shared_ptr< AtmosphereModel > tudat::aerodynamics::AtmosphereModelPointer
Definition at line 146 of file atmosphereModel.h.
CustomConstantTemperatureAtmospherePointer
typedef std::shared_ptr< CustomConstantTemperatureAtmosphere > tudat::aerodynamics::CustomConstantTemperatureAtmospherePointer
Definition at line 303 of file customConstantTemperatureAtmosphere.h.
ExponentialAtmospherePointer
typedef std::shared_ptr< ExponentialAtmosphere > tudat::aerodynamics::ExponentialAtmospherePointer
Definition at line 254 of file exponentialAtmosphere.h.
HypersonicLocalInclinationAnalysisPointer
typedef std::shared_ptr< HypersonicLocalInclinationAnalysis > tudat::aerodynamics::HypersonicLocalInclinationAnalysisPointer
Definition at line 311 of file hypersonicLocalInclinationAnalysis.h.
StandardAtmospherePointer
typedef std::shared_ptr< StandardAtmosphere > tudat::aerodynamics::StandardAtmospherePointer
Definition at line 85 of file standardAtmosphere.h.
TabulatedAtmospherePointer
typedef std::shared_ptr< TabulatedAtmosphere > tudat::aerodynamics::TabulatedAtmospherePointer
Definition at line 561 of file tabulatedAtmosphere.h.
Enumeration Type Documentation
AerodynamicCoefficientsIndependentVariables
enum tudat::aerodynamics::AerodynamicCoefficientsIndependentVariables
Enum defining a list of independent variables on which the aerodynamic coefficients can depend. Note that for a custom coefficient interface with other variables, you may use the undefined_independent_variable variable type, but at the expense of being able to use the FlightConditions class to automatically updates the aerodynamic coefficients during propagation.
Enumerator
mach_number_dependent
angle_of_attack_dependent
angle_of_sideslip_dependent
altitude_dependent
control_surface_deflection_dependent
undefined_independent_variable
Definition at line 45 of file aerodynamics.h.
AtmosphereIndependentVariables
enum tudat::aerodynamics::AtmosphereIndependentVariables
Enum of all the possible independent variables on which the atmosphere can depend.
Enumerator
altitude_dependent_atmosphere
longitude_dependent_atmosphere
latitude_dependent_atmosphere
time_dependent_atmosphere
Definition at line 30 of file atmosphereModel.h.
AtmosphereDependentVariables
enum tudat::aerodynamics::AtmosphereDependentVariables
Enum of all the possible dependent variables that an atmosphere can describe.
Enumerator
density_dependent_atmosphere
pressure_dependent_atmosphere
temperature_dependent_atmosphere
gas_constant_dependent_atmosphere
specific_heat_ratio_dependent_atmosphere
molar_mass_dependent_atmosphere
Definition at line 42 of file atmosphereModel.h.
AvailableConstantTemperatureAtmosphereModels
enum tudat::aerodynamics::AvailableConstantTemperatureAtmosphereModels
Enumerator
exponential_atmosphere_model
three_wave_atmosphere_model
three_term_atmosphere_model
Definition at line 41 of file customConstantTemperatureAtmosphere.h.
BodiesWithPredefinedExponentialAtmospheres
enum tudat::aerodynamics::BodiesWithPredefinedExponentialAtmospheres
Bodies with predefined exponential atmospheres.
Enumerator
undefined_body
earth
mars
Definition at line 41 of file exponentialAtmosphere.h.
Function Documentation
computeAerodynamicAcceleration() [1/2]
Eigen::Vector3d tudat::aerodynamics::computeAerodynamicAcceleration (const double dynamicPressure, const double referenceArea, const Eigen::Vector3d & aerodynamicCoefficients, const double vehicleMass)
This function computes the aerodynamic acceleration. It takes primitive types as arguments to perform the calculations. Therefore, these quantities (dynamic pressure, reference area and aerodynamic coefficients) have to computed before passing them to this function.
Parameters
dynamicPressure Dynamic pressure at which the body undergoing the acceleration flies.
referenceArea Reference area of the aerodynamic coefficients.
aerodynamicCoefficients Aerodynamic coefficients in right-handed reference frame.
vehicleMass Mass of vehicle undergoing acceleration.
Returns
Resultant aerodynamic acceleration, given in reference frame in which the aerodynamic coefficients were given (assuming coefficients in positive direction).
Definition at line 20 of file aerodynamicAcceleration.cpp.
References computeAerodynamicForce().
Referenced by tudat::aerodynamics::AerodynamicAcceleration::getAcceleration().
computeAerodynamicAcceleration() [2/2]
Eigen::Vector3d tudat::aerodynamics::computeAerodynamicAcceleration (const double dynamicPressure, AerodynamicCoefficientInterfacePointer coefficientInterface, const double vehicleMass)
This function computes the aerodynamic acceleration. It takes the dynamic pressure and an aerodynamic coefficient interface as input. The coefficient interface has to have been updated with current vehicle conditions before being passed to this function. Aerodynamic coefficients and reference area are then retrieved from it.
Parameters
dynamicPressure Dynamic pressure at which the body undergoing the acceleration flies.
coefficientInterface AerodynamicCoefficientInterface class from which reference area and coefficients are retrieved.
vehicleMass Mass of vehicle undergoing acceleration.
Returns
Resultant aerodynamic acceleration, given in reference frame in which the aerodynamic coefficients were given (assuming coefficients in positive direction).
Definition at line 30 of file aerodynamicAcceleration.cpp.
References computeAerodynamicForce().
informUserOnSavedCoefficient()
void tudat::aerodynamics::informUserOnSavedCoefficient (std::vector< unsigned int > coefficientIndices)
Function to print to console which aerodynamic coefficients are being saved.
Parameters
coefficientIndices Indices of coefficients to be saved.
Definition at line 21 of file aerodynamicCoefficientGenerator.cpp.
Referenced by tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >::saveAerodynamicCoefficientsTables().
computeAerodynamicForce() [1/2]
Eigen::Vector3d tudat::aerodynamics::computeAerodynamicForce (const double dynamicPressure, const double referenceArea, const Eigen::Vector3d & aerodynamicCoefficients)
This function calculates the aerodynamic force. It takes primitive types as arguments to perform the calculations. Therefore, these quantities (dynamicPressure, reference area and aerodynamic coefficients) have to computed before passing them to this function.
Parameters
dynamicPressure Dynamic pressure at which the body undergoing the force flies.
referenceArea Reference area of the aerodynamic coefficients.
aerodynamicCoefficients Aerodynamic coefficients in right-handed reference frame.
Returns
Resultant aerodynamic force, given in reference frame in which the aerodynamic coefficients were given.
Definition at line 19 of file aerodynamicForce.cpp.
Referenced by computeAerodynamicAcceleration(), and computeAerodynamicForce().
computeAerodynamicForce() [2/2]
Eigen::Vector3d tudat::aerodynamics::computeAerodynamicForce (const double dynamicPressure, AerodynamicCoefficientInterfacePointer coefficientInterface)
This function calculates the aerodynamic force. It takes the dynamic pressure and an aerodynamic coefficient interface as input. The coefficient interface has to have been updated with current vehicle conditions before being passed to this function. Aerodynamic coefficients and reference area are then retrieved from it.
Parameters
dynamicPressure Dynamic pressure at which the body undergoing the force flies.
coefficientInterface AerodynamicCoefficientInterface class from which reference area and coefficients are retrieved.
Returns
Resultant aerodynamic force, given in reference frame in which the aerodynamic coefficients were given.
Definition at line 38 of file aerodynamicForce.cpp.
References computeAerodynamicForce().
computeLocalToStaticPressureRatio()
double tudat::aerodynamics::computeLocalToStaticPressureRatio (double machNumber, double ratioOfSpecificHeats)
Computes the local to static pressure ratio, assuming a thermally and calorically perfect gas.
Parameters
machNumber Flow Mach number.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
Returns
Local-to-static pressure ratio.
Definition at line 41 of file aerodynamics.cpp.
Referenced by computePrandtlMeyerFreestreamPressureCoefficient().
computePrandtlMeyerFunction()
double tudat::aerodynamics::computePrandtlMeyerFunction (double machNumber, double ratioOfSpecificHeats)
Computes the value of the Prandtl-Meyer function at the given Mach number and ratio of specific heat.
Parameters
machNumber Flow Mach number.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
Returns
Prandtl-Meyer function value.
Definition at line 50 of file aerodynamics.cpp.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateExpansionPressures().
computeStagnationPressure()
double tudat::aerodynamics::computeStagnationPressure (double machNumber, double ratioOfSpecificHeats)
Computes the stagnation pressure coefficient, assuming a thermally and calorically perfect gas.
Parameters
machNumber Flow Mach number.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
Returns
Stagnation pressure coefficient.
Definition at line 64 of file aerodynamics.cpp.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::determinePressureCoefficients().
computeNewtonianPressureCoefficient()
double tudat::aerodynamics::computeNewtonianPressureCoefficient (double inclinationAngle)
Computes the pressure coefficient based on Newtonian theory.
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
Returns
Newtonian pressure coefficient.
Definition at line 83 of file aerodynamics.cpp.
Referenced by computeModifiedDahlemBuckPressureCoefficient(), and tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures().
computeModifiedNewtonianPressureCoefficient()
double tudat::aerodynamics::computeModifiedNewtonianPressureCoefficient (double inclinationAngle, double stagnationPressureCoefficient)
Computes the pressure coefficient based on modified Newtonian theory.
Parameters
inclinationAngle Angle between the wall and the freestream velocity vector.
stagnationPressureCoefficient Stagnation pressure coefficient.
Returns
Newtonian pressure coefficient.
Definition at line 90 of file aerodynamics.cpp.
Referenced by computeHankeyFlatSurfacePressureCoefficient(), and tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures().
computeEmpiricalTangentWedgePressureCoefficient()
double tudat::aerodynamics::computeEmpiricalTangentWedgePressureCoefficient (double inclinationAngle, double machNumber)
Computes tangent wedge pressure coefficient based on empirical correlation for ratio of specific heats = 1.4 (terrestrial atmosphere).
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
machNumber Flow Mach number.
Returns
Empirical tangent wedge pressure coefficient.
Definition at line 98 of file aerodynamics.cpp.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures().
computeEmpiricalTangentConePressureCoefficient()
double tudat::aerodynamics::computeEmpiricalTangentConePressureCoefficient (double inclinationAngle, double machNumber)
Computes tangent cone pressure coefficient based on empirical correlation for ratio of specific heats = 1.4 (terrestrial atmosphere).
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
machNumber Flow Mach number.
Returns
Empirical tangent wedge pressure coefficient.
Definition at line 113 of file aerodynamics.cpp.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures().
computeModifiedDahlemBuckPressureCoefficient()
double tudat::aerodynamics::computeModifiedDahlemBuckPressureCoefficient (double inclinationAngle, double machNumber)
Computes tangent cone pressure coefficient based on Dahlem-Buck empirical method.
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
machNumber Flow Mach number.
Returns
Dahlem-Buck pressure coefficient.
Definition at line 131 of file aerodynamics.cpp.
References computeNewtonianPressureCoefficient(), and tudat::mathematical_constants::PI.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures().
computeHankeyFlatSurfacePressureCoefficient()
double tudat::aerodynamics::computeHankeyFlatSurfacePressureCoefficient (double inclinationAngle, double machNumber)
Computes tangent cone pressure coefficient based on the Hankey flat surface method.
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
machNumber Flow Mach number.
Returns
Hankey Flat surface pressure coefficient.
Definition at line 179 of file aerodynamics.cpp.
References computeModifiedNewtonianPressureCoefficient(), and tudat::mathematical_constants::PI.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures().
computeSmythDeltaWingPressureCoefficient()
double tudat::aerodynamics::computeSmythDeltaWingPressureCoefficient (double inclinationAngle, double machNumber)
Computes tangent cone pressure coefficient based on the Smyth delta wing surface method.
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
machNumber Flow Mach number.
Returns
Smyth delta wing pressure coefficient.
Definition at line 207 of file aerodynamics.cpp.
References tudat::mathematical_constants::PI.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures().
computeVanDykeUnifiedPressureCoefficient()
double tudat::aerodynamics::computeVanDykeUnifiedPressureCoefficient (double inclinationAngle, double machNumber, double ratioOfSpecificHeats, int type)
Computes tangent cone pressure coefficient based on the van Dyke unified method.
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
machNumber Flow Mach number.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
type (expansion (1) or compression(-1)).
Returns
Hankey Flat surface pressure coefficient.
Definition at line 236 of file aerodynamics.cpp.
References computeVacuumPressureCoefficient().
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures().
computePrandtlMeyerFreestreamPressureCoefficient()
double tudat::aerodynamics::computePrandtlMeyerFreestreamPressureCoefficient (double inclinationAngle, double machNumber, double ratioOfSpecificHeats, double freestreamPrandtlMeyerFunction)
Computes pressure coefficient using Prandtl-Meyer expansion from freestream. Currently only terrestrial atmosphere (ratio of specific heat = 1.4) is supported due to the use of an empirical fit for the inverse Prandtl-Meyer function determination.
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
machNumber Flow Mach number.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
freestreamPrandtlMeyerFunction Freestream Prandtl-Meyer function.
Returns
Prandtl-Meyer pressure coefficient.
Definition at line 290 of file aerodynamics.cpp.
References computeInversePrandtlMeyerFunction(), computeLocalToStaticPressureRatio(), computeVacuumPressureCoefficient(), and maximumPrandtlMeyerFunctionValue.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateExpansionPressures().
computeVacuumPressureCoefficient()
double tudat::aerodynamics::computeVacuumPressureCoefficient (double machNumber, double ratioOfSpecificHeats)
Computes the pressure coefficient at vacuum assuming a thermally and calorically perfect gas.
Parameters
machNumber Flow Mach number.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
Returns
Vacuum pressure coefficient.
Definition at line 332 of file aerodynamics.cpp.
Referenced by computePrandtlMeyerFreestreamPressureCoefficient(), computeVanDykeUnifiedPressureCoefficient(), and tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateExpansionPressures().
computeHighMachBasePressure()
double tudat::aerodynamics::computeHighMachBasePressure (double machNumber)
This function calculates the high Mach base pressure coefficient approximation.
Parameters
machNumber Flow Mach number.
Returns
Vacuum pressure coefficient.
Definition at line 340 of file aerodynamics.cpp.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateExpansionPressures().
computeAcmEmpiricalPressureCoefficient()
double tudat::aerodynamics::computeAcmEmpiricalPressureCoefficient (double inclinationAngle, double machNumber)
Computes tangent cone pressure coefficient based on the ACM empirical method.
Parameters
inclinationAngle Angle between wall and freestream velocity vector.
machNumber Flow Mach number.
Returns
ACM empirical surface pressure coefficient.
Definition at line 347 of file aerodynamics.cpp.
References tudat::mathematical_constants::PI.
Referenced by tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateExpansionPressures().
computeInversePrandtlMeyerFunction()
double tudat::aerodynamics::computeInversePrandtlMeyerFunction (double prandtlMeyerFunctionValue)
Computes the inverse of the Prandtl-Meyer function. Currently the function is limited to use with ratio of specific heats of 1.4 as it uses an empirical correlation.
Parameters
prandtlMeyerFunctionValue Prandyl-Meyer function value.
Returns
Mach number.
Definition at line 378 of file aerodynamics.cpp.
References maximumPrandtlMeyerFunctionValue, PrandtlMeyerParameter1, PrandtlMeyerParameter2, PrandtlMeyerParameter3, PrandtlMeyerParameter4, and PrandtlMeyerParameter5.
Referenced by computePrandtlMeyerFreestreamPressureCoefficient().
computeShockPressureRatio()
double tudat::aerodynamics::computeShockPressureRatio (double normalMachNumber, double ratioOfSpecificHeats)
Computes ratio of post- to pre-shock pressure, assuming thermally and calorically perfect gas.
Parameters
normalMachNumber Mach number of flow velocity normal to shock.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
Definition at line 402 of file aerodynamics.cpp.
Referenced by computeShockEntropyJump(), and computeShockTemperatureRatio().
computeShockDensityRatio()
double tudat::aerodynamics::computeShockDensityRatio (double normalMachNumber, double ratioOfSpecificHeats)
Compute ratio of post- to pre-shock density, assuming thermally and calorically perfect gas.
Parameters
normalMachNumber Mach number of flow velocity normal to shock.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
Definition at line 411 of file aerodynamics.cpp.
Referenced by computeShockTemperatureRatio().
computeShockTemperatureRatio()
double tudat::aerodynamics::computeShockTemperatureRatio (double normalMachNumber, double ratioOfSpecificHeats)
Computes ratio of post- to pre-shock temperature, assuming thermally and calorically perfect gas.
Parameters
normalMachNumber Mach number of flow velocity normal to shock.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
Definition at line 426 of file aerodynamics.cpp.
References computeShockDensityRatio(), and computeShockPressureRatio().
Referenced by computeShockEntropyJump().
computeShockEntropyJump()
double tudat::aerodynamics::computeShockEntropyJump (double normalMachNumber, double ratioOfSpecificHeats, double specificGasConstant)
Compute jump in entropy across a shock wave, assuming thermally and calorically perfect gas.
Parameters
normalMachNumber Mach number of flow velocity normal to shock.
ratioOfSpecificHeats ratio of specific heat at constant pressure to specific heat at constant volume.
specificGasConstant gas constant per unit mass for flow composition.
Definition at line 435 of file aerodynamics.cpp.
References computeShockPressureRatio(), and computeShockTemperatureRatio().
Referenced by computeShockTotalPressureRatio().
computeShockTotalPressureRatio()
double tudat::aerodynamics::computeShockTotalPressureRatio (double normalMachNumber, double ratioOfSpecificHeats, double specificGasConstant)
Compute post- to pre-shock total pressure ratio from the entropy jump across a shock wave. Assumption of thermally and calorically perfect gas is made.
Parameters
normalMachNumber Mach number of flow velocity normal to shock.
ratioOfSpecificHeats ratio of specific heat at constant pressure to specific heat at constant volume.
specificGasConstant gas constant per unit mass for flow composition.
Definition at line 454 of file aerodynamics.cpp.
References computeShockEntropyJump().
computeShockDeflectionAngle()
double tudat::aerodynamics::computeShockDeflectionAngle (double shockAngle, double machNumber, double ratioOfSpecificHeats)
Computes the flow deflection angle across a shock wave.
Parameters
shockAngle Angle of shock wave w.r.t. freestream flow.
machNumber Freestream Mach number.
ratioOfSpecificHeats Ratio of specific heat at constant pressure to specific heat at constant volume.
Definition at line 464 of file aerodynamics.cpp.
computeSpeedOfSound()
double tudat::aerodynamics::computeSpeedOfSound (const double temperature, const double ratioOfSpecificHeats, const double specificGasConstant)
Function to compute the speed of sound in a gas
Parameters
temperature Gas temperature
ratioOfSpecificHeats Ratio of specific heats aat constant pressure and constant volume
specificGasConstant Specific gas constant of the gas
Returns
Speed of sound in the gas.
Definition at line 481 of file aerodynamics.cpp.
Referenced by tudat::aerodynamics::NRLMSISE00Atmosphere::computeProperties(), tudat::aerodynamics::ExponentialAtmosphere::getSpeedOfSound(), tudat::aerodynamics::CustomConstantTemperatureAtmosphere::getSpeedOfSound(), and tudat::aerodynamics::TabulatedAtmosphere::getSpeedOfSound().
computeMachNumber()
double tudat::aerodynamics::computeMachNumber (const double speed, const double speedOfSound)
Compute Mach number
Parameters
speed Airspeed of object for which Mach number is to be computed.
speedOfSound Speed of sound for atmosphere position at which Mach number is to be computed.
Returns
Mach number
Definition at line 488 of file aerodynamics.cpp.
Referenced by tudat::propagators::getDoubleDependentVariableFunction().
computeMeanFreePath()
double tudat::aerodynamics::computeMeanFreePath (const double weightedAverageCollisionDiameter, const double averageNumberDensity)
Function to compute the mean free path of a particle from e.g. (Chapman, S. & Cowling, T. The mathematical theory of nonuniform gases Cambridge University Press, 1970)
Parameters
weightedAverageCollisionDiameter Weighted (using specie number density) average collision diameter of the particles in the gas.
averageNumberDensity Average number density of the gas.
Returns
Mean free path of a particle in the gas.
Definition at line 494 of file aerodynamics.cpp.
References tudat::mathematical_constants::PI.
Referenced by tudat::aerodynamics::NRLMSISE00Atmosphere::computeProperties().
computeAerodynamicLoad()
double tudat::aerodynamics::computeAerodynamicLoad (const double airDensity, const double airSpeed, const double referenceArea, const double vehicleMass, const Eigen::Vector3d & aerodynamicForceCoefficients)
Function to compute the aerodynamic load experienced by a vehicle.
Function that computes the aerodynamic load (a.k.a. load factor) experienced by a vehicle.
Parameters
airDensity Freestream air density.
airSpeed Airspeed of the vehicle.
referenceArea Reference area of the vehicle.
vehicleMass Mass of the vehicle.
aerodynamicForceCoefficients Aerodynamic force coefficients of the vehicle.
Returns
Aerodynamic load experienced by the vehicle.
Definition at line 501 of file aerodynamics.cpp.
References computeAerodynamicLoadFromAcceleration().
computeAerodynamicLoadFromAcceleration()
double tudat::aerodynamics::computeAerodynamicLoadFromAcceleration (const Eigen::Vector3d & aerodynamicAccelerationVector)
Function that computes the aerodynamic load (a.k.a. load factor) experienced by a vehicle.
Parameters
aerodynamicAccelerationVector Aerodynamic acceleration actinv on vehicle.
Returns
Aerodynamic load experienced by the vehicle.
Definition at line 513 of file aerodynamics.cpp.
References tudat::physical_constants::SEA_LEVEL_GRAVITATIONAL_ACCELERATION.
Referenced by computeAerodynamicLoad(), and tudat::propagators::getDoubleDependentVariableFunction().
computeEquilibriumHeatflux()
double tudat::aerodynamics::computeEquilibriumHeatflux (const std::function< double(const double) > heatTransferFunction, const double wallEmmisivity, const double adiabaticWallTemperature)
Funtion to compute the equilibrium heat flux experienced by a vehicle.
Parameters
heatTransferFunction Function returning the feat flux as a function of wall temperature.
wallEmmisivity Emmissivity of the wall to which heat transfer is taking place
adiabaticWallTemperature Adiabatic wall temperature (used only for initialization of root finder).
Returns
Convective heat flux experienced acording to Fay Riddell model at equilibrium wall temperature.
Definition at line 519 of file aerodynamics.cpp.
References computeEquilibiumWallTemperature().
Referenced by computeEquilibriumFayRiddellHeatFlux().
computeEquilibriumFayRiddellHeatFlux()
double tudat::aerodynamics::computeEquilibriumFayRiddellHeatFlux (const double airDensity, const double airSpeed, const double airTemperature, const double machNumber, const double noseRadius, const double wallEmissivity = 0.80)
Function that computes the heat flux experienced by a vehicle. This function is an implementation of the Fay-Riddell formula, assuming an equlibrium wall temperature
Parameters
airDensity Freestream density of the air.
airSpeed Airspeed of the vehicle.
airTemperature Freestream air temperature.
machNumber Freestream Mach number.
noseRadius Nose radius of the vehicle.
wallEmissivity Wall emissivity of the vehicle.
Returns
Convective heat flux experienced by the vehicle.
Definition at line 528 of file aerodynamics.cpp.
References computeAdiabaticWallTemperature(), computeEquilibriumHeatflux(), and computeFayRiddellHeatFlux().
Referenced by tudat::propagators::computeEquilibriumFayRiddellHeatFluxFromProperties().
computeFayRiddellHeatFlux()
double tudat::aerodynamics::computeFayRiddellHeatFlux (const double airDensity, const double airSpeed, const double airTemperature, const double noseRadius, const double wallTemperature)
Function that computes the heat flux experienced by a vehicle. This function is an implementation of the Fay-Riddell formula.
Parameters
airDensity Freestream density of the air.
airSpeed Airspeed of the vehicle.
airTemperature Freestream air temperature.
noseRadius Nose radius of the vehicle.
wallTemperature Temperature at the wall of the vehicle.
Returns
Convective heat flux experienced by the vehicle.
Definition at line 546 of file aerodynamics.cpp.
References FAY_RIDDEL_HEAT_FLUX_CONSTANT.
Referenced by computeEquilibriumFayRiddellHeatFlux().
computeAdiabaticWallTemperature()
double tudat::aerodynamics::computeAdiabaticWallTemperature (const double airTemperature, const double machNumber, const double ratioSpecificHeats = 1.4, const double recoveryFactor = 0.845)
Function to compute the adiabatic wall temperature experienced by a vehicle.
Function that computes the adiabatic wall temperature experienced by a vehicle.
Parameters
airTemperature Freestream air temperature.
machNumber Freestream Mach number.
ratioSpecificHeats Ratio of specific heats of the air.
recoveryFactor Recovery factor of flow, e.g. fraction of total enthalpy contribution from velocoty that can be recovered at the wal
Returns
Adiabatic wall temperature experienced by the vehicle.
Definition at line 558 of file aerodynamics.cpp.
Referenced by computeEquilibriumFayRiddellHeatFlux().
concatenateForceAndMomentCoefficients()
Eigen::Vector6d tudat::aerodynamics::concatenateForceAndMomentCoefficients (const std::function< Eigen::Vector3d(const std::vector< double > &) > & forceCoefficientFunction, const std::function< Eigen::Vector3d(const std::vector< double > &) > & momentCoefficientFunction, const std::vector< double > & independentVariables) inline
Function to combined the force and moment coefficients from separate function pointers. The output is the concatenated force and moment coefficient vector, evaluated at the current set of independent variables.
Parameters
forceCoefficientFunction Function returning the aerodynamic force coefficients as function of the set of independent variables.
momentCoefficientFunction Function returning the aerodynamic force coefficients as function of the set of independent variables.
independentVariables Current list of values of the independent variables upon which the coefficients depend.
Definition at line 67 of file aerodynamics.h.
Referenced by tudat::aerodynamics::CustomAerodynamicCoefficientInterface::CustomAerodynamicCoefficientInterface(), and tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::CustomControlSurfaceIncrementAerodynamicInterface().
computeAerodynamicMoment() [1/3]
Eigen::Vector3d tudat::aerodynamics::computeAerodynamicMoment (const double dynamicPressure, const double referenceArea, const double referenceLength, const Eigen::Vector3d & momentCoefficients)
Compute the aerodynamic moment in same reference frame as input coefficients, with same reference lengths for each axis.
This function calculates the aerodynamic moment. It takes primitive types as arguments to perform the calculations. Therefor, these quantities (dynamic pressure, reference area, reference length and aerodynamic coefficients) have to computed before passing them to this function.
Parameters
dynamicPressure Dynamic pressure at which the body undergoing the force flies.
referenceArea Reference area of the aerodynamic coefficients.
referenceLength Reference length of the aerodynamic coefficients. Note that this reference length is used for all three independent directions.
momentCoefficients Aerodynamic moment coefficients in right-handed reference frame.
Returns
Resultant aerodynamic moment, given in reference frame in which the aerodynamic coefficients were given, but with opposite sign. i.e., a positive drag coefficient will give a negative force in -x direction (in the aerodynamic frame).
Definition at line 20 of file aerodynamicTorque.cpp.
Referenced by computeAerodynamicMoment(), and tudat::aerodynamics::AerodynamicTorque::updateMembers().
computeAerodynamicMoment() [2/3]
Eigen::Vector3d tudat::aerodynamics::computeAerodynamicMoment (const double dynamicPressure, const double referenceArea, const Eigen::Vector3d & referenceLengths, const Eigen::Vector3d & momentCoefficients)
Compute the aerodynamic moment in same reference frame as input coefficients, with different reference lengths for each axis.
This function calculates the aerodynamic moment. It takes primitive types as arguments to perform the calculations. Therefor, these quantities (dynamic pressure, reference area, reference lengths and aerodynamic coefficients) have to computed before passing them to this function.
Parameters
dynamicPressure Dynamic pressure at which the body undergoing the force flies.
referenceArea Reference area of the aerodynamic coefficients.
referenceLengths Reference lengths of the aerodynamic coefficients, used in x, y and z directions.
momentCoefficients Aerodynamic moment coefficients in right-handed reference frame.
Returns
Resultant aerodynamic moment, given in reference frame in which the aerodynamic coefficients were given, but with opposite sign. i.e., a positive drag coefficient will give a negative force in -x direction (in the aerodynamic frame).
Definition at line 28 of file aerodynamicTorque.cpp.
computeAerodynamicMoment() [3/3]
Eigen::Vector3d tudat::aerodynamics::computeAerodynamicMoment (const double dynamicPressure, AerodynamicCoefficientInterfacePointer coefficientInterface)
Compute the aerodynamic moment in same reference frame as input coefficients.
This function calculates the aerodynamic moment. It takes the dynamic pressure and an aerodynamic coefficient interface as input. The coefficient interface has to have been updated with current vehicle conditions before being passed to this function. Aerodynamic coefficients and reference area and length are then retrieved from it.
Parameters
dynamicPressure Dynamic pressure at which the body undergoing the force flies.
coefficientInterface AerodynamicCoefficientInterface class from which reference area and length, and the moment coefficients are retrieved.
Returns
Resultant aerodynamic moment, given in reference frame in which the aerodynamic coefficients were given.
Definition at line 36 of file aerodynamicTorque.cpp.
References computeAerodynamicMoment().
exponentialAtmosphereModel()
double tudat::aerodynamics::exponentialAtmosphereModel (const double altitude, const double longitude, const double latitude, const double time, const double referenceAltitude, const double densityAtReferenceAltitude, const double scaleHeight)
First atmosphere model, based on exponential atmosphere.
Parameters
altitude Current altitude.
longitude Current longitude (unused).
latitude Current latitude (unused).
time Current time (unused).
referenceAltitude Reference altitude.
densityAtReferenceAltitude Density at reference altitude condition.
scaleHeight Scale height of the atmosphere.
Returns
Density at current conditions, based on the exponential model with given characteristics.
Definition at line 12 of file customConstantTemperatureAtmosphere.cpp.
References TUDAT_UNUSED_PARAMETER.
Referenced by tudat::simulation_setup::createAtmosphereModel(), tudat::aerodynamics::CustomConstantTemperatureAtmosphere::CustomConstantTemperatureAtmosphere(), and threeWaveAtmosphereModel().
threeWaveAtmosphereModel()
double tudat::aerodynamics::threeWaveAtmosphereModel (const double altitude, const double longitude, const double latitude, const double time, const double referenceAltitude, const double densityAtReferenceAltitude, const double scaleHeight, const double uncertaintyFactor, const double dustStormFactor)
Second atmosphere model, based on a three longitudinal waves model. The parameters for the three longitudinal waves are hard coded in the function. Based on (Justus, et al., 2004).
Parameters
altitude Current altitude.
longitude Current longitude.
latitude Current latitude (unused).
time Current time (unused).
referenceAltitude Reference altitude.
densityAtReferenceAltitude Density at reference altitude condition.
scaleHeight Scale height of the atmosphere.
uncertaintyFactor Factor representing uncertainty in the atmosphere. Can be a random variable.
dustStormFactor Factor representing presence of planet-wide dust storm (particularly useful for Mars applications).
Returns
Density at current conditions, based on the three-waves model with given characteristics.
Definition at line 23 of file customConstantTemperatureAtmosphere.cpp.
References tudat::unit_conversions::convertDegreesToRadians(), and exponentialAtmosphereModel().
Referenced by tudat::aerodynamics::CustomConstantTemperatureAtmosphere::CustomConstantTemperatureAtmosphere().
threeTermAtmosphereModel()
double tudat::aerodynamics::threeTermAtmosphereModel (const double altitude, const double longitude, const double latitude, const double time, const double referenceAltitude, const double densityAtReferenceAltitude, const double scaleHeight, const std::vector< double > & modelWeights)
Third atmosphere model, based on three constant scale height atmospheres. The first term is the same as for the exponential model, whereas the other two are a sine and a cosine term. Based on (Jah, et al., 2008).
Parameters
altitude Current altitude.
longitude Current longitude (unused).
latitude Current latitude (unused).
time Current time (unused).
referenceAltitude Reference altitude.
densityAtReferenceAltitude Density at reference altitude condition.
scaleHeight Scale height of the atmosphere.
modelWeights Weights for each of the three models.
Returns
Density at current conditions, based on the exponential model with given characteristics.
Definition at line 37 of file customConstantTemperatureAtmosphere.cpp.
References tudat::mathematical_constants::PI, and TUDAT_UNUSED_PARAMETER.
Referenced by tudat::aerodynamics::CustomConstantTemperatureAtmosphere::CustomConstantTemperatureAtmosphere().
computeEquilibiumWallTemperature()
double tudat::aerodynamics::computeEquilibiumWallTemperature (const std::function< double(const double) > heatTransferFunction, const double wallEmmisivity, const double adiabaticWallTemperature)
Function to compute the equilibrium wall temperature from the heat input and emmisivity. This function calls a root- finder to determine the wall temperature where the heat input equals the radiative output.
Parameters
heatTransferFunction Function that returns the heat input as a function of current temperature
wallEmmisivity Value of the material emmisivity
adiabaticWallTemperature Adiabatic wall temperature. This variables is only used as an upper bound, and to generate an initial giess for the equilibrium temperature
Returns
Wall temperature at which input and output of heat are in equilibrium.
Definition at line 23 of file equilibriumWallTemperature.cpp.
References tudat::root_finders::BisectionCore< DataType >::execute(), tudat::root_finders::SecantRootFinderCore< DataType >::execute(), and TUDAT_NAN.
Referenced by computeEquilibriumHeatflux().
setTrimmedConditions()
std::shared_ptr< TrimOrientationCalculator > tudat::aerodynamics::setTrimmedConditions (const std::shared_ptr< AtmosphericFlightConditions > flightConditions)
Definition at line 240 of file flightConditions.cpp.
References tudat::aerodynamics::TrimOrientationCalculator::findTrimAngleOfAttackFromFunction(), tudat::aerodynamics::AtmosphericFlightConditions::getAerodynamicCoefficientIndependentVariables(), and tudat::aerodynamics::AtmosphericFlightConditions::getControlSurfaceAerodynamicCoefficientIndependentVariables().
getDefaultHypersonicLocalInclinationMachPoints()
std::vector< double > tudat::aerodynamics::getDefaultHypersonicLocalInclinationMachPoints (const std::string & machRegime)
Returns default values of mach number for use in HypersonicLocalInclinationAnalysis.
Definition at line 45 of file hypersonicLocalInclinationAnalysis.cpp.
getDefaultHypersonicLocalInclinationAngleOfAttackPoints()
std::vector< double > tudat::aerodynamics::getDefaultHypersonicLocalInclinationAngleOfAttackPoints ()
Returns default values of angle of attack for use in HypersonicLocalInclinationAnalysis.
Definition at line 87 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::mathematical_constants::PI.
getDefaultHypersonicLocalInclinationAngleOfSideslipPoints()
std::vector< double > tudat::aerodynamics::getDefaultHypersonicLocalInclinationAngleOfSideslipPoints ()
Returns default values of angle of sideslip for use in HypersonicLocalInclinationAnalysis.
Definition at line 104 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::mathematical_constants::PI.
operator<<()
std::ostream& tudat::aerodynamics::operator<< (std::ostream & stream, NRLMSISE00Input & nrlmsiseInput)
Definition at line 120 of file nrlmsise00Atmosphere.cpp.
References tudat::aerodynamics::NRLMSISE00Input::apDaily, tudat::aerodynamics::NRLMSISE00Input::apVector, tudat::aerodynamics::NRLMSISE00Input::dayOfTheYear, tudat::aerodynamics::NRLMSISE00Input::f107, tudat::aerodynamics::NRLMSISE00Input::f107a, tudat::aerodynamics::NRLMSISE00Input::localSolarTime, tudat::aerodynamics::NRLMSISE00Input::secondOfTheDay, tudat::aerodynamics::NRLMSISE00Input::switches, and tudat::aerodynamics::NRLMSISE00Input::year.
eigenToStlVector()
std::vector< double > tudat::aerodynamics::eigenToStlVector (const Eigen::VectorXd & vector)
Definition at line 24 of file nrlmsise00InputFunctions.cpp.
Referenced by nrlmsiseInputFunction().
nrlmsiseInputFunction()
NRLMSISE00Input tudat::aerodynamics::nrlmsiseInputFunction (const double altitude, const double longitude, const double latitude, const double time, const tudat::input_output::solar_activity::SolarActivityDataMap & solarActivityMap, const bool adjustSolarTime = false, const double localSolarTime = 0.0)
NRLMSISE00 Input function.
This function is used to define the input for the NRLMSISE model. This function reads solar activity data and defines the input using this data.
Parameters
altitude Altitude at which output is to be computed [m].
longitude Longitude at which output is to be computed [rad].
latitude Latitude at which output is to be computed [rad].
time Time at which output is to be computed (seconds since J2000).
solarActivityMap SolarActivityData structure
adjustSolarTime Boolean denoting whether the computed local solar time should be overidden with localSolarTime input.
localSolarTime Local solar time that is used when adjustSolarTime is set to true.
Returns
NRLMSISE00Input nrlmsiseInputFunction
Definition at line 36 of file nrlmsise00InputFunctions.cpp.
References tudat::aerodynamics::NRLMSISE00Input::apDaily, tudat::aerodynamics::NRLMSISE00Input::apVector, tudat::basic_astrodynamics::convertCalendarDateToJulianDay(), tudat::basic_astrodynamics::convertJulianDayToSecondsSinceEpoch(), tudat::basic_astrodynamics::convertSecondsSinceEpochToJulianDay(), tudat::aerodynamics::NRLMSISE00Input::dayOfTheYear, eigenToStlVector(), tudat::aerodynamics::NRLMSISE00Input::f107, tudat::aerodynamics::NRLMSISE00Input::f107a, tudat::basic_astrodynamics::JULIAN_DAY_ON_J2000, tudat::aerodynamics::NRLMSISE00Input::localSolarTime, tudat::mathematical_constants::PI, tudat::aerodynamics::NRLMSISE00Input::secondOfTheDay, and tudat::aerodynamics::NRLMSISE00Input::year.
Referenced by tudat::simulation_setup::createAtmosphereModel().
checkVariableUniqueness()
template<typename VariableType > void tudat::aerodynamics::checkVariableUniqueness (std::vector< VariableType > variables)
Function to check uniqueness of input for (in)dependent variables. The function works by checking that there are no duplicates, after having sorted the vector. For this reason, a local copy of the input vector is taken.
Template Parameters
VariableType Type belonging to the input vector.
Parameters
variables Vector of variables which needs to be checked.
Definition at line 28 of file tabulatedAtmosphere.cpp.
to_json() [1/3]
void tudat::aerodynamics::to_json (nlohmann::json & jsonObject, const AerodynamicCoefficientsIndependentVariables & aerodynamicVariable) inline
Definition at line 41 of file aerodynamics.h.
References aerodynamicVariables, and tudat::json_interface::stringFromEnum().
from_json() [1/3]
void tudat::aerodynamics::from_json (const nlohmann::json & jsonObject, AerodynamicCoefficientsIndependentVariables & aerodynamicVariable) inline
Definition at line 47 of file aerodynamics.h.
References aerodynamicVariables, and tudat::json_interface::enumFromString().
to_json() [2/3]
void tudat::aerodynamics::to_json (nlohmann::json & jsonObject, const AtmosphereIndependentVariables & atmosphereIndependentVariable) inline
Definition at line 39 of file atmosphere.h.
References atmosphereIndependentVariables, and tudat::json_interface::stringFromEnum().
from_json() [2/3]
void tudat::aerodynamics::from_json (const nlohmann::json & jsonObject, AtmosphereIndependentVariables & atmosphereIndependentVariable) inline
Definition at line 45 of file atmosphere.h.
References atmosphereIndependentVariables, and tudat::json_interface::enumFromString().
to_json() [3/3]
void tudat::aerodynamics::to_json (nlohmann::json & jsonObject, const AtmosphereDependentVariables & atmosphereDependentVariable) inline
Definition at line 68 of file atmosphere.h.
References atmosphereDependentVariables, and tudat::json_interface::stringFromEnum().
from_json() [3/3]
void tudat::aerodynamics::from_json (const nlohmann::json & jsonObject, AtmosphereDependentVariables & atmosphereDependentVariable) inline
Definition at line 74 of file atmosphere.h.
References atmosphereDependentVariables, and tudat::json_interface::enumFromString().
Variable Documentation
maximumPrandtlMeyerFunctionValue
const double tudat::aerodynamics::maximumPrandtlMeyerFunctionValue static
Initial value:
=
    mathematical_constants::PI / 2.0 * ( std::sqrt( 6.0 ) - 1.0 )
Maximum Prandtl-Meyer function value for ratio of specific heats = 1.4.
Definition at line 82 of file aerodynamics.h.
Referenced by computeInversePrandtlMeyerFunction(), and computePrandtlMeyerFreestreamPressureCoefficient().
PrandtlMeyerParameter1
const double tudat::aerodynamics::PrandtlMeyerParameter1 = 1.3604 static
Constant for use in inverse Prandtl-Meyer function calculation for ratio of specific heats = 1.4.
Definition at line 90 of file aerodynamics.h.
Referenced by computeInversePrandtlMeyerFunction().
PrandtlMeyerParameter2
const double tudat::aerodynamics::PrandtlMeyerParameter2 = 0.0962 static
Constant for use in inverse Prandtl-Meyer function calculation for ratio of specific heats = 1.4.
Definition at line 97 of file aerodynamics.h.
Referenced by computeInversePrandtlMeyerFunction().
PrandtlMeyerParameter3
const double tudat::aerodynamics::PrandtlMeyerParameter3 = -0.5127 static
Constant for use in inverse Prandtl-Meyer function calculation for ratio of specific heats = 1.4.
Definition at line 104 of file aerodynamics.h.
Referenced by computeInversePrandtlMeyerFunction().
PrandtlMeyerParameter4
const double tudat::aerodynamics::PrandtlMeyerParameter4 = -0.6722 static
Constant for use in inverse Prandtl-Meyer function calculation for ratio of specific heats = 1.4.
Definition at line 111 of file aerodynamics.h.
Referenced by computeInversePrandtlMeyerFunction().
PrandtlMeyerParameter5
const double tudat::aerodynamics::PrandtlMeyerParameter5 = -0.3278 static
Constant for use in inverse Prandtl-Meyer function calculation for ratio of specific heats = 1.4.
Definition at line 118 of file aerodynamics.h.
Referenced by computeInversePrandtlMeyerFunction().
FAY_RIDDEL_HEAT_FLUX_CONSTANT
const double tudat::aerodynamics::FAY_RIDDEL_HEAT_FLUX_CONSTANT = 3.53E-4 static
Definition at line 453 of file aerodynamics.h.
Referenced by computeFayRiddellHeatFlux().
aerodynamicVariables
std::map< AerodynamicCoefficientsIndependentVariables, std::string > tudat::aerodynamics::aerodynamicVariables static
Initial value:
=
{
    { mach_number_dependent, "machNumber" },
    { angle_of_attack_dependent, "angleOfAttack" },
    { angle_of_sideslip_dependent, "angleOfSideslip" },
    { altitude_dependent, "altitude" },
    { control_surface_deflection_dependent, "controlSurfaceDeflection" },
    { undefined_independent_variable, "undefined" }
}
Definition at line 27 of file aerodynamics.h.
Referenced by from_json(), and to_json().
unsupportedAerodynamicVariables
std::vector< AerodynamicCoefficientsIndependentVariables > tudat::aerodynamics::unsupportedAerodynamicVariables = { } static
Definition at line 38 of file aerodynamics.h.
atmosphereIndependentVariables
std::map< AtmosphereIndependentVariables, std::string > tudat::aerodynamics::atmosphereIndependentVariables static
Initial value:
=
{
    { altitude_dependent_atmosphere, "altitude" },
    { longitude_dependent_atmosphere, "longitude" },
    { latitude_dependent_atmosphere, "latitude" },
    { time_dependent_atmosphere, "time" }
}
Definition at line 27 of file atmosphere.h.
Referenced by from_json(), and to_json().
unsupportedAtmosphereIndependentVariables
std::vector< AtmosphereIndependentVariables > tudat::aerodynamics::unsupportedAtmosphereIndependentVariables = { } static
Definition at line 36 of file atmosphere.h.
atmosphereDependentVariables
std::map< AtmosphereDependentVariables, std::string > tudat::aerodynamics::atmosphereDependentVariables static
Initial value:
=
{
    { density_dependent_atmosphere, "density" },
    { pressure_dependent_atmosphere, "pressure" },
    { temperature_dependent_atmosphere, "temperature" },
    { gas_constant_dependent_atmosphere, "gasConstant" },
    { specific_heat_ratio_dependent_atmosphere, "specificHeatRatio" },
    { molar_mass_dependent_atmosphere, "molarMass" }
}
Definition at line 54 of file atmosphere.h.
Referenced by from_json(), and to_json().
unsupportedAtmosphereDependentVariables
std::vector< AtmosphereDependentVariables > tudat::aerodynamics::unsupportedAtmosphereDependentVariables = { } static
Definition at line 65 of file atmosphere.h.