Tudat: tudat::numerical_integrators Namespace Reference
tudat::numerical_integrators Namespace Reference
Classes
class AdamsBashforthMoultonIntegrator
Adams-Bashforth-Moulton Variable Order and Stepsize integrator.
class AdamsBashforthMoultonSettings
Class to define settings of variable step ABAM numerical integrator.
class BulirschStoerIntegratorSettings
class BulirschStoerVariableStepSizeIntegrator
Class that implements the Bulirsch-Stoer variable stepsize integrator.
class EulerIntegrator
Class that implements the Euler integrator.
class IntegratorSettings
Class to define settings of numerical integrator.
class NumericalIntegrator
Base class for the numerical integrators.
class ReinitializableNumericalIntegrator
Base class for reinitializable numerical integrators.
class RungeKutta4Integrator
Class that implements the Runge-Kutta 4 integrator.
struct RungeKuttaCoefficients
Struct that defines the coefficients of a Runge-Kutta integrator.
class RungeKuttaVariableStepSizeBaseSettings
Base class to define settings of variable step RK numerical integrator.
class RungeKuttaVariableStepSizeIntegrator
Class that implements the Runge-Kutta variable stepsize integrator.
class RungeKuttaVariableStepSizeSettingsScalarTolerances
Class to define settings of variable step RK numerical integrator with scalar tolerances.
class RungeKuttaVariableStepSizeSettingsVectorTolerances
Class to define settings of variable step RK numerical integrator with vector tolerances.
Typedefs
typedef AdamsBashforthMoultonIntegrator< double, double, double, double > AdamsBashforthMoultonIntegratord
Typedef of a scalar Adams-Bashforth-Moulton integrator.
typedef std::shared_ptr< AdamsBashforthMoultonIntegratord > AdamsBashforthMoultonIntegratordPointer
Typedef of pointer to a scalar Adams-Bashforth-Moulton integrator.
typedef AdamsBashforthMoultonIntegrator< > AdamsBashforthMoultonIntegratorXd
Typedef of Adam-Bashforh-Moulton integrator (state/state derivative = VectorXd, independent variable = double).
typedef std::shared_ptr< AdamsBashforthMoultonIntegratorXd > AdamsBashforthMoultonIntegratorXdPointer
Typedef of pointer to default Adams-Bashforth-Moulton integrator.
typedef BulirschStoerVariableStepSizeIntegrator< > BulirschStoerVariableStepSizeIntegratorXd
Typedef of a variable-step size Bulirsch-Stoer integrator with VectorXds as state and state derivative and double as independent variable.
typedef EulerIntegrator< double, double, double > EulerIntegratord
Typedef of a scalar Euler integrator.
typedef std::shared_ptr< EulerIntegratord > EulerIntegratordPointer
Typedef of pointer to a scalar Euler integrator.
typedef EulerIntegrator< > EulerIntegratorXd
Typedef of Euler integrator (state/state derivative = VectorXd, independent variable = double).
typedef std::shared_ptr< EulerIntegratorXd > EulerIntegratorXdPointer
Typedef for a shared-pointer to default Euler integrator.
typedef std::shared_ptr< NumericalIntegrator< double, double, double > > NumericalIntegratordPointer
Typedef for a shared-pointer to a scalar numerical integrator.
typedef std::shared_ptr< NumericalIntegrator< > > NumericalIntegratorXdPointer
Typedef for shared-pointer to default numerical integrator.
typedef std::shared_ptr< ReinitializableNumericalIntegrator< double, double, double > > ReinitializableNumericalIntegratordPointer
Typedef for a shared-pointer to a scalar, re-initializable numerical integrator.
typedef std::shared_ptr< ReinitializableNumericalIntegrator< > > ReinitializableNumericalIntegratorXdPointer
Typedef for shared-pointer to default, re-initializable numerical integrator.
typedef RungeKutta4Integrator< double, double, double > RungeKutta4Integratord
Typedef of a scalar RK4 integrator.
typedef std::shared_ptr< RungeKutta4Integratord > RungeKutta4IntegratordPointer
Typedef of pointer to a scalar RK4 integrator.
typedef RungeKutta4Integrator< > RungeKutta4IntegratorXd
Typedef of RK4 integrator (state/state derivative = VectorXd, independent variable = double).
typedef std::shared_ptr< RungeKutta4IntegratorXd > RungeKutta4IntegratorXdPointer
Typedef of pointer to default RK4 integrator.
typedef std::shared_ptr< RungeKuttaCoefficients > RungeKuttaCoefficientsPointer
Typedef for shared-pointer to RungeKuttaCoefficients object.
typedef RungeKuttaVariableStepSizeIntegrator< > RungeKuttaVariableStepSizeIntegratorXd
Typedef of a variable-step size Runge-Kutta integrator with VectorXds as state and state derivative and double as independent variable.
typedef std::shared_ptr< RungeKuttaVariableStepSizeIntegratorXd > RungeKuttaVariableStepSizeIntegratorXdPointer
Typedef for shared-pointer to RungeKuttaVariableStepSizeIntegratorXd object.
template<typename IndependentVariableType = double>
using RungeKuttaVariableStepSizeSettings = RungeKuttaVariableStepSizeSettingsScalarTolerances< IndependentVariableType >
Alias for variable step RK numerical integrator with scalar tolerances (added for compatibility with old code).
Enumerations
enum AvailableIntegrators {
euler, rungeKutta4, rungeKuttaVariableStepSize, bulirschStoer,
adamsBashforthMoulton
}
Enum to define available integrators.
enum ExtrapolationMethodStepSequences { bulirsch_stoer_sequence, deufelhard_sequence }
Types of sequences available for extrapolation integration methods.
Functions
template<typename IndependentVariableType , typename DependentVariableType , typename IndependentVariableStepType = IndependentVariableType>
std::shared_ptr< numerical_integrators::NumericalIntegrator< IndependentVariableType, DependentVariableType, DependentVariableType, IndependentVariableStepType > > createIntegrator (std::function< DependentVariableType(const IndependentVariableType, const DependentVariableType &) > stateDerivativeFunction, const DependentVariableType initialState, std::shared_ptr< IntegratorSettings< IndependentVariableType > > integratorSettings)
Function to create a numerical integrator.
void from_json (const nlohmann::json &jsonObject, AvailableIntegrators &availableIntegrator)
Convert json to AvailableIntegrators.
void from_json (const nlohmann::json &jsonObject, RungeKuttaCoefficients::CoefficientSets &rungeKuttaCoefficientSet)
Convert json to RungeKuttaCoefficients::CoefficientSets.
template<typename TimeType >
void from_json (const nlohmann::json &jsonObject, std::shared_ptr< IntegratorSettings< TimeType > > &integratorSettings)
Create a json object from a shared pointer to an IntegratorSettings object.
std::vector< unsigned int > getBulirschStoerStepSequence (const ExtrapolationMethodStepSequences &extrapolationMethodStepSequenceType, const unsigned int lengthOfSequence)
Function to retrieve the sequence of number of steps to used for Bulirsch-Stoer integration.
void initializerungeKutta87DormandPrinceCoefficients (RungeKuttaCoefficients &rungeKutta87DormandPrinceCoefficients)
Initialize RK87 (Dormand and Prince) coefficients.
void initializeRungeKuttaFehlberg45Coefficients (RungeKuttaCoefficients &rungeKuttaFehlberg45Coefficients)
Initialize RKF45 coefficients.
void initializeRungeKuttaFehlberg56Coefficients (RungeKuttaCoefficients &rungeKuttaFehlberg56Coefficients)
Initialize RKF56 coefficients.
void initializeRungeKuttaFehlberg78Coefficients (RungeKuttaCoefficients &rungeKuttaFehlberg78Coefficients)
Initialize RKF78 coefficients.
void to_json (nlohmann::json &jsonObject, const AvailableIntegrators &availableIntegrator)
Convert AvailableIntegrators to json.
void to_json (nlohmann::json &jsonObject, const RungeKuttaCoefficients::CoefficientSets &rungeKuttaCoefficientSet)
Convert RungeKuttaCoefficients::CoefficientSets to json.
template<typename TimeType >
void to_json (nlohmann::json &jsonObject, const std::shared_ptr< IntegratorSettings< TimeType > > &integratorSettings)
Create a json object from a shared pointer to an IntegratorSettings object.
Variables
static std::map< AvailableIntegrators, std::string > integratorTypes
Map of AvailableIntegrators string representations.
static std::map< RungeKuttaCoefficients::CoefficientSets, std::string > rungeKuttaCoefficientSets
Map of RungeKuttaCoefficients::CoefficientSets string representations.
static std::vector< AvailableIntegrators > unsupportedIntegratorTypes = { }
AvailableIntegrators not supported by json_interface.
static std::vector< RungeKuttaCoefficients::CoefficientSets > unsupportedRungeKuttaCoefficientSets = { }
RungeKuttaCoefficients::CoefficientSets not supported by json_interface.
Typedef Documentation
AdamsBashforthMoultonIntegratorXd
typedef AdamsBashforthMoultonIntegrator< > tudat::numerical_integrators::AdamsBashforthMoultonIntegratorXd
Typedef of a Adams-Bashforth-Moulton integrator with VectorXds as state and state derivative and double as independent variable.
Definition at line 1006 of file adamsBashforthMoultonIntegrator.h.
AdamsBashforthMoultonIntegratord
typedef AdamsBashforthMoultonIntegrator< double, double, double, double > tudat::numerical_integrators::AdamsBashforthMoultonIntegratord
Typedef of an Adams-Bashforth-Moulton integrator with doubles as state and state derivative and independent variable.
Definition at line 1013 of file adamsBashforthMoultonIntegrator.h.
AdamsBashforthMoultonIntegratorXdPointer
typedef std::shared_ptr< AdamsBashforthMoultonIntegratorXd > tudat::numerical_integrators::AdamsBashforthMoultonIntegratorXdPointer
Typedef of pointer to a Adams-Bashforth-Moulton integrator with VectorXds as state and state derivative and double as independent variable.
Definition at line 1020 of file adamsBashforthMoultonIntegrator.h.
AdamsBashforthMoultonIntegratordPointer
typedef std::shared_ptr< AdamsBashforthMoultonIntegratord > tudat::numerical_integrators::AdamsBashforthMoultonIntegratordPointer
Typedef of pointer to an Adams-Bashforth-Moulton integrator with doubles as state and state derivative and independent variable.
Definition at line 1027 of file adamsBashforthMoultonIntegrator.h.
BulirschStoerVariableStepSizeIntegratorXd
typedef BulirschStoerVariableStepSizeIntegrator< > tudat::numerical_integrators::BulirschStoerVariableStepSizeIntegratorXd
Typedef of variable-step size Bulirsch-Stoer integrator (state/state derivative = VectorXd, independent variable = double).
Definition at line 514 of file bulirschStoerVariableStepsizeIntegrator.h.
RungeKuttaVariableStepSizeSettings
template<typename IndependentVariableType = double> using tudat::numerical_integrators::RungeKuttaVariableStepSizeSettings = typedef RungeKuttaVariableStepSizeSettingsScalarTolerances< IndependentVariableType >
Definition at line 322 of file createNumericalIntegrator.h.
EulerIntegratorXd
typedef EulerIntegrator< > tudat::numerical_integrators::EulerIntegratorXd
Typedef of an Euler integrator with VectorXds as state and state derivative and double as independent variable.
Definition at line 242 of file euler.h.
EulerIntegratord
typedef EulerIntegrator< double, double, double > tudat::numerical_integrators::EulerIntegratord
Typedef of a Euler integrator with doubles as state and state derivative and independent variable.
Definition at line 248 of file euler.h.
EulerIntegratorXdPointer
typedef std::shared_ptr< EulerIntegratorXd > tudat::numerical_integrators::EulerIntegratorXdPointer
Typedef for a shared-pointer to an Euler integrator with VectorXds as state and state derivative and double as independent variable.
Definition at line 255 of file euler.h.
EulerIntegratordPointer
typedef std::shared_ptr< EulerIntegratord > tudat::numerical_integrators::EulerIntegratordPointer
Typedef of pointer to an Euler integrator with doubles as state and state derivative and independent variable.
Definition at line 262 of file euler.h.
NumericalIntegratorXdPointer
typedef std::shared_ptr< NumericalIntegrator< > > tudat::numerical_integrators::NumericalIntegratorXdPointer
Typedef for shared-pointer to a default numerical integrator (IndependentVariableType = double, StateType = Eigen::VectorXd, StateDerivativeType = Eigen::VectorXd).
Definition at line 338 of file numericalIntegrator.h.
NumericalIntegratordPointer
typedef std::shared_ptr< NumericalIntegrator< double, double, double > > tudat::numerical_integrators::NumericalIntegratordPointer
Typedef for shared-pointer to a scalar numerical integrator (IndependentVariableType = double, StateType = double, StateDerivativeType = double).
Definition at line 345 of file numericalIntegrator.h.
ReinitializableNumericalIntegratorXdPointer
typedef std::shared_ptr< ReinitializableNumericalIntegrator< > > tudat::numerical_integrators::ReinitializableNumericalIntegratorXdPointer
Typedef for shared-pointer to a default, re-initializable numerical integrator (IndependentVariableType = double, StateType = Eigen::VectorXd, StateDerivativeType = Eigen::VectorXd).
Definition at line 79 of file reinitializableNumericalIntegrator.h.
ReinitializableNumericalIntegratordPointer
typedef std::shared_ptr< ReinitializableNumericalIntegrator< double, double, double > > tudat::numerical_integrators::ReinitializableNumericalIntegratordPointer
Typedef for shared-pointer to a scalar numerical, re-initializable integrator (IndependentVariableType = double, StateType = double, StateDerivativeType = double).
Definition at line 87 of file reinitializableNumericalIntegrator.h.
RungeKutta4IntegratorXd
typedef RungeKutta4Integrator< > tudat::numerical_integrators::RungeKutta4IntegratorXd
Typedef of a RK4 integrator with VectorXds as state and state derivative and double as independent variable.
Definition at line 281 of file rungeKutta4Integrator.h.
RungeKutta4Integratord
typedef RungeKutta4Integrator< double, double, double > tudat::numerical_integrators::RungeKutta4Integratord
Typedef of an RK4 integrator with doubles as state and state derivative and independent variable.
Definition at line 288 of file rungeKutta4Integrator.h.
RungeKutta4IntegratorXdPointer
typedef std::shared_ptr< RungeKutta4IntegratorXd > tudat::numerical_integrators::RungeKutta4IntegratorXdPointer
Typedef of pointer to a RK4 integrator with VectorXds as state and state derivative and double as independent variable.
Definition at line 295 of file rungeKutta4Integrator.h.
RungeKutta4IntegratordPointer
typedef std::shared_ptr< RungeKutta4Integratord > tudat::numerical_integrators::RungeKutta4IntegratordPointer
Typedef of pointer to an RK4 integrator with doubles as state and state derivative and independent variable.
Definition at line 302 of file rungeKutta4Integrator.h.
RungeKuttaCoefficientsPointer
typedef std::shared_ptr< RungeKuttaCoefficients > tudat::numerical_integrators::RungeKuttaCoefficientsPointer
Definition at line 112 of file rungeKuttaCoefficients.h.
RungeKuttaVariableStepSizeIntegratorXd
typedef RungeKuttaVariableStepSizeIntegrator< > tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegratorXd
Typedef of variable-step size Runge-Kutta integrator (state/state derivative = VectorXd, independent variable = double).
Definition at line 735 of file rungeKuttaVariableStepSizeIntegrator.h.
RungeKuttaVariableStepSizeIntegratorXdPointer
typedef std::shared_ptr< RungeKuttaVariableStepSizeIntegratorXd > tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegratorXdPointer
Definition at line 739 of file rungeKuttaVariableStepSizeIntegrator.h.
Enumeration Type Documentation
ExtrapolationMethodStepSequences
enum tudat::numerical_integrators::ExtrapolationMethodStepSequences
Enumerator
bulirsch_stoer_sequence
deufelhard_sequence
Definition at line 41 of file bulirschStoerVariableStepsizeIntegrator.h.
AvailableIntegrators
enum tudat::numerical_integrators::AvailableIntegrators
Enumerator
euler
rungeKutta4
rungeKuttaVariableStepSize
bulirschStoer
adamsBashforthMoulton
Definition at line 34 of file createNumericalIntegrator.h.
Function Documentation
to_json() [1/3]
void tudat::numerical_integrators::to_json (nlohmann::json & jsonObject, const AvailableIntegrators & availableIntegrator) inline
Definition at line 38 of file integrator.h.
References integratorTypes, and tudat::json_interface::stringFromEnum().
from_json() [1/3]
void tudat::numerical_integrators::from_json (const nlohmann::json & jsonObject, AvailableIntegrators & availableIntegrator) inline
Definition at line 44 of file integrator.h.
References tudat::json_interface::enumFromString(), and integratorTypes.
to_json() [2/3]
void tudat::numerical_integrators::to_json (nlohmann::json & jsonObject, const RungeKuttaCoefficients::CoefficientSets & rungeKuttaCoefficientSet) inline
Definition at line 63 of file integrator.h.
References rungeKuttaCoefficientSets, and tudat::json_interface::stringFromEnum().
from_json() [2/3]
void tudat::numerical_integrators::from_json (const nlohmann::json & jsonObject, RungeKuttaCoefficients::CoefficientSets & rungeKuttaCoefficientSet) inline
Definition at line 69 of file integrator.h.
References tudat::json_interface::enumFromString(), and rungeKuttaCoefficientSets.
to_json() [3/3]
template<typename TimeType > void tudat::numerical_integrators::to_json (nlohmann::json & jsonObject, const std::shared_ptr< IntegratorSettings< TimeType > > & integratorSettings)
Definition at line 78 of file integrator.h.
References adamsBashforthMoulton, tudat::json_interface::assertNonnullptrPointer(), bulirschStoer, euler, tudat::json_interface::handleUnimplementedEnumValue(), integratorTypes, rungeKutta4, rungeKuttaCoefficientSets, rungeKuttaVariableStepSize, tudat::json_interface::stringFromEnum(), and unsupportedIntegratorTypes.
from_json() [3/3]
template<typename TimeType > void tudat::numerical_integrators::from_json (const nlohmann::json & jsonObject, std::shared_ptr< IntegratorSettings< TimeType > > & integratorSettings)
Definition at line 179 of file integrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeSettingsScalarTolerances< IndependentVariableType >::absoluteErrorTolerance_, tudat::numerical_integrators::BulirschStoerIntegratorSettings< IndependentVariableType >::absoluteErrorTolerance_, tudat::numerical_integrators::AdamsBashforthMoultonSettings< IndependentVariableType >::absoluteErrorTolerance_, adamsBashforthMoulton, tudat::numerical_integrators::IntegratorSettings< IndependentVariableType >::assessPropagationTerminationConditionDuringIntegrationSubsteps_, tudat::numerical_integrators::AdamsBashforthMoultonSettings< IndependentVariableType >::bandwidth_, bulirsch_stoer_sequence, bulirschStoer, euler, tudat::numerical_integrators::BulirschStoerIntegratorSettings< IndependentVariableType >::extrapolationSequence_, tudat::json_interface::getValue(), tudat::json_interface::handleUnimplementedEnumValue(), integratorTypes, tudat::numerical_integrators::RungeKuttaVariableStepSizeBaseSettings< IndependentVariableType >::maximumFactorIncreaseForNextStepSize_, tudat::numerical_integrators::BulirschStoerIntegratorSettings< IndependentVariableType >::maximumFactorIncreaseForNextStepSize_, tudat::numerical_integrators::BulirschStoerIntegratorSettings< IndependentVariableType >::maximumNumberOfSteps_, tudat::numerical_integrators::AdamsBashforthMoultonSettings< IndependentVariableType >::maximumOrder_, tudat::numerical_integrators::RungeKuttaVariableStepSizeBaseSettings< IndependentVariableType >::minimumFactorDecreaseForNextStepSize_, tudat::numerical_integrators::BulirschStoerIntegratorSettings< IndependentVariableType >::minimumFactorDecreaseForNextStepSize_, tudat::numerical_integrators::AdamsBashforthMoultonSettings< IndependentVariableType >::minimumOrder_, tudat::numerical_integrators::RungeKuttaVariableStepSizeSettingsScalarTolerances< IndependentVariableType >::relativeErrorTolerance_, tudat::numerical_integrators::BulirschStoerIntegratorSettings< IndependentVariableType >::relativeErrorTolerance_, tudat::numerical_integrators::AdamsBashforthMoultonSettings< IndependentVariableType >::relativeErrorTolerance_, rungeKutta4, rungeKuttaVariableStepSize, tudat::numerical_integrators::RungeKuttaVariableStepSizeBaseSettings< IndependentVariableType >::safetyFactorForNextStepSize_, tudat::numerical_integrators::BulirschStoerIntegratorSettings< IndependentVariableType >::safetyFactorForNextStepSize_, tudat::numerical_integrators::IntegratorSettings< IndependentVariableType >::saveFrequency_, and unsupportedIntegratorTypes.
getBulirschStoerStepSequence()
std::vector< unsigned int > tudat::numerical_integrators::getBulirschStoerStepSequence (const ExtrapolationMethodStepSequences & extrapolationMethodStepSequenceType = bulirsch_stoer_sequence, const unsigned int lengthOfSequence = 12)
Function to retrieve the sequence of number of steps to used for Bulirsch-Stoer integration
Parameters
extrapolationMethodStepSequenceType Type of sequence that is to be retrieved
lengthOfSequence Length of the sequence that is to be retrieved (default 12)
Returns
Function to retrieve the sequence of number of steps to used for Bulirsch-Stoer integration
Definition at line 30 of file bulirschStoerVariableStepsizeIntegrator.cpp.
References bulirsch_stoer_sequence, and deufelhard_sequence.
Referenced by createIntegrator().
createIntegrator()
template<typename IndependentVariableType , typename DependentVariableType , typename IndependentVariableStepType = IndependentVariableType> std::shared_ptr< numerical_integrators::NumericalIntegrator< IndependentVariableType, DependentVariableType,DependentVariableType, IndependentVariableStepType > > tudat::numerical_integrators::createIntegrator (std::function< DependentVariableType(const IndependentVariableType, const DependentVariableType &) > stateDerivativeFunction, const DependentVariableType initialState, std::shared_ptr< IntegratorSettings< IndependentVariableType > > integratorSettings)
Function to create a numerical integrator from given integrator settings, state derivative function and initial state.
Parameters
stateDerivativeFunction Function returning the state derivative from current time and state.
initialState Initial state for numerical integration.
integratorSettings Settings for numerical integrator.
Returns
Numerical integrator object.
Definition at line 567 of file createNumericalIntegrator.h.
References adamsBashforthMoulton, bulirschStoer, euler, tudat::numerical_integrators::RungeKuttaCoefficients::get(), getBulirschStoerStepSequence(), rungeKutta4, and rungeKuttaVariableStepSize.
initializeRungeKuttaFehlberg45Coefficients()
void tudat::numerical_integrators::initializeRungeKuttaFehlberg45Coefficients (RungeKuttaCoefficients & rungeKuttaFehlberg45Coefficients)
Definition at line 31 of file rungeKuttaCoefficients.cpp.
References tudat::numerical_integrators::RungeKuttaCoefficients::aCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::bCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::cCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::higherOrder, tudat::numerical_integrators::RungeKuttaCoefficients::lower, tudat::numerical_integrators::RungeKuttaCoefficients::lowerOrder, and tudat::numerical_integrators::RungeKuttaCoefficients::orderEstimateToIntegrate.
Referenced by tudat::numerical_integrators::RungeKuttaCoefficients::get().
initializeRungeKuttaFehlberg56Coefficients()
void tudat::numerical_integrators::initializeRungeKuttaFehlberg56Coefficients (RungeKuttaCoefficients & rungeKuttaFehlberg56Coefficients)
Definition at line 91 of file rungeKuttaCoefficients.cpp.
References tudat::numerical_integrators::RungeKuttaCoefficients::aCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::bCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::cCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::higherOrder, tudat::numerical_integrators::RungeKuttaCoefficients::lower, tudat::numerical_integrators::RungeKuttaCoefficients::lowerOrder, and tudat::numerical_integrators::RungeKuttaCoefficients::orderEstimateToIntegrate.
Referenced by tudat::numerical_integrators::RungeKuttaCoefficients::get().
initializeRungeKuttaFehlberg78Coefficients()
void tudat::numerical_integrators::initializeRungeKuttaFehlberg78Coefficients (RungeKuttaCoefficients & rungeKuttaFehlberg78Coefficients)
Definition at line 164 of file rungeKuttaCoefficients.cpp.
References tudat::numerical_integrators::RungeKuttaCoefficients::aCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::bCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::cCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::higherOrder, tudat::numerical_integrators::RungeKuttaCoefficients::lower, tudat::numerical_integrators::RungeKuttaCoefficients::lowerOrder, and tudat::numerical_integrators::RungeKuttaCoefficients::orderEstimateToIntegrate.
Referenced by tudat::numerical_integrators::RungeKuttaCoefficients::get().
initializerungeKutta87DormandPrinceCoefficients()
void tudat::numerical_integrators::initializerungeKutta87DormandPrinceCoefficients (RungeKuttaCoefficients & rungeKutta87DormandPrinceCoefficients)
Definition at line 287 of file rungeKuttaCoefficients.cpp.
References tudat::numerical_integrators::RungeKuttaCoefficients::aCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::bCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::cCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::higher, tudat::numerical_integrators::RungeKuttaCoefficients::higherOrder, tudat::numerical_integrators::RungeKuttaCoefficients::lowerOrder, and tudat::numerical_integrators::RungeKuttaCoefficients::orderEstimateToIntegrate.
Referenced by tudat::numerical_integrators::RungeKuttaCoefficients::get().
Variable Documentation
integratorTypes
std::map< AvailableIntegrators, std::string > tudat::numerical_integrators::integratorTypes static
Initial value:
=
{
    { rungeKutta4, "rungeKutta4" },
    { euler, "euler" },
    { rungeKuttaVariableStepSize, "rungeKuttaVariableStepSize" },
    { adamsBashforthMoulton, "adamsBashforthMoulton" },
    { bulirschStoer, "bulirschStoer" },
}
Definition at line 25 of file integrator.h.
Referenced by from_json(), and to_json().
unsupportedIntegratorTypes
std::vector< AvailableIntegrators > tudat::numerical_integrators::unsupportedIntegratorTypes = { } static
Definition at line 35 of file integrator.h.
Referenced by from_json(), and to_json().
rungeKuttaCoefficientSets
std::map< RungeKuttaCoefficients::CoefficientSets, std::string > tudat::numerical_integrators::rungeKuttaCoefficientSets static
Initial value:
=
{
    { RungeKuttaCoefficients::rungeKuttaFehlberg45, "rungeKuttaFehlberg45" },
    { RungeKuttaCoefficients::rungeKuttaFehlberg56, "rungeKuttaFehlberg56" },
    { RungeKuttaCoefficients::rungeKuttaFehlberg78, "rungeKuttaFehlberg78" },
    { RungeKuttaCoefficients::rungeKutta87DormandPrince, "rungeKutta87DormandPrince" }
}
Definition at line 51 of file integrator.h.
Referenced by from_json(), and to_json().
unsupportedRungeKuttaCoefficientSets
std::vector< RungeKuttaCoefficients::CoefficientSets > tudat::numerical_integrators::unsupportedRungeKuttaCoefficientSets = { } static
Definition at line 60 of file integrator.h.