Tudat: tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType > Class Template Reference
tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType > Class Template Reference
Class to calculate the light time between two points.
#include <lightTimeSolution.h>
Public Types
typedef Eigen::Matrix< ObservationScalarType, 3, 1 > PositionType
typedef Eigen::Matrix< ObservationScalarType, 6, 1 > StateType
Public Member Functions
LightTimeCalculator (const std::function< StateType(const TimeType) > positionFunctionOfTransmittingBody, const std::function< StateType(const TimeType) > positionFunctionOfReceivingBody, const std::vector< std::shared_ptr< LightTimeCorrection > > correctionFunctions=std::vector< std::shared_ptr< LightTimeCorrection > >(), const bool iterateCorrections=false)
Class constructor.
LightTimeCalculator (const std::function< StateType(const TimeType) > positionFunctionOfTransmittingBody, const std::function< StateType(const TimeType) > positionFunctionOfReceivingBody, const std::vector< LightTimeCorrectionFunction > correctionFunctions, const bool iterateCorrections=false)
Class constructor.
ObservationScalarType calculateLightTime (const TimeType time, const bool isTimeAtReception=true, const ObservationScalarType tolerance=getDefaultLightTimeTolerance< ObservationScalarType >())
Function to calculate the light time.
ObservationScalarType calculateLightTimeWithLinkEndsStates (StateType &receiverStateOutput, StateType &transmitterStateOutput, const TimeType time, const bool isTimeAtReception=1, const ObservationScalarType tolerance=(getDefaultLightTimeTolerance< ObservationScalarType >()))
Function to calculate the light time and link-ends states.
PositionType calculateRelativeRangeVector (const TimeType time, const bool isTimeAtReception=1, const ObservationScalarType tolerance=getDefaultLightTimeTolerance< ObservationScalarType >())
Function to calculate the 'measured' vector from transmitter to receiver.
std::vector< std::shared_ptr< LightTimeCorrection > > getLightTimeCorrection ()
Function to get list of light-time correction functions.
Eigen::Matrix< ObservationScalarType, 1, 3 > getPartialOfLightTimeWrtLinkEndPosition (const StateType &transmitterState, const StateType &receiverState, const TimeType transmitterTime, const TimeType receiverTime, const bool isPartialWrtReceiver)
Function to get the part wrt linkend position.
Protected Member Functions
ObservationScalarType calculateNewLightTimeEstime (const StateType &receiverState, const StateType &transmitterState) const
Function to calculate a new light-time estimate from the link-ends states.
void setTotalLightTimeCorrection (const StateType &transmitterState, const StateType &receiverState, const TimeType transmissionTime, const TimeType receptionTime)
Function to reset the currentCorrection_ variable during current iteration.
Protected Attributes
std::vector< std::shared_ptr< LightTimeCorrection > > correctionFunctions_
List of light-time correction functions.
double currentCorrection_
Current light-time correction.
bool iterateCorrections_
Boolean deciding whether to recalculate the correction during each iteration.
std::function< StateType(const double) > stateFunctionOfReceivingBody_
Receiver state function.
std::function< StateType(const double) > stateFunctionOfTransmittingBody_
Transmitter state function.
Detailed Description
template<typename ObservationScalarType = double, typename TimeType = double>
class tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >
This class calculates the light time between two points, of which the state functions have to be provided. Additionally, light-time corrections (such as tropospheric or relatvistic corrections) can be applied. The motion of the ends of the link during the light time is taken into account in the calculations.
Definition at line 155 of file lightTimeSolution.h.
Member Typedef Documentation
StateType
template<typename ObservationScalarType = double, typename TimeType = double> typedef Eigen::Matrix< ObservationScalarType, 6, 1 > tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::StateType
Definition at line 160 of file lightTimeSolution.h.
PositionType
template<typename ObservationScalarType = double, typename TimeType = double> typedef Eigen::Matrix< ObservationScalarType, 3, 1 > tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::PositionType
Definition at line 161 of file lightTimeSolution.h.
Constructor & Destructor Documentation
LightTimeCalculator() [1/2]
template<typename ObservationScalarType = double, typename TimeType = double> tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::LightTimeCalculator (const std::function< StateType(const TimeType) > positionFunctionOfTransmittingBody, const std::function< StateType(const TimeType) > positionFunctionOfReceivingBody, const std::vector< std::shared_ptr< LightTimeCorrection > > correctionFunctions = std::vector< std::shared_ptr< LightTimeCorrection > >(), const bool iterateCorrections = false) inline
This constructor is used to initialize the state functions and light-time correction objects.
Parameters
positionFunctionOfTransmittingBody State function of transmitter.
positionFunctionOfReceivingBody State function of receiver.
correctionFunctions List of light-time correction objects.
iterateCorrections Boolean determining whether to recalculate the light-time correction during each iteration.
Definition at line 173 of file lightTimeSolution.h.
LightTimeCalculator() [2/2]
template<typename ObservationScalarType = double, typename TimeType = double> tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::LightTimeCalculator (const std::function< StateType(const TimeType) > positionFunctionOfTransmittingBody, const std::function< StateType(const TimeType) > positionFunctionOfReceivingBody, const std::vector< LightTimeCorrectionFunction > correctionFunctions, const bool iterateCorrections = false) inline
This constructor is used to initialize the state functions and light-time functions
Parameters
positionFunctionOfTransmittingBody State function of transmitter.
positionFunctionOfReceivingBody State function of receiver.
correctionFunctions List of light-time correction functions.
iterateCorrections Boolean determining whether to recalculate the light-time correction during each iteration.
Definition at line 194 of file lightTimeSolution.h.
References tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::correctionFunctions_.
Member Function Documentation
calculateLightTime()
template<typename ObservationScalarType = double, typename TimeType = double> ObservationScalarType tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTime (const TimeType time, const bool isTimeAtReception = true, const ObservationScalarType tolerance = getDefaultLightTimeTolerance< ObservationScalarType >()) inline
This function calculates the light time between the link ends defined in the constructor. The input time can be either at transmission or at reception (default) time.
Parameters
time Time at reception or transmission.
isTimeAtReception True if input time is at reception, false if at transmission.
tolerance Maximum allowed light-time difference between two subsequent iterations for which solution is accepted.
Returns
The value of the light time between the link ends.
Definition at line 222 of file lightTimeSolution.h.
References tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates().
calculateRelativeRangeVector()
template<typename ObservationScalarType = double, typename TimeType = double> PositionType tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateRelativeRangeVector (const TimeType time, const bool isTimeAtReception = 1, const ObservationScalarType tolerance = getDefaultLightTimeTolerance< ObservationScalarType >()) inline
Function to calculate the vector from transmitter at transmitter time to receiver at reception time. The input time can be either at transmission or reception (default) time.
Parameters
time Time at reception or transmission.
isTimeAtReception True if input time is at reception, false if at transmission.
tolerance Maximum allowed light-time difference between two subsequent iterations for which solution is accepted.
Returns
The vector from the transmitter to the reciever.
Definition at line 248 of file lightTimeSolution.h.
References tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates().
calculateLightTimeWithLinkEndsStates()
template<typename ObservationScalarType = double, typename TimeType = double> ObservationScalarType tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates (StateType & receiverStateOutput, StateType & transmitterStateOutput, const TimeType time, const bool isTimeAtReception = 1, const ObservationScalarType tolerance = (getDefaultLightTimeTolerance< ObservationScalarType >())) inline
Function to calculate the transmitter state at transmission time, the receiver state at reception time, and the light time. The input time can be either at transmission or reception (default) time.
Parameters
receiverStateOutput Output by reference of receiver state.
transmitterStateOutput Output by reference of transmitter state.
time Time at reception or transmission.
isTimeAtReception True if input time is at reception, false if at transmission.
tolerance Maximum allowed light-time difference between two subsequent iterations for which solution is accepted.
Returns
The value of the light time between the reciever state and the transmitter state.
Definition at line 276 of file lightTimeSolution.h.
References tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateNewLightTimeEstime(), tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::currentCorrection_, tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::iterateCorrections_, tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::setTotalLightTimeCorrection(), tudat::physical_constants::SPEED_OF_LIGHT, tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::stateFunctionOfReceivingBody_, and tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::stateFunctionOfTransmittingBody_.
Referenced by tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTime(), and tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateRelativeRangeVector().
getPartialOfLightTimeWrtLinkEndPosition()
template<typename ObservationScalarType = double, typename TimeType = double> Eigen::Matrix< ObservationScalarType, 1, 3 > tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::getPartialOfLightTimeWrtLinkEndPosition (const StateType & transmitterState, const StateType & receiverState, const TimeType transmitterTime, const TimeType receiverTime, const bool isPartialWrtReceiver) inline
Function to get the part wrt linkend position
Parameters
transmitterState State of transmitter.
receiverState State of receiver.
transmitterTime Time at transmission.
receiverTime Time at reiver.
isPartialWrtReceiver If partial is to be calculated w.r.t. receiver or transmitter.
Definition at line 395 of file lightTimeSolution.h.
References tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::currentCorrection_, and tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::setTotalLightTimeCorrection().
getLightTimeCorrection()
template<typename ObservationScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< LightTimeCorrection > > tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::getLightTimeCorrection () inline
Function to get list of light-time correction functions
Returns
List of light-time correction functions
Definition at line 418 of file lightTimeSolution.h.
References tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::correctionFunctions_.
calculateNewLightTimeEstime()
template<typename ObservationScalarType = double, typename TimeType = double> ObservationScalarType tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateNewLightTimeEstime (const StateType & receiverState, const StateType & transmitterState) const inline protected
Function to calculate a new light-time estimate from the states of the two ends of the link. This function recalculates the light time each iteration from the assumed receiver/transmitter state, as well as the currentCorrection_ variable.
Parameters
receiverState Assumed state of receiver.
transmitterState Assumed state of transmitter.
Returns
New value of the light-time estimate.
Definition at line 468 of file lightTimeSolution.h.
References tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::currentCorrection_.
Referenced by tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates().
setTotalLightTimeCorrection()
template<typename ObservationScalarType = double, typename TimeType = double> void tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::setTotalLightTimeCorrection (const StateType & transmitterState, const StateType & receiverState, const TimeType transmissionTime, const TimeType receptionTime) inline protected
Function to reset the currentCorrection_ variable during current iteration, representing the sum of all corrections causing the light time to deviate from the Euclidean value.
Parameters
transmitterState State of transmitter.
receiverState State of receiver.
transmissionTime Time at transmission.
receptionTime Time at reception.
Definition at line 486 of file lightTimeSolution.h.
References tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::correctionFunctions_, and tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::currentCorrection_.
Referenced by tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates(), and tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::getPartialOfLightTimeWrtLinkEndPosition().
Member Data Documentation
stateFunctionOfTransmittingBody_
template<typename ObservationScalarType = double, typename TimeType = double> std::function< StateType(const double) > tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::stateFunctionOfTransmittingBody_ protected
Transmitter state function.
Definition at line 430 of file lightTimeSolution.h.
Referenced by tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates().
stateFunctionOfReceivingBody_
template<typename ObservationScalarType = double, typename TimeType = double> std::function< StateType(const double) > tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::stateFunctionOfReceivingBody_ protected
Receiver state function.
Definition at line 437 of file lightTimeSolution.h.
Referenced by tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates().
correctionFunctions_
template<typename ObservationScalarType = double, typename TimeType = double> std::vector< std::shared_ptr< LightTimeCorrection > > tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::correctionFunctions_ protected
List of light-time correction functions, i.e. tropospheric, relativistic, etc.
Definition at line 443 of file lightTimeSolution.h.
Referenced by tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::getLightTimeCorrection(), tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::LightTimeCalculator(), and tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::setTotalLightTimeCorrection().
iterateCorrections_
template<typename ObservationScalarType = double, typename TimeType = double> bool tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::iterateCorrections_ protected
Boolean deciding whether to recalculate the correction during each iteration. If it is set true, the corrections are calculated during each iteration of the light-time calculations. If it is set to false, it is calculated once at the begining. Additionally, when convergence is reached, it is recalculated to check whether the light time with new correction violates the convergence. If so, another iteration is performed.
Definition at line 454 of file lightTimeSolution.h.
Referenced by tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates().
currentCorrection_
template<typename ObservationScalarType = double, typename TimeType = double> double tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::currentCorrection_ protected
Definition at line 457 of file lightTimeSolution.h.
Referenced by tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateLightTimeWithLinkEndsStates(), tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::calculateNewLightTimeEstime(), tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::getPartialOfLightTimeWrtLinkEndPosition(), and tudat::observation_models::LightTimeCalculator< ObservationScalarType, TimeType >::setTotalLightTimeCorrection().
The documentation for this class was generated from the following file:
Astrodynamics/ObservationModels/lightTimeSolution.h