Tudat: tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType > Class Template Reference
tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType > Class Template Reference
Class that implements the Runge-Kutta variable stepsize integrator.
#include <rungeKuttaVariableStepSizeIntegrator.h>
Classes
class MinimumStepSizeExceededError
Exception that is thrown if the minimum step size is exceeded.
Public Types
typedef boost::function< std::pair< TimeStepType, bool > const TimeStepType, const TimeStepType, const TimeStepType, const TimeStepType, const StateType &, const StateType &, const StateType &, const StateType &) > NewStepSizeFunction
Typedef to the function used to compute the new step size.
typedef numerical_integrators::ReinitializableNumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType > ReinitializableNumericalIntegratorBase
Typedef of the base class.
typedef ReinitializableNumericalIntegratorBase::NumericalIntegratorBase::StateDerivativeFunction StateDerivativeFunction
Typedef to the state derivative function.
Public Types inherited from tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >
typedef boost::function< StateDerivativeType(const IndependentVariableType, const StateType &) > StateDerivativeFunction
Typedef to the state derivative function.
Public Member Functions
RungeKuttaVariableStepSizeIntegrator (const RungeKuttaCoefficients &coefficients, const StateDerivativeFunction &stateDerivativeFunction, const IndependentVariableType intervalStart, const StateType &initialState, const IndependentVariableType minimumStepSize, const IndependentVariableType maximumStepSize, const StateType &relativeErrorTolerance, const StateType &absoluteErrorTolerance, const TimeStepType safetyFactorForNextStepSize=0.8, const TimeStepType maximumFactorIncreaseForNextStepSize=4.0, const TimeStepType minimumFactorDecreaseForNextStepSize=0.1, const NewStepSizeFunction &newStepSizeFunction=0)
Default constructor.
RungeKuttaVariableStepSizeIntegrator (const RungeKuttaCoefficients &coefficients, const StateDerivativeFunction &stateDerivativeFunction, const IndependentVariableType intervalStart, const StateType &initialState, const TimeStepType minimumStepSize, const TimeStepType maximumStepSize, const typename StateType::Scalar relativeErrorTolerance, const typename StateType::Scalar absoluteErrorTolerance, const TimeStepType safetyFactorForNextStepSize=0.8, const TimeStepType maximumFactorIncreaseForNextStepSize=4.0, const TimeStepType minimumFactorDecreaseForNextStepSize=0.1, const NewStepSizeFunction &newStepSizeFunction=0)
Default constructor.
virtual IndependentVariableType getCurrentIndependentVariable () const
Get current independent variable.
virtual StateType getCurrentState () const
Get current state.
std::vector< StateDerivativeType > getCurrentStateDerivatives ()
Get current state derivatives.
virtual TimeStepType getNextStepSize () const
Get step size of the next step.
void modifyCurrentState (const StateType &newState)
Modify the state at the current interval.
virtual StateType performIntegrationStep (const TimeStepType stepSize)
Perform a single integration step.
virtual bool rollbackToPreviousState ()
Rollback internal state to the last state.
Public Member Functions inherited from tudat::numerical_integrators::ReinitializableNumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >
ReinitializableNumericalIntegrator (const typename NumericalIntegratorBase::StateDerivativeFunction &aStateDerivativeFunction)
Default constructor.
virtual ~ReinitializableNumericalIntegrator ()
Default destructor.
Public Member Functions inherited from tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >
NumericalIntegrator (const StateDerivativeFunction &stateDerivativeFunction)
Default constructor.
virtual ~NumericalIntegrator ()
Default virtual destructor.
bool getPropagationTerminationConditionReached ()
Function to return the termination condition was reached during the current step.
StateDerivativeFunction getStateDerivativeFunction ()
Function to return the function that computes and returns the state derivative.
virtual StateType integrateTo (const IndependentVariableType intervalEnd, const TimeStepType initialStepSize, const TimeStepType finalTimeTolerance=std::numeric_limits< TimeStepType >::epsilon())
Perform an integration to a specified independent variable value.
void setPropagationTerminationFunction (boost::function< bool(const double) > terminationFunction)
Setter for the (optional) propagation termination function.
Protected Member Functions
virtual std::pair< TimeStepType, bool > computeNewStepSize (const TimeStepType stepSize, const TimeStepType lowerOrder, const TimeStepType higherOrder, const TimeStepType safetyFactorForNextStepSize, const StateType &relativeErrorTolerance, const StateType &absoluteErrorTolerance, const StateType &lowerOrderEstimate, const StateType &higherOrderEstimate)
Compute new step size.
virtual bool computeNextStepSizeAndValidateResult (const StateType &lowerOrderEstimate, const StateType &higherOrderEstimate, const TimeStepType stepSize)
Computes the next step size and validates the result.
Protected Attributes
StateType absoluteErrorTolerance_
Absolute error tolerance.
RungeKuttaCoefficients coefficients_
Coefficients for the integrator.
IndependentVariableType currentIndependentVariable_
Current independent variable.
StateType currentState_
Current state.
std::vector< StateDerivativeType > currentStateDerivatives_
Vector of state derivatives.
IndependentVariableType lastIndependentVariable_
Last independent variable.
StateType lastState_
Last state.
TimeStepType maximumFactorIncreaseForNextStepSize_
Maximum factor increase for next step size.
TimeStepType maximumStepSize_
Maximum step size.
TimeStepType minimumFactorDecreaseForNextStepSize_
Minimum factor decrease for next step size.
TimeStepType minimumStepSize_
Minimum step size.
NewStepSizeFunction newStepSizeFunction_
Function that returns the new step size computed.
StateType relativeErrorTolerance_
Relative error tolerance.
TimeStepType safetyFactorForNextStepSize_
Safety factor for next step size.
TimeStepType stepSize_
Last used step size.
Protected Attributes inherited from tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >
bool propagationTerminationConditionReachedDuringStep_ = false
Boolean to denote whether the propagation termination condition was reached during the evaluation of one of the sub-steps.
boost::function< bool(const double) > propagationTerminationFunction_ = boost::lambda::constant(false)
Propagation termination function.
StateDerivativeFunction stateDerivativeFunction_
Function that returns the state derivative.
Additional Inherited Members
Protected Types inherited from tudat::numerical_integrators::ReinitializableNumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >
typedef numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType > NumericalIntegratorBase
Typedef of the base class.
Detailed Description
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType>
class tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >
Class that implements the Runge-Kutta variable step size integrator.
Template Parameters
StateType The type of the state. This type should be an Eigen::Matrix derived type.
StateDerivativeType The type of the state derivative. This type should be an Eigen::Matrix derived type.
IndependentVariableType The type of the independent variable. This type should be either a float or double.
See also
NumericalIntegrator.
Definition at line 50 of file rungeKuttaVariableStepSizeIntegrator.h.
Member Typedef Documentation
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> typedef boost::function< std::pair< TimeStepType, bool > const TimeStepType, const TimeStepType, const TimeStepType, const TimeStepType, const StateType&, const StateType&, const StateType&, const StateType&) > tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::NewStepSizeFunction
Typedef to the function used to compute the new step size. This should be a pointer to a function or a boost function.
Definition at line 65 of file rungeKuttaVariableStepSizeIntegrator.h.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> typedef numerical_integrators::ReinitializableNumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType > tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::ReinitializableNumericalIntegratorBase
Typedef of the base class with all template parameters filled in.
Definition at line 73 of file rungeKuttaVariableStepSizeIntegrator.h.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> typedef ReinitializableNumericalIntegratorBase::NumericalIntegratorBase:: StateDerivativeFunction tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::StateDerivativeFunction
Typedef to the state derivative function inherited from the base class.
See also
NumericalIntegrator::StateDerivativeFunction.
Definition at line 81 of file rungeKuttaVariableStepSizeIntegrator.h.
Constructor & Destructor Documentation
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::RungeKuttaVariableStepSizeIntegrator (const RungeKuttaCoefficients & coefficients, const StateDerivativeFunction & stateDerivativeFunction, const IndependentVariableType intervalStart, const StateType & initialState, const IndependentVariableType minimumStepSize, const IndependentVariableType maximumStepSize, const StateType & relativeErrorTolerance, const StateType & absoluteErrorTolerance, const TimeStepType safetyFactorForNextStepSize = 0.8, const TimeStepType maximumFactorIncreaseForNextStepSize = 4.0, const TimeStepType minimumFactorDecreaseForNextStepSize = 0.1, const NewStepSizeFunction & newStepSizeFunction = 0) inline
Default constructor, taking coefficients, a state derivative function, initial conditions, minimum & maximum step size and relative & absolute error tolerance per item in the state vector as argument.
Parameters
coefficients Coefficients to use with this integrator.
stateDerivativeFunction State derivative function.
intervalStart The start of the integration interval.
initialState The initial state.
minimumStepSize The minimum step size to take. If this constraint is violated, an exception will be thrown and the next state is computed using the minimum value.
maximumStepSize The maximum step size to take. If this constraint is violated, an exception will be thrown and the next state is computed using the maximum value.
relativeErrorTolerance The relative error tolerance, for each individual state vector element.
absoluteErrorTolerance The absolute error tolerance, for each individual state vector element.
safetyFactorForNextStepSize Safety factor used to scale prediction of next step size.
maximumFactorIncreaseForNextStepSize Maximum factor increase for next step size.
minimumFactorDecreaseForNextStepSize Maximum factor decrease for next step size.
newStepSizeFunction Function that returns the new step size computed, default: RungeKuttaVariableStepSizeIntegrator::computeNewStepSize.
See also
NumericalIntegrator::NumericalIntegrator.
Definition at line 114 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNewStepSize(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::newStepSizeFunction_.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::RungeKuttaVariableStepSizeIntegrator (const RungeKuttaCoefficients & coefficients, const StateDerivativeFunction & stateDerivativeFunction, const IndependentVariableType intervalStart, const StateType & initialState, const TimeStepType minimumStepSize, const TimeStepType maximumStepSize, const typename StateType::Scalar relativeErrorTolerance, const typename StateType::Scalar absoluteErrorTolerance, const TimeStepType safetyFactorForNextStepSize = 0.8, const TimeStepType maximumFactorIncreaseForNextStepSize = 4.0, const TimeStepType minimumFactorDecreaseForNextStepSize = 0.1, const NewStepSizeFunction & newStepSizeFunction = 0) inline
Default constructor, taking coefficients a state derivative function, initial conditions, minimum & maximum step size and relative & absolute error tolerance for all items in the state vector as argument.
Parameters
coefficients Coefficients to use with this integrator.
stateDerivativeFunction State derivative function.
intervalStart The start of the integration interval.
initialState The initial state.
minimumStepSize The minimum step size to take. If this constraint is violated, an exception will be thrown and the next state is computed using the minimum value.
maximumStepSize The maximum step size to take. If this constraint is violated, an exception will be thrown and the next state is computed using the maximum value.
relativeErrorTolerance The relative error tolerance, equal for all individual state vector elements.
absoluteErrorTolerance The absolute error tolerance, equal for all individual state vector elements.
safetyFactorForNextStepSize Safety factor used to scale prediction of next step size.
maximumFactorIncreaseForNextStepSize Maximum factor increase for next step size.
minimumFactorDecreaseForNextStepSize Maximum factor decrease for next step size.
newStepSizeFunction Function that returns the new step size computed, default: RungeKuttaVariableStepSizeIntegrator::computeNewStepSize.
See also
NumericalIntegrator::NumericalIntegrator.
Definition at line 174 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNewStepSize(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::newStepSizeFunction_.
Member Function Documentation
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual TimeStepType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getNextStepSize () const inline virtual
Returns the step size of the next step.
Returns
Step size to be used for the next step.
Implements tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Definition at line 217 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::stepSize_.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual StateType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentState () const inline virtual
Returns the current state of the integrator.
Returns
Current integrated state.
Implements tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Definition at line 224 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentState_.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual IndependentVariableType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentIndependentVariable () const inline virtual
Returns the current value of the independent variable of the integrator.
Returns
Current independent variable.
Implements tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Definition at line 231 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentIndependentVariable_.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> std::vector< StateDerivativeType > tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentStateDerivatives () inline
Returns the current state derivatives, i.e., the values of k_{i} (stage evaluations) in Runge-Kutta scheme.
Returns
Current state derivatives evaluated according to stages of Runge-Kutta scheme.
Definition at line 242 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentStateDerivatives_, and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep().
template<typename IndependentVariableType , typename StateType , typename StateDerivativeType , typename TimeStepType > StateType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep (const TimeStepType stepSize) virtual
Perform a single integration step and compute a new step size.
Parameters
stepSize The step size to take. If the time step is too large to satisfy the error constraints, the step is redone until the error constraint is satisfied.
Returns
The state at the end of the interval.
Implements tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Definition at line 434 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaCoefficients::aCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::bCoefficients, tudat::numerical_integrators::RungeKuttaCoefficients::cCoefficients, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::coefficients_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentIndependentVariable_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentState_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentStateDerivatives_, tudat::numerical_integrators::RungeKuttaCoefficients::higher, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::lastIndependentVariable_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::lastState_, tudat::numerical_integrators::RungeKuttaCoefficients::lower, tudat::numerical_integrators::RungeKuttaCoefficients::orderEstimateToIntegrate, tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::propagationTerminationConditionReachedDuringStep_, tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::propagationTerminationFunction_, tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::stateDerivativeFunction_, and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::stepSize_.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentStateDerivatives().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual bool tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::rollbackToPreviousState () inline virtual
Performs rollback of the internal state to the last state. This function can only be called once after calling integrateTo() or performIntegrationStep() unless specified otherwise by implementations, and can not be called before any of these functions have been called. Will return true if the rollback was successful, and false otherwise.
Returns
True if the rollback was successful.
Implements tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Definition at line 264 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentIndependentVariable_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentState_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::lastIndependentVariable_, and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::lastState_.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> void tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::modifyCurrentState (const StateType & newState) inline virtual
Modify the state at the current interval. This allows for discrete jumps in the state, often used in simulations of discrete events. In astrodynamics, this relates to simulations of rocket staging, impulsive shots, parachuting, attitude normalization, ideal control, etc. The modified state cannot be rolled back; to do this, just simply store the state before calling this function the first time, and call it again with the initial state as parameter to revert to the state before the discrete change.
Parameters
newState The state to set the current state to.
Implements tudat::numerical_integrators::ReinitializableNumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Definition at line 286 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNewStepSize(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentIndependentVariable_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentState_, and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::lastIndependentVariable_.
template<typename IndependentVariableType , typename StateType , typename StateDerivativeType , typename TimeStepType > bool tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult (const StateType & lowerOrderEstimate, const StateType & higherOrderEstimate, const TimeStepType stepSize) protected virtual
Compute the next step size and validate the result.
Computes the next step size based on a higher and lower order estimate, determines if the error is within bounds and returns a new step size.
Parameters
lowerOrderEstimate The integrated result with the lower order coefficients.
higherOrderEstimate The integrated result with the higher order coefficients.
stepSize The step size used to obtain these results.
Returns
True if teh error was within bounds, false otherwise.
Definition at line 512 of file rungeKuttaVariableStepSizeIntegrator.h.
References tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::coefficients_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNewStepSize(), tudat::numerical_integrators::RungeKuttaCoefficients::lowerOrder, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::maximumFactorIncreaseForNextStepSize_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::maximumStepSize_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::minimumFactorDecreaseForNextStepSize_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::minimumStepSize_, tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::newStepSizeFunction_, and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::stepSize_.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::modifyCurrentState(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep().
template<typename IndependentVariableType , typename StateType , typename StateDerivativeType , typename TimeStepType > std::pair< TimeStepType, bool > tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNewStepSize (const TimeStepType stepSize, const TimeStepType lowerOrder, const TimeStepType higherOrder, const TimeStepType safetyFactorForNextStepSize, const StateType & relativeErrorTolerance, const StateType & absoluteErrorTolerance, const StateType & lowerOrderEstimate, const StateType & higherOrderEstimate) protected virtual
Computes the new step size based on a generic definition of the local truncation error.
Parameters
stepSize Integration step size of current step.
lowerOrder Lower of the two orders of the two schemes used in variable step size integration.
higherOrder Higher of the two orders of the two schemes used in variable step size integration.
safetyFactorForNextStepSize Safety factor used to scale prediction of next step size.
relativeErrorTolerance Allowable relative error between integrations using two schemes.
absoluteErrorTolerance Allowable relative error between integrations using two schemes.
lowerOrderEstimate Numerical integration result using lower order scheme.
higherOrderEstimate Numerical integration result using higher order scheme.
Returns
Pair with new step size and a boolean denoting whether the step size computation was succesfull, i.e. whether tolerances etc. are met.
Computes the new step size based on a generic definition of the local truncation error.
Definition at line 569 of file rungeKuttaVariableStepSizeIntegrator.h.
References TUDAT_UNUSED_PARAMETER.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::modifyCurrentState(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::RungeKuttaVariableStepSizeIntegrator().
Member Data Documentation
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> TimeStepType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::stepSize_ protected
Last used step size, passed to either integrateTo() or performIntegrationStep().
Definition at line 336 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getNextStepSize(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> IndependentVariableType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentIndependentVariable_ protected
Current independent variable as computed by performIntegrationStep().
Definition at line 342 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentIndependentVariable(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::modifyCurrentState(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::rollbackToPreviousState().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> StateType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentState_ protected
Current state as computed by performIntegrationStep().
Definition at line 348 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentState(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::modifyCurrentState(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::rollbackToPreviousState().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> IndependentVariableType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::lastIndependentVariable_ protected
Last independent variable value as computed by performIntegrationStep().
Definition at line 354 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::modifyCurrentState(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::rollbackToPreviousState().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> StateType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::lastState_ protected
Last state as computed by performIntegrationStep().
Definition at line 360 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::rollbackToPreviousState().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> RungeKuttaCoefficients tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::coefficients_ protected
Coefficients for the integrator, as defined by the Butcher tableau.
Definition at line 366 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> TimeStepType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::minimumStepSize_ protected
Minimum step size.
Definition at line 372 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> TimeStepType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::maximumStepSize_ protected
Maximum step size.
Definition at line 378 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> StateType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::relativeErrorTolerance_ protected
Relative error tolerance per element in the state.
Definition at line 384 of file rungeKuttaVariableStepSizeIntegrator.h.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> StateType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::absoluteErrorTolerance_ protected
Absolute error tolerance per element in the state.
Definition at line 390 of file rungeKuttaVariableStepSizeIntegrator.h.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> TimeStepType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::safetyFactorForNextStepSize_ protected
Safety factor used to scale prediction of next step size. This is usually picked between 0.8 and 0.9 (Burden and Faires, 2001).
Definition at line 397 of file rungeKuttaVariableStepSizeIntegrator.h.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> TimeStepType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::maximumFactorIncreaseForNextStepSize_ protected
The maximum factor by which the next step size can increase compared to the current value. The need for this maximum stems from a need to ensure that the step size changes do not alias with the dynamics of the model being integrated. This is typically set at 4.0, based on numerical experiments (Burden and Faires, 2001).
Definition at line 406 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> TimeStepType tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::minimumFactorDecreaseForNextStepSize_ protected
The minimum factor by which the next step size can decrease compared to the current value. The need for this minimum stems from a need to ensure that the step size changes do not alias with the dynamics of the model being integrated. This is typically set at 0.1, based on numerical experiments (Burden and Faires, 2001).
Definition at line 415 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> NewStepSizeFunction tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::newStepSizeFunction_ protected
Function that returns the new step size computed, as passed to the constructor.
Definition at line 421 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::computeNextStepSizeAndValidateResult(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::RungeKuttaVariableStepSizeIntegrator().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> std::vector< StateDerivativeType > tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::currentStateDerivatives_ protected
Vector of state derivatives, i.e. values of k_{i} in Runge-Kutta scheme.
Definition at line 427 of file rungeKuttaVariableStepSizeIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentStateDerivatives(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep().
The documentation for this class was generated from the following file:
Mathematics/NumericalIntegrators/rungeKuttaVariableStepSizeIntegrator.h