Tudat: tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType > Class Template Reference
tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType > Class Template Reference
Trapezoid numerical quadrature wrapper class.
#include <trapezoidQuadrature.h>
Public Member Functions
TrapezoidNumericalQuadrature (const std::vector< IndependentVariableType > &independentVariables, const std::vector< DependentVariableType > &dependentVariables)
Constructor.
DependentVariableType getQuadrature ()
Function to return computed value of the quadrature.
void resetData (const std::vector< IndependentVariableType > &independentVariables, const std::vector< DependentVariableType > &dependentVariables)
Function to reset the (in)dependent variable values.
Public Member Functions inherited from tudat::numerical_quadrature::NumericalQuadrature< IndependentVariableType, DependentVariableType >
virtual ~NumericalQuadrature ()
Destructor.
Protected Member Functions
void performQuadrature ()
Function that is called to perform the numerical quadrature.
Private Attributes
std::vector< DependentVariableType > dependentVariables_
Dependent variables.
std::vector< IndependentVariableType > independentVariables_
Independent variables.
DependentVariableType quadratureResult_
Computed value of the quadrature, as computed by last call to performQuadrature.
Detailed Description
template<typename IndependentVariableType, typename DependentVariableType>
class tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >
Numerical method that uses the trapezoid method to compute definite integrals of a dataset.
Definition at line 118 of file trapezoidQuadrature.h.
Constructor & Destructor Documentation
TrapezoidNumericalQuadrature()
template<typename IndependentVariableType , typename DependentVariableType > tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::TrapezoidNumericalQuadrature (const std::vector< IndependentVariableType > & independentVariables, const std::vector< DependentVariableType > & dependentVariables) inline
Constructor
Parameters
independentVariables Values of independent variables at which dependentVariables are given
dependentVariables Values of function for which the numerical quadrature is to be computed, given at independentVariables.
Definition at line 129 of file trapezoidQuadrature.h.
References tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::dependentVariables_, tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::independentVariables_, and tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::performQuadrature().
Member Function Documentation
resetData()
template<typename IndependentVariableType , typename DependentVariableType > void tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::resetData (const std::vector< IndependentVariableType > & independentVariables, const std::vector< DependentVariableType > & dependentVariables) inline
Function to reset the (in)dependent variable values.
Parameters
independentVariables Values of independent variables at which dependentVariables are given
dependentVariables Values of function for which the numerical quadrature is to be computed, given at independentVariables.
Definition at line 144 of file trapezoidQuadrature.h.
References tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::dependentVariables_, tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::independentVariables_, and tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::performQuadrature().
getQuadrature()
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::getQuadrature () inline virtual
Function to return computed value of the quadrature, as computed by last call to performQuadrature.
Returns
Function to return computed value of the quadrature, as computed by last call to performQuadrature.
Implements tudat::numerical_quadrature::NumericalQuadrature< IndependentVariableType, DependentVariableType >.
Definition at line 157 of file trapezoidQuadrature.h.
References tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::quadratureResult_.
performQuadrature()
template<typename IndependentVariableType , typename DependentVariableType > void tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::performQuadrature () inline protected virtual
Function that is called to perform the numerical quadrature. Sets the result in the quadratureResult_ local variable.
Implements tudat::numerical_quadrature::NumericalQuadrature< IndependentVariableType, DependentVariableType >.
Definition at line 169 of file trapezoidQuadrature.h.
References tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::dependentVariables_, tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::independentVariables_, tudat::numerical_quadrature::performTrapezoidalQuadrature(), and tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::quadratureResult_.
Referenced by tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::resetData(), and tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::TrapezoidNumericalQuadrature().
Member Data Documentation
independentVariables_
template<typename IndependentVariableType , typename DependentVariableType > std::vector< IndependentVariableType > tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::independentVariables_ private
Definition at line 177 of file trapezoidQuadrature.h.
Referenced by tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::performQuadrature(), tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::resetData(), and tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::TrapezoidNumericalQuadrature().
dependentVariables_
template<typename IndependentVariableType , typename DependentVariableType > std::vector< DependentVariableType > tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::dependentVariables_ private
Definition at line 180 of file trapezoidQuadrature.h.
Referenced by tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::performQuadrature(), tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::resetData(), and tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::TrapezoidNumericalQuadrature().
quadratureResult_
template<typename IndependentVariableType , typename DependentVariableType > DependentVariableType tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::quadratureResult_ private
Definition at line 183 of file trapezoidQuadrature.h.
Referenced by tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::getQuadrature(), and tudat::numerical_quadrature::TrapezoidNumericalQuadrature< IndependentVariableType, DependentVariableType >::performQuadrature().
The documentation for this class was generated from the following file:
Mathematics/NumericalQuadrature/trapezoidQuadrature.h