Tudat: tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType > Class Template Reference
tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType > Class Template Reference abstract
Base class for the numerical integrators.
#include <numericalIntegrator.h>
Public Types
typedef boost::function< StateDerivativeType(const IndependentVariableType, const StateType &) > StateDerivativeFunction
Typedef to the state derivative function.
Public Member Functions
NumericalIntegrator (const StateDerivativeFunction &stateDerivativeFunction)
Default constructor.
virtual ~NumericalIntegrator ()
Default virtual destructor.
virtual IndependentVariableType getCurrentIndependentVariable () const =0
Get current independent variable.
virtual StateType getCurrentState () const =0
Get current state.
virtual TimeStepType getNextStepSize () const =0
Get step size of the next step.
bool getPropagationTerminationConditionReached ()
Function to return the termination condition was reached during the current step.
StateDerivativeFunction getStateDerivativeFunction ()
Function to return the function that computes and returns the state derivative.
virtual StateType integrateTo (const IndependentVariableType intervalEnd, const TimeStepType initialStepSize, const TimeStepType finalTimeTolerance=std::numeric_limits< TimeStepType >::epsilon())
Perform an integration to a specified independent variable value.
virtual StateType performIntegrationStep (const TimeStepType stepSize)=0
Perform a single integration step.
virtual bool rollbackToPreviousState ()=0
Rollback internal state to the step performed by performIntegrationStep()
void setPropagationTerminationFunction (boost::function< bool(const double) > terminationFunction)
Setter for the (optional) propagation termination function.
Protected Attributes
bool propagationTerminationConditionReachedDuringStep_ = false
Boolean to denote whether the propagation termination condition was reached during the evaluation of one of the sub-steps.
boost::function< bool(const double) > propagationTerminationFunction_ = boost::lambda::constant(false)
Propagation termination function.
StateDerivativeFunction stateDerivativeFunction_
Function that returns the state derivative.
Detailed Description
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType>
class tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >
Base class for numerical integrators.
Template Parameters
StateType The type of the state. This type should support addition, subtraction and assignment operators.
StateDerivativeType The type of the state derivative. This type should support multiplication with IndependentVariableType and doubles.
IndependentVariableType The type of the independent variable.
Definition at line 39 of file numericalIntegrator.h.
Member Typedef Documentation
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> typedef boost::function< StateDerivativeType(const IndependentVariableType, const StateType&) > tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::StateDerivativeFunction
Typedef to the state derivative function. This should be a pointer to a function or a boost function.
Definition at line 49 of file numericalIntegrator.h.
Constructor & Destructor Documentation
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::NumericalIntegrator (const StateDerivativeFunction & stateDerivativeFunction) inline
Default constructor, taking a state derivative function as argument.
Parameters
stateDerivativeFunction State derivative function.
Definition at line 56 of file numericalIntegrator.h.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::~NumericalIntegrator () inline virtual
Default virtual destructor.
Definition at line 63 of file numericalIntegrator.h.
References tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentIndependentVariable(), tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentState(), tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getNextStepSize(), tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::integrateTo(), tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), and tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::rollbackToPreviousState().
Member Function Documentation
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual TimeStepType tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getNextStepSize () const pure virtual
Returns the step size of the next step. Derived classes should override this and provide the last step size that was computed or passed to performIntegrationStep().
Returns
Step size to be used for the next step.
Implemented in tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, tudat::numerical_integrators::EulerIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, and tudat::numerical_integrators::RungeKutta4Integrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Referenced by tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::integrateTo(), and tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::~NumericalIntegrator().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual StateType tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentState () const pure virtual
Returns the current state of the integrator. Derived classes should override this and provide the computed state by performIntegrationStep().
Returns
Current integrated state.
Implemented in tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, tudat::numerical_integrators::EulerIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, and tudat::numerical_integrators::RungeKutta4Integrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Referenced by tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::integrateTo(), and tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::~NumericalIntegrator().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual IndependentVariableType tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentIndependentVariable () const pure virtual
Returns the current value of the independent variable of the integrator. Derived classes should override this and provide the computed independent variable by performIntegrationStep().
Returns
Current independent variable.
Implemented in tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, tudat::numerical_integrators::EulerIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, and tudat::numerical_integrators::RungeKutta4Integrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Referenced by tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::integrateTo(), and tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::~NumericalIntegrator().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual bool tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::rollbackToPreviousState () pure virtual
Performs rollback of internal state to the step performed by performIntegrationStep(). This is not necessarily equal the start of the integration interval after integrateTo() has been. called. This function can only be called once after calling or performIntegrationStep() unless specified otherwise by implementations, and can not be called before integrateTo() has been called. Will return true if the rollback was successful, and false otherwise.
Returns
True if the rollback was successful.
Implemented in tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, tudat::numerical_integrators::RungeKutta4Integrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, and tudat::numerical_integrators::EulerIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Referenced by tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::~NumericalIntegrator().
template<typename IndependentVariableType , typename StateType , typename StateDerivativeType , typename TimeStepType > StateType tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::integrateTo (const IndependentVariableType intervalEnd, const TimeStepType initialStepSize, const TimeStepType finalTimeTolerance = std::numeric_limits< TimeStepType >::epsilon()) virtual
Performs an integration to independentVariableEnd with initial state and initial independent variable value specified by the current state of the integrator and the current independent variable value. This implementation of integrateTo chooses the final step size such that it exactly coincides with the given independentVariableEnd.
Parameters
intervalEnd The value of the independent variable at the end of the interval to integrate over.
initialStepSize The initial step size to use.
finalTimeTolerance Tolerance to within which the final time should be reached.
Returns
The state at independentVariableEnd.
Definition at line 190 of file numericalIntegrator.h.
References tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentIndependentVariable(), tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getCurrentState(), tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getNextStepSize(), and tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep().
Referenced by tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::~NumericalIntegrator().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> virtual StateType tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep (const TimeStepType stepSize) pure virtual
Performs a single integration step from current independent variable and state as specified by initialStateHistory and specified stepSize. This function should determine the next step and make it available to getNextStepSize(), return the current state and store it for getCurrentState(), and store the current independent variable value for getCurrentIndependentVariable().
Parameters
stepSize The step size of this step.
Returns
The state at the end of the interval.
Implemented in tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, tudat::numerical_integrators::EulerIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >, and tudat::numerical_integrators::RungeKutta4Integrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >.
Referenced by tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::integrateTo(), and tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::~NumericalIntegrator().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> StateDerivativeFunction tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getStateDerivativeFunction () inline
Function to return the function that computes and returns the state derivative
Returns
Function that returns the state derivative
Definition at line 136 of file numericalIntegrator.h.
References tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::stateDerivativeFunction_.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> bool tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getPropagationTerminationConditionReached () inline
Function to return the termination condition was reached during the current step
Returns
True if the termination condition was reached during the current step
Definition at line 146 of file numericalIntegrator.h.
References tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::propagationTerminationConditionReachedDuringStep_.
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> void tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::setPropagationTerminationFunction (boost::function< bool(const double) > terminationFunction) inline
Setter for the (optional) propagation termination function, to be evaluated during the intermediate state updates performed to compute the quantities necessary to integrate the state to a new epoch (e.g. k1-k4 for RK$).
Parameters
terminationFunction Function that returns true if termination condition is reached, false if it has not, as a function of current time.
Definition at line 158 of file numericalIntegrator.h.
References tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::propagationTerminationFunction_.
Member Data Documentation
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> StateDerivativeFunction tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::stateDerivativeFunction_ protected
Function that returns the state derivative, as passed to the constructor.
Definition at line 169 of file numericalIntegrator.h.
Referenced by tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getStateDerivativeFunction(), tudat::numerical_integrators::RungeKutta4Integrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), tudat::numerical_integrators::EulerIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> bool tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::propagationTerminationConditionReachedDuringStep_ = false protected
Boolean to denote whether the propagation termination condition was reached during the evaluation of one of the sub-steps necessary to perform the last integration step. Parameter is false by default, and when set to true must be accompanied by propagationTerminationFunction_ (which is non-active by default)
Definition at line 176 of file numericalIntegrator.h.
Referenced by tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::getPropagationTerminationConditionReached(), tudat::numerical_integrators::RungeKutta4Integrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), and tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep().
template<typename IndependentVariableType = double, typename StateType = Eigen::VectorXd, typename StateDerivativeType = StateType, typename TimeStepType = IndependentVariableType> boost::function< bool(const double) > tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::propagationTerminationFunction_ = boost::lambda::constant(false) protected
Propagation termination function to be evaluated during the intermediate state updates performed to compute the quantities necessary to integrate the state to a new epoch. By default, this function evaluates always to false, so the propagation termination conditions will not be checked during the integration subteps.
Definition at line 185 of file numericalIntegrator.h.
Referenced by tudat::numerical_integrators::RungeKutta4Integrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::performIntegrationStep(), and tudat::numerical_integrators::NumericalIntegrator< IndependentVariableType, StateType, StateDerivativeType, TimeStepType >::setPropagationTerminationFunction().
The documentation for this class was generated from the following file:
Mathematics/NumericalIntegrators/numericalIntegrator.h