Tudat: tudat::ephemerides::ApproximatePlanetPositions Class Reference
tudat::ephemerides::ApproximatePlanetPositions Class Reference
Ephemeris class using JPL "Approximate Positions of Major Planets".
#include <approximatePlanetPositions.h>
Public Member Functions
ApproximatePlanetPositions (BodiesWithEphemerisData bodyWithEphemerisData, const double aSunGravitationalParameter=1.32712440018e20, const double referenceJulianDate=basic_astrodynamics::JULIAN_DAY_ON_J2000)
Default constructor.
Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)
Get cartesian state from ephemeris.
Eigen::Vector6d getKeplerianStateFromEphemeris (const double secondsSinceEpoch)
Get keplerian state from ephemeris.
Public Member Functions inherited from tudat::ephemerides::ApproximatePlanetPositionsBase
ApproximatePlanetPositionsBase (const double aSunGravitationalParameter)
Default constructor.
virtual ~ApproximatePlanetPositionsBase ()
Default destructor.
double getSunGravitationalParameter ()
Returns the gravitational parameter of the Sun.
void parseEphemerisLineData_ (const unsigned int &firstLineNumber)
Parse ephemeris line data.
void parseExtraTermsEphemerisLineData_ (const unsigned int &lineNumber)
Parse line data for extra terms for ephemeris.
void reloadData ()
Load in ephemeris data for planets.
Public Member Functions inherited from tudat::ephemerides::Ephemeris
Ephemeris (const std::string &referenceFrameOrigin="", const std::string &referenceFrameOrientation="")
Constructor.
virtual ~Ephemeris ()
Default destructor.
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get state from ephemeris (with long double as state scalar).
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with long double as state scalar and Time as time type).
virtual Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with double as state scalar and Time as time type).
std::string getReferenceFrameOrientation ()
Get reference frame orientation.
std::string getReferenceFrameOrigin ()
Get reference frame origin.
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (double specialization).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (long double specialization).
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (double specialization with Time input).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (long double specialization with Time input).
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > getTemplatedStateFromEphemeris (const TimeType &time)
Get state from ephemeris, with state scalar as template type.
Private Attributes
double eccentricAnomalyAtGivenJulianDate_
Eccentric anomaly at given Julian date.
double longitudeOfPerihelionAtGivenJulianDate_
Longitude of perihelion at given Julian date.
double meanAnomalyAtGivenJulianDate_
Mean anomaly at given Julian date.
double referenceJulianDate_
double trueAnomalyAtGivenJulianData_
True anomaly at given Julian date.
Additional Inherited Members
Public Types inherited from tudat::ephemerides::ApproximatePlanetPositionsBase
enum BodiesWithEphemerisData {
mercury, venus, earthMoonBarycenter, mars,
jupiter, saturn, uranus, neptune,
pluto
}
Bodies with ephemeris data.
Protected Member Functions inherited from tudat::ephemerides::ApproximatePlanetPositionsBase
void setPlanet (BodiesWithEphemerisData bodyWithEphemerisData)
Set planet.
Protected Attributes inherited from tudat::ephemerides::ApproximatePlanetPositionsBase
ApproximatePlanetPositionsDataContainer approximatePlanetPositionsDataContainer_
Approximate planet positions data container.
std::map< unsigned int, std::string > containerOfDataFromEphemerisFile_
Map container of data from ephemeris file.
std::stringstream ephemerisLineData_
String stream for ephemeris line data.
double julianDate_
Julian date.
double meanLongitudeAtGivenJulianDate_
Mean longitude at given Julian date.
double numberOfCenturiesPastJ2000_
Number of centuries passed J2000.
Eigen::Vector6d planetKeplerianElementsAtGivenJulianDate_
Keplerian elements of planet at given Julian date.
const double sunGravitationalParameter
Gravitational parameter of the Sun.
Protected Attributes inherited from tudat::ephemerides::Ephemeris
std::string referenceFrameOrientation_
Reference frame orientation.
std::string referenceFrameOrigin_
Reference frame origin.
Detailed Description
Ephemeris class using JPL "Approximate Positions of Major Planets".
Definition at line 37 of file approximatePlanetPositions.h.
Constructor & Destructor Documentation
tudat::ephemerides::ApproximatePlanetPositions::ApproximatePlanetPositions (BodiesWithEphemerisData bodyWithEphemerisData, const double aSunGravitationalParameter = 1.32712440018e20, const double referenceJulianDate = basic_astrodynamics::JULIAN_DAY_ON_J2000) inline
Default constructor that initializes the class from the body for which the position is approximated and the gravitational parameter of the Sun (default 1.32712440018e20). Other members are initialized to default values (NAN).
Parameters
bodyWithEphemerisData The body for which the position is approximated.
aSunGravitationalParameter The gravitational parameter of the Sun [m^3/s^2].
referenceJulianDate Reference julian day w.r.t. which ephemeris is evaluated.
See also
BodiesWithEphemerisData, ApproximatePlanetPositionsBase.
Definition at line 54 of file approximatePlanetPositions.h.
References getCartesianState(), getKeplerianStateFromEphemeris(), and tudat::ephemerides::ApproximatePlanetPositionsBase::setPlanet().
Member Function Documentation
Eigen::Vector6d tudat::ephemerides::ApproximatePlanetPositions::getCartesianState (const double secondsSinceEpoch) virtual
Get state from ephemeris.
Returns cartesian state from ephemeris.
Parameters
secondsSinceEpoch Seconds since epoch.
Returns
State in Cartesian elements from ephemeris.
Implements tudat::ephemerides::Ephemeris.
Definition at line 31 of file approximatePlanetPositions.cpp.
References tudat::orbital_element_conversions::convertKeplerianToCartesianElements(), getKeplerianStateFromEphemeris(), and tudat::ephemerides::ApproximatePlanetPositionsBase::sunGravitationalParameter.
Referenced by ApproximatePlanetPositions().
Eigen::Vector6d tudat::ephemerides::ApproximatePlanetPositions::getKeplerianStateFromEphemeris (const double secondsSinceEpoch)
Returns keplerian state in from ephemeris.
Parameters
secondsSinceEpoch Seconds since epoch.
Returns
State in Keplerian elements from ephemeris.
Definition at line 42 of file approximatePlanetPositions.cpp.
References tudat::ephemerides::ApproximatePlanetPositionsDataContainer::additionalTermB_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::additionalTermC_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::additionalTermF_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::additionalTermS_, tudat::ephemerides::ApproximatePlanetPositionsBase::approximatePlanetPositionsDataContainer_, tudat::orbital_element_conversions::argumentOfPeriapsisIndex, tudat::basic_mathematics::computeModulo(), tudat::unit_conversions::convertAstronomicalUnitsToMeters(), tudat::unit_conversions::convertDegreesToRadians(), tudat::orbital_element_conversions::convertEccentricAnomalyToTrueAnomaly(), tudat::orbital_element_conversions::convertMeanAnomalyToEccentricAnomaly(), tudat::basic_astrodynamics::convertSecondsSinceEpochToJulianDay(), eccentricAnomalyAtGivenJulianDate_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::eccentricity_, tudat::orbital_element_conversions::eccentricityIndex, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::inclination_, tudat::orbital_element_conversions::inclinationIndex, tudat::ephemerides::ApproximatePlanetPositionsBase::julianDate_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::longitudeOfAscendingNode_, tudat::orbital_element_conversions::longitudeOfAscendingNodeIndex, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::longitudeOfPerihelion_, longitudeOfPerihelionAtGivenJulianDate_, meanAnomalyAtGivenJulianDate_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::meanLongitude_, tudat::ephemerides::ApproximatePlanetPositionsBase::meanLongitudeAtGivenJulianDate_, tudat::ephemerides::ApproximatePlanetPositionsBase::numberOfCenturiesPastJ2000_, tudat::ephemerides::ApproximatePlanetPositionsBase::planetKeplerianElementsAtGivenJulianDate_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfEccentricity_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfInclination_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfLongitudeOfAscendingNode_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfLongitudeOfPerihelion_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfMeanLongitude_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::rateOfChangeOfSemiMajorAxis_, referenceJulianDate_, tudat::ephemerides::ApproximatePlanetPositionsDataContainer::semiMajorAxis_, tudat::orbital_element_conversions::semiMajorAxisIndex, trueAnomalyAtGivenJulianData_, and tudat::orbital_element_conversions::trueAnomalyIndex.
Referenced by ApproximatePlanetPositions(), and getCartesianState().
Member Data Documentation
double tudat::ephemerides::ApproximatePlanetPositions::referenceJulianDate_ private
Definition at line 89 of file approximatePlanetPositions.h.
Referenced by getKeplerianStateFromEphemeris().
double tudat::ephemerides::ApproximatePlanetPositions::eccentricAnomalyAtGivenJulianDate_ private
Eccentric anomaly of planet at given Julian date.
Definition at line 95 of file approximatePlanetPositions.h.
Referenced by getKeplerianStateFromEphemeris().
double tudat::ephemerides::ApproximatePlanetPositions::longitudeOfPerihelionAtGivenJulianDate_ private
Longitude of perihelion of planet at given Julian date.
Definition at line 101 of file approximatePlanetPositions.h.
Referenced by getKeplerianStateFromEphemeris().
double tudat::ephemerides::ApproximatePlanetPositions::meanAnomalyAtGivenJulianDate_ private
Mean anomaly of planet at given Julian date.
Definition at line 107 of file approximatePlanetPositions.h.
Referenced by getKeplerianStateFromEphemeris().
double tudat::ephemerides::ApproximatePlanetPositions::trueAnomalyAtGivenJulianData_ private
True anomaly of planet at given Julian date.
Definition at line 113 of file approximatePlanetPositions.h.
Referenced by getKeplerianStateFromEphemeris().
The documentation for this class was generated from the following files:
Astrodynamics/Ephemerides/approximatePlanetPositions.h
Astrodynamics/Ephemerides/approximatePlanetPositions.cpp