Tudat: tudat::propulsion::ParameterizedThrustMagnitudeWrapper Class Reference
tudat::propulsion::ParameterizedThrustMagnitudeWrapper Class Reference
Class to compute the engine thrust and specific impulse as a parameterized function of any number of indepedent variables.
#include <thrustMagnitudeWrapper.h>
Public Member Functions
ParameterizedThrustMagnitudeWrapper (const std::function< double(const std::vector< double > &) > thrustMagnitudeFunction, const std::function< double(const std::vector< double > &) > specificImpulseFunction, const std::vector< std::function< double() > > thrustInputVariableFunctions, const std::vector< std::function< double() > > specificImpulseInputVariableFunctions, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables, const std::function< void(const double) > inputUpdateFunction=std::function< void(const double) >())
Constructor for parameterized thrust and specific impulse.
~ParameterizedThrustMagnitudeWrapper ()
Destructor.
double getCurrentMassRate ()
Function to return the current mass rate.
double getCurrentThrustMagnitude ()
Function to return the current thrust magnitude.
virtual void resetDerivedClassCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the thrust model derived class.
void update (const double time)
Function to update the thrust magnitude to the current time.
Public Member Functions inherited from tudat::propulsion::ThrustMagnitudeWrapper
ThrustMagnitudeWrapper ()
Constructor.
virtual ~ThrustMagnitudeWrapper ()
Destructor.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the thrust model.
Private Attributes
double currentSpecificImpulse_
Current specific impulse, as computed by last call to update member function.
std::vector< double > currentSpecificImpulseInputVariables_
List of current input data to specific impulse function.
std::vector< double > currentThrustInputVariables_
List of current input data to thrust function.
double currentThrustMagnitude_
Current thrust magnitude, as computed by last call to update member function.
const std::function< void(const double) > inputUpdateFunction_
Function that is called to update the user-defined guidance to the current time.
std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables_
std::function< double(const std::vector< double > &) > specificImpulseFunction_
Function returning the current specific impulse as a function of its independent variables.
std::vector< std::function< double() > > specificImpulseInputVariableFunctions_
List of functions returning input variables for specificImpulseFunction_.
std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables_
std::vector< std::function< double() > > thrustInputVariableFunctions_
List of functions returning input variables for thrustMagnitudeFunction_.
std::function< double(const std::vector< double > &) > thrustMagnitudeFunction_
Function returning the current thrust as a function of its independent variables.
Additional Inherited Members
Protected Attributes inherited from tudat::propulsion::ThrustMagnitudeWrapper
double currentTime_
Current time for model.
Detailed Description
Class to compute the engine thrust and specific impulse as a parameterized function of any number of indepedent variables.
The physical meaning of the variables must be defined here, selecting from the options in the ThrustIndependentVariables enum, and they are automatically retrieved from the relevant environment models during the propagation. Note that any number of user-specific functions may be included, as a guidance_input_dependent_thrust type or throttle_dependent_thrust. Note that a throttle_dependent_thrust may not be used as one of the independent variables of the thrust magnitude for this class. This setting is parsed through the ParameterizedThrustMagnitudeSettings class, which is the class that is typically used to create this class.
Definition at line 331 of file thrustMagnitudeWrapper.h.
Constructor & Destructor Documentation
ParameterizedThrustMagnitudeWrapper()
tudat::propulsion::ParameterizedThrustMagnitudeWrapper::ParameterizedThrustMagnitudeWrapper (const std::function< double(const std::vector< double > &) > thrustMagnitudeFunction, const std::function< double(const std::vector< double > &) > specificImpulseFunction, const std::vector< std::function< double() > > thrustInputVariableFunctions, const std::vector< std::function< double() > > specificImpulseInputVariableFunctions, const std::vector< propulsion::ThrustIndependentVariables > thrustIndependentVariables, const std::vector< propulsion::ThrustIndependentVariables > specificImpulseDependentVariables, const std::function< void(const double) > inputUpdateFunction = std::function< void(const double) >()) inline
Constructor, defines the functions for thrust and specific impulse, as well as the physical meaning of each of the independent variables.
Parameters
thrustMagnitudeFunction Function returning the current thrust as a function of the independent variables.
specificImpulseFunction Function returning the current specific impulse as a function of the independent variables.
thrustInputVariableFunctions List of functions returning input variables for the thrust The order of the functions in this vector is passed to the thrustMagnitudeFunction in the same order as entries of this vector.
specificImpulseInputVariableFunctions List of functions returning input variables for the specific impulse. The order of the functions in this vector is passed to the specificImpulseFunction in the same order as entries of this vector.
thrustIndependentVariables List of identifiers for the physical meaning of each of the entries of the input to the thrustMagnitudeFunction function.
specificImpulseDependentVariables List of identifiers for the physical meaning of each of the entries of the input to the specificImpulseDependentVariables function.
inputUpdateFunction Function that is called to update the user-defined guidance to the current time (empty by default).
Definition at line 355 of file thrustMagnitudeWrapper.h.
References currentSpecificImpulseInputVariables_, currentThrustInputVariables_, specificImpulseDependentVariables_, specificImpulseInputVariableFunctions_, thrustIndependentVariables_, and thrustInputVariableFunctions_.
~ParameterizedThrustMagnitudeWrapper()
tudat::propulsion::ParameterizedThrustMagnitudeWrapper::~ParameterizedThrustMagnitudeWrapper () inline
Definition at line 389 of file thrustMagnitudeWrapper.h.
Member Function Documentation
update()
void tudat::propulsion::ParameterizedThrustMagnitudeWrapper::update (const double time) inline virtual
Function to update the thrust magnitude to the current time.
Parameters
time Time to which the model is to be updated.
Implements tudat::propulsion::ThrustMagnitudeWrapper.
Definition at line 396 of file thrustMagnitudeWrapper.h.
References currentSpecificImpulse_, currentSpecificImpulseInputVariables_, currentThrustInputVariables_, currentThrustMagnitude_, tudat::propulsion::ThrustMagnitudeWrapper::currentTime_, inputUpdateFunction_, specificImpulseFunction_, specificImpulseInputVariableFunctions_, thrustInputVariableFunctions_, and thrustMagnitudeFunction_.
resetDerivedClassCurrentTime()
virtual void tudat::propulsion::ParameterizedThrustMagnitudeWrapper::resetDerivedClassCurrentTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the current time of the thrust model derived class. Function is typically used to reset the time to NaN, signalling the need for a recomputation of all required quantities.
Parameters
currentTime New current time to be set in model.
Reimplemented from tudat::propulsion::ThrustMagnitudeWrapper.
Definition at line 430 of file thrustMagnitudeWrapper.h.
References inputUpdateFunction_.
getCurrentThrustMagnitude()
double tudat::propulsion::ParameterizedThrustMagnitudeWrapper::getCurrentThrustMagnitude () inline virtual
Function to return the current thrust magnitude, as computed by last call to update member function.
Returns
Current thrust magnitude
Implements tudat::propulsion::ThrustMagnitudeWrapper.
Definition at line 443 of file thrustMagnitudeWrapper.h.
References currentThrustMagnitude_.
getCurrentMassRate()
double tudat::propulsion::ParameterizedThrustMagnitudeWrapper::getCurrentMassRate () inline virtual
Function to return the current mass rate, computed from quantities set by last call to update member function.
Returns
Current mass rate.
Implements tudat::propulsion::ThrustMagnitudeWrapper.
Definition at line 453 of file thrustMagnitudeWrapper.h.
References tudat::propulsion::computePropellantMassRateFromSpecificImpulse(), currentSpecificImpulse_, and currentThrustMagnitude_.
Member Data Documentation
thrustMagnitudeFunction_
std::function< double(const std::vector< double >&) > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::thrustMagnitudeFunction_ private
Definition at line 462 of file thrustMagnitudeWrapper.h.
Referenced by update().
specificImpulseFunction_
std::function< double(const std::vector< double >&) > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::specificImpulseFunction_ private
Definition at line 465 of file thrustMagnitudeWrapper.h.
Referenced by update().
thrustInputVariableFunctions_
std::vector< std::function< double() > > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::thrustInputVariableFunctions_ private
Definition at line 468 of file thrustMagnitudeWrapper.h.
Referenced by ParameterizedThrustMagnitudeWrapper(), and update().
specificImpulseInputVariableFunctions_
std::vector< std::function< double() > > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::specificImpulseInputVariableFunctions_ private
Definition at line 471 of file thrustMagnitudeWrapper.h.
Referenced by ParameterizedThrustMagnitudeWrapper(), and update().
thrustIndependentVariables_
std::vector< propulsion::ThrustIndependentVariables > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::thrustIndependentVariables_ private
List of identifiers for the physical meaning of each of the entries of the input to the thrustMagnitudeFunction function.
Definition at line 475 of file thrustMagnitudeWrapper.h.
Referenced by ParameterizedThrustMagnitudeWrapper().
specificImpulseDependentVariables_
std::vector< propulsion::ThrustIndependentVariables > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::specificImpulseDependentVariables_ private
List of identifiers for the physical meaning of each of the entries of the input to the specificImpulseDependentVariables function.
Definition at line 479 of file thrustMagnitudeWrapper.h.
Referenced by ParameterizedThrustMagnitudeWrapper().
currentThrustInputVariables_
std::vector< double > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::currentThrustInputVariables_ private
Definition at line 482 of file thrustMagnitudeWrapper.h.
Referenced by ParameterizedThrustMagnitudeWrapper(), and update().
currentSpecificImpulseInputVariables_
std::vector< double > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::currentSpecificImpulseInputVariables_ private
Definition at line 485 of file thrustMagnitudeWrapper.h.
Referenced by ParameterizedThrustMagnitudeWrapper(), and update().
inputUpdateFunction_
const std::function< void(const double) > tudat::propulsion::ParameterizedThrustMagnitudeWrapper::inputUpdateFunction_ private
Definition at line 489 of file thrustMagnitudeWrapper.h.
Referenced by resetDerivedClassCurrentTime(), and update().
currentThrustMagnitude_
double tudat::propulsion::ParameterizedThrustMagnitudeWrapper::currentThrustMagnitude_ private
Definition at line 492 of file thrustMagnitudeWrapper.h.
Referenced by getCurrentMassRate(), getCurrentThrustMagnitude(), and update().
currentSpecificImpulse_
double tudat::propulsion::ParameterizedThrustMagnitudeWrapper::currentSpecificImpulse_ private
Definition at line 495 of file thrustMagnitudeWrapper.h.
Referenced by getCurrentMassRate(), and update().
The documentation for this class was generated from the following file:
Astrodynamics/Propulsion/thrustMagnitudeWrapper.h