Tudat: tudat::simulation_setup::ThrustInputParameterGuidance Class Reference
tudat::simulation_setup::ThrustInputParameterGuidance Class Reference abstract
Interface base class that can be defined by user to make the use of the ParameterizedThrustMagnitudeSettings class easier.
#include <thrustSettings.h>
Public Member Functions
ThrustInputParameterGuidance (const int numberOfThrustInputParameters, const int numberOfSpecificImpulseInputParameters, const bool includeThrottleSetting=false, const int throttleSettingIndex=-1)
Constructor.
virtual ~ThrustInputParameterGuidance ()
Destructor.
bool getIncludeThrottleSetting ()
Function to retrieve whether any of the guidance-input parameters for the thrust define a throttle setting.
int getNumberOfSpecificImpulseInputParameters ()
Function to retrieve the number of guidance-input parameters that are computed for the specific impulse.
int getNumberOfThrustInputParameters ()
Function to retrieve the number of guidance-input parameters that are computed for the thrust.
double getSpecificImpulseInputGuidanceParameter (const int inputParameterIndex)
Function to retrieve a guidance-input parameter that for the specific impulse.
int getThrottleSettingIndex ()
Function to retrieve the index in list of thrust guidance parameters that denotes the throttle setting.
double getThrustInputGuidanceParameter (const int inputParameterIndex)
Function to retrieve a guidance-input parameter that for the thrust.
void update (const double time)
Update function for the guidance algorithm.
virtual void updateGuidanceParameters ()=0
Pure virtual function that updates the guidance algorithm to the current time/state.
Protected Attributes
std::vector< double > currentSpecificImpulseParameters_
Vector of guidance-input parameters that are computed for the specific impulse.
std::vector< double > currentThrustGuidanceParameters_
Vector of guidance-input parameters that are computed for the thrust.
double currentTime_
Current time of interface object (e.g. time to which object was last updated).
bool includeThrottleSetting_
Boolean that denotes whether any of the guidance-input parameters for the thrust define a throttle setting.
int numberOfSpecificImpulseInputParameters_
Number of guidance-input parameters that are computed for the specific impulse.
int numberOfThrustInputParameters_
Number of guidance-input parameters that are computed for the thrust.
int throttleSettingIndex_
Index in list of thrust guidance parameters that denotes the throttle setting (if any)
Detailed Description
For a specific user-defined guidance approach, a derived class must be defined, that computes the guidance/throttle commands at each time step/vehicle state. Using the createParameterizedThrustMagnitudeSettings functions, a ParameterizedThrustMagnitudeSettings can then be made. In the derived class, the user must define an updateGuidanceParameters function, which sets the entries of the currentThrustGuidanceParameters_ and currentSpecificImpulseParameters_ vectors (size must be compatible with ThrustInputParameterGuidance constructor). Note that the throttle setting is simply defined as one of the entries of currentThrustGuidanceParameters_.
Definition at line 370 of file thrustSettings.h.
Constructor & Destructor Documentation
tudat::simulation_setup::ThrustInputParameterGuidance::ThrustInputParameterGuidance (const int numberOfThrustInputParameters, const int numberOfSpecificImpulseInputParameters, const bool includeThrottleSetting = false, const int throttleSettingIndex = -1) inline
Constructor
Parameters
numberOfThrustInputParameters Number of guidance-input parameters that are computed for the thrust
numberOfSpecificImpulseInputParameters Number of guidance-input parameters that are computed for the specific impulse
includeThrottleSetting Boolean that denotes whether any of the guidance-input parameters for the thrust define a throttle setting
throttleSettingIndex Index in list of thrust guidance parameters that denotes the throttle setting (if any)
Definition at line 384 of file thrustSettings.h.
virtual tudat::simulation_setup::ThrustInputParameterGuidance::~ThrustInputParameterGuidance () inline virtual
Definition at line 407 of file thrustSettings.h.
Member Function Documentation
int tudat::simulation_setup::ThrustInputParameterGuidance::getNumberOfThrustInputParameters () inline
Function to retrieve the number of guidance-input parameters that are computed for the thrust
Returns
Number of guidance-input parameters that are computed for the thrust
Definition at line 414 of file thrustSettings.h.
int tudat::simulation_setup::ThrustInputParameterGuidance::getNumberOfSpecificImpulseInputParameters () inline
Function to retrieve the number of guidance-input parameters that are computed for the specific impulse
Returns
Number of guidance-input parameters that are computed for the specific impulse
Definition at line 424 of file thrustSettings.h.
double tudat::simulation_setup::ThrustInputParameterGuidance::getThrustInputGuidanceParameter (const int inputParameterIndex) inline
Function to retrieve a guidance-input parameter that for the thrust
Parameters
inputParameterIndex Entry of guidance-input vector for thrust that is to be retrieved.
Returns
Guidance-input parameters that for the thrust at given index
Definition at line 435 of file thrustSettings.h.
Referenced by tudat::simulation_setup::createParameterizedThrustMagnitudeSettings().
double tudat::simulation_setup::ThrustInputParameterGuidance::getSpecificImpulseInputGuidanceParameter (const int inputParameterIndex) inline
Function to retrieve a guidance-input parameter that for the specific impulse
Parameters
inputParameterIndex Entry of guidance-input vector for specific impulse that is to be retrieved.
Returns
Guidance-input parameters that for the specific impulse at given index
Definition at line 446 of file thrustSettings.h.
Referenced by tudat::simulation_setup::createParameterizedThrustMagnitudeSettings().
bool tudat::simulation_setup::ThrustInputParameterGuidance::getIncludeThrottleSetting () inline
Function to retrieve whether any of the guidance-input parameters for the thrust define a throttle setting
Returns
Boolean that denotes whether any of the guidance-input parameters for the thrust define a throttle setting.
Definition at line 456 of file thrustSettings.h.
int tudat::simulation_setup::ThrustInputParameterGuidance::getThrottleSettingIndex () inline
Function to retrieve the index in list of thrust guidance parameters that denotes the throttle setting (-1 if none)
Returns
Index in list of thrust guidance parameters that denotes the throttle setting
Definition at line 466 of file thrustSettings.h.
virtual void tudat::simulation_setup::ThrustInputParameterGuidance::updateGuidanceParameters () pure virtual
Implemented in tudat::simulation_setup::AccelerationLimitedThrottleGuidance.
void tudat::simulation_setup::ThrustInputParameterGuidance::update (const double time) inline
Update function for the guidance algorithm, calls the updateGuidanceParameters that is to be implemented in derived class. Calling this function with NaN time signals that a new time step has commenced.
Parameters
time Time to which guidance object is to be updated
Definition at line 480 of file thrustSettings.h.
Referenced by tudat::simulation_setup::createParameterizedThrustMagnitudeSettings().
Member Data Documentation
std::vector< double > tudat::simulation_setup::ThrustInputParameterGuidance::currentThrustGuidanceParameters_ protected
Definition at line 499 of file thrustSettings.h.
std::vector< double > tudat::simulation_setup::ThrustInputParameterGuidance::currentSpecificImpulseParameters_ protected
Definition at line 502 of file thrustSettings.h.
int tudat::simulation_setup::ThrustInputParameterGuidance::numberOfThrustInputParameters_ protected
Definition at line 505 of file thrustSettings.h.
int tudat::simulation_setup::ThrustInputParameterGuidance::numberOfSpecificImpulseInputParameters_ protected
Definition at line 508 of file thrustSettings.h.
bool tudat::simulation_setup::ThrustInputParameterGuidance::includeThrottleSetting_ protected
Definition at line 511 of file thrustSettings.h.
int tudat::simulation_setup::ThrustInputParameterGuidance::throttleSettingIndex_ protected
Definition at line 514 of file thrustSettings.h.
double tudat::simulation_setup::ThrustInputParameterGuidance::currentTime_ protected
Definition at line 517 of file thrustSettings.h.
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/thrustSettings.h