Tudat: tudat::reference_frames::DependentOrientationCalculator Class Reference
tudat::reference_frames::DependentOrientationCalculator Class Reference abstract
Class that computes the orientation of a body as a function of the current state and time.
#include <dependentOrientationCalculator.h>
Public Member Functions
DependentOrientationCalculator ()
Constructor.
virtual ~DependentOrientationCalculator ()
Destructor.
virtual Eigen::Quaterniond getRotationToGlobalFrame ()=0
Function to get the current rotation from the local (body-fixed) to the global (propagation/inertial) frame.
Eigen::Quaterniond getRotationToGlobalFrame (const double currentTime)
Function to update the object to teh current time and retrieve the rotation to the global frame.
virtual Eigen::Quaterniond getRotationToLocalFrame ()=0
Function to get the current rotation from the global (propagation/inertial) to the local (body-fixed) frame.
Eigen::Quaterniond getRotationToLocalFrame (const double currentTime)
Function to update the object to teh current time and retrieve the rotation to the local frame.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the object.
virtual void resetDerivedClassTime (const double currentTime=TUDAT_NAN)
Function to reset the current time in the derived class.
virtual void updateCalculator (const double currentTime)=0
Pure virtual function to update the object to the current state.
Protected Attributes
double currentTime_
Current simulation time.
Detailed Description
Class that computes the orientation of a body as a function of the current state and time. The functionality of this class is distinct from the RotationalEphemeris, in the sense that it is only defined during the numerical propagation, as it relies on the current state of the environment for the computation of the rotations.
Definition at line 30 of file dependentOrientationCalculator.h.
Constructor & Destructor Documentation
tudat::reference_frames::DependentOrientationCalculator::DependentOrientationCalculator () inline
Definition at line 35 of file dependentOrientationCalculator.h.
virtual tudat::reference_frames::DependentOrientationCalculator::~DependentOrientationCalculator () inline virtual
Definition at line 38 of file dependentOrientationCalculator.h.
References getRotationToGlobalFrame(), getRotationToLocalFrame(), and updateCalculator().
Member Function Documentation
virtual Eigen::Quaterniond tudat::reference_frames::DependentOrientationCalculator::getRotationToLocalFrame () pure virtual
Function to get the current rotation from the global (propagation/inertial) to the local (body-fixed) frame. Function is pure virtual and must be defined in derived class.
Returns
Current rotation from the global (propagation/inertial) to the local (body-fixed) frame.
Implemented in tudat::reference_frames::AerodynamicAngleCalculator, and tudat::propulsion::BodyFixedForceDirectionGuidance.
Referenced by getRotationToLocalFrame(), tudat::reference_frames::setAerodynamicDependentOrientationCalculatorClosure(), and ~DependentOrientationCalculator().
virtual Eigen::Quaterniond tudat::reference_frames::DependentOrientationCalculator::getRotationToGlobalFrame () pure virtual
Function to get the current rotation from the local (body-fixed) to the global (propagation/inertial) frame. Function is pure virtual and must be defined in derived class.
Returns
Current rotation from the local (body-fixed) to the global (propagation/inertial) frame.
Implemented in tudat::propulsion::OrientationBasedForceGuidance, tudat::propulsion::DirectionBasedForceGuidance, and tudat::reference_frames::AerodynamicAngleCalculator.
Referenced by tudat::propulsion::OrientationBasedForceGuidance::getCurrentForceDirectionInPropagationFrame(), getRotationToGlobalFrame(), tudat::propulsion::BodyFixedForceDirectionGuidance::getRotationToLocalFrame(), and ~DependentOrientationCalculator().
virtual void tudat::reference_frames::DependentOrientationCalculator::updateCalculator (const double currentTime) pure virtual
Pure virtual function to update the object to the current state.
Parameters
currentTime Time to which angle calculator is to be updated.
Implemented in tudat::reference_frames::AerodynamicAngleCalculator, and tudat::propulsion::BodyFixedForceDirectionGuidance.
Referenced by getRotationToGlobalFrame(), getRotationToLocalFrame(), and ~DependentOrientationCalculator().
Eigen::Quaterniond tudat::reference_frames::DependentOrientationCalculator::getRotationToLocalFrame (const double currentTime) inline
Function to update the object to teh current time and retrieve the rotation to the local frame Note that the environment must have been updated to the current time before calling this function.
Parameters
currentTime Time to which angle calculator is to be updated.
Returns
Current rotation from the global (propagation/inertial) to the local (body-fixed) frame.
Definition at line 71 of file dependentOrientationCalculator.h.
References getRotationToLocalFrame(), and updateCalculator().
Eigen::Quaterniond tudat::reference_frames::DependentOrientationCalculator::getRotationToGlobalFrame (const double currentTime) inline
Function to update the object to teh current time and retrieve the rotation to the global frame Note that the environment must have been updated to the current time before calling this function.
Parameters
currentTime Time to which angle calculator is to be updated.
Returns
Current rotation from the local (body-fixed) to the global (propagation/inertial) frame.
Definition at line 84 of file dependentOrientationCalculator.h.
References getRotationToGlobalFrame(), and updateCalculator().
virtual void tudat::reference_frames::DependentOrientationCalculator::resetDerivedClassTime (const double currentTime = TUDAT_NAN) inline virtual
Function to reset the current time in the derived class, must be implemented in the derived class.
See also
resetCurrentTime
Parameters
currentTime New value of currentTime_ variable.
Reimplemented in tudat::reference_frames::AerodynamicAngleCalculator.
Definition at line 96 of file dependentOrientationCalculator.h.
Referenced by resetCurrentTime().
void tudat::reference_frames::DependentOrientationCalculator::resetCurrentTime (const double currentTime = TUDAT_NAN) inline
Function to reset the current time of the object. Note that the orientation is not recomputed by calling this function only the currentTime_ (and any associated variables) are reset. Function is typically used to reset time to NaN, signalling the need to recompute all variables.
Parameters
currentTime New value of currentTime_ variable.
Definition at line 105 of file dependentOrientationCalculator.h.
References currentTime_, and resetDerivedClassTime().
Member Data Documentation
double tudat::reference_frames::DependentOrientationCalculator::currentTime_ protected
Definition at line 114 of file dependentOrientationCalculator.h.
Referenced by resetCurrentTime(), and tudat::reference_frames::AerodynamicAngleCalculator::update().
The documentation for this class was generated from the following file:
Astrodynamics/ReferenceFrames/dependentOrientationCalculator.h