Tudat: tudat::aerodynamics::HypersonicLocalInclinationAnalysis Class Reference
tudat::aerodynamics::HypersonicLocalInclinationAnalysis Class Reference
Class for inviscid hypersonic aerodynamic analysis using local inclination methods.
#include <hypersonicLocalInclinationAnalysis.h>
Public Member Functions
HypersonicLocalInclinationAnalysis (const std::vector< std::vector< double > > &dataPointsOfIndependentVariables, const boost::shared_ptr< SurfaceGeometry > inputVehicleSurface, const std::vector< int > &numberOfLines, const std::vector< int > &numberOfPoints, const std::vector< bool > &invertOrders, const std::vector< std::vector< int > > &selectedMethods, const double referenceArea, const double referenceLength, const Eigen::Vector3d &momentReferencePoint)
Default constructor.
~HypersonicLocalInclinationAnalysis ()
Default destructor.
void determineInclinations (const double angleOfAttack, const double angleOfSideslip)
Determine inclination angles of panels on a given part.
Eigen::Vector6d getAerodynamicCoefficientsDataPoint (const boost::array< int, 3 > independentVariables)
Get aerodynamic coefficients.
int getNumberOfVehicleParts () const
Get the number of vehicle parts.
boost::shared_ptr< geometric_shapes::LawgsPartGeometry > getVehiclePart (const int vehicleIndex) const
Get a vehicle part.
Public Member Functions inherited from tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >
AerodynamicCoefficientGenerator (const std::vector< std::vector< double > > &dataPointsOfIndependentVariables, const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame=true, const bool areCoefficientsInNegativeAxisDirection=true)
Default base class constructor.
virtual ~AerodynamicCoefficientGenerator ()
Default destructor.
virtual Eigen::Matrix< double, NumberOfCoefficients, 1 > getAerodynamicCoefficientsDataPoint (const boost::array< int, NumberOfIndependentVariables > independentVariables)=0
Get aerodynamic coefficients.
boost::multi_array< Eigen::Matrix< double, NumberOfCoefficients, 1 >, NumberOfIndependentVariables > getAerodynamicCoefficientsTables ()
Function to return the complete set of aerodynamic coefficients that have been calculated.
std::vector< std::vector< double > > getDataPointsOfIndependentVariables ()
Get the data points of the independent variables at which the coefficients are calculated.
double getIndependentVariablePoint (const int independentVariable, const int index) const
Get a value of an independent variable.
int getNumberOfValuesOfIndependentVariable (const int independentVariable) const
Get the number of points for an independent variable.
virtual void updateCurrentCoefficients (const std::vector< double > &independentVariables)
Compute the aerodynamic coefficients at current flight condition.
Public Member Functions inherited from tudat::aerodynamics::AerodynamicCoefficientInterface
AerodynamicCoefficientInterface (const double referenceLength, const double referenceArea, const double lateralReferenceLength, const Eigen::Vector3d &momentReferencePoint, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames, const bool areCoefficientsInAerodynamicFrame=true, const bool areCoefficientsInNegativeAxisDirection=true)
Constructor.
virtual ~AerodynamicCoefficientInterface ()
Default destructor.
bool getAreCoefficientsInAerodynamicFrame ()
Function that returns whether the coefficients are given in aerodynamic frame.
bool getAreCoefficientsInNegativeAxisDirection ()
Function that returns whether the coefficients are positive in positive axes directions.
AerodynamicCoefficientsIndependentVariables getControlSurfaceIndependentVariableName (const std::string &controlSurface, const unsigned int index)
Function to get the identifier for a single independent variable for a single control surface.
std::map< std::string, std::vector< AerodynamicCoefficientsIndependentVariables > > getControlSurfaceIndependentVariables ()
Function to get the list of independent variables for all control surfaces.
std::string getControlSurfaceName (const int index)
Function to get control surface name at given index in list of control surfaces.
Eigen::Matrix< double, 6, 1 > getCurrentAerodynamicCoefficients ()
Function for calculating and returning aerodynamic force and moment coefficients.
Eigen::Vector3d getCurrentForceCoefficients ()
Pure virtual function for calculating and returning aerodynamic force coefficients.
Eigen::Vector3d getCurrentMomentCoefficients ()
Pure virtual function for calculating and returning aerodynamic moment coefficients.
AerodynamicCoefficientsIndependentVariables getIndependentVariableName (const unsigned int index)
Function to return a single identifier of the physical meaning of one independent variable.
std::vector< AerodynamicCoefficientsIndependentVariables > getIndependentVariableNames ()
Function to return the identifiers of the physical meaning of each independent variable.
double getLateralReferenceLength ()
Get lateral reference length.
Eigen::VectorXd getMomentReferencePoint ()
Get moment reference point.
unsigned int getNumberOfControlSurfaceIndependentVariables (const std::string controlSurface)
Function to return the number of independent variables for a given control surface.
unsigned int getNumberOfControlSurfaces ()
Function to return the number of control surfaces in current coefficient interface.
unsigned int getNumberOfIndependentVariables ()
Function to return the number of independent variables upon which the coeficients depend.
double getReferenceArea ()
Get reference area.
double getReferenceLength ()
Get reference length.
Eigen::Vector3d getReferenceLengths ()
void setControlSurfaceIncrements (const std::map< std::string, boost::shared_ptr< ControlSurfaceIncrementAerodynamicInterface > > controlSurfaceIncrementInterfaces)
Function to set the list of control surface aerodynamic coefficient interfaces.
void updateCurrentControlSurfaceCoefficientsCoefficients (const std::string &currentControlSurface, std::vector< double > controlSurfaceIndependentVariables)
Compute the aerodynamic coefficients for a single control surface, and add to full configuration coefficients.
void updateFullCurrentCoefficients (const std::vector< double > &independentVariables, const std::map< std::string, std::vector< double > > &controlSurfaceIndependentVariables=std::map< std::string, std::vector< double > >())
Function to update the aerodynamic coefficients of the full body with control surfaces.
Private Member Functions
Eigen::Vector3d calculateForceCoefficients (const int partNumber)
Determine force coefficients of a part.
Eigen::Vector3d calculateMomentCoefficients (const int partNumber)
Determine moment coefficients of a part.
Eigen::Vector6d determinePartCoefficients (const int partNumber, const boost::array< int, 3 > independentVariableIndices)
Determine aerodynamic coefficients for a single LaWGS part.
void determinePressureCoefficients (const int partNumber, const boost::array< int, 3 > independentVariableIndices)
Determine pressure coefficients on a given part.
void determineVehicleCoefficients (const boost::array< int, 3 > independentVariableIndices)
Generate aerodynamic coefficients at a single set of independent variables.
void generateCoefficients ()
Generate aerodynamic database.
void updateCompressionPressures (const double machNumber, const int partNumber)
Determine the compression pressure coefficients of a given part.
void updateExpansionPressures (const double machNumber, const int partNumber)
Determine the expansion pressure coefficients of a given part.
Private Attributes
std::vector< std::vector< std::vector< double > > > inclination_
Three-dimensional array of panel inclination angles.
boost::multi_array< bool, 3 > isCoefficientGenerated_
Multi-array as which indicates which coefficients have been calculated already.
std::vector< std::vector< std::vector< double > > > pressureCoefficient_
Three-dimensional array of panel pressure coefficients.
std::map< std::pair< double, double >, std::vector< std::vector< std::vector< double > > > > previouslyComputedInclinations_
Map of angle of attack and -sideslip pair and associated panel inclinations.
double ratioOfSpecificHeats
Ratio of specific heats.
std::vector< std::vector< int > > selectedMethods_
Array of selected methods.
double stagnationPressureCoefficient
Stagnation pressure coefficient.
std::vector< boost::shared_ptr< geometric_shapes::LawgsPartGeometry > > vehicleParts_
Array of vehicle parts.
Friends
std::ostream & operator<< (std::ostream &stream, HypersonicLocalInclinationAnalysis &hypersonicLocalInclinationAnalysis)
Overload ostream to print class information.
Additional Inherited Members
Protected Member Functions inherited from tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >
void createInterpolator ()
Protected Attributes inherited from tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >
boost::multi_array< Eigen::Matrix< double, NumberOfCoefficients, 1 >, NumberOfIndependentVariables > aerodynamicCoefficients_
N-dimensional array containing all computer aerodynamic coefficients.
boost::shared_ptr< interpolators::Interpolator< double, Eigen::Vector6d > > coefficientInterpolator_
std::vector< std::vector< double > > dataPointsOfIndependentVariables_
Data points of the independent variables at which the coefficients are calculated.
Protected Attributes inherited from tudat::aerodynamics::AerodynamicCoefficientInterface
bool areCoefficientsInAerodynamicFrame_
Boolean to denote whether coefficients are defined in aerodynamic or body frame.
bool areCoefficientsInNegativeAxisDirection_
Boolean to denote whether coefficients are positive along frame axes.
std::map< std::string, boost::shared_ptr< ControlSurfaceIncrementAerodynamicInterface > > controlSurfaceIncrementInterfaces_
List of control surface aerodynamic coefficient interfaces.
std::vector< std::string > controlSurfaceNames_
Explicit list of control surface names, in same order as iterator over controlSurfaceIncrementInterfaces_.
Eigen::Vector3d currentForceCoefficients_
The current force coefficients.
Eigen::Vector3d currentMomentCoefficients_
The current moment coefficients.
std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames_
double lateralReferenceLength_
Lateral aerodynamic reference length.
Eigen::Vector3d momentReferencePoint_
Aerodynamic moment reference point.
unsigned int numberOfIndependentVariables_
Number of independent variables upon which the force and moment coefficients depend.
double referenceArea_
Aerodynamic reference area.
double referenceLength_
Aerodynamic reference length.
Eigen::Vector3d referenceLengths_
Detailed Description
Class for inviscid hypersonic aerodynamic analysis using local inclination methods. These methods assume that the local pressure on the vehicle is only dependent on the local inclination angle w.r.t. the freestream flow and freestream conditions, such as Mach number and ratio of specific heats. All aerodynamic coefficients can be calculated using the generateCoefficients function, or on an as needed basis by using the getAerodynamicCoefficientsDataPoint function. Note that during the panel inclination determination process, a geometry with outward surface-normals is assumed. The resulting coefficients are expressed in the same reference frame as that of the input geometry.
Definition at line 71 of file hypersonicLocalInclinationAnalysis.h.
Constructor & Destructor Documentation
tudat::aerodynamics::HypersonicLocalInclinationAnalysis::HypersonicLocalInclinationAnalysis (const std::vector< std::vector< double > > & dataPointsOfIndependentVariables, const boost::shared_ptr< SurfaceGeometry > inputVehicleSurface, const std::vector< int > & numberOfLines, const std::vector< int > & numberOfPoints, const std::vector< bool > & invertOrders, const std::vector< std::vector< int > > & selectedMethods, const double referenceArea, const double referenceLength, const Eigen::Vector3d & momentReferencePoint)
Default constructor of class, specified vehicle geometry, discretization properties, independent variable ranges, reference values and local inclination methods that are to be used
Parameters
dataPointsOfIndependentVariables Vector of vector, with each subvector containing the data points of each of the independent variables for the coefficient generation. The physical meaning of each of the three independent variables is: 0 = mach numner, 1 = angle of attack, 2 = angle of sideslip. Each of the subvectors must be sorted in ascending order.
inputVehicleSurface Vehicle surface geometry for which the coefficients are to be determined.
numberOfLines Number of discretization points in the first independent surface variable of each of the subparts of inputVehicleSurface.
numberOfPoints Number of discretization points in the second independent surface variable of each of the subparts of inputVehicleSurface.
invertOrders Booleans to denote whether the surface normals of the panels of each discretized inputVehicleSurface subpart are to be inverted (i.e. inward-facing->outward facing or vice versa)
selectedMethods Array of selected local inclination methods, the first index represents compression/expansion, the second index denotes the vehicle part index. The value for each separate method can be found in the updateCompressionPressures and updateExpansionPressures functions, respectively.
referenceArea Reference area used to non-dimensionalize aerodynamic forces and moments.
referenceLength Reference length used to non-dimensionalize aerodynamic moments.
momentReferencePoint Reference point wrt which aerodynamic moments are calculated.
Definition at line 120 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >::createInterpolator(), tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >::dataPointsOfIndependentVariables_, generateCoefficients(), tudat::geometric_shapes::CompositeSurfaceGeometry::getNumberOfSingleSurfaceGeometries(), inclination_, isCoefficientGenerated_, pressureCoefficient_, and vehicleParts_.
tudat::aerodynamics::HypersonicLocalInclinationAnalysis::~HypersonicLocalInclinationAnalysis () inline
Default destructor.
Definition at line 118 of file hypersonicLocalInclinationAnalysis.h.
References determineInclinations(), and getAerodynamicCoefficientsDataPoint().
Member Function Documentation
Vector6d tudat::aerodynamics::HypersonicLocalInclinationAnalysis::getAerodynamicCoefficientsDataPoint (const boost::array< int, 3 > independentVariables)
Returns aerodynamic coefficients. The physical meaning of each of the three independent variables is: 0 = mach numner, 1 = angle of attack, 2 = angle of sideslip.
Parameters
independentVariables Array of values of independent variable indices in dataPointsOfIndependentVariables_.
Returns
vector of coefficients at specified independent variable indices.
Definition at line 238 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >::aerodynamicCoefficients_, determineVehicleCoefficients(), and isCoefficientGenerated_.
Referenced by ~HypersonicLocalInclinationAnalysis().
void tudat::aerodynamics::HypersonicLocalInclinationAnalysis::determineInclinations (const double angleOfAttack, const double angleOfSideslip)
Determines the inclination angle of panels on a single part.
Determines panel inclinations for all panels on all parts for given attitude. Outward pointing surface-normals are assumed!
Parameters
angleOfAttack Angle of attack at which to determine inclination angles.
angleOfSideslip Angle of sideslip at which to determine inclination angles.
Definition at line 417 of file hypersonicLocalInclinationAnalysis.cpp.
References inclination_, tudat::mathematical_constants::PI, and vehicleParts_.
Referenced by determinePartCoefficients(), and ~HypersonicLocalInclinationAnalysis().
int tudat::aerodynamics::HypersonicLocalInclinationAnalysis::getNumberOfVehicleParts () const inline
Returns the number of vehicle parts.
Returns
The number of vehicle parts.
Definition at line 147 of file hypersonicLocalInclinationAnalysis.h.
References vehicleParts_.
boost::shared_ptr< geometric_shapes::LawgsPartGeometry > tudat::aerodynamics::HypersonicLocalInclinationAnalysis::getVehiclePart (const int vehicleIndex) const inline
Returns a vehicle part.
Parameters
vehicleIndex Index in vehicleParts_ to be retrieved.
Returns
Requested vehicle part.
Definition at line 158 of file hypersonicLocalInclinationAnalysis.h.
References calculateForceCoefficients(), calculateMomentCoefficients(), determinePartCoefficients(), determinePressureCoefficients(), determineVehicleCoefficients(), generateCoefficients(), operator<<, updateCompressionPressures(), updateExpansionPressures(), and vehicleParts_.
void tudat::aerodynamics::HypersonicLocalInclinationAnalysis::generateCoefficients () private virtual
Generates aerodynamic database. Settings of geometry, reference quantities, database point settings and analysis methods should have been set previously.
Implements tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >.
Definition at line 252 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >::dataPointsOfIndependentVariables_, and determineVehicleCoefficients().
Referenced by getVehiclePart(), and HypersonicLocalInclinationAnalysis().
void tudat::aerodynamics::HypersonicLocalInclinationAnalysis::determineVehicleCoefficients (const boost::array< int, 3 > independentVariableIndices) private
Generates aerodynamic coefficients at a single set of independent variables. Determines values and sets corresponding entry in vehicleCoefficients_ array.
Parameters
independentVariableIndices Array of indices from lists of Mach number, angle of attack and angle of sideslip points at which to perform analysis.
Definition at line 278 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >::aerodynamicCoefficients_, determinePartCoefficients(), isCoefficientGenerated_, and vehicleParts_.
Referenced by generateCoefficients(), getAerodynamicCoefficientsDataPoint(), and getVehiclePart().
Vector6d tudat::aerodynamics::HypersonicLocalInclinationAnalysis::determinePartCoefficients (const int partNumber, const boost::array< int, 3 > independentVariableIndices) private
Determine aerodynamic coefficients of a single vehicle part.
Determines aerodynamic coefficients for a single LaWGS part, calls determinepressureCoefficient_ function for given vehicle part.
Parameters
partNumber Index from vehicleParts_ array for which to determine coefficients.
independentVariableIndices Array of indices of independent variables.
Returns
Force and moment coefficients for requested vehicle part.
Definition at line 296 of file hypersonicLocalInclinationAnalysis.cpp.
References calculateForceCoefficients(), calculateMomentCoefficients(), tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >::dataPointsOfIndependentVariables_, determineInclinations(), determinePressureCoefficients(), inclination_, and previouslyComputedInclinations_.
Referenced by determineVehicleCoefficients(), and getVehiclePart().
void tudat::aerodynamics::HypersonicLocalInclinationAnalysis::determinePressureCoefficients (const int partNumber, const boost::array< int, 3 > independentVariableIndices) private
Determine the pressure coefficients on a single vehicle part.
Determines pressure coefficients on a single vehicle part. Calls the updateExpansionPressures and updateCompressionPressures for given vehicle part.
Parameters
partNumber Index from vehicleParts_ array for which to determine coefficients.
independentVariableIndices Array of indices of independent variables.
Definition at line 341 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::aerodynamics::computeStagnationPressure(), tudat::aerodynamics::AerodynamicCoefficientGenerator< 3, 6 >::dataPointsOfIndependentVariables_, ratioOfSpecificHeats, stagnationPressureCoefficient, updateCompressionPressures(), and updateExpansionPressures().
Referenced by determinePartCoefficients(), and getVehiclePart().
Eigen::Vector3d tudat::aerodynamics::HypersonicLocalInclinationAnalysis::calculateForceCoefficients (const int partNumber) private
Determine force coefficients from pressure coefficients.
Sums the pressure coefficients of given part and determines force coefficients from it by non-dimensionalization with reference area.
Parameters
partNumber Index from vehicleParts_ array for which determine coefficients.
Returns
Force coefficients for requested vehicle part.
Definition at line 358 of file hypersonicLocalInclinationAnalysis.cpp.
References pressureCoefficient_, tudat::aerodynamics::AerodynamicCoefficientInterface::referenceArea_, and vehicleParts_.
Referenced by determinePartCoefficients(), and getVehiclePart().
Eigen::Vector3d tudat::aerodynamics::HypersonicLocalInclinationAnalysis::calculateMomentCoefficients (const int partNumber) private
Determine moment coefficients from pressure coefficients.
Determines the moment coefficients of a given part by summing the contributions of all panels on the part. Moment arms are taken from panel centroid to momentReferencePoint. Non- dimensionalization is performed by product of referenceLength and referenceArea.
Parameters
partNumber Index from vehicleParts_ array for which to determine coefficients.
Returns
Moment coefficients for requested vehicle part.
Definition at line 384 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::aerodynamics::AerodynamicCoefficientInterface::momentReferencePoint_, pressureCoefficient_, tudat::aerodynamics::AerodynamicCoefficientInterface::referenceArea_, tudat::aerodynamics::AerodynamicCoefficientInterface::referenceLength_, and vehicleParts_.
Referenced by determinePartCoefficients(), and getVehiclePart().
void tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateCompressionPressures (const double machNumber, const int partNumber) private
Determine compression pressure coefficients on all parts.
Sets the values of pressureCoefficient_ on given part and at given Mach number for which inclination > 0.
Parameters
machNumber Mach number at which to perform analysis.
partNumber of part from vehicleParts_ which is to be analyzed.
Definition at line 456 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::aerodynamics::computeEmpiricalTangentConePressureCoefficient(), tudat::aerodynamics::computeEmpiricalTangentWedgePressureCoefficient(), tudat::aerodynamics::computeHankeyFlatSurfacePressureCoefficient(), tudat::aerodynamics::computeModifiedDahlemBuckPressureCoefficient(), tudat::aerodynamics::computeModifiedNewtonianPressureCoefficient(), tudat::aerodynamics::computeNewtonianPressureCoefficient(), tudat::aerodynamics::computeSmythDeltaWingPressureCoefficient(), tudat::aerodynamics::computeVanDykeUnifiedPressureCoefficient(), inclination_, pressureCoefficient_, ratioOfSpecificHeats, selectedMethods_, stagnationPressureCoefficient, and vehicleParts_.
Referenced by determinePressureCoefficients(), and getVehiclePart().
void tudat::aerodynamics::HypersonicLocalInclinationAnalysis::updateExpansionPressures (const double machNumber, const int partNumber) private
Determines expansion pressure coefficients on all parts.
Determine the values of pressureCoefficient_ on given part and at given Mach number for which inclination <= 0.
Parameters
machNumber Mach number at which to perform analysis.
partNumber of part from vehicleParts_ which is to be analyzed.
Definition at line 540 of file hypersonicLocalInclinationAnalysis.cpp.
References tudat::aerodynamics::computeAcmEmpiricalPressureCoefficient(), tudat::aerodynamics::computeHighMachBasePressure(), tudat::aerodynamics::computePrandtlMeyerFreestreamPressureCoefficient(), tudat::aerodynamics::computePrandtlMeyerFunction(), tudat::aerodynamics::computeVacuumPressureCoefficient(), inclination_, pressureCoefficient_, ratioOfSpecificHeats, selectedMethods_, and vehicleParts_.
Referenced by determinePressureCoefficients(), and getVehiclePart().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, HypersonicLocalInclinationAnalysis & hypersonicLocalInclinationAnalysis) friend
Overloads ostream to print class information, prints the number of lawgs geometry parts and names.
Parameters
stream Stream object.
hypersonicLocalInclinationAnalysis Hypersonic local inclination analysis.
Returns
Stream object.
Referenced by getVehiclePart().
Member Data Documentation
std::vector< boost::shared_ptr< geometric_shapes::LawgsPartGeometry > > tudat::aerodynamics::HypersonicLocalInclinationAnalysis::vehicleParts_ private
Array of vehicle parts.
Definition at line 257 of file hypersonicLocalInclinationAnalysis.h.
Referenced by calculateForceCoefficients(), calculateMomentCoefficients(), determineInclinations(), determineVehicleCoefficients(), getNumberOfVehicleParts(), getVehiclePart(), HypersonicLocalInclinationAnalysis(), updateCompressionPressures(), and updateExpansionPressures().
boost::multi_array< bool, 3 > tudat::aerodynamics::HypersonicLocalInclinationAnalysis::isCoefficientGenerated_ private
Multi-array as which indicates which coefficients have been calculated already. Indices of entries coincide with indices of aerodynamicCoefficients_.
Definition at line 264 of file hypersonicLocalInclinationAnalysis.h.
Referenced by determineVehicleCoefficients(), getAerodynamicCoefficientsDataPoint(), and HypersonicLocalInclinationAnalysis().
std::vector< std::vector< std::vector< double > > > tudat::aerodynamics::HypersonicLocalInclinationAnalysis::inclination_ private
Three-dimensional array of panel inclination angles at current values of independent variables. Indices indicate part-line-point.
Definition at line 271 of file hypersonicLocalInclinationAnalysis.h.
Referenced by determineInclinations(), determinePartCoefficients(), HypersonicLocalInclinationAnalysis(), updateCompressionPressures(), and updateExpansionPressures().
std::map< std::pair< double, double >, std::vector< std::vector< std::vector< double > > > > tudat::aerodynamics::HypersonicLocalInclinationAnalysis::previouslyComputedInclinations_ private
Map of angle of attack and -sideslip pair and associated panel inclinations.
Definition at line 278 of file hypersonicLocalInclinationAnalysis.h.
Referenced by determinePartCoefficients().
std::vector< std::vector< std::vector< double > > > tudat::aerodynamics::HypersonicLocalInclinationAnalysis::pressureCoefficient_ private
Three-dimensional array of panel pressure coefficients at current values of independent variables. Indices indicate part-line-point.
Definition at line 285 of file hypersonicLocalInclinationAnalysis.h.
Referenced by calculateForceCoefficients(), calculateMomentCoefficients(), HypersonicLocalInclinationAnalysis(), updateCompressionPressures(), and updateExpansionPressures().
double tudat::aerodynamics::HypersonicLocalInclinationAnalysis::stagnationPressureCoefficient private
Stagnation pressure coefficient for flow which has passed through a normal shock wave at current Mach number.
Definition at line 292 of file hypersonicLocalInclinationAnalysis.h.
Referenced by determinePressureCoefficients(), and updateCompressionPressures().
double tudat::aerodynamics::HypersonicLocalInclinationAnalysis::ratioOfSpecificHeats private
Ratio of specific heat at constant pressure to specific heat at constant pressure.
Definition at line 298 of file hypersonicLocalInclinationAnalysis.h.
Referenced by determinePressureCoefficients(), updateCompressionPressures(), and updateExpansionPressures().
std::vector< std::vector< int > > tudat::aerodynamics::HypersonicLocalInclinationAnalysis::selectedMethods_ private
Array of selected methods, first index represents compression/expansion, second index represents vehicle part.
Definition at line 305 of file hypersonicLocalInclinationAnalysis.h.
Referenced by updateCompressionPressures(), and updateExpansionPressures().
The documentation for this class was generated from the following files:
Astrodynamics/Aerodynamics/hypersonicLocalInclinationAnalysis.h
Astrodynamics/Aerodynamics/hypersonicLocalInclinationAnalysis.cpp