Tudat: tudat::geometric_shapes::SphereSegment Class Reference
tudat::geometric_shapes::SphereSegment Class Reference
Sphere segment class.
#include <sphereSegment.h>
Public Member Functions
SphereSegment (const double radius, const double minimumAzimuthAngle=0.0, const double maximumAzimuthAngle=2.0 *mathematical_constants::PI, const double minimumZenithAngle=0.0, const double maximumZenithAngle=mathematical_constants::PI)
Default constructor.
double getMaximumAzimuthAngle ()
Get maximum value of azimuth angle.
double getMaximumZenithAngle ()
Get maximum value of zenith angle.
double getMinimumAzimuthAngle ()
Get minimum value of azimuth angle.
double getMinimumZenithAngle ()
Get minimum value of the zenith angle.
double getParameter (const int index)
Get parameter of sphere segment.
double getRadius ()
Get radius.
Eigen::VectorXd getSurfaceDerivative (const double azimuthAngle, const double zenithAngle, const int powerOfZenithAngleDerivative, const int powerOfAzimuthAngleDerivative)
Get surface derivative on sphere segment.
Eigen::VectorXd getSurfacePoint (const double azimuthAngle, const double zenithAngle)
Get surface point on sphere segment.
Public Member Functions inherited from tudat::geometric_shapes::SingleSurfaceGeometry
SingleSurfaceGeometry ()
Default constructor.
virtual ~SingleSurfaceGeometry ()
Default destructor.
double getMaximumIndependentVariable (const int parameterIndex)
Get maximum value of independent variable.
double getMinimumIndependentVariable (const int parameterIndex)
Get minimum value of independent variable.
Eigen::VectorXd getOffset ()
Get offset from the shape.
Eigen::MatrixXd getRotationMatrix ()
Get rotation matrix from the shape.
Eigen::MatrixXd getScalingMatrix ()
Get scaling matrix from the shape.
void setOffset (const Eigen::VectorXd &offset)
Set offset of the shape.
void setRotationMatrix (const Eigen::MatrixXd &rotationMatrix)
Set rotation matrix of the shape.
void setScalingMatrix (const Eigen::MatrixXd &scalingMatrix)
Set scaling matrix of the shape.
void transformPoint (Eigen::VectorXd &point)
Apply transformation to vehicle part.
Public Member Functions inherited from tudat::SurfaceGeometry
virtual ~SurfaceGeometry ()
Default destructor.
Private Attributes
double radius_
Sphere radius.
Friends
std::ostream & operator<< (std::ostream &stream, SphereSegment &sphereSegment)
Overload ostream to print class information.
Additional Inherited Members
Public Types inherited from tudat::geometric_shapes::SingleSurfaceGeometry
enum IndependentVariables { firstIndependentVariable = 1, secondIndependentVariable = 2 }
Independent variables.
Protected Member Functions inherited from tudat::geometric_shapes::SingleSurfaceGeometry
void setMaximumIndependentVariable (const int parameterIndex, const double maximumValue)
Set maximum value of independent variable.
void setMinimumIndependentVariable (const int parameterIndex, const double minimumValue)
Set minimum value of independent variable.
Protected Attributes inherited from tudat::geometric_shapes::SingleSurfaceGeometry
Eigen::VectorXd cartesianPositionVector_
Cartesian position vector for use in getSurfacePoint function.
IndependentVariables independentVariable_
Indepedent variable.
double maximumIndependentVariable1_
Maximum value of independent variable 1.
double maximumIndependentVariable2_
Maximum value of independent variable 2.
double minimumIndependentVariable1_
Minimum value of independent variable 1.
double minimumIndependentVariable2_
Minimum value of independent variable 2.
Eigen::VectorXd offset_
Offset vector.
double parameter_
Parameter for use in get parameter function.
Eigen::MatrixXd rotationMatrix_
Rotation matrix.
Eigen::MatrixXd scalingMatrix_
Scaling matrix.
Detailed Description
Class that defines the sphere (segment) shape. Parametrization is based on spherical coordinates, with azimuth and zenith angles as 1st and 2nd variables (see basic_mathematics::convertSphericalToCartesian). In addition to the minimum and maximum of these two variables, the sphere radius is required for defining the sphere. Note that by using the scalingMatrix_ member variable, this class can also represent ellipsoids.
Definition at line 38 of file sphereSegment.h.
Constructor & Destructor Documentation
SphereSegment()
tudat::geometric_shapes::SphereSegment::SphereSegment (const double radius, const double minimumAzimuthAngle = 0.0, const double maximumAzimuthAngle = 2.0 * mathematical_constants::PI, const double minimumZenithAngle = 0.0, const double maximumZenithAngle = mathematical_constants::PI)
Default constructor. Default angle values are set to a full sphere.
Parameters
radius Radius of sphere.
minimumAzimuthAngle Minimum of azimuth angle.
maximumAzimuthAngle Maximum of azimuth angle.
minimumZenithAngle Minimum of zenith angle.
maximumZenithAngle Maximum of zenith angle.
Definition at line 29 of file sphereSegment.cpp.
References radius_, tudat::geometric_shapes::SingleSurfaceGeometry::setMaximumIndependentVariable(), and tudat::geometric_shapes::SingleSurfaceGeometry::setMinimumIndependentVariable().
Member Function Documentation
getSurfacePoint()
Eigen::VectorXd tudat::geometric_shapes::SphereSegment::getSurfacePoint (const double azimuthAngle, const double zenithAngle) virtual
Retrieves a surface point on the sphere, by performing the mapping of independent variables to cartesian coordinates for the sphere segment by spherical coordinate transformation. Function uses cartesianPositionVector_ member variable. Values of this vector set previous to function call are irrelevant.
Parameters
azimuthAngle Azimuth angle.
zenithAngle Zenith angle.
Returns
Surface point on sphere.
Implements tudat::geometric_shapes::SingleSurfaceGeometry.
Definition at line 43 of file sphereSegment.cpp.
References tudat::geometric_shapes::SingleSurfaceGeometry::cartesianPositionVector_, tudat::coordinate_conversions::convertSphericalToCartesian(), radius_, and tudat::geometric_shapes::SingleSurfaceGeometry::transformPoint().
Referenced by getSurfaceDerivative().
getSurfaceDerivative()
Eigen::VectorXd tudat::geometric_shapes::SphereSegment::getSurfaceDerivative (const double azimuthAngle, const double zenithAngle, const int powerOfZenithAngleDerivative, const int powerOfAzimuthAngleDerivative) virtual
Retrieves the derivatives of the surface point with respect to the two independent variables. For powerOfZenithDerivative = 1 and powerOfAzimuthDerivative = 2 the function returns:
(with u and v the zenith and azimuth angles).
Parameters
azimuthAngle Azimuth angle.
zenithAngle Zenith angle.
powerOfZenithAngleDerivative Power of derivative with respect to azimuth angle.
powerOfAzimuthAngleDerivative Power of derivative with respect to zenith angle.
Returns
Surface derivative on sphere.
Implements tudat::geometric_shapes::SingleSurfaceGeometry.
Definition at line 61 of file sphereSegment.cpp.
References getSurfacePoint(), radius_, tudat::geometric_shapes::SingleSurfaceGeometry::rotationMatrix_, and tudat::geometric_shapes::SingleSurfaceGeometry::scalingMatrix_.
getParameter()
double tudat::geometric_shapes::SphereSegment::getParameter (const int index) virtual
Returns a parameter of the sphere segment. Function uses parameter_ member variable to prevent multiple declarations.
Parameters
index Index of parameter to return (index = 0: returns radius).
Returns
Selected parameter.
Implements tudat::geometric_shapes::SingleSurfaceGeometry.
Definition at line 190 of file sphereSegment.cpp.
References tudat::geometric_shapes::SingleSurfaceGeometry::parameter_, and radius_.
getRadius()
double tudat::geometric_shapes::SphereSegment::getRadius () inline
Returns the radius of the sphere segment.
Returns
Radius of the sphere segment.
Definition at line 108 of file sphereSegment.h.
References radius_.
Referenced by tudat::geometric_shapes::operator<<().
getMaximumAzimuthAngle()
double tudat::geometric_shapes::SphereSegment::getMaximumAzimuthAngle () inline
Returns the maximum values of the azimuth angle.
Returns
Maximum value of azimuth angle.
Definition at line 115 of file sphereSegment.h.
References tudat::geometric_shapes::SingleSurfaceGeometry::maximumIndependentVariable1_.
getMinimumAzimuthAngle()
double tudat::geometric_shapes::SphereSegment::getMinimumAzimuthAngle () inline
Returns the minimum value of the azimuth angle.
Returns
Minimum value of azimuth angle.
Definition at line 122 of file sphereSegment.h.
References tudat::geometric_shapes::SingleSurfaceGeometry::minimumIndependentVariable1_.
getMaximumZenithAngle()
double tudat::geometric_shapes::SphereSegment::getMaximumZenithAngle () inline
Returns the maximum value of the zenith angle.
Returns
Maximum value of zenith angle.
Definition at line 129 of file sphereSegment.h.
References tudat::geometric_shapes::SingleSurfaceGeometry::maximumIndependentVariable2_.
getMinimumZenithAngle()
double tudat::geometric_shapes::SphereSegment::getMinimumZenithAngle () inline
Returns the minimum value of the zenith.
Returns
Minimum value of zenith angle.
Definition at line 136 of file sphereSegment.h.
References tudat::geometric_shapes::SingleSurfaceGeometry::minimumIndependentVariable2_.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, SphereSegment & sphereSegment) friend
Overloads ostream to print class information, prints the class type, the ranges for the azimuth and zenith angles and the radius.
Parameters
stream Stream object.
sphereSegment Sphere segment.
Returns
Stream object.
Definition at line 210 of file sphereSegment.cpp.
Member Data Documentation
radius_
double tudat::geometric_shapes::SphereSegment::radius_ private
Sphere radius.
Definition at line 156 of file sphereSegment.h.
Referenced by getParameter(), getRadius(), getSurfaceDerivative(), getSurfacePoint(), and SphereSegment().
The documentation for this class was generated from the following files:
Mathematics/GeometricShapes/sphereSegment.h
Mathematics/GeometricShapes/sphereSegment.cpp