Tudat: tudat::ephemerides::ConstantEphemeris Class Reference
tudat::ephemerides::ConstantEphemeris Class Reference
Ephemeris class that gives a constant (i.e. time independent) state.
#include <constantEphemeris.h>
Public Member Functions
ConstantEphemeris (const std::function< Eigen::Vector6d() > constantStateFunction, const std::string &referenceFrameOrigin="SSB", const std::string &referenceFrameOrientation="ECLIPJ2000")
Constructor of a constant Ephemeris object.
ConstantEphemeris (const Eigen::Vector6d constantState, const std::string &referenceFrameOrigin="SSB", const std::string &referenceFrameOrientation="ECLIPJ2000")
Constructor of a constant Ephemeris object.
virtual Eigen::Vector6d getCartesianState (const double secondsSinceEpoch)=0
Get state from ephemeris.
Eigen::Vector6d getCartesianState (const double seconsSinceEpoch=0.0)
Get state from ephemeris.
void updateConstantState (const Eigen::Vector6d &newState)
Modifies the constant state.
Public Member Functions inherited from tudat::ephemerides::Ephemeris
Ephemeris (const std::string &referenceFrameOrigin="", const std::string &referenceFrameOrientation="")
Constructor.
virtual ~Ephemeris ()
Default destructor.
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongState (const double secondsSinceEpoch)
Get state from ephemeris (with long double as state scalar).
virtual Eigen::Matrix< long double, 6, 1 > getCartesianLongStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with long double as state scalar and Time as time type).
virtual Eigen::Vector6d getCartesianStateFromExtendedTime (const Time &currentTime)
Get state from ephemeris (with double as state scalar and Time as time type).
std::string getReferenceFrameOrientation ()
Get reference frame orientation.
std::string getReferenceFrameOrigin ()
Get reference frame origin.
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (double specialization).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const double &time)
Get state from ephemeris, with state scalar as template type (long double specialization).
template<>
Eigen::Matrix< double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (double specialization with Time input).
template<>
Eigen::Matrix< long double, 6, 1 > getTemplatedStateFromEphemeris (const Time &time)
Get state from ephemeris, with state scalar as template type (long double specialization with Time input).
template<typename StateScalarType , typename TimeType >
Eigen::Matrix< StateScalarType, 6, 1 > getTemplatedStateFromEphemeris (const TimeType &time)
Get state from ephemeris, with state scalar as template type.
Private Attributes
std::function< Eigen::Vector6d() > constantStateFunction_
Time-independent state function.
Additional Inherited Members
Protected Attributes inherited from tudat::ephemerides::Ephemeris
std::string referenceFrameOrientation_
Reference frame orientation.
std::string referenceFrameOrigin_
Reference frame origin.
Detailed Description
Definition at line 26 of file constantEphemeris.h.
Constructor & Destructor Documentation
ConstantEphemeris() [1/2]
tudat::ephemerides::ConstantEphemeris::ConstantEphemeris (const std::function< Eigen::Vector6d() > constantStateFunction, const std::string & referenceFrameOrigin = "SSB", const std::string & referenceFrameOrientation = "ECLIPJ2000") inline
Constructor.
Parameters
constantStateFunction Function returning the constant state.
referenceFrameOrigin Origin of reference frame in which state is defined.
referenceFrameOrientation Orientation of reference frame in which state is defined.
Definition at line 39 of file constantEphemeris.h.
ConstantEphemeris() [2/2]
tudat::ephemerides::ConstantEphemeris::ConstantEphemeris (const Eigen::Vector6d constantState, const std::string & referenceFrameOrigin = "SSB", const std::string & referenceFrameOrientation = "ECLIPJ2000") inline
Constructor
Parameters
constantState Constant state value.
referenceFrameOrigin Origin of reference frame in which state is defined.
referenceFrameOrientation Orientation of reference frame in which state is defined.
Definition at line 52 of file constantEphemeris.h.
References constantStateFunction_.
Member Function Documentation
getCartesianState() [1/2]
Eigen::Vector6d tudat::ephemerides::ConstantEphemeris::getCartesianState (const double seconsSinceEpoch = 0.0) inline virtual
Returns state from ephemeris at given time.
Parameters
seconsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated (not used in this derived class)
Returns
Constant state given by constantStateFunction_
Implements tudat::ephemerides::Ephemeris.
Definition at line 65 of file constantEphemeris.h.
References constantStateFunction_.
updateConstantState()
void tudat::ephemerides::ConstantEphemeris::updateConstantState (const Eigen::Vector6d & newState) inline
Changes the constant state value to a new value.
Parameters
newState New value for constant state.
Definition at line 76 of file constantEphemeris.h.
References constantStateFunction_.
getCartesianState() [2/2]
virtual Eigen::Vector6d tudat::ephemerides::Ephemeris::getCartesianState
Returns state from ephemeris at given Julian date.
Parameters
secondsSinceEpoch Seconds since epoch at which ephemeris is to be evaluated.
Returns
State from ephemeris.
Member Data Documentation
constantStateFunction_
std::function< Eigen::Vector6d() > tudat::ephemerides::ConstantEphemeris::constantStateFunction_ private
Function that returns a constant cartesian state.
Definition at line 87 of file constantEphemeris.h.
Referenced by ConstantEphemeris(), getCartesianState(), and updateConstantState().
The documentation for this class was generated from the following file:
Astrodynamics/Ephemerides/constantEphemeris.h