Tudat: tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel Class Reference
tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel Class Reference
Body shape model for an oblate spheroid.
#include <oblateSpheroidBodyShapeModel.h>
Public Member Functions
OblateSpheroidBodyShapeModel (const double equatorialRadius, const double flattening)
Constructor.
~OblateSpheroidBodyShapeModel ()
Destructor.
double getAltitude (const Eigen::Vector3d &bodyFixedPosition)
Calculates the altitude above the oblate spheroid.
double getAverageRadius ()
Function to return the mean radius of the oblate spheroid.
double getEquatorialRadius ()
Function to obtain the equatorial radius.
double getFlattening ()
Function to obtain the flattening of the oblate spheroid.
double getGeodeticLatitude (const Eigen::Vector3d &bodyFixedPosition, const double tolerance=1.0E-4)
Calculates the geodetic latitude w.r.t. the oblate spheroid.
Eigen::Vector3d getGeodeticPositionWrtShape (const Eigen::Vector3d &bodyFixedPosition, const double tolerance=1.0E-4)
Calculates the geodetic position w.r.t. the oblate spheroid.
Public Member Functions inherited from tudat::basic_astrodynamics::BodyShapeModel
BodyShapeModel ()
Default constructor.
virtual ~BodyShapeModel ()
Virtual destructor.
Private Attributes
double equatorialRadius_
Equatorial radius of the oblate spheroid.
double flattening_
Flattening of the oblate spheroid.
double polarRadius_
Polar radius of the oblate spheroid.
Detailed Description
Body shape model for an oblate spheroid (flattened sphere), typically used as approximation for planets and large moons.
Definition at line 34 of file oblateSpheroidBodyShapeModel.h.
Constructor & Destructor Documentation
OblateSpheroidBodyShapeModel()
tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::OblateSpheroidBodyShapeModel (const double equatorialRadius, const double flattening) inline
Constructor, sets the geomtric properties of the shape.
Parameters
equatorialRadius Equatorial radius of the oblate spheroid
flattening Flattening of the oblate spheroid
Definition at line 44 of file oblateSpheroidBodyShapeModel.h.
References flattening_, and polarRadius_.
~OblateSpheroidBodyShapeModel()
tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::~OblateSpheroidBodyShapeModel () inline
Definition at line 52 of file oblateSpheroidBodyShapeModel.h.
Member Function Documentation
getAltitude()
double tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getAltitude (const Eigen::Vector3d & bodyFixedPosition) inline virtual
Function to calculate the altitude above the oblate spheroid from a body fixed position.
Parameters
bodyFixedPosition Cartesian, body-fixed position of the point at which the altitude is to be determined.
Returns
Altitude above the oblate spheroid.
Implements tudat::basic_astrodynamics::BodyShapeModel.
Definition at line 61 of file oblateSpheroidBodyShapeModel.h.
References tudat::coordinate_conversions::calculateAltitudeOverOblateSpheroid(), tudat::mathematical_constants::E, equatorialRadius_, and flattening_.
getGeodeticPositionWrtShape()
Eigen::Vector3d tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getGeodeticPositionWrtShape (const Eigen::Vector3d & bodyFixedPosition, const double tolerance = 1.0E-4) inline
Function to calculate the geodetic position w.r.t. the oblate spheroid.
See also
convertCartesianToGeodeticCoordinates
Parameters
bodyFixedPosition Cartesian, body-fixed position of the point at which the geodetic position is to be determined.
tolerance Convergence criterion for iterative algorithm that is employed. Represents the required change of position (in m) between two iterations.
Returns
Geodetic coordinates at requested point.
Definition at line 77 of file oblateSpheroidBodyShapeModel.h.
References tudat::coordinate_conversions::convertCartesianToGeodeticCoordinates(), equatorialRadius_, and flattening_.
getGeodeticLatitude()
double tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getGeodeticLatitude (const Eigen::Vector3d & bodyFixedPosition, const double tolerance = 1.0E-4) inline
Function to calculate the geodetic latitude w.r.t. the oblate spheroid.
See also
convertCartesianToGeodeticCoordinates
Parameters
bodyFixedPosition Cartesian, body-fixed position of the point at which the geodetic latitude is to be determined.
tolerance Convergence criterion for iterative algorithm that is employed. Represents the required change of position (in m) between two iterations.
Returns
Geodetic latitude at requested point.
Definition at line 94 of file oblateSpheroidBodyShapeModel.h.
References tudat::coordinate_conversions::calculateGeodeticLatitude(), equatorialRadius_, and flattening_.
Referenced by tudat::aerodynamics::FlightConditions::FlightConditions().
getAverageRadius()
double tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getAverageRadius () inline virtual
Function to return the mean radius of the oblate spheroid.
Returns
Average radius of oblate spheroid.
Implements tudat::basic_astrodynamics::BodyShapeModel.
Definition at line 106 of file oblateSpheroidBodyShapeModel.h.
References equatorialRadius_, and polarRadius_.
getEquatorialRadius()
double tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getEquatorialRadius () inline
Function to obtain the equatorial radius
Returns
Equatorial radius of the oblate spheroid
Definition at line 116 of file oblateSpheroidBodyShapeModel.h.
References equatorialRadius_.
getFlattening()
double tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getFlattening () inline
Function to obtain the flattening of the oblate spheroid
Returns
Flattening radius of the oblate spheroid
Definition at line 126 of file oblateSpheroidBodyShapeModel.h.
References flattening_.
Referenced by tudat::coordinate_conversions::convertPositionElements(), and tudat::ground_stations::getRotationQuaternionFromBodyFixedToTopocentricFrame().
Member Data Documentation
equatorialRadius_
double tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::equatorialRadius_ private
Definition at line 133 of file oblateSpheroidBodyShapeModel.h.
Referenced by getAltitude(), getAverageRadius(), getEquatorialRadius(), getGeodeticLatitude(), and getGeodeticPositionWrtShape().
polarRadius_
double tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::polarRadius_ private
Definition at line 136 of file oblateSpheroidBodyShapeModel.h.
Referenced by getAverageRadius(), and OblateSpheroidBodyShapeModel().
flattening_
double tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::flattening_ private
Definition at line 139 of file oblateSpheroidBodyShapeModel.h.
Referenced by getAltitude(), getFlattening(), getGeodeticLatitude(), getGeodeticPositionWrtShape(), and OblateSpheroidBodyShapeModel().
The documentation for this class was generated from the following file:
Astrodynamics/BasicAstrodynamics/oblateSpheroidBodyShapeModel.h