Tudat: tudat::simulation_setup::PodOutput< ObservationScalarType > Struct Template Reference
tudat::simulation_setup::PodOutput< ObservationScalarType > Struct Template Reference
Data structure through which the output of the orbit determination is communicated.
#include <podInputOutputTypes.h>
Public Member Functions
PodOutput (const Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > &parameterEstimate, const Eigen::VectorXd &residuals, const Eigen::MatrixXd &normalizedInformationMatrix, const Eigen::VectorXd &weightsMatrixDiagonal, const Eigen::VectorXd &informationMatrixTransformationDiagonal, const Eigen::MatrixXd &inverseNormalizedCovarianceMatrix, const double residualStandardDeviation, const std::vector< Eigen::VectorXd > &residualHistory=std::vector< Eigen::VectorXd >(), const std::vector< Eigen::VectorXd > &parameterHistory=std::vector< Eigen::VectorXd >(), const bool exceptionDuringInversion=false, const bool exceptionDuringPropagation=false)
Constructor.
Eigen::MatrixXd getCorrelationMatrix ()
Function to retrieve the correlation matrix of the estimation result.
Eigen::VectorXd getFormalErrorVector ()
Function to retrieve the unnormalized formal error vector of the estimation result.
Eigen::MatrixXd getParameterHistoryMatrix ()
Function to get parameter vectors per iteration concatenated into a matrix.
Eigen::MatrixXd getResidualHistoryMatrix ()
Function to get residual vectors per iteration concatenated into a matrix.
Eigen::MatrixXd getUnnormalizedCovarianceMatrix ()
Function to retrieve the unnormalized estimation covariance matrix.
Eigen::MatrixXd getUnnormalizedInverseCovarianceMatrix ()
Function to retrieve the unnormalized inverse estimation covariance matrix.
Public Attributes
bool exceptionDuringInversion_
Boolean denoting whether an exception was caught during inversion of normal equations.
bool exceptionDuringPropagation_
Boolean denoting whether an exception was caught during (re)propagation of equations of motion (and variational equations)
Eigen::VectorXd informationMatrixTransformationDiagonal_
Vector of values by which the columns of the unnormalized information matrix were divided to normalize its entries.
Eigen::MatrixXd inverseNormalizedCovarianceMatrix_
Inverse of postfit normalized covariance matrix.
Eigen::MatrixXd normalizedInformationMatrix_
Matrix of observation partials (normalixed) used in estimation (may be empty if so requested)
Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > parameterEstimate_
Vector of estimated parameter values.
std::vector< Eigen::VectorXd > parameterHistory_
Vector of parameter vectors per iteration (entry 0 is pre-estimation values)
std::vector< Eigen::VectorXd > residualHistory_
Vector of residuals per iteration.
Eigen::VectorXd residuals_
Vector of postfit observation residuals.
double residualStandardDeviation_
Standard deviation of postfit residuals vector.
Eigen::VectorXd weightsMatrixDiagonal_
Diagonal of weights matrix used in the estimation.
Detailed Description
template<typename ObservationScalarType = double>
struct tudat::simulation_setup::PodOutput< ObservationScalarType >
Definition at line 355 of file podInputOutputTypes.h.
Constructor & Destructor Documentation
PodOutput()
template<typename ObservationScalarType = double> tudat::simulation_setup::PodOutput< ObservationScalarType >::PodOutput (const Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > & parameterEstimate, const Eigen::VectorXd & residuals, const Eigen::MatrixXd & normalizedInformationMatrix, const Eigen::VectorXd & weightsMatrixDiagonal, const Eigen::VectorXd & informationMatrixTransformationDiagonal, const Eigen::MatrixXd & inverseNormalizedCovarianceMatrix, const double residualStandardDeviation, const std::vector< Eigen::VectorXd > & residualHistory = std::vector< Eigen::VectorXd >(), const std::vector< Eigen::VectorXd > & parameterHistory = std::vector< Eigen::VectorXd >(), const bool exceptionDuringInversion = false, const bool exceptionDuringPropagation = false) inline
Constructor
Parameters
parameterEstimate Vector of estimated parameter values.
residuals Vector of postfit observation residuals
normalizedInformationMatrix Matrix of observation partials (normalixed) used in estimation (may be empty if so requested)
weightsMatrixDiagonal Diagonal of weights matrix used in the estimation
informationMatrixTransformationDiagonal Vector of values by which the columns of the unnormalized information matrix were divided to normalize its entries.
inverseNormalizedCovarianceMatrix Inverse of postfit normalized covariance matrix
residualStandardDeviation Standard deviation of postfit residuals vector
residualHistory Vector of residuals per iteration
parameterHistory Vector of parameter vectors per iteration (entry 1 is pre-estimation values)
exceptionDuringInversion Boolean denoting whether an exception was caught during inversion of normal equations
exceptionDuringPropagation Boolean denoting whether an exception was caught during (re)propagation of equations of motion (and variational equations).
Definition at line 376 of file podInputOutputTypes.h.
Member Function Documentation
getUnnormalizedInverseCovarianceMatrix()
template<typename ObservationScalarType = double> Eigen::MatrixXd tudat::simulation_setup::PodOutput< ObservationScalarType >::getUnnormalizedInverseCovarianceMatrix () inline
Function to retrieve the unnormalized inverse estimation covariance matrix
Returns
Isnverse estimation covariance matrix
Definition at line 404 of file podInputOutputTypes.h.
References tudat::simulation_setup::PodOutput< ObservationScalarType >::informationMatrixTransformationDiagonal_, and tudat::simulation_setup::PodOutput< ObservationScalarType >::inverseNormalizedCovarianceMatrix_.
Referenced by tudat::simulation_setup::PodOutput< ObservationScalarType >::getUnnormalizedCovarianceMatrix().
getUnnormalizedCovarianceMatrix()
template<typename ObservationScalarType = double> Eigen::MatrixXd tudat::simulation_setup::PodOutput< ObservationScalarType >::getUnnormalizedCovarianceMatrix () inline
Function to retrieve the unnormalized estimation covariance matrix
Returns
Estimation covariance matrix
Definition at line 427 of file podInputOutputTypes.h.
References tudat::simulation_setup::PodOutput< ObservationScalarType >::getUnnormalizedInverseCovarianceMatrix().
Referenced by tudat::simulation_setup::PodOutput< ObservationScalarType >::getCorrelationMatrix(), and tudat::simulation_setup::PodOutput< ObservationScalarType >::getFormalErrorVector().
getFormalErrorVector()
template<typename ObservationScalarType = double> Eigen::VectorXd tudat::simulation_setup::PodOutput< ObservationScalarType >::getFormalErrorVector () inline
Function to retrieve the unnormalized formal error vector of the estimation result.
Returns
Formal error vector of the estimation result.
Definition at line 437 of file podInputOutputTypes.h.
References tudat::simulation_setup::PodOutput< ObservationScalarType >::getUnnormalizedCovarianceMatrix().
Referenced by tudat::simulation_setup::PodOutput< ObservationScalarType >::getCorrelationMatrix().
getCorrelationMatrix()
template<typename ObservationScalarType = double> Eigen::MatrixXd tudat::simulation_setup::PodOutput< ObservationScalarType >::getCorrelationMatrix () inline
Function to retrieve the correlation matrix of the estimation result.
Returns
Correlation matrix of the estimation result.
Definition at line 447 of file podInputOutputTypes.h.
References tudat::simulation_setup::PodOutput< ObservationScalarType >::getFormalErrorVector(), and tudat::simulation_setup::PodOutput< ObservationScalarType >::getUnnormalizedCovarianceMatrix().
getResidualHistoryMatrix()
template<typename ObservationScalarType = double> Eigen::MatrixXd tudat::simulation_setup::PodOutput< ObservationScalarType >::getResidualHistoryMatrix () inline
Function to get residual vectors per iteration concatenated into a matrix (one column per iteration).
Returns
Residual vectors per iteration concatenated into a matrix
Definition at line 457 of file podInputOutputTypes.h.
References tudat::simulation_setup::PodOutput< ObservationScalarType >::residualHistory_.
getParameterHistoryMatrix()
template<typename ObservationScalarType = double> Eigen::MatrixXd tudat::simulation_setup::PodOutput< ObservationScalarType >::getParameterHistoryMatrix () inline
Function to get parameter vectors per iteration concatenated into a matrix (one column per iteration). Column 0 contains pre-estimation values
Returns
Parameter vectors per iteration concatenated into a matrix
Definition at line 481 of file podInputOutputTypes.h.
References tudat::simulation_setup::PodOutput< ObservationScalarType >::parameterHistory_.
Member Data Documentation
parameterEstimate_
template<typename ObservationScalarType = double> Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > tudat::simulation_setup::PodOutput< ObservationScalarType >::parameterEstimate_
Definition at line 500 of file podInputOutputTypes.h.
residuals_
template<typename ObservationScalarType = double> Eigen::VectorXd tudat::simulation_setup::PodOutput< ObservationScalarType >::residuals_
Definition at line 503 of file podInputOutputTypes.h.
normalizedInformationMatrix_
template<typename ObservationScalarType = double> Eigen::MatrixXd tudat::simulation_setup::PodOutput< ObservationScalarType >::normalizedInformationMatrix_
Definition at line 506 of file podInputOutputTypes.h.
weightsMatrixDiagonal_
template<typename ObservationScalarType = double> Eigen::VectorXd tudat::simulation_setup::PodOutput< ObservationScalarType >::weightsMatrixDiagonal_
Definition at line 509 of file podInputOutputTypes.h.
informationMatrixTransformationDiagonal_
template<typename ObservationScalarType = double> Eigen::VectorXd tudat::simulation_setup::PodOutput< ObservationScalarType >::informationMatrixTransformationDiagonal_
Definition at line 512 of file podInputOutputTypes.h.
Referenced by tudat::simulation_setup::PodOutput< ObservationScalarType >::getUnnormalizedInverseCovarianceMatrix().
inverseNormalizedCovarianceMatrix_
template<typename ObservationScalarType = double> Eigen::MatrixXd tudat::simulation_setup::PodOutput< ObservationScalarType >::inverseNormalizedCovarianceMatrix_
Definition at line 515 of file podInputOutputTypes.h.
Referenced by tudat::simulation_setup::PodOutput< ObservationScalarType >::getUnnormalizedInverseCovarianceMatrix().
residualStandardDeviation_
template<typename ObservationScalarType = double> double tudat::simulation_setup::PodOutput< ObservationScalarType >::residualStandardDeviation_
Definition at line 518 of file podInputOutputTypes.h.
residualHistory_
template<typename ObservationScalarType = double> std::vector< Eigen::VectorXd > tudat::simulation_setup::PodOutput< ObservationScalarType >::residualHistory_
Definition at line 521 of file podInputOutputTypes.h.
Referenced by tudat::simulation_setup::PodOutput< ObservationScalarType >::getResidualHistoryMatrix().
parameterHistory_
template<typename ObservationScalarType = double> std::vector< Eigen::VectorXd > tudat::simulation_setup::PodOutput< ObservationScalarType >::parameterHistory_
Definition at line 524 of file podInputOutputTypes.h.
Referenced by tudat::simulation_setup::PodOutput< ObservationScalarType >::getParameterHistoryMatrix().
exceptionDuringInversion_
template<typename ObservationScalarType = double> bool tudat::simulation_setup::PodOutput< ObservationScalarType >::exceptionDuringInversion_
Definition at line 527 of file podInputOutputTypes.h.
exceptionDuringPropagation_
template<typename ObservationScalarType = double> bool tudat::simulation_setup::PodOutput< ObservationScalarType >::exceptionDuringPropagation_
Definition at line 530 of file podInputOutputTypes.h.
The documentation for this struct was generated from the following file:
Astrodynamics/OrbitDetermination/podInputOutputTypes.h