Tudat: tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface Class Reference
tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface Class Reference
Control surface aerodynamic coefficient interface taking function pointers providing aerodynamic coefficient increments as a function of independent variables (doubles).
#include <controlSurfaceAerodynamicCoefficientInterface.h>
Public Member Functions
CustomControlSurfaceIncrementAerodynamicInterface (const std::function< Eigen::Vector6d(const std::vector< double > &) > coefficientFunction, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Constructor.
CustomControlSurfaceIncrementAerodynamicInterface (const std::function< Eigen::Vector3d(const std::vector< double > &) > forceCoefficientFunction, const std::function< Eigen::Vector3d(const std::vector< double > &) > momentCoefficientFunction, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames)
~CustomControlSurfaceIncrementAerodynamicInterface ()
Destructor.
void updateCurrentCoefficients (std::vector< double > &independentVariables)
Compute the aerodynamic coefficient increments of the control surface.
Public Member Functions inherited from tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface
ControlSurfaceIncrementAerodynamicInterface (const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames)
Constructor.
virtual ~ControlSurfaceIncrementAerodynamicInterface ()
Destructor.
Eigen::Matrix< double, 6, 1 > getCurrentAerodynamicCoefficients ()
Function for returning current aerodynamic force and moment coefficients.
Eigen::Vector3d getCurrentForceCoefficients ()
Function for returning current aerodynamic force coefficients.
Eigen::Vector3d getCurrentMomentCoefficients ()
Function for returning current aerodynamic moment coefficients.
AerodynamicCoefficientsIndependentVariables getIndependentVariableName (const unsigned int index)
Function to return a single identifier of the physical meaning of one independent variable.
std::vector< AerodynamicCoefficientsIndependentVariables > getIndependentVariableNames ()
Function to return the identifiers of the physical meaning of each independent variable.
unsigned int getNumberOfIndependentVariables ()
Function to return the number of independent variables upon which the coeficients depend.
Protected Attributes
std::function< Eigen::Vector6d(const std::vector< double > &) > coefficientFunction_
Protected Attributes inherited from tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface
Eigen::Vector3d currentForceCoefficients_
The current force coefficient increments.
Eigen::Vector3d currentMomentCoefficients_
The current moment coefficient increments.
std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames_
Vector with identifiers for the physical meaning of each independent variable of the aerodynamic coefficients.
unsigned int numberOfIndependentVariables_
Number of independent variables upon which the force and moment coefficient increments depend.
Detailed Description
Control surface aerodynamic coefficient interface taking function pointers providing aerodynamics coefficient increments as a function of independent variables (doubles).
The origin of the coefficients or the nature of the independent variables is irrelevant for this class. A typical use of this class is to interface interpolated tabulated control surface increments.
Definition at line 203 of file controlSurfaceAerodynamicCoefficientInterface.h.
Constructor & Destructor Documentation
CustomControlSurfaceIncrementAerodynamicInterface() [1/2]
tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::CustomControlSurfaceIncrementAerodynamicInterface (const std::function< Eigen::Vector6d(const std::vector< double > &) > coefficientFunction, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames) inline
Constructor.
Parameters
coefficientFunction Function returning the concatenated aerodynamic force and moment coefficient increments as function of the set of independent variables.
independentVariableNames Vector with identifiers for the physical meaning of each independent variable of the aerodynamic coefficients.
Definition at line 215 of file controlSurfaceAerodynamicCoefficientInterface.h.
CustomControlSurfaceIncrementAerodynamicInterface() [2/2]
tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::CustomControlSurfaceIncrementAerodynamicInterface (const std::function< Eigen::Vector3d(const std::vector< double > &) > forceCoefficientFunction, const std::function< Eigen::Vector3d(const std::vector< double > &) > momentCoefficientFunction, const std::vector< AerodynamicCoefficientsIndependentVariables > independentVariableNames) inline
Definition at line 221 of file controlSurfaceAerodynamicCoefficientInterface.h.
References coefficientFunction_, and tudat::aerodynamics::concatenateForceAndMomentCoefficients().
~CustomControlSurfaceIncrementAerodynamicInterface()
tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::~CustomControlSurfaceIncrementAerodynamicInterface () inline
Definition at line 234 of file controlSurfaceAerodynamicCoefficientInterface.h.
Member Function Documentation
updateCurrentCoefficients()
void tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::updateCurrentCoefficients (std::vector< double > & independentVariables) inline virtual
Computes the current force and moment coefficients increments of the control surface. Input is a set of independent variables (doubles) which represent the variables from which the coefficients are calculated
Parameters
independentVariables Independent variables of force and moment coefficient determination implemented by derived class
Implements tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface.
Definition at line 244 of file controlSurfaceAerodynamicCoefficientInterface.h.
References coefficientFunction_, tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::currentForceCoefficients_, tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::currentMomentCoefficients_, and tudat::aerodynamics::ControlSurfaceIncrementAerodynamicInterface::numberOfIndependentVariables_.
Member Data Documentation
coefficientFunction_
std::function< Eigen::Vector6d(const std::vector< double >&) > tudat::aerodynamics::CustomControlSurfaceIncrementAerodynamicInterface::coefficientFunction_ protected
Function returning the concatenated aerodynamic force and moment coefficient increments as function of the set of independent variables.
Definition at line 265 of file controlSurfaceAerodynamicCoefficientInterface.h.
Referenced by CustomControlSurfaceIncrementAerodynamicInterface(), and updateCurrentCoefficients().
The documentation for this class was generated from the following file:
Astrodynamics/Aerodynamics/controlSurfaceAerodynamicCoefficientInterface.h