Tudat: tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients Class Reference
tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients Class Reference
Interface class for estimation of spherical harmonic gravity field cosine coefficients.
#include <sphericalHarmonicCosineCoefficients.h>
Public Member Functions
SphericalHarmonicsCosineCoefficients (const std::function< Eigen::MatrixXd() > getCosineCoefficients, const std::function< void(Eigen::MatrixXd) > setCosineCoefficients, const std::vector< std::pair< int, int > > blockIndices, const std::string &associatedBody)
Constructor.
~SphericalHarmonicsCosineCoefficients ()
Destructor.
std::vector< std::pair< int, int > > getBlockIndices ()
Function to retrieve the list of cosine coefficient indices which are to be estimated.
std::string getParameterDescription ()
int getParameterSize ()
Function to retrieve the size of the parameter.
Eigen::VectorXd getParameterValue ()
Function to retrieve the current values of the cosine coefficients that are to be estimated.
void setParameterValue (const Eigen::VectorXd parameterValue)
Function to reset the cosine coefficients that are to be estimated.
Public Member Functions inherited from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >
EstimatableParameter (const EstimatebleParametersEnum parameterName, const std::string &associatedBody, const std::string &pointOnBodyId="")
Constructor.
virtual ~EstimatableParameter ()
Virtual destructor.
EstimatebleParameterIdentifier getParameterName ()
Function to retrieve the type and associated body of the parameter.
virtual std::string getSecondaryIdentifier ()
Function to return additional identifier for parameter.
Private Attributes
std::vector< std::pair< int, int > > blockIndices_
List of cosine coefficient indices which are to be estimated.
std::function< Eigen::MatrixXd() > getCosineCoefficients_
Function to retrieve the full set of sine coefficients, of which a subset is to be estimated.
int parameterSize_
std::function< void(Eigen::MatrixXd) > setCosineCoefficients_
Function to reset the full set of sine coefficients, of which a subset is to be estimated.
Additional Inherited Members
Protected Attributes inherited from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >
EstimatebleParameterIdentifier parameterName_
Identifier of parameter.
Detailed Description
Interface class for estimation of spherical harmonic gravity field cosine coefficients. Interfaces the estimation with the member coefficients of an instance of the SphericalHarmonicsGravityField (or nominal coefficients of TimeDependentSphericalHarmonicsGravityField).
Definition at line 32 of file sphericalHarmonicCosineCoefficients.h.
Constructor & Destructor Documentation
SphericalHarmonicsCosineCoefficients()
tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::SphericalHarmonicsCosineCoefficients (const std::function< Eigen::MatrixXd() > getCosineCoefficients, const std::function< void(Eigen::MatrixXd) > setCosineCoefficients, const std::vector< std::pair< int, int > > blockIndices, const std::string & associatedBody) inline
Constructor
Parameters
getCosineCoefficients Function to retrieve the full set of sine coefficients, of which a subset is to be estimated.
setCosineCoefficients Function to reset the full set of sine coefficients, of which a subset is to be estimated.
blockIndices List of cosine coefficient indices which are to be estimated (first and second are degree and order for each vector entry).
associatedBody Name of body for which cosine coefficients are to be estimated.
Definition at line 48 of file sphericalHarmonicCosineCoefficients.h.
References blockIndices_, and parameterSize_.
~SphericalHarmonicsCosineCoefficients()
tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::~SphericalHarmonicsCosineCoefficients () inline
Definition at line 61 of file sphericalHarmonicCosineCoefficients.h.
Member Function Documentation
getParameterValue()
Eigen::VectorXd tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::getParameterValue () virtual
Function to retrieve the current values of the cosine coefficients that are to be estimated. The order of the entries in this vector is the same as in the blockIndices_ member vector.
Returns
List of values for cosine coefficients that are to be estimated.
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 20 of file sphericalHarmonicCosineCoefficients.cpp.
References blockIndices_, getCosineCoefficients_, and parameterSize_.
setParameterValue()
void tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::setParameterValue (const Eigen::VectorXd parameterValue) virtual
Function to reset the cosine coefficients that are to be estimated. The order of the entries in this vector is the same as in the blockIndices_ member vector.
Parameters
parameterValue List of new values for cosine coefficients that are to be estimated.
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 35 of file sphericalHarmonicCosineCoefficients.cpp.
References blockIndices_, getCosineCoefficients_, tudat::input_output::field_types::general::parameterValue, and setCosineCoefficients_.
getParameterSize()
int tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::getParameterSize () inline virtual
Function to retrieve the size of the parameter, equal to the length of the blcokIndices_ member vector, i.e. the number of coefficients that are to be estimated.
Returns
Size of parameter value.
Implements tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 85 of file sphericalHarmonicCosineCoefficients.h.
References parameterSize_.
Referenced by tudat::acceleration_partials::SphericalHarmonicsGravityPartial::getParameterPartialFunction().
getBlockIndices()
std::vector< std::pair< int, int > > tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::getBlockIndices () inline
Function to retrieve the list of cosine coefficient indices which are to be estimated (first and second are degree and order for each vector entry).
Returns
List of cosine coefficient indices which are to be estimated.
Definition at line 93 of file sphericalHarmonicCosineCoefficients.h.
References blockIndices_.
getParameterDescription()
std::string tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::getParameterDescription () inline virtual
Reimplemented from tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >.
Definition at line 96 of file sphericalHarmonicCosineCoefficients.h.
References blockIndices_, tudat::estimatable_parameters::getParameterTypeString(), and tudat::estimatable_parameters::EstimatableParameter< Eigen::VectorXd >::parameterName_.
Member Data Documentation
getCosineCoefficients_
std::function< Eigen::MatrixXd() > tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::getCosineCoefficients_ private
Definition at line 115 of file sphericalHarmonicCosineCoefficients.h.
Referenced by getParameterValue(), and setParameterValue().
setCosineCoefficients_
std::function< void(Eigen::MatrixXd) > tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::setCosineCoefficients_ private
Definition at line 118 of file sphericalHarmonicCosineCoefficients.h.
Referenced by setParameterValue().
blockIndices_
std::vector< std::pair< int, int > > tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::blockIndices_ private
List of cosine coefficient indices which are to be estimated (first and second are degree and order for each vector entry).
Definition at line 125 of file sphericalHarmonicCosineCoefficients.h.
Referenced by getBlockIndices(), getParameterDescription(), getParameterValue(), setParameterValue(), and SphericalHarmonicsCosineCoefficients().
parameterSize_
int tudat::estimatable_parameters::SphericalHarmonicsCosineCoefficients::parameterSize_ private
Definition at line 127 of file sphericalHarmonicCosineCoefficients.h.
Referenced by getParameterSize(), getParameterValue(), and SphericalHarmonicsCosineCoefficients().
The documentation for this class was generated from the following files:
Astrodynamics/OrbitDetermination/EstimatableParameters/sphericalHarmonicCosineCoefficients.h
Astrodynamics/OrbitDetermination/EstimatableParameters/sphericalHarmonicCosineCoefficients.cpp