Tudat: tudat::input_output Namespace Reference
tudat::input_output Namespace Reference
Namespaces
dictionary
field_types
parsed_data_vector_utilities
solar_activity
stream_filters
Classes
class Extractor
Extractor base class.
class FieldTransform
Field transform base class.
class FieldValue
Field value class.
class FixedWidthParser
Fixed-width parser.
class LinearFieldTransform
Linear field transform class.
class MissileDatcomData
Class which converts and contains the Missile Datcom output aerodynamic data.
class MissileDatcomReader
Class to read a for004.dat file generated by missile Datcom.
class MultiArrayFileReader
Interface class for reading coefficients as a function of N independent variables from a file.
class MultiArrayFileReader< 1 >
Interface class for reading coefficients as a function of 1 independent variables from a file.
class MultiArrayFileReader< 2 >
Interface class for reading coefficients as a function of 2 independent variables from a file.
class MultiArrayFileReader< 3 >
Interface class for reading coefficients as a function of 3 independent variables from a file.
class Parser
Parser interface, indicates that the class can parse passed string and stream data.
class SeparatedParser
Separated parser class.
class TextParser
A TextParser is a Parser that specialized in parsing text files.
struct TwoLineElementData
TLE data class.
class TwoLineElementsTextFileReader
TLE catalog text file reader class.
Typedefs
typedef std::map< double, double > DoubleKeyTypeDoubleValueTypeMap
Typedef for double-KeyType, double-ValueType map.
typedef std::map< double, Eigen::Matrix3d > DoubleKeyTypeMatrix3dValueTypeMap
Typedef for double-KeyType, Matrix3d-ValueType map.
typedef std::map< double, Eigen::MatrixXd > DoubleKeyTypeMatrixXdValueTypeMap
Typedef for double-KeyType, MatrixXd-ValueType map.
typedef std::map< double, Eigen::Vector3d > DoubleKeyTypeVector3dValueTypeMap
Typedef for double-KeyType, Vector3d-ValueType map.
typedef std::map< double, Eigen::VectorXd > DoubleKeyTypeVectorXdValueTypeMap
Typedef for double-KeyType, VectorXd-ValueType map.
typedef boost::shared_ptr< FieldTransform > FieldTransformPointer
Typedef for shared-pointer to FieldTransform object.
typedef std::size_t FieldType
FieldType is a hash number of a description.
typedef boost::shared_ptr< FieldValue > FieldValuePointer
Typedef for shared-pointer to FieldValue object.
typedef boost::shared_ptr< FixedWidthParser > FixedWidthParserPointer
Typedef for shared-pointer to FixedWidthParser object.
typedef std::map< int, double > IntKeyTypeDoubleValueTypeMap
Typedef for int-KeyType, double-ValueType map.
typedef boost::shared_ptr< LinearFieldTransform > LinearFieldTransformPointer
Typedef for shared-pointer to LinearFieldTransform object.
typedef boost::shared_ptr< MissileDatcomData > MissileDatcomDataPointer
Typedef for shared-pointer to MissileDatcomData object.
typedef boost::shared_ptr< MissileDatcomReader > MissileDatcomReaderPointer
Typedef for shared-pointer to MissileDatcomReader object.
typedef boost::shared_ptr< Parser > ParserPointer
Typedef for shared-pointer to Parser object.
typedef boost::shared_ptr< SeparatedParser > SeparatedParserPointer
Typedef for shared-pointer to SeparatedParser object.
typedef boost::shared_ptr< TextParser > TextParserPointer
Typedef for shared-pointer to TextParser object.
typedef boost::shared_ptr< TwoLineElementData > TwoLineElementDataPointer
Typedef for shared-pointer to TwoLineElementData object.
typedef boost::shared_ptr< TwoLineElementsTextFileReader > TwoLineElementsTextFileReaderPointer
Typedef for shared-pointer to TwoLineElementsTextFileReader object.
Functions
bool compareIndependentVariables (const std::vector< std::vector< double > > &list1, const std::vector< std::vector< double > > &list2)
Function to compare if two lists of aerodynamic coefficient independent variables are equal.
static std::string getAtmosphereTablesPath ()
Get atmosphere tables path.
static std::string getEarthOrientationDataFilesPath ()
static std::string getGravityModelsPath ()
Get gravity models path.
int getNumberOfIndependentVariablesInCoefficientFile (const std::string &fileName)
Function to retrieve the number of independent variables that the coefficients in a file are given for.
static std::string getSpaceWeatherDataPath ()
Get space weather data files path.
static std::string getSpiceKernelPath ()
Get Spice kernel path.
static std::string getTudatRootPath ()
Get root-path for Tudat library.
std::vector< boost::filesystem::path > listAllFilesInDirectory (const boost::filesystem::path &directory, const bool isRecurseIntoSubdirectories)
Lists all files in directory.
template<unsigned int NumberOfDimensions>
boost::multi_array< Eigen::Vector3d, static_cast< size_t > NumberOfDimensions) > mergeNDimensionalCoefficients (boost::multi_array< double, static_cast< size_t >(NumberOfDimensions) > xComponents, boost::multi_array< double, static_cast< size_t >(NumberOfDimensions) > yComponents, boost::multi_array< double, static_cast< size_t >(NumberOfDimensions) > zComponents)
Function to merge three double multi-arrays of N dimension into a single Vector3d multi-array.
boost::multi_array< Eigen::Vector3d, 1 > mergeOneDimensionalCoefficients (const boost::multi_array< double, 1 > xComponents, const boost::multi_array< double, 1 > yComponents, const boost::multi_array< double, 1 > zComponents)
Function to merge three double multi-arrays of 1 dimension into a single Vector3d multi-array.
boost::multi_array< Eigen::Vector3d, 3 > mergeThreeDimensionalCoefficients (const boost::multi_array< double, 3 > xComponents, const boost::multi_array< double, 3 > yComponents, const boost::multi_array< double, 3 > zComponents)
Function to merge three double multi-arrays of 3 dimensions into a single Vector3d multi-array.
boost::multi_array< Eigen::Vector3d, 2 > mergeTwoDimensionalCoefficients (const boost::multi_array< double, 2 > xComponents, const boost::multi_array< double, 2 > yComponents, const boost::multi_array< double, 2 > zComponents)
Function to merge three double multi-arrays of 2 dimensions into a single Vector3d multi-array.
std::ostream & operator<< (std::ostream &stream, TwoLineElementData &twoLineElementData)
Overload ostream to print class information.
boost::multi_array< double, 1 > parseRawOneDimensionalCoefficientsFromFile (const std::vector< int > independentVariableSize, const Eigen::MatrixXd &coefficientsBlock)
Function to parse a block of values read from a file into a multi-array of size 1.
boost::multi_array< double, 3 > parseRawThreeDimensionalCoefficientsFromFile (const std::vector< int > independentVariableSize, const Eigen::MatrixXd &coefficientsBlock)
Function to parse a block of values read from a file into a multi-array of size 3.
boost::multi_array< double, 2 > parseRawTwoDimensionalCoefficientsFromFile (const std::vector< int > independentVariableSize, const Eigen::MatrixXd &coefficientsBlock)
Function to parse a block of values read from a file into a multi-array of size 2.
std::string printInFormattedScientificNotation (const double floatingPointNumber, const int basePrecision, const int exponentWidth)
Print floating-point number in formatted scientific notation.
template<unsigned int NumberOfDimensions>
std::pair< boost::multi_array< Eigen::Vector3d, static_cast< size_t > NumberOfDimensions) >, std::vector< std::vector< double > > > readAerodynamicCoefficients (const std::vector< std::string > &fileNames)
Function to read a list of aerodynamic coefficients and associated independent variables from a set of files.
template<unsigned int NumberOfDimensions>
std::pair< boost::multi_array< Eigen::Vector3d, static_cast< size_t > NumberOfDimensions) >, std::vector< std::vector< double > > > readAerodynamicCoefficients (const std::map< int, std::string > &fileNames)
Function to read a list of aerodynamic coefficients and associated independent variables from a set of files.
void readCoefficientsFile (const std::string fileName, std::vector< std::vector< double > > &independentVariables, Eigen::MatrixXd &coefficientBlock)
Function to read a coefficient file (data on a structured grid as a function of N independent variables)
template<typename EigenVectorType = Eigen::VectorXd>
std::map< typename EigenVectorType::Scalar, EigenVectorType > readEigenVectorMapFromFile (const std::string &relativePath, const std::string &separators="\t ;,", const std::string &skipLinesCharacter="%")
Read a map of Eigen vectors from a text file.
Eigen::MatrixXd readMatrixFromFile (const std::string &relativePath, const std::string &separators, const std::string &skipLinesCharacter)
Read the file and return the data matrix.
template<typename KeyType , typename ScalarValueType >
std::map< KeyType, std::vector< ScalarValueType > > readStlVectorMapFromFile (const std::string &relativePath, const std::string &separators="\t ;,", const std::string &skipLinesCharacter="%")
Read a map of std vector from a text file.
template<typename InputIterator >
void writeDataMapToTextFile (InputIterator iteratorDataMap, InputIterator last, const std::string &outputFilename, const boost::filesystem::path &outputDirectory, const std::string &fileHeader, const int precisionOfKeyType, const int precisionOfValueType, const std::string &delimiter)
Write data map to text file.
template<typename KeyType , typename ValueType >
void writeDataMapToTextFile (const std::map< KeyType, ValueType > &dataMap, const std::string &outputFilename, const boost::filesystem::path &outputDirectory, const std::string &fileHeader="", const int precisionOfKeyType=16, const int precisionOfValueType=16, const std::string &delimiter="\t")
Write data map to text file.
template<typename InputIterator >
void writeDataMapToTextFile (InputIterator first, InputIterator last, const std::string &outputFilename)
Write data map to text file.
template<typename KeyType , typename ValueType >
void writeDataMapToTextFile (const std::map< KeyType, ValueType > &dataMap, const std::string &outputFilename)
Write data map to text file.
template<typename KeyType , typename ScalarType , int NumberOfRows, int NumberOfColumns, int Options, int MaximumRows, int MaximumCols>
void writeDataMapToTextFile (const std::map< KeyType, Eigen::Matrix< ScalarType, NumberOfRows, NumberOfColumns, Options, MaximumRows, MaximumCols > > &dataMap, const std::string &outputFilename)
Write data map to text file.
template<typename KeyType , typename ValueType >
void writeDataMapToTextFile (const std::map< KeyType, ValueType > &dataMap, const boost::filesystem::path &outputPath, const std::string &fileHeader, const int precision)
Write data map to text file.
template<typename ScalarType , int NumberOfRows, int NumberOfColumns>
void writeMatrixToFile (Eigen::Matrix< ScalarType, NumberOfRows, NumberOfColumns > matrixToWrite, const std::string &outputFilename, const int precisionOfMatrixEntries=16, const boost::filesystem::path &outputDirectory=getTudatRootPath(), const std::string &delimiter="\t", const std::string &header="")
Write Eigen matrix to text file.
template<typename OutputStream , typename ValueType >
void writeValueToStream (OutputStream &stream, const ValueType &value, const int precision, const std::string &delimiter)
Write a value to a stream.
template<typename OutputStream , typename ScalarType , int NumberOfRows, int NumberOfColumns, int Options, int MaximumRows, int MaximumCols>
void writeValueToStream (OutputStream &stream, const Eigen::Matrix< ScalarType, NumberOfRows, NumberOfColumns, Options, MaximumRows, MaximumCols > &value, const int precision, const std::string &delimiter, const bool endLineAfterRow=0)
Write an Eigen type to a stream.
Typedef Documentation
typedef std::map< double, double > tudat::input_output::DoubleKeyTypeDoubleValueTypeMap
Typedef for double-KeyType, double-ValueType map.
Definition at line 441 of file basicInputOutput.h.
typedef std::map< double, Eigen::VectorXd > tudat::input_output::DoubleKeyTypeVectorXdValueTypeMap
Typedef for double-KeyType, VectorXd-ValueType map.
Definition at line 447 of file basicInputOutput.h.
typedef std::map< double, Eigen::Vector3d > tudat::input_output::DoubleKeyTypeVector3dValueTypeMap
Typedef for double-KeyType, Vector3d-ValueType map.
Definition at line 453 of file basicInputOutput.h.
typedef std::map< double, Eigen::MatrixXd > tudat::input_output::DoubleKeyTypeMatrixXdValueTypeMap
Typedef for double-KeyType, MatrixXd-ValueType map.
Definition at line 459 of file basicInputOutput.h.
typedef std::map< double, Eigen::Matrix3d > tudat::input_output::DoubleKeyTypeMatrix3dValueTypeMap
Typedef for double-KeyType, Matrix3d-ValueType map.
Definition at line 465 of file basicInputOutput.h.
typedef std::map< int, double > tudat::input_output::IntKeyTypeDoubleValueTypeMap
Typedef for int-KeyType, double-ValueType map.
Definition at line 471 of file basicInputOutput.h.
typedef boost::shared_ptr< FieldTransform > tudat::input_output::FieldTransformPointer
Definition at line 52 of file fieldTransform.h.
typedef std::size_t tudat::input_output::FieldType
FieldType is a hash number (see note at the end of this comment) created from a description for that FieldType. This means that it is important to maintain different descriptions of each field, as the same description leads to the same hash. It is strongly advised to use the following convention:
A description is built up from a category path. Each category starts with a capital letter and must not contain any spaces. Following the category name is a colon followed by a space and the description of the next sub-category or the actual string identifying the specific field. The same conventions as for categories are used on the string identifier.
Examples can be seen in FieldType.h
Note: A hash number is a fixed length key that uniquely indexes a variable length key. Hash numbers are mostly used to accelerate table lookup or data comparison tasks such as finding items in a database (Wikipedia). Here, each field type (variable length) is associated with a hash number of fixed length.
Definition at line 46 of file fieldType.h.
typedef boost::shared_ptr< FieldValue > tudat::input_output::FieldValuePointer
Definition at line 97 of file fieldValue.h.
typedef boost::shared_ptr< FixedWidthParser > tudat::input_output::FixedWidthParserPointer
Definition at line 84 of file fixedWidthParser.h.
typedef boost::shared_ptr< LinearFieldTransform > tudat::input_output::LinearFieldTransformPointer
Definition at line 68 of file linearFieldTransform.h.
typedef boost::shared_ptr< MissileDatcomData > tudat::input_output::MissileDatcomDataPointer
Definition at line 223 of file missileDatcomData.h.
typedef boost::shared_ptr< MissileDatcomReader > tudat::input_output::MissileDatcomReaderPointer
Definition at line 145 of file missileDatcomReader.h.
typedef boost::shared_ptr< Parser > tudat::input_output::ParserPointer
Definition at line 68 of file parser.h.
typedef boost::shared_ptr< SeparatedParser > tudat::input_output::SeparatedParserPointer
Definition at line 96 of file separatedParser.h.
typedef boost::shared_ptr< TextParser > tudat::input_output::TextParserPointer
Definition at line 123 of file textParser.h.
typedef boost::shared_ptr< TwoLineElementData > tudat::input_output::TwoLineElementDataPointer
Definition at line 301 of file twoLineElementData.h.
typedef boost::shared_ptr< TwoLineElementsTextFileReader > tudat::input_output::TwoLineElementsTextFileReaderPointer
Definition at line 327 of file twoLineElementsTextFileReader.h.
Function Documentation
boost::multi_array< Eigen::Vector3d, 1 > tudat::input_output::mergeOneDimensionalCoefficients (const boost::multi_array< double, 1 > xComponents, const boost::multi_array< double, 1 > yComponents, const boost::multi_array< double, 1 > zComponents)
Definition at line 20 of file aerodynamicCoefficientReader.cpp.
boost::multi_array< Eigen::Vector3d, 2 > tudat::input_output::mergeTwoDimensionalCoefficients (const boost::multi_array< double, 2 > xComponents, const boost::multi_array< double, 2 > yComponents, const boost::multi_array< double, 2 > zComponents)
Definition at line 45 of file aerodynamicCoefficientReader.cpp.
boost::multi_array< Eigen::Vector3d, 3 > tudat::input_output::mergeThreeDimensionalCoefficients (const boost::multi_array< double, 3 > xComponents, const boost::multi_array< double, 3 > yComponents, const boost::multi_array< double, 3 > zComponents)
Definition at line 76 of file aerodynamicCoefficientReader.cpp.
References k.
bool tudat::input_output::compareIndependentVariables (const std::vector< std::vector< double > > & list1, const std::vector< std::vector< double > > & list2)
Function to compare if two lists of aerodynamic coefficient independent variables (vector of vector of doubles) are equal
Parameters
list1 First list that is to be compared.
list2 Second list that is to be compared.
Returns
True of the two lists are completely equal in size and contents, false otherwise.
Definition at line 109 of file aerodynamicCoefficientReader.cpp.
Referenced by mergeNDimensionalCoefficients(), readAerodynamicCoefficients(), tudat::simulation_setup::readGivenSizeTabulatedAerodynamicCoefficientsFromFiles(), and tudat::simulation_setup::readGivenSizeTabulatedControlIncrementAerodynamicCoefficientsFromFiles().
template<unsigned int NumberOfDimensions> boost::multi_array< Eigen::Vector3d, static_cast< size_t > NumberOfDimensions) > tudat::input_output::mergeNDimensionalCoefficients (boost::multi_array< double, static_cast< size_t >(NumberOfDimensions) > xComponents, boost::multi_array< double, static_cast< size_t >(NumberOfDimensions) > yComponents, boost::multi_array< double, static_cast< size_t >(NumberOfDimensions) > zComponents)
Function to merge three double multi-arrays of N dimension into a single Vector3d multi-array, where the three double multi-arrays represent the x-, y- and z-components of the Vector3ds.
Parameters
xComponents Multi-array containing the x-components of the Vector3d
yComponents Multi-array containing the y-components of the Vector3d
zComponents Multi-array containing the z-components of the Vector3d
Returns
Single multi-array containing Vector3ds according to double multi-arrays.
Definition at line 32 of file aerodynamicCoefficientReader.h.
References compareIndependentVariables(), tudat::utilities::getMultiArrayIndexArray(), and p().
template<unsigned int NumberOfDimensions> std::pair< boost::multi_array< Eigen::Vector3d, static_cast< size_t > NumberOfDimensions) >,std::vector< std::vector< double > > > tudat::input_output::readAerodynamicCoefficients (const std::vector< std::string > & fileNames)
Function to read a list of aerodynamic coefficients of NumberOfDimensions independent variables and associated independent variables from a set of files.
Parameters
fileNames Vector of size 3, containing the file names for the x-, y- and z- components of the aerodynamic coefficients. Note that the independent variables for each components must be identical.
Returns
Pair: first entry containing multi-array of aerodynamic coefficients, second containing list of independent variables at which coefficients are defined.
Definition at line 108 of file aerodynamicCoefficientReader.h.
template<unsigned int NumberOfDimensions> std::pair< boost::multi_array< Eigen::Vector3d, static_cast< size_t > NumberOfDimensions) >,std::vector< std::vector< double > > > tudat::input_output::readAerodynamicCoefficients (const std::map< int, std::string > & fileNames)
Function to read a list of aerodynamic coefficients of 2 independent variables and associated independent variables from a set of files.
Parameters
fileNames Map of file names, with the key required to be 0, 1 and/or 2. These indices denote the x-, y- and z- components of the aerodynamic coefficients. All indices that are not provided in this map are assumed to have associated coefficients equal to zero for all values of the independent variables Note that the independent variables for each components must be identical.
Returns
Pair: first entry containing multi-array of aerodynamic coefficients, second containing list of independent variables at which coefficients are defined.
Definition at line 138 of file aerodynamicCoefficientReader.h.
References compareIndependentVariables().
std::string tudat::input_output::printInFormattedScientificNotation (const double floatingPointNumber, const int basePrecision = std::numeric_limits< double >::digits10, const int exponentWidth = 2)
Prints floating-point number in formatted scientific notation. The user can specify the precision that the base is represented by (default=maximum precision for doubles), and the number of digits (width) in the exponent (default=2). This function can be used to ensure that the string output generated in scientific notation is the consistently the same for all platforms.
Parameters
floatingPointNumber Floating-point number to format.
basePrecision Number of digits to represent the base of the floating-point number.
exponentWidth Number of digits to represent the exponent of the floating-point number.
Returns
Formatted string representation of floating-point number in scientific notation.
Definition at line 28 of file basicInputOutput.cpp.
Referenced by getSpaceWeatherDataPath(), and tudat::input_output::MissileDatcomData::writeCoefficientsToFile().
std::vector< boost::filesystem::path > tudat::input_output::listAllFilesInDirectory (const boost::filesystem::path & directory, const bool isRecurseIntoSubdirectories = false)
List all files in directory.
Lists all files in a given directory. There is a recursion option to allow all files in subdirectories to be listed as well.
Parameters
directory Absolute directory path.
isRecurseIntoSubdirectories Flag to set if algorithm should recurse through subdirectories. Set to false by default.
Returns
Container of filenames in directory, stored as Boost path variables.
Definition at line 95 of file basicInputOutput.cpp.
Referenced by getSpaceWeatherDataPath().
static std::string tudat::input_output::getTudatRootPath () inline static
Returns root-path corresponding with root-directory of Tudat library as a string with trailing slash included.
Returns
Tudat root-path.
Definition at line 45 of file basicInputOutput.h.
Referenced by getAtmosphereTablesPath(), getGravityModelsPath(), getSpaceWeatherDataPath(), getSpiceKernelPath(), tudat::input_output::TwoLineElementsTextFileReader::openFile(), tudat::numerical_quadrature::readGaussianQuadratureNodes(), tudat::numerical_quadrature::readGaussianQuadratureWeights(), tudat::ephemerides::ApproximatePlanetPositionsBase::reloadData(), and writeDataMapToTextFile().
static std::string tudat::input_output::getEarthOrientationDataFilesPath () inline static
Definition at line 60 of file basicInputOutput.h.
Referenced by tudat::earth_orientation::getDefaultPolarMotionCorrectionCalculator(), and tudat::earth_orientation::getDefaultUT1CorrectionCalculator().
static std::string tudat::input_output::getSpiceKernelPath () inline static
Returns path in which Spice kernels are located.
Returns
Path containing Spice kernels.
Definition at line 77 of file basicInputOutput.h.
References getTudatRootPath().
Referenced by tudat::spice_interface::loadStandardSpiceKernels().
static std::string tudat::input_output::getAtmosphereTablesPath () inline static
Returns path in which atmosphere tables are located.
Returns
Path containing atmosphere tables.
Definition at line 91 of file basicInputOutput.h.
References getTudatRootPath().
Referenced by tudat::simulation_setup::getDefaultAtmosphereModelSettings().
static std::string tudat::input_output::getGravityModelsPath () inline static
Returns path in which gravity models are located.
Returns
Path containing gravity models.
Definition at line 101 of file basicInputOutput.h.
References getTudatRootPath().
Referenced by tudat::simulation_setup::getPathForSphericalHarmonicsModel().
static std::string tudat::input_output::getSpaceWeatherDataPath () inline static
Returns path in which space weather data files are located.
Returns
Path containing space weather data files.
Definition at line 111 of file basicInputOutput.h.
References getTudatRootPath(), listAllFilesInDirectory(), and printInFormattedScientificNotation().
Referenced by tudat::simulation_setup::createAtmosphereModel().
template<typename OutputStream , typename ValueType > void tudat::input_output::writeValueToStream (OutputStream & stream, const ValueType & value, const int precision, const std::string & delimiter)
Write a value to a stream, left-aligned at a specified precision. Value is preceded by delimiter followed by a space, and followed by an end-of-line character. Helper function for writeDataMapToTextFile().
Template Parameters
OutputStream Type of the stream to write to.
ValueType Type of the value to write, should support the << operator.
Parameters
stream Stream to write to.
value Value to write to stream.
precision Precision to write the value with.
delimiter Delimiter to precede the value.
Definition at line 158 of file basicInputOutput.h.
Referenced by writeDataMapToTextFile(), and writeMatrixToFile().
template<typename OutputStream , typename ScalarType , int NumberOfRows, int NumberOfColumns, int Options, int MaximumRows, int MaximumCols> void tudat::input_output::writeValueToStream (OutputStream & stream, const Eigen::Matrix< ScalarType, NumberOfRows, NumberOfColumns, Options, MaximumRows, MaximumCols > & value, const int precision, const std::string & delimiter, const bool endLineAfterRow = 0)
Write an Eigen type to a stream, row-by-row and left-aligned at a specified precision. Each value is preceded by delimiter followed by a space, and followed by an end-of-line character. Helper function for writeDataMapToTextFile().
Template Parameters
OutputStream Type of the stream to write to.
ScalarType Scalar type for Eigen::Matrix to write to stream.
NumberOfRows Number of rows in Eigen::Matrix to write to stream.
NumberOfColumns Number of columns in Eigen::Matrix to write to stream.
Options options for Eigen::Matrix to write to stream.
MaxiumumRows Maximum number of rows for Eigen::Matrix to write to stream.
MinimumRows Minimum number of rows for Eigen::Matrix to write to stream.
Parameters
stream Stream to write to.
value Value to write to stream.
precision Precision to write the value with.
delimiter Delimiter to precede the value.
endLineAfterRow Boolean to denote whether a new line is to be started after each row of the matrix
Definition at line 186 of file basicInputOutput.h.
template<typename InputIterator > void tudat::input_output::writeDataMapToTextFile (InputIterator iteratorDataMap, InputIterator last, const std::string & outputFilename, const boost::filesystem::path & outputDirectory, const std::string & fileHeader, const int precisionOfKeyType, const int precisionOfValueType, const std::string & delimiter)
Writes data stored in a map to text file.
Template Parameters
InputIterator Iterator of pairs.
Parameters
iteratorDataMap Iterator to the first item of the sequence to write.
last Iterator to the item past the the last item of the sequence to write.
outputFilename Output filename.
outputDirectory Output directory. This can be passed as a string as well. It will be created if it does not exist.
fileHeader Text to be placed at the head of the output file. N.B: This string MUST end in a newline/return character, or the first line of data will not be printed on a new line.
precisionOfKeyType Number of significant digits of KeyType-data to output.
precisionOfValueType Number of significant digits of ValueType-data to output.
delimiter Delimiter character, to delimit data entries in file.
Definition at line 228 of file basicInputOutput.h.
References writeValueToStream().
Referenced by tudat::json_interface::exportResultsOfDynamicsSimulator(), and writeDataMapToTextFile().
template<typename KeyType , typename ValueType > void tudat::input_output::writeDataMapToTextFile (const std::map< KeyType, ValueType > & dataMap, const std::string & outputFilename, const boost::filesystem::path & outputDirectory, const std::string & fileHeader = "", const int precisionOfKeyType = 16, const int precisionOfValueType = 16, const std::string & delimiter = "\t")
Writes data stored in a map to text file.
Template Parameters
KeyType Data type for map key.
ValueType Data type for map value.
Parameters
dataMap Map with data.
outputFilename Output filename.
outputDirectory Output directory. This can be passed as a string as well. It will be created if it does not exist.
fileHeader Text to be placed at the head of the output file. N.B: This string MUST end in a newline/return character, or the first line of data will not be printed on a new line.
precisionOfKeyType Number of significant digits of KeyType-data to output.
precisionOfValueType Number of significant digits of ValueType-data to output.
delimiter Delimiter character, to delimit data entries in file.
Definition at line 280 of file basicInputOutput.h.
References writeDataMapToTextFile().
template<typename InputIterator > void tudat::input_output::writeDataMapToTextFile (InputIterator first, InputIterator last, const std::string & outputFilename)
Writes data stored in a map to text file, using default KeyType-precision and ValueType-precision (digits10 from "limits" standard library), output directory (Tudat root-path), and delimiter (space). Do not use this function for Eigen types. Instead, use the function that accepts a map as input parameter below, or the function with the full argument list. Otherwise, your input will be truncated.
Template Parameters
InputIterator Iterator of pairs.
Parameters
first Iterator to the first item of the sequence to write.
last Iterator to the item past the the last item of the sequence to write.
outputFilename Output filename.
Definition at line 305 of file basicInputOutput.h.
References getTudatRootPath(), and writeDataMapToTextFile().
template<typename KeyType , typename ValueType > void tudat::input_output::writeDataMapToTextFile (const std::map< KeyType, ValueType > & dataMap, const std::string & outputFilename)
Writes data stored in a map to text file, using default KeyType-precision and ValueType-precision (digits10 from "limits" standard library), output directory (Tudat root-path), and delimiter (space).
Template Parameters
KeyType Data type for map key.
ValueType Data type for map value.
Parameters
dataMap Map with data.
outputFilename Output filename.
Definition at line 330 of file basicInputOutput.h.
References getTudatRootPath(), and writeDataMapToTextFile().
template<typename KeyType , typename ScalarType , int NumberOfRows, int NumberOfColumns, int Options, int MaximumRows, int MaximumCols> void tudat::input_output::writeDataMapToTextFile (const std::map< KeyType, Eigen::Matrix< ScalarType, NumberOfRows, NumberOfColumns, Options, MaximumRows, MaximumCols > > & dataMap, const std::string & outputFilename)
Writes Eigen data stored in a map to text file, using default KeyType-precision and ValueType-precision (digits10 from "limits" standard library), output directory (Tudat root-path), and delimiter (space).
Template Parameters
KeyType Data type for map key.
ValueType Data type for Eigen::Matrix, used as map value.
NumberOfRows Number of rows in Eigen::Matrix, used as map value.
NumberOfColumns Number of columns in Eigen::Matrix, used as map value.
Options options for Eigen::Matrix, used as map value.
MaxiumumRows Maximum number of rows for Eigen::Matrix, used as map value.
MinimumRows Minimum number of rows for Eigen::Matrix, used as map value.
Parameters
dataMap Map with data.
outputFilename Output filename.
Definition at line 359 of file basicInputOutput.h.
References getTudatRootPath(), and writeDataMapToTextFile().
template<typename KeyType , typename ValueType > void tudat::input_output::writeDataMapToTextFile (const std::map< KeyType, ValueType > & dataMap, const boost::filesystem::path & outputPath, const std::string & fileHeader, const int precision)
Writes Eigen data stored in a map to text file, using default KeyType-precision and ValueType-precision (digits10 from "limits" standard library), output directory (Tudat root-path), and delimiter (space).
Template Parameters
KeyType Data type for map key.
ValueType Data type for Eigen::Matrix, used as map value.
Parameters
dataMap Map with data.
outputPath Path of the output file.
fileHeader Text to be placed at the head of the output file. N.B: This string MUST end in a newline/return character, or the first line of data will not be printed on a new line.
precision Number of significant digits of KeyType-data and ValueType-data to output.
Definition at line 388 of file basicInputOutput.h.
References writeDataMapToTextFile().
template<typename ScalarType , int NumberOfRows, int NumberOfColumns> void tudat::input_output::writeMatrixToFile (Eigen::Matrix< ScalarType, NumberOfRows, NumberOfColumns > matrixToWrite, const std::string & outputFilename, const int precisionOfMatrixEntries = 16, const boost::filesystem::path & outputDirectory = getTudatRootPath(), const std::string & delimiter = "\t", const std::string & header = "")
Write Eigen matrix to text file.
Parameters
matrixToWrite Matrix that is to be written to a file
outputFilename Output filename.
precisionOfMatrixEntries Number of significant digits of Matrix output
outputDirectory Output directory. It can be passed as a string as well. The directory be created if it does not exist.
delimiter Delimiter character, to delimit data entries in file.
header Header to be added in the first line. Header char (e.g. %, #), if any, must be included in this string. Must end in line break to make data matrix start in the next line.
Definition at line 411 of file basicInputOutput.h.
References writeValueToStream().
Referenced by tudat::json_interface::exportResultsOfDynamicsSimulator().
template<typename EigenVectorType = Eigen::VectorXd> std::map< typename EigenVectorType::Scalar, EigenVectorType > tudat::input_output::readEigenVectorMapFromFile (const std::string & relativePath, const std::string & separators = "\t ;,", const std::string & skipLinesCharacter = "%")
Read a textfile whith separated (space, tab, comma etc...) values. The first element of each line is a key. Successive elements in the current line are the associated values, converted to Eigen column vector.
Remarks
The scalar type of EigenVectorType is used for the keys of the returned map.
Parameters
relativePath Relative path to file.
separators Separators used, every character in the string will be used as separators. (multiple seperators possible).
skipLinesCharacter Skip lines starting with this character.
Returns
The map with data as read from the file.
Definition at line 56 of file mapTextFileReader.h.
template<typename KeyType , typename ScalarValueType > std::map< KeyType, std::vector< ScalarValueType > > tudat::input_output::readStlVectorMapFromFile (const std::string & relativePath, const std::string & separators = "\t ;,", const std::string & skipLinesCharacter = "%")
Read a textfile whith separated (space, tab, comma etc...) values. The first element of each line is a key. Successive elements in the current line are the associated values, stored as an STL vector.
Parameters
relativePath Relative path to file.
separators Separators used, every character in the string will be used as separators. (multiple seperators possible).
skipLinesCharacter Skip lines starting with this character.
Returns
The map with data as read from the file.
Definition at line 104 of file mapTextFileReader.h.
References tudat::json_interface::split().
Eigen::Matrix< ScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::input_output::readMatrixFromFile (const std::string & relativePath, const std::string & separators = "\t ;,", const std::string & skipLinesCharacter = "%")
Read a textfile whith separated (space, tab, comma etc...) numbers. The class returns these numbers as a matrixXd. The first line with numbers is used to define the number of columns.
Parameters
relativePath Relative path to file.
separators Separators used, every character in the string will be used as separators. (multiple seperators possible).
skipLinesCharacter Skip lines starting with this character.
Returns
The datamatrix.
Definition at line 34 of file matrixTextFileReader.cpp.
References tudat::json_interface::split().
Referenced by tudat::aerodynamics::TabulatedAtmosphere::initialize(), and tudat::earth_orientation::readAmplitudesAndFundamentalArgumentMultipliers().
boost::multi_array< double, 1 > tudat::input_output::parseRawOneDimensionalCoefficientsFromFile (const std::vector< int > independentVariableSize, const Eigen::MatrixXd & coefficientsBlock)
Function to parse a block of values read from a file into a multi-array of size 1. The size of the independent variable is provided as input from this file.
Parameters
independentVariableSize Size of independent variables (must be of size 1)
coefficientsBlock Raw number block as read from file.
Returns
Multi-array of size 1, according to input data.
Definition at line 28 of file multiDimensionalArrayReader.cpp.
Referenced by tudat::input_output::MultiArrayFileReader< 1 >::readMultiArrayAndIndependentVariables().
boost::multi_array< double, 2 > tudat::input_output::parseRawTwoDimensionalCoefficientsFromFile (const std::vector< int > independentVariableSize, const Eigen::MatrixXd & coefficientsBlock)
Function to parse a block of values read from a file into a multi-array of size 2. The size of the independent variables is provided as input from this file.
Parameters
independentVariableSize Size of independent variables (must be of size 2)
coefficientsBlock Raw number block as read from file.
Returns
Multi-array of size 2, according to input data.
Definition at line 54 of file multiDimensionalArrayReader.cpp.
Referenced by tudat::input_output::MultiArrayFileReader< 2 >::readMultiArrayAndIndependentVariables().
boost::multi_array< double, 3 > tudat::input_output::parseRawThreeDimensionalCoefficientsFromFile (const std::vector< int > independentVariableSize, const Eigen::MatrixXd & coefficientsBlock)
Function to parse a block of values read from a file into a multi-array of size 3. The size of the independent variables is provided as input from this file.
Parameters
independentVariableSize Size of independent variables (must be of size 3)
coefficientsBlock Raw number block as read from file.
Returns
Multi-array of size 3, according to input data.
Definition at line 83 of file multiDimensionalArrayReader.cpp.
References k.
Referenced by tudat::input_output::MultiArrayFileReader< 3 >::readMultiArrayAndIndependentVariables().
void tudat::input_output::readCoefficientsFile (const std::string fileName, std::vector< std::vector< double > > & independentVariables, Eigen::MatrixXd & coefficientBlock)
Function to read a coefficient file (data on a structured grid as a function of N independent variables). This function reads the file as raw data, converting teh data into a multi-array of the correct size can be done using the MultiArrayFileReader class if needed. The file format is defined in the Tudat wiki.
Parameters
fileName Name of file containing coefficients,
independentVariables Independent variables of coefficients, as read from file (returned by reference)
coefficientBlock Block of coefficients, as read from file (returned by reference)
Definition at line 119 of file multiDimensionalArrayReader.cpp.
References tudat::json_interface::split().
Referenced by tudat::input_output::MultiArrayFileReader< 1 >::readMultiArrayAndIndependentVariables(), tudat::input_output::MultiArrayFileReader< 2 >::readMultiArrayAndIndependentVariables(), and tudat::input_output::MultiArrayFileReader< 3 >::readMultiArrayAndIndependentVariables().
int tudat::input_output::getNumberOfIndependentVariablesInCoefficientFile (const std::string & fileName)
Function to retrieve the number of independent variables that the coefficients in a file are given for.
Parameters
fileName Name of the file containing the coefficients.
Returns
Number of independent variables that the coefficients in a file are given for.
Definition at line 250 of file multiDimensionalArrayReader.cpp.
References tudat::json_interface::split().
Referenced by tudat::simulation_setup::readCoefficientInterpolatorFromFile(), tudat::simulation_setup::readTabulatedAerodynamicCoefficientsFromFiles(), and tudat::simulation_setup::readTabulatedControlIncrementAerodynamicCoefficientsFromFiles().
std::ostream& tudat::input_output::operator<< (std::ostream & stream, TwoLineElementData & twoLineElementData)
Overloads ostream to print class information; prints all converted TLE variables obtained from TLE.
Parameters
stream Stream to print class data to.
twoLineElementData TLE data to print.
Returns
Stream handler.
Definition at line 49 of file twoLineElementData.cpp.
References tudat::input_output::TwoLineElementData::apogee, tudat::orbital_element_conversions::argumentOfPeriapsisIndex, tudat::input_output::TwoLineElementData::bStar, tudat::input_output::TwoLineElementData::coefficientOfBStar, tudat::input_output::TwoLineElementData::coefficientOfSecondDerivativeOfMeanMotionDividedBySix, tudat::orbital_element_conversions::eccentricityIndex, tudat::input_output::TwoLineElementData::epochDay, tudat::input_output::TwoLineElementData::epochYear, tudat::input_output::TwoLineElementData::exponentOfBStar, tudat::input_output::TwoLineElementData::exponentOfSecondDerivativeOfMeanMotionDividedBySix, tudat::input_output::TwoLineElementData::firstDerivativeOfMeanMotionDividedByTwo, tudat::input_output::TwoLineElementData::fourDigitEpochYear, tudat::input_output::TwoLineElementData::fourDigitlaunchYear, tudat::orbital_element_conversions::inclinationIndex, tudat::input_output::TwoLineElementData::launchNumber, tudat::input_output::TwoLineElementData::launchPart, tudat::input_output::TwoLineElementData::launchYear, tudat::input_output::TwoLineElementData::lineNumberLine1, tudat::input_output::TwoLineElementData::lineNumberLine2, tudat::orbital_element_conversions::longitudeOfAscendingNodeIndex, tudat::input_output::TwoLineElementData::meanAnomaly, tudat::input_output::TwoLineElementData::meanMotionInRevolutionsPerDay, tudat::input_output::TwoLineElementData::modulo10CheckSumLine1, tudat::input_output::TwoLineElementData::modulo10CheckSumLine2, tudat::input_output::TwoLineElementData::objectIdentificationNumber, tudat::input_output::TwoLineElementData::objectIdentificationNumberLine2, tudat::input_output::TwoLineElementData::objectName, tudat::input_output::TwoLineElementData::objectNameString, tudat::input_output::TwoLineElementData::orbitalModel, tudat::input_output::TwoLineElementData::perigee, tudat::input_output::TwoLineElementData::revolutionNumber, tudat::input_output::TwoLineElementData::secondDerivativeOfMeanMotionDividedBySix, tudat::orbital_element_conversions::semiMajorAxisIndex, tudat::input_output::TwoLineElementData::tleClassification, tudat::input_output::TwoLineElementData::TLEKeplerianElements, tudat::input_output::TwoLineElementData::tleNumber, and tudat::input_output::TwoLineElementData::totalRevolutionNumber.