Tudat: tudat::coordinate_conversions Namespace Reference
tudat::coordinate_conversions Namespace Reference
Enumerations
enum CartesianCoordinateIndices {
xCartesianCoordinateIndex, yCartesianCoordinateIndex, zCartesianCoordinateIndex, xDotCartesianCoordinateIndex,
yDotCartesianCoordinateIndex, zDotCartesianCoordinateIndex
}
Cartesian coordinate indices.
enum CylindricalCoordinateIndices {
rCylindricalCoordinateIndex, thetaCylindricalCoordinateIndex, zCylindricalCoordinateIndex, rDotCylindricalCoordinateIndex,
vThetaCylindricalCoordinateIndex, zDotCylindricalCoordinateIndex
}
Cylindrical coordinate indices.
enum PositionElementTypes { cartesian_position, spherical_position, geodetic_position }
Enum defining available types of position representations.
enum SphericalCoordinateIndices {
radiusSphericalCoordinateIndex, azimuthSphericalCoordinateIndex, elevationSphericalCoordinateIndex, radialVelocitySphericalCoordinateIndex,
azimuthVelocitySphericalCoordinateIndex, elevationVelocitySphericalCoordinateIndex
}
Spherical coordinate indices.
enum StateElementTypes { cartesian_state, keplerian_state, modified_equinoctial_state }
Enum defining available types of position representations.
Functions
double calculateAltitudeOverOblateSpheroid (const Eigen::Vector3d cartesianState, const double zInterceptOffset, const double interceptToSurfaceDistance)
Calculate the altitude over an oblate spheroid of a position vector from auxiliary variables.
double calculateAltitudeOverOblateSpheroid (const Eigen::Vector3d cartesianState, const double equatorialRadius, const double flattening, const double tolerance)
Calculate the altitude over an oblate spheroid of a position vector.
double calculateEllipticity (const double flattening)
Calculate the ellipticity of an ellipsoid.
std::pair< double, double > calculateGeodeticCoordinatesAuxiliaryQuantities (const Eigen::Vector3d cartesianState, const double equatorialRadius, const double ellipticity, const double tolerance)
Calculate auxiliary quantities for geodetic coordinate conversions.
double calculateGeodeticLatitude (const Eigen::Vector3d cartesianState, const double zInterceptOffset)
Calculate the geodetic latitude from Cartesian position and offset of z-intercept.
double calculateGeodeticLatitude (const Eigen::Vector3d cartesianState, const double equatorialRadius, const double flattening, const double tolerance)
Calculate the geodetic latitude of a position vector.
Eigen::Vector3d convertCartesianToCylindrical (const Eigen::Vector3d &cartesianCoordinates)
Convert Cartesian to cylindrical coordinates.
Eigen::Vector6d convertCartesianToCylindricalState (const Eigen::Vector6d &cartesianState)
Convert Cartesian to cylindrical state.
Eigen::Vector3d convertCartesianToGeodeticCoordinates (const Eigen::Vector3d cartesianCoordinates, const double equatorialRadius, const double flattening, const double tolerance)
Calculate geodetic coordinates (altitude, geodetic latitude, longitude) of a position vector.
template<typename ScalarType = double>
Eigen::Matrix< ScalarType, 3, 1 > convertCartesianToSpherical (const Eigen::Matrix< ScalarType, 3, 1 > &cartesianCoordinates)
Convert Cartesian (x,y,z) to spherical (radius, zenith, azimuth) coordinates.
Eigen::Vector6d convertCartesianToSphericalState (const Eigen::Vector6d &cartesianState)
Convert Cartesian to spherical state.
Eigen::Vector3d convertCylindricalToCartesian (const double radius, const double azimuthAngle, const double z)
Convert cylindrical to Cartesian coordinates.
Eigen::Vector3d convertCylindricalToCartesian (const Eigen::Vector3d &cylindricalCoordinates)
Convert cylindrical to cartesian coordinates.
Eigen::Vector6d convertCylindricalToCartesianState (const Eigen::Vector6d &cylindricalState)
Convert cylindrical to Cartesian state.
Eigen::Vector3d convertGeodeticToCartesianCoordinates (const Eigen::Vector3d geodeticCoordinates, const double equatorialRadius, const double flattening)
Calculate the Cartesian position from geodetic coordinates.
Eigen::Vector3d convertPositionElements (const Eigen::Vector3d &originalElements, const PositionElementTypes originalElementType, const PositionElementTypes convertedElementType, const boost::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel, const double tolerance)
Function to convert a position from one representation to another.
Eigen::Vector3d convertSphericalToCartesian (const Eigen::Vector3d &sphericalCoordinates)
Convert spherical (radius_, zenith, azimuth) to Cartesian (x,y,z) coordinates.
Eigen::Vector3d convertSphericalToCartesianGradient (const Eigen::Vector3d &sphericalGradient, const Eigen::Vector3d &cartesianCoordinates)
Convert spherical to Cartesian gradient.
Eigen::Vector6d convertSphericalToCartesianState (const Eigen::Vector6d &sphericalState)
Convert spherical to Cartesian state.
Eigen::Matrix3d getDerivativeOfSphericalToCartesianGradient (const Eigen::Vector3d &sphericalGradient, const Eigen::Vector3d &cartesianCoordinates, std::vector< Eigen::Matrix3d > &subMatrices)
Function to compute the derivative of the Cartesian gradient w.r.t.
Eigen::Matrix3d getDerivativeOfSphericalToCartesianGradient (const Eigen::Vector3d &sphericalGradient, const Eigen::Vector3d &cartesianCoordinates)
Function to compute the derivative of the Cartesian gradient w.r.t.
Eigen::Matrix3d getSphericalToCartesianGradientMatrix (const Eigen::Vector3d &cartesianCoordinates)
Compute matrix by which to precompute a spherical gradient vector to obtain the Cartesian gradient.
Enumeration Type Documentation
enum tudat::coordinate_conversions::StateElementTypes
Enumerator
cartesian_state
keplerian_state
modified_equinoctial_state
Definition at line 29 of file stateRepresentationConversions.h.
enum tudat::coordinate_conversions::PositionElementTypes
Enumerator
cartesian_position
spherical_position
geodetic_position
Definition at line 37 of file stateRepresentationConversions.h.
enum tudat::coordinate_conversions::SphericalCoordinateIndices
Spherical coordinate indices, for position and velocity components. With r the radius, theta the azimuthal angle, phi the elevational angle. Vr, Vtheta, Vphi are the velocities along the corresponding base vectors of r, theta, phi.
Enumerator
radiusSphericalCoordinateIndex
azimuthSphericalCoordinateIndex
elevationSphericalCoordinateIndex
radialVelocitySphericalCoordinateIndex
azimuthVelocitySphericalCoordinateIndex
elevationVelocitySphericalCoordinateIndex
Definition at line 100 of file coordinateConversions.h.
enum tudat::coordinate_conversions::CylindricalCoordinateIndices
Cylindrical coordinate vector indices, for position and velocity components.
Enumerator
rCylindricalCoordinateIndex
thetaCylindricalCoordinateIndex
zCylindricalCoordinateIndex
rDotCylindricalCoordinateIndex
vThetaCylindricalCoordinateIndex
zDotCylindricalCoordinateIndex
Definition at line 114 of file coordinateConversions.h.
enum tudat::coordinate_conversions::CartesianCoordinateIndices
Cartesian coordinate vector indices, for position and velocity components.
Enumerator
xCartesianCoordinateIndex
yCartesianCoordinateIndex
zCartesianCoordinateIndex
xDotCartesianCoordinateIndex
yDotCartesianCoordinateIndex
zDotCartesianCoordinateIndex
Definition at line 128 of file coordinateConversions.h.
Function Documentation
double tudat::coordinate_conversions::calculateEllipticity (const double flattening)
Calculates the ellipticity of an ellipsoid from its flattening. From Montenbruck & Gill (2000). Note: The ellipticity is not to be confused with the eccentricity.
Parameters
flattening Flattening of the ellipsoid.
Returns
Ellipticity of the ellipsoid.
Definition at line 29 of file geodeticCoordinateConversions.cpp.
Referenced by calculateAltitudeOverOblateSpheroid(), calculateGeodeticLatitude(), and convertCartesianToGeodeticCoordinates().
std::pair< double, double > tudat::coordinate_conversions::calculateGeodeticCoordinatesAuxiliaryQuantities (const Eigen::Vector3d cartesianPosition, const double equatorialRadius, const double ellipticity, const double tolerance)
Calculates auxiliary quantities for geodetic coordinate conversions. (Montenbruck & Gill, 2010, Fig 5.12). The auxiliary quantities are determined by creating a line through the cartesianPosition, perpendicular to the surface and finding its intercept with the z-axis. The distance between the body surface and the z-axis intercept is the first auxiliary quantity, the offset in z-direction of the intersect point from the origin is the second auxiliary variable.
Parameters
cartesianPosition Cartesian position in body-fixed frame where altitude is to be determined.
equatorialRadius Equatorial radius of oblate spheroid.
ellipticity Ellipticity of oblate spheroid.
tolerance Convergence criterion for iterative algorithm that is employed. Represents the required change of position (in m) between two iterations.
Returns
Auxiliary parameters for geodetic coordinate conversions.
Definition at line 36 of file geodeticCoordinateConversions.cpp.
Referenced by calculateAltitudeOverOblateSpheroid(), calculateGeodeticLatitude(), and convertCartesianToGeodeticCoordinates().
Eigen::Vector3d tudat::coordinate_conversions::convertGeodeticToCartesianCoordinates (const Eigen::Vector3d geodeticCoordinates, const double equatorialRadius, const double flattening)
Calculates the Cartesian position from geodetic coordinates (altitude, geodetic latitude, longitude).
Parameters
geodeticCoordinates Geodetic coordinates w.r.t. given body.
equatorialRadius Equatorial radius of oblate spheroid.
flattening Flattening of oblate spheroid.
Returns
Cartesian position in body-fixed frame.
Definition at line 82 of file geodeticCoordinateConversions.cpp.
Referenced by convertPositionElements().
double tudat::coordinate_conversions::calculateAltitudeOverOblateSpheroid (const Eigen::Vector3d cartesianPosition, const double zInterceptOffset, const double interceptToSurfaceDistance)
Calculates the altitude over an oblate spheroid of a position vector. This function gets the auxiliary variables(see calculateGeodeticCoordinatesAuxiliaryQuantities) as input. These values are determined by drawing the line L from cartesianPosition perpendicular to the ellipsoid and calculating the intercept with the z-axis.
Parameters
cartesianPosition Cartesian position in body-fixed frame where altitude is to be determined.
zInterceptOffset Offset of intercept of line L with z-axis from origin in z-direction.
interceptToSurfaceDistance Distance from intercept of line L with z-axis to body surface
Returns
Altitude above specified oblate spheroid at requested point.
See also
calculateGeodeticCoordinatesAuxiliaryQuantities
Definition at line 105 of file geodeticCoordinateConversions.cpp.
Referenced by calculateAltitudeOverOblateSpheroid(), convertCartesianToGeodeticCoordinates(), and tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getAltitude().
double tudat::coordinate_conversions::calculateAltitudeOverOblateSpheroid (const Eigen::Vector3d cartesianPosition, const double equatorialRadius, const double flattening, const double tolerance)
Calculates the altitude over an oblate spheroid of a position vector. The algorithm that is used is iterative, so that it requires a tolerance (in m) for the difference of associated geodetic position between two iterations.
Parameters
cartesianPosition Cartesian position in body-fixed frame where altitude is to be determined.
equatorialRadius Equatorial radius of oblate spheroid.
flattening Flattening of oblate spheroid.
tolerance Convergence criterion for iterative algorithm that is employed. Represents the required change of position (in m) between two iterations.
Returns
Altitude above specified oblate spheroid at requested point.
Definition at line 117 of file geodeticCoordinateConversions.cpp.
References calculateAltitudeOverOblateSpheroid(), calculateEllipticity(), and calculateGeodeticCoordinatesAuxiliaryQuantities().
double tudat::coordinate_conversions::calculateGeodeticLatitude (const Eigen::Vector3d cartesianPosition, const double zInterceptOffset)
Calculates the geodetic latitude from Cartesian position and offset of z-intercept. This intercept is determined by drawing the line from cartesianPosition perpendicular to the ellipsoid and calculating the offset from the origin where it intercepts the z-axis.
Parameters
cartesianPosition Cartesian position in body-fixed frame where geodetic latitude is to be determined.
zInterceptOffset Offset from origin of intersection with z-axis of line perpendicular to surface from cartesianPosition.
Returns
Geodetic latitude above specified oblate spheroid at requested point.
Definition at line 133 of file geodeticCoordinateConversions.cpp.
Referenced by calculateGeodeticLatitude(), convertCartesianToGeodeticCoordinates(), tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getGeodeticLatitude(), and tudat::ground_stations::getRotationQuaternionFromBodyFixedToTopocentricFrame().
double tudat::coordinate_conversions::calculateGeodeticLatitude (const Eigen::Vector3d cartesianPosition, const double equatorialRadius, const double flattening, const double tolerance)
Calculates the geodetic latitude of a position vector on an oblate spheroid. The algorithm that is used is iterative, so that it requires a tolerance (in m) for the difference of associated geodetic position between two iterations.
Parameters
cartesianPosition Cartesian position in body-fixed frame where geodetic latitude is to be determined.
equatorialRadius Equatorial radius of oblate spheroid.
flattening Flattening of oblate spheroid.
tolerance Convergence criterion for iterative algorithm that is employed. Represents the required change of position (in m) between two iterations.
Returns
Geodetic latitude above specified oblate spheroid at requested point.
Definition at line 144 of file geodeticCoordinateConversions.cpp.
References calculateEllipticity(), calculateGeodeticCoordinatesAuxiliaryQuantities(), and calculateGeodeticLatitude().
Eigen::Vector3d tudat::coordinate_conversions::convertCartesianToGeodeticCoordinates (const Eigen::Vector3d cartesianCoordinates, const double equatorialRadius, const double flattening, const double tolerance)
Calculate geodetic coordinates (altitude, geodetic latitude, longitude) of a position vector.
Calculates the geodetic coordinates (altitude, geodetic latitude, longitude) of a position vector. The algorithm that is used is iterative, so that it requires a tolerance (in m) for the difference of associated geodetic position between two iterations.
Parameters
cartesianCoordinates Cartesian position in body-fixed frame where geodetic coordinates are to be determined.
equatorialRadius Equatorial radius of oblate spheroid.
flattening Flattening of oblate spheroid.
tolerance Convergence criterion for iterative algorithm that is employed. Represents the required change of position (in m) between two iterations.
Returns
Geodetic coordinates at requested point.
Definition at line 160 of file geodeticCoordinateConversions.cpp.
References calculateAltitudeOverOblateSpheroid(), calculateEllipticity(), calculateGeodeticCoordinatesAuxiliaryQuantities(), calculateGeodeticLatitude(), and convertCartesianToSpherical().
Referenced by convertPositionElements(), and tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getGeodeticPositionWrtShape().
Eigen::Vector3d tudat::coordinate_conversions::convertPositionElements (const Eigen::Vector3d & originalElements, const PositionElementTypes originalElementTypes, const PositionElementTypes convertedElementTypes, const boost::shared_ptr< basic_astrodynamics::BodyShapeModel > shapeModel = NULL, const double tolerance = 1.0E-4)
Function to convert a position from one representation to another
Parameters
originalElements Position in element type given by originalElementTypes
originalElementTypes Element type used for input.
convertedElementTypes Element type to which originalElements is to be converted.
shapeModel Shape model associated with position (only required for specific element types, e.g. geodetic) default NULL.
tolerance Tolerance used for conversion (only required for specific element types, e.g. geodetic), default 0.1 mm.
Returns
Position in requested element type.
Definition at line 23 of file stateRepresentationConversions.cpp.
References cartesian_position, convertCartesianToGeodeticCoordinates(), convertCartesianToSpherical(), convertGeodeticToCartesianCoordinates(), convertSphericalToCartesian(), geodetic_position, tudat::spice_interface::getAverageRadius(), tudat::basic_astrodynamics::OblateSpheroidBodyShapeModel::getFlattening(), tudat::mathematical_constants::PI, spherical_position, and TUDAT_NAN.
Referenced by tudat::ground_stations::GroundStationState::resetGroundStationPositionAtEpoch().
Eigen::Vector3d tudat::coordinate_conversions::convertSphericalToCartesian (const Eigen::Vector3d & sphericalCoordinates)
Convert spherical (radius, zenith, azimuth) to Cartesian (x,y,z) coordinates.
Converts spherical to cartesian coordinates. Schematic representation can be found on, e.g., http://mathworld.wolfram.com/SphericalCoordinates.html. The transformation equations are the following, with the radius, the azimuth angle and the zenith angle:
Parameters
sphericalCoordinates Vector containing radius, zenith and azimuth (in that order).
Returns
Vector containing Cartesian coordinates, as calculated from sphericalCoordinates.
Definition at line 37 of file coordinateConversions.cpp.
Referenced by convertPositionElements(), tudat::orbital_element_conversions::convertSphericalOrbitalToCartesianState(), tudat::ephemerides::ApproximatePlanetPositionsCircularCoplanar::getCartesianState(), and tudat::geometric_shapes::SphereSegment::getSurfacePoint().
Eigen::Vector3d tudat::coordinate_conversions::convertCylindricalToCartesian (const double radius, const double azimuthAngle, const double z)
Converts cylindrical to Cartesian coordinates. Schematic representation can be found on, e.g., http://mathworld.wolfram.com/CylindricalCoordinates.html. The transformation equations are the following, with the radius and the azimuth angle [rad]:
Parameters
radius Cylindrical radial coordinate r.
azimuthAngle Cylindrical azimuthal coordinate [rad].
z Cylindrical height coordinate z.
Returns
Vector of Cartesian coordinates [x,y,z].
Definition at line 60 of file coordinateConversions.cpp.
Referenced by convertCylindricalToCartesianState(), and tudat::geometric_shapes::ConicalFrustum::getSurfacePoint().
Eigen::Vector3d tudat::coordinate_conversions::convertCylindricalToCartesian (const Eigen::Vector3d & cylindricalCoordinates)
Converts cylindrical to cartesian coordinates. Schematic representation can be found on, e.g., http://mathworld.wolfram.com/CylindricalCoordinates.html. The transformation equations are the following, with the radius and the azimuth angle [rad]:
Parameters
cylindricalCoordinates Vector of cylindrical coordinates [r,theta,z].
Returns
Vector of Cartesian coordinates [x,y,z].
Definition at line 81 of file coordinateConversions.cpp.
Eigen::Vector6d tudat::coordinate_conversions::convertCylindricalToCartesianState (const Eigen::Vector6d & cylindricalState)
Converts cylindrical to Cartesian state. Schematic representation can be found on, e.g., http://mathworld.wolfram.com/CylindricalCoordinates.html and http://staffweb.cms.gre.ac.uk/~ct02/research/thesis/node26.html. The transformation equations are the following, with the radius and the azimuth angle [rad]:
Parameters
cylindricalState Vector of cylindrical state [r,theta,z,Vr,Vtheta,Vz], where Vtheta = r*thetadot.
Returns
Vector of Cartesian state [x,y,z,xdot,ydot,zdot].
Definition at line 104 of file coordinateConversions.cpp.
References convertCylindricalToCartesian().
Eigen::Vector3d tudat::coordinate_conversions::convertCartesianToCylindrical (const Eigen::Vector3d & cartesianCoordinates)
Converts Cartesian to cylindrical coordinates. Schematic representation can be found on, e.g., http://mathworld.wolfram.com/CylindricalCoordinates.html. The transformation equations are the following, with the radius and the azimuth angle [rad] [0,2 ]:
Parameters
cartesianCoordinates Vector of Cartesian coordinates [x,y,z].
Returns
Vector of cylindrical coordinates [r,theta,z].
Definition at line 145 of file coordinateConversions.cpp.
References tudat::basic_mathematics::computeModulo(), and tudat::mathematical_constants::PI.
Referenced by convertCartesianToCylindricalState().
Eigen::Vector6d tudat::coordinate_conversions::convertCartesianToCylindricalState (const Eigen::Vector6d & cartesianState)
Converts Cartesian to cylindrical state. Schematic representation can be found on, e.g., http://mathworld.wolfram.com/CylindricalCoordinates.html and http://staffweb.cms.gre.ac.uk/~ct02/research/thesis/node26.html. The transformation equations are the following, with the radius, the azimuth angle [rad] [0,2 ] and , and the linear cylindrical velocities:
Parameters
cartesianState Vector of Cartesian state [x,y,z,xdot,ydot,zdot].
Returns
Vector of cylindrical state [r,theta,z,Vr,Vtheta,Vz], where Vtheta = r*thetadot.
Definition at line 183 of file coordinateConversions.cpp.
References convertCartesianToCylindrical().
Eigen::Matrix3d tudat::coordinate_conversions::getSphericalToCartesianGradientMatrix (const Eigen::Vector3d & cartesianCoordinates)
Compute matrix by which to precompute a spherical gradient vector to obtain the Cartesian gradient
Parameters
cartesianCoordinates Vector with Cartesian position at which gradient is computed.
Returns
Matrix by which to precompute a spherical gradient vector to obtain the Cartesian gradient
Definition at line 219 of file coordinateConversions.cpp.
Referenced by tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), convertSphericalToCartesianGradient(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtCosineCoefficientBlock(), tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtSineCoefficientBlock(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::wrtTidalModelParameter().
Eigen::Vector3d tudat::coordinate_conversions::convertSphericalToCartesianGradient (const Eigen::Vector3d & sphericalGradient, const Eigen::Vector3d & cartesianCoordinates)
This function converts a gradient vector with respect to spherical coordinates to a gradient vector with respect to Cartesian coordinates. The partial derivatives are calculated according to Vallado [2001] as:
in which , and are the Cartesian coordinates. is an arbitrary scalar. Radius is the length of the position vector. Elevation is the the angle between the position vector and the XY-plane (with the positive direction towards the Z-axis). Azimuth is the dihedral angle about the Z-axis between the X-axis and the position vector (with the positive direction being right-handed about the Z-axis).
Parameters
sphericalGradient Vector with partial derivatives with respect to spherical coordinates. The order is important! sphericalGradient(0) = partial derivative with respect to radius, sphericalGradient(1) = partial derivative with respect to elevation, sphericalGradient(2) = partial derivative with respect to azimuth.
cartesianCoordinates Vector with Cartesian coordinates. The order is important! cartesianCoordinates(0) = x coordinate, cartesianCoordinates(1) = y coordinate, cartesianCoordinates(2) = z coordinate.
Returns
Vector with partial derivatives with respect to Cartesian coordinates. The order is important! cartesianGradient(0) = partial derivative with respect to x coordinate, cartesianGradient(1) = partial derivative with respect to y coordinate, cartesianGradient(2) = partial derivative with respect to z coordinate.
Definition at line 249 of file coordinateConversions.cpp.
References getSphericalToCartesianGradientMatrix().
Referenced by tudat::gravitation::computeGeodesyNormalizedGravitationalAccelerationSum(), and tudat::gravitation::computeSingleGeodesyNormalizedGravitationalAcceleration().
Eigen::Matrix3d tudat::coordinate_conversions::getDerivativeOfSphericalToCartesianGradient (const Eigen::Vector3d & sphericalGradient, const Eigen::Vector3d & cartesianCoordinates, std::vector< Eigen::Matrix3d > & subMatrices)
Function to compute the derivative of the Cartesian gradient w.r.t. the Cartesian position, keeping the spherical gradient constant.
the Cartesian position, keeping the spherical gradient constant.
Parameters
sphericalGradient Value of spherical gradient (derivatives w.r.t. radius, latitude and longitude).
cartesianCoordinates Cartesian position at whichr result is to be computed.
subMatrices Subcomputations performed by this function: derivatives of results of getSphericalToCartesianGradientMatrix, w.r.t. x, y and z component of cartesianCoordinates, respectively.
Returns
Require derivative of cartesian gradient.
Definition at line 258 of file coordinateConversions.cpp.
Referenced by tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), and getDerivativeOfSphericalToCartesianGradient().
Eigen::Matrix3d tudat::coordinate_conversions::getDerivativeOfSphericalToCartesianGradient (const Eigen::Vector3d & sphericalGradient, const Eigen::Vector3d & cartesianCoordinates)
Function to compute the derivative of the Cartesian gradient w.r.t. the Cartesian position, keeping the spherical gradient constant.
the Cartesian position, keeping the spherical gradient constant.
Parameters
sphericalGradient Value of spherical gradient (derivatives w.r.t. radius, latitude and longitude).
cartesianCoordinates Cartesian position at whichr result is to be computed..
Returns
Require derivative of cartesian gradient.
Definition at line 354 of file coordinateConversions.cpp.
References getDerivativeOfSphericalToCartesianGradient().
Eigen::Vector6d tudat::coordinate_conversions::convertSphericalToCartesianState (const Eigen::Vector6d & sphericalState)
Converts a spherical state to a Cartesian state. The transformation matrices are computed according to Torok [2000, pp.10-11].
NOTE: This function is implemented separately from the other conversions due to a different definition of the elevation/zenith angle. This should be consolidated in a future update.
The transformation equations are the following, with the radius (positive from origin to the point in orbit, in meters), the azimuth angle (positive from the x-axis to the y-axis, in radians) and the elevation angle (positive from the xy-plane to the z-axis, in radians):
with
Parameters
sphericalState Vector containing the spherical coordinates and spherical velocities. The order is important! sphericalState(0) = radius r [m], sphericalState(1) = azimuth theta [rad], sphericalState(2) = elevation phi [rad], sphericalState(3) = radial velocity Vr [m/s], sphericalState(4) = azimuthal velocity Vtheta [m/s], sphericalState(5) = elevational velocity Vphi [m/s].
Returns
Vector containing the Cartesian state (both position and velocity, in that order). cartesianState(0) = x [m], cartesianState(1) = y [m], cartesianState(2) = z [m], cartesianState(3) = Vx [m/s], cartesianState(4) = Vy [m/s], cartesianState(5) = Vz [m/s].
Take care: here the elevation is used, not the zenith angle!
Definition at line 363 of file coordinateConversions.cpp.
Eigen::Vector6d tudat::coordinate_conversions::convertCartesianToSphericalState (const Eigen::Vector6d & cartesianState)
Converts a Cartesian state to a spherical state. The transformation matrices are computed according to Torok [2000, pp.10-11].
NOTE: This function is implemented separately from the other conversions due to a different definition of the elevation/zenith angle. This should be consolidated in a future update.
The transformation equations are the following, with the radius (positive from origin to the point in orbit), the azimuth angle (positive from the x-axis to the y-axis) and the elevation angle (positive from the xy-plane to the z-axis):
with
Parameters
cartesianState Vector containing the Cartesian coordinates and Cartesian velocities. The order is important! cartesianState(0) = x [m], cartesianState(1) = y [m], cartesianState(2) = z [m], cartesianState(3) = Vx [m/s], cartesianState(4) = Vy [m/s], cartesianState(5) = Vz [m/s].
Returns
Vector containing the spherical state (both position and velocity, in that order). The order is important! sphericalState(0) = radius r [m], sphericalState(1) = azimuth theta [rad], sphericalState(2) = elevation phi [rad], sphericalState(3) = radial velocity Vr [m/s], sphericalState(4) = azimuthal velocity Vtheta [m/s], sphericalState(5) = elevational velocity Vphi [m/s].
Take care: here the elevation is used, not the zenith!
Definition at line 415 of file coordinateConversions.cpp.
template<typename ScalarType = double> Eigen::Matrix< ScalarType, 3, 1 > tudat::coordinate_conversions::convertCartesianToSpherical (const Eigen::Matrix< ScalarType, 3, 1 > & cartesianCoordinates)
Converts Cartesian to spherical coordinates. Schematic representation can be found on, e.g., http://mathworld.wolfram.com/SphericalCoordinates.html. The transformation equations are the following, with the radius, the azimuth angle and the zenith angle:
Parameters
cartesianCoordinates Vector containing Cartesian coordinates.
Returns
Vector containing sphericalCoordinates radius, zenith and azimuth (in that order), as calculated from sphericalCoordinates.
Definition at line 67 of file coordinateConversions.h.
Referenced by tudat::gravitation::calculateSolidBodyTideSingleCoefficientSetCorrectionFromAmplitude(), tudat::gravitation::calculateSphericalHarmonicGravitationalPotential(), tudat::gravitation::computeGeodesyNormalizedGravitationalAccelerationSum(), tudat::acceleration_partials::computePartialDerivativeOfBodyFixedSphericalHarmonicAcceleration(), tudat::gravitation::computeSingleGeodesyNormalizedGravitationalAcceleration(), convertCartesianToGeodeticCoordinates(), convertPositionElements(), tudat::gravitation::BasicSolidBodyTideGravityFieldVariations::setBodyGeometryParameters(), tudat::orbit_determination::TidalLoveNumberPartialInterface::setCurrentTidalBodyStates(), and tudat::acceleration_partials::SphericalHarmonicsGravityPartial::update().