Tudat: tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType > Class Template Reference
tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType > Class Template Reference abstract
Base class for calculating the state derivative model for a single type of dynamics.
#include <singleStateTypeDerivative.h>
Public Member Functions
SingleStateTypeDerivative (const IntegratedStateType integratedStateType)
Constructor.
virtual ~SingleStateTypeDerivative ()
Virtual destructor.
virtual void calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative)=0
Calculates the state derivative of the system of equations for the given type of dynamics.
virtual void clearStateDerivativeModel ()=0
Function to clear reference/cached values of state derivative model.
virtual void convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton)=0
Function to convert the propagator-specific form of the state to the conventional form in the global frame.
virtual Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &outputSolution, const TimeType &time)=0
Function to convert the state in the conventional form to the propagator-specific form.
virtual void convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &internalSolution, const TimeType &time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton)=0
Function to convert the propagator-specific form of the state to the conventional form.
virtual int getConventionalStateSize ()=0
Function to return the size of the conventional state handled by the object.
IntegratedStateType getIntegratedStateType ()
Function to return the type of dynamics for which the state derivative is calculated.
virtual int getPropagatedStateSize ()
Function to return the size of the propagated state handled by the object.
virtual bool isStateToBePostProcessed ()
Function to return whether the state needs to be post-processed.
virtual void postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState)
Function to process the state vector during propagation.
virtual void postProcessState (Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &unprocessedState)
virtual void updateStateDerivativeModel (const TimeType currentTime)=0
Function to update the state derivative model to the current time.
Protected Attributes
IntegratedStateType integratedStateType_
Type of dynamics for which the state derivative is calculated.
Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > unprocessedState_
Vector used during post-processing of state.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >
Base class for calculating the state derivative model for a single type of dynamics (i.e. translational, rotational, etc.). Each type of dynamics requires its own derived class. Moreover, a specific type of propagator (Cowell, Encke, etc. for translational dynamics) may require their own further derived class, depending on the exact requirements of such a propagator.
Definition at line 64 of file singleStateTypeDerivative.h.
Constructor & Destructor Documentation
SingleStateTypeDerivative()
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::SingleStateTypeDerivative (const IntegratedStateType integratedStateType) inline
Constructor.
Parameters
integratedStateType Type of dynamics for whichh the state derivative is calculated.
Definition at line 73 of file singleStateTypeDerivative.h.
References tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getPropagatedStateSize(), tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::isStateToBePostProcessed(), and tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::unprocessedState_.
~SingleStateTypeDerivative()
template<typename StateScalarType = double, typename TimeType = double> virtual tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::~SingleStateTypeDerivative () inline virtual
Definition at line 83 of file singleStateTypeDerivative.h.
Member Function Documentation
calculateSystemStateDerivative()
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::calculateSystemStateDerivative (const TimeType time, const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & stateOfSystemToBeIntegrated, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > > stateDerivative) pure virtual
Calculates the state derivative of the system of equations for the given type of dynamics. The environment and acceleration models (updateStateDerivativeModel) must be updated before calling this function. It returns the state derivative in the form required for the specific type of propagator used (defined by derived class).
Parameters
time Time at which the state derivative is to be calculated.
stateOfSystemToBeIntegrated Current state of the system, in the form that the equations are propagated (i.e. directly from numerical integrator)
stateDerivative Derivative of the state of the system, in the form that the equations are propagated (i.e. to be piped directly to numerical integrator), returned by reference.
Implemented in tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::BodyMassStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyCowellStateDerivative< StateScalarType, TimeType >, and tudat::propagators::CustomStateDerivative< StateScalarType, TimeType >.
clearStateDerivativeModel()
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::clearStateDerivativeModel () pure virtual
Function to clear reference/cached values of state derivative model, such as the current time and/or state. This function is to be implemented in each derived class
Implemented in tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >, tudat::propagators::BodyMassStateDerivative< StateScalarType, TimeType >, and tudat::propagators::CustomStateDerivative< StateScalarType, TimeType >.
updateStateDerivativeModel()
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::updateStateDerivativeModel (const TimeType currentTime) pure virtual
Function to update the state derivative model (i.e. acceleration, torque, etc. models) to the current time. Note that this function only updates the state derivative model itself, the environment models must be updated before calling this function
Parameters
currentTime Time to which the state derivative is to be updated.
Implemented in tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >, tudat::propagators::BodyMassStateDerivative< StateScalarType, TimeType >, and tudat::propagators::CustomStateDerivative< StateScalarType, TimeType >.
convertCurrentStateToGlobalRepresentation()
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::convertCurrentStateToGlobalRepresentation (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton) pure virtual
Function to convert the propagator-specific form of the state to the conventional form in the global frame.
The conventional form is one that is typically used to represent the current state in the environment (e.g. Body class). For translational dynamics this is the Cartesian position and velocity). The inertial frame is typically the barycenter with J2000/ECLIPJ2000 orientation, but may differ depending on simulation settings
Parameters
internalSolution State in propagator-specific form (i.e. form that is used in numerical integration).
time Current time at which the state is valid.
currentCartesianLocalSoluton State (internalSolution), converted to the 'conventional form' in inertial coordinates, that can for instance be set directly in the body object (returned by reference).
Implemented in tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >, tudat::propagators::BodyMassStateDerivative< StateScalarType, TimeType >, and tudat::propagators::CustomStateDerivative< StateScalarType, TimeType >.
convertFromOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> virtual Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::convertFromOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & outputSolution, const TimeType & time) pure virtual
Function to convert the state in the conventional form to the propagator-specific form. The conventional form is one that is typically used to represent the current state in the environment (e.g. Body class). For translational dynamics this is the Cartesian position and velocity).
Parameters
outputSolution State in 'conventional form'
time Current time at which the state is valid.
Returns
State (outputSolution), converted to the 'propagator-specific form'
Implemented in tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::BodyMassStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::CustomStateDerivative< StateScalarType, TimeType >, and tudat::propagators::NBodyCowellStateDerivative< StateScalarType, TimeType >.
convertToOutputSolution()
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::convertToOutputSolution (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & internalSolution, const TimeType & time, Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > currentCartesianLocalSoluton) pure virtual
Function to convert the propagator-specific form of the state to the conventional form. The conventional form is one that is typically used to represent the current state in the environment (e.g. Body class). For translational dynamics this is the Cartesian position and velocity). In contrast to the convertCurrentStateToGlobalRepresentation function, this function does not provide the state in the inertial frame, but instead provides it in the frame in which it is propagated.
Parameters
internalSolution State in propagator-specific form (i.e. form that is used in numerical integration).
time Current time at which the state is valid.
currentCartesianLocalSoluton State (internalSolution), converted to the 'conventional form' (returned by reference).
Implemented in tudat::propagators::NBodyEnckeStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyGaussKeplerStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyGaussModifiedEquinictialStateDerivative< StateScalarType, TimeType >, tudat::propagators::BodyMassStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyCowellStateDerivative< StateScalarType, TimeType >, and tudat::propagators::CustomStateDerivative< StateScalarType, TimeType >.
Referenced by tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >::convertCurrentStateToGlobalRepresentation(), and tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >::convertCurrentStateToGlobalRepresentation().
getConventionalStateSize()
template<typename StateScalarType = double, typename TimeType = double> virtual int tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getConventionalStateSize () pure virtual
Function to return the size of the conventional state handled by the object. This is the size of the conventional propagation state, e.g., size of Cartesian state for translational propagation.
Returns
Size of the state under consideration.
Implemented in tudat::propagators::NBodyStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionStateDerivative< StateScalarType, TimeType >, tudat::propagators::BodyMassStateDerivative< StateScalarType, TimeType >, and tudat::propagators::CustomStateDerivative< StateScalarType, TimeType >.
Referenced by tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getPropagatedStateSize().
getPropagatedStateSize()
template<typename StateScalarType = double, typename TimeType = double> virtual int tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getPropagatedStateSize () inline virtual
Function to return the size of the propagated state handled by the object. This is the size of the actual propagation state, e.g., size of USM7 state for translational propagation.
Returns
Size of the propagated state under consideration.
Reimplemented in tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >, and tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >.
Definition at line 181 of file singleStateTypeDerivative.h.
References tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getConventionalStateSize().
Referenced by tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >::convertFromOutputSolution(), tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::postProcessState(), and tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::SingleStateTypeDerivative().
getIntegratedStateType()
template<typename StateScalarType = double, typename TimeType = double> IntegratedStateType tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getIntegratedStateType () inline
Function to return the type of dynamics for which the state derivative is calculated
Returns
Type of dynamics for which the state derivative is calculated.
Definition at line 191 of file singleStateTypeDerivative.h.
References tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::integratedStateType_.
postProcessState() [1/2]
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::postProcessState (Eigen::Block< Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > unprocessedState) inline virtual
Function to process the state during propagation. Is especially useful for attitude states (e.g., normalization of quaternions and transformation to/from shadow attitude parameters).
Parameters
unprocessedState State computed after propagation.
Reimplemented in tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >, and tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >.
Definition at line 202 of file singleStateTypeDerivative.h.
References TUDAT_UNUSED_PARAMETER.
Referenced by tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::postProcessState().
postProcessState() [2/2]
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::postProcessState (Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & unprocessedState) inline virtual
Definition at line 207 of file singleStateTypeDerivative.h.
References tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getPropagatedStateSize(), tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::postProcessState(), and tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::unprocessedState_.
isStateToBePostProcessed()
template<typename StateScalarType = double, typename TimeType = double> virtual bool tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::isStateToBePostProcessed () inline virtual
Function to return whether the state needs to be post-processed. Default value is false.
Returns
Boolean informing whether the state needs to be post-processed.
Reimplemented in tudat::propagators::NBodyUnifiedStateModelModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelExponentialMapStateDerivative< StateScalarType, TimeType >, tudat::propagators::NBodyUnifiedStateModelQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionQuaternionsStateDerivative< StateScalarType, TimeType >, tudat::propagators::RotationalMotionModifiedRodriguesParametersStateDerivative< StateScalarType, TimeType >, and tudat::propagators::RotationalMotionExponentialMapStateDerivative< StateScalarType, TimeType >.
Definition at line 219 of file singleStateTypeDerivative.h.
Referenced by tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::SingleStateTypeDerivative().
Member Data Documentation
integratedStateType_
template<typename StateScalarType = double, typename TimeType = double> IntegratedStateType tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::integratedStateType_ protected
Definition at line 227 of file singleStateTypeDerivative.h.
Referenced by tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::getIntegratedStateType().
unprocessedState_
template<typename StateScalarType = double, typename TimeType = double> Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::unprocessedState_ protected
Definition at line 230 of file singleStateTypeDerivative.h.
Referenced by tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::postProcessState(), and tudat::propagators::SingleStateTypeDerivative< StateScalarType, TimeType >::SingleStateTypeDerivative().
The documentation for this class was generated from the following file:
Astrodynamics/Propagators/singleStateTypeDerivative.h