Tudat: tudat::system_models::EngineModel Class Reference
tudat::system_models::EngineModel Class Reference abstract
Base class for a model of an engine, the mass rate/thrust computations are not implemented here.
#include <engineModel.h>
Public Member Functions
EngineModel (const Eigen::Vector3d bodyFixedThrustDirection=Eigen::Vector3d::UnitX())
Constructor.
virtual ~EngineModel ()
Destructor.
Eigen::Vector3d getBodyFixedThrustDirection ()
Function to retrieve the vector denoting the direction of the thrust delivered by the engine in the body-fixed frame.
virtual double getCurrentMassRate ()=0
Pure virtual function to retrieve the propellant mass rate.
double getCurrentThrust ()
Function to retrive the magnitude of the current engine thrust.
virtual void updateEngineModel (const double currentTime)=0
Pure virtual function to update the engine model to the current time.
Protected Attributes
Eigen::Vector3d bodyFixedThrustDirection_
Vector denoting the direction of the thrust delivered by the engine in the body-fixed frame.
double currentThrust_
Current magnitude of the thrust delivered by the engine.
Detailed Description
Base class for a model of an engine, the mass rate/thrust computations are not implemented here, and should be performed in a derived class.
Definition at line 31 of file engineModel.h.
Constructor & Destructor Documentation
tudat::system_models::EngineModel::EngineModel (const Eigen::Vector3d bodyFixedThrustDirection = Eigen::Vector3d::UnitX()) inline
Constructor
Parameters
bodyFixedThrustDirection Vector denoting the direction of the thrust delivered by the engine in the body-fixed frame (for an ideal engine, this is the opposite direction of the nozzle direction). By default, this vector is set to the positive x-direction, along the longitudinal axis.
Definition at line 42 of file engineModel.h.
virtual tudat::system_models::EngineModel::~EngineModel () inline virtual
Definition at line 49 of file engineModel.h.
Member Function Documentation
double tudat::system_models::EngineModel::getCurrentThrust () inline
Function to retrive the magnitude of the current engine thrust, which was set by the last call to the updateEngineModel function (to be defined in the derived class).
Returns
Current engine thrust.
Definition at line 57 of file engineModel.h.
References currentThrust_, getCurrentMassRate(), and updateEngineModel().
Referenced by tudat::simulation_setup::getBodyFixedThrustDirection().
virtual void tudat::system_models::EngineModel::updateEngineModel (const double currentTime) pure virtual
Pure virtual function to update the engine model to the current time. This function must be implemented in teh derived class, wehre it typically resets the currentThrust_ variable (and any associated variables).
Parameters
currentTime Current itme in simulation.
Implemented in tudat::system_models::DirectEngineModel.
Referenced by getCurrentThrust().
virtual double tudat::system_models::EngineModel::getCurrentMassRate () pure virtual
Pure virtual function to retrieve the propellant mass rate.
Returns
Propellant mass rate.
Implemented in tudat::system_models::DirectEngineModel.
Referenced by getCurrentThrust().
Eigen::Vector3d tudat::system_models::EngineModel::getBodyFixedThrustDirection () inline
Function to retrieve the vector denoting the direction of the thrust delivered by the engine in the body-fixed frame
Returns
Vector denoting the direction of the thrust delivered by the engine in the body-fixed frame
Definition at line 82 of file engineModel.h.
References bodyFixedThrustDirection_.
Referenced by tudat::simulation_setup::getBodyFixedThrustDirection().
Member Data Documentation
double tudat::system_models::EngineModel::currentThrust_ protected
Definition at line 90 of file engineModel.h.
Referenced by getCurrentThrust(), and tudat::system_models::DirectEngineModel::updateEngineModel().
Eigen::Vector3d tudat::system_models::EngineModel::bodyFixedThrustDirection_ protected
Vector denoting the direction of the thrust delivered by the engine in the body-fixed frame (for an ideal engine, this is the opposite direction of the nozzle direction). By default, this vector is set to the positive x-direction, along the longitudinal axis
Definition at line 98 of file engineModel.h.
Referenced by getBodyFixedThrustDirection().
The documentation for this class was generated from the following file:
Astrodynamics/SystemModels/engineModel.h