Tudat: tudat::relativity Namespace Reference
tudat::relativity Namespace Reference
Classes
class PPNParameterSet
Class that stores the PPN parameters, typically used as a 'global' environment property stored in ppnParameterSet variable.
class RelativisticAccelerationCorrection
Class to compute typical relativistic corrections to the dynamics of an orbiter.
Functions
Eigen::Vector3d calculateDeSitterCorrectionAcceleration (const Eigen::Vector3d &orbiterRelativeVelocity, const Eigen::Vector3d &orbitedBodyPositionWrtLargerBody, const Eigen::Vector3d &orbitedBodyVelocityWrtLargerBody, const double commonCorrectionTermOfLargerBody, const double ppnParameterGamma)
Function to compute the de Sitter term of the relativistic acceleration correction.
Eigen::Vector3d calculateDeSitterCorrectionAcceleration (const double largerBodyGravitationalParameter, const Eigen::Vector6d &orbiterRelativeState, const Eigen::Vector6d &orbitedBodyStateWrtLargerBody, const double ppnParameterGamma)
Function to compute the de Sitter term of the relativistic acceleration correction.
double calculateFirstCentralBodyProperTimeRateDifference (const double relativeSpeed, const double gravitationalScalarPotential, const double equivalencePrincipleLpiViolationParameter)
Function to compute proper-time rate w.r.t. coordinate time, minus 1.0, from a speed and scalar potential.
double calculateFirstCentralBodyProperTimeRateDifference (const Eigen::Vector6d relativeStateVector, const double centralBodyGravitationalParameter, const double equivalencePrincipleLpiViolationParameter)
Function to compute proper-time rate w.r.t. coordinate time, minus 1.0, from a speed and scalar potential.
Eigen::Matrix< double, 1, 3 > calculateFirstOrderCentralBodyLightTimeCorrectionGradient (const double bodyGravitationalParameter, const Eigen::Vector3d &transmitterPosition, const Eigen::Vector3d &receiverPosition, const Eigen::Vector3d &centralBodyPosition, const bool evaluateGradientAtReceiver, const double ppnParameterGamma)
Function to calculate gradient of first order relativistic light time correction due to a gravitating point mass.
double calculateFirstOrderLightTimeCorrectionFromCentralBody (const double bodyGravitationalParameter, const Eigen::Vector3d &transmitterPosition, const Eigen::Vector3d &receiverPosition, const Eigen::Vector3d &centralBodyPosition, const double ppnParameterGamma)
Function to calculate first order relativistic light time correction due to a gravitating point mass.
Eigen::Vector3d calculateLenseThirringCorrectionAcceleration (const Eigen::Vector3d &relativePosition, const Eigen::Vector3d &relativeVelocity, const double relativeDistance, const double commonCorrectionTerm, const Eigen::Vector3d &centralBodyAngularMomentum, const double ppnParameterGamma)
Function to compute the Lense-Thirring term of the relativistic acceleration correction.
Eigen::Vector3d calculateLenseThirringCorrectionAcceleration (const double centralBodyGravitationalParameter, const Eigen::Vector6d &relativeState, const Eigen::Vector3d &centralBodyAngularMomentum, const double ppnParameterGamma)
Function to compute the Lense-Thirring term of the relativistic acceleration correction.
double calculateRelativisticAccelerationCorrectionsCommonterm (const double centralBodyGravitationalParameter, const double relativeDistance)
Function to compute a term common to several relativistic acceleration terms.
Eigen::Vector3d calculateScharzschildGravitationalAccelerationCorrection (const double centralBodyGravitationalParameter, const Eigen::Vector3d &relativePosition, const Eigen::Vector3d &relativeVelocity, const double relativeDistance, const double commonCorrectionTerm, const double ppnParameterGamma, const double ppnParameterBeta)
Function to compute the Schwarzschild term of the relativistic acceleration correction.
Eigen::Vector3d calculateScharzschildGravitationalAccelerationCorrection (double centralBodyGravitationalParameter, const Eigen::Vector6d &relativeState, double ppnParameterGamma, double ppnParameterBeta)
Function to compute the Schwarzschild term of the relativistic acceleration correction.
Variables
double equivalencePrincipleLpiViolationParameter = 0.0
Global parameter denoting EP violation in proper time rate, initialized to GR value of 0 upon compilation.
static const Eigen::Matrix4d minkowskiMetric
Minkowski metric (-1,1,1,1 signature) represented as a Matrix.
boost::shared_ptr< PPNParameterSet > ppnParameterSet = boost::make_shared< PPNParameterSet >(1.0, 1.0)
Initialize global PPN parameters.
Function Documentation
double tudat::relativity::calculateRelativisticAccelerationCorrectionsCommonterm (const double centralBodyGravitationalParameter, const double relativeDistance)
Function to compute a term common to several relativistic acceleration terms, defined by mu / (c^2 * r^3), with mu the gravitational parameter of the central body, c the speed of light and r the distance between the bodies
Parameters
centralBodyGravitationalParameter Gravitational parameter of body exerting acceleration.
relativeDistance Distance between bodies undergoing and exerting acceleration
Returns
Common term in relativistic accelerations.
Definition at line 22 of file relativisticAccelerationCorrection.cpp.
References tudat::physical_constants::SPEED_OF_LIGHT.
Referenced by calculateDeSitterCorrectionAcceleration(), calculateLenseThirringCorrectionAcceleration(), calculateScharzschildGravitationalAccelerationCorrection(), and tudat::relativity::RelativisticAccelerationCorrection::updateMembers().
Eigen::Vector3d tudat::relativity::calculateScharzschildGravitationalAccelerationCorrection (const double centralBodyGravitationalParameter, const Eigen::Vector3d & relativePosition, const Eigen::Vector3d & relativeVelocity, const double relativeDistance, const double commonCorrectionTerm, const double ppnParameterGamma = 1.0, const double ppnParameterBeta = 1.0)
Function to compute the Schwarzschild term of the relativistic acceleration correction.
Parameters
centralBodyGravitationalParameter Gravitational parameter of body exerting acceleration.
relativePosition Position of body undergoing, w.r.t. body exerting, acceleration.
relativeVelocity Velocity of body undergoing, w.r.t. body exerting, acceleration.
relativeDistance Distance between bodies undergoing and exerting acceleration (norm of relativePosition)
commonCorrectionTerm Common term in relativistic accelerations, as computed by calculateRelativisticAccelerationCorrectionsCommonterm function
ppnParameterGamma PPN parameter gamma
ppnParameterBeta PPN parameter beta
Returns
Schwarzschild term of the relativistic acceleration correction.
Definition at line 32 of file relativisticAccelerationCorrection.cpp.
Referenced by calculateScharzschildGravitationalAccelerationCorrection(), and tudat::relativity::RelativisticAccelerationCorrection::updateMembers().
Eigen::Vector3d tudat::relativity::calculateScharzschildGravitationalAccelerationCorrection (const double centralBodyGravitationalParameter, const Eigen::Vector6d & relativeState, const double ppnParameterGamma = 1.0, const double ppnParameterBeta = 1.0)
Function to compute the Schwarzschild term of the relativistic acceleration correction.
Parameters
centralBodyGravitationalParameter Gravitational parameter of body exerting acceleration.
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
ppnParameterGamma PPN parameter gamma
ppnParameterBeta PPN parameter beta
Returns
Schwarzschild term of the relativistic acceleration correction.
Definition at line 49 of file relativisticAccelerationCorrection.cpp.
References calculateRelativisticAccelerationCorrectionsCommonterm(), and calculateScharzschildGravitationalAccelerationCorrection().
Eigen::Vector3d tudat::relativity::calculateLenseThirringCorrectionAcceleration (const Eigen::Vector3d & relativePosition, const Eigen::Vector3d & relativeVelocity, const double relativeDistance, const double commonCorrectionTerm, const Eigen::Vector3d & centralBodyAngularMomentum, const double ppnParameterGamma = 1.0)
Function to compute the Lense-Thirring term of the relativistic acceleration correction.
Parameters
relativePosition Position of body undergoing, w.r.t. body exerting, acceleration.
relativeVelocity Velocity of body undergoing, w.r.t. body exerting, acceleration.
relativeDistance Distance between bodies undergoing and exerting acceleration (norm of relativePosition)
commonCorrectionTerm Common term in relativistic accelerations, as computed by calculateRelativisticAccelerationCorrectionsCommonterm function
centralBodyAngularMomentum Angular momentum vector of central body.
ppnParameterGamma PPN parameter gamma
Returns
Lense-Thirring term of the relativistic acceleration correction.
Definition at line 64 of file relativisticAccelerationCorrection.cpp.
Referenced by calculateLenseThirringCorrectionAcceleration(), and tudat::relativity::RelativisticAccelerationCorrection::updateMembers().
Eigen::Vector3d tudat::relativity::calculateLenseThirringCorrectionAcceleration (const double centralBodyGravitationalParameter, const Eigen::Vector6d & relativeState, const Eigen::Vector3d & centralBodyAngularMomentum, const double ppnParameterGamma = 1.0)
Function to compute the Lense-Thirring term of the relativistic acceleration correction.
Parameters
centralBodyGravitationalParameter Gravitational parameter of body exerting acceleration.
relativeState Cartesian state of body undergoing, w.r.t. body exerting, acceleration.
centralBodyAngularMomentum Angular momentum vector of central body.
ppnParameterGamma PPN parameter gamma
Returns
Schwarzschild term of the relativistic acceleration correction.
Definition at line 81 of file relativisticAccelerationCorrection.cpp.
References calculateLenseThirringCorrectionAcceleration(), and calculateRelativisticAccelerationCorrectionsCommonterm().
Eigen::Vector3d tudat::relativity::calculateDeSitterCorrectionAcceleration (const Eigen::Vector3d & orbiterRelativeVelocity, const Eigen::Vector3d & orbitedBodyPositionWrtLargerBody, const Eigen::Vector3d & orbitedBodyVelocityWrtLargerBody, const double commonCorrectionTermOfLargerBody, const double ppnParameterGamma = 1.0)
Function to compute the de Sitter term of the relativistic acceleration correction.
Parameters
orbiterRelativeVelocity Velocity of body undergoing, w.r.t. body exerting, acceleration.
orbitedBodyPositionWrtLargerBody Position of body undergoing acceleration w.r.t. its central body. For an acceleration on a satellite orbiting the Earth, this would be the position of the Earth w.r.t. the Sun.
orbitedBodyVelocityWrtLargerBody Velocity of body undergoing acceleration w.r.t. its central body. For an acceleration on a satellite orbiting the Earth, this would be the velocity of the Earth w.r.t. the Sun.
commonCorrectionTermOfLargerBody Common term in relativistic accelerations, with properties of e.g. Earth w.r.t the Sun for an Earth-orbitign satellite, as computed by calculateRelativisticAccelerationCorrectionsCommonterm function
ppnParameterGamma PPN parameter gamma
Returns
De Sitter term of the relativistic acceleration correction.
Definition at line 96 of file relativisticAccelerationCorrection.cpp.
Referenced by calculateDeSitterCorrectionAcceleration(), and tudat::relativity::RelativisticAccelerationCorrection::updateMembers().
Eigen::Vector3d tudat::relativity::calculateDeSitterCorrectionAcceleration (const double largerBodyGravitationalParameter, const Eigen::Vector6d & orbiterRelativeState, const Eigen::Vector6d & orbitedBodyStateWrtLargerBody, const double ppnParameterGamma = 1.0)
Function to compute the de Sitter term of the relativistic acceleration correction.
Parameters
largerBodyGravitationalParameter Gravitational parameter of body primarilly responsible for the motion of the body exerting the acceleration.
orbiterRelativeState State of body undergoing, w.r.t. body exerting, acceleration.
orbitedBodyStateWrtLargerBody Cartesian state of body undergoing acceleration w.r.t. its central body. For an acceleration on a satellite orbiting the Earth, this would be the Cartesian state of the Earth w.r.t. the Sun.
ppnParameterGamma PPN parameter gamma
Returns
De Sitter term of the relativistic acceleration correction.
Definition at line 108 of file relativisticAccelerationCorrection.cpp.
References calculateDeSitterCorrectionAcceleration(), and calculateRelativisticAccelerationCorrectionsCommonterm().
double tudat::relativity::calculateFirstOrderLightTimeCorrectionFromCentralBody (const double bodyGravitationalParameter, const Eigen::Vector3d & transmitterPosition, const Eigen::Vector3d & receiverPosition, const Eigen::Vector3d & centralBodyPosition, const double ppnParameterGamma = 1.0)
Function to calculate first order relativistic light time correction due to a gravitating point mass, according to Eq. (11.17) of 2010 IERS conventions.
Parameters
bodyGravitationalParameter Gravitational parameter of gravitating body.
transmitterPosition Position of origin of electromagnetic signal (at time of transmission).
receiverPosition Position of target of electromagentic signal (at time of reception)
centralBodyPosition Position of perturbing body (at certain time during signal propagation).
ppnParameterGamma Parametric post-Newtonian parameter gamma, a measure for the space-time curvature due to a unit rest mass (1.0 in GR)
Returns
Light time correction (in seconds) due to the gravitating point mass.
Definition at line 20 of file relativisticLightTimeCorrection.cpp.
References tudat::physical_constants::INVERSE_CUBIC_SPEED_OF_LIGHT.
Referenced by tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::calculateLightTimeCorrection().
Eigen::Matrix< double, 1, 3 > tudat::relativity::calculateFirstOrderCentralBodyLightTimeCorrectionGradient (const double bodyGravitationalParameter, const Eigen::Vector3d & transmitterPosition, const Eigen::Vector3d & receiverPosition, const Eigen::Vector3d & centralBodyPosition, const bool evaluateGradientAtReceiver, const double ppnParameterGamma = 1.0)
Function to calculate gradient of first order relativistic light time correction due to a gravitating point mass. Correction is according to Eq. (11.17) of 2010 IERS conventions.
Parameters
bodyGravitationalParameter Gravitational parameter of gravitating body.
transmitterPosition Position of origin of electromagnetic signal (at time of transmission).
receiverPosition Position of target of electromagentic signal (at time of reception)
centralBodyPosition Position of perturbing body (at certain time during signal propagation).
ppnParameterGamma Parametric post-Newtonian parameter gamma, a measure for the space-time curvature due to a unit rest mass (1.0 in GR)
evaluateGradientAtReceiver Boolean denoting whether to compute gradient at receiver or transmitter
Returns
Light time correction (in seconds) due to the gravitating point mass.
Definition at line 39 of file relativisticLightTimeCorrection.cpp.
References tudat::physical_constants::INVERSE_CUBIC_SPEED_OF_LIGHT.
Referenced by tudat::observation_models::FirstOrderLightTimeCorrectionCalculator::calculateLightTimeCorrectionPartialDerivativeWrtLinkEndPosition().
double tudat::relativity::calculateFirstCentralBodyProperTimeRateDifference (const double relativeSpeed, const double gravitationalScalarPotential, const double equivalencePrincipleLpiViolationParameter = 0.0)
Function to compute proper-time rate w.r.t. coordinate time, minus 1.0, from a speed and scalar potential, allowing for the possibility of EP violation (nominally none)
Parameters
relativeSpeed Speed of object for which proper time is to be computed, w.r.t. frame of which coordinate time is used
gravitationalScalarPotential Scalar potential at location of object for which proper time is to be computed
equivalencePrincipleLpiViolationParameter Violation parameter of equivalence principle (default to GR value of 0.0
Returns
Proper time rate minus one (d tau/dt - 1.0)
Definition at line 21 of file relativisticTimeConversion.cpp.
References tudat::physical_constants::INVERSE_SQUARE_SPEED_OF_LIGHT.
Referenced by calculateFirstCentralBodyProperTimeRateDifference(), and tudat::observation_models::DirectFirstOrderDopplerProperTimeRateInterface::getOberverProperTimeDeviation().
double tudat::relativity::calculateFirstCentralBodyProperTimeRateDifference (const Eigen::Vector6d relativeStateVector, const double centralBodyGravitationalParameter, const double equivalencePrincipleLpiViolationParameter = 0.0)
Function to compute proper-time rate w.r.t. coordinate time, minus 1.0, for a 1/c^2 potential from a static mass monopole.
Function to compute proper-time rate w.r.t. coordinate time, minus 1.0, for a 1/c^2 potential from a static mass monopole located at the origin of the reference frame of which the coordinate time is used., allowing for the possibility of EP violation (nominally none)
Parameters
relativeStateVector Cartesian state of point where proper time rate is to be computed
centralBodyGravitationalParameter Newtonian gravitational potnetial of central body.
equivalencePrincipleLpiViolationParameter Violation parameter of equivalence principle (default to GR value of 0.0
Returns
Proper time rate minus one (d tau/dt - 1.0)
Definition at line 30 of file relativisticTimeConversion.cpp.
References calculateFirstCentralBodyProperTimeRateDifference(), and equivalencePrincipleLpiViolationParameter.
Variable Documentation
boost::shared_ptr< PPNParameterSet > tudat::relativity::ppnParameterSet = boost::make_shared< PPNParameterSet >(1.0, 1.0)
Global PPN parameter set, initialized upon compilation (with values equal to GR).
Definition at line 22 of file metric.cpp.
Referenced by tudat::simulation_setup::createDoubleParameterToEstimate(), tudat::observation_models::createLightTimeCorrections(), and tudat::simulation_setup::createRelativisticCorrectionAcceleration().
double tudat::relativity::equivalencePrincipleLpiViolationParameter = 0.0
Definition at line 24 of file metric.cpp.
Referenced by calculateFirstCentralBodyProperTimeRateDifference(), tudat::observation_models::DirectFirstOrderDopplerProperTimeRateInterface::getOberverProperTimeDeviation(), tudat::estimatable_parameters::EquivalencePrincipleLpiViolationParameter::getParameterValue(), tudat::estimatable_parameters::EquivalencePrincipleLpiViolationParameter::setParameterValue(), and tudat::observation_partials::OneWayDopplerDirectFirstOrderProperTimeComponentScaling::update().
const Eigen::Matrix4d tudat::relativity::minkowskiMetric static
Initial value:
= (Eigen::Matrix4d() <<
                                                 -1.0, 0.0, 0.0, 0.0,
                                                 0.0, 1.0, 0.0, 0.0,
                                                 0.0, 0.0, 1.0, 0.0,
                                                 0.0, 0.0, 0.0, 1.0 ).finished( )
Definition at line 26 of file metric.h.