Tudat: tudat::propulsion::OrientationBasedForceGuidance Class Reference
tudat::propulsion::OrientationBasedForceGuidance Class Reference
Class for computing the force direction using the rotation matrix from the propagation to the body-fixed frame.
#include <thrustGuidance.h>
Public Member Functions
OrientationBasedForceGuidance (const std::function< Eigen::Quaterniond(const double) > bodyFixedFrameToBaseFrameFunction, const std::function< Eigen::Vector3d() > bodyFixedForceDirection=[](){ return Eigen::Vector3d::UnitX();})
Constructor.
Eigen::Vector3d getCurrentForceDirectionInPropagationFrame ()
Function returning the current force direction, as computed by last call to updateCalculator/updateForceDirection.
Eigen::Quaterniond getRotationToGlobalFrame ()
Function to get the rotation from body-fixed to inertial frame.
Public Member Functions inherited from tudat::propulsion::BodyFixedForceDirectionGuidance
BodyFixedForceDirectionGuidance (const std::function< Eigen::Vector3d() > bodyFixedForceDirection)
Constructor.
virtual ~BodyFixedForceDirectionGuidance ()
Destructor.
Eigen::Quaterniond getRotationToLocalFrame ()
Function to compute the rotation from the propagation frame to the body-fixed frame.
void updateCalculator (const double time)
Function to update the object to the current time.
Public Member Functions inherited from tudat::reference_frames::DependentOrientationCalculator
DependentOrientationCalculator ()
Constructor.
virtual ~DependentOrientationCalculator ()
Destructor.
Eigen::Quaterniond computeAndGetRotationToLocalFrame (const double currentTime)
Function to update the object to the current time and retrieve the rotation to the local frame.
Eigen::Quaterniond getRotationToGlobalFrame (const double currentTime)
Function to update the object to the current time and retrieve the rotation to the global frame.
void resetCurrentTime (const double currentTime=TUDAT_NAN)
Function to reset the current time of the object.
virtual void resetDerivedClassTime (const double currentTime=TUDAT_NAN)
Function to reset the current time in the derived class.
Protected Member Functions
void updateForceDirection (const double time)
Function to update the force direction to the current time.
Protected Attributes
std::function< Eigen::Quaterniond(const double) > bodyFixedFrameToBaseFrameFunction_
Function returning rotation from the body-fixed frame to the relevant propagation frame as a function of time.
Eigen::Quaterniond currentBodyFixedFrameToBaseFrame_
The rotation from body-fixed to inertial frame.
Protected Attributes inherited from tudat::propulsion::BodyFixedForceDirectionGuidance
std::function< Eigen::Vector3d() > bodyFixedForceDirection_
Function returning the direction of the force in the body-fixed frame.
Eigen::Vector3d currentBodyFixedForceDirection_
Current direction of the force in the body-fixed frame as set by last call to updateCalculator function.
Protected Attributes inherited from tudat::reference_frames::DependentOrientationCalculator
double currentTime_
Current simulation time.
Detailed Description
Definition at line 217 of file thrustGuidance.h.
Constructor & Destructor Documentation
OrientationBasedForceGuidance()
tudat::propulsion::OrientationBasedForceGuidance::OrientationBasedForceGuidance (const std::function< Eigen::Quaterniond(const double) > bodyFixedFrameToBaseFrameFunction, const std::function< Eigen::Vector3d() > bodyFixedForceDirection = [ ](){ return Eigen::Vector3d::UnitX(); }) inline
Constructor
Parameters
bodyFixedFrameToBaseFrameFunction Function returning rotation from the body-fixed frame to the relevant propagation frame as a function of time.
bodyFixedForceDirection Function returning the unit-vector of the force direction in a body-fixed frame (e.g. engine thrust pointing in body-fixed frame).
Definition at line 229 of file thrustGuidance.h.
Member Function Documentation
getCurrentForceDirectionInPropagationFrame()
Eigen::Vector3d tudat::propulsion::OrientationBasedForceGuidance::getCurrentForceDirectionInPropagationFrame () inline virtual
Function returning the current force direction, as computed by last call to updateCalculator/updateForceDirection.
Returns
Current force direction, expressed in propagation frame.
Implements tudat::propulsion::BodyFixedForceDirectionGuidance.
Definition at line 241 of file thrustGuidance.h.
References tudat::propulsion::BodyFixedForceDirectionGuidance::currentBodyFixedForceDirection_, and getRotationToGlobalFrame().
getRotationToGlobalFrame()
Eigen::Quaterniond tudat::propulsion::OrientationBasedForceGuidance::getRotationToGlobalFrame () inline virtual
Function to get the rotation from body-fixed to inertial frame. For thsi derived class, this simply means returning the currentBodyFixedFrameToBaseFrame_ rotation.
Returns
The rotation from body-fixed to inertial frame.
Implements tudat::reference_frames::DependentOrientationCalculator.
Definition at line 252 of file thrustGuidance.h.
References currentBodyFixedFrameToBaseFrame_.
Referenced by getCurrentForceDirectionInPropagationFrame().
updateForceDirection()
void tudat::propulsion::OrientationBasedForceGuidance::updateForceDirection (const double time) inline protected virtual
Function to update the force direction to the current time.
Parameters
time Time to which object is to be updated.
Implements tudat::propulsion::BodyFixedForceDirectionGuidance.
Definition at line 264 of file thrustGuidance.h.
References bodyFixedFrameToBaseFrameFunction_, and currentBodyFixedFrameToBaseFrame_.
Member Data Documentation
bodyFixedFrameToBaseFrameFunction_
std::function< Eigen::Quaterniond(const double) > tudat::propulsion::OrientationBasedForceGuidance::bodyFixedFrameToBaseFrameFunction_ protected
Definition at line 270 of file thrustGuidance.h.
Referenced by updateForceDirection().
currentBodyFixedFrameToBaseFrame_
Eigen::Quaterniond tudat::propulsion::OrientationBasedForceGuidance::currentBodyFixedFrameToBaseFrame_ protected
Definition at line 273 of file thrustGuidance.h.
Referenced by getRotationToGlobalFrame(), and updateForceDirection().
The documentation for this class was generated from the following file:
Astrodynamics/Propulsion/thrustGuidance.h