Tudat: tudat::input_output::MultiArrayFileReader< 2 > Class Template Reference
tudat::input_output::MultiArrayFileReader< 2 > Class Template Reference
Interface class for reading coefficients as a function of 2 independent variables from a file.
#include <multiDimensionalArrayReader.h>
Static Public Member Functions
static boost::multi_array< double, 2 > readMultiArray (const std::string fileName)
Function to read only a multi-array of size 2 from the file.
static std::pair< boost::multi_array< double, 2 >, std::vector< std::vector< double > > > readMultiArrayAndIndependentVariables (const std::string fileName)
Function to read a multi-array from the file, and the values of the independent variables at which it is defined.
Detailed Description
template<>
class tudat::input_output::MultiArrayFileReader< 2 >
Definition at line 185 of file multiDimensionalArrayReader.h.
Member Function Documentation
readMultiArray()
static boost::multi_array< double, 2 > tudat::input_output::MultiArrayFileReader< 2 >::readMultiArray (const std::string fileName) inline static
Function to read only a multi-array of size 2 from the file, not saving the values of the independent variables it is defined.
Parameters
fileName Name of the coefficient file
Returns
Multi-array containing file contents.
Definition at line 196 of file multiDimensionalArrayReader.h.
References tudat::input_output::MultiArrayFileReader< NumberOfDimensions >::readMultiArrayAndIndependentVariables().
readMultiArrayAndIndependentVariables()
static std::pair< boost::multi_array< double, 2 >, std::vector< std::vector< double > > > tudat::input_output::MultiArrayFileReader< 2 >::readMultiArrayAndIndependentVariables (const std::string fileName) inline static
Function to read a multi-array of size 2 from the file, and the values of the independent variables at which it is defined
Parameters
fileName Name of the coefficient file
Returns
Pair: first entry containing multi-array of double coefficients, second containing list of independent variables at which coefficients are defined.
Definition at line 211 of file multiDimensionalArrayReader.h.
References tudat::input_output::parseRawTwoDimensionalCoefficientsFromFile(), and tudat::input_output::readCoefficientsFile().
The documentation for this class was generated from the following file:
InputOutput/multiDimensionalArrayReader.h