Tudat: tudat::propagators::DynamicsSimulator< StateScalarType, TimeType > Class Template Reference
tudat::propagators::DynamicsSimulator< StateScalarType, TimeType > Class Template Reference abstract
Base class for performing full numerical integration of a dynamical system.
#include <dynamicsSimulator.h>
Public Member Functions
DynamicsSimulator (const simulation_setup::NamedBodyMap &bodyMap, const bool clearNumericalSolutions=true, const bool setIntegratedResult=true)
Constructor of simulator.
virtual ~DynamicsSimulator ()
Virtual destructor.
virtual std::vector< std::map< TimeType, double > > getCummulativeComputationTimeHistoryBase ()=0
virtual std::vector< std::map< TimeType, Eigen::VectorXd > > getDependentVariableNumericalSolutionBase ()=0
Pure virtual function that returns the numerical result of the dependent variable history.
virtual std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > getEquationsOfMotionNumericalSolutionBase ()=0
Pure virtual function that returns the numerical result of the state propagation.
simulation_setup::NamedBodyMap getNamedBodyMap ()
Function to get the map of named bodies involved in simulation.
virtual void integrateEquationsOfMotion (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > &initialGlobalStates)=0
This function numerically (re-)integrates the equations of motion.
virtual bool integrationCompletedSuccessfully () const =0
Get whether the integration was completed successfully.
void resetNamedBodyMap (const simulation_setup::NamedBodyMap &bodyMap)
Function to reset the named body map.
void resetSetIntegratedResult (const bool setIntegratedResult)
Protected Member Functions
virtual void processNumericalEquationsOfMotionSolution ()=0
This function updates the environment with the numerical solution of the propagation.
Protected Attributes
simulation_setup::NamedBodyMap bodyMap_
Map of bodies (with names) of all bodies in integration.
bool clearNumericalSolutions_
bool setIntegratedResult_
Boolean to determine whether to automatically use the integrated results to set ephemerides.
Detailed Description
template<typename StateScalarType = double, typename TimeType = double>
class tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >
Base class for performing full numerical integration of a dynamical system. Governing equations are set once, but can be re-integrated for different initial conditions using the same instance of the class. Derived classes define the specific kind of integration that is performed (single-arc/multi-arc/etc.)
Definition at line 181 of file dynamicsSimulator.h.
Constructor & Destructor Documentation
template<typename StateScalarType = double, typename TimeType = double> tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::DynamicsSimulator (const simulation_setup::NamedBodyMap & bodyMap, const bool clearNumericalSolutions = true, const bool setIntegratedResult = true) inline
Constructor of simulator, constructs integrator and object for calculating each time step of integration.
Parameters
bodyMap Map of bodies (with names) of all bodies in integration.
clearNumericalSolutions Boolean to determine whether to clear the raw numerical solution member variables after propagation and resetting ephemerides (default true).
setIntegratedResult Boolean to determine whether to automatically use the integrated results to set ephemerides (default true).
Definition at line 194 of file dynamicsSimulator.h.
template<typename StateScalarType = double, typename TimeType = double> virtual tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::~DynamicsSimulator () inline virtual
Definition at line 203 of file dynamicsSimulator.h.
References tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::getCummulativeComputationTimeHistoryBase(), tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::getDependentVariableNumericalSolutionBase(), tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolutionBase(), tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), and tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::integrationCompletedSuccessfully().
Member Function Documentation
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion (const Eigen::Matrix< StateScalarType, Eigen::Dynamic, Eigen::Dynamic > & initialGlobalStates) pure virtual
This function numerically (re-)integrates the equations of motion, using the settings set through the constructor and a new initial state vector provided here. The raw results are set in the equationsOfMotionNumericalSolution_
Parameters
initialGlobalStates Initial state vector that is to be used for numerical integration. Note that this state should be in the correct frame (i.e. corresponding to centralBodies in propagatorSettings_), but not in the propagator-specific form (i.e Encke, Gauss, etc. for translational dynamics)
See also
SingleStateTypeDerivative::convertToOutputSolution
Implemented in tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >, and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >.
Referenced by tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::MultiArcDynamicsSimulator(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::SingleArcDynamicsSimulator(), and tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::~DynamicsSimulator().
template<typename StateScalarType = double, typename TimeType = double> virtual bool tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::integrationCompletedSuccessfully () const pure virtual
Get whether the integration was completed successfully.
Returns
Whether the integration was completed successfully by reaching the termination condition.
Implemented in tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >, and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >.
Referenced by tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::~DynamicsSimulator().
template<typename StateScalarType = double, typename TimeType = double> virtual std::vector< std::map< TimeType, Eigen::Matrix< StateScalarType, Eigen::Dynamic, 1 > > > tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::getEquationsOfMotionNumericalSolutionBase () pure virtual
Pure virtual function that returns the numerical result of the state propagation.
Returns
Numerical result of the state propagation. See derived class documentation for precise contents structure.
Implemented in tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >, and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >.
Referenced by tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::~DynamicsSimulator().
template<typename StateScalarType = double, typename TimeType = double> virtual std::vector< std::map< TimeType, Eigen::VectorXd > > tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::getDependentVariableNumericalSolutionBase () pure virtual
Pure virtual function that returns the numerical result of the dependent variable history
Returns
Numerical result of the dependent variable history. See derived class documentation for precise contents structure.
Implemented in tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >, and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >.
Referenced by tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::~DynamicsSimulator().
template<typename StateScalarType = double, typename TimeType = double> virtual std::vector< std::map< TimeType, double > > tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::getCummulativeComputationTimeHistoryBase () pure virtual
Implemented in tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >, and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >.
Referenced by tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::~DynamicsSimulator().
template<typename StateScalarType = double, typename TimeType = double> simulation_setup::NamedBodyMap tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::getNamedBodyMap () inline
Function to get the map of named bodies involved in simulation.
Returns
Map of named bodies involved in simulation.
Definition at line 248 of file dynamicsSimulator.h.
References tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::bodyMap_.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::resetNamedBodyMap (const simulation_setup::NamedBodyMap & bodyMap) inline
Function to reset the named body map.
Parameters
bodyMap The new named body map.
Definition at line 258 of file dynamicsSimulator.h.
References tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::bodyMap_.
template<typename StateScalarType = double, typename TimeType = double> void tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::resetSetIntegratedResult (const bool setIntegratedResult) inline
Definition at line 263 of file dynamicsSimulator.h.
References tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution(), and tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::setIntegratedResult_.
template<typename StateScalarType = double, typename TimeType = double> virtual void tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution () protected pure virtual
This function updates the environment with the numerical solution of the propagation. For instance, it sets the propagated translational dynamics solution as the new input for the Ephemeris object of the body that was propagated. This function is pure virtual and must be implemented in the derived class.
Implemented in tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >, and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >.
Referenced by tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::manuallySetAndProcessRawNumericalEquationsOfMotionSolution(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::manuallySetAndProcessRawNumericalEquationsOfMotionSolution(), and tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::resetSetIntegratedResult().
Member Data Documentation
template<typename StateScalarType = double, typename TimeType = double> simulation_setup::NamedBodyMap tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::bodyMap_ protected
Definition at line 280 of file dynamicsSimulator.h.
Referenced by tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::getNamedBodyMap(), tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution(), tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::resetNamedBodyMap(), and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::SingleArcDynamicsSimulator().
template<typename StateScalarType = double, typename TimeType = double> bool tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::clearNumericalSolutions_ protected
Boolean to determine whether to clear the raw numerical solution member variables after propagation and resetting ephemerides.
Definition at line 284 of file dynamicsSimulator.h.
Referenced by tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution(), and tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::processNumericalEquationsOfMotionSolution().
template<typename StateScalarType = double, typename TimeType = double> bool tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::setIntegratedResult_ protected
Definition at line 287 of file dynamicsSimulator.h.
Referenced by tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::MultiArcDynamicsSimulator< StateScalarType, TimeType >::integrateEquationsOfMotion(), tudat::propagators::DynamicsSimulator< StateScalarType, TimeType >::resetSetIntegratedResult(), and tudat::propagators::SingleArcDynamicsSimulator< StateScalarType, TimeType >::SingleArcDynamicsSimulator().
The documentation for this class was generated from the following file:
SimulationSetup/PropagationSetup/dynamicsSimulator.h